reactos/reactos

README.md

This new markdown page should prettify this repository 😎 
Please feel free to edit if you find any mistakes.

Readme Markdown Page

---

dll/shellext/ntobjshex/foldercommon.h

See [CORE-13863](https://jira.reactos.org/browse/CORE-13863)

Patch by Sergei Abramov fixing a typo in ntobjshex

---

boot/freeldr/freeldr/arch/i386/pcmem.c

See https://jira.reactos.org/browse/CORE-12881
Split in 2 commits

CORE-12881 Patch: Fix freeldr memory enumeration

---

README.md

I've added a few badges to README.md. We can add more like download stats for SourceForge, CI status etc. etc.
Badges are simple icons. I used [shields.io](https://shields.io/) for the graphics.
New badges can be added using following syntax:
```[![Badge Description](/link/to/badge)](/clickable/link)```

Adding badges to README.md

---

dll/cpl/intl/advanced.c

[INTL]
Nit: merge duplicate code from r74582.
CORE-13242

CORE-13242. Nit: merge duplicate code from r74582.

---

boot/bootdata/readme.txt

Recently discussed this on IRC.
New file is opened in ReactOS Notepad without encoding issues.

[BOOTDATA] Change readme encoding to UTF-8

---

ntoskrnl/mm/ARM3/vadnode.c

[NTOSKRNL] Add ASSERTs to ensure, we never use an uninitialized variable

---

sdk/lib/atl/atlwin.h

Implement CDialogImpl
JIRA issue: [CORE-13895](https://jira.reactos.org/browse/CORE-13895)

CDialogImpl for ATL

---

base/applications/msconfig_new/comctl32ex/listview.c
base/applications/regedit/listview.c
dll/win32/shell32/CDefView.cpp

See https://github.com/reactos/reactos/commit/be9a0afc1f1b24a3edbd14dffe3b04814e85074c#commitcomment-25230680

Correctly check for presence of list view sort header.

---

base/shell/explorer/CMakeLists.txt
base/shell/explorer/explorer.cpp
base/shell/explorer/precomp.h
base/shell/explorer/resource.h
base/shell/explorer/settings.cpp
base/shell/explorer/taskswnd.cpp
base/shell/explorer/trayntfy.cpp
base/shell/explorer/trayprop.cpp
base/shell/explorer/traywnd.cpp

Rewrote the dialog code and the code to load and save the settings to work. Implements toggling autohide, always on top and locked state. More options will be implemented later. I didn't mention any bug report as it addresses several ones.

[EXPLORER] Taskbar properties

---

sdk/lib/atl/atlbase.h

CORE-13908
JIRA issue: [CORE-13908](https://jira.reactos.org/browse/CORE-13908)

[ATL] Initial implementation of CAtlExeModuleT.

---

boot/freeldr/freeldr/arch/i386/pcmem.c

[FREELDR]
Nit: Cast MAX_BIOS_DESCRIPTORS to explicit ULONG from implicit int.
PcMemGetBiosMemoryMap(): Comment/Add checks for PcMemoryMap/PcBiosMemoryMap arrays being full and bare handling of error cases.
CORE-13332

CORE-13332. Check for arrays being full.

---

base/applications/rapps/lang/de-DE.rc

Translation update.
JIRA issue: [CORE-13782](https://jira.reactos.org/browse/CORE-13782)

[RAPPS] Update German translation. CORE-13782

---

dll/opengl/opengl32/dllmain.c
dll/opengl/opengl32/opengl32.h

Fix opengl crashes uncovered in [CORE-12232](https://jira.reactos.org/browse/CORE-12232)

Opengl - CORE-12232

---

dll/win32/browseui/lang/bg-BG.rc
dll/win32/browseui/lang/de-DE.rc
dll/win32/browseui/lang/en-US.rc
dll/win32/browseui/lang/es-ES.rc
dll/win32/browseui/lang/fr-FR.rc
dll/win32/browseui/lang/he-IL.rc
dll/win32/browseui/lang/it-IT.rc
dll/win32/browseui/lang/ja-JP.rc
dll/win32/browseui/lang/pl-PL.rc
dll/win32/browseui/lang/pt-BR.rc
dll/win32/browseui/lang/ro-RO.rc
dll/win32/browseui/lang/ru-RU.rc
dll/win32/browseui/lang/sq-AL.rc
dll/win32/browseui/lang/tr-TR.rc
dll/win32/browseui/lang/uk-UA.rc
dll/win32/browseui/lang/zh-CN.rc
dll/win32/browseui/lang/zh-TW.rc
dll/win32/browseui/resource.h
dll/win32/browseui/shellbars/CISFBand.cpp

Add support for "Open Folder" feature to CISFBand class.
JIRA issue: [CORE-13996](https://jira.reactos.org/browse/CORE-13996)

[BROWSEUI] CISFBand: Add "Open Folder" feature

---

sdk/include/crt/emmintrin.h
sdk/lib/rtl/i386/rtlmem.s

Rtl & emmintrin fixes

---

dll/win32/shell32/lang/ru-RU.rc

[SHELL32] Update Russian translation, following 6465705

---

drivers/network/afd/afd/bind.c
drivers/network/afd/afd/connect.c
drivers/network/afd/afd/context.c
drivers/network/afd/afd/event.c
drivers/network/afd/afd/info.c
drivers/network/afd/afd/listen.c
drivers/network/afd/afd/lock.c
drivers/network/afd/afd/main.c
drivers/network/afd/afd/read.c
drivers/network/afd/afd/select.c
drivers/network/afd/afd/tdi.c
drivers/network/afd/afd/tdiconn.c
drivers/network/afd/afd/write.c
drivers/network/afd/include/afd.h

Thanks to @prozacchiwawa for assisting me with this.

[AFD] Introduce and use pool tags. CORE-14048

---

base/shell/explorer/lang/zh-CN.rc

Update Simplified Chinese translation.

---

win32ss/printing/base/winspool/CMakeLists.txt
win32ss/printing/base/winspool/devmode.c
win32ss/printing/base/winspool/forms.c
win32ss/printing/base/winspool/jobs.c
win32ss/printing/base/winspool/main.c
win32ss/printing/base/winspool/monitors.c
win32ss/printing/base/winspool/ports.c
win32ss/printing/base/winspool/printerdata.c
win32ss/printing/base/winspool/printerdrivers.c
win32ss/printing/base/winspool/printers.c
win32ss/printing/base/winspool/printprocessors.c
win32ss/printing/base/winspool/printproviders.c
win32ss/printing/base/winspool/winspool.spec

Pull Request is just for checking if CI builds it successfully :)

Winspool improvements

---

boot/bootdata/hivesys.inf
drivers/filesystems/ntfs/CMakeLists.txt
drivers/filesystems/ntfs/attrib.c
drivers/filesystems/ntfs/blockdev.c
drivers/filesystems/ntfs/btree.c
drivers/filesystems/ntfs/create.c
drivers/filesystems/ntfs/dirctl.c
drivers/filesystems/ntfs/dispatch.c
drivers/filesystems/ntfs/fcb.c
drivers/filesystems/ntfs/finfo.c
drivers/filesystems/ntfs/fsctl.c
drivers/filesystems/ntfs/mft.c
drivers/filesystems/ntfs/misc.c
drivers/filesystems/ntfs/ntfs.c
drivers/filesystems/ntfs/ntfs.h
drivers/filesystems/ntfs/rw.c
drivers/filesystems/ntfs/volinfo.c

This merges Trevor's NTFS work, rebased on top of the git-migrated repository.
I plan to do this using a merge commit, which preserves history, does not clutter master with tons of commits, and should not negatively affect our current linear history approach (the merge-base is older than the 0.4.8-dev tag, and pre-git branch merges use merge commits anyway).
I've requested review from most of you just to discuss any issues you might see with the merge strategy.
JIRA issue: [CORE-10998](https://jira.reactos.org/browse/CORE-10998)

Merge GSoC NTFS work

---

ntoskrnl/include/internal/kd.h
ntoskrnl/kd/kdio.c
ntoskrnl/kd/kdmain.c
ntoskrnl/kd64/kdprint.c
ntoskrnl/kdbg/kdb_cli.c

JIRA issue: [CORE-14103](https://jira.reactos.org/browse/CORE-14103)

Avoid _alloca inside SEH, use correct PreviousMode

---

win32ss/gdi/gdi32/objects/text.c

TextOutA won't handle multibyte string length correctly. This Pull Request fixes it.
JIRA issue: [CORE-14070](https://jira.reactos.org/browse/CORE-14070)

Fix TextOutA multibyte text length overgoing

---

hal/halx86/apic/apic.c
hal/halx86/generic.cmake
hal/halx86/generic/pic.c
hal/halx86/include/halp.h
hal/halx86/up/pic.c

Just some first work towards deduplicating code in our HALs, along with a one-liner fix. Nothing revolutionary here.
As this is a highly debated topic on ros-dev, I'm asking for reviews though to make sure that my approach is going into the right direction.

First take at HAL deduplication cleanup

---

boot/bootdata/livecd.ini
dll/ntdll/ldr/ldrapi.c
dll/win32/kernel32/client/loader.c
drivers/sac/driver/init.c
ntoskrnl/fsrtl/stackovf.c
ntoskrnl/fsrtl/unc.c
ntoskrnl/include/internal/amd64/ke.h
ntoskrnl/include/internal/amd64/mm.h
ntoskrnl/include/internal/arm/mm.h
ntoskrnl/include/internal/i386/mm.h
ntoskrnl/io/pnpmgr/pnpreport.c
ntoskrnl/ke/amd64/cpu.c
ntoskrnl/ke/amd64/kiinit.c
ntoskrnl/ke/amd64/krnlinit.c
ntoskrnl/mm/ARM3/mminit.c
ntoskrnl/mm/amd64/init.c
ntoskrnl/mm/mminit.c
ntoskrnl/ps/debug.c
ntoskrnl/ps/process.c
sdk/include/ndk/ldrfuncs.h
sdk/lib/rtl/memstream.c
sdk/lib/rtl/rtlp.h

This PR is based on PR #115 and includes all changes that I think can be merged as of now.
It also changes the committer name to "Ivan Labutin".
@Barracuda72 Please review.

X64 boot fixes (partial)

---

ntoskrnl/io/iomgr/device.c

see CORE-14128
Allow code path to execute
JIRA issue: [CORE-14128](https://jira.reactos.org/browse/CORE-14128)
Removed ASSERT

Remove constant assert

---

modules/rostests/apitests/atl/CComBSTR.cpp
modules/rostests/apitests/atl/CString.cpp
modules/rostests/apitests/atl/CString.inl
modules/rostests/apitests/atl/devenv/CSimpleArray.vcxproj
modules/rostests/apitests/atl/devenv/CSimpleMap.vcxproj
modules/rostests/apitests/atl/devenv/CString.vcxproj
sdk/lib/atl/atlcomcli.h
sdk/lib/atl/cstringt.h

Adds Attach for CComBSTR, and AllocSysString for CString.

Some small atl improvements

---

ntoskrnl/ex/handle.c
ntoskrnl/include/internal/ex.h

Based on patch by Ivan Labutin. See PR #115

[NTOS:EX] Fix handle table code for x64.

---

base/setup/reactos/lang/it-IT.rc

Some English strings were left un-translated. This patch brings the latest translations.

[SETUP:REACTOS] Quick-update for Italian translation

---

ntoskrnl/config/cmsysini.c

In an attempt to close some JIRA reports with "PATCH" label, I've adapted Timo's patch from https://jira.reactos.org/browse/CORE-6844 to latest HEAD.
Looks and builds okay here, but Timo, please tell me if this can be merged or whether it conflicts with some uncommitted changes of yours.

[NTOS:CM] Improve code in cmsysini.c

---

drivers/filesystems/fastfat/cleanup.c

Add 1 parenthesis and indentation, like all the other cases.

[FASTFAT] Improve code style in addition to 8294118

---

base/setup/usetup/muifonts.h

- Improve code readability of muifonts.h
- Add the SimHei (Chinese font name) entry to ChineseSimplifiedFonts array.

usetup: Improve muifonts.h and add a "SimHei" font subst entry

---

ntoskrnl/config/ntapi.c
sdk/include/reactos/debug.h

Limit spam from unimplemented functions that see high traffic.
JIRA issue: [CORE-13125](https://jira.reactos.org/browse/CORE-13125)

Add unimplemented once macro

---

dll/win32/setupapi/devinst.c

Rename SetupDiSetDeviceRegistryPropertyW to IntSetupDiSetDeviceRegistryPropertyAW and use it for both (A/W).
The FIXME in the A-Version was already implemented in the W-Version.
CORE-14173

[setupapi]: Fix a FIXME in SetupDiSetDeviceRegistryPropertyA.

---

dll/appcompat/apphelp/sdbapi.c
dll/appcompat/apphelp/shimeng.c

Some local changes that I wanna run on the builders :)

Small appcompat fixes

---

drivers/network/tcpip/datalink/lan.c

* Add some missing allocation checks pointed out by Coverity
* Fix wrong buffer size (+ instead of *)

TCPIP fixes

---

drivers/usb/usbhub_new/pnp.c

Two small fixations for the usbhub driver.
1 - Move DPRINT down, after calling USBH_SyncGetPortStatus()
2 - Correcting L"USB\\Vid_0000&Pid_0000"

Usbhub small fixes

---

base/applications/drwtsn32/main.cpp

[DRWTSN32] Update output string copypasta from #268

---

ntoskrnl/cache/section/swapout.c
ntoskrnl/ex/interlocked.c
ntoskrnl/fstub/translate.c
ntoskrnl/io/pnpmgr/pnpinit.c
ntoskrnl/mm/ARM3/contmem.c
ntoskrnl/mm/ARM3/mdlsup.c
ntoskrnl/mm/ARM3/procsup.c
ntoskrnl/mm/ARM3/section.c
ntoskrnl/mm/ARM3/vadnode.c
ntoskrnl/mm/ARM3/virtual.c
ntoskrnl/mm/marea.c
ntoskrnl/ob/oblife.c

[NTOS] Fix 64 bit warnings

---

base/shell/explorer/trayntfy.cpp

Implements NIS_SHAREDICON, and fixes a whole bunch of issues with the code.
Should fix most of what's described in [CORE-10690](https://jira.reactos.org/browse/CORE-10690)

[EXPLORER] Fix some issues with the notification area code,

---

sdk/cmake/widl-support.cmake

JIRA issue: [CORE-14204](https://jira.reactos.org/browse/CORE-14204)

[CMAKE/WIDL] Add rudimentary dependency tracking in add_rpcproxy_files

---

sdk/lib/drivers/lwip/src/core/dhcp.c

Fix a while() check order.
JIRA issue: [CORE-8978](https://jira.reactos.org/browse/CORE-8978)

CORE-8978. dhcp.c: Cherry-pick lwIP 32aa9a4

---

dll/win32/shell32/lang/pl-PL.rc

Fix Polish translation typos in shell32

[SHELL32] Fix typo in Polish translation pl-PL.rc

---

dll/appcompat/apphelp/apphelp.h
dll/appcompat/apphelp/hsdb.c
dll/appcompat/apphelp/shimeng.c
dll/appcompat/shims/shimlib/shimlib.c
modules/rostests/apitests/apphelp/apphelp.c
modules/rostests/apitests/appshim/CMakeLists.txt
modules/rostests/apitests/appshim/appshim_apitest.h
modules/rostests/apitests/appshim/dispmode.c
modules/rostests/apitests/appshim/genral_hooks.c
modules/rostests/apitests/appshim/layer_hooks.c
modules/rostests/apitests/appshim/testlist.c
modules/rostests/apitests/appshim/versionlie.c

Some local stuff that I want to run on testbot and after that, merge

Various apphelp related patches

---

base/shell/explorer/trayntfy.cpp
sdk/include/reactos/rosctrls.h

Tray balloon notifications

---

dll/cpl/desk/lang/ru-RU.rc

Translation here ;)
Cc @HBelusca

[TRANSLATION] [DESK] Update russian translation

---

base/applications/network/tracert/lang/bg-BG.rc
base/applications/network/tracert/lang/cs-CZ.rc
base/applications/network/tracert/lang/de-DE.rc
base/applications/network/tracert/lang/en-US.rc
base/applications/network/tracert/lang/es-ES.rc
base/applications/network/tracert/lang/fr-FR.rc
base/applications/network/tracert/lang/it-IT.rc
base/applications/network/tracert/lang/pl-PL.rc
base/applications/network/tracert/lang/ro-RO.rc
base/applications/network/tracert/lang/ru-RU.rc
base/applications/network/tracert/lang/sq-AL.rc
base/applications/network/tracert/lang/sv-SE.rc
base/applications/network/tracert/lang/tr-TR.rc
base/applications/network/tracert/lang/uk-UA.rc
base/applications/network/tracert/lang/zh-CN.rc
base/applications/network/tracert/lang/zh-TW.rc
base/applications/network/tracert/resource.h
base/applications/network/tracert/tracert.cpp

Improve tracert command network error handling and output.
JIRA issue: [CORE-14242](https://jira.reactos.org/browse/CORE-14242)
- Correctly interpret network error codes
- Add output for generic transmit failure
Cc @gedmurphy

[TRACERT] Improve error handling and output

---

base/applications/network/ping/ping.c

Fix ping command problems.
JIRA issue: [CORE-14241](https://jira.reactos.org/browse/CORE-14241)
- Host/net unreachable error should be obtained from `EchoReply->Status` according to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366051(v=vs.85).aspx)
- Use `GetNameInfoW` to decode actual response addresses (borrowed from tracert code)

[PING] Fix error handling and response address decoding

---

modules/rostests/apitests/gdi32/CMakeLists.txt
modules/rostests/apitests/gdi32/GetTextMetrics.c
modules/rostests/apitests/gdi32/testlist.c

This PR adds detailed GetTextMetrics and GetTextExtentPoint32 tests to gdi32_apitest.
JIRA issue: [CORE-13840](https://jira.reactos.org/browse/CORE-13840)
Tested on Win2k3 and Win10.

add GetTextMetrics tests to gdi32_apitest (CORE-13840)

---

dll/appcompat/apphelp/shimeng.c
dll/appcompat/apphelp/shimeng.h
media/sdb/sysmain.xml
sdk/tools/xml2sdb/xml2sdb.cpp
sdk/tools/xml2sdb/xml2sdb.h

Both GetShortPathNameNT4 and GetDiskFreeSpace2GB (5bee374c) were already implemented,
but they were not accessible to users.

Make GetShortPathNameNT4 and GetDiskFreeSpace2GB accessible

---

base/applications/network/ping/lang/bg-BG.rc
base/applications/network/ping/lang/cs-CZ.rc
base/applications/network/ping/lang/en-US.rc
base/applications/network/ping/lang/es-ES.rc
base/applications/network/ping/lang/it-IT.rc
base/applications/network/ping/lang/pl-PL.rc
base/applications/network/ping/lang/ru-RU.rc
base/applications/network/ping/lang/sq-AL.rc
base/applications/network/ping/lang/sv-SE.rc
base/applications/network/ping/lang/uk-UA.rc
base/applications/network/ping/lang/zh-CN.rc
base/applications/network/ping/lang/zh-TW.rc
base/applications/network/tracert/lang/ru-RU.rc

Translation fixes here ;)
Cc @HBelusca

Add and fix translations for ping and tracert

---

base/applications/sc/print.c

- Plus: Update license header.
- Re-use PrintServiceStatus(), as SERVICE_STATUS_PROCESS is in fact an extension of SERVICE_STATUS.
- Use the "SERVICE_*" defines, not magic numbers.

[SC] print.c: Minor code improvements

---

.gitmessage
CONTRIBUTING.md

This template defines a general commit style, and will be most
helpful for newcomers. I will be using it personally :)
This supersedes #131.

[CONTRIBUTING] Add a commit template and a paragraph about it

---

base/applications/network/tracert/lang/it-IT.rc
base/applications/network/tracert/lang/ro-RO.rc

Now that Ged Murphy merged his latest improvements for the trace route utility (TRACERT) I decided to come up with two translations. Note that I didn't translate TRACERT into Romanian language yet because I'm quite in a hurry but will keep you informed (I made this PR for the purpose to keep track on my work).

[TRACERT] Translation for Italian and Romanian language

---

base/applications/clipbrd/clipbrd.rc
base/applications/clipbrd/lang/it-IT.rc

Italian language implementation for the Clipboard Viewer software has been added. Checked twice for any mistakes or errors, found none, so I'd say this PR can be merged safely. If not, then please let me know.

[CLIPBRD] Italian language implemented

---

dll/win32/oleaut32/oleaut.c
dll/win32/oleaut32/olepicture.c
dll/win32/oleaut32/tmarshal.c
dll/win32/oleaut32/typelib.c
dll/win32/oleaut32/typelib.h
dll/win32/oleaut32/variant.c
dll/win32/oleaut32/vartype.c
media/doc/README.WINE

The "sync" zapped a lot of fixes, in particular 64 bit compatibility.

Revert "[OLEAUT32] Sync with Wine 3.0. CORE-14225"

---

dll/win32/shimgvw/shimgvw.c

Enable zooming in and zooming out at shimgvw.
JIRA issue: [CORE-12338](https://jira.reactos.org/browse/CORE-12338)

shimgvw: Enable zooming

---

configure.cmd

[CMAKE] Add some fool-proofing to configure.cmd related to MSVS:
-VSSolution switch now outputs to a dedicated folder if running from source directory.
-Give an error if the user is trying to mix ninja and VSSolution in the same output directory.
-In a MingW environment, give an error on VSSolution switch and give a warning on RTC switch.
-Fix -DNEW_STYLE_BUILD=0 option.
-Ensure the source path doesn't contain any spaces.
-Issue a warning if passed an invalid switch.
-Don't announce completion if there were errors.
-Make end message specific for VSSolution.
-Replace redundant exit commands with quit label, as suggested by HBelusca.

configure.cmd user experience improvements by Trevor

---

dll/cpl/timedate/dateandtime.c
dll/cpl/timedate/internettime.c
dll/cpl/timedate/ntpclient.c
dll/cpl/timedate/timedate.h

JIRA issue: [CORE-14167](https://jira.reactos.org/browse/CORE-14167)

[TIMEDATE] Correctly set the time when using the "Update now" button

---

boot/freeldr/freeldr/arch/i386/hardware.c
boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/ntldr/winldr.c

JIRA issue: [CORE-14280](https://jira.reactos.org/browse/CORE-14280)

Reduce serial mouse detection timeout to avoid hang

---

base/applications/rapps/gui.cpp

[RAPPS] Do not resize (hide) the treeview when minimizing.

---

media/doc/README.WINE
sdk/include/reactos/wine/strmbase.h
sdk/lib/3rdparty/strmbase/mediatype.c
sdk/lib/3rdparty/strmbase/outputqueue.c
sdk/lib/3rdparty/strmbase/pin.c
sdk/lib/3rdparty/strmbase/pospass.c
sdk/lib/3rdparty/strmbase/renderer.c
sdk/lib/3rdparty/strmbase/transform.c
sdk/lib/3rdparty/strmbase/video.c
sdk/lib/3rdparty/strmbase/window.c

This hasn't been included in the last couple syncs. Maybe updating it will fix a couple tests.

[STRMBASE] Sync with Wine 3.0. CORE-14225

---

sdk/lib/crt/startup/gs_support.c

CORE-14306. Fix a Clang-Cl warning about GS_ExceptionPointers

---

hal/halx86/apic/apic.h
hal/halx86/apic/apictimer.c
hal/halx86/apic/halinit_apic.c
hal/halx86/include/halp.h

Implement HAL profiling
Accorting to "clean room" approach I should put docs somewhere. Where can I put them?

Hal intr profiling

---

dll/directx/d3d9/d3d9_helpers.c
modules/rosapps/applications/cmdutils/arping/arping.c

Like
JIRA issue: [CORE-14193](https://jira.reactos.org/browse/CORE-14193)
- [D3D9] Add a missing va_end()
- [ARPING] Add a missing va_start(), Move 2 va_end()

Add a missing va_start() and a missing va_end()

---

win32ss/user/ntuser/menu.c

Hit some crashes there when debugging CORE-14222.

Safely handle allocation failures in menu code

---

base/setup/reactos/lang/de-DE.rc

It is rather unusual to put a "then" after "If..", so removed that.
Enhance readability with selected language being German.

Syntax fix

---

base/setup/reactos/lang/de-DE.rc

Very minor grammar improvements in the German installer.

[TRANSLATION] Minor German grammar improvements

---

dll/shellext/stobject/lang/de-DE.rc

This completes de-DE.rc in stobject as it was lacking the translation of IDS_PWR_CHARGING.

[TRANSLATION] Completed German translation in stobject

---

dll/cpl/input/lang/bg-BG.rc
dll/cpl/input/lang/ru-RU.rc
dll/cpl/input/lang/uk-UA.rc

[TRANSLATION] Some translations fixes

---

dll/win32/browseui/addressband.cpp
dll/win32/browseui/addresseditbox.cpp
dll/win32/browseui/basebarsite.cpp
dll/win32/browseui/explorerband.cpp
dll/win32/browseui/shellbars/CBandSite.cpp
dll/win32/browseui/shellbars/CISFBand.cpp
dll/win32/shell32/shellmenu/CMenuBand.cpp
dll/win32/shell32/shellmenu/CMenuToolbars.cpp

Windows's explorer.exe can pass NULL.
JIRA issue: [CORE-14443](https://jira.reactos.org/browse/CORE-14443)

[BROWSEUI][SHELL32] Treat OnWinEvent's result parameter as optional.

---

base/shell/explorer/lang/de-DE.rc
dll/win32/browseui/lang/de-DE.rc
dll/win32/comctl32/lang/comctl_De.rc
dll/win32/comdlg32/lang/cdlg_De.rc
dll/win32/setupapi/lang/de-DE.rc
dll/win32/shell32/lang/de-DE.rc

Update German translation

---

base/shell/explorer/explorer.exe.manifest

[EXPLORER] Do not force X86 in the manifest.

---

ntoskrnl/io/pnpmgr/pnpmgr.c

[NTOSKRNL] Adding IopValidateID() to test characters in IDs (IRP_MN_QUERY_ID).
IRP_MN_QUERY_ID is documented here https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-mn-query-id

IopValidateID()

---

drivers/network/afd/afd/main.c

[AFD] Respond to FileFsDeviceInformation.

---

dll/win32/browseui/lang/zh-CN.rc

If possible, I hope to apply this patch to 0.4.8-rc as well, thank you.

[BROWSEUI] Update Simplified Chinese translation.

---

base/applications/mplay32/lang/it-IT.rc

Small patch with the updated version of ReactOS Multimedia Player (MPLAY32) for Italian.

[TRANSLATION][MPLAY32] Translation update for the Italian language

---

dll/cpl/inetcpl/lang/it-IT.rc

PR with some translated strings onto Italian language.

[TRANSLATION][INETCPL] Italian translation update

---

base/applications/rapps/lang/it-IT.rc
base/applications/rapps/lang/ro-RO.rc

ReactOS Applications Manager had a commit update on certificates as well as new resource strings which they weren't translated though. This PR solves this.

[TRANSLATION][RAPPS] Translation update for Italian and Romanian

---

win32ss/drivers/displays/framebuf/pointer.c

JIRA issue: [CORE-14511](https://jira.reactos.org/browse/CORE-14511)
- Fix a copypasta.
- Remove dead code.

CORE-14511. Improve/Fix uncompiled-by-default DrvSetPointerShape()

---

base/services/tftpd/tftpd.cpp
dll/directx/wine/dsound/buffer.c
dll/directx/wine/dsound/primary.c
drivers/usb/usbohci_new/usbohci.h
drivers/usb/usbport/usbport.h
hal/halx86/generic/reboot.c
modules/rosapps/applications/sysutils/utils/binpatch/patch.c
modules/rosapps/drivers/vfd/vfddev.c
modules/rosapps/drivers/vfd/vfddrv.h
modules/rosapps/drivers/vfd/vfdimg.c
modules/rosapps/drivers/vfd/vfdlink.c
modules/rostests/apitests/atl/CComObject.cpp
modules/rostests/apitests/ntdll/LdrEnumResources.c
modules/rostests/apitests/ntdll/NtAcceptConnectPort.c
modules/rostests/apitests/ntdll/NtApphelpCacheControl.c
modules/rostests/apitests/ntdll/NtCreateFile.c
modules/rostests/apitests/ntdll/RtlAllocateHeap.c
modules/rostests/apitests/ntdll/RtlDosPathNameToNtPathName_U.c
modules/rostests/apitests/ntdll/RtlpEnsureBufferSize.c
modules/rostests/winetests/ntdll/exception.c
ntoskrnl/mm/ARM3/mminit.c
sdk/include/xdk/winnt_old.h
sdk/lib/rtl/amd64/unwind.c
sdk/lib/rtl/rtlp.h

* [HAL] Simplify HalpReboot() and make it portable
* [NTOS:MM] Cast constant to PVOID
* [BINPATCH] Fix 64 bit build
* [VFDDRV] Fix 64 bit build and buffer overruns
* [USBOHCI] Fix structure alignment issues
* [ATL_APITEST] Fix 64 bit build
* [XDK] Update unwind structures in winnt.h
* [NTDLL_APITEST] Fix 64 bit build
* [NTDLL_WINETEST] Fix 64 bit build
* [TFTPD] Fix x64 build

Fix 64 bit build

---

sdk/include/ndk/extypes.h
win32ss/user/winsrv/usersrv/harderror.c
win32ss/user/winsrv/usersrv/init.c
win32ss/user/winsrv/usersrv/lang/bg-BG.rc
win32ss/user/winsrv/usersrv/lang/cs-CZ.rc
win32ss/user/winsrv/usersrv/lang/de-DE.rc
win32ss/user/winsrv/usersrv/lang/el-GR.rc
win32ss/user/winsrv/usersrv/lang/en-US.rc
win32ss/user/winsrv/usersrv/lang/es-ES.rc
win32ss/user/winsrv/usersrv/lang/fr-FR.rc
win32ss/user/winsrv/usersrv/lang/he-IL.rc
win32ss/user/winsrv/usersrv/lang/id-ID.rc
win32ss/user/winsrv/usersrv/lang/it-IT.rc
win32ss/user/winsrv/usersrv/lang/ja-JP.rc
win32ss/user/winsrv/usersrv/lang/no-NO.rc
win32ss/user/winsrv/usersrv/lang/pl-PL.rc
win32ss/user/winsrv/usersrv/lang/pt-BR.rc
win32ss/user/winsrv/usersrv/lang/ro-RO.rc
win32ss/user/winsrv/usersrv/lang/ru-RU.rc
win32ss/user/winsrv/usersrv/lang/sk-SK.rc
win32ss/user/winsrv/usersrv/lang/sv-SE.rc
win32ss/user/winsrv/usersrv/lang/tr-TR.rc
win32ss/user/winsrv/usersrv/lang/uk-UA.rc
win32ss/user/winsrv/usersrv/lang/zh-CN.rc
win32ss/user/winsrv/usersrv/lang/zh-TW.rc
win32ss/user/winsrv/usersrv/resource.h
win32ss/user/winsrv/usersrv/shutdown.c
win32ss/user/winsrv/usersrv/usersrv.h

PR to improve the hard-error handling code in USERSRV.
See each commit messages for the details.

[USERSRV] Hard-error improvements

---

dll/win32/shell32/lang/et-EE.rc

Fix up various mistakes with the Estonian translation of shell32. It should now be more clearly understandable.

[TRANSLATION][SHELL32] Corrected mistakes

---

base/applications/drwtsn32/drwtsn32.rc
base/applications/drwtsn32/lang/en-US.rc
base/applications/drwtsn32/lang/pl-PL.rc
base/system/winlogon/lang/pl-PL.rc
win32ss/user/winsrv/usersrv/lang/pl-PL.rc

Polish translation update for drwtsn32, winlogon and usersrv.

[TRANSLATION] Polish translation update

---

dll/shellext/zipfldr/lang/et-EE.rc
dll/shellext/zipfldr/zipfldr.rc

Add Estonian translation for zipfldr.

[TRANSLATION][ZIPFLDR] Added Estonian translation

---

dll/apisets/api-ms-win-core-crt-l2-1-0.spec
dll/apisets/api-ms-win-crt-multibyte-l1-1-0.spec
dll/apisets/update.py

Thanks to Timo for the help :)

[APISETS] Fix data forwarding.

---

dll/shellext/zipfldr/lang/ru-RU.rc
dll/shellext/zipfldr/zipfldr.rc

[ZIPFLDR] Add Russian translation

---

dll/shellext/zipfldr/CZipExtract.cpp
dll/shellext/zipfldr/CZipFolder.hpp
dll/shellext/zipfldr/zippidl.cpp
dll/win32/shell32/wine/shell32_main.c
sdk/lib/atl/atlwin.h

[CORE-14542](https://jira.reactos.org/browse/CORE-14542) and [CORE-14543](https://jira.reactos.org/browse/CORE-14543)

[Zipfldr] Various usability improvements

---

dll/cpl/console/lang/it-IT.rc

The patch fixes up some mistakes from the previous commit of mine that it would cause lots of confusions. Now it should be alright.
Cc @ale5000-git

[TRANSLATION][CONSOLE] Some mistake corrections

---

sdk/include/reactos/mc/bugcodes.mc

Add description to MANUALLY_INITIATED_CRASH

---

dll/win32/advapi32/service/sctrl.c

[ADVAPI32] Fix 2 TRACE() format copypastas.

---

dll/win32/comctl32/lang/comctl_Ro.rc

Some updates for the Romanian resource file of Common Controls (COMCTL32).

[COMCTL32] Update Romanian translation

---

drivers/usb/usbhub/misc.c
drivers/usb/usbhub/pdo.c
drivers/usb/usbhub/usbhub.c

There are a few trivial mistakes in the file descriptions so this is just fixing them.
JIRA issue: [CORE-12966](https://jira.reactos.org/browse/CORE-12966)

CORE-12966 Fixed file headers

---

modules/rostests/kmtests/kmtest/service.c

Detect service stop failures.
And start failures too, if such happen.
JIRA issue: [ROSTESTS-263](https://jira.reactos.org/browse/ROSTESTS-263)
Simple tests passed/failed on WXP, as intented.
`rosautotest` passed on ROS r76032.

ROSTESTS-263. Check/Wait for start/stop of services to complete

---

dll/win32/iphlpapi/ipstats_reactos.c

- Improve/Promote failures to ERR.
- Improve other TRACE calls.

[IPHLPAPI] ipstats_reactos: Review all TRACE/WARN calls

---

base/applications/drwtsn32/drwtsn32.rc
base/applications/drwtsn32/lang/zh-CN.rc

[TRANSLATIONS][drwtsn32] Add zh-CN translation.

---

base/applications/mspaint/imgarea.cpp

This PR should finally fix [CORE-14539](https://jira.reactos.org/browse/CORE-14539). :wink:

[MSPAINT] Fix divide by zero in drawZoomFrame

---

dll/win32/shell32/CDefView.cpp
ntoskrnl/wmi/smbios.c
win32ss/user/ntuser/cursoricon.c

The smbios.c one was initially spotted by "Alahndro" on CORE-6328.

[REACTOS] Improve/Fix some "printf" formats

---

base/applications/drwtsn32/drwtsn32.rc
base/applications/drwtsn32/lang/it-IT.rc
base/applications/drwtsn32/lang/ro-RO.rc

I had to re-create a new Pull Request because I've accidentally removed all the contents from the branch from #527 when I attempted to push the changes.

[TRANSLATION][DRWTSN32] Add Romanian & Italian translations

---

base/applications/notepad/lang/tr-TR.rc

- Translate notepad to Turkish
Improve notepad's Turkish translation. Sorry for wrong commit message.
Improve notepad's Turkish translation. Sorry for wrong commit message.

[TRANSLATION] Improve notepad's Turkish translation.

---

modules/rosapps/readme.txt
modules/rostests/readme.txt

Changed readme for rosapps and rostests as they are included in the main repository

[MODULES] Updated readme file, with instructions

---

dll/win32/shell32/shlfileop.cpp

Files are copied with trying to find new path by adding (%d) suffix before asking for overwrite existing item

[SHELL32] Copy-paste files/folders into current place.

---

base/setup/usetup/lang/it-IT.h

Translation update following up the recent changes from #608.
CC @SebastianoPistore for review.

[TRANSLATION][USETUP] Italian translation update

---

base/setup/welcome/lang/hi-IN.rc
base/setup/welcome/welcome.rc

Hindi translation of welcome and defined at welcome.rc for hi-IN.rc
- Added hi-IN.rc in lang folder.
- Defined hi-IN.rc in welcome.rc

Hindi translation of Welcome

---

dll/win32/shlwapi/shlwapi.spec
modules/rostests/apitests/shlwapi/CMakeLists.txt
modules/rostests/apitests/shlwapi/PathUnExpandEnvStringsForUser.c
modules/rostests/apitests/shlwapi/testlist.c

This PR will add the testcase of shlwapi private PathUnExpandEnvStringsForUser function.
JIRA issue: [ROSTESTS-308](https://jira.reactos.org/browse/ROSTESTS-308)

[SHLWAPI][APITESTS] Add test for PathUnExpandEnvStringsForUser

---

dll/win32/shell32/lang/fr-FR.rc

This PR will improve French Folder Options.
JIRA issue: [CORE-12480](https://jira.reactos.org/browse/CORE-12480)
AFTER:

[SHELL32] Improve French Folder Options

---

configure.cmd

This adds support for the lasted VS version to the configure script

[CMAKE] Add support for VS 15.7.1 / CL 19.14.x

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
PULL_REQUEST_MANAGEMENT.md

As discussed during the meeting, we have a growing list of idle pull requests, that are either accepted but unmerged, or have been waiting for changes for a long time.
To try to alleviate that issue, we came up with a set of rules we should try to follow, in order to avoid making it worse.
The rules (helpfully gathered by @ColinFinck) have been written into the new document, and this new document has been linked from CONTRIBUTING.md, and CODE_OF_CONDUCT.md
This goes to all the team members, specially those that commonly review, merge or reject pull requests.
We would want your input on:
- Wording
- Location of the links within the files
- The rules themselves
Speak now or forever hold your peace.

Add a document on the rules we should follow while managing/reviewing PRs

---

base/applications/cmdutils/whoami/lang/it-IT.rc
base/applications/cmdutils/whoami/whoami.rc

Italian resource file for `whoami` command line utility.
CC @SebastianoPistore / @ElCresh for review.

[TRANSLATION][WHOAMI] Add Italian resource

---

dll/win32/shell32/dialogs/filetypes.cpp

This PR implements the 'Change' button at 'File Types' tab of Folder Options.
JIRA issue: [CORE-12906](https://jira.reactos.org/browse/CORE-12906)

[SHELL32] Implement 'Change' button of 'File Types' tab of Folder Options 

---

base/applications/cmdutils/at/at.rc
base/applications/cmdutils/at/lang/it-IT.rc

[TRANSLATION][AT] Implement the Italian resource file

---

dll/win32/shell32/dialogs/filedefext.cpp

In the folder property sheet, if the folder icon was changed, then 'General' tab should be also updated.
JIRA issue: [CORE-11407](https://jira.reactos.org/browse/CORE-11407)
- Implement PSM_QUERYSIBLINGS action for each property page.
- Send PSM_QUERYSIBLINGS message to the property sheet when the icon was updated.

[SHELL32] Refresh 'General' tab if folder icon updated

---

base/applications/cmdutils/tree/lang/pl-PL.rc
base/applications/cmdutils/tree/tree.rc

Translated `tree` utility to Polish.

[TRANSLATION][TREE] Polish translation of tree utility

---

base/applications/cmdutils/timeout/lang/pl-PL.rc
base/applications/cmdutils/timeout/timeout.rc

Translated `timeout` cmd utility to Polish.

[TRANSLATION][TIMEOUT] Add Polish translation of timeout cmd utility

---

drivers/setup/blue/font.c

* Fix spacing / formatting
* Refactor nested if / else
* Add more success checks and DPRINTs
* Fix usage of LARGE_INTEGER

[BLUE] Formatting and code improvements

---

modules/rosapps/applications/devutils/gdihv/gdi.h
modules/rosapps/applications/devutils/gdihv/handlelist.c
modules/rosapps/applications/devutils/syscalldump/syscalldump.c
modules/rosapps/applications/devutils/vgafontedit/editglyphdlg.c
modules/rosapps/applications/devutils/vgafontedit/fontboxeswnd.c
modules/rosapps/applications/devutils/vgafontedit/fontwnd.c
modules/rosapps/applications/devutils/vgafontedit/mainwnd.c
modules/rosapps/applications/sysutils/utils/stats/stats.c

Fixes a number of bugs / warnings

[ROSAPPS] Fix 64 bit issues

---

base/shell/explorer/traywnd.cpp
dll/win32/browseui/shellbrowser.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shell32.cpp
dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp
dll/win32/shell32/stubs.cpp
sdk/include/reactos/undocshell.h

This PR will force update of the system-wide environment variables.
JIRA issue: [CORE-1459](https://jira.reactos.org/browse/CORE-1459), [CORE-14397](https://jira.reactos.org/browse/CORE-14397)
- Implement RegenerateUserEnvironment function in shell32.
- CShellBrowser and CDesktopBrowser implements WM_SETTINGCHANGE actions.

[SHELL32][EXPLORER] Update system-wide environment variables

---

base/shell/explorer/traywnd.cpp

This PR will fix CORE-14772. Its symptom is as follows:
1. Click Task Bar.
2. On keyboard, type App key.
3. Access violation happens.
JIRA issue: [CORE-14772](https://jira.reactos.org/browse/CORE-14772)

[EXPLORER] Fix TrackCtxMenu about NULL ppt

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.h
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shlfolder.cpp

This implements the 'Properties...' menu item in My Computer.
JIRA issue: [CORE-12509](https://jira.reactos.org/browse/CORE-12509)
- Add the Shell_DefaultContextMenuCallBack function.
- Implement IContextMenuCB interface in CDrivesFolder.

[SHELL32] Add 'Properties' menu item in My Computer

---

win32ss/user/user32/windows/mdi.c

This PR will implement CascadeWindows function in user32.
JIRA issue: [CORE-14807](https://jira.reactos.org/browse/CORE-14807)

[USER32][WIN32SS] Implement CascadeWindows function

---

win32ss/user/user32/windows/mdi.c

This is an improvement of CascadeWindows in user32.
JIRA issue: [CORE-14807](https://jira.reactos.org/browse/CORE-14807)
- If the window is too large, then shrink it if possible.

[USER32][WIN32SS] Improve CascadeWindows function

---

base/applications/cmdutils/clip/clip.rc
base/applications/cmdutils/clip/lang/it-IT.rc

[TRANSLATION][CLIP] Italian resource file

---

dll/cpl/desk/lang/es-ES.rc

_As old way for submitting patches is deprecated, I forked a ReactOS repo on GitHub and made some changes._
JIRA issue: [CORE-14767](https://jira.reactos.org/browse/CORE-14767)
_Start with a few translations for new strings added months ago._
_Please apologize me if some mistakes were made, I am a completely github noob._

Spanish translations

---

base/shell/cmd/del.c

Based on the patch by @Doug-Lyons.
JIRA issue: [CORE-14059](https://jira.reactos.org/browse/CORE-14059)

[CMD] del /s directory doesn't show directries of files for confirmation

---

win32ss/user/user32/windows/mdi.c

This PR will implement TileWindows function in user32.
JIRA issue: [CORE-14815](https://jira.reactos.org/browse/CORE-14815)

[USER32][WIN32SS] Implement TileWindows function

---

modules/rosapps/applications/sysutils/rosddt/rosddt.c

JIRA issue: [ROSAPPS-343](https://jira.reactos.org/browse/ROSAPPS-343)

ROSAPPS-343. [ROSDDT] do_update_base(): Fix assignment to f

---

dll/cpl/desk/lang/es-ES.rc
dll/shellext/acppage/lang/es-ES.rc
dll/win32/browseui/lang/es-ES.rc
dll/win32/shell32/lang/es-ES.rc
dll/win32/userenv/lang/es-ES.rc

More strings translated to spanish in some areas like shell32 and win32, browseui, etc., also fix a typo in display cpl.
JIRA issue: [CORE-14767](https://jira.reactos.org/browse/CORE-14767)

[SHELL32][WIN32] Spanish translations

---

drivers/input/i8042prt/CMakeLists.txt
drivers/input/i8042prt/hwhacks.c
sdk/lib/CMakeLists.txt
sdk/lib/dmilib/CMakeLists.txt
sdk/lib/dmilib/dmi.h
sdk/lib/dmilib/dmilib.c
sdk/lib/dmilib/dmilib.h
sdk/lib/dmilib/precomp.h

Move DMI/SMBIOS parsing functions into library.
This would allow using the parsing functions both in kernel and user mode.

[I8042PRT] Move DMI/SMBIOS parsing functions into library

---

base/applications/cmdutils/taskkill/lang/it-IT.rc
base/applications/cmdutils/taskkill/taskkill.rc

Implement the Italian resource file for `taskkill` command utility.
CC @ElCresh for review.

[TRANSLATION][TASKKILL] Add Italian translation

---

dll/shellext/zipfldr/CZipFolder.hpp
dll/shellext/zipfldr/zipfldr.cpp
sdk/lib/atl/atlcomcli.h

- Implement `RouteTheCall` so that applications like rapps can directly `launch` zip files
- Add multiple context menu's so that we can extract from inside a zip view.
JIRA issue: [CORE-13982](https://jira.reactos.org/browse/CORE-13982)

Zipfldr usability fixes

---

base/applications/cmdutils/wmic/lang/it-IT.rc
base/applications/cmdutils/wmic/wmic.rc

[TRANSLATION][WMIC] Add Italian translation

---

win32ss/user/ntuser/sysparams.c

[WIN32SS][USER] fixing couple typos for WINVER >= 0x600

---

ntoskrnl/mm/ARM3/procsup.c

Kernel stacks that re freed, can be placed on an SLIST for quick reuse. The old code was using a member of the PFN of the last stack page as the SLIST_ENTRY. This relies on the following (non-portable) assumptions:
- A stack always has a PTE associated with it.
- This PTE has a PFN associated with it.
- The PFN has an empty field that can be re-used as an SLIST_ENTRY.
- The PFN has another field that points back to the PTE, which then can be used to get the stack base.
Specifically: On x64 the PFN field is not 16 bytes aligned, so it cannot be used as an SLIST_ENTRY. (In a "usermode kernel" the other assumptions are also invalid).
The new code does what Windows does (and which seems absolutely obvious to do): Place the SLIST_ENTRY directly on the stack.

[NTOS:MM] Make SLIST handling for kernel stacks portable

---

modules/rostests/apitests/atl/CComQIPtr.cpp
modules/rostests/apitests/atl/CMakeLists.txt
modules/rostests/apitests/atl/devenv/ATLTest.sln
modules/rostests/apitests/atl/devenv/CComObject.vcxproj
modules/rostests/apitests/atl/devenv/CComQIPtr.vcxproj
modules/rostests/apitests/atl/devenv/CImage.vcxproj
modules/rostests/apitests/atl/devenv/CSimpleArray.vcxproj
modules/rostests/apitests/atl/devenv/CString.vcxproj
modules/rostests/apitests/atl/testlist.c
sdk/lib/atl/atlcomcli.h

Don't mind me, just here for the free buildbot.

Atl improvements

---

sdk/include/reactos/mc/errcodes.mc

This PR replaces PR #487 
It was rebased and conflicts resolved.

[TRANSLATION] Polish translation of errcodes.mc (0-499)

---

win32ss/gdi/ntgdi/freetype.c

[FONT][WIN32SS] Refactor the loop (3 of 5)

---

win32ss/gdi/ntgdi/freetype.c

[FONT][WIN32SS] Refactor the loop (5 of 5)

---

win32ss/gdi/ntgdi/freetype.c

[FONT][WIN32SS] Refactor the loop (4 of 5)

---

win32ss/gdi/ntgdi/freetype.c

[FONT][WIN32SS] Refactor the loop (2 of 5)

---

win32ss/gdi/ntgdi/freetype.c

[FONT][WIN32SS] Refactor the loop (1 of 5)

---

dll/win32/syssetup/install.c

Previously CommonInstall() could return while the thread was still running and the caller would then free syssetup.dll.

[SETUP] Wait for ShowStatusMessageThread to terminate

---

drivers/filesystems/btrfs/btrfs.c
drivers/filesystems/btrfs/btrfs_drv.h
drivers/filesystems/btrfs/create.c
drivers/filesystems/btrfs/devctrl.c
drivers/filesystems/btrfs/dirctrl.c
drivers/filesystems/btrfs/fileinfo.c
drivers/filesystems/btrfs/pnp.c
drivers/filesystems/btrfs/read.c
drivers/filesystems/btrfs/security.c
drivers/filesystems/btrfs/write.c

[BTRFS] Fix booting with runtime checks.

---

dll/win32/shell32/CShellLink.cpp

This PR will enable the user to change the shortcut icon.
JIRA issue: [CORE-11407](https://jira.reactos.org/browse/CORE-11407)

[SHELL32] Enable to change shortcut icon

---

dll/shellext/zipfldr/lang/sv-SE.rc
dll/shellext/zipfldr/zipfldr.rc

Swedish translation of zipfldr

[ZIPFLDR] Add Swedish translation

---

dll/shellext/zipfldr/lang/ja-JP.rc
dll/shellext/zipfldr/zipfldr.rc

This PR will add Japanese translation to ZIP folder shell extension.
JIRA issue: [CORE-14954](https://jira.reactos.org/browse/CORE-14954)

[ZIPFLDR] Add Japanese translation

---

base/services/nfsd/idmap.c
base/services/nfsd/nfs41_daemon.c
base/services/telnetd/telnetd.c
base/services/telnetd/telnetd.h

JIRA issue: [CORE-14747](https://jira.reactos.org/browse/CORE-14747)

Remove the hardcoded directory paths C:\ReactOS

---

win32ss/gdi/ntgdi/bitblt.c
win32ss/gdi/ntgdi/path.c
win32ss/gdi/ntgdi/path.h
win32ss/gdi/ntgdi/region.h

I want to extend the PATH_FillPath function with adding a PBRUSH parameter.
JIRA issue: [CORE-2527](https://jira.reactos.org/browse/CORE-2527)

[WIN32SS][NTGDI] Extend PATH_FillPath as PATH_FillPathEx

---

dll/win32/shell32/CShellLink.cpp

This will fix CORE-14961. It was regression by #784.
JIRA issue: [CORE-14961](https://jira.reactos.org/browse/CORE-14961), [CORE-14009](https://jira.reactos.org/browse/CORE-14009)

[SHELL32] Fix CShellLink::GetIconLocation

---

dll/win32/comctl32/button.c
dll/win32/comctl32/combo.c
dll/win32/comctl32/comctl32.h
dll/win32/comctl32/commctrl.c
dll/win32/comctl32/edit.c
dll/win32/comctl32/listbox.c
dll/win32/comctl32/static.c

This should help fix some crashes.

[COMCTL32] Unregister some classes that were registered.

---

sdk/include/reactos/mc/errcodes.mc
sdk/include/reactos/mc/neteventmsg.mc

I had to complete the Polish messages by duplicating the English messages in order to fix MSVC build.
JIRA issue: [CORE-14977](https://jira.reactos.org/browse/CORE-14977)

Duplicate English messages as Polish Messages

---

dll/win32/msgina/lang/ru-RU.rc

[MSGINA] Update russian translation

---

dll/shellext/fontext/fontext.rc
dll/shellext/fontext/lang/it-IT.rc

[TRANSLATION][FONTEXT] Add Italian translation

---

base/setup/usetup/lang/bg-BG.h
base/setup/usetup/lang/bn-BD.h
base/setup/usetup/lang/cs-CZ.h
base/setup/usetup/lang/da-DK.h
base/setup/usetup/lang/de-DE.h
base/setup/usetup/lang/el-GR.h
base/setup/usetup/lang/en-US.h
base/setup/usetup/lang/es-ES.h
base/setup/usetup/lang/et-EE.h
base/setup/usetup/lang/fr-FR.h
base/setup/usetup/lang/he-IL.h
base/setup/usetup/lang/it-IT.h
base/setup/usetup/lang/ja-JP.h
base/setup/usetup/lang/lt-LT.h
base/setup/usetup/lang/ms-MY.h
base/setup/usetup/lang/nl-NL.h
base/setup/usetup/lang/pl-PL.h
base/setup/usetup/lang/pt-BR.h
base/setup/usetup/lang/ro-RO.h
base/setup/usetup/lang/ru-RU.h
base/setup/usetup/lang/sk-SK.h
base/setup/usetup/lang/sq-AL.h
base/setup/usetup/lang/sv-SE.h
base/setup/usetup/lang/tr-TR.h
base/setup/usetup/lang/uk-UA.h
base/setup/usetup/mui.h
base/setup/usetup/usetup.c

For those who are very familiar with the XP and 2000's USETUP, on quit and success pages there is a progress bar with a dynamic countdown which automatically reboots the computer when the time out is reached. I thank @HBelusca for giving me guidance and helping at fixing annoying bugs. ^_^
**Video URL:** https://www.youtube.com/watch?v=VoT56K3O6SQ

[USETUP] Implement progress bar on reboot phase

---

base/setup/reactos/lang/vi-VN.rc
base/setup/reactos/reactos.rc

[BASE/SETUP/REACTOS/LANG]
Took waay too long to figure stuff out.
If I'm doing anything incorrectly, tell me. 
- Added Vietnamese translation

Added Vietnamese translation

---

base/setup/usetup/lang/it-IT.h
base/setup/usetup/lang/ro-RO.h

Translations update for both _Romanian_ and _Italian_ resources to meet the recent #833 commit in master.
CC @ElCresh for review

[TRANSLATION][USETUP] Translations update (Romanian & Italian)

---

win32ss/gdi/ntgdi/freetype.c

This PR will add some dumping functions for debugging the font engine.
JIRA issue: [CORE-14912](https://jira.reactos.org/browse/CORE-14912)

[FONT][WIN32SS] Add dumping functions for debugging

---

base/setup/usetup/lang/ru-RU.h
base/setup/usetup/usetup.c

- Use update interval of 10 ms instead of 1 second
- Update russian translation

[USETUP] Make countdown progress bar smoother

---

dll/ntdll/ldr/ldrinit.c
dll/win32/kernel32/client/fiber.c
modules/rostests/apitests/kernel32/CMakeLists.txt
modules/rostests/apitests/kernel32/FLS.c
modules/rostests/apitests/kernel32/testlist.c
sdk/include/ndk/rtltypes.h

FLS implementation passes all tests.
Test passes from xp up to 10.
https://testbot.winehq.org/JobDetails.pl?Key=38266

FLS Callbacks

---

drivers/storage/class/ramdisk/ramdisk.c

Make installation via PXE possible
Implement the two missing IOCTLs in ramdisk which kept the bootcd from working

PXE BootCD Bringup

---

boot/freeldr/freeldr/lib/fs/btrfs.c

[FREELDR] Fix MSVC warnings C4146

---

base/applications/charmap_new/lang/it-IT.rc
base/applications/charmap_new/lang/ro-RO.rc
base/applications/msconfig_new/lang/ro-RO.rc

- Small translation update for `msconfig_new`
- Update the E-mail address header string (for `charmap_new`)

[TRANSLATION] Romanian translation update

---

base/applications/network/dwnl/CMakeLists.txt
base/applications/network/dwnl/dwnl.c
base/applications/network/dwnl/dwnl.rc
base/applications/network/dwnl/lang/en-US.rc
base/applications/network/dwnl/resource.h

Localize the file download utility.
JIRA issue: [CORE-14498](https://jira.reactos.org/browse/CORE-14498)
- Make it so that the file download utility can be translated into other languages.
- Also, added a timestamp feature that tells the user when the download started similar to how wget works (e.g. --2018-9-12 7:43:55--). This can be reverted on request.

Dwnl localize

---

base/applications/network/dwnl/dwnl.c
base/applications/network/dwnl/dwnl.rc
base/applications/network/dwnl/lang/ru-RU.rc

Translation here! :wink: 
Also improved date print just a bit.

[DWNL] Add russian translation

---

base/applications/network/dwnl/dwnl.rc
base/applications/network/dwnl/lang/pl-PL.rc

_Translated network dwnl utility to Polish._

[TRANSLATION] Added Polish DWNL translation

---

dll/win32/msports/lang/ru-RU.rc

[MSPORTS] Add russian translation

---

README.md

Added link to nightly builds in the apopriate place for convenience

Added link to nightly builds in the apopriate place of RM

---

dll/directx/wine/dmusic/dmobject.c

[DMUSIC] Fix the build for vs 2010

---

win32ss/gdi/ntgdi/font.h
win32ss/gdi/ntgdi/freetype.c

Thanks to Doug Lyons for pinpointing the issue.
JIRA issue: [CORE-14044](https://jira.reactos.org/browse/CORE-14044)

[FONT][WIN32SS] Include the style name in the registry key.

---

dll/win32/devmgr/lang/ru-RU.rc
dll/win32/msports/lang/ru-RU.rc
dll/win32/netcfgx/lang/ru-RU.rc

[DEVMGR][MSPORTS][NETCFGX] Update russian translation

---

dll/cpl/appwiz/lang/ru-RU.rc

[APPWIZ] Update russian translation

---

modules/rosapps/applications/sysutils/systeminfo/systeminfo.c

Use better source for uptime information in `systeminfo` (which has been merged into `sysdm`)

[UPTIME][SYSTEMINFO] Improvements

---

sdk/cmake/CMakeMacros.cmake
sdk/tools/mkhive/mkhive.c
sdk/tools/mkhive/mkhive.h
sdk/tools/mkhive/reginf.c
sdk/tools/mkhive/registry.c
sdk/tools/mkhive/registry.h

- Make mkhive a bit more flexible, so that it can generate only specific hives on-demand (and not all of them always at once).
- Perform the associated adjustments in CMakeMacros.cmake.

Setup improvements n°2 -- MKHIVE, hives (cmake)

---

ntoskrnl/kd/wrappers/gdbstub_powerpc.c

Complete this issue a bit more.
JIRA issue: [CORE-8545](https://jira.reactos.org/browse/CORE-8545)

CORE-8545. [NTOS:KD] A few trivial code improvements

---

dll/win32/dbghelp/CMakeLists.txt
dll/win32/kernel32/kernel32.spec
sdk/cmake/gcc.cmake
sdk/cmake/msvc.cmake
sdk/include/reactos/stubs.h
sdk/tools/spec2def/spec2def.c

Initial support for forwarders based on NT versions.

Forwarders

---

dll/win32/shell32/CDefView.cpp

JIRA issue: [CORE-14976](https://jira.reactos.org/browse/CORE-14976)
This allows shell extensions to start with a non-default view (like, zipfld starts in detail mode)

[SHELL32] CDefView: Query SFVM_DEFVIEWMODE before creating the list view

---

modules/rosapps/applications/cmdutils/gflags/CMakeLists.txt
modules/rosapps/applications/cmdutils/gflags/gflags.c
modules/rosapps/applications/cmdutils/gflags/gflags.h
modules/rosapps/applications/cmdutils/gflags/imagefile.c
modules/rosapps/applications/cmdutils/gflags/pageheap.c

Moved some code around as to not have a huge mess in one file.
the `/p` functionality should still work as before, except that the image filename can no longer be specified before the `/p`

Add image GlobalFlags to our gflags

---

subsystems/mvdm/ntvdm/dos/dos32krnl/dosfiles.c

Found when trying Holmes2:
https://z.abandonware-france.org/jeux/1996/jeu-00796-sherlock_holmes_rose_tatouee-pcdos.7z

[NTVDM] Implement INT21, AX=4408, Determine if a block device is removable.

---

subsystems/mvdm/ntvdm/dos/dos32krnl/dos.c

Some applications, run on a CDROM, may attempt to open
a file with write access. CDFS driver will deny such
request in ReactOS (but also in Windows NT). Then, to
restore that behavior from old Windows (9X), our ntvdm,
as Microsoft ntvdm will attempt to reopen the file only
with read access, if opening failed because of denied access
and if the file is on a CDROM.
These are the last bits required to fix Lost Files 2 setup in ReactOS :-).
JIRA issue: [CORE-15211](https://jira.reactos.org/browse/CORE-15211)

[NTVDM] Allow opening files with write access on CDROM

---

base/applications/notepad/lang/hi-IN.rc
base/applications/notepad/rsrc.rc

- Creating hi-IN.rc and doing translations in it.
- Defining hi-IN.rc in rsrc.rc

ReactOS Notepad Hindi Translation

---

dll/cpl/appwiz/lang/it-IT.rc
dll/cpl/appwiz/lang/ro-RO.rc

[TRANSLATION][APPWIZ] Translation update for Romanian & Italian resources

---

base/applications/rapps/lang/et-EE.rc
base/applications/rapps/rapps.rc

This PR translates RAPPS into Estonian.

[RAPPS][TRANSLATION] Estonian localization

---

base/applications/regedit/childwnd.c

- Beautify ResizeWnd function.
- Delete useless (void) type casts.

[REGEDIT] Code formatting

---

ntoskrnl/config/ntapi.c

- Improve the capture of OBJECT_ATTRIBUTES parameters that are passed
(by pointer) to the Cm* helper functions, and the capture of
UNICODE_STRINGs.
- Correctly differentiate user-mode vs. kernel-mode root directory handles
(in OBJECT_ATTRIBUTES): note that most of the Cm* APIs expect their
parameters to be kernel-mode (pointers, handles...).
CORE-13448

[NTOS:CM] Improve the capture of user-mode parameters.

---

modules/rostests/apitests/ntdll/NtLoadUnloadKey.c
ntoskrnl/config/cmapi.c
ntoskrnl/config/ntapi.c
ntoskrnl/include/internal/cm.h

Implement more support for force-unloading registry hives.
CORE-13448 CORE-10705

[NTOS:CM] Implement more support for force-unloading registry hives. CORE-13448

---

base/applications/regedit/childwnd.c

[REGEDIT] Fix the layout of controls

---

dll/win32/shimgvw/shimgvw.c

Make "Picture and Fax Viewer" able to play.
JIRA issue: [CORE-12680](https://jira.reactos.org/browse/CORE-12680)

[SHIMGVW] Play GIF animation

---

win32ss/user/ntuser/menu.c

This PR will fix the vertical position of menu text.
JIRA issue: [CORE-15094](https://jira.reactos.org/browse/CORE-15094)

[WIN32SS][MENU] Fix menu text Y positioning

---

win32ss/gdi/ntgdi/freetype.c

This PR will improve human readability of IntGdiGetFontResourceInfo function in freetype.c.
- NULL-ify the NameInfo1 and NameInfo2 variables.
- Groupify the destruction of NameInfo1 and NameInfo2.
- Add two constant variables of MAX_FAM_INFO_BYTES and NAMEINFO_SIZE.

[FONT][WIN32SS] Improve readability of IntGdiGetFontResourceInfo

---

win32ss/user/user32/windows/window.c

This PR will fix user32!SwitchToThisWindow function.

[WIN32SS][USER32] Fix SwitchToThisWindow function

---

sdk/include/reactos/mc/errcodes.mc

JIRA issue: [CORE-11898](https://jira.reactos.org/browse/CORE-11898)
Based on patch by @reactos-contributor.

[TRANSLATION][MC] Add Romanian messages

---

base/applications/taskmgr/lang/et-EE.rc
base/applications/taskmgr/taskmgr.rc

Translate Task Manager to Estonian.

[TASKMGR][TRANSLATION] Estonian localization

---

dll/win32/shimgvw/shimgvw.c

When shell image viewer renders animations, there is flickering between frames. This PR fixes it.
- Do `InvalidateRect` without clearing background
- Use `NULL_BRUSH` to make `Rectangle` transparent (avoid extra clear)
- Do not fill entire window with `FillRect`, instead fill regions around the image
Cc @katahiromz and @yagoulas 
Note for Giannis:
> I also tried to make usage of `WndClass.hbrBackground` but not appreciated it (it flickers the entire window when resizing, even toolbar :open_mouth: )

[SHIMGVW] Fix image flickering when rendering animations

---

modules/rostests/apitests/user32/CMakeLists.txt
modules/rostests/apitests/user32/SwitchToThisWindow.c
modules/rostests/apitests/user32/testlist.c

Add an API test program for user32!SwitchToThisWindow function.

[APITESTS][USER32] Add testcase for SwitchToThisWindow

---

win32ss/user/ntuser/menu.c

JIRA issue: [CORE-15226](https://jira.reactos.org/browse/CORE-15226)
- Move the menu item contents 1 pixel right and down if the condition was satisfied.
- Add the "forgotten" background painting in specific condition.

[WIN32SS][NTUSER] Implement sunken menu item

---

win32ss/user/ntuser/menu.c

This should fix microregression introduced in ed41bd7.
JIRA issue: [CORE-15226](https://jira.reactos.org/browse/CORE-15226)
- Make offset only for menu bars

[WIN32SS][NTUSER] Make offset only for menu bars

---

win32ss/user/user32/windows/window.c

[WIN32SS][USER32] Fix #984

---

win32ss/user/user32/windows/window.c

- Make the return value of CloseWindow the result value of PostMessageW. This will simplify CloseWindow code.

[WIN32SS][USER32] Improve CloseWindow

---

win32ss/user/ntuser/simplecall.c
win32ss/user/user32/include/ntwrapper.h
win32ss/user/user32/windows/window.c

- Implement user32!SwitchToThisWindow by NtUserCallTwoParam TWOPARAM_ROUTINE_SWITCHTOTHISWINDOW.
- Improve user32!CloseWindow.

[WIN32SS] Move SwitchToThisWindow codes to win32k

---

win32ss/user/ntuser/simplecall.c
win32ss/user/user32/windows/window.c

Thanks info @HBelusca.
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-switchtothiswindow
https://blogs.msdn.microsoft.com/oldnewthing/20111107-00/?p=9183

[WIN32SS] SwitchToThisWindow 2nd argument is fAltTab

---

base/applications/drwtsn32/stacktrace.cpp

Especially when dealing with nullpointers.

[DRWTSN32] Improve stack dumping

---

base/applications/drwtsn32/stacktrace.cpp
dll/win32/kernel32/client/proc.c
dll/win32/kernel32/client/thread.c
win32ss/user/ntuser/scrollbar.c

JIRA issue: [CORE-13918](https://jira.reactos.org/browse/CORE-13918)

[WIN32SS] Disable scrollbars when SIF_DISABLENOSCROLL is used

---

win32ss/user/ntuser/simplecall.c

[WIN32SS] Make window foreground in SwitchToThisWindow

---

modules/rostests/apitests/user32/CMakeLists.txt
modules/rostests/apitests/user32/CloseWindow.c
modules/rostests/apitests/user32/testlist.c

This PR will add a testcase for user32!CloseWindow function.

[APITESTS] Add CloseWindow testcase

---

modules/rostests/apitests/user32/CloseWindow.c

This PR will improve the testcase for user32!CloseWindow function.
- Fix the caption text.
- Add a check for CloseWindow(NULL).

[APITESTS] Improve CloseWindow testcase

---

modules/rostests/apitests/user32/SwitchToThisWindow.c

[APITESTS] Add InSendMessage check in SwitchToThisWindow testcase

---

win32ss/gdi/ntgdi/freetype.c

Improve Font Precision Penalty.

[WIN32SS][FONT] Improve Precision Penalty

---

modules/rostests/kmtests/ntos_mm/ZwMapViewOfSection.c

JIRA issue: [ROSTESTS-110](https://jira.reactos.org/browse/ROSTESTS-110)

ROSTESTS-110. [KMTESTS:MM] Fix 'PAGE_NOACCESS' copypasta, in an error string

---

sdk/include/reactos/msgdump.h
sdk/include/reactos/winxx.h

Add "winxx.h" and "msgdump.h" to "sdk/include/reactos".
"winxx.h" defines additional message cracker macros.
"msgdump.h" enables us to dump Win32API message info.

[INCLUDE] Add <winxx.h> and <msgdump.h>

---

dll/cpl/appwiz/lang/pl-PL.rc

[APPWIZ] Update polish translation

---

base/setup/reactos/lang/tr-TR.rc
base/setup/welcome/lang/tr-TR.rc

[REACTOS] Fix and add Turkish translations.
[WELCOME] Fix some Turkish translations.

Turkish Translations of [REACTOS] and [WELCOME]

---

base/system/rundll32/lang/tr-TR.rc
base/system/userinit/lang/tr-TR.rc
base/system/winlogon/lang/tr-TR.rc
media/themes/blackshade.msstyles/lang/tr-TR.rc
media/themes/lautus.msstyles/lang/tr-TR.rc
media/themes/modern.msstyles/lang/tr-TR.rc
subsystems/mvdm/ntvdm/lang/tr-TR.rc
win32ss/printing/monitors/localmon/ui/lang/ui_Tr.rc
win32ss/user/user32/lang/tr-TR.rc
win32ss/user/winsrv/consrv/frontends/gui/lang/tr-TR.rc
win32ss/user/winsrv/consrv_new/frontends/gui/lang/tr-TR.rc
win32ss/user/winsrv/usersrv/lang/tr-TR.rc

[NTVDM] Fix Turkish translations.
[LOCALMON] Fix Turkish translations.
[USER32] Fix Turkish translations.
[CONSRV] Fix Turkish translations.
[CONSRW_NEW] Fix Turkish translations.
[USERSRV] Fix and add Turkish translations.
[BLACKSHADE.MSSTYLES] Fix Turkish translations.
[LAUTUS.MSSTYLES] Fix Turkish translations.
[MODERN.MSSTYLES] Fix Turkish translations.
[RUNDLL32] Fix Turkish translations.
[USERINIT] Fix and add Turkish translations.
[WINLOGON] Fix and add Turkish translations.

Turkish translations of many components.

---

base/system/chkdsk/chkdsk.rc
base/system/chkdsk/lang/it-IT.rc
base/system/chkdsk/lang/ro-RO.rc

[CHKDSK] Implement translation files for Romanian & Italian

---

dll/shellext/netshell/README

[NETSHELL] Fix '0' typo, in a text

---

base/applications/drwtsn32/CMakeLists.txt
base/applications/drwtsn32/sysinfo.cpp
sdk/lib/dmilib/dmilib.h
sdk/lib/udmihelp/udmihelp.h

Add SMBIOS system information to the Dr. Watson Appcrash log. :relaxed: 

[DRWTSN32] Add SMBIOS data to the system information

---

base/applications/dxdiag/CMakeLists.txt
base/applications/dxdiag/precomp.h
dll/cpl/sysdm/CMakeLists.txt
dll/cpl/sysdm/smbios.c
modules/rosapps/applications/sysutils/systeminfo/CMakeLists.txt
modules/rosapps/applications/sysutils/systeminfo/systeminfo.c

Include only one user-mode DMI library. Addendum to baf2c0cc.

[SYSDM][DXDIAG][SYSTEMINFO] Include only one user-mode DMI library

---

win32ss/user/ntuser/ntstubs.c

Fix indentation (inconsistent with the rest of the file) and return actual BOOL.

[WIN32K][NTUSER] Tiny codestyle fix to NtUserLockWindowUpdate

---

sdk/include/reactos/msgdump.h
sdk/include/reactos/winxx.h

[INCLUDE] Update winxx.h and msgdump.h

---

win32ss/CMakeLists.txt
win32ss/user/ntuser/ghost.c
win32ss/user/ntuser/ghost.h
win32ss/user/ntuser/message.c
win32ss/win32kp.h

JIRA issue: [CORE-11944](https://jira.reactos.org/browse/CORE-11944)

[WIN32SS] Add IntGoGhost function (stub)

---

dll/win32/shell32/dialogs/fprop.cpp

@learn-more advised me.
JIRA issue: [CORE-10481](https://jira.reactos.org/browse/CORE-10481)

[SHELL32] Follow up of #1085

---

dll/win32/shell32/dialogs/fprop.cpp

careless s/E_FAIL/FALSE/

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-15419](https://jira.reactos.org/browse/CORE-15419)
- Improve FamilyUnknown font penalty.

[WIN32SS][FONT] Improve FamilyUnknown Penalty

---

win32ss/gdi/ntgdi/font.c
win32ss/gdi/ntgdi/freetype.c

[WIN32SS][FONT] Add some assertions

---

base/applications/notepad/lang/ru-RU.rc
base/setup/usetup/lang/ru-RU.h
win32ss/user/user32/lang/ru-RU.rc

Update russian translations

---

win32ss/include/ghostwnd.h
win32ss/user/ntuser/class.h
win32ss/user/ntuser/ghost.c
win32ss/user/ntuser/ghost.h
win32ss/user/ntuser/message.c
win32ss/user/user32/controls/ghost.c

In previous #1100 commit, ReactOS wouldn't startup. This PR is fixed.
JIRA issue: [CORE-11944 ](https://jira.reactos.org/browse/CORE-11944 )

[WIN32SS][USER32] Add Ghost codes (retrial of #1100)

---

dll/win32/shell32/dialogs/dialogs.cpp

JIRA issue: [CORE-15431](https://jira.reactos.org/browse/CORE-15431)
BEFORE:
AFTER:

[SHELL32] Accept environment variables in 'Run' dialog

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-15433](https://jira.reactos.org/browse/CORE-15433)

[WIN32SS][FONT] Check NULL of Face->style_name

---

dll/win32/shell32/lang/ca-ES.rc
dll/win32/shell32/lang/da-DK.rc
dll/win32/shell32/lang/en-GB.rc
dll/win32/shell32/lang/en-US.rc
dll/win32/shell32/lang/fi-FI.rc
dll/win32/shell32/lang/he-IL.rc
dll/win32/shell32/lang/hu-HU.rc
dll/win32/shell32/lang/ko-KR.rc
dll/win32/shell32/lang/nl-NL.rc
dll/win32/shell32/lang/pt-BR.rc
dll/win32/shell32/lang/sl-SI.rc
dll/win32/shell32/lang/zh-TW.rc

_Changed "content" to "contents"._
_Fix IDS_TRASHFOLDER_TEXT grammar._
- ~~"Are you sure that you want to send '%1' and all its content to the Recycle Bin?"~~
- "Are you sure that you want to send '%1' and all its contents to the Recycle Bin?"
Text can't feel. So we have to change what it says, before it becomes sentient.

Grammar fix: content -> contents

---

ntoskrnl/mm/ARM3/pagfault.c

Merely typo-fixing PR (earlier also contained #1035 equivalent).
**update:** since #1035 is merged, this will be typo-fixing PR.

[NTOS:MM] Fix typo in MiCheckForUserStackOverflow

---

modules/rostests/apitests/ws2_32/WSAAsync.c
modules/rostests/apitests/ws2_32/nonblocking.c

[WS2_32_APITEST] Fix 'inialialization' typo, in comments

---

dll/cpl/access/access.c
dll/cpl/appwiz/createlink.c
dll/cpl/console/console.c
dll/cpl/desk/desk.c
dll/cpl/hdwwiz/hdwwiz.c
dll/cpl/inetcpl/inetcpl.c
dll/cpl/input/input.c
dll/cpl/intl/generalp.c
dll/cpl/intl/intl.c
dll/cpl/main/keyboard.c
dll/cpl/main/mouse.c
dll/cpl/mmsys/mmsys.c
dll/cpl/openglcfg/openglcfg.c
dll/cpl/powercfg/powercfg.c
dll/cpl/sysdm/sysdm.c
dll/cpl/timedate/timedate.c
dll/cpl/usrmgr/usrmgr.c
dll/cpl/wined3dcfg/wined3dcfg.c

JIRA issue: [CORE-15445](https://jira.reactos.org/browse/CORE-15445)

[CPL] Properly set display icons of control panel applets

---

base/shell/explorer/trayprop.cpp

JIRA issue: [CORE-10494](https://jira.reactos.org/browse/CORE-10494)

[EXPLORER] Set display icon of task properties

---

dll/win32/shell32/lang/fr-FR.rc

Improve French dialog layout.
JIRA issue: [CORE-15259](https://jira.reactos.org/browse/CORE-15259)
BEFORE:
AFTER:

[SHELL32] Improve French translation of Folder Options View

---

dll/keyboard/kbdrost/kbdrost.c
modules/rostests/apitests/ntdll/RtlGenerate8dot3Name.c

Add UTF-8 Bottom Order Mark (BOM) to the top of files.
JIRA issue: [CORE-15447](https://jira.reactos.org/browse/CORE-15447)

[KBDROST][NTDLL_APITEST] Add UTF-8 BOM

---

win32ss/user/user32/controls/appswitch.c

Implement Arrow keys on App Switcher (Alt+Tab).
JIRA issue: [CORE-15449](https://jira.reactos.org/browse/CORE-15449)

[USER32] App Switcher Arrow keys

---

dll/win32/ole32/usrmarshal.c

This imports wine commit 25b136d40080a80c006b89e02708d2e248504a42,
by Huw Davies and Zebediah Figura
JIRA issue: [CORE-14696](https://jira.reactos.org/browse/CORE-14696)

[OLE32] Don't free handles that are just copied in the inproc case.

---

modules/rosapps/applications/devutils/vgafontedit/CMakeLists.txt
modules/rosapps/applications/devutils/vgafontedit/mainwnd.c

- Allow file drop on EXE file.
- Allow file drop on the main window.

[ROSAPPS][VGAFONTEDIT] Allow file drop

---

base/setup/usetup/lang/he-IL.h

Finish the Hebrew translation, no more reversed Hebrew gibberish.
Notes:
Codepage is 862,
Text is stored in visual order (characters are written in the order they should be displayed)
Some strings weren't changed to avoid issues with the formatting tokens inside them.
Utility I wrote to make this less annoying: https://github.com/peterooch/myutils/tree/master/OneLineReorderer

[TRANSLATION][USETUP] Complete Hebrew translation

---

base/applications/osk/lang/et-EE.rc

The welcome dialog box resource (which shows up on startup) was missing. So let's just add it.

[OSK] Add missing welcome box resource for Estonian

---

win32ss/gdi/eng/rlecomp.c

This PR is based on a patch by @Vort.
JIRA issues: [CORE-10553](https://jira.reactos.org/browse/CORE-10553), [CORE-11399](https://jira.reactos.org/browse/CORE-11399)

[WIN32SS] Fix RLE4 bitmap decoding

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-14856](https://jira.reactos.org/browse/CORE-14856)
Simplify the background filling codes.

[FONT][WIN32SS] Refactor rendering text background

---

win32ss/user/ntuser/menu.c

This PR will fix vertical position of non-menubar menu text.
JIRA issue: [CORE-15226](https://jira.reactos.org/browse/CORE-15226)

[MENU][WIN32SS] Fix non-menubar menu text Y position

---

dll/win32/browseui/browseui.rc
dll/win32/browseui/lang/hi-IN.rc
dll/win32/comctl32/lang/comctl_Hi.rc
dll/win32/comctl32/rsrc.rc
dll/win32/shell32/lang/hi-IN.rc
dll/win32/shell32/shell32.rc

- Translated browseui, comctl32 and shell32
- Added new .rc files of translated ones.
- Defined Hindi translated .rc file on the browseui.rc, rsrc.rc and shell32.rc

[TRANSLATION] Translation of browseui, comctl32 and shell32

---

dll/ntdll/ldr/ldrinit.c
dll/ntdll/ldr/ldrpe.c
dll/ntdll/ldr/ldrutils.c

Fix some issues pointed out by PVS-Studio.

PVS - ntdll fixes

---

base/applications/osk/lang/it-IT.rc

This improves the sentence's wording a lot better. The idea is based on [that comment](https://github.com/reactos/reactos/commit/760027783a6c8d5c8e23fb49addef4c694b8e672#commitcomment-31835111l).

[OSK] Fix a sentence in Italian resource

---

dll/appcompat/apphelp/CMakeLists.txt
dll/appcompat/apphelp/apphelp.h
dll/appcompat/apphelp/hsdb.c
dll/appcompat/apphelp/sdbstringtable.c
dll/appcompat/apphelp/sdbwrite.c
dll/appcompat/apphelp/shimeng.c
dll/appcompat/shims/shimlib/implement_shim.inl
dll/appcompat/shims/shimlib/shimlib.h
sdk/include/reactos/appcompat/sdbtagid.h
sdk/include/reactos/appcompat/sdbtypes.h
sdk/tools/xml2sdb/CMakeLists.txt
sdk/tools/xml2sdb/xml2sdb.h

Move those 2 common files to a shared location (in preparation of other work).
Also tack on a few unrelated commits to slightly reduce my local diff.

[APPCOMPAT] Move sdbtagid.h and sdbtypes.h to a shared location

---

base/shell/cmd/config.h
dll/win32/kernel32/include/kernel32.h
dll/win32/kernel32/kernel32.spec
dll/win32/kernel32/winnls/string/lang.c
dll/win32/kernel32/winnls/string/lcformat.c
dll/win32/kernel32/winnls/string/nls.c
media/doc/README.WINE
sdk/include/psdk/winnls.h

[KERNEL32] make some NLS and Format functions work

---

modules/rostests/apitests/spoolss/MarshallDownStructuresArray.c
modules/rostests/apitests/spoolss/PackStrings.c
win32ss/gdi/gdi32/CMakeLists.txt
win32ss/printing/base/spoolss/tools.c
win32ss/printing/base/spoolsv/printerdrivers.c
win32ss/printing/base/winspool/printers.c
win32ss/printing/include/marshalling/printerdrivers.h
win32ss/printing/include/spoolss.h
win32ss/printing/monitors/localmon/ports.c
win32ss/printing/processors/winprint/main.c
win32ss/printing/providers/localspl/CMakeLists.txt
win32ss/printing/providers/localspl/jobs.c
win32ss/printing/providers/localspl/main.c
win32ss/printing/providers/localspl/monitors.c
win32ss/printing/providers/localspl/precomp.h
win32ss/printing/providers/localspl/printerdrivers.c
win32ss/printing/providers/localspl/printers.c

_winetest goes boom_
JIRA issue: [CORE-15522](https://jira.reactos.org/browse/CORE-15522)

Semi-implement GetPrinterDriverW and DocumentPropertiesW

---

modules/rostests/kmtests/ntos_ex/ExPools.c
ntoskrnl/include/ntoskrnl.h
ntoskrnl/mm/ARM3/expool.c
ntoskrnl/mm/ARM3/section.c
ntoskrnl/ps/quota.c

This implements expansion of the big pool tracker table.
JIRA issue: [CORE-15051](https://jira.reactos.org/browse/CORE-15051)

Implement big pool table expansion

---

dll/apisets/api-ms-win-core-crt-l1-1-0.spec
dll/apisets/api-ms-win-crt-private-l1-1-0.spec
dll/win32/msvcrt/msvcrt.spec

[MSVCRT] export _local_unwind4 for 6.0+ version

---

dll/cpl/mmsys/audio.c

Properly select current MIDI output device.
JIRA issue: [CORE-15582](https://jira.reactos.org/browse/CORE-15582)

[MMSYS] Properly select current MIDI output device

---

dll/win32/shell32/CDefView.cpp

[SHELL32] CDefView: Remove a remnant string part

---

modules/rostests/apitests/user32/GetMessageTime.c

Compare `GetMessageTime` and `GetTickCount` values.
JIRA issue: [CORE-15565](https://jira.reactos.org/browse/CORE-15565)

[USER32_APITEST] Improve GetMessageTime tests more

---

win32ss/user/ntuser/defwnd.c

This is a follow-up and refactoring of #1226.
JIRA issue: [CORE-12845](https://jira.reactos.org/browse/CORE-12845)

[WIN32SS][NTUSER] Follow-up of PR #1226

---

win32ss/user/ntuser/defwnd.c
win32ss/user/ntuser/nonclient.c

Desktop window was treated as possible to resize.
fix for 7e396787ed00a3939031447725f79697a41878e1
CORE-15624

[WIN32SS][NTUSER] fix window snap madness

---

win32ss/user/ntuser/caret.c

Fix caret position of Ghostscript.
JIRA issue: [CORE-13934](https://jira.reactos.org/browse/CORE-13934), [CORE-15656](https://jira.reactos.org/browse/CORE-15656).

[WIN32SS][NTUSER] Fix caret position of Ghostscript

---

dll/win32/winmm/registry.c

Load Wave/MIDI mapper drivers only after actual device drivers.
JIRA issue: [CORE-15620](https://jira.reactos.org/browse/CORE-15620)
**Note:** winmm is not synced with Wine (it's forked), so I did not used `__REACTOS__` ifdefs.

[WINMM] Load Wave/MIDI mapper drivers only after actual device drivers

---

ntoskrnl/ke/i386/v86vdm.c

PR because I messed up things with my git setup...

[NTOS/KE] Add diagnosis DPRINT for CORE-15642

---

base/shell/explorer/taskswnd.cpp
win32ss/user/user32/controls/appswitch.c

JIRA issue: [CORE-15653](https://jira.reactos.org/browse/CORE-15653)

[USER32] Fix AppSwitcher (Alt+Tab)

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

[WIN32KNT_APITEST] Improve NtGdiSetBitmapBits more

---

win32ss/gdi/ntgdi/bitmaps.c

Improve `UnsafeGetBitmap` and `NtGdiGetBitmapBits` functions.
Splitted from #1305.

[WIN32SS][NTGDI] Improve UnsafeGetBitmapBits and NtGdiGetBitmapBits

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

The magic value `565` comes from the position of the `Bits` buffer on the stack and does not say anything about the implementation of NtGdiSetBitmapBits.
Here's an example that shows the function will accept buffers at least as large as 0x100000, and will fail if probing the entire range fails (in this case due to an explicit NOACCESS page at the end).

[WIN32KNT_APITEST] Test large buffers without relying on stack layout.

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

JIRA issue: [CORE-15657](https://jira.reactos.org/browse/CORE-15657) and [CORE-15695](https://jira.reactos.org/browse/CORE-15695)
- Add some PAGE_READONLY tests.
- Add two bit pattern tests.

[WIN32KNT_APITEST] Improve NtGdiSetBitmapBits 6

---

base/setup/usetup/lang/ReadMe.txt
base/setup/usetup/lang/ro-RO.h

- Add `lang/ReadMe.txt` for code7bit description.
- Follow up `ro-RO.h` file (#1317).
Cc @reactos-contributor

[USETUP] Follow-up ro-RO.h and add lang/ReadMe.txt

---

ntoskrnl/ob/oblife.c

JIRA issue: [CORE-14271](https://jira.reactos.org/browse/CORE-14271)

CORE-14271. [NTOS:OB] Correctly check SeSinglePrivilegeCheck() return value

---

modules/rostests/apitests/gdi32/CMakeLists.txt
modules/rostests/apitests/gdi32/TextTransform.c
modules/rostests/apitests/gdi32/testlist.c

This PR will prove text/font transformation functionality (#1238).

[APITESTS][GDI32] Add TextTransform testcase

---

win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/xformobj.c

Improve coordinate transformation except `LOGFONT.lfOrientation` in font/text rendering.
JIRA issue: [CORE-15554](https://jira.reactos.org/browse/CORE-15554), [CORE-15623](https://jira.reactos.org/browse/CORE-15623)

[FONT][WIN32SS] Improve font coordinate transformation

---

boot/freeldr/freeldr/arch/i386/entry.S

Option 2
JIRA issue: [CORE-15700](https://jira.reactos.org/browse/CORE-15700)

[FREELDR] Fix msvc boot

---

modules/rostests/apitests/ntdll/CMakeLists.txt
modules/rostests/apitests/ntdll/NtQueryInformationFile.c
modules/rostests/apitests/ntdll/NtQuerySystemInformation.c
modules/rostests/apitests/ntdll/NtQueryVolumeInformationFile.c
modules/rostests/apitests/ntdll/NtSetInformationFile.c
modules/rostests/apitests/ntdll/NtSetVolumeInformationFile.c
modules/rostests/apitests/ntdll/testlist.c
ntoskrnl/ex/sysinfo.c
ntoskrnl/io/iomgr/iofunc.c

JIRA issue: [CORE-15651](https://jira.reactos.org/browse/CORE-15651)

[NTOSKRNL] Guard against negative InformationClass enum values.

---

ntoskrnl/mm/ARM3/expool.c

Should hopefully stop kmtest:ExPools from taking up large parts of the testbot log.

[NTOS:MM] Dump pool consumers at most once per second.

---

dll/ntdll/include/ntdllp.h
dll/ntdll/ldr/ldrinit.c
dll/ntdll/rtl/libsupp.c
modules/rostests/apitests/ntdll/CMakeLists.txt
modules/rostests/apitests/ntdll/RtlComputePrivatizedDllName_U.c
modules/rostests/apitests/ntdll/testlist.c
sdk/include/ndk/rtlfuncs.h
sdk/lib/rtl/path.c

JIRA issue: [CORE-187](https://jira.reactos.org/browse/CORE-187)

Add support for .Local files

---

dll/ntdll/ldr/ldrpe.c

JIRA issue: [CORE-15729](https://jira.reactos.org/browse/CORE-15729)

[LDR] Check forwarded imports against the manifest before trying to load them

---

boot/bootdata/hivecls.inf
dll/shellext/CMakeLists.txt
dll/shellext/cryptext/CMakeLists.txt
dll/shellext/cryptext/cryptext.c
dll/shellext/cryptext/cryptext.spec
dll/shellext/cryptext/precomp.h

I'll leave the translating, the iconizing and friendly naming to whoever feels like doing that
So a suggestion to update the PR with either of those will volunteer you to add it.

[CRYPTEXT] Add a minimal shell extension that will show the certificate dialog

---

dll/win32/iphlpapi/CMakeLists.txt
dll/win32/iphlpapi/iphlpapi.spec
dll/win32/iphlpapi/iphlpapi_fakestubs.c

JIRA issue: [CORE-8462](https://jira.reactos.org/browse/CORE-8462)
JIRA issue: [CORE-15665](https://jira.reactos.org/browse/CORE-15665)

[IPHLPAPI] Preserve decoration in exported symbols

---

dll/shellext/cryptext/cryptext.rc
dll/shellext/cryptext/lang/ru-RU.rc

Translation here! :wink: 
Addendum to d56d9c1.

[CRYPTEXT] Add russian translation

---

media/inf/nete1000.inf

Fix E1000 driver date. DriverVer date format is `mm/dd/yyyy`.

[MEDIA][INF] Fix E1000 driver date

---

sdk/include/crt/_mingw.h
sdk/include/ndk/section_attribs.h
sdk/lib/cpprt/CMakeLists.txt
sdk/lib/cpprt/terminate.cpp
sdk/lib/crt/crt.cmake
sdk/lib/crt/msvcrtex.cmake
sdk/lib/crt/startup/threadSafeInit.c
sdk/lib/crt/stdlib/clang-alias.s
sdk/lib/crt/stdlib/rot.c
subsystems/mvdm/asm16.cmake

This fixes a a number of issues that we have with Clang-CL recently, probably due to an update to the Clang version that we use. (@AmineKhaldi?)

Fix clang cl build

---

dll/shellext/cryptext/cryptext.rc
dll/shellext/cryptext/lang/it-IT.rc
dll/shellext/cryptext/lang/ro-RO.rc

[CRYPTEXT] Add Romanian & Italian translations

---

base/setup/usetup/usetup.c

As per the Thomas' comment from #1264:
>Now of course you'd also need to check this functions return value... :p
(To be clear, I'm okay with not doing that in this PR)

[USETUP] Check the status value of BuildInstallPaths()

---

sdk/include/reactos/msgdump.h
sdk/include/reactos/winxx.h

Support Drag & Drop undocumented messages in `sdk/include/reactos/msgdump.h`.

[INCLUDE] msgdump.h undocumented drag & drop support

---

win32ss/user/ntuser/menu.c

JIRA issue: [CORE-15733](https://jira.reactos.org/browse/CORE-15733)

[WIN32K:NTUSER] Do not try to reposition an off-screen menu as if it were a popup menu

---

base/applications/sndvol32/lang/ru-RU.rc

[SNDVOL32] Add Russian translation

---

sdk/include/ndk/iotypes.h

On behalf of Vadim Galyant.
JIRA issue: [CORE-15769](https://jira.reactos.org/browse/CORE-15769)

CORE-15769. [NDK] Fix 'DeletedChidren' typo

---

dll/appcompat/apphelp/apphelp.c
dll/appcompat/apphelp/apphelp.h
dll/appcompat/apphelp/apphelp.spec
dll/appcompat/apphelp/layer.c
dll/appcompat/apphelp/sdbapi.c
dll/win32/kernel32/client/appcache.c
modules/rostests/apitests/apphelp/CMakeLists.txt
modules/rostests/apitests/apphelp/db.cpp
modules/rostests/apitests/apphelp/register.cpp
modules/rostests/apitests/apphelp/testlist.c
ntoskrnl/ps/apphelp.c
sdk/include/reactos/appcompat/sdbtypes.h
sdk/include/xdk/ntbasedef.h

JIRA issue: [CORE-11301](https://jira.reactos.org/browse/CORE-11301)

Initial work to allow compatibility databases to be installed

---

drivers/wdm/audio/hdaudbus/fdo.cpp
drivers/wdm/audio/hdaudbus/hdaudbus.cpp
drivers/wdm/audio/hdaudbus/hdaudbus.h
drivers/wdm/audio/hdaudbus/pdo.cpp

Review with "ignore whitespace"!
This implements device removal / driver unload and satisfies Driver Verifier.
Should fix [CORE-14617](https://jira.reactos.org/browse/CORE-14617) (and probably other issues).

HDAudBus PnP fixes

---

base/applications/drwtsn32/sysinfo.cpp

[DRWTSN32] Print some extra exception info

---

dll/win32/comdlg32/lang/cdlg_Hi.rc
dll/win32/comdlg32/rsrc.rc

Hindi translation of comdlg32.
- Added cdlg_Hi.rc
- Defined cdlg_Hi.rc in rsrc.rc

Hindi translation of comdlg32.

---

dll/win32/samsrv/lang/hi-IN.rc
dll/win32/samsrv/samsrv.rc
dll/win32/syssetup/lang/hi-IN.rc
dll/win32/syssetup/syssetup.rc

Adding Hindi translation of sysetup and samsrv.
- Added hi-IN.rc on the lang folders of both,
- Defined it on the resource file.

[TRANSLATION] Hindi translation of SYSSETUP and SAMSRV.

---

base/applications/shutdown/lang/it-IT.rc

[SHUTDOWN] Better Italian translation.
Better Italian translation.
I want to enhance the Italian translation.

[SHUTDOWN] Small Italian translation update

---

base/shell/explorer/lang/ru-RU.rc

Update Russian translation for Show the Desktop action in explorer.
JIRA issue: [CORE-15506](https://jira.reactos.org/browse/CORE-15506)
- Translate "Show Open Windows" menu item into Russian.
Before:
After:

[EXPLORER] Show the Desktop Russian translation update

---

drivers/storage/ide/uniata/atacmd_map.h
drivers/storage/ide/uniata/atapi.h
drivers/storage/ide/uniata/bm_devs.h
drivers/storage/ide/uniata/bsmaster.h
drivers/storage/ide/uniata/config.h
drivers/storage/ide/uniata/id_ata.cpp
drivers/storage/ide/uniata/id_dma.cpp
drivers/storage/ide/uniata/id_init.cpp
drivers/storage/ide/uniata/id_probe.cpp
drivers/storage/ide/uniata/id_sata.cpp
drivers/storage/ide/uniata/ntddk_ex.h
drivers/storage/ide/uniata/uniata_ver.h

JIRA issue: [CORE-15843](https://jira.reactos.org/browse/CORE-15843)

Update UniATA to 46e8.

---

README.md

This layout is much better and confortable for eyes +add chat link

This layout is much better and confortable for eyes +add chat link

---

dll/cpl/sysdm/smbios.c

I updated my SMBIOS parsing code.
Amount of tested data increased from 4183 to **9871** unique SMBIOS dumps, no regressions found so far in the parser output.
(Warning!) Big data here: https://docs.google.com/spreadsheets/d/17psq53hoEtZmgdtdnkBNjOXe6KNXYVwRdWiWdSSQfgg/edit#gid=0

[SYSDM] Update SMBIOS parsing code

---

sdk/tools/log2lines/log2lines.c

[LOG2LINES] Add a TODO, Use a snprintf()

---

base/applications/sndvol32/lang/it-IT.rc

[SNDVOL32] Better Italian translation.
Better Italian translation.
I want to enhance the Italian translation.

[SNDVOL32] Small Italian translation update

---

base/applications/winver/CMakeLists.txt
base/applications/winver/winver.c
base/applications/winver/winver.rc

Fix winver theming

---

dll/win32/comctl32/button.c
win32ss/user/user32/controls/button.c
win32ss/user/user32/windows/dialog.c

Fix the radio button focus problem by importing Wine commits.
JIRA issue: [CORE-8526](https://jira.reactos.org/browse/CORE-8526)
Testbot results: https://www.reactos.org/testman/compare.php?ids=66597,66598

Winesync button & dialog

---

base/applications/osk/main.c
base/applications/osk/osk.h

The commit message explains it all.

[OSK] Initialize the common controls

---

configure.cmd

This simplifies the Visual Studio generator selection logic and adds support for Visual Studio 16.0 (aka 2019).

[CONFIGURE] Add VS 16.0 support, simplify generator selection

---

win32ss/printing/base/spoolss/main.c

Free the module when done. This PR should fix Coverity issue of 1401149 ID.

[COVERITY][SPOOLSS] Fix a resource leak

---

drivers/filesystems/udfs/Include/Sys_spec_lib.cpp
drivers/filesystems/udfs/Include/phys_lib.cpp
drivers/filesystems/udfs/Include/phys_lib.h
drivers/filesystems/udfs/Include/wcache_lib.cpp
drivers/filesystems/udfs/Include/wcache_lib.h
drivers/filesystems/udfs/close.cpp
drivers/filesystems/udfs/create.cpp
drivers/filesystems/udfs/env_spec.cpp
drivers/filesystems/udfs/env_spec.h
drivers/filesystems/udfs/fastio.cpp
drivers/filesystems/udfs/fileinfo.cpp
drivers/filesystems/udfs/fscntrl.cpp
drivers/filesystems/udfs/protos.h
drivers/filesystems/udfs/read.cpp
drivers/filesystems/udfs/udf_info/alloc.cpp
drivers/filesystems/udfs/udf_info/dirtree.cpp
drivers/filesystems/udfs/udf_info/extent.cpp
drivers/filesystems/udfs/udf_info/mount.cpp
drivers/filesystems/udfs/udf_info/remap.cpp
drivers/filesystems/udfs/udf_info/udf_info.cpp
drivers/filesystems/udfs/udf_info/udf_info.h
drivers/filesystems/udfs/udf_info/udf_rel.h
drivers/filesystems/udfs/write.cpp

[UDFS] Fix 64 bit issues

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-15907](https://jira.reactos.org/browse/CORE-15907)
Fix wrong text bounding box height when the viewport is set.

[WIN32SS][FONT] Fix font bounding box mapping for viewport CORE-15907

---

modules/rostests/apitests/gdi32/GetRandomRgn.c
modules/rostests/apitests/gdi32/GetTextExtentExPoint.c
modules/rostests/apitests/gdi32/GetTextFace.c
modules/rostests/apitests/gdi32/SetMapMode.c
modules/rostests/apitests/gdi32/SetWindowExtEx.c

- Use `ok_int`, `ok_long` and `ok_err` macros instead of obsolete `TEST` macros.

[ROSTESTS][GDI32_APITEST] Refactor testcases

---

modules/rostests/apitests/gdi32/SetWindowExtEx.c

[ROSTESTS][GDI32_APITEST] Follow up of #1457

---

modules/rostests/apitests/gdi32/DPtoLP.c

JIRA-issue: [ROSTESTS-319](https://jira.reactos.org/browse/ROSTESTS-319)
Improve the `GDI32_APITEST` `DPtoLP` testcase.

[GDI32_APITEST] Improve DPtoLP testcase

---

dll/cpl/timedate/timezone.c
dll/win32/syssetup/syssetup.rc
dll/win32/syssetup/wizard.c
sdk/include/reactos/libs/syssetup/syssetup.h

[SYSSETUP] Add a missing break
[SYSSETUP] Ask for common controls v6 when using v6 features

Small syssetup fixes

---

modules/rostests/apitests/gdi32/DPtoLP.c

Follow up of #1459.
JIRA issue: [ROSTESTS-319](https://jira.reactos.org/browse/ROSTESTS-319)

[ROSTESTS][GDI32_APITEST] Follow up of #1459

---

modules/rostests/apitests/gdi32/CMakeLists.txt
modules/rostests/apitests/gdi32/LPtoDP.c
modules/rostests/apitests/gdi32/testlist.c

Add a testcase for `gdi32!LPtoDP` function.
JIRA issue: [ROSTESTS-320](https://jira.reactos.org/browse/ROSTESTS-320)

[GDI32_APITEST] Add LPtoDP testcase

---

boot/bootdata/hivesys.inf

This PR will add registry info about Japanese calendar.

[BOOTDATA] Japanese calendar-related registry info

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CFSFolder.h
sdk/include/reactos/undocshell.h

Implement the background image feature of Explorer. This PR is retrial of #801.
JIRA issue: [CORE-5516](https://jira.reactos.org/browse/CORE-5516)

[SHELL32] Implement Explorer background image (Retrial of #801)

---

modules/rostests/apitests/kernel32/CMakeLists.txt
modules/rostests/apitests/kernel32/JapaneseCalendar.c
modules/rostests/apitests/kernel32/testlist.c

Add Japanese calendar-related tests.

[KERNEL32_APITEST] Japanese calendar testcase

---

dll/win32/shimgvw/shimgvw.c

Fix the cursor of `shimgvw.dll`.
JIRA issue: [CORE-15219](https://jira.reactos.org/browse/CORE-15219)

[SHIMGVW] Fix cursor

---

sdk/lib/atl/atlcore.h

Today is the Independence Day of ReactOS ATL (RATL).
JIRA issue: [CORE-12935](https://jira.reactos.org/browse/CORE-12935)
https://github.com/katahiromz/RATL

[SDK][ATL] Independence Day of ReactOS ATL

---

boot/bootdata/bootcdregtest/AHKAppTests.cmd

```bat
dbgprint "AHK Application testing suite not present, skipping."
+    dbgprint "Insert ReactOS CD and try again."
exit /b 0
```

[BOOTDATA] Improve error message of AHKAppTests.cmd

---

dll/win32/kernel32/CMakeLists.txt
dll/win32/kernel32/winnls/string/japanese.c
dll/win32/kernel32/winnls/string/japanese.h
dll/win32/kernel32/winnls/string/lang.c
dll/win32/kernel32/winnls/string/lcformat.c

Implement the Japanese calendar in `kernel32`.

[KERNEL32] Support Japanese calendar

---

base/applications/rapps/lang/ru-RU.rc
dll/win32/syssetup/lang/ru-RU.rc

[SYSSETUP][RAPPS] Update Russian translation

---

media/themes/modern.msstyles/CMakeLists.txt

Cmake file fixup for Modern theme, addendum to 00ff951.
JIRA issue: [CORE-13020](https://jira.reactos.org/browse/CORE-13020)

[THEMES][CMAKE] Cmake file fixup for Modern theme

---

appveyor.yml

If any errors in building a commit, finish the job for the error commit quickly.

[APPVEYOR] Enable fast_finish

---

boot/bootdata/hivedef.inf
boot/bootdata/livecd.inf

Add registry keys for `ComDlg32`.
JIRA issue: [CORE-7114](https://jira.reactos.org/browse/CORE-7114)

[BOOTDATA] Add registry keys for ComDlg32

---

sdk/include/psdk/lmrepl.h

Added public domain header. This file was originally imported in r8283 from w32api where is has no copyright.

[PSDK] Improve lmrepl.h

---

appveyor.yml

Addendum to 48f98e88edc26688a3bac5f5b7525cd90494f572.

[FORMATTING] appveyor.yml: Remove an extra space

---

modules/rostests/apitests/win32nt/CMakeLists.txt
modules/rostests/apitests/win32nt/ntgdi/NtGdiTransformPoints.c
modules/rostests/apitests/win32nt/testlist.c
modules/rostests/apitests/win32u/win32u_2k3sp2/CMakeLists.txt
modules/rostests/apitests/win32u/win32u_2ksp4/CMakeLists.txt
modules/rostests/apitests/win32u/win32u_ros/CMakeLists.txt
modules/rostests/apitests/win32u/win32u_vista/CMakeLists.txt
modules/rostests/apitests/win32u/win32u_xpsp2/CMakeLists.txt

Add a testcase for `NtGdiTransformPoints` function.
JIRA issue: [CORE-15983](https://jira.reactos.org/browse/CORE-15983)
- `set_module_type(win32u... win32dll)`

[APITESTS] Add NtGdiTransformPoints testcase

---

base/applications/osk/main.c

A hotfix for #1536. Before that, the application was drawn not just with the current working theme but as well keeping the classic style control buttons.

[OSK] Hotfix for #1536 PR

---

modules/rostests/apitests/appshim/genral_hooks.c
modules/rostests/apitests/appshim/layer_hooks.c
modules/rostests/apitests/appshim/versionlie.c

[APPSHIM_APITEST] Fix 2k3 test failures

---

sdk/include/psdk/ntddndis.h

Fill in the rest of the NDIS definitions (and others that I came across) needed for netkvm, I've done my best to keep the structure right on everything, 
[CORE-15841]( https://jira.reactos.org/browse/CORE-15841)

[DDK][PSDK] Added the rest of the defines for netkvm

---

modules/rostests/apitests/gdi32/TextTransform.c

[GDI32_APITEST] Strengthen TextTransform testcase

---

win32ss/gdi/ntgdi/font.h
win32ss/gdi/ntgdi/freetype.c

- Reduce `gdi32_apitest!TextTransform` failures.
- Optimize for speed.
- Add `Width` and `Escapement` parameters to `FONT_CACHE_ENTRY` structure.
BEFORE:
AFTER:
Bingo!

[WIN32SS][NTGDI] Improve Text Transformation

---

modules/rostests/apitests/gdi32/GetGlyphIndices.c

Strengthen the testcase for `gdi32!GetGlyphIndicesW`.
JIRA issue: [CORE-12825](https://jira.reactos.org/browse/CORE-12825)

[GDI32_APITEST] Improve GetGlyphIndices testcase

---

modules/rostests/apitests/kernel32/SetComputerNameExW.c

JIRA issue: [ROSTESTS-322](https://jira.reactos.org/browse/ROSTESTS-322)
Also test `NV Hostname` registry value in the testcase of `kernel32!SetComputerNameW`.

[KERNEL32_APITEST] Check 'NV Hostname' in SetComputerNameExW testcase

---

win32ss/gdi/ntgdi/freetype.c

Don't use `FLOAT` variable in `ftGdiGetGlyphOutline` function.
JIRA issue: [CORE-15838](https://jira.reactos.org/browse/CORE-15838)

[WIN32SS][NTGDI] Don't use FLOAT in ftGdiGetGlyphOutline

---

dll/win32/syssetup/wizard.c

Based on @Doug-Lyons's patch.
JIRA issue: [CORE-16067](https://jira.reactos.org/browse/CORE-16067)

[SYSSETUP] Set registry hostname in WriteComputerSettings

---

win32ss/user/user32/controls/appswitch.c

Task Switcher didn't correctly behave on the windows with `WS_EX_APPWINDOW` extended style.
JIRA issue: [CORE-15653](https://jira.reactos.org/browse/CORE-15653)

[USER32] Fix behavior of Task Switcher (Alt+Tab)

---

win32ss/user/user32/controls/appswitch.c

This PR will fix task switcher (Alt+Tab) as Win2k3. It became more reliable.
JIRA issue: [CORE-15653](https://jira.reactos.org/browse/CORE-15653)

[WIN32SS][USER32] Fix Task Switcher more

---

modules/rostests/apitests/user32/WndProc.c

This PR is only improving current code.
It does not target the main issue.
JIRA issue: [ROSTESTS-316](https://jira.reactos.org/browse/ROSTESTS-316)
WTB result: [Job 42474](https://testbot.winehq.org/JobDetails.pl?Key=42474)

ROSTESTS-316. Improve WndProc ApiTest

---

modules/rostests/apitests/win32nt/ntdd/NtGdiDdCreateDirectDrawObject.c
modules/rostests/apitests/win32nt/ntdd/NtGdiDdDeleteDirectDrawObject.c
modules/rostests/apitests/win32nt/ntdd/NtGdiDdQueryDirectDrawObject.c

This PR is only improving current code.
It does not target the main issue.
JIRA issue: [ROSTESTS-315](https://jira.reactos.org/browse/ROSTESTS-315)
WTB results: [Job 42362](https://testbot.winehq.org/JobDetails.pl?Key=42362) and [Job 42363](https://testbot.winehq.org/JobDetails.pl?Key=42363)

ROSTESTS-315. Improve NtGdiDd ApiTests

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiRestoreDC.c
modules/rostests/apitests/win32nt/ntuser/NtUserGetIconInfo.c
modules/rostests/apitests/win32nt/ntuser/NtUserSystemParametersInfo.c
modules/rostests/apitests/win32nt/win32nt.h

Addendum to b7794e8112e31a58829bac63d44de53677318c3d.
Cc @katahiromz

[WIN32KNT_APITEST] Replace remaining TESTX()

---

win32ss/printing/providers/localspl/printers.c

Addendum to [r74433](https://git.reactos.org/?p=reactos.git;a=commit;h=30d5e8f413f4da2a7d37fe6b66fe2f94104b3d8f).

[LOCALSPL] Check DBG with #if, not #ifdef

---

README.md

Warnings to encourage people to test ReactOS in VMS until it becomes more stable.

Added a Alpha note for new users to the readme

---

dll/win32/shell32/lang/uk-UA.rc

Hope everthing is ok because I edited it right in browser

[SHELL32] Update Ukrainian translation

---

base/shell/explorer/lang/uk-UA.rc

Hope everthing is ok because I edited it right in browser

[EXPLORER] Update Ukrainian translation

---

dll/win32/newdev/lang/uk-UA.rc

Hope everthing is ok because I edited it right in browser

[NEWDEV] Update Ukrainian translation

---

dll/win32/browseui/lang/uk-UA.rc

Hope everthing is ok because I edited it right in browser

[BROWSEUI] Update Ukrainian translation

---

dll/win32/browseui/shellbars/CSHEnumClassesOfCategories.cpp

Addendum to fdfef818ef5dcb4d0132da8fe4e91eb00415db24.
JIRA issue: [CORE-11711](https://jira.reactos.org/browse/CORE-11711)
Cc @HBelusca

[BROWSEUI] Fix SHEnumClassesOfCategories() parameter validation. CORE-11711

---

dll/win32/lpk/lpk.c

Fix for JIRA issue: [CORE-16115](https://jira.reactos.org/browse/CORE-16115)
Use the total extent (width) and font metrics (height) as values to put in the lpSize variable instead of calling ScriptString_pSize in the LpkGetTextExtentExPoint function.
This is unrelated to #1651.

[LPK] Fix for CORE-16115

---

base/applications/magnify/magnifier.c

Fix a division by zero exception.
BEFORE:
<a href="http://it.tinypic.com?ref=258mcz6" target="_blank"><img src="http://i64.tinypic.com/258mcz6.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
AFTER:
<a href="http://it.tinypic.com?ref=9hrng5" target="_blank"><img src="http://i64.tinypic.com/9hrng5.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

[MAGNIFY] Fix a division by zero exception

---

modules/rostests/apitests/ws2_32/CMakeLists.txt
modules/rostests/apitests/ws2_32/gethostname.c
modules/rostests/apitests/ws2_32/testlist.c

Add "gethostname" test option to ws2_32_apitest.
JIRA issue: [ROSTESTS-326](https://jira.reactos.org/browse/ROSTESTS-326)

Add ws2_32_apitest gethostname option.

---

drivers/input/i8042prt/hwhacks.c

Now mouse works out of the box on this laptop, please note there's been a regression on the system so it no longer boot without reverting to older drivers, I'm going to find the guilty commit though
edit: Well there's an extra 4 in the commit name

[i8042prt] Add Latitude E6400 to the hack list

---

dll/cpl/input/settings_page.c

JIRA issue: [CORE-16121](https://jira.reactos.org/browse/CORE-16121)

[INPUT] Don't race the system to free an imagelist

---

dll/win32/urlmon/axinstall.c

JIRA issue: [CORE-15795](https://jira.reactos.org/browse/CORE-15795)

[URLMON] Directly call cabinet!Extract instead of calling it via advpack!ExtractFilesW

---

dll/cpl/main/lang/fr-FR.rc

**JIRA Issue:** [CORE-12372](https://jira.reactos.org/browse/CORE-12372)

[CPL][MAIN] Adjust the GROUPBOX control spacing for French resource

---

dll/win32/netcfgx/lang/pt-PT.rc
dll/win32/netcfgx/netcfgx.rc
dll/win32/netid/lang/pt-PT.rc
dll/win32/netid/netid.rc
dll/win32/newdev/lang/pt-PT.rc
dll/win32/newdev/newdev.rc

Portuguese translation to WIN32 module
netcfg, netid and newdev

Portuguese translation to WIN32 module

---

drivers/filesystems/fastfat/misc.c
drivers/filters/fltmgr/Interface.c
drivers/filters/fltmgr/Messaging.c
ntoskrnl/fsrtl/oplock.c
ntoskrnl/io/iomgr/rawfs.c
ntoskrnl/ob/devicemap.c
ntoskrnl/po/poshtdwn.c
ntoskrnl/ps/job.c
ntoskrnl/wmi/guidobj.c

**JIRA Issue:** [CORE-16081](https://jira.reactos.org/browse/CORE-16081)

Do not explicitly call ObfDereferenceObject()

---

sdk/lib/inflib/infcore.c
sdk/lib/inflib/infget.c
sdk/lib/inflib/infpriv.h
sdk/lib/inflib/infput.c

This makes inflib work on x64 and usetup crash later.

[INFLIB] Fix INFCONTEXT structure to be compatible with the official definition

---

win32ss/gdi/ntgdi/xformobj.c

Check if the determinant of the given transformation matrix is non-zero. If zero, the function returns `DDI_ERROR` without change.

[WIN32SS][NTGDI] Strictly check in XFORMOBJ_iSetXform

---

modules/rostests/apitests/gdi32/SetWorldTransform.c

Improve the test to check different types of invalid transformations and rounding errors.

[GDI32_APITEST] Improve test for SetWorldTransform

---

sdk/cmake/CMakeMacros.cmake
sdk/include/psdk/sal.h

The code is released by MS under the MIT license.
See https://github.com/microsoft/service-fabric/blob/master/src/prod/src/pal/src/internal/rt/sal.h
This allows to do static analysis with MSVC again.

Add sal.h from Microsoft GitHub repository

---

drivers/filesystems/fastfat/cleanup.c

[FASTFAT] Fix use after free when volume is unmounted

---

boot/bootdata/hivesys.inf
modules/rostests/kmtests/include/kmt_platform.h
modules/rostests/kmtests/ntos_ob/ObSecurity.c
ntoskrnl/include/internal/ob.h
ntoskrnl/ob/obdir.c
ntoskrnl/ob/obname.c
sdk/include/ndk/psfuncs.h
sdk/include/ndk/rtlfuncs.h
sdk/include/xdk/zwfuncs.h
subsystems/win/basesrv/basesrv.h
subsystems/win/basesrv/dosdev.c
subsystems/win/basesrv/init.c

This implements support for device maps in objects lookup in Ob
JIRA issue: [CORE-16114](https://jira.reactos.org/browse/CORE-16114)

[NTOSKRNL] Implement support for device maps in ObpLookupObjectName

---

dll/win32/shell32/lang/ru-RU.rc
dll/win32/userenv/lang/ru-RU.rc

Improve Russian translation (fixes [CORE-16170](https://jira.reactos.org/browse/CORE-16170))

[SHELL32][USERENV] Improve Russian translation

---

drivers/filesystems/fastfat_new/cachesup.c
drivers/filesystems/fastfat_new/create.c
drivers/filesystems/fastfat_new/dirsup.c
drivers/filesystems/fastfat_new/fatdata.c
drivers/filesystems/fastfat_new/fatinit.c
drivers/filesystems/fastfat_new/fatstruc.h
drivers/filesystems/fastfat_new/fileinfo.c

JIRA issue: [CORE-14879](https://jira.reactos.org/browse/CORE-14879)

[FASTFAT_NEW] Fix MsVC builds

---

modules/rostests/apitests/gdi32/SetWorldTransform.c

Improve the testcase for `gdi32!SetWorldTransform` function.

[GDI32_APITEST] Improve SetWorldTransform testcase

---

sdk/lib/crt/startup/tlsmthread.c
sdk/lib/crt/startup/tlssup.c

JIRA issue: [CORE-15491](https://jira.reactos.org/browse/CORE-15491)

[CRT] Remove mingwm10.dll usage in tls support code

---

win32ss/user/user32/controls/appswitch.c

This PR will fix app switcher (Alt+Tab)'s behavior when there is only one window.
JIRA issue: [CORE-16176](https://jira.reactos.org/browse/CORE-16176)

[USER32] Switch to only one window (Alt+Tab)

---

dll/win32/shell32/dialogs/recycler_prop.cpp

The fix is based on #1688.
**JIRA Issue:** [CORE-12312](https://jira.reactos.org/browse/CORE-12312)

[SHELL32] Enable the "Apply" button on text box change

---

sdk/include/psdk/winuser.h

- Add `WM_INPUT_DEVICE_CHANGE` and `WM_INPUT` messages.
- Add the relevant constant values.

[SDK][INCLUDE] Add WM_INPUT_DEVICE_CHANGE and WM_INPUT

---

boot/freeldr/freeldr/arch/i386/hwdisk.c

This fixes infinite loop when booting FreeLoader on Xbox / XQEMU.
JIRA issue: [CORE-16205](https://jira.reactos.org/browse/CORE-16205)

[FREELDR] hwdisk: Add sanity checks to avoid infinite loop

---

base/applications/osk/main.c

[CORE-16214](https://jira.reactos.org/browse/CORE-16214)

[OSK] Use new coordinates on keyboard layout changing

---

base/setup/reactos/lang/he-IL.rc

I have Fixed some of the Translations and Added some new ones.

[TRANSLATION] Hebrew Translations For Setup

---

CODEOWNERS

Follow-up to #1517 comments.
Cc @ThFabba

[CODEOWNERS] Add UniATA

---

drivers/bus/acpi/cmbatt/cmbatt.c
sdk/lib/drivers/sound/shared/time.c
subsystems/win/basesrv/dosdev.c
win32ss/drivers/font/bmfd/bmfd.h
win32ss/drivers/font/bmfd/glyph.c
win32ss/user/ntuser/menu.c

Fix warning C4146: unary minus operator applied to unsigned type, result still unsigned

[REACTOS] Fix warning unary minus operator warnings

---

boot/freeldr/freeldr/arch/i386/xboxdisk.c
boot/freeldr/freeldr/disk/disk.c

Trivial improvements, fixes uninitialized string, adds a comment, and improves code style.
JIRA issue: [CORE-16248](https://jira.reactos.org/browse/CORE-16248)

[FREELDR] Trivial improvements

---

dll/keyboard/kbdhu/kbdhu.c

Fix Hungarian keyboard layout, as it is completely wrong now.
JIRA issue: [CORE-15567](https://jira.reactos.org/browse/CORE-15567)

[KBDHU] Fix Hungarian keyboard layout.

---

dll/win32/kernel32/client/proc.c
dll/win32/kernel32/client/thread.c

Add some cleanup code in CreateRemoteThread().
JIRA issue: None!

[KERNEL32] Add some cleanup code in CreateRemoteThread().

---

win32ss/user/ntuser/menu.c

JIRA issue: [CORE-15863](https://jira.reactos.org/browse/CORE-15863)

Implement (popup) menu excluding the specified rectangle

---

boot/freeldr/freeldr/bootmgr.c
boot/freeldr/freeldr/custom.c
boot/freeldr/freeldr/include/custom.h
boot/freeldr/freeldr/include/freeldr.h
boot/freeldr/freeldr/include/options.h
boot/freeldr/freeldr/include/ui.h
boot/freeldr/freeldr/include/ui/gui.h
boot/freeldr/freeldr/include/ui/noui.h
boot/freeldr/freeldr/include/ui/tui.h
boot/freeldr/freeldr/options.c
boot/freeldr/freeldr/ui/directui.c
boot/freeldr/freeldr/ui/minitui.c
boot/freeldr/freeldr/ui/noui.c
boot/freeldr/freeldr/ui/tui.c
boot/freeldr/freeldr/ui/tuimenu.c
boot/freeldr/freeldr/ui/ui.c

- Add "Edit Boot Command Line" feature
JIRA issue: [CORE-16260](https://jira.reactos.org/browse/CORE-16260)
Video: [(click)](https://youtu.be/Gz7ykY0Go2Y)
[![Безымянный](https://user-images.githubusercontent.com/25367511/62010658-4e559680-b176-11e9-94df-d3f8cde0eab2.png)](https://youtu.be/Gz7ykY0Go2Y)
- Add ReactOS Setup as a custom boot type

[FREELDR] New features

---

win32ss/user/ntuser/menu.c

JIRA issue: [CORE-15863](https://jira.reactos.org/browse/CORE-15863)

[WIN32SS] Fix the last remaining menu regressions

---

modules/rostests/apitests/atl/CAtlArray.cpp
modules/rostests/apitests/atl/CAtlFileMapping.cpp
modules/rostests/apitests/atl/CAtlList.cpp
modules/rostests/apitests/atl/CComObject.cpp
modules/rostests/apitests/atl/CComQIPtr.cpp
modules/rostests/apitests/atl/CImage.cpp
modules/rostests/apitests/atl/CSimpleArray.cpp
modules/rostests/apitests/atl/CSimpleMap.cpp
modules/rostests/apitests/atl/CString.cpp
modules/rostests/apitests/atl/atltest.h

- Add `"atltest.h"` header file for common use in `atl_apitest`.
- Delete the duplicated and simplify.

[ATL_APITEST] Add 'atltest.h' and use it

---

modules/rostests/apitests/atl/CAtlArray.cpp
modules/rostests/apitests/atl/CAtlList.cpp
modules/rostests/apitests/atl/CComQIPtr.cpp
modules/rostests/apitests/atl/CSimpleArray.cpp
modules/rostests/apitests/atl/CSimpleMap.cpp

Simplify the code by using `ok_int`, `ok_long` etc.

[ATL_APITEST] Simplify code by using ok_int etc.

---

modules/rostests/apitests/wininet/CMakeLists.txt
modules/rostests/apitests/wininet/Download.c
modules/rostests/apitests/wininet/Redirection.c
modules/rostests/apitests/wininet/testlist.c

JIRA issue: [CORE-16310](https://jira.reactos.org/browse/CORE-16310)

[WININET_APITEST] Add Download testcase

---

base/applications/atactl/atactl.cpp
base/applications/calc/winmain.c
base/applications/msconfig/startuppage.c
base/applications/msconfig_new/fileutils.c
base/applications/msconfig_new/utils.c
base/applications/msconfig_new/utils.h
base/applications/mscutils/eventvwr/eventvwr.c
base/applications/mstsc/connectdialog.c
base/applications/mstsc/settings.c
base/services/dhcpcsvc/dhcp/adapter.c
base/services/dhcpcsvc/dhcp/socket.c
base/setup/lib/utils/arcname.c
dll/ntdll/csr/connect.c
dll/ntdll/ldr/ldrinit.c
dll/ntdll/ldr/ldrutils.c
dll/ntdll/rtl/version.c
ntoskrnl/mm/pagefile.c
sdk/include/reactos/shellutils.h
sdk/lib/rtl/network.c
sdk/lib/rtl/path.c
win32ss/drivers/videoprt/videoprt.c

[REACTOS] Fix SIZE_T related warnings

---

modules/rostests/apitests/dbghelp/data.c
modules/rostests/apitests/dbghelp/pdb.c
modules/rostests/apitests/dbghelp/rsym.c

Also reorder some stuff to make the tests more alike

[DBGHELP_APITEST] Add rsym+pdb tests on loaded modules

---

dll/win32/jscript/CMakeLists.txt
dll/win32/jscript/enumerator.c
dll/win32/jscript/global.c
dll/win32/jscript/jscript.h
dll/win32/jscript/object.c
dll/win32/jscript/resource.h

https://source.winehq.org/git/wine.git/commit/6630bc4096870d1586e6d431b93dd74eb7ce017d
https://source.winehq.org/git/wine.git/commit/a015c626438dc8cba445242c68d4175f381b2128
JIRA issue: [CORE-13810](https://jira.reactos.org/browse/CORE-13810)

[JSCRIPT] import wine commits "stub + implement Enumerator()"

---

drivers/usb/usbohci_new/usbohci.c

Refactor OHCI_AbortTransfer function so @Extravert-ir can read the code with less pain. :wink:
- Added SAL annotation
- Simplified local variables
- Replace counterintuitive `do {} while ()` loops with nice `for` loops
- Get rid of goto and its label, it can be simply avoided

[USBOHCI_NEW] Refactor OHCI_AbortTransfer function

---

dll/win32/newdev/lang/he-IL.rc

Completed the Hebrew translations for the Whole NEWDEV Prompt. Glad i won't be needing to do strings for it in the future.
Next PR i'll work on cpl/hdwwiz
the String Height change was done so the long string could fit:

[TRANSLATION][NEWDEV] Complete Hebrew Translations for New Device Prompt

---

sdk/tools/rsym/rsym.c

Fixes backtraces showing LsaRegisterLogonProcess for what is really RtlpBreakWithStatusInstruction.
Symbol dump for comparison.
Old:
```
Sym: 00155D31 sdk/lib/lsalib/lsa.c:343 (LsaRegisterLogonProcess)
Sym: 00155D39 sdk/lib/lsalib/lsa.c:266 (LsaRegisterLogonProcess)
Sym: 00155D3E sdk/lib/lsalib/lsa.c:344 (LsaRegisterLogonProcess)
Sym: 00155D4A sdk/lib/lsalib/lsa.c:344 (LsaRegisterLogonProcess)
Sym: 00155D4C sdk/lib/rtl/i386/debug_asm.S:20 (LsaRegisterLogonProcess)
Sym: 00155D4D sdk/lib/rtl/i386/debug_asm.S:21 (DbgBreakPointNoBugCheck)
Sym: 00155D4E sdk/lib/rtl/i386/debug_asm.S:33 (LsaRegisterLogonProcess)
Sym: 00155D4E :0 (DbgBreakPoint)
Sym: 00155D4E :0 (DbgUserBreakPoint)
Sym: 00155D4F sdk/lib/rtl/i386/debug_asm.S:34 (LsaRegisterLogonProcess)
Sym: 00155D50 …
```

[RSYM] When determining the current function, prefer COFF symbols if they're closer.

---

hal/halx86/legacy/bus/pcibus.c

Yeah it really needs it :sweat_smile:

[HAL] Xbox needs more PCI blacklisting!

---

dll/shellext/stobject/hotplug.cpp
dll/shellext/stobject/volume.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CRegFolder.cpp

Addendum to 944aba1fcce206af0e1d35187a0df12571dc318b.
JIRA issue: [CORE-16299](https://jira.reactos.org/browse/CORE-16299)

WIP. [SHELL32][STOBJECT] Enforce ShellExecuteW(..., file, parameters, ...)

---

dll/win32/dnsapi/dnsapi/query.c
modules/rostests/apitests/dnsapi/DnsQuery.c

JIRA issue: [CORE-11634](https://jira.reactos.org/browse/CORE-11634)

[DNSAPI][DNSAPI_APITEST] Fix DnsQuery_UTF8 function and add tests

---

dll/win32/comctl32/imagelist.c

JIRA issue: [CORE-16316](https://jira.reactos.org/browse/CORE-16316)
JIRA issue: [CORE-16275](https://jira.reactos.org/browse/CORE-16275)

[COMCTL32] imagelist: Invalidate the cookie of a destroyed imagelist

---

hal/halx86/legacy/bus/pcibus.c

- Use a separate function for detecting blacklisted PCI slots
- Blacklist PCI-to-PCI bridge to avoid stack overflow on real hardware Microsoft Xbox 1.3
JIRA issue: [CORE-16319](https://jira.reactos.org/browse/CORE-16319)

[HAL] Refactor PCI blacklisting for Xbox

---

dll/win32/iphlpapi/icmp.c

Follow-up to #537.
Ease sync.
Mark all our (new) differences.

[IPHLPAPI] icmp.c: Restore sync after Wine Staging 1.7.55

---

base/applications/cmdutils/timeout/timeout.c
boot/environ/app/rosload/rosload.c
boot/environ/lib/misc/util.c
boot/freeldr/bootsect/CMakeLists.txt
boot/freeldr/freeldr/ntldr/setupldr.c
dll/ntdll/def/ntdll.spec
dll/win32/framedyn/framedyn.spec
dll/win32/ntdll_vista/CMakeLists.txt
modules/rostests/apitests/crt/CMakeLists.txt
modules/rostests/apitests/crt/testlist.c
sdk/include/ndk/arm/ketypes.h
sdk/include/ndk/tests/CMakeLists.txt
sdk/include/xdk/ntbasedef.h
sdk/lib/runtmchk/rtcapi.c

This fixes configuring an arm build,
and some build errors

Some arm build fixes

---

media/doc/README.WINE

- [README.WINE] Remove obsolete 'reactos/'
- [README.WINE] Fix path to '.../winfile'
- [README.WINE] Add '.../winetests/iphlpapi'

[README.WINE] Remove obsolete 'reactos/'

---

dll/cpl/hdwwiz/lang/he-IL.rc
dll/win32/newdev/lang/he-IL.rc
dll/win32/shell32/lang/he-IL.rc

Updated Translation for NewDev (won't be touching Newdev again)
Translations for new hardware wizard 
And i changed Recycle bin from 'Trash' like in old ReactOS to Recycle bin.

[TRANSLATION]More Hebrew Translations

---

base/applications/utilman/lang/en-US.rc
base/applications/utilman/lang/fr-FR.rc
base/applications/utilman/lang/he-IL.rc
base/applications/utilman/lang/it-IT.rc
base/applications/utilman/lang/ro-RO.rc
base/applications/utilman/utilman.rc
media/inf/shortcuts.inf

-Translated UTILMAN To hebrew
-Fixed the Hebrew translation a bit in shortcut.inf
- Changed (C) to © cus why not.

[TRANSLATION][UTILMAN] Translations for UTILMAN and some other stuff

---

dll/cpl/openglcfg/general.c
dll/cpl/wined3dcfg/general.c

[CORE-16330](https://jira.reactos.org/browse/CORE-16330)

[CPL] Do not enable the "Apply" button unconditionally

---

win32ss/drivers/miniport/xboxvmp/xboxvmp.c
win32ss/drivers/miniport/xboxvmp/xboxvmp.h

- Fix code formatting
- Improve debugging prints

[XBOXVMP] Code style and debugging improvement

---

drivers/filters/mountmgr/symlink.c

Addendum to 77657c22c950dc1d5404df1cac7ce06e0cf8fa24.

[MOUNTMGR] Remove a leftover UNREFERENCED_PARAMETER()

---

sdk/tools/spec2def/spec2def.c

This is the first part of #1874 
I pulled this out, because it seems the other PR causes some issues on some tests.

Improve spec2def part 1

---

sdk/tools/spec2def/spec2def.c

- Improve error output
- Use const properly
- Refactor to avoid parsing multiple times
testman: https://reactos.org/testman/compare.php?ids=68921,68923,68925,68929,68931
new run: https://reactos.org/testman/compare.php?ids=69036,69038,69040

Improve spec2def

---

dll/cpl/openglcfg/general.c

[OPENGLCFG] Fix crash if no drivers

---

drivers/filters/mountmgr/device.c
drivers/filters/mountmgr/mountmgr.c

Same fix as bf6215c6019ad14352a9afcc7fc28095bebd2673 ;-)

[MOUNTMGR] HasDriveLetter(): Fix and simplify

---

dll/win32/browseui/lang/he-IL.rc
dll/win32/shell32/lang/he-IL.rc
media/inf/shortcuts.inf

Updated the Hebrew translations for BrowseUI including the new Search function. and Some other misc Changes.
@peterooch

[BROWSEUI][SHELL32][TRANSLATION] Major Translations to BROWSEUI And New Search function to Hebrew. and Some Other changes.

---

drivers/wdm/audio/hdaudbus/hdaudbus.h
drivers/wdm/audio/hdaudbus/pdo.cpp

JIRA issue: [CORE-13702](https://jira.reactos.org/browse/CORE-13702)

[HDAUDBUS] Build a device instance ID from Codec & node number

---

hal/halx86/legacy/bussupp.c

Fix more bugs in HalpDebugPciDumpBus.
- Don't match device id outside current vendor id list.
- Don't match subsystem id outside current device id list.
- Refactor some magic constants.
Addendum to 894635b.
```
00:01.3 Bridge [0680]: MediaQ Inc. MQ-200 [4d51:0200] (rev 03)
Subsystem: Unknown [0000:0000]
00:01.3 Bridge [0680]: MediaQ Inc. [mvHYPERION-CLe/CLb] CameraLink PCI Express x1 Frame Grabber [4d51:0000] (rev 03)
Subsystem: Unknown [0000:0000]
00:01.3 Bridge [0680]: MediaQ Inc. [mvHYPERION-CLe/CLb] CameraLink PCI Express x1 Frame Grabber [4d51:0000] (rev 03)
Subsystem: 86C775 Trio64V2/DX [5333:8900]
00:01.3 Bridge [0680]: S3 Graphics Ltd. 86c755 [Trio 64V2/DX] [5333:8900] (rev 03)
Subsystem: 86C775 Trio64V2/DX [5333:8900]
00:01.3 Bridge [0680]: S3 Graphics Ltd. 86c755 …
```

[HAL] Fix more bugs in HalpDebugPciDumpBus

---

drivers/usb/usbport/endpoint.c

Same fix as 085528c31ad8b91ae7af6dda9b9faa5c463ade70.

USBPORT_InvalidateEndpointHandler(): Properly enumerate endpoints

---

ntoskrnl/include/internal/i386/mm.h

Addendum to 65dbfc286818e18095b7cc0c85f63cde6b3e629d.

[NTOS:MM] _MI_HAS_NO_EXECUTE: Minor improvements

---

README.md

Update the release version and the release link on the readme pointing to 0.4.12.
Updated the release version and the release link on the readme from 0.4.11 to 0.4.12.

Updated release version and release link on readme

---

hal/halx86/CMakeLists.txt
hal/halx86/xbox.cmake
hal/halx86/xbox/halxbox.h
hal/halx86/xbox/reboot.c

[HALXBOX] Implement shutdown, reboot, and power cycle routines

---

boot/freeldr/freeldr/arch/i386/hwacpi.c
boot/freeldr/freeldr/lib/fs/btrfs.c
boot/freeldr/freeldr/lib/peloader.c
boot/freeldr/freeldr/ntldr/setupldr.c
boot/freeldr/freeldr/ntldr/winldr.c

A series of patches by @maharmstone for fixing Freeldr NTOS loading, that are also needed for loading Windows Vista; see PR #1905.

FreeLoader fixes towards Vista loading

---

drivers/filters/mountmgr/point.c

Addendum to a7f97cc70f62f6805e71b28eba51f52b942d22b4.

[MOUNTMGR] Properly look for device and break when found

---

win32ss/drivers/miniport/xboxvmp/CMakeLists.txt
win32ss/drivers/miniport/xboxvmp/xboxi2c.c
win32ss/drivers/miniport/xboxvmp/xboxvmp.c
win32ss/drivers/miniport/xboxvmp/xboxvmp.h

- Remove old hacky code based on `MmHighestPhysicalPage`
- Split I2C SMBus code into a separate source file
JIRA issue: [CORE-16357](https://jira.reactos.org/browse/CORE-16357)

[XBOXVMP] Fix broken pixels and general refactoring

---

base/shell/explorer/trayclock.cpp
base/shell/explorer/trayntfy.cpp

JIRA issue: [CORE-16397](https://jira.reactos.org/browse/CORE-16397)

[EXPLORER] Fix right-click menu for taskbar clock

---

dll/win32/msafd/misc/dllmain.c

Addendum to 6bc61f63f1e0ad20ab09f881d6968558eba9a8e6.
JIRA issue: [CORE-15804](https://jira.reactos.org/browse/CORE-15804)

[MSAFD] WSPSetSockOpt(): Fix a copypasta. CORE-15804

---

CODEOWNERS

- Add /drivers/filters/*/ entries.
- Also add Pierre's Jira username.

[CODEOWNERS] Add /drivers/filters/*/ entries

---

dll/win32/msafd/misc/dllmain.c

[MSAFD] SizeOf*Buffer: Type is ULONG, not INT/DWORD

---

boot/freeldr/freeldr/ui/minitui.c

Trivial fix. I also checked Tui, DirectUi, and others -- no such problem here. Cc @HBelusca

[FREELDR] MiniTui: Fix progress bar width on custom resolutions

---

base/setup/lib/utils/bldrsup.c
drivers/filesystems/reiserfs/src/memory.c
drivers/filesystems/udfs/Include/wcache_lib.cpp

Some CID Fixes. Any objections anyone?

Coverityfixes

---

boot/freeldr/freeldr/lib/fs/btrfs.c

We're still in real mode, where memory is at a premium, when we call BtrFsRead, and I was getting out of memory errors. This changes it so that we only allocate a temp buffer for the first 512-byte sector, and read normally from then on.

[FREELDR] Use less memory when doing unaligned reads on Btrfs

---

base/applications/cmdutils/eventcreate/eventcreate.rc
base/applications/cmdutils/eventcreate/lang/it-IT.rc

With this addition, all cmdutils are finally translated in italian.

[CMDUTILS] Add italian translation for eventcreate.

---

base/applications/notepad/text.c

JIRA issue: [CORE-16467](https://jira.reactos.org/browse/CORE-16467)

[NOTEPAD] Prioritize CP_ACP over CP_UTF8

---

win32ss/user/ntuser/draw.c
win32ss/user/user32/windows/draw.c

JIRA issue: [CORE-16470](https://jira.reactos.org/browse/CORE-16470)
- Don't change background mode.

[WIN32SS][NTUSER][USER32] Fix menu checkmarks

---

base/setup/usetup/lang/hu-HU.h

Fix some grammatical mistakes I made.

[USETUP] Hungarian translation fix

---

dll/shellext/fontext/CFontCache.cpp
dll/shellext/fontext/CFontExt.cpp
dll/shellext/fontext/CFontExt.hpp
dll/shellext/fontext/CFontMenu.cpp
dll/shellext/fontext/CMakeLists.txt
dll/shellext/fontext/precomp.h

JIRA issue: [CORE-12861](https://jira.reactos.org/browse/CORE-12861)

[SHELLEXT][FONTEXT] An attempt to implement IDropTarget

---

sdk/lib/drivers/rdbsslib/rdbss.c

Author = Victor Martinez.
JIRA issue: [CORE-13383](https://jira.reactos.org/browse/CORE-13383)

[RDBSSLIB] RxFirstCanonicalize(): Fix pointer arithmetic. CORE-13383

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHLimitInputEdit.cpp
modules/rostests/apitests/shell32/resource.rc
modules/rostests/apitests/shell32/testlist.c
sdk/include/psdk/shobjidl.idl

JIRA issue: [CORE-11701](https://jira.reactos.org/browse/CORE-11701)
- Add `IItemNameLimits` interface into `shobjidl.idl`.
- Add a testcase for `shell32!SHLimitInputEdit` function.

[INCLUDE][SHELL32_APITEST] Add SHLimitInputEdit testcase

---

base/applications/osk/main.c
base/applications/osk/precomp.h

The commit message description explains it all.

[OSK] Reduce the delay when redrawing LED keyboard resources

---

dll/cpl/desk/lang/ja-JP.rc
dll/cpl/hdwwiz/lang/ja-JP.rc
dll/cpl/inetcpl/lang/ja-JP.rc
dll/cpl/main/lang/ja-JP.rc
dll/cpl/sysdm/lang/ja-JP.rc
dll/win32/msgina/lang/ja-JP.rc
dll/win32/netid/lang/ja-JP.rc

Improve Japanese translation.
Thanks to @98mebius.

[TRANSLATION] Improve Japanese translation

---

dll/shellext/ntobjshex/foldercommon.h
dll/shellext/ntobjshex/ntobjfolder.cpp
dll/shellext/ntobjshex/regfolder.cpp

And use explicit StringCbCopyW().

[NTOBJSHEX] StringCbCopy*() need sizeof(), not _countof()

---

boot/bootdata/hivesft.inf

JIRA issue: [CORE-11335](https://jira.reactos.org/browse/CORE-11335)
BEFORE:
AFTER:

[BOOTDATA] Add 'App Paths' registry entries

---

dll/win32/shell32/res/icons/Icon_Licence/Tango.txt

Add a download URL for referencing source.
JIRA issue: [CORE-11736](https://jira.reactos.org/browse/CORE-11736)

[SHELL32] Add Tango icons download URL

---

dll/win32/shell32/res/icons/Icon_Licence/RenameIcon.txt
dll/win32/shell32/res/icons/svg/242-rename-small.svg
dll/win32/shell32/res/icons/svg/242-rename.svg

JIRA issue: [CORE-11736](https://jira.reactos.org/browse/CORE-11736)

[SHELL32] Add SVG files of 'Rename' icon

---

boot/bootdata/hivecls.inf

JIRA issue: [CORE-16519](https://jira.reactos.org/browse/CORE-16519)
Please compare with Plan A: https://github.com/reactos/reactos/pull/2081

[SHELL32] Shift-Right-Click patch: Plan B

---

dll/win32/shell32/droptargets/CFSDropTarget.cpp

Reduce failures of `DragDrop` testcase.
JIRA issue: [CORE-11238](https://jira.reactos.org/browse/CORE-11238)

[SHELL32] Improve DragEnter of CFSDropTarget

---

dll/win32/shell32/dialogs/drive.cpp

Follow-up of https://github.com/reactos/reactos/commit/aedba8441af6dbe3da9bee501ecd74dce851b5a1.
Can you try this, anyone? I cannot test.
JIRA issue: [CORE-12756](https://jira.reactos.org/browse/CORE-12756)

[SHELL32] Make SHFormatDrive multi-thread

---

base/applications/mmc/console.c

JIRA issue: [CORE-11688](https://jira.reactos.org/browse/CORE-11688)

[MMC] DoSaveFileAs(): Respect szPath size. CORE-11688

---

dll/win32/comctl32/listview.c

This should at least reduce confusion when discussing this code (change) on CORE-16504...
Addendum to b931f643e35e6a23dbef99e785804039ea579b6a.
JIRA issue: [CORE-16466](https://jira.reactos.org/browse/CORE-16466)

[COMCTL32] Minimize Wine diff. CORE-16466

---

dll/win32/setupapi/install.c

Author = Victor Martinez.
JIRA issue: [CORE-11612](https://jira.reactos.org/browse/CORE-11612)

[SETUPAPI] profile_items_callback(): Check LinkName. CORE-11612

---

sdk/tools/cabman/cabinet.cxx

Author = Victor Martinez.
JIRA issue: [CORE-11090](https://jira.reactos.org/browse/CORE-11090)

[CABMAN] Fix 2 handle leaks, in case of error. CORE-11090

---

dll/win32/urlmon/CMakeLists.txt

JIRA issue: [CORE-5007](https://jira.reactos.org/browse/CORE-5007)

[URLMON] Delay-load advpack

---

dll/shellext/zipfldr/CMakeLists.txt
dll/shellext/zipfldr/CSendToZip.cpp
dll/shellext/zipfldr/CSendToZip.hpp
dll/shellext/zipfldr/CZipCreater.cpp
dll/shellext/zipfldr/CZipCreater.hpp
dll/shellext/zipfldr/lang/de-DE.rc
dll/shellext/zipfldr/lang/en-US.rc
dll/shellext/zipfldr/lang/et-EE.rc
dll/shellext/zipfldr/lang/fr-FR.rc
dll/shellext/zipfldr/lang/hi-IN.rc
dll/shellext/zipfldr/lang/it-IT.rc
dll/shellext/zipfldr/lang/ja-JP.rc
dll/shellext/zipfldr/lang/pl-PL.rc
dll/shellext/zipfldr/lang/ro-RO.rc
dll/shellext/zipfldr/lang/ru-RU.rc
dll/shellext/zipfldr/lang/sv-SE.rc
dll/shellext/zipfldr/lang/zh-CN.rc
dll/shellext/zipfldr/precomp.h
dll/shellext/zipfldr/res/zipfldr.rgs
dll/shellext/zipfldr/resource.h
dll/shellext/zipfldr/zipfldr.cpp

This PR will implement `*.ZFSendToTarget` file type that will realize `SendTo` ZIP folder in future.
JIRA issue: [CORE-16495](https://jira.reactos.org/browse/CORE-16495), [CORE-12562](https://jira.reactos.org/browse/CORE-12562)
BEFORE:
AFTER:

[SHELLEXT][ZIPFLDR] Implement ZIP creation

---

ntoskrnl/po/poshtdwn.c

And document values.
Addendum to 55aed4f8fa919ce3b210e14bff7aec1919202848.
JIRA issue: [CORE-16342](https://jira.reactos.org/browse/CORE-16342)

[NTOS:PO] PopShutdownHandler(): Fully screen-center images. CORE-16342

---

dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CFSFolder.h

JIRA issue: [CORE-7585](https://jira.reactos.org/browse/CORE-7585)

[SHELL32] Add 'm_' prefix to CFSFolder members

---

modules/rostests/apitests/user32/CMakeLists.txt
modules/rostests/apitests/user32/DrawText.c
modules/rostests/apitests/user32/testlist.c

This PR will add a testcase for `user32!DrawText` function.
JIRA issue: [CORE-15478](https://jira.reactos.org/browse/CORE-15478)
Win2k3:
Win10:
Successful.

[USER32_APITEST] Add DrawText testcase

---

base/setup/usetup/lang/hu-HU.h
dll/win32/syssetup/lang/hu-HU.rc

Fix hungarian translation for usetup & syssetup to use formal addressing / conjugation.

[TRANSLATION] Fix hungarian translation for usetup & syssetup to use formal addressing / conjugation

---

win32ss/user/ntuser/sysparams.c

JIRA issue: [CORE-16547](https://jira.reactos.org/browse/CORE-16547)
- Fix `SPI_GETSCREENSAVETIMEOUT`, `SPI_GETKEYBOARDSPEED` and `SPI_GETKEYBOARDDELAY` values.

[NTUSER] Improve loading settings (SystemParamtersInfo)

---

base/applications/osk/main.c
base/applications/osk/precomp.h
base/applications/osk/settings.c

Refactor the settings configuration code of On-Screen Keyboard. This adds up two function helpers for save/query the needed value settings of the application. 
This gives the opportunity to save or load up certain data values individually without having to load the data settings all at once.

[OSK] Refactor the registry configuration code

---

win32ss/user/user32/misc/exticon.c

JIRA issue: [CORE-16557](https://jira.reactos.org/browse/CORE-16557)

[USER32] Add ICO_ExtractIconExW RetPtr NULL check

---

base/applications/mspaint/selectionmodel.cpp
base/applications/mspaint/selectionmodel.h

- Initialize all members in `SelectionModel`'s ctor.
- Add `SelectionModel`'s dtor.

[MSPAINT] Fix memory leak of SelectionModel

---

boot/bootdata/hivedef.inf
win32ss/user/ntuser/sysparams.c

JIRA issue: [CORE-16547](https://jira.reactos.org/browse/CORE-16547)
- Add `IconTitleWrap` registry value.
- Modify `gspv.dwMenuShowDelay` initial value.
- Initialize `gspv.bFastTaskSwitch` as `TRUE`.

[BOOTDATA][NTUSER] Fix some system parameters

---

win32ss/gdi/ntgdi/freetype.c

[WIN32SS][NTGDI][FREETYPE] Add ASSERT(pOS2); to FillTM

---

sdk/include/psdk/gdiplusbase.h
sdk/include/psdk/gdiplusbrush.h
sdk/include/psdk/gdipluscolor.h
sdk/include/psdk/gdipluscolormatrix.h
sdk/include/psdk/gdipluseffects.h
sdk/include/psdk/gdiplusenums.h
sdk/include/psdk/gdiplusflat.h
sdk/include/psdk/gdiplusgpstubs.h
sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdiplusimageattributes.h
sdk/include/psdk/gdiplusimaging.h
sdk/include/psdk/gdiplusinit.h
sdk/include/psdk/gdipluslinecaps.h
sdk/include/psdk/gdiplusmatrix.h
sdk/include/psdk/gdiplusmem.h
sdk/include/psdk/gdiplusmetafile.h
sdk/include/psdk/gdiplusmetaheader.h
sdk/include/psdk/gdipluspath.h
sdk/include/psdk/gdipluspen.h
sdk/include/psdk/gdipluspixelformats.h
sdk/include/psdk/gdiplusstringformat.h
sdk/include/psdk/gdiplustypes.h

Just code formatting.
This PR is the results of the following command:
```bash
$ clang-format -style=file -i sdk/include/psdk/gdiplus[a-z]*
```

[SDK][INCLUDE] Formatting gdiplus headers

---

sdk/include/psdk/gdiplusheaders.h

[SDK][INCLUDE] Rename Gdiplus::Image::image as nativeImage (Retry)

---

sdk/include/psdk/gdipluseffects.h

[SDK][INCLUDE] Improve gdipluseffects.h

---

sdk/include/psdk/gdiplusheaders.h

[SDK][INCLUDE] Improve gdiplusheader.h

---

dll/win32/winhttp/net.c
dll/win32/winhttp/session.c
modules/rostests/winetests/winhttp/notification.c

Fix test failures after syncing with wine-staging 4.18 (5bd6580)
JIRA issue: [ROSTESTS-348](https://jira.reactos.org/browse/ROSTESTS-348)
I would like some help from people who are more familiar with this
Cc @AmineKhaldi

[WINHTTP] Initialize winsock upon WinHttpOpenRequest

---

ntoskrnl/io/iomgr/volume.c

[NTOS:IO] Fix list enumeration in IopShutdownBaseFileSystems

---

win32ss/user/winsrv/consrv/alias.c
win32ss/user/winsrv/consrv/coninput.c
win32ss/user/winsrv/consrv/conoutput.c
win32ss/user/winsrv/consrv/console.c
win32ss/user/winsrv/consrv/frontendctl.c
win32ss/user/winsrv/consrv/handle.c
win32ss/user/winsrv/consrv/history.c
win32ss/user/winsrv/consrv/subsysreg.c
win32ss/user/winsrv/consrv_new/alias.c
win32ss/user/winsrv/consrv_new/coninput.c
win32ss/user/winsrv/consrv_new/conoutput.c
win32ss/user/winsrv/consrv_new/console.c
win32ss/user/winsrv/consrv_new/frontendctl.c
win32ss/user/winsrv/consrv_new/handle.c
win32ss/user/winsrv/consrv_new/lineinput.c

Add comments to improve human-readability and referencing of CSR API.

[WIN32SS][WINSRV] Add CSR API_NUMBER info comments

---

sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdiplusmatrix.h
sdk/include/psdk/gdipluspath.h
sdk/include/psdk/gdipluspen.h
sdk/include/psdk/gdiplustypes.h

`Point`, `PointF`, `Size`, `SizeF`, `Rect` and `RectF` are also implemented.

[SDK][INCLUDE] Implementing Gdiplus::GraphicsPath

---

sdk/tools/do_code_format.sh

[SDK][TOOLS] Add do_code_format.sh to sdk/tools

---

sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdipluslinecaps.h
sdk/include/psdk/gdipluspath.h

Implement `Gdiplus::CustomLineCap` and `Gdiplus::AdjustableArrowCap`.

[SDK][INCLUDE] Implement Gdiplus::CustomLineCap

---

sdk/include/psdk/gdiplusimageattributes.h

[SDK][INCLUDE] Implement Gdiplus::ImageAttributes

---

sdk/include/psdk/gdiplusheaders.h

[SDK][INCLUDE] Improve Gdiplus::FontCollection

---

sdk/include/psdk/gdiplusbrush.h
sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdipluspen.h

[SDK][INCLUDE] Rename Gdiplus::Brush::brush as nativeBrush

---

sdk/include/psdk/gdiplusbrush.h
sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdiplusimageattributes.h
sdk/include/psdk/gdiplusmatrix.h

[SDK][INCLUDE] Implement Gdiplus::Brush

---

sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdipluspen.h

[SDK][INCLUDE] Rename Gdiplus::Pen::pen as nativePen

---

sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdipluspen.h

[SDK][INCLUDE] Implement Gdiplus::Pen

---

sdk/include/psdk/gdiplusbrush.h
sdk/include/psdk/gdiplusheaders.h

Move the code into the place it should be in.

[SDK][INCLUDE] Move Gdiplus::TextureBrush codes

---

sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdiplusheaders.h

[SDK][INCLUDE] Rename Gdiplus::Graphics::graphics as nativeGraphics

---

sdk/include/psdk/gdiplusbrush.h
sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdiplusimageattributes.h
sdk/include/psdk/gdiplusmatrix.h
sdk/include/psdk/gdipluspath.h
sdk/include/psdk/gdipluspen.h

[SDK][INCLUDE] Improve Gdiplus::Graphics

---

sdk/include/psdk/gdiplusheaders.h

[SDK][INCLUDE] Rename Gdiplus::Region::region as nativeRegion

---

sdk/include/psdk/gdiplusbase.h
sdk/include/psdk/gdiplusbrush.h
sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdipluslinecaps.h
sdk/include/psdk/gdiplusmatrix.h
sdk/include/psdk/gdipluspath.h
sdk/include/psdk/gdipluspen.h

Define `getNat` helper functions in `gdiplusbase.h` and use them.

[SDK][INCLUDE] Refinement of Gdiplus headers

---

sdk/include/psdk/gdipluspath.h

[SDK][INCLUDE] Improve gdipluspath.h

---

sdk/include/psdk/gdiplusstringformat.h

[SDK][INCLUDE] Improve gdiplusstringformat.h

---

sdk/include/psdk/gdiplusmatrix.h

[SDK][INCLUDE] Improve gdiplusmatrix.h

---

sdk/include/psdk/gdiplusmetafile.h

[SDK][INCLUDE] Improve gdiplusmetafile.h

---

sdk/include/psdk/gdiplusbase.h
sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdiplusmetafile.h
sdk/include/psdk/gdiplusstringformat.h

[SDK][INCLUDE] Improve gdiplusgraphics.h

---

sdk/include/psdk/gdiplusbase.h
sdk/include/psdk/gdiplusflat.h
sdk/include/psdk/gdiplusgraphics.h
sdk/include/psdk/gdiplusheaders.h
sdk/include/psdk/gdiplusmetafile.h
sdk/include/psdk/gdipluspath.h
sdk/include/psdk/gdipluspen.h

[SDK][INCLUDE] Total refinement of Gdiplus headers

---

drivers/ksfilter/ks/irp.c

Addendum to r42117 (4725a4fd9cb76e05ab5bb225e1f30bd94743e8d9).

[KS] KsQueryInformationFile(): Fix 'FastIoQueryBasicInfo' copypasta

---

dll/win32/shell32/lang/pt-PT.rc

[TRANSLATION] [SHELL32] Improvements to Portuguese translation  
and minor object adjustments because text lenght

[TRANSLATION] [SHELL32] Improvements to Portuguese translation

---

dll/apisets/api-ms-win-appmodel-runtime-l1-1-1.spec

Be consistent.
Addendum to #1942 192926ee026ee04992e1f8d5c6b34916389fd9ca.

[APISETS] Forwarders don't need parameter specifications

---

boot/freeldr/freeldr/arch/i386/hwdisk.c
boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/arch/i386/pcdisk.c
boot/freeldr/freeldr/arch/i386/xboxdisk.c
boot/freeldr/freeldr/include/arch/pc/machpc.h

Speed up the loading time a bit.

[FREELDR] Cache the drive geometry in the PcDiskReadLogicalSectorsCHS

---

dll/win32/browseui/browseui.rc
dll/win32/browseui/lang/hu-HU.rc
dll/win32/ieframe/ieframe.rc
dll/win32/ieframe/lang/hu-HU.rc
dll/win32/shell32/lang/hu-HU.rc

Add/update Hungarian translation for shell32, ieframe, browseui

[TRANSLATION] Add/update Hungarian translation for shell32, ieframe, browseui

---

dll/cpl/sysdm/general.c

[SYSDM] general.c: Make 2 global variables 'static'

---

boot/freeldr/bootsect/CMakeLists.txt
boot/freeldr/bootsect/pc98/fat12fdd.S
boot/freeldr/freeldr/CMakeLists.txt
sdk/cmake/config.cmake

The first part of [PC-98 Port](https://reactos.org/wiki/PC-98)
- FAT12 boot sector

[FREELDR] Add FAT12 file system boot sector for NEC PC-98 series

---

dll/ntdll/ldr/ldrinit.c

JIRA issue: [CORE-16631](https://jira.reactos.org/browse/CORE-16631)

[NTDLL] Add policy kill-switch for manifest based automatic shimming

---

dll/win32/browseui/CAutoComplete.cpp

import wine commits 9c2217 and 644358, slightly tweaked to fit our code
This fixes testman crash in shell32:autocomplete

[BROWSEUI] Fix infinite recursion in autocomplete control

---

boot/freeldr/freeldr/arch/i386/machpc.c

Microsoft Docs says that `KeyboardFlags` is defined by x86 BIOS INT 16h.

[FREELDR] Properly set keyboard flags in hardware detection

---

win32ss/printing/base/winspool/printers.c

See Regressions tests:
VBox https://reactos.org/testman/compare.php?ids=71252,71254

Add Implementation of EnumPrintersA

---

CODEOWNERS

[CODEOWNERS] Add 'Printing' entry

---

base/shell/explorer/startmnucust.cpp

On branch CodeFormat
Changes to be committed:
modified:   base/shell/explorer/startmnucust.cpp
For a better visualization and understanding of the code
Fix some Code format issue
- 
-

Fix some Code format issue in startmnucust.cpp

---

win32ss/printing/base/winspool/printers.c

_Add code for GetPrinterA based on GetPrinterW._

[WINSPOOL] Implement GetPrinterA based on GetPrinterW

---

dll/opengl/glu32/src/libnurbs/internals/arctess.cc
dll/opengl/glu32/src/libnurbs/internals/ccw.cc
dll/opengl/glu32/src/libnurbs/internals/hull.cc
dll/opengl/glu32/src/libnurbs/internals/mapdesc.cc
dll/opengl/glu32/src/libnurbs/internals/mesher.cc
dll/opengl/glu32/src/libnurbs/internals/trimline.cc
dll/opengl/glu32/src/libtess/priorityq.c
dll/opengl/glu32/src/libutil/error.c
dll/opengl/glu32/src/libutil/mipmap.c
media/doc/3rd Party Files.txt

This PR introduces changes incorporated into the latest upstream release to `dll/opengl/glu32/`.

[GLU32] Sync with glu 9.0.1

---

drivers/wdm/audio/backpln/portcls/irp.cpp

JIRA issue: [CORE-16611](https://jira.reactos.org/browse/CORE-16611)

[PORTCLS] Fixes to power IRP handling

---

sdk/lib/drivers/sound/mmixer/controls.c
sdk/lib/drivers/sound/mmixer/midi.c
sdk/lib/drivers/sound/mmixer/sup.c
sdk/lib/drivers/sound/mmixer/wave.c

JIRA issue: [CORE-16611](https://jira.reactos.org/browse/CORE-16611)
The last of the three commits should fix the actual bug, the rest are opportunistic fixes.

[MMIXER] Fix some device name handling bugs

---

dll/cpl/appwiz/createlink.c

JIRA issue: [CORE-16669](https://jira.reactos.org/browse/CORE-16669)
- Load `comctl32.dll` and call the `InitCommonControls` function to enable Visual Style.

[CPL][APPWIZ] Attempt to enable Visual Style

---

dll/win32/shell32/stubs.cpp
dll/win32/shell32/wine/shellord.c

JIRA issue: [CORE-11701](https://jira.reactos.org/browse/CORE-11701)
BEFORE:
AFTER:

[SHELL32] Initial implement SHLimitInputEdit

---

win32ss/printing/base/winspool/CMakeLists.txt
win32ss/printing/base/winspool/precomp.h
win32ss/printing/base/winspool/printers.c
win32ss/printing/base/winspool/utils.c

_Also implement one helper function for In-Place Unicode to ANSI conversions in utils.c._

[WINSPOOL] Implement GetPrinterDriverA

---

boot/bootdata/txtsetup.sif
hal/halx86/legacy/halpcat.c
media/inf/hal.inf

What the title says. :wink: 
There are also some minor whitespace corrections in `hal.inf`.

[HALXBOX][BOOTDATA][INF] Give the Xbox HAL its own personality

---

base/services/nfsd/idmap.c
base/services/nfsd/nfs41_daemon.c
base/services/telnetd/telnetd.c
dll/3rdparty/libtirpc/src/wintirpc.c
dll/3rdparty/libtirpc/tirpc/netconfig.h
modules/rosapps/applications/sysutils/man/man.cmd

JIRA issue: [CORE-14747](https://jira.reactos.org/browse/CORE-14747)

[NFSD][TELNETD][LIBTIRPC][MAN] Don't hardcode C:\ReactOS

---

dll/opengl/opengl32/swimpl.c

Fix CORE-16221
JIRA issue: [CORE-16221](https://jira.reactos.org/browse/CORE-16221)

[OPENGL32] Fix RGB <-> BGR mismatch

---

modules/rostests/apitests/shell32/ShellExecuteW.cpp

JIRA issue: [CORE-14747](https://jira.reactos.org/browse/CORE-14747)

[SHELL32_APITEST] Don't hardcode C:\ReactOS

---

dll/win32/syssetup/lang/ru-RU.rc

Translate Product Options page in syssetup into Russian.

[SYSSETUP] Update Russian translation for Product Options page

---

dll/win32/msgina/gui.c

JIRA issue: [CORE-16697](https://jira.reactos.org/browse/CORE-16697)
- Rename `hBitmap` as `hLogoBitmap` of `DLG_DATA` structure.
- Make `DLG_DATA` object-oriented.
- Add `DlgData_Create`. `DlgData_LoadBitmaps`, and `DlgData_Destroy` functions.

[MSGINA] Make DLG_DATA object-oriented

---

modules/rostests/apitests/kernel32/ConsoleCP.c
win32ss/user/winsrv/consrv/condrv/text.c
win32ss/user/winsrv/consrv/frontends/terminal.c
win32ss/user/winsrv/consrv/include/conio.h
win32ss/user/winsrv/consrv/popup.c

Additional issues to consider:
https://github.com/rprichard/winpty/issues/105
https://github.com/Maximus5/ConEmu/issues/945
https://testbot.winehq.org/JobDetails.pl?Key=63849

[CONSRV] Miscellaneous console fixes for CJK support and screenbuffer iteration.

---

win32ss/gdi/gdi32/include/precomp.h
win32ss/printing/base/winspool/devmode.c
win32ss/printing/base/winspool/precomp.h
win32ss/printing/base/winspool/printers.c

_Once this PR is merged CORE-16622 should be fixed._

[WINSPOOL] Implement DocumentPropertiesA

---

base/shell/cmd/if.c

JIRA issue: [CORE-14797](https://jira.reactos.org/browse/CORE-14797)
BEFORE:
AFTER:

[CMD] Fix 'if exist' command for root directories

---

boot/bootdata/hivedef.inf
dll/win32/shell32/CDefView.cpp

JIRA issue: [CORE-15242](https://jira.reactos.org/browse/CORE-15242)
BEFORE:
AFTER:

[SHELL32][BOOTDATA] Don't select filename extension upon renaming

---

base/shell/explorer/explorer.rc
base/shell/explorer/lang/hu-HU.rc
dll/win32/msgina/lang/hu-HU.rc
dll/win32/msgina/msgina.rc

Add Hungarian translation for explorer, msgina

[TRANSLATION] Add Hungarian translation for explorer, msgina

---

boot/freeldr/freeldr/lib/comm/rs232.c
boot/freeldr/freeldr/ntldr/headless.c
drivers/base/kdcom/kdcom.c
drivers/base/kdgdb/kdcom.c
ntoskrnl/inbv/inbvport.c
ntoskrnl/kd/i386/kdbg.c
sdk/include/reactos/drivers/pc98/cpu.h
sdk/include/reactos/drivers/pc98/pit.h
sdk/include/reactos/drivers/pc98/serial.h
sdk/include/reactos/drivers/pc98/sysport.h
sdk/lib/cportlib/CMakeLists.txt
sdk/lib/cportlib/cport_pc98.c

There are 2 known onboard serial ports:
- COM1 - based on Intel 8251A
- COM2 - National Semiconductor 16550 (Untested, but should work)
- Add a new ComPort library

[CPORTLIB][NTOS:INBV][KDCOM][FREELDR] Add ComPort library for NEC PC-98 series

---

base/setup/usetup/lang/it-IT.h
base/setup/usetup/lang/pl-PL.h

[USETUP] Fix ' \n' typos, in *.h

---

dll/win32/rasdlg/lang/de-DE.rc

Addendum to 92aabb07fb85a1095af6891e6480dc3c2c7b0235.

[RASDLG] Fix remaining '\n\n\n\n\n\n\n' typo

---

modules/rostests/apitests/shell32/SHChangeNotify.cpp
modules/rostests/apitests/shell32/shell-notify.cpp

Add pathname checks.
WinXP:
Win2k3:
Win10:

[SHELL32_APITEST] Strengthen SHChangeNotify testcase

---

base/services/umpnpmgr/rpcserver.c

Addendum to db02f87d7b33201ffa64890c098d5dc7b56018cc.

[UMPNPMGR] rpcserver.c: Fix debug message copypastas

---

dll/win32/shlwapi/ordinal.c
dll/win32/shlwapi/shlwapi.spec

- Implement `shlwapi!SHLockSharedEx` function.
- Modify `shlwapi.spec` file (some argument conversions from `long` to `ptr`).

[SHLWAPI] Implement SHLockSharedEx function

---

base/applications/sndvol32/misc.c
base/applications/sndvol32/sndvol32.c
base/applications/sndvol32/sndvol32.h

The following patch restores the previous window coordinates. It's currently WIP.

[SNDVOL32] Restore the previous placement data of the window

---

dll/win32/msvcrt/msvcrt.spec
dll/win32/wintrust/wintrust.spec
sdk/lib/crt/string/scanf.c

required to load some windows server 2003 mmc snapins

Add _snwscanf, WTHelperGetFileHash stub

---

dll/cpl/main/lang/pt-PT.rc
dll/cpl/powercfg/lang/pt-PT.rc
dll/cpl/powercfg/powercfg.rc

Portuguese translation
- Fixed one word left untranslated in IDD_PAGE_BUTTON dialog
- New Portuguese translation to cpl/powercfg
-

Pt pt translation

---

modules/rostests/apitests/ntdll/NtQueryInformationProcess.c

Only buffer structure misalignment are being treated with this testcase right now. I'm trying to check for a possible fix for [CORE-16757](https://jira.reactos.org/browse/CORE-16757).
**Windows XP:**
**Windows Server 2003:**
**ReactOS:**

[APITEST][NTDLL] Add testcase for process priority class

---

sdk/include/ndk/pstypes.h

More information can be found in the commit description.
**BEFORE:**
**AFTER:**

[SDK] Align PROCESS_PRIORITY_CLASS of 4-bytes (ULONG)
