reactos/reactos

- dll/win32/rpcrt4/rpcrt4.spec
Addendum to b6fdb56b9adf780902cc9cf65af1f76365a96ce4.
Import
https://source.winehq.org/git/wine.git/commit/c73352047d20a503c67bdd583f6ef8d98711a678
JIRA issue: [CORE-15682](https://jira.reactos.org/browse/CORE-15682)
> [RPCRT4] Fix 'Routeines' typos. CORE-15682

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtSetInformationProcess.c
- modules/rostests/apitests/ntdll/testlist.c
**Windows Server 2003:**
**Windows XP:**
**ReactOS:**
> [APITEST] Implement NtSetInformationProcess testcase

- dll/cpl/sysdm/smbios.c
Totally not an April Fools day joke. :ok_hand:
> [SYSDM] Cumulative update 2020-04-01 for SMBIOS parser

- sdk/include/psdk/guiddef.h
Cherry-pick
https://source.winehq.org/git/wine.git/commit/4626db2bb2a61cdceb00e0e346628062ee51aade
Import
https://source.winehq.org/git/wine.git/commit/54f58769fee73a55675d503e0281e8f381a8e8b1
https://source.winehq.org/git/wine.git/commit/34f3e7793b40d0eac60c373f66f262be2e0d5cdb
> [PSDK] guiddef.h: Remove unwanted '&& !defined(CINTERFACE)'

- base/applications/utilman/CMakeLists.txt
- base/applications/utilman/precomp.h
- base/applications/utilman/registry.c
This is an initial implementation skeleton of the Registry management code for Utilman. More to come.
> [UTILMAN] Implement the Registry management code skeleton

- base/applications/rapps/available.cpp
- base/applications/rapps/include/available.h
- base/applications/rapps/include/defines.h
- base/applications/rapps/loaddlg.cpp
- sdk/include/crt/crtdbg.h
- sdk/lib/atl/atlbase.h
- sdk/lib/atl/atlcom.h
- sdk/lib/atl/atlwin.h
- sdk/lib/crt/misc/dbgrpt.cpp
- sdk/lib/crt/msvcrtex.cmake
Most functionality is working, except output to file
JIRA issue: [CORE-11835](https://jira.reactos.org/browse/CORE-11835)
> [CRT] Implement _CrtDbgReport and _CrtDbgReportW

- ntoskrnl/po/power.c
This means we now correctly handle the `DO_POWER_PAGABLE` flag.
In particular, Windows's usbhub.sys calls `KeDelayExecutionThread` from a
power IRP dispatch routine. We now handle this correctly.
JIRA issues:
* [CORE-11648](https://jira.reactos.org/browse/CORE-11648)
* [CORE-16704](https://jira.reactos.org/browse/CORE-16704)
> [NTOS:PO] Call power IRP handlers at PASSIVE_LEVEL when needed

- ntoskrnl/mm/ARM3/i386/init.c
- ntoskrnl/mm/ARM3/mminit.c
- sdk/include/ndk/mmtypes.h
JIRA issue: [CORE-16731](https://jira.reactos.org/browse/CORE-16731)
cc @vgalnt
> [NTOS:MM] Initialize MmSubsectionBase.

- drivers/base/bootvid/precomp.h
- hal/halx86/generic/misc.c
- ntoskrnl/inbv/inbv.c
- ntoskrnl/inbv/logo.h
- ntoskrnl/include/internal/inbv.h
- ntoskrnl/kd/kdio.c
- ntoskrnl/ke/bug.c
- ntoskrnl/po/poshtdwn.c
- sdk/include/reactos/drivers/bootvid/bootvid.h
- sdk/include/reactos/drivers/bootvid/display.h
Reduce the hardcoded values. Easier way to add custom resolutions. No visual changes.
> [BOOTVID][NTOSKRNL][HALX86] Move hardcoded coordinates of bootvid into one place

- dll/win32/browseui/explorerband.cpp
- dll/win32/browseui/explorerband.h
Add `'m_'` prefix to the variable members of class `CExplorerBand` for readability.
> [BROWSEUI] Add 'm_' prefix to CExplorerBand members

- boot/freeldr/fdebug/CMakeLists.txt
- boot/freeldr/install/CMakeLists.txt
It might be useful to have installfreeldr on LiveCD/HybridCD as well.
> [FREELDR][INSTALL] Include installfreeldr in LiveCD and HybridCD

- dll/shellext/zipfldr/lang/ru-RU.rc
- dll/shellext/zipfldr/res/zipfldr.rgs
- dll/win32/shell32/lang/ru-RU.rc
Update Russian translation, also fix trivial bug in rgs file. — JIRA issue: [CORE-16866](https://jira.reactos.org/browse/CORE-16866)
> [TRANSLATION] Update Russian translation

- media/doc/README.WINE
JIRA issue: [CORE-16441](https://jira.reactos.org/browse/CORE-16441)
> [README.WINE] Fix 'User32' typo and add winetests/winmm. CORE-16441

- dll/win32/iphlpapi/iphlpapi_main.c
- dll/win32/iphlpapi/ipstats.h
And fix 4 comments.
Follow-up to 68d94581ad181efe860a168dc6938846c87638fc.
> [IPHLPAPI] GetAdaptersAddresses(): Add 1 free() in ERROR_NO_DATA case

- drivers/crypto/ksecdd/ksecdd.spec
- drivers/crypto/ksecdd/stubs.c
JIRA issue: [CORE-15186](https://jira.reactos.org/browse/CORE-15186)
> Improve GetSecurityUserInfo Stub

- dll/cpl/appwiz/lang/pl-PL.rc
[APPWIZ.CPL} PL Translate update
> [APPWIZ.CPL] PL Translate update

- dll/shellext/zipfldr/lang/pl-PL.rc
> [ZIPFLDR] PL-pl lang update

- dll/win32/shell32/lang/pl-PL.rc
> [shell32] PL-pl cosmetical changes

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/RtlGetNtProductType.c
- modules/rostests/apitests/ntdll/testlist.c
**Windows Server 2003:**
**Windows XP:**
**ReactOS:**
> [APITEST][NTDLL] Implement RtlGetNtProductType testcase

- base/applications/rapps/loaddlg.cpp
use _beginthreadex instead of CreateThread
use _beginthreadex instead of CreateThread
> [RAPPS] Use _beginthreadex instead of CreateThread

- boot/freeldr/freeldr/arch/i386/pc98/pc98video.c
- sdk/include/reactos/drivers/pc98/video.h
> [FREELDR] Fix typos

- dll/cpl/inetcpl/lang/fr-FR.rc
FR translation for inet.cpl
JIRA issue: [CORE-16900](https://jira.reactos.org/browse/CORE-16900)
FR translation for inet.cpl
> [Inet cpl] fr-fr translation update

- base/shell/explorer/startup.cpp
JIRA issue: [CORE-16909](https://jira.reactos.org/browse/CORE-16909)
> [EXPLORER] Keep processing messages while waiting for a startup task

- boot/bootdata/hivedef.inf
_Update default ReactOS HKCU file._
JIRA issue: [CORE-16882](https://jira.reactos.org/browse/CORE-16882)
> Add Search Hidden Files and Folders Registry Entry for HKCU

- dll/win32/shimgvw/lang/es-ES.rc
> [TRANSLATION] (shimgvw) Minimal translation.

- dll/win32/browseui/lang/fr-FR.rc
_ fr-fr translation update following PR2602
JIRA issue: [CORE-10989](https://jira.reactos.org/browse/CORE-10989)
_ Update of fr-fr new error message to match Windows wording
_ Various fr-fr addition on Taskbar / Toolbar strings
> [BROWSEUI] fr-fr translation update following PR2602

- dll/win32/shimgvw/lang/fr-FR.rc
_ fr-fr translation following PR 2606 by @katahiromz
(https://github.com/reactos/reactos/pull/2608 closed following Git mistake)
> [SHIMGVW] fr-fr translation following PR 2606

- .github/FUNDING.yml
- CONTRIBUTING.md
- INSTALL
- README.md
And improve/fix some urls.
NB:
Fixing code will be done in separate PRs.
> [REACTOS] Update now-redirected 'http' and 'www.reactos.org' urls

- dll/win32/shell32/lang/pt-PT.rc
[TRANSLATION] Fix grammatical error in shell32/lang/pt-PT.rc file
- 
-
> [SHELL32]  PT translation Fix grammatical error

- dll/shellext/sendmail/lang/fr-FR.rc
_ French (fr-fr) update following https://github.com/reactos/reactos/pull/2616
> [SENDMAIL] fr-fr update

- .github/FUNDING.yml
- .travis.yml
- CONTRIBUTING.md
- CREDITS
- INSTALL
- README.md
> [REACTOS] Update some external URLs

- drivers/bus/pci/CMakeLists.txt
- drivers/bus/pci/pci.h
- drivers/bus/pci/pdo.c
- drivers/bus/pcix/CMakeLists.txt
- drivers/bus/pcix/debug.c
- drivers/bus/pcix/enum.c
- drivers/bus/pcix/pci.h
- drivers/bus/pcix/utils.c
- ntoskrnl/include/internal/cm.h
- ntoskrnl/io/pnpmgr/pnpres.c
- sdk/include/reactos/drivers/cmreslist.h
- win32ss/drivers/videoprt/resource.c
Also add a hack to avoid failing on now occurring resource conflict detection and try to fix at least one resource in ACPI hal.
CORE-10146
CORE-12892
Test results: https://reactos.org/testman/compare.php?ids=71547,71548 (Revision 58e947e is this PR)
> [NTOS:IO] Fix parsing of resource lists

- dll/win32/shell32/lang/fr-FR.rc
_ Translation of all fr-fr missing elements in Shell32 (in particular files & folders options & file associations panels)
> [SHELL32] fr-fr translation

- dll/cpl/powercfg/lang/pl-PL.rc
Update after https://github.com/reactos/reactos/pull/2593
> Update polish translation for PowerCFG

- dll/cpl/desk/lang/pl-PL.rc
After https://github.com/reactos/reactos/pull/2591
> Desk update Polish translation

- dll/win32/shimgvw/lang/pl-PL.rc
> [SHIMGVW] Update Polish translation

- dll/win32/shell32/wine/brsfolder.c
Enable Del/Delete key to delete the selected folder in "Browse for Folder" dialog.
JIRA issue: [CORE-7592](https://jira.reactos.org/browse/CORE-7592)
You can use https://jira.reactos.org/secure/attachment/40118/getfolder.zip as a test program.
> [SHELL32] Implement VK_DELETE on SHBrowseForFolder

- dll/cpl/intl/lang/pl-PL.rc
After https://github.com/reactos/reactos/pull/2654
> Intl polish update

- dll/win32/msv1_0/CMakeLists.txt
- dll/win32/msv1_0/lsa.c
- dll/win32/msv1_0/lsa.h
- dll/win32/msv1_0/msv1_0.c
- dll/win32/msv1_0/msv1_0.spec
- dll/win32/msv1_0/precomp.h
Creates "stubs" for function-pointers returned with SECPKG_FUNCTION_TABLE from SpLsaModeInitialize.
> [MSV1_0] Create stubs for ntlm functions (lsa mode)

- ntoskrnl/ke/i386/traphdlr.c
> [NTOS:KE] KiTrap0DHandler(): Fix a copypasta

- sdk/lib/drivers/lwip/src/rostcp.c
Try to fix CORE-16868 by calling tcp_close when we get shutdown with both tx and rx enabled.
JIRA issue: [CORE-16868](https://jira.reactos.org/browse/CORE-16868)
> [LWIP] Attempt to fix CORE-16868

- CODEOWNERS
> Add comment about Translations section in CODEOWNERS

- dll/win32/rpcrt4/rpcrt4.spec
Based on @learn-more's [comment](https://jira.reactos.org/browse/CORE-12534?focusedCommentId=87173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87173)
JIRA issue: [CORE-12534](https://jira.reactos.org/browse/CORE-12534)
- Stub only.
> [RPCRT4] Stub I_RpcSNCHOption(). CORE-12534

- win32ss/printing/base/winspool/printers.c
Split off from #2298.
Addendum to e8b1778.
> [WINSPOOL] EnumPrintersA(): Fix failure handling on/after EnumPrintersW(). CORE-16622

- sdk/lib/crt/stdlib/mbtowc.c
[CORE-16885](https://jira.reactos.org/browse/CORE-16885)
> [SDK] Wine sync _mbtowc_l code

- base/applications/mspaint/dib.cpp
- base/applications/mspaint/dib.h
- base/applications/mspaint/globalvar.h
- base/applications/mspaint/history.cpp
- base/applications/mspaint/history.h
- base/applications/mspaint/main.cpp
- base/applications/mspaint/winproc.cpp
- base/applications/mspaint/winproc.h
JIRA issue: [CORE-16982](https://jira.reactos.org/browse/CORE-16982), [CORE-16979](https://jira.reactos.org/browse/CORE-16979)
- Add `DoLoadImageFile`, `CreateWhiteDIB`, and `CMainWindow::ConfirmSave` functions.
- Replace `LoadDIBFromFile` function with `DoLoadImageFile`.
- Fix the empty file loading.
- Delete `UpdateApplicationProperties` function.
- Rewrite `SaveDIBToFile` function.
> [MSPAINT] Refactor loading/saving image file

- base/applications/cmdutils/label/lang/zh-CN.rc
zh-CN translation of cmdutil ```label```
> [LABEL] Update Chinese Simplified translation

- dll/cpl/appwiz/createlink.c
Show editbox text in selected mode (in blue);
> [APPWIZ] Make shortcut name selected on creation

- sdk/include/reactos/mc/net_msg.mc
[NET_MSG.MC] Polish translation update: net.exe
> [MC][NET] Polish translation update

- dll/win32/shell32/lang/pl-PL.rc
After https://github.com/reactos/reactos/pull/2695 (committed in https://github.com/reactos/reactos/commit/8f3079c67f85f61727f6f8a3cfaaa7d42264702e)
> [SHELL32] Update Polish translation

- win32ss/user/user32/controls/listbox.c
- win32ss/user/user32/windows/defwnd.c
Fixed scrolling issue_on Change Icon dialog 
JIRA CORE16163
>  [USER32] Fixed scrolling issue in Change Icon dialog. CORE-16163

- dll/shellext/netshell/lang/pt-PT.rc
Fixed some typos in Portuguese translation for  netshell
> [NETSHELL] Fixed some typos in Portuguese translation

- dll/win32/ole32/ifs.c
_ Wine's implementation of IMalloc.DidAlloc.
_ Problem reported to WineHQ : https://bugs.winehq.org/show_bug.cgi?id=48941
_ Implementation done in Wine 5.7
_ Patch produced by @Doug-Lyons to get the fix ahead of WineSync with Wine 5.7
JIRA issue: [CORE-15262 ](https://jira.reactos.org/browse/CORE-15262 )
_ Integration of patch produced by Doug here : https://jira.reactos.org/browse/CORE-15262
_ Test done with SUMo 5.10.16 => No more exceptions raised when called "Scan folder" a second time and no functionnal impact (problem is solved)
> [OLE32] Fix Wine's implementation of IMalloc.DidAlloc ahead of Wine 5.7 (CORE-15262)

- base/applications/rapps/lang/pl-PL.rc
After https://github.com/reactos/reactos/commit/fb1582d330116f9946e235d99b5384dd76b6fa79
> [RAPPS] Polish translation

- base/setup/welcome/lang/pl-PL.rc
> [welcome] pl-pl update

- README.md
- configure.cmd
- sdk/cmake/gcc.cmake
- sdk/cmake/msvc.cmake
- sdk/include/reactos/libs/pseh/pseh3.h
This year we celebrate a 10th anniversary of Visual Studio 2010 IDE.
Good time make this pull request :D
> Drop Visual Studio 2010-2013

- dll/win32/netid/lang/pl-PL.rc
After https://github.com/reactos/reactos/commit/c276681ef46ca308e9facc1cc33688c1bbf6272b
> [NETID] Update pl-PL

- dll/apisets/api-ms-win-crt-private-l1-1-0.spec
- dll/apisets/api-ms-win-crt-runtime-l1-1-0.spec
- dll/win32/crtdll/crtdll.spec
Addendum to 65fd292867bd55cc2a8da231176cbc2ad7e82181.
JIRA issue: [CORE-16700](https://jira.reactos.org/browse/CORE-16700)
> [APISETS] *_seh_filter_*() are NT6+. CORE-16700

- dll/win32/advapi32/reg/hkcr.c
Addendum to 5dfe3455db5d8c21a326178006ae8dab9c71fc4b.
> [ADVAPI32] Remove now-redundant comment

- base/system/userinit/livecd.c
- base/system/userinit/userinit.h
- boot/bootdata/CMakeLists.txt
- boot/bootdata/livecd/unattend.inf
Allows booting straight to desktop
> [USERINIT] Add unattend.inf functionality to livecd

- README.md
Updated RosBE links and badges to 2.2.0 version
> Updated RosBE links and badges to 2.2.0 version

- README.md
improved logic of the text
improved logic of the text
removed some line break
> "Building ReactOS" belongs to "Building" part

- dll/win32/comctl32/button.c
- win32ss/user/user32/controls/button.c
> Revert "Revert "[COMCTL32][USER32] Fix radio button regression""

- base/applications/sndrec32/lang/fr-FR.rc
- Completion of FR-fr translation for SNDREC32 module.
Note : Caution when merged along with https://github.com/reactos/reactos/pull/2754
> [SNDREC32] French translation update

- boot/freeldr/freeldr/arch/i386/pc98/machpc98.c
- boot/freeldr/freeldr/arch/i386/xbox/machxbox.c
- boot/freeldr/freeldr/arch/i386/xbox/xboxcons.c
- boot/freeldr/freeldr/arch/i386/xbox/xboxvideo.c
- boot/freeldr/freeldr/include/arch/i386/machxbox.h
- boot/freeldr/freeldr/include/debug.h
- boot/freeldr/freeldr/lib/debug.c
> [FREELDR] Add vertical screen scrolling for Xbox with console mode

- dll/win32/shell32/folders/CRecycleBin.cpp
> [SHELL32] Don't hardcode C: drive

- dll/cpl/intl/lang/pl-PL.rc
intl.cpl - PL-pl update
-dialogs fix
-strings update
> [INTL.CPL] PL-pl update

- dll/cpl/main/lang/pl-PL.rc
MAIN.CPL - PL-pl
-dialogs fix
-strings update
> [MAIN.CPL] PL-pl update

- dll/win32/browseui/lang/pl-PL.rc
browseui.dll - PL-pl translation update :)
> [BROWSEUI] PL-pl update

- base/applications/network/ftp/main.c
> [FTP] Don't hardcode C: drive

- modules/rosapps/applications/sysutils/man/man.c
> [ROSAPPS][MAN] Don't hardcode C: drive

- base/applications/mplay32/mplay32.c
> [MPLAY32] Don't hardcode C: drive

- dll/win32/shlwapi/ordinal.c
Implement `shlwapi!SHIsLowMemoryMachine` function.
> [SHLWAPI] Implement SHIsLowMemoryMachine

- dll/win32/shell32/lang/pl-PL.rc
shell32.dll PL-pl 
-FIXED invisible text in DIALOGS
> [SHELL32] PL-pl Dialogs fix

- dll/win32/shell32/stubs.cpp
Implement `shell32!MakeShellURLFromPathA` function.
> [SHELL32] Implement MakeShellURLFromPathA

- dll/win32/shell32/stubs.cpp
Implement `shell32!SheShortenPathA` function.
> [SHELL32] Implement SheShortenPathA

- drivers/base/bootvid/CMakeLists.txt
- drivers/base/bootvid/bootvid.rc
- drivers/base/bootvid/i386/pc98/bootvid.c
- drivers/base/bootvid/i386/pc98/pc98.h
- drivers/base/bootvid/precomp.h
- sdk/include/reactos/drivers/pc98/video.h
> [BOOTVID] Add boot video driver for NEC PC-98 series

- base/services/dcomlaunch/network.c
> [SERVICES][DCOMLAUNCH] Don't hardcode C: drive

- dll/win32/comdlg32/filedlg.c
- dll/win32/comdlg32/filedlgbrowser.c
- dll/win32/shell32/folders/CFSFolder.cpp
- dll/win32/shell32/folders/CFSFolder.h
- dll/win32/shlwapi/reg.c
- sdk/include/psdk/shlwapi.h
- sdk/include/reactos/shellutils.h
- sdk/include/reactos/shlwapi_undoc.h
Also make `CFileSysEnum` before changing it,
and fix some random crap.
JIRA issue: [CORE-16908](https://jira.reactos.org/browse/CORE-16908)
> [COMDLG32] Do not allow traversal inside virtual folders when selecting a file

- dll/shellext/acppage/ACPPage.rc
- dll/shellext/acppage/lang/pt-PT.rc
[SHELLEXT] New PT translation to acppage rc file
minor object readjustment to fit text
> [SHELLEXT] New Portuguese translation to acppage rc file

- drivers/base/bootvid/CMakeLists.txt
- drivers/base/bootvid/bootvid.rc
- drivers/base/bootvid/i386/xbox/bootvid.c
- drivers/base/bootvid/i386/xbox/nv2a.h
- drivers/base/bootvid/precomp.h
- hal/halx86/generic/bios.c
Also make HalpBiosDisplayReset() function always return FALSE, because we don't have a BIOS on Xbox. [CORE-16219](https://jira.reactos.org/browse/CORE-16219)
> [BOOTVID][HALXBOX] Implement boot video driver for Xbox

- ntoskrnl/io/pnpmgr/pnproot.c
JIRA issue: [CORE-15882](https://jira.reactos.org/browse/CORE-15882)
> [NTOS:PNP] Avoid unnecessary stack buffers

- base/applications/mscutils/eventvwr/lang/pl-PL.rc
After https://github.com/reactos/reactos/commit/8756cec0e34813cdedc3b66701df743dbaace8b3 (https://github.com/reactos/reactos/pull/2744)
> [EVENTVWR] Update polish translation

- dll/cpl/desk/lang/pt-PT.rc
- dll/cpl/timedate/lang/pt-PT.rc
[CPL] Update Portuguese translation to desk.rc file
> [DESK] Update Portuguese translation

- dll/cpl/timedate/lang/fr-FR.rc
- Completion of French translation for NTP page
- Translation of last 2 NTP related strings
> [TIMEDATE] French translation

- base/applications/rapps/loaddlg.cpp
- base/applications/rapps/winmain.cpp
several trivial fixes
- specify W explicitly for URL_COMPONENTS
- remove malloc/free for once used HostName in urlComponents
- use PathAppendW to operate path string
> [RAPPS] Rapps trivial fixes

- ntoskrnl/inbv/inbv.c
JIRA issue: [CORE-16786](https://jira.reactos.org/browse/CORE-16786)
> [NTOS:INBV] Fix screen flash and more

- dll/cpl/access/lang/pt-PT.rc
[CPL] Improvement to Portuguese translation
> [ACCESS] Improvements to Portuguese translation

- dll/win32/syssetup/wizard.c
Addendum to 612729b09272aeb693e156de6b5991891951dbf2.
JIRA issue: [CORE-17069](https://jira.reactos.org/browse/CORE-17069)
> [SYSSETUP] DoWriteProductOption(): Fix 'pData' copypastas. CORE-17069

- win32ss/printing/base/winspool/printers.c
Addendum to ecde3768254664ca40a3f2fa49d1342d4bd92c02.
> [WINSPOOL] GetPrinterA(): Refactor failure handling. CORE-16622

- base/applications/rapps/lang/pt-PT.rc
[RAPPS] Update pt translation following PR#2792
> [RAPPS] Update pt translation following PR#2792

- dll/cpl/appwiz/lang/pl-PL.rc
appwiz.cpl PL-pl
-FIXED: dialogs, button, description
> [APPWIZ] PL-pl update

- dll/win32/lsasrv/authpackage.c
Thanks to 'qarmin', who reported!
JIRA issue: [CORE-17074](https://jira.reactos.org/browse/CORE-17074)
> [LSASRV] LsapLogonUser(): Fix 'AuthenticatingAuthority' copypasta. CORE-17074

- dll/win32/shell32/lang/hu-HU.rc
Hungarian translation update for shell32
> [TRANSLATION] Hungarian translation update for shell32

- dll/win32/advapi32/advapi32.spec
Convert ordinals to @ in spec file
> [ADVAPI32] Convert ordinals to @ in spec file

- dll/cpl/mmsys/speakervolume.c
JIRA issue: [CORE-17079](https://jira.reactos.org/browse/CORE-17079)
> [MMSYS] OnHScroll(): Fix wrong '&&' operator. CORE-17079

- win32ss/printing/base/winspool/precomp.h
- win32ss/printing/base/winspool/printers.c
- win32ss/printing/base/winspool/utils.c
Addendum to d90beaeed26863985486874aaa2a1c3422fd6d9f.
> [WINSPOOL] GetPrinterDriverA(): Refactor failure handling. CORE-16622

- ntoskrnl/CMakeLists.txt
> [CMAKE] Group files in the project file based on directory layout

- base/applications/sndrec32/sndrec32.cpp
Addendum to 82e4efea77aa19d79a4a14c41ae2222c2994b829.
> [SNDREC32] Use ShellAboutW(..., ..., NULL, ...)

- dll/win32/msgina/gui.c
And let bar timer depend on the bar image only.
> [MSGINA] gui: Improve DlgData_LoadBitmaps()

- base/applications/rapps/lang/zh-TW.rc
> [RAPPS] Update Chinese (Taiwan) translation

- dll/apisets/api-ms-win-crt-private-l1-1-0.spec
- dll/apisets/api-ms-win-crt-runtime-l1-1-0.spec
[WTB 71164](https://testbot.winehq.org/JobDetails.pl?Key=71164)
JIRA issue: [CORE-16700](https://jira.reactos.org/browse/CORE-16700)
> [APISETS] *_onexit_*() are NT10(v1607)+. CORE-16700

- sdk/lib/rtl/acl.c
Improve debug log a bit.
JIRA issue: [CORE-11506](https://jira.reactos.org/browse/CORE-11506)
> [SDK:RTL] RtlValidAcl(): Improve ACL error messages. CORE-11506

- base/applications/rapps/gui.cpp
- base/applications/rapps/include/misc.h
- base/applications/rapps/misc.cpp
- base/applications/rapps/winmain.cpp
I add a window layer, now the richedit does not belong to the main window directly.
why I am doing so is because:
- the main window has undertaken too many tasks.
- later I want to add a window at the left side of the richedit in order to display a snapshot or an icon
> [RAPPS] add a layer of window above the richedit

- modules/rostests/winetests/secur32/schannel.c
Cherry-pick
https://source.winehq.org/git/wine.git/commit/16254af818095216e10aee4d9032a8def3ac3344
JIRA issue: [CORE-17088](https://jira.reactos.org/browse/CORE-17088)
> [SECUR32_WINETEST] Update for new WineHQ certificate. CORE-17088

- media/doc/README.FSD
JIRA issue: [CORE-8204](https://jira.reactos.org/browse/CORE-8204)
> [README.FSD] Add 'nfs41 project' entries. CORE-8204

- ntoskrnl/include/internal/io.h
- ntoskrnl/io/pnpmgr/devnode.c
- ntoskrnl/io/pnpmgr/pnpmgr.c
- ntoskrnl/io/pnpmgr/pnpreport.c
- ntoskrnl/ntos.cmake
> [NTOS:IO] Move device node functions from pnpmgr.c to devnode.c

- base/applications/rapps/CMakeLists.txt
- base/applications/rapps/asyncinet.cpp
- base/applications/rapps/available.cpp
- base/applications/rapps/gui.cpp
- base/applications/rapps/include/asyncinet.h
- base/applications/rapps/include/available.h
support specifying an URL for a snapshot
> [RAPPS] snapshot url support

- base/applications/rapps/available.cpp
- base/applications/rapps/gui.cpp
- base/applications/rapps/include/available.h
- Use "Scrnshot" instead of "Snapshot"
*Include changing the folder name used to store screenshots.*
- some other minor rename
nothing is changed functionally in this PR
> [RAPPS] rename variables

- modules/rostests/rosautotest/CConfiguration.cpp
- modules/rostests/rosautotest/CConfiguration.h
- modules/rostests/rosautotest/main.cpp
> [ROSAUTOTEST] Add /t parameter for repeating tests

- dll/win32/crtdll/dllmain.c
- sdk/lib/crt/stdlib/atexit.c
And related improvements.
Addendum to b30bf6de315557f80cfa16574689563dfe08eab5 (r54651).
> [CRT] atexit.c: Fix memory handling

- modules/rostests/apitests/powrprof/power.c
Note that both tests are currently skipped...
> [POWRPROF_APITEST] Fix 2+1 Cppcheck reports

- modules/rostests/winetests/advapi32/service.c
Cherry-pick
https://source.winehq.org/git/wine.git/commit/56a83c585aeb071af29824399e22db5cdce0318a
> [ADVAPI32_WINETEST] test_create_delete_svc(): Fix 'account' size

- base/services/svchost/globals.c
- base/services/svchost/svchost.h
JIRA issue: [CORE-17151](https://jira.reactos.org/browse/CORE-17151)
> [SVCHOST] Fix PSID initialization

- media/doc/3rd Party Files.txt
Addendum to 65780ec (r68685).
NB:
I checked and current ReactOS code does not match upstream 0.6 file...
> [3rd Party Files.txt] Add 'chmc and lzxcomp' entry

- dll/win32/msgina/gui.c
Addendum to 623dd26ccea5e79001aee769c230fb4f8e304fc8.
Part of #2490.
> [MSGINA] gui: Improve 'DlgData_Destroy()'

- drivers/filesystems/cdfs/cdprocs.h
- drivers/storage/floppy_new/floppy.c
> [CDFS][FLOPPY_NEW] Simplify unsupported NT6.2+ workarounds

- base/services/rpcss/setup.c
- base/services/svchost/security.cxx
- dll/cpl/sysdm/userprofile.c
- dll/win32/netid/netid.c
> [REACTOS] Fix GetTokenInformation() usage

- boot/bootdata/hivedef.inf
It works now.
JIRA issue: [CORE-12973](https://jira.reactos.org/browse/CORE-12973)
> [BOOTDATA] Enable 'REG_EXPAND_SZ' for 'kbswitch.exe'

- base/applications/rapps/available.cpp
- base/applications/rapps/cabinet.cpp
- base/applications/rapps/gui.cpp
- base/applications/rapps/installed.cpp
- base/applications/rapps/integrity.cpp
- base/applications/rapps/loaddlg.cpp
- base/applications/rapps/misc.cpp
- base/applications/rapps/settingsdlg.cpp
- base/applications/rapps/unattended.cpp
- base/applications/rapps/winmain.cpp
update some header to newer format, update purpose and add my name to those files I've modified( those I should take responsibilities for them)
> [RAPPS] update some file-header

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
> [IMM32] Add ImmShowSoftKeyboard and ImmDestroySoftKeyboard

- dll/win32/shell32/CDefView.cpp
- Delete `DefMessageSFVCB` method.
- Add some callbacking.
> [SHELL32] Improve callbacking of CDefView

- win32ss/include/ntuser.h
- win32ss/user/ntuser/window.c
- Add `QUERY_WINDOW_*` constant values for `NtUserQueryWindow` funciton.
> [NTUSER] Add more QUERY_WINDOW_* values

- modules/rostests/apitests/shell32/SHAppBarMessage.cpp
- Add workarea checks.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
> [SHELL32_APITEST] Strengthen SHAppBarMessage testcase for workarea

- dll/win32/shell32/lang/pl-PL.rc
pl-pl Polish translation update for new dialog with SHORTCUT
> [SHELL32] Polish translation for "Problem with Shortcut" dialog

- base/applications/fontview/fontview.c
Based on Mark Jansen's patch in CORE-17001. Not tested yet.
JIRA issue: [CORE-17001](https://jira.reactos.org/browse/CORE-17001)
> [FONTVIEW] Fix regression; opening files won't list files

- modules/rostests/kmtests/CMakeLists.txt
- modules/rostests/kmtests/kmtest_drv/testlist.c
- modules/rostests/kmtests/rtl/RtlRangeList.c
- sdk/include/ndk/rtlfuncs.h
- sdk/include/ndk/rtltypes.h
JIRA issue: [CORE-6372](https://jira.reactos.org/browse/CORE-6372)
> [KMTESTS] Add initial tests for range list functions. CORE-6372

- win32ss/user/winsrv/usersrv/lang/he-IL.rc
> [USERSRV] Update Hebrew translation

- dll/win32/shell32/folders/CDrivesFolder.cpp
JIRA issue: [CORE-17041](https://jira.reactos.org/browse/CORE-17041)
> [SHELL32] Fix regression #2703 CORE-17041 (trial)

- base/system/userinit/lang/zh-TW.rc
- base/system/winlogon/lang/zh-TW.rc
- win32ss/user/user32/lang/zh-TW.rc
- win32ss/user/winsrv/usersrv/lang/zh-TW.rc
improved some Traditional Chinese translation for some files.
> [USERINIT][WINLOGON][USER32][USERSRV] Update Traditional Chinese (Taiwan) translation

- README.md
Mention the important legal limitation of contribution in the appropriate place of README
> Legal notice about WRK

- dll/win32/browseui/shellfind/CFindFolder.cpp
Fix column sorting in search results folder.
JIRA issue: [CORE-16825](https://jira.reactos.org/browse/CORE-16825)
> [SHELLFIND] Fix column sorting. CORE-16825

- dll/cpl/appwiz/lang/pt-PT.rc
- dll/cpl/intl/lang/pt-PT.rc
- dll/cpl/liccpa/lang/pt-PT.rc
- dll/cpl/powercfg/lang/pt-PT.rc
[TRANSLATION] Update PT translation for CPL files
> [TRANSLATION] Update PT translation for CPL  files

- dll/win32/shell32/lang/pl-PL.rc
[shell32] [pl-pl] copy to folder  UPDATE
> [shell32] [pl-pl] copy to folder  UPDATE

- dll/win32/shell32/lang/fr-FR.rc
fr-fr French translation update for new dialog with SHORTCUT
> [SHELL32] French translation for "Problem with Shortcut" dialog

- dll/win32/shell32/lang/pl-PL.rc
[shell32] [pl-pl] MoveToFolder Translation
> [shell32] [pl-pl] MoveToFolder Translation

- base/shell/explorer/lang/pl-PL.rc
[Explorer] [pl-pl] Description Fix
> [Explorer] [pl-pl] Description Fix

- dll/win32/browseui/lang/pl-PL.rc
[browseui] [pl-pl] MoveTo Description Fix
> [browseui] [pl-pl] MoveTo Description Fix

- dll/win32/browseui/lang/de-DE.rc
Corrected some mistakes in dll/win32/browseui/lang/de-DE.rc
- 
- 
> [BROWSEUI] Few corrections for de-DE translation

- win32ss/user/ntuser/sysparams.c
JIRA issue: [CORE-12018](https://jira.reactos.org/browse/CORE-12018), [CORE-7237](https://jira.reactos.org/browse/CORE-7237)
> [NTUSER] Improve SPI_SETWORKAREA setting for multiple monitors

- hal/halx86/acpi/halpnpdd.c
- hal/halx86/legacy/halpnpdd.c
- ntoskrnl/include/internal/io.h
- ntoskrnl/io/iomgr/driver.c
- ntoskrnl/io/iomgr/iomgr.c
- ntoskrnl/io/iomgr/ramdisk.c
- ntoskrnl/io/pnpmgr/devaction.c
- ntoskrnl/io/pnpmgr/plugplay.c
- ntoskrnl/io/pnpmgr/pnpinit.c
- ntoskrnl/io/pnpmgr/pnpmgr.c
Now the actions are processed in a serialized way by PipEnumerationWorker.
JIRA issue: [CORE-10456](https://jira.reactos.org/browse/CORE-10456)
> Fix race conditions in PnP manager

- base/applications/rapps/unattended.cpp
- base/applications/rapps/winmain.cpp
trivial improvement about when to call ConInitStdStreams
> [RAPPS] improve when to call  ConInitStdStreams

- base/applications/rapps/CMakeLists.txt
- base/applications/rapps/gui.cpp
- base/applications/rapps/include/settings.h
- base/applications/rapps/include/winmain.h
- base/applications/rapps/settings.cpp
- base/applications/rapps/settingsdlg.cpp
- base/applications/rapps/winmain.cpp
refactor code about settings
now settings are no longer stored in registery in binary form.
but a more human-friendly way.
> [RAPPS] settings read/write refactor

- dll/opengl/mesa/attrib.h
- modules/rosapps/applications/sysutils/regexpl/Completion.h
> [MESA][REGEXPL] Fix clang-cl 10 'Wheader-guard'

- base/shell/explorer/taskswnd.cpp
- Implement `HSHELL_ACTIVATESHELLWINDOW` shell hook.
> [EXPLORER] Implement HSHELL_ACTIVATESHELLWINDOW

- modules/rostests/apitests/atl/CString.cpp
- modules/rostests/apitests/atl/CString.inl
- sdk/lib/atl/cstringt.h
> [ATL][ATL_APITEST] Add CString::Tokenize + testcase

- sdk/tools/cabman/CCFDATAStorage.cxx
- sdk/tools/cabman/CCFDATAStorage.h
- sdk/tools/cabman/CMakeLists.txt
- sdk/tools/cabman/cabinet.cxx
- sdk/tools/cabman/cabinet.h
- sdk/tools/cabman/cabman.cxx
- sdk/tools/cabman/cabman.h
- sdk/tools/cabman/dfp.cxx
- sdk/tools/cabman/dfp.h
- sdk/tools/cabman/mszip.h
- sdk/tools/cabman/raw.h
First round of cleanup
JIRA issue: [CORE-17231](https://jira.reactos.org/browse/CORE-17231)
> [CABMAN] Replace some dynamically allocated strings with std::string

- modules/rostests/apitests/gdi32/CMakeLists.txt
- modules/rostests/apitests/gdi32/StretchBlt.c
- modules/rostests/apitests/gdi32/testlist.c
_Added new code to gdi32_apitest for testing StretchBlt functions._
JIRA issue: [CORE-16642](https://jira.reactos.org/browse/CORE-16642)
> [GDI32_APITEST] Create StretchBlt Regression Test

- sdk/tools/cabman/cabinet.cxx
- sdk/tools/cabman/cabinet.h
JIRA issue: [CORE-17231](https://jira.reactos.org/browse/CORE-17231)
In preparation of  [CORE-17258](https://jira.reactos.org/browse/CORE-17258)
> [CABMAN] Replace linked lists with std::list

- dll/win32/wdmaud.drv/mmixer.c
Fixes crash caused by WdmAudCommitWaveBufferByMMixer due to race conditions.
Code was simulating completion callback using a thread, this resulted in singled threaded code being executed simultaneous by multiple threads.
1. remove thread
2. use NtDeviceIoContol with completion apc (mirrors usage of WriteFileEx in WdmAudCommitWaveBufferByLegacy)
JIRA issue: [CORE-17214](https://jira.reactos.org/browse/CORE-17214)
An excellent first time contribution of Michael Stamper: michaelstamper1@gmail.com
> [WDMAUD.DRV] USE_MMIXER_LIB crash fix

- base/applications/rapps/lang/zh-CN.rc
> [RAPPS] zh-CN translation

- dll/win32/shell32/dialogs/drive.cpp
- While looking at https://jira.reactos.org/browse/CORE-17272 some logging could be improved to better manage such situation
- Logging of name for unknown fs
- Fix some trace content as not only HDD could be affected
> [SHELL32] Improve Format dialog debug log (trivial)

- base/applications/rapps/lang/fr-FR.rc
- win32ss/user/winsrv/consrv/frontends/gui/lang/fr-FR.rc
- Missing French translation for some new items
- Add missing items in French translation
> [RAPPS][CONSRV] French translation update

- dll/win32/browseui/addressband.cpp
- dll/win32/browseui/toolsband.cpp
- win32ss/user/user32/windows/cursoricon.c
- win32ss/user/user32/windows/menu.c
> [BROWSEUI][USER32] Explicitly use some MAKEINTRESOURCEW()

- win32ss/drivers/videoprt/videoprt.c
Add useful variable for debugging video drivers. See https://docs.microsoft.com/ru-ru/previous-versions/ff570170(v=vs.85)
> [VIDEOPRT] Define debug variable

- base/applications/rapps/include/unattended.h
> [RAPPS] update help command

- base/setup/reactos/lang/fr-FR.rc
- dll/cpl/mmsys/lang/fr-FR.rc
- dll/win32/shell32/lang/fr-FR.rc
- 2 typos in MMSYS French ressource file
- Setup ressource for French is missing
- 1 missing item in shell32 French ressource file
- Fix 2 typos in MMSYS French ressource file
- Complete Setup ressource for French
- Full shell32 French ressource file
> [SETUP][MMSYS][SHELL32] Adding missing French translation (and typo fix on existing)

- drivers/crypto/ksecdd/crypt.c
- modules/rostests/apitests/advapi32/RtlEncryptMemory.c
Fixes use of uninitialized memory.
> [KSECDD] Fix RtlEncryptMemory test regression

- base/applications/rapps/unattended.cpp
> [RAPPS] Remove string casts after the conutils fix

- dll/win32/shell32/shellmenu/CStartMenu.cpp
> [SHELL32] Fix usage of return value

- ntoskrnl/ps/query.c
> [NTOS:PS] Fix size handling in ProcessDeviceMap

- ntoskrnl/io/iomgr/driver.c
This removes an old hack, that isn't needed anymore.
> [NTOS] Remove an old hack

- ntoskrnl/mm/ARM3/mminit.c
Fix paged pool initialization on x64
> [NTOS:MM] Fix paged pool initialization on x64

- dll/ntdll/ldr/ldrutils.c
- modules/rostests/apitests/ntdll/NtMapViewOfSection.c
- ntoskrnl/mm/section.c
JIRA issue: [CORE-17284](https://jira.reactos.org/browse/CORE-17284)
> [NTOS:MM] Correctly handle SizeOfRawData

- modules/rosapps/applications/cmdutils/gflags/pageheap.c
Addendum to ec62127.
JIRA issue: [CORE-17325](https://jira.reactos.org/browse/CORE-17325)
> [GFLAGS] ModifyStatus(): Remove a remnant HeapFree()

- boot/bootdata/txtsetup.sif
- drivers/input/CMakeLists.txt
- drivers/input/inport/CMakeLists.txt
- drivers/input/inport/hardware.c
- drivers/input/inport/inport.c
- drivers/input/inport/inport.h
- drivers/input/inport/inport.rc
- drivers/input/inport/ioctl.c
- drivers/input/inport/pnp.c
- drivers/input/inport/wmi.c
- media/inf/msmouse.inf
- ntoskrnl/io/pnpmgr/pnpmgr.c
Basic input support. Driver also supports PC (Untested, but should work).
AFTER:
- Install mouse driver on NEC PC-98 series
- Add driver for bus mouse devices
> [INPORT] Add driver for bus mouse devices

- README.md
Improving the readability of the warning. Now the warning looks and reads better than a huge chunk of text in bold and italics at once.
Replace a piece of bold text with a more elegant paragraph
> Improving the readability of the stability warning

- win32ss/gdi/gdi32/main/dllmain.c
Found with Application Verifier :)
> [GDI32] Prevent double initialization in GdiProcessSetup

- base/applications/rapps/available.cpp
- base/applications/rapps/cabinet.cpp
- base/applications/rapps/include/defines.h
- base/applications/rapps/include/misc.h
- base/applications/rapps/loaddlg.cpp
- base/applications/rapps/settingsdlg.cpp
- sdk/include/psdk/shlwapi.h
- sdk/include/psdk/winbase.h
Building on the work of @kernelbin from GSoC 2020 :)
JIRA issue: [CORE-17258](https://jira.reactos.org/browse/CORE-17258)
> Add rapps support for extracting folders from .cab files

- drivers/filesystems/fastfat/create.c
- drivers/filesystems/fastfat/finfo.c
- drivers/filesystems/fastfat/string.c
- drivers/filesystems/fastfat/vfat.h
_Add testing for these values and return appropriately._
JIRA issue: [CORE-11325](https://jira.reactos.org/browse/CORE-11325)
> [FASTFAT] Fix create for DOT and DOT-DOT leaving bad directory entry

- dll/win32/browseui/aclistisf.cpp
- dll/win32/browseui/aclistisf.h
Implement enumeration of `IShellFolder` items of auto-completion.
BEFORE:
There were many failures.
AFTER:
Successful.
> [BROWSEUI] Implement CLSID_ACListISF

- ntoskrnl/io/iomgr/error.c
Fix few bugs encountered in IoRaiseHardError() while discussing with @Extravert-ir and @ThFabba.
JIRA issue: [CORE-14037](https://jira.reactos.org/browse/CORE-14037).
- Fix buggy retrieval of the current calling Irp->Tail.Overlay.Thread.
- The 4th argument (KernelRoutine) to the KeInitializeApc() is **NOT**
optional; however its 5th argument (RundownRoutine) is.
So use the mandatory routine for freeing the allocated APC instead.
We don't use the rundown routine yet.
- Check whether the ExAllocatePoolWithTag() call failed or not before
queueing the allocated APC.
> [NTOS:IO] Some fixes for IoRaiseHardError().

- dll/win32/dbghelp/compat.h
See:
https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-context
> [DBGHELP] Add missing support for AMD64.

- modules/rostests/apitests/gdi32/GetObject.c
- win32ss/gdi/gdi32/misc/misc.c
Adds a test for GdiFixUpHandle and fix GdiFixUpHandle accordingly
> [GDI32] Fix up GdiFixUpHandle for x64

- ntoskrnl/include/internal/amd64/mm.h
- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/ARM3/miarm.h
- ntoskrnl/mm/ARM3/pagfault.c
- ntoskrnl/mm/ARM3/procsup.c
- ntoskrnl/mm/ARM3/session.c
- ntoskrnl/mm/amd64/init.c
- ntoskrnl/mm/amd64/page.c
- ntoskrnl/mm/mminit.c
This PR includes most of the x64 specific Mm changes of the amd64_bringup branch.
None of the changes should affect x86.
Reviewing might be easier to do by commit, as each commit usually only has a small change, that is easy to understand.
> [NTOS:MM] Merge most of the amd64 changes

- win32ss/drivers/miniport/pc98vid/ioctl.c
- win32ss/drivers/miniport/pc98vid/pc98vid.c
- win32ss/drivers/miniport/pc98vid/pc98vid.h
Addendum to 5c7ce4475e246560d1622b8cc60dc603e3955f66.
- Add missing header file
- Some prototypes are not needed anymore
> [PC98VID] Fix build for PC-98 target

- base/shell/cmd/cmd.rc
- base/shell/cmd/lang/pt-PT.rc
[CMD] Add new portuguese (PT) translation for cmd.rc file
> [CMD] Add new portuguese (PT) translation

- sdk/tools/spec2def/spec2def.c
Relevant for https://github.com/reactos/reactos/pull/3335
> [SPEC2DEF] Implement support for private exports

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtQueryValueKey.c
- modules/rostests/apitests/ntdll/testlist.c
- ntoskrnl/config/cmvalche.c
JIRA issue: [CORE-17358](https://jira.reactos.org/browse/CORE-17358)
> [NTOS:CM] Implement support for KeyValuePartialInformationAlign64. CORE-17358

- ntoskrnl/io/iomgr/driver.c
- ntoskrnl/io/pnpmgr/devnode.c
- ntoskrnl/kd64/kdprint.c
JIRA issue: [CORE-17215](https://jira.reactos.org/browse/CORE-17215)
> [NTOS] Reduce stack usage in some functions.

- sdk/lib/rtl/image.c
We can't run 32 bit images on x64 yet, but we should at least be able to map them and retrieve their resources, etc.
> [RTL] Fix RtlImageDirectoryEntryToData for 32 bit images on x64

- dll/win32/shimgvw/lang/cs-CZ.rc
Updates the Czech translation of shimgvw.
> [SHIMGVW] Update Czech translation

- drivers/bus/acpi/busmgr/utils.c
Addendum to 44f1cf1 (r74559).
JIRA issue: [CORE-12942](https://jira.reactos.org/browse/CORE-12942)
> [ACPI] acpi_create_registry_table(): Close the key handle, on errors

- dll/win32/shell32/lang/pl-PL.rc
> shell32 [pl-pl] lang fix

- drivers/wdm/audio/drivers/CMIDriver/CMakeLists.txt
> [CMIPCI] Compile it as NT5.2, not NT6.0

- drivers/wdm/audio/drivers/CMIDriver/CM8738-x32-WaveRT.inf
- drivers/wdm/audio/drivers/CMIDriver/CM8738-x32.inf
- drivers/wdm/audio/drivers/CMIDriver/CM8738-x64-WaveRT.inf
- drivers/wdm/audio/drivers/CMIDriver/CM8738-x64.inf
- media/doc/3rd Party Files.txt
- media/inf/legcydrv.inf
- media/inf/scsi.inf
- modules/rosapps/drivers/green/green.inf
> [CMIPCI][DOC][GREEN][INF] Fix 7 DriverVer values 

- media/themes/Lunar/lunar.msstyles/lang/cs-CZ.rc
- media/themes/Mizu/mizu.msstyles/lang/cs-CZ.rc
Updates the Czech translation of ReactOS themes.
> [THEMES] Update Czech (cs-CZ) translation

- drivers/storage/class/cdrom_new/cdrom.inf
- drivers/storage/class/disk_new/disk.inf
_Add Russian translation for disk and cdrom class_
_Russian translation for disk and cdrom class_
> Add Russian translation for disk and cdrom class

- media/themes/Lunar/lunar.msstyles/lunar.rc
Fixes a mistake from #3424 where is no reference to the new file with Czech translation in Lunar theme. Everything else is OK.
> [THEMES] Fix Lunar theme

- base/setup/lib/bootsup.c
> [SETUPLIB] Fix 'unlock' copypasta, in a log

- media/inf/defltsv.inf
- media/inf/defltwk.inf
Updates translations in files with default security settings.
> [INF] Update Czech (cs-CZ), Slovak (sk-SK) and Esperanto (eo-AA) translations

- base/applications/rapps/lang/pl-PL.rc
> [RAPPS] Improve Polish translation (pl-PL)

- dll/win32/shimgvw/lang/cs-CZ.rc
Updates the Czech translation of shimgvw.
> [SHIMGVW] Update Czech (cs-CZ) translation

- README.md
A minor correction to README.md.
- Replace "Seven" with "7" to keep in line with Microsoft's official naming
> [TRANSLATION] Update English (United States) (en-US) translation

- dll/win32/browseui/lang/pt-PT.rc
[BROWSEUI] Update PT Translation
> [BROWSEUI] Update PT translation

- modules/rostests/apitests/browseui/CMakeLists.txt
- modules/rostests/apitests/browseui/IAutoComplete.cpp
- modules/rostests/apitests/browseui/testlist.c
Add tests for `IAutoComplete` objects, especially on the drop-down window and related controls.
WinXP:
Win2k3:
Win10:
> [BROWSEUI_APITEST] Add IAutoComplete testcase

- sdk/lib/rtl/CMakeLists.txt
> [RTL_VISTA] CMakeLists.txt: Fix 'rtl' copypasta

- dll/win32/shell32/lang/pl-PL.rc
translated strings from PR #3399
> [shell32] improve Polish [pl-PL] translation

- base/applications/games/solitaire/lang/pl-PL.rc
translated string from PR #3422
> [solitaire] improve Polish [pl-PL] translation

- dll/win32/shell32/dialogs/drive.cpp
Do not outlaw FATX as an unknown filesystem when it's already proposed in the combo listbox.
**JIRA Issue:** [CORE-17272](https://jira.reactos.org/browse/CORE-17272)
> [SHELL32] Determine if the FS is of type FATX

- ntoskrnl/ex/sysinfo.c
- ntoskrnl/ps/query.c
- ntoskrnl/ps/quota.c
- sdk/include/ndk/pstypes.h
Pretty much what the PR title and commit description say. Tested the patch on my backend, ROS works quite nicely without nasty issues or the like.
> [NTOS:PS] Implement PS_QUOTA_TYPE and let the quota code use it

- dll/win32/devmgr/lang/pt-PT.rc
- dll/win32/netid/lang/pt-PT.rc
[DEVMGR] Update PT translation
Readjust objects size to fit all text in Driver tab
[NETID] Update PT translation
> [DEVMGR] Update PT translation

- ntoskrnl/ps/quota.c
Prior to acquiring a quota from the process and do whatever it's needed to do (charge it or return it back), we must guard ourselves with a spinlock so that we may not get into potential race conditions. 
In Windows Server 2003, `PspGivebackQuota` and `PspExpandQuota` do the same thing and they're the equivalent to `PspReturnProcessQuotaSpecifiedPool` and `PspChargeProcessQuotaSpecifiedPool` in our codebase.
> [NTOS:PS] Guard the quota in a spin lock

- modules/rostests/apitests/compiler/pseh.c
> [COMPILER_APITEST] Sync an '#if defined(_X86_)'

- drivers/storage/class/cdrom_new/CMakeLists.txt
Addendum to 83b85e2.
JIRA issue: [CORE-17129](https://jira.reactos.org/browse/CORE-17129)
> [CDROM_NEW] CMakeLists.txt: Add cdrom.rc

- media/doc/3rd Party Files.txt
> [DOC] 3rd Party Files.txt: Use complete MS W.D.S. URLs

- boot/freeldr/freeldr/lib/fs/ext2.c
- boot/freeldr/freeldr/lib/fs/fat.c
- boot/freeldr/freeldr/ntldr/inffile.c
Reduce FreeLdr memory size.
Also reported by CppCheck:
```
BytesToRead -= BytesToRead;<--- Same expression on both sides of '-='.
if (Data != NULL)<--- Condition 'Data!=NULL' is always true
```
JIRA issue: [CORE-14516](https://jira.reactos.org/browse/CORE-14516)
> [FREELDR] Remove a few useless code lines

- base/shell/explorer/syspager.cpp
- base/shell/explorer/taskswnd.cpp
- base/shell/explorer/traywnd.cpp
- dll/shellext/netshell/lanstatusui.cpp
- dll/win32/shell32/shellmenu/CMenuToolbars.cpp
- dll/win32/shell32/shellmenu/CMenuToolbars.h
- sdk/include/reactos/rosctrls.h
Fix some assertions,
hack out some others (they need more ATL work).
[CORE-17505](https://jira.reactos.org/browse/CORE-17505)
> Fix some assertions now that they are enabled

- sdk/lib/atl/CMakeLists.txt
> [ATL] CMakeLists.txt: Use a bare endif()

- dll/shellext/deskadp/lang/pl-PL.rc
>  [DESKADP] Update Polish [pl-PL] translation

- modules/rostests/apitests/browseui/ACListISF.cpp
Add tests for `ACListISF` testcase to clarify the details.
- Improve file header of `ACListISF.cpp`.
- Add tests in `test_ACListISF_CURRENTDIR` function.
Win2k3:
Win10:
> [BROWSEUI_APITEST] Strengthen ACListISF testcase

- dll/win32/syssetup/security.c
Fixes invalid memory access deep in rpc code.
> [SYSSETUP] SamQueryInformationDomain expects a pointer

- dll/cpl/mmsys/lang/pl-PL.rc
> [MMSYS] Update Polish (pl-PL) translation

- dll/cpl/hdwwiz/lang/pl-PL.rc
> [HDWWIZ] Update Polish (pl-PL) translation 

- subsystems/win32/csrsrv/procsup.c
- subsystems/win32/csrsrv/thredsup.c
Fix a deadlock when doing heavily console-related stuff
JIRA issue: [CORE-12461](https://jira.reactos.org/browse/CORE-12461) maybe
> [CSRSRV] Do not hold the lock while destroying dead thread.

- sdk/lib/atl/atlwin.h
Addendum to e076e05.
JIRA issue: [CORE-17505](https://jira.reactos.org/browse/CORE-17505)
> [ATL] CWindowImplBaseT::WindowProc(): Narrow 2 ATLASSERT() down

- ntoskrnl/mm/ARM3/section.c
> [NTOS:MM] Properly fail for invalid sizes of data section mappings

- ntoskrnl/mm/ARM3/sysldr.c
Drivers compiled with a newer SDK check that their cookie is non-default.
This is not the same algorithm as Windows.
> [NTOS:MM] Stubplement cookie generation for drivers

- base/system/chkdsk/chkdsk.rc
- base/system/chkdsk/lang/pt-PT.rc
- base/system/userinit/lang/pt-PT.rc
[CHKDSK] Add Portuguese translation
> [CHKDSK][USERINIT] Add and improve Portuguese (pt-PT) translation

- ntoskrnl/se/token.c
* Guard the token in a lock whilst querying stuff
* Remove the piece of code that checks if the information class provided is above the maximum information class threshold. That code literally duplicates the inner functionality of the default case in the switch block, where the code falls in that case if an invalid information class is provided anyway.
* Remove the redundant information classes. Internally, this function in Windows has 12 switch case blocks (11 token info classes + the default case) and the other classes are supported in NtQueryInformationToken only so it doesn't make any logical sense to keep them in the codebase.
* Annotate the argument parameters with SAL and add documentation header
> [NTOS:SE] Lock the token in SeQueryInformationToken and do some cleanup

- base/system/winlogon/sas.c
- dll/win32/mpr/mpr.spec
- sdk/include/reactos/undocmpr.h
Be consistent...
Noticed while looking into issue CORE 17488.
> [MPR] WNetClearConnections: Enforce HWND parameter type

- dll/win32/msgina/shutdown.c
Do a sanity check onto the dialog box type before terminating it. As it stands now, a call of `PostQuitMessage` is invoked even when the dialog box is modal. This is illegal due to the fact that the shutdown dialog box is initiated by the "Security" main window thus `WlxDialogBoxParam`.
A call to `PostQuitMessage` onto a modal dialog box leads to a undefined behaviour, as it'll not just terminate the thread but also eventually killing the Winlogon process whose the thread belongs to. This fixes [CORE-17535](https://jira.reactos.org/browse/CORE-17535).
> [MSGINA] Determine which kind of dialog box is before terminating it

- dll/cpl/usrmgr/groupprops.c
- dll/cpl/usrmgr/groups.c
- dll/cpl/usrmgr/userprops.c
- dll/cpl/usrmgr/users.c
`UNLEN` + `\0`, as everywhere else.
> [USRMGR] Increase name sizes to 'UNLEN + 1'

- base/applications/mscutils/servman/misc.c
- dll/cpl/mmsys/sounds.c
- modules/rosapps/applications/imagesoft/misc.c
- modules/rostests/winetests/GUI/misc.c
> [REACTOS] InitImageList(): Fix error checks

- base/applications/cacls/cacls.rc
- base/applications/cacls/lang/sr-SP.rc
- base/applications/cacls/lang/sr-SR.rc
2 files (1 modified, 1 added) for the start just to see how it goes.
> [TRANSLATION] Serbian, SR. Start of a new language.

- base/applications/cmdutils/fc/fc.rc
- base/applications/cmdutils/fc/lang/bg-BG.rc
- base/applications/cmdutils/fc/lang/cs-CZ.rc
- base/applications/cmdutils/fc/lang/de-DE.rc
- base/applications/cmdutils/fc/lang/el-GR.rc
- base/applications/cmdutils/fc/lang/en-GB.rc
- base/applications/cmdutils/fc/lang/es-ES.rc
- base/applications/cmdutils/fc/lang/et-EE.rc
- base/applications/cmdutils/fc/lang/fr-FR.rc
- base/applications/cmdutils/fc/lang/he-IL.rc
- base/applications/cmdutils/fc/lang/hu-HU.rc
- base/applications/cmdutils/fc/lang/id-ID.rc
- base/applications/cmdutils/fc/lang/it-IT.rc
- base/applications/cmdutils/fc/lang/ja-JP.rc
- base/applications/cmdutils/fc/lang/nl-NL.rc
- base/applications/cmdutils/fc/lang/no-NO.rc
- base/applications/cmdutils/fc/lang/pl-PL.rc
- base/applications/cmdutils/fc/lang/pt-BR.rc
- base/applications/cmdutils/fc/lang/pt-PT.rc
- base/applications/cmdutils/fc/lang/ro-RO.rc
- base/applications/cmdutils/fc/lang/ru-RU.rc
- base/applications/cmdutils/fc/lang/sk-SK.rc
- base/applications/cmdutils/fc/lang/sq-AL.rc
- base/applications/cmdutils/fc/lang/sv-SE.rc
- base/applications/cmdutils/fc/lang/tr-TR.rc
- base/applications/cmdutils/fc/lang/uk-UA.rc
- base/applications/cmdutils/fc/lang/zh-CN.rc
- base/applications/cmdutils/fc/lang/zh-TW.rc
Enable localization or internationalization (i18n) on FC (file comparison) command, by resource mechanism.
JIRA issue: [CORE-17500](https://jira.reactos.org/browse/CORE-17500)
- Add 27 languages as clone of English.
> [FC][TRANSLATION] FC: Enable localization

- sdk/cmake/config.cmake
- sdk/include/crt/mingw32/intrin_x86.h
- sdk/lib/crt/math/exp2.c
- sdk/lib/crt/math/exp2f.c
> [CMAKE][CRT] Fix a few minor copypastas

- dll/cpl/joy/lang/he-IL.rc
Update the Hebrew translation.
לעניות ידיעתי, כרגע אין תקן לתרגום של המיזם הזה. מה דעתכם על שימוש ב[תקן של קיי־די־אי](https://il.kde.org/hebrew/guidelines/) או ב[תקן של מיזם גז״ר](http://wiki.hamakor.org.il/index.php/Gezer)?‏
> [JOY] Update Hebrew (he-IL) translation

- base/applications/cmdutils/fc/lang/pl-PL.rc
fc cmd tool, "POLISH pl-pl" translation
> [FC] Polish (pl-PL) translation

- ntoskrnl/include/internal/ob.h
- ntoskrnl/ob/devicemap.c
> [NTOS:OB] ObQueryDeviceMapInformation(): Fix annotations

- ntoskrnl/se/token.c
> [NTOS:SE] Get the session ID and assign it to the new token

- ntoskrnl/include/internal/ex.h
- ntoskrnl/include/internal/i386/intrin_i.h
- ntoskrnl/include/internal/i386/ke.h
- ntoskrnl/include/internal/ke.h
- ntoskrnl/include/internal/ke_x.h
- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/ARM3/miarm.h
- ntoskrnl/mm/ARM3/mminit.c
- ntoskrnl/mm/ARM3/procsup.c
- ntoskrnl/mm/ARM3/session.c
- ntoskrnl/mm/ARM3/wslist.cpp
- ntoskrnl/ntos.cmake
- sdk/include/ndk/kefuncs.h
- sdk/include/ndk/mmtypes.h
Split #3300 into something which can be hopefully reviewed.
Implement initializing, adding & removing entries into working set list.
Not used yet, but can be tested in #3300.
With some C++ inside the kernel :open_mouth: 
At process initialisation time, properly initialize the working set list.
Implement adding entries to it (private pages only for now).
Implement removing entries from it (private pages only).
Implement growing/shrinking the WSLE array.
Implement trimming it.
Ready to be reviewed.
> [NTOS:MM] Make Working Set Lists usable

- base/setup/usetup/lang/de-DE.h
- base/system/userinit/livecd.c
- dll/cpl/sysdm/general.c
- sdk/include/psdk/wincon.h
- subsystems/win32/csrsrv/api.c
- win32ss/user/winsrv/consrv/alias.c
- win32ss/user/winsrv/consrv/frontends/wcwidth.c
Fix some Clang warnings.
JIRA issue: [CORE-17545](https://jira.reactos.org/browse/CORE-17545)
See commits.
> Fix some Clang warnings

- base/setup/usetup/mui.c
Currently it's WIP, more to come.
> [USETUP][MUI] Loop over next MUI entries with the same ID

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/RtlGetLengthWithoutLastFullDosOrNtPathElement.c
- modules/rostests/apitests/ntdll/RtlpApplyLengthFunction.c
- modules/rostests/apitests/ntdll/testlist.c
- sdk/lib/rtl/path.c
JIRA issue: [CORE-11990](https://jira.reactos.org/browse/CORE-11990)
> Implement RtlGetLengthWithoutLastFullDosOrNtPathElement and RtlpApplyLengthFunction

- sdk/tools/pefixup.c
1. Some improvements:
- Only recalculate the PE checksum if the image is not from a reproducible build (with original checksum == 0).
- Section names are case-sensitive, so we can just use strncmp() instead of the non-standard strncasecmp() for names comparisons.
- Avoid multi-level nesting of code with the error handling done at the very end. Use size_t variables for file sizes.
2. A fix:
- Use vfprintf() with the va_args list.
3. The new functionality:
Add support for overriding the attributes of specific PE sections.
Use a syntax identical to the one from the EDITBIN tool:
`--section:name[=newname][,[[!]{CDEIKOMPRSUW}][A{1248PTSX}]]`
https://docs.microsoft.com/en-us/cpp/build/reference/section-editbin?view=msvc-160
Should also help with PR #3594
> PEFIXUP: Improvements and add support for overriding section attributes

- drivers/storage/class/cdrom_new/cdrom.inf
Added Polish pl-PL translation
> [CDROM_NEW] Add Polish (pl-PL) translation

- drivers/storage/class/disk_new/disk.inf
Added Polish pl-PL translation
> [DISK_NEW] Add Polish (pl-PL) translation

- win32ss/drivers/miniport/pc98vid/ioctl.c
- win32ss/drivers/miniport/pc98vid/pc98vid.c
- win32ss/drivers/miniport/pc98vid/pc98vid.h
Addendum to 3adf45086743d5f075e4270af7af64017eb01d63
Also isolate the constant structures into page section
and restore the previous sections for start IO and entrypoint routines.
> [PC98VID] Fix MSVC 2015 build for PC-98 target

- ntoskrnl/include/internal/ke.h
- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/ARM3/miarm.h
- ntoskrnl/mm/ARM3/pagfault.c
- ntoskrnl/mm/ARM3/procsup.c
- ntoskrnl/mm/ARM3/virtual.c
- ntoskrnl/mm/ARM3/wslist.cpp
- ntoskrnl/mm/marea.c
> [NTOS:MM] Add process private pages to its working set

- drivers/usb/usbccgp/misc.c
- drivers/usb/usbhub/debug.c
> Mute usbdebug

- ntoskrnl/cc/view.c
Fix use of unintialized variable (caught by RTC1)
> [NTOS:CC] Fix use of unintialized variable (caught by RTC1)

- ntoskrnl/ke/amd64/cpu.c
- ntoskrnl/ke/amd64/stubs.c
- ntoskrnl/ke/amd64/trap.S
- ntoskrnl/ke/amd64/usercall.c
- sdk/include/asm/trapamd64.inc
- sdk/lib/crt/crt.cmake
- sdk/lib/crt/libcntpr.cmake
- sdk/lib/crt/math/amd64/sqrt.S
This is stuff that I consider ready to merge. Everythig is x64 only!
> Merge a bunch of commits from amd64-bringup branch

- sdk/include/asm/asm.inc
- sdk/lib/rtl/amd64/except_asm.S
- sdk/lib/rtl/amd64/stubs.c
* [RTL] Improve RtlInitializeContext
* [RTL] Improve RtlCaptureContext
* [RTL] Implement RtlRestoreContext
> [RTL] Improve / implement amd64 context functions

- ntoskrnl/se/srm.c
This implements `SepRmDeleteLogonSession`. Also declare a prototype for `SepCleanupLUIDDeviceMapDirectory` and annotate it with SAL.
> [NTOS:SE] Implement logon session deletion

- base/system/winlogon/lang/pl-PL.rc
[winlogon] [pl-PL] update:
-restarting
-shutting down
> [WINLOGON] Polish translation update

- dll/win32/browseui/lang/pl-PL.rc
> [BROWSEUI] Polish translation update

- base/shell/explorer/lang/pl-PL.rc
[explorer] [pl-PL] update
cosmetical changes...
> [EXPLORER] Polish translation update

- CMakeLists.txt
Addendum to fae2044 (r51783).
JIRA issue: [CORE-17604](https://jira.reactos.org/browse/CORE-17604)
> [CMAKE] CMakeLists.txt: Fix 'omap-zoom2' typo

- ntoskrnl/ke/amd64/interrupt.c
- ntoskrnl/ke/amd64/trap.S
"Good" enough to not hit a break point.
> [NTOS:KE] Improve KeConnectInterrupt

- modules/rostests/kmtests/rtl/RtlStack.c
- ntoskrnl/rtl/libsupp.c
Fixes wrong behavior of RtlPcToFileHeader. KM test included.
> [RTL][KMTEST] RtlPcToFileHeader doesn't handle user mode images in kernel mode

- modules/rostests/apitests/atl/CMakeLists.txt
- modules/rostests/apitests/atl/CString.inl
- sdk/lib/atl/cstringt.h
> Atl cstring operator !=

- base/setup/usetup/lang/pl-PL.h
> [USETUP] Polish translation update

- ntoskrnl/mm/ARM3/miarm.h
- ntoskrnl/mm/i386/page.c
- ntoskrnl/mm/section.c
Fix stuff.
JIRA issue: [CORE-17587](https://jira.reactos.org/browse/CORE-17587)
- Fix MI_MAKE_HARDWARE_PTE_KERNEL: Currently it creates read/write PTEs whatever the protection it is handed to.
- Try fix CORE-17587 with debug prints to see what happens on test bot
> Core 17587

- ntoskrnl/include/internal/icif.h
- ntoskrnl/include/internal/ps_i.h
- ntoskrnl/se/token.c
> [NTOSKRNL] Use IQS_NONE for non existent classes

- win32ss/win32k.spec
Checked against Windows XP x64 and Windows 8 ARM.
This also fixes VMware user-mode display driver on x64.
Before:
After:
> [WIN32K] Add x64/arm exports

- sdk/tools/check_packing.py
Help detect stuff like 9229e73f03
> [SDK] Add script to check includes with modified struct packing

- drivers/network/tcpip/include/tcp.h
- drivers/network/tcpip/include/titypes.h
- drivers/network/tcpip/tcpip/ainfo.c
- drivers/network/tcpip/tcpip/dispatch.c
- drivers/network/tcpip/tcpip/fileobjs.c
- drivers/network/tcpip/tcpip/icmp.c
- ntoskrnl/ke/wait.c
- sdk/lib/drivers/ip/transport/datagram/datagram.c
- sdk/lib/drivers/ip/transport/rawip/rawip.c
- sdk/lib/drivers/ip/transport/tcp/accept.c
- sdk/lib/drivers/ip/transport/tcp/event.c
- sdk/lib/drivers/ip/transport/tcp/tcp.c
- sdk/lib/drivers/ip/transport/udp/udp.c
- sdk/lib/drivers/lwip/src/include/rosip.h
- sdk/lib/drivers/lwip/src/rostcp.c
Unbreak the most broken. Split #3672 on Timo's request.
JIRA issue: [CORE-6473](https://jira.reactos.org/browse/CORE-6473)
> [TCPIP][IP] Use as eresource instead of a spinlock as locking mechanism

- ntoskrnl/cc/view.c
- ntoskrnl/include/internal/cc.h
- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/section.c
> [NTOS:CC][NTOS:MM] 2 functions: Fix Iosb annotation

- ntoskrnl/CMakeLists.txt
- ntoskrnl/include/internal/mm.h
- ntoskrnl/io/pnpmgr/pnpmgr.c
- ntoskrnl/ke/amd64/cpu.c
- ntoskrnl/ke/amd64/stubs.c
- ntoskrnl/mm/ARM3/pagfault.c
- ntoskrnl/mm/ARM3/pfnlist.c
- ntoskrnl/mm/ARM3/procsup.c
Fix duplicated symbols
Enforce -fno-common
Fix PFN tracing
JIRA issue: [CORE-17595](https://jira.reactos.org/browse/CORE-17595) maybe
Lots of rambling.
> Random fixes for ntoskrnl

- hal/halx86/apic.cmake
- hal/halx86/apic/apic.c
- hal/halx86/apic/apicp.h
- hal/halx86/apic/apicsmp.c
- Use an enum for the APIC registers
- Add support routine for SMP.
> [HAL:APIC] Improve code

- dll/win32/comctl32/datetime.c
_Update comctrl from Wine with fix._
JIRA issue: [CORE-17199](https://jira.reactos.org/browse/CORE-17199)
> [COMCTL32] Sync datetime.c to Wine-6.0

- sdk/include/ddk/kernelspecs.h
- sdk/include/psdk/driverspecs.h
> [SDK] Add missing sal annotations in driverspecs.h and kernelspec.h

- dll/win32/netapi32/wksta_new.c
- sdk/lib/rtl/amd64/unwind.c
* [RTL/x64] Properly handle UNW_FLAG_CHAININFO
* [NETAPI32] Zero out lpNameBuffer in NetGetJoinInformation
* [NTDLL_APITEST] Add test for some user mode exceptions
* [NTOS:KE/x64] Handle user faults in KiGeneralProtectionFaultHandler
> Misc x64 fixes

- dll/win32/imm32/imm.c
- sdk/include/reactos/imm32_undoc.h
- Rewrite `imm32!ImmGetDescriptionA` and `imm32!ImmGetDescriptionW` functions.
> [IMM32] Rewrite ImmGetDescriptionA/W

- dll/win32/imm32/imm.c
- Rewrite `imm32!ImmGetConversionStatus` function.
> [IMM32] Rewrite ImmGetConversionStatus

- dll/ntdll/ldr/ldrpe.c
> [NTDLL] LdrpWalkImportDescriptor(): Fix 'Status' copypasta

- win32ss/drivers/videoprt/resource.c
Addendum to 25eae4b (r54237).
JIRA issue: [CORE-17651](https://jira.reactos.org/browse/CORE-17651) (Point 3)
Return unchanged `Irp` status.
> [VIDEOPRT] Fix 'Irp->IoStatus.Information' copypasta

- dll/win32/imm32/imm.c
- Rewrite `ImmCreateIMCC`, `ImmDestroyIMCC`, `ImmReSizeIMCC`, `ImmGetIMCCLockCount`, `ImmUnlockIMCC`, `ImmLockIMCC`, `ImmGetIMCCSize` functions.
> [IMM32] Rewrite IMCC handling functions

- dll/win32/imm32/imm.c
- win32ss/include/ntuser.h
- Rewrite `ImmIsIME` function.
- Fix `enum IMEINFOEXCLASS`.
> [IMM32] Rewrite ImmIsIME (Retry)

- dll/win32/imm32/imm.c
- Rewrite `ImmGetOpenStatus` function.
> [IMM32] Rewrite ImmGetOpenStatus

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/CAutoComplete.h
Improve auto-completion without timeout and jerky of typing.
- Make auto-completion multi-threaded.
> [BROWSEUI] Multithreaded auto-completion

- .github/workflows/build.yml
- sdk/cmake/msvc.cmake
- sdk/include/crt/math.h
- sdk/include/crt/stdlib.h
- sdk/lib/crt/math/_hypotf.c
- sdk/lib/crt/math/acosf.c
- sdk/lib/crt/math/asinf.c
- sdk/lib/crt/math/atan2f.c
- sdk/lib/crt/math/atanf.c
- sdk/lib/crt/math/ceilf.c
- sdk/lib/crt/math/cosf.c
- sdk/lib/crt/math/coshf.c
- sdk/lib/crt/math/div.c
- sdk/lib/crt/math/expf.c
- sdk/lib/crt/math/floorf.c
- sdk/lib/crt/math/fmodf.c
- sdk/lib/crt/math/hypot.c
- sdk/lib/crt/math/ldiv.c
- sdk/lib/crt/math/log10f.c
- sdk/lib/crt/math/logf.c
- sdk/lib/crt/math/sinf.c
- sdk/lib/crt/math/sinhf.c
- sdk/lib/crt/math/sqrtf.c
- sdk/lib/crt/math/tanf.c
- sdk/lib/crt/math/tanhf.c
- sdk/lib/crt/mem/memchr.c
- sdk/lib/crt/mem/memmove.c
This PR fixes MSVC Release builds for both x86 and x64 and adds them as build types to GitHub actions.
The x64 Release build doesn't boot, the x86 one crashes in 2nd stage.
> Fix msvc release build

- dll/win32/imm32/imm.c
- Implement `ImmGetCandidateListCountA` and `ImmGetCandidateListCountW` functions by using newly defined `ImmGetCandidateListCountAW` function.
> [IMM32] Rewrite ImmGetCandidateListCountA/W

- dll/win32/imm32/imm.c
- Rewrite `ImmGetCompositionWindow` function.
> [IMM32] Rewrite ImmGetCompositionWindow

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
- Rewrite `ImmGetDefaultIMEWnd` function.
- Add `g_dwImm32Flags` global variable.
- Add `Imm32QueryWindow` helper function.
- Implement `CtfImmIsCiceroEnabled` function.
> [IMM32] Rewrite ImmGetDefaultIMEWnd

- dll/win32/imm32/imm.c
- Rewrite `ImmGetIMEFileNameA` and `ImmGetIMEFileNameW` functions.
> [IMM32] Rewrite ImmGetIMEFileNameA/W

- modules/rostests/kmtests/CMakeLists.txt
- modules/rostests/kmtests/kmtest_drv/testlist.c
- modules/rostests/kmtests/ntos_se/SeLogonSession.c
- ntoskrnl/se/srm.c
- sdk/include/xdk/setypes.h
**Windows Server 2003 SP2**
**ReactOS**
> [NTOS:SE] Implement logon session termination notification

- dll/win32/imm32/imm.c
- Rewrite `ImmGetCandidateWindow` function.
> [IMM32] Rewrite ImmGetCandidateWindow

- dll/win32/imm32/imm.c
- Rewrite `ImmGetStatusWindowPos` function.
> [IMM32] Rewrite ImmGetStatusWindowPos

- sdk/lib/crt/math/arm/__rt_div_worker.h
- sdk/lib/crt/math/arm/__rt_sdiv.c
- sdk/lib/crt/math/arm/__rt_sdiv64.s
- sdk/lib/crt/math/arm/__rt_udiv.c
- sdk/lib/crt/math/arm/__rt_udiv64.s
> __rt_div fixes for arm

- dll/win32/imm32/imm.c
- sdk/include/reactos/imm32_undoc.h
- Fix `Imm32HeapAlloc` function.
- Fix `ImmUnlockClientImc` function.
> [IMM32] Improve ImmUnlockClientImc and Imm32HeapAlloc

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
- sdk/include/reactos/imm32_undoc.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/ntstubs.c
- Add `IMEDPI` structure to `ntuser.h`.
- Implement `ImmLockImeDpi`/`ImmUnlockImeDpi` functions.
- Rewrite `ImmSetOpenStatus` function.
- Modify some NTUSER function prototypes.
> [IMM32] Imm(Lock|Unlock)ImeDpi and ImmSetOpenStatus

- dll/win32/imm32/imm.c
- Rewrite `imm32!ImmSetStatusWindowPos` function.
> [IMM32] Rewrite ImmSetStatusWindowPos

- dll/win32/imm32/imm.c
- Rewrite `imm32!ImmNotifyIME` function.
> [IMM32] Rewrite ImmNotifyIME

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
- Implement `imm32!ImmLoadLayout` function.
> [IMM32] Implement ImmLoadLayout

- dll/win32/imm32/imm.c
- Rewrite `imm32!ImmSetCompositionWindow` function.
> [IMM32] Rewrite ImmSetCompositionWindow

- modules/rostests/apitests/crt/__rt_div.c
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/testlist.c
Addendum to f2bc1f0e and f1e2c6cb.
> [CRT_APITEST] Add tests for __rt_sdiv/udiv/sdiv64/udiv64 on ARM

- modules/rostests/apitests/crt/__fto64.c
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/testlist.c
- sdk/lib/crt/math/arm/__dtoi64.s
- sdk/lib/crt/math/arm/__dtoi64_worker.c
- sdk/lib/crt/math/arm/__dtou64.s
- sdk/lib/crt/math/arm/__dtou64_worker.c
- sdk/lib/crt/math/arm/__fto64_worker.h
- sdk/lib/crt/math/arm/__stoi64.s
- sdk/lib/crt/math/arm/__stoi64_worker.c
- sdk/lib/crt/math/arm/__stou64.s
- sdk/lib/crt/math/arm/__stou64_worker.c
- sdk/lib/crt/math/math.cmake
- sdk/lib/crt/msvcrtex.cmake
JIRA issue: [CORE-17703](https://jira.reactos.org/browse/CORE-17703)
> [CRT/ARM] Implementations of __dtoi64,__dtou64,__stoi64 and __stou64

- dll/win32/imm32/imm.c
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ntstubs.c
- Add `Imm32IsValidHimc`, `Imm32BuildHimcList` and `Imm32AllocAndBuildHimcList` helper functions.
- Rewrite `ImmEnumInputContext` function by using them.
- Modify `NtUserBuildHimcList`.
> [IMM32] Rewrite ImmEnumInputContext

- dll/win32/imm32/imm.c
- Rewrite `ImmInstallIMEA` function.
> [IMM32] Rewrite ImmInstallIMEA

- dll/win32/imm32/imm.c
- Implement `ImmGetGuideLineA` and `ImmGetGuideLineW` functions.
> [IMM32] Implement ImmGetGuideLineA/W

- dll/win32/imm32/imm.c
- Rewrite `ImmSetConversionStatus` function.
> [IMM32] Rewrite ImmSetConversionStatus

- win32ss/user/ntuser/main.c
- win32ss/user/ntuser/ntuser.c
- win32ss/user/ntuser/ntuser.h
> [WIN32K] Init User part after GDI one.

- ntoskrnl/mm/section.c
When opening the file for write access, FS driver calls this routine. ~Read the data from the file & make it resident in RAM for opened image maps.~ 
Treat it like MmFlushForDelete, add a FIXME regarding the MmFlushForDelete part.
> [NTOS:MM] Implement MmFlushImageSection(MmFlushForWrite)

- dll/win32/imm32/imm.c
- Rewrite `ImmSetCandidateWindow` function.
> [IMM32] Rewrite ImmSetCandidateWindow

- dll/win32/imm32/imm.c
- Rewrite `ImmGetVirtualKey` function.
> [IMM32] Rewrite ImmGetVirtualKey

- dll/win32/imm32/imm.c
- Rewrite `ImmRegisterWordW` function.
> [IMM32] Rewrite ImmRegisterWordW

- dll/win32/imm32/imm.c
- Rewrite `ImmUnregisterWordA` function.
> [IMM32] Rewrite ImmUnregisterWordA

- dll/win32/imm32/imm.c
- Rewrite `ImmUnregisterWordW` function.
> [IMM32] Rewrite ImmUnregisterWordW

- dll/win32/imm32/imm.c
- Rewrite `ImmGetConversionListA` and `ImmGetConversionListW` functions.
- Delete useless `convert_candidatelist_AtoW` and `convert_candidatelist_WtoA` functions.
> [IMM32] Rewrite ImmGetConversionListA/W

- dll/win32/imm32/imm.c
- Rewrite `ImmGetProperty` function.
> [IMM32] Rewrite ImmGetProperty

- dll/win32/imm32/imm.c
- win32ss/include/imetable.h
- Rewrite `ImmEnumRegisterWordA` and `ImmEnumRegisterWordW` functions.
- Modify `win32ss/include/imetable.h`.
> [IMM32] Rewrite ImmEnumRegisterWordA/W

- modules/rostests/apitests/imm32/CMakeLists.txt
- modules/rostests/apitests/imm32/ImmIsUIMessage.c
- modules/rostests/apitests/imm32/testlist.c
Proof of concept on `ImmIsUIMessageA/W`.
- Add `ImmIsUIMessage` testcase in `IMM32_APITEST`.
> [IMM32_APITEST] Add ImmIsUIMessage testcase

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
- Implement `ImmWINNLSGetIMEHotkey` function.
> [IMM32] Implement ImmWINNLSGetIMEHotkey

- win32ss/include/ntuser.h
- win32ss/user/ntuser/win32.h
- win32ss/user/ntuser/window.c
- Improve `NtUserQueryWindow` function.
- Add `IMC` structure.
- Modify `THREADINFO` structure.
> [NTUSER] Improve NtUserQueryWindow

- dll/win32/iernonce/CMakeLists.txt
- dll/win32/iernonce/dialog.cpp
- dll/win32/iernonce/dialog.h
- dll/win32/iernonce/iernonce.cpp
- dll/win32/iernonce/iernonce.spec
- dll/win32/iernonce/include/registry.h
- dll/win32/iernonce/registry.cpp
Display a dialog to show progress, add a thread to execute commands.
I will investigate how iernonce works under win2k3 later, perhaps another PR for it.
> [IERNONCE] Display a dialog to show progress, add a thread to execute.

- base/applications/taskmgr/perfdata.c
Use less (useless) resources.
- Call `NtQuerySystemInformation()` once only, with a minimal struct only.
- Save number of handles only.
> [TASKMGR] Handles: Get number only, skip data

- base/setup/lib/bootsup.c
- boot/bootdata/livecd.ini
> [BOOTDATA][SETUPLIB] Sync HAL/option names between Boot and Live CDs

- hal/halx86/apic/apic.c
> [HALX86:APIC] apic.c: Use new defines some more

- base/applications/drwtsn32/main.cpp
- base/applications/mspaint/registry.cpp
- base/applications/rapps/misc.cpp
Follow-up to 42e111f.
- Add 2 `else`.
- Remove 2 `Close()` calls.
> [REACTOS] Review CRegKey uses

- dll/win32/imm32/CMakeLists.txt
- dll/win32/imm32/candidate.c
- dll/win32/imm32/guideline.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/nt3.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/regword.c
- dll/win32/imm32/utils.c
The `imm.c` file became big and bloated, so we split the source file.
- Split the `IMM32` code and do formatting.
> [IMM32] Restructure! (Retry)

- win32ss/user/ntuser/scrollbar.c
_Added conditional checks to single line of scrollbar update code._
JIRA issues: [CORE-17754](https://jira.reactos.org/browse/CORE-17754) and [CORE-17755](https://jira.reactos.org/browse/CORE-17755)
_Fix both JIRA issues noted above._
> [NTUSER] Improve Themed Scrollbars by Minimizing Updates.

- dll/win32/imm32/imm.c
- sdk/include/psdk/imm.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ntstubs.c
- Rewrite `ImmAssociateContextEx` function.
- Modify `NtUserAssociateInputContext` prototype.
> [IMM32] Rewrite ImmAssociateContextEx

- ntoskrnl/se/sd.c
Implement the portion chunk of code that is responsible for setting the system access control list (SACL) to the World security descriptor, based from SeWorldSid (World security identifier).
> [NTOS:SE] Set the SACL to the World security descriptor

- dll/win32/imm32/imm.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- Improve `Imm32CleanupContext` and `ImmLockClientImc` functions.
- Add `ValidateHandleNoErr` and `Imm32CheckImcProcess` helper functions.
- Delete needless functions.
> [IMM32] Improve Imm32CleanupContext and ImmLockClientImc

- dll/win32/imm32/imm.c
- Rewrite `ImmAssociateContext` function.
> [IMM32] Rewrite ImmAssociateContext

- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- Re-implement `ImmSetActiveContext` function.
- Modify `NtUserNotifyIMEStatus` prototype.
- Improve `ImmSetConversionStatus` and `ImmSetOpenStatus` functions.
> [IMM32] Rewrite ImmSetActiveContext

- base/applications/rapps/appview.cpp
- base/applications/rapps/configparser.cpp
- base/applications/rapps/include/appview.h
- base/applications/rapps/include/configparser.h
- base/applications/rapps/include/gui.h
- base/applications/rapps/include/misc.h
- base/applications/rapps/misc.cpp
- base/applications/rapps/winmain.cpp
* Cache ini sections
* Lock window updates while adding entries
* Remove dead code
> [RAPPS] Speed up app loading

- dll/win32/imm32/imm32.spec
- dll/win32/imm32/keymsg.c
- Implement `ImmSystemHandler` function.
- Add `Imm32UnknownProcess1` and `Imm32SendChange` helper functions.
> [IMM32] Implement ImmSystemHandler

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/ntstubs.c
- win32ss/user/ntuser/object.c
- win32ss/user/ntuser/userfuncs.h
- Implement `NtUserDestroyInputContext` function.
> [WIN32SS][NTUSER] Implement NtUserDestroyInputContext

- dll/win32/advapi32/wine/security.c
The WINE's implementation of this function is nothing but a pile of hacks (and a stub) as it only duplicates the token and that's it. So refactor the code and properly implement it by calling `NtFilterToken`.
This has to be merged only when #4056 is merged into master.
> [ADVAPI32] Properly implement CreateRestrictedToken

- base/applications/drwtsn32/drwtsn32.cpp
- base/applications/drwtsn32/main.cpp
- base/applications/drwtsn32/stacktrace.cpp
- base/applications/drwtsn32/sysinfo.cpp
Please note that this is not verified yet, but it builds (tm)
> [DRWTSN32] Implement arm context reading

- dll/shellext/fontext/CFontCache.hpp
- dll/shellext/fontext/CFontExt.cpp
- dll/shellext/fontext/CFontMenu.cpp
- dll/shellext/fontext/precomp.h
- dll/shellext/mydocs/CMyDocsDropHandler.cpp
- dll/shellext/sendmail/CDeskLinkDropHandler.cpp
- dll/win32/shell32/CCopyToMenu.cpp
- dll/win32/shell32/CCopyToMoveToMenu.h
- dll/win32/shell32/CMakeLists.txt
- dll/win32/shell32/CMoveToMenu.cpp
- dll/win32/shell32/COpenWithMenu.cpp
- dll/win32/shell32/droptargets/CFSDropTarget.cpp
- dll/win32/shell32/shldataobject.cpp
- dll/win32/shell32/shlfolder.cpp
- dll/win32/shell32/stubs.cpp
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/SHGetAttributesFromDataObject.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/psdk/shlobj.h
- sdk/include/reactos/shellutils.h
* Implement SHGetAttributesFromDataObject (+tests)
* Simplify HIDA usage in various shell extensions
* Fix FONTEXT font installation (drag font to font folder will now succeed + refresh the font view)
> [SHELL][SHELLEXT] Implement SHGetAttributesFromDataObject, simplify HIDA usage

- boot/bootdata/hivesys.inf
- drivers/bus/isapnp/isapnphw.h
- media/inf/machine.inf
Support PnP hardware on C-bus.
> [ISAPNP] Add support for NEC PC-98 series

- sdk/cmake/config.cmake
Make arm(64) ports ever so closer to building
JIRA issue: 
- Don't force x86 specifics on everybody
> arm64 fixes

- dll/win32/shell32/folders/CControlPanelFolder.cpp
Fixes context menus not invoking commands when right clicking for Control panel items
Change the context menu ID offset
> [SHELL32] Control panel context menu bugfix

- sdk/lib/crt/stdio/file.c
A first/small step to more sync.
> [CRT] stdio/file.c: Import 3 Wine one-liner fixes

- sdk/include/psdk/winuser.h
> [PSDK] Unduplicate QS_RAWINPUT

- configure.cmd
JIRA issue: [CORE-17733](https://jira.reactos.org/browse/CORE-17733)
> [CONFIGURE] Add support for 'Visual Studio 2022, v17.x'

- base/setup/usetup/lang/pt-PT.h
[USETUP] Remove duplicate word
[USETUP]  Improve pt-PT translation
[USETUP]  Fix typos
> [USETUP] Improve pt-Pt Translation

- base/applications/wordpad/lang/hr-HR.rc
- base/applications/wordpad/rsrc.rc
Translate Wordpad to Craotian
JIRA issue: no issue
-  Update rsrc.rc
-  Upload hr-HR.rc
No tasks to do, I builded and tested
> Wordpad translation

- win32ss/user/ntuser/window.c
Based on I_Kill_Bugs' patch.
JIRA issue: [CORE-12052](https://jira.reactos.org/browse/CORE-12052)
- Move the code of linking the window.
> [NTUSER] Fix where linking newly created window is done

- win32ss/user/ntuser/window.c
- win32ss/user/user32/windows/window.c
- Check `FNID_GHOST` and `MsqIsHung`.
> [NTUSER][USER32] Simplify user32.IsHungAppWindow

- sdk/include/crt/vadefs.h
- Add a entry to the vadefs macros for arm64
JIRA issue: [CORE-17621](https://jira.reactos.org/browse/CORE-17621)
> [CRT] Add vadefs entry for arm64

- drivers/network/dd/e1000/CMakeLists.txt
- drivers/network/dd/e1000/hardware.c
- drivers/network/dd/e1000/info.c
- drivers/network/dd/e1000/interrupt.c
- drivers/network/dd/e1000/ndis.c
- drivers/network/dd/e1000/nic.h
- drivers/network/dd/e1000/send.c
- Add support for 64-bit counters (Intel gigabit NICs)
- Properly handle OIDs
- Check that the packet filter is not 0
- Performance increase
> [E1000] Minor improvements

- base/applications/taskmgr/graphctl.c
- base/applications/taskmgr/graphctl.h
- base/applications/taskmgr/perfpage.c
* also the graph stays preserved on the show/hide kernel time toggle
* an attempt to clean up the collected cruft was made as well
> [TASKMGR] Preserve graphs history on resizes

- base/applications/taskmgr/taskmgr.c
- `HideWhenMinimized = FALSE;` at `LoadSettings` function.
- `AlwaysOnTop = TRUE;` at `LoadSettings` function.
> [TASKMGR] Make 'Hide When Minimized' non-default

- dll/keyboard/kbdcr/kbdcr.c
Croatian keyboards are QWERTZ.
JIRA issue: unknown
Update kbdcr.c
Nothing, I builded and tested in virtual machine and works.
> [KEYBOARD] Switch to QWERTZ for Croatian keyboard layout

- dll/win32/msv1_0/CMakeLists.txt
- dll/win32/msv1_0/lsa.c
- dll/win32/msv1_0/lsa.h
- dll/win32/msv1_0/msv1_0.c
- dll/win32/msv1_0/msv1_0.spec
- dll/win32/msv1_0/ntlm/global.c
- dll/win32/msv1_0/ntlm/global.h
- dll/win32/msv1_0/precomp.h
- dll/win32/msv1_0/user.c
- dll/win32/msv1_0/user.h
- dll/win32/msv1_0/usercontext.c
- dll/win32/msv1_0/usercontext.h
…alize)
This commit fixes a bug too.
Old code of SpUserModeInitialze returns a pointer to a local variable (SECPKG_USER_FUNCTION_TABLE).
> [MSV1_0] Create stubs for SECPKG_USER_FUNCTION_TABLE

- boot/bootdata/hivesft.inf
Improve "Open with" registry info.
JIRA issue: [CORE-17814](https://jira.reactos.org/browse/CORE-17814)
- Uncomment the EMF/WMF file type info.
> [BOOTDATA] Support EMF/WMF metafile file types

- dll/win32/msv1_0/CMakeLists.txt
- dll/win32/msv1_0/lsa.c
- dll/win32/msv1_0/lsa.h
- dll/win32/msv1_0/msv1_0.c
- dll/win32/msv1_0/msv1_0.h
- dll/win32/msv1_0/ntlm/global.c
- dll/win32/msv1_0/ntlm/global.h
- dll/win32/msv1_0/ntlm/protocol.h
- dll/win32/msv1_0/ntlm/util.c
- dll/win32/msv1_0/ntlm/util.h
- dll/win32/msv1_0/precomp.h
- dll/win32/msv1_0/sam.c
- dll/win32/msv1_0/sam.h
This PR is part of sspi-bringup.
It implements (partly) network login. No (ntlm-)calculations will done so far. This part is left out and will follow any time.
However code is already working in sspi-bringup.
> [MSV1_0] Partly implement network login (part 1-5)

- base/applications/mspaint/common.h
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/precomp.h
- base/applications/mspaint/scrollbox.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/sizebox.cpp
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/toolsmodel.h
- base/applications/mspaint/winproc.cpp
Our code became too complicated. Try to simplify.
- Define `Zoomed` and `UnZoomed` helper functions.
- Use them.
> [MSPAINT] Add Zoomed and UnZoomed and use them

- dll/cpl/sysdm/lang/es-ES.rc
Some strings were not translated. Fix it.
> [SYSDM] Enhance Spanish translation

- base/applications/cmdutils/attrib/attrib.c
_Add additional functionality to attrib command._
JIRA issue: [CORE-16284](https://jira.reactos.org/browse/CORE-16284)
_Attempt to add remaining unimplemented items to attrib command._
This should allow @ThFabba's functions mentioned below to work correctly.
In addition there is now a very close symmetry between the "PrintAttribute" and "ChangeAttribute" functions of the program.
> [ATTRIB] Attrib command improvements

- modules/rostests/kmtests/ntos_io/IoCreateFile_drv.c
Avoid crashing in IoCreateFile test when pool allocations are failed
> [KMTESTS:IO] …Avoid crashing in IoCreateFile

- base/applications/drwtsn32/drwtsn32.rc
- base/applications/drwtsn32/lang/es-ES.rc
Spanish translation was not created. Fix it.
> [DRWTSN32] Spanish Translation

- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/ntuser.h
- win32ss/user/ntuser/win32.h
- Add `IS_IMM_MODE()` macro to `ntuser.h`.
- Add `W32PF_DISABLEIME` flag to `win32.h`.
- Modify `NtUserDisableThreadIme` prototype.
- Implement `NtUserDisableThreadIme` function.
> [NTUSER] Implement NtUserDisableThreadIme

- sdk/lib/atl/atlwin.h
Implement few missing simple CWindow getters.
In particular, `GetWindowText(CSimpleString&)` is one missing that is needed by RAPPS (currently it's hacked into the RAPPS-specific CUiWindow class, in rosui.h).
_I suppose they are trivial enough for not necessitating any unit tests (and we don't have any for any of the CWindow functions in our `rostests/apitests/atl` module...). If you don't agree please let me know._
> [SDK:ATL] Implement GetDlgItemText(BSTR&), GetTopLevelParent(), GetWindowText(CSimpleString&).

- dll/win32/imm32/compstr.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- sdk/include/reactos/undocuser.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ntstubs.c
- Modify `NtUserQueryInputContext` prototype.
- Implement `NtUserQueryInputContext` function.
- Add `enum QUERY_INPUT_CONTEXT (QIC_*)` to `undocuser.h`.
> [NTUSER] Implement NtUserQueryInputContext

- dll/win32/imm32/imm.c
- sdk/include/reactos/undocuser.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ntstubs.c
- Modify `NtUserUpdateInputContext` prototype.
- Implement `NtUserUpdateInputContext` function.
- Add `enum UPDATE_INPUT_CONTEXT (UIC_*)` to `undocuser.h`.
> [NTUSER] Implement NtUserUpdateInputContext

- base/applications/mplay32/lang/es-ES.rc
Some strings were not translated. Fix this.
> [MPLAY32] Enhance spanish translation

- dll/shellext/netshell/lang/pt-PT.rc
[NETSHELL] Fix typos and improvements to pt-PT translation.
> [NETSHELL] Fix typos and improvements to pt-PT translation

- win32ss/drivers/videoprt/registry.c
- win32ss/drivers/videoprt/videoprt.c
even if kernel mode does not care.
> [VIDEOPRT] Match Zw*Key() DesiredAccess values

- base/applications/mspaint/drawing.cpp
- base/applications/mspaint/drawing.h
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/lang/ja-JP.rc
- base/applications/mspaint/palette.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/selection.h
- base/applications/mspaint/toolsettings.cpp
JIRA issue: [CORE-17969](https://jira.reactos.org/browse/CORE-17969)
- Fix Japanese `IDS_MINIATURETITLE` resource string.
- Fix Japanese `IDM_VIEWSHOWMINIATURE` menu item text.
- Fix `DWORD` as `COLORREF`.
- Improve some `OnPaint`'s.
> [MSPAINT] Some minor improvements

- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- Modify `NtUserSetImeInfoEx` prototype.
- Add `UserSetImeInfoEx` helper function.
- Implement `NtUserSetImeInfoEx` function.
> [NTUSER] Implement NtUserSetImeInfoEx

- win32ss/include/ntuser.h
- win32ss/user/ntuser/ntstubs.c
- Modify `NtUserSetThreadLayoutHandles` prototype.
- Implement `NtUserSetThreadLayoutHandles` function.
> [NTUSER] Implement NtUserSetThreadLayoutHandles

- dll/win32/netapi32/misc.c
- dll/win32/samsrv/domain.c
- [SAMSRV] Return correct status for existing groups and users
- [NETAPI32] NetpNtStatusToApiStatus: Update accordingly
Maybe it even fixes some API tests, but I didn't checked.
> Fix net command output for PR #4096

- base/applications/network/net/cmdUser.c
- base/applications/network/net/main.c
- base/applications/network/net/net.h
- sdk/include/reactos/mc/netmsgmsg.mc
Several net improvements.
- Add translation for net command
- Simplify conditions
> [NET] Some improvements

- base/applications/msconfig_new/lang/zh-CN.rc
- base/applications/notepad/lang/zh-CN.rc
- base/applications/utilman/lang/zh-CN.rc
- base/applications/utilman/utilman.rc
- base/shell/explorer/lang/zh-CN.rc
Some improvements about grammar and punctuation.
> [TRANSLATION] Update Simplified Chinese (zh-CN) translation

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/ntstubs.c
- Add `UserBuildHimcList` helper function.
- Implement `NtUserBuildHimcList` function.
> [NTUSER] Implement NtUserBuildHimcList

- dll/cpl/sysdm/lang/pl-PL.rc
Addendum to https://github.com/reactos/reactos/commit/ecfd01eefc430876a95cbaca595d2f2e6f52a215 and other
CC: @reactos/lang-polish
> [SYSDM] Update pl translation

- modules/rostests/apitests/win32nt/ntuser/NtUserGetThreadState.c
JIRA issue: [CORE-17732](https://jira.reactos.org/browse/CORE-17732)
- Add some paramters to test on.
WinXP:
Successful.
Win2k3:
Successful.
> [WIN32KNT_APITEST] Strengthen NtUserGetThreadState testcase

- ntoskrnl/mm/ARM3/virtual.c
Makes MS videoprt work in ROS.
Dedicated to @hpoussin
> [NTOS:MM] Implement partial virtual region releases.

- base/shell/explorer/precomp.h
- base/shell/explorer/syspager.cpp
- base/shell/explorer/taskswnd.cpp
- base/shell/explorer/traywnd.cpp
JIRA issue: [CORE-18013](https://jira.reactos.org/browse/CORE-18013)
- Enable `_DEBUG` if debugging.
- Fix assertion failures.
> [EXPLORER] Enable _DEBUG and fix assertion failures

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/ntstubs.c
- Move the IMM-related code from `ntstubs.c` into `ime.c`.
> [NTUSER] Move IMM-related code to ime.c

- win32ss/user/ntuser/ime.c
- Add some code to `NtUserSetImeOwnerWindow` function.
- Add `IntGetTopLevelWindow` helper function.
> [NTUSER] Half-implement NtUserSetImeOwnerWindow

- win32ss/user/ntuser/ime.c
- Rewrite `NtUserDestroyInputContext` function.
- Move `IntAssociateInputContext` function.
> [NTUSER] Rewrite NtUserDestroyInputContext

- hal/halx86/apic/apic.c
First, wait for the APIC to be idle before requesting an interrupt. Then, wait until we actually see the interrupt request bit set.
This will ensure that if we're at a low enough IRQL, the software interrupt will happen immediately (which is an invariant that Windows's IRQL mechanism relies on).
JIRA issue: [CORE-17663](https://jira.reactos.org/browse/CORE-17663)
> [HAL:APIC] Ensure the interrupt gets requested immediately in ApicRequestSelfInterrupt.

- base/applications/mspaint/dib.cpp
- base/applications/mspaint/dib.h
- base/applications/mspaint/drawing.cpp
- base/applications/mspaint/drawing.h
- base/applications/mspaint/history.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/selectionmodel.h
- base/applications/mspaint/winproc.cpp
JIRA issue: [CORE-16634](https://jira.reactos.org/browse/CORE-16634)
- Add `SkewDIB` helper function in `dib.cpp`.
- Implement Stretch and Skew feature by `SelectionModel::StretchSkew` and `ImageModel::StretchSkew`.
- Move `ColorKeyedMaskBlt` function.
> [MSPAINT] Implement skew

- dll/win32/shell32/shlexec.cpp
Added a check (PathIsExeW) to SHELL_execute to prevent it from executing non-exe files
JIRA issue: [CORE-18038](https://jira.reactos.org/browse/CORE-18038)
> [SHELL32] Stop SHELL_execute from always executing files

- README.md
Add link to Discord server in README
Upadate README.md
> [README] Add Discord server in README

- dll/shellext/fontext/CFontMenu.cpp
- dll/win32/shell32/CDefaultContextMenu.cpp
- dll/win32/shell32/debughlp.cpp
- dll/win32/shell32/debughlp.h
- dll/win32/shell32/droptargets/CFSDropTarget.cpp
- dll/win32/shell32/folders/CFSFolder.cpp
JIRA issue: [CORE-17691](https://jira.reactos.org/browse/CORE-17691)
> [SHELL32] CDefaultContextMenu: Provide a fallback property sheet

- win32ss/user/user32/controls/scrollbar.c
JIRA issue: [CORE-18048](https://jira.reactos.org/browse/CORE-18048)
> [USER32] SetScrollPos should not bypass UserApiHook

- drivers/wdm/audio/drivers/ac97/ac97.rc
- Improve AC'97 audio driver version info
> [AC97] Improve version info

- base/applications/taskmgr/taskmgr.rc
- Add task manager version info
> [TASKMGR] Add version info

- dll/win32/shell32/dialogs/drive.cpp
JIRA issue: [CORE-18073](https://jira.reactos.org/browse/CORE-18073)
> [SHELL32] Do not reopen the drive properties dialog on cancel

- boot/freeldr/freeldr/include/fs/ntfs.h
- boot/freeldr/freeldr/lib/fs/ntfs.c
Minor changes to Freeloader that will allow booting from NTFS volume.
> [FREELDR] Allow booting from NTFS volume.

- base/applications/utilman/umandlg/lang/ru-RU.rc
- base/applications/utilman/umandlg/lang/uk-UA.rc
- dll/shellext/cryptext/lang/uk-UA.rc
- dll/win32/browseui/CShellTaskScheduler.cpp
- dll/win32/browseui/CShellTaskScheduler.h
- dll/win32/browseui/CUserAssist.cpp
- dll/win32/browseui/CUserAssist.h
- dll/win32/imm32/compstr.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/utils.c
- dll/win32/kernel32/client/file/iocompl.c
- dll/win32/profmap/profmap.c
- dll/win32/syssetup/lang/ru-RU.rc
- dll/win32/syssetup/wizard.c
- win32ss/reactx/ntddraw/dxeng.c
Use my current email address for all copyrights in the code.
Change it to Gmail, because Yandex disabled ua domain, which was used in my previous email. So due to this, an old address doesn't exist anymore, so it cannot receive a new email letters.
Although I might just continue using Yandex address with a new domain, but IMHO Gmail has much less problems.
> Update email in all my copyrights

- base/applications/regedit/lang/pt-PT.rc
- dll/cpl/access/lang/pt-PT.rc
[CPL.ACCESS] Improve pt-PT translation
[CPL:ACCESS] Adjust object position for better appearance
[[REGEDIT] Update pt-PT translation and object adjustement
> [ACCESS] [REGEDIT] Improve pt-PT translation

- dll/win32/shell32/dialogs/filetypes.cpp
[SHELL32]  Remove horizontal scrollbar from IDC_FILETYPES_LISTVIEW
in FileTypes Dialog
> [SHELL32]  Remove horizontal scrollbar from IDC_FILETYPES_LISTVIEW in FileTypes … 

- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/precomp.h
- Rename `g_csImeDpi` as `gcsImeDpi`.
> [IMM32] Renaming: s/g_csImeDpi/gcsImeDpi/

- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/precomp.h
- Rename `g_pImeDpiList` as `gpImeDpiList`.
- Add `Win:` comment.
> [IMM32] Renaming: s/g_pImeDpiList/gpImeDpiList/

- base/system/diskpart/lang/pl-PL.rc
diskpart update help in lang pl-pl
> [DISKPART] Update Polish (pl-PL) translation

- boot/bootdata/bootcd/unattend.inf
- dll/win32/syssetup/wizard.c
This allows to add environment variables during unattended setup
> [SYSSETUP] Add new Env section to unattend.inf

- win32ss/user/ntuser/ime.c
Refactoring.
- Improve `NtUserDestroyInputContext` and related codes.
> [NTUSER] Improve NtUserDestroyInputContext etc.

- win32ss/user/ntuser/ime.c
Set the last error code correctly.
> [NTUSER] Set error on NtUserCreateInputContext

- dll/win32/imm32/ime.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- Add `Win:` comments to some IMM functions.
> [IMM32] Add Win: comments more

- dll/win32/imm32/imm.c
- dll/win32/imm32/utils.c
Improve code readability.
- Improve `ImmLockClientImc` function.
- Add `Win:` comment to `Imm32CheckImcProcess` function.
> [IMM32] Improve ImmLockClientImc

- drivers/network/dd/CMakeLists.txt
- drivers/network/dd/nvnet/CMakeLists.txt
- drivers/network/dd/nvnet/backoff.c
- drivers/network/dd/nvnet/debug.h
- drivers/network/dd/nvnet/eth.h
- drivers/network/dd/nvnet/init.c
- drivers/network/dd/nvnet/interrupt.c
- drivers/network/dd/nvnet/netnv.inf
- drivers/network/dd/nvnet/nic.c
- drivers/network/dd/nvnet/nic.h
- drivers/network/dd/nvnet/nvnet.c
- drivers/network/dd/nvnet/nvnet.h
- drivers/network/dd/nvnet/nvnet.rc
- drivers/network/dd/nvnet/phy.c
- drivers/network/dd/nvnet/phyreg.h
- drivers/network/dd/nvnet/requests.c
- drivers/network/dd/nvnet/send.c
- hal/halx86/generic/usage.c
- sdk/include/psdk/ntddndis.h
Support networking on OG Xbox.
JIRA issue: [CORE-15872](https://jira.reactos.org/browse/CORE-15872)
> [NVNET] Add driver for nForce-based NICs 

- win32ss/user/ntuser/desktop.c
- win32ss/user/ntuser/ime.c
- Add `IntImeSetFutureOwner`, `IntGetLastTopMostWindowNoIME`, `IntImeSetTopMost`, and `IntImeCheckTopmost` helper functions.
- Implement `NtUserSetImeOwnerWindow` function.
> [NTUSER] Implement NtUserSetImeOwnerWindow

- modules/rostests/apitests/gdi32/GetObject.c
[GDI32_APITEST] Add CursorIcon GetObject test case
CORE-17752
> [GDI32_APITEST] Add CursorIcon GetObject test case

- base/system/diskpart/lang/en-US.rc
- base/system/diskpart/lang/pl-PL.rc
- base/system/diskpart/lang/pt-PT.rc
- base/system/diskpart/lang/ro-RO.rc
- base/system/diskpart/lang/ru-RU.rc
- base/system/diskpart/lang/sq-AL.rc
- base/system/diskpart/lang/tr-TR.rc
- base/system/diskpart/lang/zh-CN.rc
- base/system/diskpart/lang/zh-TW.rc
To Fix Volume Number & Label Issue to protect table layout of diskpart's `list volume` command
JIRA issue: [CORE-18138](https://jira.reactos.org/browse/CORE-18138)
- Made Volume label to output only 11 characters at max
- Made Volume numbering left padded
> [DISKPART] Fixed Volume Number & Label Issue

- dll/win32/browseui/explorerband.cpp
Addendum to 0c47416 (r72003).
JIRA issue: [CORE-12804](https://jira.reactos.org/browse/CORE-12804)
Co-Authored-By: Victor Martinez Calvo <...>
> [BROWSEUI] Remove useless variable and unreachable code

- drivers/filesystems/fs_rec/fs_rec.c
- drivers/filesystems/udfs/Include/regtools.cpp
- drivers/filesystems/udfs/udfinit.cpp
- drivers/ksfilter/ks/connectivity.c
- drivers/ksfilter/ks/image.c
- drivers/serial/serial/pnp.c
- drivers/wdm/audio/legacy/wdmaud/mmixer.c
- drivers/wdm/audio/legacy/wdmaud/sup.c
Match Zw*() uses.
JIRA issue: [CORE-10207](https://jira.reactos.org/browse/CORE-10207)
This PR covers most of `drivers` directory.
A few less trivial cases will be submitted separately.
> [DRIVERS] Add some OBJ_KERNEL_HANDLE

- drivers/sac/driver/util.c
Match Zw*() uses.
Plus:
- GetRegistryValueBuffer(): Add missing ZwClose(Handle), Fix a copypasta.
- SetRegistryValue(): 1 s/NtClose/ZwClose/.
JIRA issue: [CORE-10207](https://jira.reactos.org/browse/CORE-10207)
> [SACDRV] Add 2 OBJ_KERNEL_HANDLE

- ntoskrnl/ke/amd64/cpu.c
- ntoskrnl/ke/i386/cpu.c
Fix CPU-Revision and Type
JIRA issue: [CORE-17974](https://jira.reactos.org/browse/CORE-17974)
use correct amount of nibbles to determine CPU-Revision and Type
> [NTOS:KE] Fix CPU family and model detection

- dll/keyboard/kbdja/kbdja.c
Simplify the code to improve readability.
- Delete the duplicated key data.
> [KDBJA] Delete duplicate key entries

- ntoskrnl/mm/ARM3/mdlsup.c
- ntoskrnl/mm/ARM3/procsup.c
- ntoskrnl/mm/ARM3/section.c
- ntoskrnl/mm/ARM3/virtual.c
Charge quotas for VAD allocations and free the quotas again when the VADs are freed.
JIRA issue: [CORE-18028](https://jira.reactos.org/browse/CORE-18028)
> [NTOS:MM] Charge and free quotas for VAD allocations

- win32ss/CMakeLists.txt
- win32ss/gdi/eng/ldevobj.c
- win32ss/gdi/eng/mouse.c
- win32ss/gdi/eng/pandisp.c
- win32ss/gdi/eng/pdevobj.c
Implement panning driver (virtual screen resolution > real screen resolution ; move viewport with mouse)
- Fix LDEVOBJ_bProbeAndCaptureDevmode, so panning feature is preserved in devmode capture
- Fix some problems with DrvMovePointer graphics callbacks
- Implement panning driver
> Video panning driver

- base/applications/notepad/dialog.c
- base/applications/notepad/main.h
When typing text on NotePad, then NotePad title bar flickers.
- Save previous modification flag.
- If no change in modification flag, do not set the title bar text.
> [NOTEPAD] Less flickering title bar

- modules/rosapps/applications/fraginator/DriveVolume.cpp
…Fraginator
_Set BitmapSize to zero so DeviceIOControl doesn't fail_
JIRA issue: [ROSAPPS-332](https://jira.reactos.org/browse/ROSAPPS-332)
_Make Fraginator working again_
> [FRAGINATOR] Fix some uninitialized variables and make it work again

- modules/rostests/apitests/ntdll/NtQueryInformationToken.c
- ntoskrnl/se/tokencls.c
`TokenGroupsAndPrivileges ` is the younger sister of two `TokenGroups` and `TokenPrivileges` classes. In its purpose there's no huge substantial differences apart that this class comes with its own structure, **TOKEN_GROUPS_AND_PRIVILEGES**, and that this structure comes with extra information.
> [NTOS:SE] Implement token groups & privileges querying

- base/applications/taskmgr/procpage.c
- Fix `DevicePathToDosPath`, don't use the same in-out buffer.
- Also simplify functions related to [59dcec1](https://github.com/reactos/reactos/commit/59dcec1fafcb27ad18b246d34531e3373c8c1012)
> [TASKMGR] Process page: Fix DevicePathToDosPath

- sdk/lib/drivers/ip/network/address.c
Properly handle BitTest reaching 0.
JIRA issue: [CORE-18225](https://jira.reactos.org/browse/CORE-18225)
> [IP] AddrCountPrefixBits(): Fix loop condition

- dll/ntdll/CMakeLists.txt
- dll/ntdll/def/ntdll.spec
- ntoskrnl/rtl/libsupp.c
- sdk/lib/rtl/CMakeLists.txt
- sdk/lib/rtl/amd64/dynfntbl.c
- sdk/lib/rtl/amd64/unwind.c
Implement x64 dynamic function table support functions.
> [RTL] Implement dynamic function tables for x64

- modules/rostests/apitests/ntdll/RtlGetNtProductType.c
> [NTDLL_APITEST] Fix RtlGetNtProductType test

- sdk/include/crt/emmintrin.h
Implement intrinsics in emmintrin.h
> [CRT] Add emmintrin.h

- base/shell/explorer/taskswnd.cpp
Fix taskbar icon display problem mentioned in [PR #4488](https://github.com/reactos/reactos/pull/4488)
> [EXPLORER] Fix taskbar icon display problem

- sdk/include/crt/math.h
- sdk/lib/crt/math/round.c
- sdk/lib/crt/math/roundf.c
- sdk/lib/crt/msvcrtex.cmake
Add round and roundf and add it to msvcrtex to make clang v14 happy
> [CRT] Add round and roundf

- sdk/lib/cmlib/CMakeLists.txt
- sdk/lib/cmlib/cmlib.h
Re-enables PAGED_CODE() asserts in the kernel.
> Don't redefine PAGED_CODE() to nothing in cmlib.h except for cmlib_host

- dll/win32/imm32/ime.c
- dll/win32/imm32/imm32.spec
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- sdk/include/ddk/immdev.h
- win32ss/user/user32/misc/imm.c
Implement inter-process menu item retrieving.
- Implement `ImmPutImeMenuItemsIntoMappedFile` function.
- Implement `Imm32GetImeMenuItemWInterProcess` function.
> [IMM32][USER32] ImmPutImeMenuItemsIntoMappedFile

- win32ss/user/ntuser/kbdlayout.c
Improve security. Based on @ThFabba's idea.
- Add local variable `ustrNameSafe` and use it as cache.
> [NTUSER] Security: Follow-up of #4595

- dll/win32/imm32/keymsg.c
Some detailed investigation has found the real function names.
We want to use concrete names rather than unknown names.
- Renaming some functions and some structures.
- Converting C++-style comments to C-style comments.
- `s/IMM_UNKNOWN_PROCESS1/IMM_DELAY_SET_LANG_BAND/`
- `s/Imm32UnknownProcess1Proc/Imm32DelaySetLangBandProc/` (Win: `DelaySetLangBand`)
- `s/Imm32UnknownProcess1/CtfImmSetLangBand/` (Win: `CtfImmSetLangBand`)
- `s/Imm32SendChangeProc/Imm32SendNotificationProc/` (Win: `SendNotificationProc`)
- `s/Imm32SendChange/Imm32SendNotification/` (Win: `ImmSendNotification`)
> [IMM32] Renaming around ImmSystemHandler

- win32ss/include/ntuser.h
- win32ss/user/ntuser/kbdlayout.c
- Add `IntHKLtoPKL`, `co_UserActivateKeyboardLayout`, `IntReorderKeyboardLayouts`, and `co_IntActivateKeyboardLayout` helper functions.
- Rewrite `NtUserUnloadKeyboardLayout` by using helper functions.
> [NTUSER] Refactor NtUserUnloadKeyboardLayout

- win32ss/user/ntuser/window.c
- Send `WM_IME_SYSTEM:IMS_LOADTHREADLAYOUT` message at `IntCreateWindow` function.
- Improve code.
> [NTUSER] Send WM_IME_SYSTEM:IMS_LOADTHREADLAYOUT at IntCreateWindow

- base/applications/cmdutils/reg/lang/zh-TW.rc
- base/system/diskpart/diskpart_msg.mc
- base/system/diskpart/lang/zh-TW.rc
- dll/win32/hhctrl.ocx/lang/Zh.rc
update Chinese Traditional (zh-TW) translation
Update translation for:
- REG
- DISKPART
- hhctrl.ocx
> [TRANSLATION] Update Traditional Chinese (zh-TW) translation - Jun 2022

- win32ss/user/ntuser/kbdlayout.c
Implementing Japanese input... We have to send `WM_IME_SYSTEM:IMS_SENDNOTIFICATION` at keyboard layout activation.
- Add code to `co_UserActivateKeyboardLayout` function for IME.
- Add `IntImmActivateLayout` helper function.
> [NTUSER] Empower co_UserActivateKeyboardLayout

- base/applications/osk/lang/ru-RU.rc
> [OSK] Update Russian translation (ru-RU)

- win32ss/user/user32/misc/imm.c
- In `ImeWndProc_common`, correctly get/set the `PIMEUI` value by `Get/SetWindowLongPtrW`.
> [USER32] Get/SetWindowLongPtr about PIMEUI

- dll/cpl/input/layout_list.c
Improve code readability. `LayoutList_Create` function was too complicated.
- Add `LayoutList_ReadLayout` helper function.
- Improve and simplify `LayoutList_Create` function.
> [INPUT] Refactor LayoutList_Create

- ntoskrnl/mm/ARM3/kdbg.c
> [NTOS:MM] kdbg.c: Fix Argv[n] copypastas

- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/user32/windows/input.c
Reverts reactos/reactos#4632 (ea2d32b)
[CORE-18338](https://jira.reactos.org/browse/CORE-18338)
> Revert "[USER32] Fix HKL value in IntLoadKeyboardLayout" (ea2d32b)

- dll/win32/kernel32/kernel32.rc
JIRA issue: [CORE-18177](https://jira.reactos.org/browse/CORE-18177)
- Move `#pragma code_page(65001)` line.
> [KERNEL32] Fix kernel32.rc for UTF-8 codepage

- dll/cpl/usrmgr/CMakeLists.txt
- dll/cpl/usrmgr/groupprops.c
- dll/cpl/usrmgr/misc.c
- dll/cpl/usrmgr/userprops.c
- dll/cpl/usrmgr/usrmgr.h
- Current code uses "MessageBox" with leftover of old debug code
- Proposed modification is to use DPRINT instead
JIRA issue: [CORE-18276](https://jira.reactos.org/browse/CORE-18276)
> [USRMGR] Replace old (leftover) debug MessageBox with Wine macros

- dll/shellext/zipfldr/CZipExtract.cpp
- dll/shellext/zipfldr/resource.h
- dll/shellext/zipfldr/zipfldr.rc
> [ZIPFLDR] Show icon on the taskbar

- dll/win32/syssetup/syssetup.rc
Added Tango Desktop Project icons to the list of used projects
> [SYSSETUP] Add Tango Desktop Project icons to the list of used projects

- media/doc/3rd Party Files.txt
> [DOC] 3rd Party Files.txt: Add 3rdparty/ to some sdk/lib/ paths

- media/inf/hdc.inf
> [INF] Add description for IDE-compatible controllers

- dll/cpl/hotplug/hotplug.c
- Add small icon to the title bar
- Set large icon correctly
Jira issue: [CORE-15445](https://jira.reactos.org/browse/CORE-15445)
> [HOTPLUG] Add title bar icon

- dll/cpl/hotplug/hotplug.rc
- dll/cpl/hotplug/lang/fr-FR.rc
> [HOTPLUG] Add French (fr-FR) translation

- base/shell/explorer/traywnd.cpp
Improves code that was added by 0.4.15-dev-5078-g 46de3a22acc964f27a5260e144089125f83586ff without any review yesterday.
JIRA issue: [CORE-15369](https://jira.reactos.org/browse/CORE-15369)
> [EXPLORER] Cleanup after last commit CORE-15369

- dll/appcompat/apphelp/apphelp.c
- dll/appcompat/apphelp/apphelp.spec
- dll/appcompat/apphelp/shimeng.c
- dll/appcompat/shims/layer/versionlie.inl
- dll/win32/msi/CMakeLists.txt
- dll/win32/msi/package.c
This is a bit of a hack (how it's implemented, that is),
but for now it is 'good enough'
Also includes a fix to a shim that has been broken from day 1.
[CORE-18362](https://jira.reactos.org/browse/CORE-18362)
> [MSI] Allow shims to be used on a setup

- media/doc/WINESYNC.txt
- modules/rostests/winetests/bcrypt/CMakeLists.txt
- modules/rostests/winetests/bcrypt/bcrypt.c
This supersedes half of #195.
JIRA issue: [ROSTESTS-296](https://jira.reactos.org/browse/ROSTESTS-296)
- Import, as is, the next 2 commits from Wine.
> [BCRYPT_WINETEST] Wine Sync, to let it load on WXP and WS03

- base/applications/mscutils/eventvwr/eventvwr.c
- base/applications/mscutils/eventvwr/eventvwr.h
- base/applications/mscutils/eventvwr/eventvwr.rc
- base/applications/mscutils/eventvwr/evtdetctl.c
- base/applications/mscutils/eventvwr/evtdetctl.h
- base/applications/mscutils/eventvwr/lang/bg-BG.rc
- base/applications/mscutils/eventvwr/lang/cs-CZ.rc
- base/applications/mscutils/eventvwr/lang/de-DE.rc
- base/applications/mscutils/eventvwr/lang/el-GR.rc
- base/applications/mscutils/eventvwr/lang/en-US.rc
- base/applications/mscutils/eventvwr/lang/es-ES.rc
- base/applications/mscutils/eventvwr/lang/fr-FR.rc
- base/applications/mscutils/eventvwr/lang/he-IL.rc
- base/applications/mscutils/eventvwr/lang/it-IT.rc
- base/applications/mscutils/eventvwr/lang/ja-JP.rc
- base/applications/mscutils/eventvwr/lang/ko-KR.rc
- base/applications/mscutils/eventvwr/lang/no-NO.rc
- base/applications/mscutils/eventvwr/lang/pl-PL.rc
- base/applications/mscutils/eventvwr/lang/pt-BR.rc
- base/applications/mscutils/eventvwr/lang/pt-PT.rc
- base/applications/mscutils/eventvwr/lang/ro-RO.rc
- base/applications/mscutils/eventvwr/lang/ru-RU.rc
- base/applications/mscutils/eventvwr/lang/sk-SK.rc
- base/applications/mscutils/eventvwr/lang/sq-AL.rc
- base/applications/mscutils/eventvwr/lang/sv-SE.rc
- base/applications/mscutils/eventvwr/lang/tr-TR.rc
- base/applications/mscutils/eventvwr/lang/uk-UA.rc
- base/applications/mscutils/eventvwr/lang/zh-CN.rc
- base/applications/mscutils/eventvwr/resource.h
- Update file headers.
- Simplify some duplicated code.
> Minor cleanup for EventVwr

- dll/win32/shell32/CDefView.cpp
- dll/win32/shell32/CDefaultContextMenu.cpp
- dll/win32/shell32/dialogs/drive.cpp
- dll/win32/shell32/dialogs/fprop.cpp
- dll/win32/shell32/folders/CDrivesFolder.cpp
- dll/win32/shell32/folders/CFSFolder.cpp
- dll/win32/shell32/shlfolder.cpp
- dll/win32/shell32/wine/shell32_main.h
- sdk/include/reactos/shellutils.h
JIRA issue: [CORE-18386](https://jira.reactos.org/browse/CORE-18386)
> [SHELL32] Show file / drive properties at the position where the mouse was.

- win32ss/user/ntuser/draw.c
- win32ss/user/user32/windows/draw.c
> Revert "[USER32][NTUSER] Fill by white in DrawFrameControl:DFC_MENU"

- dll/win32/shell32/CDefaultContextMenu.cpp
- dll/win32/shell32/folders/CDesktopFolder.cpp
This restores the 'properties' functionality on the desktop
Bug found by Hervé Poussineau
> [SHELL32] Fix menu item handling

- dll/win32/shell32/CDefaultContextMenu.cpp
> [SHELL32] Fix 'Paste' command in context menu not working

- win32ss/user/ntuser/ime.c
Improve code readability and fix some minor stuffs.
- Add comments.
- Use the `LOWORD` value for `VK_PACKET` detection.
- `IntGetImeHotKeyByKeyAndLang` accepts neutral language identifier.
> [NTUSER] Improve IntSetImeHotKey

- dll/cpl/desk/lang/pl-PL.rc
desk.cpl, hide,change icons pl-pl update
> [DESK] Update Polish (pl-PL) translation

- dll/win32/imm32/candidate.c
- dll/win32/imm32/compstr.c
- dll/win32/imm32/ctf.c
- dll/win32/imm32/guideline.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/regword.c
- dll/win32/imm32/utils.c
- dll/win32/imm32/win3.c
Totally improve debuggability.
- Strengthen tracing.
- Introduce `IS_NULL_UNEXPECTEDLY`, `IS_ZERO_UNEXPECTEDLY` etc. macros to manage tracing.
- Add `Imm32UnitTest()` on debug version.
> [IMM32] Improve debuggability at all

- base/system/diskpart/diskpart_msg.mc
[DISKPART] polish (pl-PL) translation messages  **diskpart_msg.mc**
>  [DISKPART] Update Polish translation for message table

- win32ss/gdi/gdi32/misc/misc.c
- win32ss/gdi/gdi32/objects/gdiobj.c
- win32ss/gdi/ntgdi/palette.c
- Use GDI_HANDLE_* macros for readability
> [WIN32SS] Use GDI_HANDLE_* macros

- dll/win32/imm32/candidate.c
- dll/win32/imm32/compstr.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/utils.c
Follow-up of https://github.com/reactos/reactos/commit/c2a943653e1f4881a10d20054ae951bd53cc1a1c (#4798).
- Improve trace messages in reasoning why the log message is generated.
> [IMM32] Add reasoning for tracing

- dll/win32/shell32/CSendToMenu.cpp
[CORE-18517](https://jira.reactos.org/browse/CORE-18517)
> [SHELL32] Fix empty 'Send to' menu

- dll/appcompat/apphelp/shimeng.c
- dll/win32/msi/package.c
[CORE-18532](https://jira.reactos.org/browse/CORE-18532)
[CORE-13283](https://jira.reactos.org/browse/CORE-13283)
> [APPHELP] Stop shimeng being initialized multiple times

- win32ss/user/ntuser/metric.c
Supporting Japanese input...
- In `InitMetrics` function, initialize `SM_DBCSENABLED` and `SM_IMMENABLED` system metric values.
- Don't set `SRVINFO_CICERO_ENABLED` flag because we don't have Cicero support.
- Improve `UserGetSystemMetrics` for `SM_DBCSENABLED` and `SM_IMMENABLED`.
- Delete useless `UserIsDBCSEnabled` function.
> [NTUSER] Support SM_DBCSENABLED and SM_IMMENABLED

- dll/win32/dbghelp/compat.h
Add the ARM64 entry for compat.h in the dbghelp dll.
Fixes ARM64 buildbot in preparation for 
https://github.com/reactos/reactos/pull/4809
> [DBGHELP] Add ARM64 compat.h entry

- base/applications/kbswitch/kbswitch.c
Add icons to the left-click menu.
- Add `BitmapFromIcon` helper function.
- Insert menu items with icons by `InsertMenuItem` function.
> [KBSWITCH] Menu with icons

- base/applications/network/ipconfig/ipconfig.c
ipconfig used a fixed format for time/date display (for DHCP lease) while it should respect local setting
JIRA issue: [CORE-18396](https://jira.reactos.org/browse/CORE-18396)
Use `GetDateFormat` (with long date format) and `GetTimeFormat` instead of `_tasctime` like [#2655](https://github.com/reactos/reactos/pull/2655) did
Win2K3:
ReactOS before:
After this PR:
> [IPCONFIG] Localized datetime format

- dll/cpl/desk/lang/pl-PL.rc
> [DESK] Improve Polish (pl-PL) translation

- dll/win32/shell32/CDefView.cpp
Noticed while running with DPH
> [SHELL32] Fix CDefView UAF

- dll/cpl/input/lang/pl-PL.rc
[INPUT.CPL] Update Polish (pl-PL) translation
> [INPUT] Update Polish (pl-PL) translation

- win32ss/gdi/eng/engobjects.h
- win32ss/gdi/ntgdi/brush.h
- win32ss/gdi/ntgdi/dc.h
- win32ss/include/ntgdihdl.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/win32.h
Add reference to https://reactos.org/wiki/Techwiki:Win32k/structures for cross-reference.
- Add 'See also' URLs to some undocumented structures.
> [NTGDI][NTUSER][INCLUDE] Add 'See also:' comments for structures

- sdk/tools/hhpcomp/chmc/chmc.c
`int wsize_code = 16;` !
JIRA issue: [CORE-18642](https://jira.reactos.org/browse/CORE-18642)
> [HHPCOMP:CHMC] chmc_crunch_lzx(): Disable a dead check

- dll/cpl/sysdm/advanced.c
JIRA issue: [CORE-18610](https://jira.reactos.org/browse/CORE-18610)
- Close "System Parameters" dialog on ESC
> [SYSDM] System Parameters: Close dialog on ESC

- dll/cpl/appwiz/lang/pt-PT.rc
- dll/cpl/input/lang/pt-PT.rc
- dll/cpl/intl/lang/pt-PT.rc
- dll/cpl/liccpa/lang/pt-PT.rc
- dll/cpl/sysdm/lang/pt-PT.rc
- dll/shellext/ntobjshex/lang/pt-PT.rc
- dll/shellext/zipfldr/lang/pt-PT.rc
[CPL/SYSDM] Update and improvement to pt-PT translation
[CPL] Fix typos and improve pt-PT translation
[CPL/INPUT] Update pt-pt translation
[CPL/APPWIZ] Improve pt-pt translation
[SHELLEXT] Update pt-PT translation
[SHELLEXT/ZIPFLDR] Update and improve pt-PT translation
> [SHELLEXT][CPL] Improve Portuguese (pt-PT) translation

- dll/3rdparty/libpng/docs/ANNOUNCE
- dll/3rdparty/libpng/docs/CHANGES
- dll/3rdparty/libpng/docs/INSTALL
- dll/3rdparty/libpng/docs/LICENSE
- dll/3rdparty/libpng/docs/README
- dll/3rdparty/libpng/docs/example.c
- dll/3rdparty/libpng/docs/libpng-manual.txt
- dll/3rdparty/libpng/png.c
- dll/3rdparty/libpng/pngget.c
- dll/3rdparty/libpng/pngpriv.h
- dll/3rdparty/libpng/pngread.c
- dll/3rdparty/libpng/pngrtran.c
- dll/3rdparty/libpng/pngrutil.c
- dll/3rdparty/libpng/pngset.c
- dll/3rdparty/libpng/pngstruct.h
- dll/3rdparty/libpng/pngwrite.c
- dll/3rdparty/libpng/pngwutil.c
- media/doc/3rd Party Files.txt
- sdk/include/reactos/libs/libpng/png.h
- sdk/include/reactos/libs/libpng/pngconf.h
- sdk/include/reactos/libs/libpng/pnglibconf.h
JIRA issue: [CORE-18670](https://jira.reactos.org/browse/CORE-18670)
Sync script used: https://gist.github.com/ThFabba/ac60dfd528e446a3fb83a79c168ab748
> [LIBPNG] Update to version 1.6.39

- dll/win32/rpcrt4/msvc.S
as suggested by Thomas
[CORE-18505](https://jira.reactos.org/browse/CORE-18505)
This fixes the VirtualBox 2.0.0 installer.
> [RPCRT4] Sync msvc.S with WINE's inline assembly,

- base/shell/explorer/desktop.cpp
- Fix Windows XP compatibility after 1aa95f3 (#4371)
JIRA issue: [CORE-18694](https://jira.reactos.org/browse/CORE-18694)
- Remove the use of `GetThreadId` which is a Win2003+ API. This allows ReactOS Explorer to work on Windows XP again.
> [EXPLORER] Fix Windows XP compatibility

- dll/cpl/mmsys/sounds.c
- Check if the list already contains the sound
Before:
After:
> [MMSYS] Prevent the same sound from being added multiple times

- dll/win32/shell32/folders/CRegFolder.cpp
JIRA issue: [CORE-17509](https://jira.reactos.org/browse/CORE-17509)
Before: Nothing happens.
After:
> [SHELL32] Fix My Documents properties

- dll/win32/shell32/folders/CRecycleBin.cpp
- Split off from [#4755](https://github.com/reactos/reactos/pull/4755) (This change doesn't require [#4635](https://github.com/reactos/reactos/pull/4635) to work.)
- Remove `MAX_PATH` limit
- Use ATL classes
- Play the sound asynchronously
> [SHELL32] Improve empty recycle bin sound code

- modules/rostests/kmtests/example/Example_user.c
- modules/rostests/kmtests/hidparse/HidP_user.c
- modules/rostests/kmtests/include/kmt_test.h
- modules/rostests/kmtests/kernel32/FileAttributes_user.c
- modules/rostests/kmtests/kernel32/FindFile_user.c
- modules/rostests/kmtests/kmtest/support.c
- modules/rostests/kmtests/ntos_cc/CcCopyRead_user.c
- modules/rostests/kmtests/ntos_cc/CcCopyWrite_user.c
- modules/rostests/kmtests/ntos_cc/CcMapData_user.c
- modules/rostests/kmtests/ntos_cc/CcPinMappedData_user.c
- modules/rostests/kmtests/ntos_cc/CcPinRead_user.c
- modules/rostests/kmtests/ntos_cc/CcSetFileSizes_drv.c
- modules/rostests/kmtests/ntos_cc/CcSetFileSizes_user.c
- modules/rostests/kmtests/ntos_io/IoCreateFile_user.c
- modules/rostests/kmtests/ntos_io/IoDeviceObject_user.c
- modules/rostests/kmtests/ntos_io/IoReadWrite_user.c
- modules/rostests/kmtests/ntos_mm/MmMapLockedPagesSpecifyCache_user.c
- modules/rostests/kmtests/ntos_mm/NtCreateSection_user.c
- modules/rostests/kmtests/ntos_po/PoIrp_user.c
- modules/rostests/kmtests/tcpip/TcpIp_user.c
- ntoskrnl/ke/amd64/trap.S
- win32ss/gdi/ntgdi/freetype.c
- win32ss/gdi/ntgdi/path.c
- win32ss/gdi/ntgdi/region.c
- win32ss/pch.h
A number of fixes to help get the x64 testbot to succeed. But also affecting x86.
- KVM: https://reactos.org/testman/compare.php?ids=85262,85264,85273
- VBox: https://reactos.org/testman/compare.php?ids=85263,85265,85274
> A bunch of random fixes

- win32ss/gdi/ntgdi/path.c
Missed change.
Addendum to 215e0d9 (r64177).
- `s/*pHrgn/Rgn/`
> [WIN32K:NTGDI] PATH_PathToRegion(): Update documentation

- dll/cpl/sysdm/lang/hu-HU.rc
> [SYSDM] Update Hungarian (hu-HU) translation

- base/applications/msconfig/lang/pt-PT.rc
- dll/win32/shell32/lang/pt-PT.rc
- dll/win32/userenv/lang/pt-PT.rc
- win32ss/user/user32/lang/pt-PT.rc
[SHELL32][USER32] Improve pt-PT translation
[USERENV] Don't translate Documents and Settings folder
> [SHELL32][USER32][USERENV] Improve Portuguese (pt-PT) translation

- ntoskrnl/config/cmapi.c
Currently the failure code path doesn't do any kind of cleanup against the hive that was being linked to master. The cleanup is pretty straightforward as you just simply close the hive file handles and free the registry kernel structures.
**JIRA Issues:** [CORE-5772](https://jira.reactos.org/browse/CORE-5772), [CORE-13559](https://jira.reactos.org/browse/CORE-13559), [CORE-17263](https://jira.reactos.org/browse/CORE-17263)
> [NTOS:CM] Cleanup the hive in case linking it to master fails

- base/applications/osk/lang/es-ES.rc
- base/applications/rapps/lang/es-ES.rc
- base/system/subst/lang/es-ES.rc
- base/system/userinit/lang/es-ES.rc
Update the old email to the new one.
> [REACTOS] Update my email address

- win32ss/user/ntuser/nonclient.c
Restore snapped window to normal size by dragging window caption
CORE-15638
In initial PR where window snap was created user was able restore window size only by Win+Arrow keys, not with mouse - now this UX is complete :)
> [WIN32SS:NTUSER] restore snapped window to normal size. CORE-15638

- ntoskrnl/io/pnpmgr/plugplay.c
Let's not abuse the kernel stack...
> [NTOS:PNP] Avoid recursion when walking the device tree.

- sdk/lib/3rdparty/freetype/CMakeLists.txt
- sdk/lib/drivers/ip/CMakeLists.txt
- sdk/lib/drivers/ip/network/ip.c
- sdk/lib/drivers/ip/transport/rawip/rawip.c
- sdk/lib/drivers/ip/transport/udp/udp.c
- sdk/lib/drivers/sound/legacy/CMakeLists.txt
- sdk/lib/drivers/sound/shared/CMakeLists.txt
- sdk/lib/drivers/sound/soundblaster/CMakeLists.txt
- sdk/lib/drivers/sound/uartmidi/CMakeLists.txt
Nothing interesting, made a PR just to run the CI
> [DRIVERS] Remove unused __NTDRIVER__ and KERNEL definitions

- modules/rostests/apitests/compiler/ms_seh.c
- modules/rostests/apitests/compiler/pseh.c
- modules/rostests/apitests/crt/strlen.c
- modules/rostests/apitests/ntdll/StackOverflow.c
- modules/rostests/apitests/ntdll/Timer.c
- modules/rostests/apitests/ntdll/probelib.c
- modules/rostests/apitests/win32nt/CMakeLists.txt
- modules/rostests/apitests/win32nt/ntdd/NtGdiDdQueryDirectDrawObject.c
- modules/rostests/apitests/win32nt/ntgdi/NtGdiCreateDIBSection.c
- modules/rostests/apitests/win32nt/ntgdi/NtGdiExtTextOutW.c
- modules/rostests/apitests/win32nt/ntgdi/NtGdiPolyPolyDraw.c
- modules/rostests/apitests/win32nt/ntuser/NtUserEnumDisplaySettings.c
- modules/rostests/apitests/win32nt/ntuser/NtUserSystemParametersInfo.c
- modules/rostests/apitests/win32nt/testlist.c
Fixes a number of tests on Test WHS
ReactOS: https://reactos.org/testman/compare.php?ids=85718,85719,85721,85724
Test WHS: ...
> Fix a number of tests on Test WHS

- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/CommandLineToArgvW.cpp
- modules/rostests/apitests/shell32/testlist.c
Fix command line parsing.
JIRA issue: [CORE-17787](https://jira.reactos.org/browse/CORE-17787)
- Add `CommandLineToArgvW` testcase.
> [SHELL32_APITEST] Add CommandLineToArgvW testcase

- modules/rostests/kmtests/kmtest/testlist.c
https://build.reactos.org/#/builders/2/builds/2799
https://build.reactos.org/#/builders/2/builds/2798
https://build.reactos.org/#/builders/2/builds/2797
https://build.reactos.org/#/builders/2/builds/2796
> [KMTESTS:CC] Disable broken CcCopyWrite

- dll/win32/winmm/mmio.c
JIRA issue: [CORE-18810](https://jira.reactos.org/browse/CORE-18810)
Import fixes from Wine commits
[https://source.winehq.org/git/wine.git/commit/cc5f2b2c766bbe4975d7ee4a7c3b269650cbf874](https://source.winehq.org/git/wine.git/commit/cc5f2b2c766bbe4975d7ee4a7c3b269650cbf874)
[https://source.winehq.org/git/wine.git/commit/4431c32c91206040d59d3eb82a971245594d1243](https://source.winehq.org/git/wine.git/commit/4431c32c91206040d59d3eb82a971245594d1243)
[https://source.winehq.org/git/wine.git/commit/4aca7601265ca76339662aa4e1a9c6669cebc9a0](https://source.winehq.org/git/wine.git/commit/4aca7601265ca76339662aa4e1a9c6669cebc9a0)
> [WINMM] MMIO_ParseExtA: Import fixes from Wine

- base/applications/notepad/text.c
https://github.com/reactos/reactos/pull/5012 didn't handle the empty files correctly.
JIRA issue: [CORE-14641](https://jira.reactos.org/browse/CORE-14641), [CORE-18826](https://jira.reactos.org/browse/CORE-18826)
- Check if the file is empty, if so, treat it correctly.
> [NOTEPAD] Treat empty file correctly

- base/applications/rapps/installed.cpp
Trivial fix to installed apps information so it displays properly
JIRA issue: [CORE-18397](https://jira.reactos.org/browse/CORE-18397) [CORE-18774](https://jira.reactos.org/browse/CORE-18774)
- ReleaseBuffer()
> [RAPPS] Fix Installed Apps information display

- base/applications/notepad/dialog.c
JIRA issue: [CORE-18832](https://jira.reactos.org/browse/CORE-18832)
- Use `EM_GETHANDLE` to get the text.
- Check zero size and handle it elegantly.
> [NOTEPAD] Fix and improve DoSaveFile

- base/applications/notepad/main.c
Simplify code for human readability.
- Simplify `NOTEPAD_EnableSearchMenu` function.
> [NOTEPAD] Simplify NOTEPAD_EnableSearchMenu

- base/applications/notepad/dialog.c
Simplify code.
- Simplify `FileExists` helper function by using `GetFileAttributes` function.
> [NOTEPAD] Simplify FileExists function

- base/applications/notepad/dialog.c
- Use `EM_GETHANDLE` message to get text.
- Reduce lines.
> [NOTEPAD] Simplify GetSelectionText

- dll/win32/comdlg32/finddlg.c
The flags were not updated correctly.
JIRA issue: [CORE-17064](https://jira.reactos.org/browse/CORE-17064)
BEFORE:
FAILED.
AFTER:
Successful.
> [COMDLG32] Find/Replace: Correctly set flags

- dll/win32/comctl32/edit.c
- win32ss/user/user32/controls/edit.c
Noticed while running with DPH
> [COMCTL32] Fix edit UAF

- modules/rostests/apitests/crt/_wsystem.c
- modules/rostests/apitests/crt/crtdll_crt_apitest.cmake
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/static_crt_apitest.cmake
- modules/rostests/apitests/crt/system.c
- modules/rostests/apitests/crt/testlist.c
- sdk/lib/crt/process/_system.c
Make an ReactOS's CRT function working.
- Implement `msvcrt!_wsystem` function, by referring `msvcrt!system` function.
- Improve `system()` function.
- Use `WaitForSingleObject` in `system()` and `_wsystem()`.
- Check existence of `COMSPEC`.
> [MSVCRT][CRT_APITEST] Implement _wsystem

- dll/win32/ws2_32/src/send.c
_Fix two DPRINT typo errors._
JIRA issue: NONE
_Correct text errors that pointed to incorrect functions._
> [WS2_32] Fix Two DPRINT typo errors.

- base/applications/regedit/regedit.c
JIRA issue: [CORE-18770](https://jira.reactos.org/browse/CORE-18770)
Compare to https://github.com/reactos/reactos/blob/66030257b1d51556feec0cc78f49c93e48900d49/base/applications/regedit/regedit.c#L139-192
> [REGEDIT] Add back import prompt message lost during Wine sync

- base/applications/regedit/regedit.h
- base/applications/regedit/treeview.c
JIRA issue: [CORE-18602](https://jira.reactos.org/browse/CORE-18602)
> [REGEDIT] Avoid buffer overflow in SelectNode

- base/applications/notepad/dialog.c
- base/applications/notepad/main.c
- base/applications/notepad/settings.c
Improve readability.
- Reduce lines.
> [NOTEPAD] Reduce lines in and around comments

- sdk/lib/scrnsave/scrnsave.c
This makes it easier to start the screensavers by double-clicking.
> [SDK:SCRNSAVE] Implement mouse move threshold.

- base/applications/notepad/dialog.c
- base/applications/notepad/settings.c
Simplify the code.
- Remove some needless type casts.
> [NOTEPAD] Remove some needless type casts

- base/applications/notepad/main.c
Refactoring to improve prospects.
- Add `hInstance` parameter to `NOTEPAD_InitData`.
- Move some code in `_tWinMain` into `NOTEPAD_InitData`.
- Move some code in `_tWinMain` into `WM_CREATE` handling.
- Move some code in `WM_CLOSE` handling into `WM_DESTROY` handling.
- Fix the exit code of `_tWinMain`.
> [NOTEPAD] Refactor around _tWinMain

- base/applications/notepad/dialog.c
- base/applications/notepad/dialog.h
- base/applications/notepad/main.c
- base/applications/notepad/notepad_res.h
- base/applications/notepad/printing.c
- base/applications/notepad/rsrc.rc
- base/applications/notepad/settings.c
- base/applications/notepad/text.c
https://reactos.org/wiki/Coding_Style
Coding style says that we should use new-style file headers.
- Use new-style file headers.
> [NOTEPAD] Use new-style file header

- base/applications/regedit/regproc.c
Remove the ROS-diff 
JIRA issue: [CORE-18603](https://jira.reactos.org/browse/CORE-18603)
> [REGEDIT] import Wine commit f5fe9a6.

- dll/win32/kernel32/client/heapmem.c
`GlobalMemoryStatusEx` should return FALSE and set Last Error when failed
`GlobalMemoryStatusEx` return FALSE and set Last Error when failed.
Before this PR, `GlobalMemoryStatusEx` always return TRUE and didn't inspect result of calling `Nt*`.
> [KERNEL32] GlobalMemoryStatusEx should handle error and return FALSE when failed

- dll/win32/msi/dialog.c
Continuing from : [PR](https://github.com/reactos/reactos/pull/4966)
JIRA issue: [CORE-18749](https://jira.reactos.org/browse/CORE-18749)
Test
> [MSI] Fix empty disc costing

- modules/rostests/apitests/crt/wctomb.c
- modules/rostests/apitests/iphlpapi/GetInterfaceName.c
- modules/rostests/apitests/kernel32/FindFiles.c
- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtMapViewOfSection.c
- modules/rostests/apitests/shell32/testlist.c
- modules/rostests/apitests/user32/AttachThreadInput.c
- modules/rostests/apitests/user32/GetMessageTime.c
- modules/rostests/apitests/win32nt/testlist.c
- modules/rostests/winetests/gdiplus/image.c
- modules/rostests/winetests/jscript/run.c
More test fixes
-- Build: https://build.reactos.org/#/builders/2/builds/2863
-- Testman: https://reactos.org/testman/compare.php?ids=86860,86862,86865,86866,86869
-- Build: https://build.reactos.org/#/builders/9/builds/33792
-- Testman: https://reactos.org/testman/compare.php?ids=86848,86852,86854,86856,86871
> [ROSTESTS] Fix some tests that fail on WHS testbot

- modules/rostests/apitests/atl/AtlObjMap.cpp
- modules/rostests/apitests/atl/CMakeLists.txt
- modules/rostests/apitests/atl/devenv/ATLTest.sln
- modules/rostests/apitests/atl/devenv/AtlObjMap.vcxproj
- modules/rostests/apitests/atl/testlist.c
- sdk/lib/atl/atlbase.h
- sdk/lib/atl/atlcom.h
JIRA issue: [CORE-18936](https://jira.reactos.org/browse/CORE-18936)
> [ATL] Add OBJECT_ENTRY_AUTO for simpler com object registration 

- modules/rostests/apitests/atl/CAtlList.cpp
- sdk/lib/atl/atlcoll.h
Needed for the implementation of [CORE-18941](https://jira.reactos.org/browse/CORE-18941)
> [ATL] Add CAtlList::SwapElements

- modules/rostests/apitests/CMakeLists.txt
- modules/rostests/apitests/advpack/CMakeLists.txt
- modules/rostests/apitests/advpack/DelNode.c
- modules/rostests/apitests/advpack/testlist.c
Preparation for `advpack!DelNodeA/W` functions implementation.
JIRA issue: [CORE-13275](https://jira.reactos.org/browse/CORE-13275), [ROSTESTS-276](https://jira.reactos.org/browse/ROSTESTS-276)
WinXP:
Win2k3:
Win10:
> [ADVPACK_APITEST] Add advpack_apitest:DelNode testcase

- dll/cpl/input/layout_list.c
Remove the needless hack and reduce the maintenance cost. Because `shlwapi!SHLoadRegUIStringW` function is already implemented, so we don't need the hack any more.
- Simplify `FakeSHLoadRegUIStringW` without using hack.
> [INPUT] Remove SHLoadRegUIStringW hack

- drivers/network/dd/e1000/hardware.c
Respect the private data of people sending logs to us.
> [E1000] Stop logging MAC, is sensitive data of log-contributors

- boot/freeldr/freeldr/arch/uefi/stubs.c
- boot/freeldr/freeldr/arch/uefi/uefidisk.c
- boot/freeldr/freeldr/uefi.cmake
Implement the needed memory management functions for freeldr UEFI
JIRA issue: [CORE-11954](https://jira.reactos.org/browse/CORE-11954)
- implement disk routines for freeldr
> [FREELDR] Add disk access handlers for UEFI

- dll/win32/imm32/imm32.spec
- dll/win32/imm32/keymsg.c
- sdk/include/reactos/jpnvkeys.h
- win32ss/user/ntuser/ime.c
Implementing Console IME...
- Add `<jpnvkeys.h>` header file.
- Add `imm32!ImmCallImeConsoleIME` function.
> [IMM32][NTUSER][SDK] Add ImmCallImeConsoleIME

- base/applications/rapps/gui.cpp
- base/applications/rapps/include/configparser.h
- base/applications/rapps/include/dialogs.h
- base/applications/rapps/include/gui.h
- base/applications/rapps/include/misc.h
- base/applications/rapps/include/settings.h
- base/applications/rapps/include/winmain.h
- base/applications/rapps/unattended.cpp
Looking at the source of RAPPS gives the impression that a lot of headers are included again and again in the different files (or some are included when they are not needed, because they are included via another file, etc.).
Let us "slap some sense" in these headers.
> [RAPPS] Cleanup headers inclusions.

- modules/rostests/apitests/user32/CMakeLists.txt
- modules/rostests/apitests/user32/GetClassInfo.c
- modules/rostests/apitests/user32/GetSetWindowInt.c
- modules/rostests/apitests/user32/testlist.c
- modules/rostests/apitests/win32nt/ntuser/NtUserGetClassInfo.c
Add some user32 apitests tests to test window extra bytes
- Add tests for [Get|Set]Window[Word|Long|LongPtr]
- Add tests for GetClassInfo
- Test WHS: https://reactos.org/testman/compare.php?ids=87133
- Test Win2003_x64: https://reactos.org/testman/compare.php?ids=87134
> [USER32_APITEST] Add some tests

- boot/boot_images.cmake
Fix broken build after UEFI merge.
Guilty commit: 150f72127
> [FREELDR] Fix builds for PC-98 and Xbox platforms

- base/applications/utilman/umandlg/lang/pt-PT.rc
- base/applications/utilman/umandlg/umandlg.rc
[UTILMAN] Add Portuguese (pt-PT) translation.
> [UTILMAN] Add Portuguese (pt-PT) translation

- base/services/umpnpmgr/rpcserver.c
JIRA issue: [CORE-18986](https://jira.reactos.org/browse/CORE-18986)
> [UMPNPMGR] Fix uninitialized variable

- ntoskrnl/se/token.c
- ntoskrnl/se/tokenlif.c
Check the commit descriptions for explanation.
[CORE-18986](https://jira.reactos.org/browse/CORE-18986)
> [NTOS:SE] Refactor NtOpenThreadTokenEx + fix a pool corruption in SepDuplicateToken

- base/applications/notepad/lang/nl-NL.rc
- base/applications/taskmgr/lang/nl-NL.rc
- base/setup/welcome/lang/nl-NL.rc
- base/shell/explorer/lang/nl-NL.rc
Improve the Dutch translation in Task Manager, Notepad, Explorer and Welcome.
> [TRANSLATION] Improve Dutch (nl-NL) translation

- base/applications/mspaint/lang/pt-PT.rc
[MSPAINT] Update portuguese (pt-PT) translation
> [MSPAINT] Update Portuguese (pt-PT) translation

- win32ss/user/ntuser/security.c
And remove the `!NT_SUCCESS(Status` check which is excessive, the expected status will always be **STATUS_BUFFER_TOO_SMALL** anyway. This should fix some compilation warnings spotted by GCC. 
Courtesy goes to Hermes for letting me know of these warnings.
> [NTUSER] Fix an unintialized user's token variable case

- base/applications/mspaint/common.h
- base/applications/mspaint/dib.cpp
- base/applications/mspaint/dib.h
- base/applications/mspaint/history.cpp
- base/applications/mspaint/history.h
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/winproc.cpp
Improve code quality and readability.
JIRA issue: [CORE-17969](https://jira.reactos.org/browse/CORE-17969), [CORE-18867](https://jira.reactos.org/browse/CORE-18867)
- Unify `ImageModel::Insert` and `ImageModel::CopyPrevious` to `ImageModel::PushImageForUndo`.
- Delete useless members.
- Simplify `ImageModel` code.
- Fix some memory leaks.
- Fix `IDM_IMAGECROP` command.
> [MSPAINT] Refactor ImageModel

- ntoskrnl/io/iomgr/iorsrce.c
- Add missing ExAllocatePool NULL checks.
- Fix order of KeBugCheckEx parameters for PNP_DETECTED_FATAL_ERROR.
- The Controller and Peripheral numbers are zero-based, so if the caller wants to inspect controller (or peripheral) zero, let it be so! The original code was treating controller number zero for enumerating controllers of a given class within the different buses, which is wrong. See the diff'ed trace below. Tested with Windows' videoprt.sys VideoPortGetDeviceData().
```diff
IoQueryDeviceDescription()
BusType:          0xB093C224 (0)
BusNumber:        0xB093C228 (0)
ControllerType:   0xF9D01030 (19)
ControllerNumber: 0xF9D01038 (0)
PeripheralType:   0x00000000 (4294967295)
PeripheralNumber: 0x00000000 (4294967295)
CalloutRoutine:   0xF9CF74E4
Context:          0xF9D5A340
--> …
```
> [NTOS:IO] Fix some bugs in the IoQueryDeviceDescription helpers.

- base/applications/mspaint/history.cpp
- base/applications/mspaint/history.h
- base/applications/mspaint/miniature.cpp
- base/applications/mspaint/miniature.h
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/selectionmodel.h
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/winproc.cpp
Fix the miniature window.
- Save the position and size of the miniature window.
- Improve drawing of the miniature window.
- Sync with the canvas.
> [MSPAINT] Improve CMiniatureWindow

- boot/freeldr/freeldr/disk/scsiport.c
- drivers/storage/port/scsiport/scsiport.c
- drivers/storage/port/storport/miniport.c
- sdk/include/ddk/srb.h
- sdk/include/ddk/storport.h
See the individual commits for more details.
See also https://www.osronline.com/article.cfm%5Earticle=538.htm
> [SCSIPORT][STORPORT] Use some defines for some hardcoded values

- base/applications/fontview/lang/de-DE.rc
String translation in de-DE.rc
> [FONTVIEW] Update German (de-DE) translation
