- dll/win32/iphlpapi/iphlpapi_main.c
Properly call HeapFree on buffer allocated with HeapAlloc.
JIRA issue: [CORE-16513](https://jira.reactos.org/browse/CORE-16513)
Spine-chiller bugs
> [IPHLPAPI] Do not use free() on buffer allocated with HeapAlloc

- drivers/bus/acpi/acpica/include/acpi.h
- drivers/bus/acpi/buspdo.c
- modules/rostests/apitests/CMakeLists.txt
- modules/rostests/apitests/acpi/Bus_PDO_QueryResourceRequirements.c
- modules/rostests/apitests/acpi/CMakeLists.txt
- modules/rostests/apitests/acpi/testlist.c
Here's a typical ACPI resource descriptor:
```
Name (_PRS, ResourceTemplate ()  // _PRS: Possible Resource Settings
{
StartDependentFnNoPri ()
{
IO (Decode16,
0x03E8,             // Range Minimum
0x03E8,             // Range Maximum
0x08,               // Alignment
0x08,               // Length
)
IRQNoFlags ()
{3,4,5,6,7,9,10,11,12,14,15}
}
StartDependentFnNoPri ()
{
IO (Decode16,
0x02E8,             // Range Minimum
0x02E8,             // Range Maximum
0x08,               // Alignment
0x08,               // Length
)
IRQNoFlags ()
{3,4,5,6,7,9,10,11,12,14,15}
}
StartDependentFn (0x02, 0x01)
{
IO (Decode16,
0x0100,             // Range Minimum
0x03F8,             // Range Maximum
0x08,               // Alignment
0x08,               // Length
)
IRQNoFlags ()
{3,4,5,6,7,9,10,11,12,14,15}
} …
```
> [ACPI] Fix Bus_PDO_QueryResourceRequirements.

- .travis.yml
Inconsistent git clone depth in CI.
For Travis = 1
For AppVeyor = 5
Version A - update Travis to depth 5
Please see Version B: https://github.com/reactos/reactos/pull/2533
> [TRAVIS] Fix inconsistent git clone depth in CI

- dll/win32/syssetup/wizard.c
Just added a simple flag for mandatory password in syssetup.
JIRA issue: [CORE-8038](https://jira.reactos.org/browse/CORE-8038)
> added a flag for mandatory password

- base/applications/charmap/charmap.c
- base/applications/charmap/map.c
This pull request updates charmap to look a bit better (removes gap at bottom of the window), removes the blank space character (0x0020) from the charmap, and also modifies the behaviour of when a larger glyph is rendered (allowing the user to select a new glyph by holding down the mouse button).  This better mimics the charmap.exe that is bundled by Microsoft.
- Remove gap where the advanced button is normally rendered when compiled with REMOVE_ADVANCED (which is the default behaviour)
- Skip over the blank space character
- Change behaviour of rendering large glyphs to allow mouse move, and to hide on double click
- Optimize search for glyph under the mouse by using the cellSize instead of PtInRect
> [CHARMAP] Updates to behaviour and UI

- dll/win32/winsta/logon.c
- dll/win32/winsta/winsta.spec
Add a stubs for the WinStationCanLogonProceed() and _WinStationOpenSessionDirectory() functions in Winsta. Based on the prototypes by @HBelusca from PR #2072: https://github.com/reactos/reactos/pull/2072#issuecomment-559795653. The only difference are functions types (`VOID WINSTAAPI` instead of `BOOLEAN WINSTAAPI`) and the function arguments (`PVOID A`, `B`, `C` etc, instead of `DWORD dwUnknown1`, `DWORD dwUnknown2`, `LPCWSTR pString1`, `LPCWSTR pString2` etc). I wrote them the same as all other Winsta stubs. If they are not (completely) correct, I think they nevertheless can be a good (temporary) solution for now.
Now MS Winlogon does not fail at all due to our Winsta. :smiley:
JIRA issue: [CORE-16458](https://jira.reactos.org/browse/CORE-16458), …
> [WINSTA] Stub WinStationCanLogonProceed and _WinStationOpenSessionDirectory

- dll/win32/sfc/sfc.spec
- dll/win32/sfc_os/sfc_os.spec
Improve exports for undocumented sfc_1-7() and sfc_os_1-7() functions in our sfc.dll and sfc_os.dll accordingly. Also remove extra whitespaces between all function names and their arguments in sfc.
Required by userenv.dll from Win2k3 together with MS win32k.sys & others replaced, in Frankensteined ReactOS and also by some MS installers, like Windows Media Encoder 7.1 installer. Now they should not fail due to that functions.
JIRA issue: [CORE-16458](https://jira.reactos.org/browse/CORE-16458)
Improve exports for the following functions:
- in sfc.dll
- sfc_1();
- sfc_2();
- sfc_3();
- sfc_4();
- sfc_5();
- sfc_6();
- sfc_7();
- in sfc_os.dll
- sfc_os_1();
- sfc_os_2();
- sfc_os_3();
- sfc_os_4();
- sfc_os_6();
- sfc_os_7().
Also remove unnecessary whitespaces in dll/win32/sfc/sfc.spec.
> [SFC][SFC_OS] Improve exports for sfc_1-7() and sfc_os_1-7()

- dll/win32/comctl32/listview.c
- dll/win32/shell32/CDefView.cpp
This pull request improves the behaviour of the listview used by the shell32 file explorer to more closely mimic what a user would expect (do not allow icons to be moved when auto-arrange is enabled).  This pull request also provides a (dumb) version of snap-to-grid for the listview control and hooks up the 'line up icons' context menu item in shell32.
- [COMCTL32 listview] Do not allow user to move icons when auto-arrange is enabled.
- [COMCTL32 listview] Implement a basic snap to grid layout scheme (moves icon to closest grid location, does not deal with stacked icons for now).
- [SHELL32] Hook up 'Line up Icons' context menu item and have it fire Arrange(LVA_SNAPTOGRID).
I think the pull request as-is (after review and any fixes) takes a good step in the right direction, and I would …
> [COMCTL32 and SHELL32] Add basic snap-to-grid

- base/applications/utilman/CMakeLists.txt
- base/applications/utilman/NOTES.txt
- base/applications/utilman/lang/en-US.rc
- base/applications/utilman/precomp.h
- base/applications/utilman/resource.h
- base/applications/utilman/umandlg/CMakeLists.txt
- base/applications/utilman/umandlg/about.c
- base/applications/utilman/umandlg/lang/en-US.rc
- base/applications/utilman/umandlg/lang/es-ES.rc
- base/applications/utilman/umandlg/lang/fr-FR.rc
- base/applications/utilman/umandlg/lang/he-IL.rc
- base/applications/utilman/umandlg/lang/it-IT.rc
- base/applications/utilman/umandlg/lang/pl-PL.rc
- base/applications/utilman/umandlg/lang/ro-RO.rc
- base/applications/utilman/umandlg/lang/ru-RU.rc
- base/applications/utilman/umandlg/lang/uk-UA.rc
- base/applications/utilman/umandlg/process.c
- base/applications/utilman/umandlg/registry.c
- base/applications/utilman/umandlg/resource.h
- base/applications/utilman/umandlg/umandlg.c
- base/applications/utilman/umandlg/umandlg.h
- base/applications/utilman/umandlg/umandlg.rc
- base/applications/utilman/umandlg/umandlg.spec
- base/applications/utilman/utilman.c
- base/applications/utilman/utilman.rc
Utility Manager has its own library which contains all the needed resources and stuff. The PR implements that library and move the dialog management and other chunks of code there.
> [UTILMAN] Implement UManDlg library and move most of the code there

- dll/win32/browseui/addresseditbox.cpp
This PR will attempt to parse an absolute path even in the case of an unexpected failure while computing the relative path of a directory entered into the address bar of the file explorer.  An unexpected error could occur when `BindToObject` is unimplemented, or when `BindToObject` was attempted on the Desktop.
- Attempt to parse an absolute path as long as `psfDesktop` is valid.
To reproduce this issue:
1.  Boot up a copy of ReactOS and navigate the file explorer to the desktop.
2.  Try to enter a valid path and navigate to it using the address bar.
3.  You will be unable to navigate using the address bar.  The error being returned is E_INVALIDARG by `BindToObject` because the Desktop is the current path.
> [BROWSEUI] Attempt absolute path on relative path fail

- dll/win32/shimgvw/lang/bg-BG.rc
- dll/win32/shimgvw/lang/cs-CZ.rc
- dll/win32/shimgvw/lang/de-DE.rc
- dll/win32/shimgvw/lang/en-US.rc
- dll/win32/shimgvw/lang/es-ES.rc
- dll/win32/shimgvw/lang/fr-FR.rc
- dll/win32/shimgvw/lang/he-IL.rc
- dll/win32/shimgvw/lang/it-IT.rc
- dll/win32/shimgvw/lang/ja-JP.rc
- dll/win32/shimgvw/lang/lt-LT.rc
- dll/win32/shimgvw/lang/no-NO.rc
- dll/win32/shimgvw/lang/pl-PL.rc
- dll/win32/shimgvw/lang/pt-PT.rc
- dll/win32/shimgvw/lang/ro-RO.rc
- dll/win32/shimgvw/lang/ru-RU.rc
- dll/win32/shimgvw/lang/sk-SK.rc
- dll/win32/shimgvw/lang/sq-AL.rc
- dll/win32/shimgvw/lang/tr-TR.rc
- dll/win32/shimgvw/lang/uk-UA.rc
- dll/win32/shimgvw/lang/zh-CN.rc
- dll/win32/shimgvw/lang/zh-TW.rc
- dll/win32/shimgvw/resource.h
- dll/win32/shimgvw/shimgvw.c
If loading an image file failed, then properly handle it.
JIRA issue: [CORE-16911](https://jira.reactos.org/browse/CORE-16911)
BEFORE:
AFTER:
The command line is `rundll32 shimgvw.dll,ImageView_Fullscreen`.
> [SHIMGVW] Consider failure case of loading file

- base/applications/rapps/settingsdlg.cpp
_ When a proxy was selected then "default settings" is applied, the state of the proxy text fields is unduly kept enabled because the test code in the dialog initialization section is only able to "re-enable" these fields with the wrong assumption that they have been disabled beforehand
JIRA issue: [CORE-16853](https://jira.reactos.org/browse/CORE-16853)
_  Change in InitSettingsControls in order to Disable these 2 text fields when not necessary.
> [RAPPS] Proxy fields default state fix (CORE-16853)

- boot/bootdata/floppy_pc98.ini
- boot/freeldr/freeldr/lib/comm/rs232.c
- boot/freeldr/freeldr/lib/debug.c
- boot/freeldr/freeldr/ntldr/headless.c
- drivers/base/kdcom/kdcom.c
- drivers/base/kdgdb/kdcom.c
- ntoskrnl/inbv/inbvport.c
- ntoskrnl/kd/i386/kdbg.c
Attempt to fix bug described in that Twitter post: https://twitter.com/simk98l/status/1251340347491282945.
According to PC-9801 Bible p. 50, divisor for PIT will become unsupported in some cases after having removed the fractional part. 
- Replace 19200 value with 9600 which is supported by both 10 MHz and 8 MHz machines.
> [KDCOM][NTOS:INBV][FREELDR] Decrease default baud rate for PC-98

- modules/rostests/apitests/gdi32/GetTextMetrics.c
_Tahoma is available in Windows and ReactOS both, so this allows us to compare these fonts in both systems._
> [GDI32_APITEST] Add Tahoma font to GetTextMetrics apitest set

- base/applications/rapps/README.RUS
- base/applications/rapps/lang/bg-BG.rc
- base/applications/rapps/lang/cs-CZ.rc
- base/applications/rapps/lang/de-DE.rc
- base/applications/rapps/lang/en-US.rc
- base/applications/rapps/lang/es-ES.rc
- base/applications/rapps/lang/et-EE.rc
- base/applications/rapps/lang/fr-FR.rc
- base/applications/rapps/lang/he-IL.rc
- base/applications/rapps/lang/id-ID.rc
- base/applications/rapps/lang/it-IT.rc
- base/applications/rapps/lang/ja-JP.rc
- base/applications/rapps/lang/no-NO.rc
- base/applications/rapps/lang/pl-PL.rc
- base/applications/rapps/lang/pt-BR.rc
- base/applications/rapps/lang/pt-PT.rc
- base/applications/rapps/lang/ro-RO.rc
- base/applications/rapps/lang/ru-RU.rc
- base/applications/rapps/lang/sk-SK.rc
- base/applications/rapps/lang/sq-AL.rc
- base/applications/rapps/lang/sv-SE.rc
- base/applications/rapps/lang/tr-TR.rc
- base/applications/rapps/lang/uk-UA.rc
- base/applications/rapps/lang/zh-CN.rc
- base/applications/rapps/lang/zh-TW.rc
NB:
http://www.reactos.org/wiki/Bulgarian_translation
is not updated, as it returns
`Error 404 - Page not found`.
> [RAPPS] Update now-redirected 'http' and 'www.reactos.org' URLs

- base/setup/usetup/lang/bg-BG.h
- base/setup/usetup/lang/bn-BD.h
- base/setup/usetup/lang/cs-CZ.h
- base/setup/usetup/lang/da-DK.h
- base/setup/usetup/lang/de-DE.h
- base/setup/usetup/lang/el-GR.h
- base/setup/usetup/lang/en-US.h
- base/setup/usetup/lang/es-ES.h
- base/setup/usetup/lang/et-EE.h
- base/setup/usetup/lang/fr-FR.h
- base/setup/usetup/lang/he-IL.h
- base/setup/usetup/lang/hu-HU.h
- base/setup/usetup/lang/id-ID.h
- base/setup/usetup/lang/it-IT.h
- base/setup/usetup/lang/ja-JP.h
- base/setup/usetup/lang/lt-LT.h
- base/setup/usetup/lang/ms-MY.h
- base/setup/usetup/lang/nl-NL.h
- base/setup/usetup/lang/pl-PL.h
- base/setup/usetup/lang/pt-BR.h
- base/setup/usetup/lang/pt-PT.h
- base/setup/usetup/lang/ro-RO.h
- base/setup/usetup/lang/sk-SK.h
- base/setup/usetup/lang/sq-AL.h
- base/setup/usetup/lang/sv-SE.h
- base/setup/usetup/lang/tr-TR.h
NB:
http://www.reactos.org/uk/
is not updated, as it returns
`Error 404 - Page not found`.
> [USETUP] Update now-redirected 'http' and 'www.reactos.org' URLs

- ntoskrnl/kdbg/kdb.c
Moved a declaration inside the #ifndef
> [NTOS:KDBG] Fixed variable declaration to make buildable the project

- win32ss/gdi/ntgdi/freetype.c
JIRA issue: [CORE-15949](https://jira.reactos.org/browse/CORE-15949)
In return of `GetGlyphOutline` function call, `gm.gmBlackBoxX` and `gm.gmBlackBoxY` must be non-zero to avoid Division by Zero. At epilogue of `ftGdiGetGlyphOutline`, we adjust the values.
> [NTGDI][FREETYPE] Return non-zero gm.gmBlackBoxX/Y

- boot/bootdata/readme.txt
NB:
https://www.reactos.org/joining/faqs
is not updated, as it returns
`Error 404 - Page not found`.
> [README] Update now-redirected 'www.reactos.org' URLs

- boot/bootdata/hivedef.inf
- boot/bootdata/hivesft.inf
_ In current implementation, init value for hide/show hidden files & folders is set to 1 (Show) while "default" button sets it to 2 (Hide). "Default" button should set to "Show" (1).
JIRA issue: [CORE-16932](https://jira.reactos.org/browse/CORE-16932)
_ Change of Advanced Files & Folders Settings action of Default button to select "Show"
_ Change is made by flipping the HKLM default values
> [SHELL32] Fix for incorrect init of hide/show hidden files & folders (CORE-16932)

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/RtlMultipleAllocateHeap.c
- modules/rostests/apitests/ntdll/testlist.c
- sdk/include/ndk/rtlfuncs.h
- sdk/lib/rtl/heap.c
JIRA issue: [CORE-12026](https://jira.reactos.org/browse/CORE-12026)
- Add `RtlMultipleAllocateHeap` and `RtlMultipleFreeHeap` functions (`2k3+`).
- Add a testcase for two functions.
WinXP:
XP doesn't support two functions.
Win2k3:
Win10:
AFTER:
> [SDK][RTL][NTDLL_APITEST] Add RtlMultipleAllocateHeap and RtlMultipleFreeHeap

- dll/win32/shell32/shlexec.cpp
Based on JIRA user `amaneureka`'s idea.
JIRA issue: [CORE-16384](https://jira.reactos.org/browse/CORE-16384)
- In `SHELL_execute` function, add a backslash for Drive `"C:"`, `"D:"` or `"E:"` etc.
BEFORE:
AFTER:
> [SHELL32] Command 'start C:' should open 'C:\'

- base/applications/control/control.c
Fix JIRA issue [CORE-11373](https://jira.reactos.org/browse/CORE-11373)
- patch by Jira user "wimh"
- also addressed Hermes' suggestion to use ARRAYSIZE instead of MAX_PATH
You have to tell me, if there's something  ;)
> [CONTROL] Fix hang while calling RunControlPanel() CORE-11373

- base/applications/notepad/dialog.c
- Add to recent documents upon file save.
JIRA issue: [CORE-3588](https://jira.reactos.org/browse/CORE-3588)
> [NOTEPAD] Add to recent files on file save

- base/applications/mspaint/dib.cpp
JIRA issue: [CORE-3588](https://jira.reactos.org/browse/CORE-3588)
- Add to recent documents upon file save.
> [MSPAINT] Add to recent documents

- dll/win32/netid/lang/fr-FR.rc
_ Correct fr-fr translation in order to better match with component size and standard wording.
> [NETID] fr-fr translation fix and component size

- modules/rostests/apitests/crt/crtdll_crt_apitest.cmake
- modules/rostests/apitests/crt/mbtowc.c
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/ntdll_crt_apitest.cmake
- modules/rostests/apitests/crt/testlist.c
**Windows XP**
**ReactOS (with #2563 applied to build)**
> [CRT_APITEST] Add testcase for mbtowc()

- dll/win32/shell32/CDefView.cpp
By specifying `LPSTR_TEXTCALLBACKW`, we explicitly update the text/name of the listview item of Explorer.
JIRA issue: [CORE-16960](https://jira.reactos.org/browse/CORE-16960)
> [SHELL32] Update name in CDefView::LV_RenameItems

- dll/ntdll/rtl/version.c
- sdk/include/ndk/rtlfuncs.h
Calling this function with fake `NULL` causes an access violation exception on Windows :->
> [NDK][NTDLL] RtlGetNtProductType(): update it with SAL2 annotations.

- dll/ntdll/include/ntdllp.h
- dll/ntdll/ldr/ldrapi.c
- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/RtlGetUnloadEventTrace.c
- modules/rostests/apitests/ntdll/testlist.c
- sdk/include/ndk/rtltypes.h
- sdk/lib/rtl/trace.c
This allows viewing unloaded modules in f.e. windbg:
```
kd> !lm
No export lm found
kd> lm
start    end        module name
00400000 004e0000   mshtml_winetest   (private pdb symbols)  C:\ProgramData\dbg\sym\mshtml_winetest.pdb\5542EB3B9C9E440B95C224B107D54EB830\mshtml_winetest.pdb
77190000 77308000   mshtml     (private pdb symbols)  C:\ProgramData\dbg\sym\mshtml.pdb\D0A7F49CFC0845E4A3E5353C4E6358AF43\mshtml.pdb
7c620000 7c908000   kernel32 M (private pdb symbols)  C:\ProgramData\dbg\sym\kernel32.pdb\375CDA8E2B794AD6BC5F5BD69116B3FC45\kernel32.pdb
7c920000 7c9d1000   ntdll      (private pdb symbols)  C:\ProgramData\dbg\sym\ntdll.pdb\88B32AD594B4402F8A52E9D04ED37C0A51\ntdll.pdb
80081000 80088000   kdcom      (deferred)             
80088000 80090000   bootvid    (deferred) …
```
> Implement LdrpRecordUnloadEvent

- win32ss/user/user32/controls/edit.c
Use `#ifdef __REACTOS__` for WINESYNC'ed code.
Partially reverts 71ab0b5d4cb7fe00e0047308a18ae48c734266b9.
JIRA issue: [CORE-10266](https://jira.reactos.org/browse/CORE-10266)
> CORE-10266. [USER32] EDIT_WM_KillFocus(): Restore Wine code, #ifdef'ed out

- sdk/lib/crt/startup/crtexe.c
Native CRT on ARM & ARM64 Windows doesn't have these functions.
For compatibility, it's mandatory to not have it at all. Otherwise,
ARM executables built for ReactOS do not run on true ARM Windows.
> [CRT] ARM & ARM64 Windows do not have initenv in their CRTs

- sdk/lib/crt/except/arm/chkstk_asm.s
Incoming r4 contains the number of dwords to allocate, converting to bytes then return.
This makes ReactOS applications compiled for ARM running on true ARM Windows.
Reference: https://github.com/wine-mirror/wine/commit/2b095beace7b457586bd33b3b1c81df116215193
> [CRT] Implement __chkstk function for ARM

- dll/win32/shlwapi/shlwapi.spec
Improve export for SHEvaluateSystemCommandTemplate funtion in shlwapi by using `stdcall -stub` instead of `stub`.
Required by TuneUP service from TuneUP Utilites 2014. After my changes, it does no longer crash, and main app now works correctly. Since this stub it enough to avoid that crash, I guess it is not necessarily to add a full code stub.
JIRA issue: [CORE-14742](https://jira.reactos.org/browse/CORE-14742)
- Replace `stub` by `stdcall -stub`;
- Add function arguments according to MSDN, since using them is required by `stdcall -stub` unlike `stub`.
Before:
After:
> [SHLWAPI] Improve SHEvaluateSystemCommandTemplate export CORE-14742

- base/shell/explorer/trayclock.cpp
1. When shown: correctly calculate 1-second due time.
2. When hidden: stop useless timer(s), skip display update (easy code parts at least).
3. On setting changed: use correct delay (1-second or 1-minute).
> [EXPLORER] trayclock:Update taskbar clock display when it should (only)

- base/shell/explorer/lang/fr-FR.rc
_ One label is misplaced
_ "default" button is too narrow
JIRA issue: [CORE-16930](https://jira.reactos.org/browse/CORE-16930)
_ By opportunty improve fix of https://jira.reactos.org/browse/CORE-12386 on parent window
> [EXPLORER] Fix incorrect component position and size for French language

- dll/win32/netid/lang/fr-FR.rc
_ Missing fr-fr translation for some items
_ Wrong components size and/or position to fully display text
JIRA issue: [CORE-16597](https://jira.reactos.org/browse/CORE-16597)
_ Complete fr-fr translation of associated .rc file
_ Fix of component design (size, location, BS_MULTILINE).
> [NETID] Fix incorrect component position and size, complete translation for French language

- win32ss/gdi/ntgdi/font.c
- win32ss/user/ntuser/class.c
JIRA issue: [CORE-15811](https://jira.reactos.org/browse/CORE-15811)
> [WIN32K] Allocate a buffer for a classname that is too long

- dll/cpl/sysdm/userprofile.c
_ User Profiles window incorrectly release Heap zone in its OnDestroy() function, leading to undue closure of its parent Window
JIRA issue: [CORE-16921](https://jira.reactos.org/browse/CORE-16921)
_ Correct initialization of "Item" variable before using it
_ Protection against invalid Handle usage
_ Consistency of variable naming accross the window
> [SYSDM] User Profiles fix of OnDestroy (CORE-16921)

- dll/win32/shimgvw/shimgvw.c
JIRA issue: [CORE-16983](https://jira.reactos.org/browse/CORE-16983)
- Use `WS_EX_CLIENTEDGE` extended style for display window.
- Fix message `WM_SIZE` handling.
BEFORE:
AFTER:
> [SHIMGVW] Correctly draw display border

- dll/shellext/netshell/lanstatusui.cpp
_ Current Network information does not rely on system / user settings for date and time formatting
_ Current Network information always insert a "blank" DNS server line before the actual one.
JIRA issue: [CORE-16947](https://jira.reactos.org/browse/CORE-16947)
_ Use correct formatting
_ Remove erroneous DNS line
> [NETSHELL] Remove erroneous DNS Server line and fix date/time format

- dll/win32/setupapi/setupapi.spec
Improve exports for SetupRemoveFromSourceListA and SetupRemoveFromSourceListW functions in setupapi.dll by replacing `stub` with `stdcall -stub`. Also add functions arguments according to MSDN: https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupremovefromsourcelista, https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupremovefromsourcelistw, they are required by `stdcall -stub`.
It fixes EXCEPTION_WINE_STUB during installation the manufacturer's supplied software of USB wireless dongle D-LINK DWA-123, so now it does no longer fail (as confirmed by reporter).
JIRA issue: [CORE-16968](https://jira.reactos.org/browse/CORE-16968)
> [SETUPAPI] Improve SetupRemoveFromSourceListA/W exports CORE-16968

- modules/rostests/apitests/kernel32/CMakeLists.txt
- modules/rostests/apitests/kernel32/QueryUserAPC.c
- modules/rostests/apitests/kernel32/testlist.c
Add a testcase for `kernel32!QueryUserAPC`, `SleepEx` and `WaitForSingleObjectEx` functions.
WinXP:
Win2k3:
Win10:
ReactOS:
> [KERNEL32_APITEST] Add QueryUserAPC testcase

- media/inf/nettcpip.inf
_ Net TCP/IP strings are not localized, therefore some parts of Network Properties are not available for translation
_ Localization of display names and descriptions
_ First implementation in English and French
> [INF] Localize network services and drivers strings

- dll/apisets/api-ms-win-crt-private-l1-1-0.spec
- dll/win32/msvcrt/msvcrt.spec
XP x86 has this function.
`-version=0x600+` was erroneously added on 99fe069ce64f9b079b51e083ebb4e1b4092f71ff.
JIRA issue: [CORE-15135](https://jira.reactos.org/browse/CORE-15135)
> __DestructExceptionObject(): Update spec files. CORE-15135

- CODEOWNERS
Add missing translation teams
`*` is, because we have other file extension for translation somewhere like here: https://github.com/reactos/reactos/tree/master/base/setup/usetup/lang
Some language teams appears here more than one, like lang-chinese or portuguese, but I belive this list is not finished yet.
Lang codes: http://www.lingoes.net/en/translator/langcode.htm
> Update CODEOWNERS - translation section

- dll/cpl/desk/background.c
This patch makes some changes to the browse for wallpaper dialog. It sets and uses the lpstrInitialDir flag and sets it to the My Pictures folder. Please note Server 2003 doesn't have a My Pictures folder and instead sets the default folder to My Documents. This patch also adds the OFN_EXPLORER so the Open file dialog uses the XP/2003 style dialog instead of the old style dialog.
Photos below!
> [DESK] Set some flags for Browse for Wallpaper dialog

- dll/win32/shell32/COpenWithMenu.cpp
- When opening "Open With..." dialog for a given file format, multiple MRU items are appended to registry : 2 items written, even if dialog is closed "cancel".
- Expected behavior : 1 MRU item if execute is selected and 0 MRU if cancel is selected
JIRA issue: [CORE-16981](https://jira.reactos.org/browse/CORE-16981)
- MRU item write in registry only if "Execute" if selected (no MRU if "cancel")
- MRU item presence flag corectly set after writing MRU item to avoid multiple write action
> [SHELL32] Fix "Open With..." spamming registry MRU keys.

- dll/win32/syssetup/syssetup.spec
Improve an export for SetupQueryRegisteredOsComponent function in syssetup by using `stdcall -stub` instead of `stub`. Also, since this function is completely undocumented from MS side and there is no even any unofficial prototype, we don't know the function's arguments at all, so just use `()` without arguments then.
Required by Windows Media Encoder 9 installer from Rapps. This fix avoids the rundll32 crashes during WME9 installation. So now it installs without any errors.
Please note that it will install successfully only without VirtualBox Guest Additions installed. If they are installed, then installer will hang at the start of the installation due to another unrelated problem in netapi32. See the ticket description for details.
JIRA issue: …
> [SYSSETUP] Improve SetupQueryRegisteredOsComponent export CORE-16784

- win32ss/reactx/ntddraw/dxeng.c
Get complexity of visible region in DxEngGetDCState function, according to its remarks.
My implementation of that returns a number of rectangles that make up the region, similarly to as it done in `REGION_Complexity` function: https://git.reactos.org/?p=reactos.git;a=blob;f=win32ss/gdi/ntgdi/region.c;h=38bf3d377fa805e9db8768774c4fc473590252d0;hb=HEAD#l573.
Required by MS ddraw.dll when calling win32k/dxg functions during launching DirectDraw test or any DirectX 1 - 7 apps/games.
JIRA issue: [CORE-7733](https://jira.reactos.org/browse/CORE-7733)
- Implement type 2 of DxEngGetDCState;
- Add a comment;
- Update function remarks;
- Update copyright.
> [WIN32SS][NTDDRAW] Get complexity of visible region in DxEngGetDCState CORE-7733

- modules/rostests/apitests/crt/crtdll_crt_apitest.cmake
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/ntdll_crt_apitest.cmake
- modules/rostests/apitests/crt/testlist.c
- modules/rostests/apitests/crt/wctomb.c
CRT, NTDLL and MSVCRT testcase work flawlessly in Windows Server 2003, ReactOS and Windows XP (with the exception of NTDLL testcase in Windows XP as usual).
**Windows XP**
**ReactOS**
The implementation of `wctomb` in ReactOS is not that all gold and roses...
> [CRT_APITEST] Add testcase for wctomb()

- base/applications/mscutils/servman/control.c
- base/applications/mscutils/servman/lang/bg-BG.rc
- base/applications/mscutils/servman/lang/cs-CZ.rc
- base/applications/mscutils/servman/lang/de-DE.rc
- base/applications/mscutils/servman/lang/el-GR.rc
- base/applications/mscutils/servman/lang/en-US.rc
- base/applications/mscutils/servman/lang/es-ES.rc
- base/applications/mscutils/servman/lang/fr-FR.rc
- base/applications/mscutils/servman/lang/he-IL.rc
- base/applications/mscutils/servman/lang/id-ID.rc
- base/applications/mscutils/servman/lang/it-IT.rc
- base/applications/mscutils/servman/lang/ja-JP.rc
- base/applications/mscutils/servman/lang/ko-KR.rc
- base/applications/mscutils/servman/lang/no-NO.rc
- base/applications/mscutils/servman/lang/pl-PL.rc
- base/applications/mscutils/servman/lang/ro-RO.rc
- base/applications/mscutils/servman/lang/ru-RU.rc
- base/applications/mscutils/servman/lang/sk-SK.rc
- base/applications/mscutils/servman/lang/sq-AL.rc
- base/applications/mscutils/servman/lang/sv-SE.rc
- base/applications/mscutils/servman/lang/th-TH.rc
- base/applications/mscutils/servman/lang/tr-TR.rc
- base/applications/mscutils/servman/lang/uk-UA.rc
- base/applications/mscutils/servman/lang/zh-CN.rc
- base/applications/mscutils/servman/lang/zh-TW.rc
- base/applications/mscutils/servman/precomp.h
- base/applications/mscutils/servman/progress.c
- base/applications/mscutils/servman/resource.h
- base/applications/mscutils/servman/start.c
- base/applications/mscutils/servman/stop.c
_ Current design does not warn user nor logs DEBUG traces when Service Start/Stop command fails or reach timeout
_ Current Service Start/Stop progress window are WS_EX_TOOLWINDOW which reduce lisibility, is a ReactOS specificity without good reason
This is to be considered as a pre-requisite for https://jira.reactos.org/browse/CORE-16950 resolution, which will imply message pump to be added + interaction with running threads
_ DPRINT1 traces added on failure cases
_ Error Message box presented to user upon failure with explicit root cause identification
_ Change Dialog definition to standard Windows
> [SERVMAN] UI update and Error Management

- base/applications/rapps/include/resource.h
- base/applications/rapps/lang/bg-BG.rc
- base/applications/rapps/lang/cs-CZ.rc
- base/applications/rapps/lang/de-DE.rc
- base/applications/rapps/lang/en-US.rc
- base/applications/rapps/lang/es-ES.rc
- base/applications/rapps/lang/et-EE.rc
- base/applications/rapps/lang/fr-FR.rc
- base/applications/rapps/lang/he-IL.rc
- base/applications/rapps/lang/id-ID.rc
- base/applications/rapps/lang/it-IT.rc
- base/applications/rapps/lang/ja-JP.rc
- base/applications/rapps/lang/no-NO.rc
- base/applications/rapps/lang/pl-PL.rc
- base/applications/rapps/lang/pt-BR.rc
- base/applications/rapps/lang/pt-PT.rc
- base/applications/rapps/lang/ro-RO.rc
- base/applications/rapps/lang/ru-RU.rc
- base/applications/rapps/lang/sk-SK.rc
- base/applications/rapps/lang/sq-AL.rc
- base/applications/rapps/lang/sv-SE.rc
- base/applications/rapps/lang/tr-TR.rc
- base/applications/rapps/lang/uk-UA.rc
- base/applications/rapps/lang/zh-CN.rc
- base/applications/rapps/lang/zh-TW.rc
- base/applications/rapps/loaddlg.cpp
- Current RAPPS has many failure conditions during download process where process stops without user awareness nor logging, making root cause analysis difficult / impossible
JIRA issue: [CORE-16851](https://jira.reactos.org/browse/CORE-16851)
- Systematic error messages presented to the users when user awareness is required
- Additionnal logging when no additionnal user awareness is required (cancellation,...)
- All messages added to localization files
> [RAPPS] Add error messages on all download failure cases (CORE-16851)

- base/applications/sndvol32/dialog.c
- GetDC() is called without properly calling ReleaseDC() as required in order to releases a device context.
Similar to https://github.com/reactos/reactos/pull/2707
- Add missing ReleaseDC
> [SNDVOL32] Fix GetDC/ReleaseDC error management

- sdk/lib/crt/stdlib/mbstowcs.c
- sdk/lib/crt/string/wcs.c
`wctomb` is not addressed in this commit, it crashes our current testcase unit we have for that function.
Here are the test results for `mbstowcs` and `wcstombs`.
> [SDK][STDLIB][STRING] Wine-sync wcsrtombs_l and _mbstowcs_l

- dll/win32/shell32/dialogs/dialogs.cpp
Apply the OFN_EXPLORER flag to the Run dialog so the dialog uses the newer style browse dialog.
Why? Because it's a whole lot easier and quicker to browse for files with the newer style dialog. :)
> [SHELL32] Let the run dialog use the newer style browse dialog

- dll/win32/shell32/CDefView.cpp
- dll/win32/shell32/changenotify.cpp
- dll/win32/shell32/shelldesktop/CChangeNotifyServer.cpp
- dll/win32/shell32/shelldesktop/CChangeNotifyServer.h
Notify filesystem change notifications by using `ReadDirectoryChangesW` function. Creating/Deleting files/folders will be responsive in Explorer.
> [SHELL32] Notify filesystem changes

- dll/win32/advapi32/reg/hkcr.c
- In current implementation, when Regedit opens HKCR root key, an error is logged
err:(dll/win32/advapi32/reg/hkcr.c:964) Returning 259.
This is not correct as code 259 is for ERROR_NO_MORE_ITEMS which is the nominal return value when end of enumeration is reached.
Err is not displayed when ERROR_NO_MORE_ITEMS is returned.
> [ADVAPI32] Fix undue debug print in nominal case

- base/applications/regedit/regproc.c
- When exporting registry keys (to.reg files) some variables from the heap are not free'd while log indicates "HEAP: Trying to free an invalid address"
- This is due to the export_registry_key() function which includes call to 
HeapFree(GetProcessHeap(), 0, reg_key_name);
while reg_key_name. is an argument provided by the caller, which is always a statically defined array of WCHAR.
Menwhile reg_key_name_buf is never free'd and cause a memory leak each time the function gets called.
- Replace reg_key_name by reg_key_name_buf in the HeapFree instruction.
> [REGEDIT] Fix HeapFree() on the wrong variable causing memory leak and "HEAP: Trying to free an invalid address"

- dll/win32/shell32/dialogs/drvdefext.cpp
- dll/win32/shell32/folders/CDrivesFolder.cpp
Distinguish floppy drive and non-floppy removable drive in icon and description.
JIRA issue: [CORE-10221](https://jira.reactos.org/browse/CORE-10221)
> [SHELL32] Distinguish floppy and removable drives

- drivers/storage/ide/pciidex/pdo.c
This is the required value for both 'compatibility' and native-PCI modes.
JIRA issue: [CORE-9922](https://jira.reactos.org/browse/CORE-9922)
Co-Authored-By: Vadim Galyant \<vgal?rambler.ru\>
> [PCIIDEX] Increase command port length to 8 from 7. CORE-9922

- base/applications/rapps/loaddlg.cpp
change ```SetWindowLongW``` to ```SetWindowLongPtrW```
it's the same (because the value is 0) but I think it's better
> [RAPPS] 64bit compatibility fix

- base/system/userinit/livecd.c
- dll/cpl/desk/settings.c
- dll/cpl/sysdm/general.c
[SYSDM]
- When closing System Properties page, log show
(win32ss/user/ntuser/windc.c:749) err: [00060138] GetDC() without ReleaseDC()!
because GetDC() is called (multiple times) without properly calling ReleaseDC() as required in order to releases a device context.
- This module also lacks some error management in case null DC are provided (on error)
- LiveCD Userinit, based on SYSDM is affected too
[DESK]
- Fix missing ReleaseDC related to the spectrum (color depth)
- ReleaseDC() added
- Error management in case of null DC
- Overall alignement of LiveCD Userinit and SYSDM
> [SYSDM][DESK] Fix GetDC/ReleaseDC error management

- dll/win32/comctl32/button.c
- win32ss/user/user32/controls/button.c
Reverts reactos/reactos#2146.
#2135 (e329e83) and #2146 (2d4d3f5) are my mistakes. I misunderstood the difference with real Microsoft Tahoma font.
JIRA issue: [CORE-16552](https://jira.reactos.org/browse/CORE-16552), [CORE-16747](https://jira.reactos.org/browse/CORE-16747)
> Revert "[COMCTL32][USER32] Fix radio button regression"

- dll/win32/comctl32/treeview.c
- Current implementation from Wine comDlg32 Treeview component handles WM_SYSKEYDOWN at its level, therefore preventing management at upper level.
- As consequence, when focus is on a treeview (Regedit, EventViewer,....), ALT-F4 has no effect.
- Other components are not affected as they are not managing WM_SYSKEYDOWN in their "KeyDown" processing
JIRA issue: [CORE-17020](https://jira.reactos.org/browse/CORE-17020)
- Remove WM_SYSKEYDOWN handling at component level, in consistency with other components (ListView,...)
- Early embodiement of the fix proposed to WineHQ : https://bugs.winehq.org/show_bug.cgi?id=49097 in order to remove functionnal limitation in ReactOS.
> [COMDLG32] Fix Treeview undue handling of WM_SYSKEYDOWN

- dll/win32/comdlg32/filedlg.c
Add Recent Documents and My Network Places to the places bar in the open file dialog. There is an issue with label wrapping, I've looked at it, appears to be a bug deeper in comctl32 I think.
> [COMDLG32] Add some more places to the places bar

- dll/win32/shell32/folders/CDrivesFolder.cpp
Shell32 currently returns S_OK when browsing to a drive that does not exist.  This causes browseui to allow browsing to non-available drive letters.
The purpose of this PR is to address this issue by returning ERROR_INVALID_DRIVE if the drive is either unknown or unmounted.
Check to see if the drive type is unknown or unmounted by making a call to `GetDriveTypeW` while validating arguments in `CDrivesFolder`.  I'm not 100% sure if this is the correct place to do this check, so I'm definitely open to suggestions on changing how/where this is done.
- Invalid network locations continue to behave incorrectly.  I think network support in general is limited, so modifying this will take some future work.
> [SHELL32] Return ERROR_INVALID_DRIVE

- dll/win32/kernel32/winnls/string/lcformat.c
- Current implementation of GetCurrencyFormatW only supports "single digit" grouping format ("0", "3", ...) while ReactOs use it with "double digits" in Regional Settings ("32" in order to propose format la 12 34 567)
- Problem is located in GetCurrencyFormatW implementation where lpFormat->Grouping is only considered as a "constant" numeric grouping value (2, 3, ...) but does not support "multidigits" like 32 in order to respect lpDecimalSep definition in MSDN ( https://docs.microsoft.com/fr-fr/windows/win32/api/winnls/ns-winnls-currencyfmta ) and use case of currency grouping with parameter set to 32. This should be implemented in a similar way to GetNumberFormatW which supports format "32" in a specific way
JIRA issue: [CORE-17009](https://jira.reactos.org/browse/CORE-17009)
- Provide …
> [WINNLS] Fix of GetCurrencyFormatW to handle "32" grouping format

- win32ss/user/rtl/text.c
JIRA issue: [CORE-16747](https://jira.reactos.org/browse/CORE-16747)
BEFORE:
Spotify won't start up.
AFTER:
Spotify starts up.
Double checked.
> [WIN32SS] Fix DrawTextExWorker extent for Spotify

- media/inf/shortcuts.inf
- Addition of Wine IE Shortcuts in Start Menu. This was proposed as an improvement 4 years ago with a preliminary patch but never implemented. Dektop icon to be added in a dedicated PR (see comment from @binarymaster) 
JIRA issue: [CORE-11257](https://jira.reactos.org/browse/CORE-11257)
- Wine IE shortcut added to Start Menu Program with creation of additionnal string for localization.
- %16422% is used as per https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-dirids instead of %ProgramFiles% because of https://jira.reactos.org/browse/CORE-17016
> [SHORTCUTS] Addition of Wine IE Shortcuts in Start Menu

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtQueryInformationThread.c
- modules/rostests/apitests/ntdll/testlist.c
This is the initial implementation of a testcase unit for `NtQueryInformationThread`. It can be expanded later on.
**Windows XP**
**ReactOS**
> [NTDLL_APITEST] Add NtQueryInformationThread testcase

- dll/cpl/openglcfg/general.c
If the registry key that holds the names of installed
opengl drivers is missing, all list boxes in openglcfg
are empty. This is a minor code rearrangement to fix
this behavior.
> [OPENGLCFG] Empty list boxes if registry key is missing

- dll/win32/shell32/folders/CRecycleBin.cpp
- Avoid buffer overrun.
- Don't hardcode C: drive.
> [SHELL32] Don't hardcode C: drive again

- modules/rostests/apitests/ws2_32/WSAAsync.c
Split off from #1077.
JIRA issue: [ROSTESTS-317](https://jira.reactos.org/browse/ROSTESTS-317)
Result examples:
[(WTB) Job 45711, MAX=1](https://testbot.winehq.org/JobDetails.pl?Key=45711)
[(WTB) Job 45712, MAX=9](https://testbot.winehq.org/JobDetails.pl?Key=45712)
- Explicit trace, tiny delay to help a bit, **loop**.
> [WS2_32_APITEST:WSAASYNC] Fix and improve. ROSTESTS-317

- base/shell/explorer/trayprop.cpp
- dll/win32/comctl32/propsheet.c
In the file "win32ss / user / user32 / windows / dialog.c"
In the DIALOG_CreateIndirect (...) function, before calling CreateWindowEx (...) the code attempts to adjust the position of the window within the screen area if possible.
For this calculates:
dY = pos.y + size.cy - rcWork.bottom
if (dY> 0) pos.y - = dY;
this size.cy was read from IDD_PROPSHEET TEMPLATE structure
and has a value of 140.
Here we need the correct window height value which is that of the IDD_TASKBARPROP_TASKBAR TEMPLATE and is equal to (218 + Title_height + ExtraButtons_height) to subtract from the current position which is the position of the top left corner of the start button.
JIRA issue: [CORE 9008](https://jira.reactos.org/browse/CORE-9008)
(and will also improve [CORE …
> [COMCTL32] Fix Properties dialog position

- base/applications/regedit/childwnd.c
- base/applications/regedit/listview.c
- base/applications/regedit/main.h
- base/applications/regedit/treeview.c
Several fix and improvement identified during investigation for CORE-17020
- Current implementation misses a NULL Handle check in the Treeview creation
- When Editing a key name in treeview, incorrect Address bar and Status indicatation (double trailing slash) - see screenshot 
- Code could be better structured for maintainability by organizing the TreeView management of WM_NOTIFY in a similar way to what has been put in place for ListView (all NOTIFY code resp in listview.c or treeview.c). This will simplify lisibility and maintainability of the code.
- [CORE-17048](https://jira.reactos.org/browse/CORE-17048) shows a lack of error reporting to users when key edit in treeview fails
- Addition of NULL handle check
- Do not append a slash if already present in to-be key name
- Refactoring …
> [REGEDIT] Fix and improvement in TreeView (Null handle check, incorrect display after edit, WM_NOTIFY refactor)

- sdk/tools/cabman/cabinet.h
- sdk/tools/hhpcomp/utils.cpp
Without this, I would hit fun errors like:
```
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(17792,5): error C3861: '__stosb': identifier not found (compiling source file R:\src\wip\sdk\tools\cabman\mszip.cxx) [R:\build\wip\devenv_2019\host-tools\sdk\tools\cabman\cabman.vcxproj]
```
> [HOST-TOOLS] Fix the build from IDE for visual studio 2019 CE

- ntoskrnl/ps/security.c
- sdk/include/ndk/pstypes.h
Should make us hit that assert only when we actually need to do something.
JIRA issue: [CORE-8787](https://jira.reactos.org/browse/CORE-8787)
> [NTOS:SE] Implement job case in PsImpersonateClient. CORE-8787

- base/applications/mscutils/eventvwr/eventvwr.c
- base/applications/mscutils/eventvwr/lang/bg-BG.rc
- base/applications/mscutils/eventvwr/lang/cs-CZ.rc
- base/applications/mscutils/eventvwr/lang/de-DE.rc
- base/applications/mscutils/eventvwr/lang/el-GR.rc
- base/applications/mscutils/eventvwr/lang/en-US.rc
- base/applications/mscutils/eventvwr/lang/es-ES.rc
- base/applications/mscutils/eventvwr/lang/fr-FR.rc
- base/applications/mscutils/eventvwr/lang/he-IL.rc
- base/applications/mscutils/eventvwr/lang/it-IT.rc
- base/applications/mscutils/eventvwr/lang/ja-JP.rc
- base/applications/mscutils/eventvwr/lang/ko-KR.rc
- base/applications/mscutils/eventvwr/lang/no-NO.rc
- base/applications/mscutils/eventvwr/lang/pl-PL.rc
- base/applications/mscutils/eventvwr/lang/pt-BR.rc
- base/applications/mscutils/eventvwr/lang/ro-RO.rc
- base/applications/mscutils/eventvwr/lang/ru-RU.rc
- base/applications/mscutils/eventvwr/lang/sk-SK.rc
- base/applications/mscutils/eventvwr/lang/sq-AL.rc
- base/applications/mscutils/eventvwr/lang/sv-SE.rc
- base/applications/mscutils/eventvwr/lang/tr-TR.rc
- base/applications/mscutils/eventvwr/lang/uk-UA.rc
- base/applications/mscutils/eventvwr/lang/zh-CN.rc
- base/applications/mscutils/eventvwr/lang/zh-TW.rc
- base/applications/mscutils/eventvwr/resource.h
- boot/bootdata/hivesys.inf
Implementation of functional code for log properties page  (currently "set default", "Delete log" does nothing, apply systematically greyed, changes not saved nor taken into account...)
Implementation of functional code for log properties page in order to allow user to :
- Make modification and have them saved in registry when properties page is closed / apply is used and taken into account at the next session
- Set defaults (including correction of default max size)
- Delete content of log
- Make "Apply" button functional based on user inputs
- Keep current specific default values (no time based log pruning, extended size) as per discussion with @HBelusca : https://github.com/reactos/reactos/pull/2744#discussion_r420819152
> [EVENTVWR] Implementation of Properties page functionnal code.

- dll/cpl/main/lang/fr-FR.rc
- Some IU elements are incorrectly defined
- Some translation are wrong (copy/paste of other elements)
> [MAIN] Fix of Keyboard settings French translation

- dll/win32/devmgr/CMakeLists.txt
- dll/win32/devmgr/devmgmt/MainWindow.cpp
- dll/win32/devmgr/lang/bg-BG.rc
- dll/win32/devmgr/lang/cs-CZ.rc
- dll/win32/devmgr/lang/de-DE.rc
- dll/win32/devmgr/lang/el-GR.rc
- dll/win32/devmgr/lang/en-US.rc
- dll/win32/devmgr/lang/es-ES.rc
- dll/win32/devmgr/lang/et-EE.rc
- dll/win32/devmgr/lang/fr-FR.rc
- dll/win32/devmgr/lang/he-IL.rc
- dll/win32/devmgr/lang/hu-HU.rc
- dll/win32/devmgr/lang/id-ID.rc
- dll/win32/devmgr/lang/it-IT.rc
- dll/win32/devmgr/lang/ja-JP.rc
- dll/win32/devmgr/lang/no-NO.rc
- dll/win32/devmgr/lang/pl-PL.rc
- dll/win32/devmgr/lang/pt-BR.rc
- dll/win32/devmgr/lang/pt-PT.rc
- dll/win32/devmgr/lang/ro-RO.rc
- dll/win32/devmgr/lang/ru-RU.rc
- dll/win32/devmgr/lang/sk-SK.rc
- dll/win32/devmgr/lang/sq-AL.rc
- dll/win32/devmgr/lang/tr-TR.rc
- dll/win32/devmgr/lang/uk-UA.rc
- dll/win32/devmgr/lang/zh-CN.rc
- dll/win32/devmgr/lang/zh-TW.rc
- dll/win32/devmgr/precomp.h
- dll/win32/devmgr/resource.h
As the dialog simply displays the copyright names and nothing particular it makes sense to use ShellAboutW() instead.
Similar to #2743 by @HBelusca
> [DEVMGR] Use the ShellAboutW API routine to display the about dialog and French translation update

- ntoskrnl/ex/init.c
Detected by Cppcheck: identicalInnerCondition.
Addendum to c307d73c126758e2b123f32fb6f3e39299522a8e (r25621).
> [NTOS:EX] ExpInitializeExecutive(): Fix 'PerfMem' copypasta

- subsystems/mvdm/ntvdm/vddsup.c
No impact.
Detected by Cppcheck: redundantInitialization.
Addendum to ed874b41fc691f2dee27796b6d2f16777dc10d50 (r61283).
> [NTVDM] GetNextFreeVDDEntry(): Remove 'Entry' redundant initialization

- win32ss/user/ntuser/nonclient.c
No impact.
Detected by Cppcheck: identicalInnerCondition.
Addendum to 98060c28c8b051bc4cfd460bd008a2eff125658e (r60622).
> [WIN32K:NTUSER] NC_IconForWindow(): Remove redundant if()

- base/applications/cmdutils/label/label.c
Detected by Cppcheck: uninitvar.
Addendum to 6bfe4f68aff2011f2a840ddfe16cd42067033d8e.
JIRA issue: [CORE-9444](https://jira.reactos.org/browse/CORE-9444)
> [LABEL] wmain(): Initialize 'szBuffer'. CORE-9444

- dll/win32/shell32/wine/shellstring.c
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/CheckEscapes.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/reactos/undocshell.h
- Fix and improve `shell32!CheckEscapesA/W` functions.
- Add a testcase for `shell32!CheckEscapesA/W` to `shell32_apitest`.
> [SHELL32][INCLUDE] Improve CheckEscapesA/W

- dll/win32/mstask/CMakeLists.txt
- dll/win32/mstask/mstask.spec
- dll/win32/mstask/stubs.c
MSVC's LINK is not able to export both the undecorated and decorated symbol from the same dll. This results in an incoherence between the spec file entries and the actual exports, breaking the dll export versioning.
> [MSTASK] Add C stubs and comment out decorated exports

- dll/ntdll/ldr/ldrinit.c
Use lowest OS version GUID in the application manifest, instead of highest
> [NTDLL] Use lowest OS version GUID in the application manifest

- dll/win32/advpack/advpack.c
- dll/win32/mscoree/metahost.c
- dll/win32/mscoree/mscoree_main.c
- dll/win32/shlwapi/ordinal.c
Cherry-pick:
https://source.winehq.org/git/wine.git/commit/a359e026662251b7c3367fe2815dcb6cb371af50
https://source.winehq.org/git/wine.git/commit/0662da18b85634928905e72041961ffd3a6e8045
https://source.winehq.org/git/wine.git/commit/e4e5eda3d9afcb5360747ddd97e6bf4fdc0c1c0f
JIRA issue: [CORE-9665](https://jira.reactos.org/browse/CORE-9665)
Co-authored-by: Victor Martinez <vicmarcal@gmail.com>
> [REACTOS] RegQueryValueExW() wants bytes, not chars. CORE-9665

- win32ss/user/user32/windows/mdi.c
No impact.
Missed part of
https://source.winehq.org/git/wine.git/commit/fb6304119a967ea13688ff9e34ed9d819bd50785
Detected by Cppcheck: identicalInnerCondition.
Addendum to 303ece24219da7ec0cac1016767092287abd7877 (r72520).
> [USER32] MDIClientWndProc_common(): Properly sync to old Wine

- subsystems/win32/csrsrv/server.c
And remove unused NtRaiseHardError() assignment.
Detected by Cppcheck: redundantAssignment.
Addendum to d221bdfbb1581227c0933e7cf93c7de9cdead01d (r55647).
> [CSRSRV] CsrUnhandledExceptionFilter: Check RtlAdjustPrivilege() result

- dll/win32/shell32/shelldesktop/CChangeNotifyServer.cpp
- dll/win32/shell32/shelldesktop/CDirectoryWatcher.cpp
- dll/win32/shell32/shelldesktop/CDirectoryWatcher.h
- dll/win32/shell32/shelldesktop/CFilePathList.cpp
- dll/win32/shell32/shelldesktop/CFilePathList.h
- dll/win32/shell32/shelldesktop/CMakeLists.txt
Improve human readability of filesystem change notification.
Cc @yagoulas
- Rename the identifiers for human readabilities.
- Split the code into `CFilePathList` and `CDirectoryWatcher` classes.
- Encapsulation of code.
> [SHELL32] Improve readability of filesystem notification

- dll/win32/iphlpapi/ifenum_reactos.c
No impact.
Detected by Cppcheck: redundantCondition.
Addendum to 1fe3a2d6c307a1ec11d7728a9493360a5808e1ac (r9788).
> [IPHLPAPI] getNumInterfacesInt(): Remove 'if()' redundant condition

- dll/win32/kernel32/client/proc.c
Addendum to 21d2accad37825f47e3caa78ff36153751652238 (r71793).
> [KERNEL32] FatalAppExitW: Add an 'UNREFERENCED_LOCAL_VARIABLE(Status)'

- modules/rosapps/applications/devutils/cdmake/cdmake.c
No impact.
Detected by Cppcheck: doubleFree.
> [CDMAKE] Add 'DECLSPEC_NORETURN' to 'error_exit()'

- ntoskrnl/include/internal/i386/asmmacro.S
- ntoskrnl/include/internal/i386/trap_x.h
- ntoskrnl/ke/i386/traphdlr.c
- sdk/lib/rtl/i386/except_asm.s
If SEH is used in a C trap handler, the exception frame will be registered before the call to KiEnterTrap, which means we save the wrong exception frame. We'll therefore also restore this wrong frame for the excepting code, resulting in a stale SEH chain.
We avoid this problem by saving the handler in the assembly trap entry code. However, SEH in a C trap handler function will also not be correctly unwound, since the function never exits (it uses KiEoiHelper instead). This may result in finally handlers not running or other unexpected behavior. Therefore we still forbid doing this through asserts in the C KiEnterTrap variants.
JIRA issue: [CORE-15723](https://jira.reactos.org/browse/CORE-15723)
> [NTOS:KE] Avoid SEH in trap handlers. CORE-15723

- modules/rostests/apitests/ntdll/NtSetInformationProcess.c
`ProcessRaisePriority` class expects a buffer information of **KPRIORITY** type.
**Windows XP**
**Windows 10 Home 1909**
**ReactOS**
> [NTDLL_APITEST] Expand the NtSetInformationProcess testcase with some tests

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtSetInformationThread.c
- modules/rostests/apitests/ntdll/testlist.c
It seems like both XP and Server 2003 do privilege probe checks when setting a base priority to a thread whereas ReactOS doesn't. I've to fix that later.
**Windows XP**
**ReactOS**
> [NTDLL_APITEST] Add NtSetInformationThread testcase

- modules/rostests/apitests/apphelp/data.c
- modules/rostests/apitests/apphelp/layerapi.c
Detected by Cppcheck: memleak, redundantAssignment.
Addendum to 78280ad21f833411074e7ff0aa3d3345fb9e0704 (r71226).
> [APPHELP_APITEST] Properly handle a couple 'malloc()/free()'

- base/services/nfsd/readdir.c
Obviously, increase the value, not move the pointer!
JIRA issue: [CORE-17078](https://jira.reactos.org/browse/CORE-17078)
> [NFSD] readdir_copy_shortname(): Add needed brackets to '*name_size_out'. CORE-17078

- dll/win32/rpcrt4/rpcrt4.spec
Add export for NdrCreateServerInterfaceFromStub function in our rpcrt4.
Required by MS ole32.dll. Since this function is undocumented, and we don't know its exact arguments, use just `stub` for an export. Moreover, it's enough to allow MS ole32 no longer fail.
JIRA issue: [CORE-15395](https://jira.reactos.org/browse/CORE-15395), [CORE-17004](https://jira.reactos.org/browse/CORE-17004).
Before:
After:
> [RPCRT4] Export NdrCreateServerInterfaceFromStub as `stub`

- modules/rostests/kmtests/ntos_ob/ObTypes.c
Update Port and WaitablePort values.
https://reactos.org/testman/detail.php?id=48331275&prev=0
```
ObTypes.c:218: Port
ObTypes.c:218: Test failed: ObjectType->TypeInfo.InvalidAttributes = 0x00000fb2, expected 0x000007b2
ObTypes.c:219: WaitablePort
ObTypes.c:219: Test failed: ObjectType->TypeInfo.InvalidAttributes = 0x00000fb2, expected 0x000007b2
ObTypes: 828 tests executed (0 marked as todo, 2 failures), 0 skipped.
```
NB:
Core should set `0xfb2` instead of `0x7b2`, somewhere...
> [KMTESTS:OB] ObTypes: Support latest NT5.2 results

- win32ss/drivers/videoprt/videoprt.c
- win32ss/drivers/videoprt/videoprt.h
Detected by Cppcheck: funcArgOrderDifferent, redundantAssignment.
> [VIDEOPRT] IntVideoPortCreateAdapterDeviceObject(): 1+1 trivial fixes

- win32ss/gdi/gdi32/objects/region.c
Detected by Cppcheck: uselessAssignmentPtrArg.
Addendum to 794e7aa (r31523) and e647530 (r65893).
> [GDI32] MirrorRgnByWidth(): Fix 'phrgn' parameter handling

- dll/win32/winmm/time.c
Improve Windows Multimedia timer implementations.  Many games that use a frame-limiter to keep their framerate locked rely on these functions giving millisecond accurate timing readings.  The previous implementation of wrapping GetTickCount only offers accuracy of tens of milliseconds leading to unstable or slow framerates and gameplay.
JIRA issue: [CORE-17121](https://jira.reactos.org/browse/CORE-17121)
- Improve timeGetTime by using the more accurate QueryPerformanceCounter function when a high-resolution timer was requested.
- timeBeginPeriod with a resolution of 5ms or less will switch timeGetTime from using GetTickCount to QueryPerformanceCounter.
- timeEndPeriod with a resolution of 5ms or less will switch timeGetTime back to GetTickCount.
> [WINMM] Improve implementation of timeGetTime, timeBeginPeriod, timeEndPeriod

- win32ss/user/ntuser/callback.c
- win32ss/user/rtl/text.c
Fix uninitialized memory cause memory disclosure used for `KeUserModeCallback`.
<details>
<summary>Click to see</summary>
```c
#ifndef UNICODE
#define UNICODE
#endif 
#include <windows.h>
#include <stdio.h>
LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam);
typedef struct _WINDOWPROC_CALLBACK_ARGUMENTS
{
WNDPROC Proc;
BOOL IsAnsiProc;
HWND Wnd;
UINT Msg;
WPARAM wParam;
LPARAM lParam;
INT lParamBufferSize;
LRESULT Result;
/* char Buffer[]; */
} WINDOWPROC_CALLBACK_ARGUMENTS, *PWINDOWPROC_CALLBACK_ARGUMENTS;
int main()
{
return wWinMain(GetModuleHandle(NULL), NULL, GetCommandLineW(), SW_SHOWNORMAL);
}
int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE, PWSTR pCmdLine, int nCmdShow)
{
// Register the window class.
const wchar_t CLASS_NAME[] = L"Sample Window …
```
> [WIN32SS][NTUSER] Fix uninitialized memory cause memory disclosure used for KeUserModeCallback

- ntoskrnl/mm/arm/stubs.c
No impact.
Detected by Cppcheck: unreachableCode.
Addendum to ddaf47dec3f096666757ff2cc9892adc01da887c (r34976).
> [NTOS:MM] MiGetPageTableForProcess(): #if out unreachable code

- dll/cpl/sysdm/sysdm.c
Currently, sysdm.cpl loads a different icon for the title/task bar than what is used in Control Panel. This patch loads the proper icon.
> [SYSDM] Set the proper icon in title/task bar

- dll/apisets/api-ms-win-crt-utility-l1-1-0.spec
MSVC 'Release' build reports:
'dll\apisets\api-ms-win-crt-utility-l1-1-0_stubs.c(41): warning C4391: 'int llabs()': incorrect return type for intrinsic function, expected '__int64''
Addendum to 3f15a0d.
> [APISETS] api-ms-win-crt-utility-l1-1-0: Fix 'llabs' return type

- dll/win32/msi/msi_ros.diff
- dll/win32/msi/msvchelper.h
- dll/win32/ole32/ole32_ros.diff
MSVC build reports:
{{
dll\win32\msi\msvchelper.h(3): warning C4005: '__ASM_DEFINE_FUNC': macro redefinition
sdk\include\reactos\wine/asm.h(60): note: see previous definition of '__ASM_DEFINE_FUNC'
dll\win32\msi\custom.c(547): warning C4003: not enough actual parameters for macro '__ASM_DEFINE_FUNC'
}}
Addendum to 476c99b and 9efafd6.
> [MSI][OLE32] 1+1 removals, related to wine/asm.h

- base/services/svchost/svchost.h
- sdk/include/reactos/svc.h
Move all svchost declarations which should be global, from private svchost.h header to public svc.h header.
It will allow to use those declarations globally where they are required (e. g. for SvchostPushServiceGlobals functions in some services: https://www.geoffchappell.com/studies/windows/win32/services/svchost/dll/svchostpushserviceglobals.htm?tx=76).
That public header probably will be ROS-specific, since MS did not document it, see https://www.geoffchappell.com/studies/windows/win32/services/svchost/process/globaldata.htm?tx=78 instead.
No functional changes.
- Create a public sdk/include/reactos/svc.h header;
- Move there all declarations which should be public, from private base/services/svchost/svchost.h;
- Update the includes in svchost.h accordingly. Move all …
> [SDK][SVCHOST] Move all global svchost declarations to public header

- dll/win32/mswsock/mswsock.spec
- dll/win32/mswsock/stubs.c
Update the prototype of SvchostPushServiceGlobals() stub in mswsock, according to https://www.geoffchappell.com/studies/windows/win32/services/svchost/dll/svchostpushserviceglobals.htm, because this is completely undocumented from MS side.
It uses a public sdk/include/reactos/svc.h with global svchost declarations, which I added in my previous #2931 PR. Without that PR applied, the checks will fail. So please merge that first.
- Update the function prototype;
- Include svc.h header added in the previous PR;
- Update the comment by adding a link to the documentation.
> [MSWSOCK] Use a correct prototype for SvchostPushServiceGlobals stub

- base/applications/rapps/available.cpp
- base/applications/rapps/gui.cpp
- base/applications/rapps/include/available.h
- base/applications/rapps/include/misc.h
- base/applications/rapps/misc.cpp
move icon to a field in .txt file, no longer use the software's name
using the software's name may lead to some problems like the software name is too long, or contain some illegal chars (for example, ```Code::Blocks```. in a normal file name ```:``` is not allowed. ```:``` is used for alternate data streams in NTFS?)
some code is also added to check if ```../``` is used for directory escape
> [RAPPS] move icon to a field in .txt file

- win32ss/user/ntuser/window.c
- win32ss/user/user32/controls/listbox.c
win32ss/user/user32/controls/listbox.c   
Fixed wrong return from LB_GETLISTBOXINFO in case LBS_MULTICOLUMN
According to Microsoft the message LB_GETLISTBOXINFO should return the number of visible items in the column. In case of a list style LBS_MULTICOLUMN the returned value(line 3045), has no meaning since the calculation multiplies the number of items in a column by its width in pixels.
win32ss/user/ntuser/window.c Line _3422   must match listbox.c L_3045 
(see window.c line 3420)
> [USER32]  Fix wrong return from LB_GETLISTBOXINFO

- base/applications/network/net/cmdAccounts.c
No uninitialized use, as done at the other `RtlGetNtProductType()` calls.
https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=NT_PRODUCT_TYPE+.*ProductType&sr=1
> [NET] cmdAccounts(): Set ProductType default value

- modules/rostests/tests/sertest/sertest.c
Not compiled.
Detected by Cppcheck: uninitvar.
JIRA issue: [ROSTESTS-204](https://jira.reactos.org/browse/ROSTESTS-204)
Co-authored-by: Victor Martinez <vicmarcal@gmail.com>
> [ROSTESTS] sertest.c: Replace a busy loop with 'Sleep()'. ROSTESTS-204

- modules/rosapps/applications/devutils/createspec/CMakeLists.txt
- modules/rostests/winetests/advpack/CMakeLists.txt
- modules/rostests/winetests/fusion/CMakeLists.txt
- modules/rostests/winetests/msi/CMakeLists.txt
- modules/rostests/winetests/msvcrt/CMakeLists.txt
- modules/rostests/winetests/services/CMakeLists.txt
- modules/rostests/winetests/setupapi/CMakeLists.txt
- modules/rostests/winetests/shell32/CMakeLists.txt
- modules/rostests/winetests/user32/CMakeLists.txt
- modules/rostests/winetests/version/CMakeLists.txt
- sdk/cmake/gcc.cmake
> [CMAKE] Remove obsolete 'GCC_VERSION' checks

- win32ss/gdi/ntgdi/font.c
Fix pool memory disclosure in NtGdiGetOutlineTextMetricsInternalW
The memory disclosure occurs because the `Size` variable which is used at https://github.com/reactos/reactos/blob/a98bebb0b0a22ba833041eca08855955ecf60705/win32ss/gdi/ntgdi/font.c#L924 is greater than `sizeof(*potm)`. When I used msvc 14.0 x86 to compile ReactOS, `sizeof(*potm)` is 216 bytes whereas the value of `Size` variable is 300 bytes. This means that although all fields of `potm` are initialized then the redundant bytes still be uninitialized then they will be copied to user land memory at https://github.com/reactos/reactos/blob/a98bebb0b0a22ba833041eca08855955ecf60705/win32ss/gdi/ntgdi/font.c#L934-L935
> [Win32SS][GDI] Fix pool memory disclosure in NtGdiGetOutlineTextMetricsInternalW

- ntoskrnl/io/pnpmgr/plugplay.c
Fix pool memory disclosure in IopQueueTargetDeviceEvent
The device event entry is initialized at https://github.com/reactos/reactos/blob/a05051f5546ad2a118daf4e9de484b10b472f152/ntoskrnl/io/pnpmgr/plugplay.c#L63-L77 but some fields of it aren't initialized, for example: `EventEntry->Event.Result`, `EventEntry->Event.Flags`. The entry will be inserted into double linked list  at https://github.com/reactos/reactos/blob/a05051f5546ad2a118daf4e9de484b10b472f152/ntoskrnl/io/pnpmgr/plugplay.c#L84-L85
And at the function `IopQueueTargetDeviceEvent`, the event entry will be gotten at https://github.com/reactos/reactos/blob/a05051f5546ad2a118daf4e9de484b10b472f152/ntoskrnl/io/pnpmgr/plugplay.c#L1213-L1215 then copy its memory into user land memory at …
> [NTOS:IO] Fix pool memory disclosure in IopQueueTargetDeviceEvent

- sdk/cmake/host-tools.cmake
When building from the IDE in Release, the host-tools would be built in Debug,
and the targets using them expect to find them in the Release folder.
> [SDK] Fix host-tools build from visual studio ide in Release

- base/services/audiosrv/debug.c
Mininal workaround for
JIRA issue: [CORE-16814](https://jira.reactos.org/browse/CORE-16814)
> [AUDIOSRV] logmsg(): Disable its file part. CORE-16814

- base/applications/taskmgr/perfdata.c
Return string length, not buffer size.
> [TASKMGR] CachedGetUserFromSid(): Fix user name length on cache hit

- base/applications/network/telnet/CMakeLists.txt
- base/services/tftpd/CMakeLists.txt
- dll/3rdparty/libxslt/CMakeLists.txt
following upgrade to RosBE 2.2.0 support and GCC 8.4.
Split off from #2979.
> [CMAKE] Remove obsolete 'CMAKE_CXX_COMPILER_VERSION' checks

- ntoskrnl/include/internal/kd64.h
> [NTOS:KD64] Fix 'MAX_KD_COMPONENT_TABLE_ENTRIES' value

- base/applications/rapps/CMakeLists.txt
- base/applications/rapps/appview.cpp
- base/applications/rapps/gui.cpp
- base/applications/rapps/include/appview.h
- base/applications/rapps/include/gui.h
- base/applications/rapps/include/installed.h
- base/applications/rapps/include/misc.h
- base/applications/rapps/include/rosui.h
- base/applications/rapps/installed.cpp
- base/applications/rapps/misc.cpp
- sdk/lib/atl/atltypes.h
refactor application-view, fix some bugs and some trivial improvements
- application-view is now in a separate file (```appview.cpp```, corresponding header ```appview.h```). and add a header for ```gui.cpp``` (```gui.h```)
- ```GetSystemColorDepth``` are now moved into ```misc.cpp```
- fix missing ```inline``` in ```sdk/lib/atl/atltypes.h```
- fix & improve tab-order handling
- now double click on an item, or right click on an item and select Install in popup-menu will install exactly **this** application
> [RAPPS] application-view refactor

- ntoskrnl/ke/amd64/stubs.c
- ntoskrnl/ke/arm/usercall.c
- ntoskrnl/ke/i386/usercall.c
Fix stack memory disclosure in KiInitializeUserApc
In the function `KiInitializeUserApc`, the function `KeTrapFrameToContext` will initialize the value for local variable `Context` then copy value of `Context` to user land memory at https://github.com/reactos/reactos/blob/893a3c9d030fd8b078cbd747eeefd3f6ce57e560/ntoskrnl/ke/i386/usercall.c#L77-L84
But `KeTrapFrameToContext` will not initialize all fields of `Context`, it depends on the value of `Context.ContextFlags`. In x86 architecture, the value of `Context.ContextFlags` is `CONTEXT_FULL | CONTEXT_DEBUG_REGISTERS`, it still lacks some value, for example: `CONTEXT_EXTENDED_REGISTERS` so `KeTrapFrameToContext` will not execute bellow code:
https://github.com/reactos/reactos/blob/b20f81512688f26c91a131b81f41fc8cf9506f04/ntoskrnl/ke/i386/ex …
> [NTOS:KE] Fix stack memory disclosure in KiInitializeUserApc

- drivers/base/bootvid/arm/bootvid.c
- drivers/base/bootvid/common.c
- drivers/base/bootvid/i386/pc/pc.h
- drivers/base/bootvid/i386/pc/vga.c
- drivers/base/bootvid/i386/pc98/bootvid.c
- drivers/base/bootvid/i386/xbox/bootvid.c
- sdk/include/reactos/drivers/bootvid/bootvid.h
- sdk/include/reactos/drivers/pc98/video.h
Fix drawing strings on top of the bitmap.
JIRA issue: [CORE-15896](https://jira.reactos.org/browse/CORE-15896)
- Fix VGA pixel drawing
- Minor improvements
- Annotate some functions to avoid confusing
- Fix BitBlt behavior
- PC-98
- Improve text scrolling performance
- Fix failure handling
- Reduce memory mapping that's not needed
- Fix screen buffer copying code
> [BOOTVID] Fix drawing strings on top of the bitmap

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
- Add `imm32!ImmSetActiveContext` and `ImmSetActiveContextConsoleIME` function stubs.
> [IMM32] Add ImmSetActiveContext stub

- win32ss/user/ntuser/prop.c
Fix structure alignment cause to stack memory disclosure in NtUserBuildPropList
```
kd> dt win32k!PROPLISTITEM
+0x000 Atom             : Uint2B
+0x004 Data             : Ptr32 Void
kd> ??sizeof(PROPLISTITEM)
unsigned int 8
```
There are 2 padding bytes after field `Atom` and that structure is type of local variable `listitem`, value of `listitem` will be copied into user land memory at https://github.com/reactos/reactos/blob/c2c66aff7dacc62d125f2cd61d1167e9a2aa3fd6/win32ss/user/ntuser/prop.c#L181 so it leads to memory disclosure.
> [Win32SS][USER] Fix stack memory disclosure in NtUserBuildPropList

- dll/win32/imm32/CMakeLists.txt
- dll/win32/imm32/imm.c
- sdk/include/psdk/imm.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- Implement `imm32!ImmGetHotKey` function.
- Modify `NtUserGetImeHotKey` function.
- Add `LPHKL` typedef into `<imm.h>` header.
> [IMM32][NTUSER] Implement ImmGetHotKey

- base/shell/explorer/syspager.cpp
- base/shell/explorer/traywnd.cpp
- Check `pCopyData->dwData` value.
- Don't send message needlessly.
> [EXPLORER] Improve CTrayWindow::OnCopyData

- base/shell/explorer/appbar.cpp
- base/shell/explorer/traywnd.cpp
The AppBar window has to receive the `ABN_WINDOWARRANGE` notification message before and after the window arrangement from taskbar.
> [EXPLORER] Implement ABN_WINDOWARRANGE

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- Add the definition of `imm32!ImmGetImeInfoEx` function.
- Add `IMEINFOEXCLASS` and `IS_IME_HKL` into `"ntuser.h"`.
- Modify `NtUserGetImeInfoEx` function prototype.
> [IMM32][NTUSER] Add ImmGetImeInfoEx

- dll/cpl/appwiz/addons.c
JIRA issue: [CORE-14538](https://jira.reactos.org/browse/CORE-14538)
- Do not call `EndDialog` outside the dialog procedure.
> [APPWIZ] Don't hung up in Gecko download cancellation

- ntoskrnl/ps/debug.c
Fix stack memory disclosure in PsGetContextThread.
There is only one field of `GetSetContext.Context` is initialized at https://github.com/reactos/reactos/blob/8723be733c9fdc865fbd7ff4f7bac7a19ed301fa/ntoskrnl/ps/debug.c#L149 but `GetSetContext.Context` still be used to copy into user land memory at https://github.com/reactos/reactos/blob/8723be733c9fdc865fbd7ff4f7bac7a19ed301fa/ntoskrnl/ps/debug.c#L207 so it leads to stack memory disclosure.
> [NTOS:PS] Fix stack memory disclosure in PsGetContextThread

- base/applications/taskmgr/perfdata.c
- base/applications/taskmgr/perfdata.h
Fixes issue [CORE-17115](https://jira.reactos.org/browse/CORE-17115)
The `CMD_LINE_CACHE` index (`idx`) does not update when programs are closed. The following fix is implemented: compare it with the cache's process id (`pid`) and the process id determined by the index in the same cache.
> [TASKMGR] Fix display of process command-line string

- base/applications/regedit/regedit.c
Improve the messagebox responsible for importing the data from the *.reg file in Regedit.
Now it looks same as in Windows. The only difference is the translations, but I think it is not necessarily to make them identical to MS ones.
JIRA issue: [CORE-15494](https://jira.reactos.org/browse/CORE-15494)
- Remove "Cancel" button, since "No" and "Cancel" buttons do exactly the same thing. They both close the messagebox without applying the .reg file content and without terminating all other messageboxes if there is more than one.
Also remove IDCANCEL case for this.
- Disable Close button by setting the messagebox's window class style to `CS_NOCLOSE`, same as it done in Windows Regedit. Now it is not clickable, but still visible.
- Change the messagebox's icon type from warning icon to question …
> [REGEDIT] Improve importing registry files messagebox CORE-15494

- dll/win32/comctl32/static.c
[COMCTL32] Fix issue on showing  mouse pointer
GetIconInfo()  fill info.hbmColor with NULL HBITMAP handle on black/white bitmaps
JIRA issue: [CORE-17062](https://jira.reactos.org/browse/CORE-17062)
> [COMCTL32] Fix issue on showing mouse pointer on Mouse Prop Dlg

- drivers/filters/mountmgr/point.c
Fix pool memory disclosure in QueryPointsFromMemory of mountmgr driver
The memory disclosure happens when the comparison https://github.com/reactos/reactos/blob/a058e680b662ad4aca76e1fe4803fe033c124aa2/drivers/filters/mountmgr/point.c#L344-L354 is true or the loop at https://github.com/reactos/reactos/blob/a058e680b662ad4aca76e1fe4803fe033c124aa2/drivers/filters/mountmgr/point.c#L359-L361 doesn't execute (in case `DeviceEntry == &(DeviceExtension->DeviceListHead`) then `MountPoints` will be uninitialized.
Additional, structure type of `MountPoints` is MOUNTMGR_MOUNT_POINTS which has padding bytes.
```
kd> dt -b MOUNTMGR_MOUNT_POINTS
mountmgr_apitest!MOUNTMGR_MOUNT_POINTS
+0x000 Size             : Uint4B
+0x004 NumberOfMountPoints : Uint4B
+0x008 MountPoints      : _MOUNTMGR_MOUNT_POINT …
```
> [MOUNTMGR] Fix pool memory disclosure in QueryPointsFromMemory

- base/applications/rapps/appview.cpp
- base/applications/rapps/loaddlg.cpp
fix the not-working toolbar. now it's working again.
some workaround to reduce the chance assert failed.
https://jira.reactos.org/browse/CORE-16819
**this pr does not fix this bug.** I know what's causing it and fixing it completely requires a lot of time (which I don't have now). I will probably refactor all code about downloading later (which will fix this bug)
*as it's annoying and influencing user experience, I check the window's existence each time before operating on the window to reduce the chance assert failed.*
> [RAPPS] small bugfix and some workaround

- win32ss/user/ntuser/message.c
JIRA issue: [CORE-12124](https://jira.reactos.org/browse/CORE-12124)
Set the last error code `ERROR_INVALID_WINDOW_HANDLE` when `user32!PostMessage` failed with destroyed window.
> [NTUSER] Set ERROR_INVALID_WINDOW_HANDLE when PostMessage failed

- drivers/filesystems/reiserfs/src/write.c
'...\write.c(38): error C2373: 'RfsdFloppyFlush': redefinition; different type modifiers'
'...\write.c(45): error C2373: 'RfsdFloppyFlushDpc': redefinition; different type modifiers'
Similar to MS FastFAT.
> [REISERFS] Fix MSVC compilation with '_VS_ANALYZE_'

- boot/bootdata/hiveinst_pc98.inf
- sdk/cmake/CMakeMacros.cmake
- sdk/include/reactos/drivers/pc98/video.h
- win32ss/drivers/miniport/CMakeLists.txt
- win32ss/drivers/miniport/pc98vid/CMakeLists.txt
- win32ss/drivers/miniport/pc98vid/hardware.c
- win32ss/drivers/miniport/pc98vid/ioctl.c
- win32ss/drivers/miniport/pc98vid/pc98disp.inf
- win32ss/drivers/miniport/pc98vid/pc98vid.c
- win32ss/drivers/miniport/pc98vid/pc98vid.h
- win32ss/drivers/miniport/pc98vid/pc98vid.rc
- win32ss/drivers/miniport/pc98vid/pc98vid_reg.inf
Support generic graphics on PC-9821.
- Add framebuffer video miniport driver for NEC PC-98 series
AFTER:
> [PC98VID] Add framebuffer video miniport driver for NEC PC-98 series

- boot/freeldr/bootsect/fat32.S
This fixes a bug in the reactos bootcode
JIRA issue: [CORE-17178](https://jira.reactos.org/browse/CORE-17178)
- 
-
> [FREELDR] Bootsector fix for CHS read on old BIOSes which lack INT 3e

- base/applications/mspaint/lang/es-ES.rc
- base/applications/network/ping/lang/es-ES.rc
- base/applications/notepad/lang/es-ES.rc
- base/applications/osk/lang/es-ES.rc
- base/applications/rapps/lang/es-ES.rc
- base/shell/cmd/lang/es-ES.rc
- base/system/subst/lang/es-ES.rc
- base/system/userinit/lang/es-ES.rc
- base/system/winlogon/lang/es-ES.rc
General translation in Spanish.
Missing translations and spell corrections.
- Missing translations from applications: `mspaint`, `notepad` & `rapps`
- Missing translations and improvements on `osk`
- Missing translations on cmd help descriptions: `assoc`, `CTTY`, `replace`, `prompt `& `set`
- Missing translation on system: `subst`, `userinit` & `winlogon`
> [BASE] Improve Spanish translation

- dll/win32/shell32/droptargets/CRecyclerDropTarget.cpp
Trivial fix
- CRecyclerDropTarget spams log (Err rather than Trace) on nominal case
- replace ERR by TRACE.
> [SHELL32] CRecyclerDropTarget spams log (Err rather than Trace) on nominal case (trivial fix)

- win32ss/gdi/ntgdi/font.c
Fix pool memory disclosure in NtGdiGetGlyphOutline.
The value of `pvBuf` will be initialized in function `ftGdiGetGlyphOutline`. But in some cases like https://github.com/reactos/reactos/blob/52fb8c1a8d1d1ef2ddb46c017b461011b26188ee/win32ss/gdi/ntgdi/freetype.c#L4016-L4017 `ftGdiGetGlyphOutline` will return without initializing `pvBuf` so it will lead to memory disclosure when execute this https://github.com/reactos/reactos/blob/50510538db49b58b3364a0938a82879bc08890a3/win32ss/gdi/ntgdi/font.c#L767-L768
I guess this is a bug pattern when initializer function does a comparison then return immediately without initializing.
~~- [ ] Remove redundant RtlZeroMemory functions in `ftGdiGetGlyphOutline`~~
> [Win32SS][GDI] Fix pool memory disclosure in NtGdiGetGlyphOutline

- win32ss/gdi/ntgdi/freetype.c
- win32ss/gdi/ntgdi/text.c
Fix structure alignment leads to stack memory disclosure in NtGdiGetTextMetricsW
In msvc x86 build, compiler add 3 padding bytes after `TextMetric.tmCharSet` in the structure `TMW_INTERNAL`
```
kd> dt -b TMW_INTERNAL
win32k!TMW_INTERNAL
+0x000 TextMetric       : tagTEXTMETRICW
+0x000 tmHeight         : Int4B
+0x004 tmAscent         : Int4B
+0x008 tmDescent        : Int4B
+0x00c tmInternalLeading : Int4B
+0x010 tmExternalLeading : Int4B
+0x014 tmAveCharWidth   : Int4B
+0x018 tmMaxCharWidth   : Int4B
+0x01c tmWeight         : Int4B
+0x020 tmOverhang       : Int4B
+0x024 tmDigitizedAspectX : Int4B
+0x028 tmDigitizedAspectY : Int4B
+0x02c tmFirstChar      : Wchar
+0x02e tmLastChar       : Wchar
+0x030 tmDefaultChar    : Wchar
+0x032 tmBreakChar      : Wchar
+0x034 tmItalic         : UChar …
```
> [NTGDI] Fix stack memory disclosure in NtGdiGetTextMetricsW

- ntoskrnl/rtl/misc.c
- sdk/include/ndk/rtlfuncs.h
Implement `RtlGetNtProductType` in the kernel mode RTL and let `NtSetSystemPowerState` use it (this has to be investigated in the future why and how is the product type value used). 
The documentation of this function can be found here -> https://fraizeraust.github.io/pages/doc/ntoskrnl/rtl/prodver.html
> [NTOS:RTL] Implement the kernel-mode version of RtlGetNtProductType

- dll/opengl/opengl32/wgl.c
- wglCurrentContext raises the following error :
err:(dll/opengl/opengl32/wgl.c:747) Error: hdc is not a DC handle!
In particular during ROS installation, after declining Wine Gecko installation.
- Looking at the code and inspecting wgl.c from Wine HEAD : https://source.winehq.org/git/wine.git/blob_plain/HEAD:/dlls/opengl32/wgl.c
it appears that this "Err" is not an error, since we will naturally fall into this branch in particular when wglMakeCurrent(NULL, NULL) is called (from DLL_THREAD_DETACH or DLL_PROCESS_DETACH,....)
- This Err is not present in Wine's head (where the wglMakeCurrent is also much lighter)
JIRA: https://jira.reactos.org/browse/CORE-17224
- Remove unecssary ERR macro call.
> [OpenGL32] Remove Err Log Spam from wglMakeCurrent in nominal cases CORE-17224

- win32ss/gdi/gdi32/objects/font.c
- win32ss/gdi/ntgdi/text.c
_ReactOS has no Raster fonts today, so compensate for this affecting the editbox margins._
JIRA issue: [CORE-1091](https://jira.reactos.org/browse/CORE-1091)
This patch is from a concept and a rough patch by me that was polished by @katahiromz.
This patch fixes the inability to see all of the characters in the CD-KEY box of Starcraft and Visual Basic 5 and Visual Basic 6 Installs. It supersedes https://github.com/reactos/reactos/pull/2656
> [GDI32] Preserve PitchAndFamily across GetTextMetricsW call

- CMakeLists.txt
- boot/CMakeLists.txt
- boot/bootdata/packages/CMakeLists.txt
- sdk/cmake/CMakeMacros.cmake
Rework how our cdrom targets are generated, with proper dependency tracking, thanks to properties maintained at target level and avoiding calling functions at the end of the party.
Maybe we should move the add_cd_file function to boot/CmakeFiles.txt to make it clearer where everything comes from.
> Improve cdrom targets

- dll/win32/shell32/CDefView.cpp
- dll/win32/shell32/changenotify.cpp
- dll/win32/shell32/folders/CFSFolder.cpp
- dll/win32/shell32/shelldesktop/CChangeNotifyServer.cpp
- dll/win32/shell32/shelldesktop/CDirectoryList.cpp
- dll/win32/shell32/shelldesktop/CDirectoryWatcher.cpp
- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/wine/pidl.c
- Reduced the failures of `SHChangeNotify` testcase.
- Simplified change notification mechanism.
- Realized PIDL aliasing.
BEFORE:
AFTER:
> [SHELL32] Big fix for change notification

- base/setup/usetup/lang/fr-FR.h
- After selecting "French" during setup, 2 pages are still en english : version status and Licence T&C
- Translation in French of the above mentionned 2 pages.
> [SETUP] French translation of missing elements

- win32ss/user/ntuser/message.c
- Log spam issue with WM_ASYNC_DESTROYWINDOW, similar to past JIRA ticket https://jira.reactos.org/browse/CORE-10539 about WM_PAINT
- Missing \n in ERR() macro
- Formatting issues
- Change ERR to TRACE in WM_ASYNC_DESTROYWINDOW
- Fixed missing \n
- Fixed code formatting
> [WIN32SS] Log spam & log trivial fix

- modules/rostests/apitests/browseui/SHExplorerParseCmdLine.c
JIRA issue: [CORE-14177](https://jira.reactos.org/browse/CORE-14177)
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Skipped.
> [BROWSEUI_APITEST] Strengthen SHExplorerParseCmdLine testcase a bit

- win32ss/gdi/gdi32/objects/painting.c
_Fix 2 cases of cx used instead of cy._
No JIRA related issue
I stumbled onto this looking into fixing the StretchBlt function.
I discussed this with Jim Tabor and he agreed it was a typo error.
> [GDI32] Fix double cx's in call to HANDLE_METADC in win32ss painting.c

- dll/win32/browseui/basebarsite.cpp
- Make the captions of the explorer bars vertically centered.
BEFORE:
AFTER:
AFTER:
- Use `DT_VCENTER` to vertically center the text.
- Shrink the rectangle bottom 1 pixel.
> [BROWSEUI] Set DT_VCENTER to Explorer Bars' title

- dll/win32/browseui/shellfind/CFindFolder.cpp
JIRA issue: [CORE-17244](https://jira.reactos.org/browse/CORE-17244)
If the search phrase was not empty, it must not match the directory.
BEFORE:
AFTER:
- If there is the phrase to search, its match isn't a directory.
> [SHELLFIND] Fix directory search upon non-empty word/phrase query

- dll/win32/browseui/shellfind/CFindFolder.cpp
JIRA issue: [CORE-17250](https://jira.reactos.org/browse/CORE-17250)
- Consider UTF-8/UTF-16/UTF-16BE encodings in file search.
- Optimize for speed.
TestData:
BEFORE:
AFTER:
- Look the BOM (byte order mark) or NUL characters at the beginning of the file if any and find the text.
- If found, it became a match of a file item.
> [SHELLFIND] Encoding-aware file search

- base/shell/explorer/shellservice.cpp
- If goto cleanup is called, the key won't be closed.
JIRA issue: [CORE-14519](https://jira.reactos.org/browse/CORE-14519)
- Close key as 1st cleanup step (since neither nominal case which close the key, nor the failed key opening would lead there)
> [EXPLORER] Registry key not closed on error (CORE-14519)

- dll/win32/browseui/shellfind/CFindFolder.cpp
Split encoding detection code to improve code quality. @Extravert-ir This is follow-up of #3134 (7376cdebb6fc945798b29212c9f3239ea52cf89f).
JIRA issue: [CORE-17250](https://jira.reactos.org/browse/CORE-17250)
- Split encoding detection code as newly added `IsDataUnicode` function from `SearchFile` function.
> [SHELLFIND] Split encoding detection code

- dll/win32/shell32/dialogs/filedefext.cpp
- dll/win32/shell32/dialogs/filedefext.h
- Current design of ReactOS shows blank "size on disk" field in file & folders properties dialog from Explorer
- Current design does not take credit of C++ functions for String management (using CString class) 
- Current design use MAX_PATH sized buffers for strings not related to file path.
JIRA issue: [CORE-12559](https://jira.reactos.org/browse/CORE-12559)
- Implement computation and display of "size on disk", following recommendation from @Extravert-ir (Differs from initial code proposed by @amber8706 in comments of the Jira Ticket https://jira.reactos.org/browse/CORE-12559 )
- Refactoring of the recursive routine using CString, following recommendation from @learn-more
> [SHELL32] Show "size on disk" in file/folder properties

- drivers/filesystems/cdfs/volinfo.c
- drivers/filesystems/fastfat/volume.c
- drivers/filesystems/nfs/nfs41_driver.c
- drivers/filesystems/npfs/volinfo.c
- drivers/filesystems/udfs/volinfo.cpp
Fix structure alignment leads to pool memory disclosure in drivers support `FS_INFORMATION_CLASS.FileFsVolumeInformation`
The structure `_FILE_FS_VOLUME_INFORMATION`
```
kd> dt _FIlE_FS_VOLUME_INFORMATION
shell32!_FILE_FS_VOLUME_INFORMATION
+0x000 VolumeCreationTime : _LARGE_INTEGER
+0x008 VolumeSerialNumber : Uint4B
+0x00c VolumeLabelLength : Uint4B
+0x010 SupportsObjects  : UChar
+0x012 VolumeLabel      : [1] Wchar
```
is added 1 padding byte after the field `SupportsObjects` so it will lead to memory disclosure although all fields are initialized.
The backtrace report of bochspwn-reloaded:
```
#0  0x80581cb8 ((00181cb8) ntoskrnl.exe!memcpy+48)
#1  0x80485686 ((00085686) ntoskrnl.exe!IopCompleteRequest+1c6 [h:\project\reactos\ntoskrnl\io\iomgr\irp.c @ 292])
#2  0x8047b3aa ((0007b3aa) …
```
> [FILESYSTEMS] Fix pool memory disclosure in filesystem drivers supporting FS_INFORMATION_CLASS.FileFsVolumeInformation

- dll/shellext/fontext/CFontExt.cpp
- dll/shellext/fontext/CFontExt.hpp
- sdk/include/reactos/undocgdi.h
JIRA issue: [CORE-12861](https://jira.reactos.org/browse/CORE-12861)
This PR is a preparation of fonts folder implementation.
Not working yet.
- Use  `GetFontResourceInfoW` to get the font name.
> [FONTEXT] Initial implementation of CFontExt::DoGetFontTitle

- modules/rostests/apitests/shell32/ShellExecuteW.cpp
I want to support opening the special folders in `ShellExecute` function.
JIRA issue: [CORE-16939](https://jira.reactos.org/browse/CORE-16939)
- Add tests for special folders.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
ReactOS:
There are some failures.
> [SHELL32_APITEST] Strengthen ShellExecuteW testcase

- win32ss/user/winsrv/consrv/frontends/gui/lang/zh-CN.rc
The new word is more in line with PRC people's usage habits, and it
is actually used in the Simplified Chinese translation of Windows.
> [winsrv] improve zh-CN translation

- dll/win32/kernel32/client/proc.c
Match return type, to reduce confusion.
JIRA issue: [CORE-16757](https://jira.reactos.org/browse/CORE-16757)
> [KERNEL32] GetPriorityClass(): Return explicit 0, not FALSE

- dll/apisets/api-ms-win-crt-private-l1-1-0.spec
- dll/apisets/api-ms-win-crt-runtime-l1-1-0.spec
- dll/win32/msvcrt/msvcrt.spec
- dll/win32/msvcrt/stubs.c
- sdk/lib/crt/crt.cmake
- sdk/lib/crt/except/amd64/cpp.s
This adds/fixes some architecture specific exports, adds Vista specific exports and turns a few stubs into implementations.
> Add MSVCRT Vista exports

- dll/shellext/ntobjshex/lang/pl-PL.rc
Follow https://github.com/reactos/reactos/pull/3167 (pushed into master in https://github.com/reactos/reactos/commit/e358d1d2197906669e9d20fbba55d2383a0bfe70)
@reactos/lang-polish: Should we translate `Przestrzeń nazw NT Object` to `Przestrzeń nazw obiektów NT` and `Umożliwia przeglądanie przestrzeni nazw NT Object` to `Umożliwia przeglądanie przestrzeni nazw obiektów NT`?
> [NTOBJSHEX] Update Polish (pl-PL) translation

- dll/win32/shell32/precomp.h
- dll/win32/shell32/shell32.spec
- dll/win32/shell32/wine/shellord.c
- dll/win32/shlwapi/ordinal.c
- sdk/include/psdk/shellapi.h
- sdk/include/reactos/shlwapi_undoc.h
And:
[PSDK] Explicily use WINAPIV for the variadic ShellMessageBoxA/W functions.
[INCLUDE/REACTOS] Add ShellMessageBoxWrapW in shlwapi_undoc.h .
JIRA issue: [CORE-17271](https://jira.reactos.org/browse/CORE-17271)
See also PR #3172 by @KyleKatarn31.
This makes ShellMessageBoxW use the correct implementation where the
text buffer size is dynamic, instead of having a too small hardcoded
size.
However we cannot straightforwardly implement ShellMessageBoxA around
ShellMessageBoxW, by converting some parameters from ANSI to UNICODE,
because there may be some variadic ANSI strings, associated with '%s'
printf-like formatters inside the format string, that would also need
to be converted; however there is no way for us to find these and perform
the conversion ourselves.
Therefore, we …
> [SHELL32][SHLWAPI] Forward shell32.ShellMessageBoxW directly to shlwapi.ShellMessageBoxWrapW.

- base/system/format/format.c
- At the end of the format operation, text in console gets overwritten and leftovers from previous line remain displayed.
- Output the missing linefeed.
> [FORMAT] Fix of output text overlap in console when finished

- base/shell/progman/dialog.c
- sdk/lib/crt/misc/dbgrpt.cpp
- win32ss/user/user32/windows/cursoricon.c
These modules are not compiled as NT6+.
JIRA issue: [CORE-12004](https://jira.reactos.org/browse/CORE-12004)
> [REACTOS] Do not use LoadLibraryEx() NT6+ flags

- modules/rostests/apitests/shell32/ShellExecCmdLine.cpp
`ShellExecCmdLine` should support opening the special folders ("My Documents" and "Control Panel" etc.).
JIRA issue: [CORE-16939](https://jira.reactos.org/browse/CORE-16939)
- Add tests for "My Documents" and "Control Panel".
- Add some comments for usability.
Win10:
Successful.
ReactOS:
There are some failures.
> [SHELL32_APITEST] Strengthen ShellExecCmdLine testcase

- ntoskrnl/kdbg/kdb_symbols.c
kdbg leaks file handle when it fails to load the symbols from a module. This fixes that leak
Reorder operations so that file handle is always closed
> [KDBG] Fixed handle leak in KdbpSymLoadModuleSymbols() when RosSymCreateFromFile() fails

- drivers/storage/ide/pciidex/miniport.c
- drivers/storage/ide/pciidex/pciidex.spec
- drivers/storage/inc/ide.h
Useful for debugging IDE controller minidrivers.
AFTER:
> [PCIIDEX] Add missing exported function

- base/applications/rapps/gui.cpp
- When tying to modify/uninstall and empty selection, RAPPS crashes due to unhandled exception. This is due to the result of GetFocusedItemData() behind used without being checked non NULL.
JIRA issue: [CORE-17279](https://jira.reactos.org/browse/CORE-17279)
- Return FALSE and do nothing (as expected) when GetFocusedItemData() is NULL.
> [RAPPS] Fix of unhandled exception when trying to modify/uninstall without selection

- dll/win32/comctl32/listview.c
- dll/win32/shell32/CDefView.cpp
Fix the behaviors of keyboard arrow keys on desktop.
Enable reordering on auto-arrange listview.
JIRA issue: [CORE-16875](https://jira.reactos.org/browse/CORE-16875)
- Disable special auto-arrange codes in `LISTVIEW_GetNextItem` function.
- Add auto-arrange reordering codes on `CDefView`.
Arrow keys are working:
Auto-arrange reordering (by D&D) is working.
> [COMCTL32][SHELL32] Fix arrow keys and reordering on ListView

- dll/win32/kernel32/client/compname.c
Reduce failures of `kernel32_apitest` `SetComputerNameExW` testcase and improve `SetComputerNameExW`.
- Improve `IsValidComputerName` function.
- Add `BaseVerifyDnsName` function to implement `IsValidComputerName`.
- Set last error.
BEFORE:
There were many failures.
AFTER:
There is one failure. The last one failure is related to truncating.
> [KERNEL32] Improve SetComputerNameExW

- base/shell/cmd/history.c
- Cmd history command output is broken (missing linefeed)
JIRA issue: [CORE-12603](https://jira.reactos.org/browse/CORE-12603)
- Add linefeed as proposed by mjw and reviewed by @HBelusca in Jira
> [SHELL] Fix cmd.exe "history" output (missing linefeed)

- dll/shellext/mydocs/CMyDocsDropHandler.cpp
- dll/win32/shell32/CCopyToMenu.cpp
- dll/win32/shell32/CMoveToMenu.cpp
- dll/win32/shell32/droptargets/CFSDropTarget.cpp
- dll/win32/shell32/droptargets/CRecyclerDropTarget.cpp
- dll/win32/shell32/shellrecyclebin/recyclebin_v5.c
- dll/win32/shell32/shlfileop.cpp
- We are currently not logging failures of SHFileOperation in a systematic and consistent way
- Some ERR() are unduly triggered for normal operations
- We use GetLastError() while MSDN states : "Do not use GetLastError with the return values of this function."
- Result sometime wrongly used as HRESULT
- Systematic design pattern for SHFileOperation logging
- Explicit use of SHFileOperationW
- Replace ERR() by TRACE() for normal operations
- ERR() shows return code instead of GetLastError as per MSDN
- Result never used as HRESULT
> [SHELL32][SHELLEXT] Fix use of SHFileOperation results and improve log on failure / fix log spam

- base/applications/cmdutils/more/more.c
This PR will implement the 'Q' key on the command line tool 'MORE'.
JIRA issue: [CORE-4019](https://jira.reactos.org/browse/CORE-4019)
- Implement 'Quit' action for keyboard key 'Q'.
BEFORE:
It goes next page.
AFTER:
It quits.
> [MORE] Implement 'Q' key for 'Quit'

- base/applications/rapps/CreateCabFile.bat
- base/applications/rapps/CreateCabFile.sh
- sdk/tools/cabman/cabinet.cxx
- sdk/tools/cabman/cabinet.h
- sdk/tools/cabman/cabman.cxx
- sdk/tools/cabman/dfp.cxx
Update rapps example scripts for new usage
JIRA issue: [CORE-17230](https://jira.reactos.org/browse/CORE-17230)
We need to create 2 .cab files, since rapps cannot handle extracting folders without a code change.
To work around this, the first file does not include the icons (but rapps cannot extract it anyway),
and the second file (with a new name) does include the icons (and since rapps needs an update to change the filename, folder extraction can be added in the same update)
> [CABMAN] Add commandline support for creating a cab with folders

- sdk/cmake/msvc.cmake
to work around a CMake bug generating broken dll targets
JIRA issue: [ROSBE-159](https://jira.reactos.org/browse/ROSBE-159)
https://gitlab.kitware.com/cmake/cmake/-/issues/21180
> [SDK] Add dummy import lib files for MSVC_IDE build,

- base/applications/rapps/appview.cpp
- base/applications/rapps/include/appview.h
- base/applications/rapps/include/installed.h
- base/applications/rapps/installed.cpp
Allow Rapps to display custom app icons for installed software instead of just default Rapps icon.
In my opinion, default icon for each application looks monotonously and not informatively, because it doesn't display what it should. So displaying the custom app's icon instead will make it less hard to understand which app is actually installed.
Moreover, it already has been done for available apps (during GSoC 2020).
JIRA issue: [CORE-17257](https://jira.reactos.org/browse/CORE-17257)
- Implement `RetrieveIcon` helper function in `CInstalledApplicationInfo` class, which retrueves the current app's icon from registrty, same as it done for `CAvailableApplicationInfo`.
- Use it for loading the icon in `CAppsListView::AddInstalledApplication` function, via `ExtractIconW`. Load default Rapps …
> [RAPPS] Display custom applications icons for installed applications CORE-17257

- base/applications/rapps/installed.cpp
Use `RegDeleteKeyW` function instead of `RegDeleteKeyExW` for deleting the aspplications strings from registry, if the 2nd one is not available in advapi32.dll, on Windows versions whose don't have the Ex function (XP SP3 x32, Server 2003 SP0 and earlier). So now, on XP x64/Server 2003 SP1+, it will use Ex function, and on earlier versions - non-Ex one.
It will fix a regression with Rapps startup on these systems, due to that missing function.
JIRA issue: [CORE-17264](https://jira.reactos.org/browse/CORE-17264)
- First retrieve the advapi32 handle.
- It it has been found, get the address of `RegDeleteKeyExW` function.
- If the address has been found too, call that function from advapi32.dll with all required parameters.
- Otherwise, if it has not been found, call `RegDeleteKeyW` instead. …
> [RAPPS] Use `RegDeleteKeyExW` for deleting the apps strings from registry only if it is available in advapi32

- drivers/wdm/audio/backpln/portcls/pin_wavecyclic.cpp
Fix stutter that occurs with waveout mode in winamp using official ac97 driver
replace call to AllocatedBufferSize(), with BufferSize()
> [PORTCLS] fixed audio stutter with rosapps AC97 driver

- dll/win32/iphlpapi/ifenum_reactos.c
JIRA issue: [CORE-16513](https://jira.reactos.org/browse/CORE-16513)
_Fix iphlpapi regressiion tests which tend to cause multiple ASSERTS at present._
The comment is included to help speed the review and should be removed or updated on the commit or afterwards.
> [IPHLPAPI] Fix for hasArp which crashes some iphlpapi tests.

- dll/win32/comctl32/ipaddress.c
Improve IP address controls.
JIRA issue: [CORE-3479](https://jira.reactos.org/browse/CORE-3479)
- Set focus to `EDIT` control to show caret.
- Process `WM_GETDLGCODE` messages on `EDIT` control to catch Tab key.
- Process `Tab` key and `Shift+Tab` key in processing `WM_KEYDOWN`.
BEFORE:
Tab not working, Caret invisible.
AFTER:
Tab working, Caret visible.
> [COMCTL32] Improve IP Address Controls (Tab and caret)

- dll/win32/comdlg32/cdlg.h
- dll/win32/comdlg32/cdlg32.c
- dll/win32/comdlg32/filedlg.c
Enable key accelerators on File Open/Save Dialog.
JIRA issue: [CORE-14332](https://jira.reactos.org/browse/CORE-14332)
- Introduce `WH_MSGFILTER` hook upon `WM_INITDIALOG`.
- Add a critical section `COMDLG32_OpenFileLock`.
- The hook procedure `OpenFileMsgProc` calls `IShellView::TranslateAccelerator`.
- Disable hook upon `WM_DESTROY`.
AFTER:
`F2` and `Delete` keys are enabled.
> [COMDLG32] Support shortcut keys on Open/Save Dialog

- dll/win32/shlwapi/CMakeLists.txt
- dll/win32/shlwapi/autocomp.cpp
- dll/win32/shlwapi/url.c
- sdk/include/reactos/shlwapi_undoc.h
Retrial of #3214. Try to implment `shlwapi!SHAutoComplete` function.
- Modify `CMakeLists.txt` to add and compile `autocomp.cpp`.
- Add some functions to implement `SHAutoComplete`.
- Add `shlwapi!SHPinDllOfCLSID` function prototype into `shlwapi_undoc.h`.
- Try to implement `SHAutoComplete`.
> [SHLWAPI] 1/3-implement SHAutoComplete

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/shell32/dialogs/dialogs.cpp
Improve the usability of `Ctrl+Back` key combination on auto-completion (`AutoComplete`) edit boxes.
JIRA issue: [CORE-1419](https://jira.reactos.org/browse/CORE-1419)
- In module `browseui`, add `Edit_BackWord` function to delete previous word of caret.
- Use `Edit_BackWord` upon `WM_KEYDOWN` `VK_CONTROL`+`VK_BACK` (`Ctrl+Back`).
- In module `shell32`, add `CoInitializeEx` and `CoUninitialize` calls in `Run` dialog.
The key combination `Ctrl+Back` is well working in auto-completion edit boxes!
> [BROWSEUI][SHELL32] Enable Ctrl+Backspace in AutoComplete edit boxes

- dll/win32/browseui/CAutoComplete.cpp
Improve deletion of characters about `Ctrl+Back`.
JIRA issue: [CORE-1419](https://jira.reactos.org/browse/CORE-1419)
- Fix `Edit_BackWord` function by using `GetStringTypeW`.
> [BROWSEUI] Fix Edit_BackWord function

- modules/rostests/apitests/browseui/IACLCustomMRU.cpp
Add some tests for `"TypedURLs"` of a special case.
The `TypedURLs` key consists of the registry values of `"url1", "url2", "url3"` etc instead of `"MRUList", "a", "b"` etc.
- On registry key `"Software\\Microsoft\\Internet Explorer\\TypedURLs"`, save the `"url1"` and `"url2"` registry values.
- And then set `"aaa"` and `"bbb"` to the registry values.
- Create a `CLSID_ACLCustomMRU` with interface `IACLCustomMRU`.
- Initialize `IACLCustomMRU` with `TypedURLs`.
- Query `IEnumString` interface.
- Call `Next` and verify the values `"aaa"` and `"bbb"`.
- Restore `"url1"` and `"url2"` registry values.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
> [BROWSEUI_APITEST] Strengthen IACLCustomMRU testcase

- base/services/umpnpmgr/install.c
- base/services/umpnpmgr/precomp.h
- base/services/umpnpmgr/umpnpmgr.c
- base/setup/usetup/devinst.c
Actually use linked-lists. Reverts part of commit 043a98dd (see also commit b2aeafca).
Investigation of the bug crash reported at
JIRA issue: [CORE-16103](https://jira.reactos.org/browse/CORE-16103)
I investigate the usage of regular (doubly) linked lists with explicit mutex locking.
> WIP - [UMPNPMGR] Investigate bug crash. CORE-16103

- base/setup/usetup/consup.c
- base/setup/usetup/consup.h
Fix the visual "blinking" that occurs due to screen clearing, whenever a screen transition is done.
JIRA issue: [CORE-17312](https://jira.reactos.org/browse/CORE-17312)
Hide everything under the same foreground & background colors, so that
the actual color and text blanking reset does not create a visual "blinking".
Then, blank the text and finally reset the actual foreground &
background colors.
We do this because we cannot do the screen scrolling trick that would
allow to change both the text and the colors at the same time (the
function is currently not available in our console "emulation" layer).
> [USETUP] Fix usetup screen transition. CORE-17312

- dll/win32/browseui/ACLCustomMRU.cpp
- dll/win32/browseui/ACLCustomMRU.h
Related to #3249. `IACLCustomMRU` has to load the `TypedURLs` key correctly.
The `TypedURLs` key consists of the registry values of `"url1", "url2", "url3" etc` instead of `"MRUList"`, `"a"`, `"b"` etc.
- In `CACLCustomMRU::Initialize` method, if the key was `TypedURLs`, then load the `TypedURLs` registry key.
- If the key was `TypedURLs`, then don't save the entries.
- Implement `IEnumString` and `IACList`.
BEFORE:
2 failures, 1 skipped.
AFTER:
Successful.
> [BROWSEUI] Accept TypedURLs to CLSID_ACLCustomMRU

- drivers/network/tcpip/tcpip/dispatch.c
Implementing a patch submitted by hater which adds additional NULL checks to DispTdiQueryInformation, which return STATUS_INVALID_PARAMETER.
JIRA issue: [CORE-12274](https://jira.reactos.org/browse/CORE-12274)
-  Two additional NULL checks in DispTdiQueryInformation which cause STATUS_INVALID_PARAMETER to be returned instead of a NULL pointer dereference taking place in Kernel Mode.
> [DRIVERS:TCPIP] DispTdiQueryInformation NULL checks

- dll/win32/browseui/desktopipc.cpp
- dll/win32/browseui/shellbrowser.cpp
- dll/win32/browseui/travellog.cpp
- dll/win32/shell32/CFolder.cpp
This way, when the view asks for a directory _during creation_ it
does not get either an old, or an invalid directory
Also include some vaguely related bugfixes
JIRA issue: [CORE-17270](https://jira.reactos.org/browse/CORE-17270)
> [BROWSEUI] Update the current directory before creating a view

- base/system/winlogon/shutdown.c
- base/system/winlogon/winlogon.h
Display the shutdown message popup dialog on the current input desktop.
JIRA issue: [CORE-17050](https://jira.reactos.org/browse/CORE-17050)
Display the shutdown message popup dialog on the current input desktop,
and periodically monitor for any change of the input desktop. When the
latter changes, close the dialog and recreate it on the new input desktop.
In addition, retain the current dialog position and restore it when the
dialog is recreated on the new desktop.
> [WINLOGON] Display the shutdown message popup dialog on the current input desktop.

- boot/bootdata/hivesys.inf
This entry is unused as there is no biosinfo.inf anywhere yet, and it only breaks boot with NTLDR
Before:
After:
> [BOOTDATA] Comment out biosinfo.inf

- dll/win32/browseui/ACLCustomMRU.cpp
Delete "backslash one" (indicates `SW_` values) from auto-completion list.
BEFORE:
AFTER:
> [BROWSEUI] Remove '\1' from AutoComplete list

- base/shell/cmd/filecomp.c
When using cmd, you can press TAB to invoke auto filename completion,
but it could cause a incorrect result. For example, if the current
directory is `C:\Documents and Settings\Administrator\`, then you input
`".` and press TAB, the completion result would be `".Administrator"`,
which even does not exist.
Maybe it is a typo, because the `.` and the `/` are neighboring on the
keyboard.
> [CMD] Fix a typo in filename completion

- win32ss/user/ntuser/window.c
- win32ss/user/ntuser/winpos.c
Fix Shell Hook and reduce failures of `shell32_apitest ShellHook` testcase.
JIRA issue: [CORE-17330](https://jira.reactos.org/browse/CORE-17330)
- Fix the condition of notifying shell hook `HSHELL_WINDOWCREATED` in `ntuser/winpos.c`.
BEFORE:
Some failures.
AFTER:
Successful.
> [NTUSER] Fix Shell Hook HSHELL_WINDOWCREATED

- drivers/filesystems/fastfat/misc.c
- drivers/filesystems/fastfat/rw.c
- drivers/filesystems/fastfat/vfat.h
Cc may decide to process deferred writes any time, so the context might
already be freed by the time we return from CcDeferWrite.
Also mark the IRPs as pending.
JIRA issue: [CORE-17328](https://jira.reactos.org/browse/CORE-17328)
> [FASTFAT] Ensure that deferred write IRP contexts are not touched.

- ntoskrnl/ex/uuid.c
- ntoskrnl/include/internal/ex.h
Taking over #3086.
JIRA issue: [ROSTESTS-359](https://jira.reactos.org/browse/ROSTESTS-359)
Co-authored-by: Nguyen Trung Khanh <nguyentrungkhanh97@gmail.com>
> [NTOS:EX] ExUuidCreate(): Correctly fill Uuid->Data4

- ntoskrnl/include/config.h
- ntoskrnl/include/ntoskrnl.h
Cleanup.
```
* SERIALIZE_DBGPRINT: Removed on c15e04c (r18078).
* ENABLE_VALIDATE_POOL: Removed on 5899e14 (r42249).
* TAG_STATISTICS_TRACKING: Removed on 5899e14 (r42249).
* POOL_DEBUG_APIS: Removed on 5899e14 (r42249).
* R_RZ: Removed on 7d21cf7 (r48999).
* R_STACK: Removed on 7d21cf7 (r48999).
* WHOLE_PAGE_ALLOCATIONS: Removed on b431563 (r17306).
+
* _GLOBAL_PAGES_ARE_AWESOME_: Move it here.
```
> [NTOSKRNL] include/config.h: Sync it to current code

- CMakeLists.txt
- modules/rostests/tests/spec2def/CMakeLists.txt
- sdk/cmake/gcc.cmake
- sdk/cmake/host-tools.cmake
Use the ExternalProject CMake module instead of manually executing the process.
> |CMAKE] Use ExternalProject for host-tools build

- boot/bootdata/CMakeLists.txt
- boot/bootdata/bootcd/CMakeLists.txt
- boot/bootdata/bootcd/unattend.inf.in
Instead of messing around with a file in the source tree and risk commiting it
use cmake -DUNATTENDED_BOOTCD=yes to enable it, and use the UNATTENDED_BOOTCD_* cache variables to configure
> [CMAKE] Make unattended bootcd configurable via cmake

- dll/win32/mlang/mlang.c
MSVC:
'...\mlang.c(3568): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)'
Import
https://source.winehq.org/git/wine.git/commit/2dc0758b5d0fe4ef49b7d0635299e5cb9e0360df
> [MLANG] Fix scripts values in fnIMLangFontLink2_GetScriptFontInfo()

- dll/win32/shell32/shell32.spec
- dll/win32/shell32/stubs.cpp
Add a stubs for SHGetShellStyleHInstance and SHGetAttributesFromDataObject functions in our shell32.dll, according to the following references:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb762202(v=vs.85)
https://docs.microsoft.com/ru-ru/windows/win32/api/shlobj_core/nf-shlobj_core-shgetattributesfromdataobject
They are required by MS Picture and Fax Viewer (shimgvw.dll), together with replaced browseui.dll. Now it does no longer crash.
JIRA issue: [CORE-17337](https://jira.reactos.org/browse/CORE-17337)
Before:
After:
> [SHELL32] Stub SHGetShellStyleHInstance and SHGetAttributesFromDataObject CORE-17337

- drivers/filesystems/fastfat/fsctl.c
- drivers/filesystems/fastfat/misc.c
- drivers/filesystems/fastfat/vfat.h
This avoids blocking all Ex worker threads in fastfat, thereby making Cc
unable to issue the lazy writes that would unblock those workers.
This is more or less directly taken from fastfat_new.
JIRA issue: [CORE-17344](https://jira.reactos.org/browse/CORE-17344)
> [FASTFAT] Implement the overflow queue. CORE-17344

- win32ss/user/ntuser/winpos.c
_Code change to recognize Calculator Window Style and handle it like before the regression._
JIRA issue: [CORE-16827](https://jira.reactos.org/browse/CORE-16827)
> [WIN32SS] Repaint the whole window frame on some style bits set

- boot/bootdata/packages/CMakeLists.txt
Instead of being always out of date & always trigger reactos.cab creation
> [CMAKE] Make reactos_cab_inf really depend on reactos.inf

- modules/rostests/apitests/ntdll/LdrEnumResources.c
JIRA issue: [ROSTESTS-361](https://jira.reactos.org/browse/ROSTESTS-361)
> [NTDLL_APITEST] Fix LdrEnumResources testdata initialization

- subsystems/win/basesrv/dosdev.c
Addendum to commit 0a392b18.
Does what the title says :)
Re-enable validity checks that were originally disabled in 0a392b18 due to an unknown problem, that may have been fixed by my recent commit b3fa53f8.
> [BASESRV] Re-enable CsrValidateMessageBuffer() checks in BaseSrvDefineDosDevice().

- ntoskrnl/cc/mdl.c
Otherwise, drivers that have `MdlReadComplete = FsRtlMdlReadCompleteDev` are calling `CcMdlReadComplete2()` twice.
https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=FsRtlMdlReadCompleteDev
JIRA issue: [CORE-17342](https://jira.reactos.org/browse/CORE-17342)
> [NTOS:CC] CcMdl*Complete(): Return if FastIO succeeded

- modules/rostests/apitests/crt/atexit.c
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/testlist.c
- sdk/cmake/msvc.cmake
- sdk/lib/crt/crt.cmake
- sdk/lib/crt/startup/atonexit.c
- sdk/lib/crt/startup/crtexe.c
- sdk/lib/crt/stdlib/atexit.c
This improves the CRT situation a bit by removing the duplicated stuff and use the same code in msvcrtex as is exported from msvcrt. It also adds a simple apitest to validate that it works correctly.
> [CRT] Remove duplicate atexit/_onexit

- modules/rostests/kmtests/CMakeLists.txt
- modules/rostests/kmtests/hal/HalSystemInfo.c
- modules/rostests/kmtests/kmtest_drv/testlist.c
JIRA issue: [CORE-17359](https://jira.reactos.org/browse/CORE-17359)
> [KMTESTS:HAL] Add a test for HalQueryAMLIIllegalIOPortAddresses. CORE-17359

- dll/win32/psapi/psapi.c
The previous version was miscalculating the buffer size on x64 (due to alignment) and always using a too small buffer.
The new version removes the size calculation entirely and uses the required size returned by NtQuerySystemInformation.
> [PSAPI] Fix and simplify FindDeviceDriver

- modules/rostests/apitests/win32nt/ntgdi/NtGdiDeleteObjectApp.c
- win32ss/gdi/ntgdi/gdiobj.c
* [WIN32NT_APITEST] Add tests for truncated and extended handle to NtGdiDeleteObjectApp test
* [WIN32K] Fix an ASSERT to ignore the upper 32 bits of a passed in GDI handle
This PR wants @ColinFinck to fix the WHS x64 tester.
> [WIN32K] Fix handling of upper 32 bits of GDI handles on x64

- hal/halx86/amd64/x86bios.c
- hal/halx86/generic/halinit.c
- hal/halx86/include/halp.h
* Call HalInitializeBios both in phase 0 and 1
* In phase 0 allocate some physical memory, instead of using arbitrary hardcoded pages, that then end up as page tables and get filled with VESA tables
> [HAL:X64] Fix/improve the BIOS interface

- boot/bootdata/hivesys.inf
This gets ReactOS with Win2003 NT kernel + HAL boot a bit further.
Before:
After:
> [BOOTDATA] Add empty SystemPrefix value

- hal/halx86/generic/sysinfo.c
- hal/halx86/include/halp.h
Implement `HalQueryAMLIIllegalIOPortAddresses` case in `HaliQuerySystemInformation`.
Based on the patch by @vgalnt.
JIRA issue: [CORE-17359](https://jira.reactos.org/browse/CORE-17359)
> [HALX86] Implement HalQueryAMLIIllegalIOPortAddresses case in HaliQuerySystemInformation CORE-17359

- base/applications/regedit/find.c
Make the messagebox which notifies the user about finishing the search in registry, when no more items are found, owned by the main Regedit window. Now user will always see the notification on top until he will not close it manually. It repeats the behaviour of Windows Regedit.
JIRA issue: [CORE-17367](https://jira.reactos.org/browse/CORE-17367)
> [REGEDIT] Make finished find messagebox owned by Regedit window CORE-17367

- dll/win32/msgina/msgina.spec
- dll/win32/msgina/shutdown.c
Implement undocumented `ShellTurnOffDialog` function based on the (most of all correct) following prototype: http://diendan.congdongcviet.com/threads/t13622::tim-handle-cua-cua-so-tat-may-tren-windows-nhu-the-nao.cpp?p=69284#post69284 (line 32) and return ShellShutdownDialog from it with all required parameters.
It fixes the crash when trying to open the shutdown dialog from the Start Menu with shell32.dll (and other required dlls) from Windows Server 2003 SP2 (when installing ReactOS as Workstation). So now it opens successfully, and it is possible to restart or shutdown the system properly from Start Menu without logging off (with replaced shell).
JIRA issue: [CORE-17313](https://jira.reactos.org/browse/CORE-17313)
Before:
After:
> [MSGINA] Implement ShellTurnOffDialog CORE-17313

- ntoskrnl/include/internal/io.h
- ntoskrnl/io/iomgr/deviface.c
- ntoskrnl/io/iomgr/iomgr.c
- ntoskrnl/io/pnpmgr/devaction.c
- ntoskrnl/io/pnpmgr/devnode.c
- ntoskrnl/io/pnpmgr/pnpmgr.c
- ntoskrnl/io/pnpmgr/pnpnotify.c
- ntoskrnl/io/pnpmgr/pnpreport.c
- BUGFIX: do not call IoGetRelatedTargetDevice while guarded mutex is acquired
(the function issues an APC, but they are disabled inside a critical section)
- BUGFIX: only the beginning of a structure for GUID_PNP_CUSTOM_NOTIFICATION was copied and queued.
Just pass it as-is to a subscriber, without copying
- Don't convert event GUID to string, store and compare GUID struct itself
- Split IopNotifyPlugPlayNotification into 3 functions for each type of notification
(less stack usage and for future changes)
- Move initialization code for notifications into a separate routine
- Use separate lists and locks for every type of notification
- Put "TargetDeviceChange" notifications into their place inside DEVICE_NODE
> [NTOS:PNP] Fix and improve PnP notifications code

- modules/rostests/apitests/user32/SystemParametersInfo.c
- win32ss/user/ntuser/sysparams.c
This fixes a problem when the window title bar is dithered down to the 256/16-color palette.
See also [0705f303d054ac636a53ca04d9e41172fd7c36bc](https://git.reactos.org/?p=reactos.git;a=commit;h=0705f303d054ac636a53ca04d9e41172fd7c36bc).
BEFORE:
AFTER:
> [WIN32K:NTUSER] Fix gradient caption bars with low color depth

- base/applications/regedit/find.c
- base/applications/regedit/framewnd.c
- base/applications/regedit/main.h
Display the notification messagebox if no more items were found when search via "Edit" -> "Find Next" (or just F3 hotkey).
Also move the messagebox into separate function and call it in all appropriate places: in `FindDialog`, where it was from the start, and in the `ID_EDIT_FINDNEXT`, which is responsible for "Find Next" action.
So now it is more understandable whether the search was finished.
It repeats behaviour of Windows Regedit.
JIRA issue: [CORE-17368](https://jira.reactos.org/browse/CORE-17368)
> [REGEDIT] Display finished find messagebox after finishing the search via "Find Next" (F3) CORE-17368

- dll/win32/shell32/shell32.spec
Addendum to cdb48b8.
JIRA issue: [CORE-17337](https://jira.reactos.org/browse/CORE-17337)
> [SHELL32] spec: Fix SHGetAttributesFromDataObject() parameter types

- modules/rostests/apitests/gdi32/CMakeLists.txt
- modules/rostests/apitests/gdi32/SetLayout.c
- modules/rostests/apitests/gdi32/testlist.c
As part of the efforts to fix mirroring (Right-to-left UI), this apitest should help determine what is wrong currently in how certain functions behave when the DC is mirrored.
This test focuses mostly on BitBlt, StretchBlt and LPtoDP.
This apitest was inspired by PR #3109
I have figured a solution for the LPtoDP issue (based on how Wine does it)  but I'm currently waiting for PR #2942 (Horizontal flipping is one of the features of mirroring) so I could build upon that.
JIRA issue: [CORE-17298](https://jira.reactos.org/browse/CORE-17298)
Tests results:
Win10 version 2004
Win2003
ReactOS
> [GDI32_APITEST] Add tests for SetLayout and its effects

- base/applications/dxdiag/system.c
- dll/cpl/sysdm/general.c
- drivers/bus/acpi/main.c
- ntoskrnl/config/i386/cmhardwr.c
Creating this Pull Request to run on test bots, gonna merge quickly on success, but feel free to review anyway.
JIRA issues: [CORE-17413](https://jira.reactos.org/browse/CORE-17413) and [CORE-7952](https://jira.reactos.org/browse/CORE-7952)
- Properly fix ACPI driver (regression introduced by @tkreuzer in CORE-7952)
- Revert hack in Configuration Manager (committed by @christophvw in 7a985425)
- Fix displaying CPU identifier in System Properties and DxDiag
Fortunately our Device Manager didn't needed any changes at all and handled this gracefully. :slightly_smiling_face:
> Fix several problems with ProcessorNameString registry value

- dll/win32/msvcrt/msvcrt.spec
- sdk/lib/crt/startup/atonexit.c
- sdk/lib/crt/startup/crtdll.c
- sdk/lib/crt/startup/crtexe.c
- sdk/lib/crt/startup/gccmain.c
Fix atexit & _onexit
JIRA issue: [CORE-17362](https://jira.reactos.org/browse/CORE-17362)
Do not call CRT heap functions at initilization
Call MSVCRT's _onexit for executables
> Onexit fix

- drivers/storage/ide/uniata/id_ata.cpp
Emulate SCSI INQUIRY to properly recognize Xbox DVD drives and allow booting from them on a real OG Xbox.
JIRA issue: [CORE-16692](https://jira.reactos.org/browse/CORE-16692)
Explicitly check known drives by their names using ATA IDENTIFY PACKET fields. It should be possible to send INQUIRY anyway and then check for `SCSI_SENSE_ILLEGAL_REQUEST` error code, but I found it too hard to implement, so I'd let @Alter-1 implement this feature in upstream if he wants.
These notes were found by @Extravert-ir while investigating this problem. Maybe this could be an argument for adding it officially to UniATA driver.
```
In Linux, if the DEVICE exists and the SCSI INQUIRY fails (e.g. because
the SG_IO ioctl is not supported) then an ATA IDENTIFY (PACKET)  DEVICE
is tried. If it succeeds then device …
```
> [UNIATA] Emulate SCSI INQUIRY to properly recognize Xbox DVD drives

- drivers/bus/acpi/main.c
JIRA issue: [CORE-10207](https://jira.reactos.org/browse/CORE-10207)
> [ACPI] AcpiRegOpenKey(): Add a missing OBJ_KERNEL_HANDLE

- ntoskrnl/ex/sysinfo.c
- sdk/include/ndk/extypes.h
This field is the current number of processors in the system plus the number of processors that could be added without rebooting.
https://www.geoffchappell.com/studies/windows/km/ntoskrnl/api/ex/sysinfo/processor.htm
> [NDK] Rename Reserved to MaximumProcessors in SYSTEM_PROCESSOR_INFORMATION

- base/shell/cmd/lang/id-ID.rc
Improve Indonesian (ID-id) translation for several CMD links:
+ Change "version" to "versi"
+ Fully translate the "color" command help text (the former translation version still have a bunch of English words)
+ Consider using more formal words such as "dapat" instead of "bisa", and "...di bawah ketentuan lisensi GNU General Public License sebagaimana..." instead of "...di bawah term lisensi GNU General Public License seperti..." (**Original text:** ...under the terms of GNU General Public License as...")
> [CMD] Improve Indonesian (ID-id) translation

- sdk/lib/crt/msvcrtex.cmake
fixes:
```
CMake Error: CMake can not determine linker language for target: ftol2_sse
```
> [CMAKE] Fix MSVC configuring

- boot/bootdata/CMakeLists.txt
The program is listed in Start Menu accessibility items for BootCD builds but not in LiveCD ones.
> [BOOTDATA] Link the Accessibility Utility Manager for LiveCD builds

- drivers/storage/port/scsiport/fdo.c
- media/inf/scsi.inf
Fixes UniATA root SCSI devices detection in the Device Manager. **IMPORTANT:** This depends on PR #3437.
Based on the description of `GEN_SCSIADAPTER` from Windows `pnpscsi.inf` (see also [this reference](https://community.osr.com/discussion/41967/installing-isa-scsi-miniport-driver-through-f6-on-fresh-install-of-windows-2000-problem)):
```
;*********************************
;Generic scsi adpater - compatible ID match on GEN_SCSIADAPTER
;as a method of making all non-pnp miniports have their adapters
;show up as scsi adapters in devmgr. Scsiport adds this id to
;legacy detected adapters.
```
See also chat messages:
- https://chat.reactos.org/reactos/pl/qii1w36wu7yrxyukh9b5dzwnje
- https://chat.reactos.org/reactos/pl/f5tanc9nfjdb5m17nhrq33994a
JIRA issue: …
> [SCSIPORT] Append GEN_SCSIADAPTER compatible ID for legacy adapters

- ntoskrnl/include/internal/tag.h
- ntoskrnl/se/token.c
- sdk/include/ndk/setypes.h
Instead of using a global lock for tokens, initialise the lock locally every time a token is about to be created or duplicated (as in Windows Server 2003).
> [NTOS:SE] Do not use a global lock for tokens

- dll/win32/shell32/COpenWithMenu.cpp
Fixing the bug where open with menu where OpenWithMenu does not handle handler's path when there are spaces in the path string.
JIRA issue: [CORE-17445](https://jira.reactos.org/browse/CORE-17445)
- Adds quote marks around %1 when recording the registry entry for file handler.
> [SHELL32] Fixing COpenWithMenu.cpp for handling path strings with spaces

- modules/rosapps/applications/sysutils/utils/driver/load/load.c
- modules/rosapps/applications/sysutils/utils/driver/unload/unload.c
Less warnings, work better.
NB:
I don't know a successful case.
*WXP: Various NTSTATUS.
*ROS: Always '0xc0000061 = STATUS_PRIVILEGE_NOT_HELD'.
Also:
*Set ServiceName.MaximumLength.
*Fix MSVC warnings.
'...\load\load.c(19): warning C4267: '=': conversion from 'size_t' to 'USHORT', possible loss of data
+
'...\unload\unload.c(19): warning C4267: '=': conversion from 'size_t' to 'USHORT', possible loss of data'
'...\unload\unload.c(24): warning C4476: 'wprintf' : unknown type field character 'U' in format specifier'
'...\unload\unload.c(24): warning C4474: 'wprintf' : too many arguments passed for format string'
> [LOAD][UNLOAD] Fix w*printf() format strings

- ntoskrnl/mm/ARM3/virtual.c
- win32ss/drivers/videoprt/int10.c
- win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
Make that address range unavailable to user-mode (only CSRSS.exe affected) and avoid weird behaviour such as NOT CRASHING ON NULL ACCESS.
- Call ZwAllocateVirtualMemory(PAGE_NOCCESS) on the said memory range once we are done with it. ZwProtectVirtualMemory is unavailable for kernel drivers...
> [VIDEOPRT] Mark range 0x00000000 - 0x000A0000 as no access outside of dedicated functions

- win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
> [CONSRV] SetConWndConsoleLeaderCID(): Check must be before deref

- dll/cpl/mmsys/sounds.c
Add the OFN_EXPLORER flag to the Browse for sound dialog to take advantage of the newer XP/Server 2003 style dialog.
> [MMSYS] Add the OFN_EXPLORER flag to the Browse for sound dialog

- dll/win32/shimgvw/shimgvw.c
- Make the calls of `CallWindowProc` and `DefWindowProc` Wide (Unicode).
- Delete needless type casts.
- Add `const` to function arguments.
- Improve `ImageView_LoadSettings` function.
- Insert `OFN_EXPLORER` flag.
> [SHIMGVW] Refactoring

- ntoskrnl/wmi/wmi.c
Supersedes #3381.
JIRA issue: [CORE-17384](https://jira.reactos.org/browse/CORE-17384)
Test log:
```
(/ntoskrnl/wmi/wmi.c:112) IoWMIWriteEvent() called for WnodeEventItem FCAD8708 (Flags = 0x00120000), returning success
(/ntoskrnl/wmi/wmi.c:116) IoWMIWriteEvent(): Flags has WNODE_FLAG_TRACED_GUID
```
> [NTOS:WMI] IoWMIWriteEvent(): Add WNODE_FLAG_TRACED_GUID case

- modules/CMakeLists.txt
- win32ss/gdi/dib/dib16bpp.c
- win32ss/gdi/dib/dib1bpp.c
- win32ss/gdi/dib/dib24bpp.c
- win32ss/gdi/dib/dib32bpp.c
- win32ss/gdi/dib/dib32bppc.c
- win32ss/gdi/dib/dib4bpp.c
- win32ss/gdi/dib/dib8bpp.c
- win32ss/gdi/dib/stretchblt.c
- win32ss/gdi/eng/bitblt.c
- win32ss/gdi/eng/copybits.c
- win32ss/gdi/eng/stretchblt.c
- win32ss/gdi/ntgdi/bitblt.c
- win32ss/gdi/ntgdi/dibobj.c
_Modify dib\dibxxbpp.c programs to understand flipped images._
JIRA issue: [CORE-16642](https://jira.reactos.org/browse/CORE-16642)
and
JIRA issue: [CORE-14408](https://jira.reactos.org/browse/CORE-14408)
Improvements to JIRA issue: [CORE-16634](https://jira.reactos.org/browse/CORE-16634)
1) Mirroring Horizontally works.
2) Mirroring Vertically works.
3) Rotation 180° works.
See Videos at [CORE-16642](https://jira.reactos.org/browse/CORE-16642)
This is an update of [PR#2942](https://github.com/reactos/reactos/pull/2942)
Before:
After:
> [WIN32K] Add StretchBlt function ability to flip images

- dll/win32/shimgvw/shimgvw.c
Improve code for standardization and erasing warning.
- Use `_countof` macro instead of non-standard `ARRAYSIZE` macro.
- Use `UINT` type for array index instead of `INT` type, for erasing signed/unsigned comparison warning.
> [SHIMGVW] Use _countof instead of ARRAYSIZE and use UINT

- dll/opengl/opengl32/swimpl.c
_Swap red and green values in swimpl.c._
JIRA issue: [CORE-16221](https://jira.reactos.org/browse/CORE-16221)
> [OPENGL32] Fix Red and Green Color Swap

- boot/freeldr/freeldr/arch/i386/pc/machpc.c
- boot/freeldr/freeldr/arch/i386/pc98/pc98hw.c
Addendum to 17990b2 (r73617).
JIRA issue: [CORE-12623](https://jira.reactos.org/browse/CORE-12623)
> [FREELDR] DetectPnpBios(): Add 'i' to an ERR()

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/CAutoComplete.h
Improve readability of `CAutoComplete` code.
- Expand tabs to spaces in `CAutoComplete.h`.
- Add `m_` prefix to every member variable.
> [BROWSEUI] Refactoring CAutoComplete Part 1

- dll/win32/browseui/CAutoComplete.cpp
Fix a mistake in `CAutoComplete` PR #3472 (https://github.com/reactos/reactos/commit/6bfb76b68a7f8fe12b4fa4503b6225297108dd0c) and improve.
- Fix confusion between `m_hwndEdit` and `hwndEdit`.
- Delete extra `this->` codes.
> [BROWSEUI] CAutoComplete: Small fix and small improvements

- modules/rostests/apitests/atl/CMakeLists.txt
- modules/rostests/apitests/atl/SubclassWindow.cpp
- modules/rostests/apitests/atl/devenv/.gitignore
- modules/rostests/apitests/atl/devenv/ATLTest.sln
- modules/rostests/apitests/atl/devenv/SubclassWindow.vcxproj
- modules/rostests/apitests/atl/testlist.c
- sdk/lib/atl/atlwin.h
I want `CWindowImpl::UnsubclassWindow` and `CContainedWindowT::UnsubclassWindow` to implement AutoComplete (auto input completion).
- Implement `CWindowImpl::UnsubclassWindow` method.
- Implement `CContainedWindowT::UnsubclassWindow` method.
- Add `SubclassWindow` testcase to `atl_apitest` test program.
- Fix generic text mapping of `<atlwin.h>`.
> [SDK][ATL] Implement UnsubclassWindow methods

- sdk/lib/atl/atlwin.h
- Fix generic text mapping for `GetWindowText` and `GetWindowTextLength` functions.
- Fix the length.
- Fail elegantly if necessary.
> [SDK][ATL] Fix CWindow::GetWindowText method of BSTR

- modules/rostests/apitests/browseui/IAutoComplete.cpp
- Test the extended list-view style of the listview.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
> [BROWSEUI_APITEST] Strengthen IAutoComplete testcase on extended LV style

- modules/rostests/apitests/ntdll/NtQueryInformationProcess.c
Attempt to fix one understandable case of a flaky test in ntdll_apitest.
Testbots will show if that test reliably passes now.
https://github.com/reactos/reactos/pull/2906#issuecomment-641274438 proves that this was a problem not just under ReactOS, but also under Windows Server 2003.
JIRA issue: [CORE-17483](https://jira.reactos.org/browse/CORE-17483)
> [NTDLL_APITEST] Ensure that some noticeable time has passed since process creation to fix a flaky test.

- ntoskrnl/kd/kdio.c
And assert being in kernel mode
to be explicit that using Nt*() is safe.
> [NTOS:KD] KdpDebugLogInit(): Close the thread handle

- modules/rostests/apitests/browseui/IAutoComplete.cpp
Improve the `IAutoComplete` testcase.
- Simplify the test mechanism.
- Add more tests for `WM_KEYDOWN` message.
WinXP:
Win2k3:
Win10:
> [BROWSEUI_APITEST] Strengthen IAutoComplete on WM_KEYDOWN

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtCompareTokens.c
- modules/rostests/apitests/ntdll/testlist.c
- ntoskrnl/se/token.c
This implements the rest of `SepCompareTokens()` code which makes `NtCompareTokens()` able to properly distinguish the tokens.
* Implement SepCompareSidAndAttributesFromTokens and SepComparePrivilegeAndAttributesFromTokens functions for array elements comparison
* Implement the token comparison code in SepCompareTokens function
* Add a missing PAGED_CODE() in SepCompareTokens as most of the token comparison code is paged
* Use SAL annotations for SepCompareTokens and NtCompareTokens
> [NTOS:SE] Complete the SepCompareTokens implementation

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/CAutoComplete.h
Implement `IAutoComplete` to realize input auto completion.
JIRA issue: [CORE-9281](https://jira.reactos.org/browse/CORE-9281), [CORE-1419](https://jira.reactos.org/browse/CORE-1419)
- The main features of this PR are Auto-Suggest and Auto-Append.
- Auto-Suggest shows a list near the textbox (an EDIT control) when the user has typed partial pathname into the textbox.
- Auto-Append appends complement text into the textbox to complete the pathname with selected status.
- The list of AutoSuggest is a top-level window whose window class is `"Auto-Suggest Dropdown"`. We call it "the drop-down window".
- The drop-down window contains three controls: a listview, a scrollbar and a sizebox.
- If the list is short, then the scrollbar might be invisible.
- The drop-down window watches the input into …
> [BROWSEUI] Implement auto-completion

- dll/cpl/appwiz/createlink.c
> [APPWIZ] Enable auto-completion on 'Create Shortcut'

- dll/win32/shell32/dialogs/dialogs.cpp
> [SHELL32] Enable auto-completion on 'Folder Options' > 'Change Icon'

- base/applications/rapps/include/defines.h
- sdk/lib/atl/CMakeLists.txt
- sdk/lib/atl/atlcom.h
- sdk/lib/atl/statreg.h
Currently `ATLASSERT` macro won't work in some environments, due to lack of `_DEBUG` macro.
Microsoft-style debugging needs `_DEBUG` macro definition. Thanks to @zefklop.
JIRA issue: [CORE-17505](https://jira.reactos.org/browse/CORE-17505)
- `if(DBG) target_compile_definitions(atl_classes INTERFACE _DEBUG) endif(DBG)` in `sdk/lib/atl`.
- Fix `sdk/lib/atl/statreg.h` (misuse of `ATLASSERT`).
- Fix `sdk/lib/atl/atlcom.h` (non-NULL check for non-NULL).
- Fix `base/applications/rapps/include/defines.h` (redefinition of `_DEBUG`).
> [CMAKE] Define _DEBUG for better ATL debugging (Retry)

- base/applications/rapps/appview.cpp
- base/shell/explorer/syspager.cpp
- base/shell/explorer/taskswnd.cpp
- base/shell/explorer/traywnd.cpp
- dll/win32/shell32/shellmenu/CMenuToolbars.cpp
- sdk/lib/atl/CMakeLists.txt
We are not ready for enabling `ATLASSERT`. Enabling ATL assertions takes time to realize.
JIRA issue: [CORE-17505](https://jira.reactos.org/browse/CORE-17505)
- Disable `ATLASSERT` by undefining `_DEBUG`.
- Revert currently non-fixable codes.
> [ATL][SHELL32][EXPLORER] Disable ATLASSERT

- base/services/umpnpmgr/rpcserver.c
- base/setup/usetup/devinst.c
- ntoskrnl/include/internal/io.h
- ntoskrnl/io/pnpmgr/devaction.c
- ntoskrnl/io/pnpmgr/plugplay.c
- sdk/include/ndk/cmtypes.h
This adds another action for starting devices after usermode PnP service enables the driver for it.
`PlugPlayControlResetDevice` is wrong in this case, because it returns the device node back to `DeviceNodeUninitialized` state, which is an overkill here (initialization phase is completed successfully, no need to repeat it)
Should fix: [CORE-17490](https://jira.reactos.org/browse/CORE-17490), [CORE-17463](https://jira.reactos.org/browse/CORE-17463)
> [NTOS:PNP] Implement PlugPlayControlStartDevice control class and use it

- ntoskrnl/mm/ARM3/virtual.c
- sdk/lib/rtl/heap.c
- sdk/lib/rtl/heap.h
It's super annoying to work on memory-related stuff when any memory-intensive application takes hours to do its things when it should be minutes.
JIRA issue: [CORE-15793](https://jira.reactos.org/browse/CORE-15793)
AVOID BUSY LOOPS
- Add a "guard" heap entry at the end of each committed range in order to be able to quickly commit new range without having to scan the whole committed region to know what the previous entry is. 
- Turn the FreeLists array into a single list for free entries, and add a "hint" array + bitmap which will give instantly gives the caller a free entry which will be large enough to hold the required size.
The only loops left is when the required alloc size is bigger than the decommit threshold and there are free entries which are bigger that this threshold, and when …
> [RTL] Improve heap performance

- ntoskrnl/mm/ARM3/expool.c
- ntoskrnl/mm/ARM3/pool.c
- ntoskrnl/mm/ARM3/syspte.c
Instead of blindly asking for pages when allocating and happily crash, just fail the allocation and let the caller handle that.
> [NTOS:MM] Fail NP pool allocations when running out of pages

- sdk/include/ndk/umtypes.h
- sdk/include/xdk/ntbasedef.h
Because myLongLong < MINLONG is supposed to behave like you'd expect.
I accept donations for being such a talented developer.
> [NDK][XDK] Use decimal literals for MINxxxx defines

- dll/win32/browseui/CAutoComplete.cpp
Reduce failures against Delete key on auto-completion.
- On `VK_DELETE`, delete the check of `IsWindowVisible()`.
BEFORE:
```txt
autocomplete: 65 tests executed (0 marked as todo, 0 failures), 1 skipped.
autocomplete: 214 tests executed (0 marked as todo, 48 failures), 0 skipped.
ACListISF: 546 tests executed (0 marked as todo, 0 failures), 0 skipped.
IACLCustomMRU: 331 tests executed (0 marked as todo, 0 failures), 0 skipped.
IAutoComplete: 66275 tests executed (0 marked as todo, 56 failures), 0 skipped.
```
AFTER:
```txt
autocomplete: 65 tests executed (0 marked as todo, 0 failures), 1 skipped.
autocomplete: 214 tests executed (0 marked as todo, 48 failures), 0 skipped.
ACListISF: 546 tests executed (0 marked as todo, 0 …
```
> [BROWSEUI] Fix auto-completion on VK_DELETE

- dll/win32/browseui/CAutoComplete.cpp
Reduce failures on sanity check of auto-completion.
- Return `E_FAIL` rather than `E_INVALIDARG` in sanity check of `CAutoComplete::Init` (`IAutoComplete::Init`).
BEFORE:
```txt
autocomplete: 65 tests executed (0 marked as todo, 0 failures), 1 skipped.
autocomplete: 214 tests executed (0 marked as todo, 48 failures), 0 skipped.
ACListISF: 550 tests executed (0 marked as todo, 0 failures), 0 skipped.
IACLCustomMRU: 331 tests executed (0 marked as todo, 0 failures), 0 skipped.
IAutoComplete: 66275 tests executed (0 marked as todo, 43 failures), 0 skipped.
```
AFTER:
```txt
autocomplete: 65 tests executed (0 marked as todo, 0 failures), 1 skipped.
autocomplete: 214 tests executed (0 marked as todo, 46 failures), 0 skipped. …
```
> [BROWSEUI] Fix return value on sanity check of auto-completion

- base/shell/explorer/trayclock.cpp
- dll/cpl/timedate/clock.c
- dll/cpl/timedate/dateandtime.c
- dll/cpl/timedate/monthcal.c
- dll/win32/syssetup/wizard.c
And a few related improvements.
JIRA issue: [CORE-13121](https://jira.reactos.org/browse/CORE-13121)
> [SYSSETUP][TIMEDATE] Use exact setTimer() timeouts, to stay in sync

- sdk/tools/hhpcomp/chmc/chm.h
ARM32 seems to use the same type defines as i386 and friends.
Let's allow the thing to be compiled again!
Signed-off-by: Konrad Dybcio <konrad.dybcio@somainline.org>
One step closer to getting ARM back on the track
JIRA issue: [CORE-17517](https://jira.reactos.org/browse/CORE-17517) seems the closest
Add type definitions for ARM
> [HHPCOMP] Add ARM (32-bit) types

- dll/win32/syssetup/security.c
And
* Make 1 cast more explicit.
* Fix 1 'SamSetInformationUser' copypasta in DPRINT1() text.
* Optimize 1 '.MaximumLength' assignment.
> [SYSSETUP] security.c: Remove 3 useless casts

- dll/win32/browseui/CAutoComplete.cpp
Support Tab key on auto-completion.
The following screenshots are from CORE-9281 test.rar.
BEFORE:
Tab key wouldn't work correctly.
AFTER:
Tab key works.
> [BROWSEUI] Support ACO_USETAB and SHACF_USETAB on auto-completion

- ntoskrnl/include/internal/se.h
- ntoskrnl/se/acl.c
- ntoskrnl/se/sd.c
- ntoskrnl/se/semgr.c
- ntoskrnl/se/token.c
On Windows three kind of system tokens are being created -- 1) system process token (which we already do that in ReactOS, 2) anonymous logon token not including the "Everyone SID group" and 3) anonymous logon token that includes such SID group.
The latter two tokens are created during phase 0 of the initialisation process of the SRM kernel component and they're needed for eventual impersonation of such tokens and such. With that being said, this is a next step closer to the implementation of `NtImpersonateAnonymousToken`.
* Implement `SepCreateSystemAnonymousLogonToken` and `SepCreateSystemAnonymousLogonTokenNoEveryone` functions (they're equivalent to `SeMakeAnonymousLogonToken` and `SeMakeAnonymousLogonTokenNoEveryone` on Windows).
* Set up a security descriptor and an access control …
> [NTOS:SE] Create two system anonymous logon tokens on boot

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/CAutoComplete.h
Fix and improve Auto-Append of auto-completion.
- Implement `CAutoComplete::DoAutoAppend` method.
- Use `SetWindowSubclass` rather than `SubclassWindow`.
- Add `compare1` function to compare two items, and use it.
- Delete `CACEditCtrl` class and add `CAutoComplete::EditWndProc` method.
- Add `DropPrefix` function to handle the prefixes.
- Add `CAutoComplete::FilterPrefixes` method.
I used the test program of CORE-9281 `test.rar`.
Win2k3:
Correctly working.
BEFORE:
It is not working.
AFTER:
AutoAppend is working well.
> [BROWSEUI] Enable AutoAppend of auto-completion

- dll/win32/comdlg32/CMakeLists.txt
- dll/win32/comdlg32/autocomp.cpp
- dll/win32/comdlg32/filedlg.c
- dll/win32/comdlg32/filedlgbrowser.c
- dll/win32/comdlg32/filedlgbrowser.h
Auto-completion will be enabled when the user opens "Open" or "Save As" dialog of the common dialogs.
- Add `autocomp.cpp` to implement in C++.
- Use `CLSID_ACListISF` and `CLSID_AutoComplete` objects to realize auto-completion.
- Modify `FileOpenDlgInfos` structure.
- Modify `FILEDLG95_InitControls` function and `COMDLG32_UpdateCurrentDir` function and `FileOpenDlgProc95` function.
It is working.
NOTE: The relative pathes, `"..\"` and `"\"` are not working. Those are bugs in `CLSID_ACListISF`.
> [COMDLG32] Enable auto-completion on comdlg32

- base/applications/clipbrd/clipbrd.c
- base/applications/mmc/console.c
- base/applications/mplay32/mplay32.c
- base/applications/mscutils/eventvwr/eventvwr.c
- base/applications/mscutils/servman/propsheet_recovery.c
- base/applications/mspaint/main.cpp
- base/applications/notepad/dialog.c
- base/applications/regedit/framewnd.c
- base/applications/winhlp32/winhelp.c
- base/applications/wordpad/print.c
- base/applications/wordpad/wordpad.c
- base/shell/progman/dialog.c
- dll/shellext/shellbtrfs/recv.cpp
- dll/shellext/shellbtrfs/send.cpp
- dll/win32/cryptui/main.c
- dll/win32/setupapi/dialog.c
- dll/win32/shell32/COpenWithMenu.cpp
- dll/win32/shell32/dialogs/filetypes.cpp
- modules/rosapps/applications/devutils/vgafontedit/opensave.c
- modules/rosapps/applications/sysutils/utils/infinst/infinst.c
- modules/rosapps/lib/vfdlib/vfdguiopen.c
- modules/rosapps/lib/vfdlib/vfdguisave.c
Use new-style file open/save-as dialog. The new-style dialog has the place bar on left side, and the size-grip on lower right corner.
- Add `OFN_EXPLORER` flag to `OPENFILENAME` structure in `notepad`, `wordpad`, `mspaint`, `clipbrd`, `mmc`, `mplay32`, `mscutils`, `regedit`, `winhlp32`, `progman`, `shellbtrfs`, `cryptui`, `shell32`, `setupapi`, `vgafontedit`, `infinst`, and `vfdlib` modules.
.
NOTEPAD (BEFORE):
WORDPAD (BEFORE):
MSPAINT (BEFORE):
NOTEPAD (AFTER):
WORDPAD (AFTER):
MSPAINT (AFTER):
> [NOTEPAD][WORDPAD][MSPAINT]... Use newer file open dialog

- dll/win32/newdev/CMakeLists.txt
- dll/win32/newdev/wizard.c
Realize auto-completion on Hardware Wizard.
- Call `SHAutoComplete` function.
- Add `CoInitialize`/`CoUninitialize` function calls (for `SHAutoComplete`).
- Add links to `shlwapi` and `ole32`.
BEFORE:
Auto-completion won't work.
AFTER:
Auto-completion does work.
> [NEWDEV] Enable auto-completion on Hardware Wizard

- dll/win32/shell32/CShellLink.cpp
Enable auto-completion on "Properties for Shortcut files".
- Call `SHAutoComplete` against dialog controls `IDC_SHORTCUT_TARGET_TEXT` and `IDC_SHORTCUT_START_IN_EDIT`.
> [SHELL32] Auto-completion on Properties for Shortcut

- modules/rostests/apitests/browseui/ACListISF.cpp
Give power to `ACListISF` testcase to analyze `CLSID_ACListISF`'s behavior about relative paths.
- Add `skip` calls.
- Add more tests for the relative paths.
Win2k3:
Successful.
Win10:
Successful.
> [BROWSEUI_APITEST] Strengthen ACListISF testcase

- dll/win32/browseui/aclistisf.cpp
Fix the `CLSID_ACListISF` object about relative paths.
- If the given path is relative at `CACListISF::Expand`, then convert it to a full path.
BEFORE:
There was a hung up.
AFTER:
There is no failure.
> [BROWSEUI] Fix auto-completion on relative paths

- modules/rostests/apitests/fontext/CMakeLists.txt
- modules/rostests/apitests/fontext/GetDisplayNameOf.cpp
- modules/rostests/apitests/fontext/testlist.c
Add `GetDisplayNameOf` testcase.
> [FONTEXT_APITEST] Show that fontext returns absolute paths with SHGDN_FORPARSING

- dll/win32/browseui/aclistisf.cpp
- dll/win32/browseui/aclistisf.h
Reduce failures in `ACListISF` testcase. Skip left space in auto-completion. Accept the pair of drive letter and colon.
- Rename `m_szExpand` as `m_szRawPath`.
- Add `m_szExpanded` member.
- Skip left space in `Expand`.
- Convert `"C:"` to `"C:\\"`.
BEFORE:
AFTER:
> [BROWSEUI] auto-completion: Reduce failures in ACListISF

- ntoskrnl/include/internal/i386/ke.h
- ntoskrnl/ke/i386/trap.s
Instead of making assumptions about what the compiler does with forced-inline functions
GCC version doesn't properly clobber ecx, edx & eax.
MSVC version assumes that the compiler puts return value of forced-inline functions into eax.
CLANG just blows up.
See PR #3566
> [NTOS:KE] Rewrite KiSystemCallTrampoline in assembly

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/CAutoComplete.h
- Delete `OnEditUpdate` method.
- Improve the expand condition.
BEFORE:
AFTER:
> [BROWSEUI] Reduce IAutoComplete failures

- ntoskrnl/mm/ARM3/section.c
- ntoskrnl/se/audit.c
Mute debug prints of `MmDoesFileHaveUserWritableReferences` and `SeAuditingFileEventsWithContext` stubs.
These stubs are very noisy and create a lot of spam in the log when using Microsoft NTFS driver in ReactOS (with some other improvements applied).
Implementing those functions isn't badly required for the proper work of this driver, so better way for now is just mute these stubs a bit.
After my changes, they will be displayed only once, and the log will be more clear, so it will seem to be enough to understand that the driver calls these routines.
JIRA issue: [CORE-17409](https://jira.reactos.org/browse/CORE-17409)
> [NTOS:MM][NTOS:SE] Mute some noisy stubs CORE-17409

- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/CAutoComplete.h
Enable filtering on enumeration of large number of items to process the items correctly.
- Add `m_bPartialList` and `m_dwTick` members.
- Add `CAutoComplete::ScrapeOffList` and `CAutoComplete::DoesMatch` methods.
- If the items are too many, enable filtering in item enumeration.
- Add `strText` parameter to some methods.
- Make some methods `const`.
- Improve match condition.
BEFORE:
```txt
autocomplete: 65 tests executed (0 marked as todo, 0 failures), 1 skipped.
autocomplete: 215 tests executed (0 marked as todo, 36 failures), 0 skipped.
ACListISF: 563 tests executed (0 marked as todo, 0 failures), 0 skipped.
IACLCustomMRU: 331 tests executed (0 marked as todo, 0 failures), 0 skipped.
IAutoComplete: 66415 tests executed …
```
> [BROWSEUI] auto-completion: Support large number items

- base/applications/utilman/umandlg/umandlg.c
- base/shell/cmd/lang/de-DE.rc
- drivers/storage/ide/uniata/id_ata.cpp
Read the expected/actual keys, otherwise results are always nonexistent/false.
JIRA issue: [CORE-17524](https://jira.reactos.org/browse/CORE-17524)
While here, fix typo elsewhere too.
> [UNIATA] DriverEntry(): Fix 'Paramaters' typo, in reg key names

- drivers/storage/ide/uniata/uniata_reg.inf
commented out, for the time being.
JIRA issue: [CORE-17395](https://jira.reactos.org/browse/CORE-17395)
> [UNIATA] uniata_reg.inf: Add 'PnpInterface\5' key

- dll/win32/mshtml/CMakeLists.txt
MSVC amd64
'...\dll\win32\mshtml\nsio.c(3755): error C4028: formal parameter 3 different from declaration'
was fixed by 5ed1867.
> [MSHTML] MSVC: There is no 'error C4028' anymore

- modules/rostests/winetests/CMakeLists.txt
- modules/rostests/winetests/gdiplus/CMakeLists.txt
Is more explicit and re-enables the warning for all the other modules.
Addendum to 42d2d5e.
> [CMAKE] winetests/: Move '/wd4133' to gdiplus/ only

- sdk/include/crt/stddef.h
- sdk/include/psdk/commctrl.h
JIRA issue: [CORE-17547](https://jira.reactos.org/browse/CORE-17547)
Clang-CL (i386) was failing:
```txt
In file included from D:\a\reactos\reactos\src\dll\appcompat\apphelp\shimeng.c:16:
D:\a\reactos\reactos\src\dll\appcompat\apphelp/shimeng.h(40,1): error: function declaration cannot have variably modified type
C_ASSERT(offsetof(HOOKAPIEX, pShimInfo) == offsetof(HOOKAPI, Reserved));
^
sdk\include\psdk\winnt.h(807,38): note: expanded from macro 'C_ASSERT'
#define C_ASSERT(expr) extern char (*c_assert(void)) [(expr) ? 1 : -1]
```
- Fix `offsetof` macro of CRT `<stddef.h>` if `__clang__` is defined.
- Fix `CCSIZEOF_STRUCT` macro in `<commctrl.h>`, using `__builtin_offsetof` operator.
> [SDK][INCLUDE] Fix offsetof and CCSIZEOF_STRUCT for Clang-CL build

- sdk/tools/hhpcomp/chmc/chm.h
These were missing.. not anymore!
Tested on a PinePhone of all things..
Big hack that allows it to build (on Linux for Linux.. arm-windows-winpe in llvm when!?):
`
mkdir build
cd build
cmake .. -DARCH=arm -DWINARCH=arm -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_C_COMPILER_TARGET=aarch64-linux-eabi -DCMAKE_CXX_COMPILER_TARGET=aarch64-linux-eabi -DCMAKE_C_COMPILER_FORCED=TRUE -DCMAKE_CXX_COMPILER_FORCED=TRUE -DLD_EXECUTABLE=ld
make -j4 -k
`
The apps that managed to build do run on linux/arm64.
> [HHPCOMP] Add ARM64/AARCH64 types

- boot/bootdata/hivesys.inf
- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtImpersonateAnonymousToken.c
- modules/rostests/apitests/ntdll/testlist.c
- ntoskrnl/include/internal/se.h
- ntoskrnl/se/srm.c
- ntoskrnl/se/token.c
- sdk/include/ndk/sefuncs.h
This implements the `NtImpersonateAnonymousToken` system call function, so that we can finally impersonate the logon token whether by calling the system call or `ImpersonateAnonymousToken` user mode service from ADVAPI32 library.
* Add `EveryoneIncludesAnonymous` registry value to Lsa (Local Security Authority) registry key
* Add the prototype of `SepRegQueryHelper` to the internal kernel header, making it public for other kernel code to use, and also annotate its parameters and include a documentation header
* Implement `SepImpersonateAnonymousToken`
> [NTOS:SE] Implement anonymous logon token impersonation

- ntoskrnl/ps/query.c
Fix Clang-Cl
'...\ntoskrnl\ps\query.c(583,33): warning: variable 'Status' is uninitialized when used here [-Wuninitialized]'
Addendum to 1074a9a.
> [NTOS:PS] NtQueryInformationProcess(): Fix ProcessDeviceMap case

- sdk/include/psdk/winbase.h
Sync' with MS SDK.
NB:
Noticed while checking CORE-14306, which this PR does not fix.
Sync' with
https://source.winehq.org/git/wine.git/commit/a9e50da352e32d4c1bc8d0a686efa1e1bb7a84da
> [PSDK] UnlockResource(): Improve definition

- ntoskrnl/include/internal/se.h
- ntoskrnl/ps/security.c
- ntoskrnl/se/token.c
`PsImpersonateClient` blindly impersonates the requested client even though it doesn't know if the actual token given to the call can be impersonated for the thread of the client which we are going to begin impersonation. 
In the case where impersonation is not possible, make a copy of the given token and assign the newly one for impersonation instead.
**JIRA Issue:** [CORE-17539](https://jira.reactos.org/browse/CORE-17539)
> [NTOS:SE][NTOS:PS] Ensure that client impersonation is possible

- win32ss/gdi/gdi32/misc/gdientry.c
Place `pColorTable` after `pSurfaceLocal->hDDSurface`, instead of before it, since such ordering is used in the calling `NtGdiDdGetDC`. See https://docs.microsoft.com/en-us/windows/win32/devnotes/-dxgkernel-ntgdiddgetdc for the reference.
It allows to properly pass the DirectDraw surface handle (and palette entry pointer) from MS ddraw into win32k.
Otherwise, they are passing into the wrong parameters of actual `NtGdi`* function, and due to this, since they're detected as invalid, they become `NULL`, and that function does not work correctly.
Required by MS DirectDraw stack (ddraw.dll & dxg.sys). Although it does not completely fix the issue, but it at least improves the situation.
JIRA issue: [CORE-17561](https://jira.reactos.org/browse/CORE-17561)
> [GDI32] Fix wrong ordering of parameters in NtGdiDdGetDC call

- base/applications/cmdutils/fc/CMakeLists.txt
- base/applications/cmdutils/fc/fc.c
- base/applications/cmdutils/fc/fc.h
- base/applications/cmdutils/fc/text.h
- base/applications/cmdutils/fc/texta.c
- base/applications/cmdutils/fc/textw.c
Implement text file comparison by using file mappings (both Unicode and ANSI).
JIRA issue: [CORE-17500](https://jira.reactos.org/browse/CORE-17500)
- We split text into lines, and then compare lines.
- If two text file are identical, return `FCRET_IDENTICAL`.
- If different, show the difference and return `FCRET_DIFFERENT`.
- If any error occurred, then return `FCRET_INVALID`.
BEFORE:
61 failures.
AFTER:
7 failures.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fc
> [CMDUTILS][FC] Implement text file comparison

- CMakeLists.txt
On `build-msbuild-i386`:
`-- Build Type: `
is replaced by
`-- Configuration types: Debug;Release;MinSizeRel;RelWithDebInfo`
Follow-up to d10728a.
> [CMAKE] CMakeLists.txt: Print CMAKE_CONFIGURATION_TYPES

- sdk/include/reactos/wine/typeof.h
Fix msbuild amd64
'...\sdk\include\reactos\wine/typeof.h(50,64): error C2059: syntax error: '<parameter-list>' [D:\a\reactos\reactos\build\dll\win32\msxml3\msxml3.vcxproj]'
Addendum to 32072cf (r42469).
NB:
Line 50 duplicates line 45.
> [SDK] wine/typeof.h: Remove duplicate ImeGetRegisterWordStyle line

- base/applications/rapps/installed.cpp
- base/applications/rapps/loaddlg.cpp
Rapps used to have this, it got lost during refactoring.
Does it make sense to restore this?
Do we optionally want to increase verbosity? (e.g. log install success/failure, maybe download start/failure/stop?)
> [RAPPS] Restore event logging of install/uninstall actions

- drivers/bus/pcix/CMakeLists.txt
- drivers/storage/ide/pciide/CMakeLists.txt
- sdk/cmake/gcc.cmake
- sdk/tools/pefixup.c
- GCC: Make resource sections discardable for kernel-mode drivers and DLLs
- Fix pciide and pcix drivers
JIRA issue: [CORE-17401](https://jira.reactos.org/browse/CORE-17401)
> Fixup of resource sections in GCC builds

- modules/rostests/winetests/CMakeLists.txt
- modules/rostests/winetests/kernel32/CMakeLists.txt
Is more explicit and re-enables the warning for all the other modules.
Also add matching remove_target_compile_option().
Addendum to 42d2d5e.
NB:
Also, this avoids the related failure on #3645.
I guess the `if` related to this variable is optimized out, which triggers this error.
> [CMAKE] winetests/: Move '/wd4101' to kernel32/ only

- modules/rostests/winetests/CMakeLists.txt
- modules/rostests/winetests/comctl32/CMakeLists.txt
- modules/rostests/winetests/gdi32/CMakeLists.txt
- modules/rostests/winetests/ntdll/CMakeLists.txt
Is more explicit and re-enables the warning for all the other modules.
Addendum to 42d2d5e.
NB:
Also, this avoids the related failures on #3645.
> [CMAKE] winetests/: Move '/wd4334' to 3 sub-modules only

- ntoskrnl/se/token.c
The groups length is already returned by SeCaptureSidAndAttributesArray, it doesn't make sense to not use it.
> [NTOS:SE] Capture the groups length when creating a token

- ntoskrnl/po/power.c
- sdk/include/xdk/iotypes.h
The `CompletionFunction` parameter is really optional.
This fixes a bugcheck caused by shutdown with IDE driver stack.
JIRA issue: [CORE-17401](https://jira.reactos.org/browse/CORE-17401)
> [NTOS:PO] Check for optional parameter in the completion routine

- ntoskrnl/mm/ARM3/procsup.c
This is not needed anymore and causes havoc on amd64
Remove a hack which is not necessary anymore and only wastes System PTE space
> [NTOS:MM] Do not map Process Working Set List in kernel space

- CMakeLists.txt
- sdk/cmake/host-tools.cmake
Configure time environment variables are not stored / re-used by cmake,
and bison/flex need environment variables to function.
JIRA issue: [ROSBE-174](https://jira.reactos.org/browse/ROSBE-174)
> [CMAKE] Store and re-use M4 and BISON_PKGDATADIR env variables

- ntoskrnl/include/internal/amd64/mm.h
> [NTOS:MM] MiIsPdeForAddressValid is NOT an INIT function!

- base/applications/regedit/main.c
- Call `comctl32!InitCommonControlsEx` function rather than `comctl32!InitCommonControls` funciton.
No change.
> [REGEDIT] Use InitCommonControlsEx instead of InitCommonControls

- win32ss/gdi/dib/dib32bpp.c
Using in unsigned integer will cause the calculations to be unsigned, which on x64 leads to wrong results, when adding it to a pointer.
> [WIN32K] Fix wrong calculation in DIB_32BPP_BitBltSrcCopy

- drivers/usb/usbport/pnp.c
- drivers/usb/usbport/usbport.c
- drivers/usb/usbport/usbport.h
This PR makes the USBPORT driver unload, when it fails to load.
This is needed for x64, where USB doesn't work yet.
> [USBPORT] Make unload work

- win32ss/user/ntuser/winpos.c
Improve `HSHELL_WINDOWCREATED` shell hook.
JIRA issue: [CORE-15669](https://jira.reactos.org/browse/CORE-15669)
- Modify the condition of generating `HSHELL_WINDOWCREATED`, especially on `WS_CHILD` window style.
> [WIN32SS][NTUSER] Improve HSHELL_WINDOWCREATED condition

- .github/workflows/build.yml
- Restore actually requesting v12, not default
- Avoid gcc configure
```
CMake Warning:
Manually-specified variables were not used by the project:
CLANG_VERSION
```
Addendum to a66214c.
> [GITHUB] build.yml: Properly set and use LLVM_VERSION

- win32ss/user/ntuser/winpos.c
Improve compatibility of `user32!ShowWindow` function.
JIRA issue: [CORE-15669](https://jira.reactos.org/browse/CORE-15669)
- `user32!ShowWindow.SW_MINIMIZE` should show the window.
- Fix the return value of `ShowWindow` function on invalid parameter.
BEFORE:
AFTER:
Successful.
BEFORE:
The setup program of DVD Write Now won't show the taskbar pane.
AFTER:
The setup program of DVD Write Now shows the taskbar pane.
Win2k3:
> [WIN32SS][NTUSER] ShowWindow.SW_MINIMIZE should show window

- dll/cpl/appwiz/addons.c
JIRA issue: [CORE-17550](https://jira.reactos.org/browse/CORE-17550), [CORE-5737](https://jira.reactos.org/browse/CORE-5737)
- Move the focus by sending `WM_NEXTDLGCTL` before making the focus control disabled or hidden.
Start download of gecko by pressing `Enter` key...
And cancel by keyboard `Esc` key.
OK.
> [CPL][APPWIZ] Make gecko download cancellable by keyboard

- base/applications/rapps/available.cpp
- base/applications/rapps/include/misc.h
- base/applications/rapps/misc.cpp
This PR adds support for architecture specific section, e.g. [Section.amd64], [Section.0c0a.amd64])
See also https://github.com/reactos/rapps-db/pull/142
Example for a new entry:
```
[Section]
Name = 7-Zip
Version = 19.00
License = LGPL
Description = A file archiving utility with support for 7zip, zip, tar, rar and many other archive formats.
Size = 1.1 MiB
Category = 12
URLSite = https://www.7-zip.org/
URLDownload = https://www.7-zip.org/a/7z1900.exe
SHA1 = 2f23a6389470db5d0dd2095d64939657d8d3ea9d
CDPath = none
SizeBytes = 1185968
[Section.amd64]
URLSite = http://svn.reactos.org/
URLDownload = http://svn.reactos.org/packages/7z1900-x64.exe
SHA1 = 0138746b529d4d3a81302c2bc355a0b855a86d38
```
> [RAPPS] Implement support for architecture specific sections

- dll/win32/mpr/mpr.spec
All that we learned so far.
JIRA issue: [CORE-14376](https://jira.reactos.org/browse/CORE-14376)
--
NT4 Winfile, example debug log:
```
WARNING: calling stub WNetGetDirectoryTypeW('D:\',0x00D1FF3C,0x1)
WARNING: calling stub WNetGetDirectoryTypeW('D:\',0x0012D4E4,0x0)
WARNING: calling stub WNetGetDirectoryTypeW('D:\efi',0x0012D4E4,0x0)
WARNING: calling stub WNetGetDirectoryTypeW('D:\loader',0x0012D4E4,0x0)
WARNING: calling stub WNetGetDirectoryTypeW('D:\reactos',0x0012D4E4,0x0)
```
> [MPR] spec: Add stubs, document parameter types, stub-enable 2 functions

- base/shell/cmd/where.c
For the testbot
JIRA issue: [CORE-17351](https://jira.reactos.org/browse/CORE-17351), [CORE-16898](https://jira.reactos.org/browse/CORE-16898), [CORE-17612](https://jira.reactos.org/browse/CORE-17612)
> [CMD] Properly handle case when command is given with leading or trailing spaces

- base/applications/cmdutils/more/lang/bg-BG.rc
- base/applications/cmdutils/more/lang/ca-ES.rc
- base/applications/cmdutils/more/lang/cs-CZ.rc
- base/applications/cmdutils/more/lang/de-DE.rc
- base/applications/cmdutils/more/lang/el-GR.rc
- base/applications/cmdutils/more/lang/en-US.rc
- base/applications/cmdutils/more/lang/es-ES.rc
- base/applications/cmdutils/more/lang/et-EE.rc
- base/applications/cmdutils/more/lang/fr-FR.rc
- base/applications/cmdutils/more/lang/it-IT.rc
- base/applications/cmdutils/more/lang/lt-LT.rc
- base/applications/cmdutils/more/lang/no-NO.rc
- base/applications/cmdutils/more/lang/pl-PL.rc
- base/applications/cmdutils/more/lang/ro-RO.rc
- base/applications/cmdutils/more/lang/ru-RU.rc
- base/applications/cmdutils/more/lang/sk-SK.rc
- base/applications/cmdutils/more/lang/sq-AL.rc
- base/applications/cmdutils/more/lang/sv-SE.rc
- base/applications/cmdutils/more/lang/tr-TR.rc
- base/applications/cmdutils/more/lang/uk-UA.rc
- base/applications/cmdutils/more/lang/zh-CN.rc
- base/applications/cmdutils/more/lang/zh-TW.rc
- base/applications/cmdutils/more/more.c
- boot/bootdata/hivesft.inf
- sdk/lib/conutils/pager.c
- sdk/lib/conutils/pager.h
Implement missing features of the `MORE` command.
JIRA issue: [CORE-4019](https://jira.reactos.org/browse/CORE-4019)
- Extend `conutils` module.
- Implement all the subcommands of `MORE`.
- Handle long lines.
- Modify `IDS_USAGE` resource string.
- Add `IDS_BAD_FLAG`, `IDS_CONTINUE_OPTIONS`, `IDS_CONTINUE_LINES` and `IDS_CONTINUE_LINE_AT` resource strings.
- Handle command line options.
> [MORE][CONUTILS] Implement missing features of the MORE command.

- sdk/lib/drivers/hidparser/parser.h
NEVER DO THIS! It is guaranteed to be wrong. Instead always individually pack single structures that need packing.
This fixes USB mouse on 64 bit builds.
> [HIDPARSER] Don't include pshpack1.h before including other headers

- sdk/cmake/host-tools.cmake
Use same condition in the 2 files,
to avoid
```
CMake Warning:
Manually-specified variables were not used by the project:
ROS_SAVED_BISON_PKGDATADIR
ROS_SAVED_M4
```
on all the other builds.
Addendum to 18e95f5.
JIRA issue: [ROSBE-174](https://jira.reactos.org/browse/ROSBE-174)
> [CMAKE] host-tools: Define ROS_SAVED_* for MSVC_IDE only

- modules/rostests/apitests/shell32/ShellExecCmdLine.cpp
Make the testcase usable.
JIRA issue: [CORE-17351](https://jira.reactos.org/browse/CORE-17351), [CORE-16898](https://jira.reactos.org/browse/CORE-16898), [CORE-17612](https://jira.reactos.org/browse/CORE-17612)
- Simplify code.
- Loose the condition of success.
- Add some missing tests.
- Close newly opened windows gracefully.
Win10:
Successful.
The tests of WinXP and Win2k3 are skipped.
> [SHELL32_APITEST] Improve ShellExecCmdLine testcase more

- ntoskrnl/mm/ARM3/pool.c
When freeing pages, free page entries with pages num == 3 were incorrectly treated as entries with pages num >= 4 and thus their re-insertion was not triggered. That lead to non paged pool fragmentation (can be triggered by kmtest:ExPools, for example)
Also, altered the index acquisition code for MmNonPagedPoolFreeList entries so it looks more clear
Kudos go to @ThFabba for finding this bug :tada:
> [NTOS:MM] Fix placing entries into MmNonPagedPoolFreeListHead

- win32ss/gdi/ntgdi/palette.c
_Revert part of R50928 that causes Durak card suites to have wrong colors._
JIRA issue: [CORE-13748](https://jira.reactos.org/browse/CORE-13748) <= Durak Example
JIRA issue: [CORE-16510](https://jira.reactos.org/browse/CORE-16510) <= GDIProg Example
Durak in R50927
Durak in R50928
Correct GDIProg from CORE-17164
GDIProg Menu Before:
GDIProg Menu After:
GDIProg Palette Before:
GDIProg Palette After:
> [WIN32K] Revert incorrect part of R50928 for RealizePalette.

- drivers/bus/pci/fdo.c
This is how Windows pci.sys works. Fixes [CORE-17636](https://jira.reactos.org/browse/CORE-17636)
> [PCI] Filter out devices with null vendor and device ID

- drivers/storage/ide/uniata/CMakeLists.txt
- drivers/storage/ide/uniata/bm_devs.h
- drivers/storage/ide/uniata/id_queue.cpp
Fix random crashes on Virtual PC (2004, at least).
- Workaround regressions.
JIRA issue: [CORE-17371](https://jira.reactos.org/browse/CORE-17371)
> [UNIATA] Workaround a regression

- base/shell/cmd/CMakeLists.txt
- base/shell/cmd/batch.c
- base/shell/cmd/cmd.c
Sledgehammer deletion of weird outdated debug stuff, because I am tired of seeing cmd:batch taking way too much time when I run the test suite.
Do not use custom alloc/free functions. If you need this, use DPH.
Do not free resources at process exit.
- You're doing it brick by brick while the OS does that with a bulldozer better than you do.
> [CMD] Improve performance

- sdk/lib/atl/atlbase.h
As is described in MSDN [here](https://docs.microsoft.com/en-us/cpp/atl/reference/cregkey-class?view=msvc-160#dtor), `~CRegKey` should release `m_hKey` 
but the code in ReactOS's ATL seems to do nothing at all
- make up the missing cleanup code in  `~CRegKey`
> [ATL] Close m_hKey in CRegKey destructor

- ntoskrnl/cache/section/sptab.c
- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/ARM3/miarm.h
- ntoskrnl/mm/rmap.c
- ntoskrnl/mm/section.c
Fix case when you can't delete an executable file after having executed it.
JIRA issue: [CORE-17544](https://jira.reactos.org/browse/CORE-17544)
Actually free the pages lying around when all image sections are deleted and MmFlushImageSection(MmFlushForDelete) is called. This makes the image section drops all its refcount and finally be deleted.
> Implement MmFlushImageSection(MmFlushForDelete)

- ntoskrnl/include/internal/icif.h
- ntoskrnl/include/internal/ps_i.h
- ntoskrnl/ps/query.c
- subsystems/win32/csrss/csrss.c
This fixes several issues regarding process/thread information classes where they fail with a size mismatch status error in AMD64 build.
> [NTOS:PS] Fix several issues within info classes in AMD64 build

- dll/win32/shell32/CMakeLists.txt
- dll/win32/shell32/CShellLink.cpp
- dll/win32/shell32/wine/shellpath.c
- sdk/include/reactos/shlwapi_undoc.h
- sdk/include/reactos/undocshell.h
Our shell needs `shell32!PathResolve` function to go deep.
JIRA issue: [CORE-12665](https://jira.reactos.org/browse/CORE-12665)
- Implement `PathResolveW` function.
- Implement `PathQualifyA/W` functions using newly-defined `PathQualifyExW` function.
BEFORE:
Too many failures (2976).
AFTER:
Failures are reduced a lot (down to 324).
> [SHELL32] Implement PathResolveW function

- boot/freeldr/freeldr/CMakeLists.txt
- boot/freeldr/freeldr/arch/i386/ntoskrnl.c
- hal/halx86/generic/spinlock.c
- modules/rostests/kmtests/ntos_ke/KeSpinLock.c
- ntoskrnl/cache/newcc.h
- ntoskrnl/cache/section/data.c
- ntoskrnl/cache/section/swapout.c
- ntoskrnl/include/internal/kd64.h
- ntoskrnl/include/internal/ke.h
- ntoskrnl/include/internal/spinlock.h
- ntoskrnl/kd/kdio.c
- ntoskrnl/kd64/kdlock.c
- ntoskrnl/kd64/kdprint.c
- ntoskrnl/kd64/kdtrap.c
- ntoskrnl/kdbg/i386/i386-dis.c
- ntoskrnl/kdbg/kdb.c
- ntoskrnl/kdbg/kdb.h
- ntoskrnl/kdbg/kdb_cli.c
- ntoskrnl/kdbg/kdb_expr.c
- ntoskrnl/kdbg/kdb_symbols.c
- ntoskrnl/ke/spinlock.c
- ntoskrnl/mm/freelist.c
- sdk/cmake/gcc.cmake
- sdk/include/reactos/rossym.h
- sdk/lib/crt/crt.cmake
- sdk/lib/crt/libcntpr.cmake
- sdk/lib/rossym/rossympriv.h
- win32ss/user/ntuser/keyboard.c
Partly based on @ThFabba proposal
374fef2d59f39b714ff3152f1590f6af843c8bf5 is so embarrassing that I can't just sit there and do nothing. Let's make that not happen again.
Check that we don't own spin locks before acquiring them.
> [NTOS:KE] Test spinlock ownership on both UP & MP build

- dll/win32/shell32/wine/shellpath.c
Follow-up of #3762.
JIRA issue: [CORE-12665](https://jira.reactos.org/browse/CORE-12665)
- Add `PathResolveA` implementation by ANSI/Unicode conversion.
> [SHELL32] Implement PathResolveA function

- dll/win32/imm32/imm.c
I have started development of imm32-related stuffs.
- Just call `NtUserDisableThreadIme` in `ImmDisableIME` directly.
> [IMM32] ImmDisableIME calls NtUserDisableThreadIme

- win32ss/gdi/ntgdi/dibobj.c
_Reviewed full history of changes to this function and merged significant changes into reverted logic._
JIRA issue: [CORE-16236](https://jira.reactos.org/browse/CORE-16236)
Updated and Commit Cleaned Replacement for PR #3757.
First testing results:
CORE-16236 JID59763 NtGdiStretchDIBitsInternal_14.patch on top of 835c302
KVM: https://reactos.org/testman/compare.php?ids=78051,78058
VBOX: https://reactos.org/testman/compare.php?ids=78053,78059
Over 100 fewer failures in gdi32:dib
Four (4) fewer failures in gdi32:bitmap
No difference in gdiplus:graphics.
Next Test Results:
CORE-16236 JID59765 NtGdiStretchDIBitsInternal_15.patch on top of 0ffbbab
KVM:  https://reactos.org/testman/compare.php?ids=78054,78060
VBox: https://reactos.org/testman/compare.php?ids=78057,78061
Over 100 fewer failures …
> [WIN32K] Revert NtGdiStretchDIBitsInternal to Previous Logic

- modules/rostests/rosautotest/CWineTest.cpp
This fixes a number of tests on Test WHS.
- advapi32:RtlEncryptMemory: 2 failures -> 0 failures
- browseui:ACListISF: CRASH -> 0 failures
- gdi32:AddFontResource: 8 failures -> 0 failures
- kernel32:path: 1 failure -> 0 failures
- kernel32:process: 27 failures -> 13 failures
- usp10:usp10: 24 tests more executed (+ 3 failures)
Regression:
- ntdll:file: 0 failures -> 1 failure
Comparison: https://reactos.org/testman/compare.php?ids=77657,77910,77911,77915,78025 (this PR on the right)
> [ROSAUTOTEST] Run tests with current dir set to the test dir

- ntoskrnl/io/iomgr/deviface.c
Use `REG_OPTION_NON_VOLATILE` instead of `REG_OPTION_VOLATILE` in all `ZwCreateKey` calls of `OpenRegistryHandlesFromSymbolicLink`, since the keys created/opened by this function, should be non-volatile (in other words, saved after reboot).
Also `Device Parameters` subkey that is created in `IoOpenDeviceInterfaceRegistryKey` (which uses that routine as well), is non-volatile too, so the parent keys whose contain it, cannot be volatile.
It will fix an error with status `0xc0000181` (`STATUS_CHILD_MUST_BE_VOLATILE`) occuring during loading kernel mode audio drivers from Windows XP/2003, especially checked (debug) versions, with my `IoGetDeviceInterfaceAlias` implementation from previous PR #3510. Also it may fix other error cases.
JIRA issue: …
> [NTOS:IO] OpenRegistryHandlesFromSymbolicLink: Use REG_OPTION_NON_VOLATILE CORE-17361

- dll/win32/shell32/dialogs/dialogs.cpp
_Change code in dialogs.cpp to try two different methods for ShellExec._
JIRA issue: [CORE-16898](https://jira.reactos.org/browse/CORE-16898)
_Fixes "iexplore" and "www.Web-Site-Here.xxx"._
KVM: https://reactos.org/testman/compare.php?ids=78129,78134, LGTM
VBox: https://reactos.org/testman/compare.php?ids=78131,78135, LGTM
> [SHELL32] Improve Start-Run Dialog Box Features

- sdk/include/reactos/wine/ddk/imm.h
Add offset and size information to `INPUTCONTEXT` structure for information help.
- Use `C_ASSERT` and `offsetof` macros against `INPUTCONTEXT` structure.
> [SDK][INCLUDE] Add offset info to INPUTCONTEXT

- ntoskrnl/mm/ARM3/sysldr.c
CORE-16387 CORE-17638
Windows only makes the header RO for session space mapped drivers (win32k, dx and display drivers)
> [NTOS:MM] Fix MiSetSystemCodeProtection

- dll/win32/imm32/imm.c
- sdk/include/reactos/wine/ddk/imm.h
- Rewrite `ImmGetCompositionFontA` and `ImmGetCompositionFontW` functions.
- Add `INIT_*` macro definitions in `<ddk/imm.h>`.
> [IMM32] Rewrite ImmGetCompositionFontA/W

- modules/rostests/apitests/imm32/CMakeLists.txt
- modules/rostests/apitests/imm32/clientimc.c
- modules/rostests/apitests/imm32/imcc.c
- modules/rostests/apitests/imm32/precomp.h
- modules/rostests/apitests/imm32/testlist.c
- sdk/include/reactos/imm32_undoc.h
Add more testcase for proof.
- Add `clientimc` testcase to `imm32_apitest`.
- Add `"precomp.h"`.
WinXP (Japanese):
Successful.
Win2k3 (English):
Successful.
Win10 x64 (Japanese):
Successful.
> [IMM32_APITEST] Add clientimc testcase

- dll/directx/wine/ddraw/ddraw.c
_Replace defective code in Wine's DirectDraw with updated code._
JIRA issue: [CORE-15128](https://jira.reactos.org/browse/CORE-15128)
_This fixes the black boxes on the desktop when Fall 0.1.3 is exited._
> [DDRAW] Patch ddraw.c function ddraw7_FlipToGDISurface to match Wine-6.8

- sdk/lib/cpprt/arm/cpprt.s
Sync' arm with i386/amd64.
JIRA issue: [CORE-17606](https://jira.reactos.org/browse/CORE-17606)
> [CPPRT] arm: Add 2 'MSVCRTEX_eh_vector_*structor_iterator' aliases

- win32ss/drivers/videoprt/registry.c
- win32ss/user/ntuser/keyboard.c
JIRA issue: [CORE-17688](https://jira.reactos.org/browse/CORE-17688)
When a new driver is installed for the same device (like VBoxVideo), it uses the same hardware enum registry key and thus reuses the same DisplayId and the same display registry key. Therefore we need to update the setting in that key, even when the key already exists.
This seems to work good and not cause any issues, but testing indicated that on Windows some values are only updated, when the driver has changed. If neccessary, this can be achieved by updating and querying the ActiveService value in the device enum key (e.g. HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\PCI\VEN_80EE&DEV_BEEF&SUSYS_00000000&REV_00\3&267a616a&0&10\Control: ActiveService). If that doesn't match the current device name (from …
> [VIDEOPRT] Fix updating of new registry path values

- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/section.c
Do not hold PFN lock when freeing section data.
JIRA issue: [CORE-17690](https://jira.reactos.org/browse/CORE-17690) [CORE-17698](https://jira.reactos.org/browse/CORE-17698) 
Always release the PFN lock in MmDereferenceSegmentWithLock
Add relevant annotations for this function & MiAcquirePfnLock & friends
Split from #3798
> Pfn lock fix

- dll/win32/imm32/imm.c
- win32ss/include/ntuser.h
- Add `Imm32ProcessHotKey` and some helper functions to implement `ImmSimulateHotKey` function.
- Improve `ImmSimulateHotKey` function.
- Modify `IMEDPI` structure.
> [IMM32] Improve ImmSimulateHotKey

- ntoskrnl/include/internal/se.h
- ntoskrnl/include/internal/tag.h
- ntoskrnl/se/sid.c
- ntoskrnl/se/srm.c
- ntoskrnl/se/token.c
With the introduction of a missing member of the TOKEN data structure in [`f5dc1c7`](https://github.com/reactos/reactos/commit/f5dc1c77b5803c35f7cc60ea53806d74d29ec3a7#diff-12dc4fd6f09d553b9b2dd23d1fb4a7462b79cee172b777ced18077cf75c24ea8) (why was this important member missing but whatever), we gotta have to implement session reference tracking of logons on tokens. 
The next step is to implement session referencing handling on LSASRV side by setting token information with `TokenSessionReference` for proper session referencing in tokens.
[CORE-17700](https://jira.reactos.org/browse/CORE-17700)
> [NTOS:SE] Add/remove referenced logon sessions of tokens

- win32ss/user/ntuser/desktop.c
- win32ss/user/ntuser/desktop.h
- win32ss/user/ntuser/main.c
- win32ss/user/ntuser/ntuser.c
- win32ss/user/ntuser/painting.c
- win32ss/user/ntuser/simplecall.c
- win32ss/user/ntuser/timer.c
- win32ss/user/ntuser/usrheap.c
- win32ss/user/ntuser/usrheap.h
- win32ss/win32kp.h
Fix some win32k potential heap corruptions.
Enable Heap use-after-free & overflow helpers in debug build for win32k
ASSERT that we hold the user global lock when using win32k heaps
Fix bugs uncovered by the previous two.
> Win32k heap checks

- drivers/filesystems/ntfs/fcb.c
- drivers/filesystems/ntfs/ntfs.h
- drivers/filesystems/ntfs/rw.c
We shoudn't read file if it's encrypted.
Also I added several new defines for future contributions.
- Add new defines for NTFS's file attributes
- Don't read file if it's encrypted
> [NTFS] New defines & stub for reading encrypted files

- ntoskrnl/ke/amd64/stubs.c
- ntoskrnl/ke/amd64/zeropage.S
- ntoskrnl/ke/i386/cpu.c
- ntoskrnl/ke/i386/zeropage.S
- ntoskrnl/mm/ARM3/hypermap.c
- ntoskrnl/mm/ARM3/pagfault.c
- ntoskrnl/mm/ARM3/zeropage.c
- ntoskrnl/ntos.cmake
We spend a lot of time in this function, let's optimize it.
Noticed while running heavy memory tests like mshtml_winetest
> [NTOS:KE] Rewrite KeZeroPages in assembly & add SSE version

- dll/win32/imm32/imm.c
- sdk/include/reactos/wine/ddk/imm.h
- Add `WideToAnsiLogFont` and `AnsiToWideLogFont` helper functions.
- Rewrite `ImmSetCompositionFontA` and `ImmSetCompositionFontW` functions.
- Add `INPUTCONTEXTDX` structure as an extension of `INPUTCONTEXT`.
> [IMM32] Rewrite ImmSetCompositionFontA/W

- win32ss/gdi/ntgdi/text.c
_This list had fonts listed that ReactOS does not support and was missing fonts._
JIRA issues: [CORE-17662](https://jira.reactos.org/browse/CORE-17662) and [CORE-17723](https://jira.reactos.org/browse/CORE-17723)
_This fixes the text shown in the toolbar for Pidgin and Geany when using the Lunar theme ._
While we are editing this file, we will alphabetize the font names as well.
Here is my test program for proving that CORE-1091 is still fixed:
Before first patch:
After 1st patch and current:
> [GDI32] Revise IntTMWFixUp Raster Font List

- dll/win32/imm32/imm.c
- Add `Imm32WideFromAnsi`, `Imm32AnsiFromWide` and `Imm32IsCrossThreadAccess` helper functions.
- Simplify the `IMM32` code by using the helper functions.
> [IMM32] Refactor and simplify code

- dll/win32/imm32/imm.c
- win32ss/include/imetable.h
- Rewrite `ImmGetRegisterWordStyleA` and `ImmGetRegisterWordStyleW` functions.
- Modify `win32ss/include/imetable.h` table.
> [IMM32] Rewrite ImmGetRegisterWordStyleA/W

- dll/win32/imm32/imm.c
- dll/win32/imm32/imm32.spec
We don't need Wine-specific functions for Japanese input.
- Delete `__wine_get_ui_window`, `__wine_register_window` and `__wine_unregister_window` functions.
> [IMM32] Delete Wine-specific functions

- sdk/lib/rtl/amd64/except.c
- sdk/lib/rtl/amd64/unwind.c
I think `RtplUnwindInternal` implemented at #3708 is a typo.
`Rtlp` means **R**un**T**ime **L**ibrary **P**rivate.
Is it intentional use? Correct me if I am wrong. :)
> [RTL/x64] Fix a typo RtplUnwindInternal -> RtlpUnwindInternal

- dll/win32/imm32/imm.c
- sdk/include/reactos/undocuser.h
- win32ss/include/ntuser.h
Make code clean and clear.
- Move `WM_IME_SYSTEM` macro from `ntuser.h` into `undocuser.h`.
- Add `#include <undocuser.h>` in `IMM32`.
> [INCLUDE] Move WM_IME_SYSTEM from ntuser.h to undocuser.h

- base/shell/explorer/startup.cpp
Handle RunOnceEx by invoking RunOnceEx in iernonce.dll
// I've already checked, RunOnceEx is not handled under Safe Mode
Looks like Windows **ONLY** checks if HKLM one exists and invokes RunOnceEx in iernonce.dll
but `iernonce` will handle both HKLM and HKCU.
currently the code imitate what Windows do
But I wonder if this is intended...
> [EXPLORER] [RUNONCEEX] Handle RunOnceEx by invoking RunOnceEx in iernonce.dll

- modules/rostests/apitests/win32nt/CMakeLists.txt
- modules/rostests/apitests/win32nt/ntuser/NtUserGetThreadState.c
- modules/rostests/apitests/win32nt/testlist.c
I want to fix `NtUserGetThreadState` function and `enum ThreadStateRoutines`.
JIRA issue: [CORE-17732](https://jira.reactos.org/browse/CORE-17732), [CORE-11700](https://jira.reactos.org/browse/CORE-11700)
- Add `NtUserGetThreadState` testcase.
WinXP:
Successful.
Win2k3:
Successful.
> [WIN32KNT_APITEST] Add NtUserGetThreadState testcase

- ntoskrnl/include/internal/se.h
- ntoskrnl/se/access.c
- ntoskrnl/se/accesschk.c
- ntoskrnl/se/acl.c
- ntoskrnl/se/audit.c
- ntoskrnl/se/priv.c
- ntoskrnl/se/sd.c
- ntoskrnl/se/semgr.c
- ntoskrnl/se/sid.c
- ntoskrnl/se/srm.c
- ntoskrnl/se/token.c
- sdk/include/ndk/sefuncs.h
As the title says, write document comment headers in Doxygen format for all the functions in SRM for once and for all. The documentation headers will be updated regularly when time calls for it. In addition of documenting the subsystem module, update the file headers and annotate the remaining functions with SAL. ~~Currently WIP.~~
> [NTOS:SE] Document the whole subsystem in Doxygen format

- boot/bootdata/CMakeLists.txt
- sdk/cmake/CMakeMacros.cmake
Starting with commit 6158207c318bccaf1767d1a5c1545de45beb113d, caroots.inf is no longer added to LiveCD image builds, this turns into a trouble when a LiveCD user tries to load TLS/SSL sites using our built-in secure channel, and what they find is that the CA chains cannot be generated and thus failing.
JIRA issue: [CORE-17739](https://jira.reactos.org/browse/CORE-17739)
1) Add caroots.inf contents directly to the registry hives when building the LiveCD ISO.
2) Do not include the file caroots.inf in the LiveCD ISO, because it is added directly into the registry.
> [CMAKE][BOOTDATA]  Fix root CA certificates for Live CD

- dll/win32/uxtheme/themehooks.c
- sdk/include/psdk/winuser.h
- win32ss/user/ntuser/scrollbar.c
_Add themehook.c code to implement ThemeSetScrollInfo and use this to send Themed or not info to scrollbar.c._
JIRA issue: [CORE-16735](https://jira.reactos.org/browse/CORE-16735)
_This fixes scrollbar arrows and interior flashing both when themed and not themed._
> [UXTHEME][NTUSER] Fix flashing of scrollbar when scrolling

- dll/win32/msi/dialog.c
_Only show the main dialog pane in the taskbar when executing a Cancel dialog._
JIRA issue: [CORE-17702](https://jira.reactos.org/browse/CORE-17702)
> [MSI] Fix dialog.c showing two taskbar panes on Cancel

- sdk/lib/cmlib/cmlib.h
MSVC arm64:
'...\cmlib.h(200): fatal error C1189: #error:  Local PAGE_SIZE definition required when built as host'
JIRA issue: [CORE-17518](https://jira.reactos.org/browse/CORE-17518)
> [CMLIB] arm64: Define PAGE_SIZE

- dll/directx/wine/dsound/dsound_main.c
- media/doc/WINESYNC.txt
Fix and improve `DirectSoundEnumerateW` and `DirectSoundCaptureEnumerateW` implementations in our dsound.
Use the Windows-compatible way to get the device name and pass it to a callback.
This fixes incorrect detection of DirectSound audio input and output devices, so now a lot of apps are able to detect it correctly, and can play the sound properly (e. g., AIMP 2.61 and IcyTower from Rapps). :smiley: 
JIRA issue: [CORE-7535](https://jira.reactos.org/browse/CORE-7535), [CORE-10907](https://jira.reactos.org/browse/CORE-10907), [CORE-15324](https://jira.reactos.org/browse/CORE-15324), [CORE-15533](https://jira.reactos.org/browse/CORE-15533), [CORE-16340](https://jira.reactos.org/browse/CORE-16340) (Pocket Tanks 1.6, Stamina, Dave Gnukem all do improve)
- Don't use Wine-specific …
> [DSOUND] Improvements to DirectSound(Capture)EnumerateW

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtAdjustPrivilegesToken.c
- modules/rostests/apitests/ntdll/precomp.h
- modules/rostests/apitests/ntdll/testlist.c
~~This is a patch that fixes a symptom that's been unveiled with #3938, where a caller can definitely disable a privilege that's been enabled by default whereas we only disable privileges that have been enabled manually with functions like `NtAdjustPrivilegesToken` and friends.~~
Implement `NtAdjustPrivilegesToken` API testcase that exercises the behavior of disabling an enabled by default privilege.
> [NTDLL_APITEST] Implement NtAdjustPrivilegesToken testcase

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtDuplicateToken.c
- modules/rostests/apitests/ntdll/testlist.c
- ntoskrnl/se/token.c
This implements the effective only option where the caller may want to duplicate an access token but only with enabled parts of it, the privileges and groups respectively. Also write tests that exercise the behavior of making the token as effective only.
> [NTOS:SE] Implement token effective option upon duplication

- ntoskrnl/io/iomgr/driver.c
Implement the TODO in `IopInitializeDriverModule()`:
Set the DRVO_LEGACY_DRIVER flag if the driver is not WDM.
See commit.
> [NTOS:IO] IopInitializeDriverModule(): Set the DRVO_LEGACY_DRIVER flag if the driver is not WDM.

- dll/win32/imm32/imm.c
- modules/rostests/apitests/win32nt/ntuser/NtUserProcessConnect.c
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ntstubs.c
- win32ss/user/user32/include/user32p.h
- win32ss/user/user32/include/user_x.h
- win32ss/user/user32/misc/dllmain.c
Do the server/client-space pointers conversion in `NtUserProcessConnect()`, instead of having the client (who calls this function) to do the job. Should make the behaviour Windows-compatible, and remove some of the hackfixes in e.g. PR #3935.
Fixes also the IMM32-induced crash reported in [CORE-17741](https://jira.reactos.org/browse/CORE-17741)
> [WIN32SS:NTUSER:USER32][IMM] Fix NtUserProcessConnect() returned pointers.

- dll/win32/syssetup/lang/bg-BG.rc
- dll/win32/syssetup/lang/cs-CZ.rc
- dll/win32/syssetup/lang/da-DK.rc
- dll/win32/syssetup/lang/el-GR.rc
- dll/win32/syssetup/lang/en-GB.rc
- dll/win32/syssetup/lang/en-US.rc
- dll/win32/syssetup/lang/et-EE.rc
- dll/win32/syssetup/lang/fi-FI.rc
- dll/win32/syssetup/lang/he-IL.rc
- dll/win32/syssetup/lang/hi-IN.rc
- dll/win32/syssetup/lang/it-IT.rc
- dll/win32/syssetup/lang/lt-LT.rc
- dll/win32/syssetup/lang/nl-NL.rc
- dll/win32/syssetup/lang/no-NO.rc
- dll/win32/syssetup/lang/pt-BR.rc
- dll/win32/syssetup/lang/ro-RO.rc
- dll/win32/syssetup/lang/sk-SK.rc
- dll/win32/syssetup/lang/sq-AL.rc
- dll/win32/syssetup/lang/sv-SE.rc
- dll/win32/syssetup/lang/th-TH.rc
- dll/win32/syssetup/lang/zh-CN.rc
- dll/win32/syssetup/lang/zh-TW.rc
- dll/win32/syssetup/syssetup.rc
The British Language wasn't included here. However, i have corrected some texts that are still American English.
The British English resource wasn't exist while during Setup. however, There might include various American English text including the word "Customize", So i have decided add these on it.
- The file en-GB.rc isn't exist on SYSSETUP Language Resource folder.
> [SYSSETUP] Add en-GB.rc

- dll/directx/wine/dsound/primary.c
Don't force `HRESULT` status to `DSERR_BUFFERLOST` by default in `primarybuffer_SetFormat` function. Assign to it `S_OK` instead, as done in current Wine: https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/dsound/primary.c#l440.
That variable is already set to failure in other appropriate place, when this is indeed needed: https://git.reactos.org/?p=reactos.git;a=blob;f=dll/directx/wine/dsound/primary.c;h=b04a526929e4e817ff63aa652530e5901a3253a6;hb=HEAD#l511.
The assigned failure status caused executing failure handling code even when the fail actually didn't happen. In particular, `DSOUND_ReopenDevice` failed on `waveOutOpen` call when calling this was not needed.
After my changes, it's called only when needed, i. e., only when the actual failure happens. Otherwise, if all goes good, …
> [DSOUND] Don't force status to failure by default in primarybuffer_SetFormat

- drivers/filesystems/fastfat_new/fatstruc.h
Since VS 16.11 the compiler sometimes emits calls to _RTC_UninitUse, when parts of a bitfield are initialized (See https://developercommunity.visualstudio.com/t/Broken-runtime-checks-with-CL-19293013/1503629). Fix this by using an ULONG instead of a bitfield.
Note: The structure uses a 24 bit bitfield plus an UCHAR, which is supposed to form a 32 bit field, but that doesn't work anyway.
> [FASTFAT_NEW] "Fix" Flags bitfield to avoid RTC error

- ntoskrnl/kd64/kdapi.c
- ntoskrnl/kd64/kdlock.c
- ntoskrnl/kd64/kdtrap.c
- ntoskrnl/ke/freeze.c
Commits 608032bd and 835c3023 improved the usage of IRQL in diverse parts of the KD; however one aspect was overlooked: the IRQL is raised/lowered respectively by `KeFreezeExecution()` and `KeThawExecution()` (that are called respectively by `KdEnterDebugger()` and `KdExitDebugger()`).
This allows removing the `KeRaiseIrqlToDpcLevel()` call that was added in `KdpTrap()`, but should be absent (and is, on Windows), since the IRQL will be adjusted when actually entering/leaving the debugger.
Without this, one would encounter an `IRQL_NOT_GREATER_OR_EQUAL` BSOD in the following case:
1. manually break into kd in order to add a breakpoint into some kernel-mode code (for example, `win32k!NtUserProcessConnect`)
2. start some win32 app.
3. When the function is hit (and kd breaks), I refresh the …
> [NTOS:KD64] Diverse IRQL usage fixes.

- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/nt3.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/regword.c
- dll/win32/imm32/utils.c
Simplify `IMM32` code to improve readability.
- Define `Imm32HeapFree` macro in `precomp.h`.
- Use it.
- Omit some NULL checks (thanks to `HeapFree`).
> [IMM32] Define Imm32HeapFree macro and use it

- dll/win32/imm32/ime.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/regword.c
Simplify `IMM32` code to improve readability.
- Define `ImeDpi_IsUnicode` macro in `precomp.h`.
- Use it.
> [IMM32] Define ImeDpi_IsUnicode macro and use it

- modules/rostests/apitests/imm32/CMakeLists.txt
- modules/rostests/apitests/imm32/himc.c
- modules/rostests/apitests/imm32/testlist.c
Provide the way to confirm the IMM32 implementation.
- Add `himc` testcase.
WinXP (Japanese):
Win2k3 (English):
Win10 (Japanese):
> [IMM32_APITEST] Add himc testcase

- dll/shellext/fontext/fontext.cpp
- dll/win32/shell32/folders/CFSFolder.cpp
JIRA issue: [CORE-17673](https://jira.reactos.org/browse/CORE-17673)
Also sneak the fonts folder icon back in.
> [SHELL32] CFSFolder: Add fallback for failing shell extension

- modules/rostests/apitests/imm32/himc.c
- Use `ok` macro rather than `ok_int` macro.
> [IMM32_APITEST] himc: Use ok rather than ok_int

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtAdjustGroupsToken.c
- modules/rostests/apitests/ntdll/testlist.c
- ntoskrnl/se/token.c
- sdk/include/ndk/sefuncs.h
This implements `NtAdjustGroupsToken` syscall which is roughly similar to the privileges counterpart in terms of implementation, with a few exceptions.
> [NTOS:SE] Implement token groups adjusting

- dll/win32/iphlpapi/iphlpapi_main.c
- dll/win32/iphlpapi/merge-notes.txt
WineSync missed part of
https://source.winehq.org/git/wine.git/commit/629352bdc4683a5059f6d9c735df6930b1ea30c3
JIRA issue: [CORE-8454](https://jira.reactos.org/browse/CORE-8454)
> [IPHLPAPI] GetAdaptersInfo(): Update Wine registry key name

- modules/rostests/apitests/user32/CMakeLists.txt
- modules/rostests/apitests/user32/keybd_event.c
- modules/rostests/apitests/user32/testlist.c
- win32ss/user/ntuser/keyboard.c
When KEYEVENTF_SCANCODE is supplied, the edited routine is supposed to ignore the supplied VK and hence procure it itself from the given scancode. The word VK is getting values > 0xFE from the keyboard table which is incorrect (VK > 0xFE do not exist)
JIRA issue: [CORE-17144](https://jira.reactos.org/browse/CORE-17144)
Turns out, simply ```&= 0xFF``` makes the VK correspond to the correct value.
> [NTUSER] Fix UserSendKeyboardInput() KEYEVENTF_SCANCODE use case

- dll/win32/imm32/imm.c
- dll/win32/imm32/utils.c
- modules/rostests/apitests/imm32/clientimc.c
- sdk/include/reactos/wine/ddk/imm.h
- win32ss/include/ntuser.h
- Add `Imm32InitContext` and `Imm32LockIMCEx` helper functions.
- Re-implement `ImmLockIMC` function (this is not `ImmLockIMCC`, don't confuse).
- Modify `CLIENTIMC` and `INPUTCONTEXTDX` structures.
> [IMM32] Rewrite ImmLockIMC

- ntoskrnl/se/priv.c
- ntoskrnl/se/sid.c
In addition to that, the limit "magic" threshold value in `SeCaptureSidAndAttributesArray` must also be explicitly named with a define macro so that one understands what is it about.
> [NTOS:SE] Check the privilege count if it's within the limit threshold when capturing

- dll/win32/shell32/shellmenu/CMenuToolbars.cpp
This fixes log spam about NM_CUSTOMDRAW not being handled
> [SHELL32] Fix uninitialized variable usage.

- modules/rostests/apitests/imm32/CMakeLists.txt
- modules/rostests/apitests/imm32/ImmGetImeInfoEx.c
- modules/rostests/apitests/imm32/testlist.c
Investigate `IMM32` implementation.
- Add `ImmGetImeInfoEx` testcase.
WinXP (Japanese):
Successful.
Win2k3 (English):
Successful.
Win10 (Japanese):
Successful.
> [IMM32_APITEST] Add ImmGetImeInfoEx testcase

- dll/win32/shell32/COpenWithMenu.cpp
_Add registry handling of two keys to COpenWithMenu.cpp._
JIRA issue: [CORE-17816](https://jira.reactos.org/browse/CORE-17816)
> [SHELL32] Enable OpenWith to handle "NoOpenWith" and "NoStartPage" registry keys

- ntoskrnl/include/internal/amd64/mm.h
- ntoskrnl/include/internal/i386/mm.h
- ntoskrnl/ke/i386/traphdlr.c
Explicit macros vs magic values.
> [NTOSKRNL] Use MI_IS_WRITE_ACCESS(), instead of magic values

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtFilterToken.c
- modules/rostests/apitests/ntdll/testlist.c
- modules/rostests/kmtests/CMakeLists.txt
- modules/rostests/kmtests/kmtest_drv/testlist.c
- modules/rostests/kmtests/ntos_se/SeTokenFiltering.c
- ntoskrnl/se/token.c
- sdk/include/ndk/sefuncs.h
- sdk/include/ndk/setypes.h
- sdk/include/xdk/setypes.h
The support of token filtering allows the kernel to create "filtered" access tokens (or in other words, restricted tokens of regular ones) with disabled SIDs, deleted privileges, etc, so that the token is prevented from accessing the securable objects and such.
`NtFilterToken` is used respectively in `CreateRestrictedToken` ADVAPI32 API routine call. A separate PR for it will be published as soon as this gets merged, since our `CreateRestrictedToken` implementation is mere hacks.
> [NTOS:SE] Implement token filtering

- dll/win32/comctl32/status.c
wParam (num_parts) is allowed to be bigger than the actual amount of parts
JIRA issue: [CORE-17842](https://jira.reactos.org/browse/CORE-17842)
This allows process explorer 16.02 to start.
> [COMCTL32] Fix crash on SB_GETPARTS

- sdk/lib/crt/stdio/file.c
_Revert locking ioinfo when spawing to previous logic._
JIRA issue: [CORE-15176](https://jira.reactos.org/browse/CORE-15176)
_Stops GIMP Version 2.6.11 from freezing when opening a file._
> [CRT] Do Not lock ioinfo when Spawning Functions

- ntoskrnl/include/internal/tag.h
- ntoskrnl/se/sid.c
SIDs are variadic by nature which means their lengths can vary in a given amount of time and certain factors that allow for this happen. This also especially can lead to issues when capturing SIDs and attributes because SeCaptureSidAndAttributesArray might end up overwriting the buffer during the time it's been called.
Therefore when we're copying the SIDs, validate their lengths. In addition to that, update the documentation header accordingly.
> [NTOS:SE] Validate the SID lengths when capturing them

- sdk/include/crt/setjmp.h
Added in setjmp for arm64.
Pulled from:
mingw-w64 v9.0.0
JIRA issue: [CORE-17622](https://jira.reactos.org/browse/CORE-17622)
- Add setjmp for arm64
> [SDK] Add setjmp for the arm64 architecture

- sdk/tools/hhpcomp/hhpcomp.cpp
Good afternoon.
I noticed that your code is using chdir without checking the return value. it may not be safe.
I suggest adding a check.
> [HHPCOMP] Check return value when calling chdir

- dll/win32/shell32/droptargets/CFSDropTarget.cpp
- dll/win32/shell32/droptargets/CFSDropTarget.h
We couldn't create a shortcut of a drive correctly. This PR will fix the behavior of right-drag-and-drop.  
JIRA issue: [CORE-17813](https://jira.reactos.org/browse/CORE-17813)
- If the Right-dropped item was a drive, then get the display name of the drive and use it.
- Use `FAILED_UNEXPECTEDLY` instead of `FAILED` macro.
- Accept `::{GUID}`.
- Refactoring.
Successful.
Able to create the `::{GUID}` shortcut.
> [SHELL32] Drop a shortcut of the drive

- boot/bootdata/hivesft.inf
Update some time zones for Eastern Europe
JIRA issue: [CORE-12025](https://jira.reactos.org/browse/CORE-12025)
- Remove Minsk from GMT+02:00 (is now GMT+03:00)
- Change description for GMT+02:00 time zones
- Add Turkey time GMT+03:00
> Please ping to contributors who responsible to this.
> [BOOTDATA] Update some time zones for Eastern Europe

- ntoskrnl/ex/sysinfo.c
- sdk/include/ndk/exfuncs.h
- sdk/include/ndk/extypes.h
[NDK][NTOS:EX] Minor formatting.
[NDK][NTOS:EX] Add/fix SAL annotations for Nt/ZwSetSystemInformation + last parameter type.
[NTOS:EX] NtQuerySystemInformation: Use same parameter names as documentation. FStatus --> Status.
> Minor formatting + SAL annotations for NtQuery/SetSystemInformation 

- ntoskrnl/ex/sysinfo.c
Since NT 3.51, this information class is trivially implemented.
The path to the NT directory is now stored in the KUSER_SHARED_DATA
as the NtSystemRoot member.
Windows Checked builds break to the debugger to show a message
before failing the function as not implemented:
EX: SystemPathInformation now available via SharedUserData
See https://www.geoffchappell.com/studies/windows/km/ntoskrnl/api/ex/sysinfo/query.htm
and https://www.geoffchappell.com/studies/windows/km/ntoskrnl/inc/api/ntexapi_x/kuser_shared_data/index.htm
for more information.
> [NTOS:EX] Clarify the situation with the SystemPathInformation class.

- win32ss/user/user32/windows/message.c
Some versions of libgdk-win32-2.0.0.dll enters into an infinite loop when calling GetQueueStatus() with QS_ALLINPUT flag.
This happens because the RealGetQueueStatus() function performs a wrong flag check, thus calling it with QS_ALLINPUT leads to a 0 returned and setting the last error to ERROR_INVALID_FLAGS.
This seems to be fatal for [libgdk calls to GetQueueStatus()](https://gitlab.gnome.org/search?search=GetQueueStatus&group_id=8&project_id=665&scope=&search_code=true&snippets=false&repository_ref=2.24.11&nav_source=navbar) as they relies in GetQueueStatus() not returning 0.
@julenuri told me some time ago that this issue is not present in Wine, so a quick look in [Wine's implementation of GetQueueStatus](https://source.winehq.org/git/wine.git/blob/32fb017d4a22be38ca271bf387e466e95860 …
> [USER32] GetQueueStatus() should not return 0 when passing QS_ALLINPUT flag

- ntoskrnl/include/internal/io_x.h
- ntoskrnl/include/internal/ke_x.h
We're protecting against IopCompleteRequest, which is a special
kernel APC. So this is a little bit faster than raising the IRQL.
> [NTOS:IO] Use a guarded region in IopQueueIrpToThread.

- win32ss/gdi/ntgdi/dibobj.c
_Correct 'use after free' in dibobj.c._
JIRA issue: [CORE-17861](https://jira.reactos.org/browse/CORE-17861)
> [WIN32K] Fix 'use after free' in NtGdiStretchDIBitsInternal

- win32ss/user/ntuser/defwnd.c
InternalPos.NormalRect is a key data for detecting is window was snapped. Keeping it after restore affecting next snap actions
JIRA issue: [CORE-16477](https://jira.reactos.org/browse/CORE-16477)
> [WIN32SS:NTUSER] Fix window state after restoring snapped window. CORE-16477

- dll/win32/shell32/CDefView.cpp
- subsystems/mvdm/ntvdm/dos/dos32krnl/process.c
_Add otya128's WineVDM link code into the ReactOS NTVDM._
JIRA issue: [CORE-17852](https://jira.reactos.org/browse/CORE-17852)
> [NTVDM] Add otya128's WineVDM integration code into ReactOS

- subsystems/mvdm/ntvdm/dos/dos32krnl/process.c
_Change strcat functions to StringCbCatA ones._
JIRA issue: [CORE-17852](https://jira.reactos.org/browse/CORE-17852)
This is an extension of https://github.com/reactos/reactos/pull/4113
> [NTVDM] Use strsafe functions for concantenation of strings in otvdm code.

- dll/win32/riched20/paint.c
Baidu Browser installer used to get an assertion failure.
JIRA issue: [CORE-16578](https://jira.reactos.org/browse/CORE-16578)
- Fail elegantly on `ME_EnsureVisible` function if `pRow` or `pPara` is `NULL`.
BEFORE:
AFTER:
> [RICHED20] Fail elegantly if pRow or pPara is NULL on ME_EnsureVisible

- base/shell/explorer/traywnd.cpp
_Changes to code to allow different calculation for 'cy' when theme is active._
JIRA issue: [CORE-16742](https://jira.reactos.org/browse/CORE-16742)
> [EXPLORER] Fix for Start Button Wrong size when Using Themes

- win32ss/gdi/eng/device.c
Pass the correct display name to `EngpFindGraphicsDevice` function in `EngpUpdateGraphicsDeviceList`. According to our TechWiki page: https://reactos.org/wiki/Techwiki:Win32k/GRAPHICS_DEVICE, it actually should look like `\\.\DISPLAY<n>` (since it comes from user mode), which that function searches, not `\\Device\\Video<n>`, like done in kernel mode. Otherwise, passing wrong name causes mismatch and further conflicts.
It fixes the problem with access to the video device (failure with status 0xc0000022 when trying to open it). Hence, it also removes the following logspam:
`(/win32ss/gdi/eng/device.c:350) err: Could not open device \Device\Video0, 0xc0000022`.
UPD: it also fixes screen resolution saving regression described in CORE-17719, as confirmed by @Doug-Lyons. :slightly_smiling_face: …
> [WIN32SS][ENG] Search for the correct display name when updating graphics devices list

- boot/freeldr/freeldr/include/debug.h
Be explicit.
Addendum to 0.4.15-dev-200-g98c17d3.
JIRA issue: [CORE-16216](https://jira.reactos.org/browse/CORE-16216)
> [FREELDR] debug.h: Add an explicit VOID parameter type

- dll/win32/comctl32/combo.c
Sync Wine commit c82d6ee by Gabriel Ivancescu
JIRA issue: [CORE-17883](https://jira.reactos.org/browse/CORE-17883)
Before:
After:
> [COMCTL32] Redraw children when the combo box is dropped down.

- win32ss/gdi/ntgdi/fillshap.c
- win32ss/gdi/ntgdi/line.c
- win32ss/gdi/ntgdi/path.c
- win32ss/gdi/ntgdi/path.h
- win32ss/gdi/ntgdi/pen.c
- win32ss/gdi/ntgdi/pen.h
Implement the pen width.
JIRA issue: [CORE-2527](https://jira.reactos.org/browse/CORE-2527), [CORE-8366](https://jira.reactos.org/browse/CORE-8366)
The test program: https://jira.reactos.org/secure/attachment/43554/PenTest2.zip
- Extend `PATH_WidenPath` function as `PATH_WidenPathEx` with the path argument.
- Use `PATH_WidenPathEx` and `PATH_FillPathEx` functions to implement wide pen drawing in `PATH_StrokePath` function.
- Add the code to `IntGdiLineTo`, `IntRectangle`, `IntGdiPolygon`, and `IntGdiPolyline` in order to stroke the path when the effective wide pen.
Win10:
BEFORE:
AFTER:
> [NTGDI] Support the wide pen

- base/services/w32time/lang/es-ES.rc
- base/services/w32time/w32time.rc
Spanish translation of w32time service. Created es-ES.rc file.
> [W32TIME] Add Spanish (es-ES) translation

- win32ss/user/user32/controls/appswitch.c
Task Switcher (`Alt+Tab`) used to be hung up if there were any halted windows.
NOTE: This is not the perfect fix.
- Use `SendMessageTimeout` instead of `SendMessage`.
- Use `SwitchToThisWindow` instead of `BringWindowToTop`.
- Use `ShowWindowAsync` instead of `ShowWindow`.
- Use `SWP_ASYNCWINDOWPOS` for `SetWindowPos`.
> [USER32] Partially fix freezing of Task Switcher

- base/setup/usetup/lang/pt-PT.h
- base/setup/usetup/usetup.c
[USETUP] Set menu item length to maximum string length
In pt-PT language in usetup.c BootLoaderPage  the menu bar when selected is shorter than the string length
Better solution by improving pt-PT translation
> [USETUP] Improve pt-PT translation

- win32ss/user/ntuser/simplecall.c
- win32ss/user/user32/controls/appswitch.c
`user32.SwitchToThisWindow` function is used in Task Switcher.
- Delete useless `wtodw` user function (because we already have `_wtoi` and `wcstol` functions).
- Delete `MakeWindowActive` user function and directly call `user32.SwitchToThisWindow` function in Task Switcher.
- Improve and simplify `user32.SwitchToThisWindow`.
BEFORE:
AFTER:
No change.
> [NTUSER][USER32] Simplify SwitchToThisWindow

- base/applications/cmdutils/help/lang/tr-TR.rc
Fixes (tr-TR) resource file sporadic compilation error RC2102 on VS2015 and VS2017
JIRA issue: [CORE-17910](https://jira.reactos.org/browse/CORE-17910)
Based on the work done at CORE-7405, moves the string split location so
the first part of the message isn't too long anymore.
> [HELP] Fixes (tr-TR) resource sporadic compilation error on VisualStudio

- base/shell/explorer/taskswnd.cpp
- Reduce the timeout amount for `SendMessageTimeout` calls.
- Add `bAlive` flag to check whether the window is hung-up in order to optimize for speed.
AFTER:
The taskbar right-click menu is able to appear quickly even if there is a halted window.
> [EXPLORER] Quick taskbar menu even if any halted window

- win32ss/include/ntuser.h
- win32ss/user/ntuser/winpos.c
- win32ss/user/user32/windows/mdi.c
- win32ss/user/user32/windows/window.c
Hanging used to happen because `user32.TileWindows` and `user32!CascadeWindows` were processing synchronously.
- Modify `NtUserEndDeferWindowPosEx` prototype.
- Use asynchronous way in `TileWindows` and `CascadeWindows` functions.
> [NTUSER][USER32] Use async way in TileWindows and CascadeWindows

- base/applications/taskmgr/applpage.c
Performs asynchronous window processing to accept the halted windows without hanging.
- Use `SwitchToThisWindow` directly.
- Use `ShowWindowAsync` instead of `ShowWindow`.
> [TASKMGR] Avoid hangs as much as possible

- win32ss/gdi/ntgdi/pen.c
JIRA issue: [CORE-13819](https://jira.reactos.org/browse/CORE-13819)
- Check the pen style and elegantly fail if the style was wrong.
BEFORE:
AFTER:
Successful.
BEFORE:
Successful.
AFTER:
Successful.
> [NTGDI] Strictly check pen style

- base/shell/explorer/traywnd.cpp
[EXPLORER] Fixed issue in TaskBar AUTOHIDE
In the "Taskbar and Start Menu Properties" dialog box,
with option "Auto-Hide TaskBar" checked, and
unlocking and moving the taskbar to the top or the left side of the desktop, the CTrayWindow :: ProcessAutoHide () method enters an infinite loop.
In case ABE_LEFT and ABE_TOP the m_AutoHideOffset attribute never reaches the local variable "w" or "h", so that the timer be not restarted again in line 1897.
JIRA issue: CORE-17093
> [EXPLORER] Fixed issue in TaskBar AUTOHIDE CORE-17093

- dll/win32/msi/package.c
_Partial Wine-6.8 sync of package.c for MSI_OpenPackageW._
JIRA issue: [CORE-17693](https://jira.reactos.org/browse/CORE-17693)
> [MSI] Fix MS Office 2000/2003 Installs by Wine-6.8 Sync of MSI_OpenPackageW

- win32ss/user/ntuser/msgqueue.c
_Implement I_Kill_Bugs 'No remove' patch._
JIRA issue: [CORE-8217](https://jira.reactos.org/browse/CORE-8217)
_This fixes one component of the 3dtext screensaver not being responsive._
> [WIN32SS] Do not remove message from the Message Queue if not ours

- hal/halx86/generic/dma.c
Simplify code, instead of adding 2 missing ObDereferenceObject().
JIRA issue: [CORE-17904](https://jira.reactos.org/browse/CORE-17904)
> [HALX86] HalpDmaAllocateChildAdapter(): Fix memory leak, on error

- drivers/filesystems/ntfs/btree.c
- drivers/filesystems/udfs/Include/wcache_lib.cpp
- drivers/filesystems/udfs/env_spec.cpp
- fix build of ntfs/btree.c
- comment out not used variable in env_spec.cpp
- fix missed brackets in else wcache_lib.cpp
Fix build with removed NDEBUG
> fix necessary that build runs through with removed NDEBUG

- win32ss/reactx/ntddraw/dxeng.c
Add several improvements in `case 2` of `DxEngGetDCState` function in our win32k.
This allows to properly enable and use DirectDraw and Direct3D hardware acceleration with the following MS DirectX components: ddraw.dll, d3d8.dll, d3d9.dll and dxg.sys. As in VM, same on real hardware. :smiley: 
But note that now the bugcheck 0x50 (`PAGE_FAULT_IN_NONPAGED_AREA`) occurs when executing fullscreen DDraw apps, after switching display mode. It's unhidden by this fix. **To be reported.**
Addendum to 855bf46.
JIRA issue: [CORE-17561](https://jira.reactos.org/browse/CORE-17561)
- Use the `REGION_Complexity()` function to get the actual region complexity instead of just number of rectangles.
- Don't use `prgnRao` at all, because it is always uninitialized when passed to the function. So in condition …
> [WIN32SS][NTDDRAW] Improve DxEngGetDCState type 2 implementation

- dll/shellext/netshell/lang/bg-BG.rc
- dll/shellext/netshell/lang/da-DK.rc
- dll/shellext/netshell/lang/el-GR.rc
- dll/shellext/netshell/lang/en-US.rc
- dll/shellext/netshell/lang/he-IL.rc
- dll/shellext/netshell/lang/id-ID.rc
- dll/shellext/netshell/lang/it-IT.rc
- dll/shellext/netshell/lang/nl-NL.rc
- dll/shellext/netshell/lang/no-NO.rc
- dll/shellext/netshell/lang/sk-SK.rc
- dll/shellext/netshell/lang/sq-AL.rc
- dll/shellext/netshell/lang/sv-SE.rc
A string in the installer is missing the word "not", and as a result is slightly confusing.  Add the missing word.
> [NETSHELL] Improve workgroup vs. domain wording

- win32ss/user/ntuser/window.c
Based on `I_Kill_Bugs`' patch.
JIRA issue: [CORE-10499](https://jira.reactos.org/browse/CORE-10499)
- Use `IsCallProcHandle` to check if the procedure is a call procedure handle.
- If so, use the call procedure.
BEFORE:
FAILED.
AFTER:
Successful.
> [NTUSER] Use call procedure handle if available

- base/applications/taskmgr/applpage.c
- Change the timeout value of `SendMessageTimeout`.
- Use `SMTO_ABORTIFHUNG` flag.
- Check if the window alive.
> [TASKMGR] Avoid freezing in getting icons

- drivers/input/i8042prt/hwhacks.c
Fixes the Dell Latitude D820 TouchPad not working
Add the Dell Latitude D820 string to `i8042HardwareTable`
> [I8042PRT] Add Dell Latitude D820 to the hack list

- dll/win32/gdiplus/image.c
JIRA issue: [CORE-17814](https://jira.reactos.org/browse/CORE-17814)
- Add `hbitmap_from_emf` helper function.
- `GdipCreateBitmapFromStream` accepts the metafiles.
> [GDIPLUS] GdipCreateBitmapFromStream should accept metafiles

- base/applications/mspaint/lang/bg-BG.rc
- base/applications/mspaint/lang/cs-CZ.rc
- base/applications/mspaint/lang/de-DE.rc
- base/applications/mspaint/lang/en-GB.rc
- base/applications/mspaint/lang/en-US.rc
- base/applications/mspaint/lang/es-ES.rc
- base/applications/mspaint/lang/et-EE.rc
- base/applications/mspaint/lang/eu-ES.rc
- base/applications/mspaint/lang/fr-FR.rc
- base/applications/mspaint/lang/he-IL.rc
- base/applications/mspaint/lang/hu-HU.rc
- base/applications/mspaint/lang/id-ID.rc
- base/applications/mspaint/lang/it-IT.rc
- base/applications/mspaint/lang/ja-JP.rc
- base/applications/mspaint/lang/nl-NL.rc
- base/applications/mspaint/lang/no-NO.rc
- base/applications/mspaint/lang/pl-PL.rc
- base/applications/mspaint/lang/pt-BR.rc
- base/applications/mspaint/lang/pt-PT.rc
- base/applications/mspaint/lang/ro-RO.rc
- base/applications/mspaint/lang/ru-RU.rc
- base/applications/mspaint/lang/sk-SK.rc
- base/applications/mspaint/lang/sq-AL.rc
- base/applications/mspaint/lang/sv-SE.rc
- base/applications/mspaint/lang/tr-TR.rc
- base/applications/mspaint/lang/uk-UA.rc
- base/applications/mspaint/lang/vi-VN.rc
- base/applications/mspaint/lang/zh-CN.rc
- base/applications/mspaint/lang/zh-TW.rc
- base/applications/mspaint/main.cpp
BMP is obsolete. We will use PNG as default.
- Make `IDS_DEFAULTFILENAME` resource strings PNG extension.
- Choose PNG on `GetSaveFileName`.
- Clear the filename on `GetOpenFileName`.
> [MSPAINT] Make PNG default instead of BMP

- base/applications/mspaint/common.h
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/main.cpp
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/scrollbox.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/winproc.cpp
Reduce magic numbers.
- Define `GRIP_SIZE` macro (its value is `3`) in `common.h`.
- Use it.
> [MSPAINT] Define GRIP_SIZE macro and use it

- dll/win32/comctl32/tab.c
Based on @JoachimHenze (reactosfanboy)'s patch.
JIRA issue: [CORE-4245](https://jira.reactos.org/browse/CORE-4245)
- Switch `TCIS_BUTTONPRESSED` flag at `TAB_SetCurFocus` function.
> [COMCTL32] Handle TCIS_BUTTONPRESSED at TAB_SetCurFocus

- base/applications/mspaint/registry.cpp
If the bitmap size from the registry settings is too large, we should fix it.
- Fix the initial values of `BMPHeight` and `BMPWidth`.
- Fix the values of `BMPHeight` and `BMPWidth` if too large.
> [MSPAINT] Fix the size of settings if too large

- base/applications/mspaint/common.h
- base/applications/mspaint/mouse.cpp
Refactoring...
- Add `nearlyEqualPoints` helper function and use it.
- The `nearlyEqualPoints`  function uses `GetSystemMetrics(SM_CXDRAG)` and `GetSystemMetrics(SM_CYDRAG)`.
> [MSPAINT] Add nearlyEqualPoints and use it

- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/selectionmodel.h
Improve code quality.
- Add `const` keywords to some methods of `SelectionModel` class.
> [MSPAINT] Add const to SelectionModel methods

- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/toolsmodel.h
Improve code quality.
- Add `const` keywords to some methods of `ToolsModel` class.
> [MSPAINT] Add const to ToolsModel methods

- base/applications/mspaint/CMakeLists.txt
- base/applications/mspaint/common.h
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/imgarea.h
- base/applications/mspaint/scrollbox.cpp
- base/applications/mspaint/scrollbox.h
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/selection.h
- base/applications/mspaint/toolsettings.cpp
- base/applications/mspaint/winproc.cpp
- base/applications/mspaint/winproc.h
Expect usability improvement by mouse wheel handling.
JIRA issue: [CORE-17937](https://jira.reactos.org/browse/CORE-17937)
- If the mouse wheel message has come to the child windows, then forward it to its parent window.
- Post some scroll messages on mouse wheel message of the main window.
- Or modify the zoom rate.
- Modify `CMakeLists.txt` to use `_WIN32_WINNT=0x600`.
> [MSPAINT] Mouse Wheel support

- base/applications/mspaint/definitions.h
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/toolbox.cpp
- base/applications/mspaint/toolsettings.cpp
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/toolsmodel.h
- base/applications/mspaint/winproc.cpp
Improve code quality and debuggability.
- Define `enum TOOLTYPE` in `toolsmodel.h`.
- Use it.
- Add the missing cases in the `switch` statements.
> [MSPAINT] Define enum TOOLTYPE and use it

- ntoskrnl/dbgk/dbgkobj.c
- ntoskrnl/ex/atom.c
- ntoskrnl/ex/harderr.c
- ntoskrnl/ex/profile.c
- ntoskrnl/fsrtl/filelock.c
- ntoskrnl/fsrtl/oplock.c
- ntoskrnl/inbv/inbv.c
- ntoskrnl/include/internal/tag.h
- ntoskrnl/io/iomgr/driver.c
- ntoskrnl/io/pnpmgr/devaction.c
- ntoskrnl/kdbg/kdb.h
- ntoskrnl/ke/bug.c
- ntoskrnl/ke/i386/kiinit.c
- ntoskrnl/ke/i386/v86vdm.c
- ntoskrnl/ob/obhandle.c
- ntoskrnl/po/povolume.c
- ntoskrnl/ps/apphelp.c
- ntoskrnl/ps/i386/psldt.c
- ntoskrnl/rtl/libsupp.c
We already have a dedicated header file where we store pool allocation tags that are used in NT, called `tag.h`, and yet I still see some tags around the kernel which is annoying and confusing. Everyone who discovers a new pool tag or whatever has to use `tag.h` from now on.
> [NTOSKRNL] Regroup the pool allocation tags in one dedicated place

- sdk/lib/3rdparty/freetype/CMakeLists.txt
Make current state more explicit.
Especially, `CLANG` is also `GCC` or `MSVC`, so current code is "broken".
> [FREETYPE] CMakeLists.txt: Fix if conditions

- sdk/lib/crt/mem/memchr.c
- sdk/lib/crt/mem/memmove.c
Fix (AppVeyor/GitHub) MSVC 14.0 amd64.
A.k.a. unbreak VS 2015 amd64 build. (VS 2017/2019 still have unrelated CORE-17585.)
Addendum to aea4cfb.
--
[Minimal testcase](https://github.com/SergeGautherie/reactos/actions/runs/1035792736):
```
sdk\lib\crt\mem\memchr.c(5): error C4163: 'memchr': not available as an intrinsic function
sdk\lib\crt\mem\memmove.c(4): error C4163: 'memmove': not available as an intrinsic function
```
> [CRT] mem/: Fix msvc14.0-amd64 build

- toolchain-clang.cmake
Sync Clang with Gcc.
Needed to fix Clang part of #3787.
Addendum to 8cd5c4e.
JIRA issue: [CORE-14513](https://jira.reactos.org/browse/CORE-14513)
> [CMAKE] toolchain-clang.cmake: Use overrides-gcc.cmake

- dll/win32/syssetup/wizard.c
Write sound events values in registry in case user selected Workstation setup during 2nd setup stage.
This makes ROS behaving more like XP (which is also Workstation), since all sound events are enabled there by default.
JIRA issue: [CORE-13951](https://jira.reactos.org/browse/CORE-13951)
- Define sound events registry keys and arrays with sound events values.
- Implement helper `DoWriteSoundEvent` function, which does all work.
- Call it in `DoWriteProductOption` in case if Workstation was selected.
> [SYSSETUP] Enable sound events for Workstation

- drivers/filters/fltmgr/Messaging.c
Avoid extra `ObDereferenceObject()`.
JIRA issue: [CORE-17904](https://jira.reactos.org/browse/CORE-17904)
> [FLTMGR] CreateClientPort(): Fix ObInsertObject() error handling

- base/applications/mspaint/palettemodel.cpp
- base/applications/mspaint/palettemodel.h
- base/applications/mspaint/winproc.cpp
Reduce magic numbers and improve debuggability.
- Define `NUM_COLORS` macro and `enum PAL_TYPE` in `palettemodel.h`.
- Use them.
- Add `static const` to `modernColors` and `oldColors` in `PaletteModel::SelectPalette`.
- Use `COLORREF` for some color values.
> [MSPAINT] Add NUM_COLORS and enum PAL_TYPE

- win32ss/gdi/eng/surface.c
Set an `API_BITMAP` flag for bitmaps created by `EngCreateBitmap`.
This avoids failure when created bitmap is passed to `NtGdiSelectBitmap`, since it checks for this flag and fails if it isn't set.
Otherwise, if failure occurs, the bitmap is hot handled properly.
Setting this flag outside of that function is not an option at all, because it is a public (exported) function, and in many cases it's called directly by the caller (in case with MS DDraw stack, it can be called also by dxg.sys from `dxgthk!EngCreateBitmap`, which directly calls `win32k!EngCreateBitmap`).
In particular, it allows Windows XP/2003 DirectDraw stack (ddraw.dll & dxg.sys) to properly work in ReactOS (in software emulation mode), even on real hardware. So now, a lot of DirectX 1-7 apps and games (whose can work without …
> [WIN32SS][ENG] EngCreateBitmap: mark created bitmaps as API bitmaps

- dll/win32/devmgr/devmgmt/DeviceView.cpp
- dll/win32/devmgr/devmgmt/DeviceView.h
- dll/win32/devmgr/devmgmt/MainWindow.cpp
_Fix a bug related to the device manager where double clicking anywhere when you have selected an item opens the property sheet_
JIRA issue: [CORE-17207](https://jira.reactos.org/browse/CORE-17207)
_Ensure that you are clicking an item when opening the property sheet_
> [DEVMGR] Ensure clicking on item when opening property sheet

- dll/win32/shell32/shellmenu/CMenuFocusManager.cpp
_Focus manager doesn't handle double click_
JIRA issue: [CORE-9943](https://jira.reactos.org/browse/CORE-9943)
_Just pretend that double click is a normal click button_
> [SHELL32] Handle double click on focus manager

- dll/win32/msi/dialog.c
_Only show the main dialog pane in the taskbar when executing a Cancel dialog._
JIRA issue: [CORE-17702](https://jira.reactos.org/browse/CORE-17702)
> [MSI] Improve previous msi/dialog.c patch to match code committed to Wine.

- boot/bootdata/bootcd.ini
- boot/bootdata/floppy_pc98.ini
- boot/bootdata/hybridcd.ini
- boot/bootdata/livecd.ini
Based on the idea proposed by @vgalnt in:
JIRA issue: [CORE-17350](https://jira.reactos.org/browse/CORE-17350)
Makes testing easier on real hardware (especially for these configs
where debugging can only be done via screen mode).
Add also an experimental Setup ACPI APIC entry in bootcd.ini for testing
purposes, along the lines of commit 5ee0925 .
In the similar LiveCD entry, use instead the /HAL= option.
> [BOOTDATA] Add new Setup Debug/Screen boot entries in BootCD/HybridCD/PC98 boot menus.

- dll/shellext/fontext/CFontExt.cpp
- dll/shellext/zipfldr/CZipFolder.hpp
- dll/win32/shell32/CExtractIcon.cpp
- sdk/include/psdk/shlobj.h
Note that even if the MS PSDK and MSDN documents an hypothetical
ANSI version SHCreateFileExtractIconA(), this one never existed
exported in any Windows version!
> [PSDK][SHELL32][SHELLEXT] Add SHCreateFileExtractIconW() to the PSDK headers, and SAL-annotate it.

- dll/win32/syssetup/wizard.c
This prevents a race condition, where hSysSetupInf could be closed before all type libraries are registered
> [SYSSETUP] Register type libraries before signaling we are done

- dll/win32/imm32/imm.c
- win32ss/include/ntuser.h
- win32ss/user/ntuser/main.c
- win32ss/user/ntuser/ntstubs.c
- win32ss/user/ntuser/userfuncs.h
- Modify `NtUserCreateInputContext` prototype.
- Add `UserCreateInputContext` helper function.
- Implement `NtUserCreateInputContext` function by using `UserCreateInputContext`.
- Call `UserCreateInputContext(0)` in `InitThreadCallback` function to create the default input context.
> [NTUSER] Implement NtUserCreateInputContext

- dll/win32/bcrypt/bcrypt_main.c
Add ECDSA P256 to known algorithms.
Fix download problems for notepad++ with RAPPS
I started syncing bcrypt from WINE to ReactOS to support ECDSA algorithm.
At the point that i had to adjust the code to mbedtls, i tried to debug where
i have to do more adjustments. To my surprise the code work at this point already.
Therefor i check what is the minimal change to fix the reported issue.
This PR is the result.
See [video](https://jira.reactos.org/secure/attachment/61351/61351_reactos-bcrypt-2021-12-30T20-58-06-726618000Z.webm) for proof. Tested on an linux host under QEMU
and  Virtualbox.
JIRA issue: [CORE-16741](https://jira.reactos.org/browse/CORE-16741)
Add ECSDA P256 algorithm structs and BCryptOpenAlgorithmProvider function.
- Fix download problems for notepad++ with RAPPS
> [BCRYPT] Add ECDSA P256 to known algorithms

- win32ss/user/ntuser/ime.c
KVM and VBox tests was failing since https://github.com/reactos/reactos/commit/d5deacd90305a83d413af18dca8fa41fe03e61b3
- Check `NULL` at `UserFreeInputContext` and `UserDestroyInputContext` functions.
- Move `UserMarkObjectDestroy` into the `UserDestroyInputContext` function.
> [NTUSER] Fix KVM and VBox tests

- drivers/storage/ide/uniata/srb.h
Now it's consistent with our structure in `sdk/include/ddk/srb.h`.
Thanks to Hervé Poussineau for help with problem analysis.
JIRA issue: [CORE-17966](https://jira.reactos.org/browse/CORE-17966)
> [UNIATA] Fix packing for port configuration information structures

- win32ss/user/ntuser/main.c
- win32ss/user/ntuser/ntstubs.c
- Call `UserDereferenceObject` function in `UserCreateInputContext`.
- Don't call `UserDereferenceObject` against input context at the other places.
> [NTUSER] Plan A: UserDereferenceObject in UserCreateInputContext

- drivers/processor/processr/cpu.inf
- ntoskrnl/config/i386/cmhardwr.c
- ntoskrnl/ke/amd64/cpu.c
Also generate processor identifier properly based on this value
on the Configuration Manager machine-dependent initialization.
Update processor driver INF file accordingly.
JIRA issue: [CORE-17970](https://jira.reactos.org/browse/CORE-17970)
> [NTOS:KE/x64] Detect CPU vendor properly and store value in PRCB

- dll/win32/rpcrt4/ndr_typelib.c
Cherry-pick wine-5.0-rc1-50-g1aaf870 by Jacek Caban.
https://source.winehq.org/git/wine.git/?a=commit;h=1aaf870039dfb8419ae060d8c67240df1366b953
(OLEAUT32_WINETEST part shall be imported later.)
JIRA issue: [CORE-17884](https://jira.reactos.org/browse/CORE-17884)
> [RPCRT4] Fix implicit in attribute handling in write_param_fs()

- dll/win32/windowscodecs/bmpdecode.c
- dll/win32/windowscodecs/converter.c
- dll/win32/windowscodecs/main.c
- dll/win32/windowscodecs/wincodecs_private.h
This fixes CORE-15708 "PdfSam 3.3.5 setup can not decode bmp"
https://jira.reactos.org/browse/CORE-15708
Wine does not have this issue, but it did not have it back when last sync to
WineStaging-4.18 was done. This commit is as near as possible to actual
wine-7.0-rc3 version. This wine code uses reverse_bgr8 instead of own
convert_rgba_to_bgra, but it leads to wrong colors.
JIRA issue: [CORE-15708](https://jira.reactos.org/browse/CORE-15708)
- Add converter for WICPixelFormat32bppRGBA
> [WINDOWSCODECS] Add converter for WICPixelFormat32bppRGBA

- base/applications/screensavers/3dtext/settings.c
- base/system/winlogon/screensaver.c
_Change User Context of creating the screensaver process in winlogon.exe ._
JIRA issue: [CORE-17875](https://jira.reactos.org/browse/CORE-17875)
_This fixes the wrong text of "ReactOS Rocks!" being displayed when this screensaver times out._
> [WINLOGON] Start screen saver with current user

- drivers/ksfilter/ks/swenum.c
- drivers/wdm/audio/hdaudbus/hdaudbus.cpp
Redundant with previous `if()`.
Added as is.
I don't know if different conditions were intended.
> [HDAUDBUS][KS] Remove a redundant ASSERT()

- base/applications/mspaint/main.cpp
The Fonts toolbar uses toolbar and tooltips. Thus this flag is needed.
JIRA issue: [CORE-17949](https://jira.reactos.org/browse/CORE-17949)
- Add `ICC_BAR_CLASSES` flag to `InitCommonControlsEx` call.
> [MSPAINT] Add ICC_BAR_CLASSES

- dll/cpl/sysdm/environment.c
Fix the issue of the changes of the environment values not being set sometimes through fancy dialog box.
- Make sure the environment value buffer is always reallocated before taking the values.
> [SYSDM] Fix fancy edit Environment dialog box

- base/applications/mspaint/selection.cpp
- base/applications/mspaint/selection.h
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/winproc.cpp
JIRA issue: [CORE-17969](https://jira.reactos.org/browse/CORE-17969)
- Don't hide the selection on zooming.
- Move the selection window by calling `placeSelWin()` when zoomed.
> [MSPAINT] Don't hide selection on zooming

- dll/win32/shell32/folders/CRecycleBin.cpp
- dll/win32/shell32/shellrecyclebin/recyclebin_v5.c
_There was a handle reference leak in the recycler bin and the bin wasn't removing the copied file after restoring it_
JIRA issue: [CORE-13730](https://jira.reactos.org/browse/CORE-13730)
_Close the handle were the memory leak was and delete the file when restoring it_
> [SHELL32] Fix recycle bin handle reference leaking

- dll/win32/shell32/folders/CRecycleBin.cpp
- dll/win32/shell32/shellrecyclebin/recyclebin.c
- dll/win32/shell32/shellrecyclebin/recyclebin.h
- dll/win32/shell32/shellrecyclebin/recyclebin_v5.c
- dll/win32/shell32/shellrecyclebin/recyclebin_v5_enumerator.c
- Folders cannot be sent to recycle bin by a bug inside the implementation.
- Adjust column size of the RecycleBin virtual folder in details mode (sugested by hbelusca).
JIRA issue: [CORE-11000](https://jira.reactos.org/browse/CORE-11000)
Ensure folders can be opened on the function, this partially fix the bug, but my other PR that's still in review fix the other part of the bug, as this bug is related to it by the handle leak bug.
> [SHELL32] Fix folders on recycle bin and adjust the column size

- modules/rostests/kmtests/CMakeLists.txt
- modules/rostests/kmtests/kmtest_drv/testlist.c
- modules/rostests/kmtests/ntos_ps/PsQuota.c
- ntoskrnl/ex/handle.c
- ntoskrnl/fsrtl/notify.c
- ntoskrnl/include/internal/ex.h
- ntoskrnl/include/internal/mm.h
- ntoskrnl/include/internal/ob.h
- ntoskrnl/include/internal/ps.h
- ntoskrnl/include/internal/tag.h
- ntoskrnl/mm/ARM3/pool.c
- ntoskrnl/ob/obhandle.c
- ntoskrnl/ob/oblife.c
- ntoskrnl/ps/kill.c
- ntoskrnl/ps/quota.c
As it currently stands, the implementation of process quotas in the kernel is a stub. We're not checking if a process' quota usage is 0 when it de-references the quota block and we're lacking in code that handles Return, Limit, Peak and Usage fields of a quota block. The Object Manager of ReactOS kernel doesn't make any attempts to charge or return quotas of a given object.
Moreover on Windows the Process Manager cooperates with the Memory Manager if quota limit raising has to occur or not, something which we don't do that. With this PR the process quota support in the kernel is now half-implemented (we currently don't support paging so process page file quota is left behind for now). Kernel consistency is also now enforced as ReactOS kernel checks every time that there's no quota usage …
> [NTOS:PS] Process Quota Overhaul

- dll/win32/bcrypt/bcrypt_main.c
Add missing structs and handler in BCryptOpenAlgorithmProvider().
Cherry-pick a part of Michael Müller's
https://source.winehq.org/git/wine.git/commit/76b6c360fa7f3d6a0a14ed935075f5eb10f2f719
Follow-up to e0a47b7 (0.4.15-dev-3603).
JIRA issue: [CORE-14198](https://jira.reactos.org/browse/CORE-14198)
> [BCRYPT] Add ECDSA P384 to known algorithms

- sdk/lib/crt/wine/wine.cmake
Another small step...
Follow-up to 9efafd6 (0.4.14-dev-934).
JIRA issue: [CORE-17518](https://jira.reactos.org/browse/CORE-17518)
> [CRT/arm64] Build wine/except_arm64.c

- win32ss/user/user32/misc/exticon.c
- win32ss/user/user32/windows/cursoricon.c
_Add handling for 'RIFF' formats._
JIRA issue: [CORE-16287](https://jira.reactos.org/browse/CORE-16287)
Before:
After:
> [USER32] Improve icon extraction to handle RIFF formats and Fix crash

- dll/win32/imm32/ime.c
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- Add `UserGetImeInfoEx` helper function.
- Implement `NtUserGetImeInfoEx` function by using `UserGetImeInfoEx`.
- Fix `imm32.ImmGetImeInfoEx`.
- Modify `enum IMEINFOEXCLASS`.
> [NTUSER][IMM32] Implement NtUserGetImeInfoEx

- dll/win32/syssetup/install.c
The CJK (Chinese, Japanese and Korean; Asian) dialog uses the different font. So, the logo and bar positions of CJK are different from English positions. We will add adjustment to the CJK dialog.
- Add positional adjustment to `IDD_STATUSWINDOW_DLG` if CJK.
BEFORE:
AFTER:
> [SYSSETUP] Adjust Status Window if Asian

- win32ss/user/user32/windows/mdi.c
Not to make the windows too small.
- Improve the threshold of `CascadeWindows` function not to make the windows too small.
Still working.
> [USER32] Adjust the threshold in CascadeWindows

- dll/win32/shell32/folders/CRecycleBin.cpp
- dll/win32/shell32/shellrecyclebin/recyclebin_private.h
- dll/win32/shell32/shellrecyclebin/recyclebin_v5_enumerator.c
_Shell32 recycle bin ExtractIcon interface was unimplemented, half done by gigaherz_
JIRA issue: [CORE-3938](https://jira.reactos.org/browse/CORE-3938)
_Insert IExtractIcon interface inside of private recycle bin api, and then call it from CRecycleBin_
> [SHELL32] Implement Recycler Bin icons

- win32ss/user/ntuser/sysparams.c
Fixes CORE-14359
dwCaretWidth is not initialized in NtUser, this causes that when calling SystemParametersInfo() with SPI_GETCARETWIDTH flag, the DWord pointer passed as 3rd parameter always returns zero, the visible effect of this is that carets are created with 0 width and cannot be seen in text inputs.
JIRA issue: [CORE-13984](https://jira.reactos.org/browse/CORE-13984)  [CORE-14359](https://jira.reactos.org/browse/CORE-14359)  [CORE-16624](https://jira.reactos.org/browse/CORE-16624)
> [NTUSER] Initialize correctly CaretWidth value.

- base/applications/mspaint/history.cpp
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/palettemodel.cpp
- base/applications/mspaint/precomp.h
- base/applications/mspaint/scrollbox.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/textedit.cpp
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/winproc.cpp
- sdk/lib/atl/atlbase.h
- sdk/lib/atl/atltrace.h
Improve traceability of ATL applications.
JIRA issue: [CORE-17969](https://jira.reactos.org/browse/CORE-17969), [CORE-18012](https://jira.reactos.org/browse/CORE-18012)
- Implement `ATLTRACE` and `AtlTrace` in `atlbase.h`.
- Fix assertion failures in `mspaint`.
> [ATL][MSPAINT] Add ATLTRACE and fix assertion failures

- win32ss/user/user32/misc/exticon.c
Display icons/cursors correctly without hungup.
JIRA issue: [CORE-16287](https://jira.reactos.org/browse/CORE-16287)
- Correctly show `cross.cur` and `hcross.cur` cursor files.
No problem.
> [USER32] Follow-up of #4262 (a47590c)

- base/applications/taskmgr/graphctl.c
* improper adjustment of the array index in graphctl.c, introduced in PR #4141 lead to an off-by-one pool corruption. fixing this.
JIRA issue: [CORE-18015](https://jira.reactos.org/browse/CORE-18015)
> [TASKMGR]: Fixing the pool corruption bug

- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/ntuser.c
- win32ss/user/ntuser/ntuser.h
- Add `AtomImeLevel` atom.
- Modify `NtUserSetAppImeLevel` prototype.
- Implement `NtUserGetAppImeLevel` and `NtUserSetAppImeLevel` functions.
> [NTUSER] Implement NtUserGetAppImeLevel and NtUserSetAppImeLevel

- win32ss/user/user32/misc/imm.c
- Implement handling of `WM_CREATE` and `WM_DESTROY` messages of the IME window.
> [USER32] Implement WM_CREATE of IME window

- win32ss/include/ntuser.h
- win32ss/user/user32/misc/imm.c
- Add `User32CreateImeUIWindow`, `User32GetImeShowStatus`, `User32SendImeUIMessage`, `User32UpdateImcOfImeUI`, `User32SetImeWindowOfImc` and `User32NotifyOpenStatus` helper functions.
- Add `WM_IME_SELECT`, `WM_IME_COMPOSITION`, `WM_IME_STARTCOMPOSITION` and `WM_IME_ENDCOMPOSITION` message handling of the IME window.
- Rename `ImeWnd_OnDestroy` as `User32DestroyImeUIWindow`.
- Rename `CheckIMCForWindow` as `User32CanSetImeWindowToImc`.
- Improve `ImeWnd_OnCreate` function.
> [USER32] Implement WM_IME_SELECT and WM_IME_COMPOSITION of IME window

- win32ss/user/ntuser/metric.c
- Add `UserIsDBCSEnabled` helper function.
- Support `SM_DBCSENABLED` value of `GetSystemMetrics` function.
WinXP (Japanese):
Win2k3 (English):
ReactOS (English):
ReactOS (Japanese):
> [NTUSER] Implement GetSystemMetrics.SM_DBCSENABLED

- base/applications/mspaint/history.cpp
- base/applications/mspaint/history.h
- base/applications/mspaint/imgarea.cpp
- base/applications/mspaint/imgarea.h
- base/applications/mspaint/mouse.cpp
- base/applications/mspaint/palette.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/selection.h
- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/selectionmodel.h
- base/applications/mspaint/toolsettings.cpp
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/toolsmodel.h
- base/applications/mspaint/winproc.cpp
Fix and improve mspaint UI/UX.
JIRA issue: [CORE-17969](https://jira.reactos.org/browse/CORE-17969)
- Fix Undo/Redo mechanism.
- Finish drawing when the tool is to be chanaged and when the file is to be saved.
- Add `ToolBase::OnFinishDraw` to virtualize finishing drawing.
- Extend `bClearRedo` parameter to `ImageModel::Undo`.
- Add `ImageModel::DrawSelectionBackground` and `ImageModel::DeleteSelection` methods.
- Fix some `WM_PAINT` message handling.
> [MSPAINT] Improve Undo/Redo and finishing tool

- win32ss/user/user32/CMakeLists.txt
- win32ss/user/user32/controls/edit.c
- win32ss/user/user32/windows/defwnd.c
Reduce binary size.
- Don't directly call the `IMM32` functions. Use `IMM_FN` instead.
- Modify `CMakeLists.txt` to unlink `imm32.dll`.
BEFORE:
1,553,920 bytes.
AFTER:
1,552,384 bytes.
`1,552,384 - 1,553,920 == -1536 bytes.`
> [USER32] Don't delay-load-link to imm32.dll

- sdk/include/ddk/immdev.h
- sdk/include/psdk/imm.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/simplecall.c
- win32ss/user/user32/misc/imm.c
- Modify `NtUserSetImeOwnerWindow` prototype.
- Add `User32GetTopLevelWindow` function.
- Add `ImeWnd_OnImeSetContext` function.
- Implement `WM_IME_SETCONTEXT` message handling of the IME window.
> [USER32] Implement ImeWnd_OnImeSetContext

- dll/ntdll/def/ntdll.spec
- dll/win32/kernel32/client/heapmem.c
- dll/win32/kernel32/kernel32.spec
- sdk/include/ndk/rtlfuncs.h
- sdk/lib/rtl/heap.c
Minor update, to be consistent.
- [NDK][NTDLL][RTL] RtlCreateTagHeap(): Fix types and annotations
- [KERNEL32] HeapCreateTagsW(): Sync' types and add annotations
> [REACTOS] RtlCreateTagHeap() and HeapCreateTagsW(): Fix types and annotations

- win32ss/user/ntuser/main.c
- win32ss/user/ntuser/window.h
PR #4334 introduced Window List. This PR deletes the window lists that are no longer needed at the end of the thread / process.
- Cleanup the window lists that are no longer needed at the thread / process termination.
> [NTUSER] Cleanup window lists on thread/process exit

- win32ss/user/ntuser/ime.c
- Define "the special virtual keys for Japanese".
- Add `UserSetImeConversionKeyState` helper function.
- Implement `NtUserNotifyIMEStatus` function.
> [NTUSER] Implement NtUserNotifyIMEStatus

- dll/win32/kernel32/client/console/console.c
- dll/win32/kernel32/client/console/init.c
- dll/win32/kernel32/client/thread.c
- dll/win32/kernel32/include/console.h
- modules/rostests/apitests/kernel32/ConsoleCP.c
- sdk/include/reactos/subsys/win/conmsg.h
- win32ss/user/winsrv/concfg/font.h
- win32ss/user/winsrv/consrv/console.c
For a given non-unicode display code page, the console may not support showing the characters of the corresponding character set, if no suitable monospace font is available.
(For example, this is especially true in CJK ReactOS installations where no default _monospace_ font with CJK characters is installed; one needs an external fonts pack. But this observation is not limited to ReactOS.)
In this case, the console may change the code page to a default one. Or it may not, and might instead keep the code page, even if the selected font does not fully support displaying the corresponding characters.
On the other hand, a suitable font may exist and the console would keep the output code page.
In any of these cases, it is advisable that the console also tells which language it advises to be …
> Sync thread's language/locale with console's preferred language

- dll/cpl/console/console.c
- dll/cpl/console/font.c
- win32ss/user/winsrv/concfg/font.c
- win32ss/user/winsrv/concfg/font.h
- win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
- win32ss/user/winsrv/consrv/frontends/gui/guisettings.c
- win32ss/user/winsrv/consrv/frontends/gui/guisettings.h
- win32ss/user/winsrv/consrv/frontends/gui/guiterm.c
- win32ss/user/winsrv/consrv/frontends/gui/guiterm.h
When changing the console output code page, check whether the current
font can support it. If not, try to find a suitable font for the new
code page. If none can be found:
- if we are creating a new console, forcefully switch to codepage 437
(OEM USA) and retry finding a font, falling back to "Terminal" if
none could be found;
- if we were just changing the current CP, just fail and keep the old
code page and font.
Rework the console font selection/creation functions for this new job
(see CreateConsoleFontEx() and friends). Elements of implementation
based from https://github.com/microsoft/terminal ; see code for more
information.
JIRA issue: [CORE-17601](https://jira.reactos.org/browse/CORE-17601), [CORE-17803](https://jira.reactos.org/browse/CORE-17803), …
> Use a suitable font when changing console output CP; fail if none found.

- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- Modify `NtUserCheckImeHotKey` prototype.
- Add `IntGetImeHotKeyLanguageScore`, `IntGetActiveKeyboardLayout`, `IntGetImeHotKeyByKey`, and `IntCheckImeHotKey` helper functions.
- Implement `NtUserCheckImeHotKey` function.
> [NTUSER] Implement NtUserCheckImeHotKey

- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- win32ss/include/ntuser.h
- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/misc.c
- Use newly-defined `Imm32CurrentPti()` instead of `NtCurrentTeb()->Win32ThreadInfo`.
- `THREADSTATE_GETTHREADINFO` is same as `THREADSTATE_UNKNOWN18`.
- Use the paged pool to allocate `HIMC` rather than heap.
- Fix and improve `ImmDestroyContext` function.
> [NTUSER][IMM32] Use Imm32CurrentPti and pool

- base/applications/mspaint/dib.cpp
- base/applications/mspaint/dib.h
- base/applications/mspaint/history.cpp
- base/applications/mspaint/main.cpp
- base/applications/mspaint/selection.cpp
- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/selectionmodel.h
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/winproc.cpp
JIRA issue: [CORE-16634](https://jira.reactos.org/browse/CORE-16634)
- Add `Rotate90DegreeBlt` function to `dib.cpp`.
- Implement `ImageModel::RotateNTimes90Degrees` and `SelectionModel::RotateNTimes90Degrees`.
- Improve `ToolsModel::SetBackgroundTransparent`.
- Extend and improve `SelectionModel::InsertFromHBITMAP`.
Always selecting the bitmap object is bad design. Our source is cursed. Two DCs can't select the same bitmap at once.
> [MSPAINT] Implement canvas rotation

- win32ss/user/user32/controls/static.c
JIRA issue: [CORE-17315](https://jira.reactos.org/browse/CORE-17315)
Import Wine Commit 0ba1bfb0624d5e95f15499d6cfc9af1910c7c5be by Marcus
Meissner: user32: DrawText gets a 32bit flag, not a 16bit flag.
Fixes CORE-17315 - spottted by I_Kill_Bugs
> [USER32] Use UINT as parameter for Drawtext()

- win32ss/user/ntuser/scrollbar.c
This ensure we do not rely on usermode for always passing this flag in,
which is a ReactOS specific flag.
Thanks to Doug Lyons for finding the source of the problem.
JIRA issue: [CORE-17780](https://jira.reactos.org/browse/CORE-17780)
> [WIN32SS] Store the scrollbar theming enabled flag in the scrollbar

- win32ss/gdi/ntgdi/dclife.c
Remove useless `ASSERT(FALSE);` in `IntGdiCreateDisplayDC`, because it actually does not check anything useful. It only asserts each time when the function is called from `DxEngCreateMemoryDC` by MS DirectDraw stack (ddraw.dll & dxg.sys).
`UNIMPLEMENTED` debug print is enough a lot to see that this function is not implemented properly.
**This function does not play the major role for DirectDraw and Direct3D at least. It does properly the main thing which it should do - DC is creating successfully. So its current implementation is enough for this case. The bug with running in fullscreen mode is caused by another code.**
JIRA issue: [CORE-17561](https://jira.reactos.org/browse/CORE-17561)
As result, the DirectDraw and Direct3D acceleration is now working properly with MS ddraw.dll, …
> [WIN32SS][NTGDI] Remove useless assert

- dll/win32/imm32/utils.c
- win32ss/user/ntuser/ime.c
`imm32.ValidateHandleNoErr` is an important function to get the object pointer from a handle. It was not working.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-18049](https://jira.reactos.org/browse/CORE-18049)
- Add `DesktopPtrToUser` helper function.
- Fix `imm32.ValidateHandleNoErr` function.
- Use `DesktopHeapAlloc` to allocate the IMC, instead of `ExAllocatePoolWithTag`.
- Use `DesktopHeapFree` to free the IMC, instead of `ExFreePoolWithTag`.
> [NTUSER][IMM32] Fix ValidateHandleNoErr

- win32ss/user/ntuser/winpos.c
If a Rebar window is altered by calling either ShowWindow() or UpdateWindow()
then we were only updating the parent and omitting their children windows.
This is closer to the behavior of the very very old SVN r27394 == git f1a7f30887ac02e9a6c6605d0409af2618771154 .
And therefore intentionally excludes parts of SVN r27403 == git e2651a0dbc4d98dbda0d87746b87bd9575fb4f4c .
The bots have no complaints about it:
KVM https://reactos.org/testman/compare.php?ids=81266,81290
VBox https://reactos.org/testman/compare.php?ids=81267,81291
JIRA issue: [CORE-12342](https://jira.reactos.org/browse/CORE-12342)
> [NTUSER] Fix Toolbar re-painting when Rebar parent has been altered.

- drivers/wdm/audio/drivers/ac97/ac97.inf
This driver might work with all Intel AC'97 audio controllers. So far I tested it successfully on 82801FBM (ICH6-M).
> [AC97] Enable on all Intel AC'97 audio controllers

- dll/win32/shell32/wine/shellpath.c
Adding the `CSIDL_FLAG_NO_ALIAS` flag to `SHGetSpecialFolderLocation` should return the physical PIDL.
JIRA issue: [CORE-18079](https://jira.reactos.org/browse/CORE-18079)
BEFORE:
AFTER:
> [SHELL32] Support CSIDL_FLAG_NO_ALIAS

- sdk/lib/atl/atlsync.h
Add `atlsync.h` to use ATL synchronization feature.
- Add `atlsync.h` and implement `CCriticalSection`, `CEvent`, `CMutex` and `CSemaphore` classes.
> [ATL] Add atlsync.h

- drivers/network/dd/netkvm/Common/ParaNdis-Common.c
- drivers/network/dd/netkvm/Common/ParaNdis-Debug.c
- drivers/network/dd/netkvm/Common/ndis56common.h
Fix a bugcheck on checked build of Windows.
> [NETKVM] Fix calling convention for callback and variadic functions

- base/system/winlogon/sas.c
Changing this because the current beep might be annoying, specifically on real hardware with loud PC speaker and mostly because it's just too long. Win2k3 one is much shorter and a bit easier on ears (in my opinion).
> [WINLOGON] Make PC Speaker "beep" similar to Windows 2003 one

- base/applications/rapps/installed.cpp
- base/applications/rapps/misc.cpp
- 'WindowsInstaller' setups do not fill the UninstallString and ModifyPath with the needed info, so manually calculate those.
- Fix the case where REG_EXPAND_SZ is used instead of REG_SZ
- Take NoModify into account
> [RAPPS] Fix uninstalling applications

- ntoskrnl/io/iomgr/deviface.c
Always create only non-volatile (sub)keys when registering a new device interface, so then they are saved after reboot.
On Windows, nearly all device interface keys are non-volatile, except the "Control" subkey, which is managed by `IoSetDeviceInterfaceState` instead.
In particular, it fixes MS sysaudio loading failure with MS audio drivers replacement (ks, portcls, swenum, sysaudio, wdmaud). My `IoGetDeviceInterfaceAlias` implementation from #3510 is also required to be applied. MS sysaudio implementation(s) except that those keys are non-volatile (but we're creating them volatile instead), and trying to create a subkey(s) there (via other IoDeviceInterface* routines), to read/write some needed data. But then they fail to do that with `STATUS_CHILD_MUST_BE_VOLATILE` (`0xc0000181`), …
> [NTOS:IO] IoRegisterDeviceInterface: create non-volatile keys for new device interfaces

- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
I had confirmed the name of `pImmHeap` on WinDBG, but @HBelusca thinks it's bad name. Renaming correctly...
- Rename `pImmHeap` as `ghImmHeap`.
> [IMM32] Renaming: s/pImmHeap/ghImmHeap/

- dll/win32/imm32/candidate.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- `s/Imm32WriteRegIme/Imm32WriteImeLayout/` --> `Win: WriteImeLayout`
- `s/Imm32GetRegImes/Imm32GetImeLayout/` --> `Win: GetImeLayout`
- `s/Imm32GetNextHKL/Imm32AssignNewLayout/` --> `Win: AssignNewLayout`
- `s/Imm32NotifyAction/Imm32MakeIMENotify/` --> `Win: MakeIMENotify`
- `s/Imm32CopyFile/Imm32CopyImeFile/` --> `Win: CopyImeFile`
> [IMM32] Renaming about IME layout

- dll/win32/imm32/candidate.c
- dll/win32/imm32/compstr.c
- dll/win32/imm32/guideline.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/keymsg.c
- Add `Win:` comments for A/W worker functions.
- Renaming: `s/Imm32SetCompositionStringAW/ImmSetCompositionStringAW`
- Renaming: `s/Imm32GetImeMenuItemsAW/ImmGetImeMenuItemsAW/`
- Renaming: `s/Imm32RequestMessageAW/ImmRequestMessageAW/`
- `ImmGetCandidateListAW` --> `Win: ImmGetCandidateListWorker`
- `ImmGetCandidateListCountAW` --> `Win: ImmGetCandidateListCountWorker`
- `ImmGetGuideLineAW` --> `Win: ImmGetGuideLineWorker`
- `ImmGetImeMenuItemsAW` --> `Win: ImmGetImeMenuItemsWorker`
- `ImmIsUIMessageAW` --> `Win: ImmIsUIMessageWorker`
- `ImmSetCompositionStringAW` --> `Win: ImmSetCompositionStringWorker`
- `ImmRequestMessageAW` --> `Win: ImmRequestMessageWorker`
> [IMM32] Renaming: worker functions

- dll/win32/imm32/compstr.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/utils.c
Improve debuggability by adding Windows-side information.
- `LogFontWideToAnsi` --> `Win: LFontWtoLFontA`
- `LogFontAnsiToWide` --> `Win: LFontAtoLFontW`
- `Imm32GetCompStrA` --> `Win: InternalGetCompositionStringA`
- `Imm32GetCompStrW` --> `Win: InternalGetCompositionStringW`
- `Imm32LoadImeVerInfo` --> `Win: LoadVersionInfo`
- `Imm32GetSystemLibraryPath` --> `Win: InternalGetSystemPathName`
- `Imm32UIntToStr` --> `Win: UIntToStr`
- `Imm32ProcessHotKey` --> `Win: HotKeyIDDispatcher`
> [IMM32] Add more 'Win:' comments

- sdk/cmake/msvc.cmake
Function-level-Linking '/Gy' is already enabled unconditionally
at line 26. So no need to enable it here another time.
Makes the differences between the multiple OPTIMIZE-levels more obvious.
> [CMAKE] msvc.cmake: Remove redundant '/Gy'

- base/services/seclogon/precomp.h
- base/services/seclogon/rpcserver.c
- base/services/seclogon/seclogon.c
- base/services/svchost/globals.c
- base/services/svchost/rpcsrv.c
- base/services/svchost/svchost.c
- base/services/svchost/svchost.h
- dll/win32/mswsock/stubs.c
- sdk/include/reactos/svc.h
[SDK:REACTOS][SVCHOST] Following commit 24a727a23, give a lift to the SVCHOST global header and add & complete all the missing definitions.
- Based on https://www.geoffchappell.com/studies/windows/win32/services/svchost/process/globaldata.htm
from public debug symbols (e.g. svchost, mswsock, w32time, wscsvc...),
adjust some of our symbols' names.
- Make the header C++-compatible.
- Even if the start/stop RPC server functions return an error code whose
underlying storage type is a 32-bit long, they don't return an RPC
status error code, but an NT status. Thus, use the adequate type
instead.
- The PSVCHOST_STOP_CALLBACK is nothing but a WAITORTIMERCALLBACK function.
- Take the opportunity to fix some of these functions' SAL annotations.
- Remark: "LP" for pointers is old-fashioned Windows, …
> Lift the SVCHOST global header and add & complete all the missing definitions.

- sdk/lib/drivers/ntoskrnl_vista/CMakeLists.txt
- sdk/lib/rtl/CMakeLists.txt
- sdk/lib/rtl/runonce.c
- sdk/lib/rtl/utf8.c
The reason is that both RtlUTF8ToUnicodeN() and RtlUnicodeToUTF8N() are
exported in both kernel and user-mode (ntdll) in Windows 7+. They are not
limited to the kernel only.
References:
https://www.geoffchappell.com/studies/windows/km/ntoskrnl/history/names61.htm
https://www.geoffchappell.com/studies/windows/win32/ntdll/history/names61.htm
Conversion from and to UTF8 are fundamental enough that they indeed
deserve to be in a separate file.
> Move the RTL UTF8 functions to the main RTL library, to be linked in the rtl_vista target.

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/window.c
- Add 'Win:' comments to clarify the Windows-side function names.
> [NTUSER] Add 'Win:' comments to ime.c and window.c

- dll/win32/imm32/imm.c
- Rename `Imm32InitInstance` as `ImmInitializeGlobals`.
- Add `Win:` comments.
> [IMM32] Renaming: s/Imm32InitInstance/ImmInitializeGlobals/

- dll/win32/winhttp/CMakeLists.txt
JIRA issue: [CORE-18104](https://jira.reactos.org/browse/CORE-18104)
Fixes
Creating library dll\win32\winhttp\winhttp.lib and object dll\win32\winhttp\winhttp.exp
LINK : warning LNK4199: /DELAYLOAD:ole32.dll ignored; no imports found from ole32.dll
which I could observe all the way from releases/0.4.7 up to releases/0.4.14
would like to have a review of ThFabba, who added that import 10 years ago via:
ae0056953a4926121b2f063e846fc627b6fd691c == SVN r56891
I double-checked with MSDepends: Neither 2k3sp2 nor XPSP3 do have that direct delayedImport of OLE32.
> [WINHTTP] Fix 1 MSVC x86 warning LNK4199

- sdk/lib/drivers/ntoskrnl_vista/CMakeLists.txt
Fix GCC AMD64 build, following commit 6f559e9c5.
Problem only arises on GCC AMD64 build bot and is:
```
FAILED: drivers/filesystems/nfs/nfs41_driver.sys 
: && /home/runner/work/reactos/reactos/RosBE-CI/amd64/bin/x86_64-w64-mingw32-gcc   -nostdlib
<-- stripped -->
&& /home/runner/work/reactos/reactos/build/host-tools/bin/pefixup --kernelmodedriver /home/runner/work/reactos/reactos/build/drivers/filesystems/nfs/nfs41_driver.sys
/home/runner/work/reactos/reactos/RosBE-CI/amd64/lib/gcc/x86_64-w64-mingw32/8.4.0/../../../../x86_64-w64-mingw32/bin/ld:
sdk/lib/rtl/CMakeFiles/rtl_vista.dir/utf8.c.obj: in function `RtlUnicodeToUTF8N':
/sdk/include/crt/mingw32/intrin_x86.h:76: undefined reference to `memcpy'
collect2: error: ld returned 1 exit status
```
Notice the rtl_vista library is included at …
> [SDK:NTOS_VISTA] Fix GCC AMD64 build. Addendum for commit 6f559e9c5.

- dll/win32/shell32/wine/control.c
In MS Windows all control panel applets are single instance applications. This prevents the collision of multiple accesses to the configuration data.
Jira tickets: [CORE-7921](https://jira.reactos.org/browse/CORE-7921), [CORE-17025](https://jira.reactos.org/browse/CORE-17025)
Before start of the applets, is now searched the dialog window of the preinstance. If the search is successful, this dialog is brought to the foreground and a second instance not started.
Supersedes #4404.
> [SHELL32] Make Control Panel applets start in single instance

- hal/halx86/CMakeLists.txt
- hal/halx86/acpi.cmake
- hal/halx86/acpi/madt.c
- hal/halx86/apic/halinit.c
- hal/halx86/include/smp.h
- hal/halx86/legacy.cmake
- hal/halx86/smp.cmake
- hal/halx86/smp/mps/mps.c
- hal/halx86/smp/smp.c
Parse the MADT tables and make then usable across the APIC/SMP Hal(s).
- Parse the MADT tables for the number of Local APICs in the system and those IDs.
- Use the ACPICA headers to gather the information.
- Give all the APIC Hals the ability to use the information in a custom structure.
- Add a helper function for getting a pointer to the PRCB of every processor in the system and assign it to the struct above
- Make this work in a way that can be easily integrated with the MPS Hal(s).
> [HALX86] Parse the MADT tables and make then usable across the APIC/SMP Hal(s)

- dll/win32/imm32/ime.c
- Rename `Imm32FreeImeDpi` as `Imm32UnloadIME`.
- Add `Win:` comment.
> [IMM32] Renaming: s/Imm32FreeImeDpi/Imm32UnloadIME/

- dll/win32/shell32/shlfileop.cpp
- sdk/include/psdk/winbase.h
JIRA issue: [CORE-18089](https://jira.reactos.org/browse/CORE-18089)
> [SHELL32] Copy without FILE_ATTRIBUTE_READONLY from a CDROM

- sdk/tools/winesync/winesync.py
Encountered when syncing msi,
there was a file deleted from the wine tree that was not present in the ReactOS tree.
> [WINESYNC] Fail gracefully when unable to delete a file

- dll/win32/imm32/candidate.c
- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
- Add many `Win:` comments.
- `s/Imm32UnloadIME/Imm32FreeIME/`
- `s/Imm32LoadImeInfo/Imm32LoadIME/`
- `s/g_hImm32Inst/ghImm32Inst/`
- `s/g_bClientRegd/gfImmInitialized/`
- `s/Imm32AllocAndBuildHimcList/Imm32BuildHimcList/`
- `s/Imm32SelectLayout/Imm32SelectInputContext/`
- `s/Imm32NotifyCompStrProc/Imm32NotifyIMEProc/`
> [IMM32] Many renamings and 'Win:' info

- hal/halx86/acpi.cmake
This also removes the following warnings, that were present because,
as the ACPICA acpi.h header was used as PCH (instead of none, or the
hal's own main header), it was "included" before any other header
-- and in particular, before hal.h -- and as a result, colliding defines
were still defined even if the #undef tricks were used for them.
```
rosbuilds\sdk\include\reactos\mc\bugcodes.h(1417): warning C4005: 'ACPI_BIOS_ERROR': macro redefinition
reactos\drivers\bus\acpi\acpica\include\acoutput.h(243): note: see previous definition of 'ACPI_BIOS_ERROR'
reactos\hal\halx86\include\hal.h(41): warning C4109: unexpected identifier '_read'
reactos\hal\halx86\include\hal.h(42): warning C4109: unexpected identifier '_read'
```
> [HALX86:ACPI] Use the correct PCH file for compilation.

- win32ss/user/ntuser/win32.h
Remove incorrect packing specification around _TL, _WIN32THREAD and _THREADINFO structures.
JIRA issue: [CORE-18140](https://jira.reactos.org/browse/CORE-18140)
This was introduced historically in commit 583de66b3 (r7460) to
workaround some compiler problems (or replace already existing
GCC-specific `__attribute__((packed))` annotations); however these
structures are in-memory-only, do not describe any on-disk data
format and don't describe hardware-specific data. So they should
have the "natural" alignment of the target platform.
They also have to match the documented layouts at:
https://reactos.org/wiki/Techwiki:Win32k/THREADINFO
https://www.geoffchappell.com/studies/windows/km/win32k/structs/threadinfo/index.htm
at least for the compatible parts that ReactOS shares.
> [WIN32K] Remove incorrect packing specification around _TL, _WIN32THREAD and _THREADINFO structures.

- win32ss/include/ntuser.h
- Add `C_ASSERT` assertions on the offsets of the members of `IMC` structure.
> [NTUSER][INCLUDE] Add IMC offset info

- win32ss/user/ntuser/ime.c
- Make the return value of `IntDestroyInputContext` a `BOOL`.
- Make the first paramter of `IntDestroyInputContext` a `PIMC`.
> [NTUSER] Simplify IntDestroyInputContext

- win32ss/user/ntuser/ime.c
`UserCreateInputContext(0);` can be called multiple times in the process because the thread(s) in the process can be multiple.
- Dereference `pti->spDefaultImc` by `UserDereferenceObject` if `pti->spDefaultImc` is `NULL` at `UserCreateInputContext` function.
> [NTUSER] Dereference spDefaultImc at UserCreateInputContext

- sdk/cmake/msvc.cmake
C4090: different 'modifier' qualifiers
Follow-up to 42d2d5e (0.4.14-dev-847) and 41bc57d (0.4.15-dev-2952),
which silenced affected modules.
> [CMAKE] msvc.cmake: Enable C4090 warning as error

- modules/rostests/apitests/imm32/himc.c
- win32ss/user/ntuser/window.c
- Set the default input context to `WND` at `IntCreateWindow` function.
- Add more tests to the `himc` testcase of `imm32_apitest`.
> [NTUSER][IMM32_APITEST] Associate HIMC to WND

- win32ss/CMakeLists.txt
- win32ss/gdi/eng/device.c
- win32ss/gdi/eng/device.h
- win32ss/gdi/eng/engbrush.c
- win32ss/gdi/eng/ldevobj.c
- win32ss/gdi/eng/ldevobj.h
- win32ss/gdi/eng/mdevobj.c
- win32ss/gdi/eng/mdevobj.h
- win32ss/gdi/eng/multidisp.c
- win32ss/gdi/eng/pdevobj.c
- win32ss/gdi/eng/pdevobj.h
- win32ss/gdi/eng/stubs.c
- win32ss/gdi/ntgdi/dclife.c
- win32ss/gdi/ntgdi/device.c
- win32ss/gdi/ntgdi/gdidbg.c
- win32ss/user/ntuser/display.c
- win32ss/user/ntuser/metric.c
- win32ss/user/ntuser/tags.h
- win32ss/user/ntuser/win32kdebug.h
- win32ss/user/ntuser/windc.c
- win32ss/user/ntuser/winsta.c
- win32ss/win32kp.h
Preparatory work to handle multiple displays.
- rework loading/unloading of graphic display drivers to not tie PDEVOBJ creation and using graphics display driver
- introduce MDEVOBJ structure, to keep a list of currently enable displays
- add a way to load "internal" drivers, ie drivers with entrypoint in win32k
- add a stub for multidisplay driver, which always returns failure
- invoke multidisplay driver when having more than one display
- when enumerating display settings (with desk.cpl), the display settings list is refreshed at each mode query. Try to refresh this list only when required?
- UserChangeDisplaySettings needs to call PDEVOBJ_lChangeDisplaySettings
- implement the multidisplay driver
> Preparatory work for multidisplay

- win32ss/user/user32/include/user32p.h
- win32ss/user/user32/misc/dllmain.c
- win32ss/user/user32/misc/imm.c
- Add many `Win:` comments to `misc/imm.c`.
- Rename `GetImmFileName` as `User32GetImmFileName`.
- Rename `bImmInitializing` as `gbImmInitializing`.
- Rename `gnImmUnknownFlag1` as `gfConIme`.
- Formating `UpdatePerUserImmEnabling` code.
> [USER32] Add 'Win:' info to misc/imm.c

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/main.c
- win32ss/user/ntuser/object.c
- win32ss/user/ntuser/object.h
According to JIRA user simonelombardo, there was crash in exiting a thread.
JIRA issue: [CORE-18044](https://jira.reactos.org/browse/CORE-18044)
- Add `UserAssignmentLock`, and `UserAssignmentUnlock` helper functions.
- Lock and unlock `pti->spDefaultImc` by using those helper functions.
> [NTUSER] Do assignment lock pti->spDefaultImc

- win32ss/user/ntuser/callback.c
- win32ss/user/ntuser/ime.c
- Use `UserAssignmentLock` in `NtUserSetThreadLayoutHandles`.
- Add `Win:` comments to many functions.
- Rename `glcid` as `glcidSystem`.
> [NTUSER] Do assignment lock at NtUserSetThreadLayoutHandles

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/window.c
- win32ss/user/ntuser/window.h
- Add `IntFindNonImeRelatedWndOfSameThread`, `IntImeCanDestroyDefIMEforChild`, and `IntImeCanDestroyDefIME` helper functions.
- Do assignment unlock `spwndDefaultIme` at `co_UserFreeWindow` function.
- Destroy the default IME window of the specified window if necessary at `co_UserDestroyWindow` function.
> [NTUSER] Destroy the default IME window

- modules/rostests/apitests/imm32/himc.c
- Display the window class name on failure of `CreateWindow` function call.
> [IMM32_APITEST] himc: Show class on CreateWindow failure

- dll/win32/imm32/ime.c
- dll/win32/imm32/imm.c
- dll/win32/imm32/keymsg.c
- dll/win32/imm32/precomp.h
- dll/win32/imm32/utils.c
`imm32_winetest` expects some OS error code. Setting it properly...
- Set the last error on failure of handle validation.
> [IMM32] Add ValidateHandle function

- .github/workflows/build.yml
Fix the MSVC build workers.
JIRA issue: [CORE-18146](https://jira.reactos.org/browse/CORE-18146)
```
[GITHUB] Use the correct worker to get MSBuild VS2019 working. (#4454)
CORE-18146
```
```
[GITHUB] Fix MSVC 2015 (v14.0) build, until a clear consensus is reached for PR #3872 (#4454)
CORE-18146
Use the matrix.os + include/exclude technique, as suggested
by Serge Gautherie :)
```
NOTE: aminya's msvc-dev-cmd fork (`aminya/msvc-dev-cmd@vs-version`)
supports providing an explicit VS version for vswhere, via the `vsversion` property,
thus not having to always get the latest VS.
> [GITHUB] Use the correct worker to get MSBuild VS2019 working.

- subsystems/win32/csrsrv/procsup.c
When increasing the base priority at shutdown, acquire the necessary
SE_INC_BASE_PRIORITY_PRIVILEGE in CsrSetToShutdownPriority(),
called by CsrShutdownProcesses(), which is necessary due to the increase
of process base priority (i.e. increase of scheduling) being done.
Dedicated to George Bișoc :)
The Shutdown privilege is however unnecessary (or unwanted) since this
has been already dealt with by the shutdown caller. Also, it will be
needed only by the caller of NtShutdownSystem() -- that we don't call
at all here.
> [CSRSRV] Acquire the necessary SE_INC_BASE_PRIORITY_PRIVILEGE at shutdown

- dll/win32/msvcrt/msvcrt.spec
Allows to enable software such like VLC under ReactOS 64 bits.
JIRA issue: [CORE-17666](https://jira.reactos.org/browse/CORE-17666)
- Activate them. Check if work as they should.
- Not in this pull request, but [CORE-17666](https://jira.reactos.org/browse/CORE-17666) needs the MSI to finish the install, that surely will need something else.
- Not in this PR, but  [CORE-18158](https://jira.reactos.org/browse/CORE-18158) msvcrt needs some fixes to go on.
> [MSVCRT] Enable _wfindfirst64 and _wfindnext64 in msvcrt.spec

- win32ss/user/ntuser/focus.c
Fix access violation on `IntFocusSetInputContext`.
JIRA issue: [CORE-18163](https://jira.reactos.org/browse/CORE-18163)
- Add locking on `pWndPrev`.
> [NTUSER] Add locking at IntSendFocusMessage

- ntoskrnl/include/internal/io.h
- ntoskrnl/io/pnpmgr/devaction.c
- ntoskrnl/io/pnpmgr/pnpirp.c
- ntoskrnl/io/pnpmgr/pnpmgr.c
Implement the correct start-stop sequence for resource rebalancing
without the actual rebalancing. Also move IoInvalidateDeviceState
processing into the enumeration thread as it should be.
Jira issue: [CORE-17519](https://jira.reactos.org/browse/CORE-17519)
> [NTOS:PNP] Halfplement IoInvalidateDeviceState

- ntoskrnl/io/pnpmgr/plugplay.c
```txt
/srv/buildbot/worker_data/Build_GCCLin_x86/build/ntoskrnl/io/pnpmgr/plugplay.c: In function 'IopInitializeDevice':
/srv/buildbot/worker_data/Build_GCCLin_x86/build/ntoskrnl/io/pnpmgr/plugplay.c:248:5: error: ignoring return value of 'RtlDuplicateUnicodeString', declared with attribute warn_unused_result [-Werror=unused-result]
RtlDuplicateUnicodeString(0, &DeviceInstance, &DeviceNode->InstancePath);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
- Get the return value of `RtlDuplicateUnicodeString` function call as `Status`.
- Output the error message if failed.
> [NTOS:PNP] Fix GCC build (ignoring return value)

- dll/win32/newdev/wizard.c
Observed behavior:
The Update Driver Wizard Dialog is not completely visible.
Part of the window is off the screen.
Expected behavior:
As in Windows XP the dialog box is positioned slightly below
and to the right of the parent window (Z order).
> [NEWDEV] Fix Update Driver Wizard Dialog position

- sdk/include/reactos/wine/test.h
_The winhttp:winhttp test was often crashing on wine_dbgstr_wn._
JIRA issue: [ROSTESTS-377](https://jira.reactos.org/browse/ROSTESTS-377)
_This brings most of Wine's current wine_dbgstr_wn code into ReactOS._
It is not possible to completely sync this to current Wine.
This is because there is Wine-specific code regarding "debug_info" and their TEB in remaining code.
I confirmed this with @ThFabba.
> [ROSTESTS] Fix crash in winhttp:winhttp regression test

- sdk/include/crt/mingw32/intrin_arm.h
Fix a little bug present on the CRT, located with a cegcc compiler under ReactOS Build Environment (for more info, visit http://max.kellermann.name/projects/cegcc/ ), little MinGW intrin_arm.h that is making an error, thanks to @HBelusca.
``` ../sdk/include/crt/mingw32/intrin_arm.h:44:32: error: '<<' in boolean context, did you mean '<' ? [-Werror=int-in-bool-context] ```
- Well, it's cegcc and arm... So surely more bugs will be encountered.
> [CRT] Fix MinGW-arm intrin minor bug

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/object.c
Fix the `HIMC` handle leak.
- `UserDestroyInputContext` always returns `TRUE`.
- Don't call `UserMarkObjectDestroy` in `UserDestroyInputContext`.
> [NTUSER] Fix UserDestroyInputContext (again)

- win32ss/user/ntuser/ime.c
Fix hung-up.
- Add call of `UserMarkObjectDestroy`.
> [NTUSER] Fix UserDestroyInputContext (again and again)

- win32ss/gdi/gdi32/objects/gdiobj.c
Fix latest gdi32:GetObject:
ok_long(GetObjectA(hBrush, 0, &TestStruct), 0);
https://git.reactos.org/?p=reactos.git;a=blob;hb=680f103f3d52bf46b41eb5249c17d097ac55a3c2;f=modules/rostests/apitests/gdi32/GetObject.c#l162
[gdiobj.c]
::GetObjectW::
- When "cbSize" is "0", GetObjectW shouldn't return "sizeof(LOGBRUSH)" but 0.
- Rely in BRUSH::cjGetObject behavior which returns 0 when cjSize is 0.
> Fix last gdi32:GetObject testcase

- dll/win32/browseui/browseui.spec
- dll/win32/browseui/desktopipc.cpp
- dll/win32/browseui/parsecmdline.cpp
- modules/rostests/apitests/browseui/SHExplorerParseCmdLine.c
- sdk/include/reactos/browseui_undoc.h
NB:
Major drop in executed checks, simply as `Padding` is commented out.
JIRA issue: [ROSTESTS-302](https://jira.reactos.org/browse/ROSTESTS-302)
Cc @katahiromz
> [BROWSEUI][BROWSEUI_APITEST] SHExplorerParseCmdLine(): Sync and improve

- win32ss/include/ntuser.h
- win32ss/user/ntuser/window.c
- win32ss/user/user32/windows/mdi.c
- win32ss/user/user32/windows/window.c
Fix hung-up and memory leaks.
JIRA issue: [CORE-18173](https://jira.reactos.org/browse/CORE-18173)
- Modify the prototype of `NtUserBuildHwndList` function.
- Wrap the code by `UserEnterExclusive();` and `UserLeave();`.
- Fix calling of `NtUserBuildHwndList` in `user32.dll`.
> [NTUSER][USER32] Make NtUserBuildHwndList exclusive

- win32ss/user/ntuser/window.c
A follow-up to #4485 (c2a51c7).
JIRA issue: [CORE-18173](https://jira.reactos.org/browse/CORE-18173)
- Use correct NTSTATUS values for return.
> [NTUSER] NtUserBuildHwndList should return NTSTATUS

- dll/win32/shell32/folders/CControlPanelFolder.cpp
- dll/win32/shell32/folders/CDrivesFolder.cpp
- dll/win32/shell32/folders/CFSFolder.cpp
- dll/win32/shell32/folders/CRegFolder.cpp
Adjust column sequence in folder view to match WinXP and Win2k3 order.
JIRA issue: [CORE-11846](https://jira.reactos.org/browse/CORE-11846)
**Before:**
**After:**
**Win2k3:**
**WinXP:**
> [SHELL32] Folders: Adjust column sequence in details view

- dll/win32/shell32/CDefView.cpp
- dll/win32/shell32/CDefaultContextMenu.cpp
- dll/win32/shell32/droptargets/CRecyclerDropTarget.cpp
_Fixes to shell32 files to allow permanent deletion using shift-delete._
JIRA issue: [CORE-17802](https://jira.reactos.org/browse/CORE-17802)
> [SHELL32] Fix Shift-Delete to Permanently Delete Files and Folders

- win32ss/user/ntuser/object.c
_Add memory allocation for CF_DIB formatted data on clipboard_
JIRA issue: [CORE-17318](https://jira.reactos.org/browse/CORE-17318)
> [WIN32SS] Fix CF_DIB format not being saved to clipboard on Print Screen key

- modules/rostests/apitests/shell32/ShellExecCmdLine.cpp
- modules/rostests/apitests/shell32/ShellExecuteEx.cpp
This design, introduced in 418edcd2b, is fundamentally flawed as it
can also close windows unrelated to the running test (e.g. windows
of programs that the user can start, while the test is running).
But since we cannot do much better, mitigate instead the other main
problem of this design: Just use PostMessageW(WM_CLOSE), as it used
to be, instead of TerminateProcess().
Indeed, using TerminateProcess() otherwise could kill unrelated
processes the test hasn't created. In particular it could kill the
csrss.exe system process if, during the testing procedure, a hard-error
popup shows up.
And this is precisely the case when this test runs with limited memory,
and a hard-error
"Insufficient system resources exist to complete the requested service."
arises.
Effectively partly revert commit …
> [SHELL32_APITEST] ShellExecCmdLine: Do **NOT** use TerminateProcess to close the opened windows.

- drivers/bus/pcix/init.c
- drivers/bus/pcix/utils.c
Match `Zw*()` uses.
JIRA issue: [CORE-10207](https://jira.reactos.org/browse/CORE-10207)
> [PCIX] Add 2 OBJ_KERNEL_HANDLE

- base/system/winlogon/security.c
- win32ss/user/ntuser/desktop.c
- win32ss/user/ntuser/security.c
- win32ss/user/ntuser/security.h
The problem ReactOS currently faces is this -- whenever the desktop is being parsed we aren't assigning a security descriptor to it. As a matter of fact when Winlogon tries to assign new security information to the application desktop when a user logs in, Winlogon fails because no prior descriptor has been created for it even though we already do this when initializing security buffers in Winlogon.
With that said, we must assign a descriptor when parsing the desktop as well. This fixes a hack in Winlogon where security assigning of application desktop during a log in is disabled (which we can now enable such code path back).
> [WIN32K:NTUSER] Assign a security descriptor when parsing the desktop

- dll/win32/shell32/wine/control.c
Adding the Control Panel applet to the taskbar caused a visual glitch in the installation wizard via the RunDLL window 
JIRA issue: [CORE-18175](https://jira.reactos.org/browse/CORE-18175)
Implemented a check if the parent window of RunDLL is the desktop to add the system control applet to the taskbar only if it is.
In case of a problem, the installer window is the parent window of RunDLL, so now the RunDLL window is not manipulated.
> [SHELL32] Fix of visual glitch problem after CORE-18137 shell32 fix

- dll/keyboard/kbdja/kbdja.c
The ReactOS Japanese keyboard could not use `VK_CONVERT`/`VK_NONCONVERT` keys. This PR will enable these two keys.
- ScanCode 121 (`0x79`) --> `VK_CONVERT`.
- ScanCode 123 (`0x7B`) --> `VK_NONCONVERT`.
> [KBDJA] Enable VK_CONVERT/VK_NONCONVERT keys

- dll/keyboard/kbdja/kbdja.c
Improve readability of Japanese keyboard.
- `SC_13` (`0xDE`) --> `VK_OEM_7`
- `SC_27` (`0xC0`) --> `VK_OEM_3`
- `SC_40` (`0xBB`) --> `VK_OEM_PLUS`
- `SC_41` (`0xBA`) --> `VK_OEM_1`
> [KBDJA] Delete temporary hacks

- dll/keyboard/kbdja/kbdja.c
- win32ss/user/ntuser/keyboard.c
Improve Japanese keyboard.
- Fix `scancode_to_vk` variable.
- Add special handling to `win32k!ProcessKeyEvent` function for Japanese.
> [KBDJA][NTUSER] Improve scancode_to_vk data

- ntoskrnl/mm/ARM3/section.c
If inserting the allocated VAD fails, MiMapViewOfDataSection will make no attempt to free the allocated VAD.
This PR should fix the leaking of memory in such situations.
> [NTOS:MM] Fix memory leak in MiMapViewOfDataSection

- ntoskrnl/se/acl.c
- ntoskrnl/se/sd.c
- ntoskrnl/se/token.c
Noticed by @JohnyTheCarrot while testing Google Chrome installation on ReactOS, where the contents of a `TOKEN`'s `DefaultDacl` gets corrupted.
The problem resides in the `SepPerformTokenFiltering()` helper function, where the `EndMem` pointer is changed to point to the dynamic part, before being used again later on on data that reside instead in the variable part of the token.
Example:
```
kd> ?? Token
struct _TOKEN * 0xe18cb8e0
+0x000 TokenSource      : _TOKEN_SOURCE
+0x010 TokenId          : _LUID
+0x018 AuthenticationId : _LUID
+0x020 ParentTokenId    : _LUID
+0x028 ExpirationTime   : _LARGE_INTEGER 0x7fffffff`ffffffff
+0x030 TokenLock        : 0xb85de878 _ERESOURCE
+0x038 AuditPolicy      : _SEP_AUDIT_POLICY
+0x040 ModifiedId       : _LUID
+0x048 SessionId        : 0
+0x04c …
```
> [NTOS:SE] Add extra sanitization and fix some bugs in token filtering.

- base/applications/rapps/installed.cpp
We want the datetime formated in local datetime independent from the source registry-key
_Show install time of software in RAPPS as localized datetime instead of YYYYDDMM formatted string_
JIRA issue: [CORE-17422](https://jira.reactos.org/browse/CORE-17422)
> [RAPPS] Add localized display of installation date and time

- modules/rostests/kmtests/CMakeLists.txt
- modules/rostests/kmtests/kmtest_drv/testlist.c
- modules/rostests/kmtests/ntos_ke/KeFloatPointState.c
- ntoskrnl/include/internal/i386/intrin_i.h
- ntoskrnl/include/internal/i386/ke.h
- ntoskrnl/include/internal/tag.h
- ntoskrnl/ke/i386/cpu.c
- sdk/include/reactos/mc/bugcodes.mc
On ReactOS we are merely doing a **FNSAVE** when saving the non-volatile data of floating point unit state, while on Windows it does a lot more than that.
FPU state saving is done thorough this rule -- check the NPX state of the current thread. If NPX is loaded then the mechanism grabs the NPX registers, otherwise the non-volatile data is obtained from NPX frame. Windows performs a `FNSAVE` or `FXSAVE` only if NPX state is loaded and that the FPU state context is being held in a pool allocation.
If the NPX interrupt level is no longer equal to the current interrupt level of the calling thread, it checks if the level in question is APC_LEVEL and if that's the case then from that moment memory pool is allocated to hold the FX save area, otherwise the said area is obtained from the current …
> [NTOS:KE] Fully implement FPU state Save/Restore mechanism

- dll/win32/kernel32/client/path.c
Previously there was no room reserved for the ULONG, only for a BYTE
> [KERNEL32] Fix reading SafeDllSearchMode

- sdk/include/asm/asm.inc
Should make tracking down issues like [CORE-17639](https://jira.reactos.org/browse/CORE-17639) easier
> [ASM x64] Fix UNIMPLEMENTED macro for MSVC

- hal/halx86/include/halp.h
- hal/halx86/legacy/bussupp.c
BEFORE:
```
00:01.1 IDE interface [0101]: Intel Corporation 82371AB/EB/MB PIIX4 IDE [8086:7111] (rev 01)
Subsystem: Unknown [0000:0000]
Flags: bus master, fast devsel, latency 0
I/O ports at d000 [size=4K]
```
AFTER:
```
00:01.1 IDE interface [0101]: Intel Corporation 82371AB/EB/MB PIIX4 IDE [8086:7111] (rev 01)
Subsystem: Unknown [0000:0000]
Flags: bus master, fast devsel, latency 0
I/O ports at d000 [size=16]
```
Note: 64-bit BARs are not supported yet.
> [HALX86] Print the correct size of the BAR in HalpDebugPciDumpBus()

- ntoskrnl/mm/ARM3/procsup.c
Fix MiInsertSharedUserPageVad to not charge the system process pool quota.
Even though PsChargeProcessNonPagedPoolQuota itself checks if the process specified is the system process, this doesn't work here as we're too early into boot for the kernel to know what the system process is.
> [NTOS:MM] Fix MiInsertSharedUserPageVad preventing boot on x64

- ntoskrnl/mm/ARM3/virtual.c
When an allocated VAD's insertion fails, the VAD is not freed. This commit attempts to fix this behaviour.
> [NTOS:MM] Fix memory leak in NtAllocateVirtualMemory

- drivers/bus/pci/fdo.c
- drivers/bus/pci/pci.c
- drivers/bus/pci/pci.h
- hal/halx86/generic.cmake
- hal/halx86/generic/kdpci.c
- hal/halx86/include/bus.h
- hal/halx86/legacy/bus/pcibus.c
- hal/halx86/pc98.cmake
- hal/halx86/xbox.cmake
This allows ROS to work with KD transport DLLs for PCI devices.
JIRA issue: [CORE-17360](https://jira.reactos.org/browse/CORE-17360)
- Add initial support for PCI debugging devices.
> [PCI][HALX86] Support PCI debugging devices

- win32ss/user/ntuser/simplecall.c
MFC42 applications only expect an IME window when on a DBCS system,
so they will capture this IME window as their 'main' window on non-DBCS systems.
JIRA issue: [CORE-18212](https://jira.reactos.org/browse/CORE-18212)
> [WIN32K] Conditionally enable IMM32

- sdk/include/crt/_mingw.h
- sdk/include/crt/mingw32/intrin.h
- sdk/include/crt/mingw32/intrin_x86.h
- sdk/include/crt/mmintrin.h
- sdk/include/crt/xmmintrin.h
This change implements all intrinsics in mmintrin.h (MMX) and xmmintrin.h (SSE)
Note: the previous GCC definition of __m128 was broken and didn't work.
It's preparation work for importing some SSE math functions for x64
* Implement all mmintrin.h/xmmintrin.h functions as inline wrappers around GCC/Clang builtins
* Move __INTRIN_INLINE definition to mingw32.h, which is always included
* Allow attribute artificial for Clang, too
> [CRT] Implement mmintrin.h and xmmintrin.h

- ntoskrnl/ex/event.c
- ntoskrnl/ex/mutant.c
- ntoskrnl/ex/sem.c
- ntoskrnl/ex/timer.c
- ntoskrnl/include/internal/icif.h
- ntoskrnl/include/internal/probe.h
- ntoskrnl/io/iomgr/iocomp.c
- ntoskrnl/ps/query.c
- ntoskrnl/se/tokencls.c
`NtQueryInformationToken` is by far the only system call in NT where `ReturnLength` simply cannot be optional. On Windows this parameter is always probed and an argument to NULL directly leads to an access violation exception.
This is due to the fact of how tokens work, as its information contents (token user, owner, primary group, et al) are dynamic and can vary throughout over time in memory.
What happens on current ReactOS master however is that `ReturnLength` is only probed if the parameter is not NULL. On a NULL case scenario the probing checks succeed and `NtQueryInformationToken` fails later. For this, just get rid of `CompleteProbing`
parameter and opt in for a bit mask flag based approach, with **ICIF_FORCE_RETURN_LENGTH_PROBE** being set on `DefaultQueryInfoBufferCheck` which …
> [NTOSKRNL] Force a probe against ReturnLength on query & Misc ICIF stuff

- modules/rostests/apitests/ntdll/NtQueryInformationToken.c
- ntoskrnl/include/internal/se.h
- ntoskrnl/se/token.c
- ntoskrnl/se/tokencls.c
Since there's support for restricted tokens in the kernel which also supports for sandbox inert tokens as well, just implement the querying part outright, aka `TokenSandBoxInert` class.
> [NTOS:SE] Implement token sandbox inert querying

- media/doc/WINESYNC.txt
- modules/rostests/winetests/msxml3/schema.c
_Add four ifdef REACTOS to bypass code causing crashes and Sync to Wine-6.14._
JIRA issue: [CORE-17783](https://jira.reactos.org/browse/CORE-17783)
> [MSXML3_WINETEST] Fix schema test crashes and sync to Wine-6.14

- base/applications/regedit/find.c
Searching the registry for a key or value gives no results 
[REGEDIT] Fix issue at Find registry key
If we dont select a value to [pszValueName] as a starting point to search from,  we need set [pszValueName]  to the first item in current subkey
[[REGEDIT] Set focus to subkey when we search for it.
[[REGEDIT] Check pszSubKey length before calling RegFindRecurse.
> [REGEDIT] Fix issue at Find registry key

- sdk/include/crt/fpieee.h
Add some missing constants (needed for upcoming import of SSE2 math functions from AMD's libm)
> [CRT] Add missing OP_* constants in fpieee.h

- boot/freeldr/freeldr/include/ver.h
- sdk/include/reactos/version.rc
- sdk/include/reactos/wine/wine_common_ver.rc
Follow up of Colin's idea to use "ReactOS Project" consistently everywhere. This fixes PE version inconsistency that I mentioned in [CORE-18191](https://jira.reactos.org/browse/CORE-18191).
There are some files which also have "ReactOS Development Team", but I doubt whether to update them:
- [drivers/storage/ide/uniata/idedma.rc](https://github.com/reactos/reactos/blob/bbccad0ed60d619e49eb6e5d4e85cf9e0d932e2e/drivers/storage/ide/uniata/idedma.rc#L10)
- [sdk/lib/3rdparty/freetype/freetype.rc](https://github.com/reactos/reactos/blob/bbccad0ed60d619e49eb6e5d4e85cf9e0d932e2e/sdk/lib/3rdparty/freetype/freetype.rc#L5)
- [win32ss/drivers/font/ftfd/freetype.rc](https://github.com/reactos/reactos/blob/bbccad0ed60d619e49eb6e5d4e85cf9e0d932e2e/win32ss/drivers/font/ftfd/freetype.rc#L5)
> [FREELDR][SDK] Use "ReactOS Project" for consistency

- ntoskrnl/include/internal/se.h
- ntoskrnl/se/token.c
- ntoskrnl/se/tokencls.c
- ntoskrnl/se/tokenlif.c
On current master, ReactOS faces these problems:
- ObCreateObject charges both paged and non paged pool a size of TOKEN structure, not the actual dynamic contents of WHAT IS inside a token. For paged pool charge the size is that of the dynamic area (primary group + default DACL if any). This is basically what DynamicCharged is for.
For the non paged pool charge, the actual charge is that of TOKEN structure upon creation. On duplication and filtering however, the paged pool charge size is that of the inherited dynamic charged space from an existing token whereas the non paged pool size is that of the calculated token body
length for the new duplicated/filtered token. On current master, we're literally cheating the kernel by charging the wrong amount of quota not taking into account the …
> [NTOS:SE] Properly handle dynamic counters in token

- win32ss/gdi/eng/alphablend.c
Part of
JIRA issue: [CORE-11156](https://jira.reactos.org/browse/CORE-11156)
Co-authored-by: Carlo Bramini <...>
> [WIN32K:ENG] EngAlphaBlend(): Release EnterLeaveSource on error

- ntoskrnl/mm/ARM3/virtual.c
When a PDE gets empty, we skip the address to the next PDE boundary, which might introduce an AddressGap, which wasn't handled before.
> [NTOSKRNL] Fix a bug in MiDeleteVirtualAddresses

- ntoskrnl/mm/ARM3/mdlsup.c
- ntoskrnl/mm/ARM3/procsup.c
- ntoskrnl/mm/ARM3/virtual.c
Since we were charging the pool quota after the VAD insertion, if the quota charge failed, the VAD would still have been inserted. This commit attempts to resolve this issue by charging quota before inserting the VAD, allowing the quota charge to fail before inserting any VADs.
> [NTOS:MM] Fix VADs being inserted even though the quota would exceed.

- base/shell/explorer/traywnd.cpp
JIRA issue: [CORE-18024](https://jira.reactos.org/browse/CORE-18024)
- Add `AddRef` call in `CStartButton::OnContextMenu`.
BEFORE:
FAILED.
AFTER:
Success.
> [EXPLORER] Fix assertion failure on start button

- win32ss/user/ntuser/winsta.h
JIRA issue: [CORE-18252](https://jira.reactos.org/browse/CORE-18252)
- Add a comment for `WINSTATION_OBJECT` structure.
- Modify `WINSTATION_OBJECT` structure with inserting `struct tagKL *spklList` member.
- Add some `C_ASSERT(offsetof(WINSTATION_OBJECT, ...) == ...);`.
> [NTUSER] Improve WINSTATION_OBJECT compatibility

- win32ss/user/ntuser/winsta.c
This PR allows that the window station's keyboard layout can be assignment-locked. Currently no effect.
- Call `UserAssignmentUnlock((PVOID*)&WinSta->spklList);` in `IntWinStaObjectDelete` function.
> [NTUSER] Release WinSta->spklList at IntWinStaObjectDelete

- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/ntuser/winsta.c
- win32ss/user/ntuser/winsta.h
This PR's implementation enables `KLF_UNLOAD` flag awareness on listing the KLs.
- Add `IntGetProcessWindowStation` helper function to `winsta.c`.
- Add `IntGetKeyboardLayoutList` helper function to `kbdlayout.c`.
- Implement `NtUserGetKeyboardLayoutList` function in `kbdlayout.c`, using `IntGetKeyboardLayoutList` and `IntGetProcessWindowStation`.
> [NTUSER] KLF_UNLOAD flag of NtUserGetKeyboardLayoutList

- modules/rostests/apitests/win32u/win32u_2k3sp2/win32u_2k3sp2.spec
- modules/rostests/apitests/win32u/win32u_ros/win32u_ros.spec
- modules/rostests/apitests/win32u/win32u_vista/win32u_vista.spec
- modules/rostests/apitests/win32u/win32u_xpsp2/win32u_xpsp2.spec
- win32ss/include/ntuser.h
- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/user32/windows/input.c
#4594 has proved that the 1st argument of `NtUserGetKeyboardLayoutName` has type `PUNICODE_STRING`.
- Modify `NtUserGetKeyboardLayoutName` prototype.
- Adjust `GetKeyboardLayoutNameW` for this modification.
- If an `HKL` was an IME keyboard layout, then use the `HKL` for layout name.
> [NTUSER][USER32] NtUserGetKeyboardLayoutName and GetKeyboardLayoutNameW

- dll/win32/shell32/res/rgs/adminfoldershortcut.rgs
- dll/win32/shell32/res/rgs/fontsfoldershortcut.rgs
JIRA issue: [CORE-18251](https://jira.reactos.org/browse/CORE-18251)
> [SHELL32] Fix "Fonts" and "Administrative Tools" control panel icon incorrectly displayed after 8d520f3

- dll/win32/kernel32/client/console/readwrite.c
Some applications (and libraries, like [replxx](https://github.com/AmokHuginnsson/replxx/blob/master/src/windows.cxx)) rely on this undocumented behavior and throw internally an memory access violation exception.
> [KERNEL32] lpNumberOfCharsWritten is optional for WriteConsole

- win32ss/user/user32/misc/stubs.c
- win32ss/user/user32/windows/input.c
I want to fix the keyboard layout handling, but fixing by one shot is difficult.
- Add `IntLoadKeyboardLayout` (Win: `LoadKeyboardLayoutWorker`) helper function.
- Use it in `LoadKeyboardLayoutW` and `LoadKeyboardLayoutEx` functions.
- Add `TRACE`.
> [USER32] Refactoring on LoadKeyboardLayout(W/Ex)

- dll/win32/imm32/keymsg.c
- sdk/include/ddk/immdev.h
- win32ss/user/user32/misc/imm.c
Implementing Japanese input... `WM_IME_SYSTEM` message is important for IMM/IME management.
- Add code to `ImeWnd_OnImeSystem` function (Win: `ImeSystemHandler`).
- Add `CtfLoadThreadLayout` and `User32DoImeHelp` helper functions.
- Define `IMS_...` constants (for `WM_IME_SYSTEM` `wParam`) and fix some magic numbers.
> [USER32][IMM32][INCLUDE] Empower WM_IME_SYSTEM handling

- win32ss/user/user32/windows/input.c
Implementing Far-East-Asian input... Enable the IME hotkeys.
- Call `CliImmInitializeHotKeys.SETIMEHOTKEY_ADD` on `IntLoadKeyboardLayout` epilogue.
> [USER32] Call CliImmInitializeHotKeys in IntLoadKeyboardLayout

- win32ss/user/user32/misc/imm.c
- win32ss/user/user32/windows/defwnd.c
- Add `WM_IME_SYSTEM` message handling on `RealDefWindowProcA` and `RealDefWindowProcW` functions.
- Improve `WM_IME_...` messages handling.
- `s/IMMGWL_IMC/IMMGWLP_IMC/`
- Don't set `IMMGWLP_IMC` value to the default IME window.
> [USER32] RealDefWindowProcA/W WM_IME_SYSTEM handling

- win32ss/include/ntuser.h
- win32ss/user/user32/misc/imm.c
- win32ss/user/user32/windows/class.c
Improve code uniformity and backward compatibility of `NtUserSetWindowLongPtr`.
- Add `NtUserSetWindowLongPtr` macro on non-Win64.
- Use `NtUserSetWindowLongPtr` instead of `NtUserSetWindowLong`.
> [NTUSER][USER32] Define NtUserSetWindowLongPtr for non-Win64

- win32ss/include/ntuser.h
- win32ss/user/user32/misc/imm.c
- Add `IS_CICERO_MODE()` macro.
- Append `DWORD dwLastStatus` to `IMEUI` structure.
- Modify `ImeWndProc_common`, `ImeWnd_OnCreate`, `ImeWnd_OnImeSelect`, and `ImeWnd_OnImeControl` functions.
> [USER32] Adjustment for IME/IMM

- win32ss/user/ntuser/kbdlayout.c
- Add `co_IntUnloadKeyboardLayoutEx` (Win: `xxxInternalUnloadKeyboardLayout`), `IntUnloadKeyboardLayout` (Win: `xxxUnloadKeyboardLayout`) helper functions.
- Rewrite `NtUserUnloadKeyboardLayout` function.
> [NTUSER] Rewrite NtUserUnloadKeyboardLayout

- boot/environ/CMakeLists.txt
- boot/freeldr/freeldr/CMakeLists.txt
- sdk/lib/cmlib/CMakeLists.txt
This also allows using the CMLIB with any reduced functionality
that could be required at boot-time.
> [BOOT][SDK:CMLIB] Compile a CMLIB for FreeLdr / NT bootloader with correct definitions.

- win32ss/user/ntuser/ime.c
- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/ntuser/keyboard.c
- win32ss/user/ntuser/main.c
Improve stability when switching languages.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-18317](https://jira.reactos.org/browse/CORE-18317)
- When the system is to assign a pointer to `THREADINFO.KeyboardLayout`, it uses `UserAssignmentLock`.
- When the system is to detach a pointer from `THREADINFO.KeyboardLayout`, it uses `UserAssignmentUnlock`.
- Synchronize `ClientInfo->hKL` with `pti->KeyboardLayout->hkl`.
> [NTUSER] Use assignment-lock against THREADINFO.KeyboardLayout

- dll/win32/imm32/ctf.c
- dll/win32/imm32/imm32.spec
- win32ss/include/imetable.h
- Add `CtfImmIsGuidMapEnable` and `CtfImmGetGuidAtom` functions.
- Modify `imetable.h` and `imm32.spec`.
> [IMM32] Add CtfImmIsGuidMapEnable and CtfImmGetGuidAtom

- base/applications/kbswitch/kbswitch.c
- win32ss/user/ntuser/hotkey.c
Improve language switching.
JIRA issue: [CORE-11737](https://jira.reactos.org/browse/CORE-11737)
- Fix `co_UserProcessHotKeys` on modifiers-only hot-keys.
- Add `Alt+Shift` hotkeys to `kbswitch` window.
BEFORE:
Cannot switch languages by `Alt+Shift` key combination.
AFTER:
Able to switch languages by `Alt+Shift` key combination.
> [KBSWITCH][NTUSER] Realize Shift+Alt language switch

- dll/cpl/input/input.c
- Use `MAKEINTRESOURCE` instead of `LoadString` with the length of `MAX_STR_LEN`
> [INPUT] Use MAKEINTRESOURCE instead of LoadString

- base/applications/rapps/loaddlg.cpp
JIRA issue: [CORE-14686](https://jira.reactos.org/browse/CORE-14686)
- Invalidate rectangle at `CDownloaderProgress::OnSetText`.
- Unsubclass the progress bar if necessary.
- Set zero to the progress for each download beginning.
> [RAPPS] Really update progress bar text

- base/applications/kbswitch/kbswitch.c
Even when the user installed three or more languages into the system, `Shift+Alt` key combination should work correctly.
JIRA issue: [CORE-11737](https://jira.reactos.org/browse/CORE-11737)
For example, we assume the user installed three Latin languages (English, French, and German), then typing `Alt+Shift` should work like EN → FR → DE → EN → FR → DE → ... (cyclically).
- Add `GetMaxLayoutNum` helper function.
- Fix `GetNextLayout` function to make `Shift+Alt` cyclic.
> [KBSWITCH] Fix GetNextLayout for three or more languages

- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/user32/windows/input.c
Implementing Japanese input... The loaded HKL values were wrong.
- Check `"IME File"` value if the `HKL` is an IME `HKL`.
- If the `HKL` is an IME `HKL`, use that `HKL` value for `dwHKL`.
- Add security comments.
> [USER32] Fix HKL value in IntLoadKeyboardLayout

- dll/cpl/access/access.c
- dll/cpl/desk/desk.c
- dll/cpl/intl/generalp.c
- dll/cpl/intl/intl.c
- dll/cpl/main/keyboard.c
- dll/cpl/main/mouse.c
- dll/cpl/mmsys/mmsys.c
- dll/cpl/mmsys/speakervolume.c
- dll/cpl/openglcfg/openglcfg.c
- dll/cpl/powercfg/powercfg.c
- dll/cpl/timedate/timedate.c
- dll/cpl/usrmgr/usrmgr.c
- dll/cpl/wined3dcfg/wined3dcfg.c
- Follow-up of [0ed302e](https://github.com/reactos/reactos/commit/0ed302ef656ed39c932e084508ffa506b47c463b)
- Replace unnecessary `LoadString` calls with `MAKEINTRESOURCE`
> [CPL] Use MAKEINTRESOURCE instead of LoadString

- dll/cpl/sysdm/general.c
- dll/cpl/sysdm/lang/bg-BG.rc
- dll/cpl/sysdm/lang/cs-CZ.rc
- dll/cpl/sysdm/lang/da-DK.rc
- dll/cpl/sysdm/lang/de-DE.rc
- dll/cpl/sysdm/lang/el-GR.rc
- dll/cpl/sysdm/lang/en-US.rc
- dll/cpl/sysdm/lang/es-ES.rc
- dll/cpl/sysdm/lang/fr-FR.rc
- dll/cpl/sysdm/lang/he-IL.rc
- dll/cpl/sysdm/lang/hu-HU.rc
- dll/cpl/sysdm/lang/id-ID.rc
- dll/cpl/sysdm/lang/it-IT.rc
- dll/cpl/sysdm/lang/ja-JP.rc
- dll/cpl/sysdm/lang/nl-NL.rc
- dll/cpl/sysdm/lang/no-NO.rc
- dll/cpl/sysdm/lang/pl-PL.rc
- dll/cpl/sysdm/lang/pt-PT.rc
- dll/cpl/sysdm/lang/ro-RO.rc
- dll/cpl/sysdm/lang/ru-RU.rc
- dll/cpl/sysdm/lang/sk-SK.rc
- dll/cpl/sysdm/lang/sq-AL.rc
- dll/cpl/sysdm/lang/sv-SE.rc
- dll/cpl/sysdm/lang/tr-TR.rc
- dll/cpl/sysdm/lang/uk-UA.rc
- dll/cpl/sysdm/lang/zh-CN.rc
- dll/cpl/sysdm/lang/zh-HK.rc
- dll/cpl/sysdm/lang/zh-TW.rc
Implement auto-updating for system uptime
https://user-images.githubusercontent.com/86486978/185762489-13a95f6e-5740-4854-bf90-418b4bc7ed96.mp4
This change helps testing ROS uptime more accurate.
> Done, but the system uptime doesn’t seem to auto-update. So it’s a bit misleading actually.
[https://www.reddit.com/r/reactos/comments/wl68g8/ive_set_up_a_web_server_running_on_reactos_today/](https://www.reddit.com/r/reactos/comments/wl68g8/ive_set_up_a_web_server_running_on_reactos_today/)
> [SYSDM] General page: Implement auto-updating for system uptime

- win32ss/user/ntuser/ntuser.h
- win32ss/user/ntuser/win32.h
Define type in proper place.
- Move `struct _TL` and `TL` definitions from `win32.h` to `ntuser.h`.
- Modify the type of `TL.pfnFree` as newly-defined `TL_FN_FREE` function pointer.
> [NTUSER] Move TL structure definition to ntuser.h

- dll/cpl/console/console.c
- Current implementation use hardcoded text for "Default" title and does not use the translated ressource to be used as CPL name
- Load the localized CPL name as title, similarly to [4631](https://github.com/KRosUser/reactos/issues/4631)
Post change :
> [CONSOLE] Use translated resource rather than hardcoded text

- base/applications/taskmgr/applpage.c
Fix discrepancy on "Switch To" action when multiple applications are selected
Menu is available (and only Switch to one of the selected apps) but button is disabled.
WinXPSP3 : both active and behaves like ReactOS menu (only Switch to one of the selected apps)
Proposed changes : Make button and menu consistent
> [TASKMGR] Fix UI on SwitchTo for multiple application

- base/applications/taskmgr/lang/fr-FR.rc
Controls are sized with 0 pixal gap, which is OK in general but raises an overlap upon selection
Add the extra 1 pixel gap
> [TASKMGR] Fix overlapping controls (French only)

- ntoskrnl/ex/sysinfo.c
- ntoskrnl/ob/obhandle.c
As explained by @HBelusca in the Jira ticket, PsIdleProcess and PsInitialSystemProcess share the same HandleTable. This leads to the same number of Handles to be reported by ObGetProcessHandleCount then feeding the SYSTEM_PROCESS_INFORMATION structure?
JIRA issue: [CORE-16577](https://jira.reactos.org/browse/CORE-16577)
Proposed change is to force the HandleCount to 0 for the Idle process in SystemProcessInformation handling instead of calling ObGetProcessHandleCount.
> [NTOSKRNL] Fix returned number of handles for Idle System Process

- media/themes/Modern/modern.msstyles/textfiles/Dark/ExtraLargeDark.INI
- media/themes/Modern/modern.msstyles/textfiles/Dark/LargeFontsDark.INI
- media/themes/Modern/modern.msstyles/textfiles/Dark/RegularDark.INI
Improve readability of text in the Modern dark theme
Use lighter text colors and darker text shadow colors
Before:
After:
> [THEMES] Improve text colors of Modern Dark theme

- dll/shellext/netshell/lanstatusui.cpp
Opening Network Status page creates a systematic "ghost" network activity, activating RX+TX activity icon both on property page and tray, while no Rx/Tx.
This is due to pContext->dwIn{out}Octets being initialized to 0 and compared to refreshed interface data.
On first Update, copy refreshed interface data to the Context
> [NETSHELL] Fix "ghost" network activity when opening Network Status page

- base/shell/explorer/startctxmnu.cpp
_ Current design is not processing actions verbs correctly for some Start Menu context menu actions (Properties, Open all users, Explore all users) despite associated code being implemented
_ This bug is cased by an incorrect actions id filtering not routing to the appropriate processing
JIRA issue: [CORE-18336](https://jira.reactos.org/browse/CORE-18336)
_ before : Properties, Open all users, Explore all users have no effect
_ after : Properties, Open all users, Explore all users open the appropriate windows
> [EXPLORER] Fix Start Menu context menu actions

- dll/win32/shell32/CDefView.cpp
_ ReactOS asserts when opening File menu in MyComputer for the second time
_ This is due to the cached copy of IContextMenu not being released before attempting to cache it again.
JIRA issue: [CORE-18353](https://jira.reactos.org/browse/CORE-18353)
_ Fix based on the patch proposed by user https://jira.reactos.org/secure/ViewProfile.jspa?name=I_Kill_Bugs
> [SHELL32] Fix Assertion when opening "File" menu in MyComputer twice

- base/applications/mspaint/CMakeLists.txt
- base/applications/mspaint/precomp.h
- base/shell/explorer/CMakeLists.txt
- base/shell/explorer/precomp.h
- dll/win32/shell32/CMakeLists.txt
- dll/win32/shell32/precomp.h
- dll/win32/shell32/shellmenu/CMakeLists.txt
In MSVC builds they would not work reliably when enabled in the precompiled header
JIRA issue: [CORE-17505](https://jira.reactos.org/browse/CORE-17505)
> [MSPAINT][EXPLORER][SHELL32] Enable ATL asserts in CMake

- dll/win32/shell32/shellmenu/CMenuDeskBar.cpp
- dll/win32/shell32/shellmenu/CMenuSite.cpp
- dll/win32/shell32/shellmenu/CMenuToolbars.cpp
* [SHELL32] Don't try to remove buttons on a nonexisting window
* [SHELL32] Properly destroy window
* [SHELL32] Only hide a window when there is a window to hide
> [SHELL32] Various fixes caught by asserts

- drivers/filesystems/ntfs/btree.c
> [NTFS] PrintAllVCNs(): Fix a typo in an ASSERT()

- media/doc/3rd Party Files.txt
Rather use version from active line in .rc than from comment in .c.
Addendum to 5ee633f (0.4.15-dev-4556).
JIRA issue: [CORE-18180](https://jira.reactos.org/browse/CORE-18180)
(Split off from #4642.)
> [DOC] 3rd Party Files.txt: Fix Buslogic driver version

- sdk/lib/atl/atlwin.h
By right-click on a Desktop icon, "Properties" menu, "Compatibility" tab and the "Edit compatibility modes" button, this opens a window centered on the parent window.
If we moved the parent window to one of the sides, (left or right) and then click on the "Edit modes" button, this window will appear cut off because it exceeds the width of the screen.
[ CORE-17089](https://jira.reactos.org/browse/CORE-17089)
Expected behavior:
The window should be completely visible
> [ATL] Fix window position to fit in screen area CORE-17089

- win32ss/user/user32/include/user32p.h
- win32ss/user/user32/misc/logon.c
- win32ss/user/user32/windows/input.c
JIRA issue: [CORE-16600](https://jira.reactos.org/browse/CORE-16600)
- Add `IntLoadPreloadKeyboardLayouts` helper function to load the layouts on log-on.
- In `UpdatePerUserSystemParameters` function, call `CliImmInitializeHotKeys` and `IntLoadPreloadKeyboardLayouts` functions.
> [USER32] Load keyboard layouts on logon correctly

- dll/cpl/input/input.c
- Use `int` for applet index (like other CPLs)
- Revert some changes from https://github.com/reactos/reactos/commit/976d48baeb1a98d620107885022b44b24bad77a1
> [INPUT] Fix taskbar icon and remove small icon hack

- dll/cpl/mmsys/audio.c
- dll/cpl/mmsys/mmsys.c
- dll/cpl/mmsys/mmsys.h
- dll/cpl/mmsys/sounds.c
- dll/cpl/mmsys/speakervolume.c
- dll/cpl/mmsys/voice.c
- dll/cpl/mmsys/volume.c
Multimedia Control Panel diverse fixes
- Use Unicode (WCHAR) instead of TCHAR
- Code formatting
- Use string safe functions
- Close handles after calling `CreateProcess`
- Save sound path as `REG_EXPAND_SZ` only if the path contains '%' character, like Windows does
- Fix `wcsdup` leaks
- ~~Fix incorrect `IDC_SPEAKIMG` control position and size~~ **Next PR**
- ~~Use transparent background for "Speaker settings" bitmap~~ **Next PR**
> mmsys.cpl diverse fixes

- dll/win32/shell32/lang/fr-FR.rc
[SHELL32] Fix French message for "Overwrite Folder" confirmation message
Before
After
> [SHELL32] Fix French message for "Overwrite Folder" confirmation message

- dll/cpl/access/access.c
- dll/cpl/desk/desk.c
- dll/cpl/hotplug/hotplug.c
- dll/cpl/input/input.c
- dll/cpl/intl/intl.c
- dll/cpl/joy/joy.c
- dll/cpl/main/main.c
- dll/cpl/mmsys/mmsys.c
- dll/cpl/powercfg/powercfg.c
- dll/cpl/sysdm/sysdm.c
- dll/cpl/timedate/timedate.c
- dll/cpl/usrmgr/usrmgr.c
Improve stability of the system.
- Check the boundary `(i < NUM_APPLETS)` of the variable `i` in `CPlApplet` functions.
- Use `UINT` type for the variable `i`.
> [CPL] Boundary check of Control Panel applets

- ntoskrnl/include/internal/mm.h
- ntoskrnl/mm/ARM3/miarm.h
- ntoskrnl/mm/i386/page.c
- ntoskrnl/mm/marea.c
- ntoskrnl/mm/rmap.c
- ntoskrnl/mm/section.c
In one of the revert patch for CORE-17595, I noticed there's a slight difference in checks that are done in the way PDEs are checked. Let's see f that matters. Those are sanity checks which are worth having anyway.
- Check that PDE double mapping is always in sync
- Check the user-mode PDEs are consistent with their share count.
> [NTOS] Add some sanity checks when synchronizing PDEs

- win32ss/gdi/gdi32/objects/text.c
JIRA issue: [CORE-18365](https://jira.reactos.org/browse/CORE-18365)
after fix:
> [GDI32] Fix ExtTextOutA with ETO_GLYPH_INDEX

- dll/directx/wine/ddraw/utils.c
fixme:(dll/directx/wine/ddraw/utils.c:584) Unhandled flags 0x20.
gets logged many times per second.
It does affect several applications, e.g. the game 'Anno 1602' from 1998, and the 'Diablo 2 demo' from rapps,
For both games it can be observed with both: our VBEMP driver and the VBox4.3.12 3D-accelerated-driver.
Muting may improve performance a bit in such apps.
It gets logged although no missing features can be perceived visually in the rendering.
Fix it by importing Wine-commit [b943c7910b3261c9603343369cd632f7a3b56bba](https://source.winehq.org/git/wine.git/commit/b943c7910b3261c9603343369cd632f7a3b56bba)
ddraw: Handle DDLOCK_WRITEONLY in wined3dmapflags_from_ddrawmapflags().
Signed-off-by: Henri Verbeet <hverbeet@codeweavers.com>
Signed-off-by: Alexandre Julliard <julliard@winehq.org> …
> [DDRAW] Mute aggressive log-spam in game 'Anno 1602' CORE-18378

- dll/shellext/zipfldr/CZipExtract.cpp
- Set large icon correctly
Alt + Tab Before:
Alt + Tab After:
> [ZIPFLDR] Set large icon correctly

- dll/win32/shell32/dialogs/fprop.cpp
[SHELL32] Fix property sheets that can't be closed due to failed init
- When a PropertySheet fails to init, log and ERR but is displayed with no page and can't be closed.
JIRA issue: [CORE-18333](https://jira.reactos.org/browse/CORE-18333)
- In such error case, do not open PropertySheet.
> [SHELL32] Fix property sheets that can't be closed due to failed init

- dll/cpl/intl/languages.c
- In `intl.cpl`, realize automatic Japanese IME installation by checkbox `Install files for East Asian languages` by using `rapps.exe`.
- Disable checkbox `Install files for East Asian languages` if Japanese IME is not installable.
> [CPL][INTL] Realize automatic Japanese IME installation

- base/shell/explorer/traywnd.cpp
Follow-up of PR #4715.
JIRA issue: [CORE-15369](https://jira.reactos.org/browse/CORE-15369)
- The 'Show Desktop' button of taskbar works on button up instead of button down.
- Add `NULL` checks for `m_ShowDesktopButton`.
- Fix hung-up in rebooting.
> [EXPLORER] 'Show Desktop' button should work on button up

- boot/bootdata/txtsetup.sif
- boot/freeldr/freeldr/lib/fs/fat.c
This fixes JIRA issue: [CORE-16329](https://jira.reactos.org/browse/CORE-16329)
Creating a PR to run on testbots, to make sure 1st stage setup passes on non-Xbox.
> [FREELDR] Allow to boot from FATX volume using vfatfs driver

- base/applications/kbswitch/kbswitch.c
- base/applications/kbswitch/resource.h
- win32ss/user/ntuser/defwnd.c
- win32ss/user/ntuser/window.c
- win32ss/user/ntuser/window.h
`Alt+Shift` is a useful key combination to switch the current keyboard layout.
JIRA issue: [CORE-11737](https://jira.reactos.org/browse/CORE-11737)
- Add `ID_NEXTLAYOUT` command to `kbswitch`.
- Send command `ID_NEXTLAYOUT` to `kbswitch` on `Alt+Shift` key combination in `WM_SYSKEYDOWN` handling of `IntDefWindowProc` function.
- Make `IntFindWindow` a non-static function.
Hopefully, it works.
> [NTUSER][KBSWITCH] Realize Alt+Shift keyboard switch (retry)

- dll/shellext/shellbtrfs/propsheet.cpp
- dll/shellext/shellbtrfs/shellbtrfs.rc
- dll/win32/ubtrfs/ubtrfs.rc
- drivers/filesystems/btrfs/btrfs.c
- drivers/filesystems/btrfs/btrfs.inf
- drivers/filesystems/btrfs/btrfs.rc
- drivers/filesystems/btrfs/btrfs_drv.h
- drivers/filesystems/btrfs/create.c
- drivers/filesystems/btrfs/fileinfo.c
- drivers/filesystems/btrfs/flushthread.c
- drivers/filesystems/btrfs/free-space.c
- drivers/filesystems/btrfs/fsctl.c
- drivers/filesystems/btrfs/registry.c
- drivers/filesystems/btrfs/treefuncs.c
v1.8.1 (2022-08-23):
- Fixed use-after-free when flushing
- Fixed crash when opening volume when AppLocker installed
- Compression now disabled for no-COW files, as on Linux
- Flushing now scales better on very fast drives
- Fixed small files getting padded to 4,096 bytes by lazy writer
- Added NoDataCOW registry option
JIRA issue: [CORE-18322](https://jira.reactos.org/browse/CORE-18322)
> [BTRFS][UBTRFS][SHELLBTRFS] Upgrade to 1.8.1

- media/doc/3rd Party Files.txt
Addendum to 29d1938 (0.4.15-dev-5113).
JIRA issue: [CORE-18322](https://jira.reactos.org/browse/CORE-18322)
> [DOC] 3rd Party Files.txt: Update WinBtrfs to v1.8.1

- dll/win32/dnsapi/rpc.c
Code has been unchanged for 3 years.
Addendum to b79246c (0.4.14-dev-174).
JIRA issue: [CORE-18384](https://jira.reactos.org/browse/CORE-18384)
> [DNSAPI] DNSRSLVR_HANDLE_bind(): Demote 1 DPRINT1()

- base/applications/kbswitch/kbswitch.c
BEFORE:
AFTER:
- Do the same behaviour as `input.dll` in getting indicator text.
- Use full color DIB (device-independent bitmap) to improve icon.
- Use `SPI_GETICONTITLELOGFONT` for font.
> [KBSWITCH] Fix keyboard indicator text and font

- dll/win32/shell32/CDefView.cpp
Previously, we would share one object between a multitude of options
Now, the only two options that need to store something for later use each have their own space for it.
The context menu always cleans up after itself, the File menu does not.
JIRA issue: [CORE-18345](https://jira.reactos.org/browse/CORE-18345)
JIRA issue: [CORE-18361](https://jira.reactos.org/browse/CORE-18361)
JIRA issue: [CORE-18366](https://jira.reactos.org/browse/CORE-18366)
> [SHELL32] CDefView: Rework context menu handling

- base/shell/explorer/startctxmnu.cpp
- base/shell/explorer/tbsite.cpp
- base/shell/explorer/traywnd.cpp
- dll/shellext/netshell/lanstatusui.cpp
- dll/win32/browseui/CAutoComplete.cpp
- dll/win32/browseui/desktopipc.cpp
- dll/win32/browseui/internettoolbar.cpp
- dll/win32/browseui/shellbrowser.cpp
- dll/win32/shell32/CFolderItems.cpp
- dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp
- dll/win32/shell32/shellmenu/CMenuBand.cpp
- sdk/include/reactos/browseui_undoc.h
- sdk/include/reactos/shellutils.h
- sdk/lib/atl/atlcomcli.h
This mimics what MS's CComPtr is doing:
https://learn.microsoft.com/en-us/cpp/atl/reference/ccomptrbase-class?view=msvc-170#operator_ptr
The reasoning behind this is that AddRef/Release is handled by the CComPtr,
so anyone calling that is most likely not using the CComPtr correct.
> [ATL] Prohibit the use of AddRef/Release on objects inside CComPtr

- modules/rostests/apitests/user32/CMakeLists.txt
- modules/rostests/apitests/user32/VirtualKey.c
- modules/rostests/apitests/user32/testlist.c
API tests for @julcar's PR #4730.
JIRA issue: [CORE-17906](https://jira.reactos.org/browse/CORE-17906)
```
VirtualKey: 18 tests executed (0 marked as todo, 0 failures), 0 skipped.
```
```
VirtualKey.c:44: Test failed: [0] Returned 128, expected 0
VirtualKey.c:52: Test failed: [4] ScanCode = 0, expected 29
VirtualKey: 18 tests executed (0 marked as todo, 2 failures), 0 skipped.
```
Cc @HBelusca to review this, as it covers some of his WIP stuff.
> [USER32_APITEST] Add tests for MapVirtualKeyW

- base/applications/network/wlanconf/wlanconf.c
**JIRA issue:** [**CORE-18032**](https://jira.reactos.org/browse/CORE-18032)
GetInterfaceInfo returns interface name in Windows XP and 2003 in this format: `\DEVICE\TCPIP_{GUID}`.
MSDN says that the `Name` member of the `IP_ADAPTER_INDEX_MAP` may start with '{' character on Windows Vista and later.
https://docs.microsoft.com/en-us/windows/win32/api/ipexport/ns-ipexport-ip_adapter_index_map
Change the code to support both cases.
Tested with RTL8187-based USB adapter:
> [WLANCONF] Fix getting the interface GUID value

- win32ss/user/ntuser/winpos.c
_Change how Windows Hierarchy is changed when creating pop-up windows as owned._
JIRA issue: [CORE-18132](https://jira.reactos.org/browse/CORE-18132)
> [NTUSER] Fix 'Trying to link windows to itself' with Patch by I_Kill_Bugs

- win32ss/user/ntuser/focus.c
- win32ss/user/ntuser/nonclient.c
- win32ss/user/ntuser/window.c
- win32ss/user/ntuser/winpos.c
- win32ss/user/user32/controls/appswitch.c
`WS_EX_NOACTIVATE` flag forbids the window to be activated.
JIRA issue: [CORE-18417](https://jira.reactos.org/browse/CORE-18417)
- Don't activate the window if `WS_EX_NOACTIVATE` is set.
- Ignore the window that has `WS_EX_NOACTIVATE` flag on Task Switcher.
> [NTUSER][USER32] Initial support of WS_EX_NOACTIVATE flag

- base/applications/mscutils/eventvwr/eventvwr.c
- base/applications/mscutils/eventvwr/evtdetctl.c
- base/applications/mscutils/eventvwr/evtdetctl.h
When clicking outside a selected event item in the list, or right clicking on a non-selected line,
we used to get "No Items in ListView" error.
This error came from a check for code paths that should, in principle, be not taken if no event item is selected.
JIRA issue: [CORE-18438](https://jira.reactos.org/browse/CORE-18438)
Rework how some aspects of item selection retrieval is done.
- Each event detail control stores its own "current" item index, so
that there can be different event detail dialogs showing different
events concurrently (half-plemented; this is a Win7-like feature).
As such, give the index of the selected event item when sending
the EVT_DISPLAY message, instead of having the details dialog
retrieve everytime by itself the current selected item (that may
change in-between …
> [EVENTVWR] Improve behaviour on event item selection.

- base/system/winlogon/CMakeLists.txt
- base/system/winlogon/notify.c
- base/system/winlogon/sas.c
- base/system/winlogon/winlogon.h
3rd-party code (e.g. Gina notification handlers DLLs), or related code (e.g. winmm.dll when playing sound events via sound files) can run in the context of WinLogon.exe. If this code crashes (because it contains a bug, or plays a corrupted sound file, etc.), then WinLogon would crash, and since this is a marked system process, this would trigger a BSoD.
Protect calls to this 3rd-party code by SEH.
(Remark: LoadLibrary calls, that run dll's DllMain() functions, don't need to be under SEH, since LoadLibrary already handles that. Thanks to Mark for noticing this.)
This includes:
- Notification dll calling in CallNotificationDll().
- winmm.dll API calling (e.g. PlaySound) in PlaySoundRoutine().
Also:
- Fix dwKeyName usage in RegEnumKeyExW() specifying a number of *characters*.
> [WINLOGON] Protect function calls to '3rd-party' DLLs by SEH.
