base/applications/regedit/edit.c

Add support for editing (or rather viewing, since like REG_RESOURCE_LIST the results are not written back) REG_FULL_RESOURCE_DESCRIPTOR registry values like HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\MultifunctionAdapter\1:ConfiguratonData aka "ACPI BIOS" / BIOS memory map, which itself seems to be broken in it's format, but that is for another patch...

[REGEDIT] Support editing REG_FULL_RESOURCE_DESCRIPTOR values

---

drivers/storage/class/class2/class2.c
drivers/storage/class/include/class2.h

- In ScsiClassCreateDeviceObject() don't drop received object name and store it in the device extension
- Implement support for the IOCTL_MOUNTDEV_QUERY_DEVICE_NAME IOCTL; return the store device name

[CLASS2] Implement support for IOCTL_MOUNTDEV_QUERY_DEVICE_NAME

---

drivers/wdm/audio/legacy/wdmaud/entry.c
drivers/wdm/audio/legacy/wdmaud/mmixer.c
drivers/wdm/audio/legacy/wdmaud/wdmaud.h

Here is the second part of the patch which closes all mixer events on device cleanup, which should kill CORE-10735 forever.

[WDMAUD] Close mixers on cleanup. Should fix CORE-10735 definitely

---

base/system/msiexec/msiexec.c
media/doc/README.WINE

d73c38f msiexec: Fix parsing of command lines where quoted strings and properties are not separated by whitespace.

[MSIEXEC] Sync with Wine Staging 2.16. CORE-13762

---

media/doc/README.WINE
sdk/tools/widl/header.c
sdk/tools/widl/typelib.c

b42a155 widl: Handle C++ aggregate returns in a MSVC compatible way.
084fa63 widl: Only generate Proxy Stubs when functions have the call_as attribute.
fbdf119 widl: Try to find imported typelib using .tlb extension if it wasn't specified.

[WIDL] Sync with Wine Staging 2.16. CORE-13762

---

dll/win32/msi/format.c

Imported wine commit:
f517022: msi: Fix an invalid write in build_default_format (Valgrind).

[MSI] Fix a buffer overrun in build_default_format CORE-13881

---

boot/freeldr/freeldr/arch/i386/pcmem.c

[FREELDR]
PcMemGetBiosMemoryMap(): Discard empty entries/ranges.
Nit: Improve a TRACE() from f588de2e79e67fc7878e71dccb4ea67debdacf5e.
CORE-13332

CORE-13332. Discard empty entries/ranges.

---

drivers/crypto/ksecdd/random.c
drivers/filesystems/btrfs/create.c
sdk/cmake/msvc.cmake
sdk/include/psdk/basetsd.h

- SIZE_T -> ULONG in KsecGatherEntropyData
- Add missing ZwQueryInformationProcess() prototype for x64 build of btrfs
- Fix ml.exe path for VS 2017 Community Edition
- Add missing Handle32ToHandle to basetsd.h

[REACTOS] Fix x64 build

---

drivers/storage/port/storport/misc.c
drivers/storage/port/storport/storport.spec

On x64 StoportQuerySystemTime cannot be forwarded to ntoskrnl, since it is an inline only function. So implement a wrapper for it.

[STORPORT] Fix x64 build

---

sdk/lib/crt/misc/getargs.c

the cFileName member of WIN32_FIND_DATA is an array of MAX_PATH(260). Using strcpy/wcscpy with the target buffer being smaller is potentially bad. Corresponds to CID 1401198 and 1401195.

Destination Buffer too small

---

configure.cmd

A workaround for [ROSBE-121](https://jira.reactos.org/browse/ROSBE-121).
Add a flag to explicitly specify wanted version. Say, you want to create vssolutions for VS2017 using RosBE CMake. You can only create VS 2015 files, so you specify that using a flag with an argument:
```
configure vssolution -VS_VER 14 
```

Add -VS_VER flag as a workaround for our CMake in RosBE.

---

drivers/input/i8042prt/keyboard.c

[CORE-13048](https://jira.reactos.org/browse/CORE-13048)
- keyboard.c: Restore 1 "Irql =" (which was lost in r30000).

CORE-13048. [I8042PRT] keyboard.c: Restore 1 "Irql =" (which was lost in r30000).

---

ntoskrnl/fsrtl/dbcsname.c
ntoskrnl/fsrtl/name.c

Fixes CIDs [1401178](https://scan5.coverity.com/reports.htm#v11004/p10080/fileInstanceId=128127278&defectInstanceId=35935338&mergedDefectId=1401178), [1401177](https://scan5.coverity.com/reports.htm#v11004/p10080/fileInstanceId=128127278&defectInstanceId=35935340&mergedDefectId=1401177), [1401083](https://scan5.coverity.com/reports.htm#v11004/p10080/fileInstanceId=128127287&defectInstanceId=35934996&mergedDefectId=1401083)

[NTOSKRNL] Fix memory leak and out-of-bounds access in FsRtlIsDbcsInExpression

---

ntoskrnl/config/cmwraprs.c
ntoskrnl/kdbg/kdb_cli.c
sdk/lib/rossym/zwfile.c
sdk/lib/rossym_new/zwfile.c

Update NtReadFile()/NtWriteFile() calls wrt ByteOffset param use.
JIRA issue: [CORE-13910](https://jira.reactos.org/browse/CORE-13910)
- ZwReadFile() calls: Use explicit NULL instead of ambiguous 0, Set and use ByteOffset.
- After review, I'll check/add the 3 other greps too.

CORE-13910. Update NtReadFile()/NtWriteFile() calls wrt ByteOffset param use

---

drivers/filters/mountmgr/database.c
ntoskrnl/config/cmwraprs.c

Update NtReadFile()/NtWriteFile() calls wrt ByteOffset param use.
(This is part 2/4.)
JIRA issue: [CORE-13910](https://jira.reactos.org/browse/CORE-13910)
- ZwWriteFile() calls: Use explicit NULL instead of ambiguous 0.

CORE-13910. Update ZwWriteFile() calls wrt ByteOffset param use.

---

sdk/lib/rtl/memstream.c

BytesRead is an optional out parameter and must be checked before being written to.

CID 1206831 Dereference after null check

---

base/applications/network/net/cmdUser.c

"Password last set" and "Password changeable" sections were missing newlines.

Add missing newlines to net utility output

---

dll/win32/shell32/folders/CDesktopFolder.cpp

This fixes the following issue : when selecting multiple icons
on the desktop, and then right-clicking; the Properties sheet
would immediately be displayed, conflicting with the context
menu.
This improves the following issue : when selecting multiple
files, and then right-clicking -> Properties on the context
menu, we now display each file's Properties sheet one after
another.
CORE-12510
JIRA issue: [CORE-12510](https://jira.reactos.org/browse/CORE-12510)

[SHELL32] Fix multiple selection of desktop icons, improve MFS

---

base/applications/mspaint/dialogs.cpp
base/applications/mspaint/dialogs.h
base/applications/mspaint/globalvar.h
base/applications/mspaint/main.cpp
base/applications/mspaint/winproc.cpp

- Wrap implementation of Mirror/Rotate, Stretch/Skew and Attributes dialog in subclasses of CDialogImpl
- Turn global variables from code that was moved into member functions into member variables
- Add global instances of all three dialog classes
- Use _global instance_.DoModal(...) instead of one-line wrappers
- Replace some TCHAR arrays with CStrings

[MSPAINT] Base dialog implementations on CDialogImpl

---

base/setup/usetup/bootsup.c
base/setup/usetup/native/utils/console.c
modules/rosapps/applications/sysutils/utils/pice/module/utils.c
sdk/lib/fslib/ext2lib/Disk.c

Update NtReadFile()/NtWriteFile() calls wrt ByteOffset param use.
(This is part 3/4.)
JIRA issue: [CORE-13910](https://jira.reactos.org/browse/CORE-13910)
- NtReadFile() calls: Remove unused 'ByteOffset = 0', Use explicit NULL instead of ambiguous 0, Remove casts to same type.

CORE-13910. Update NtReadFile() calls wrt ByteOffset param use.

---

win32ss/user/ntuser/mouse.c
win32ss/user/ntuser/window.c

This aims to fix crashes in `IntQueryTrackMouseEvent` caused by an invalid `spwndTrack`
JIRA issue: [CORE-13619](https://jira.reactos.org/browse/CORE-13619)
I am not entirely sure that setting `spwndTrack` to NULL is allowed?

[WIN32K] Check if the window being destroyed is currently tracked.

---

base/setup/usetup/bootsup.c
ntoskrnl/kdbg/i386/i386-dis.c
ntoskrnl/kdbg/kdb.c
sdk/lib/fslib/ext2lib/Disk.c

Update NtReadFile()/NtWriteFile() calls wrt ByteOffset param use.
(This is part 4/4.)
JIRA issue: CORE-13910
- NtWriteFile() calls: Remove unused 'ByteOffset = 0', Use explicit NULL instead of ambiguous 0.

CORE-13910. Update NtWriteFile() calls wrt ByteOffset param use.

---

base/applications/rapps/include/dialogs.h
base/applications/rapps/loaddlg.cpp

Some download links may not tell the final content-length of the file.
This PR adds indication of currently downloaded file size, if content-length is not available.
Make use of `PBS_MARQUEE` and `PBM_SETMARQUEE` powers!
Cc @sanchaez

[RAPPS] Add support for no-length downloads indication

---

dll/win32/setupapi/driver.c

Fix a typo.
JIRA issue: [CORE-12580](https://jira.reactos.org/browse/CORE-12580)
See [CORE-12580 comment](https://jira.reactos.org/browse/CORE-12580?focusedCommentId=87618&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87618).

CORE-12580. SetupApi: it is _WIN32_WINNT, not WIN32_WINNT

---

win32ss/gdi/eng/engwindow.c
win32ss/gdi/eng/pdevobj.h
win32ss/gdi/eng/surface.h
win32ss/gdi/ntgdi/print.c

Exclusively lock The NtUser implementation in EngCreateWnd and EngDeleteWnd, as needed by underlying internal functions.
For this, one needs to ensure that the Escape routine is called without any lock held.
JIRA issue: [CORE-7727](https://jira.reactos.org/browse/CORE-7727)
See https://msdn.microsoft.com/en-us/library/windows/hardware/ff564769(v=vs.85).aspx for a bit of documentation.
Also, managed to break my commit history, so meh...

[WIN32SS] Exclusively lock NtUser in Eng*Wnd functions

---

base/setup/usetup/muifonts.h

This patch adds "Comic Sans MS", "Georgia" and "Palatino Linotype" font
substitutes.
- "Comic Sans MS" |--> "Ubuntu".
- "Georgia" |--> "FreeSerif".
- "Palatino Linotype" |--> "DejaVu Serif".
JIRA issue: [CORE-12419](https://jira.reactos.org/browse/CORE-12419)

Add more font substitutes

---

boot/freeldr/freeldr/arch/i386/pcmem.c
boot/freeldr/freeldr/include/arch/pc/pcbios.h

PcMemGetBiosMemoryMap(): Add checks for entry sizes and bare handling of error case.
CORE-13332

CORE-13332. Add checks for entry sizes and bare handling of error case.

---

dll/cpl/input/input_list.c
dll/cpl/input/input_list.h
dll/cpl/input/lang/bg-BG.rc
dll/cpl/input/lang/cs-CZ.rc
dll/cpl/input/lang/de-DE.rc
dll/cpl/input/lang/el-GR.rc
dll/cpl/input/lang/en-US.rc
dll/cpl/input/lang/es-ES.rc
dll/cpl/input/lang/fr-FR.rc
dll/cpl/input/lang/he-IL.rc
dll/cpl/input/lang/it-IT.rc
dll/cpl/input/lang/ja-JP.rc
dll/cpl/input/lang/no-NO.rc
dll/cpl/input/lang/pl-PL.rc
dll/cpl/input/lang/pt-BR.rc
dll/cpl/input/lang/ro-RO.rc
dll/cpl/input/lang/ru-RU.rc
dll/cpl/input/lang/sk-SK.rc
dll/cpl/input/lang/sq-AL.rc
dll/cpl/input/lang/tr-TR.rc
dll/cpl/input/lang/uk-UA.rc
dll/cpl/input/lang/zh-CN.rc
dll/cpl/input/lang/zh-TW.rc
dll/cpl/input/resource.h
dll/cpl/input/settings_page.c

If the system language was changed, then the system should overwrite the preferred settings of font substitutes.
JIRA issue: [CORE-13246](https://jira.reactos.org/browse/CORE-13246)

input: Overwrite font substitutes settings on lang change

---

dll/win32/shell32/lang/ru-RU.rc
drivers/filters/fltmgr/CMakeLists.txt
drivers/filters/fltmgr/Filter.c
drivers/filters/fltmgr/Interface.c
drivers/filters/fltmgr/Messaging.c
drivers/filters/fltmgr/Misc.c
drivers/filters/fltmgr/Registry.c
drivers/filters/fltmgr/Registry.h
drivers/filters/fltmgr/fltmgr.h
drivers/filters/fltmgr/fltmgrint.h
modules/rostests/kmtests/CMakeLists.txt
modules/rostests/kmtests/fltmgr/CMakeLists.txt
modules/rostests/kmtests/fltmgr/fltmgr_load/CMakeLists.txt
modules/rostests/kmtests/fltmgr/fltmgr_load/fltmgr_load.c
modules/rostests/kmtests/fltmgr/fltmgr_load/fltmgr_user.c
modules/rostests/kmtests/fltmgr/fltmgr_register/CMakeLists.txt
modules/rostests/kmtests/fltmgr/fltmgr_register/fltmgr_reg_user.c
modules/rostests/kmtests/fltmgr/fltmgr_register/fltmgr_register.c
modules/rostests/kmtests/include/kmt_platform.h
modules/rostests/kmtests/include/kmt_test.h
modules/rostests/kmtests/kmtest/filter.c
modules/rostests/kmtests/kmtest/fltsupport.c
modules/rostests/kmtests/kmtest/kmtest.h
modules/rostests/kmtests/kmtest/testlist.c
modules/rostests/kmtests/kmtest_drv/kmtest_fsminifilter.c

Push my local branch across to master as the patch is getting a bit large. This is still WIP and none of this code is run in ros yet, so don't fret if you see ugly code or int3's dotted around.
[FLTMGR] Move the fltmgr forward a bit
- Implement handling of connections from clients
- Implement closing of client ports
- Add a basic message waiter queue using CSQ's (untested)
- Hand off messages for the comms object to be handled by the comms file
- Initialize the connection list
- Add a registry file which will contain lib functions for accessing filter service entries
[KMTEST] Initial usermode support for testing FS mini-filters
- Add base routines to wrap the win32 'Filter' APis
- Add support routines to be used when testing FS filter drivers
- Move KmtCreateService to a private routine …

[FLTMGR] Latest from my branch

---

dll/win32/shell32/dialogs/drive.cpp
dll/win32/shell32/dialogs/fprop.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/wine/shell32_main.h

Don't show error message when successful closing a disk property sheet.
JIRA issue: [CORE-14035](https://jira.reactos.org/browse/CORE-14035)
- Change the return value type of SH_ShowDriveProperties.
- Fix the return value of SH_ShowDriveProperties.
- Adapt DrivesContextMenuCallback and SH_ShowPropertiesDialog functions for this fix.

don't show error when closing disk prop sheet

---

dll/win32/iphlpapi/iphlpapi.spec
dll/win32/iphlpapi/iphlpapi_main.c
modules/rostests/apitests/iphlpapi/CMakeLists.txt
modules/rostests/apitests/iphlpapi/GetInterfaceName.c
modules/rostests/apitests/iphlpapi/testlist.c

Implement network interface name resolving functions.
JIRA issues: [CORE-13831](https://jira.reactos.org/browse/CORE-13831), [CORE-14033](https://jira.reactos.org/browse/CORE-14033)
Reference: https://github.com/boundary/wireshark/blob/master/capture_win_ifnames.c#L275
- Implement `NhGetInterfaceNameFromDeviceGuid`
- Unstub and implement `NhGetInterfaceNameFromGuid`

[IPHLPAPI] Implement interface name resolving functions

---

dll/win32/shell32/wine/shellpath.c

Fix a typo.
JIRA issue: [CORE-12580](https://jira.reactos.org/browse/CORE-12580)
See [CORE-12580 comment](https://jira.reactos.org/browse/CORE-12580?focusedCommentId=87704&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87704).

CORE-12580. Shell32: it is _WIN32_WINNT, not WIN32_WINNT

---

dll/win32/browseui/parsecmdline.cpp
modules/rostests/apitests/browseui/SHExplorerParseCmdLine.c
modules/rostests/apitests/shell32/SHParseDisplayName.cpp

Explorer should be able to parse relative paths specified in command line parameter, including paths from root directory (beginning with `\`) or from current directory.
JIRA issues: [CORE-12882](https://jira.reactos.org/browse/CORE-12882), [CORE-13847](https://jira.reactos.org/browse/CORE-13847)
This PR was expected to fix first issue, but it also **partially** fixes the second too! Partially because it allows to open `Fonts` folder, but not all available folders in a `PATH` environment variable.
- Fix SHExplorerParseCmdLine tests according to Windows 2003 behaviour
- Modify SHExplorerParseCmdLine to allow parsing relative paths from root or current directory
- Add more SHParseDisplayName tests to show that changes makes sense
Cc @yagoulas

[BROWSEUI] Improve relative path handling for explorer

---

base/applications/mscutils/servman/propsheet.c

Should fix the regression introduced in the last commit.

[SERVMAN] Fix return check on PropSheet_IsDialogMessage

---

modules/rostests/apitests/ntdll/NtApphelpCacheControl.c
modules/rostests/apitests/ntdll/NtLoadUnloadKey.c
modules/rostests/apitests/ntdll/RtlCopyMappedMemory.c

Let ntdll_apitest.exe run on WXP, for people who can't test on WS03.
JIRA issue: [ROSTESTS-293](https://jira.reactos.org/browse/ROSTESTS-293)
Link at execution, instead of at compilation.
- Use GetProcAddress("NtApphelpCacheControl"), instead of implicit link.
NtApphelpCacheControl; looking for review.

ROSTESTS-293. Let ntdll_apitest.exe run on WXP.

---

modules/rostests/apitests/ntdll/NtFreeVirtualMemory.c

Add an ApiTest, before fixing the actual code.
JIRA issue: [CORE-13126](https://jira.reactos.org/browse/CORE-13126)
- Code formatting fixes.
- Create `Test_NtFreeVirtualMemory_Parameters()`.

CORE-13126. Create Test_NtFreeVirtualMemory_Parameters().

---

ntoskrnl/cache/section/data.c
ntoskrnl/cache/section/fault.c
ntoskrnl/include/internal/mm.h
ntoskrnl/mm/ARM3/contmem.c
ntoskrnl/mm/ARM3/dynamic.c
ntoskrnl/mm/ARM3/i386/init.c
ntoskrnl/mm/ARM3/mdlsup.c
ntoskrnl/mm/ARM3/mminit.c
ntoskrnl/mm/ARM3/pagfault.c
ntoskrnl/mm/ARM3/pfnlist.c
ntoskrnl/mm/ARM3/pool.c
ntoskrnl/mm/ARM3/procsup.c
ntoskrnl/mm/ARM3/section.c
ntoskrnl/mm/ARM3/session.c
ntoskrnl/mm/ARM3/special.c
ntoskrnl/mm/ARM3/sysldr.c
ntoskrnl/mm/ARM3/virtual.c
ntoskrnl/mm/ARM3/zeropage.c
ntoskrnl/mm/amd64/page.c
ntoskrnl/mm/balance.c
ntoskrnl/mm/freelist.c
ntoskrnl/mm/marea.c
ntoskrnl/mm/section.c

Spin locks don't deadlock on UP, so this will allow better debugging.

Use inline functions to acquire/release the PFN lock. 

---

win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.c

This Pull Request fixes GetTextFace function to report the font face name correctly.
JIRA issue: [CORE-14071](https://jira.reactos.org/browse/CORE-14071)
- Initialize TEXTOBJ.FaceName member in TextIntRealizeFont function in "win32ss/gdi/ntgdi/freetype.c".
- Set the face name in NtGdiGetTextFaceW function by using TEXTOBJ.FaceName in "win32ss/gdi/ntgdi/text.c".

Fix NtGdiGetTextFaceW to report face name correctly

---

ntoskrnl/include/internal/kd.h
ntoskrnl/kd/kdio.c
ntoskrnl/kd/kdmain.c
ntoskrnl/kdbg/kdb_cli.c

Fix bugcheck when running ntdll_winetest:exception.
JIRA issue: [CORE-14057](https://jira.reactos.org/browse/CORE-14057)
This is in "working" state but will need some cleanup (consistency, comments etc).

Add SEH/probes to user-accessible kdbg functions

---

ntoskrnl/mm/ARM3/virtual.c

Fix NtFreeVirtualMemory() FreeType parameter checks.
JIRA issue: [CORE-13126](https://jira.reactos.org/browse/CORE-13126)
NB: Test committed in #150.

CORE-13126. Fix NtFreeVirtualMemory() FreeType parameter checks.

---

sdk/include/reactos/idl/pnp.idl

Fix a "WIN32_WINNT" typo.
JIRA issue: [CORE-12580](https://jira.reactos.org/browse/CORE-12580)
- [SDK] pnp.idl: Add a reminder comment about removed Vista/+ functions.

CORE-12580. Add a reminder comment about removed Vista/+ functions

---

drivers/ksfilter/swenum/CMakeLists.txt
drivers/ksfilter/swenum/swenum.rc

This adds version information to swenum.sys. The installer for DirectX 9.0 looks for this version info, and fails if is not found.
JIRA issue: [CORE-14112](https://jira.reactos.org/browse/CORE-14112)

[SWENUM] Add version info

---

hal/halx86/generic/memory.c
hal/halx86/include/halp.h

Fix potential integer overflow in HalpAllocPhysicalMemory on systems with more than 4GB RAM by using ULONG64 instead of ULONG_PTR for the physical address.

[HAL] Use 64 bits for physical addresses.

---

ntoskrnl/ps/quota.c

Fix return of uninitialized variable in PspSetQuotaLimits
CID-1322247

[NTOSKRNL] Fix return of uninitialized variable in PspSetQuotaLimits

---

modules/rostests/apitests/atl/CComObject.cpp
modules/rostests/apitests/atl/CMakeLists.txt
modules/rostests/apitests/atl/devenv/ATLTest.sln
modules/rostests/apitests/atl/devenv/CComObject.vcxproj
modules/rostests/apitests/atl/testlist.c
sdk/lib/atl/atlbase.h

Interface enumeration should not stop after a failing COM_INTERFACE_ENTRY_FUNC_BLIND.
(This can be useful for logging).
Test written against MS's ATL.

ATL: Fix for COM_INTERFACE_ENTRY_FUNC_BLIND

---

boot/freeldr/freeldr/arch/i386/pcmem.c
boot/freeldr/freeldr/include/arch/pc/pcbios.h

Add ACPI 3.0 to 6.2-A support, especially its validity bit.
JIRA issue: [CORE-13332](https://jira.reactos.org/browse/CORE-13332)
- Update ACPI definitions to latest (6.2-A) specification,
- Check entry validity from E.A. bit.
- Some (un)related minor code updates too.
I just want some early feedback, mainly wrt the 4 separate commits.

CORE-13332. PcMemGetBiosMemoryMap(): Update ACPI (Extended Attributes) support.

---

sdk/lib/atl/atlwin.h

Add the COMMAND_CODE_HANDLER macro and the CWindow::GetDlgItemText overload that takes a CString as parameter

Two ATL additions

---

win32ss/gdi/ntgdi/fillshap.c

Fixes a failed ASSERT.
JIRA issue: [CORE-14148](https://jira.reactos.org/browse/CORE-14148)

[WIN32K] Check for empty output rect in GreGradientFill

---

dll/win32/rasapi32/rasapi.c
dll/win32/rasapi32/rasapi32.spec

That's my patch from [CORE-10426](https://jira.reactos.org/browse/CORE-10426).

[RASAPI32] Add stub for RasGetConnectionStatistics

---

drivers/filters/mountmgr/mountmgr.c
drivers/hid/kbdhid/kbdhid.c
drivers/hid/mouhid/mouhid.c
drivers/input/sermouse/readmouse.c
drivers/network/ndis/ndis/control.c
drivers/network/ndis/ndis/io.c
drivers/usb/usbhub_new/usbhub.c
drivers/usb/usbport/usbport.c
drivers/wdm/audio/legacy/stream/pnp.c
modules/rostests/kmtests/kmtest_drv/kmtest_drv.c
modules/rostests/kmtests/npfs/NpfsHelpers.c
ntoskrnl/fstub/disksup.c
ntoskrnl/io/iomgr/rawfs.c
ntoskrnl/lpc/reply.c
sdk/lib/drivers/chew/workqueue.c
sdk/lib/drivers/rdbsslib/rdbss.c
sdk/lib/drivers/rxce/rxce.c

This avoids having to acquire the dispatcher lock, thus improving performance.

Use KeClearEvent instead of KeResetEvent where the previous state is not needed

---

base/applications/charmap_new/lang/ro-RO.rc

The new ReactOS Character Map lacks a Romanian translation implementation, barely any. This patch adds the translation file for CHARMAP_NEW.

[CHARMAP:NEW] Romanian language implementation

---

base/applications/charmap_new/lang/it-IT.rc

This patch contains the Italian translation file for charmap_new (ReactOS Character Map) considering nobody have done it before.

[CHARMAP:NEW] Italian language implementation

---

base/applications/charmap_new/charmap.rc

As of now, charmap.rc lacks proper indentation for macro preprocessors especially `#include`. 
This patch doesn't bring any fancy stuff or the like, it just fixes the missing indentation. It is better to have an indented code so that it makes everyone's life easier.

[CHARMAP:NEW] Adding some indentation

---

dll/win32/newdev/lang/ro-RO.rc

The PR itself is self-explanatory, not needed to describe more.

Wrong char in Romanian newdev translation fix

---

ntoskrnl/kd/i386/kdbg.c

I #undef'ed NDEBUG in File "ntoskrnl/kd/i386/kdbg.c", then my compiler complainted as follows:
```
../ntoskrnl/kd/i386/kdbg.c: In function 'KdPortInitializeEx':
../ntoskrnl/kd/i386/kdbg.c:117:17: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'PUCHAR' [-Werror=format]
cc1.exe: all warnings being treated as errors
[254/537] Building C object ntoskrnl/n...les/ntkrnlmp.dir/__/mm/i386/page.c.obj
ninja: build stopped: subcommand failed.
```
JIRA issue: [CORE-14174](https://jira.reactos.org/browse/CORE-14174)
s/%lx/%p/

ntoskrnl: fix DPRINT format specifier in kdbg.c

---

ntoskrnl/ex/keyedevt.c

Don't dereference ExpCritSecOutOfMemoryEvent when it was never referenced.

[NTOS:EX] Don't dereference a keyed event that was never referenced.

---

dll/win32/kernel32/client/proc.c

In my opinion, there is no reason to fail at image versions > 5.01 as long as we don't have a better way to deal with them.
This change already gets a simple "Hello World" compiled by VS 2017 regular "v141" toolchain to run under ReactOS.
It reports many missing apisets but prints its "Hello World" message. As soon as [Mark's work on apisets](https://github.com/learn-more/reactos/commits/apisets) is imported, these messages should vanish and many more NT6+ applications should be supported.

[KERNEL32] Accept images for NT 3.1 and higher instead of bailing out at image versions > 5.01

---

dll/win32/kernel32/client/version.c

Changes the useless print `VerifyVersionInfo -- Version mismatch` into something usable by including some info about the requested version.

[KERNEL32] Add version info to VerifyVersionInfo mismatch print.

---

dll/win32/usp10/usp10.c
dll/win32/usp10/usp10_internal.h
modules/rostests/winetests/usp10/usp10.c

This massively improves the performance of loading a large number of lines into an edit contorl.
I'm submitting this to Wine tonight after their code freeze is lifted, will update if I get any review from upstream. Putting it up here meanwhile...

[USP10] Re-use script caches. CORE-14192

---

base/shell/explorer/precomp.h
base/shell/explorer/trayntfy.cpp

Initial implementation of a watcher for the systray (notification area) that removes icons if the owning process dies or terminates without removing it.
This fixes a long time 'bug' in windows (win95 - win10) where notification icons can exist in the tray without an owner. Only when you move your mouse cursor over them do they disappear. 
If we don't want this on by default, I could add a checkbox to the taskbar setting to toggle this functionality?
https://i.imgur.com/MeMALd4.gif
https://i.imgur.com/NJNuDrD.gif

[EXPLORER] systray watcher

---

win32ss/user/ntuser/menu.c

Fix disabled menu item hardcoded colors.
JIRA issue: [CORE-14196](https://jira.reactos.org/browse/CORE-14196)
- Remove hardcoded colors
- Add dynamic colors using IntGetSysColor

[WIN32K:NTUSER] Fix hardcoded color for MF_GRAYED menu items

---

dll/cpl/desk/draw.c

Fix text color for disabled menu in classic theme preview.
JIRA issue: [CORE-14238](https://jira.reactos.org/browse/CORE-14238)
- Remove hardcoded RGB's
- Obtain actual scheme colors from `crColor` array

[DESK.CPL] Fix hardcoded colors in classic theme preview

---

win32ss/user/ntuser/menu.c

Correct the system color indices, that will fix CORE-14231 and all themes (including classic ones).
JIRA issue: [CORE-14231](https://jira.reactos.org/browse/CORE-14231)
Cc @yagoulas

[WIN32K:NTUSER] Fix color indices for themes

---

boot/freeldr/freeldr/arch/i386/i386vid.c

Silence harmless errors, which can be reported at every boot.
JIRA issue: [CORE-13496](https://jira.reactos.org/browse/CORE-13496)

CORE-13496. i386vid.c: Downgrade/Improve 3 false ERR() to WARN()

---

base/applications/sndvol32/dialog.c

This fixes the offset for the controls in the sndvol32 main dialog.
It will otherwise fail an assert.
JIRA issue: [CORE-9108](https://jira.reactos.org/browse/CORE-9108)

[SNDVOL32] Fix controls' offset

---

modules/rostests/kmtests/tcpip/TcpIp_user.c

Trivial code fix. No functional changes.
JIRA issue: [ROSTESTS-274](https://jira.reactos.org/browse/ROSTESTS-274)
- 1 s/ok_bool_true/ok/, overkill though harmless.
- 1 s/ntohs/htons/, typo though harmless.

ROSTESTS-274. TcpIpConnect: Fix a harmless typo

---

dll/win32/netcfgx/lang/da-DK.rc
dll/win32/netcfgx/lang/el-GR.rc
dll/win32/netcfgx/lang/en-US.rc
dll/win32/netcfgx/lang/hu-HU.rc
dll/win32/netcfgx/lang/id-ID.rc
dll/win32/netcfgx/lang/ja-JP.rc
dll/win32/netcfgx/lang/nl-NL.rc
dll/win32/netcfgx/lang/sk-SK.rc
dll/win32/netcfgx/lang/sv-SE.rc
dll/win32/netcfgx/netcfgx.c

It should look a little better both in the system tray and in the Network Connections folder.
Fix the capitalization to make it look better in the system tray and in the Network Connections folder.
At some point, numbering the network connections is needed but that's beyond my expertise level.

[NETCFGX] Rename 'Network connection' to 'Network Connection'.

---

ntoskrnl/cc/view.c
sdk/include/ndk/rtltypes.h

Fixes booting with msvc after the CcIdleDelay commit.

[NTOSKRNL] Fix CcIdleDelay initializer for old msvc versions

---

ntoskrnl/include/internal/amd64/mm.h
ntoskrnl/mm/ARM3/mminit.c

- Change MM_SYSTEM_SPACE_START to 0xFFFFF88000000000
- Move MI_DEBUG_MAPPING to the end of the system PTE range
- Add MI_SYSTEM_CACHE_START and MI_SYSTEM_CACHE_END, which is in the range that Vista uses as dynamic VA space for cache and other allocations
- Wrap x86 specific code that makes now invalid assumptions about the address space layout in #ifdef _M_IX86

[NTOS:MM] Make x64 address space layout more like Vista+

---

base/applications/cmdutils/timeout/lang/ro-RO.rc
base/applications/cmdutils/timeout/timeout.rc
dll/shellext/fontext/fontext.rc
dll/shellext/fontext/lang/ro-RO.rc

Romanian translations were both missing for FONTEXT and TIMEOUT (timeout utility). Here's the PR which includes the latest updates as of now.

[TRANSLATION] Romanian translation for FONTEXT and TIMEOUT

---

ntoskrnl/ke/bug.c

Suggested by @ThFabba in
JIRA issue: [CORE-14293](https://jira.reactos.org/browse/CORE-14293)
> We should fix the logging to get rid of that term

[NTOS:KE] Replace "Fatal System Error" with "BugCheck"

---

dll/cpl/openglcfg/general.c
win32ss/reactx/dxg/dd.c

Assumed fixes...
- [OPENGLCFG] Fix a Clang-Cl warning about IDC_DEBUG_OUTPUT.
Added as is in r74208 by khornicek.
- [DXG] Fix a Clang-Cl warning about DDHAL_CB32_CANCREATESURFACE.
Added as is in r74181 by @gasioreks.

CORE-14306. Fix 2 Clang-Cl "constant operand" warnings

---

sdk/include/asm/ks386.template.h
sdk/include/asm/ksx.template.h
sdk/include/ddk/fcb.h
sdk/include/ndk/i386/asm.h
sdk/include/ndk/peb_teb.h
sdk/include/psdk/winddi.h
sdk/include/psdk/winuser.h
sdk/include/psdk/ws2spi.h

fixing issue and some more SDK headers NT6 improvements
JIRA issue: [CORE-12596](https://jira.reactos.org/browse/CORE-12596)

[SDK] CORE-12596 fix NT6 building issues.

---

base/shell/explorer/syspager.cpp

WatchList gets declared as a single NULL pointer value and gets freed from the memory after. This is the correct behaviour, however in the 417 line, WatchList is created again but as a set of array objects with `new[]`. Freeing it later with `delete` but not `delete[]` will surely cause a undefined behaviour in the code.
Using `delete[]` for deleting the variable and its array should be the correct way to avoid unexpected results.
**NOTE:** The idea of making this PR is not mine. A guy named maddin200 (source post: [click me!](https://www.reactos.org/forum/viewtopic.php?f=13&t=16923)) noticed this issue and for some reason he  can't create a patch so I decided to create the pull request for him.

[EXPLORER] WatchList should be freed with delete[], not delete

---

base/shell/explorer/syspager.cpp

Assumed fix...
- "warning: expression result unused [-Wunused-value]"
Regressed in be2bf9b by @gedmurphy.

CORE-14306. Fix a Clang-Cl warning about Icon->ProcessId

---

modules/rostests/apitests/appshim/versionlie.c

Assumed fixes...
- "warning: expression result unused [-Wunused-value]"
Added as is in r71442 by @learn-more.

CORE-14306. Fix 2 Clang-Cl warnings about ok2

---

base/applications/sc/sc.h

Whether this feature was activated on purpose or not, I assume it is not needed anymore, 11.5 years later.
Noticed in
JIRA issue: [CORE-14260](https://jira.reactos.org/browse/CORE-14260)
- Comment `#define SCDBG` out.
Uncommented in r23868 by @gedmurphy.

[SC] Disable debug messages on user interface

---

dll/win32/shell32/wine/shell32_main.c

This patch reduces failures of SHGetFileInfo function. CORE-7159
Improve SHGetFileInfo.
JIRA issue: [CORE-7159](https://jira.reactos.org/browse/CORE-7159)

improve SHGetFileInfo

---

hal/halx86/include/halp.h
hal/halx86/up/pic.S
hal/halx86/up/pic.c

This uses wrapper functions to force tail call elimination, as already done in r71307.
JIRA issue: [CORE-14076](https://jira.reactos.org/browse/CORE-14076)
The practical issue is that we can end up with recursion too deep for the kernel stack if software interrupts are scheduled in quick succession. The linked Jira ticket gives an example; the original, [CORE-11123](https://jira.reactos.org/browse/CORE-11123), is another.
I see several solutions to this:
1. This PR. Create wrapper functions to force tail call elimination. This requires only small changes, and a small amount of assembly code, but has a bunch of duplication in the assembly, and feels a bit silly.
2. Write all of the corresponding functions in assembly to get complete control over the stack layout. This is what Microsoft …

RFC: Eliminate tail calls in all software interrupt handlers

---

modules/rostests/kmtests/npfs/NpfsHelpers.c
modules/rostests/kmtests/ntos_io/IoFilesystem.c

Assumed fixes...
- "warning: variable 'ShareAccess' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]"
Added as is in r62695 by @ThFabba.
- "warning: variable 'NameLength' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]"
Added as is in r69897 by @ThFabba.
- Also make an ExFreePoolWithTag() call conditional.
Added as is in r69897 by @ThFabba.

CORE-14306. Fix 3 Clang-Cl warnings in kmtests

---

ntoskrnl/cc/cacheman.c
ntoskrnl/cc/copy.c
sdk/include/ndk/cctypes.h

This avoids the following at the end of first stage:
```(ntoskrnl/cc/copy.c:568) Failed to request VACB: c000000d!```

Avoid read-ahead past end of file

---

modules/rostests/kmtests/ntos_fsrtl/FsRtlMcb.c

Addendum to 22037684e42e29abc99a9a280278b16305eaa2e2. (@HeisSpiter)
JIRA issue: [CORE-11819](https://jira.reactos.org/browse/CORE-11819)
- Result: check "== FALSE" not "= TRUE".
- Report compared values, not different ones.
I assume the different values were leftovers, weren't they?
`(ULONG) -1` seems unobvious: to be double-checked/documented?
Also, the rest of the file too could use `ok_bool_*()` and `ok_eq_*()`.
Tell me whether you want a second commit with that.

CORE-11819. Fix all FsRtlLargeMcbTestsFastFat() checks

---

dll/win32/iphlpapi/ipstats_reactos.c

This code was added as is in r8194.
- Obviously not `status`. Not current `numRoutes` either, I assume.

[IPHLPAPI] Fix getNumRoutes() return value, on Mib error

---

base/shell/explorer/syspager.cpp
base/shell/explorer/taskswnd.cpp
sdk/include/reactos/undocuser.h
win32ss/user/user32/windows/message.c
win32ss/user/winsrv/usersrv/harderror.c

Implement the hard error balloon

---

dll/win32/shell32/dialogs/folder_options.cpp

This PR fixes the item order of the tree view of Folder Options.
JIRA issue: [CORE-14393](https://jira.reactos.org/browse/CORE-14393)
- Fix Advanced_Compare function in "reactos/dll/win32/shell32/dialogs/folder_options.cpp".

[SHELL32] Fix item order in Folder Options

---

win32ss/user/winsrv/consrv/frontends/gui/guiterm.c

This partially reverts r58615.
JIRA issue: [CORE-13734](https://jira.reactos.org/browse/CORE-13734)

[WINSRV] Don't try to remove messages from the queue without dispatching them.

---

drivers/bus/acpi/main.c

Since **0.4.7** release, ReactOS is subject to [CORE-14134](https://jira.reactos.org/browse/CORE-14134). The symptom of this is the repetitive output of `Unsupported IOCTL: 294040` bloating the debug log and it doesn't stop regardless. It's annoying.

[BUS][ACPI] Silence the debug output of DPRINT1()

---

modules/rostests/kmtests/ntos_cc/CcCopyRead_drv.c
modules/rostests/kmtests/ntos_cc/CcMapData_drv.c

Fixes driver unload failing on Windows.
ROSTESTS-264 ROSTESTS-300

[KMTESTS:CC] Truncate file cache on uninitialize to avoid leaking a reference

---

modules/rostests/apitests/ntdll/NtAllocateVirtualMemory.c

JIRA issue: [ROSTESTS-297](https://jira.reactos.org/browse/ROSTESTS-297)
- Fix "Below 0x10000" check result.
- Create CheckSomeDefaultAddresses(), with additional checks.
Documented with help of SysInternals VMMap too.
Tested on WXP and ReactOS/r76032.

ROSTESTS-297. Fix/Extend ApiTest NtAllocateVirtualMemory on both WS03 and ROS

---

drivers/input/i8042prt/i8042prt.h
drivers/input/i8042prt/pnp.c

Fix Lenovo ACPI mistake when keyboard is not initializing.
JIRA issue: [CORE-14256](https://jira.reactos.org/browse/CORE-14256)
Sends 0xae to i8042 command register. SHOULD NOT AFFECT NON-PROBLEM MOTHERBOARDS!

Fix Lenovo ACPI mistake.

---

CMakeLists.txt
boot/CMakeLists.txt
boot/bootdata/packages/CMakeLists.txt
boot/freeldr/freeldr/CMakeLists.txt
sdk/cmake/CMakeMacros.cmake
sdk/include/asm/CMakeLists.txt
subsystems/mvdm/asm16.cmake
subsystems/mvdm/dos/CMakeLists.txt
subsystems/mvdm/ntvdm/CMakeLists.txt

This should get modern CMake versions to the same speed as our ancient RosBE version.

[CMAKE] Avoid the use of LOCATION properties

---

ntoskrnl/ex/harderr.c
ntoskrnl/ex/shutdown.c
ntoskrnl/include/internal/ex.h
ntoskrnl/po/poshtdwn.c
ntoskrnl/ps/process.c

- In addition to the hard-error port, reference also the process that handles the hard errors so that it doesn't disappear behind our back. On shutdown both the hard-error port and process are dereferenced.
- Forbid processes without the Tcb prvilege to perform a user-mode hard-error BSOD.
- Update Doxygen descriptions for NtRaiseHardError, ExRaiseHardError, ExpRaiseHardError and NtSetDefaultHardErrorPort.
- Don't hardcode flag values for DefaultHardErrorProcessing.
- Don't emit hard errors for the calling thread if hard errors have been disabled for this thread on user-mode side.
- ExRaiseHardError(): Protect strings copy to user-mode space inside a SEH block.
- Simplify NtRaiseHardError() by merging the terminating blocks. Return the status codes provided by the Ex(p)RaiseHardError() …

[NTOSKRNL] Enhancements for hard-error code

---

ntoskrnl/cc/cacheman.c
sdk/include/reactos/debug.h

- Define UNIMPLEMENTED_ONCE for "!DBG && _MSC_VER" too.
(Addendum to 81eb3bbceb518c331f3d8e4754ad61adc0e94d33.)
- Use UNIMPLEMENTED_ONCE instead of custom code.
(Rewrite e319f85e67b1d057fb1c0d0449a6756fa0d459ba.)

UNIMPLEMENTED_ONCE: Add a definition, Improve a use

---

dll/shellext/zipfldr/zipfldr.rc

Just a typo fix. Don't blame me, Mark Jansen was in a hurry while making the resources for ZIPFLDR implementation. :stuck_out_tongue_closed_eyes:

[ZIPFLDR] Typo fix

---

boot/CMakeLists.txt
boot/bootdata/packages/CMakeLists.txt
sdk/cmake/CMakeMacros.cmake

Fixes configuring with VSSolution.

[CMAKE] Use configuration-specific names for files generated by CMake.

---

dll/appcompat/apphelp/apphelp.h
dll/appcompat/apphelp/apphelp.spec
dll/appcompat/apphelp/hsdb.c
dll/appcompat/apphelp/sdbapi.c
dll/appcompat/apphelp/sdbread.c
dll/ntdll/ldr/ldrinit.c
media/sdb/sysmain.xml
modules/rostests/apitests/apphelp/db.cpp
modules/rostests/apitests/apphelp/testdb.xml
sdk/tools/xml2sdb/xml2sdb.cpp
sdk/tools/xml2sdb/xml2sdb.h

Allows shims to override the RosProcessCompatVersion.
The SHIMVERSIONNT is in base-10 to stay windows-compatible.

Set RosProcessCompatVersion from version shims

---

dll/win32/shell32/CFolder.cpp
dll/win32/shell32/CFolder.h
dll/win32/shell32/CFolderItemVerbs.cpp
dll/win32/shell32/CFolderItems.cpp
dll/win32/shell32/CFolderItems.h
dll/win32/shell32/CShellDispatch.cpp
dll/win32/shell32/CShellDispatch.h

This should fix `shell32_winetest shelldispatch` from crashing.
JIRA issue: [CORE-12955](https://jira.reactos.org/browse/CORE-12955)

[SHELL32] Sync CShellDispatch and family with wine.

---

dll/win32/kernel32/client/fiber.c

Addendum to ac620c2e8ea7a14e7175ce32d1bfa74585f9ff36.
Noticed on
JIRA issue: [CORE-14532](https://jira.reactos.org/browse/CORE-14532)
`(R:\src\master\dll\win32\kernel32\client\fiber.c:355) FlsAlloc: Got lpCallback 0x00CBDAE2, UNIMPLEMENTED!(R:\src\master\dll\win32\kernel32\client\fiber.c:355) FlsAlloc: Got lpCallback 0x00CC1F4E, UNIMPLEMENTED!WARNING: calling stub LCMapStringEx()`
@learn-more

[KERNEL32] FlsAlloc(): Add a missing '\n' to a DPRINT1()

---

dll/shellext/zipfldr/CZipExtract.cpp
dll/shellext/zipfldr/lang/en-US.rc
dll/shellext/zipfldr/lang/it-IT.rc
dll/shellext/zipfldr/lang/ro-RO.rc
dll/shellext/zipfldr/resource.h
dll/shellext/zipfldr/zipfldr.rc

The zip shell extension currently only supports English by default without any support for multilingual interface. Here I am implementing the support for other languages other than English just like in any software written here for ReactOS.
- Initial MUI implementation for Zip Shell Extension
- Romanian & Italian translations
- Typo fix in `IDD_PROPPAGEDESTIONATION` (should be IDD_PROPPAGEDESTINATION)

[ZIPFLDR] Implement MUI support

---

base/system/winlogon/lang/ro-RO.rc

The part of the Shutdown System dialog wasn't translated at all. Here I am providing this PR which covers the untranslated strings.

[TRANSLATION][WINLOGON] Romanian translation update

---

win32ss/printing/providers/localspl/jobs.c

@ColinFinck
- "warning: comparison of unsigned expression < 0 is always false [-Wtautological-unsigned-zero-compare]"
- "warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]"

CORE-14306. [LOCALSPL] Fix 2 Clang-Cl warnings about ullResult and "UserName"

---

base/applications/mspaint/common.h
base/applications/mspaint/imgarea.cpp
base/applications/mspaint/precomp.h
base/applications/mspaint/toolsettings.cpp
base/applications/mspaint/winproc.cpp

Fix Paint crash on zoom out.
JIRA issue: [CORE-14539](https://jira.reactos.org/browse/CORE-14539)
- Check the denominator for zero for both zoomed width and height.
- Do not allow to move zoom slider above possible position.
- Move commonly used `zoomTo` function into new header file.

[MSPAINT] Fix crash on zoom out

---

drivers/storage/class/class2/class2.c

The break statement is unnecessary because the goto on the line before it returns from the routine so it can never be reached.
JIRA issue: [CORE-14554](https://jira.reactos.org/browse/CORE-14554)
* Removal of the break statement

CORE-14554 Unreachable line

---

drivers/filesystems/fastfat/cleanup.c
drivers/filesystems/fastfat/fcb.c

Don't leak directories FILE_OBJECT, FCB and cache entries.
JIRA issue: [CORE-14557](https://jira.reactos.org/browse/CORE-14557)
Once a directory is crossed (opened or a child is opened), associated
FCB structure is created in FastFAT, but also a stream FO for caching.
Up to now, due to an extra reference taken by the stream file object,
even when the directory was no longer used, the directory was kept in
memory: the FCB was never deleted, the file object was never dereferenced,
and the cache never released.
The immediate effect of this bug is that our FAT driver was leaking every
directory that was used affecting the whole OS situation. In case of
directories intensive operation (like extraction the ReactOS source code
in ReactOS ;-)), we were just killin the whole OS RAM without any way …

[FASTFAT] Don't leak directories FILE_OBJECT, FCB and cache entries.

---

drivers/filesystems/fastfat/CMakeLists.txt
drivers/filesystems/fastfat/cleanup.c
drivers/filesystems/fastfat/close.c
drivers/filesystems/fastfat/fcb.c
drivers/filesystems/fastfat/iface.c
drivers/filesystems/fastfat/kdbg.c
drivers/filesystems/fastfat/vfat.h

This is a RFC PR, the purpose is not to nitpick on "You poorly named your variable". The purpose is to agree on the fact such KDBG extensions can be of use in ReactOS, and whether we want them, in that way or in another.
FastFAT here just serves as playground for prototyping the thing.
This KDBG extension relies on the fact that KdSystemDebugControl() is stubbed and is an open door to KDBG for drivers. That way, drivers can register a KDBG CLI callback. Then, each time data is submitted to KDBG, it will go throught every registered callback, including the driver.
Obviously, the day KdSystemDebugControl() will be properly implemented, it's likely this hack will be gone and the extension will be removed. But we're not here yet!

RFC: [FASTFAT] Introduce a KDBG extension.

---

sdk/cmake/msvc.cmake

Silence 5 current warnings, which are not bugs.
As suggested in #504.
Not touching `gcc.cmake`, as we have no build using that case.

CORE-14306. [CMAKE] USE_CLANG_CL: Add "-Wno-parentheses-equality"

---

drivers/filesystems/ntfs/btree.c

Assumed fix...
- "warning: logical not is only applied to the left hand side of this bitwise operator [-Wlogical-not-parentheses]"

CORE-14306. [NTFS] Fix 2 Clang-Cl warnings about CurrentKey->IndexEntry->Flags

---

base/services/umpnpmgr/umpnpmgr.c

Assumed fix...
- "warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]"

CORE-14306. [UMPNPMGR] Fix a Clang-Cl warning about "CSConfigFlags"

---

dll/cpl/desk/general.c

Assumed fix...
- "warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]"

CORE-14306. [DESK.CPL] Fix a Clang-Cl warning about "LogPixels"

---

dll/win32/devmgr/properties/misc.cpp

Assumed fix...
- "warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]"

CORE-14306. [DEVMGR] Fix a Clang-Cl warning about DriverInfoDetailData.SectionName

---

modules/rostests/apitests/appshim/dispmode.c

Cc @learn-more
- "warning: comparison of unsigned expression >= 0 is always true [-Wtautological-unsigned-zero-compare]"

CORE-14306. [APPSHIM_APITEST] Fix a Clang-Cl warning about n

---

dll/win32/shell32/dialogs/folder_options.cpp

JIRA issue: [CORE-12906](https://jira.reactos.org/browse/CORE-12906)
There are mistakes in usage of DeferWindowPos in #544. We should use the return value of DeferWindowPos. This PR fixes it.

[SHELL] Fix usage of DeferWindowPos (fix of #544)

---

base/applications/mspaint/imgarea.cpp

This fixes unexpected undo action when zooming out with right mouse
click.
The call sequence in OnLButtonUp is already correct.
CORE-14539

[MSPAINT] Fix call sequence in OnRButtonUp

---

base/applications/mspaint/winproc.cpp

Store subsequent changes to file selected via Save As.
Paint has erroneously been storing subsequent changes to Unnamed.bmp.
JIRA issue: [CORE-13291](https://jira.reactos.org/browse/CORE-13291)
This merely adds a forgotten `_tcsncpy`.

[MSPAINT] Store subsequent changes to file selected via Save As

---

boot/bootdata/hivecls.inf

Addendum to 313ded4. CORE-13293
This will fix right-click the bitmap file and choose the "Edit" menu item, when the file path have spaces in it.

[BOOTDATA] Use double quotes for mspaint file path

---

modules/rostests/apitests/ntdll/NtMapViewOfSection.c
ntoskrnl/mm/section.c

This fixes loading binaries with some packers (like MPRESS)
JIRA issue: [CORE-14556](https://jira.reactos.org/browse/CORE-14556)

Ignore IMAGE_SCN_CNT_UNINITIALIZED_DATA

---

sdk/include/reactos/version.cmake

"fatal: No names found, cannot describe anything." message,
when called without enough history, i.e. appveyor.yml `clone_depth: 5`.
Same issue with a local shallow clone.
[git-describe](https://www.git-scm.com/docs/git-describe/2.9.3)

[CMAKE] Add "--always" parameter to "git describe" call

---

configure.cmd
sdk/cmake/msvc.cmake

ReactOS does not compile anymore with it. ([ninja](https://ci.appveyor.com/project/SergeGautherie/reactos/build/VS9-ninja.reactos.appveyor.495), [msbuild](https://ci.appveyor.com/project/SergeGautherie/reactos/build/reactos.appveyor.488))
VS9 is already officially unsupported. ([CMake](https://www.reactos.org/wiki/CMake), [Building ReactOS](https://www.reactos.org/wiki/Building_ReactOS))
JIRA issue: [CORE-11836](https://jira.reactos.org/browse/CORE-11836)
- Remove Visual Studio 9 (2008) support
Question:

CORE-11836. [CONFIGURE][CMAKE] Remove Visual Studio 9 (2008) support

---

dll/win32/browseui/CMakeLists.txt

I guess duplication is useless, isn't it?
Double-added on [r65496](https://svn.reactos.org/svn/reactos?view=revision&revision=65496).
@AmineKhaldi, simple copypasta? Or, wild guess, was one meant to be maybe `explorer`?

[BROWSEUI] Remove a duplicated add_custom_command() call

---

drivers/filesystems/ext2/CMakeLists.txt
drivers/filesystems/reiserfs/CMakeLists.txt

With VS12, multiple "error C4189: '[...]': local variable is initialized but not referenced".
JIRA issue: [CORE-11280](https://jira.reactos.org/browse/CORE-11280)
- Remove unwanted quotation marks.

[EXT2FS][REISERFS] VSSolution: Disable C4189 errors, actually. CORE-11280

---

base/shell/rshell/CMakeLists.txt

I guess duplication is useless, isn't it?
Added on [r62448](https://svn.reactos.org/svn/reactos?view=revision&revision=62448), duplicated on [r62449](https://svn.reactos.org/svn/reactos?view=revision&revision=62449).
@gigaherz, simple copypasta? Or was one meant to be `explorer-new`?

[RSHELL] Remove a duplicated add_custom_command() call

---

modules/rostests/apitests/user32/RedrawWindow.c

Match `CreateWindowExW()` call.
Addendum to 7905efdf357ad830d4abba23a428dcd9e6195247 by @ThFabba.
JIRA issue: [CORE-13734](https://jira.reactos.org/browse/CORE-13734)

CORE-13734. RedrawWindow: Add a DestroyWindow() call

---

modules/rostests/winetests/msi/CMakeLists.txt

JIRA issue: [CORE-11836](https://jira.reactos.org/browse/CORE-11836)
- MSVC_IDE: Add an 'include_directories()'

CORE-11836. VSSolution: Fix MSI_WINETEST compile error with VS10 and VS12

---

drivers/network/afd/afd/bind.c
drivers/network/afd/afd/read.c

This avoids unlimited buildup of received data, leading to OOM.
JIRA issue: [CORE-14048](https://jira.reactos.org/browse/CORE-14048)

Respect the maximum receive buffer size for datagram sockets

---

base/setup/usetup/lang/bg-BG.h
base/setup/usetup/lang/bn-BD.h
base/setup/usetup/lang/cs-CZ.h
base/setup/usetup/lang/da-DK.h
base/setup/usetup/lang/de-DE.h
base/setup/usetup/lang/el-GR.h
base/setup/usetup/lang/en-US.h
base/setup/usetup/lang/es-ES.h
base/setup/usetup/lang/et-EE.h
base/setup/usetup/lang/fr-FR.h
base/setup/usetup/lang/he-IL.h
base/setup/usetup/lang/it-IT.h
base/setup/usetup/lang/ja-JP.h
base/setup/usetup/lang/lt-LT.h
base/setup/usetup/lang/ms-MY.h
base/setup/usetup/lang/nl-NL.h
base/setup/usetup/lang/pl-PL.h
base/setup/usetup/lang/pt-BR.h
base/setup/usetup/lang/ro-RO.h
base/setup/usetup/lang/ru-RU.h
base/setup/usetup/lang/sk-SK.h
base/setup/usetup/lang/sq-AL.h
base/setup/usetup/lang/sv-SE.h
base/setup/usetup/lang/tr-TR.h
base/setup/usetup/lang/uk-UA.h

As you guys know, ReactOS is in Alpha and barely stable. Having a notification concerning ReactOS' release status is critical as it informs the user the risks of running this operating system considering ReactOS is under heavy development and many bugs are still in the wild.
Displaying the said message in the 1st stage setup is a viable option.
Image URL: https://imgur.com/a/kpo0DtS
As you can see, I have only edited the `en-US.h` file because the actual statements aren't that perfect. For this reason, I've set the Pull Request in WIP state as I request review from the devs to check if the wording is alright (or there needs some changes so it can fit better). Once everything is OK I'll edit the other language files.

[USETUP] Display the ReactOS release status

---

dll/win32/syssetup/wizard.c

This update was missed in [r75495](https://svn.reactos.org/svn/reactos?view=revision&revision=75495).
@yagoulas
- "(sdk/lib/rtl/heappage.c:1329) corrupted suffix pattern"
detected at
`dll/win32/syssetup/wizard.c:2672 (InstallWizard)`
- Add an ASSERT(), as hinted by Mark Jansen.
- Add a few comments.
- Remove a few extra blank lines.

[SYSSETUP] Fix a DPH report about dwPageCount

---

hal/halx86/up/pic.c

- Add a cast to `PVOID` and a comment.
- Also add an unrelated comment.

CORE-14306. [HALX86] Fix a Clang-Cl warning about KiUnexpectedInterrupt

---

sdk/lib/delayimp/delayimp.c

Assumed fixes...
I don't have MsVC. This PR may need different solutions.
- "warning: 'extern' variable has an initializer [-Wextern-initializer]"
Added as is in r71190 by @learn-more.
Plus:
-  Fix/Merge definitions of __pfnDliNotifyHook2 and __pfnDliFailureHook2.
NB: They are already declared `extern` in the `.h`.

CORE-14306. Fix 2 Clang-Cl warnings about __pfnDliNotifyHook2Default and __pfnDliFailureHook2Default

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/OpenAs_RunDLL.cpp
modules/rostests/apitests/shell32/testlist.c

This PR will add tests of OpenAs_RunDLLA and OpenAs_RunDLLW functions in shell32.
[ROSTESTS-310](https://jira.reactos.org/browse/ROSTESTS-310)

[SHELL32][APITESTS] Add tests of OpenAs_RunDLL

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/ShellState.cpp
modules/rostests/apitests/shell32/testlist.c

This PR adds testcase for SHELLSTATE structure, ShellState registry value and SHGetSettings function.
JIRA issue: [CORE-12822](https://jira.reactos.org/browse/CORE-12822)
- Add file "modules/rostests/apitests/shell32/ShellState.cpp".
- Modify file "modules/rostests/apitests/shell32/CMakeLists.txt".
- Modify file "modules/rostests/apitests/shell32/testlist.c".

[SHELL32][APITESTS] Add test of ShellState

---

CMakeLists.txt

Matching whats currently in rosbe
Remove policy checks already implied by the minimum version
Much of the cmake code in reactos can be simplified using features from cmake 3.0+, and as the patched version of cmake in rosbe is currently required it seems needless to restrict reactos to the cmake 2.8 feature set

Bump minimum cmake version to 3.2

---

modules/rostests/apitests/netapi32/DsRoleGetPrimaryDomainInformation.c

Added as is on [r75208](https://svn.reactos.org/svn/reactos?view=revision&revision=75208).
@ColinFinck
NB:
This PR is not aimed at fixing the main DPH issue.
- Fix a NULL dereference of pInfo
With DPH enabled,
{{
Unhandled exception
ExceptionCode:    c0000005
Faulting Address:        0
...
modules/rostests/apitests/netapi32/DsRoleGetPrimaryDomainInformation.c:23 (func_DsRoleGetPrimaryDomainInformation)
...
}}

[NETAPI32_APITEST] Fix a NULL dereference of pInfo

---

sdk/tools/log2lines/log2lines.c

Avoids half-uninitialized value on, i.e., Linux 64-bit (with ReactOS 32-bit).
JIRA issue: [CORE-14737](https://jira.reactos.org/browse/CORE-14737)
- translate_line(): Let 'offset' be an 'unsigned int', instead of a 'size_t'

CORE-14737. [LOG2LINES] translate_line(): Let 'offset' be an 'unsigned int', instead of a 'size_t'

---

base/applications/regedit/regproc.c

This bug was found when i try to import *.reg with huge HEX value (about 500 and much more lines of hex text)
Such a big file i got exporting values from HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TrayNotify on windows XP

[REGEDIT] fix importing very big *.reg files (HEX values commonly)

---

dll/win32/shell32/shlexec.cpp

This PR will implement the OpenAs_RunDLLA and OpenAs_RunDLLW functions in shell32.
JIRA issue: [CORE-14751](https://jira.reactos.org/browse/CORE-14751)

[SHELL32] Implement OpenAs_RunDLLA/W

---

dll/win32/shell32/folders/CFSFolder.cpp

#595 failed at non-Desktop folder. We should use ILGetDisplayNameExW instead of SHGetPathFromLDList to get path from psf and pidl.
JIRA issue: [CORE-9196](https://jira.reactos.org/browse/CORE-9196)

[SHELL32] Fix desktop.ini folder icon again (retrial of #595)

---

dll/win32/browseui/shellbrowser.cpp

This PR will enable the "Folder Options" menu item in Explorer.
JIRA issue: [CORE-11141](https://jira.reactos.org/browse/CORE-11141)

[BROWSEUI][EXPLORER] Enable the 'Folder Options' menu item

---

base/applications/regedit/regproc.c
dll/win32/shell32/folders/CRecycleBin.cpp

Function TRASH_CanTrashFile() would always fail because GetVolumeInformationW() requires only the base root path. The path (stored in buffer wszRootPathName) was not being stripped correctly.
Note this issue [CORE-12340] appears to have regressed and is currently in reactos:master.
JIRA issue: [CORE-12340](https://jira.reactos.org/browse/CORE-12340)
- Remove PathRemoveFileSpecW as this did nothing relevant
- PathAddBackslashW is redundant as PathStripToRootW already has a backslash
- Added a function header
- Added my name to file header
- Cleaned up some comments near the change to be more clearer.
- Added some more debug information to the ERR when GetVolumeInformationW fails

[SHELL32] Fixed TRASH_CanTrashFile() sending the wrong path string to GetVolumeInformationW()

---

dll/win32/newdev/lang/ru-RU.rc

In Russian locale, a portion of text is truncated in Driver Installation Wizard dialog especially when the driver hasn't been installed properly.
URL Image -- https://imgur.com/a/Q2kewWS
Issue ID -- [CORE-14761](https://jira.reactos.org/browse/CORE-14761)

[NEWDEV] Fix a truncated text

---

dll/win32/shell32/folders/CDrivesFolder.cpp

This PR will properly show the custom icon for the optical disk with file "autorun.inf".
JIRA issue: [CORE-14766](https://jira.reactos.org/browse/CORE-14766)

[SHELL32] Enable custom CD/DVD icons

---

dll/win32/shell32/wine/shellpath.c

Add the "desktop.ini" files to the special folders to realize the custom icons of them.
JIRA issue: [CORE-10045](https://jira.reactos.org/browse/CORE-10045)

[SHELL32] Add missing desktop.ini files

---

win32ss/gdi/ntgdi/freetype.c

This PR refactors font engine codes. 
JIRA issue: [CORE-13065](https://jira.reactos.org/browse/CORE-13065)
The target source is "win32ss/gdi/ntgdi/freetype.c".
- Add "g_" prefix to global variables.
- Make the locking macros function-like.

[FONT][FREETYPE] Refactor global variable names and locking

---

base/applications/notepad/dialog.c

- "...\dialog.c(365) : error C4133: 'function' : incompatible types - from 'ENCODING *' to 'int *'"
* See https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=ReadText
* `ENCODING` is an `enum`.

CORE-7538. [NOTEPAD] Fix a MSVC warning about Globals.encFile

---

base/applications/notepad/dialog.c

Trivial addendum to #648 and 97df61e, while we are all there.

[NOTEPAD] Globals.encFile: explicitly cast to ENCODING

---

win32ss/gdi/eng/bitblt.c
win32ss/gdi/eng/bitblt_new.c
win32ss/gdi/ntgdi/rect.h

[WIN32K] Implement RECTL_bClipRectBySize() and use it in IntEngBitBlt() to clip the target rect against the bounds of the target surface. Also clip the source rect against the source surface. Fixes remaining part of CORE-14463

CORE-14463 Fix possible out of bounds access in EngBitBlt

---

win32ss/user/ntuser/clipboard.c
win32ss/user/user32/windows/clipboard.c

This PR will fix the GetClipboardData function for the synthesized text formats (CF_TEXT, CF_OEMTEXT and CF_UNICODETEXT).
JIRA issue: [CORE-11471](https://jira.reactos.org/browse/CORE-11471)

[WIN32SS] Fix NtUserGetClipboardData for text paste

---

sdk/include/reactos/mc/errcodes.mc
sdk/include/reactos/mc/neteventmsg.mc
sdk/include/reactos/mc/netmsgmsg.mc

* Latest VS does not like half translated files
* errcodes.mc is duplicated in kernel32
* It would probably be better to separate each language into it's own file, but we need a build mechanism for that

[MC] Fix build of message text files for latest VS version

---

boot/freeldr/freeldr/arch/i386/pcmem.c

Improve/Add FreeLdr logs.
JIRA issues: [CORE-13332](https://jira.reactos.org/browse/CORE-13332) and [CORE-14150](https://jira.reactos.org/browse/CORE-14150)
- pcmem.c: Improve output strings. No functional changes. CORE-13332
- PcMemGetBiosMemoryMap(): Add a default handling of entry with "EA.ErrorLog = 1". CORE-14150

CORE-14150. PcMemGetBiosMemoryMap(): Add a default handling of entry with "EA.ErrorLog = 1"

---

win32ss/user/ntuser/painting.c
win32ss/user/ntuser/window.c
win32ss/user/ntuser/winpos.c

In https://svn.reactos.org/svn/reactos/trunk/reactos/win32ss/user/ntuser/painting.c?r1=73532&r2=73531&pathrev=73532
correct code in IntSendChildNCPaint() has been disabled and been replaced by other one, supposedly to fix [CORE-12085](https://jira.reactos.org/browse/CORE-12085) and [CORE-12071](https://jira.reactos.org/browse/CORE-12071), however this new code introduced subtle painting problems like hangs in some situations (last in date is [CORE-14763](https://jira.reactos.org/browse/CORE-14763)).
This PR aims at re-enabling the original code.
JIRA issue: [CORE-14763](https://jira.reactos.org/browse/CORE-14763)
It fixes the testbots:
(Old tests)
https://build.reactos.org/builders/Test%20KVM/builds/20737
Tests results: https://www.reactos.org/testman/compare.php?ids=61203,61219
(New …

[WIN32K:NTUSER] Re-enable the correct original code in IntSendChildNCPaint. Fixes painting hangs under diverse situations.

---

dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/CShellLink.h

This PR will improve display and UI in the shortcut dialog.
JIRA issue: [CORE-11407](https://jira.reactos.org/browse/CORE-11407)
- Use strdupW instead of HeapAlloc.
- Unimplement Extract method.
- Add CreateShortcutIcon method to create an arrowed icon.
- Add BOOL m_bInitializing member to determine the moment is in initialization.
- Implement CShellLink::Extract.

[SHELL32] improve CShellLink a little

---

dll/win32/shell32/shlexec.cpp

Based on a patch by @learn-more.
JIRA issue: [CORE-14469](https://jira.reactos.org/browse/CORE-14469)

[SHELL32] lpDirectory must have priority in ShellExecuteEx

---

win32ss/user/ntuser/defwnd.c
win32ss/user/ntuser/window.c
win32ss/user/ntuser/window.h
win32ss/user/ntuser/winpos.c

This PR will fix the display status of owned popup windows.
An owned popup window should be hidden when its owner window was minimized.
JIRA issue: [CORE-14818](https://jira.reactos.org/browse/CORE-14818), [CORE-12252](https://jira.reactos.org/browse/CORE-12252), [CORE-13168](https://jira.reactos.org/browse/CORE-13168), [CORE-3326](https://jira.reactos.org/browse/CORE-3326), and [CORE-14824](https://jira.reactos.org/browse/CORE-14824).
Splitted from #668.
- Add IntWinListOwnedPopups function.
- Fix ShowWindow and ShowOwnedPopups functions.

[USER32][WIN32SS] Fix display of owned popup windows

---

dll/win32/windowscodecs/info.c

Cherry-pick https://source.winehq.org/git/wine.git/commit/90518ebd2ca14568879831a5a87685a8385a21d7
- "...\info.c(2163) : warning C4028: formal parameter 1 different from declaration"

CORE-7538. [WINDOWSCODECS] Fix an MSVC warning about get_decoder_info()

---

base/shell/explorer/startmnucust.cpp

Right now, the create shortcut dialog drops custom shortcuts in the Start Menu folder. This places the shortcuts in the favorites portion of the start menu. This commit fixes it so the shortcut is dropped into the Start Menu\Programs folder like expected.
JIRA issue: [CORE-10782](https://jira.reactos.org/browse/CORE-10782)

CORE-10782 [EXPLORER] Fix creation of shortcuts in the start menu.

---

modules/rostests/kmtests/CMakeLists.txt
modules/rostests/kmtests/kmtest_drv/structs.c
sdk/include/xdk/iotypes.h

Got broken with #516
Hopefully fixes stuff like:
JIRA issue: [CORE-14782](https://jira.reactos.org/browse/CORE-14782)
C_ASSERTS created in a winddk v 3790.1830 environment.

Fix IO_STACK_LOCATION alignment

---

dll/win32/lpk/lpk.c
dll/win32/lpk/ros_lpk.h

Added additional code in case BIDI_reorder doesn't create the lpGlyphs array, fixes CORE-14732.
ExtTextOutW code changes are similar on how wine handles if lyGlyphs array is NULL.
Added memory management in LpkExtTextOut
Refactored some codepaths in LpkGetCharacterPlacement
JIRA issue: [CORE-14732](https://jira.reactos.org/browse/CORE-14732)
No functional changes unless the above mentioned error occurs.
Thanks to @Doug-Lyons for bringing out the issue and finding the cause of it.

[LPK] Winetest Crash fix + code refactoring/changes

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-11536](https://jira.reactos.org/browse/CORE-11536)
This PR will change the type of the 2nd argument of IntRequestFontSize function in file "win32ss/gdi/ntgdi/freetype.c"
Retrial of #706.

[WIN32SS][FONT] Change the type of 2nd argument of IntRequestFontSize

---

win32ss/gdi/eng/engobjects.h

JIRA issue: [CORE-11536](https://jira.reactos.org/browse/CORE-11536)
This PR will add 5 members to FONTGDI structure.
They are the precomputed font metrics (not used yet).
Retrial of #706.

[WIN32SS][FONT] Add 5 members to FONTGDI structure

---

base/applications/rapps/gui.cpp

I found it unintuitive that each time I selected some software for installation, it wasn't automatically deselected after installation. I kept re-triggering the same installation a few times before I realized I had to manually uncheck the checked packages.
Deselect installed apps after installation.

[RAPPS] Deselect apps after installing

---

dll/cpl/usrmgr/usrmgr.c

I hope it's pretty clear what I'm wanting to do. The tab is not needed and it does nothing at the moment. So lets disable it.

Disable Extra tab in usrmgr

---

ntoskrnl/io/pnpmgr/pnpmgr.c

```
kd> kp
ChildEBP RetAddr  
f7923354 80412f7a nt!memmove+0x48
f792342c 80428bc6 nt!CmSetValueKey(struct _CM_KEY_CONTROL_BLOCK * Kcb = 0xe105c890, struct _UNICODE_STRING * ValueName = 0xf7923464 "ActiveService", unsigned long Type = 1, void * Data = 0x00000000, unsigned long DataLength = 2)+0x46a [r:\src\master\ntoskrnl\config\cmapi.c @ 812]
f79234e8 8054a95b nt!NtSetValueKey(void * KeyHandle = 0x800007d4, struct _UNICODE_STRING * ValueName = 0xf7923618 "ActiveService", unsigned long TitleIndex = 0, unsigned long Type = 1, void * Data = 0x00000000, unsigned long DataSize = 2)+0x266 [r:\src\master\ntoskrnl\config\ntapi.c @ 721]
f7923510 805487d4 nt!KiSystemCallTrampoline(void * Handler = 0x80428960, void * Arguments = 0xf79235d8, unsigned long StackBytes = 0x18)+0x1b …
```

[NTOSKRNL] Fix a nullptr dereference in IopStartDevice

---

ntoskrnl/ex/init.c
ntoskrnl/kd/kdio.c
ntoskrnl/kd64/kdinit.c

This fixes the "debug log" part of the issue.
JIRA issue: [CORE-12321](https://jira.reactos.org/browse/CORE-12321)
- Round memory size up. Assumed to better match actual physical RAM size.

CORE-12321. Round memory size up, "debug log" part

---

base/system/smss/smss.c
boot/environ/lib/misc/rtlcompat.c
boot/freeldr/freeldr/arch/i386/pcmem.c
boot/freeldr/freeldr/lib/debug.c
drivers/bus/acpi/buspdo.c
drivers/bus/pcix/arb/tr_irq.c
drivers/bus/pcix/enum.c
drivers/bus/pcix/intrface/agpintrf.c
drivers/bus/pcix/intrface/busintrf.c
drivers/bus/pcix/intrface/cardbus.c
drivers/bus/pcix/intrface/devhere.c
drivers/bus/pcix/intrface/lddintrf.c
drivers/bus/pcix/intrface/locintrf.c
drivers/bus/pcix/intrface/pmeintf.c
drivers/bus/pcix/intrface/routintf.c
drivers/bus/pcix/utils.c
modules/rostests/kmtests/npfs/NpfsHelpers.c
ntoskrnl/config/cmconfig.c
ntoskrnl/config/cmparse.c
ntoskrnl/config/cmvalche.c
ntoskrnl/ex/callback.c
ntoskrnl/include/internal/cm.h
ntoskrnl/po/power.c
sdk/lib/cmlib/cmindex.c
sdk/lib/cmlib/cmlib.h
sdk/lib/rtl/assert.c
sdk/tools/mkhive/rtl.c

More consistency with/without message.
Though not using an all-on-one-line format as elsewhere.
- [REACTOS] RtlAssert(): use "%lu" as LineNumber format
- [CMLIB] Simplify an ASSERTMSG() as an ASSERT()
- [REACTOS] Improve ASSERTMSG() Message values

Improve RtlAssert(..., Message) handling

---

dll/win32/shell32/shlexec.cpp
modules/rostests/apitests/shell32/ShellExecCmdLine.cpp

This PR fix my careless mistake of ShellExecCmdLine.
JIRA issue: [CORE-14886](https://jira.reactos.org/browse/CORE-14886)

[SHELL32] Fix a careless mistake of ShellExecCmdLine

---

base/shell/explorer/trayclock.cpp
win32ss/gdi/eng/engobjects.h
win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.c
win32ss/user/ntuser/draw.c
win32ss/user/ntuser/nonclient.c
win32ss/user/ntuser/painting.c
win32ss/user/rtl/text.c

This PR aims to fix the font metrics.
JIRA issue: [CORE-11536](https://jira.reactos.org/browse/CORE-11536)
Retrial of #706.
[V] FIXED: Total Commander 8.52 setup: font displayed too large
https://jira.reactos.org/browse/CORE-11620
[V] FIXED: CORE-14378: Effective File Search 6.8.1 german localization text rendering issues
https://jira.reactos.org/browse/CORE-14378
[V] FIXED: CORE-9767: Font garbage in register splash screen in Foxit Reader 7.1.5
https://jira.reactos.org/browse/CORE-9767
[V] FIXED: Calipers-1 is not displayed correctly.
https://jira.reactos.org/browse/CORE-14302
[V] FIXED: some msi-Installers draw their dialogs too large (example: Click-N-Type Virtual Keyboard 3.03.0412)
https://jira.reactos.org/browse/CORE-13161
[V] FIXED: Irfanview 4.50 font in zoom combobox displayed …

[WIN32SS][FONT] Fix font metrics (retry)

---

modules/rosapps/applications/sysutils/systeminfo/CMakeLists.txt
modules/rosapps/applications/sysutils/systeminfo/systeminfo.c

Fix various bugs in `systeminfo` utility and add SMBIOS support.
- Fix output of registry strings
- Fix output of install date
- Remove hardcoded `To Be Filled By O.E.M.` strings (these are known and reserved values in some motherboards)
- Print actual strings from SMBIOS

[SYSTEMINFO] Fix various bugs and add SMBIOS support

---

win32ss/user/rtl/text.c

This PR will fix DrawText function behaviour wrt DT_CALCRECT | DT_VCENTER.
JIRA issue: [CORE-14896](https://jira.reactos.org/browse/CORE-14896)
The test program: https://jira.reactos.org/secure/attachment/47925/TnB3.zip
BEFORE:
AFTER:
WIN2K3:
WIN10 JAPANESE:

[WIN32SS] Fix DrawText wrt DT_CALCRECT | DT_VCENTER

---

win32ss/gdi/ntgdi/freetype.c

This PR will support the MS symbol encoding (FT_ENCODING_MS_SYMBOL) in our font engine.
JIRA issue: [CORE-14907](https://jira.reactos.org/browse/CORE-14907), [CORE-13269](https://jira.reactos.org/browse/CORE-13269)
This will fix display of Anastasia font. And replacing our Marlett font with Windows' Marlett font is also fixed.

[FONT][WIN32SS] Support MS symbol encoding

---

ntoskrnl/mm/marea.c

Revert unwanted part of r12728.
JIRA issue: [CORE-12729](https://jira.reactos.org/browse/CORE-12729)

CORE-12729. [NTOS:MM] s/MmFreeMemoryAreaByNode/MmFreeMemoryArea/ in a DPRINT()

---

ntoskrnl/se/sd.c

Prevents pool corruption on x64

[NTOS:SE] Fix SeSetSecurityDescriptorInfoEx

---

CMakeLists.txt

Better be explicit immediately, than fail later without a clue.
JIRA issue: [CORE-14607](https://jira.reactos.org/browse/CORE-14607)
Questions:
No: errors with "CMake 3.11.1 + msbuild".
No, as errorring out here is refused, so build will warn and continue.

CORE-14607. [REACTOS] Warn if not using RosBE custom CMake

---

win32ss/gdi/ntgdi/freetype.c

It's better to ignore the identical substitution mappings in loading the font substitutions.

[FONT][WIN32SS] Ignore identical substitution mappings in IntLoadFontSubstList

---

dll/win32/oleaut32/vartype.c

Mininal cherry-pick Alexandre Julliard https://source.winehq.org/git/wine.git/commit/18f7ec3670375f6389b36527fbfe1216fe795e53
- "...\vartype.c(3808) : warning C4028: formal parameter 2 different from declaration"

CORE-7538. [OLEAUT32] Fix an MSVC warning about VarCyMul()

---

base/system/smss/pagefile.c
dll/win32/kernel32/client/file/disk.c
ntoskrnl/ps/query.c

The PROCESS_DEVICEMAP_INFORMATION  union has 2 fields, one is a handle, the other one is a structure of 36 bytes (independent of architecture). The handle forces 64 bit alignment on 64 bit builds, making the structure 4 bytes bigger than on 32 bit builds. The site is checked in NtQueryInformationProcess (case ProcessDeviceMap). The expected size on x64 is the size of the Query structure without alignment. autocheck correctly passes the site of the Query union member, while smss passes the full size of PROCESS_DEVICEMAP_INFORMATION. Packing the structure is not an option, since it is defined in public headers without packing. Using the original headers sizeof(PROCESS_DEVICEMAP_INFORMATION) is 0x28, sizeof(PROCESS_DEVICEMAP_INFORMATION::Query) is 0x24.

[NTOS:PS] Fix an issue with PROCESS_DEVICEMAP_INFORMATION  size on x64

---

win32ss/user/user32/windows/class.c

This must be done field by field, since the alignment of the structures is different on _WIN64

[USER32] Fix copying from WNDCLASS to WNDCLASSEX

---

boot/freeldr/freeldr/include/mm.h
boot/freeldr/freeldr/lib/mm/meminit.c

On x64 we only map 1GB of pages, so adjust MM_MAX_PAGE accordingly and also respect that value when searching for the best location of the page lookup table.

[FREELDR] Fix calculation of page lookup table

---

boot/freeldr/freeldr/ntldr/wlregistry.c

This happened for the livecd, where the cdfs driver was inserted twice - once since it is the driver for the boot device, and the 2nd time, because it was specified in the registry - which was then initialized twice by the kernel, leading to a name conflict when trying to create another device object, which resulted in the newly created device object to be dereferenced again and the driver unloaded. This can be seen from the debug message "(ntoskrnl\mm\ARM3\sysldr.c:955) Leaking driver: cdfs.sys"

[FREELDR] Don't insert a driver into the BootDriver list twice

---

sdk/tools/log2lines/config.h

Work around some "7z" dealing with files not named "*.iso" as "Cab" type.
JIRA issue: [CORE-14734](https://jira.reactos.org/browse/CORE-14734)
- Enforce "Iso" type when unpacking the Iso file

CORE-14734. [LOG2LINES] Enforce "Iso" type when unpacking the Iso file

---

appveyor.yml

Disabled by default, though ready to be enabled.
As in, to be used by people (as a reference), not to be built on every commit (unless that would be wanted).
Related to work on
JIRA issue: CORE-11836

[APPVEYOR] Add 'BuildType: "vssolution"'

---

dll/win32/kernel32/client/sysinfo.c
modules/rostests/apitests/kernel32/SystemFirmware.c
modules/rostests/apitests/kernel32/precomp.h
ntoskrnl/ex/sysinfo.c

Get rid of my hacks in kernel32 and implement SystemFirmwareTableInformation class!
- Extend `kernel32_apitest`: add SystemFirmwareTableInformation tests
- `kernel32`: Implement system firmware functions properly
- `ntos:ex`: Implement SystemFirmwareTableInformation class
Thanks goes to @learn-more for help with implementation! :relaxed:

Get rid of my hacks in kernel32 and implement SystemFirmwareTableInformation class

---

base/system/services/database.c
base/system/winlogon/screensaver.c
sdk/include/reactos/undocuser.h
win32ss/include/ntuser.h
win32ss/user/ntuser/desktop.c
win32ss/user/ntuser/desktop.h
win32ss/user/ntuser/main.c
win32ss/user/ntuser/misc.c
win32ss/user/ntuser/shutdown.c
win32ss/user/ntuser/sysparams.c
win32ss/user/ntuser/userfuncs.h
win32ss/user/ntuser/winsta.c
win32ss/user/ntuser/winsta.h
win32ss/user/user32/misc/winsta.c
win32ss/user/winsrv/consrv/frontends/gui/guiterm.c
win32ss/user/winsrv/usersrv/harderror.c

- Additions to handle calls to CreateWindowStation with a NULL or empty provided window station name.
I expect some fixes in user32:winstation winetests.
- TODO:
JIRA issue: [CORE-11933](https://jira.reactos.org/browse/CORE-11933)
Test case is Git-for-Windows' mintty console, which uses Cygwin.
The related code is: [fhandler_console.cc!fhandler_console::create_invisible_console()](https://github.com/cygwin/cygwin/blob/7b9bfb4136f23655e243bab89fb62b04bdbacc7f/winsup/cygwin/fhandler_console.cc#L2494)
https://reactos.org/testman/compare.php?ids=61114,61120,61123
While both user32:GetUserObjectInformation and user32:winstation show improvements, user32:desktop has regressed. I will investigate.

Additions for window station handling.

---

dll/win32/mshtml/htmlinput.c

Temporary fix, until WINESYNC replaces this function.
Similar to #688. See also [CORE-14829](https://jira.reactos.org/browse/CORE-14829).
- "...\htmlinput.c(1303) : warning C4028: formal parameter 2 different from declaration"

CORE-7538. [MSHTML] Fix an MSVC warning about HTMLInputElementImpl_fire_event()

---

base/shell/cmd/alias.c
base/shell/cmd/assoc.c
base/shell/cmd/batch.c
base/shell/cmd/batch.h
base/shell/cmd/cmd.h
base/shell/cmd/cmdinput.c
base/shell/cmd/dir.c
base/shell/cmd/dirstack.c
base/shell/cmd/for.c
base/shell/cmd/history.c
base/shell/cmd/misc.c
base/shell/cmd/parser.c
base/shell/cmd/path.c
base/shell/cmd/setlocal.c
base/shell/cmd/start.c
base/shell/cmd/where.c

Adapted from a patch by Jacob S. Preciado.
Add missing memory allocation NULL checks in the code.
I also want advice from people to know whether these WARN are OK or can be skipped.
JIRA issue: [CORE-8304](https://jira.reactos.org/browse/CORE-8304)

[CMD] Add missing memory allocation NULL checks. CORE-8304

---

dll/win32/mshtml/htmlanchor.c
dll/win32/mshtml/htmlarea.c
dll/win32/mshtml/htmlform.c

Cherry-pick Jacek Caban https://source.winehq.org/git/wine.git/commit/a660f673cb7d6d04e0f2a9a98cff439b5403365b
- "...\htmlanchor.c(769) : warning C4028: formal parameter 2 different from declaration"
- "...\htmlarea.c(427) : warning C4028: formal parameter 2 different from declaration"
- "...\htmlform.c(757) : warning C4028: formal parameter 2 different from declaration"

CORE-7538. [MSHTML] Fix 3 MSVC warnings about HTML*Element_handle_event()

---

CMakeLists.txt

Compiles fine with "CMake_321-ROS + VS10 + msbuild".
@AmineKhaldi
- Resolve [r67773](https://svn.reactos.org/svn/reactos?view=revision&revision=67773) "# FIXME: Remove the MSVC_IDE condition when the upcoming RosBE lands.".

[CMAKE] MSVC_IDE: Enable 'unset(CMAKE_IMPORT_LIBRARY_SUFFIX)'

---

base/setup/usetup/progress.c
base/setup/usetup/progress.h

Currently our USETUP lacks the option to choose a different colour from yellow, which is the default colour for the most of progress bars in the setup. This patch implements the required code to solve this. This allows me to begin the implementation of a reboot progress bar similar on 2000/XP USETUPs - you know what I mean.
- Add a new member to the struct, ``ProgressColour``
- Implement ``CreateProgressBarEx()`` and recreate ``CreateProgressBar()`` which will invoke the extended function
- Remove the hard-coded parameter on 222 line
**Video URL:** https://youtu.be/4s5tGsUhx1k

[USETUP] Implement CreateProgressBarEx()

---

base/system/services/rpcserver.c
modules/rostests/winetests/advapi32/service.c

Fix
```
Running Wine Test, Module: advapi32, Test: service
...
err:(dll/win32/rpcrt4/rpc_message.c:1864) we got fault packet with status 0x3e6
service.c:2147: Test failed: expected ChangeServiceConfig2A to succeed
```
JIRA issue: [CORE-14521](https://jira.reactos.org/browse/CORE-14521)
- [SERVICES] RChangeServiceConfig2A(): Zero-Initialize InfoW variable
- [ADVAPI32_WINETEST] Restore service.c changes from 3c1b7834e1

CORE-14521. [SERVICES] RChangeServiceConfig2A(): Zero-Initialize InfoW variable

---

dll/win32/shell32/CShellLink.cpp

remove some dead code + check PathUnExpandEnvStringsW for success (don't try to use un-initialized crap)

Small CShellLink fixes

---

dll/ntdll/ldr/ldrinit.c
modules/rostests/apitests/ntdll/CMakeLists.txt
modules/rostests/apitests/ntdll/RtlDosApplyFileIsolationRedirection_Ustr.c

Currently, when loading dlls, the manifest from the main executable is always used.
This is because the manifest prober for a dll lives in kernel32, and that was only loaded when the application links against it explicitly.
So there were cases, when the process could fail initialization if one of the earlier imported modules needed its own manifest.
By manually loading kernel32 in `LdrpInitializeProcess` we fix this,
and as added bonus, a tiny step is taken towards TS support.
JIRA issue: [CORE-9219](https://jira.reactos.org/browse/CORE-9219)

Fix manifest activation when loading imported dlls

---

drivers/storage/storahci/storahci.c

This PR will fix "uninitialized local variable" error (C4700) in driver storahci.
Retrial of #821.

[DRIVERS] Fix MSVC C4700 error of storahci (retry)

---

win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.c
win32ss/gdi/ntgdi/text.h

Google Chrome with -no-sandbox parameter in ReactOS wouldn't display the web page because first-chance exception raised. This PR will fix it (CORE-14926). 
JIRA issue: [CORE-14926](https://jira.reactos.org/browse/CORE-14926)
- Remove FullName, Style, and FaceName members from TEXTOBJ structure.
- Add TextFace member into TEXTOBJ structure.
- Add MatchFontName and MatchFontNames functions.
- Fix GetTextFace and related.

[FONT][WIN32SS] Fix GetTextFace function and related

---

sdk/include/reactos/wine/debug.h
sdk/lib/3rdparty/libwine/debug.c

**Supersedes PR #112.**
JIRA issue: [CORE-12671](https://jira.reactos.org/browse/CORE-12671)
- The default format is used when no format name is specified: this is
the one we use so far in ReactOS:
`<debug_class>:(<file>:<line>) <message>`
with "debug_class" being "trace", "warn", "err".
- The "wine" format is the one used by Wine. It can be used when trying
to diff-compare traces for a module with the corresponding one
obtained from a Wine run. It can also be useful because the logging of
Wine-synced code assumes that the function names are automatically
added by the helper macros "FIXME()", "TRACE()", "WARN()" or "ERR()",
and not manually inside the logging string given to these macros:
for example:
`FIXME("(%params) message\n", params);`
displays:
`fixme:<module>:SomeFunc(params) …

[REACTOS] Introduce a "DEBUGFORMAT" environment variable that allows to select different debug trace formats. - CORE-12671

---

modules/rostests/kmtests/CMakeLists.txt

ExPools and other tests don't break Windows Server 2003 anymore.
JIRA issue: [CORE-12657](https://jira.reactos.org/browse/CORE-12657)
Succeeds on WS03 (only): [WTB 40651](https://testbot.winehq.org/JobDetails.pl?Key=40651)
- Revert r73535, so KmTests run on "Test WHS" bot.

CORE-12657. Re-enable kmtest_.exe installation, so it runs on "Test WHS"

---

modules/rostests/winetests/comctl32/treeview.c

JIRA issue: [CORE-14975](https://jira.reactos.org/browse/CORE-14975)

[COMCTL32_WINETEST] treeview.c: Skip test_right_click(), until CORE-14975 is fixed

---

dll/cpl/access/lang/fr-FR.rc

This patch fixes some of the truncated strings in the _Accessibility_ dialog in French translation.
**JIRA Issue**: [CORE-12481](https://jira.reactos.org/browse/CORE-12481)
**Image URL:** https://imgur.com/a/jRUYMgS

[CPL][ACCESS] Fix some truncated strings in French resource

---

sdk/lib/cmlib/hiveinit.c

Addendum to r70582.
@HBelusca
JIRA issue: [CORE-12596](https://jira.reactos.org/browse/CORE-12596)
```
.../sdk/lib/cmlib/hiveinit.c: In function 'HvInitialize':
.../sdk/lib/cmlib/hiveinit.c:559:9: error: 'struct _HHIVE' has no member named 'Log'
```

CORE-12596. [CMLIB] Fix compiling as NT6+

---

modules/rostests/kmtests/kmtest/testlist.c

Not worth investigating in current state.
JIRA issue: [ROSTESTS-299](https://jira.reactos.org/browse/ROSTESTS-299)
For what it's worth, it crashes [without](https://testbot.winehq.org/JobDetails.pl?Key=41482) or [with](https://testbot.winehq.org/JobDetails.pl?Key=41476) PR502.
And add "// TODO: WIP/untested/crashes."

ROSTESTS-299. [KMTESTS:FLTMGR] Hide FltMgrLoad and FltMgrReg

---

dll/win32/lpk/bidi.c
dll/win32/lpk/lpk.c
modules/rostests/win32/user32/biditext/biditext.c
modules/rostests/win32/user32/biditext/biditext.h
win32ss/gdi/gdi32/objects/font.c

Use ScriptStringCPtoX to calculate caret positions when the GCP_REORDER flag is used.
Now the lpCaretPos array will contain value equivalent to the Windows results.
Added test code to the demo program to show the values, includes the changes in #825
[(Filed a report to wine about the incorrect lpOrder values)](https://bugs.winehq.org/show_bug.cgi?id=45793)

[LPK] Make GetCharacterPlacement caret position calculation to respect bidi text

---

base/setup/usetup/lang/pl-PL.h

_As recently reboot progress bar was implemented in usetup (https://github.com/reactos/reactos/commit/e5c0bfacf1374abf34abbaf75047149a6252ca5e), this PR translates the "Your computer will reboot in X second(s)..." string to Polish._

[TRANSLATION] Updated Polish translation in USETUP

---

MAINTAINERS

This is a proposal so that ReactOS also gets a MAINTAINERS file.
The purpose of this file is to allow newcomers to know at a glance who's responsible of what in the project. It also puts some limits on what a maintainer is (and isn't).
It also helps newcomers knowing that some code is 3rd party and shouldn't directly be handled in ReactOS.
This is a pull request for comments, and approval.
Feel free to directly push to the branch what areas you want to be maintainer of.
Some examples:
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/MAINTAINERS
- https://source.winehq.org/git/wine.git/blob/HEAD:/MAINTAINERS

Add a maintainers file

---

base/shell/cmd/cmdinput.c

Avoid overwriting the input string with command prompt on Ctrl+C event.
JIRA issue: [CORE-15029](https://jira.reactos.org/browse/CORE-15029)
Fully print the entered string so the command prompt would not overwrite it.
Cc @HBelusca

[CMD] Do not overwrite input string on Ctrl+C

---

win32ss/gdi/ntgdi/freetype.c

Fix APC_INDEX_MISMATCH bugcheck.
JIRA issue: [CORE-15031](https://jira.reactos.org/browse/CORE-15031)
Check whether Win32Process is NULL.

Fix APC_INDEX_MISMATCH bugcheck

---

.gitignore

Exclude [boot|live|hybrid]cd_extras from git as well since they are not part of the source code itself.

[GITIGNORE] Ignore [boot|live|hybrid]cd_extras

---

base/applications/msconfig_new/lang/ro-RO.rc

As the title of the PR says, we should not assign an access key to a letter with diacritic in anyway. The patch is for [`29603e7`](https://github.com/reactos/reactos/commit/29603e7291401080a14fde6f327c703b5ce6f640).

[TRANSLATION][MSCONFIG_NEW] Do not assign an access key to a letter with diacritic

---

dll/ntdll/ldr/ldrpe.c

JIRA issue: [CORE-15135](https://jira.reactos.org/browse/CORE-15135)

[LDR] Include dllname in snap failure DPRINT.

---

modules/rostests/kmtests/tcpip/connect.c

ReactOS (new) results are out of scope of this PR.
JIRA issue: [ROSTESTS-268](https://jira.reactos.org/browse/ROSTESTS-268)
Windows results: [(WTB) Job 42089](https://testbot.winehq.org/JobDetails.pl?Key=42089)

ROSTESTS-268. Fix kmtest:TcpIpConnect on Test WHS

---

modules/rostests/kmtests/tcpip/connect.c

Split off of PR868.
> ThFabba: approved.
> HeisSpiter: "What's the purpose of that trace?"
To complete the 3 other traces.

[KMTESTS:TCPIP] Add an "Associate address IRP completed" trace

---

dll/cpl/appwiz/addons.c
dll/cpl/appwiz/lang/bg-BG.rc
dll/cpl/appwiz/lang/cs-CZ.rc
dll/cpl/appwiz/lang/de-DE.rc
dll/cpl/appwiz/lang/el-GR.rc
dll/cpl/appwiz/lang/en-US.rc
dll/cpl/appwiz/lang/es-ES.rc
dll/cpl/appwiz/lang/et-EE.rc
dll/cpl/appwiz/lang/fr-FR.rc
dll/cpl/appwiz/lang/he-IL.rc
dll/cpl/appwiz/lang/it-IT.rc
dll/cpl/appwiz/lang/ja-JP.rc
dll/cpl/appwiz/lang/no-NO.rc
dll/cpl/appwiz/lang/pl-PL.rc
dll/cpl/appwiz/lang/pt-BR.rc
dll/cpl/appwiz/lang/ro-RO.rc
dll/cpl/appwiz/lang/ru-RU.rc
dll/cpl/appwiz/lang/sk-SK.rc
dll/cpl/appwiz/lang/sq-AL.rc
dll/cpl/appwiz/lang/tr-TR.rc
dll/cpl/appwiz/lang/uk-UA.rc
dll/cpl/appwiz/lang/zh-CN.rc
dll/cpl/appwiz/lang/zh-TW.rc
dll/cpl/appwiz/resource.h

If `hres` is failing, like due to lack of Internet connection, the Gecko installer directly quits and goes to the last setup page without providing a reason for such action to the user whatsoever. A message box explaining what happened should be enough.
- Move `message` wide character variable at the top of `download_proc()`
- Display a message box with `MessageBoxW()`
- Add `IDS_DWL_FAILED` to resource files and header

[APPWIZ][GECKO] Display a message box in case of failure

---

win32ss/gdi/ntgdi/freetype.c

Define and use GOT_PENALTY macro to specify the font penalty info.
JIRA issue: [CORE-5519](https://jira.reactos.org/browse/CORE-5519)

[FONT][WIN32SS] Use GOT_PENALTY macro to specify the penalty

---

sdk/lib/crt/process/process.c

CORE-9182
When passing in an environment for CreateProcess, it should be indicated that this is already unicode.

[CRT] spawn: define a unicode environment when needed

---

win32ss/gdi/ntgdi/freetype.c

We had forgotten the pool tag in freetype.c.

[FONT][WIN32SS] Use ExFreePoolWithTag instead of ExFreePool

---

base/applications/regedit/childwnd.c
base/applications/regedit/framewnd.c

- In resize_frame_rect function, use GetWindowRect instead of GetClientRect.

[REGEDIT] Trivial resizing code fix

---

dll/cpl/appwiz/addons.c

With the merge of #913, the message box will always be displayed even when the user attempts to abort the download of the Gecko package which confuses the user.
**JIRA Issue:** [CORE-15183](https://jira.reactos.org/browse/CORE-15183)
If `hres` returns **E_ABORT**, do not display the message box.

[APPWIZ][GECKO] Do not display the message box if the user aborts the download

---

dll/cpl/sysdm/lang/bg-BG.rc
dll/cpl/sysdm/lang/cs-CZ.rc
dll/cpl/sysdm/lang/da-DK.rc
dll/cpl/sysdm/lang/de-DE.rc
dll/cpl/sysdm/lang/el-GR.rc
dll/cpl/sysdm/lang/en-US.rc
dll/cpl/sysdm/lang/es-ES.rc
dll/cpl/sysdm/lang/fr-FR.rc
dll/cpl/sysdm/lang/he-IL.rc
dll/cpl/sysdm/lang/hu-HU.rc
dll/cpl/sysdm/lang/id-ID.rc
dll/cpl/sysdm/lang/it-IT.rc
dll/cpl/sysdm/lang/ja-JP.rc
dll/cpl/sysdm/lang/nl-NL.rc
dll/cpl/sysdm/lang/no-NO.rc
dll/cpl/sysdm/lang/pl-PL.rc
dll/cpl/sysdm/lang/ro-RO.rc
dll/cpl/sysdm/lang/ru-RU.rc
dll/cpl/sysdm/lang/sk-SK.rc
dll/cpl/sysdm/lang/sq-AL.rc
dll/cpl/sysdm/lang/sv-SE.rc
dll/cpl/sysdm/lang/tr-TR.rc
dll/cpl/sysdm/lang/uk-UA.rc
dll/cpl/sysdm/lang/zh-CN.rc
dll/cpl/sysdm/lang/zh-TW.rc

This fixes checkbox rendering issue.
JIRA issue: [CORE-13792](https://jira.reactos.org/browse/CORE-13792)
- Fix label height in russian translation. Other translations are ok.
- Fix controls order in IDD_SYSSETTINGS dialog

[SYSDM] Fix label height in IDD_SYSSETTINGS dialog

---

base/applications/network/net/lang/pl-PL.rc

```
-                 (na przykład: WARSZAWA\PIOTRS).\n"
+                 (na przykład: WARSZAWA\\PIOTRS).\n"
```
"\P" is invalid escape sequence.

[NET] Fix an escape sequence in Polish translation

---

base/setup/usetup/lang/it-IT.h

- Fix a broken character encoding in the Italian translation file
- And since we're here, add two spaces at the beginning of the "deleting cache" string

[USETUP] Fix a broken character in Italian resource

---

base/applications/regedit/childwnd.c
base/applications/regedit/main.c

Use the background brush or WM_ERASEBKGND message instead.

[REGEDIT] Don't paint background in WM_PAINT

---

boot/bootdata/hivecls.inf

Use shell image viewer for GIF files.
JIRA issue: [CORE-12680](https://jira.reactos.org/browse/CORE-12680)
Cc @katahiromz

[BOOTDATA][HIVECLS] Use shell image viewer for GIF files

---

dll/win32/lpk/CMakeLists.txt
dll/win32/lpk/bidi.c
dll/win32/lpk/lpk.c
dll/win32/lpk/ros_lpk.h
dll/win32/lpk/stub.c
win32ss/gdi/gdi32/include/gdi32p.h
win32ss/gdi/gdi32/main/dllmain.c
win32ss/gdi/gdi32/misc/misc.c
win32ss/gdi/gdi32/objects/utils.c

Add a mechanism that detects via the version resource if to mirror the application layout or not.
This is a "follow up" to commit 5b14b6f58196fec0dc7c899c26c93a68d4c8542d, even though I think there are better ways to implement mirroring.
This code is taken from the [`GetProcessDefaultLayout`](https://github.com/wine-mirror/wine/blob/377243b41105085ed23407eb2a03b54737d59f64/dlls/user32/win.c#L3994) function from Wine, which is [called](https://github.com/wine-mirror/wine/blob/377243b41105085ed23407eb2a03b54737d59f64/dlls/user32/win.c#L1463) in Wine's internal `WIN_CreateWindowEx` function.
In windows this happens when the GDI is loading the lpk.
Snippet to check if it works in welcome in ReactOS:
https://gist.github.com/peterooch/5e443168af19252036a5b541a4767497
Note: …

[LPK][GDI32] Enable mirroring via version resource

---

boot/bootdata/setupreg.inf
boot/freeldr/freeldr/include/winldr.h
boot/freeldr/freeldr/ntldr/setupldr.c
boot/freeldr/freeldr/ntldr/winldr.c
boot/freeldr/freeldr/ntldr/winldr.h
boot/freeldr/freeldr/ntldr/wlmemory.c
boot/freeldr/freeldr/ntldr/wlregistry.c
ntoskrnl/config/cmlazy.c
ntoskrnl/config/cmsysini.c
ntoskrnl/config/i386/cmhardwr.c
ntoskrnl/config/ntapi.c
ntoskrnl/config/powerpc/cmhardwr.c
ntoskrnl/ex/init.c
ntoskrnl/include/internal/cm.h
ntoskrnl/io/iomgr/driver.c
ntoskrnl/io/pnpmgr/pnpinit.c
ntoskrnl/io/pnpmgr/pnpmgr.c
ntoskrnl/io/pnpmgr/pnpreport.c
sdk/cmake/CMakeMacros.cmake

- Make FreeLdr load a registry hive in setup mode.
- Remove ReactOS-specific NTOS registry 1-st-stage hacks.

Setup improvements n°3 -- FREELDR, NTOS

---

win32ss/user/user32/controls/appswitch.c

This PR will fix Task Switcher in switching tasks and enumeration.
- Don't enumerate the windows whose owner window exists.
- Use PostMessage SC_RESTORE instead of ShowWindowAsync SW_RESTORE.

[USER32] Fix task switcher

---

CMakeLists.txt
sdk/include/reactos/builddir.h.cmake
sdk/include/reactos/debug.h
sdk/include/reactos/version.cmake
sdk/include/reactos/wine/debug.h

It's easier on the command line and the eyes looking at it

[CMAKE] Use configured include files to define the __RELFILE__ hack

---

base/applications/drwtsn32/stacktrace.cpp
dll/win32/kernel32/client/proc.c
dll/win32/kernel32/client/thread.c

This should allow unhandled exceptions in a thread to trigger our crash reporter,
instead of killing the process directly.

[KERNEL32] Use the default UnhandledExceptionFilter in BaseThreadStartup and BaseProcessStartup .

---

win32ss/gdi/ntgdi/freetype.c

Adjust timing of FreeType unlocking in ftGdiGetTextMetricsW function of "freetype.c".

[WIN32SS][FONT] Move IntUnLockFreeType(); in ftGdiGetTextMetricsW

---

win32ss/gdi/ntgdi/freetype.c

Add a assertion for locking, in FillTMEx function of freetype.c.
JIRA issue: [CORE-15166](https://jira.reactos.org/browse/CORE-15166)

[WIN32SS][FONT] Add ASSERT_FREETYPE_LOCK_HELD(); in FillTMEx

---

win32ss/gdi/ntgdi/freetype.c

- Define IntUnicodeStringToBuffer function to copy the contents of a UNICODE_STRING to a string buffer with a UNICODE_NULL correctly.
- Use it.

[WIN32SS][FONT] Define IntUnicodeStringToBuffer function and use it

---

modules/rostests/kmtests/ntos_mm/ZwMapViewOfSection.c
ntoskrnl/mm/section.c

Properly handle page fault in protected areas for file-backed sections.
JIRA issue: [ROSTESTS-110](https://jira.reactos.org/browse/ROSTESTS-110)
The page fault handler should fail early in case of a region marked as PAGE_NOACCESS or PAGE_GUARD, otherwise it allocates a page as if handling it in PAGE_READWRITE, and then bugchecks afterwards because of this inconsistency.

Properly handle PAGE_NOACCESS and PAGE_GUARD

---

win32ss/gdi/ntgdi/freetype.c

This PR will reduce many failures in wine font testcase by fixing NEWTEXTMETRIC.ntmCellHeight value.
JIRA issue: [CORE-15331](https://jira.reactos.org/browse/CORE-15331)

[WIN32SS][FONT] Fix ntmCellHeight value to usWinAscent + usWinDescent

---

base/setup/lib/fsutil.c
base/setup/lib/utils/partlist.c
base/setup/usetup/usetup.c
base/system/diskpart/partlist.c
sdk/include/reactos/rosioctl.h

When BTRFS is chosen as the filesystem for the partition, we think of it as being Ext2 partly because of the partition type ID being the same, `0x83`. However there are other Linux filesystems which use this ID as well therefore it doesn't make sense to print `Found Linux EXT2 partition`.
- Display the correct debug message in the console and not `Found Linux EXT2 partition` when there can be other filesystems which have the same ID type too

[USETUP] Don't print "found EXT2 partition" when it's actually a different FS type

---

base/services/tftpd/tftpd.cpp

- The extbuff array is declared as
https://github.com/reactos/reactos/blob/95bc44e214cb03fb8184519c8a7ad5a1880a35a2/base/services/tftpd/tftpd.cpp#L41
- The macro _MAX_PATH is defined as
https://github.com/reactos/reactos/blob/95bc44e214cb03fb8184519c8a7ad5a1880a35a2/sdk/include/crt/stdlib.h#L116
**And if we analyze GetModuleInfoA function**:
https://github.com/reactos/reactos/blob/95bc44e214cb03fb8184519c8a7ad5a1880a35a2/sdk/include/psdk/winbase.h#L3645 https://github.com/reactos/reactos/blob/95bc44e214cb03fb8184519c8a7ad5a1880a35a2/dll/win32/kernel32/client/loader.c#L541-L600
**we will note that out-of-bounds access cases are possible, which is what coverity warns about.**

Fix Coverity #1434273

---

dll/win32/winmm/joystick.c

Reduce CPU usage while using certain programs/games by not continuously looking up for the default joystick driver that isn't included in ReactOS.
Imported the following wine commit
https://github.com/wine-mirror/wine/commit/ebae298aa4d2711fef35d4ac60c6012438f36d61
Fix for JIRA issue [CORE-15336](https://jira.reactos.org/browse/CORE-15336)

[WINMM] Sync wine commit ebae298 as a fix for CORE-15336

---

base/shell/cmd/history.c

https://github.com/reactos/reactos/blob/9491979ac3fd9f4e3ec3898a43960e940ec2f198/base/shell/cmd/history.c#L312 is incorrect expression to compare with `Bottom`.

[CMD] Fix Coverity #715934 "Copy-paste error"

---

base/applications/network/tracert/tracert.cpp

- The IpAddress array is declared as
https://github.com/reactos/reactos/blob/97150ce9dd96412036e64a1aa74ccfd2ca9c1805/base/applications/network/tracert/tracert.cpp#L255 https://github.com/reactos/reactos/blob/97150ce9dd96412036e64a1aa74ccfd2ca9c1805/base/applications/network/tracert/tracert.cpp#L34
- The macro NI_MAXHOST is defined as
https://github.com/reactos/reactos/blob/97150ce9dd96412036e64a1aa74ccfd2ca9c1805/sdk/include/psdk/ws2def.h#L359
'IpAddress' must be of size NI_MAXHOST to comply with its usage in the GetNameInfoW() call made in the code.

[TRACERT] Fix Coverity #1434258  "Out-of-Bounds access"

---

modules/rosapps/applications/sysutils/systeminfo/lang/zh-CN.rc

The resource string IDS_SYS_TYPE of systeminfo Chinese translation is missing a quote character.

[SYSTEMINFO] Fix Chinese resource to fix MSVC2010 build

---

base/applications/mspaint/scrollbox.cpp

This is a small fix for a scrollbar related edge case functionality exhibited in mspaint (and in a lesser degree also elsewhere in instances of) scrollbar controlled content. As known, the scrollbars presence is given by the size ratio between the accommodating outer frame and the scroll-controlled contents inside it, and it works for the most part. There is, however, a case where the presence of both toolbars is kept even when the contents would fit the frame (if not for the scrollbars themselves that increase the size of the contents' area). Please take the current commit as a demo fix and a provisional correction for mspaint (as I think that the proper fix should reside in common controls).
JIRA issue: [CORE-15096](https://jira.reactos.org/browse/CORE-15096)
The commit exposes the …

[MSPAINT] Fix scrollbar presence on canvas/view fitting

---

dll/win32/shell32/CShellLink.cpp

If SearchPathW, GetFullPathNameW or PathFileExistsW fails for some reason, the error code is not displayed to the debug terminal which is a burden to search for the cause of the problem.
- Use `GetLastError()` to retrieve the error code

[SHELL32] Print out the error code

---

configure.cmd

Latest VS 2017 CL.EXE compiler wasn't being correctly detected by the configure.cmd script.
- Adds support for CL.EXE compiler versions starting with 19.16 to the configure.cmd script.

Add support for latest VS2017 (15.0) compiler

---

sdk/include/reactos/mc/errcodes.mc

This was causing the MSVC build to fail.
- Fix syntax errors in translations so that the MSVC build succeeds.
- This also fixes the translations when not built using MSVC, which would still be malformed.

Fix syntax errors in errcodes.mc

---

dll/win32/kernel32/client/fiber.c

FlsAlloc - fiber local storage list was not initialized before using
This bug was found while installing .net 4.5

[KERNEL32] FlsAlloc - fiber local storage list was not initialized before using.

---

drivers/filesystems/fastfat/cleanup.c
drivers/filesystems/fastfat/close.c
drivers/filesystems/fastfat/fat.c
drivers/filesystems/fastfat/fcb.c
drivers/filesystems/fastfat/flush.c
drivers/filesystems/fastfat/fsctl.c
drivers/filesystems/fastfat/misc.c
drivers/filesystems/fastfat/shutdown.c
drivers/filesystems/fastfat/vfat.h
ntoskrnl/io/iomgr/file.c

- Cache the RootFcb so that its cleanup can be handled separately
during dismounting.
- Force volume dismount at cleanup if the VCB_DISMOUNT_PENDING flag
is set.
- Actually dismount a volume if its VCB has been flagged as not good,
or if we force dismounting.
NOTE: In their *CheckForDismount() function, our 3rd-party FS drivers
as well as MS' fastfat, perform a comparison check of the current VCB's
VPB ReferenceCount with some sort of "dangling"/"residual" open count.
It seems to be related to the fact that the volume root directory as
well as auxiliary data stream(s) are still opened, and only these are
allowed to be opened at that moment. After analysis it appears that for
the ReactOS' fastfat, this number is equal to "3". But this should be
investigated more closely...
- On …

[FASTFAT] Improvements for volume dismount + minor bugfixing.

---

ntoskrnl/io/iomgr/error.c

Add quotes around string, since it is often empty, thus confusing in log.

[NTOSKRNL][IO] Tiny improvement to debug message

---

win32ss/user/ntuser/winpos.c

Reduce confusion by specifying the omitted constant HWND_TOP == 0.

[WIN32K][NTUSER] Specify constant name explicitly

---

sdk/include/ndk/extypes.h

There is no reason this struct is usermode-only. Will be used in future PR to add support for `SystemMemoryListInformation` (`NtQuerySystemInformation`).

[SDK] Allow use of SYSTEM_MEMORY_LIST_INFORMATION in kernel code

---

dll/cpl/sysdm/smbios.c

Explicitly check DMI strings for NULL pointers to make CRT string comparison functions happy.
JIRA issue: [CORE-15403](https://jira.reactos.org/browse/CORE-15403)

[SYSDM] Explicitly check DMI strings for NULL pointers

---

dll/win32/shell32/dialogs/folder_options.cpp

JIRA issue: [CORE-10481](https://jira.reactos.org/browse/CORE-10481)
- Create a stub window "MSGlobalFolderOptionsStub".
- Create Folder Options dialog owned by the stub window.

[SHELL32] Don't show taskbar button of Folder Options

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-15166](https://jira.reactos.org/browse/CORE-15166)
See also: https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fsselection
- If (pOS2->fsSelection & 0x80) is true, then use pHori->Ascender and pHori->Descender (it's recommended).

[WIN32SS][FONT] Use HHEA table metrics if (fsSelection & 0x80)

---

dll/directx/ddraw/Ddraw/ddraw_displaymode.c

Complete this issue a bit more.
JIRA issue: [CORE-8545](https://jira.reactos.org/browse/CORE-8545)
Use same code, especially `DDSD_PITCH`, as elsewhere in this file and as Wine `ddraw7_GetDisplayMode()`.
These values now match filled members.

CORE-8545. [DDRAW] Fix 2 duplicate DDSD_WIDTH uses

---

sdk/tools/log2lines/cache.c
sdk/tools/log2lines/log2lines.c
sdk/tools/log2lines/options.c

`Log2Lines` uses a mix of `malloc()` and no `malloc()`. I don't know why.
Simpler and safer code.
- Replace overkill malloc() uses
- Optimize malloc() uses
- Free all memory on exit

[LOG2LINES] Improve malloc() and free() uses

---

base/applications/osk/main.c

As requested by Hermes Belusca (on #1102), this patch fixes the issue which it couldn't display the original On-Screen Keyboard icon.
- Implement `OSK_SetImageApp()`
- Call the function on `WM_INITDIALOG` when the message is sent

[OSK] Display the correct icon of the application

---

CMakeLists.txt
sdk/include/reactos/builddir.h.cmake
sdk/include/reactos/debug.h
sdk/include/reactos/version.cmake
sdk/include/reactos/wine/debug.h

Fixes missing characters in debuglog after introduction of __RELFILE__.
JIRA issue: [CORE-14839](https://jira.reactos.org/browse/CORE-14839)
* Revert commit [07bd6089ec96b068d92f42e764cc7336a7de24a0](https://git.reactos.org/?p=reactos.git;a=commit;h=07bd6089ec96b068d92f42e764cc7336a7de24a0), which reverted my earlier changes and replaced 3 lines in the toplevel CMake file with ~20 lines in 3 different files, adding a new file and auto-generating another file, because "It's easier on the command line and the eyes looking at it".
* Do a runtime-detect relative vs absolute path (based on Thomas' suggestion), using the size of the relative path from the build dir to the source dir as the length of the prefix to skip.
* Fix broken escaping in definition of REACTOS_*_DIR, which worked, but …

Cmake/core 14839 fix  relfile  

---

win32ss/user/ntuser/ghost.c

@HeisSpiter says ASSERT(FALSE); in IntGhostWindowFromHungWindow is incorrect in [f469aca](https://github.com/reactos/reactos/commit/f469acacecfd3d215ebe5dde79517c45b92aa730#commitcomment-31640772).
JIRA issue: [CORE-11944](https://jira.reactos.org/browse/CORE-11944)

[WIN32SS] Replace ASSERT(FALSE); in IntGhostWindowFromHungWindow

---

dll/win32/shell32/dialogs/dialogs.cpp

Running "%SYSTEMROOT%" sometimes crashed. This will fix it.
JIRA issue: [CORE-15431](https://jira.reactos.org/browse/CORE-15431)

[SHELL32] Fix 'Run' dialog crash

---

base/applications/regedit/main.c

There is a problem with drawing of splitter. 
JIRA issue: [CORE-15442](https://jira.reactos.org/browse/CORE-15442)
We can fix this bug by setting the background brush of the child window.

[REGEDIT] Set background brush to child window

---

dll/win32/browseui/parsecmdline.cpp

Add a backslash to the path if the path is a directory in parsing Explorer command line.
JIRA issue: [CORE-15434](https://jira.reactos.org/browse/CORE-15434)

[BROWSEUI] Add backslash for directory

---

base/setup/lib/muifonts.h
media/inf/font.inf

I have solved this problem by mapping Ubuntu to Droid Sans Fallback via Font Substitutes. 
I know this is not a way to completely solve the problem, but I think this is the best way before improve the ReactOS font mechanism in the future.
JIRA: [CORE-15179](https://jira.reactos.org/browse/CORE-15179)

Fix CJK font problems in the Official theme

---

modules/rostests/kmtests/rtl/RtlException.c

On behalf of Victor Martinez.
JIRA issue: [CORE-8773](https://jira.reactos.org/browse/CORE-8773)

CORE-8773. [KMTEST:RTL] RtlException: Remove '#if CORE_6640_IS_FIXED'

---

base/services/umpnpmgr/umpnpmgr.c
sdk/include/c++/stlport/stl/config/_reactos.h
sdk/include/psdk/winbase.h

[UMPNPMGR] Re-enable the usage of Interlocked Singly-Linked lists.
Using locked operations (insertion & removal) on the list of queued
devices installations is necessary, because these operations are done
concurrently by two different threads: PnpEventThread() and
DeviceInstallThread().
Addendum to commit b2aeafca (r24365).

[UMPNPMGR] Re-enable the usage of Interlocked Singly-Linked lists.

---

dll/cpl/input/input.c
dll/cpl/joy/joy.c
dll/cpl/sysdm/hardprof.c
dll/cpl/sysdm/sysdm.c
dll/win32/shell32/dialogs/folder_options.cpp

Set more small and large icons to Control Panel applets.
JIRA issue: [CORE-15445](https://jira.reactos.org/browse/CORE-15445)

[CPL][SHELL32] Add icons to input, joy, sysdm, folder options

---

sdk/cmake/msvc.cmake

- "C4028: formal parameter N different from declaration"

CORE-7538. [CMAKE] MSVC: Make C4028 warning into error, on "i386" only

---

dll/win32/shell32/CDefView.cpp

Add CDefView::DefMessageSFVCB method for default processing of IShellFolderView callbacks.
JIRA issue: [CORE-14976](https://jira.reactos.org/browse/CORE-14976)

[SHELL32] Add CDefView::DefMessageSFVCB (Retrial of #1145)

---

dll/win32/shell32/shlexec.cpp

JIRA issue: [CORE-15455](https://jira.reactos.org/browse/CORE-15455), [CORE-11772](https://jira.reactos.org/browse/CORE-11772)
- Fix ShellExecCmdLine function.

[SHELL32] 'Run' dialog box should accept URL

---

dll/win32/shell32/shlexec.cpp

This PR will fix 'Run' dialog box's behaivour after entering `"C:"`.
JIRA issue: [CORE-15434](https://jira.reactos.org/browse/CORE-15434)
In CORE-15434, amber has detected that `ShellExecCmdLine` call for `"C:"` will append a backslash to the path by replacing `explorer.exe` in Windows.

[SHELL32] ShellExecCmdLine: Add backslash if path was like C:

---

modules/rosapps/applications/screensavers/cylfrac/cylfrac.c

- "...\cylfrac.c(160): warning C4028: formal parameter 3 different from declaration"
- "...\cylfrac.c(160): warning C4028: formal parameter 4 different from declaration"
- "...\cylfrac.c(160): warning C4028: formal parameter 5 different from declaration"

CORE-7538. [CYLFRAC] Fix 3 MSVC-x64 warnings about TimeProc()

---

dll/shellext/netshell/lanstatusui.cpp

Use distinct icon for connection status window.
JIRA issue: [CORE-15445](https://jira.reactos.org/browse/CORE-15445)
AFTER:

[NETSHELL] Use distinct icon for connection status window

---

dll/win32/jscript/jsutils.c

"...\jsutils.c(679) : warning C4028: formal parameter 3 different from declaration"
Cherry-pick https://source.winehq.org/git/wine.git/commit/961d5c8ed05eeccbe216ff24faa0e3d6a0c2b332

CORE-7538. [JSCRIPT] Fix a MSVC-x64 warning about to_uint32()

---

dll/directx/wine/d3dcompiler_43/d3dcompiler_private.h
dll/directx/wine/d3dcompiler_43/utils.c

"...\utils.c(561) : warning C4028: formal parameter 2 different from declaration"
Cherry-pick https://source.winehq.org/git/wine.git/commit/ffe9346120ca74f193d8a31d0b6a48eb55604d2b

CORE-7538. [D3DCOMPILER_43] Fix a MSVC-x64 warning about dxbc_init()

---

ntoskrnl/cc/copy.c

Addendum to 945ff8ea2ee2abd48f5ecbe707131446546e75a3.
Should not change behavior, especially with regard to overflow, as `Length = MAX_ZERO_LENGTH;` currently...

WIP. [NTOS:CC] CcCanIWrite(): Use BYTES_TO_PAGES(Length)

---

sdk/tools/cabman/CCFDATAStorage.cxx

See [CORE-14431](https://jira.reactos.org/browse/CORE-14431)

[CABMAN] Fix a problem with creating temp files on some Windows system

---

dll/cpl/appwiz/createlink.c
dll/cpl/appwiz/lang/bg-BG.rc
dll/cpl/appwiz/lang/cs-CZ.rc
dll/cpl/appwiz/lang/de-DE.rc
dll/cpl/appwiz/lang/el-GR.rc
dll/cpl/appwiz/lang/en-US.rc
dll/cpl/appwiz/lang/es-ES.rc
dll/cpl/appwiz/lang/et-EE.rc
dll/cpl/appwiz/lang/fr-FR.rc
dll/cpl/appwiz/lang/he-IL.rc
dll/cpl/appwiz/lang/it-IT.rc
dll/cpl/appwiz/lang/ja-JP.rc
dll/cpl/appwiz/lang/no-NO.rc
dll/cpl/appwiz/lang/pl-PL.rc
dll/cpl/appwiz/lang/pt-BR.rc
dll/cpl/appwiz/lang/ro-RO.rc
dll/cpl/appwiz/lang/ru-RU.rc
dll/cpl/appwiz/lang/sk-SK.rc
dll/cpl/appwiz/lang/sq-AL.rc
dll/cpl/appwiz/lang/tr-TR.rc
dll/cpl/appwiz/lang/uk-UA.rc
dll/cpl/appwiz/lang/zh-CN.rc
dll/cpl/appwiz/lang/zh-TW.rc
dll/cpl/appwiz/resource.h

In the recent commit ([`c5f89b8`](https://github.com/reactos/reactos/commit/c5f89b815921d41fe97ce645c72cdbb9e4ef8683)) in APPWIZ control panel module, the last implemented strings were hardcoded in the code whereas most of the strings are translatable through resources. In other words, let's make those strings translatable too!
- Make the strings translatable
- Use the UNICODE variation of MessageBox() service instead of the ANSI one

[APPWIZ] Do not hardcode the strings

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-11848](https://jira.reactos.org/browse/CORE-11848), [CORE-15319](https://jira.reactos.org/browse/CORE-15319)
This PR will partially implement font/text rotation by LOGFONT.lfEscapement and improve the rendering image. If (angle % 90) was non-zero, then the background won't be drawn. The case of (angle % 90) will be later work.

[FONT][WIN32SS] Partially implement font/text rotation

---

CONTRIBUTING.md

Sometimes newcomers contribute to ReactOS repository for the first time although they haven't noticed that you have to use your real name and E-mail when committing changes. 
When we show them the contribution guidelines, it doesn't tell anywhere how to ACTUALLY use your name and E-mail for commits. Thus to make things easier for both sides, let's add a notice with links which point to tutorials/guides on how to do so.

[CONTRIBUTING] Add a notice for how to set your real name/mail

---

win32ss/user/user32/controls/appswitch.c

If there is only one top-level window, then let App Switcher (Alt+Tab) activate the window.

[USER32] Let App Switcher activate even if only one window

---

sdk/lib/rtl/path.c

RtlGetFullPathName_UEx is required for ProcessHacker 3.0+.
Also reimplemented RtlGetFullPathName_U using RtlGetFullPathName_UEx.
The function is not exported for now.

[NTDLL][RTL] Implement RtlGetFullPathName_UEx

---

sdk/tools/log2lines/log2lines.c

Follow-up to #1109, to support some options like '-m -M'.
NB: Last step would be to re-use `translate_files()`... I am not planning to do that, at the moment.

[LOG2LINES] Use translate_line() for command line input too

---

win32ss/gdi/gdi32/objects/font.c
win32ss/gdi/ntgdi/freetype.c

This will fix `EnumFonts` and `EnumFontFamilies` functions.
JIRA issue: [CORE-15558](https://jira.reactos.org/browse/CORE-15558)

[FONT][GDI32] Fix font enumeration functions

---

win32ss/user/ntuser/simplecall.c
win32ss/user/ntuser/window.c

1. Added a check in `co_UserCreateWindowEx` for parentless windows,
that checks the default layout direction, if its `LAYOUT_RTL` add the `WS_EX_LAYOUTRTL` flag to the extended window styles.
2. Made the internal routine to also accept `LAYOUT_LTR` as a value for `SetProcessDefaultLayout`
Now all the reactos applications that have SetProcessDefaultLayout calls to mirror the layout get mirrored.
(albeit to mixed results)
This code is based on this following wine code path->
[How wine checks for default process layout](https://github.com/wine-mirror/wine/blob/da5112c74313b5236183135204cab38a8b0169ed/dlls/user32/win.c#L1437)
Hopefully this will fare better than PR #600

[NTUSER] Fix SetProcessDefaultLayout

---

sdk/include/reactos/stubs.h

It appears noone tested `-stub` with `int64` parameters - gives compilation error. Fix by defining the constant in common stub header.

[SPEC2DEF] Fix compilation of generated stub C files with int64 parameters

---

dll/win32/syssetup/syssetup.spec

Add spec definition for `SetupInfObjectInstallActionW`.
It just forwards the call to `SETUPAPI.InstallHinfSectionW`.
JIRA issue: [CORE-9897](https://jira.reactos.org/browse/CORE-9897)

[SYSSETUP] Add spec definition for SetupInfObjectInstallActionW

---

win32ss/user/ntuser/menu.c

Previously, we would just stick the menu on the edge of the screen.
We should actually try to flip the menu around the point of origin,
and only when that fails move it to the edge of the screen.
CORE-15001
CORE-9037
JIRA issue: [CORE-15001](https://jira.reactos.org/browse/CORE-15001)
JIRA issue: [CORE-9037](https://jira.reactos.org/browse/CORE-9037)

[WIN32K:NTUSER] Find a better position for a menu that is off-screen

---

sdk/cmake/config-amd64.cmake
sdk/cmake/config-arm.cmake
sdk/cmake/msvc.cmake

- Always use string pooling when building: this helps reducing the
size of the binaries due to string redundancy coming from the usage
of __FILE__ / __RELFILE__ in the debugging helper macros. Note also
that GCC builds use string pooling by default.
- Use suitable add_compile_flags() command.
- Add some explanative comments for some settings.
Some numbers (obtained with my local builds):
Before / After => Reduction
===========================
freeldr.sys  :  443 KB (  453.632 bytes) /  364 KB (  372.736 bytes) => ~ 18%
win32k.sys   : 1877 KB (1.922.048 bytes) / 1562 KB (1.599.488 bytes) => ~ 17%
ntoskrnl.exe : 2253 KB (2.307.072 bytes) / 1902 KB (1.947.136 bytes) => ~ 15.6%
kernel32.dll : 3008 KB (3.080.192 bytes) / 2906 KB (2.975.744 bytes) => ~ 3.4%

[CMAKE] MSVC cmake settings improvements.

---

base/applications/taskmgr/taskmgr.h

Now "commit charge" not clipped

[TASKMGR] adjust widths for status bar parts

---

win32ss/user/ntuser/simplecall.c

Check if the window is not hung when switching to the window. This avoids taskbar hung up.

[WIN32SS][NTUSER] Don't freeze Task Bar in switching the app

---

win32ss/user/user32/windows/window.c

`IsHungAppWindow(a ghost window) == TRUE`.
JIRA issue: [CORE-11944](https://jira.reactos.org/browse/CORE-11944)

[WIN32SS][USER32] Ghost is a hung window

---

win32ss/user/user32/windows/window.c

Check `Window->fnid == FNID_GHOST` in `IsHungAppWindow` function.
JIRA issue: [CORE-11944](https://jira.reactos.org/browse/CORE-11944)

[WIN32SS][USER32] Make IsHungAppWindow check FNID

---

base/applications/msconfig_new/comctl32ex/comctl32supp.h
base/shell/explorer/precomp.h
dll/shellext/stobject/precomp.h
dll/win32/browseui/internettoolbar.cpp
dll/win32/browseui/shellbars/shellbars.h
dll/win32/browseui/toolsband.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/shellmenu/CMenuToolbars.cpp
sdk/lib/atl/atlwin.h
win32ss/user/ntuser/menu.c

The previous context menu fix introduced a small regression,
the menu would be off-screen if it was too far to the right.
The first commit fixes this case.
The second commit makes a macro available for general use, and removes copypasta.
The third commit fixes our `CDefView` context menu behavior when triggered from the keyboard.
Previously, we would send huge coordinates, because we treated the input as unsigned.
Additionally, we now also position the menu over a focused or selected item.

Fix desktop context menu + improve it

---

win32ss/user/ntuser/defwnd.c
win32ss/user/ntuser/hotkey.c
win32ss/user/ntuser/hotkey.h
win32ss/user/ntuser/input.c
win32ss/user/ntuser/nonclient.c

Implemented this actions
- Win key + Arrows;
- drag to left/right/top screen border;
- double-click on top/bottom
CORE-12845
My second try. First was implemented inside explorer.exe but rejected bcz of that. Now it is placed in `ntuser` but i made one ugly hack in `uxtheme.dll` (i still can't get how messaging working and where to place handler for `WM_KEYDOWN` :(  please help!  )

[WIN32SS][NTUSER] Aero Snap feature

---

dll/cpl/mmsys/sounds.c

Let's try this again. Set the initial media folder location for the Browse button on the Sounds tab to C:\ReactOS\Media using %SystemRoot%.

[MMSYS] Set the initial media folder location

---

ntoskrnl/include/internal/amd64/mm.h
ntoskrnl/include/internal/arm/mm.h
ntoskrnl/include/internal/i386/mm.h
ntoskrnl/include/ntoskrnl.h
ntoskrnl/mm/ARM3/miarm.h
ntoskrnl/mm/ARM3/sysldr.c
ntoskrnl/mm/mminit.c

* The previous version was insanely overcomplicated and broken and therefore disabled.
* The new version also enforces NX protection on x64.
* Now that protecting works, also protect the boot loaded images.

[NTOS:Mm] Rewrite MiWriteProtectSystemImage

---

dll/win32/winmm/midimap/midimap.c

Support Windows XP compatible MIDIMap registry setting.
JIRA issue: [CORE-15602](https://jira.reactos.org/browse/CORE-15602)
**Note:** midimap is not synced with Wine (it's forked), so I did not used `__REACTOS__` ifdefs.

[WINMM][MIDIMAP] Support Windows XP compatible MIDIMap registry setting

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiGetBitmapBits.c
modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

Improve the testcases of `NtGdiGetBitmapBits` and `NtGdiSetBitmapBits`.
- Use `ok_long` macro instead of obsolete `RTEST` macro.

[APITESTS][WIN32KNT_APITEST] Use ok_long for NtGdiGetBitmapBits/NtGdiSetBitmapBits

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiArcInternal.c

Improve `NtGdiArcInternal` testcase.
- Use `ok_int` and `ok_long` macros instead of obsolete `TEST` macro.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiArcInternal testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiCombineRgn.c

Improve the testcase of `NtGdiCombineRgn` function.
- Use `ok_int` and `ok_long` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiCombineRgn testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiBitBlt.c

Improve the testcase for `NtGdiBitBlt` function.
- Use `ok_int`, `ok_long` and `ok` macros instead of obsolete `TEST` and `TESTX` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiBitBlt testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiCreateBitmap.c

Improve the testcase of `NtGdiCreateBitmap` function.
- Use `ok`, `ok_int`, `ok_long` and `ok_ptr` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiCreateBitmap testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiCreateCompatibleDC.c

Improve the testcase of `NtGdiCreateCompatibleDC` function.
- Use `ok`, `ok_int` and `ok_ptr` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiCreateCompatibleDC testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiGetRandomRgn.c

Improve the testcase of `NtGdiGetRandomRgn` function.
- Use `ok_int` and `ok_long` macros instead of obsolete `TEST` and `RTEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiGetRandomRgn testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiFlushUserBatch.c

Improve the testcase of `NtGdiFlushUserBatch` function.
- Use `ok`, `ok_int`, `ok_long`, and `ok_ptr` macros instead of `TEST` and `ASSERT` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiFlushUserBatch testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiExtTextOutW.c

Improve the testcase of `NtGdiExtTextOutW` function.
- Use `ok_int` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiExtTextOutW testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiDeleteObjectApp.c

Improve the testcase of `NtGdiDeleteObjectApp` function.
- Use `ok`, `ok_int` and `ok_long` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiDeleteObjectApp testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiDoPalette.c

Improve the testcase of `NtGdiDoPalette` function.
- Use `ok`, `ok_int` and `ok_long` macros instead of `RTEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiDoPalette testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiEngCreatePalette.c

Improve the testcase of `NtGdiEngCreatePalette` function.
- Use `ok` and `ok_long` and `ok_ptr` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiEngCreatePalette testcase

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiEnumFontOpen.c

Improve the testcase of `NtGdiEnumFontOpen` function.
- Use `ok`, `ok_int` and `ok_ptr` macros instead of obsolete `TEST` macros.

[APITESTS][WIN32KNT_APITEST] Improve NtGdiEnumFontOpen testcase

---

win32ss/user/user32/controls/appswitch.c

App Switcher should use the non-owned window's icon.
JIRA issue: [CORE-15672](https://jira.reactos.org/browse/CORE-15672)

[USER32] App Switcher should use the non-owned window's icon

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

Expand Tabs to Spaces in `NtGdiSetBitmapBits` testcase. Follow-up of #1304.
JIRA issue: N/A.

[WIN32KNT_APITEST] NtGdiSetBitmapBits: Expand tabs to spaces

---

win32ss/gdi/ntgdi/bitmaps.c
win32ss/gdi/ntgdi/bitmaps.h

Fix `UnsafeSetBitmapBits` function.
Splitted from #1305.

[WIN32SS][NTGDI] Fix UnsafeSetBitmapBits

---

win32ss/gdi/ntgdi/bitmaps.c

Don't check `WORD` alignment in `NtGdiSetBitmapBits`.
Splitted from #1305.

[WIN32SS][NTGDI] Alignment probe change in NtGdiSetBitmapBits

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

Improve `NtGdiSetBitmapBits` testcase by adding tests for maximum buffer size.

[WIN32KNT_APITEST] NtGdiSetBitmapBits: Add tests for maximum buffer size

---

modules/rostests/apitests/win32nt/ntgdi/NtGdiSetBitmapBits.c

Improve `NtGdiSetBitmapBits` testcase again and again.

[WIN32KNT_APITEST] NtGdiSetBitmapBits: Add tests for max buffer size 2

---

win32ss/gdi/ntgdi/bitmaps.c

Fix `NtGdiSetBitmapBits` function in buffer size checking.
- Let it fail if buffer size was greater than 564.

[WIN32SS][NTGDI] Fix NtGdiSetBitmapBits in buffer size

---

sdk/lib/3rdparty/freetype/src/autofit/afcjk.c
sdk/lib/3rdparty/freetype/src/autofit/aflatin.c
sdk/lib/3rdparty/freetype/src/autofit/afmodule.c
sdk/lib/3rdparty/freetype/src/cid/cidgload.c
sdk/lib/3rdparty/freetype/src/psaux/psintrp.c
sdk/lib/3rdparty/freetype/src/raster/ftraster.c
sdk/lib/3rdparty/freetype/src/smooth/ftgrays.c
sdk/lib/3rdparty/freetype/src/type1/t1gload.c

Running out of pool is likely at least during kmtest:ExPools.
There is a chance of crashing when dereferencing these null pointers -- but
worse, there's also a chance of overwriting the IVT or BDA if a VDM BIOS
call is in progress, which can lead to crashes in non-obvious places later.
JIRA issue: [CORE-15642](https://jira.reactos.org/browse/CORE-15642)

[FREETYPE] Handle allocation failures in our stack-saving hacks.

---

win32ss/gdi/ntgdi/bitmaps.c

JIRA issue: [CORE-15657](https://jira.reactos.org/browse/CORE-15657) and [CORE-15695](https://jira.reactos.org/browse/CORE-15695).
- Use `ProbeForWrite` instead of `ProbeForRead`.

[WIN32SS][NTGDI] Use ProbeForWrite in NtGdiSetBitmapBits

---

drivers/storage/ide/uniata/id_sata.cpp

Add AHCI revision 1.3.1 and also explicitly print current AHCI revision in debug log.
Original patch comes from UniATA's author Alexandr A. Telyatnikov aka Alter.
JIRA issue: [CORE-15643](https://jira.reactos.org/browse/CORE-15643)
----
@JoachimHenze wrote:
> I agree that v46e3_to_v46e8-ahci131.diff looks very safe. If it'll get committed to master until rls-date, I might pick it.
So let's commit it. :slightly_smiling_face:

[UNIATA] Add AHCI revision 1.3.1

---

CMakeLists.txt
boot/freeldr/freeldr/CMakeLists.txt
dll/3rdparty/libtirpc/CMakeLists.txt
ntoskrnl/CMakeLists.txt
ntoskrnl/ntkrnlmp/CMakeLists.txt

Adds the ENABLE_EXPORTS property where needed. newer versions of cmake require this
Fixes a def file being listed twice, this triggers an issue in some unix versions of cmake where it attempts to merge two def files using a cmake command only available on windows
Related JIRA issue: [CORE-15406](https://jira.reactos.org/browse/CORE-15406)
Previous PR: https://github.com/reactos/reactos/pull/808

Fixes for upstream cmake

---

ntoskrnl/mm/ARM3/expool.c

"Free" build should not BSoD on 'Freeing pool - invalid tag specified' case.
JIRA issue: [CORE-15446](https://jira.reactos.org/browse/CORE-15446)

CORE-15446. [NTOS:MM] ExFreePoolWithTag(): Accept tag mismatch, on release build

---

subsystems/mvdm/ntvdm/console/console.c
subsystems/mvdm/ntvdm/emulator.c

Original code compared against the pointer value rather
than the first byte
Found while building with gcc 7.3,  oddly gcc 4.7 does not emit a warning for this

[mvdm] Fix missing pointer dereference

---

boot/freeldr/freeldr/CMakeLists.txt

`configure.cmd VSSolution` was failing due to `add_asm_files()` macro expansion.
It was using the same `freeldr_linker_file` variable name as a temporary filename base twice.
This patch uses `_target` parameter to make those variable names differ and fixes the configure step.

[FREELDR] Fix VSSolution configuring and build

---

drivers/filesystems/udfs/create.cpp

SeSinglePrivilegeCheck() returns a BOOLEAN, not a NTSTATUS.
JIRA issue: [CORE-14271](https://jira.reactos.org/browse/CORE-14271)

CORE-14271. [UDFS] Correctly check SeSinglePrivilegeCheck() return value

---

base/setup/lib/setuplib.c
base/setup/reactos/drivepage.c
base/setup/usetup/usetup.c

Currently the `InitDestinationPaths()` doesn't check the used routines inside the code and if one of those functions fail, the user won't know why did it fail.
- Check the status conditions given by the functions inside `InitDestinationPaths()`
- Check the status values of `InitDestinationPaths()`

[USETUP][REACTOS] Check the status return value of InitDestinationPaths()

---

sdk/cmake/msvc.cmake

Addendum to 5e673f3.
JIRA issue: [CORE-14373](https://jira.reactos.org/browse/CORE-14373)

CORE-14373. [CMAKE] msvc.cmake: Remove 2 now redundant '/GF'

---

.travis.yml
configure.sh

Right now configure.sh creates a folder in build directory but configure.cmd does not.
This PR makes configure.sh consistent with configure.cmd

Make configure.sh behave like configure.cmd

---

drivers/storage/class/ramdisk/ramdisk.c

Last element in a query registry table needs to have a null name

Fix unterminated query table

---

base/applications/network/nslookup/nslookup.c

Prevent nslookup.exe from crashing when executed in a ROS VM with no network
interfaces. This is due to a NULL pointer dereference occurring if
`GetNetworkParams` in `main` fails with an error other than
`ERROR_BUFFER_OVERFLOW`. In this case, `pNetInfo` remains initialized to
NULL, causing `strncpy` to crash.
Fixes a bug in nslookup.exe causing it to crash with a NULL pointer dereference in situations with no network connectivity.
JIRA issue: *none*
Move the entire logic that copies the results obtained from `GetNetworkParams` to the global `State` struct into the branch where the first `GetNetworkParams` call was successful but reported the desired size for `pNetInfo`. This additionally is a bit more consistent with regard to `pNetInfo` being allocated and freed within the same code …

[NSLOOKUP] Fix crash in case of no network connectivity

---

boot/freeldr/freeldr/lib/fs/pxe.c

PXE: Fix network packet size. 1024 bytes should fit into a single network packet. Original patch by @mifritscher.
JIRA issue: [CORE-15706](https://jira.reactos.org/browse/CORE-15706)
------
Cc @HBelusca (since the ticket in JIRA is assigned to you)

[FREELDR] PXE: Fix network packet size

---

base/system/winlogon/winlogon.c

Fixes winlogon keyboard layout fallback flags. Previously the flags were made up from the locale identifier (409) and the result was an invalid combination of flags. This causes `NtUserLoadKeyboardLayoutEx` to fail [when checking the flags](https://github.com/reactos/reactos/blob/893a3c9d030fd8b078cbd747eeefd3f6ce57e560/win32ss/user/ntuser/kbdlayout.c#L610), resulting in an eventual boot failure.

[WINLOGON] Fix fallback keyboard layout flags

---

modules/rostests/kmtests/kmtest_drv/kmtest_fsminifilter.c

@gedmurphy
- 1 "warning: variable 'Status' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]"
Double-check this fix, as I am unsure which default value should be used.
- 2 "warning: comparison of unsigned expression < 0 is always false [-Wtautological-unsigned-zero-compare]"
- Also update license header.
Double-check this fix, as I assumed a year for Thomas, as I am unsure why he is listed here.
plus
- Use a consistent type for "i" and fix a comment
Mark, never look at this additional commit...

CORE-14306. [KMTEST] Fix 3 Clang-Cl warnings about Status and Callbacks

---

ntoskrnl/mm/ARM3/sysldr.c

This will reenable write protection for system images, which got accidentally disabled earlier.

[NTOS::Mm] Fix inverted check in MiWriteProtectSystemImage

---

dll/win32/setupapi/cfgmgr.c

`HeapAlloc()` allocates a memory block which is never freed when the function finishes the last operation. Therefore, the resources allocated in the memory from the heap must be released. 
This patch fixes a Coverity issue with 1427056 CID.

[COVERITY][SETUPAPI] Release the blocks of memory when done

---

dll/appcompat/shims/genral/CMakeLists.txt
dll/appcompat/shims/layer/CMakeLists.txt
dll/appcompat/shims/layer/forcedxsetupsuccess.c
dll/appcompat/shims/shimlib/shimlib.c
dll/appcompat/shims/shimlib/shimlib.h
media/sdb/sysmain.xml
modules/rostests/apitests/appshim/CMakeLists.txt
modules/rostests/apitests/appshim/forcedxsetup.c
modules/rostests/apitests/appshim/layer_hooks.c
modules/rostests/apitests/appshim/testlist.c

This shim is used on older installers that try to install DirectX,
but encounter errors doing so with the bundled setup.
JIRA issue: [CORE-15814](https://jira.reactos.org/browse/CORE-15814)

[ACLAYERS] Implement the ForceDXSetupSuccess shim

---

dll/appcompat/apphelp/shimeng.c
dll/appcompat/apphelp/shimeng.h
dll/appcompat/shims/layer/CMakeLists.txt
dll/appcompat/shims/layer/forcedxsetupsuccess.c
dll/appcompat/shims/layer/ignoreloadlibrary.c
dll/appcompat/shims/shimlib/shimlib.c
dll/appcompat/shims/shimlib/shimlib.h
dll/ntdll/ldr/ldrutils.c
media/sdb/sysmain.xml
modules/rostests/apitests/appshim/CMakeLists.txt
modules/rostests/apitests/appshim/ignoreloadlib.c
modules/rostests/apitests/appshim/layer_hooks.c
modules/rostests/apitests/appshim/testlist.c
sdk/include/ndk/ldrtypes.h

* Simplify ForceDXSetupSuccess
* Add test for IgnoreLoadLibrary
* Add stubplemented IgnoreLoadLibrary shim
* Find shims case-insensitive
* Do not call module entrypoints while loading the shim engine.
* Implement experimental support for multiple hooks on the same function
JIRA issue: [CORE-15845](https://jira.reactos.org/browse/CORE-15845)
JIRA issue: [CORE-15846](https://jira.reactos.org/browse/CORE-15846)
JIRA issue: [CORE-15814](https://jira.reactos.org/browse/CORE-15814)

Implement IgnoreLoadLibrary & shimeng fixes

---

README.md

This was outdated, pointing to 0.4.10 not 0.4.11
- Just updated the link 
Also, should we link the mattermost chat server on the readme?
Taking about https://chat.reactos.org/
edit: this feels like such a waste of the CI's time, building it just for a readme update.

Updated the release link

---

dll/win32/ole32/ole2.c

The window that has `WS_EX_ACCEPTFILES` extended style, should pretend like a drop target that accepts `CF_HDROP` data. This PR will fix many bugs related to Drag & Drop.
JIRA issue: [CORE-11238](https://jira.reactos.org/browse/CORE-11238)

[OLE32] Implement WS_EX_ACCEPTFILES

---

dll/win32/shell32/dialogs/drvdefext.cpp

Disable the Hardware tab in the properties dialog for Network drives. This matches what Windows does. 
I've tested this and it didn't appear to break this tab for hard drives, cd drives and floppy drives but I can't test every scenario.

[SHELL32] Disable the Hardware tab in the properties dialog for Network drives

---

dll/win32/msi/action.c

Allow to pass product key validation check. This is actually a hackfix, but I'm not sure Wine will implement this function properly any time soon.
JIRA issue: [CORE-14710](https://jira.reactos.org/browse/CORE-14710)

[MSI] Allow to pass product key validation check

---

base/applications/sndvol32/lang/it-IT.rc

Better Italian translation.
I want to enhance the Italian translation.
Some days ago ElCresh has explained that In italian we indicate freq with "Alti" (plural) (Treble) and "Bassi" (plural) (Bass) and the volume with "Basso" (singular) and "Alto" (singular). So a mix of the two is the right answers.
https://github.com/reactos/reactos/pull/1401
I've updated the Italian terms for Bass and Treble.

[SNDVOL32] Small Italian translation update

---

dll/win32/comctl32/edit.c
win32ss/user/user32/controls/edit.c

Fix rectangle overflow when inserting characters in edit controls in `comctl32` and `user32`. This PR is based on patch by JIRA contributor 'I_Kill_Bugs'.
JIRA issue: [CORE-11475](https://jira.reactos.org/browse/CORE-11475)

Fix rectangle overflow when inserting characters

---

dll/win32/wtsapi32/wtsapi32.c
sdk/include/psdk/wtsapi32.h

Since ReactOS doesn't actually support non-local WinSTA/WTS capabilities, this seems to be a good way to reduce spam in the log while providing correct behaviour.
Also call Unicode version from ANSI one to reduce code duplication.
I have a [collection of patches](https://github.com/andrew-boyarshin/reactos/tree/a11y) to ReactOS for quite some time (regularly rebased upon upstream). Finally I've decided to send PRs upstream. These PRs (a lot more to come) are generated automatically based on latest `a11y` branch in my repo.
I am looking for a good guide related ReactOS changes to Winesynced code. What are my next steps?

[WTSAPI32] Implement WTSConnectState and WTSClientProtocolType in WTSQuerySessionInformation

---

base/applications/osk/main.c
base/applications/osk/main.h
base/applications/osk/settings.c

This PR implements a feature which lets On-Screen Keyboard launching its own dialog with previous coordinate values (this can be also seen with the Windows XP's counterpart of On-Screen Keyboard).
**Video URL**: https://www.youtube.com/watch?v=ONQjKg6I3jo

[OSK] Use the previous coordinate data of the dialog when launching

---

dll/win32/shell32/wine/shpolicy.c

I ran into a problem when I tried to [implement NoSimpleStartMenu](https://github.com/reactos/reactos/pull/1258) policy for explorer.
[_(message link)_](https://github.com/reactos/reactos/pull/1258#discussion_r249244170)
There are no backslash between ``Policies`` and ``Explorer``, we need to add one.
[CORE-15666](https://jira.reactos.org/browse/CORE-15666)
- ``strcat`` backslash before ``strcat`` ``p->appstr``

[SHPOLICY] Fix the missing backslash in SHRestricted

---

dll/win32/lpk/lpk.c
dll/win32/lpk/lpk.spec
dll/win32/lpk/ros_lpk.h
dll/win32/lpk/stub.c
sdk/include/reactos/undocgdi.h
win32ss/gdi/gdi32/include/gdi32p.h
win32ss/gdi/gdi32/objects/text.c
win32ss/gdi/gdi32/objects/utils.c

Implement and integrate LpkGetTextExtentExPoint into GDI32.
The main improvement will be that for certain texts written in complex scripts there would more correct size calculations, using data generated from USP10.
This is most noticeable with scripts that undergo ligation before being displayed such as Arabic.
Use GetTextExtentExPointWPri to forward non-complex text back to the gdi.

[LPK][GDI32] Implement LpkGetTextExtentExPoint

---

dll/win32/comctl32/edit.c
win32ss/user/user32/controls/edit.c

Fix caret and scroll position in edit controls in `comctl32` and `user32`. This PR is based on patch by JIRA contributor 'I_Kill_Bugs'.
JIRA issue: [CORE-15780](https://jira.reactos.org/browse/CORE-15780)

Fix caret and scroll position in edit controls

---

base/shell/explorer/trayclock.cpp

Add date tooltip to taskbar clock.
JIRA issue: [CORE-11444](https://jira.reactos.org/browse/CORE-11444)

[EXPLORER] Add date tooltip to taskbar clock

---

ntoskrnl/mm/section.c

If you open cmd.exe, enter "nul" and press enter, it will crash.
This PR fixes this crash.
Possibly related JIRA issue: [CORE-15589](https://jira.reactos.org/browse/CORE-15589)
@ThFabba said in the chat that this is the wrong way to solve the crash issue.
Maybe the problem is elsewhere.
Check FileObject->SectionObjectPointer value received by ObReferenceObjectByHandle for HANDLE of nul file in win.

Fix crash that occurs if nul is typed in cmd.exe

---

dll/win32/setupapi/devinst.c
dll/win32/setupapi/driver.c
dll/win32/setupapi/interface.c

The Reserved field is ULONG and we need ULONG_PTR. ClassInstallReserved was unused so far. I have no idea whether this is correct, but it cannot be more incorrect than what we had.

[SETUPAPI] Use ClassInstallReserved field instead of Reserved to store a pointer.

---

dll/win32/netapi32/netapi32.c
dll/win32/netapi32/netapi32.h
dll/win32/netapi32/user.c

The previous implementation used the resume_handle parameter to return a pointer to the active enumeration context, but resume_handle is a DWORD. To support 64 bit pointers, the enumeration context is inserted into a global linked list and given a unique 32 bit value as identifier for later lookup.
The way the function is implemented, leaking a data structure while the MSDN description does not indicate that, seems a little questionable in general, but that is something that I leave to the original author to investigate.

[NETAPI32] Fix NetUserEnum to work on x64

---

dll/win32/kernel32/kernel32.spec

This fixes an obvious typo in kernel32.spec where commas are incorrectly used to separate argument types

[kernel32] Fix typo in kernel32.spec

---

drivers/storage/ide/uniata/id_init.cpp

fix for uninitialized Lun pointer, CORE-15886
Fixes crash on Intel AHCI init
JIRA issue: [CORE-15886](https://jira.reactos.org/browse/CORE-15886)
AtapiSetupLunPtrs() was not called after UniataAllocateLunExt() in Intel SATA/AHCI detect code. It is necessary to do it at this moment because
we have to setup LUN-specfic flags at this moment.

[UNIATA] fix for uninitialized Lun pointer, CORE-15886

---

dll/win32/shell32/dialogs/filedefext.cpp

Fix application information in the file dialog

[SHELL32] Fix version info in the file dialog

---

modules/rostests/apitests/kernel32/JapaneseCalendar.c

- Skip tests if the current codepage is not Japanese.

[KERNEL32_APITEST] Follow up of #1466

---

sdk/lib/crt/printf/streamout.c

JIRA issue: [CORE-13955](https://jira.reactos.org/browse/CORE-13955)
This PR will reduce `wsprintf` function failures (`"%*s"`).

[CRT][USER32] fix wsprintf additional argument (%*s)

---

modules/rostests/apitests/kernel32/MultiByteToWideChar.c

Strengthen the testcase for `kernel32!MultiByteToWideChar` function.
JIRA issue: [ROSTESTS-282](https://jira.reactos.org/browse/ROSTESTS-282)
Tested on Win10:

[KERNEL32_APITEST] Improve MultiByteToWideChar testcase

---

dll/win32/kernel32/winnls/string/nls.c

This PR will reduce `MultiByteToWideChar` failures.
JIRA issue: [CORE-13349](https://jira.reactos.org/browse/CORE-13349)

[KERNEL32] Improve MultiByteToWideChar

---

boot/bootdata/hivedef.inf
win32ss/gdi/ntgdi/freetype.c
win32ss/user/ntuser/sysparams.c

Fix for the missing functionality of storing values FontSmoothing* in the registry
Also added render mode LCD for CLEARTYPE_QUALITY, when you enable font smoothing.

[FONT] Fix FontSmoothing params storing

---

modules/rostests/apitests/kernel32/JapaneseCalendar.c

Reported by @ThFabba in IRC, one-character Heisei for `CAL_SABBREVERASTRING` locale info can be `U+337B` or `U+5E73`. And one-character Reiwa `U+32FF`, `U+4EE4`, and `U+F9A8` are also added. Improve `kernel32_apitest` testcase.

[KERNEL32_APITEST] Improve one-character Heisei tests

---

drivers/hid/hidusb/hidusb.c

Now when unplugging the mouse while moving it, the driver does not assert

[USBHID] Do not assert if the device was unplugged during an operation.

---

dll/win32/shell32/shlfileop.cpp

This PR will reduce the failures of Move operation of `shell32!SHFileOperation` function.
JIRA issue: [CORE-13450](https://jira.reactos.org/browse/CORE-13450), [CORE-13176](https://jira.reactos.org/browse/CORE-13176)

[SHELL32] Fix SHFileOperation Move operation

---

win32ss/gdi/gdi32/objects/font.c

Make `gdi32!IntFontFamilyListUnique` function `std::unique` compatible.
JIRA issue: [CORE-15785](https://jira.reactos.org/browse/CORE-15785)

[GDI32] Improve IntFontFamilyListUnique function

---

win32ss/gdi/gdi32/include/precomp.h
win32ss/gdi/gdi32/objects/font.c
win32ss/gdi/ntgdi/freetype.c

Follow up of #1492.
JIRA issue: [CORE-15755](https://jira.reactos.org/browse/CORE-15755)
- Use `RtlULongMult` function to check integer overflows.
Cc @ThFabba

[GDI32][NTGDI] Avoid integer overflow (follow-up of #1492)

---

win32ss/gdi/eng/eng.h
win32ss/user/ntuser/event.c
win32ss/user/ntuser/input.c
win32ss/user/ntuser/keyboard.c
win32ss/user/ntuser/main.c
win32ss/user/ntuser/message.c
win32ss/user/ntuser/misc.c
win32ss/user/ntuser/mouse.c
win32ss/user/ntuser/msgqueue.c
win32ss/user/ntuser/msgqueue.h
win32ss/user/ntuser/timer.c

This PR will fix CORE-15565 and make #1245 GetMessageTime testcase successful.
JIRA issue: [CORE-15565](https://jira.reactos.org/browse/CORE-15565)
- Erase `MsqCalculateMessageTime` function.
- Use `(DWORD)EngGetTickCount()` instead.
- Ghosting is temporarily disabled.

[WIN32SS][NTUSER] Fix message time

---

dll/directx/wine/readme.txt

Fix 3 typos in dll/directx/wine/readme.txt, in words `tempary` and `sovlotions`. Replace them with correct `temporary` and `solutions`.

[DIRECTX] Fix typos in readme.txt

---

dll/cpl/openglcfg/lang/en-US.rc
dll/cpl/openglcfg/lang/tr-TR.rc

Capitalize configuration in the applet name for OpenGL configuration so it matches the rest of the Control Panel applets.

[OPENGLCFG] Capitalize Configuration in applet name

---

boot/bootdata/bootcdregtest/AHKAppTests.cmd

Addendum to df2a8c40becc5542bf093238826d795cce70a6c7.
@katahiromz

[BOOTDATA] AHKAppTests.cmd: Fix 'media' typo

---

sdk/cmake/msvc.cmake

Addendum to 545a2c79367e1457e4bc7ac14d3c0f840c7e063c.
@tkreuzer

CORE-7538. [CMAKE] msvc.cmake: Remove now redundant '/we4028' special case

---

modules/rostests/CMakeLists.txt
modules/rostests/apitests/atl/CAtlFileMapping.cpp
modules/rostests/apitests/atl/CComObject.cpp
modules/rostests/apitests/atl/CComQIPtr.cpp
modules/rostests/apitests/atl/CImage.cpp
modules/rostests/apitests/atl/CSimpleArray.cpp
modules/rostests/apitests/atl/CSimpleMap.cpp
modules/rostests/apitests/atl/CString.cpp
modules/rostests/apitests/atl/devenv/CComObject.vcxproj
modules/rostests/apitests/atl/devenv/CComQIPtr.vcxproj
modules/rostests/apitests/atl/devenv/CImage.vcxproj
modules/rostests/apitests/atl/devenv/CSimpleArray.vcxproj
modules/rostests/apitests/atl/devenv/CSimpleMap.vcxproj
modules/rostests/apitests/atl/devenv/CString.vcxproj
sdk/lib/atl/atlbase.h
sdk/lib/atl/atldef.h
sdk/lib/atl/atlfile.h

Adapt ReactOS ATL for RATL.
Independent ReactOS ATL (RATL): https://github.com/katahiromz/RATL
- Modify `atldef.h` for non-ReactOS environments.
- Update ATL testcase project files (from `v120_xp` to `v140_xp`).
- `#define HAVE_APITEST` and use it.
- `s/NULL/0/`

[ATL][ATLTEST] Adapt to RATL and improvements

---

dll/appcompat/shims/genral/ignorefreelib.c

Addendum to 007cc5cd8a4ede70516bf2bf15dd62af01dfc8f0, by @HeisSpiter.
- Fix a MSVC warning about a ShimLib_ShimFree() call.
"...\ignorefreelib.c(125): error C4090: 'function': different 'const' qualifiers"

CORE-7538. [ACGENRAL] Fix a C4090 warning

---

dll/opengl/opengl32/icdload.c
dll/opengl/opengl32/opengl32.h
ntoskrnl/ke/i386/cpu.c
ntoskrnl/mm/ARM3/vadnode.c
win32ss/user/winsrv/usersrv/init.c

Make the Nvidia Driver <181.22 working. With Success.
The first commit contains the actual fix.
The second one is to silence some very noisy FIXMEs which hit performance hard and it is very much desired to silence them.
Applications:
- A random "wglinfo.exe" i grabbed off the internet months ago
- ReactOS 3D-Text Screensaver
- A random "cube.exe" someone sent me.
Drivers:
- 175.19
- 181.22
Confirmed working Cards:
- 7300GS 175.19,181.22
- 8800GTS 181.22
- FX5900 175.19
- FX5500 175.19
- 6600 181.22
Everyone with a card supported by 181.22, please test and have some fun.
- FurMark keeps a blank window
- wined3d applications crash the driver
But these cause issues in a completely different area which i will now take a look into.
Lessons learned:
I was assuming the driver does messed up …

[OPENGL32] Fix use of registers

---

base/applications/mspaint/main.cpp

The filename extension is important information to choose the initial directory. This PR will set the default extension of `mspaint` to `.bmp`.
JIRA issue: [CORE-7114](https://jira.reactos.org/browse/CORE-7114)
Related to #1514.

[MSPAINT] Set default extension .bmp

---

dll/win32/shell32/CNewMenu.cpp
dll/win32/shell32/CNewMenu.h

This PR is retrial of #1510.
Right-Click Desktop, and Choose [New] --> [New Link]. Wizard will start up.
JIRA issue: [CORE-15511](https://jira.reactos.org/browse/CORE-15511)
Movie: https://jira.reactos.org/secure/attachment/52382/Shortcut2ndTrial.webm
- Set `NULL` to m_pItems in `CNewMenu::UnloadAllItems()`.
- Add `bIsShortcut` member into `SHELLNEW_ITEM` structure.
- Correctly create cache about `".lnk"`.
- Add special handling for the item of `bIsShortcut == TRUE`.
- Add `bRename` parameter to `CNewMenu::SelectNewItem`.
- Add and use `CNewMenu::NewItemByCommand` and `CNewMenu::NewItemByNonCommand` methods.

[SHELL32] Implement 'New Link' (Retrial of #1510)

---

dll/cpl/appwiz/createlink.c

When creating a shortcut file by appwiz.cpl, set description as filename for shortcut name.
Movie: https://jira.reactos.org/secure/attachment/52383/SetDescription.webm

[CPL][APPWIZ] Set description

---

modules/rostests/rosautotest/CPipe.cpp
modules/rostests/rosautotest/CPipe.h
modules/rostests/rosautotest/CProcess.cpp
modules/rostests/rosautotest/CWineTest.cpp

If there is no log output within 2 minutes, the test process is killed, and we continue with the next test.
This is a rather graceful approach compared to sysreg2's 3 minute timeout before killing and restarting the entire VM.
Since we added autochk for FAT filesystems, the filesystem is often "fixed" after a reset with the consequence that ReactOS doesn't boot up anymore.
The sysreg2 restart code still remains for handling tests causing BSODs.
This should fix our testbots, which currently randomly hang in winhttp:winhttp, then let sysreg2 kill the VM, and don't boot up anymore.

[ROSAUTOTEST] Implement a process activity timeout of 2 minutes

---

win32ss/gdi/ntgdi/freetype.c

Fix CORE-15785. When `LOGFONT.lfFaceName[0] == 0`, then enumeration of font substitutes had failed.
JIRA issue: [CORE-15785](https://jira.reactos.org/browse/CORE-15785)
BEFORE:
AFTER:

[WIN32SS][NTGDI] Keep FontSubstitutes enumeration CORE-15785

---

win32ss/gdi/ntgdi/freetype.c

The font size was a bit larger than expected. FireFox will show checkmarks correctly in View menu.
JIRA issue: [CORE-15303](https://jira.reactos.org/browse/CORE-15303)

[WIN32SS][NTGDI] FireFox checkmark fix CORE-15303

---

sdk/cmake/gcc.cmake
sdk/cmake/msvc.cmake

Up to CMake 3.3 LINK_DEPENDS was ignored in non-Makefile generators. See also http://www.cmake.org/pipermail/cmake/2010-May/037206.html. 
Since CMake 3.4 it is no longer ignored, but requires CMP0005 policy to be set to NEW and it requires a full path which was already correctly used on GCC, but not on MSVC builds.
This fixes
> ninja: error: FindFirstFileExA( d:/testproject/src): The filename, directory name, or volume label syntax is incorrect.
When building ReactOS with latest CMake (3.14.3)

[CMAKE] Fix LINK_DEPENDS usage

---

base/applications/mspaint/main.cpp
dll/win32/comdlg32/filedlg.c

Use the proper open/save initial folder for `comdlg32.GetOpenFileName` and `comdlg32.GetSaveFileName`.
JIRA issue: [CORE-7114](https://jira.reactos.org/browse/CORE-7114)
- Add and use two functions `FILEDLG95_MRU_load_ext` and `FILEDLG95_MRU_save_ext`. These functions load/save the MRU list in the registry key `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\OpenSaveMRU`.
- Use undocumented MRUList functions in `ComCtl32` to manipulate MRU lists.

[COMDLG32] Save open/save location by extension

---

dll/win32/kernel32/client/thread.c

Should remove some of the "SetThreadStackGuarantee(): stub" messages in some simple cases.
Examples: CORE-13678, CORE-10424, CORE-13562... Seems also to be called by .net apps.
Information at: https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-setthreadstackguarantee

[KERNEL32] Add an (incomplete) pre-implementation for SetThreadStackGuarantee().

---

modules/rostests/rosautotest/CConfiguration.cpp
modules/rostests/rosautotest/CPipe.cpp
modules/rostests/rosautotest/CWebService.cpp
modules/rostests/rosautotest/CWineTest.cpp
modules/rostests/rosautotest/main.cpp

Add missing ones in strings, Remove duplication on output..
Split off from #1531.

[ROSAUTOTEST] "Enforce" ending '\n' on C___Exception messages

---

win32ss/gdi/ntgdi/coord.h
win32ss/gdi/ntgdi/gdiobj.c
win32ss/gdi/ntgdi/gdiobj.h
win32ss/gdi/ntgdi/xformobj.c
win32ss/gdi/ntgdi/xformobj.h

There were wrong `IN`/`OUT` about the parameters of some NTGDI functions.
JIRA issue: [CORE-15983](https://jira.reactos.org/browse/CORE-15983)

[WIN32SS][NTGDI] Fix wrong IN/OUT

---

win32ss/include/ntuser.h
win32ss/user/ntuser/desktop.c
win32ss/user/user32/misc/desktop.c

2nd parameter is already passed in usermode GetThreadDesktop, actually use it in kernelmode as a fallback.

[WIN32K][NTUSER] Use 2nd parameter for NtUserGetThreadDesktop

---

ntoskrnl/mm/section.c

[NTOS/MM] Ensure ImageBase is not used uninitialized

---

win32ss/gdi/ntgdi/coord.c
win32ss/gdi/ntgdi/freetype.c

The `ExtTextOut` function didn't correctly update the current position when the text alignment was `TA_UPDATECP`.
JIRA issue: [CORE-14994](https://jira.reactos.org/browse/CORE-14994)
- Add `WORLD_XFORM_CHANGED` flag to some positioning functions.
- Fix `IntExtTextOutW` function for `TA_UPDATECP` alignment, so that it can correctly update the current position.

[WIN32SS][NTGDI] Fix ExtTextOut upon TA_UPDATECP

---

modules/rostests/apitests/gdi32/SetMapMode.c

Check the relation of mode change and viewport change.
JIRA issue: [CORE-14994](https://jira.reactos.org/browse/CORE-14994)
Win10:
Win2k3:
Successful.

[GDI32_APITEST] Improve SetMapMode testcase

---

dll/win32/comdlg32/filedlg.c

Fix treatment of wrong filename extensions.
JIRA issue: [CORE-15270](https://jira.reactos.org/browse/CORE-15270)
- Find `ext` in filter.
- Use first one if not found.
- Use default extension if no extension in filter.
- Add extension if `ext` is wrong or different.
- Update `hwndFileName`.

[COMDLG32] Fix treatment of wrong filename extension

---

modules/rostests/rosautotest/CJournaledTestList.cpp

This fixes back journal in ReactOS "at low costs". Indeed,
because write are improperly aligned right now, journaling
just fails.
With that patch, Cc will take care of aligning writes and
journal will be written again. Because flush operations
happen at each and every write to the journal, we expect
changes to land on disk quickly (not as quickly as if
they were directly written). But that's a good trade off
between over engineering and fixing a broken feature.
JIRA issue: [CORE-15973](https://jira.reactos.org/browse/CORE-15973)

[ROSAUTOTEST] Don't disallow buffering for journal file

---

ntoskrnl/config/cmhvlist.c
ntoskrnl/config/cmlazy.c
ntoskrnl/config/cmsysini.c
ntoskrnl/ex/handle.c
ntoskrnl/io/iomgr/driver.c
ntoskrnl/io/pnpmgr/pnpmgr.c
ntoskrnl/mm/ARM3/sysldr.c

MAX_PATH is a Win32 concept that makes no sense in the kernel (unless specifically interacting with a Win32 process). Plus, fixed size buffers should be avoided anyway where possible.

Improve buffer size handling / avoid MAX_PATH

---

modules/rostests/rosautotest/main.cpp

Let it be a bit more consistent.
Also, differentiate a bit more between tests, RosAutoTest and SysReg.
- wmain(): Use endl instead of '\n', for 'System uptime' 
- wmain(): Output "[ROSAUTOTEST] " in two cases:
'System uptime' and all CSimpleException.

WIP. [ROSAUTOTEST] Fix and improve some log handling

---

ntoskrnl/mm/section.c

this fixes some kernel32:loader tests

[NTOS/MM] Recognize AMD64 image in PeFmtCreateSection failure case

---

win32ss/gdi/ntgdi/freetype.c

Appendum to 1a402847ed307af7e72fcd9e15bb970b4285690d.
JIRA issue: [CORE-15838](https://jira.reactos.org/browse/CORE-15838)
Use a 16.16 fixed point value instead of `FT_FixedFromFloat` function.

[WIN32SS][NTGDI] Don't use FLOAT in IntEscapeMatrix

---

base/setup/reactos/lang/ru-RU.rc

Fix position of the controls in ReactOS 1st stage GUI setup for IDD_DRIVEPAGE, IDD_PARTITION, IDD_BOOTOPTIONS and IDD_RESTARTPAGE dialogs in Russian translation.
JIRA issue: [CORE-16038](https://jira.reactos.org/browse/CORE-16038)
Before:
After:

[SETUP] Fix controls position in 1st stage GUI setup for Russian translation

---

win32ss/gdi/ntgdi/freetype.c

Addendum to 0137096. Use `16.16` fixed-point values instead of `FLOAT`.
JIRA issue: [CORE-15838](https://jira.reactos.org/browse/CORE-15838)

[WIN32SS][NTGDI] Don't use FLOAT for orientation

---

modules/rostests/apitests/kernel32/CMakeLists.txt
modules/rostests/apitests/kernel32/SetComputerNameExW.c
modules/rostests/apitests/kernel32/testlist.c

Add testcase of `kernel32!SetComputerNameExW` function.
JIRA issue: [ROSTESTS-227](https://jira.reactos.org/browse/ROSTESTS-227)
Win2k3 (with Admin Rights):
Win10 (with Admin Rights):
Successful.

[KERNEL32_APITEST] Add SetComputerNameExW testcase

---

modules/rostests/apitests/kernel32/SetComputerNameExW.c

Addendum to 8aeb6a920ac68474a5118b778e7162f53ab17d4e.
JIRA issue: [ROSTESTS-227](https://jira.reactos.org/browse/ROSTESTS-227)
@katahiromz

[KERNEL32_APITEST] Improve SetComputerNameExW test a bit. ROSTESTS-227

---

dll/win32/kernel32/client/compname.c

Based on @Doug-Lyons's patch.
JIRA issue: [CORE-16058](https://jira.reactos.org/browse/CORE-16058)

[KERNEL32] Fix SetComputerNameExW

---

win32ss/gdi/ntgdi/freetype.c

In `NtGdiGetGlyphIndicesW` function, allocation of zero size had caused fatal failures.
JIRA issue: [CORE-12825](https://jira.reactos.org/browse/CORE-12825)
- Avoid allocation of zero size in `ExAllocatePoolWithTag` calls.
- Optimize for `cwc == 0`.

[WIN32SS][NTGDI] Avoid allocation of zero size in NtGdiGetGlyphIndicesW

---

modules/rostests/apitests/win32nt/CMakeLists.txt

Split `win32knt_apitest` to 3 modules (`win32knt_apitest`, `win32knt_xpsp2_apitest` and `win32knt_2k3sp2_apitest`) for usability.

[WIN32KNT_APITEST] Split win32knt_apitest to 3 modules

---

modules/rostests/apitests/kernel32/FLS.c

Statically linked `ntdll.RtlIsCriticalSectionLockedByThread` had made `kernel32_apitest` unable to run in XP.
JIRA issue: [CORE-16077](https://jira.reactos.org/browse/CORE-16077)

[KERNEL32_APITEST] dynamic linked RtlIsCriticalSectionLockedByThread

---

win32ss/user/user32/controls/appswitch.c

Reverts reactos/reactos#1299 (484943d). [CORE-15672](https://jira.reactos.org/browse/CORE-15672) was wrong.

Revert "[USER32] App Switcher should use the non-owned window's icon"

---

dll/win32/advapi32/reg/reg.c
drivers/filesystems/udfs/secursup.cpp
win32ss/user/user32/windows/clipboard.c

All is 'No functional change', but using same not-overkill pattern eases search, at least.
Addendum to JIRA issue: [CORE-14271](https://jira.reactos.org/browse/CORE-14271)
Could you answer the FIXME?
Just tell me if you refuse the 3rd/RegisterClipboardFormat() commit...
- [ADVAPI32] Simplify RtlCreateUnicodeStringFromAsciiz() return value check
- [USER32] Simplify RtlCreateUnicodeStringFromAsciiz() return value check
Also, add a FIXME.
- [USER32] Simplify RegisterClipboardFormatA/W() a bit
- [UDFS] Simplify SeSinglePrivilegeCheck() return value check

Misc addendum to CORE-14271

---

ntoskrnl/mm/section.c

Addendum to 98638cc2dfdde460ae49941c76dd51f1b796a001.
JIRA issue: [CORE-15981](https://jira.reactos.org/browse/CORE-15981)
- Improve indentation.
- Merge `#ifdef` cases.
- Add an explicit DIE().

[NTOS:MM] PeFmtCreateSection(): Improve AMD64 image failure case

---

win32ss/user/user32/windows/clipboard.c

Same pattern as lots of other `RtlCreateUnicodeStringFromAsciiz()` calls.
Follow-up to #1529.

[USER32] RegisterClipboardFormatA(): Enable a SetLastError()

---

dll/win32/advapi32/reg/reg.c

Follow-up to #1529.
Cc @katahiromz
---
Not this PR:
Note that `RtlUnicodeToMultiByteN()` is documented as able to convert to multi-byte ANSI codepages.
I am not sure that possibility is taken into account in this file. Possibly not elsewhere either.
You may want to double-check that and maybe file a Jira issue.

[ADVAPI32:REG] Remove some useless casts

---

dll/win32/ntdll_vista/condvar.c

As far as I can see, `_DEBUG` is defined/tested as value-less everywhere else.
If this case is an intended exception, then I would suggest to add a comment instead...

[NTDLL_VISTA] Check _DEBUG with #ifdef, not #if

---

modules/rosapps/applications/net/ncftp/libncftp/glob.c

As far as I can see, `_DEBUG` is defined/tested as value-less everywhere else.
If this case is an intended exception, then I would suggest to add a comment instead...
--
I add `__REACTOS__`, as this app is not documented as either sync'ed or forked.
Not sure if it should be upgraded or removed (as in made available through RApps)...
https://www.ncftp.com/download/

[NCFTP] Check _DEBUG with #ifdef, not #if

---

sdk/include/dxsdk/dxerr8.h
sdk/include/dxsdk/dxerr9.h

- Use '||', instead of '|', on a '#if'.
- Synchronize some white spaces and blank lines.

[DXSDK] Improve dxerr?.h a bit

---

sdk/include/reactos/libs/mbedtls/config.h

- Don't use '|' on a '#if'
- Remove a personal comment.

[MBEDTLS] Use '#ifndef __REACTOS__', instead of '#if DBG & 0'

---

sdk/lib/drivers/lwip/src/core/init.c

Last of `#if ... & ...` typos.
1st hunk is a duplicate block, the other 2 are obvious.
Cherry-pick
http://git.savannah.nongnu.org/cgit/lwip.git/commit/src/core/init.c?id=c0b534e5318baf870e2152c70d4d11a3a86181f3

[LWIP] Fix src/core/init.c a bit

---

dll/win32/browseui/browseui.spec
dll/win32/browseui/shellbars/CSHEnumClassesOfCategories.cpp
modules/rostests/apitests/browseui/CMakeLists.txt
modules/rostests/apitests/browseui/SHEnumClassesOfCategories.cpp
modules/rostests/apitests/browseui/testlist.c

Mark wrote
> Can we prove this is correct with an apitest?
JIRA issue: [CORE-11711](https://jira.reactos.org/browse/CORE-11711)
[WTB 52076](https://testbot.winehq.org/JobDetails.pl?Key=52076)
On ReactOS, test crashes with an 'Unhandled exception', on first `1, NULL` case, as the function does not/poorly validate arguments.
- [BROWSEUI] browseui.spec: Fix SHEnumClassesOfCategories() parameters
- [BROWSEUI_APITEST] Add a test for SHEnumClassesOfCategories

[BROWSEUI_APITEST] Add a test for SHEnumClassesOfCategories. CORE-11711

---

modules/rostests/apitests/kernel32/MultiByteToWideChar.c
modules/rostests/apitests/kernel32/TunnelCache.c
modules/rostests/apitests/ntdll/NtContinue.c
modules/rostests/apitests/shell32/CUserNotification.cpp
modules/rostests/apitests/win32nt/ntgdi/NtGdiEnumFontOpen.c
modules/rostests/kmtests/ntos_ke/KeEvent.c
modules/rostests/kmtests/ntos_ob/ObReference.c

A tiny part of the task,
until I find a better way to reliably find similar cases. (Helpwanted on that.)

[ROSTESTS] Add missing '\n' to a few skip()

---

dll/win32/shell32/CDefView.cpp

This partially reverts ae2a85d003da762e4bcb232b15f1180333e5917a.
JIRA issue: [CORE-16098](https://jira.reactos.org/browse/CORE-16098)
Cc @HBelusca

[SHELL32] SHCreateShellFolderView(): Fix parameter validation order. CORE-16098

---

dll/win32/comctl32/imagelist.c

- Add a hack to rename the exported functions and use the Internal_ prefix for them so that the IImageList can use them with minimal code changes.
- Add the correct implementation of the affected exported functions making them now use the IImageList of the passed HIMAGELIST.
This indirection is also needed because we can end up using image lists created by either comctl32 v5 or comctl32 v6. This is how windows manage to use an HIMAGELIST created by comctl32 v5 when it is passed to comctl32 v6. What really happens in this scenario is that the exported functions of both versions end up using the interface stored in the object without checking if this interface is the version provided in the same dll or in the other.
JIRA issue: [CORE-14433](https://jira.reactos.org/browse/CORE-14433) …

[COMCTL32] imagelist: Make the exported functions use the internal IImageList2

---

dll/win32/setupapi/cfgmgr.c

Previous code was correct.
This reverts commit c47ad98ff79ad98042ff2043d739be58770c2fbc.
@EricKohl doesn't answer email/mailinglist on this issue and has no account on mattermost...

[SETUPAPI] Revert "Fix a typo in CM_Query_Resource_Conflict_List."

---

base/applications/regedit/childwnd.c
base/applications/regedit/framewnd.c
base/applications/regedit/listview.c
base/applications/regedit/main.h

BEFORE:
AFTER:
- Adjust the splitter position to shrink it.
- Add a `cx` parameter to `CreateListView` function.
- Fix the ListView column widths by the percent values.
- Pass the valid rectangle upon `ChildWnd` creation.

[REGEDIT] Adjust ListView column widths

---

modules/rostests/apitests/kernel32/SetComputerNameExW.c

Improve `SetComputerNameExW` testcase to check invalid characters.
JIRA issue: [CORE-16122](https://jira.reactos.org/browse/CORE-16122)
Win2k3:
Successful.

[KERNEL32_APITEST] Improve SetComputerNameExW testcase

---

base/shell/explorer/syspager.cpp

In CNotifyToolbar::AddButton tbBtn.iBitmap (imagelist-index) was inialised with 0. Tigthvnc adds the icon wihtout NIF_ICON flag. So the wrong icon index was kept and later replaced.
This PR sets tbBtn.iBitmap to -1 and fixes some traces. (\n).
[CORE-14262](https://jira.reactos.org/browse/CORE-14262)

[EXPLORER] Fix CORE-14262 (tightvnc icon crosstalk)

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-14994](https://jira.reactos.org/browse/CORE-14994)
`TT_OS2.usWinAscent` and `TT_OS2.usWinDescent` must be treated as `FT_Short`. These values affect font metrics. This PR will fix CORE-14994.

[WIN32SS][NTGDI] usWinAscent and usWinDescent must be treated as signed

---

.github/FUNDING.yml

GitHub now supports [sponsorships](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/) in the repository.
I created `.github/FUNDING.yml` file which contains a link to Liberapay and ReactOS donation page. This will now display the sponsor button, but **you need to enable this in repository settings.**
If you also have other supported providers, you can also set up them in this file. You can see [more details](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) about this and details how to enable this.

Display a sponsor button in repository

---

base/applications/network/netstat/CMakeLists.txt
base/applications/network/netstat/lang/en-US.rc
base/applications/network/netstat/netstat.c
base/applications/network/netstat/netstat.h
base/applications/network/netstat/netstat.rc
base/applications/network/netstat/resource.h

Localize the netstat utility so it can be localized into different languages. Also, the File Description of the program has been to changed to better describe the purpose of the utility and also because one day we'll support TCP/IPv6.
JIRA issue: [CORE-16119](https://jira.reactos.org/browse/CORE-16119)
- Localize the utility to support multiple languages.
- Update the File Description to better reflect the purpose of the utility.

Netstat localize

---

CMakeLists.txt
drivers/wdm/audio/backpln/portcls/dma_slave.cpp
drivers/wdm/audio/backpln/portcls/miniport.cpp
drivers/wdm/audio/backpln/portcls/miniport_dmus.cpp
drivers/wdm/audio/backpln/portcls/pin_wavecyclic.cpp
drivers/wdm/audio/backpln/portcls/private.hpp
drivers/wdm/audio/drivers/CMIDriver/precomp.h
sdk/include/ddk/stdunk.h
sdk/lib/drivers/libusb/libusb.h
sdk/lib/drivers/sound/stdunk/cunknown.cpp

Fix for MSVC warning "C2323: 'operator new': non-member operator new or delete functions may not be declared static or in a namespace other than the global namespace."
See https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-what-s-new-2003-through-2015?view=vs-2019 section "Overloaded operator new and operator delete"

[STDUNK][PORTCLS][CMIDriver] Fix issue with operator new/delete

---

boot/freeldr/freeldr/arch/arm/macharm.c
boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/arch/i386/machxbox.c
boot/freeldr/freeldr/arch/i386/pcvideo.c
boot/freeldr/freeldr/arch/i386/xboxvideo.c
boot/freeldr/freeldr/include/arch/i386/machxbox.h
boot/freeldr/freeldr/include/arch/pc/machpc.h
boot/freeldr/freeldr/include/machine.h
boot/freeldr/freeldr/ntldr/winldr.c
drivers/setup/blue/blue.c

JIRA issue: [CORE-16116](https://jira.reactos.org/browse/CORE-16116)
- always set video mode to 80x50.
it's used for usetup & kernel boot screen will change video mode to VGA if required
- a~~dd text "Setup is starting ReactOS"
the same thing was since Windows NT setup, but in ReactOS it just shows black screen. Now everything is ok.~~
(outdated)

[FREELDR] Use text video mode for compatibility with /NOGUIBOOT

---

base/applications/network/netstat/netstat.c

On WXP,
`netstat -a -p UDP`
Before:
```
UDP    xyz:500        *:*
UDP    xyz:123        *:*
UDP    nnn:123       *:*
UDP    nnn:138       *:*
```
After:
```
UDP    xyz:isakmp     *:*
UDP    xyz:ntp        *:*
UDP    nnn:ntp       *:*
UDP    nnn:netbios-dgm *:*
```

[NETSTAT] ShowUdpTable(): Fix "tcp" copypasta

---

dll/directx/dsound_new/CMakeLists.txt
dll/directx/dsound_new/capturebuffer.c
dll/directx/dsound_new/misc.c
dll/directx/dsound_new/precomp.h
dll/directx/dsound_new/primary.c
dll/directx/dsound_new/property.c
dll/directx/dsound_new/resource.h
dll/directx/dsound_new/secondary.c
dll/directx/dsound_new/stubs.c

Add CMakeLists.txt and mostly fix gcc compilation of dsound_new. Although it is still not compilable, my PR fixes at least part of compilation issues.
If you want to test it, you need to comment out `add_subdirectory(dsound)` in dll/directx/wine/CMakeLists.txt and uncomment `#add_subdirectory(dsound_new) # disabled in trunk` in dll/directx/CMakeLists.txt.
JIRA issue: [CORE-16128](https://jira.reactos.org/browse/CORE-16128)

[DSOUND_NEW] Add CMakeLists.txt + fix gcc compilation

---

win32ss/gdi/eng/stubs.c

Make EngQueryDeviceAttribute return max acceleration level allowed.
This improves the stub to return 0 when queried for QDA_ACCELERATION_LEVEL and makes the call succeed.
I used this to check if the driver just thinks it is not allowed to operate the card at full speed, but it had no effect, however other drivers might act different and disable acceleration on failure.
Also updated the function description, suggested by hbelusca, as it is [here](https://git.reactos.org/?p=reactos.git;a=blob;f=sdk/include/psdk/winddi.h;hb=2e1f594d5e3f25b3aaf2bd6a9ee76a03f5279f0b#l2237).

[WIN32SS][GDI] Improve stub for EngQueryDeviceAttribute

---

ntoskrnl/cc/copy.c

Revert 'Properly align VACB writes' part of 2a80ae2bb6fdb4135d41244335caa2dadb6c8fa9.
JIRA issue: [CORE-15384](https://jira.reactos.org/browse/CORE-15384) and [CORE-16018](https://jira.reactos.org/browse/CORE-16018)
Cc @HeisSpiter
With regard to CORE-15067, kmtest:CcCopyRead result is unchanged :-)

[NTOS:CC] CcWriteVirtualAddress(): Do not round 'Size'. CORE-16018

---

dll/win32/iphlpapi/ifenum_reactos.c
dll/win32/iphlpapi/iphlpapi_main.c

[IPHLPAPI] Use if_descrlen field for determining the length of if_descr in IFEntry structure. This fixes heap corruption on GCC8.
JIRA issue: [CORE-16088](https://jira.reactos.org/browse/CORE-16088)

[IPHLPAPI] Fix heap corruption

---

ntoskrnl/mm/ARM3/mminit.c

Fix MmSizeOfSystemCacheInPages value on AMD64.
Addendum to d56a24908908b574852091af0b8bd9dca7bc1165.
JIRA issue: [CORE-14259](https://jira.reactos.org/browse/CORE-14259)
Cc @HeisSpiter
And add 'ASSERT(MmSystemCacheEnd == ...);'.

[NTOS:MM] Fix MmSizeOfSystemCacheInPages value on AMD64. CORE-14259

---

ntoskrnl/io/pnpmgr/pnproot.c

JIRA issue: [CORE-15882](https://jira.reactos.org/browse/CORE-15882)
Avoids a use of MAX_PATH.

[NTOS:PNP] Handle arbitrary subkey name lengths in EnumerateDevices

---

ntoskrnl/dbgk/dbgkobj.c
ntoskrnl/mm/ARM3/section.c

MmGetFileNameForAddress() calls RtlCreateUnicodeString().
This also fixes a leak in MiQueryMemorySectionName().

[NTOS:MM] Fix MmGetFileNameForAddress() callers

---

drivers/bus/acpi/acpica/include/platform/acmsvc.h
drivers/bus/acpi/acpica/include/platform/acwin64.h
drivers/bus/acpi/acpica/namespace/nsnames.c

This adds missing x64 locking code to ACPICA. Instead of replicating the x86 assembly, the code is written in C.
https://jira.reactos.org/browse/CORE-16082

[ACPICA] Fix MSVC x64 build

---

base/applications/osk/lang/ar-DZ.rc
base/applications/osk/lang/cs-CZ.rc
base/applications/osk/lang/de-DE.rc
base/applications/osk/lang/en-GB.rc
base/applications/osk/lang/en-US.rc
base/applications/osk/lang/es-ES.rc
base/applications/osk/lang/et-EE.rc
base/applications/osk/lang/fr-CA.rc
base/applications/osk/lang/fr-FR.rc
base/applications/osk/lang/he-IL.rc
base/applications/osk/lang/id-ID.rc
base/applications/osk/lang/it-IT.rc
base/applications/osk/lang/pl-PL.rc
base/applications/osk/lang/ro-RO.rc
base/applications/osk/lang/ru-RU.rc
base/applications/osk/lang/tr-TR.rc
base/applications/osk/lang/zh-CN.rc
base/applications/osk/lang/zh-TW.rc
base/applications/osk/main.c
base/applications/osk/main.h
base/applications/osk/settings.c

With this implementation, it allows On-Screen Keyboard to be placed at the topmost state in Z order remaining above the non-topmost windows.

[OSK] Implement "Always on Top" feature

---

boot/freeldr/freeldr/arch/i386/pcmem.c
boot/freeldr/freeldr/arch/i386/xboxdisk.c
boot/freeldr/freeldr/arch/i386/xboxmem.c

Fix memory initialization on Xbox.  This PR is based on @mborgerson's misc hacks patch https://github.com/mborgerson/reactos/commit/0015a2e2b66c5b189f2802f29b871c55bc43661c.
No hacks here! :wink: 
JIRA issue: [CORE-16206](https://jira.reactos.org/browse/CORE-16206)
- Whitespace improvements (in a separate commit)
- Refactor and use PC memory map init functions
- This fixes filesystem detection and probably some other problems

[FREELDR] Fix memory initialization on Xbox

---

boot/freeldr/freeldr/arch/i386/hardware.c
boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/arch/i386/machxbox.c
boot/freeldr/freeldr/include/machine.h

Abstract floppy drive detection code.  This PR is based on @mborgerson's misc hacks patch https://github.com/mborgerson/reactos/commit/0015a2e2b66c5b189f2802f29b871c55bc43661c.
No hacks here! :wink: 
JIRA issue: [CORE-16207](https://jira.reactos.org/browse/CORE-16207)
- Make floppy detection code machine-specific, because Xbox CMOS cannot be used to detect floppies
- This fixes freeloader hanging at "Detecting hardware..."

[FREELDR] Abstract floppy drive detection code

---

boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/arch/i386/machxbox.c
boot/freeldr/freeldr/arch/i386/pcvideo.c
boot/freeldr/freeldr/arch/i386/xboxvideo.c
boot/freeldr/freeldr/include/arch/i386/machxbox.h
boot/freeldr/freeldr/include/arch/pc/machpc.h
boot/freeldr/freeldr/include/machine.h
boot/freeldr/freeldr/ntldr/arch/i386/winldr.c

Abstract VGA BIOS specific code.
JIRA issue: [CORE-16210](https://jira.reactos.org/browse/CORE-16210)
- `WinLdrSetupSpecialDataPointers()` uses INT 10h video interrupts, but they are not available on Xbox, so make them machine-specific
- Next it also uses INT 15h AH=C1h to get extended BIOS data area, but it doesn't exist on Xbox either, so make it machine-specific too
- This fixes freeloader hanging after "Loading boot devices..."

[FREELDR] Abstract VGA BIOS specific code

---

win32ss/gdi/ntgdi/font.c
win32ss/gdi/ntgdi/freetype.c

Add raster font (`*.fnt` and `*.fon` files) support.
JIRA issue: [CORE-16165](https://jira.reactos.org/browse/CORE-16165)
- Add `IntGetCharSet` function to get the charset by index and/or the number of charsets.
- Make `IntGdiLoadFontsFromMemory` a non-recursive function.
- `IntGetOutlineTextMetrics` accepts raster fonts.
- Improve CharMap handling (especially `TT_PLATFORM_APPLE_UNICODE`).
- Write the raster font file info to the registry.
- Don't request font size for raster fonts in `IntRequestFontSize` function.

[WIN32SS][NTGDI] Support raster fonts (*.fnt and *.fon)

---

dll/win32/advapi32/token/token.c

A minor fix to reduce an excessive allocation.
According to [the documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-rtlcreateacl) and the `ACCESS_ALLOWED_ACE` structure.
I saw that there are [other places](https://github.com/reactos/reactos/search?q=sizeof%28ACCESS_ALLOWED_ACE%29&unscoped_q=sizeof%28ACCESS_ALLOWED_ACE%29) where `sizeof(ACCESS_ALLOWED_ACE)` is used without subtracting the `sizeof(ULONG)`, you guys who are more familiar with the code might want to look at it.

Removed excessive allocation

---

win32ss/gdi/dib/stretchblt.c
win32ss/gdi/ntgdi/bitmaps.c

We assume `pso->sizlBitmap.cy` is positive.
JIRA issue: [CORE-15995](https://jira.reactos.org/browse/CORE-15995)
Because `pso->sizlBitmap.cy` is certificated as a positive value after initialization in `SURFACE_AllocSurface`, so we can safely omit `abs` and `labs` (absolute) function calls for it.

[WIN32SS][GDI] Assume pso->sizlBitmap.cy positiveness

---

dll/directx/dsound_new/CMakeLists.txt

Completely fix gcc compilation of `dsound_new` by linking some more needed libraries. Spotted by @feel-the-dz3n.
If you want to test it, you need to comment out `add_subdirectory(dsound)` in `dll/directx/wine/CMakeLists.txt` and uncomment `#add_subdirectory(dsound_new) # disabled in trunk` in `dll/directx/CMakeLists.txt`.
JIRA issue: [CORE-16128](https://jira.reactos.org/browse/CORE-16128)
- Add `ksuser`, `ole32`, `setupapi` and `user32` libs in `add_importlibs()` section of `dll/directx/dsound_new/CMakeLists.txt`.

[DSOUND_NEW] Completely fix gcc compilation (addendum to #1672)

---

base/services/w32time/w32time.c

Use `32400` as a fallback setting for `GetIntervalSetting`, which is equal to 9 hour rather than `0` which prevents spamming the time servers if the registry entry becomes corrupted or missing.
Also, disallow a setting of less than 2 minutes and instead use the fallback of 9 hour. 
JIRA issue: [CORE-16181](https://jira.reactos.org/browse/CORE-16181)

[W32Time] Use a reasonable fallback of 9 hours

---

base/services/umpnpmgr/install.c
base/services/umpnpmgr/precomp.h
base/services/umpnpmgr/umpnpmgr.c

Windows XP and Server 2003 use `SuppressUI` and `SuppressNewHWUI` registry values to allow or not the "New Hardware Wizard" dialog to be displayed of NEWDEV component.
Specifically, Windows XP 32-bit uses `SuppressNewHWUI` whereas Server 2003 and XP 64-bit use `SuppressUI` but for compatibility reasons we'll be going to implement registry functions to handle both of these values.
**JIRA Issue:** [CORE-15897](https://jira.reactos.org/browse/CORE-15897)

[UMPNPMGR] Implement registry handler functions for wizard suppression

---

base/system/winlogon/winlogon.c
dll/win32/netid/netid.c

Fixes updating Hostname in registry after Computer Name Change and reboot.
JIRA issue: [CORE-16123](https://jira.reactos.org/browse/CORE-16123)
Changes to netid.c correct the call when using the Computer Name change in ReactOS.
Changes to winlogon.c add the ability to copy from the "NV Hostname" to the "Hostname"

Fix Computer Name Change to update Hostname on reboot.

---

base/services/shsvcs/shsvcs.spec
dll/directx/bdaplgin/bdaplgin.spec
dll/directx/ddraw/ddraw.spec
dll/directx/msdvbnp/msdvbnp.spec
dll/directx/msvidctl/msvidctl.spec
dll/shellext/netplwiz/netplwiz.spec
drivers/multimedia/bdasup/bdasup.spec
sdk/tools/spec2def/spec2def.c

Fix handling of OLE exports: they should be PRIVATE and have no manually-assigned ordinals.
```
[SPEC2DEF] Check whether OLE-specific exports do not have assigned ordinals, as they should be.
The check is done at the same time as when we check also that these
exports are marked PRIVATE or not.
This permits us to check for the same conditions as MS' LINK.EXE, but
here on GCC builds as well.
See the following pages for more details:
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4104
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4222
In this last page (LNK4222), the specified list of exports is incomplete.
Manual tests showed that the very same list as for LNK4104 is checked.
```
```
[DLLs] Fix .spec files …
```

Fix handling of OLE exports

---

boot/freeldr/freeldr/arch/i386/hwdisk.c
boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/arch/i386/machxbox.c
boot/freeldr/freeldr/arch/i386/xboxdisk.c
boot/freeldr/freeldr/disk/disk.c
boot/freeldr/freeldr/disk/partition.c
boot/freeldr/freeldr/include/arch/i386/machxbox.h
boot/freeldr/freeldr/include/disk.h
sdk/include/psdk/ntdddisk.h

- This allows to detect and dynamically handle different partitioning schemes.
- Implemented detection of MBR, GPT, Xbox-BRFR, and partitionless disks.
- Currently only MBR and Xbox-BRFR partitions are handled and tested.

[FREELDR] Implement proper partition type detection and handling

---

boot/freeldr/freeldr/arch/i386/hwdisk.c
boot/freeldr/freeldr/lib/fs/fat.c

- DiskGetFileInformation() should return relative addresses
- FatXSearchDirectoryBufferForFile() should assign file attributes
- Minor code style improvements in FatOpenVolume()
Many thanks to @Extravert-ir who helped to debug and spot all these hidden bugs. :beetle: 
JIRA issue: [CORE-16248](https://jira.reactos.org/browse/CORE-16248)

[FREELDR] Fix remaining hwdisk and FATX bugs

---

win32ss/gdi/ntgdi/freetype.c

Fix and improve font dumping.
JIRA issue: [CORE-16245](https://jira.reactos.org/browse/CORE-16245)
- `FontGDI->FontObj` is not a pointer.
- `"%s"` does null check, so we remove redundant null checks.
- Add `FaceName` and `StyleName` dumping.

[WIN32SS][NTGDI] Fix and improve font dumping

---

configure.cmd

Add detection for `Microsoft (R) C/C++ compiler 19.22.27905` which comes with VS Community 2019.
Builds ReactOS successfully and runs just fine:

[CONFIGURE] Add MSVC compiler 19.22.27905 (VS Community 2019)

---

sdk/lib/3rdparty/freetype/include/freetype/config/ftoption.h

This is a workaround of Font Hinting of FreeType.
JIRA issue: [CORE-15762](https://jira.reactos.org/browse/CORE-15762), [CORE-16232](https://jira.reactos.org/browse/CORE-16232)
It seems some fonts are blurry or in bad rendering because of FreeType Font Hinting implementation.
This PR is `subpixel2.patch` from CORE-16232, based on the following comment:
https://bugs.launchpad.net/ubuntu/+source/freetype/+bug/1722508/comments/29

[FREETYPE] Improve font rendering with font hinting workaround

---

win32ss/gdi/ntgdi/misc.h
win32ss/user/ntuser/main.c
win32ss/user/ntuser/misc.c

I think every language ID is an unsigned integer.
- Make `gusLanguageID` unsigned.
- Make the return value type of `UserGetLanguageID` unsigned.

[WIN32SS][NTGDI][NTUSER] Make gusLanguageID USHORT

---

dll/win32/kernel32/client/thread.c
dll/win32/kernel32/client/utils.c
dll/win32/kernel32/include/kernel32.h
sdk/lib/rtl/thread.c

[KERNEL32][RTL] Diverse fixes/improvements for thread stack creation code.
Also make kernel32!BaseCreateStack() compatible with ntdll!RtlpCreateUserStack().
Finally RtlpFreeUserStack() doesn't need to return anything.
JIRA issue: [CORE-11319](https://jira.reactos.org/browse/CORE-11319)

Investigate some potential issues in thread stack creation code (in kernel32 & RTL)

---

win32ss/gdi/ntgdi/freetype.c

- Improve size checking of `IntGetOutlineTextMetrics` function.

[WIN32SS][NTGDI] Improve IntGetOutlineTextMetrics

---

drivers/usb/usbaudio/filter.c
drivers/usb/usbaudio/pin.c

Fix gcc compilation issues of usbaudio driver. With this fixes, it's fully compilable.
If you want to test it, you need to add `add_subdirectory(usbaudio)` in `drivers/usb/CMakeLists.txt` and `usbaudio.sys = 1,,,,,,,4,,,,1,4` in `[SourceDiskFiles]` section of `boot/bootdata/txtsetup.sif`.
- Remove declaration and value of unused `SelectorUnitDescriptor` variable of `CountTopologyComponents` function in `drivers/usb/usbaudio/filter.c`;
- Add missing `const` to the 2nd argument of `GetDataRangeIndexForFormat` function in `drivers/usb/usbaudio/pin.c`.

[USBAUDIO] Fix compilation issues

---

win32ss/gdi/ntgdi/freetype.c

- Define `EMUBOLD_NEEDED` macro to determine the condition of bold emuration necessity.
- Use this macro.
- Loose the condition.

[WIN32SS][NTGDI] Fix condition of font bold emulation

---

dll/win32/syssetup/wizard.c

JIRA issue: [CORE-16291](https://jira.reactos.org/browse/CORE-16291)
BEFORE:
AFTER:

[SYSSETUP] Fix bold font

---

win32ss/user/ntuser/menu.c

JIRA issue: [CORE-16294](https://jira.reactos.org/browse/CORE-16294)
We had added "Arial Black" font, so a request for heavy weight font will be realized as it is. This PR will fix font weight (`FW_*`) calculation of default menu items.
BEFORE:
AFTER:

[WIN32SS][NTUSER] Fix default menu item font weight

---

media/inf/CMakeLists.txt
media/inf/btrfs.inf

Added brtfs.inf 
JIRA issue: [CORE-15928](https://jira.reactos.org/browse/CORE-15928)
I added the inf from the btrfs driver's github to our repository so that we no longer have it listed as an unknown device.
Only difference between this and the original is that I removed the copy files (as they are already installed) and I added the compatible device ID of `DETECTED\BTRFS` because this is what ReactOS listed as the compatible ID.
Before:
After:

[INF] Added BTRFS inf to remove unknown device

---

dll/win32/syssetup/wizard.c

JIRA issue: [CORE-16295](https://jira.reactos.org/browse/CORE-16295)
BEFORE:
AFTER:

[SYSSETUP] Caption of 2nd stage ReactOS Setup is too heavy

---

win32ss/gdi/ntgdi/region.c

CORE-15992
_Correct code for nested loops and comparison operator_
JIRA issue: [CORE-15992](https://jira.reactos.org/browse/CORE-15992)
Testbot runs:
https://reactos.org/testman/compare.php?ids=68618,68620
https://reactos.org/testman/compare.php?ids=68619,68621

Fix two ASSERTS in win32ss\gdi\ntgdi\region.c

---

boot/freeldr/freeldr/arch/i386/pcmem.c
boot/freeldr/freeldr/arch/i386/xboxmem.c
boot/freeldr/freeldr/include/arch/pc/pcbios.h

Memory map array should be large enough to fit additional descriptors.
JIRA issue: [CORE-16267](https://jira.reactos.org/browse/CORE-16267)

[FREELDR] xboxmem: Fix array out-of-bounds access

---

boot/freeldr/freeldr/lib/inifile/ini_init.c
boot/freeldr/freeldr/lib/peloader.c
boot/freeldr/freeldr/ntldr/winldr.c
boot/freeldr/freeldr/ntldr/wlregistry.c

At the moment, Freeloader is silent about the status, returned by Arc* functions, which makes FS debugging much harder. Fixing this

[FREELDR] Verbose error output for FS errors

---

win32ss/user/ntuser/menu.c

JIRA issue: [CORE-13211](https://jira.reactos.org/browse/CORE-13211)
Fix drawing the menu scrolling arrows.
BEFORE:
AFTER:

[WIN32SS][NTUSER] Fix MENU_DrawScrollArrows

---

win32ss/user/ntuser/class.c
win32ss/user/ntuser/menu.c

JIRA issue: [CORE-16244](https://jira.reactos.org/browse/CORE-16244)
- Fix the class style, the window style and the extended style of the popup menu window.
I have investigated and confirmed these style values by WinHier in Win2k3.

[WIN32SS][NTUSER] Fix popup menu window styles

---

win32ss/gdi/ntgdi/font.h
win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.h

JIRA issue: [CORE-16269](https://jira.reactos.org/browse/CORE-16269)
- Add `IntGdiAddFontResourceEx` function that is extended from `IntGdiAddFontResource`, in order to add `dwFlags` parameter.
- Add `IntLoadFontsInRegistry` function that will load the fonts from registry info.
- If loading from registry failed, `IntLoadSystemFonts` will be called.
- Use `IntLoadFontsInRegistry` rather than `IntLoadSystemFonts` in the OS startup.
- Add `NameFromCharSet` function.
- Append `" (CharSetName)"` to registry value name if not TrueType.

[WIN32SS][NTGDI] Registry-based font management

---

win32ss/user/ntuser/menu.c

There were menu drawing regression after https://github.com/reactos/reactos/commit/03adec81414abb53e589ecd9061042b9ca2104c1.
This PR will fix it.
JIRA issue: [CORE-16244](https://jira.reactos.org/browse/CORE-16244)
- We don't have to draw the frame manually because of `WS_EX_DLGMODALFRAME` extended style.
- We don't need the margins (`MENU_TOP_MARGIN` and `MENU_BOTTOM_MARGIN`) in the client area any more because the client area doesn't contain the frame width.
- Use `GetSystemMetrics(SM_CXDLGFRAME)` and `GetSystemMetrics(SM_CYDLGFRAME)` for frame width.

[WIN32SS][NTUSER] Fix menu drawing after style change

---

ntoskrnl/ps/state.c
sdk/include/ndk/kefuncs.h

Actually rename NtQueueApcThread to NtQueueApcThreadEx and ignore one additional parameter for now.
The ignored parameter is for careful memory allocation in critical codepaths ([ref](https://wj32.org/wp/2010/07/18/the-nt-reserve-object/)). ReactOS doesn't care much about these things in pre-beta stage.
It's not exported for now, but will be in the future in Vista+ version of the NTDLL.

[NTOSKRNL][PS] Implement NtQueueApcThreadEx and use it in NtQueueApcThread

---

dll/win32/kernel32/client/vista.c

JIRA issue: [CORE-12596](https://jira.reactos.org/browse/CORE-12596)
- 1 trivial code improvement.
- 1 compilation fix, at least with GCC.

CORE-12596. Partially fix dll/win32/kernel32/client/vista.c compilation as NT6

---

dll/win32/shell32/folders/CDesktopFolder.cpp

1. Right Click the Desktop.
2. Choose "Properties" menu item.
3. "Properties for Display" dialog must be shown.
JIRA issue: [CORE-16299](https://jira.reactos.org/browse/CORE-16299)

[SHELL32] Fix Desktop Properties menu item action

---

ntoskrnl/ke/i386/usercall.c
ntoskrnl/mm/ARM3/procsup.c

Move this `DPRINT1()` to `KiUserModeCallout()` from `MmGrowKernelStackEx()`.
As suggested by @ThFabba::
> MmGrowKernelStackEx really shouldn't be DPRINT'ing. Apparently that uses too much stack. Maybe moving the print to KiUserModeCallout would make things less likely to fail.
JIRA issue: [CORE-14494](https://jira.reactos.org/browse/CORE-14494)

CORE-14494. [NTOSKRNL] Move DPRINT1("Thread wants too much stack\n") around

---

base/applications/taskmgr/endproc.c
base/applications/taskmgr/precomp.h

_ReactOS Task Manager has an option to shut down process trees, but it's not implemented properly (just the parent is terminated instead of the whole tree). This PR implements the missing functionality._
- Implement ShutdownProcessTree (and its helper, ShutdownProcessTreeHelper) in endproc.c and use it in ProcessPage_OnEndProcessTree.

[TASKMGR] Implement proper process tree ending

---

drivers/network/ndis/ndis/miniport.c
drivers/network/ndis/ndis/protocol.c

Full consistency, for real: fix building with `DBG=0`, broken by newest change.
[r1318](https://git.reactos.org/?p=reactos.git;a=commit;h=33252ab449df0b203a901b15a90ab26377b438f6): Add `MiniDisplayPacket()`, within `#ifdef DBG`. (1 miniport.h, 2 miniport.c, 1 protocol.c)
[r6295](https://git.reactos.org/?p=reactos.git;a=commit;h=74be14122f2c1169df97a9ba2c6b7b4ce3e5b35b): Always compile `MiniDisplayPacket()` itself/only, but with `#if 0` code. Add `MiniDisplayPacket2()`, with `#if 0` code.
[r10307](https://git.reactos.org/?p=reactos.git;a=commit;h=bc0ec8c03d9143c489be2d82817e067d62ddc15b): Enable `#ifdef DBG` in `MiniDisplayPacket2()`.
Between r11789 and r11883: Enable `#ifdef DBG` in `MiniDisplayPacket()`.
[r37559](https://git.reactos.org/?p=reactos.git;a=commit;h=438ac1d7da3218b28ff4e0df4c …

[NDIS] Enforce '#if DBG' around MiniDisplayPacket[2]()

---

dll/win32/comctl32/imagelist.c

Saturated images: Take mask-images in account.
Fixes JIRA issue: [CORE-14209](https://jira.reactos.org/browse/CORE-14209)

Fix CORE-14209 - Some icons not drawn in IDA Free v5.0 in 32bpp

---

drivers/filesystems/ntfs/attrib.c
drivers/filesystems/ntfs/mft.c
drivers/filesystems/ntfs/ntfs.h

Trying to implement proper handling of $ATTRIBUTE_LIST attribute, which references other MFT records containing attributes for the files
JIRA issue: [CORE-13575](https://jira.reactos.org/browse/CORE-13575)
- Lookup attributes into $ATTRIBUTE_LIST and referenced into another MFT record when not found.
Handle the case where the non-resident attribute is split across several file records (like it happens for test file in image attached in the issue)
There are two records in the $ATTRIBUTE_LIST with same AttributeType and name, but StartingVCN differs. RunLists for the other records need to be parsed too (and first data run is relative to cluster 0 again).

[NTFS] Handling of $ATTRIBUTE_LIST

---

base/applications/network/netstat/netstat.c

On WXP,
`netstat -p UDP`
WXP netstat:
```
Active Connections
Proto  Local Address          Foreign Address        State
```
ROS netstat (before):
```
Active Connections
Proto  Local Address          Foreign Address        State
UDP    xyz:500        *:*
UDP    xyz:123        *:*
UDP    nnn:123       *:*
UDP    nnn:138       *:*
```

[NETSTAT] '-p UDP' depends on '-a'

---

dll/win32/comctl32/status.c

Hide status bar size grip when window is maximized.
JIRA issue: [CORE-15240](https://jira.reactos.org/browse/CORE-15240)
- Hide size grip of status bar when `SW_MAXIMIZE` is set on the parent window.

[COMCTL32] Hide status bar size grip when window is maximized

---

boot/bootdata/txtsetup.sif
hal/halx86/CMakeLists.txt
hal/halx86/legacy/bus/pcibus.c
hal/halx86/xbox.cmake
hal/halx86/xbox/halinit_xbox.c

- Create `xbox.cmake` based on `legacy.cmake` and `pic.cmake`
- Revive Xbox HAL files and add them to the build
- Fix boot with Xbox HAL, add missing parts from `halinit_up.c`
- Code style and debug logging improvements in `pcibus.c`
- Allow to choose Xbox HAL in usetup
Please add to XBOX Boot milestone. :wink:

[HAL] Add Xbox Hardware Abstraction Layer

---

dll/win32/comctl32/comctl32.spec

They are already implemented and there is little sense for them to be hidden.
Required for ProcessHacker 3.0+.
I have a [collection of patches](https://github.com/andrew-boyarshin/reactos/tree/a11y) to ReactOS for quite some time (regularly rebased upon upstream). Finally I've decided to send PRs upstream. These PRs (a lot more to come) are generated automatically based on latest `a11y` branch in my repo.

[COMCTL32] Export LoadIconMetric and LoadIconWithScaleDown

---

base/services/audiosrv/audiosrv.txt
boot/bootdata/hivesys.inf
dll/cpl/mmsys/mmsys.c
sdk/include/reactos/libs/audiosrv/audiosrv.h

Rename RosAudioSrv to AudioSrv in audio service itself and in all system components which are related to this, same as it done in Win2k3.
It allows MS DxDiag to detect the system audio service correctly, so it becomes possible to run DirectSound test properly with MS dsound.dll, although it works with some minor errors and only in older VirtualBox versions, ~ up to 5.1.38 (and in other emulators as well).
JIRA issue: [CORE-16307](https://jira.reactos.org/browse/CORE-16307)
Rename RosAudioSrv to AudioSrv in the following source files:
- `base/services/audiosrv/audiosrv.txt` (just description of audio service, it doesn't make any changes in the system);
- `boot/bootdata/hivesys.inf` (registry values of the audio service);
- `dll/cpl/mmsys/mmsys.c` (audio properties cpl part, which calls it …

[AUDIOSRV][BOOTDATA][INCLUDE][MMSYS] Rename RosAudioSrv to AudioSrv

---

boot/freeldr/freeldr/arch/i386/machpc.c
boot/freeldr/freeldr/arch/i386/machxbox.c
boot/freeldr/freeldr/include/arch/i386/machxbox.h
boot/freeldr/freeldr/include/arch/pc/hardware.h

Add Serial ports detection in `DetectIsaBios()`. This is based on PC serial port detection code.
Please add to XBOX Boot milestone. :wink:

[FREELDR] Add Serial ports detection in DetectIsaBios()

---

boot/freeldr/freeldr/arch/i386/machxbox.c

This fixes null pointer call bug, which was revealed in 85d44fc by @HBelusca. Bug spotted by Mark Jansen.
Please add to XBOX Boot milestone. :wink:

[FREELDR] Add missing VideoSetTextCursorPosition handler for Xbox

---

dll/win32/comctl32/propsheet.c

Sorry, my mistakes continued. #1840 and #1841 are incorrect.
JIRA issue: [CORE-16280](https://jira.reactos.org/browse/CORE-16280)
BEFORE:
AFTER:
In my testing on Win2k3, `EN_CHANGE` is generated in `OnInitDialog`, that is correct. The target is property sheet. The property sheet does unchange the page after `WM_INITDIALOG` generation.

[COMCTL32] Unchange the property sheet page after WM_INITDIALOG

---

dll/cpl/desk/screensaver.c

Currently the EDITTEXT control receives EN_CHANGE/EN_UPDATE notification codes in a bad manner. These notifications must be sent only when the user takes action to the control although the notifications are always sent even without the user's prompt!
This is merely a temporary fix for **desk.cpl**. When James Tabor (or whoever else) will provide a fix for the regression, the final patch for **desk.cpl** is to check properly for EN_CHANGE.
**JIRA Issue:** [CORE-16280](https://jira.reactos.org/browse/CORE-16280)
**EDIT 1 -** [`344d559`](https://github.com/reactos/reactos/commit/344d5599351c5abae618dae9693a655cdc34dab0) has been finally merged. Here it's the final proper fix.

[DESK] Change the property "Screensaver" page on text change

---

ntoskrnl/io/iomgr/iomgr.c

Fix building with `-DCMAKE_BUILD_TYPE=Release`.
Initial code added on [r25987](https://git.reactos.org/?p=reactos.git;a=commit;h=be2645ad8a5492bfc124b0d98f4ab81c03b27f0c).
Is it the right check to add?
Are both checks needed, or would `#ifdef KDBG` be enough?

[NTOS:IO] iomgr.c: Add a missing '#if defined(KDBG)'

---

dll/win32/iphlpapi/icmp.c
media/doc/README.WINE

Noticed while checking sync/fork before [CORE-14411](https://jira.reactos.org/browse/CORE-14411).
Fix diff, ease sync.
JIRA issue: [CORE-10536](https://jira.reactos.org/browse/CORE-10536)
Addendum to [r70275](https://git.reactos.org/?p=reactos.git;a=commit;h=658ef83c7fe8c518c2347549a582a6c35556683f).
- Restore a missing brace.
- Mark all our differences (at that time). Please inspect them.

CORE-10536. [IPHLPAPI] icmp.c: Complete sync with Wine Staging 1.7.55

---

CMakeLists.txt

Remove confusion, as in #1628.

[CMAKE] KDBG and _WINKD_ do not need a value

---

sdk/include/psdk/ntddndis.h

Part of it was already added in 3da616a. [CORE-11924](https://jira.reactos.org/browse/CORE-11924)

[DDK][PSDK] Add missing definitions for WPA/WPA2 authentication

---

base/applications/cmdutils/reg/lang/bg-BG.rc
base/applications/cmdutils/reg/lang/cs-CZ.rc
base/applications/cmdutils/reg/lang/da-DK.rc
base/applications/cmdutils/reg/lang/de-DE.rc
base/applications/cmdutils/reg/lang/en-US.rc
base/applications/cmdutils/reg/lang/es-ES.rc
base/applications/cmdutils/reg/lang/fr-FR.rc
base/applications/cmdutils/reg/lang/it-IT.rc
base/applications/cmdutils/reg/lang/ja-JP.rc
base/applications/cmdutils/reg/lang/ko-KR.rc
base/applications/cmdutils/reg/lang/lt-LT.rc
base/applications/cmdutils/reg/lang/nl-NL.rc
base/applications/cmdutils/reg/lang/no-NO.rc
base/applications/cmdutils/reg/lang/pl-PL.rc
base/applications/cmdutils/reg/lang/pt-PT.rc
base/applications/cmdutils/reg/lang/ro-RO.rc
base/applications/cmdutils/reg/lang/ru-RU.rc
base/applications/cmdutils/reg/lang/sl-SI.rc
base/applications/cmdutils/reg/lang/sq-AL.rc
base/applications/cmdutils/reg/lang/sv-SE.rc
base/applications/cmdutils/reg/lang/tr-TR.rc
base/applications/cmdutils/reg/lang/uk-UA.rc
base/applications/cmdutils/reg/lang/zh-CN.rc
base/applications/cmdutils/reg/lang/zh-TW.rc
base/applications/cmdutils/reg/reg.c
base/applications/cmdutils/reg/resource.h

Does what the title of the PR says. These changes have been tested on Windows 10, and work flawlessly there. (You'll need to run reg.exe elevated to test the save and restore commands on Windows 10, though.) I am aware that `RegRestoreKeyW` is unimplemented on ReactOS.
- Add support for REG SAVE and REG RESTORE
- Two new strings have been copied to the foreign-language RC files for reg.exe; however, since I only speak English, they have not been translated.

Add support for save and restore reg.exe subcommands

---

base/applications/calc/CMakeLists.txt
base/applications/calc/htmlhelp.c
base/applications/calc/winmain.c

Some years are passed since 2005 and nowadays ReactOS includes support for htmlhelp.h and a working implementation of HHCTRL.OCX. Although current imported HHCTRL.OCX suffers of this issue:
https://bugs.winehq.org/show_bug.cgi?id=47379
and the help files of ReactOS Calc are not included in the master, I think it is not a bad idea to activate its support by default.

Enable support for HTMLHELP

---

sdk/lib/cmlib/cminit.c

This fixes the crashes in HvpGetCellMapped on Windows Server 2003 when booting from Freeloader, as mentioned in https://github.com/maharmstone/btrfs/issues/16.
When the bootloader loads the system hive, it cleans the data pertaining to any volatile keys. The Windows bootloader does this by setting SubKeyCounts[Volatile] to 0. After boot, the kernel marks any cell where this is 0 but SubKeyLists[Volatile] isn't HCELL_NIL as dirty, meaning that the sanitized version will then get flushed to the disk.
Because Freeloader sets SubKeyLists[Volatile] to HCELL_NIL straightaway, Windows thinks the cell is clean, and can unload it without flushing. If it then reads it from the disk, it will crash in HvpGetCellMapped due to the stale volatile pointers.
If you break on nt!CmpInitializeSystemHive on …

[CMLIB] Clean volatile registry entries in the same manner as Windows

---

boot/bootdata/txtsetup.sif
media/inf/display.inf
win32ss/drivers/miniport/xboxvmp/CMakeLists.txt
win32ss/drivers/miniport/xboxvmp/xboxvmp.c
win32ss/drivers/miniport/xboxvmp/xboxvmp_reg.inf
win32ss/drivers/videoprt/resource.c

- Added XboxVmp driver to system32/drivers directory
- Added required registry entries for it
- Made it compatible with current videoprt driver, specified vendor id and device id explicitly in `VideoPortGetAccessRanges()` call
- Fixed a bug in videoprt driver - `Reserved` bit field was uninitialized in `PciSlotNumber` variable, so `HalGetBusData()` call failed in this case (**important:** this might fix some other video driver issues!)
Tested and confirmed that driver doesn't interfere with VGA/VBE on normal PC installations.
JIRA issue: [CORE-16317](https://jira.reactos.org/browse/CORE-16317)
Please add to XBOX Boot milestone. :wink:

Add Xbox video miniport driver and fix a bug

---

ntoskrnl/mm/section.c

On x64 the previous implementation would only compare the upper 32 bits and ignore the lower 32 bits.

[NTOS:MM] Fix MmspCompareSegments

---

hal/halx86/legacy/bussupp.c

This fixes the bug when `VidInitialize` asks for different translated addresses and `VgaIsPresent` always returns FALSE either because the machine does not have VGA controller at all (e.g. 86Duino Zero), or it does have video hardware that is not compatible with VGA standard (e.g. Original Xbox).
The problem investigated by @binarymaster. Suggested fix by @ThFabba.
JIRA issues: [CORE-14625](https://jira.reactos.org/browse/CORE-14625), [CORE-16222](https://jira.reactos.org/browse/CORE-16222)

[HAL] Return correct bus handler in HaliFindBusAddressTranslation

---

modules/rostests/win32/cmd/test_builtins.cmd
modules/rostests/win32/cmd/test_builtins.cmd.exp

CORE-16356 Test
Check for BAT Conditionals working using find.exe.
JIRA issue: [CORE-16356](https://jira.reactos.org/browse/CORE-16356)
_Add additional testing to cmd_rostest to test find using conditional logic._

Add Regression test for "find" using BAT with Conditionals "&&" and "||"

---

drivers/filesystems/btrfs/btrfs.c

I tested 3 existing hacks: 1 is still required, 2 seem not needed anymore.
I don't know what fixed these cases.
Please, double-check.
Stages 1-2-3 custom logs:
```
Btrfs ERR : DriverEntry : ReactOS hack removed: ZwCreateKey succeeded
WARNING:  NtNotifyChangeMultipleKeys at ntoskrnl/config/ntapi.c:1450 is UNIMPLEMENTED!
Btrfs ERR : watch_registry : ZwNotifyChangeKey returned c0000002
Btrfs ERR : DriverEntry : ReactOS hack: Do not create mountmgr_thread
...
Btrfs ERR : mount_vol : ReactOS hack removed: Do not leak a dummy handle
```
I tried with system wide DPH too, but install hangs (CPU=100%) on 'Importing registry.inf'', even on FAT32 :-/

[BTRFS] Remove 2 hacks, not needed anymore

---

win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.h

JIRA issue: [CORE-16269](https://jira.reactos.org/browse/CORE-16269)
- Fix and improve registry-based font entry management.
- Append style name to registry value name.
- Make some `DPRINT` `DPRINT1` (noisy).

[WIN32SS][FONT] Fix registry-based management

---

win32ss/user/ntuser/menu.c

The submenu of desktop popup menu was erroneously shown at first right click.
JIRA issue: [CORE-16382](https://jira.reactos.org/browse/CORE-16382)
BEFORE:
AFTER:
- Fix the hit test position that was modified by window style change.

[WIN32SS][NTUSER] Fix hit test position of popup menu

---

hal/halx86/legacy/bussupp.c

I noticed one of these bugs when reading debug logs from real hardware Xbox 1.3. :slightly_smiling_face: 
- Match subclass properly, don't match third subclass
- Don't match subclass from next class, add ClassEnd boundary
- Use class name if subclass name not available
- Gracefully return "Unknown" if no class name found
```
00:03.0 16650 [0703]
00:03.0  [0750]
00:03.0 USB controller [0b03]
00:03.0  [4000]
00:03.0  [1403]
```
```
00:03.0 Modem [0703]
00:03.0 Communication controller [0750]
00:03.0 Processor [0b03]
00:03.0 Coprocessor [4000]
00:03.0 Unknown [1403]
```

[HAL] Fix parser bugs in HalpDebugPciDumpBus

---

ntoskrnl/io/pnpmgr/pnpmgr.c

Devices can be deleted during the traversal, so in order to keep the tree walk intact without use-after-free situations, this just keeps the PDO around until we no longer need the device node.
It could be argued that this is a hack, however implementing it the "correct way" (I haven't actually researched how Windows does this) is unlikely to be possible with our current PNP manager -- so this should keep us going for a while.
JIRA issue: [CORE-15874](https://jira.reactos.org/browse/CORE-15874)

[NTOS:PNP] When traversing the device tree, keep a reference to the current device

---

drivers/wdm/audio/hdaudbus/fdo.cpp

Most needed to be multiplied by 10 to match Haiku's behavior.
In one case, the broken timeout was offset by a higher number of loop
iterations, which is now  restored.
This should fix failures on real hardware that result in the
"unable to exit reset" print, and avoid a possible subsequent Pnp
manager crash.
Compare with the following (both snooze and KeStallExecutionProcessor use microseconds):
https://github.com/haiku/haiku/blob/ff38df48cfb21b95fb2dce0443762e0e470db57c/src/add-ons/kernel/drivers/audio/hda/hda_controller.cpp#L466
https://github.com/haiku/haiku/blob/ff38df48cfb21b95fb2dce0443762e0e470db57c/src/add-ons/kernel/drivers/audio/hda/hda_controller.cpp#L357
https://github.com/haiku/haiku/blob/ff38df48cfb21b95fb2dce0443762e0e470db57c/src/add-ons/kernel/drivers/audio/hda/hda_control …

[HDAUDBUS] Fix timeouts for hardware register operations. CORE-15874

---

configure.cmd

Does what the title says. Visual Studio 2019 16.3 bumps the CL.EXE version number to 16.23.*.
Detect CL 16.23.* as Visual Studio 2019.

Add support for latest MSVC toolchain

---

boot/freeldr/freeldr/include/fs/fat.h
boot/freeldr/freeldr/lib/fs/fat.c

Ramdisk boot from USB now work with adequate speed 🚀
"Ordinary" boot should work faster too
Changes:
- Added FAT cache
- Adjacent clusters are now read using one disk driver call
- Whole FAT entry chain is not read for file while opening

Make FreeLoader FAT driver work with a speed of light

---

dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/browseui/shellfind/CSearchBar.cpp

Improve Find Function of ReactOS Explorer
_Add ability to show sub-directories and generalize search item before searching._
JIRA issue: CORE-16152
Example on Windows 2003 Server:
ReactOS - Before:
ReactOS - After
Example Windows 2003 Server:
ReactOS - Before
ReactOS - After
Example Windows 2003 Server
ReactOS - Before:
ReactOS - After:

Shell Find Improvements to make Search Item general and Show Sub-directories

---

drivers/filters/mountmgr/point.c

Follow-up to 7601011f4ed578ae4a15a55298ebbe96fe3a1129.

[MOUNTMGR] QueryPointsFromMemory(): Do not leak DeviceName.Buffer

---

boot/freeldr/freeldr/arch/i386/xboxmem.c
boot/freeldr/freeldr/arch/i386/xboxvideo.c
boot/freeldr/freeldr/include/arch/i386/machxbox.h

- Reuse framebuffer address that was set up by firmware
- Get rid of XboxMemReserveMemory and use ReserveMemory instead

[FREELDR] Xbox memory management improvements

---

drivers/filters/mountmgr/point.c

Addendum to r55156 (31572e777065a14e04f12b33f3efe813b268a20f).
This PR does not fix, but is closely related to
JIRA issue: [CORE-16371](https://jira.reactos.org/browse/CORE-16371)

[MOUNTMGR] QueryPointsFromSymbolicLinkName(): Fix a copypasta. CORE-16371

---

sdk/lib/crt/msvcrtex.cmake
sdk/lib/crt/stdio/acrt_iob_func.c

This makes GCC 8.3.0 compiled with mingw-w64 6.0.0 happy.
I'm not sure if we should do anything with "old" export `__iob_func`
See https://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2

[MSVCRT] Export __acrt_iob_func from MSVC 2015 and higher

---

dll/cpl/hdwwiz/hdwwiz.c

Addendum to ce498aa5714a42c449b244feaa70c7df6d59e0af.

[HDWWIZ] ProbeListPageDlgProc(): Top 'Item' variable is enough

---

ntoskrnl/mm/ARM3/contmem.c

I'm still investigating random out-of-memory problem with patched xboxvmp (video miniport driver for Xbox, see PR #1896), which [we discussed](https://chat.reactos.org/reactos/pl/5xc4gg63zibgpegasr4uh4y5dh) with @ThFabba on Mattermost.
We came to the conclusion there is no bug in the memory manager, but for some reason the memory is full at this early loading stage. This pull request adds a debug print for the code path I'm hitting, because there are no other debug prints signaling about outage of memory.

[NTOS:MM] Add debug print to MiAllocateContiguousMemory in out-of-memory case

---

dll/directx/wine/d3d8/CMakeLists.txt
dll/directx/wine/d3d9/CMakeLists.txt
dll/directx/wine/ddraw/CMakeLists.txt
dll/directx/wine/wined3d/CMakeLists.txt

This reverts part of (revert) commit 81cffd7658765be610e53bcd9489a3d73597e5eb,
so restores 23373acbb9b5356422657fa8448d2a18270847e2.
NB:
`CMakeLists.txt` parts, which were "unexpectedly" reverted:
- error C4133: superseded by additional 36d9e80add6c295ce05a3655eb23b1efd1f3fff7.
- SHARED to MODULE: restored by this PR.
- generated files: eventually restored by dffb99c172d74986c9cbcd2ce42d73b822c5bcd9.
- error C4312: unneeded anymore... (until next `wined3d` re-sync?)

[D3D8][D3D9][DDRAW][WINED3D] Use modules instead of shared libraries

---

base/services/w32time/CMakeLists.txt
dll/apisets/CMakeLists.txt.in
dll/shellext/netplwiz/CMakeLists.txt
dll/win32/msxml3r/CMakeLists.txt
media/themes/Lunar/lunar.msstyles/CMakeLists.txt
media/themes/Mizu/mizu.msstyles/CMakeLists.txt

Follow-up to 23373acbb9b5356422657fa8448d2a18270847e2.
2 missed cases: apisets, lunar.msstyles.
4 new cases: w32time, netplwiz, msxml3r, mizu.msstyles.
If it is not, could you suggest a comment to add instead?

[CMAKE] Use modules instead of shared libraries

---

base/applications/utilman/lang/uk-UA.rc
base/applications/utilman/utilman.rc
media/inf/shortcuts.inf

Add Ukrainian translation for ReactOS Accessibility Utility Manager.
- Add the translation;
- Include it into the RC file:
- Translate the shortcut in the Start Menu.

[UTILMAN] Add Ukrainian translation

---

dll/win32/shell32/wine/shellpath.c

JIRA issue: [CORE-16496](https://jira.reactos.org/browse/CORE-16496)
- If `SendTo` folder is empty in `SHGetFolderPathAndSubDirW` function, then add a shortcut file linked to `My Documents`.

[SHELL32] Add SendTo My Documents

---

boot/freeldr/freeldr/freeldr.c

Prevent uninitialized MachVtbl usage
JIRA issue: [CORE-16507](https://jira.reactos.org/browse/CORE-16507)
- Move the trace call after the MachInit()

[FREELDR] Fix triple fault with debug on screen

---

CMakeLists.txt
dll/win32/dbghelp/CMakeLists.txt
dll/win32/dbghelp/compat.h
sdk/include/host/CMakeLists.txt
sdk/include/host/config.h.in
sdk/lib/3rdparty/zlib/CMakeLists.txt
sdk/lib/cmlib/CMakeLists.txt
sdk/lib/inflib/CMakeLists.txt
sdk/tools/CMakeLists.txt
sdk/tools/cabman/CMakeLists.txt
sdk/tools/fatten/CMakeLists.txt
sdk/tools/kbdtool/CMakeLists.txt
sdk/tools/log2lines/CMakeLists.txt
sdk/tools/mkhive/CMakeLists.txt
sdk/tools/rsym/CMakeLists.txt
sdk/tools/unicode/CMakeLists.txt
sdk/tools/widl/CMakeLists.txt
sdk/tools/wpp/CMakeLists.txt
sdk/tools/xml2sdb/CMakeLists.txt

Dynamically check for sys/types.h and pid_t in wine config.h
Use TARGET_xxx defines instead of _X86_ as this is undefined by GCC
Add some sense in include directories management by using interface
libraries.

[CMAKE] Fix host tools build on x86-64 mingw

---

win32ss/user/ntuser/mouse.c

JIRA issue: [CORE-16279](https://jira.reactos.org/browse/CORE-16279)
Upon mouse message generation, The states of `Shift` key and/or `Ctrl` key must be used. If `Shift` key is pressed, it enables `MK_SHIFT` flag of the mouse message. If `Ctrl` key is pressed, it enables `MK_CONTROL` flag of the mouse message.

[NTUSER] Support MK_SHIFT/MK_CONTROL of mouse messages

---

win32ss/user/user32/windows/dialog.c

JIRA issue: [CORE-16490](https://jira.reactos.org/browse/CORE-16490)
`DM_REPOSITION` is dialog message that can reposition the dialog to the workarea when the dialog is partially/entirely in outside of the workarea.
I know it's Wine sync though. This PR is for review.

[USER32] Implement DM_REPOSITION message

---

ntoskrnl/io/pnpmgr/pnpmgr.c

Now disk_new.sys is able to start (checked with usbstor.sys as a port driver). This makes us a bit closer to its adoption :) 
JIRA issue: [CORE-6264](https://jira.reactos.org/browse/CORE-6264)

[NTOS:IO] Fix result length for DevicePropertyRemovalPolicy request

---

sdk/include/host/CMakeLists.txt
sdk/include/host/config.h

sys/types.h is guaranteed to be available on all our supported host platforms and always contains a `pid_t` definition (cf. https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/types.h.html), so define the corresponding `HAVE_*` constants unconditionally.
If you think that this is just nitpicking, let me explain:
* Defining all `HAVE_*` constants unconditionally tells people that we only support host platforms coming with these headers and type definitions.
* Checking the host platform and defining them conditionally puts an additional burden on our build process. It asks for adding more header checks, slowly turning our CMake into an 80s-style `./configure` script. Moreover, it tells people that we support host platforms with and without these characteristics and accept patches …

[CMAKE] Follow-up to PR #2041

---

base/applications/osk/settings.c

Ensure that the value data we query on loading the registry configuration settings matches with its data size.

[OSK] Validate the registry value data on query

---

win32ss/user/ntuser/window.c
win32ss/user/ntuser/winpos.c

JIRA issue: [CORE-15655](https://jira.reactos.org/browse/CORE-15655)
If the owner window doesn't exist or is invisible or has `WS_EX_TOOLWINDOW` style, `HSHELL_WINDOWCREATED` regards the window a non-owned window.
Successful.

[NTUSER] Fix condition of HSHELL_WINDOWCREATED

---

dll/win32/shell32/dialogs/fprop.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/precomp.h

JIRA issue: [CORE-12756](https://jira.reactos.org/browse/CORE-12756)
- Add stub window (`StubWindow32`) to the drive formatting dialog to avoid locked.
- Separate the thread of drive formatting.
- Move `CStubWindow32` codes.

[SHELL32] Improve UI of drive formatting

---

dll/win32/shell32/CDefView.cpp

JIRA issue: [CORE-16519](https://jira.reactos.org/browse/CORE-16519)
- If the Right-Clicked item is not being selected, then reset the selection and select the Right-Clicked item. End if.
- If the Right-Clicked item is being selected, then do nothing. End if.

[SHELL32] Improve icon selection upon right click

---

win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-9614](https://jira.reactos.org/browse/CORE-9614)
- Delete `ItalicFromStyle` and `WeightFromStyle` functions.
- Don't use `FT_FaceRec.style_name` for font style but `pOS2->fsSelection`, `pOS2->usWeightClass`, `WinFNT.italic` and `WinFNT.weight`.
- Don't use the bitmap glyph as possible if the glyph will be oblique'd.

[NTGDI][FONT] Don't rely FT_FaceRec.style_name

---

dll/win32/shell32/wine/shellpath.c

Follow-up of #2027.
JIRA issue: [CORE-16496](https://jira.reactos.org/browse/CORE-16496)
BEFORE:
AFTER:

[SHELL32] Change icon of SendTo My Documents

---

sdk/cmake/msvc.cmake

Fix x64 build with latest version of VS 2019
- Disable EH4 on x64 globally for VS version 16.3+
See https://developercommunity.visualstudio.com/content/problem/746534/visual-c-163-runtime-uses-an-unsupported-api-for-u.html

[CMAKE] Disable EH4 for x64 and VS versions 16.3+

---

modules/rosapps/applications/net/netreg/netreg.cpp
sdk/cmake/msvc.cmake

- [NETREG] Fix a 64bit printf format warning
- [CMAKE] Turn printf format warnings (C4313 and C4477) into errors

Fix last printf warning and turn it into an error

---

dll/win32/shell32/CExtractIcon.cpp
dll/win32/shell32/folders/CFSFolder.cpp

JIRA issue: [CORE-10480](https://jira.reactos.org/browse/CORE-10480)
BEFORE:
AFTER:

[SHELL32] Set default exe icon

---

ntoskrnl/mm/ARM3/expool.c
ntoskrnl/mm/ARM3/pool.c

This PR adds code for pool debugging and fixes a use after free case that it triggers.
Looks good on VBox: https://reactos.org/testman/compare.php?ids=68839,68840,68841
Has issues on KVM: https://build.reactos.org/#/builders/6/builds/24033/steps/1/logs/stdio
Update: new runs
KVM: https://reactos.org/testman/compare.php?ids=68947,68949,68952,68953
VBox: https://build.reactos.org/#/builders/3/builds/11684 (Testman is a bitch and has eaten it)
Any help looking into these issues is highly appreceated, since these are most likely all nasty bugs that were hidden so far and should really be fixed.

[NTOS] Add pool debugging code

---

hal/halx86/generic/bios.c

As `j <= i < IOPM_SIZE / sizeof(USHORT`.
Addendum to 5887b170052db6af1ee86dc68f053d0c79d15028.
Cc @HBelusca
NB:
Unless we remove the whole "optimization" even...

[HAL:HALX86] Remove a now useless ASSERT()

---

dll/win32/devmgr/devmgmt/ClassNode.cpp
dll/win32/devmgr/devmgmt/DeviceNode.cpp
dll/win32/devmgr/devmgmt/Node.cpp
dll/win32/devmgr/devmgmt/RootNode.cpp

Also:
Always use explicit _countof() and sizeof().
Add a missing 'Size' re-init.

[DEVMGR] m_DisplayName: Some functions need bytes, not chars

---

dll/win32/shell32/dialogs/drive.cpp

This patch disables all the controls after a format is started and re-enables them after the format is complete. Doesn't make much sense to add a volume label after the format is started. :D 
I guess it could be considered a continuation of [CORE-13221](https://jira.reactos.org/browse/CORE-13221)

[SHELL32] Disable all controls during format

---

dll/cpl/openglcfg/general.c

Follow-up to e7b8f273094c9402ff1df3baa5841bf3518a3f02.
```
...\dll\cpl\openglcfg\general.c(142): warning C4267: 'function': conversion from 'size_t' to 'DWORD', possible loss of data
...\dll\cpl\openglcfg\general.c(152): warning C4267: 'function': conversion from 'size_t' to 'DWORD', possible loss of data
```

[OPENGLCFG] general.c: Fix overruns and warnings, improve code consistency

---

dll/apisets/CMakeLists.txt
dll/apisets/api-ms-win-appmodel-runtime-l1-1-1.spec
dll/win32/kernel32/client/sysinfo.c
dll/win32/kernel32/kernel32.spec

Some WiX-based installers (I have reproduced this issue with the 32-bit .NET Core 3.0 installers, which I am currently trying to get working on a different branch) call the Windows 8+ `GetCurrentPackageId()` function. Since that function is marked as a stub in the spec file, this will crash the process.
JIRA issue: (none)
I added a stub implementation of `GetCurrentPackageId()` that always returns `APPMODEL_ERROR_NO_PACKAGE`. This is the error code that Microsoft documents Windows as returning when the current process is not within an AppX package. Since that condition is never true on ReactOS, I chose this error over `ERROR_NOT_IMPLEMENTED`, as it is more accurate.

Stub GetCurrentPackageId()

---

dll/apisets/api-ms-win-core-sysinfo-l1-2-0.spec
dll/apisets/api-ms-win-core-sysinfo-l1-2-1.spec
dll/win32/kernel32/client/time.c
dll/win32/kernel32/kernel32.spec

Add a stub for Windows 8/Server 2012+ `GetSystemTimePreciseAsFileTime` function into kernel32, according to https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime (but with ROS-specific diffs in the syntax). Required by 360 Extreme Explorer 11.0.2216.0 installer.
JIRA issue: [CORE-16420](https://jira.reactos.org/browse/CORE-16420)
- Add a stub for the function in `dll/win32/kernel32/client/time.c`;
- Properly call it in `dll/apisets/api-ms-win-core-sysinfo-l1-2-0.spec` and `dll/apisets/api-ms-win-core-sysinfo-l1-2-1.spec` apisets and in `dll/win32/kernel32/kernel32.spec` itself.
Before:
After:
It also works in Win2k3 (and officially supports XP/2003):

[KERNEL32] Stub GetSystemTimePreciseAsFileTime

---

dll/win32/devmgr/devmgmt/ClassNode.cpp

`Type` is an out-only parameter.
Follow-up to 9c82d16b1489a87d5d2a82cd5a9754b04b7b2dcd.

[DEVMGR] CClassNode::SetupNode(): Properly use Type

---

boot/bootdata/hivecls.inf

Make default/Windows behavior documented/easier, until a UI exists.
Addendum to db5a2fff5d4c3c6431abde13f21ee33a27e714dc.
JIRA issue: [CORE-16519](https://jira.reactos.org/browse/CORE-16519)

[BOOTDATA] Restore "CMD here" 'Extended' key, but commented out. CORE-16519

---

dll/win32/rpcrt4/rpc_async.c
dll/win32/rpcrt4/rpcrt4.spec

Add a stub for RpcGetAuthorizationContextForClient function into rpcrt4, according to https://docs.microsoft.com/en-us/windows/win32/api/rpcasync/nf-rpcasync-rpcgetauthorizationcontextforclient (but with Wine-specific diffs in the syntax, according to the code guidelines: https://wiki.winehq.org/Submitting_Patches#Code_guidelines, since we're syncing rpcrt4 with Wine). Required by MS Winlogon with also Win32 subsystem and some other dlls replaced (aka ROS-Frankenstein), so after my changes it doesn't fail with our rpcrt4.dll at the system startup.
I think I also need to submit a patch in Wine, but it is a bit problematically to reproduce this error there, since Wine has no even winlogon.exe, and launching MS Winlogon in pair with profmap.dll, causes the crash due to unimplemented …

[RPCRT4] Stub RpcGetAuthorizationContextForClient

---

dll/win32/winsta/winsta.spec

Add export for WinStationRedirectErrorMessage function in Winsta. We already have a stub for this function in `dll/win32/winsta/logon.c`, but for some reason it is not exported.
Required by MS Winlogon with Win32SS and some other needed dlls replaced. Now it fails due to missing WinStationCanLogonProceed, for which we currently haven't a stub.
PR #2042 is also needed to be applied, in order to reproduce the problem (or just replacing rpcrt4.dll may be as an option too).
JIRA issue: [CORE-16458](https://jira.reactos.org/browse/CORE-16458)

[WINSTA] Export WinStationRedirectErrorMessage

---

dll/win32/kernel32/winnls/string/nls.c

Fix `kernel32!MultiByteToWideChar` function. The default character was wrong.
JIRA issue: [CORE-16468](https://jira.reactos.org/browse/CORE-16468)
BEFORE:
AFTER:

[KERNEL32] Fix multibyte conversion in default char

---

dll/shellext/zipfldr/CMakeLists.txt
dll/shellext/zipfldr/CSendToZip.cpp
dll/shellext/zipfldr/CSendToZip.hpp
dll/shellext/zipfldr/CZipCreator.cpp
dll/shellext/zipfldr/CZipCreator.hpp
dll/shellext/zipfldr/precomp.h
dll/win32/shell32/wine/shellpath.c

Follow-up of #2114.
JIRA issue: [CORE-16495](https://jira.reactos.org/browse/CORE-16495)
AFTER:
- `s/Creater/Creator/`
- Add an empty file in the `SendTo` folder.
- Trick in `Drop`.

[SHELL32][ZIPFLDR] Implement SendTo ZIP folder

---

dll/cpl/input/settings_page.c

JIRA issue: [CORE-13807](https://jira.reactos.org/browse/CORE-13807)
BEFORE (Japanese):
AFTER (Japanese):

[CPL][INPUT] Fix bullet

---

modules/rostests/apitests/kernel32/TunnelCache.c
modules/rostests/apitests/ntdll/NtQueryInformationProcess.c
modules/rostests/apitests/user32/RedrawWindow.c
modules/rostests/apitests/user32/SetProp.c
modules/rostests/winetests/gdi32/bitmap.c
modules/rostests/winetests/gdi32/path.c
modules/rostests/winetests/kernel32/mailslot.c
modules/rostests/winetests/kernel32/pipe.c
modules/rostests/winetests/kernel32/process.c
modules/rostests/winetests/kernel32/sync.c
modules/rostests/winetests/mshtml/xmlhttprequest.c
modules/rostests/winetests/msi/msi.c
modules/rostests/winetests/msxml3/domdoc.c
modules/rostests/winetests/ntdll/exception.c
modules/rostests/winetests/ntdll/info.c
modules/rostests/winetests/ntdll/process.c
modules/rostests/winetests/ole32/compobj.c
modules/rostests/winetests/qmgr/job.c
modules/rostests/winetests/quartz/filtermapper.c
modules/rostests/winetests/quartz/referenceclock.c
modules/rostests/winetests/riched20/editor.c
modules/rostests/winetests/rpcrt4/server.c
modules/rostests/winetests/user32/listbox.c
modules/rostests/winetests/user32/msg.c
modules/rostests/winetests/user32/win.c
modules/rostests/winetests/usp10/usp10.c
modules/rostests/winetests/wininet/ftp.c
modules/rostests/winetests/wininet/http.c
sdk/include/reactos/wine/test.h

Make the results in testman consistent through multiple runs (at least on the same VM).
- Skip (disable) 47 oks in 19 tests that randomly fail
- Disable counting successes in non-deterministic loops / asynchonous callbacks
- user32:listbox - Skip files in the current dir that have not a .exe extension to avoid downloaded/generated files
- msxml3:domdoc - Comment out cleanup code that causes a double-free and can crash the test
- kernel32:process - Fix a test failing on Windows
- ntdll:info - Don't call InitFunctionPtrs(), when the child process runs

[ROSTESTS] Skip flaky tests

---

win32ss/user/winsrv/consrv/frontends/gui/conwnd.c

Console needs speed. This PR will optimize drawing of console.
- Set `NULL` to the background brush.
- Skip `WM_ERASEBKGND`.

[WIN32SS][WINSRV] Optimize console background drawing

---

modules/rostests/apitests/kernel32/ConsoleCP.c

BEFORE (WinXP Japanese):
AFTER (WinXP Japanese):
No change.
BEFORE (Win10 Japanese):
AFTER (Win10 Japanese):
Reduced 4 failures.

[KERNEL32_APITEST] Adjust ConsoleCP testcase for Win10 JPN

---

win32ss/user/winsrv/concfg/font.c

Don't choose Asian charset font if there is no preferred font for CJK.
BEFORE:
AFTER:

[WIN32SS][WINSRV] Improve Asian font choice

---

dll/win32/shell32/shlfileop.cpp

#2085 caused some failures and hung-up in `shell32:shlfileop` testcase. This PR is a follow-up.
JIRA issue: [CORE-16546](https://jira.reactos.org/browse/CORE-16546)
BEFORE:
AFTER:

[SHELL32] Fix hung-up of shell32:shlfileop

---

dll/win32/comctl32/button.c
win32ss/user/user32/controls/button.c

PR #2135 (https://github.com/reactos/reactos/commit/e329e83857db0db67c6798c538ad658be044057e) caused radiobutton regression. This PR will fix it.
JIRA issue: [CORE-16552](https://jira.reactos.org/browse/CORE-16552)
BEFORE:
AFTER:
- Clear `DT_BOTTOM | DT_VCENTER` flags upon calculating the button text height.

[COMCTL32][USER32] Fix radio button regression

---

win32ss/user/winsrv/consrv/frontends/gui/conwnd.c

Improve CMD window Minimize and Restore so it no longer shrinks with each operation.
_Modify conwnd.c to improve user experience._
JIRA issue: [CORE-14200](https://jira.reactos.org/browse/CORE-14200)
See favorable testbot results at [CORE-14200](https://jira.reactos.org/browse/CORE-14200)

Fix for CMD windows shrinking on Minimize and Restore

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/ShellExecuteW.cpp
modules/rostests/apitests/shell32/testlist.c

_This test also shows the results of ShellExecuteW's return value._
Addendum to PR#1854: [PR#1854](https://github.com/reactos/reactos/pull/1854)
_This shows that the return value for ShellExecuteW is normally 33 or 42._

[SHELL32_APITEST] Add Regression Test for ShellExecuteW().

---

win32ss/user/winsrv/consrv.cmake
win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
win32ss/user/winsrv/consrv/frontends/gui/guiterm.h
win32ss/user/winsrv/consrv/frontends/gui/text.c
win32ss/user/winsrv/consrv/frontends/terminal.c
win32ss/user/winsrv/consrv/frontends/wcwidth.c

Make preparation for console support of Chinese, Japanese and Korean (CJK) codepages.
- Add `consrv/frontends/wcwidth.c`.
- Add `GuiPaintTextModeBufferCJK` function.

[CONSRV] Preparation for Asian console support

---

sdk/include/psdk/gdiplusheaders.h

JIRA issue: [CORE-16566](https://jira.reactos.org/browse/CORE-16566)
Our `gdiplusheaders.h` has no dtor of `Gdiplus::Image`. Our `Gdiplus::Bitmap` won't be `GdipDisposeImage`'d upon its destruction.

[SDK][INCLUDE] Add Gdiplus::Image::~Image

---

win32ss/user/ntuser/caret.c

JIRA issue: [CORE-15661](https://jira.reactos.org/browse/CORE-15661)
`co_IntSetCaretPos` function wrongly drawn the caret upon invisible timing. Take care of caret visibility. @Doug-Lyons did test this patch.

[NTUSER] Fix caret display mistake

---

.clang-format
.travis.yml
drivers/network/tcpip/.clang-format
sdk/lib/3rdparty/.clang-format
sdk/tools/check_code_format.sh

No more formatting comments while reviewing PRs!
__TODO__:

Add .clang-format and Travis job for checking formatting

---

modules/rostests/apitests/kernel32/ConsoleCP.c

Strengthen `kernel32_apitest` `ConsoleCP` testcase for `COMMON_LVB_LEADING_BYTE` and `COMMON_LVB_TRAILING_BYTE` attributes.
AFTER (WinXP Japanese):
Successful.
AFTER (Win10 Japanese):
Successful.
AFTER (Win2k3 English):
Successful.

[KERNEL32_APITEST] More power to ConsoleCP testcase

---

ntoskrnl/kd64/kdprint.c

We used to have different logic in `KdpPrint` and `NtQueryDebugFilterState`
KdpPrint: `if (!(Kd_WIN2000_Mask & Level) || (!(*Mask & Level))`
NtQueryDebugFilterState: `if (!((Kd_WIN2000_Mask & Level) || (*Mask & Level)))`
This PR fixes that and now we can filter messages by mask (it didn't work before)

[NTOS:KD] Fix wrong debug level checking logic in KdpPrint.

---

ntoskrnl/include/internal/ke_x.h
ntoskrnl/ke/apc.c
ntoskrnl/ke/gate.c
ntoskrnl/ke/procobj.c
ntoskrnl/ke/queue.c
ntoskrnl/ke/thrdobj.c
ntoskrnl/ke/timerobj.c
ntoskrnl/ke/wait.c
ntoskrnl/mm/ARM3/pagfault.c

* KiAcquireApcLock -> KiAcquireApcLockRaiseToSynch
* KiAcquireApcLockAtDpcLevel -> KiAcquireApcLockAtSynchLevel
* KiReleaseApcLockFromDpcLevel -> KiReleaseApcLockFromSynchLevel
* KiAcquireApcLockAtApcLevel -> KiAcquireApcLockRaiseToDpc
* KiAcquireProcessLock -> KiAcquireProcessLockRaiseToSynch
* KiReleaseProcessLockFromDpcLevel -> KiReleaseProcessLockFromSynchLevel
* KiAcquireDispatcherLockAtDpcLevel -> KiAcquireDispatcherLockAtSynchLevel
* KiReleaseDispatcherLockFromDpcLevel -> KiReleaseDispatcherLockFromSynchLevel
* Add some ASSERTs

[NTOS:KE] Rename some locking functions to reflect the IRQL changes

---

boot/freeldr/freeldr/arch/i386/multiboot.S
boot/freeldr/freeldr/arch/i386/xboxmem.c
boot/freeldr/freeldr/arch/i386/xboxvideo.c
boot/freeldr/freeldr/include/multiboot.h

- Obtain Xbox memory map via multiboot spec
- Also obtain framebuffer memory size the same way
JIRA issue: [CORE-16300](https://jira.reactos.org/browse/CORE-16300)

[FREELDR] Obtain Xbox memory map via multiboot spec

---

modules/rostests/apitests/ws2_32/getaddrinfo.c

Test results proves `WSAStartup` call should precede `GetAddrInfoW` calls.
BEFORE:
```
Windows XP SP3
getaddrinfo: 890 tests executed (0 marked as todo, 1 failure), 0 skipped.
Windows 7 SP1
getaddrinfo: 839 tests executed (0 marked as todo, 10 failures), 0 skipped.
```
AFTER:
```
Windows XP SP3
getaddrinfo: 898 tests executed (0 marked as todo, 1 failure), 0 skipped.
Windows 7 SP1
getaddrinfo: 847 tests executed (0 marked as todo, 10 failures), 0 skipped.
```
**_Note:_** I don't have Windows 2003 virtual machine at the moment, so I didn't fixed existing test failures.

[WS2_32_APITEST] Add some tests for GetAddrInfoW

---

boot/freeldr/freeldr/arch/i386/i386bug.c
boot/freeldr/freeldr/arch/i386/xboxcons.c

Handle right line wrap.
NB: There is no bottom screen overflow handling...
JIRA issue: [CORE-16268](https://jira.reactos.org/browse/CORE-16268)
- Add line wrap handling.
- Some additional rewrites.

WIP. [FREELDR] i386PrintText(): Add line wrap handling. CORE-16268

---

boot/freeldr/freeldr/arch/i386/pcmem.c
boot/freeldr/freeldr/include/arch/pc/pcbios.h

Update BIOS_MEMORY_MAP and PcMemGetBiosMemoryMap(), to ACPI 6.3 from 6.2-A.

[FREELDR] Update ACPI Extended Attributes support, to 6.3

---

boot/bootdata/hivedef.inf

Add `AppliedDPI` DWORD registry value 0x00000060 (96 DPI) into `HKCU\Control Panel\Desktop\WindowMetrics` registry key. For now it does nothing, since saving DPI registry settings is not implemented yet. It's required only for ViStart 8 to be started successfully (with MS VB6 Runtime installed and wshom.ocx replaced).
JIRA issue: [CORE-13877](https://jira.reactos.org/browse/CORE-13877)
Before:
After:
This value is also present in Win2k3 (96 DPI is default value):

[BOOTDATA] Add AppliedDPI registry value

---

dll/win32/shell32/shlexec.cpp

This patch removes this line from the log:  
`fixme:(dll\win32\shell32\shlexec.cpp:1810) flags ignored: 0x00000004`

[SHELL32] Fix extra fixme

---

ntoskrnl/ke/i386/exp.c
ntoskrnl/ke/i386/thrdini.c
ntoskrnl/ke/i386/v86vdm.c

The trap frame is in a random location on the stack, and setting Esp0 there
wastes significant amounts of space and may lead to unexpected stack overflows.
Also use a more descriptive expression for the V86 members of the KTRAP_FRAME.
JIRA issue: [CORE-16531](https://jira.reactos.org/browse/CORE-16531)

[NTOS:KE] In KiExitV86Mode, restore KTSS::Esp0 to its standard value

---

dll/win32/shell32/CShellItem.cpp
dll/win32/shell32/wine/pidl.c
dll/win32/shell32/wine/shellord.c
sdk/include/psdk/shdeprecated.idl
sdk/include/psdk/shlobj.h
sdk/include/psdk/shlwapi.h
sdk/include/psdk/shobjidl.idl

In this pull request, I've updated the file shlobj.h with the strictly typed version of ITEMIDLIST from MSDN.
JIRA issue: [CORE-16385](https://jira.reactos.org/browse/CORE-16385)

[CORE-16385] Support STRICT_TYPED_ITEMIDS

---

modules/rostests/winetests/wininet/http.c

Seems unneeded anymore,
though I don't know which error/failure the Jira ticket refers to.
JIRA issue: [ROSTESTS-73](https://jira.reactos.org/browse/ROSTESTS-73)

[WININET_WINETEST] http: Remove ROSTESTS_73_FIXED workaround

---

modules/rostests/apitests/kernel32/ConsoleCP.c

Add some tests for `WriteConsoleOutputCharacterW` and `WriteConsoleOutputAttribute` etc. into `ConsoleCP` testcase.
Win10 Japanese:
The test results successful.

[KERNEL32_APITEST] Strengthen ConsoleCP for Writing functions

---

drivers/filesystems/udfs/create.cpp

The issue was the use of an uninitialized variable **Returnedinformation** in the UDFS driver. The folder traversal method tries to traverse into a file which is not possible. So it returns an error when it tries to do so. But we **haven't initialized Returnedinformation** anywhere. In the next call, we assign a new variable with the value of  **Returnedinformation** which has not been initialized yet. Hence we can initialize the value before returning. The reason I went with setting the value of it as **FILE_DOES_NOT_EXIST** because of the error which closely links to it.
JIRA issue: [CORE-16174](https://jira.reactos.org/browse/CORE-16174)
Initialize **Returninformation** with the error value before returning. 
The error value I'm using is **FILE_DOES_NOT_EXIST**

[UDFS] UDFCommonCreate uninitialized var use. CORE-16174

---

modules/rostests/apitests/cmd/cmd.c

Additional Regression Tests for Attrib
JIRA issue: [CORE-16284](https://jira.reactos.org/browse/CORE-16284)
_The intent is to test the remaining unimplemented functionality of the attrib command._
Windows Server 2003:
ReactOS:

[CMD_APITEST] Add more regression tests for attrib.

---

win32ss/user/winsrv/consrv/condrv/text.c
win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
win32ss/user/winsrv/consrv/frontends/gui/guiterm.h
win32ss/user/winsrv/consrv/frontends/gui/text.c
win32ss/user/winsrv/consrv/frontends/terminal.c

Follow-up of #2231. Also fix `FillConsoleOutputAttribute`, `WriteConsoleOutputCharacterW` and `WriteConsoleOutputAttribute` functions.
BEFORE (Japanese):
AFTER (Japanese):
It's successful.
BEFORE (Japanese with ReactOS JPN Package from Rapps):
AFTER (Japanese with ReactOS JPN Package from Rapps):
It correctly handles Shift_JIS encoding.

[WIN32SS][WINSRV] Fullwidth character handling Part 2

---

boot/freeldr/freeldr/CMakeLists.txt
boot/freeldr/freeldr/arch/drivers/hwide.c
boot/freeldr/freeldr/arch/i386/machxbox.c
boot/freeldr/freeldr/arch/i386/xboxdisk.c
boot/freeldr/freeldr/include/arch/i386/machxbox.h
boot/freeldr/freeldr/include/hwide.h

Xbox doesn't have BIOS interrupts and NEC PC-98 BIOS can't boot from CD.
Which is why we need to access IDE controllers directly.
* Create a new library
* Use the functions from the library in xboxdisk.c
Driver now supports PC, Xbox and NEC PC-98.
Tested with VirtualBox, XQEMU (LiveCD only), Neko Project 21/W and it works very well.
It's also a XBOX Boot milestone.
JIRA issue: [CORE-16220](https://jira.reactos.org/browse/CORE-16220), [CORE-16216](https://jira.reactos.org/browse/CORE-16216)
BEFORE:
AFTER:
Boot from CD successfully (MachVtbl patch is required):

[FREELDR] Add ATA/ATAPI driver

---

boot/freeldr/freeldr/arch/i386/hardware.c
hal/halx86/include/halp.h

See https://xboxdevwiki.net/Porting_an_Operating_System_to_the_Xbox_HOWTO#Timer_Frequency
Xbox PIT tick rate - 1.125000 MHz.

[HAL][FREELDR] Fix system timer oscillator frequency on a Xbox

---

boot/freeldr/freeldr/arch/i386/xboxvideo.c
win32ss/drivers/miniport/xboxvmp/xboxvmp.c

Fixes framebuffer detection on real hardware Xbox.

[FREELDR][XBOXVMP] Check only low 28 bits for framebuffer address

---

hal/halx86/xbox/halxbox.h
hal/halx86/xbox/part_xbox.c

Fixes BSOD 0x7B when booting from a HDD that have both MBR and BRFR signatures.

[HALXBOX] Don't use Xbox partitions if MBR signature found

---

dll/win32/atl/CMakeLists.txt

Follow-up to e410a12242a50e850846058ef5c53652340c1724.

[ATL] Re-enable MSVC warning C4477

---

base/shell/explorer/taskswnd.cpp
sdk/include/reactos/rosctrls.h

Based on @learn-more's `CORE-11619.patch`.
JIRA issue: [CORE-11619](https://jira.reactos.org/browse/CORE-11619)
BEFORE:
AFTER:

[EXPLORER][INCLUDE] Fix wrong title on taskbar about ampersand (&)

---

dll/cpl/CMakeLists.txt

'#Warning: console\\/lang/cs-CZ.rc:143: unrecognized escape sequence'
Created on r51783.
Assumed fixed by d132a09e69c201092e21818568cfd4844f1a5eab (r58770), which removed `IDS_SCREEN_TEXT`.

[CMAKE] Remove a remnant comment related to 'dll/cpl/console'

---

win32ss/gdi/ntgdi/dibobj.c

JIRA issue: [CORE-16621](https://jira.reactos.org/browse/CORE-16621)
I am not sure if this is a fix or a hack :)

[WIN32K] Don't trust the BITMAPINFOHEADER size

---

win32ss/printing/base/winspool/printers.c

_This improves the return value for pcbNeeded from being an unititialized value and makes it zero._
_The reason for this is that this value is often used afterwards in the code for HeapAlloc._

Improve Stubs for printers.c GetPrinterA and GetPrinterDeviceA

---

dll/cpl/appwiz/createlink.c

JIRA issue: [CORE-16534](https://jira.reactos.org/browse/CORE-16534)
STEP 1: Right Click the desktop and choose `New ==> New Link`.
STEP2: `"Create Shortcut"` wizard is open and a shortcut file is created on desktop.
STEP3: Click `"Cancel"` button. Then, the file will be deleted.

[APPWIZ] Delete shortcut file upon user cancel

---

dll/cpl/appwiz/createlink.c
dll/cpl/appwiz/lang/bg-BG.rc
dll/cpl/appwiz/lang/cs-CZ.rc
dll/cpl/appwiz/lang/de-DE.rc
dll/cpl/appwiz/lang/el-GR.rc
dll/cpl/appwiz/lang/en-US.rc
dll/cpl/appwiz/lang/es-ES.rc
dll/cpl/appwiz/lang/et-EE.rc
dll/cpl/appwiz/lang/fr-FR.rc
dll/cpl/appwiz/lang/he-IL.rc
dll/cpl/appwiz/lang/id-ID.rc
dll/cpl/appwiz/lang/it-IT.rc
dll/cpl/appwiz/lang/ja-JP.rc
dll/cpl/appwiz/lang/no-NO.rc
dll/cpl/appwiz/lang/pl-PL.rc
dll/cpl/appwiz/lang/pt-BR.rc
dll/cpl/appwiz/lang/pt-PT.rc
dll/cpl/appwiz/lang/ro-RO.rc
dll/cpl/appwiz/lang/ru-RU.rc
dll/cpl/appwiz/lang/sk-SK.rc
dll/cpl/appwiz/lang/sq-AL.rc
dll/cpl/appwiz/lang/tr-TR.rc
dll/cpl/appwiz/lang/uk-UA.rc
dll/cpl/appwiz/lang/zh-CN.rc
dll/cpl/appwiz/lang/zh-TW.rc
dll/cpl/appwiz/resource.h

JIRA issue: [CORE-16534](https://jira.reactos.org/browse/CORE-16534)
STEP 1: Right Click Desktop and Choose `New ==> New Link`.
STEP2: Type `C:\` and Click `Next`.
STEP3: You will get display name.

[CPL][APPWIZ] Use display name for shortcut label

---

sdk/lib/atl/cstringt.h

`CStringT::FormatMessage` in ATL is an important method to build a formatted string.
JIRA issue: [CORE-16666](https://jira.reactos.org/browse/CORE-16666)

[SDK][ATL] Implement CStringT::FormatMessage

---

dll/shellext/zipfldr/CConfirmReplace.cpp
dll/shellext/zipfldr/CZipPassword.cpp

Using `CStringA::FormatMessage` method can simplify our code.

[SHELLEXT][ZIPFLDR] Use CStringA::FormatMessage

---

dll/shellext/zipfldr/CZipEnumerator.hpp

[SHELLEXT][ZIPFLDR] Be case sensitive

---

base/services/w32time/w32time.c
dll/cpl/timedate/CMakeLists.txt
dll/cpl/timedate/internettime.c
dll/cpl/timedate/timedate.h

In Windows XP and Server 2003 the Time/Date control applet does not display any message box in case of NTP synchronization failure or no given NTP server name. However, their applet displays a dynamic string resource every time a successful or failed NTP synchronization operation occurs.
For now, this PR merely checks if the string is empty and displaying (only) a debug information to the debugger, at disposal of displaying a message box. I might implement such dynamic resource string to the CPL later in a next PR.
**JIRA Issue:** [CORE-16654](https://jira.reactos.org/browse/CORE-16654)

[TIMEDATE] Do not display a message box when NTP sync fails

---

ntoskrnl/mm/ARM3/arm/init.c
ntoskrnl/mm/ARM3/miarm.h
ntoskrnl/mm/ARM3/mminit.c
ntoskrnl/mm/ARM3/pool.c
ntoskrnl/mm/ARM3/section.c
ntoskrnl/mm/balance.c
ntoskrnl/mm/i386/page.c
ntoskrnl/mm/marea.c

@tkreuzer added `/* Stop using these! */` on 066c89edc704dc46945798c2d7f9d44fca3c1f43 (r67568).

[NTOS:MM] Stop using PD_COUNT, PDE_COUNT and PTE_COUNT

---

dll/opengl/Mesa_for_ReactOS.txt
media/doc/3rd Party Files.txt

The Mesa library in `dll/opengl/` is based on version 2.6. (5f2bebf7a5b1a1602b553c43118d745e51c5609c, [CORE-7499](https://jira.reactos.org/browse/CORE-7499))
This PR updates related documents to reflect the current situation.
- Update ` dll/opengl/Mesa_for_ReactOS.txt` to state its purpose and add a reference to RAPPS.
- Update the entry for Mesa in `media/doc/3rd Party Files.txt`.

[OPENGL32][MESA] Describe the current status

---

dll/shellext/zipfldr/CZipExtract.cpp

Now when the user clicks "Next", a new thread is created and the extraction starts from there, allowing to move the window during the extraction, or to cancel the extraction in the middle. (Note: after clicking "Cancel", extraction continues until the current file is extracted).
JIRA issue: [CORE-14934](https://jira.reactos.org/browse/CORE-14934)

[ZIPFLDR] CORE-14934: Extraction is now in its own thread

---

sdk/lib/crt/string/strupr.c

Fixes crash in msvcrt_winetest:string.
This is a hack and is supposed to be specific to the C locale.
JIRA issue: [CORE-16667](https://jira.reactos.org/browse/CORE-16667)

[CRT] Only write to the output buffer when necessary in _strupr

---

hal/halx86/generic/dma.c

JIRA issue: [CORE-16611](https://jira.reactos.org/browse/CORE-16611)
HalPutDmaAdapter can be called at DISPATCH_LEVEL. Windows's portcls apparently does this:
```
*** Assertion failed: KeGetCurrentIrql() < DISPATCH_LEVEL || (KeGetCurrentIrql() == DISPATCH_LEVEL && Timeout && Timeout->QuadPart == 0)
***   Source File: ../ntoskrnl/ke/wait.c, line 436
Break repeatedly, break Once, Ignore, terminate Process or terminate Thread (boipt)?
kdb:> o
Execute '.cxr F74B87D0' to dump context
Entered debugger on embedded INT3 at 0x0008:0x80988afe.
kdb:> bt
Eip:
<ntoskrnl.exe:188aff (sdk/lib/rtl/i386/debug_asm.S:34 (DbgBreakPoint))>
Frames:
<ntoskrnl.exe:9e248 (ntoskrnl/ke/wait.c:436 (KeWaitForSingleObject))>
<hal.dll:17af (hal/halx86/generic/dma.c:823 (HalPutDmaAdapter))>
<portcls.sys:2f8a> …
```

[HAL] Use a spin lock for the DMA adapter list.

---

dll/ntdll/def/ntdll.spec
sdk/include/ndk/rtltypes.h
sdk/lib/rtl/trace.c

Implement RtlGetUnloadEventTrace function in ntdll, according to https://docs.microsoft.com/en-us/windows/win32/devnotes/rtlgetunloadeventtrace. As said there, it has no parameters and returns a pointer to an RtlpUnloadEventTrace array, which I added too.
It allows to generate a minidump files from the running processes via MS ProcDump 9.0 (and probably other software, which has the same feature and uses this function) with replaced verifier.dll. Without replacing that dll, now it fails due to VerifierEnumerateResource() stub.
JIRA issue: [CORE-16671](https://jira.reactos.org/browse/CORE-16671)
- Add missing `RTL_UNLOAD_EVENT_TRACE_NUMBER` definition in sdk/include/ndk/rtltypes.h,  near the `_RTL_UNLOAD_EVENT_TRACE` structure, same as in MSDN example, and static `RtlpUnloadEventTrace` …

[NTDLL] Implement RtlGetUnloadEventTrace

---

modules/rostests/apitests/shell32/SHLimitInputEdit.cpp

JIRA issue: [CORE-11701](https://jira.reactos.org/browse/CORE-11701)
```txt
D:\rossrc\reactos\modules\rostests\apitests\shell32\SHLimitInputEdit.cpp(283) : warning C4509: extension non standard utilisée : 'DialogProc' utilise SEH et 'sf' a un destructeur
D:\rossrc\reactos\modules\rostests\apitests\shell32\SHLimitInputEdit.cpp(264) : voir la déclaration de 'sf'
```

[SHELL32_APITEST] SHLimitInputEdit: Fix C4509 warning

---

boot/bootdata/hiveinst_xbox.inf
sdk/cmake/CMakeMacros.cmake

This also surprisingly fixes random "Invalid Opcode" exceptions in XQEMU.
JIRA issue: [CORE-16627](https://jira.reactos.org/browse/CORE-16627)

[CMAKE][BOOTDATA] Properly load Xbox video miniport driver in LiveCD

---

modules/rostests/apitests/user32/ScrollWindowEx.c

Improve `ScrollWindowEx` testcase for investigation of `SW_SCROLLCHILDREN` flag.
JIRA issue: [CORE-16687](https://jira.reactos.org/browse/CORE-16687), [CORE-12114](https://jira.reactos.org/browse/CORE-12114)

[USER32_APITEST] Strengthen ScrollWindowEx for SW_SCROLLCHILDREN

---

win32ss/user/ntuser/scrollex.c

Based on the patch of `I_Kill_Bugs` of JIRA user.
JIRA issue: [CORE-16687](https://jira.reactos.org/browse/CORE-16687), [CORE-12114](https://jira.reactos.org/browse/CORE-12114)
BEFORE:
AFTER:

[WIN32SS][NTUSER] Fix ScrollWindowEx SW_SCROLLCHILDREN

---

dll/win32/syssetup/wizard.c

JIRA issue: [CORE-13795](https://jira.reactos.org/browse/CORE-13795)
Write the `ReportAsWorkstation` value of the registry key `HKLM\SYSTEM\CurrentControlSet\Control\ReactOS\Settings\Version`.
The reason is shown at [CORE-6611](https://jira.reactos.org/browse/CORE-6611).

[SYSSETUP] Plan A: Also write ReportAsWorkstation value

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/folders/CDesktopFolder.h
dll/win32/shell32/folders/CFSFolder.h
dll/win32/shell32/folders/CMyDocsFolder.h
dll/win32/shell32/shellmenu/CMergedFolder.h
dll/win32/shell32/wine/shellord.c
sdk/include/reactos/undocshell.h

Reject invalid input filename characters by using `shell32!SHLimitInputEdit` function and `IItemNameLimits` interface.
JIRA issue: [CORE-11701](https://jira.reactos.org/browse/CORE-11701)
BEFORE:
AFTER:

Shell Folders: Reject invalid characters

---

base/applications/mspaint/registry.cpp
base/applications/notepad/main.c
base/applications/wordpad/wordpad.c
dll/win32/shell32/wine/shellord.c
dll/win32/shimgvw/CMakeLists.txt
dll/win32/shimgvw/shimgvw.c

Rewrite `shell32!SHAddToRecentDocs` and use it in some applications.
JIRA issue: [CORE-3588](https://jira.reactos.org/browse/CORE-3588)
BEFORE:
AFTER:
Wine's `SHAddToRecentDocs` was not Unicode supported and unusable. I will dare to rewrite.

[SHELL32] Rewrite SHAddToRecentDocs

---

ntoskrnl/wmi/guidobj.c
ntoskrnl/wmi/wmip.h

The initializer for `WmipGuidObjectType` does not set `UseDefaultObject`, and it's possible for user mode to obtain a handle to a GUID object with `SYNCHRONIZE` access.
Therefore that handle can be passed to `NtWaitForSingleObject`, which means it must start with a `DISPATCHER_HEADER`.
This is a security issue since such a wait could cause kernel memory corruption.

[NTOS:WMI] WMIP_GUID_OBJECT must start with an event object, as it is waitable.

---

dll/win32/msv1_0/msv1_0.c

- improves traces: use %wZ for UNICODE_STRING
- move validation of UNICODE_STRINGS after pointer fixup
- use RtlRunDecodeUnicodeString if needed

[MSV1_0] improve LogonUserEx2

---

drivers/ksfilter/ks/irp.c

Or, if it succeeded, return the actual NTSTATUS, not an unrelated BOOLEAN.
JIRA issue: [CORE-16618](https://jira.reactos.org/browse/CORE-16618)
I adapted code from Read/Write functions.
Some similar codes have it, some others do not...

[KS] KsQueryInformationFile(): Fallback to IRP if FastIO failed. CORE-16618

---

dll/win32/msgina/gui.c

A regression which prevented the animated bar from loading was introduced by #2353. This patch fixes it.

[MSGINA] Initialize the GINA context

---

CODEOWNERS

[CODEOWNERS] Add ending '/' to '/dll/shellext'

---

dll/appcompat/shims/layer/versionlie.c
dll/shellext/acppage/CLayerUIPropPage.cpp
media/sdb/sysmain.xml
modules/rostests/apitests/appshim/versionlie.c

Implement ReactOS-specific Windows 10 1903, Server 2016 (1709) and 2019 (1809) compatibility modes. Windows has no these modes. The latest mode which 1903 has, is "Windows 8".
Although after my changes appeared some warnings during ROS compilation, but the system still compiles successfully and the modes work correctly:
`[Err ][fromXml ] Data node (SHIMVERSIONNT) without value!`
I wonder why they appeared. I specified `A00` in `DATA_DWORD` value for each HighVersionLie layer, which is correct for NT 10, according to the `_WIN32_WINNT_*` values (e. g. `0x0600` -> `600`, so `0x0A00` -> `A00`) defined in `sdk/include/psdk/sdkddkver.h`. Propapbly I need `a00` (in lowercase)?
JIRA issue: [CORE-16454](https://jira.reactos.org/browse/CORE-16454)
- Declare VersionLieInfos and define shims in …

[APPCOMPAT][ACCPAGE][SDB][ROSTESTS] Implement compatibility modes for Windows 10, Server 2016 and 2019

---

dll/win32/shell32/shlexec.cpp

Fixes unneeded popup when installing Git for Windows 2.10.0
_Exit from ddeexec if parameter is NULL or empty string._
JIRA issue: [CORE-12266](https://jira.reactos.org/browse/CORE-12266)
_Fixes unneeded popup when ddeexec is NULL or empty string._

Fix unneeded error Popup with Git for Windows.

---

hal/halx86/legacy/bussupp.c

Noticed the problem in Daniel's debug logs from Xbox with some missing linebreaks.
```
I/O ports at 0000	I/O ports at 0000
00:09.0 IDE interface [0101]: NVIDIA Corporation nForce IDE [10de:01bc] (rev d4)
```
```
Memory at f0000000 (32-bit, prefetchable) [size=256M]
Memory at 00000000 (32-bit, prefetchable)	Device is using IRQ 3! ISA Cards using that IRQ may fail!
```

[HAL] Fix debug prints in ShowSize() and its caller

---

.travis.yml

The configuration is not final yet and we have a lot of files that don't
follow the suggested file. At this point, having it active in CI means
builds are essentially always red, and we miss actual compilation errors.

[TRAVIS] Disable code format checker in CI.

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHChangeNotify.cpp
modules/rostests/apitests/shell32/testlist.c

I will add a testcase for `shell32!SHChangeNotify` function to investigate the shell notification mechanism.
WinXP:
Win2k3:
ReactOS:

[SHELL32_APITEST] Add SHChangeNotify testcase

---

dll/3rdparty/libtirpc/CMakeLists.txt
drivers/filesystems/ext2/CMakeLists.txt
drivers/filesystems/reiserfs/CMakeLists.txt
sdk/lib/3rdparty/libxml2/CMakeLists.txt

Should fix VC2010 build.
Addendum to 11ecf5c969b.

[CMAKE] When disabling C4101, explicitly remove the error flag.

---

dll/win32/shell32/wine/shellpath.c

- Set read-only attribute instead of system attribute for some shell folders that has a folder icon.
- Delete `desktop.ini` files in Desktop and Program Files.
JIRA issue: [CORE-16711](https://jira.reactos.org/browse/CORE-16711)
BEFORE:
AFTER:
WinXP:
Win2k3:

[SHELL32] Set read-only for some shell folders and delete Desktop.ini of Desktop and Program Files

---

dll/win32/shell32/wine/changenotify.c

Windows sends notification even if two parameters are provided for notification of one parameter.
BEFORE:
AFTER:
Failures are fixed.

[SHELL32] Fix SHChangeNotify for one item events

---

base/shell/cmd/dir.c

Correctly interpret the drive-decorated pathnames (`C:` or `D:dir1` etc).
JIRA issue: [CORE-15871](https://jira.reactos.org/browse/CORE-15871)
BEFORE:
AFTER:

[CMD] Correctly parse drive-decorated pathname

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHChangeNotify.cpp
modules/rostests/apitests/shell32/shell-notify.cpp

The `shell32!SHChangeNotify` function must be tested on multiple processes.
WinXP:
Win2k3:
Win10:
ReactOS:

[SHELL32_APITEST] Support multi-process of SHChangeNotify testcase

---

dll/win32/shell32/shlexec.cpp
modules/rostests/apitests/shell32/ShellExecCmdLine.cpp

Fix and improve private function `shell32!ShellExecCmdLine` to improve `Run` Dialog behavior.
JIRA issue: [CORE-14409](https://jira.reactos.org/browse/CORE-14409)
Dot:
Dot dot:
C drive:

[SHELL32] Improve ShellExecCmdLine in path resolving

---

ntoskrnl/mm/ARM3/pfnlist.c
ntoskrnl/mm/amd64/init.c

AMD64 initialization previously only raised the IRQL.
It now acquires the lock where needed, as i386 does.

[NTOS:MM] Assert PFN lock ownership in MiInsertPageInFreeList.

---

win32ss/user/ntuser/focus.c
win32ss/user/ntuser/winpos.c

Fix taskbar button states via correct ShellHook notifications when creating/activating/switching windows.
JIRA issues:
[CORE-11324](https://jira.reactos.org/browse/CORE-11324)
[CORE-16703](https://jira.reactos.org/browse/CORE-16703)
[CORE-16705](https://jira.reactos.org/browse/CORE-16705)
[CORE-16706](https://jira.reactos.org/browse/CORE-16706)
This is my first PR here which is actual code and not just translation, so it may not be perfect.

[ntuser] fix ShellHook notifications when creating/activating windows

---

modules/rostests/winetests/kernel32/generated.c

Import test part of
https://source.winehq.org/git/wine.git/commit/a59d6387b6734cf0acb187e9c178d7c540751cae
JIRA issue: [ROSTESTS-251](https://jira.reactos.org/browse/ROSTESTS-251)

[KERNEL32_WINETEST] Fix COMMCONFIG.wcProviderData values. ROSTESTS-251

---

dll/directx/ddraw/CMakeLists.txt
dll/directx/dsound_new/CMakeLists.txt

* Create export tables for native ddraw and dsound_new
* Include native ddraw version resource in build process
JIRA issue: [CORE-16228](https://jira.reactos.org/browse/CORE-16228)

[DSOUND_NEW][DDRAW] CMake fixes

---

sdk/cmake/gcc.cmake

GCC 4.7.2 logs
'cc1: error: unrecognized command line option "-Wno-unused-const-variable" [-Werror]'
Addendum to 8eb7a1a2f4a9cce5a70a9c48efb30cdfa59bf56f.

[CMAKE] gcc.cmake: '-Wno-unused-const-variable' applies to GCC 6.1+

---

base/applications/network/tracert/tracert.cpp

Try to fix undefined behavior mentioned on [CORE-16620](https://jira.reactos.org/browse/CORE-16620).
JIRA issue: [CORE-16620](https://jira.reactos.org/browse/CORE-16620)
- Make SendBuffer and ReplyBuffer* variables together into a struct. 
None

[TRACERT] Fix ReplyBuffer sizing CORE-16620

---

modules/rostests/apitests/apphelp/layerapi.c
modules/rostests/apitests/kernel32/GetComputerNameEx.c
modules/rostests/apitests/kernel32/PrivMoveFileIdentityW.c
modules/rostests/apitests/ws2_32/WSARecv.c

To get the relevant `LastError` value.

[APITESTS] Tested function must be called before GetLastError() log

---

sdk/include/host/typedefs.h

Most of them are unaffected by packing, the ones that are affected have pointers, and packing them will only misalign them, but not making the structures 32 bit compatible.

[HOST] Do not pack structures

---

dll/win32/shell32/wine/brsfolder.c

Try to implement keyboard shortcuts in the browse folder dialog by importing wine code
JIRA issue: [CORE-14332](https://jira.reactos.org/browse/CORE-14332)
- import the wine commit which implement the shortcuts
~~- import shellfolder.h to have ISFHelper definition (That maybe let us get rid of some #ifdef __REACTOS__)~~
now at least renaming via f2 key works, but not delete via del key
get del also working (help or tips appreciated)

Sync brsfolder.c with keyboard shortcut code from wine

---

win32ss/user/user32/windows/window.c

The creation conditions of MDI window was too strict.
JIRA issue: [CORE-15633](https://jira.reactos.org/browse/CORE-15633)
BEFORE:
AFTER:

[USER32] Relax conditions for creating MDI windows

---

modules/rostests/winetests/gdi32/dc.c
modules/rostests/winetests/user32/dialog.c
modules/rostests/winetests/user32/msg.c
modules/rostests/winetests/user32/sysparams.c

No impact, as already deactivated.
Import
https://source.winehq.org/git/wine.git/commit/d0fd12b90946865a92f3fd016ccac13e5c4fdf54

[GDI32_WINETEST][USER32_WINETEST] Remove forced WINVER defines

---

win32ss/user/winsrv/consrv/frontends/gui/conwnd.c

This is a workaround that fixes console WIndows not showing up, which happens quite often on x64.
JIRA issue: [CORE-16749](https://jira.reactos.org/browse/CORE-16749)

[WINSRV] Use DIB section for frame buffer bitmap

---

win32ss/gdi/ntgdi/line.c

Fix DC bounds calculation when using LineTo & friends
FIxes ~40 gdi32:dib winetests

[WIN32K] Fix bounds calculation when drawing with a pen

---

base/applications/network/ping/ping.c

`ping -l 0 reactos.org` is valid.

[PING] Do not abort (as OoM) when request size = 0

---

boot/bootdata/hivesys.inf

I simply duplicated 0445 (bn-in).
JIRA issue: [CORE-16766](https://jira.reactos.org/browse/CORE-16766)

[BOOTDATA] Add 0845 (bn-bd) language. CORE-16766

---

dll/win32/userenv/lang/sq-AL.rc

Not to translate!
JIRA issue: [CORE-16762](https://jira.reactos.org/browse/CORE-16762)

[USERENV] sq-AL: Fix '%SistemDrive%' typo. CORE-16762

---

sdk/include/ndk/i386/mmtypes.h

This not only makes PAE possible, but also allows to make the definitions and macros in the memory manager header files more human-readable.
JIRA issue: [CORE-16702](https://jira.reactos.org/browse/CORE-16702)

[SDK][NDK] MMPTE for PAE

---

base/applications/wordpad/lang/no-NO.rc

".../no-NO.rc:81: syntax error"
NB:
This blocks enabling NO_NO.

[WORDPAD] Restore code commas in no-NO.rc

---

modules/rostests/winetests/rpcrt4/ndr_marshall.c
modules/rostests/winetests/shell32/shlexec.c

Affects rpcrt4 only.
Import
https://source.winehq.org/git/wine.git/commit/57f08ba5259e56ae681bab1e61f86d6e8ab96f37
https://source.winehq.org/git/wine.git/commit/8fc0b7d525ae5e85b5a796eaf6572d22591e02c6

[WINETESTS] Remove forced 0x050n API versions, with regard to NTDDI_VERSION

---

modules/rostests/winetests/gdi32/generated.c
modules/rostests/winetests/kernel32/generated.c
modules/rostests/winetests/ntdll/generated.c
modules/rostests/winetests/rpcrt4/generated.c
modules/rostests/winetests/shell32/generated.c
modules/rostests/winetests/shlwapi/generated.c
modules/rostests/winetests/urlmon/generated.c
modules/rostests/winetests/user32/generated.c
modules/rostests/winetests/wininet/generated.c
modules/rostests/winetests/winmm/generated.c

This actually affects 2 modules only:
* kernel32: this file is still commented out, these defines were going to be deactivated anyway.
* rpcrt4: I don't know why it had these defines (still) activated. Anyway.
Import
https://source.winehq.org/git/wine.git/commit/aa384d36429110970aa72acbc5043158de6aff03

[WINETESTS] */generated.c: Remove forced 0x0501 API versions

---

modules/rostests/winetests/kernel32/CMakeLists.txt
modules/rostests/winetests/kernel32/generated.c

JIRA issue: [ROSTESTS-251](https://jira.reactos.org/browse/ROSTESTS-251)

[KERNEL32_WINETEST] Enable 'generated.c', at last. ROSTESTS-251

---

dll/ntdll/ldr/ldrpe.c

Generates output like:
`(dll\ntdll\ldr\ldrpe.c:1065) Failed to snap kernel32.dll!GetCurrentPackageId for test.exe`

[LDR] Include source dll in static snap failure dprint

---

boot/environ/CMakeLists.txt
boot/environ/lib/rtl/libsupp.c
boot/freeldr/freeldr/lib/rtl/libsupp.c
dll/ntdll/rtl/libsupp.c
dll/win32/kernel32/client/loader.c
ntoskrnl/rtl/libsupp.c
sdk/include/ndk/rtltypes.h
sdk/lib/rtl/image.c

which implements the required functionality.
ntdll and ntoskrnl now have a wrapper for this, with SEH.
This protects the function against malformed / bad images,
whilst still being able to use the code in freeldr et al.
Idea from Thomas.
CORE-14857
JIRA issue: [CORE-14857](https://jira.reactos.org/browse/CORE-14857)

[RTL] Introduce RtlpImageNtHeader

---

win32ss/gdi/gdi32/objects/bitmap.c

allow BI_BITFIELDS compression in CreateDIBitmap
JIRA issue: [CORE-16750](https://jira.reactos.org/browse/CORE-16750)

[GDI32] allow BI_BITFIELDS compression in CreateDIBitmap

---

dll/win32/winmm/joystick.c

Follow-up to 97150ce9dd96412036e64a1aa74ccfd2ca9c1805.
Import
https://source.winehq.org/git/wine.git/commit/175a2a027637719d1f3c644d97b6df4aacabb296

[WINMM] Add a WARN() when winejoystick.drv is missing

---

dll/win32/shell32/wine/classes.c

Import
https://source.winehq.org/git/wine.git/commit/7cc2806e0e0d97c0df93e2695351a4d3a3c72254
NB:
Since #2054 is stalled.
JIRA issue: [CORE-11713](https://jira.reactos.org/browse/CORE-11713)

[SHELL32] HCR_GetIconA(): Properly use icon_idx. CORE-11713

---

modules/rostests/winetests/ntdll/exception.c
modules/rostests/winetests/ntdll/ntdll_test.h

No impact, as conditional.
Import
https://source.winehq.org/git/wine.git/commit/71d810319059d171df0e40d85752519e50e58056

[NTDLL_WINETEST] Remove forced 0x500 API versions

---

base/applications/wordpad/wordpad.c
dll/win32/riched20/editstr.h
modules/rostests/winetests/comctl32/rebar.c
modules/rostests/winetests/shell32/systray.c
modules/rostests/winetests/urlmon/sec_mgr.c
modules/rostests/winetests/user32/input.c
sdk/include/reactos/wine/commctrl.h

No impact, as already deactivated or superseded or superfluous.
Import
https://source.winehq.org/git/wine.git/commit/7770e26f2d773dcade6f073585b6fac2661e1eb3

[REACTOS] Remove forced _WIN32_IE defines

---

modules/rostests/apitests/kernel32/GetComputerNameEx.c
modules/rostests/apitests/ws2_32/WSARecv.c

Follow-up to cb5aa7bee44f57306d6c093bd5c93395ab7db7b7.

[KERNEL32_APITEST][WS2_32_APITEST] Call SetLastError() before checking LastError

---

drivers/wdm/audio/backpln/portcls/pin_wavert.cpp

Added in missing switches. (`IOCTL_KS_HANDSHAKE `and `IOCTL_KS_METHOD`)
There are many instances of replacing this driver with MS's fixing a lot of different sound issues, but it's hard to debug such a thing without warnings and errors in the logs, so I've also added unimplemented messages for when these are called. 
I wish I had the knowledge to fix such an issue, but at the least I can do small things like this

[portcls] Add in missing IoControlCode switches

---

dll/win32/aclui/sidcache.c

Same fix as 085528c31ad8b91ae7af6dda9b9faa5c463ade70.
NB:
SID cache was added on r20332 (5ec3b17e0df5b89a6f6b7b37fafdc386ddd72bd8).

[ACLUI] 1+2 functions: Properly enumerate cache+queue entries

---

sdk/tools/spec2def/spec2def.c

JIRA issue: [CORE-16769](https://jira.reactos.org/browse/CORE-16769)

[SPEC2DEF] Omit skipped exports from ordinal numbering.

---

dll/shellext/stobject/hotplug.cpp

Change the eject hardware information dialog buttons from OK/Cancel to just OK. It's just an information dialog that needs one button, it's not actually doing different actions based on user input.

[STOBJECT] Change eject hardware dialog buttons from OK/Cancel to OK

---

ntoskrnl/mm/ARM3/section.c

The SYSTEM_PD_SIZE constant should not be used to determine the page boundary for page tables. It is also better to use the MiIsPteOnPdeBoundary macro for this.

[NTOS:MM] Using the macro MiIsPteOnPdeBoundary().

---

.gitpod.Dockerfile
.gitpod.yml
.theia/launch.json
.theia/settings.json
.theia/tasks.json
README.md

I played a bit with gitpod and their online IDE (theia) and I have been pleased by the experience. The PR is about having the possibility to develop and debug ReactOS (in qemu) with a one-click solution.
The proposed configuration creates a custom docker image, and has the tasks configured to build, launch & debug both bootcd & livecd (using GDB).
I fixed a few hitches while I were at it, mostly in the build system and in KDGDB.
Nothing much, those are a bunch of config files, but you can have a look there :
https://gitpod.io#snapshot/4b28a6aa-3a64-4a6e-8bdb-5a7c190b2e10
If you want to have nice C/C++ integration, you have to choose the build configuration in the "C/C++ build config" button at the bottom right of the screen.
NB : in the "open ports" tab, you can open the browser for port …

Introduce configuration for gitpod

---

modules/rostests/winetests/comctl32/subclass.c
modules/rostests/winetests/kernel32/sync.c
modules/rostests/winetests/kernel32/thread.c
modules/rostests/winetests/kernel32/timer.c
modules/rostests/winetests/kernel32/version.c
modules/rostests/winetests/psapi/psapi_main.c
modules/rostests/winetests/user32/broadcast.c
modules/rostests/winetests/user32/class.c
modules/rostests/winetests/user32/menu.c

Only comctl32 is affected.
Import
https://source.winehq.org/git/wine.git/commit/be3cda6ec0856d143d4737ee9306844569b76e15

[WINETESTS] Remove forced _WIN32_WINNT defines

---

win32ss/include/ntuser.h

Addendum to 568b6d0558d047df1826d7438448432643d7fe5c.

[WIN32K:NTUSER] ntuser.h: Rename NtUserWaitForInputIdle() 3rd parameter

---

ntoskrnl/include/internal/amd64/mm.h
ntoskrnl/include/internal/i386/mm.h
ntoskrnl/mm/ARM3/miarm.h

Purpose: make the definitions and macros for x86 MM more human-readable.
Now definitions have become more universal for PAE mode.

[NTOS:MM] Make the definitions and macros for x86 more human-readable.

---

ntoskrnl/io/debug.c
ntoskrnl/io/pnpio.h
ntoskrnl/ntos.cmake

Useful functions for debugging IO and PNP managers:
PipDumpDeviceNodes() - displays information about a node(s) in the device tree;
PipDumpResourceRequirementsList() - displays information about a Io List;
PipDumpCmResourceList() - displays information about a Cm List
The tree list of devices (DEVICE_NODE structures) is perhaps the main one in the PnP manager. They also store information about the hardware resources required and assigned to devices.
These functions can help with debugging. For example, you can call PipDumpDeviceNodes() before and after device enumeration and compare the resulting information.
For PipDumpDeviceNodes() it is possible to optionally output:
- allocated resources and boot configuration resources
- resources required
- translated resources
It is possible to …

[NTOS:PNP] Add set functions for debugging PNP and IO managers.

---

ntoskrnl/mm/ARM3/miarm.h
ntoskrnl/mm/ARM3/mminit.c
ntoskrnl/mm/ARM3/pfnlist.c
ntoskrnl/mm/ARM3/zeropage.c

Note the first commit -- I was fixing a race condition with the current code. Then I noticed that the boolean is totally unnecessary as far as I can tell. A `NotificationEvent` can store this same information.
Feel free to prove me wrong ;)

[NTOS:MM] Get rid of unnecessary MmZeroingPageThreadActive

---

dll/appcompat/shims/shimlib/shimlib.c

JIRA issue: [CORE-16514](https://jira.reactos.org/browse/CORE-16514)
There seems to be some padding before `_shim_end`, causing the loop to continue forever.

[SHIMLIB] Fix gcc8 build crashing when using shims

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/shelldesktop/CChangeNotify.cpp

JIRA issue: [CORE-10391](https://jira.reactos.org/browse/CORE-10391)
On desktop view, we have to watch both the common desktop and the private desktop.
In Windows, `IShellLink::Save` (shortcut creation) sends `SHCNE_CREATE` or `SHCNE_UPDATEITEM` notification.
Simplify `CChangeNotify::ShouldNotify`.
AFTER:

[SHELL32] Watch for common desktop and SHCNE_CREATE for IShellLink::Save

---

base/applications/drwtsn32/sysinfo.cpp

drwtsn32.exe recognizes several standard exception codes, and prints their names in the crash log. However, EXCEPTION_WINE_STUB is not in this list, and as such it is treated as an unknown error and printed as "--". Having this error code given a name at the start of the crash dump is useful, as it allows me to identify calls to unimplemented issues more readily.
JIRA issue: (none)

[DRWTSN32] Recognize EXCEPTION_WINE_STUB

---

dll/apisets/api-ms-win-crt-runtime-l1-1-0.spec

Since these functions are forwarded to a different function name, update.py misses them. The choice of target [comes from Wine](https://github.com/wine-mirror/wine/blob/a98ca88dd1139ad8e16e63fbb349c2fc5e9ad332/dlls/ucrtbase/ucrtbase.spec#L1877-L1878).
With this change applied, calls to other stub functions from certain binaries (namely, dotnet.exe from .NET Core) now "correctly" crash, invoking drwtsn32, instead of simply exiting.

[APISETS] Forward _seh_filter_{dll,exe}

---

boot/freeldr/freeldr/ntldr/winldr.c

Purpose: add parsing boot options from *.ini files for next keys:
for NT4-W2003
/3GB
/SOS
for w2000-W2003
/SAFEBOOT
/PAE
for XP-W2003
/NOPAE
/BOOTLOGO
for non setup only
/NOEXECUTE=ALWAYSOFF
/NOEXECUTE
/EXECUTE
- Add variables:
VirtualBias
SosEnabled
PaeEnabled
PaeDisabled
SafeBoot
BootLogo
NoexecuteDisabled
NoexecuteEnabled
- Also add DPRINT1() definition for freeldr.

Freeldr parse boot options

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHAppBarMessage.cpp
modules/rostests/apitests/shell32/testlist.c

Add a testcase for `shell32!SHAppBarMessage` function.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.

[SHELL32_APITEST] Add SHAppBarMessage testcase

---

drivers/bus/pcix/CMakeLists.txt
drivers/bus/pcix/arb/ar_busno.c
drivers/bus/pcix/pci.h
hal/halx86/CMakeLists.txt
ntoskrnl/CMakeLists.txt
ntoskrnl/include/internal/ntoskrnl.h
ntoskrnl/io/pnpmgr/arbs.c
ntoskrnl/io/pnpmgr/pnpinit.c
ntoskrnl/ntkrnlmp/CMakeLists.txt
ntoskrnl/ntos.cmake
sdk/lib/drivers/CMakeLists.txt
sdk/lib/drivers/arbiter/CMakeLists.txt
sdk/lib/drivers/arbiter/arbiter.c
sdk/lib/drivers/arbiter/arbiter.h

The main purpose of this PR is to add a definition of the structures for the HW resource arbiter.
In addition to this, the IopInitializeArbiters() function was implemented in the PNP manager and stub was added for ArbInitializeArbiterInstance().
The directory "XXX" is chosen because the arbiter can be used not only by the kernel, but also by pci and acpi bus drivers, as well as legacy HAL (PIC).

[SDK][LIB] Add structures for the arbiter.
