reactos/reactos

dll/ntdll/def/ntdll.spec, modules/rostests/apitests/ntdll/CMakeLists.txt, modules/rostests/apitests/ntdll/RtlRemovePrivileges.c, modules/rostests/apitests/ntdll/testlist.c, sdk/include/ndk/rtlfuncs.h, sdk/lib/rtl/priv.c
=> [RTL][NTDLL_APITEST] Implement RtlRemovePrivileges

modules/rostests/apitests/user32/CMakeLists.txt, modules/rostests/apitests/user32/KbdLayout.c, modules/rostests/apitests/user32/testlist.c
JIRA issue: [CORE-17906](https://jira.reactos.org/browse/CORE-17906)
For @julcar. See PR #4730 for details.
<details>
<summary>Windows Server 2003, also ReactOS with replaced kbd*.dll files</summary>
```sh
KbdLayout.c:21: Testing 'KBDAL.DLL'...
KbdLayout.c:21: Testing 'kbdaze.dll'...
KbdLayout.c:21: Testing 'kbdazel.dll'...
KbdLayout.c:21: Testing 'kbdbe.dll'...
KbdLayout.c:21: Testing 'kbdbene.dll'...
KbdLayout.c:21: Testing 'kbdbhc.dll'...
KbdLayout.c:21: Testing 'kbdblr.dll'...
KbdLayout.c:21: Testing 'kbdbr.dll'...
KbdLayout.c:21: Testing 'kbdbu.dll'...
KbdLayout.c:21: Testing 'kbdca.dll'...
KbdLayout.c:21: Testing 'kbdcan.dll'...
KbdLayout.c:21: Testing 'kbdcr.dll'...
KbdLayout.c:21: Testing 'kbdcz.dll'...
KbdLayout.c:21: Testing 'kbdcz1.dll'...
KbdLayout.c:21: Testing …
```
=> [USER32_APITEST] Add tests for Keyboard Layouts

base/applications/mscutils/eventvwr/eventvwr.c, base/applications/mscutils/eventvwr/eventvwr.h
Exactly what's written in the title.
- Don't create the settings registry key when trying to load them.
Defer its creation when saving the settings.
- Use more restricted access rights when opening/creating the key.
- Ensure read and written string settings are NULL-terminated.
- Use the Win32 CRT assert so that if an assertion fails we get a
message on the screen, not via the kernel debugger.
=> [EVENTVWR] Fix settings loading. Remove usage of Rtl functions. Use Win32 CRT assert.

.gitignore
When working on macOS, the system creates a .DS_Store file in every accessed directory. They are marked as new files
in git, which is very annoying. This change will exclude these files.
- Add .DS_Store files to .gitignore
=> [GIT] Add .DS_Store files to .gitignore

dll/win32/imm32/keymsg.c
- Rename `Imm32ImeNonImeToggle` as `Imm32CImeNonImeToggle` (Win `CIMENonIMEToggle`).
- Add `Imm32ImeNonImeToggle` (Win: `IMENonIMEToggle`) function.
- Improve IME hot-key functions.
=> [IMM32] Implement Imm32ImeNonImeToggle

dll/win32/shell32/CDefaultContextMenu.cpp, dll/win32/shell32/CFolderItemVerbs.cpp
[SHELL32] Fix CDefaultContextMenu DFM_MERGECONTEXTMENU handling
[SHELL32] CFolderItemVerb: Zero-initialize output parameters
=> [SHELL32] Small fixes

dll/win32/shell32/CDefView.cpp
This got broken when when resolving a conflict between two changes in the same function.
=> [SHELL32] Fix using the wrong context menu

win32ss/user/ntuser/draw.c, win32ss/user/user32/windows/draw.c
`DrawFrameControl:DFC_MENU` draws the monochrome image of menu arrow or checkmark. However, the function didn't draw the entire rectangle correctly when the rectangle was not a square.
`DrawFrameControl:DFC_MENU` should fill the background rectangle by white.
JIRA issue: [CORE-18417](https://jira.reactos.org/browse/CORE-18417)
BEFORE:
AFTER:
=> [USER32][NTUSER] Fill by white in DrawFrameControl:DFC_MENU

win32ss/user/ntuser/draw.c, win32ss/user/ntuser/menu.c, win32ss/user/user32/windows/draw.c
This PR is a retrial of https://github.com/reactos/reactos/commit/13868ee0e85c5b778d5f2d136205fbf10ffacf0c (#4779).
JIRA issue: [CORE-18515](https://jira.reactos.org/browse/CORE-18515), [CORE-18417](https://jira.reactos.org/browse/CORE-18417)
- Fill the background if necessary, and set the text color and the back mode in `DrawFrameControl:DFC_MENU`.
- Use `UITOOLS95_DrawFrameMenu` in menu drawing instead of `DrawFrameControl`.
Win2k3:
BEFORE:
AFTER:
=> [NTUSER][USER32] Improve DrawFrameControl:DFC_MENU and DFC_BUTTON

boot/bootdata/hivesys.inf, win32ss/drivers/miniport/CMakeLists.txt, win32ss/drivers/miniport/bochs/CMakeLists.txt, win32ss/drivers/miniport/bochs/bochsmp.c, win32ss/drivers/miniport/bochs/bochsmp.h, win32ss/drivers/miniport/bochs/bochsmp.inf, win32ss/drivers/miniport/bochs/bochsmp.rc, win32ss/drivers/miniport/bochs/bochsmp_reg.inf
Add a native driver for Bochs Graphic card, emulated in Bochs and in QEMU
- Doesn't need a BIOS to work
- Supports a wide-range of predefined resolutions, up to 4K (more can be added if needed)
- Supports multidisplay
- Tested in Windows 2003
- Tested on emulator Bochs 2.7
- Tested on emulator QEMU with displays "VGA", "secondary-vga" and "bochs-display"
=> [BOCHSMP] Add driver for QEMU and Bochs graphic card

base/setup/lib/bootsup.c, base/setup/lib/fsutil.c, base/setup/lib/fsutil.h
Adding NTFS boot support for the setup library.
Jira issue: [CORE-17474](https://jira.reactos.org/browse/CORE-17474)
=> [SETUPLIB] Add NTFS boot support.

base/system/rundll32/rundll32.c, sdk/include/psdk/winbase.h
This fixes f.e. Ctrl+A not working in the Create Shortcut wizard
JIRA issue: [CORE-16669](https://jira.reactos.org/browse/CORE-16669)
=> [RUNDLL32] Try to resolve the manifest file manually

dll/cpl/access/display.c, dll/cpl/main/keyboard.c, win32ss/user/ntuser/caret.c
[MAIN.CPL] Fix Cursor/Caret blinking [CORE-17929](https://jira.reactos.org/browse/CORE-17929)
[MAIN.CPL] Do not delete system stock object
[MAIN.CPL] Save uCaretBlinkTime to CursorBlinkRate key
Cursor/Caret blinking rate never  reaching None
[NTUSER] Fix issue when caret is static
When caret is static (not blinking) it is not shown and hiden correctly when moved in a one line edit box or combobox.
=> [MAIN.CPL] Fix Cursor/Caret blinking CORE-17929

base/system/smss/smss.c, ntoskrnl/mm/ARM3/sysldr.c, subsystems/win32/csrsrv/CMakeLists.txt
`[CSRSRV] Remove deprecated dependency on smdll.`
`[SMSS][NTOS:MM] Get rid of the remaining sprintf_nt hacks.`
=> Minor cleanup of deprecated things in CSRSRV/SMSS/NTOS:MM

ntoskrnl/mm/section.c
Return TRUE instead of NTSTATUS code which has a value of FALSE and may confuse caller. Fixes sporadic 0x7B bugcheck when booting from corrupted NTFS volume using WinXP ntfs.sys.
=> [NTOS:MM] MmPurgeSegment: Fix wrong return value

dll/win32/rasdlg/lang/pl-PL.rc
`tą` and `tę` are very often mistaken for each other by native speakers..
=> [RASDLG] Fix typos in Polish translation

dll/ntdll/def/ntdll.spec, dll/ntdll/ldr/ldrapi.c
This is the final step required to properly support SE_DynamicShim 
JIRA issue: [CORE-13283](https://jira.reactos.org/browse/CORE-13283)
=> [NTDLL] Implement LdrInitShimEngineDynamic.

CONTRIBUTING.md
These links did not actually work, as GitHub expected no question mark, but we did provide one.
Removing said question marks fixes the links.
=> [CONTRIBUTING] Fix broken hash links

dll/win32/browseui/CAutoComplete.cpp, dll/win32/browseui/CAutoComplete.h
[CORE-18395](https://jira.reactos.org/browse/CORE-18395)
This was very visible when running with DPH:
Open an explorer window,
and close it again.
=> [BROWSEUI] Fix CAutoComplete use after free

dll/win32/kernel32/winnls/string/nls.c, sdk/include/reactos/subsys/win/base.h, subsystems/win/basesrv/basesrv.h, subsystems/win/basesrv/nls.c
Partially revert some aspects of commits 5696e4ba4 and bf40c7a31. (See PR #4340.)
In order for Win2k3 kernel32.dll to operate with our basesrv.dll (or our kernel32.dll to operate with Win2k3 basesrv.dll), we need in particular to have the CreateNlsSecurityDescriptor() helper to exactly take the expected parameters. Namely, a pointer to a **user-allocated** SECURITY_DESCRIPTOR buffer, its size (and an access mask).
The function expects its caller to provide all this, and the caller expects the function to initialize the security descriptor buffer. Note that the function does *NOT* allocate a new descriptor buffer to be returned!
Indeed, with the way it currently is in master, using Win2k3 kernel32 with our basesrv is now failing with the errors:
```
NLSAPI: Could NOT Create ACL - c0000023. …
```
=> [KERNEL32][BASESRV] Fix interoperability with Win2k3 regarding NLS section security.

sdk/include/psdk/wtypes.idl
nLength is the size of the struct itself,
not a number of descriptors.
Addendum to 1f12113 (r26428).
JIRA issue: noticed while investigating CORE 15471.
=> [PSDK] SECURITY_ATTRIBUTES: Remove size_is(nLength)

base/shell/explorer/traywnd.cpp
JIRA issue: [CORE-13330](https://jira.reactos.org/browse/CORE-13330)
- Add `HideStartMenu` helper method.
- Hide Start Menu before opening Run dialog.
BEFORE:
AFTER:
=> [EXPLORER] Hide Start Menu before Run dialog

ntoskrnl/fsrtl/fastio.c, ntoskrnl/include/internal/fsrtl.h, ntoskrnl/mm/section.c
Properly lock the file when flushing data to disk when reclaiming memory on file sections
JIRA issue: [CORE-17595](https://jira.reactos.org/browse/CORE-17595) maybe, I can't tell for sure.
Do something sane in FsRtlAcquireFileForModWriteEx which is currently completely irrational, and call it when we're flushing data to disk in the page-out case.
=> [NTOS] Properly implement and use FsRtlAcquireFileForModWriteEx

drivers/network/dd/e1000/send.c, modules/rostests/apitests/ntdll/RtlGenerate8dot3Name.c, modules/rostests/apitests/ntdll/RtlUnicodeStringToCountedOemString.c, modules/rostests/apitests/ntdll/RtlUnicodeToOemN.c, modules/rostests/apitests/ntdll/RtlxUnicodeStringToAnsiSize.c, modules/rostests/apitests/ntdll/RtlxUnicodeStringToOemSize.c, modules/rostests/apitests/ntdll/locale.c, ntoskrnl/mm/ARM3/wslist.cpp, ntoskrnl/mm/i386/procsup.c, sdk/include/reactos/msgdump.h, sdk/include/reactos/winxx.h, sdk/tools/gcc_plugin_seh/main.cpp, sdk/tools/txt2nls/main.cpp
Remove '.html' from spdx.org license page URLs, only in source code files (not in the media/doc/3rd Party Files.txt)
=> Remove '.html' from spdx.org license page URLs.

dll/win32/shell32/wine/shellpath.c, sdk/include/reactos/shlwapi_undoc.h
JIRA issue: [CORE-18080](https://jira.reactos.org/browse/CORE-18080), [CORE-15204](https://jira.reactos.org/browse/CORE-15204)
- Fix `shell32!PathResolve` and `shell32!PathQualifyExW` functions for double-backslash.
BEFORE:
AFTER:
Successful.
AFTER:
The icon is fixed.
=> [SHELL32][INCLUDE] Fix PathResolve for double-backslash

dll/cpl/intl/CMakeLists.txt, dll/cpl/intl/languages.c
This PR will implement `IDC_INST_FILES_FOR_ASIAN` checkbox action. It will install/uninstall `"ReactOS JPN Package"` in Japanese ReactOS.
JIRA issue: [CORE-12748](https://jira.reactos.org/browse/CORE-12748)
- Detect `"ReactOS JPN Package"` installation.
- Use `"ReactOS JPN Package"` instead of "mzimeja".
- Implement installation/uninstallation of `"ReactOS JPN Package"` as the action of `IDC_INST_FILES_FOR_ASIAN` checkbox.
=> [CPL:INTL] Use Japanese package for Far-East files

dll/win32/comdlg32/fontdlg.c
by importing Wine commit
https://source.winehq.org/git/wine.git/commit/4273004e65addb70b3f7d91e95eb3d5da31ffa3e
Thanks to @gonzoMD who quickly spotted the needed wine commit for us.
fix JIRA issue: [CORE-18588](https://jira.reactos.org/browse/CORE-18588)
I attached an after-picture for classic theme in the JIRA-report already. It works.
I also tested it successfully for Mizu, Modern, and the Luna theme from rapps.
Wine-Bug: https://bugs.winehq.org/show_bug.cgi?id=50034
Signed-off-by: Jeff Smith <whydoubt@gmail.com>
Signed-off-by: Alexandre Julliard <julliard@winehq.org>
=> [COMDLG32] Fix Font dialog Wrong background in font preview CORE-18588

modules/rostests/apitests/user32/CMakeLists.txt, modules/rostests/apitests/user32/CharFuncs.c, modules/rostests/apitests/user32/testlist.c
Add tests for CharPrev/Next/Ex/A/W.
JIRA issue: [CORE-18452](https://jira.reactos.org/browse/CORE-18452)
```
CharFuncs: 259 tests executed (0 marked as todo, 0 failures), 0 skipped.
```
```
CharFuncs.c:534: Test failed: [0] CharPrevExA: pchA (0x00233991) is not equal to pchEx (0x00233992)
CharFuncs.c:534: Test failed: [1] CharPrevExA: pchA (0x00233992) is not equal to pchEx (0x00233993)
CharFuncs.c:534: Test failed: [2] CharPrevExA: pchA (0x00233991) is not equal to pchEx (0x00233992)
CharFuncs.c:534: Test failed: [3] CharPrevExA: pchA (0x0023380D) is not equal to pchEx (0x0023380E)
CharFuncs.c:529: Test failed: [4] CharPrevA: pchA (0x00233988) is expected to be within szCurrent (0x00233808)
CharFuncs.c:532: Test failed: [4] CharPrevA: pchA is 0x00233988 (offset 384)
CharFuncs.c:532: Test …
```
=> [USER32_APITEST] Add tests for CharPrev/Next/Ex/A/W

dll/win32/shell32/shlexec.cpp, dll/win32/shell32/wine/shellreg.c, sdk/include/reactos/undocshell.h
Windows `"App Paths"` is a mechanism that realizes the command line execution with a single filename that is registered at a registry key. This PR will partially fix our broken `App Paths` mechanism.
JIRA issue: [CORE-11335](https://jira.reactos.org/browse/CORE-11335)
- Fix `SHELL_TryAppPathW` helper function using `SHRegQueryValueExW` function.
- Fix `SHRegQueryValueExA/W` functions.
Executing `"pbrush"` on the `Run` dialog
BEFORE:
Error.
AFTER:
Successful.
=> [SHELL32] shlexec: Initial support of App Paths

win32ss/gdi/eng/engobjects.h, win32ss/gdi/ntgdi/freetype.c
Optimize for speed.
- Delete some `IntRequestFontSize` function calls.
- Enable cache on font size requests.
- Add two members into `FONTGDI` structure, for font size cache.
=> [NTGDI][FREETYPE] Reduce font size request

win32ss/gdi/ntgdi/freetype.c
Optimize for speed.
- Optimize `MatchFontNames` helper function for speed.
=> [NTGDI][FREETYPE] Optimize MatchFontNames

ntoskrnl/include/internal/se.h, ntoskrnl/ntos.cmake, ntoskrnl/se/accesschk.c, ntoskrnl/se/debug.c, ntoskrnl/se/sid.c
Recently people have started to fill up tickets regarding "access check failures" of which most of them barely contain the most useful information needed to understand the cause of the failure. Perhaps some people are really diagnosed with _**weendeebagoophobia**_ (fear of WinDBG), only God knows...
Admittedly the `Failed to grant access rights` message really doesn't tell much so I guess it is time to implement some built-in debug routines for the Security subsystem, which is what this PR serves about. `debug.c` will be used as a centralized facility for whatever debug function is needed for SE, rather than having them scattered around places.
Example of debug output:
```
ntoskrnl\se\accesschk.c:711) SepAccessCheck(): Failed to grant access rights. RemainingAccess = 0x00000008 …
```
=> [NTOS:SE] Dump security debug info in case of an access rights grant failure

dll/directx/wine/ddraw/ddraw_private.h, dll/directx/wine/ddraw/palette.c, dll/directx/wine/ddraw/surface.c, media/doc/WINESYNC.txt
This PR aims the issue of lacking swap interval for the software / games (causing blank screen on rendering) that makes use of it on current ddraw of ROS.
Synced the barebone fix from wine:
https://gitlab.winehq.org/wine/wine/-/blob/master/dlls/ddraw/surface.c
and
https://gitlab.winehq.org/search?search=ddraw_surface_update_frontbuffer%28&nav_source=navbar&project_id=5&group_id=10&search_code=true&repository_ref=master
JIRA issue: [CORE-18547](https://jira.reactos.org/browse/CORE-18547)
- Added "swap_interval" argument to ddraw_surface_update_frontbuffer function
- Added "ddraw_swap_interval_from_flags" function  for dispatching the integer type of required swap interval 
- Updated the "ddraw_surface_update_frontbuffer" function for managing the swap internal between backbuffer and …
=> [DDRAW] Sync fix for swap_interval from wine

win32ss/user/ntuser/scrollbar.c, win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
Fix redrawing bug on Command Prompt.
JIRA issue: [CORE-18593](https://jira.reactos.org/browse/CORE-18593)
- Open Command Prompt.
- Type `Enter` key 30 times.
- The bottom edge of Command Prompt becomes dirty.
- Do not redraw the scrollbar if the scrollbar is hidden.
BEFORE (retested):
The bottom edge of Command Prompt is dirty.
AFTER (retested):
The bottom edge of Command Prompt is fixed.
BEFORE:
AFTER:
=> [NTUSER] Don't redraw scrollbar if it is hidden

dll/win32/shell32/wine/shellpath.c
#4850 had implemented `PathResolve` function. Actually, Windows `PathResolve` uses `IsLFNDriveW` function. Now `IsLFNDriveW` is fixed.
JIRA issue: [CORE-11335](https://jira.reactos.org/browse/CORE-11335)
- Fix `IsLFNDriveA` and `IsLFNDriveW` functions.
- Add `IsRemovableDrive` helper function.
- Fix `PathQualifyExW` by using `IsLFNDriveW`.
=> [SHELL32] Implement IsLFNDriveA/W and improve PathResolve

dll/win32/shell32/folders/CFSFolder.cpp
In explorer filebrowser 'details' view
the column 'comments' had invalid length of zero, and therefore was hidden under the 'attributes' column.
I guess even after this patch, it will not display any sane contents in there yet.
Therefore I chose a small width of 10 only, to reduce the chance for it to trigger an undesired horizontal scrollbar.
JIRA issue: [CORE-18615](https://jira.reactos.org/browse/CORE-18615)
As far as I see we don't support manual showing and hiding of additional columns.
By default my Windows does not show this column. But when activated manually, it is always
shown on the right hand side of the Atributes column.
For a video of the patched state, check the JIRA ticket.
=> [SHELL32] Show 'comments' column for folders, make it rightmost CORE-18615

base/setup/lib/muifonts.h, media/inf/font.inf, media/themes/Blackshade/blackshade.msstyles/textfiles/LargeFontsNormal.INI, media/themes/Blackshade/blackshade.msstyles/textfiles/NormalNormal.INI, media/themes/Lautus/lautus.msstyles/textfiles/LargeFontsNormal.INI, media/themes/Lautus/lautus.msstyles/textfiles/NormalNormal.INI, media/themes/Modern/modern.msstyles/textfiles/Dark/ExtraLargeDark.INI, media/themes/Modern/modern.msstyles/textfiles/Dark/LargeFontsDark.INI, media/themes/Modern/modern.msstyles/textfiles/Dark/RegularDark.INI, media/themes/Modern/modern.msstyles/textfiles/Light/ExtraLargeLight.INI, media/themes/Modern/modern.msstyles/textfiles/Light/LargeFontsLight.INI, media/themes/Modern/modern.msstyles/textfiles/Light/RegularLight.INI
An addendum to 0.4.14-dev-20-g 2f4fb903b46207ab380365908401ded63752a108 because since then we don't have the Ubuntu font anymore.
The substitutes are also not needed any longer.
We can use Tahoma here without causing any change in the current rendering, because for all languages the former
Ubuntu substitutions did point either to Tahoma,
or to the same thing, that Tahoma atm points to
(for those language that do require additional glyphs).
This way we do not only get the substitutions closer to 2k3sp2, but will also simplify our maintenance and testing, because the same font is guaranteed to be used then for all themes: Classic, Blackshade, Modern and Lautus: The font which has the needed glyphs for that specific language.
E.g.
"FreeSans" for Hindi,
"Tahoma" for most Western languages, …
=> [SETUP][INF][MEDIA] Get rid of the last Ubuntu references CORE-18607

base/system/diskpart/help.c
When the HELP command is executed for a multi-word command, for example "HELP CREATE PARTITION PRIMARY", diskpart crashes. This happens because before the desired form of the command is encountered, its single word form is found (in case of this example - "CREATE") - since the first word of the command matches the one HELP is looking for, it tries to compare the second word of the input command with the second (nonexistent) word of the encountered single word command, which is NULL. This results in diskpart crashing.
This fix makes HELP check if the to-be-compared word is not NULL before calling wcsicmp.
=> [DISKPART] Fix help for multi-word command crashing.

win32ss/user/user32/windows/text.c
Fixes 48 failing tests of `user32:CharFuncs`. Only 12 minor failing tests are left! :tada: 
JIRA issue: [CORE-18452](https://jira.reactos.org/browse/CORE-18452)
<details>
<summary>BEFORE :x:</summary>
```
CharFuncs.c:529: Test failed: [4] CharPrevA: pchA (0x00233988) is expected to be within szCurrent (0x00233808)
CharFuncs.c:532: Test failed: [4] CharPrevA: pchA is 0x00233988 (offset 384)
CharFuncs.c:532: Test failed: [5] CharPrevA: pchA is 0x00233993 (offset -7893)
CharFuncs.c:529: Test failed: [6] CharPrevA: pchA (0x00233988) is expected to be within szCurrent (0x00233808)
CharFuncs.c:532: Test failed: [6] CharPrevA: pchA is 0x00233988 (offset 384)
CharFuncs.c:568: Test failed: [5] CharPrevA: pchA is 0x00473EAA (expected 0x00473EA8)
CharFuncs.c:571: Test failed: [5] CharPrevExA: pchA …
```
=> [USER32] Rewrite CharPrev(Ex)A functions and fix tests

win32ss/user/ntuser/draw.c, win32ss/user/user32/windows/draw.c
… CORE-18609
and not black, like they erroneously were.
This patch does not seem to have any impact on how they are rendered for themed ros.
patch by @Krosuser2
JIRA issue: [CORE-18609](https://jira.reactos.org/browse/CORE-18609)
see screenshots of my own tests before + after for themed and unthemed here:
https://jira.reactos.org/browse/CORE-18609?focusedCommentId=136705&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-136705
Also ran a botrun upfront, results linked in there as well.
=> [NTUSER][USER32] Classic Theme: disabled "checked" checkboxes should be grey

modules/rostests/apitests/imm32/CMakeLists.txt, modules/rostests/apitests/imm32/ImmEnumInputContext.c, modules/rostests/apitests/imm32/testlist.c
Verify the IMM implementation.
- Add `ImmEnumInputContext` testcase.
Successful.
Win2k3 English:
Successful.
Win10 Japanese:
Successful.
=> [IMM32_APITEST] Add ImmEnumInputContext testcase

dll/win32/shell32/folders/CDrivesFolder.cpp
DFM_MERGECONTEXTMENU handler works properly now.
Addendum to 64657051c3c.
Following @learn-more's suggestion :slightly_smiling_face: 
> The fix is the same as for the recently fixed 'Send to' fix, so please just send a PR for that.
JIRA issue: [CORE-18577](https://jira.reactos.org/browse/CORE-18577)
Cc @KRosUser2 to retest.
=> [SHELL32] CDrivesFolder: Unhardcode pqcminfo->idCmdFirst value

drivers/filesystems/ntfs/fcb.c
=> [NTFS] NtfsCreateFCB(): Check allocation result

hal/halx86/acpi/halpnpdd.c, hal/halx86/legacy/halpnpdd.c
Help find out which GUIDs are actually wanted.
Note:
I guess the 2 ACPI GUIDs are only used for the ACPI HAL. Correct?
Based on CircularTriangle06's patch.
JIRA issue: [CORE-11632](https://jira.reactos.org/browse/CORE-11632)
=> [HALX86] HalpQueryInterface(): Debug log InterfaceType param

boot/bootdata/hivesft.inf, win32ss/gdi/ntgdi/misc.h, win32ss/user/ntuser/ime.c, win32ss/user/ntuser/metric.c, win32ss/user/ntuser/misc/registry.c, win32ss/user/ntuser/simplecall.c, win32ss/user/ntuser/userfuncs.h
PR #4876 revealed the bug in `ImmEnumInputContext`. 
Fix `SRVINFO_IMM32` flag and `ImmEnumInputContext` testcase's results.
This PR enables `SRVINFO_IMM32` also for non-CJK. You can disable this flag by setting zero to  the `LoadIMM` registry value if you're non-CJK.
- Fix the `LoadIMM` registry value.
- Add `RegOpenSectionKey` and `RegGetSectionDWORD` helper functions.
- Add `UserIsIMMEnabled` function by using helper funtions.
- Fix `SRVINFO_IMM32` flag status by using `UserIsIMMEnabled`.
- Fix `NOPARAM_ROUTINE_UPDATEPERUSERIMMENABLING` action by using `UserIsIMMEnabled`.
BEFORE:
Failing.
AFTER:
Successful.
=> [BOOTDATA][NTUSER] Add UserIsIMMEnabled and use it

win32ss/drivers/displays/vga/objects/screen.c, win32ss/drivers/miniport/vga/vgamp.c, win32ss/gdi/eng/device.c, win32ss/user/ntuser/display.h, win32ss/user/ntuser/ntuser.c, win32ss/win32kp.h
Prevent using both VGA driver and graphic card driver (vmx_svga.sys/bochsmp.sys/...) at the same time on the same card.
This will also prevent seeing two graphic cards (VGA + graphic card driver) in desk.cpl settings page.
JIRA issue: [CORE-18522](https://jira.reactos.org/browse/CORE-18522)
- When choosing the primary device, try to not select the VGA driver
- When using a graphic card driver, remove VGA driver from available drivers list so it is not used 
- When selecting VGA mode in freeldr, remove all drivers from available drivers list, except VGA one.
Also harmonize 640x480 mode index in VGA driver to 2, so it is the same value as in vga_new.
=> [WIN32SS] Do not use both VGA and graphic card driver at the same time

base/system/smss/pagefile.c, ntoskrnl/mm/pagefile.c
The commit log says it all:
[SMSS][NTOS:MM] Implement the architecture-specific pagefile size limits + code review.
What we have:
- Maximum number of pagefiles: 16
- Minimum pagefile size: 256 pages (1 MB when page size = 4096 bytes)
- Maximum pagefile size:
* 32-bit platforms: (1024 * 1024 - 1) pages (~ 4095 MB)
* x86 with PAE support: same size as for AMD x64
* x64 platform:  (4 * 1024 * 1024 * 1024 - 1) pages (~ 16 TB)
* IA64 platform: (8 * 1024 * 1024 * 1024 - 1) pages (~ 32 TB)
Those are the values as supported and verified by the NT kernel.
Now,  user-mode programs (including SMSS.EXE)  have different opinions
on these, namely, they consider estimates directly in MB, respectively:
4095 MB, (16 * 1024 * 1024) MB, and (32 * 1024 * 1024) MB
(verified on Win2k3 and Win7 32 and 64 bits). …
=> Pagefile review for SMSS and MM

dll/win32/comctl32/toolbar.c
This fixes the toolbar in FileZilla 3.8 being drawn wrong (grey) It regressed by 0.4.15-dev-1603-g 232c45fcd71b12a0d726b47f4a72e9a16f87432a
And todays fix is a partial revert of that guilty rev. The reverted part is not even necessarily needed for what we had in mind back then, it was just a first tiny step with the aim to get rid of the comctl32.h changes of that commit. But that goal was and even is far out of reach for many other reasons also. Actually we should have reverted the toolbar.c change back then already, before committing the "flipfix9".
Many thanks to JIRA user "julenuri" and "KrosUser" for their extensive testing.
JIRA issue: [CORE-18263](https://jira.reactos.org/browse/CORE-18263)
I could reproduce the issue with VBox4.3.12 with VBEMP graphics driver.
And do confirm the …
=> [COMCTL32] Remove a rosdiff TOOLBAR_EraseBackground()

base/applications/taskmgr/procpage.c
TaskMgr show context menu for all processes
In Win2K3, there is no context menu  on System Idle Process
JIRA issue: [CORE-18640](https://jira.reactos.org/browse/CORE-18640)
=> [TASKMGR] Prevent context menu on idle process CORE-18640

dll/win32/shell32/CDefaultContextMenu.cpp, dll/win32/shell32/dialogs/drive.cpp, dll/win32/shell32/folders/CDrivesFolder.cpp
Clicking on the Properties item in the drives context menu will open two Drives Properties dialogs one after the other.
CDefaultContextMenu::DoProperties provides a fallback call to property sheet testing the return value of the _DoCallback method, which is ultimately the return value of SH_ShowDriveProperties(...).
_Do Callback returns 0 (on error) and 1(on success), S_FALSE is defined as 1. 
https://jira.reactos.org/browse/CORE-18613
=> [SHELL32] Prevent a second call to  Drive Properties Dialog

ntoskrnl/config/cminit.c, ntoskrnl/config/cmwraprs.c
Our current CmpFileRead/CmpFileWrite do not wait for completion, so will cause stack corruption if used on files opened in async mode.
=> [NTOS:CM] Consistently use synchronous I/O for registry hives.

ntoskrnl/ke/amd64/interrupt.c
Implement `KeDisconnectInterrupt` for amd64.
- Implement `KeDisconnectInterrupt` for amd64
- Make `KeConnectInterrupt` lock the dispatcher lock
=> [NTOS:KE/x64] Implement KeDisconnectInterrupt for amd64

win32ss/gdi/ntgdi/font.h, win32ss/gdi/ntgdi/freetype.c
Simplify code and optimize for speed.
- Use `FT_Matrix` structure instead of `MATRIX` structure in `FONT_CACHE_ENTRY` structure.
- Delete `FtSetCoordinateTransform` and `SameScaleMatrix` helper functions.
- Use `FtMatrixFromMx` and `FT_Set_Transform` functions instead of `FtSetCoordinateTransform` function.
=> [NTGDI][FREETYPE] Font cache: Use FT_Matrix instead of MATRIX

dll/3rdparty/libxslt/Makefile.am, dll/3rdparty/libxslt/NEWS, dll/3rdparty/libxslt/functions.c, dll/3rdparty/libxslt/keys.c, dll/3rdparty/libxslt/numbers.c, dll/3rdparty/libxslt/pattern.c, dll/3rdparty/libxslt/transform.c, media/doc/3rd Party Files.txt, sdk/include/reactos/libs/libxml/xmlversion.h, sdk/include/reactos/libs/libxslt/xsltconfig.h, sdk/lib/3rdparty/libxml2/HTMLparser.c, sdk/lib/3rdparty/libxml2/NEWS, sdk/lib/3rdparty/libxml2/SAX2.c, sdk/lib/3rdparty/libxml2/config.h, sdk/lib/3rdparty/libxml2/entities.c, sdk/lib/3rdparty/libxml2/include/win32config.h, sdk/lib/3rdparty/libxml2/parser.c, sdk/lib/3rdparty/libxml2/tree.c, sdk/lib/3rdparty/libxml2/xpath.c
Part 3 of 3: this gets us to all the latest versions
Part 1 was here: https://github.com/reactos/reactos/pull/4890
Part 2 was here: https://github.com/reactos/reactos/pull/4894
JIRA issue: [CORE-17766](https://jira.reactos.org/browse/CORE-17766)
Sync scripts I used:
* libxml2: https://gist.github.com/ThFabba/ef1866e447d0c928f37643cfaddad8e3
* libxslt: https://gist.github.com/ThFabba/a6574d04b353e56bec7d07d613799bfc
Things to watch for:
* Check the "Improve sync with upstream" commits, since they make changes to ROS-diffs etc
* Check headers, especially config.h-type files
* Check for any unintentional changes to ROS-diffs (you can see all the ROS-diffs in my script, even though the sed/perl stuff is difficult to read)
* In libxslt, check `precomp.h`, which is entirely ours and has been …
=> [LIBXML][LIBXSLT] Sync to 2.10.3 / 1.1.37

win32ss/gdi/ntgdi/font.h, win32ss/gdi/ntgdi/freetype.c
Optimize the font rendering for speed.
- Modify `FONT_CACHE_ENTRY` structure to use hash.
- Add `IntGetHash` to calculate the hash of `FONT_CACHE_ENTRY`.
- Use hash in `ftGdiGlyphCacheGet` and `ftGdiGlyphCacheSet` functions.
- Reduce function call overheads by using `FONT_CACHE_ENTRY`, in getting glyph.
=> [NTGDI][FREETYPE] Font cache: Use hash

dll/win32/newdev/newdev.c, dll/win32/newdev/newdev_private.h, dll/win32/newdev/wizard.c, dll/win32/shell32/wine/brsfolder.c, dll/win32/syssetup/wizard.c
[NEWDEV] Enable Browser Dlg OK button, when driver is found
expected behavior:
When selecting a directory that contains a driver to update, the "OK" button in the browser dialog is activated when the requested driver is found. otherwise the "OK" button is disabled.
=> [NEWDEV][SHELL32][SYSSETUP] Enable Browser Dlg OK button, when driver is found

win32ss/gdi/ntgdi/freetype.c
Implement `LOGFONT.lfWidth` for `GetTextExtentPoint32`.
- Apply `LOGFONT.lfWidth` in `TextIntGetTextExtentPoint` function.
- Delete `XFORM` transformation in `TextIntGetTextExtentPoint` (to be simply ignored).
=> [NTGDI][FREETYPE] lfWidth for GetTextExtentPoint32

win32ss/gdi/ntgdi/font.h, win32ss/gdi/ntgdi/freetype.c
@HBelusca says a sub-structure of `FONT_CACHE_ENTRY` for hashing is wanted. 
https://github.com/reactos/reactos/commit/57702ed401b6736eeafedb5a5cf22536e74d531e#r91213473
- Add `FONT_CACHE_HASHED` structure and use it.
=> [NTGDI][FREETYPE] Add special structure for hashing

win32ss/gdi/eng/engobjects.h, win32ss/gdi/ntgdi/font.h, win32ss/gdi/ntgdi/freetype.c
Improve text/font rendering and metrics.
- Add `lfWidth` member into `FONTGDI` structure.
- Delete `IntWidthMatrix` function.
- Fix `IntRequestFontSize` behavior for processing `lfWidth` value.
- Apply `lfWidth` in `GetTextMetrics` and `GetCharWidth`.
- Ignore the `XFORM` values in `GetTextMetrics` and `GetCharWidth`.
=> [NTGDI][FREETYPE] lfWidth for GetTextMetrics and GetCharWidth

dll/win32/kernel32/client/file/mntpoint.c, modules/rostests/apitests/crt/strlen.c, modules/rostests/apitests/ws2_32/bind.c, ntoskrnl/ex/init.c, ntoskrnl/include/internal/ex.h, ntoskrnl/mm/ARM3/procsup.c, ntoskrnl/ob/oblife.c, win32ss/gdi/ntgdi/dibobj.c, win32ss/printing/base/spoolss/main.c
A bunch of random fixes that impact test runs for x64, but are also valid for x86.
- [CRT_APITEST] Restore direction flag to avoid false RTC break
- [WS2_32_APITEST] Fix uninitialized variable
- [KERNEL32] Fix a bug in GetVolumeNameForRoot
- [NTOS:EX] Initialize ExpTimeRefreshLock
- [WIN32K] Fix missing NULL check in IntCreateDIBitmap
- [NTOS] Improve MmCleanProcessAddressSpace
- [NTOS] Improve MmDeleteProcessAddressSpace
- [SPOOLSS] Fix prototype of BuildOtherNamesFromMachineName
- [NTOS] Fix double free on allocation failure in ObCreateObject
KVM: https://reactos.org/testman/compare.php?ids=85079,85082,85084,85087,85092
VBox: https://reactos.org/testman/compare.php?ids=85081,85083,85085,85088,85091
- gdi32:TextTransform: Difference due to updated test
- kernel32:QueueUserAPC: looks …
=> Random fixes

win32ss/gdi/ntgdi/freetype.c
Realize font/text transformation in correct and quick implementation. Retrial of PR #1207.
- Rename `ftGdiGetTextWidth` as `IntGetTextDisposition` and add a Y parameter.
- Add `RealYStart64` variable.
- Apply `lfEscapement` values (by multiplying matrices).
- Add `IntEngFillPolygon` and `IntEngFillBox` helper functions.
=> [NTGDI][FREETYPE] lfEscapement for TextOut

dll/shellext/sendmail/CDeskLinkDropHandler.cpp
- Set default working directory for shortcuts (except folders and zip files)
- Copy existing shortcut to the desktop if the source file is a shortcut
- Prevent destination file name collision
Notes: Verified on Windows XP SP3 and Windows 7 SP1.
Shortcut to EXE file (Before):
[ReactOS-sendto-before.webm](https://user-images.githubusercontent.com/86486978/204141743-0c683da0-04fc-4c5c-8aa5-6dc7bc5444ae.webm)
Shortcut to EXE file (After):
[ReactOS-sendto-after.webm](https://user-images.githubusercontent.com/86486978/204141767-8c38c888-2037-4f89-b38c-d3de0cd04874.webm)
=> [SENDMAIL] Fix Send To -> Desktop (create shortcut) behavior

drivers/base/kdgdb/kdpacket.c
Use cast to be compatible with "public" structure definition. (By "public" I understand that code could use MS PSDK wdbgexts.h definitions instead of our hacked version.)
Caught by @hpoussin :+1:
=> [KDGDB] Fix compilation following commit de81021ba

ntoskrnl/io/iomgr/file.c
Zero-initialize `FileObjectExtension` member of `FileObject` in `IopParseDevice` by passing the actual `ObjectSize` to `RtlZeroMemory` call, instead of `sizeof(FILE_OBJECT)` only. It allows to initialize `FileObjectExtension` members properly, such as `FilterContext` and `TopDeviceObjectHint`. Since they are deleted on file object deletion (in case it has an extension), they should also be initialized correctly on creation to avoid any failure(s).
It fixes an assert in `FsRtlPTeardownPerFileObjectContexts` and BAD_POOL_CALLER bugcheck for the apps which manage file object with an extension. For example, Kaspersky Anti-Virus 2012 installer. Now that installer fails with another issue.
JIRA issue: [CORE-18711](https://jira.reactos.org/browse/CORE-18711)
=> [NTOS:IO] Properly zero-initialize file object extension on file object creation

drivers/filesystems/btrfs/btrfs.inf
It is not imported into ReactOS.
Addendum to c8875c1 (0.4.13-dev-788) and 194ea90 (0.4.14-dev-1535).
- Comment out mkbtrfs.exe
=> [BTRFS] btrfs.inf: Comment out mkbtrfs.exe

dll/win32/shell32/folders/CControlPanelFolder.cpp, dll/win32/shell32/folders/CRegFolder.cpp
Current CControlPanelFolder::CompareIDs was using wrong lparam column index. Actual column index should be 1 instead of 4. Because of this the comment column next to name in details view was not being displayed in correct way. Please see below JIRA issues to see the bug in detail.
JIRA issue: 
[CORE-18743](https://jira.reactos.org/browse/CORE-18743)
[CORE-18501](https://jira.reactos.org/browse/CORE-18501)
=> [SHELL32] Fix detailed list views in control panel

dll/win32/shell32/folders/CDrivesFolder.cpp
Some CDs may set a custom label using autorun.inf. Read the label from the file, and if it succeeds, show it to the user.
JIRA issue: [CORE-18567](https://jira.reactos.org/browse/CORE-18567)
Add a function to read the `label` variable from autorun.inf and use it.
=> [SHELL32] Read the label for a CD from autorun.inf

win32ss/user/ntuser/winpos.c
Fix zombie window created by CTRL+ALT+DEL (Based on patch by [I_Kill_Bugs](https://jira.reactos.org/secure/ViewProfile.jspa?name=I_Kill_Bugs))
JIRA issue: [CORE-18258](https://jira.reactos.org/browse/CORE-18258)
- Don't send a HSHELL_WINDOWCREATED if the window is the desktop
=> [NTUSER] Fix zombie window created by CTRL+ALT+DEL

base/applications/dxdiag/lang/pt-BR.rc
Fix minor translation error.
JIRA issue: No IRA bug report
Replace the word "pperacional" (this doesn't exist in Portuguese language) by "operacional" .
Operating system in PT_BR is sistema operacional, not sistema ppracional.
=> [DXDIAG] Fix Portuguese (pt-BR) translation

base/applications/regedit/lang/pt-BR.rc
Improve translation for Favorites menu
Translation is missing for Favorites button
Replace the English word "Favorites" by the Portuguese word "Favoritos"
=> [REGEDIT] Fix missing translation for Favorites menu

ntoskrnl/ex/lookas.c, ntoskrnl/ke/i386/kiinit.c, ntoskrnl/ke/i386/thrdini.c, ntoskrnl/ke/krnlinit.c
This PR is mostly to get conversation going about all the small changes me and  @HBelusca 
discovered while using ReactOS with SMP support.
This is a draft as I may add more to it the coming days.
However:
This isn't every problem with the multiprocessor kernel it's only the small stuff that kills the BSP when its called by the other CPUs
- [NTOS] Swap MAXIMUM_PROCESSORS with NUMBER_POOL_LOOKASIDE_LISTS
- [NTOS] fix timer lock data and hardcode
- [NTOS] Increment ActiveProcessors accurately
- [NTOS] Set SwapBusy properly for i386
=> [NTOS] A list of Misc Changes needed to boot ReactOS with SMP

base/applications/mspaint/winproc.cpp
Our Paint allows user to try to set a .ico file as a wallpaper, which isn't possible. Different Windows versions have different behaviour, so it was decided that the simplest fix would be to just grey out "Set as wallpaper" buttons as in 2K3 (See the Jira ticket).
JIRA issue: [CORE-18661](https://jira.reactos.org/browse/CORE-18661)
Check the file extension and deactivate the buttons if needed.
=> [MSPAINT] Don't allow to set image as wallpaper if it has the wrong format

dll/shellext/ntobjshex/ntobjfolder.cpp, dll/shellext/ntobjshex/regfolder.cpp
This fixes crash when attempting to drag n drop items from NTObject Namespace and System Registry.
JIRA issues: [CORE-18480](https://jira.reactos.org/browse/CORE-18480), [CORE-18481](https://jira.reactos.org/browse/CORE-18481)
Perform a null check in GetInfoFromPidel on mkid in LPCITEMIDLIST
https://user-images.githubusercontent.com/120612254/208288691-a1cd6d4d-3afa-433c-9721-c3b3d9e1d7a1.mp4
(refer video, no more crash)
=> [NTOBJSHEX] Return early from GetInfoFromPidl when pcidl is null in LPCITEMIDLIST

sdk/lib/3rdparty/libwine/debug.c
Cf. comment https://jira.reactos.org/browse/CORE-18707?focusedCommentId=137342&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-137342
```
In file included from ../sdk/lib/3rdparty/libwine/debug_ros.c:9:
../sdk/lib/3rdparty/libwine/debug.c: In function 'get_temp_buffer':
../sdk/lib/3rdparty/libwine/debug.c:343:33: warning: passing argument 1 of '_InterlockedExchangeAdd' from incompatible pointer type [-Wincompatible-pointer-types]
idx = interlocked_xchg_add( &pos, 1 ) % (sizeof(list)/sizeof(list[0]));
^~~~
In file included from ../sdk/include/crt/mingw32/intrin.h:98,
from ../sdk/include/crt/intrin.h:1017,
from sdk/include/psdk/winnt.h:48,
from ../sdk/include/psdk/windef.h:202,
from ../sdk/include/reactos/wine/debug.h:26,
from …
```
=> [LIBWINE] Fix GCC build warning.

boot/bootdata/livecd.inf
This is what Windows does. And we forgot this location here. This is an addendum to
0.4.15-dev-5365-g 9bb5627df60392b90039266f277ff668b574b4cd [SETUP][INF] Use the standard "Helv" -> "MS Sans Serif" substitution... (#4864)
=> [BOOTDATA] Use the standard "Helv" -> "MS Sans Serif"

dll/win32/kernel32/client/proc.c, ntoskrnl/kd/kdio.c, ntoskrnl/kdbg/kdb.h, ntoskrnl/kdbg/kdb_cli.c, ntoskrnl/kdbg/kdb_keyboard.c, ntoskrnl/ps/kill.c, sdk/lib/rtl/assert.c
@julenuri noticed that debugger input is a bit "raw" when KD handles input for DbgPrompt() calls, and e.g. shows squares if backspaces are used, etc.:
Take also the opportunity to add other fixes.
- Validate DEBUG_IO API call.
- Take the LengthOfStringRead into account; use KdbpReadCommand() to read
the input, so that correct line edition is available (backspace, etc.)
For KdbpReadCommand():
- Don't read anything and return immediately if the buffer size is zero.
- Allow the controlling keys (up/down arrows, backspace) even if the
buffer is full! (especially backspace if too much has been written).
- Return the number of characters stored, not counting the NULL terminator.
=> KD/KDBG: Fix/improve KdbpReadCommand() and KdReceivePacket() for DBGKD_DEBUG_IO

media/doc/3rd Party Files.txt, media/themes/Blackshade/blackshade.msstyles/textfiles/ExtraLargeNormal.INI, media/themes/Lautus/lautus.msstyles/textfiles/ExtraLargeNormal.INI
Eliminates the last references to "Open Sans" font.
This is an addendum to ( 0.4.13-dev-765-g 04a361d091095a96bb3af376e46daf4c5fe81c63 )
and 0.4.14-dev-20-g 2f4fb903b46207ab380365908401ded63752a108
"Open Sans" has been replaced by "Trebuchet MS" back then.
=> [THEMES] "Open Sans" -> "Trebuchet MS"

ntoskrnl/mm/ARM3/sysldr.c
The `MmLoadSystemImage` function has a parameter called `IN PUNICODE_STRING NamePrefix OPTIONAL`. In the current ReactOS codebase, there's nowhere that this parameter is used. In Windows, this parameter is used in crash dump storage stack, where the special "crash mode" drivers would be loaded by kernel directly through MmLoadSystemImage, with a "dump_"(for crash dump)/"hiber_"(for hibernation) (see [reference post on OSR](https://community.osr.com/discussion/comment/97932/)).
When this parameter is specified, the actual driver's image to be loaded would be loaded under the prefixed name. The driver would appear in module list when running `lm` in WinDbg.
This isn't a urgently needed feature but I think it's better to have a solid foundation for my experiments on crash dump mechanism. And …
=> [NTOS:MM] Support image prefixing in MmLoadSystemImage

win32ss/gdi/ntgdi/freetype.c
Attempting to start DevExpress Ribbon Notepad makes crash ReactOS due to null pointer access, after some investigation, I found that `(face->charmap)` might return 0 sometimes, and we are not making this check.
This allows DevExpress Ribbon Notepad sample to start.
JIRA issue: [CORE-18091](https://jira.reactos.org/browse/CORE-18091) [CORE-18558](https://jira.reactos.org/browse/CORE-18558)
=> [NTGDI] Check if face->charmap is not zero before accessing its encoding

dll/win32/shell32/lang/de-DE.rc
English translation has its accelerators, the german ones were stripped
erroneously when this dlg was translated during 0.4.9-dev'ing.
I used the accelerators from my german WinXPSP3.
=> [SHELL32] Add 3 missing accelerators for IDM_DRAGFILE MENU in de-DE.rc

drivers/bus/pci/pdo.c
Fixes incorrect PCI IDE resources in VPC 2007.
Before:
```
[E1002948:1:1] IO: Min 0:FFA0, Max FFFFFFFF:FFFFFFAF, Align 1 Len FFFF0010
[E1002968:8:1] IO: Min 0:0, Max 0:FFFFFFFF, Align FFFF0010 Len FFFF0010
...
[E10563A0:1:1] MEM: Min 0:F8000000, Max FFFFFFFF:FBFFFFFF, Align 1 Len 4000000
[E10563C0:8:1] MEM: Min 0:0, Max 0:FFFFFFFF, Align 4000000 Len 4000000
```
After:
```
[E1002948:1:1] IO: Min 0:FFA0, Max 0:FFAF, Align 1 Len 10
[E1002968:8:1] IO: Min 0:0, Max 0:FFFFFFFF, Align 10 Len 10
...
[E10563A0:1:1] MEM: Min 0:F8000000, Max 0:FBFFFFFF, Align 1 Len 4000000
[E10563C0:8:1] MEM: Min 0:0, Max 0:FFFFFFFF, Align 4000000 Len 4000000
```
=> [PCI] Fix I/O range size of the resource descriptors

win32ss/user/ntuser/window.c
- Also check window state against `WNDS_DESTROYED`
See also: commit [https://github.com/reactos/reactos/commit/4d48b88bfbfcb6845e8742f78154156e984f6363](https://github.com/reactos/reactos/commit/4d48b88bfbfcb6845e8742f78154156e984f6363)
=> [WIN32K:NTUSER] ValidateHwndNoErr: Fix window handle validation

sdk/lib/atl/atlimage.h
Like MS ATL did, application won't be interrupted by ATLASSERT when failed to load image
JIRA issue: [CORE-18589](https://jira.reactos.org/browse/CORE-18589)
- CImage::Load() returns E_FAIL without ASSERT if failed to load image like MS ATL did
Open an invalid file in Paint:
Left (After this PR): Paint alerts the image cannot be loaded
Right (Before this PR): Paint interrupted by ATLASSERT
cooperated with KRosUser
=> [ATL] CImage::Load() returns E_FAIL without ATLASSERT if failed to load image

dll/win32/oleaut32/oleaut.c
Return proper value from OaBuildVersion 
JIRA issue: [CORE-18419](https://jira.reactos.org/browse/CORE-18419)
- Returns MAKELONG(0xffff, 50) for Win2K3 (and ReactOS)
- No useless FIXME output
=> [OLEAUT32] Return proper value from OaBuildVersion

modules/rostests/winetests/user32/msg.c, win32ss/user/ntuser/defwnd.c, win32ss/user/user32/windows/defwnd.c
Set WM_CONTEXTMENU's wParam to the child window's handle
JIRA issue: [CORE-18801](https://jira.reactos.org/browse/CORE-18801)
Cherry-picked from https://github.com/wine-mirror/wine/commit/3af8415ca9dc50e6c394c1001aad97db5f514069
=> [NTUSER][USER32] Set WM_CONTEXTMENU's wParam to the child window's handle

win32ss/user/ntuser/window.c
The guilty commit https://github.com/reactos/reactos/commit/a2c6af0da4acbba9c254d003e9d9f4ea6e03ed63 had enabled the IMM mode. So we should take care of the default IME windows. This PR will fix BSoD of `mplay32`.
JIRA issue: [CORE-18777](https://jira.reactos.org/browse/CORE-18777)
When the default IME window of the target window is to be destroyed, the target window does:
- Delete `(pti != NULL)` check.
- Check `(ti->spwndDefaultIme != Window)`.
- Check IME-like after `WNDS_DESTROYED` check.
CORE-18777 BEFORE:
CORE-18777 AFTER:
=> [NTUSER] Check IME-like after WNDS_DESTROYED check

sdk/lib/crt/misc/crt_init.c, sdk/lib/crt/wine/heap.c
Reduce differences of heap.c to wine (version 5.0rc5)
This basically reverts most of the nasty hacks that have been applied.
The goal is to make the file auto-syncable with the winesync script.
It also serves as a lesson for everyone how to make 3rd-party code compile and work without hacking every other line.
- Get back MSVCRT prefix
- Use the original wine heap functions
- Remove some unneccessary changes
- Add some functions from wine
- Sync some wine commits
https://reactos.org/testman/compare.php?ids=85614,85621,85626,85628,85630
=> Reduce crt heap diff

modules/rosapps/applications/screensavers/butterflies/butterflies.c, win32ss/gdi/gdi32/objects/bitmap.c
* Fix a memory leak in gdi32
* Fix the butterflies screensaver not to release the DC it passes to OpenGL
The screensaver now works smoothly in ROS, and without blowing up our memory manager.
JIRA issue: [CORE-18498](https://jira.reactos.org/browse/CORE-18498)
=> Fix butterflies screensaver

base/shell/explorer/traywnd.cpp, dll/win32/shell32/CCopyToMenu.cpp, dll/win32/shell32/CDefaultContextMenu.cpp, dll/win32/shell32/CMoveToMenu.cpp, dll/win32/shell32/CSendToMenu.cpp
JIRA issue: [CORE-16544](https://jira.reactos.org/browse/CORE-16544)
- Add `uFlags` argument to `CDefaultContextMenu::AddShellExtensionsToMenu`.
- `CCopyToMenu`, `CMoveToMenu`, and `CSendToMenu` check the `uFlags` against `(CMF_NOVERBS | CMF_VERBSONLY)`.
BEFORE:
AFTER:
=> [SHELL32] Improve StartButton context menu

win32ss/user/ntuser/window.c
Fix hung-up in some applications on IME window creation.
JIRA issue:
[CORE-18723](https://jira.reactos.org/browse/CORE-18723)
[CORE-18754](https://jira.reactos.org/browse/CORE-18754)
[CORE-18773](https://jira.reactos.org/browse/CORE-18773)
[CORE-18785](https://jira.reactos.org/browse/CORE-18785)
[CORE-18802](https://jira.reactos.org/browse/CORE-18802)
[CORE-18803](https://jira.reactos.org/browse/CORE-18803)
- Move the code that creates the default IME window, from `IntCreateWindow` to `co_UserCreateWindowEx`, just before sending `WM_NCCALCSIZE` message.
=> [NTUSER] Move IME window creation code

win32ss/user/ntuser/winpos.c
Thanks to the hard work of I_Kill_Bugs and Simone, I would like to propose this fix or workaround for the bugs that appears in elements rendered that include hyperlinks and images at the same time. I'm not skilled enough to call them preciselly, but after some investigations, I take 3 conclusions: 
1st, the elements are rendered once and again fighting with other rendered elements, that cause that flickering. 
2nd, that rendering causes malfunction in the whole software rendering, causing a near 99% of CPU use.
3rd, some of them are being rendered over other windows, and if we minimize it, the GUI of the software will become responsible.
Fails detected:
(SWP_NOMOVE | SWP_NOZORDER | SWP_NOACTIVATE) is from VC2008
(SWP_NOZORDER) is from CPUZ
(SWP_NOZORDER and SWP_NOSIZE) from API Monitor …
=> [NTUSER] Fix winpos bug hyperlink&images loop redrawing (CORE-7652)

dll/win32/riched20/string.c
Fix the hyperlink on Chinese Rapps.
JIRA issue: [CORE-17091](https://jira.reactos.org/browse/CORE-17091)
- Check punctuation in the word break procedure by using `iswpunct` function.
BEFORE:
Hyperlink was wrong.
AFTER:
Fixed.
BEFORE:
Hyperlink is wrong.
AFTER:
Fixed.
=> [RICHED20] Fix word break procedure for punct

media/doc/3rd Party Files.txt, sdk/include/reactos/libs/zlib/zconf.h, sdk/include/reactos/libs/zlib/zlib.h, sdk/lib/3rdparty/zlib/ChangeLog, sdk/lib/3rdparty/zlib/LICENSE, sdk/lib/3rdparty/zlib/Makefile.in, sdk/lib/3rdparty/zlib/README, sdk/lib/3rdparty/zlib/compress.c, sdk/lib/3rdparty/zlib/configure, sdk/lib/3rdparty/zlib/contrib/minizip/crypt.h, sdk/lib/3rdparty/zlib/contrib/minizip/ioapi.c, sdk/lib/3rdparty/zlib/contrib/minizip/ioapi.h, sdk/lib/3rdparty/zlib/contrib/minizip/iowin32.c, sdk/lib/3rdparty/zlib/contrib/minizip/unzip.c, sdk/lib/3rdparty/zlib/contrib/minizip/zip.c, sdk/lib/3rdparty/zlib/crc32.c, sdk/lib/3rdparty/zlib/deflate.c, sdk/lib/3rdparty/zlib/deflate.h, sdk/lib/3rdparty/zlib/gzlib.c, sdk/lib/3rdparty/zlib/gzread.c, sdk/lib/3rdparty/zlib/gzwrite.c, sdk/lib/3rdparty/zlib/infback.c, sdk/lib/3rdparty/zlib/inflate.c, sdk/lib/3rdparty/zlib/inftrees.c, sdk/lib/3rdparty/zlib/inftrees.h, sdk/lib/3rdparty/zlib/trees.c, sdk/lib/3rdparty/zlib/uncompr.c, sdk/lib/3rdparty/zlib/zutil.c, sdk/lib/3rdparty/zlib/zutil.h
Updated zlib to v1.2.13 from v1.2.12.
Added 3rd party minizip LICENSE file.
JIRA issue: [CORE-18752](https://jira.reactos.org/browse/CORE-18752)
Source : https://github.com/madler/zlib/tree/04f42ceca40f73e2978b50e93806c2a18c1281fc
I have restored and disabled some of the code in ``zconf.h`` that defined ``WIN32_LEAN_AND_MEAN``.
I just tested it quickly and it seems to work fine, but I don't know if I should restore it completely or leave it disabled.
- Fix configure issue that discarded provided CC definition
- Correct incorrect inputs provided to the CRC functions
- Repair prototypes and exporting of new CRC functions
- Fix inflateBack to detect invalid input with distances too far
- Have infback() deliver all of the available output up to any error
- Fix a bug when getting a gzip header …
=> [ZLIB] Update to v1.2.13. CORE-18752

base/applications/notepad/dialog.c, base/applications/notepad/main.h, base/applications/notepad/text.c
JIRA issue: [CORE-14641](https://jira.reactos.org/browse/CORE-14641)
- Use `EM_GETHANDLE`/`EM_SETHANDLE` message to get/set the internal buffer handle.
- Use `LocalReAlloc` to re-allocate the buffer.
- Use file mapping to speed up loading.
- Use also `IS_TEXT_UNICODE_REVERSE_STATISTICS` for `IsTextUnicode`.
=> [NOTEPAD] Speed up notepad loading

sdk/lib/crt/wine/except_i386.c, sdk/lib/crt/wine/heap.c, sdk/lib/crt/wine/msvcrt.h, sdk/lib/crt/wine/undname.c
Reduce diff between crt wine code and wine-5.0-rc5
- Remove white space changes
- Merge a number of missing commits
Rightmost 2 are this PR
KVM: https://reactos.org/testman/compare.php?ids=85666,85673,85682,85678,85681
VBox: https://reactos.org/testman/compare.php?ids=85667,85671,85683,85679,85680
=> Reduce diff of wine crt code to wine-5.0-rc5

modules/rostests/winetests/userenv/userenv.c
=> [USERENV_WINETEST] Compare variable case insensitive

dll/win32/browseui/addresseditbox.cpp, dll/win32/browseui/addresseditbox.h
If the user could execute a command line from address bar, usability will improve.
JIRA issue: [CORE-15453](https://jira.reactos.org/browse/CORE-15453)
- Add `CAddressEditBox::GetAbsolutePidl` and `CAddressEditBox::GetComboBoxText` helper functions.
- Add `CAddressEditBox::ExecuteCommandLine` function to execute the command line.
- And use them.
BEFORE:
Cannot execute from address bar.
Able to execute a command line from address bar.
=> [BROWSEUI] Execute command line from address bar

dll/win32/shell32/shlexec.cpp
`SEE_MASK_UNICODE` (0x00004000) does nothing, so we needn't mark it as "unsupported flag" and output FIXME
- `SEE_MASK_UNICODE` does nothing, see MS DevBlogs: [What does the SEE_MASK_UNICODE flag in ShellExecuteEx actually do?](https://devblogs.microsoft.com/oldnewthing/20140227-00/?p=1643)
- Corresponding FIXME output can be found in [CORE-18050](https://jira.reactos.org/browse/CORE-18050), the first line of log: `fixme:(dll/win32/shell32/shlexec.cpp:1934) flags ignored: 0x00004000`. **This PR is not for this ticket, but the FIXME output can be found in this ticket**
- No `fixme:(dll/win32/shell32/shlexec.cpp:1934) flags ignored: 0x00004000` output
=> [SHELL32] Ignore unused flag SEE_MASK_UNICODE

dll/win32/kernel32/client/path.c, dll/win32/shell32/shlexec.cpp, dll/win32/shlwapi/path.c
When no extension is provided, add default extension with correct precedence
using PathFileExistsDefExtW.
Use PathFindOnPathExW when searching in current directory and PATH environment variable
Fix Width String terminator to UNICODE_NULL
Fix all failed tests on PathFindPathExW KVM test
JIRA issue: [CORE-17612](https://jira.reactos.org/browse/CORE-17612)
=> [SHLWAPI] No need extension to execute '.bat' files CORE-17612

win32ss/user/ntuser/scrollbar.c
* fixes JIRA issue: [CORE-18050](https://jira.reactos.org/browse/CORE-18050)
* improves the code by removing ancient hacks
* reduces testbot failures
VBox: https://reactos.org/testman/compare.php?ids=85831,85832 LGTM (-2 failures in user32:scroll for both bots)
KVM: https://reactos.org/testman/compare.php?ids=85829,85833 LGTM (-2 failures in user32:scroll for both bots)
* co-authored by @Doug-Lyons . Many thanks for his contributions in the 2nd commit. Extremely valuable addition!
Back when we committed
0.4.14-dev-1134-g 00adb1a3f967ac7f5cd56b4c39df72a7b3814603
we massively improved for the unthemed painting of scrollbars. Unfortunately that introduced a few glitches with themed scrollbars, so we had to commit some follow-ups, beginning with the good idea:
0.4.15-dev-3086-g …
=> [NTUSER] Delete temporary workarounds in co_IntSetScrollInfo()

dll/win32/mshtml/olecmd.c
When using wine internet explorer it crashes if you click print even if you click cancel, this fixes that issue.
nsIWebBrowserPrint_Print apparently causes issues for unknown reasons.
JIRA issue: [CORE-16884](https://jira.reactos.org/browse/CORE-16884)
By returning S_OK print doesn't cause a crash.
Use ERR and S_OK return before hitting nsIWebBrowserPrint_Print
Created to replace https://github.com/reactos/reactos/pull/4967 which seems to be abandoned.
=> [MSHTML] Wine internet explorer print crash fix

win32ss/user/ntuser/winpos.c
_Fix for right-clicking on 'My Computer' and selecting 'explore' and there is no 'X' for the title bar in the Folders pane_
_Also fixes Rapps missing toolbar combo box and edit box controls that were not displayed._
JIRA issue: [CORE-18830](https://jira.reactos.org/browse/CORE-18830)
[CORE-18817](https://jira.reactos.org/browse/CORE-18817)
_This is a new patch from User I_Kill_Bugs as provided in https://jira.reactos.org/browse/CORE-18817_
This is a complete revert of https://github.com/reactos/reactos/pull/4995 and still retains its fixes.
=> [NTUSER] Missing "X" on "Folder" pane when Right Click > Explore from Desktop icons & Rapps toolbar errors

dll/win32/browseui/explorerband.cpp, dll/win32/browseui/explorerband.h
JIRA issue: [CORE-18646](https://jira.reactos.org/browse/CORE-18646)
Tested issuing a backspace while editing multiple folder names: No crash
Suspected Duplicates:
[CORE-18504](https://jira.reactos.org/browse/CORE-18504) Tested right clicking on left panel folders: No crash
[CORE-18746](https://jira.reactos.org/browse/CORE-18746) Tried renaming Recycle Bin: No crash
=> [EXPLORER] Crash on backspace while editing folder panel

sdk/lib/crt/printf/streamout.c
`"%zu"` is a `printf` format specifier for type `size_t`. Some apps assume the implementation of this specifier.
JIRA issue: [CORE-17787](https://jira.reactos.org/browse/CORE-17787)
BEFORE:
AFTER:
=> [CRT] printf/wprintf: Support %zu

win32ss/user/ntuser/window.c
- Fix `ASSERT(pWnd->spwndOwner == Window)` in `IntDestroyOwnedWindows`.
- Also remove window owner check hack in `IntShowOwnedPopups`.
Based on my observation, the owner of the default IME window can change and it depends on the window that is being focused.
JIRA issue: [CORE-18659](https://jira.reactos.org/browse/CORE-18659) [CORE-18768](https://jira.reactos.org/browse/CORE-18768)
=> [NTUSER] IntWinListOwnedPopups: Exclude default IME window from the list

win32ss/user/ntuser/defwnd.c, win32ss/user/ntuser/nonclient.c
I experimented with porting back the code-changes of (#5014) locally and while doing so,
I saw that it can be optimized a lot for the case that Window Snapping is turned off:
In defwnd.c we can save a call to UserGetForegroundWindow(), a call to UserGetWindowObject(hwndTop), assignments, ifs, traces.
In nonclient.c we can save a call to UserSystemParametersInfo(), assignments, ifs, traces.
In nonclient.c we are within a tight for(;;) even!
And I also think the code is much more readable like that,
as it separates the Window-Snapped-paths much leaner from the non-Window-Snapped-paths.
That gets very obvious when having a look again at the initial commit that introduced Window-Snapping:
https://github.com/reactos/reactos/commit/7e396787ed00a3939031447725f79697a41878e1
We can see that its …
=> [NTUSER] Optimize Window Snap Disabling

base/applications/notepad/dialog.c, base/applications/notepad/dialog.h, base/applications/notepad/main.c, base/applications/notepad/settings.c
Notepad's status bar was not working by some reasons. And I want to simplify Notepad code.
- Rename `DoCreateStatusBar` as `DoShowHideStatusBar`.
- The code re-arranging the controls is moved to `WM_SIZE` handler. This makes the code much simpler.
- Improve `WM_SIZE` handler.
- Enable/disable `CMD_STATUSBAR` menu item correctly.
- Make `DoShowHideStatusBar` independent from `DoCreateEditWindow`.
=> [NOTEPAD] Fix and simplify Status Bar handling

dll/win32/browseui/addresseditbox.cpp, dll/win32/browseui/addresseditbox.h
Follow-up of #5026 `[BROWSEUI] Execute command line from address bar`.
Elegantly reset the address bar after command line execution.
JIRA issue: [CORE-15453](https://jira.reactos.org/browse/CORE-15453)
- Move the code of `CAddressEditBox::Invoke` into newly-defined `CAddressEditBox::RefreshAddress` function.
- Use `CAddressEditBox::RefreshAddress`.
=> [BROWSEUI] Add CAddressEditBox::RefreshAddress and use it

drivers/network/tcpip/ip/transport/tcp/accept.c, drivers/network/tcpip/ip/transport/tcp/tcp.c, drivers/network/tcpip/tcpip/fileobjs.c
Do not declare 0XFFFF as invalid in ReactOS. Applications should be able to use 0XFFFF as it is valid. Thanks to @KRosUser for detailed analysis.
JIRA issue:
[CORE-18371](https://jira.reactos.org/browse/CORE-18371)
[CORE-18764](https://jira.reactos.org/browse/CORE-18764)
The proposed fix is similar to what is already implemented in ReactOS for existing TCPAlloc failure in [FileOpenAddress](https://git.reactos.org/?p=reactos.git;a=blob;f=drivers/network/tcpip/tcpip/fileobjs.c#l475)
This PR replaces https://github.com/reactos/reactos/pull/4968 for which the creator has been inactive for over a month.
=> [IP] Allow 0xFFFF as Valid Network Port Number

dll/win32/mciavi32/mmoutput.c
Opening Empty files in Mediaplayer leads to a crash
JIRA issue: [CORE-18669](https://jira.reactos.org/browse/CORE-18669)
=> [MCIAVI32] Media Player: Don't open empty files

dll/cpl/sysdm/lang/fr-FR.rc
Updated sysdm french translation (``dll\cpl\sysdm\lang\fr-FR.rc``).
Based on #4704
Fixed alignment for too long text.
Improved translation.
Minor adjustments.
JIRA issue: [CORE-18381](https://jira.reactos.org/browse/CORE-18381)
=> [SYSDM] Fix french translation and layout

sdk/lib/atl/atlbase.h
This retry does not happen in the native ATL, so we should not do it either.
=> [ATL] Remove some code that doesn't exist in the native ATL

dll/win32/mciavi32/mmoutput.c
`#ifdef` guard was missed as part of the previous (PR)(https://github.com/reactos/reactos/pull/5063)
=> [MCIAVI32] Add ifdef guards to prevent regression

base/setup/usetup/consup.c
When watching ReactOS Setup, I found the status text appeared to be flickering.
JIRA issue: [CORE-18838](https://jira.reactos.org/browse/CORE-18838)
- Get more speed by omitting erasing and overwriting whole line.
```txt
(base/setup/usetup/consup.c:90) CONSOLE_SetStatusTextXV: 52333248
(base/setup/usetup/consup.c:103) CONSOLE_SetStatusTextXV_Improved: 43486080
```
+17% speed up in `CONSOLE_SetStatusTextXV`.
=> [USETUP] Speed up CONSOLE_SetStatusTextXV +17%

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/shlwapi.spec, dll/win32/shlwapi/string.c, modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/SHLoadRegUIString.c, modules/rostests/apitests/shlwapi/testlist.c
`shlwapi!SHLoadIndirectString` function seems expanding the environment variable strings.
Split from https://github.com/reactos/reactos/pull/4929.
- `shlwapi!SHLoadIndirectString` expands the environmental strings if the first character was `'@'`.
- Implement `SHLoadRegUIStringA` function.
=> [SHLWAPI][SHLWAPI_APITEST] Expand string in SHLoadIndirectString

base/applications/notepad/main.c, base/applications/notepad/main.h, base/applications/notepad/settings.c
If there is the target registry key and the settings are incomplete, then the settings would become the middle status. This PR will avoid this status.
- Avoid buffer overrun in `QueryString` helper function.
- Improve `NOTEPAD_LoadSettingsFromRegistry` function.
=> [NOTEPAD] Avoid middle status of settings

win32ss/user/ntuser/winpos.c
Send `WM_IME_SYSTEM:IMS_UPDATEIMEUI` message after window position change to improve IME UI sync.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-15289](https://jira.reactos.org/browse/CORE-15289)
- `WM_IME_SYSTEM == 0x287`.
- `IMS_UPDATEIMEUI == 0x6`.
- Add `IntImeWindowPosChanged` helper function.
- Use `IntImeWindowPosChanged` on IMM mode after window position change.
`WM_IME_SYSTEM:IMS_UPDATEIMEUI` is correctly sent to the Default IME window of Notepad on moving the main window (`WM_647 == WM_IME_SYSTEM`).
Win10 x64 Japanse:
`WM_IME_SYSTEM:IMS_UPDATEIMEUI` is correctly sent to the Default IME window of Notepad on moving the main window.
Win2k3 English:
`WM_IME_SYSTEM:IMS_UPDATEIMEUI` is correctly sent to the Default IME window of Notepad on …
=> [NTUSER] Send WM_IME_SYSTEM:IMS_UPDATEIMEUI

dll/win32/syssetup/syssetup.rc
The url was outdated and redirected to the new qemu website.
Should it be kept in credits?
JIRA issue: [CORE-18495](https://jira.reactos.org/browse/CORE-18495)
- Change url for QEMU credits
=> [SYSSETUP] Changed credit link for qemu.

dll/win32/imm32/compstr.c
- Fix some typos in `Imm32GetCompStrA/W`.
=> [IMM32] Fix ImmGetCompositionStringA/W

win32ss/user/user32/misc/exticon.c
_Fix explorer crashing when trying to display icon for file with bad EXE with a bad PE header._
JIRA issue: [CORE-15879](https://jira.reactos.org/browse/CORE-15879)
_Modify ICO_ExtractIsonExW to check for trying to read data past end of file and exit._
Crredit: @ThFabba in ReactOS chat
=> [USER32] Fix ICO_ExtractIconExW causing explorer to crash on bad PE header icon display

base/applications/notepad/main.c
The whole-word search of Notepad had a bug around punctuation. For example, the text `"Windows"` didn't match in the text `"MS-DOS,Windows,ReactOS"`.
- Use `_istalnum` instead of `_istspace`.
- Fix the position to check.
`_istalnum` matches an alphabet letter or numeric digit.
=> [NOTEPAD] Fix NOTEPAD_FindTextAt

base/applications/notepad/dialog.c
We don't want to reset the status of the checkboxes even if the Find/Replace dialog was closed.
- If `lpstrFindWhat` is set, do not reset the Find/Replace settings at `DIALOG_SearchDialog`.
=> [NOTEPAD] Don't reset Find/Replace if lpstrFindWhat is set

win32ss/include/ntuser.h, win32ss/user/ntuser/kbdlayout.c, win32ss/user/ntuser/window.h, win32ss/user/user32/windows/input.c
- Split some code of `NtUserLoadKeyboardLayoutEx` to newly-added `co_IntLoadKeyboardLayoutEx` helper function.
- Modify `NtUserLoadKeyboardLayoutEx` prototype.
- Move `co_UserImmLoadLayout` code.
- Implement `KLF_REORDER`.
- Rename `UserLoadKbdLayout` as `co_UserLoadKbdLayout`.
- Improve `LoadKeyboardLayoutEx`.
=> [NTUSER][USER32] Refactor NtUserLoadKeyboardLayoutEx

base/applications/mspaint/dib.cpp
JIRA issue: [CORE-18508](https://jira.reactos.org/browse/CORE-18508)
Currently if a file is empty, while loading the file the global variable isAFile is set as FALSE.
This leads to a save as dialogue while saving thinking that no file is loaded
=> [MSPAINT] Treat as a file even if the bitmap is empty

ntoskrnl/include/internal/se.h, ntoskrnl/include/internal/tag.h, ntoskrnl/se/accesschk.c, ntoskrnl/se/debug.c
Access check is an expensive operation, that is, whenever an access to an object is performed an access check has to be done to ensure the access can be allowed to the calling thread who attempts to access such object.
Currently `SepAnalyzeAcesFromDacl` allocates a block of pool memory for access check rights, nagging the Memory Manager like a desperate naughty creep. So instead initialize the access rights as a simple variable in `SepAccessCheck` and pass it out as an address to `SepAnalyzeAcesFromDacl `so that the function will fill it up with access rights. This helps with performance, avoiding wasting a few bits of memory just to hold these access rights.
In addition to that, add a few asserts and fix the copyright header on both `se.h` and `accesschk.c,` to reflect the Coding Style …
=> [NTOS:SE] Do not allocate memory pool just for the access rights

win32ss/user/user32/controls/edit.c
wine commit id f62d8dc58fb3fb5f11a8ab55620ab9b2fbdaf967 by Nikolay Sivov <nsivov@codeweavers.com>
Fixes crash in user32:edit
=> [WINESYNC] user32/edit: Allow buffer access after EM_GETHANDLE.

dll/win32/msafd/misc/dllmain.c
_Fix hang of winetest ws2_32:sock caused by revision 0.4.12-dev-693-g2b1f6c8._
JIRA issue: [CORE-18848](https://jira.reactos.org/browse/CORE-18848)
_Revert some minor return value changes by Pierre Schweitzer for CORE-14966 which affects msafd.dll._
It appears that he attempted to improve Steam installs, but was unsuccessful to make the install run with this commit:
https://github.com/reactos/reactos/commit/2b1f6c8b0d73b80c9aeaf8808c66c0c52eb1f320
This seemed intended to only stub some functions, but the new return values caused the ws2_32:sock test to hang.
Therefore, it should not be too dangerous to revert the return values of his changes.
My intent is to reduce the test errors by reverting to the original return values when the 'sock' test worked.
This way a minimum of the current …
=> [MSAFD] Work around regression of CORE-18848 from 0.4.12-dev-693-g2b1f6c8

base/applications/notepad/dialog.c
Fix handle leak.
- Use `DestroyIcon` function instead of `DeleteObject` to destroy `notepadIcon` at `DIALOG_HelpAboutNotepad`.
=> [NOTEPAD] Use DestroyIcon instead of DeleteObject to destroy icon

dll/win32/kernel32/client/virtmem.c
This SEH wraps a syscall only, seems pointless and should be removed
Remove this SEH
=> [KERNEL32] Remove a pointless SEH in VirtualAllocEx

base/applications/notepad/dialog.c
Improving UI/UX by making `Globals.hMainWnd` the owner of the message box.
- Use `Globals.hMainWnd` variable in `ShowLastError` function.
BEFORE: Try to open a folder by dragging & dropping.
Since the owner of the messsage box was `NULL`, the message box could be overlapped by the main window.
=> [NOTEPAD] Use Globals.hMainWnd in ShowLastError

base/applications/dxdiag/lang/de-DE.rc
Fixes a text truncation on the last tab
JIRA issue: [CORE-18853](https://jira.reactos.org/browse/CORE-18853)
See before-and-after-pic within the JIRA-ticket
=> [DXDIAG] Fix text truncation german de-DE.rc CORE-18853

base/applications/mspaint/winproc.cpp
There was an exception in starting up of `mspaint` of Visual Studio 2019 build.
JIRA issue: [CORE-18594](https://jira.reactos.org/browse/CORE-18594), [CORE-18867](https://jira.reactos.org/browse/CORE-18867)
- Fix `"Use of uninitialized variable statusBarRect0"` exception in `CMainWindow::alignChildrenToMainWindow`.
=> [MSPAINT] Fix use of uninitialized variable on startup

base/applications/mspaint/toolbox.h
There were two "main" windows in our `mspaint`.
BEFORE:
Our `mspaint` had two windows of window class `"MainWindow"`.
AFTER:
One has been fixed as window class `"ToolBox"`.
- class `CToolBox` should inherit `CWindowImpl<CToolBox>` instead of `CWindowImpl<CMainWindow>`.
=> [MSPAINT] There were two "main" windows

ntoskrnl/include/internal/kd.h, ntoskrnl/kd/kdio.c, ntoskrnl/kdbg/kdb_cli.c
The dmesg command is now available even if screen output is disabled.
JIRA issue: [CORE-10749](https://jira.reactos.org/browse/CORE-10749)
----
Commit isolated from https://github.com/reactos/reactos/pull/4600/commits/aeb843e01476f104c0e5ac5c6214a2673275a15a of PR #4600 (branch "CORE-10749"), cleaned up and rebased on top of master.
=> [NTOS:KD] Move handling of Dmesg buffer from screen provider to KDBG provider.

ntoskrnl/include/internal/kd.h, ntoskrnl/io/iomgr/iomgr.c, ntoskrnl/kd/kdio.c, ntoskrnl/kd/kdmain.c, ntoskrnl/kdbg/kdb.h, ntoskrnl/kdbg/kdb_cli.c
Fix the way how (and when) we initialize KD(BG) functionality that depends on the NT I/O Manager to be up & running.
This includes, creating the debug log file + its thread, and for KDBG, loading the KDBinit file.
JIRA issue: [CORE-17470](https://jira.reactos.org/browse/CORE-17470)
**_NOTE: A hack for fixing FILE_APPEND_DATA support appears to be needed, because ReactOS doesn't fully honour it (files get overwritten instead). This will potentially be fixed in a separate PR, see [CORE-18789](https://jira.reactos.org/browse/CORE-18789)_**
Remove the ReactOS-specific (NT-incompatible) callback we do in the middle of IoInitSystem(), for a runtime mechanism that should work on Windows as well.
The idea of the new mechanism is loosely inspired by the TDL4 rootkit :sunglasses: …
=> [NTOS:KD][KDBG] Rework the BootPhase >= 2 initialization of the KD/KDBG kernel debugger.

base/applications/mspaint/main.cpp, base/applications/mspaint/registry.cpp, base/applications/mspaint/registry.h, base/applications/mspaint/winproc.cpp
Some users might want to keep the status bar hidden.
- Add `ShowStatusBar` registry setting.
- Save `ShowStatusBar` status and restore the status on startup.
=> [MSPAINT] Remember status bar visibility

win32ss/user/ntuser/kbdlayout.c, win32ss/user/user32/windows/defwnd.c
Supporting `KLF_SETFORPROCESS` flag in `ActivateKeyboardLayout` function.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-10667](https://jira.reactos.org/browse/CORE-10667)
- Implement `KLF_SETFORPROCESS` for `co_UserActivateKeyboardLayout`.
- Use `KLF_SETFORPROCESS` flag in `WM_INPUTLANGCHANGEREQUEST` handling.
- Add `co_IntSetKeyboardLayoutForProcess` helper function.
=> [NTUSER][USER32] KLF_SETFORPROCESS for ActivateKeyboardLayout

base/applications/notepad/main.c
We can borrow the power of CRT debug.
These changes are effective for debug version only.
- Insert `#include <crtdbg.h>` at `main.c`.
- Call `_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF)` at the prologue of `_tWinMain`.
- `_CrtSetDbgFlag` function: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/crtsetdbgflag?view=msvc-170
=> [NOTEPAD] Use _CrtSetDbgFlag to check memory leak

dll/win32/shell32/CDefView.cpp, dll/win32/shell32/CDefaultContextMenu.cpp, dll/win32/shell32/CNewMenu.cpp
Revert the hack from commit ed4b16b7f (PR #4950).
Real fix to this issue.
The CNewMenu::SelectNewItem method starts with a request to notify the View object about a new item by calling SHChangeNotify. After creating and obtaining the new PIDL by calling ILFindLastID, the CDefView::SelectItem method is called. This method fails right from the start when calling LV_FindItemByPidl which returns -1, thus preventing the user from being given the opportunity to change the name displayed by default.
This failure is due to the fact that this object has not yet been added to the CDefView::m_ListView. For some reason the call to SHChangeNotify did not call CDefView::OnChangeNotify with eventID SHCNE_CREATE.
Thanks to @yagoulas  by the big help.
=> [SHELL32] Give opportunity to rename file/folder on its creation

base/applications/regedit/find.c
_Fix crashes in regedit-find._
JIRA issue: [CORE-15986](https://jira.reactos.org/browse/CORE-15986)
JIRA issue: [CORE-18230](https://jira.reactos.org/browse/CORE-18230)
_After possible RegQueryValueExW append 3 zero bytes to guarantee that we will end with a UNICODE NULL._
=> [REGEDIT] Fix crashes in regedit-find affecting CORE-15986 and CORE-18230

base/applications/notepad/main.c
JIRA issue: [CORE-18259](https://jira.reactos.org/browse/CORE-18259), [CORE-18837](https://jira.reactos.org/browse/CORE-18837)
- In `HandleCommandLine` function, use `GetFullPathName` API to get the full path of a non-existent file.
=> [NOTEPAD] Use full path for non-existent file

base/applications/mspaint/main.cpp, base/applications/mspaint/registry.cpp, base/applications/mspaint/registry.h, base/applications/mspaint/winproc.cpp
Our `mspaint` didn't remember the maximized status of the main window.
- Initialize `RegistrySettings::WindowPlacement` correctly.
- Fix `mainWindowPos` values.
- Add `nCmdShow` parameter to `RegistrySettings::Load` and `RegistrySettings::LoadPresets`.
- Use `registrySettings.WindowPlacement.showCmd` for `ShowWindow` call.
=> [MSPAINT] Restore the main window saved show state

base/applications/mspaint/globalvar.h, base/applications/mspaint/imgarea.cpp, base/applications/mspaint/main.cpp, base/applications/mspaint/scrollbox.cpp, base/applications/mspaint/scrollbox.h, base/applications/mspaint/selection.cpp
BEFORE:
AFTER:
- Remove `scrlClientWindow` and simplify.
=> [MSPAINT] Remove extra scrlClientWindow

base/applications/mspaint/main.cpp, base/applications/mspaint/registry.cpp, base/applications/mspaint/registry.h, base/applications/mspaint/winproc.cpp
Allow the user to save the showing/hiding status of the palette window.
According to my registry analysis, `HKCU\Software\Microsoft\Windows\CurrentVersion\Applets\Paint\General-Bar4:Visible` is the target value.
- Improve `ReadDWORD` helper function.
- Add `ShowPalette` registry setting.
- Save the visibility on exit, and load the visibility on startup.
- Simplify `RegistrySettings::Load` and `RegistrySettings::Store`.
=> [MSPAINT] Save paletteWindow visibility

sdk/include/ddk/xfilter.h
`ff:ff:ff:ff:ff:ff` is the broadcast MAC address.
JIRA issue: [CORE-8724](https://jira.reactos.org/browse/CORE-8724)
=> [DDK:NDIS] Fix definition of broadcast address macro

boot/freeldr/freeldr/CMakeLists.txt, boot/freeldr/freeldr/arch/amd64/entry.S, boot/freeldr/freeldr/arch/amd64/misc.S, boot/freeldr/freeldr/pcat.cmake
Move platform-specific build targets into dedicated .cmake files.
Future UEFI port will use such layout.
Prerequisite for PR #5128 
```
[FREELDR] Move common x64 runtime-specific ASM helpers to a misc file.
```
and
```
[FREELDR] Move platform-specific build targets into dedicated .cmake files.
- Keep the common definitions and  file lists in CMakeLists.txt
- Move PC-AT & compatibles (PC-98, XBOX) definitions in pcat.cmake
- Future UEFI-specific definitions will be in an uefi.cmake
```
=> Freeldr - Preparation for UEFI

boot/boot_images.cmake, boot/freeldr/freeldr/CMakeLists.txt, boot/freeldr/freeldr/arch/uefi/stubs.c, boot/freeldr/freeldr/arch/uefi/ueficon.c, boot/freeldr/freeldr/arch/uefi/uefildr.c, boot/freeldr/freeldr/arch/uefi/uefisetup.c, boot/freeldr/freeldr/arch/uefi/uefiutil.c, boot/freeldr/freeldr/arch/uefi/uefivid.c, boot/freeldr/freeldr/bootmgr.c, boot/freeldr/freeldr/freeldr.c, boot/freeldr/freeldr/include/arch/uefi/machuefi.h, boot/freeldr/freeldr/include/arch/uefi/uefildr.h, boot/freeldr/freeldr/lib/fs/fs.c, boot/freeldr/freeldr/miscboot.c, boot/freeldr/freeldr/uefi.cmake
First batch of changes to implement a UEFI version of freeldr.
Supersedes PR #5128.
- Compile freeldr as EFI binary on top of the existing loader
- Stub out various functions so we can create a UEFI mach type in freeldr
- Implement all of the video output function so we can display a pretty freeldr BSoD
Remade because I accidentally blew up my own PR.
=> [BOOT] Support compiling freeldr as a UEFI loader as well - Implement UI functions

base/applications/notepad/main.c, base/applications/notepad/notepad.h
Get the full power of CRT debug.
- Add `#include <stdlib.h>` for `<crtdbg.h>`.
- Move `"#include <crtdbg.h>"` into `"notepad.h"`.
- Insert `#define _CRTDBG_MAP_ALLOC` just before `"#include <crtdbg.h>"`.
=> [NOTEPAD] Move '#include <crtdbg.h>' and add _CRTDBG_MAP_ALLOC

base/applications/notepad/dialog.c
Remove unwanted call.
JIRA issue: [CORE-18369](https://jira.reactos.org/browse/CORE-18369)
=> [NOTEPAD] LoadIcon() needs no DestroyIcon()

base/applications/notepad/dialog.c, base/applications/notepad/main.c, base/applications/notepad/notepad.h, base/applications/notepad/printing.c, base/applications/notepad/settings.c
Standardization.
- Remove the definition of `ARRAY_SIZE` macro.
- Replace `ARRAY_SIZE` and `ARRAYSIZE` with `_countof`.
=> [NOTEPAD] Use _countof macro from <stdlib.h>

base/applications/mspaint/drawing.cpp, base/applications/mspaint/main.cpp, base/applications/mspaint/toolbox.cpp, base/applications/mspaint/toolbox.h, base/applications/mspaint/toolsettings.cpp, base/applications/mspaint/toolsettings.h, base/applications/mspaint/winproc.cpp
Improve human readability and code flexibility.
Many coordinates are dynamically calculated.
It is adjustable against client area change.
- Fix some brush/eraser shapes for pixel perfection.
- Reduce magic numbers in `toolssettings.cpp`.
- Refactoring.
=> [MSPAINT] Tool settings: Reduce magic numbers

base/applications/mspaint/textedit.cpp
Reduce source code.
- Use SizeBox and simplify `textedit.c`.
=> [MSPAINT] Simplify TextEdit by using SizeBox

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-15289](https://jira.reactos.org/browse/CORE-15289)
- Do default processing on `WM_IME_SELECT` and `WM_IME_CONTROL` messages in `EDIT` controls.
=> [COMCTL32][USER32] EDIT: Do default on WM_IME_SELECT/CONTROL

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
JIRA issue: [CORE-15289](https://jira.reactos.org/browse/CORE-15289), [CORE-11700](https://jira.reactos.org/browse/CORE-11700)
- Improve `WM_IME_STARTCOMPOSITION` handling in the window procedure of the `EDIT` control.
=> [COMCTL32][USER32] EDIT: Half-implement WM_IME_STARTCOMPOSITION

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-15289](https://jira.reactos.org/browse/CORE-15289)
- Add `WM_IME_SETCONTEXT` handling to the window procedure of the `EDIT` control.
=> [COMCTL32][USER32] EDIT: Half-implement WM_IME_SETCONTEXT handling

modules/rostests/kmtests/CMakeLists.txt, modules/rostests/kmtests/kmtest_drv/testlist.c, modules/rostests/kmtests/ntos_ob/ObQuery.c, ntoskrnl/ob/oblife.c
Currently there is no implementation support for object name information querying when someone queries information about an object with `ObjectBasicInformation` class case. Some device drivers may take use of such information.
`NameInfoSize` is a size that is the sum of all name directories of an object, including path separators. `TypeInfoSize` is a size that is pointed by the size of a type object itself, therefore this size remains pretty much fixed depending on the kind of an object.
https://www.geoffchappell.com/studies/windows/km/ntoskrnl/inc/api/ntobapi/object_basic_information.htm
http://undocumented.ntinternals.net/index.html?page=UserMode%2FUndocumented%20Functions%2FNT%20Objects%2FType%20independed%2FNtQueryObject.html
=> [NTOS:OB] Implement name information querying on ObjectInformation case

.github/labeler.yml
Let the GitHub bot automatically tag PRs that touch Win32k code or Win32 client DLLs (namely GDI, USER, whatever). With this new label we can browse through these kind of PRs easily, similarly with those that touch the kernel which are labeled "Kernel & Hal".
=> Tag Win32SS related PRs with "Win32SS" label

drivers/network/afd/afd/main.c, drivers/network/afd/afd/read.c, drivers/network/afd/include/afd.h
Fix FileZilla 3.8 `ECONNRESET` error (based on patch by [KRosUser](https://jira.reactos.org/secure/ViewProfile.jspa?name=KRosUser))
JIRA issue: [CORE-18328](https://jira.reactos.org/browse/CORE-18328)
=> [AFD] ReceiveActivity: Don't return STATUS_FILE_CLOSED in case of FCB overread

base/setup/usetup/usetup.c, drivers/setup/blue/blue.c
JIRA issue: [CORE-18838](https://jira.reactos.org/browse/CORE-18838)
- Optimize `IOCTL_CONSOLE_FILL_OUTPUT_ATTRIBUTE` and `IOCTL_CONSOLE_FILL_OUTPUT_CHARACTER` for speed by using cache.
=> [BLUE] Optimize ScrIoControl for speed

dll/win32/kernel32/winnls/string/lang.c
Support Japanese Hiragana and Katakana conversion.
- Implement `LCMAP_KATAKANA` and `LCMAP_HIRAGANA` flags.
=> [KERNEL32] LCMapString: Hiragana/Katakana conversion

base/applications/mspaint/atlimagedx.h, base/applications/mspaint/canvas.cpp, base/applications/mspaint/common.h, base/applications/mspaint/dialogs.cpp, base/applications/mspaint/dib.cpp, base/applications/mspaint/dib.h, base/applications/mspaint/fullscreen.cpp, base/applications/mspaint/fullscreen.h, base/applications/mspaint/globalvar.h, base/applications/mspaint/history.cpp, base/applications/mspaint/imgarea.cpp, base/applications/mspaint/imgarea.h, base/applications/mspaint/main.cpp, base/applications/mspaint/miniature.cpp, base/applications/mspaint/miniature.h, base/applications/mspaint/palette.cpp, base/applications/mspaint/palettemodel.cpp, base/applications/mspaint/precomp.h, base/applications/mspaint/registry.cpp, base/applications/mspaint/selection.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/textedit.cpp, base/applications/mspaint/toolbox.cpp, base/applications/mspaint/toolsettings.cpp, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h, base/applications/mspaint/winproc.cpp, base/applications/mspaint/winproc.h, sdk/lib/atl/atlimage.h
Improve source code quality.
- Add `CFullscreenWindow::DoCreate`, `CMiniatureWindow::DoCreate`, and `CMainWindow::DoCreate` helper functions.
- Encapsulation around `mainWindow` and `_tWinMain`.
- Add `CMainWindow::GetOpenFileName`, `CMainWindow::GetSaveFileName`, and `CMainWindow::ChooseColor` helper functions (optimized for startup).
- Move some code in `WinMain` into `CMainWindow::OnCreate`.
- Delay creation of `CFullscreenWindow` and `CMiniatureWindow` (optimized for startup and memory usage).
- Add `atlimagedx.h` in `mspaint`.
- Extend ATL `CImage` class as `CImageDx` in `mspaint`.
Memory usage (BEFORE):
Memory usage (AFTER):
=> [MSPAINT][ATL] Encapsulation: mainWindow

base/applications/regedit/childwnd.c, base/applications/regedit/find.c, base/applications/regedit/framewnd.c, base/applications/regedit/listview.c, base/applications/regedit/main.h, base/applications/regedit/treeview.c
Follow up to #5146.
- Fix ListView Selection.
- Search a value correctly.
The `wcslen` call against non-`UNICODE_NULL`-terminated data had caused buffer overrun. We will check the data size correctly, instead of 3 `NUL` byte appending hack.
JIRA issue: [CORE-15986](https://jira.reactos.org/browse/CORE-15986), [CORE-18230](https://jira.reactos.org/browse/CORE-18230)
- Add `bSelectNone` parameter to `UpdateAddress` and `RefreshListView` functions.
- If `bSelectNone` is `TRUE`, then select nothing of ListView.
- Fix item selection of ListView.
- Rename `CompareData` helper function as `MatchData` and improve it.
- Improve the search algorithm.
- If the item selection of ListView changed, scroll down to the item.
`ReportAs`:
`DisplayVersion`:
=> [REGEDIT] Fix ListView selection and finding

ntoskrnl/mm/section.c
[CORE-17627](https://jira.reactos.org/browse/CORE-17627)
When closing a file, fastfat zeroes it out from ValidDataLength up to the end of the file.
The ValidDataLength field is updated when the file content is actually written to disk.
There is currently a race between the file-close path and the page out path, leading to potential file corruptions when the zeroing happens after the memory has been flushed to disk.
Fix this by actually flushing the file to disk when unmapping files, with file lock acquired. This way, the FS driver cannot zero out the tail of the file while we're actually flushing it to disk.
=> [NTOSKRNL] Flush file to disk when deleting file mappings

win32ss/user/ntuser/defwnd.c, win32ss/user/ntuser/event.c, win32ss/user/ntuser/hook.c
fix authored by JIRA-user "TANGaming". Many thanks for the contribution.
I do suspect that the possibility of that nullptr deref was introduced on the master branch by 0.4.13-dev-962-g 4193b8d8ace0b84d0bf82c72bc9263a35ee414a8
JIRA issue: [CORE-18899](https://jira.reactos.org/browse/CORE-18899)
Doug Lyons signalled his "ok" regarding the fix in chat already.
=> [NTUSER] Fix BSOD 0x1E nullptr deref CORE-18899

dll/win32/msi/dialog.c
Purpose : Continuing from [PR](https://github.com/reactos/reactos/pull/4951) since the remote branch was deleted
There is a bug, which displays empty optical drive as a valid Drive where applications can be installed, which is wrong. This change will skip displaying any drives that are not fixed in the disk usage table in the msi installer UI.
JIRA issue: [CORE-18758](https://jira.reactos.org/browse/CORE-18758)
Proposed changes
Revert to old solution from Doug Lyons which was working fine.
see [diff1](https://git.reactos.org/?p=reactos.git;a=commitdiff;h=d5265b07bbfb6ac6da190b8213cf2f3f8d9cd675;hp=05fb0f1c392484d774d0fafbb6ca6e0317a69fa7), [diff2](https://git.reactos.org/?p=reactos.git;a=commitdiff;h=864e20b881130cbc9668b8e253a31b8c325e9b99;hp=83fcd65700e8cf6d0c07c81d85a07e68c5d87cdc)
=> [MSI] Revert to previous working solution for disk usage display in dialog.c

base/applications/mspaint/registry.cpp, base/applications/mspaint/registry.h, base/applications/mspaint/toolbox.cpp, base/applications/mspaint/toolbox.h, base/applications/mspaint/toolsettings.cpp, base/applications/mspaint/winproc.cpp
The user will be able to move ToolBox in the main window by dragging.
- Add `Bar2ID` registry setting.
- Add `CPaintToolBar` class to encapsulate the toolbar code.
- Capture and track the mouse dragging in `CToolBox`.
- Move the ToolBox if dragging is beyond the center position.
Left:
Right:
=> [MSPAINT] Allow ToolBox to be right-aligned

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
Display the composition window correctly.
- Call `IMM32!ImmSetCompositionFontW` function in `WM_SETFONT` message handling of `EDIT` controls if necessary.
- If the specified font is `NULL`, then use `DEFAULT_GUI_FONT` stock font.
=> [COMCTL32][USER32] EDIT: WM_SETFONT for IME

sdk/include/reactos/version.rc, sdk/include/reactos/wine/wine_common_ver.rc
that we do compile into almost every dll and exe.
Reduces unnecessary scrolling in the
Versions tab of file properties dlg, which precedes the Copyright phrase anyway.
MS also uses shorter strings and therefore doesn't require to scroll. See attached screenshots in the PR.
ros_unnecessarily_long_and_duplicated_strings_do_hide_the_interesting_parts:
MS_does_not_duplicate_the_string:
=> [SDK] Shorten autogenerated Copyright strings

dll/win32/shimgvw/shimgvw.c
Noticed by user "Ben" on JIRA. Patch by KRosUser.
JIRA issue: [CORE-18905](https://jira.reactos.org/browse/CORE-18905)
Add a missing `InvalidateRect` call in `pLoadImageFromNode`.
=> [SHIMGVW] Update the display window when selecting the Previous/Next picture.

base/system/rundll32/rundll32.c, dll/win32/shell32/wine/control.c
Improve compatibility.
JIRA issue: [CORE-13895](https://jira.reactos.org/browse/CORE-13895), [CORE-18350](https://jira.reactos.org/browse/CORE-18350)
RunDLL on Win2k3:
The window class is `"RunDLL"`.
It is still working.
- Rename the window class name `"rundll32_window"` as `"RunDLL"`.
- Delete some `shell32` codes about this window class.
=> [RUNDLL32][SHELL32] Rename 'rundll32_window' as 'RunDLL'

base/applications/rapps/loaddlg.cpp
Correctly display Download ListView at right position in any languages.
AFTER:
- Correctly calculate the position of the Download Listview at `CDowloadingAppsListView::Create`.
- Use correct position to create the listview.
=> [RAPPS] Calculate download listview position

dll/win32/advapi32/reg/reg.c
_Provide graceful handling of RegCreateKeyExW when lpSecurityAttributes->nLength is zero._
JIRA issue: [CORE-15471](https://jira.reactos.org/browse/CORE-15471)
_When lpSecurityAttributes->nLength == 0 then set lpSecurityAttributes to NULL and continue._
_Provide error message showing what was found._
This allows the Win98 DDK to install without any failures.
=> [ADVAPI32] Fix RegCreateKeyExW with lpSecurityAttributes->nLength of 0

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
Correctly display the composition window and the candidate window.
The changes of this PR are on `EDIT` controls.
- Delete `composition_len` and `composition_start` members.
- Add `EDIT_ImmSetCompositionWindow` helper function.
- At `EDIT_SetCaretPos`, set the position of the composition window.
- We don't use internal composition string. Rely on the composition window.
- Improve `WM_IME_STARTCOMPOSITION`, `WM_IME_COMPOSITION` and `WM_IME_ENDCOMPOSITION` message handling.
https://user-images.githubusercontent.com/2107452/230355963-e9bdf080-fc71-4198-90a8-78f4602ceac9.mp4
=> [COMCTL32][USER32] EDIT: CompForm and CandForm

win32ss/user/ntuser/kbdlayout.c
Improve IME activation. If IME was not activated correctly, then the IME is not usable.
- In `IntImmActivateLayout` function, if `pImeWnd` was `NULL` and `pti->spDefaultImc` was non-`NULL`, then set `CI_IMMACTIVATE` flag.
=> [NTUSER] IntImmActivateLayout: Set CI_IMMACTIVATE if not pImeWnd

win32ss/user/ntuser/window.c
JIRA issue: [CORE-18821](https://jira.reactos.org/browse/CORE-18821)
Do window validation for some functions in win32k that call co_UserDestroyWindow directly.
Thanks @sdever and @yagoulas for the help.
=> [NTUSER] co_UserDestroyWindow: Validate window before destroying it

modules/rostests/winetests/user32/CMakeLists.txt
Change module type to win32cui to be able to see the test results.
Test WHS: https://reactos.org/testman/compare.php?ids=85895,85896,85897,85899,85900
=> [USER32_WINETEST] Change module type to win32cui

ntoskrnl/cc/copy.c, ntoskrnl/cc/pin.c, sdk/lib/pseh/include/pseh/pseh3.h
This PR fixes broken usage of _SEH2_FINALLY.
1. While variable assignment is handled properly with MSVC, GCC/PSEH does not know anything about exceptions and does not guarantee that your variables are set where you think they are set, because the compiler will happily remove any assignments that it considers redundant or move them to a different place. If you need to check a variable within a finally or except block, which is set in a try block, you must mark that variable with _SEH2_VOLATILE.
2. Finally handlers are - unlike except blocks - not part of the function they are in, but separate functions, which are called during unwind. PSEH implements them on GCC using nested functions. While "return" from a finally handler is allowed with native SEH, it's handled by the compiler through an …
=> Fix SEH in Cc

dll/win32/hhctrl.ocx/help.c
Reduce ROS diff for `HH_LoadString`. Addendum to [3a72a52](https://github.com/reactos/reactos/commit/3a72a52ce886c5a1bfa1e87b1a9b759e85a5c3d4) (#4554).
=> [HHCTRL.OCX] Reduce ROS diff

sdk/tools/mkisofs/schilytools/libmdigest/byte_order.h
This fixes build when using native MSVC build tools and ReactOS host-tools on ARM.
=> [MKISOFS] Fix MSVC build on ARM hosts

drivers/storage/port/scsiport/scsi.c
- Flush Map registers once the DMA completes
- Free Map registers once the DMA completes
- Add support for SGL allocated from NonPagedPool
Test:
Force Allocations of SGL from Non Paged Pool and ensure OS boots and functions properly
Test Logs:
SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
DHCPCSVC: Adapter Name: [{7cd69ac0-dabb-410a-b927-cb3961d174da}] (dynamic) SpiAdapterControlFORCING ALLOCATION FROM SGPOOL
WARNING:  HalCalculateScatterGatherListSize at hal\halx86\generic\dma.c:1168 is UNIMPLEMENTED! SpiAdapterControlFORCING ALLOCATION FROM SGPOOL …
=> [SCSIPORT] Flush and Free Map Registers

ntoskrnl/ob/oblife.c
The current implementation of `ObQueryTypeInfo` calculates the returned length to the caller in this following way -- initialize (or increment) the necessary length by summing up the size of the `ObjectTypeInfo` variable's contents and the maximum length of an object type name, aligned to a 4-byte boundary. This can lead to two problems.
1. The implementation uses `MaximumLength` in the calculation of the returned length for the target object type. Commonly `MaximumLength` would include the length of the string and the NULL terminator but that is not always the case. An object type name that is not NULL-terminated can potentially make the `ObQueryTypeInfo` function to overrun the name buffer.
2. The returned length is aligned to a 4-byte boundary, which makes perfect sense on a x86 …
=> [NTOS:OB] Properly calculate the return length in ObQueryTypeInfo

base/applications/regedit/framewnd.c
Avoid crash on exporting root.
JIRA issue: [CORE-18938](https://jira.reactos.org/browse/CORE-18938)
- Add `NULL` check of `pszSelectKey` on `CDN_FILEOK` handling.
=> [REGEDIT] Check whether pszSelectKey is NULL on CDN_FILEOK

sdk/lib/atl/atlbase.h
When it is not defined, COM should not be initialize multithreaded
`COINIT_MULTITHREADED` can cause problems when COM objects expect `Apartment` threading, because they will be serialized.
=> [ATL] Take _ATL_FREE_THREADED into account

dll/win32/riched20/caret.c, dll/win32/riched20/editor.c, dll/win32/riched20/editstr.h
Correctly display the composition window and the candidate window.
The changes of this PR are on `RichEdit` controls.
- Delete `imeStartIndex` member.
- At `update_caret` function, set the position and font of the composition window.
- We don't use internal composition string. Rely on the composition window.
- Improve `WM_IME_SETCONTEXT`, `WM_IME_CONTROL`, `WM_IME_SELECT`, `WM_IME_STARTCOMPOSITION`, `WM_IME_COMPOSITION` and `WM_IME_ENDCOMPOSITION` message handlings.
BEFORE:
AFTER:
=> [RICHED20] RichEdit: CompForm and CandForm

base/applications/kbswitch/CMakeLists.txt, base/applications/kbswitch/kbswitch.c, sdk/include/reactos/shlwapi_undoc.h
Remove the needless hack and reduce the maintenance cost. Because `shlwapi!SHLoadRegUIString` function is already implemented, so we don't need the hack any more.
- Directly use `shlwapi!SHLoadRegUIString` function instead of a hack.
- Add link to `shlwapi.dll`.
=> [KBSWITCH] Delete SHLoadRegUIString hack

dll/win32/comdlg32/filedlg.c
[COMDLG32] Enable saving files with different extension
like on Windows, gives precedence to the user's extension in file names if there is one.
Otherwise appends the selected extension. If not selected, append default extension.
=> [COMDLG32] Enable saving files with different extension

dll/win32/setupapi/queue.c, media/doc/WINESYNC.txt
_Sync setupapi/queue.c to Wine 4.8 to improve cab extraction._
_This fixes 'fixme:(dll/win32/setupapi/queue.c:418) awful hack: extracting cabinet'_
JIRA issue: [CORE-15471](https://jira.reactos.org/browse/CORE-15471)
_This is not specific to CORE-15471, but is an aside and related to it._
_Partial Wine Sync to Version 4.8 for Setupapi queue function._
=> [SETUPAPI] Sync setupapi/queue.c to Wine 4.8

dll/win32/shell32/debughlp.cpp, dll/win32/shell32/wine/pidl.c
[SHELL32] Enable Network Connection Rename 
Add Network Connection pidl type 0x99
Value hard coded at netshell/enumlist.cpp in function ILCreateNetConnectionItem(...)
ms say:
ILIsEqual performs a binary comparison of the item data.
JIRA issue: [CORE-18750](https://jira.reactos.org/browse/CORE-18750)
=> [SHELL32] Enable Network Connection Rename CORE-18750

drivers/filesystems/ext2/inc/common.h, drivers/filesystems/ext2/inc/ext2fs.h, drivers/filesystems/ext2/inc/linux/module.h, drivers/filesystems/ext2/inc/linux/types.h, drivers/filesystems/ext2/src/block.c, drivers/filesystems/ext2/src/cmcb.c, drivers/filesystems/ext2/src/devctl.c, drivers/filesystems/ext2/src/dispatch.c, drivers/filesystems/ext2/src/ext2.rc, drivers/filesystems/ext2/src/ext3/generic.c, drivers/filesystems/ext2/src/ext3/indirect.c, drivers/filesystems/ext2/src/ext4/ext4_extents.c, drivers/filesystems/ext2/src/ext4/ext4_jbd2.c, drivers/filesystems/ext2/src/fastio.c, drivers/filesystems/ext2/src/fileinfo.c, drivers/filesystems/ext2/src/flush.c, drivers/filesystems/ext2/src/init.c, drivers/filesystems/ext2/src/linux.c, drivers/filesystems/ext2/src/memory.c, drivers/filesystems/ext2/src/pnp.c, drivers/filesystems/ext2/src/write.c
add ifdefs to distinguish ReactOS code/fixes from the upstream code.
NOTE: there are no new features in this PR, we stay with upstream version 0.69.
JIRA issue: [CORE-18645](https://jira.reactos.org/browse/CORE-18645)
* surround ReactOS modifications with ifdef
* if upstream code was override, reintroduce it in #else section
* re-align .rc version info with upstream (0.69)
=> [EXT2FS] Align with upstream and mark ReactOS diff

base/shell/explorer/precomp.h, base/shell/explorer/taskswnd.cpp, base/shell/explorer/traywnd.cpp, base/system/rundll32/rundll32.c, dll/win32/shell32/wine/control.c
The minimized non-task windows were not usable due to the bugs. At some situations, the system will restore the minimized non-task windows.
JIRA issue: [CORE-13895](https://jira.reactos.org/browse/CORE-13895), [CORE-18350](https://jira.reactos.org/browse/CORE-18350)
- Add `IsTaskWnd` helper function.
- Add `SendPulseToTray` function to send a pulse to the tray window.
- At some shell hook handlings, send a pulse to the tray window.
- Add `IgnorePulse` flag to control the timing of restoring.
- Add a timer to reset `IgnorePulse` flag.
- If the pulse has come and `IgnorePulse` flag is false, then restore the minimized non-task windows.
- Modify the `rundll32` window procedure.
- Use `WINDOWPLACEMENT` to restore the minimized windows.
=> [EXPLORER][RUNDLL32] Restore minimized non-task windows

base/applications/kbswitch/kbswitch.c
JIRA issue: [CORE-13145](https://jira.reactos.org/browse/CORE-13145), [CORE-10667](https://jira.reactos.org/browse/CORE-10667), [CORE-18924](https://jira.reactos.org/browse/CORE-18924)
- Use `GetKeyboardLayoutList` to get the keyboard list instead of using `Preload` registry key.
- Get the special IDs from registry to handle special `HKL`s in newly-added `LoadSpecialIds` function.
- Add `GetKLIDFromHKL`, `GetHKLFromLayoutNum`, `UpdateLayoutList`, and `GetKLIDFromLayoutNum` helper functions.
BootCD:
LiveCD:
=> [KBSWITCH] Rely on GetKeyboardLayoutList for getting list

boot/freeldr/freeldr/arch/arm/debug.c, boot/freeldr/freeldr/arch/arm/entry.c, boot/freeldr/freeldr/arch/arm/macharm.c, boot/freeldr/freeldr/arch/uefi/stubs.c, boot/freeldr/freeldr/arch/uefi/uefildr.c, boot/freeldr/freeldr/include/debug.h, boot/freeldr/freeldr/lib/debug.c, boot/freeldr/freeldr/uefi.cmake, boot/freeldr/freeldr/ui/directui.c, boot/freeldr/freeldr/ui/gui.c, boot/freeldr/freeldr/ui/minitui.c, boot/freeldr/freeldr/ui/noui.c, boot/freeldr/freeldr/ui/tui.c, boot/freeldr/freeldr/ui/tuimenu.c, boot/freeldr/freeldr/ui/ui.c, boot/freeldr/freeldr/ui/video.c, sdk/lib/crt/float/float.cmake
In the beginning of the ARM port FreeLoader's UI functions were too slow on targeted devices. As such the solution was to split off from that and minimize what those ARM devices needed to do to achieve the FreeLoader Ui. Now in the present world we use MSVC which breaks compatibility with the devices we used to target; None of these newer device have issues with the way FreeLoader draws so we are going to attempt to unify this here today. This PR lays nearly everything we need for ARM32 to boot up to FreeLoader from EFI ARM devices. 
-> This PR will have a single link error left that'll be solved in another PR due to its complexity 
JIRA issue: [CORE-17604](https://jira.reactos.org/browse/CORE-17604)
- Disable some …
=> [FREELDR][SDK] Build UEFI bootloader for ARM32

ntoskrnl/kdbg/kdb_symbols.c
Fix x64 boot with KDBG enabled (rosautotest).
- Only load symbols on x86
=> [NTOS:KDBG] Only load symbols on x86

dll/win32/winmm/midimap/midimap.c, dll/win32/winmm/playsound.c
- Fix incorrect registry key in `get_mmioFromProfile`
- `get_mmioFromProfile` : Expand environment strings if registry value type is `REG_EXPAND_SZ`
- Use `RegOpenCurrentUser` to access the appropriate `HKEY_CURRENT_USER` key. This allows functions that use `HKEY_CURRENT_USER` to be called from system processes while impersonating, for example: winlogon
- Fix `SystemDefault` event and `SND_NODEFAULT` flag
- `get_mmioFromProfile` code formatting
- `PlaySound_IsString` code formatting
=> [WINMM] Winmm fixes for system sound

ntoskrnl/config/cmconfig.c
This is needed by some 3rd party drivers.
- Initialize the alternative system architecture field
=> [NTOS:CM] Set alternative system architecture field on PC-98

dll/win32/kernel32/client/console/console.c, sdk/include/reactos/subsys/win/conmsg.h
The `conime.exe` program exists in WinXP/Win2k3 and it realizes Console IME.
`conime.exe` calls `kernel32!RegisterConsoleIME` and `kernel32!UnregisterConsoleIME`.
To realize Console IME, these two functions are required.
- Add `IntRegisterConsoleIME` and `IntUnregisterConsoleIME` helper functions.
- Implement `RegisterConsoleIME` and `UnregisterConsoleIME` API functions.
- Add `CONSOLE_REGISTERCONSOLEIME` and `CONSOLE_UNREGISTERCONSOLEIME` structures to `sdk/include/reactos/subsys/win/conmsg.h`.
=> [KERNEL32][SDK] RegisterConsoleIME and UnregisterConsoleIME

win32ss/user/ntuser/misc.c
Implementing Console IME...
- Add `THREADSTATE_CHECKCONIME` handling in `NtUserGetThreadState` function.
=> [NTUSER] Implement THREADSTATE_CHECKCONIME

base/applications/rapps/README.ENG, base/applications/rapps/appdb.cpp, base/applications/rapps/configparser.cpp, base/applications/rapps/include/configparser.h, base/applications/rapps/include/defines.h, base/applications/rapps/misc.cpp, base/applications/rapps/settings.cpp, base/applications/rapps/settingsdlg.cpp, base/applications/rapps/unattended.cpp
The primary goal is the replace (in user's local AppData) `rapps\rapps`, which looks a bit ridiculous and could appear as a bug of RAPPS (why creating two subdirectories with the same name??), by instead `RAPPS\AppsDb`, which (to my opinion) looks more decent and tells exactly what it is for -- the offline apps database. This would also allow for future sub-directories into the `RAPPS` settings folder.
And also I take the opportunity to consolidate in one single place the defines for these directory names.
- Change the name of the application database sub-directory from "rapps\rapps" to "RApps\appdb".
- Adjust the documentation to reflect this.
- Simplify CConfigParser constructor by removing GetINIFullPath().
NOTE: In case this is accepted, https://reactos.org/wiki/RAPPS will need minor …
=> [RAPPS] Centralize the names of the RAPPS' registry setting sub-key, and user local settings & offline apps database sub-directories.

ntoskrnl/ke/amd64/trap.S, sdk/include/asm/ksamd64.template.h
This PR fixes some issues on x64, where threads that already had a large GUI stack were switched to a new large stack, deallocating the previous stack, as if it was a normal stack. With the current stack allocator, that uses system PTEs and doesn't keep track on the size of the allocation, this would have leaked system PTEs.
It also fixes a broken success check, which would always succeed, and in case of a failure execute the systemcall over and over again.
- Do not allocate a new stack, if the thread already has a large one. This prevents the function from freeing a large stack as a normal stack and subsequently leaking system PTEs.
- Fix the check for failure of PsConvertToGuiThread (test eax, not rax, for being negative, because by default rax is zero extended from eax, not sign …
=> [NTOS:KE/x64] Fix KiConvertToGuiThread

ntoskrnl/lpc/complete.c, ntoskrnl/lpc/connect.c, ntoskrnl/lpc/create.c, ntoskrnl/lpc/send.c
Ensure debug-traced user-mode data passed by pointers is captured.
JIRA issue: [CORE-18098](https://jira.reactos.org/browse/CORE-18098)
=> [NTOS:LPC] Ensure debug-traced user-mode data passed by pointers is captured.

base/applications/regedit/treeview.c
Avoid using a NULL pointer when My Computer is selected,
by disabling the New Key menu item.
Simplifies and fix code style in GetItemPath function.
Add a new entry even when no child items exist.
JIRA issue: [CORE-18878](https://jira.reactos.org/browse/CORE-18878)
=> [REGEDIT] Creating a new Key should add a new entry even when no child exist. CORE-18878

base/applications/cmdutils/attrib/attrib.c
Fix arguments parsing and redundant code in case no file specification has been given.
(Handles both "attrib" and "attrib +h /s" as given in example.)
=> [ATTRIB] Improve command-line parsing.

dll/win32/browseui/lang/fr-FR.rc
JIRA issue: [CORE-18914](https://jira.reactos.org/browse/CORE-18914)
Before
After
supersedes https://github.com/reactos/reactos/pull/5281
=> [TRANSLATION][BROWSEUI] Improve French (fr-FR) translation v2

dll/win32/browseui/lang/de-DE.rc, dll/win32/shell32/folders/CFSFolder.cpp, win32ss/user/user32/misc/exticon.c
Even more failing tests will be fixed after https://github.com/reactos/reactos/pull/5169 is committed.
_Modify some return values in exticon.c based on from where they are called._
JIRA issue: [CORE-18897](https://jira.reactos.org/browse/CORE-18897)
_Change some return values in common function ICO_ExtractIconExW based on from where they are called._
=> [SHELL32][USER32] Fix icon regression and one test

win32ss/user/user32/windows/class.c
Fixes NULL pointer access when e.g. class.lpszClassName == NULL and the
class is registered. The RegisterClass(ExA/W/...) should return 0
instead of throw an invalid access exception.
Noticed by @julenuri.
JIRA issue: [CORE-18978](https://jira.reactos.org/browse/CORE-18978)
=> [USER32] RegisterClassExWOWW/ExA: NULL or IS_ATOM class are treated the same.

dll/win32/shell32/CDefView.cpp
Revert File menu of Explorer Cabinet that had been changed at https://github.com/reactos/reactos/commit/1cf564c25f532c32f9fae891f17a70e62d5c1c14.
JIRA issue: [CORE-9467](https://jira.reactos.org/browse/CORE-9467), [CORE-18429](https://jira.reactos.org/browse/CORE-18429), [CORE-11797](https://jira.reactos.org/browse/CORE-11797)
- Revert `CDefView::FillFileMenu`.
=> [SHELL32] Revert CDefView::FillFileMenu

win32ss/user/ntuser/class.c, win32ss/user/ntuser/window.c, win32ss/user/user32/windows/class.c
Fixes access to extra space in window classes on x64. Fixes a few tests/crashes on x64.
- [USER32] Fix SetWindowWord/Long (cannot use NtUserSetWindowLongPtr!)
- [WIN32K] Fix WindowExtra for some server-side classes
GCC x86 KVM: https://reactos.org/testman/compare.php?ids=87186,87189,87195,87199,87212
MSVC x64: https://reactos.org/testman/compare.php?ids=87169,87175,87180,87184,87165
On x86:
- ✅ user32:GetSetWindowInt: 7 tests fixed
On x64:
- ✅ advapi32:eventlog: crash fixed
- ✅ comctl32:tooltips: 62 tests fixed
- ✅ dinput8:device: 2 more tests run, 1 test fixed
- ❓ gdi32:font: 758 tests less executed
- ✅ gdiplus:font: 2 tests fixed
- ✅ user32:GetClassInfo: 1 test fixed
- ✅ user32:GetSetWindowInt: 13 tests fixed
- ❌ user32:msg_focus: 1 test broken
- ✅ user32:msg_mdi: crash fixed
- ❓ …
=> [USER32][WIN32K] Fix access to window extra bytes

ntoskrnl/io/pnpmgr/pnpmap.c
_**NOTE: Made on behalf of @binarymaster **_
- Deduplicate a while-loop by adding one more recursive call.
- Add IopMapDetectedDeviceId() helper function with a structure in order to reduce hardcoded constants and checks.
JIRA issue: [CORE-18962](https://jira.reactos.org/browse/CORE-18962)
=> [NTOS:PNP] IopEnumerateDetectedDevices(): General refactoring

base/applications/rapps/gui.cpp, base/applications/rapps/include/dialogs.h, base/applications/rapps/include/gui.h, base/applications/rapps/include/resource.h, base/applications/rapps/include/unattended.h, base/applications/rapps/unattended.cpp, dll/cpl/appwiz/appwiz.c
Open the "Installed" RAPPS section when trying to view the already-installed programs from appwiz.cpl.
On behalf of @binarymaster .
JIRA issue: [CORE-18981](https://jira.reactos.org/browse/CORE-18981)
```
[RAPPS] Add /APPWIZ command-line key to open "Installed" section
Addendum to ab7ddc44.
```
```
[RAPPS] Open "Installed" section in Appwiz-mode when RAPPS already runs
```
```
[APPWIZ] Use new Appwiz-mode to start RAPPS with "Installed" section open
```
=> [RAPPS][APPWIZ] Allow to open "Installed" RAPPS section via command-line

.github/workflows/build.yml
Temporarily disable MSBuild until a proper fix is shipped, having a single failing worker just because MS did an oopsie with MSBuild is annoying.
[CORE-18911](https://jira.reactos.org/browse/CORE-18911)
=> [GITHUB] Temporarily disable MSBuild

.github/workflows/stale.yml
~~Reporting a PR as stale after 4 months and closing it after 2 weeks due to inactivity is kind of harsh. What's even harsher is that draft PRs are marked as stale even though the author is still working on a PR and may have not had the time to push the changes on the said PR yet.~~
~~With that said, increase the stale report time to 10 months and PR closure to 4 weeks. Also draft PRs should be exempt from stale warning.~~
Draft PRs should be exempt from being marked as stale, an author may have not had the time to push the changes yet into a PR. Draft by definition means that a PR is still a work in progress so it makes no sense for the bot to auto close them.
=> [GITHUB] Draft PRs should be exempt from closure by the stale PR bot

ntoskrnl/ps/security.c, ntoskrnl/se/token.c
Back then I was working on #3605 that would determine if the server is allowed to impersonate a client's token or not, although after learning more about how impersonation works there are several issues concerning with `SeTokenCanImpersonate`, that is...
- `ImpersonationLevel` is basically what the server asks to impersonate a client based on that level, having there failing if the level was either given `SecurityAnonymous` or `SecurityIdentification` doesn't make much sense. If the server wants to identify the details of a client then let it do so.
- The function does not check for `SeImpersonatePrivilege`. Certain system components of the OS or the system process itself might need to impersonate on behalf of a client to do specific OS tasks, so give them leverage.
- The function does …
=> [NTOSKRNL] Fix a double reference on client impersonation and refactor SeTokenCanImpersonate

ntoskrnl/io/pnpmgr/plugplay.c
JIRA issue: [CORE-18983](https://jira.reactos.org/browse/CORE-18976)
We should compare against `DeviceObject` as `DeviceInstance` is never NULL. The PR fixes a resource leak as well.
The bug  [CORE-18983](https://jira.reactos.org/browse/CORE-18983) seems to lay somewhere else though, I just stumbled upon this one while researching it.
- There is a BSOD on reboot after the driver's (failed) installation, on the PnP manager, but it seems it was uncovered by the fix as opposed to caused by it.
=> [NTOS:PNP] Fix bug causing all devices be considered as already existing

win32ss/gdi/ntgdi/init.c, win32ss/gdi/ntgdi/misc.h, win32ss/user/ntuser/main.c, win32ss/user/ntuser/ntuser.c
Load DirectX graphics kernel driver (dxg.sys) by our win32k when the system starts up. Keep it always loaded in memory, like done in Windows, instead of loading only by DirectX dlls. It fixes the problem with accessing to this driver, so then we need only call `DxDdEnableDirectDraw` and do other stuff when DirectDraw/Direct3D is required by anything. In other cases, it is called from win32k PDEV* functions when changing display mode (as in Windows). Since it's used by other things too, it needs to be always loaded.
Otherwise, if it's not loaded, its APIs are not accessible when needed, and then execution fails.
It fixes display mode change problem in VMWare, when a new mode fails to be applied, because when it manages DirectDraw stuff, it calls DXG routines, and therefore fails if dxg.sys …
=> [WIN32SS][NTUSER] Load DirectX graphics driver at system startup

dll/win32/shell32/CDefView.cpp
In 0.4.14-dev-955-g 1cf564c25f532c32f9fae891f17a70e62d5c1c14 Katayama experimented with populating explorers file-menu when no object is selected.
Later we found out, that none of the new entries introduced by that commit really made sense and even created duplicates. So the commit was reverted by 0.4.15-dev-6039-g 0fa4edebd9125b9ca7a4256edbea7675e2152c7e 'Revert CDefView::FillFileMenu (#5278)' CORE-18429
But it seems that not all parts were properly reverted back then, maybe because 6 lines of new code were written between the two lines in the meantime.
Here is a video of the state with the PR applied
[this_is_the_after_PR_state_and_it_behaves_same_as_the_before_state.webm](https://github.com/reactos/reactos/assets/33393466/59af6c00-428b-4d5f-989f-75db883bdaee)
It behaves the same in my …
=> [SHELL32] Strip leftover in CDefView::FillFileMenu()

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/winproc.cpp
Improve keyboard usability.
- Add `CCanvasWindow::MoveSelection` function.
- Modify `CMainWindow::OnKeyDown` function.
- If `Esc` key is pressed, then the selection will land to canvas if any.
- If any arrow key is pressed, then the selection will move a bit if any.
https://github.com/reactos/reactos/assets/2107452/1e49502b-c158-48df-9210-78891e3a0b33
=> [MSPAINT] Move selection by arrow keys

base/applications/taskmgr/precomp.h, base/applications/taskmgr/taskmgr.c
Use the power of CRT debug to detect memory leaks.
JIRA issue: [CORE-18014](https://jira.reactos.org/browse/CORE-18014)
- Define `_CRTDBG_MAP_ALLOC` and include `<crtdbg.h>` after `<stdlib.h>`.
- Call `_CrtSetDbgFlag` at prologue of `wWinMain`.
=> [TASKMGR] Report any memory leaks on exit

base/applications/taskmgr/precomp.h, base/applications/taskmgr/taskmgr.c
taskmgr doesn't use any CRT allocation. I don't see the point of using it.
This reverts commit [2441e86](https://github.com/reactos/reactos/commit/2441e869638da86106470f51a166acebdb3b3be0)
[CORE-18991](https://jira.reactos.org/browse/CORE-18991)
=> [TASKMGR] Remove CRTDBG

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/common.h, base/applications/mspaint/dialogs.cpp, base/applications/mspaint/dib.cpp, base/applications/mspaint/drawing.cpp, base/applications/mspaint/fullscreen.cpp, base/applications/mspaint/globalvar.h, base/applications/mspaint/history.cpp, base/applications/mspaint/history.h, base/applications/mspaint/main.cpp, base/applications/mspaint/miniature.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/palette.cpp, base/applications/mspaint/palette.h, base/applications/mspaint/palettemodel.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/selectionmodel.h, base/applications/mspaint/textedit.cpp, base/applications/mspaint/toolbox.cpp, base/applications/mspaint/toolbox.h, base/applications/mspaint/toolsettings.cpp, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h, base/applications/mspaint/winproc.cpp
Providing rich and consistent UI/UX to the users.
JIRA issue: [CORE-17969](https://jira.reactos.org/browse/CORE-17969)
- Painting the canvas is done by overlaying the multiple layers. Drawing each overlay is implemented as polymorphism of OOP.
- Refine the Undo/Redo mechanism.
- Some adjustments.
=> [MSPAINT] Establish Undo/Redo management

ntoskrnl/io/pnpmgr/pnproot.c
Handling PnP root driver power IRPs requires that a device object must come up with a device extension to determine whether it is a function driver and if so, handle the IRP accordingly.
**JIRA Issue:** [CORE-18989](https://jira.reactos.org/browse/CORE-18989)
=> [NTOS:PNP] Assert the presence of a device extension when handling PnP root power IRPs

base/applications/mspaint/winproc.cpp, base/applications/mspaint/winproc.h
Bug fix on Undo/Redo actions and refactoring.
- Add `CMainWindow::CanUndo` and `CMainWindow::CanRedo` and use them.
- Fix wrongly-disabled Undo/Redo in some cases.
=> [MSPAINT] Add CMainWindow::CanUndo/CanRedo

base/applications/mspaint/main.cpp
Fix filename extension cases and "File Type" field.
- If no filename extension on save, then append `.png` to the filename.
Tested on Win10.
BEFORE:
AFTER:
=> [MSPAINT] Fix CMainWindow::GetSaveFileName

dll/win32/browseui/internettoolbar.cpp
Store the state of the explorer toolbar, locked or unlocked, in the proper registry location and set the proper toolbar state when initialized.
JIRA issue: [CORE-9094](https://jira.reactos.org/browse/CORE-9094)
- Set ```HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar\Locked``` to 1 when the explorer toolbar is locked, 0 when the toolbar is unlocked.
- Query ```HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Toolbar\Locked``` when the toolbar is initialized to set the correct locked state.
- Set the default state of the toolbar to locked if the registry key does not exist, matching the behavior of Windows Server 2003.
=> [BROWSEUI] Add locked toolbar state persistence

win32ss/reactx/ntddraw/ddraw.c, win32ss/reactx/ntddraw/intddraw.h
Do it at each system startup instead, same as in Windows.
Remove old DirectX initialization code. Now it's outdated and not needed anymore. The corresponding functionality is now implemented properly by changes from #4519 and #4551 PRs.
Previously, the corresponding hackish `intEnableReactXDriver` function did two things: load dxg.sys and enable DirectDraw. Now loading DirectX graphics is done during WINSRV initialization, and enabling DirectDraw is called during each (and also first) display mode switch, same as in Windows. As debug analysis proves, there are no any other calls in `NtGdiDdCreateDirectDrawObject`, besides the corresponding DXG function. So MS does not do the initialization there.
JIRA issue: [CORE-17561](https://jira.reactos.org/browse/CORE-17561), …
=> [WIN32SS][NTDDRAW] Don't startup DirectX graphics each time on DirectDraw object creation

base/applications/mspaint/mouse.cpp
Fix the behavior of the `ShapeTool` in pressing `Shift` key.
- Correctly call `roundTo8Directions` helper function on mouse actions.
=> [MSPAINT] Fix ShapeTool with Shift key

base/applications/network/netstat/netstat.c
Fix a crash that happens when accessing cmd args out of bounds and show usage help.
JIRA issue: [CORE-19005](https://jira.reactos.org/browse/CORE-19005)
The crash was a regression of 0.4.11-dev-814-g 2b5507336017cdea726f146a225823a932df54c2
Before my fix:
https://jira.reactos.org/secure/attachment/65929/65929_0.4.15-dev-6172-gc63489f_netstatCrash_abnop.png
After my quick fix: (I showed usage help then, no crash anymore. Wrong screen output, wrong error level)
https://jira.reactos.org/secure/attachment/65931/65931_quick_fix.webm
After my final fix: (no crash, proper screen output, proper error-level)
https://jira.reactos.org/secure/attachment/65933/65933_put_love_into_the_fix_to_exactly_match_windows_screenoutput_and_errorlevel.webm
=> [NETSTAT] Fix crash when parsing the protocol CORE-19005

dll/win32/shimgvw/shimgvw.c
In win2k3, the file name was displayed in the title bar even if the file was not loaded.
However, in React OS, the file name was not displayed in the tie and river when the file was not loaded.
Therefore, the file name was displayed unless the file name could't to retrieved.
JIRA issue: [CORE-18954](https://jira.reactos.org/browse/CORE-18954)
=> [SHIMGVW] Display the file name in taskbar even if the file isn't loaded

win32ss/user/ntuser/window.c
@learn-more wrote 'break on this in debug builds'.
https://jira.reactos.org/browse/CORE-18132?focusedCommentId=133294&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-133294
Addendum to ee0511b (0.4.10-dev-323).
JIRA issue: [CORE-18132](https://jira.reactos.org/browse/CORE-18132)
- Add 1 `else`.
- Add 2 `ASSERT()`.
- Add 1 FIXME comment.
=> [NTUSER] Add ASSERT() on "linking window to itself"

drivers/network/ndis/include/ndissys.h, ntoskrnl/ex/sysinfo.c
Fix values written to ThreadKernelTime and TotalCpuTime being swapped.
=> Fix ExGetCurrentProcessorCounts

win32ss/user/ntuser/message.c
Fix CLIENTINFO pointer access.
Based on a patch by Michael Fritscher from [CORE-10017](https://jira.reactos.org/browse/CORE-10017)
Addendum to 705228250741da (r68702).
JIRA issue:
[CORE-18728](https://jira.reactos.org/browse/CORE-18728)
[CORE-19014](https://jira.reactos.org/browse/CORE-19014) (duplicate)
=> [NTUSER] NtUserWaitForInputIdle: Fix unhandled exception BSOD 0x1E

ntoskrnl/include/internal/amd64/ke.h, ntoskrnl/include/internal/i386/ke.h, ntoskrnl/ke/amd64/cpu.c, ntoskrnl/ke/amd64/kiinit.c, ntoskrnl/ke/i386/cpu.c, ntoskrnl/ke/i386/kiinit.c
Print out the CPU features only when Kernel Debugger has been initialized and `KF_*` features and policies has been applied.
Also add this feature to AMD64.
JIRA issue: [CORE-18023](https://jira.reactos.org/browse/CORE-18023)
=> [NTOS:KE] Report x86 CPU features in a separate function

dll/win32/shell32/lang/ro-RO.rc
Fix the typo "docsarul". Addendum to 8fe890e96316.
=> [SHELL32] Improve Romanian (ro-RO) translation

base/applications/network/netstat/netstat.c
When calling 'netstat -abn'
Win 2k3sp2 and XPSP3 do show both: the processes name and the PID.
Contrary Win 7 and Win 8.1 would show only the process name then without the PID.
The newer Windows versions would require you to explicitly pass -o if you want to see the PID also.
We do follow 2k3sp2 because it is our target, but also because that is a more sane default choice.
The process name is not of much use without having the PID as well,
especially if multiple processes with the same name
do run on a system, e.g.: multiple 'svchost.exe' processes.
JIRA issue: [CORE-19006](https://jira.reactos.org/browse/CORE-19006)
Attached is a picture of the fixed state:
=> [NETSTAT] -b flag implies -o flag on Windows XP/2003. CORE-19006

base/applications/mscutils/servman/export.c, base/applications/mscutils/servman/precomp.h
It was tab-delimited regardless of the user's selection.
Now, make either tab or comma separated depending on the selection.
JIRA issue: [CORE-19001](https://jira.reactos.org/browse/CORE-19001)
=> [SERVMAN] Respect the user-selected export format

modules/rostests/apitests/advapi32/IsTextUnicode.c, sdk/lib/rtl/unicode.c
Fix the garbled characters (a.k.a. mojibake) in some Japanese text files.
JIRA issue: [CORE-19016](https://jira.reactos.org/browse/CORE-19016)
- `weight` will remain `3` unless `IS_TEXT_UNICODE_DBCS_LEADBYTE` flag is set.
- Strengthen `advapi32_apitest IsTextUnicode` testcase.
BEFORE:
AFTER:
BEFORE:
AFTER:
=> [RTL][ADVAPI32_APITEST] RtlIsTextUnicode: Don't change weight unless lead-byte flag

base/applications/network/netstat/lang/en-US.rc, base/applications/network/netstat/lang/pl-PL.rc, base/applications/network/netstat/lang/zh-TW.rc, base/applications/network/netstat/netstat.c
in netstat.c 100% of the calls to
DisplayTableHeader();
have in the exact line beforehand a call to
ConResPuts(StdOut, IDS_ACTIVE_CONNECT);
So let's fuse them.
Also fix a superfluous space in the *.rc files before it will get duplicated a thousand times.
=> [NETSTAT] Optimize a bit

base/applications/network/netstat/lang/pl-PL.rc, base/applications/network/netstat/netstat.h
- add a pragma once into the header
- order -o option alphabetically also for the global variables, not only in usage-help
- pl-PL.rc: fix wrong alignment between IDS_ETHERNET_THEADER and its data
- pl-PL.rc: also don't pad the data with 2 spaces here in the beginning, which we don't do in any other locale, and MS netstat also doesn't do that here. pl-PL.rc most likely got this wrong because it was created while en-US wasn't finished yet.
here is a pic of the **fixed** polish, or let's better say: 'polished' state:
=> [NETSTAT] pragma once, reorder, fix pl-PL.rc

base/applications/network/netstat/netstat.c
- Avoid the heap in ShowIpStatistics() and ShowIcmpStatistics() to simplify the code, inspired by how we do it in ShowTcpStatistics() and ShowUdpStatistics() already
- Strip 2 Captain-Obvious-Comments
For the record: Retrieving ICMP-stats and IP-stats does not work properly in ReactOS yet, neither with nor without my changes. Lower layers are most likely wrong still somehow. But netstat itself can properly obtain ICMP-stats and IP-stats in Windows already.
=> [NETSTAT] Less heap allocations

modules/rostests/apitests/gdi32/SetDIBitsToDevice.c
_Remove some outdated 'todo_ros' qualifiers._
JIRA issue: [ROSTESTS-384](https://jira.reactos.org/browse/ROSTESTS-384)
_Remove 'todo_ros' in six (6) places._
SetDIBitsToDevice_fix.patch JID65977 on top of 0.4.15-dev-6253-g7fafeb6
VBox: https://reactos.org/testman/compare.php?ids=88092,88095 LGTM
KVM:  https://reactos.org/testman/compare.php?ids=88091,88094 LGTM
=> [GDI32_APITEST] Remove "todo_ros" for SetDIBitsToDevice tests that work now

dll/win32/browseui/shellbars/CISFBand.cpp
JIRA issue: [CORE-18966](https://jira.reactos.org/browse/CORE-18966)
- Don't call `ClientToScreen` in handling `NM_RCLICK` message because `NMMOUSE.pt` is already in screen coordinates.
BEFORE:
AFTER:
=> [BROWSEUI] Fix position of taskbar toolbar right-click menu

boot/freeldr/freeldr/arch/uefi/stubs.c, boot/freeldr/freeldr/arch/uefi/ueficon.c
Use the ConsoleIn bootservice to provide keyboard input for freeloader.
JIRA issue: [CORE-11954](https://jira.reactos.org/browse/CORE-11954)
- Support keystrokes in freeloader by translating EFI_INPUT_KEY values into PC-BIOS compatible values.
=> [FREELDR] Add UEFI Console input support

dll/win32/shell32/CDefView.cpp
Selecting all in `system32` was too slow.
JIRA issue: [CORE-18663](https://jira.reactos.org/browse/CORE-18663)
- Make `CDefView::UpdateStatusbar` function asynchronized by using a thread.
- It makes selecting all very quick (within one second).
- Add `m_hUpdateStatusbarThread` member variable in order to asynchronize.
=> [SHELL32] Update the status bar asynchronously

base/shell/explorer/traywnd.cpp
JIRA issue: [CORE-18427](https://jira.reactos.org/browse/CORE-18427)
- Add `CanBeMinimized` helper function to determine whether the window should be minimized.
- Use them in `FindEffectiveProc` and `MinimizeWindowsProc` functions.
- Improve the Minimize code.
BEFORE:
Magnifier does minimize on `Win+D`.
AFTER:
Magnifier won't minimize on `Win+D`.
AFTER:
Task Manager does minimize on `Win+D`.
=> [EXPLORER] Improve the minimize-condition on Win+D

base/shell/cmd/cmd.c
JIRA issue: [CORE-14096](https://jira.reactos.org/browse/CORE-14096)
Patch based on an earlier fix attempt by Doug Lyons.
This bug has always been present since the implementation of this feature in commit a1eb1f6ba (r40024).
The expansion of %~dpX ennhanced variables used to incorrectly show some directories in uppercase. For example:
```batch
:: testcmd.cmd
echo '%~dp0'
echo '%~dps0'
echo '%~s0'
```
would show:
```
P:\Documents and Settings\Administrator\Desktop>echo 'P:\Documents and Settings\Administrator\DESKTOP\'
'P:\Documents and Settings\Administrator\DESKTOP\'
P:\Documents and Settings\Administrator\Desktop>echo 'P:\DOCUME~1\ADMINI~1\DESKTOP\'
'P:\DOCUME~1\ADMINI~1\DESKTOP\'
P:\Documents and Settings\Administrator\Desktop>echo 'P:\DOCUME~1\ADMINI~1\DESKTOP\testcmd.cmd' …
```
=> [CMD] Correctly honour the "short" path flag in %~var enhanced variables expansion.

ntoskrnl/io/iomgr/irq.c, ntoskrnl/ntoskrnl.spec
This gives ReactOS the ability to load various modern drivers that use IoConnectInterruptEx
various drivers work after this such as the serial.sys sample driver from MS and many more KMDF drivers from later windows versions
- IoConnectInterruptEx for CONNECT_FULLY_SPECIFIED
=> [NTOS:IO] Implement IoConnectInterruptEx for fully specific interrupt types

dll/win32/shell32/folders/CDrivesFolder.cpp
_Fix regression of [4c25af5b](https://github.com/reactos/reactos/commit/4c25af5bd4ac8ea3bdfb855478683980922ed32b)_
JIRA issue: [CORE-19000](https://jira.reactos.org/browse/CORE-19000)
_Commit Number 1 (Old Line Number 1149 replacement)._
_For the Drives Detailed View of Explorer, change comments to show in column 4 instead of 2._
_Commit Number 2_
_While working in this file, replace some magic numbers._
Note: This is made more confusing by the fact that the 'Folder->GetDetailsOf' function has its column numbers and the Explorer details view has its column numbers and these do not always agree.
=> [SHELL32] Fix detail view in My Computer showing Comment in 'Total Size' column

boot/bootdata/hivedef.inf
Enable the explorer status bar by default, which the vast majority of our community voted for.
JIRA issues: [CORE-19010](https://jira.reactos.org/browse/CORE-19010) [CORE-19028](https://jira.reactos.org/browse/CORE-19028)
- Set ```HKCU\Software\Microsoft\Internet Explorer\Main\StatusBarOther``` to 1 in ```hivedef.inf```. This will show the status bar by default.
=> [BOOTDATA] Show Explorer status bar by default

dll/win32/advapi32/sec/safer.c
JIRA issues: [CORE-14015](https://jira.reactos.org/browse/CORE-14015), [CORE-6942](https://jira.reactos.org/browse/CORE-6942)
This makes Windows 2003 CMD.EXE to start batch files again. Addendum to commit 17d42ae2a (r58868).
Replaces PR #3084 by freely importing and adapting Wine patch
https://github.com/wine-mirror/wine/commit/17110a0a890d2bacb5b348bd9bb3cef10d144e19
```
advapi32: Improve the SaferComputeTokenFromLevel stub.
Wine-Bug: https://bugs.winehq.org/show_bug.cgi?id=47274
Signed-off-by: Hans Leidekker <hans@codeweavers.com>
Signed-off-by: Alexandre Julliard <julliard@winehq.org>
```
BEFORE:
AFTER:
=> [ADVAPI32] "Minimally" improve the SaferComputeTokenFromLevel() stub.

win32ss/user/winsrv/consrv/frontends/gui/conwnd.c
Work-around extra buggy WM_MOUSEMOVE events received when VBox Mouse Integration is enabled.
Those caused the "Ignore-next-mouse-event" mechanism of the console (used e.g. in QuickEdit mode for not triggering the appearance of the context menu, etc.) to not work.
Please note that those buggy events, that arise when testing ReactOS in VirtualBox with Mouse Integration is enabled, do not show up when running instead Windows (2003, ...) in the same configured VM.
Addendum to commits ac51557c0 (r63792) and 33d8a4b74 (r67218).
"Better" fix for the one reported and attempted in PR #5406 by @whindsaks , as it keeps the separation between the flag that manages the working-around of the bug, and the other flag that is used for ignoring the genuine next mouse event that follows mouse-button-down …
=> [CONSRV] Fix extra buggy WM_MOUSEMOVE events received when VBox Mouse Integration is enabled.

dll/win32/advapi32/advapi32.spec
All ordinals > 128 regressed by
0.4.15-dev-305-g dd7fb63cd1b0c7f61d7503adefcfca8ce748cc60 and were off-by-one compared to 2k3sp2 and the ros-before-state.
Now all 684 ordinals seem to be fine again.
JIRA issue: [CORE-19039](https://jira.reactos.org/browse/CORE-19039)
Before and after pic: See the ticket.
=> [ADVAPI32] Fix ordinals regression CORE-19039

dll/shellext/zipfldr/CConfirmReplace.cpp, dll/shellext/zipfldr/CEnumZipContents.cpp, dll/shellext/zipfldr/CExplorerCommand.cpp, dll/shellext/zipfldr/CZipCreator.cpp, dll/shellext/zipfldr/CZipCreator.hpp, dll/shellext/zipfldr/CZipEnumerator.hpp, dll/shellext/zipfldr/CZipExtract.cpp, dll/shellext/zipfldr/CZipFolder.hpp, dll/shellext/zipfldr/CZipPassword.cpp, dll/shellext/zipfldr/precomp.h, dll/shellext/zipfldr/zipfldr.cpp, dll/shellext/zipfldr/zippidl.cpp, dll/shellext/zipfldr/zippidl.hpp
A modern system should support UTF-8 for interoperability.
JIRA issue: [CORE-16668](https://jira.reactos.org/browse/CORE-16668)
- Extend some Ansi strings to Wide strings. 
- Check the UTF-8 flag (`1 << 11`).
- If UTF-8, then use `CP_UTF8`.
- `s/LPCWSTR/PCWSTR/`.
- `s/LPWSTR/PWSTR/`.
BEFORE:
AFTER:
AFTER:
=> [ZIPFLDR] Support UTF-8 Zip extraction

modules/rostests/apitests/atl/CMakeLists.txt, modules/rostests/apitests/atl/atlconv.cpp, modules/rostests/apitests/atl/atltest.h, modules/rostests/apitests/atl/devenv/.gitignore, modules/rostests/apitests/atl/devenv/ATLTest.sln, modules/rostests/apitests/atl/devenv/atlconv.vcxproj, modules/rostests/apitests/atl/devenv/atlconv/atlconv.vcxproj, modules/rostests/apitests/atl/testlist.c, sdk/lib/atl/atlconv.h
JIRA issue: [CORE-16668](https://jira.reactos.org/browse/CORE-16668)
- Add `<atlconv.h>` header file.
- Add `atlconv` testcase to `atl_apitest`
ATL of Visual Studio 2015:
Successful.
Win10:
One failure.
=> [ATL][ATL_APITEST] Add <atlconv.h> and atlconv testcase

dll/win32/shell32/folders/CDrivesFolder.cpp
JIRA issue: [CORE-18272](https://jira.reactos.org/browse/CORE-18272)
- Add `_ILGetDriveType` helper function.
- Use `_ILGetDrive` and `GetDriveType` functions to determine the drive type.
- If it was a CD-ROM drive, then remove `SFGAO_CANRENAME` flag.
BEFORE:
It can rename.
AFTER:
It cannot rename by F2 key nor menu.
=> [SHELL32] CD-ROM drive shouldn't be renamed

dll/cpl/appwiz/createlink.c, dll/cpl/appwiz/lang/bg-BG.rc, dll/cpl/appwiz/lang/cs-CZ.rc, dll/cpl/appwiz/lang/de-DE.rc, dll/cpl/appwiz/lang/el-GR.rc, dll/cpl/appwiz/lang/en-US.rc, dll/cpl/appwiz/lang/es-ES.rc, dll/cpl/appwiz/lang/et-EE.rc, dll/cpl/appwiz/lang/fr-FR.rc, dll/cpl/appwiz/lang/he-IL.rc, dll/cpl/appwiz/lang/hu-HU.rc, dll/cpl/appwiz/lang/id-ID.rc, dll/cpl/appwiz/lang/it-IT.rc, dll/cpl/appwiz/lang/ja-JP.rc, dll/cpl/appwiz/lang/no-NO.rc, dll/cpl/appwiz/lang/pl-PL.rc, dll/cpl/appwiz/lang/pt-BR.rc, dll/cpl/appwiz/lang/pt-PT.rc, dll/cpl/appwiz/lang/ro-RO.rc, dll/cpl/appwiz/lang/ru-RU.rc, dll/cpl/appwiz/lang/sk-SK.rc, dll/cpl/appwiz/lang/sq-AL.rc, dll/cpl/appwiz/lang/tr-TR.rc, dll/cpl/appwiz/lang/uk-UA.rc, dll/cpl/appwiz/lang/zh-CN.rc, dll/cpl/appwiz/lang/zh-HK.rc, dll/cpl/appwiz/lang/zh-TW.rc, dll/cpl/appwiz/resource.h
Improve UI/UX.
JIRA issue: [CORE-5866](https://jira.reactos.org/browse/CORE-5866)
- Add `IDS_BROWSE_FOR_TARGET` resource string.
- Use it in setting the title caption of `"Browse for Folder"` dialog.
Win2k3:
Win2k3 dialog has the title caption.
BEFORE:
No title caption.
AFTER:
The dialog  got a title caption.
=> [APPWIZ] Add title caption to 'Browse for Folder'

dll/cpl/appwiz/appwiz.h, dll/cpl/appwiz/createlink.c, sdk/include/reactos/undocshell.h
Allow command line as `Create Shortcut` wizard's target.
JIRA issue: [CORE-5866](https://jira.reactos.org/browse/CORE-5866)
- Add `szArguments` member to `CREATE_LINK_CONTEXT` structure.
- Use `IShellLink::SetArguments`.
- Split arguments from command line text by using `PathGetArgsW` and `PathRemoveArgsW`.
- Find the first parameter by using `PathFindOnPathExW` and `FindExecutableW` and use the found file path.
Win2k3:
The Win2k3 wizard accepts command line and creates shortcut files.
BEFORE:
The wizard won't accept command line.
The wizard accepts command line and creates shortcut files.
=> [APPWIZ] 'Create Shortcut' wizard: Accept arguments

dll/win32/shell32/droptargets/CFSDropTarget.cpp, dll/win32/shell32/folders/CControlPanelFolder.cpp
_Fix uninitialized variable use in CFSDropTarget.cpp._
JIRA issue: [CORE-18841](https://jira.reactos.org/browse/CORE-18841)
_Initialize STRRET strretFrom to all zeroes { 0 } to initialize strretFrom.pOleStr._
_This eventually propagates to heap.c:2304 which causes the error message in the title._
=> [SHELL32] Fix 'Attempt to free an invalid HEAP address'

base/applications/iexplore/CMakeLists.txt, base/applications/iexplore/iexplore.inf, dll/win32/ieframe/CMakeLists.txt, dll/win32/ieframe/ieframe_v1.rgs, dll/win32/ieframe/lang/cs-CZ.rc, dll/win32/ieframe/lang/de-DE.rc, dll/win32/ieframe/lang/en-US.rc, dll/win32/ieframe/lang/es-ES.rc, dll/win32/ieframe/lang/fr-FR.rc, dll/win32/ieframe/lang/hu-HU.rc, dll/win32/ieframe/lang/id-ID.rc, dll/win32/ieframe/lang/it-IT.rc, dll/win32/ieframe/lang/ja-JP.rc, dll/win32/ieframe/lang/pl-PL.rc, dll/win32/ieframe/lang/pt-PT.rc, dll/win32/ieframe/lang/ro-RO.rc, dll/win32/ieframe/lang/ru-RU.rc, dll/win32/ieframe/lang/tr-TR.rc, dll/win32/ieframe/lang/zh-CN.rc, dll/win32/ieframe/lang/zh-TW.rc, dll/win32/ieframe/resource.h, dll/win32/shell32/folders/CDesktopFolder.cpp, dll/win32/shell32/folders/CRegFolder.cpp
JIRA issue: [CORE-18625](https://jira.reactos.org/browse/CORE-18625)
relies on https://github.com/reactos/reactos/commit/1c91b0b61ddb893e7fb52e84c8d415fe426915de to work properly
- Add Internet icon on Desktop.
- Modify `"HKCR\CLSID\%CLSID_Internet%"` registry key.
- Add `IDS_INTERNET` and `IDS_INTERNET_DESCRITION` resource strings into `ieframe.dll`.
- Modify `dll/win32/shell32/folders/CDesktopFolder.cpp` and `dll/win32/shell32/folders/CRegFolder.cpp` to add the icon.
BEFORE:
No internet icon.
AFTER:
There is the Internet icon. You can hide/show the icon from Desktop's customization.
=> [IEXPLORE][IEFRAME][SHELL32] Add Internet icon on Desktop

dll/cpl/appwiz/addons.c
The pointer variable `download_binding` is used in multiple threads. I think it needs locking before accessing.
JIRA issue: [CORE-15786](https://jira.reactos.org/browse/CORE-15786)
- Add static variable `CRITICAL_SECTION csLock`.
- Use it in accessing `download_binding` pointer variable.
=> [APPWIZ] Add locking in access of download_binding

boot/bootdata/hivedef.inf, dll/win32/browseui/shellbrowser.cpp
Adds an option to set the full folder path in the window title for the file explorer.
JIRA issue: [CORE-19046](https://jira.reactos.org/browse/CORE-19046)
- Set ```HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CabinetState\FullPath``` to 0 by default. Including this registry value also enables the "Display the full path in the title bar" option in our folder options window.
- Query this same registry key when the file explorer is started to determine whether to use the full path or the display name as the window title.
- Refresh the window title and window title settings after applying changes from folder options, instead of having to restart the file browser.
=> [BROWSEUI] Add an option to use full folder path in the window title

base/shell/explorer/precomp.h, base/shell/explorer/settings.cpp, base/shell/explorer/taskswnd.cpp, dll/win32/browseui/shellbrowser.cpp
Adds large taskbar icon support. Small taskbar icons are set by default.
Jira issue: [CORE-11698](https://jira.reactos.org/browse/CORE-11698)
- Query ```HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarSmallIcons``` to set the icon size for the taskbar. If the registry value is missing, it will use small icons. If the registry value is set to 1, it will also use small icons. Only if the value exists and is set to 0 will it use large icons. This allows us to use the same registry value as Windows 7, while also keeping the taskbar icons small in most cases, including running the shell on unmodified Windows Server 2003.
=> [EXPLORER] Large taskbar icon support

CONTRIBUTING.md, PULL_REQUEST_MANAGEMENT.md
This PR is a result of discussion (links: [one](https://chat.reactos.org/reactos/pl/s1xsp4b1s38o9kx3dc41fy871e), [two](https://chat.reactos.org/reactos/pl/da3ozt58k3bnukpj96ip9n119a)) in the chat with @JoachimHenze and @ThFabba regarding noreply e-mails being used by some GitHub contributors.
It has been experimentally verified that using anonymous GitHub e-mail does not allow to deliver mail to the commit author. GitHub does replace author's real email when `Keep my email addresses private` option is enabled in the account's e-mail settings.
Additionally I have replaced old IRC links with the references to our chat.
Please approve if you are okay with the changes I made in this PR. Suggestions are also welcome.
=> [DOCS] Update contributing rules and PR management

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/shlwapi.spec, sdk/include/reactos/shlwapi_undoc.h
- Implement `SHPropertyBag_WriteBOOL`, `SHPropertyBag_WriteSHORT`, `SHPropertyBag_WriteLONG`, `SHPropertyBag_WriteDWORD`, `SHPropertyBag_WriteStr`, `SHPropertyBag_WriteGUID`, and `SHPropertyBag_WriteStream` functions.
- Modify `dll/win32/shlwapi/shlwapi.spec`.
- Modify `sdk/include/reactos/shlwapi_undoc.h`.
=> [SHLWAPI][SDK] Implement SHPropertyBag_WriteDWORD etc.

win32ss/user/ntuser/focus.c, win32ss/user/ntuser/window.c, win32ss/user/ntuser/window.h, win32ss/user/user32/windows/input.c
CORE-18811
Explicitly reference window objects when using it as sibling in some other window object
JIRA issue: [CORE-18811](https://jira.reactos.org/browse/CORE-18811)
Very much like what @tkreuzer did recently for owner window
=> [WIN32SS:USER] Always reference a window when using it as parent/child etc.

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, modules/rostests/apitests/shlwapi/testlist.c, sdk/include/reactos/shlwapi_undoc.h
- Implement `SHPropertyBag_Delete`, `SHPropertyBag_WritePOINTL`, `SHPropertyBag_WritePOINTS`, and `SHPropertyBag_WriteRECTL` functions.
- `SHPropertyBag_WriteInt` is an alias to `SHPropertyBag_WriteLONG`.
- Modify `shlwapi_undoc.h`.
- Add `SHPropertyBag` testcase to `shlwapi_apitest.exe`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
ReactOS:
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] Implement SHPropertyBag_WritePOINTL etc.

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/precomp.h, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
- Add `VariantChangeTypeForRead` helper function.
- Implement `SHPropertyBag_ReadType`, `SHPropertyBag_ReadBOOL`, `SHPropertyBag_ReadBOOLOld`, `SHPropertyBag_ReadSHORT`, `SHPropertyBag_ReadLONG`, and `SHPropertyBag_ReadDWORD` functions.
- `SHPropertyBag_ReadInt` is an alias to `SHPropertyBag_ReadLONG`.
- Modify `<shlwapi_undoc.h>`.
- Strengthen `SHPropertyBag` testcase of `shlwapi_apitest.exe`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
ReactOS:
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] Implement SHPropertyBag_ReadDWORD etc.

dll/cpl/appwiz/addons.c
Fix errors on 2nd stage setup epilogue.
JIRA issue: [CORE-15786](https://jira.reactos.org/browse/CORE-15786)
- Just return `E_NOTIMPL` in `InstallCallback_GetBindInfo` function. That's Okay.
=> [APPWIZ] Implement InstallCallback_GetBindInfo

base/shell/explorer/taskswnd.cpp
Opens minimized windows from the correct position when using the taskbar. This also fixes an issue where minimizing and opening task manager causes that window to become blank when running our shell in Windows Server 2003.
JIRA issue: [CORE-19055](https://jira.reactos.org/browse/CORE-19055)
- Stop storing and setting window positions from the taskbar and instead rely on the window's existing position.
=> [EXPLORER] Open windows with the correct position

dll/win32/advapi32/sec/lsa.c
Current code incorrectly treats a structure pointer as a simple string pointer.
JIRA issue: [CORE-18996](https://jira.reactos.org/browse/CORE-18996)
Replace code incrementing unicode string pointer incorrectly with structure appropriate code. This should eliminate an exception and make the function operate correctly.
=> [ADVAPI32] Don't treat a structure pointer as a simple string pointer. CORE-18996

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
- Implement `SHPropertyBag_ReadBSTR`, `SHPropertyBag_ReadStr`, `SHPropertyBag_ReadPOINTL`, `SHPropertyBag_ReadPOINTS`, and `SHPropertyBag_ReadRECTL` functions.
- Modify `shlwapi.spec`
- Modify `shlwapi_undoc.h`.
- Strengthen `SHPropertyBag` testcase of `shlwapi_apitest.exe`.
- Add link to `oleaut32.dll` in `shlwapi_apitest.exe`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
ReactOS:
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] Implement SHPropertyBag_ReadBSTR etc.

dll/win32/browseui/shellbrowser.cpp
Use the details view by default in the file explorer, except in the Control Panel, My Computer, and Desktop folders. This follows the default behavior in Windows Vista+.
JIRA issue: [CORE-18904](https://jira.reactos.org/browse/CORE-18904)
- Use the icon view by default for My Computer, Control Panel, and Desktop
- Use the details view by default in all other folders
- Call the "Start Navigation" sound event in ```CShellBrowser::BrowseToPIDL```
- Implement the "Display the full path in the title bar" option including setting persistence
- Properly implement ShellBags to allow the user to change the default view for each folder
- Implement ```Tiles``` view and set that view as the default for My Computer and Desktop
=> [BROWSEUI] Use details view by default

ntoskrnl/cache/section/sptab.c, ntoskrnl/cc/copy.c, ntoskrnl/cc/lazywrite.c, ntoskrnl/cc/view.c, ntoskrnl/include/internal/cc.h, ntoskrnl/include/internal/mm.h, ntoskrnl/mm/ARM3/pagfault.c, ntoskrnl/mm/ARM3/pfnlist.c, ntoskrnl/mm/balance.c, ntoskrnl/mm/freelist.c, ntoskrnl/mm/i386/page.c, ntoskrnl/mm/marea.c, ntoskrnl/mm/mmfault.c, ntoskrnl/mm/pagefile.c, ntoskrnl/mm/rmap.c, ntoskrnl/mm/section.c
This PR fixes the kernel crash, when copying large files.
JIRA issue: [CORE-17624](https://jira.reactos.org/browse/CORE-17624)
Suggested to be reviewed by commit.
There are multiple attempts to fix the bug:
- PR #4739 by Jerome (releases VACBs on memory pressure) (currently included)
- [trim_cache_patch_2.patch](https://jira.reactos.org/secure/attachment/65635/65635_trim_cache_patch_2.patch) by Thomas (well, trims individual cache pages, when needed)
- PR #5237 (based on trim_cache_patch_2)
- [ntos_mm_higher_bottom.patch](https://jira.reactos.org/secure/attachment/65511/65511_ntos_mm_higher_bottom.patch)  (only starts paging earlier)
- [modified_standby_pages_3.diff](https://jira.reactos.org/secure/attachment/65559/65559_modified_standby_pages_3.diff) by Jerome (lets the page fault …
=> Fix kernel crash, when copying large files

sdk/lib/atl/atlsimpstr.h, sdk/lib/atl/cstringt.h
Fixing type problems.
- Overload the non-const-return-version of `CSimpleStringT::GetString`.
- Overload the const-return-versions of `FindChar/FindCharReverse/FindString/FindOneOf`.
- Modify `CStringT::Replace`.
=> [ATL] Overload const-return-versions of FindChar/FindString/FindOneOf

sdk/lib/atl/atlimage.h
Refactor code for compatibility and respect the encoders and decoders info.
JIRA issue: [CORE-18867](https://jira.reactos.org/browse/CORE-18867), [CORE-19008](https://jira.reactos.org/browse/CORE-19008)
- Add `_getAllEncoders` and `_getAllDecoders` helper functions and use them in `GetImporterFilterString`, `GetExporterFilterString`, `FileTypeFromExtension` and `GetClsidFromFileType` functions.
- Add `ShouldExcludeFormat`, `FindCodecForFileType`, and `FindCodecForExtension` helper functions for compatibility.
=> [ATL] CImage: Respect CODEC info

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
- Add `VariantArrayToBuffer` helper function.
- Implement `SHPropertyBag_ReadGUID` and `SHPropertyBag_ReadStream` functions.
- Modify `shlwapi_undoc.h`.
- Strengthen `SHPropertyBag` testcase in `shlwapi_apitest.exe`.
- Link `uuid.dll` and `ole32.dll` to `shlwapi_apitest.exe`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
ReactOS:
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] Implement SHPropertyBag_ReadGUID etc.

dll/win32/shlwapi/CMakeLists.txt, dll/win32/shlwapi/assoc.c, dll/win32/shlwapi/path.c
`_WIN32_WINNT` had wrong value to do workaround on Vista+ `RegGetValueW`.
- Do `#undef` and `#define` `_WIN32_WINNT` `_WIN32_WINNT_VISTA` in `assoc.c`.
- Delete `_WIN32_WINNT` hack in `CMakeLists.txt`.
=> [SHLWAPI] Fix version control (_WIN32_WINNT)

base/shell/explorer/taskswnd.cpp, dll/win32/shell32/wine/control.c
Control panel applets and some apps don't display taskbar icon correctly when enabling large taskbar icons.
Addendum to 0e8cf6ffd58 (#5465).
Jira issue: [CORE-11698](https://jira.reactos.org/browse/CORE-11698)
Before:
After:
=> [EXPLORER][SHELL32] Fix taskbar large icon for CPLs and some apps

dll/win32/shlwapi/ordinal.c
Improve shell property bag function documentation.
- Add `@see` comments to `SHPropertyBag_...` functions. They are the links to Geoff Chappell's documentation.
=> [SHLWAPI] Add G. Chappell's documentation links

base/shell/cmd/locale.c
- Precisely describe `time` format, based on [CLDR](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) standard.
- Having spent time verifying the behaviour on Windows and ROS, this strict definition may be helpful to future researchers.
- Non-code change. Comments only. 
\#Enhancement, \#TrivialFix
=> [CMD] Tweak comment for %TIME% format

dll/win32/shell32/stubs.cpp, dll/win32/shell32/wine/shellord.c, sdk/include/reactos/undocshell.h
`SHLimitInputCombo` function sets limits on valid characters for a combobox control.
This function works like `SHLimitInputEdit`, but the target is a combobox instead of a textbox.
- Implement `SHLimitInputCombo` function.
=> [SHELL32][SDK] Implement SHLimitInputCombo

sdk/include/reactos/shlwapi_undoc.h
- Add `SHPropertyBag_ReadInt` / `SHPropertyBag_WriteInt` prototypes (they are aliases to `..._ReadLONG` / `..._WriteLONG`).
=> [SDK] Add SHPropertyBag_ReadInt/WriteInt prototype

modules/rostests/apitests/shell32/CMakeLists.txt, modules/rostests/apitests/shell32/GetDisplayNameOf.cpp, modules/rostests/apitests/shell32/testlist.c
_Add new regression test for Control Panel's GetDisplayNameOf with a NULL first parameter._
_This shows that the return value of the function is 'S_FALSE'._
_Also, the return value of STRRET is not touched by this call._
JIRA issue: [CORE-18841](https://jira.reactos.org/browse/CORE-18841)
_Add new code for regression test of Control Panel's GetDisplayNameOf._
Results of running new test on Windows Server 2003 SP2:
=> [SHELL32_APITEST] New regression test for Control Panel's GetDisplayNameOf

dll/win32/shell32/droptargets/CFSDropTarget.cpp
This change addresses a longstanding TODO in copying and moving to shell folders.
It's a simple change, but it removes a bit of code and makes things simpler.
Corresponding [wine PR](https://gitlab.winehq.org/wine/wine/-/merge_requests/3360).
=> [SHELL32] Improve CopyItems logic

dll/win32/shell32/stubs.cpp, modules/rostests/apitests/shell32/CMakeLists.txt, modules/rostests/apitests/shell32/She.cpp, modules/rostests/apitests/shell32/testlist.c, sdk/include/reactos/undocshell.h
- Implement `SheRemoveQuotesA` and `SheRemoveQuotesW` functions.
- Add `She` testcase into `shell32_apitest.exe`.
- Add `SheRemoveQuotesA` and `SheRemoveQuotesW` prototypes into `undocshell.h`
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Skipped because there are no `SheRemoveQuotesA/W` functions.
Successful.
=> [SHELL32][SHELL32_APITEST][SDK] Implement SheRemoveQuotesA/W

dll/win32/shell32/iconcache.cpp, dll/win32/shell32/stubs.cpp
Follow-up to #5517 (https://github.com/reactos/reactos/commit/358e45d33a80a8db868324cf1f477c9e24408e53). `stubs.cpp` is for stub functions only.
- Move `SheRemoveQuotesA` and `SheRemoveQuotesW` into `iconcache.cpp`.
=> [SHELL32] Move SheRemoveQuotesA/W to iconcache.cpp

dll/win32/shlwapi/CMakeLists.txt, dll/win32/shlwapi/precomp.h, dll/win32/shlwapi/propbag.cpp, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
- Add `dll/win32/shlwapi/propbag.cpp`.
- Implement `CBasePropertyBag` and `CMemPropertyBag` classes.
- Implement `SHCreatePropertyBagOnMemory` function by using these classes.
- Strengthen `SHPropertyBag` testcase in `shlwapi_apitest.exe`.
- Modify `shlwapi_undoc.h`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] SHCreatePropertyBagOnMemory

sdk/lib/atl/atlimage.h
Fix the crash on opening/saving file.
To retrieve the filename extension info from CODECs, we have to keep `gdiplus.dll` loaded.
The perfect fix will take time.
JIRA issue: [CORE-19093](https://jira.reactos.org/browse/CORE-19093), [CORE-19094](https://jira.reactos.org/browse/CORE-19094)
- By adding `CImage dummy` local variables, ensure keeping loaded the `gdiplus.dll`.
BEFORE:
Crashed!
AFTER:
Successful.
=> [ATL] CImage: Hack fix for getting filter string

boot/freeldr/freeldr/arch/i386/irqsup.S, boot/freeldr/freeldr/arch/i386/pc/machpc.c, boot/freeldr/freeldr/pcat.cmake, drivers/input/inport/hardware.c
Automatically install the inport device driver. (this is possible since 7d5e1591313df39d0b2a81c20ab2af9e8d76252a). Besides, some people have reported PS/2 mouse issues with 86Box. For now, the best work around is to use the inport driver.
References:
https://raw.githubusercontent.com/86Box/86Box/master/src/device/mouse_bus.c
https://bochs.sourceforge.io/cgi-bin/lxr/source/iodev/busmouse.cc
=> [FREELDR] Implement bus mouse detection

.github/workflows/build.yml, sdk/cmake/msvc.cmake, subsystems/mvdm/asm16.cmake
Ensure that CMAKE_ASM16_COMPILER is 32-bit MASM on all build targets as it currently is used only for compiling 16-bit x86 ASM code on non-x86 builds. This fixes NTVDM build for ARM. 
Also include subsystems folder in ARM builder.
JIRA issue: [CORE-10452](https://jira.reactos.org/browse/CORE-10452)
=> [CMAKE][MVDM] Fix CMAKE_ASM16_COMPILER for non-x86 MSVC builds

dll/win32/shell32/CMakeLists.txt, dll/win32/shell32/iconcache.cpp, dll/win32/shell32/utils.cpp
Follow-up to #5529 (7100fa8).
- Move `SheRemoveQuotesA` and `SheRemoveQuotesW` into newly created `utils.cpp`.
=> [SHELL32] Move SheRemoveQuotesA/W to utils.cpp

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/precomp.h, dll/win32/shlwapi/propbag.cpp, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
Follow-up to #5511. Implementing missing features...
- Add `CRegPropertyBag` class.
- Implement `SHCreatePropertyBagOnRegKey` function by using `CRegPropertyBag`.
- Strengthen `SHPropertyBag` testcase in `shlwapi_apitest`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] SHCreatePropertyBagOnRegKey

dll/win32/shell32/droptargets/CFSDropTarget.cpp, dll/win32/shell32/shlfileop.cpp
JIRA issue: [CORE-18599](https://jira.reactos.org/browse/CORE-18599)
- If the source and destination of copying file are on the same directory, then enable `FOF_RENAMEONCOLLISION` flag. End if.
- Don't show error message `IDS_COPYERRORSUBFOLDER` or `IDS_MOVEERRORSUBFOLDER` if the source and the destination are the same.
Do `Ctrl+C` and `Ctrl+V` on same file.
BEFORE:
AFTER:
=> [SHELL32] Rename file on copy-paste path collision

win32ss/gdi/gdi32/objects/bitmap.c
bmBits is only used and assigned on output. It points (holds the address) to the array of DIB bit values. The "Bits" parameter is however a pointer to a variable that will receive the address of that array. So it makes no sense to initially assign bmBits to the value of the Bits parameter...
=> [GDI32] CreateDIBSection: Remove erroneous assignation.

dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, sdk/include/reactos/undocshell.h
- Implement `SHCreatePropertyBag` function in `utils.cpp`.
- Add its prototype to `<undocshell.h>`.
=> [SHELL32][SDK] Implement SHCreatePropertyBag

drivers/filesystems/mup/mup.c
`drivers/filesystems/mup/mup.c` generated too heavy traces. We can make it 3 times faster.
JIRA issue: [CORE-19105](https://jira.reactos.org/browse/CORE-19105)
- Make some `DPRINT1`'s `DPRINT`'s.
BEFORE:
https://github.com/reactos/reactos/assets/2107452/71121a51-4f92-43c2-9032-1316c728b03e
Too slow.
AFTER:
https://github.com/reactos/reactos/assets/2107452/751f4a05-5450-4c80-9f20-fa4fc104d438
It's faster.
=> [MUP] Mute DPRINT1's that slow down shared folder accesses

dll/cpl/usrmgr/groupprops.c, dll/cpl/usrmgr/groups.c, dll/cpl/usrmgr/userprops.c, dll/cpl/usrmgr/users.c, dll/cpl/usrmgr/usrmgr.c, dll/cpl/usrmgr/usrmgr.h
JIRA issue: [CORE-18275](https://jira.reactos.org/browse/CORE-18275)
- Add `GetDlgItemTextAlloc` and `GetComboBoxLBTextAlloc` helper functions.
- Get the text data correctly even if the text length is zero.
BEFORE:
AFTER:
=> [USRMGR] Get text correctly even if the length is zero

base/applications/mspaint/atlimagedx.h, base/applications/mspaint/dib.cpp, base/applications/mspaint/precomp.h, base/applications/mspaint/winproc.cpp, sdk/lib/atl/atlimage.h
Send obsolete functions to Hell and improve compatibility.
- Rewrite `CImageDx` to reduce improper dependency with `CImage`.
- Check if the filename extension is supported before saving the files.
- Delete deprecated functions in `CImage`.
=> [MSPAINT][ATL] Delete deprecated functions

dll/win32/shlwapi/ordinal.c, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
Follow-up to #5531. These two functions are necessary for INI file property bag support.
- Implement `SHGetIniStringW` and `SHSetIniStringW`.
- Strengthen `SHPropertyBag` testcase of `shlwapi_apitest.exe`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] SHGetIniStringW/SHSetIniStringW

base/shell/cmd/lang/cs-CZ.rc, base/shell/cmd/lang/en-US.rc, base/shell/cmd/lang/sk-SK.rc, base/shell/explorer/traywnd.cpp, dll/cpl/main/mouse.c, dll/win32/devmgr/devmgmt/DeviceView.cpp, dll/win32/shell32/lang/bg-BG.rc, dll/win32/shell32/lang/ca-ES.rc, dll/win32/shell32/lang/cs-CZ.rc, dll/win32/shell32/lang/da-DK.rc, dll/win32/shell32/lang/el-GR.rc, dll/win32/shell32/lang/en-GB.rc, dll/win32/shell32/lang/en-US.rc, dll/win32/shell32/lang/fi-FI.rc, dll/win32/shell32/lang/he-IL.rc, dll/win32/shell32/lang/it-IT.rc, dll/win32/shell32/lang/ko-KR.rc, dll/win32/shell32/lang/nl-NL.rc, dll/win32/shell32/lang/no-NO.rc, dll/win32/shell32/lang/pt-BR.rc, dll/win32/shell32/lang/sk-SK.rc, dll/win32/shell32/lang/sl-SI.rc, dll/win32/shell32/lang/sq-AL.rc, dll/win32/shell32/lang/sv-SE.rc, modules/rosapps/applications/cmdutils/vfdcmd/vfdmsg.mc, modules/rosapps/applications/net/tsclient/rdesktop/uiports/qtewin.cpp, sdk/include/reactos/mc/errcodes.mc, sdk/include/reactos/mc/ntstatus.mc, sdk/lib/drivers/wdf/shared/inc/private/common/fxobject.hpp, win32ss/user/ntuser/msgqueue.c
Fix spellings for consistency in source code.
Replaces PR #5503 with a narrower scope. Checked it doesn't affect third-party files [(1)](https://github.com/reactos/reactos/blob/master/media/doc/3rd%20Party%20Files.txt),[(2)](https://github.com/reactos/reactos/blob/master/media/doc/WINESYNC.txt).
Fixes:
- Unassociate.
- Read-only.
- Double-click.
=> [REACTOS] Spelling fixes

base/applications/calc/winmain.c, base/applications/clipbrd/clipbrd.c, base/applications/mplay32/mplay32.c, base/applications/mscutils/eventvwr/eventvwr.c, base/applications/mscutils/servman/mainwnd.c, base/applications/mspaint/winproc.cpp, base/applications/osk/main.c, base/applications/rapps/gui.cpp, base/applications/sndrec32/sndrec32.cpp, base/applications/taskmgr/about.c, dll/win32/devmgr/devmgmt/MainWindow.cpp
Do not free shared icons, ReactOS ShellAbout() calls part.
JIRA issue: [CORE-18369](https://jira.reactos.org/browse/CORE-18369)
- Remove unwanted `DeleteObject()` and `DestroyIcon(()` calls.
Wine ieframe case will be handled separately/later.
=> [APPLICATIONS][DEVMGR] Do not free shared icon for ShellAbout() calls

base/applications/mspaint/dialogs.cpp
Improve keyboard usability.
JIRA issue: [CORE-18011](https://jira.reactos.org/browse/CORE-18011)
- Return `TRUE` on `WM_INITDIALOG` handling to set focus.
- Check if the radiobutton is checked on the radiobutton action (considering `BN_SETFOCUS` etc.).
=> [MSPAINT] Fix focus and radiobuttons of some dialogs

dll/win32/browseui/shellfind/CFindFolder.cpp
JIRA issue: [CORE-19110](https://jira.reactos.org/browse/CORE-19110)
- Use `CoInitializeEx` and `CoUninitialize` in `CFindFolder::SearchThreadProc`.
=> [BROWSEUI] Don't forget to CoInitializeEx on COM thread

win32ss/user/ntuser/sysparams.c
Fixes the behavior of the `SPI_SETFONTSMOOTHING` system parameter. This also fixes a bug when trying to select "Use the following method to smooth edges of screen fonts" in `desk.cpl`.
JIRA issue: [CORE-19092](https://jira.reactos.org/browse/CORE-19092)
- Instead of checking if `uiParam` is equal to two, treat `uiParam` as a Boolean that sets font smoothing on or off. This is the correct behavior according to [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow#SPI_SETFONTSMOOTHING).
- Use `SpiStoreSzInt` method instead of `SpiStoreSz` to store the value in the registry.
- Get font smoothing working in more windows
=> [NTUSER] Fix SPI_SETFONTSMOOTHING behavior

configure.cmd
Remove the warning when using `ninja` as a configure option
JIRA issue: [CORE-19059](https://jira.reactos.org/browse/CORE-19059)
=> [CONFIGURE] Fix using ninja as a configure option

dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, dll/win32/shell32/wine/shellord.c
- Implement `SHFindComputer` function in `utils.cpp`.
=> [SHELL32] Implement SHFindComputer

.github/workflows/build.yml
When downloading artifacts from Github Actions it's not known which artifacts use what dllver.
JIRA issue: [CORE-11288](https://jira.reactos.org/browse/CORE-11288)
- Add `matrix.dllver` before `github.sha` in artifact names.
- Add missing `-DDLL_EXPORT_VERSION=${{matrix.dllver}}` to build-linux Configure step
=> [GITHUB] Add dllver to artifact name

.github/workflows/build.yml
GitHub is starting to Discontinue Actions V2 (the date was postponed), when they enforce Actions V3 builds will probably fail to run, so its better to change this sooner rather than later.
This also silences/fixes the warnings on the builds/artifacts page
- Update Actions (`cache`, `checkout`, `upload-artifact`) to V3
- Replace `set-output` with `$GITHUB_OUTPUT`
=> [GITHUB] Update Github actions to V3 and replace deprecated set-output

sdk/lib/atl/atlimage.h
Improve compatibility.
JIRA issue: [CORE-19008](https://jira.reactos.org/browse/CORE-19008)
- Add `CInitGDIPlus` subclass in `CImage`.
- Lock the `CInitGDIPlus` data by using a critical section.
- Add `CImage::InitGDIPlus` and use it.
BEFORE:
AFTER:
=> [ATL] Make CImage thread-safe

dll/cpl/appwiz/addons.c
JIRA issue: [CORE-19110](https://jira.reactos.org/browse/CORE-19110), [CORE-15786](https://jira.reactos.org/browse/CORE-15786)
- Do `CoInitializeEx` and `CoUninitialize` in `download_proc`.
=> [APPWIZ] Don't forget to CoInitializeEx on COM thread

dll/win32/kernel32/client/proc.c, modules/rostests/winetests/kernel32/process.c
When creating a new process the monster function CreateProcessInternalW calls BaseInitializeContext to set up the context for the initial thread. One of the parameters is the PEB pointer. Instead of passing the pointer to the newly created process' PEB, the function was passing its own PEB address, leading to test failures. How this is not an issue otherwise is a mystery to be resolved by someone else. Also remove ros_skip_flaky marks in kernel32_winetest:process (yes, flaky, because sometimes the PEB addresses actually match)
Test KVM: https://reactos.org/testman/compare.php?ids=88924,88926,88931,88934,88939
=> [KERNEL32] Fix startup context of initial thread

dll/win32/kernel32/client/proc.c
Trivial consistency/optimization.
Addendum to d81cd01 (r59637).
- Use Peb variable.
=> [KERNEL32] CreateProcessInternalW(): Always use Peb variable

dll/win32/msafd/misc/dllmain.c, dll/win32/msafd/misc/sndrcv.c
Currently ReactOS' winsock2 implementation lacks of non-blocking sockets support for recv() apicall, this causes that applications that make use of this feature can lead to unexpected behaviors, one of them is Nginx web server, which uses non-blocking sockets when serving pages through Https protocol.
JIRA issue: [CORE-14486](https://jira.reactos.org/browse/CORE-14486)
According to MSDN:
1) new sockets created by accept() should inherit listening socket properties, but we're ignoring if it is a non-blocking socket.
2) recv() apicall must return SOCKET_ERROR and set last error to WSAEWOULDBLOCK when the socket is non-blocking and there is still no data to read.
=> [MSAFD] Fix non-blocking sockets support for recv()

modules/rostests/apitests/atl/CImage.cpp, modules/rostests/apitests/atl/devenv/.gitignore, modules/rostests/apitests/atl/devenv/CImage.vcxproj, sdk/lib/atl/atlimage.h
Improve compatibility of `CImage`.
JIRA issue: [CORE-19008](https://jira.reactos.org/browse/CORE-19008)
- Improve `CImage` testcase of `atl_apitest.exe`.
- Improve `CImage::BuildCodecFilterString`.
Visual Studio 2015 in Win10:
Successful.
Win10 (AFTER):
Successful.
WinXP (AFTER):
Successful.
Win2k3 (AFTER):
Successful.
=> [ATL_APITEST][SDK] Fix failures of CImage testcase

base/applications/mspaint/dib.cpp, base/applications/mspaint/dib.h, base/applications/mspaint/history.cpp
Follow-up to #5554.
- Speed up `ImageModel::PushBlackAndWhite` by using `GetDIBits` and `SetDIBits`.
The bitmap conversion of 5000x5000 pixels takes 3 seconds on x64 Win10.
=> [MSPAINT] Speed up for black and white

dll/win32/kernel32/kernel32.spec, dll/win32/kernel32/winnls/string/lang.c, sdk/include/ndk/rtlfuncs.h
Add CompareStringOrdinal from wine-3.21
Why 3.21? Because that is the state that this file is at. Except for all the useless hackery.
=> [KERNEL32] Add CompareStringOrdinal from wine-3.21

modules/rostests/kmtests/tcpip/TcpIp_user.c
On x64 the test sometimes fails to connect and then times out on the testbot, causing the system to be rebooted.
=> [KMTEST:TcpIp] Use 10 second timeout value instead of INFINITE

dll/win32/shlwapi/ordinal.c, dll/win32/shlwapi/propbag.cpp, dll/win32/shlwapi/shlwapi_main.c, sdk/include/psdk/shlwapi.h
Follow-up to #5590. Implementing missing features...
- Add `CViewStatePropertyBag` class.
- Add `SHGetViewStatePropertyBag` definition.
- Add `FreeViewStatePropertyBagCache` function and use it in `DllMain` to free the cache.
=> [SHLWAPI][SDK] Implement SHGetViewStatePropertyBag Part 1

sdk/tools/mkisofs/CMakeLists.txt
mkisofs and its components uses K&R-style function definitions to support very old compilers. Modern compilers consider K&R syntax to be deprecated. Clang therefore emits a large number of warnings over this. Supplants #5600.
- Add `-Wno-deprecated-non-prototype` compiler flag to mkisofs and its support libraries
=> [MKISOFS] Silence prototype warnings

win32ss/reactx/dxgthk/dxgthk.spec
Use two longs instead of one for the first parameter of `EngCreateBitmap` export. Make it same as win32k export. MSDN documentation says that 1st parameter is `SIZEL` (`SIZE`) structure, which actually contains 2 longs inside. Sice it is passed by value, it needs to take enough memory when export in dxgthk and redirect to win32k (since it's actually a win32k function).
Fixes the compilation of our dxg.sys when calling dxgthk!`EngCreateBitmap` from it. Found during my DirectX investigations.
Small addendum to #5604 PR.
=> [DXGTHK] Fix EngCreateBitmap exported parameters

ntoskrnl/include/internal/se.h, ntoskrnl/se/accesschk.c, ntoskrnl/se/debug.c, ntoskrnl/se/sid.c
As the commit title says. Instead of having the caller figuring out what the ACE type should be of the ACE.
=> [NTOS:SE] Let SepGetSidFromAce figure out the ACE type

base/applications/taskmgr/perfpage.c, base/applications/taskmgr/taskmgr.c, base/applications/taskmgr/taskmgr.h
Following PR #5571 (commit 2d53e95), it became apparent that the management of the status bar when showing the menu hints could be simplified further.
Use "simple-text" status-bar display mode when showing menu hints.
The original status-bar panes state is "remembered" and are automatically restored when the "simple-text" mode is disabled.
JIRA issue: [CORE-19061](https://jira.reactos.org/browse/CORE-19061)
(I would however recommend to merge this PR *after* PR #5573 that would exercise the previous code that works on Windows as well.)
=> [TASKMGR] Simplify status-bar display when menus are shown

dll/win32/shlwapi/propbag.cpp
Follow-up to #5605. Implementing missing features...
- Add some code into `CViewStatePropertyBag::Read` and `CViewStatePropertyBag::_GetRegKey`.
- Add some helper functions.
=> [SHLWAPI] Implement SHGetViewStatePropertyBag Part 2

dll/win32/advapi32/advapi32.spec, dll/win32/advapi32/wine/security.c, sdk/include/psdk/winbase.h
With #5361 now merged, the Win32 variant of access check functions can now use the following NT syscalls.
=> [ADVAPI32] Implement AccessCheckByType and AccessCheckByTypeResultList

dll/win32/shlwapi/propbag.cpp, dll/win32/shlwapi/shlwapi.spec, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp, sdk/include/reactos/shlwapi_undoc.h
- Implement `SHGetPerScreenResName` function.
- Modify `shlwapi.spec` and `<shlwapi_undoc.h>`.
- Add some tests to `SHPropertyBag` testcase of `shlwapi_apitest.exe`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
=> [SHLWAPI][SHLWAPI_APITEST][SDK] Implement SHGetPerScreenResName

dll/win32/shell32/droptargets/CRecyclerDropTarget.cpp, dll/win32/shell32/droptargets/CexeDropHandler.cpp
Plug an (apparent) memory leak.
Add missing `GlobalUnlock()` calls to balance `GlobalLock()`.
=> [SHELL32] Add two missing GlobalUnlock() calls

dll/win32/shell32/shlfileop.cpp
Confirm overwriting on moving files.
JIRA issue: [CORE-18910](https://jira.reactos.org/browse/CORE-18910)
- Add `move_file_to_file` helper function.
- Modify `move_to_dir` and `move_files` helper functions.
AFTER:
=> [SHELL32] SHFileOperation: Confirm overwrite on moving files

dll/win32/comctl32/propsheet.c
Fix the initial position of the property sheet dialog.
JIRA issue: [CORE-19141](https://jira.reactos.org/browse/CORE-19141)
- On `WM_INITDIALOG` handling of the property sheet dialog procedure, move the dialog if necessary.
Win2k3:
https://github.com/reactos/reactos/assets/2107452/1fc973e8-4f17-47c1-b961-48efc66cbbfd
BEFORE:
https://github.com/reactos/reactos/assets/2107452/afd1ef52-56c0-4b6b-a714-fa1875fab399
AFTER:
https://github.com/reactos/reactos/assets/2107452/bc350650-1cd2-4c24-8fee-94db08e4584e
=> [COMCTL32] Fix Property Sheet initial position

dll/win32/browseui/shellbrowser.cpp, sdk/include/reactos/shlwapi_undoc.h
- Add `_ILIsNetworkPlace` helper function.
- Implement `CShellBrowser::GetPropertyBag` function a little by using `SHGetViewStatePropertyBag`.
- Add `SHGetPathFromIDListWrapW` prototype to `<shlwapi_undoc.h>`.
=> [BROWSEUI][SDK] Half-implement CShellBrowser::GetPropertyBag

base/applications/notepad/dialog.c, base/applications/notepad/main.c
Use preferred string functions.
- Use `<strsafe.h>`'s `StringCchPrintf` function instead of `_sntprintf` and `_stprintf`.
=> [NOTEPAD] Use StringCchPrintf instead of _stprintf etc.

dll/apisets/api-ms-win-crt-time-l1-1-0.spec, dll/win32/msvcrt/msvcrt.spec
These two functions are implemented in our CRT, but still listed as stubs in the spec file. This function came up when I was unsuccessfully trying to get my VM’s guest tools running on ReactOS. (I am a Mac user, so I cannot use VirtualBox. I use an app called [UTM](https://getutm.app/), which is a variant on QEMU.)
- Remove stub notation for `localtime32` and `localtime32_s` symbols in msvcrt.spec.
=> [MSVCRT] Officially implement _localtime32{,_s}

base/applications/notepad/dialog.c, base/applications/notepad/main.c
- Do type cast to `int` from `SendMessage` return value.
- Fix usage of `EM_GETSEL` and `EM_LINEINDEX` messages.
=> [NOTEPAD] Do type cast to kill C4244 warnings

ntoskrnl/cc/view.c, ntoskrnl/mm/balance.c
_MM/CC Add back CcRosTrimCache as suggested by Thomas Faber which was removed in [0.4.15-dev-1717-gd8cdb89](https://github.com/reactos/reactos/commit/d8cdb89fb03006595dc40ac23db5267b8d9d9c09)._
JIRA issue: [CORE-17624](https://jira.reactos.org/browse/CORE-17624)
This PR replaces PR #5237 that was not able to be committed.
It had an extra priority boost which, according to some developers, needs more discussion.
The author of the previous PR #5237 did not act on my request for it to be closed either.
This one contains a new delay in the Page Allocate code to allow the MM time to recover cached pages.
According to @JoachimHenze this PR fixes all of the problems with [CORE-17624](https://jira.reactos.org/browse/CORE-17624).
66248_CORE-17624...patch JID66248 on top of …
=> [NTOS:CC][NTOS:MM] Add back CcRosTrimCache and add Delay for MM to recover memory

modules/rostests/winetests/winhttp/winhttp.c
_On receiving a zero length response, do not try to print returned text using wine_dbgstr_wn._
JIRA issue: [ROSTESTS-377](https://jira.reactos.org/browse/ROSTESTS-377)
_Check for zero length text returned and skip trying to print unmatched received text returned._
=> [WINHTTP_WINETEST] Skip using wine_dbgstr_wn when returned text length is zero

ntoskrnl/ke/amd64/thrdini.c
The function set CtxSwitchFrame->ApcBypass to FALSE, preventing APCs (like when user mode sets the context while the thread is suspended) from being delivered as soon as the thread lowers IRQL to PASSIVE_LEVEL. This resulted in the SetContext APC to be delivered only after the user mode APC was initialized, overwriting the user mode APC context in the trap frame. This caused kernel32_winetest process to break.
=> [NTOS:KE/x64] Fix bug in KiInitializeContextThread

modules/rostests/apitests/atl/CImage.cpp, modules/rostests/apitests/atl/devenv/CImage.vcxproj, sdk/lib/atl/atlimage.h
JIRA issue: [ROSTESTS-387](https://jira.reactos.org/browse/ROSTESTS-387), [CORE-19008](https://jira.reactos.org/browse/CORE-19008)
- Strengthen `CImage` testcase and improve `CImage` class.
- Cover all the BPPs.
- Cover all the bitmap/image formats on `CImage` testcase.
- Cover both top-down and bottom-up.
Visual Studio 2019 MS ATL:
Successful.
WinXP ROS ATL:
Successful.
Win2k3 ROS ATL:
Successful.
Win10 ROS ATL:
Successful.
ReactOS AFTER:
Some failures... They are not my faults.
=> [ATL][ATL_APITEST] CImage testcase should cover all formats

ntoskrnl/mm/ARM3/procsup.c, win32ss/gdi/eng/mapping.c
Fix a call to MmMapViewOfSection. It was passing 0 instead of SECTION_INHERIT ::ViewUnmap (2). 0 isn't even a proper constant to be used here. It worked, because MmMapViewOfSection only compares against ViewShare (1) and treats everything else as ViewUnmap.
=> [WIN32SS:ENG] Fix parameter to MmMapViewOfSection

sdk/lib/atl/atlimage.h
Reduce code duplicates.
JIRA issue: [CORE-19008](https://jira.reactos.org/browse/CORE-19008)
- Use `const_cast<CImage*>` against `this`.
- Call the non-`const` function.
=> [ATL] CImage: Simplify GetBits/GetPixelAddress

win32ss/user/ntuser/msgqueue.c
Silence two of the most debug log spammers by changing from ERR to WARN.
=> [NTUSER] Silence debug log spam

dll/opengl/mesa/misc.c
Trivial change to fix the [failing](https://reactos.org/testman/detail.php?id=66691804&prev=0) OpenGL `sw_extensions` test.
Test expects `1.1.0` and the version of Mesa ReactOS has was set to report `1.1`, windows also reports `1.1.0` per the [comment here](https://github.com/reactos/reactos/pull/3228#issuecomment-830666418).
=> [MESA] Change reported version to 1.1.0

dll/win32/getuname/getuname.rc
This massively cuts down build time on MSVC builds.
Build times without this patch:
- [GCC x86](https://build.reactos.org/#/builders/9/builds/34610): 1:06
- [MSVC x86](https://build.reactos.org/#/builders/1/builds/22187): 14:51
- [MSVC x64](https://build.reactos.org/#/builders/8/builds/8508): 13:40
Build times with this patch:
- [GCC x86](https://build.reactos.org/#/builders/9/builds/34611): 58 s
- [MSVC x86](https://build.reactos.org/#/builders/1/builds/22188): 6:44
- [MSVC x64](https://build.reactos.org/#/builders/8/builds/8509): 5:30
=> [GETUNAME] Build only english on DBG builds

modules/rostests/apitests/kernel32/InitOnce.c
Fixes stack corruption on x64 and adds an additional test case.
=> [KERNEL32_APITEST] Fix and improve InitOnce test

base/applications/notepad/dialog.c, base/applications/notepad/dialog.h, base/applications/notepad/main.c, base/applications/notepad/printing.c
Using the proper cursors improves user experience.
This PR is a reaction to "Independent ReactOS Notepad": https://github.com/katahiromz/RNotepad/issues/1
- Add `WaitCursor` helper function to display the wait cursor while heavy operation.
- Manage the wait cursor by using a lock count.
=> [NOTEPAD] Use wait cursor

base/applications/mspaint/canvas.cpp, base/applications/mspaint/dib.cpp, base/applications/mspaint/precomp.h, base/applications/mspaint/textedit.cpp, base/applications/mspaint/waitcursor.h, base/applications/mspaint/winproc.cpp
A wait cursor informs the user that the app is currently busy.
- Implement `CWaitCursor` class in newly-added `"waitcursor.h"`.
- Use `CWaitCursor` to manage the wait cursor.
- Improve `WM_SETCURSOR` handlings.
=> [MSPAINT] Use wait cursor

win32ss/user/user32/controls/combo.c
We missed to sync the [USER32] combo.c code when we committed the fix for
JIRA issue: [CORE-17883](https://jira.reactos.org/browse/CORE-17883) into [COMCTL32} combo.c
First commit does that and is the only one with functional changes, a pure addendum to ff89651 .
Second commit reduces pure whitespace-diff between the two files, no functional change.
This fixes tons of mixed tab-whitespace-indentation and also simplifies future syncs between those 2 files.
**Please refrain from any whitespace nitpicks in this PR, as this is to 100% a sync to the other file!**
=> [USER32] Comctl32 combo.c to user32 combo.c sync

win32ss/gdi/ntgdi/bitblt.c
According to the results of `CImage` testcase, the top byte of the `GetPixel()` return value is zero if the return is a valid color.
JIRA issue: [CORE-19008](https://jira.reactos.org/browse/CORE-19008)
- Do bitwise-AND operation if the color value is valid.
=> [NTGDI] GetPixel's return top byte is zero if valid

win32ss/user/ntuser/window.c
The error messsage of `co_UserCreateWindowEx` function was unfriendly to the debugger.
- Show the window class name by using `"%wZ"` in `co_UserCreateWindowEx` function.
=> [NTUSER] Error of co_UserCreateWindowEx should display class name

dll/win32/shell32/CDefView.cpp, sdk/lib/atl/atlwin.h
`WM_SIZE` message can come before `WM_CREATE` message. That's a dangerous trap.
`comdlg32:filedlg` sometimes had hit the assertion failure on `CWindow::SendMessage`.
JIRA issue: [ROSTESTS-388](https://jira.reactos.org/browse/ROSTESTS-388)
- Assert the listview control `m_ListView` existence on `CDefView::LV_...` functions.
- Actually check the `m_ListView` existence on the outside of `CDefView::LV_...` functions.
=> [SHELL32] Check m_ListView on some methods

dll/directx/wine/ddraw/ddraw_private.h, dll/directx/wine/ddraw/palette.c, dll/directx/wine/ddraw/surface.c, media/doc/WINESYNC.txt
Proposal to temporarily revert 67559215608eaf7338cbc7002ba3b74bf972a3a4.
As stated in the the ticket me and a few discord community members have noticed for awhile now that ReactOS's DirectX has been acting a little weird. Only during my investigations into syncing modern WINE did I realize the extent of what was happening and what was going on. 
This PR is to fix one of the biggest problem we're running into; Many ddraw games currently don't seem to update the entire surface anymore. During a bisection we found out it ended up being since this commit was introduced. Attached below is a picture of how games looked (If they launched at all).
I propose we temporarily revert this and reassign [CORE-18547](https://jira.reactos.org/browse/CORE-18547) to me as I continue to sync and update wine …
=> [DDRAW] Revert 67559215608eaf7338cbc7002ba3b74bf972a3a4. CORE-19167

sdk/lib/crt/stdio/file.c
Fixes advpack_apitest:DelNode crash.
If we properly synced this code, instead of forking it, we wouldn't have this crash.
JIRA issue: [CORE-19172](https://jira.reactos.org/browse/CORE-19172)
=> [CRT] Import parameter check for fclose from wine

ntoskrnl/ke/amd64/trap.S
Don't safe anything in the callee's home space, because the callee can overwrite it. Use the functions home space instead.
This affects optimized builds.
=> [NTOSKRNL/x64] Fix a bug in KeSwitchKernelStack

win32ss/user/ntuser/cursoricon.c
Use IS_INTRESOURCE to check whether a unicode string captured by ProbeAndCaptureUnicodeStringOrAtom and don't try to free it, if it is.
=> [WIN32K] Do not try to free a unicode string that is an int-resource

modules/rostests/win32/user32/kbdlayout/kbdlayout.c
- Avoid DLGPROC-cast
- Bring header-section closer to our coding guidelines
- Strip inconsistent empty-lines
- Strip useless return at the end of void func
=> [KBDLAYOUT] Avoid (DLGPROC) cast

dll/win32/shlwapi/propbag.cpp, modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/SHPropertyBag.cpp
https://reactos.org/testman/detail.php?id=66922401&prev=0
```txt
SHPropertyBag.cpp:836: Test failed: Wrong string. Expected '1024x768(1)', got '1024x719(1)'
```
- Use `HORZRES` and `VERTRES` instead of `SM_CXFULLSCREEN` and `SM_CYFULLSCREEN`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
=> [SHLWAPI][SHLWAPI_APITEST] Fix SHGetPerScreenResName

sdk/lib/atl/atlwin.h
Fix warnings when dwInitParam was omitted at `CDialogImpl::Create` and/or `CDialogImpl::DoModal`.
=> [ATL] Default value of dwInitParam is zero instead of NULL

sdk/include/ddk/wsk.h
Names need decoration (stdcall) in order to be linked.
When using the wsk.h header functions exported therein should
be WSKAPI (which enforces the stdcall calling convention). Linking
would later fail because stdcall functions are named differently in
the object code.
Just add WSKAPI (which expands to stdcall depending on compiler
used) to  the exported functions.
=> [DDK] wsk header: Added WSKAPI to exported functions.

modules/rostests/apitests/atl/CComObject.cpp, modules/rostests/apitests/atl/CComQIPtr.cpp, sdk/lib/atl/atlsimpstr.h, sdk/lib/atl/atlwin.h
This is an attempt to make ReactOS ATL (RATL) independent.
If RATL got independent, then MSPAINT and RAPPS will be also able to be independent.
It will improve interoperability and compatibility, and gain user feedbacks ([like this](https://github.com/katahiromz/RNotepad/issues/1)).
See also: https://github.com/katahiromz/RATL
JIRA issue: [CORE-19153](https://jira.reactos.org/browse/CORE-19153)
- Avoid conflict of `CAtlExeModuleT` when `__RATL__` is defined.
- Add workaround of `DECLARE_QIPTR` when `__RATL__` is defined.
- Add workaround of `_In_count_` and `_Post_z_` when `__RATL__` is defined.
- No actual code change unless `__RATL__` is defined.
=> [ATL][ATL_APITEST] Independent ReactOS ATL (RATL) support

boot/boot_images.cmake
Create the folder TEMP in X:\reactos so now we can match current livecd environment variables TMP and TEMP
May apply to [CORE-13041](https://jira.reactos.org/browse/CORE-13041)
=> [BOOTDATA] Add TEMP folder to livecd image

dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, sdk/include/psdk/shlobj.h
This PR supersedes PR #3851.
JIRA issue: [CORE-17707](https://jira.reactos.org/browse/CORE-17707)
Co-authored-by: Oleg Dubinskiy <oleg.dubinskij30@gmail.com>
- Implement `SHGetShellStyleHInstance` function.
- Add `SHGetShellStyleHInstance` prototype to `<shlobj.h>`.
=> [SHELL32][SDK] Implement SHGetShellStyleHInstance

win32ss/reactx/dxgthk/dxgthk.spec
Export driver entry point function `DriverEntry` from our dxgthk.sys. It does not improve anything so much, it just mimics Windows behaviour. Just do it the same in ReactOS as it's done in Windows. Confirmed that it is exported on Windows XP SP3 at least. See attached screenshot. :slightly_smiling_face: 
Small addendum to #5604 PR.
=> [DXGTHK] Export DriverEntry

dll/win32/kernel32/client/except.c
Fixes C++ exception handling on x64.
=> [KERNEL32] Fix RaiseException to correctly copy the passed in parameters as ULONG_PTR

win32ss/user/ntuser/window.c
Check whether Flink is NULL before removing a window from a linked list. This can happen on failure in IntCreateWindow, but I have seen it from a different path, so there are more issues here. It's a hackfix, but it makes win32k a tiny bit less crashy.
=> [WIN32K] Prevent dereferencing NULL pointer

base/applications/mspaint/winproc.cpp
Fix the graphical glitches on resizing and moving toolbars.
JIRA issue: [CORE-19137](https://jira.reactos.org/browse/CORE-19137)
- Add `SWP_NOCOPYBITS` flag on positioning controls on resizing of main window.
BEFORE:
There were some glitches.
AFTER:
FIXED.
=> [MSPAINT] Don't copy bits on resizing

base/applications/mspaint/history.cpp, base/applications/mspaint/history.h, base/applications/mspaint/main.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/selectionmodel.h, base/applications/mspaint/winproc.cpp
JIRA issue: [CORE-19181](https://jira.reactos.org/browse/CORE-19181), [CORE-19182](https://jira.reactos.org/browse/CORE-19182)
- Reduce display of error message on `IDM_EDITCOPYTO` and `IDM_EDITPASTEFROM` command actions.
- Introduce `LockBitmap`/`UnlockBitmap` mechanism for `ImageModel` and `SelectionModel`.
=> [MSPAINT] Don't show error message twice

dll/win32/rpcrt4/msvc.S
movaps is a 128 bit aligned move, we need a 64 bit unaligned move, so use movsd. Fixes a crash in oleaut32_winetest tmarshal.
=> [RPCRT4] Fix x64 assembly code

ntoskrnl/config/cmalloc.c
Triggered by low available pool memory during kmtest ExPools.
=> [NTOS:CM] Fix lock leak

dll/win32/shell32/shlexec.cpp, modules/rostests/apitests/shell32/ShellExecuteEx.cpp
_Revert https://github.com/reactos/reactos/commit/0f16d44b660266130f5c0807c01d01cfaa6e685d._
JIRA issue: [CORE-18967](https://jira.reactos.org/browse/CORE-18967)
_Add conditional 'if' to code so that it is only executed when needed._
[shlexec-cpp-05.patch](https://jira.reactos.org/secure/attachment/65772/65772_shlexec-cpp-05.patch) JID65772 on top of 0.4.15-dev-6010-g30bc0b6
VBox: https://reactos.org/testman/compare.php?ids=87117,87120 LGTM
KVM: https://reactos.org/testman/compare.php?ids=87116,87119 LGTM
All three (3) "blocks" issues checked and appear OK.
=> [SHELL32] Fix for shlexec.cpp regressions

base/applications/mspaint/common.h, base/applications/mspaint/dib.cpp, base/applications/mspaint/drawing.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/precomp.h, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h
- While holding down the `Shift` key, drawing lines with the pen/brush is limited to either of 8 directions (horizontal/vertical/diagonal).
- `s/abs/labs/`
=> [MSPAINT] Restrict drawing direction on Shift key

dll/win32/lsasrv/lsarpc.c, dll/win32/samsrv/samrpc.c, ntoskrnl/include/internal/se.h, sdk/lib/rtl/sd.c
Fixes crash of netapi32_winetest access on x64
Testbot:
- x86 KVM: https://reactos.org/testman/compare.php?ids=89792,89797
- x64 KVM: https://reactos.org/testman/compare.php?ids=89786,89791 (netapi32:access crash fixed, the rest is random)
=> [SAMSRV] Fix SamrQuerySecurityObject on x64

drivers/wdm/audio/drivers/CMIDriver/cmicontrol/main.cpp
Can be observed on the buildbots:
2023-09-17T14:19:34.2051345Z [10663/14808] Building CXX object drivers\wdm\audio\drivers\CMIDriver\cmicontrol\CMakeFiles\cmicontrol.dir\main.cpp.obj 2023-09-17T14:19:34.2052611Z D:\a\reactos\reactos\src\drivers\wdm\audio\drivers\CMIDriver\cmicontrol\main.cpp(818): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
=> [CMICONTROL] Fix MSVC 14.2 dbg x64 warning C4267

ntoskrnl/mm/i386/page.c
Test for the highest bit, not for bit 3 / 7.
=> [NTOS/Mm] Fix SWAPENTRY bit-check in MmCreatePageFileMapping

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/history.cpp, base/applications/mspaint/history.h, base/applications/mspaint/mouse.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/selectionmodel.h, base/applications/mspaint/winproc.cpp
Implement missing "Selection Clone" and "Selection Brush" features.
- Stamp the image of the selection when the user clicks on the selection while holding down the `Ctrl` key.
- Draw the image of the selection continuously when the user starts dragging the selection while holding down the `Shift` key.
=> [MSPAINT] Selection Clone and Selection Brush

base/applications/mspaint/drawing.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/toolbox.cpp, base/applications/mspaint/toolbox.h, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h
Make the pen nib bigger or smaller.
- Introduce the concept of pen width (not line width) to the tools model.
- Enable changing pen/line width by `Ctrl+Plus/Minus` key combination in `TOOL_PEN`, `TOOL_LINE`, `TOOL_BEZIER`, `TOOL_RECT`, `TOOL_SHAPE`, `TOO_ELLIPSE`, and `TOOL_RRECT` tools.
=> [MSPAINT] Larger/smaller pen nib on Ctrl+Plus/Minus

ntoskrnl/config/cmalloc.c
Use similar code pattern as `CmpAllocateKeyControlBlock()`.
Note:
Code was added as is on r29954.
- Remove duplicate CmpDelayAllocBucketLock definition.
- Remove an else.
=> [NTOS:CM] Simplify CmpDelayAllocBucketLock code a bit

boot/freeldr/freeldr/CMakeLists.txt, boot/freeldr/freeldr/arch/uefi/uefidisk.c, boot/freeldr/freeldr/arch/uefi/uefildr.c, boot/freeldr/freeldr/cmdline.c, boot/freeldr/freeldr/lib/fs/fat.c, sdk/include/crt/vadefs.h, sdk/include/ndk/arm64/ketypes.h, sdk/lib/3rdparty/freetype/CMakeLists.txt
- Made FreeLoader compile and boot on ARM64
- Fixes crashes in functions with varargs caused by wrong va_defs ([MSVC ARM64 definitions have been sourced from here](https://github.com/microsoft/mu_basecore/blob/c3baf893e5380a48b3c4856bd169ad5fa98795b7/MdePkg/Include/Base.h#L657))
- Fixes 512 byte sector size assumption in FAT filesystem driver
- Added some fixes to SDK to get a bunch of other things to compile properly.
=> [FREELDR][SDK] ARM64 FreeLoader bringup + fixes

modules/rostests/winetests/ntdll/reg.c, ntoskrnl/config/cmkcbncb.c, ntoskrnl/config/cmparse.c, ntoskrnl/config/cmse.c, ntoskrnl/config/cmsysini.c, ntoskrnl/include/internal/cm.h, ntoskrnl/include/internal/cm_x.h
ReactOS implements a cache feature for the registry thanks to `CmpCacheTable` and various functions that handle it. With this, registry data can be cached on respective key control blocks (KCBs) so that such data can be acquired quickly. Except that the cached data isn't quite consistent.
The reason why the cache can become inconsistent is because we don't properly clean the subkey's information, such as when we are creating a link node or a new key. As a result the cached data can get out of sync and such data in a KCB might not reflect with the actual data of the subkey itself. Moreover, we barely do any cache lookup which means if a key path component is already in cache we will not ever acknowledge that. This PR, together with #4571, it embodies the "registry data integrity" goal …
=> [NTOS:CM] Implement registry cache lookup & enforce cache consistency

base/shell/explorer/syspager.cpp, dll/win32/comctl32/tooltips.c
Before
After
JIRA issue: [CORE-19109](https://jira.reactos.org/browse/CORE-19109)
- Set a maximum width for balloons coming from the system pager.
- Limit balloon tooltips from extending past the edges of the monitor, not the edges of the work area.
- Instead of simply repositioning the main rectangle when the balloon is too far towards one edge of the screen, try flipping the balloon the other way. This is the same behavior as Windows Server 2003.
- Tweak some values used to draw the balloon tooltips to more closely follow the Windows balloon tooltip style.
- Removing trailing whitespace.
- While the new changes are guarded, consider cancelling our Wine sync for common controls. Our common controls are responsible for many graphical issues and lack of features throughout ReactOS.
- Add a …
=> [COMCTL32] Fix balloon tooltips and system pager alerts

dll/win32/shell32/shlfolder.cpp
GetDetailsOf does not support the column flags used by CompareIDs.
As a side effect, also fixes LPARAM to UINT truncation on 64-bit.
=> [SHELL32] Do not call GetDetailsOf with CompareIDs flags

dll/ntdll/include/ntdllp.h, dll/ntdll/ldr/ldrapi.c, dll/ntdll/ldr/ldrutils.c, dll/win32/verifier/verifier.c, sdk/include/ndk/ldrfuncs.h, sdk/include/ndk/umfuncs.h
SAL improvements and fixes
- Uniform some notations in .c and .h, and use SAL2.
- `Name` parameter in `LdrGetProcedureAddress`/`LdrpGetProcedureAddress` should be optional, if it's NULL, `Ordinal` indicates the ordinal of the function to get.
- `DllCharacteristics` parameter in `LdrGetDllHandle` should be optional, if it's NULL, no extra flag specified.
=> [NTDLL:LDR] SAL improvements and fixes

base/applications/mspaint/mouse.cpp
Kill the assertion failure on choosing text tool.
- Check whether `textEditWindow` is not null by using `IsWindowVisible`.
=> [MSPAINT] Fix assertion failure on text tool

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/dib.cpp, base/applications/mspaint/history.cpp
The scroll info was not updated when the file is loading.
- Rename `CCanvasWindow::Update` as `CCanvasWindow::updateScrollInfo`.
- Update scroll info on `ImageModel::NotifyImageChanged`.
- Improve `ImageModel::ClearHistory`.
=> [MSPAINT] Update scroll info on loading file

drivers/ksfilter/ks/irp.c
Properly set output buffer length in IO Stack Location of the current IRP, since it is passed to KsProbeStreamIrp when calling KsStreamIo, so it fails if the length isn't set properly.
Don't set an input buffer length and the buffer itself, since it isn't passed anywhere, so setting it makes no sense. Moreover, MSDN says that for IOCTL_KS_READ/WRITE_STREAM, only output buffer (and its length) is needed to be set, but not an input one. So it indeed is more correct.
It fixes buffer overflow in KsProbeStreamIrp when attempting to perform the streaming via KsStreamIo. I discovered this bug during my audio refactoring from PR #4660.
=> [KS] Fix bug in KsStreamIo

base/applications/mspaint/mouse.cpp
JIRA issue: [CORE-19214](https://jira.reactos.org/browse/CORE-19214)
- Remove `PushImageForUndo` call in Zoom tool.
=> [MSPAINT] Zoom tool shouldn't use undo buffer

base/applications/mspaint/toolbox.cpp
Make tool box pixel-perfect.
JIRA issue: [CORE-19217](https://jira.reactos.org/browse/CORE-19217)
- Add two border widths to the tool box.
=> [MSPAINT] Add border width to tool box

base/applications/mspaint/canvas.cpp
JIRA issue: [CORE-19219](https://jira.reactos.org/browse/CORE-19219)
- Get the image rectangle by using `CCanvasWindow::GetImageRect`.
- Check out of the image by using `::PtInRect`.
- If out, then don't show the status bar text.
=> [MSPAINT] Check out of image in updating status bar

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/mouse.cpp, base/applications/mspaint/toolsettings.cpp, base/applications/mspaint/toolsettings.h
JIRA issue: [CORE-19215](https://jira.reactos.org/browse/CORE-19215), [CORE-19216](https://jira.reactos.org/browse/CORE-19216)
- Delete `CCanvasWindow::drawZoomFrame`.
- Invalidate the canvas on mouse move when the active tool is Zoom tool.
- Add `ZoomTool::OnDrawOverlayOnCanvas` to draw the zoom rectangle without flickering.
- Improve the zoom trackbar position.
- Display the zoom rate on changing the value of the zoom trackbar.
- Reverse the direction of the zoom trackbar.
- Don't draw the focus rectangle.
=> [MSPAINT] Improve Zoom tool

drivers/ksfilter/ks/irp.c
Properly initialize several IRP data, which is not filled correctly by PnP and setup I/O stack location for this IRP, before it's passed to the target driver's read/write routine via `IoCallDriver`, similarly to the way as it's done in `KsStreamIo`.
This fixes several problems when calling these functions from outside, so now they are working correctly, as expected.
Discovered during my audio investigations.
JIRA issue: [CORE-19232](https://jira.reactos.org/browse/CORE-19232)
- Initialize the rest of IRP data which is not initialized by `IoBuildSynchronousFsdRequest`.
- Setup an `IO_STACK_LOCATION` structure for the IRP before calling the driver's read/write routine.
- Do this for both `KsReadFile` and `KsWriteFile` functions in our Kernel Streaming driver (ks.sys).
=> [KS] KsRead/WriteFile: finish IRP initialization and properly setup I/O stack location for it

boot/freeldr/freeldr/arch/uefi/amd64/uefiasm.S, boot/freeldr/freeldr/arch/uefi/i386/uefiasm.S, boot/freeldr/freeldr/arch/uefi/stubs.c, boot/freeldr/freeldr/arch/uefi/ueficon.c, boot/freeldr/freeldr/arch/uefi/uefihw.c, boot/freeldr/freeldr/arch/uefi/uefildr.c, boot/freeldr/freeldr/arch/uefi/uefimem.c, boot/freeldr/freeldr/arch/uefi/uefisetup.c, boot/freeldr/freeldr/uefi.cmake
Finally allow UEFI FreeLoader to boot ReactOS kernel on our 2 primary architectures.
JIRA issue: [CORE-11954](https://jira.reactos.org/browse/CORE-11954)
- Implement remaining code needed to start kernel for i386 and amd64
=> [FREELDR] Enable UEFI boot for i386 and amd64. CORE-11954

base/applications/mspaint/main.cpp, base/applications/mspaint/precomp.h, base/applications/notepad/main.c, base/applications/notepad/notepad.h, base/applications/regedit/main.c, base/applications/regedit/regedit.h
Avoid using CRTDBG in these applications. This will reduce management cost.
- Don't include `<crtdbg.h>`.
- Don't use `_CrtSetDbgFlag`.
=> [MSPAINT][NOTEPAD][REGEDIT] Don't use CRTDBG for these apps

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/dib.cpp, base/applications/mspaint/winproc.cpp
In some situations, the scroll position should be reset.
- Add `CCanvasWindow::resetScrollPos` method.
- Reset the scroll position on loading a file.
- Reset the scroll position on mirroring/rotating the image.
BEFORE:
https://github.com/reactos/reactos/assets/2107452/e3c26c2f-549b-4efe-aa00-7cf4e17940af
AFTER:
https://github.com/reactos/reactos/assets/2107452/4863b2e4-af6f-4a79-9cdb-00d734addc0b
=> [MSPAINT] Reset scroll position in some situations

base/applications/mspaint/canvas.cpp, base/applications/mspaint/mouse.cpp
Drawing lines smoothly on big image.
JIRA issue: [CORE-19094](https://jira.reactos.org/browse/CORE-19094), [CORE-19237](https://jira.reactos.org/browse/CORE-19237)
- In `CCanvasWindow::DoDraw`, calculate the intersection to reduce bits transfer.
- Improve `SmoothDrawTool` in handling `Shift` key.
BEFORE:
https://github.com/reactos/reactos/assets/2107452/fbabc642-3c6e-421a-be08-cbd3ca873547
AFTER:
https://github.com/reactos/reactos/assets/2107452/2e4d8c0e-4282-4e72-af0d-4a9f1f00632e
Improved a little. The first stroke lag is not fixed yet.
=> [MSPAINT] Calculate intersection to reduce bits transfer

sdk/lib/atl/atlbase.h, sdk/lib/atl/atlcoll.h, sdk/lib/atl/atlcomcli.h, sdk/lib/atl/atlconv.h, sdk/lib/atl/atlcore.h, sdk/lib/atl/atlfile.h, sdk/lib/atl/atlpath.h, sdk/lib/atl/atlsimpstr.h, sdk/lib/atl/atlstr.h, sdk/lib/atl/atltime.h, sdk/lib/atl/atltypes.h, sdk/lib/atl/cstringt.h
Avoid use of deprecated `throw()`.
- Mechanically replace `throw()` with `noexcept` of C++11.
=> [ATL] s/throw()/noexcept/

dll/win32/userenv/environment.c
Split off of #4349.
Addendum to 96fe018 (r72066).
=> [USERENV] SetUserEnvironmentVariable(): Remove use of uninit' ShortName

win32ss/user/ntuser/menu.c
This check doesn't seem to be correct in modern ReactOS. Furthermore, it actually hadn't been working for a long time until it was uncovered by the recent system menu changes (because the macro for checking the system menu wasn't correct).
Fixes [CORE-19170](https://jira.reactos.org/browse/CORE-19170)
=> [NTUSER] Remove a wrong check in MENU_MouseMove

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h
Reduce code.
- Unify some mouse message handlers of `CCanvasWindow`.
- Add `CCanvasWindow::m_nMouseDownMsg` member.
=> [MSPAINT] Simplify canvas mouse message handling

dll/win32/msvcrt/stubs.c, dll/win32/msvcrt20/stubs.c, dll/win32/msvcrt40/stubs.c, sdk/cmake/gcc.cmake, sdk/cmake/msvc.cmake, sdk/include/reactos/stubs.h, sdk/tools/spec2def/spec2def.c
- Exclude *_stubs file from precompiled headers
- Do not include windef.h in stubs.h
This prevents conflicts between incompatible functions declarations in headers and autogenerated stubs.
=> [SDK] Improve autogenerated stubs

dll/cpl/desk/desk.c, dll/cpl/desk/desk.spec, dll/cpl/desk/screensaver.c
This function "just" changes the per-user SCRNSAVE.EXE registry value to point to the new specified file, changes the SPI values and opens the desk.cpl "Screensaver" property tab for letting the user change the new selected screensaver properties.
In particular, it does *NOT* copy the specified file to System32 or anything else (and doesn't verify that it is a valid PE executable).
Our previous implementation did none of that, and was also relying on some private setupapi functions.
Now, we behave closer to Windows. However, we also verify that the specified file actually exists, before changing the screensaver.
See commit ff09513565aad66231bce53ef3aee0bec5edbd28 (r66688) and
JIRA issue: [CORE-6812](https://jira.reactos.org/browse/CORE-6812)
- Getting rid of the SetupDecompress stuff and …
=> [DESK] Reimplement InstallScreenSaverW to behave similarly to Windows' one.

dll/win32/shell32/CShellLink.cpp
The apply button should be enabled when the show mode is changed
=> [SHELL32] Enable Apply button when shortcut show mode is changed

base/applications/taskmgr/perfdata.h, base/applications/taskmgr/perfpage.h, base/applications/taskmgr/taskmgr.h
Hermes took care of removing those in graphctrl.h and graph.h already within the yet uncommitted PR5343. Here are a few moreto get rid of, and a bit of other bloat.
I swear I checked, that we didn't collide here.
Just cleanup.
=> [TASKMGR] Get rid of cplusplus extern c

boot/bootdata/txtsetup.sif
Avoid BootCD Stage 1
```
(base/setup/lib/utils/filesup.c:274) NtOpenFile failed: c0000034, \Device\CdRom0\reactos\system32\drivers\vfatfs.sys
(base/setup/usetup/usetup.c:3680) An error happened while trying to copy file '\Device\Harddisk0\Partition1\ReactOS\system32\drivers\vfatfs.sys' (error 0xc0000034), skipping it...
```
Addendum to 14c3936 (0.4.15-dev-5090).
JIRA issue: [CORE-16373](https://jira.reactos.org/browse/CORE-16373)
- Move this file to xbox section.
=> [BOOTDATA] vfatfs.sys is packaged for xbox only

dll/win32/comctl32/listview.c
_Hidden folders are not drawn with transparent icon until the filebrowser window is resized_
JIRA issue: [CORE-16722](https://jira.reactos.org/browse/CORE-16722)
_Seems that window doesn't send a setfocus event until the icon list are displayed so no transparent icon is displayed because the cut property is not applied to non focused listview, so the change proposed is to redraw the LVIS_CUT istead of just LVIS_SELECTED when window is focused_
=> [COMCTL32] Invalidate LVIS_CUT selected items too

drivers/multimedia/bdasup/bdasup.c, drivers/usb/usbccgp/misc.c, drivers/usb/usbstor/misc.c, drivers/usb/usbstor_new/misc.c, drivers/wdm/audio/backpln/portcls/pool.cpp, drivers/wdm/audio/sysaudio/main.c
Simpler and more secure code.
Follow-up of #5792.
- Use ExAllocatePoolZero() and ExFreePoolWithTag()
=> [BDASUP][PORTCLS][SYSAUDIO][USB] Use ExAllocatePoolZero() and ExFreePoolWithTag()

ntoskrnl/lpc/create.c
Addendum to commit b3c55b9e6 (PR #4399).
Passing &CapturedObjectName as pointer to be probed and captured would fail if e.g. PreviousMode == UserMode, since that pointer is always in kernel space. Instead, pass the original user-mode pointer.
Bug caught by Timo Kreuzer ;)
=> [NTOS:LPC] Fix input parameter for ProbeAndCaptureUnicodeString

ntoskrnl/include/internal/mm.h, ntoskrnl/mm/ARM3/vadnode.c, ntoskrnl/mm/ARM3/virtual.c, ntoskrnl/mm/i386/page.c, ntoskrnl/mm/marea.c, ntoskrnl/mm/mmfault.c, ntoskrnl/mm/mminit.c, ntoskrnl/mm/section.c
Fix locking for VAD tables. Fixes CORE-18519.
The problem was identified by @Doug-Lyons. This PR extends his original fix to make sure locking is correct and asserted in all cases.
JIRA issue: [CORE-18519](https://jira.reactos.org/browse/CORE-18519)
- Add ASSERTS to MmLockAddressSpace to guarantee lock ordering
- Fix address space locking in MiProtectVirtualMemory
- Handle page table faults in MmArmAccessFault to avoid recursive aquisition of working-set lock
- Fix bugs in MmAccessFault (proper locking and fixed range check)
- Revert previous x64 hack (Temporarily release AddressCreationLock in MmCreateVirtualMappingUnsafeEx)
- Fix MmFreeMemoryArea (proper process attach, acquire working-set lock)
- Attach to the target process in MmMapViewOfSection
- Lock kernel address space in …
=> [NTOS] Fix / assert proper locking for VADs

dll/win32/syssetup/syssetup.rc, media/doc/3rd Party Files.txt
Improves URLs in 3 distinct steps for easy review:
* [SYSSETUP] syssetup.rc part1: Kill 'git blame s worst enemy in the project'
Reformat those URLs in a way that allows new lines to be added, or
existing lines to be removed or changed,
without the need to touch any neighbor line.
This will also allow git blame to work much better in the future.
No changes to the used URLs yet.
* [SYSSETUP] syssetup.rc part2: Fix 2 outdated URLs
http://www.icu-project.org -> http://icu.unicode.org
https://fedorahosted.org/liberation-fonts -> http://pagure.io/liberation-fonts
* [SYSSETUP] syssetup.rc part3: and finally tweak for size and consistency
I checked: all of the URLs do still work as good as before.
And for the record, both:
http://www.ext2fsd.com
and
http://ext2fsd.com
do behave the same and show …
=> [SYSSETUP] syssetup.rc improve URLs

base/applications/regedit/childwnd.c, base/applications/regedit/edit.c, base/applications/regedit/find.c, base/applications/regedit/framewnd.c, base/applications/regedit/security.c, base/applications/regedit/txtproc.c
Use safer functions for buffer manipulation to avoid buffer overflow/overrun.
JIRA issue: [CORE-18876](https://jira.reactos.org/browse/CORE-18876)
- Use `<strsafe.h>` functions instead of deprecated string functions.
=> [REGEDIT] Use <strsafe.h> functions strictly

base/applications/regedit/regproc.c
Follow-up to #5825.
JIRA issue: [CORE-18876](https://jira.reactos.org/browse/CORE-18876)
- Use `StringCchPrintfW` instead of `swprintf`.
=> [REGEDIT] Use <strsafe.h> functions strictly Part 2

base/applications/regedit/main.h, base/applications/regedit/regedit.c, base/applications/regedit/regproc.c
Don't exit the main program on error.
JIRA issue: [CORE-19188](https://jira.reactos.org/browse/CORE-19188)
- Improve `output_message` function.
- Use `output_message` instead of some `error_exit` function calls.
=> [REGEDIT] Improve error handling

dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, sdk/include/reactos/undocshell.h
- Add `IsShutdownAllowed` helper function.
- Add `IsSuspendAllowed` prototype to `<undocshell.h>`.
- Implement `IsSuspendAllowed` function.
=> [SHELL32][SDK] Implement IsSuspendAllowed

dll/win32/iphlpapi/address.c
_Quiet unneeded debug output for GetAdaptersAddresses._
JIRA issue: [CORE-14388](https://jira.reactos.org/browse/CORE-14388)
_Convert FIXME to TRACE in GetAdaptersAddresses._
=> [IPHLPAPI] Silence obsolete FIXME in GetAdaptersAddresses

dll/win32/shell32/CDefView.cpp
JIRA issue: [CORE-18426](https://jira.reactos.org/browse/CORE-18426)
- Extend `CDefView::InvokeContextMenuCommand` 2nd parameter to `LPCSTR`.
- Add `CDefView::_DoCopyToMoveToFolder` method.
- Use `CDefView::_DoCopyToMoveToFolder` for `FCIDM_SHVIEW_COPYTO` and `FCIDM_SHVIEW_MOVETO` command actions.
=> [SHELL32] Fix copyto/moveto actions of Search Results

dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, sdk/include/psdk/shlobj.h
- Implement `PathIsSlowA` and `SHSetFolderPathA` functions.
- Add `PathIsSlow` and `SHSetFolderPath` prototypes to `<shlobj.h>`.
- Fix some `<shlobj.h>`'s bugs.
- Improve `SHOpenPropSheetA` function.
=> [SHELL32][SDK] Implement PathIsSlowA and SHSetFolderPathA

dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, sdk/include/reactos/undocshell.h
- Add `ExtractIconResInfoA` function implementation.
- Add `ExtractIconResInfo` prototype to `<undocshell.h>`.
=> [SHELL32] Implement ExtractIconResInfoA

dll/win32/shell32/shell32.spec, dll/win32/shell32/stubs.cpp, dll/win32/shell32/utils.cpp, sdk/include/reactos/undocshell.h
- Add `ShortSizeFormatW` prototype into `undocshell.h`.
- Implement `ShortSizeFormatW` function.
=> [SHELL32][SDK] Implement ShortSizeFormatW

dll/win32/shell32/dialogs/filedefext.cpp
Based on KRosUser's patches.
JIRA issue: [CORE-19270](https://jira.reactos.org/browse/CORE-19270), [CORE-19114](https://jira.reactos.org/browse/CORE-19114), [CORE-19275](https://jira.reactos.org/browse/CORE-19275)
- Add missing version strings `"Comments"` and `"LegalTrademarks"`.
- Add version strings `"PrivateBuild"` and `"SpecialBuild"` if necessary.
- Trim the version string for pretty display.
=> [SHELL32] Improve file properties dialog

win32ss/user/ntuser/menu.c
Based on KRosUser's `scmove.patch`.
JIRA issue: [CORE-19272](https://jira.reactos.org/browse/CORE-19272)
- Check also `WS_MINIMIZE` window style to determine to disable `SC_MOVE` system command.
=> [NTUSER] Disable SC_MOVE if WS_MAXIMIZE or WS_MINIMIZE

drivers/multimedia/bdasup/precomp.h, drivers/wdm/audio/filters/kmixer/filter.c, drivers/wdm/audio/filters/kmixer/kmixer.c, drivers/wdm/audio/legacy/stream/stream.h, sdk/lib/drivers/sound/mmixer/controls.c, sdk/lib/drivers/sound/mmixer/filter.c, sdk/lib/drivers/sound/mmixer/midi.c, sdk/lib/drivers/sound/mmixer/mixer.c, sdk/lib/drivers/sound/mmixer/sup.c, sdk/lib/drivers/sound/mmixer/topology.c, sdk/lib/drivers/sound/mmixer/wave.c
Code cleanup.
bdasup: Addendum to 40c15ec (r46632).
kmixer: Addendum to 3e489bf (r42143).
mmixer: Addendum to c42d9f2 (r44872).
stream: Addendum to 4a0debf (r41662).
- Replace `YDEBUG` by commented out `NDEBUG`.
=> [BDASUP][KMIXER][MMIXER][STREAM] Replace meaningless YDEBUG

base/setup/lib/mui.c, win32ss/user/ntuser/defwnd.c, win32ss/user/ntuser/input.h, win32ss/user/ntuser/keyboard.c, win32ss/user/ntuser/misc.c, win32ss/user/ntuser/msgqueue.c, win32ss/user/ntuser/ntuser.h, win32ss/user/ntuser/sysparams.c, win32ss/user/user32/windows/defwnd.c
Respect the toggle key settings.
- Change the hot key settings in `base/setup/lib/mui.c`.
- Revert `IntDefWindowProc` function about `Alt+Shift` handling.
- Delete some code in `co_IntProcessKeyboardMessage` for `Alt+Shift` handling.
- Add `IntGetNextKL`, `IntLanguageToggle`, and `IntCheckLanguageToggle` helper functions.
- Modify `ProcessKeyEvent` and `UserGetLanguageToggle` functions to support `[Left Alt]+Shift` and `Ctrl+Shift`.
- Improve `WM_INPUTLANGCHANGEREQUEST` handling.
`[Left Alt]+[Shift]` is working.
=> [SETUPLIB][NTUSER] Toggle input language/layout on Alt+Shift / Ctrl+Shift

dll/win32/imm32/CtfImeTable.h, dll/win32/imm32/ctf.c, dll/win32/imm32/imm32.spec, dll/win32/imm32/precomp.h, sdk/include/reactos/imm32_undoc.h, win32ss/include/ntuser.h
Implementing high-level input method...
- Add `dll/win32/imm32/CtfImeTable.h` for CTF IME functions.
- Implementing `Imm32CheckAndApplyAppCompat`, `Imm32LoadCtfIme`, and `Imm32EnumCreateCtfICProc` helper functions.
- Add `CtfAImmActivate` and `CtfAImmDeactivate` functions.
- `s/CI_TFSDISABLED/CI_TSFDISABLED/`
=> [IMM32][SDK] Add CtfAImmActivate/Deactivate functions

base/applications/taskmgr/debug.c, base/applications/taskmgr/endproc.c, base/applications/taskmgr/priority.c, base/applications/taskmgr/taskmgr.c, base/applications/taskmgr/taskmgr.h
Allow the user to hold shift to automatically answer `IDYES` when killing/debugging a process or changing the priority.
=> [TASKMGR] Hold Shift to bypass confirmation MessageBox

boot/bootdata/livecd.ini, boot/bootdata/txtsetup.sif, hal/halx86/CMakeLists.txt
It appears the SMP kernel stopped booting on x86 again so let's just enable this so it stops regressing so fast.
=> [BOOTDATA][HALX86] Compile the SMP hal on x86

base/applications/mspaint/canvas.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/textedit.cpp, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h
Reduce code and binary size a bit. This will reduce 1024 bytes in binary.
- Unify `ToolBase::OnFinishDraw` and `ToolBase::OnCancelDraw` to `ToolBase::OnEndDraw`.
=> [MSPAINT] Commonize OnFinishDraw and OnCancelDraw

base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h
Reduce code and binary size. This will reduce 512 bytes in binary.
- Don't use cache for tool creation.
=> [MSPAINT] Simplify tool creation

dll/win32/imm32/ctf.c, dll/win32/imm32/imm32.spec, sdk/include/reactos/imm32_undoc.h
Implementing advanced text service...
- Add `Imm32GetFn` helper function.
- Implement `CtfImmHideToolbarWnd` and `CtfImmRestoreToolbarWnd` functions.
- Add them to `<imm32_undoc.h>`.
=> [IMM32][SDK] Implement CtfImm(Hide,Restore)ToolbarWnd

base/services/w32time/w32time.c
Based on KRosUser's patch.
JIRA issue: [CORE-19292](https://jira.reactos.org/browse/CORE-19292)
- In the `W32TmServiceMain` function, the time check loop does check the registry value.
=> [W32TIME] Remember date/time sync settings

base/applications/mspaint/dialogs.cpp, base/applications/mspaint/main.cpp, base/applications/mspaint/precomp.h, base/applications/mspaint/registry.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/selectionmodel.h, base/applications/mspaint/textedit.cpp, base/applications/mspaint/winproc.cpp
The Copy-To-File feature had some bugs that the user couldn't save.
JIRA issue: [CORE-19186](https://jira.reactos.org/browse/CORE-19186)
- Modify `SelectionModel::GetSelectionContents`.
- Delete `SelectionModel::CopyBitmap`, `SelectionModel::LockBitmap`, and `SelectionModel::UnlockBitmap` functions.
- Fix Copy-To-File feature.
=> [MSPAINT] Fix Copy-To-File feature

dll/win32/imm32/CMakeLists.txt, dll/win32/imm32/imm.c, dll/win32/imm32/imm32.spec, dll/win32/imm32/softkbd.c, sdk/include/psdk/imm.h
- Add `dll/win32/imm32/softkbd.c` source file.
- Half-implement `ImmCreateSoftKeyboard` function.
- Move `ImmShowSoftKeyboard`, and `ImmDestroySoftKeyboard` functions.
- Modify `ImmCreateSoftKeyboard` prototype.
=> [IMM32][SDK] Implement software keyboard, Part 1

base/applications/mspaint/atlimagedx.h, base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/dialogs.cpp, base/applications/mspaint/dib.cpp, base/applications/mspaint/drawing.cpp, base/applications/mspaint/drawing.h, base/applications/mspaint/fullscreen.cpp, base/applications/mspaint/fullscreen.h, base/applications/mspaint/globalvar.h, base/applications/mspaint/history.cpp, base/applications/mspaint/history.h, base/applications/mspaint/main.cpp, base/applications/mspaint/miniature.cpp, base/applications/mspaint/miniature.h, base/applications/mspaint/mouse.cpp, base/applications/mspaint/palette.h, base/applications/mspaint/registry.cpp, base/applications/mspaint/registry.h, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/sizebox.cpp, base/applications/mspaint/textedit.cpp, base/applications/mspaint/textedit.h, base/applications/mspaint/toolbox.cpp, base/applications/mspaint/toolbox.h, base/applications/mspaint/toolsettings.cpp, base/applications/mspaint/toolsettings.h, base/applications/mspaint/winproc.cpp, base/applications/mspaint/winproc.h
Follow the standard way.
- `TCHAR` --> `WCHAR`
- `LPTSTR` --> `LPWSTR`
- `LPCTSTR` --> `LPCWSTR`
- `CString` --> `CStringW`
- `TEXT("...")` --> `L"..."`
- `_T("...")` --> `L"..."`
- `::SendMessage(` --> `::SendMessageW(`.
- `::GetWindowText(` --> `::GetWindowTextW(`
- `::SetWindowText(` --> `::SetWindowTextW(`
- Replace `_tcscat` with `StringCchCatW`.
- Replace `_tcslen` with `wcslen`.
- etc. etc.
=> [MSPAINT] Adapt to Unicode and <strsafe.h>

base/applications/mspaint/rsrc.rc
Some environment failed in mspaint compilation.
=> [MSPAINT] Use <winuser.rh> instead of <winuser.h> in rsrc.rc

dll/shellext/netshell/lanconnectui.cpp
The property page does not release the lock it takes, this prevents other threads from taking the lock later.
JIRA issue: [CORE-18349](https://jira.reactos.org/browse/CORE-18349)
----
- If you open the property page from the connections folder and the tray icon at the same time, only the first dialog gets the lock. To solve this, it would have to try to find the existing dialog and just set focus to it if found. Need to investigate how Windows handles this.
- `INetCfgImpl` leaks the mutex handle?
=> [NETSHELL] Property page needs to call ReleaseWriteLock

dll/shellext/netshell/res/netshell.rgs
Windows uses a binary value and someone forgot about little endian when converting it to a DWORD. This issue has not been very visible because of bugs in CRegFolderEnum.
=> [NETSHELL] Register Network connections folder attributes as SFGAO_FOLDER, not SFGAO_CANDELETE

base/applications/rapps/appinfo.cpp, base/applications/rapps/include/appinfo.h
- If only the "License" field is set in the DB, nothing will change (this applies to 99% of the current entries in the DB)
- If both "LicenseType" and "License" are set, both will be used (no observable change in behavior): "Open Source (GPL v2)" etc.
- If only "LicenseType" is set, it will now display just the type "Freeware" instead of "Freeware ()".
----
- It now tries to map the "License" text set to "Freeware" to the `LICENSE_FREEWARE` "LicenseType" so it is translated correctly (`LoadString`).
- I added actual numbers in the enum to make it clearer that these values should not change.
=> [RAPPS] Improve LicenseType handling

sdk/lib/cmlib/hivewrt.c
allows to get rid of static var PrintCount, at least visually in the code
=> [CMLIB] UNIMPLEMENTED_ONCE less hand-knitted

dll/win32/aclui/aclui.c
Based on KRosUser's `aclui.patch`. The list view will automatically delete the image list.
JIRA issue: [CORE-19187](https://jira.reactos.org/browse/CORE-19187)
- Don't delete the image list in `DestroySecurityPage` function.
=> [ACLUI] Let image list be automatically deleted

dll/win32/advapi32/wine/security.c
George explained that this is supposed to fail like that, aka "works as designed". So let's at least mute this now, as it is spammed with every taskmgr refresh cycle
and allows me to reduce logfile-sizes from ~50MB back to ~2MB when building ros on ros.
err:(dll/win32/advapi32/wine/security.c:309) NtOpenProcessToken failed! Status c0000022.
Fixes CORE-18521
Also strip some EOL-whitespace in the file, and slightly improve the header.
JIRA issue: [CORE-18521](https://jira.reactos.org/browse/CORE-18521)
[0logBefore_50MB.zip](https://github.com/reactos/reactos/files/13257618/0logBefore_50MB.zip)
[1logAfter_2MB.log](https://github.com/reactos/reactos/files/13257619/1logAfter_2MB.log)
=> [ADVAPI32] Mute frequent taskmgr logspam CORE-18521

base/applications/mstsc/lang/ro-RO.rc
Also, revert the translation for the word "server". It won't be translated as "servitor" anymore.
=> [MSTSC] Update Romanian (ro-RO) translation

modules/rostests/win32/advapi32/eventlog/MyEventProvider.mc
Revert the word "servitor" and fix a typo.
=> [MYEVENTPROVIDER_DLL][MC] Add Romanian (ro-RO) translation to message table

dll/win32/msvcrt/msvcrt.spec, sdk/lib/crt/mbstring/mbscmp.c, sdk/lib/crt/mem/memicmp.c, sdk/lib/crt/stdlib/gcvt.c
Some fixes for NT6
- Import _gcvt and _gcvt_s from wine and export _gcvt_s on Vista+
- Add parameter check to _mbscmp
- Fix parameter check for _memicmp on NT 6+
=> [CRT] Some NT6 fixes

win32ss/user/ntuser/ntstubs.c
=> [WIN32K] Fix alignment checks in NtUserSetInformationThread

sdk/lib/atl/atlcomcli.h
The equivalent of `CComPtrBase::CoCreateInstance` had to stay inside the `#if 0` because of `__uuidof` but the (non-standard) two parameter version should still be useful.
```
CComPtr<IFoo> foo;
HRESULT hr = foo.CoCreateInstance(CLSID_Foo, IID_IFoo);
```
=> [ATL] Added CComPtr.CoCreateInstance helper methods

dll/win32/devmgr/properties/advprop.cpp
- Fix TCHAR/WCHAR mis-usage,
- Fix as a result, a buffer overflow (GlobalAlloc takes the size in bytes, but a number of characters was passed to it instead).
- Remove usage of unsafe string function. Now the item text is directly retrieved within the allocated buffer.
Cc @Oplkill for review too!
=> [DEVMGR] Fix some bugs spotted by Thomas Faber in PR #5775

dll/shellext/fontext/CEnumFonts.cpp, dll/shellext/netshell/enumlist.cpp, dll/shellext/zipfldr/CEnumZipContents.cpp, dll/win32/shell32/CEnumIDListBase.cpp
- pceltFetched can be NULL if the caller is not requesting multiple items.
- All entries returned in rgelt must be valid, they cannot be NULL.
- Pardon the `{ hr = S_FALSE;`... code, that is the actual style used there.
=> [SHELL32][SHELLEXT] IEnumIDList::Next must handle pceltFetched and memory errors correctly

dll/win32/advpack/files.c
- Handling ADN_DEL_IF_EMPTY is critical to avoid data loss.
- SetFileAttributesW failing is not fatal, the delete might still succeed.
=> [ADVPACK] Handle ADN_DEL_IF_EMPTY in DelNodeW and DelNodeRunDLL32

dll/win32/advapi32/reg/hkcr.c, dll/win32/advapi32/reg/reg.c, dll/win32/advapi32/reg/reg.h
This fixes the bug where ROS Regedit is unable to show all the keys in HKCR when a key exists in both HKCU and HKLM.
```
REGEDIT4
[HKEY_CURRENT_USER\SOFTWARE\Classes\!Test]
"CU"=""
[HKEY_CURRENT_USER\SOFTWARE\Classes\!Test\HKCU]
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\!Test]
"LM"=""
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\!Test\HKLM]
```
Regedit from XP is slightly less broken after this PR but there is still something wrong and I suspect that issue is in `EnumHKCRKey` (PR for this coming very soon).
=> [ADVAPI32] Handle HKEY_CLASSES_ROOT in RegQueryInfoKeyW

base/setup/lib/bootsup.c, boot/bootdata/livecd.ini, boot/bootdata/txtsetup.sif, boot/freeldr/freeldr/arch/i386/pc/machpc.c, boot/freeldr/freeldr/arch/i386/xbox/machxbox.c
The serial mouse is recognized by the serial stack since NT5.x.
=> [FREELDR] Implement the FASTDETECT option and enable it by default

dll/shellext/netshell/lanconnectui.cpp, dll/shellext/netshell/lanconnectui.h
Display the class icons for the installed network components.
Also fixes a bug where the selection change whacked the checkbox of the first item.
=> [NETSHELL] Display component icons in list

dll/win32/shimgvw/shimgvw.c
Add a filename extension if necessary.
JIRA issue: [CORE-19222](https://jira.reactos.org/browse/CORE-19222)
- Set `"png"` to `OPENFILENAME.lpstrDefExt`.
BEFORE:
The filename extension wasn't added.
AFTER:
The filename extension is added.
=> [SHIMGVW] Add filename extension on file save

dll/win32/msvcrt/msvcrt.spec, sdk/include/crt/crtdbg.h, sdk/lib/atl/atltrace.h, sdk/lib/crt/misc/dbgrpt.cpp
PR #5662 properly adds _CrtDbgReport(W) in msvcrt exports. This present PR also adds the variadic _CrtDbgReport(W)V functions.
JIRA issue: [CORE-11835](https://jira.reactos.org/browse/CORE-11835), [CORE-15517](https://jira.reactos.org/browse/CORE-15517)
=> [CRT][MSVCRT][ATL] Implement _CrtDbgReport(W)V and redefine _CrtDbgReport(W) around those.

dll/win32/advapi32/reg/hkcr.c
This fixes Windows RegEdit when the same HKCR key exists in HKCU and HKLM.
=> [ADVAPI32] RegEnumKeyExW on HKCR keys must work with just KEY_ENUMERATE_SUB_KEYS access

dll/win32/shell32/COpenWithMenu.cpp
Don't display applications that don't exist.
JIRA issue: [CORE-19117](https://jira.reactos.org/browse/CORE-19117)
I verified the behavior on XP. Exe files that no longer exist are hidden but their registry entry is not deleted.
=> [SHELL32] Don't display missing applications in Open with. CORE-19117

dll/win32/cryptui/main.c
Based on KRosUser's `cryptui.patch`.
JIRA issue: [CORE-17290](https://jira.reactos.org/browse/CORE-17290)
- Don't delete the image list because the list view will delete the image list automatically.
=> [CRYPTUI] Let image list be automatically deleted

boot/bootdata/livecd.inf
Write on the registry to enable toggle hot-keys.
JIRA issue: [CORE-13145](https://jira.reactos.org/browse/CORE-13145)
```reg
[HKEY_CURRENT_USER\Keyboard Layout\Toggle]
Hotkey=1
Language Hotkey=1
Layout Hotkey=2
```
BOOTCD:
LIVECD (AFTER):
Video:
[ReactOS-screen0.webm](https://github.com/reactos/reactos/assets/2107452/eb375c77-5726-4f68-8251-8bb6b31f1b96)
=> [BOOTDATA] LiveCD: Enable Toggle key (Alt+Shift etc.) by registry

ntoskrnl/cc/view.c
Do not access VACB after decrementing its reference count. It might already be deleted by a different thread.
=> [NTOS:CC] Do not access VACB after decrementing its reference count

modules/rostests/kmtests/kmtest/testlist.c, modules/rostests/kmtests/kmtest_drv/testlist.c
In the beginning two tests with the name "RtlCaptureContext" were added to kmtest. This had made testman very angry and has been widely regarded as a bad move.
x64 kvm: https://reactos.org/testman/compare.php?ids=91072
=> [KMTEST] Fix duplicated test names to stop testman from blowing up

dll/cpl/access/general.c
Based on KRosUser's `access.patch`.
JIRA issue: [CORE-19303](https://jira.reactos.org/browse/CORE-19303)
- Anyway select something at `IDC_RESET_COMBO` combo box.
=> [ACCESS] Improve IDC_RESET_COMBO selection

base/applications/mspaint/history.cpp, base/applications/mspaint/history.h, base/applications/mspaint/mouse.cpp, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h
When computer resources are limited, it is desirable to conserve memory usage. We can reduce memory usage by using "partial" images in history.
- Add `IMAGE_PART` structure and use as history items.
- Overload `ImageModel::PushImageForUndo(const RECT& rcPartial)`.
- Add `ToolsModel::GetToolSize`.
- Implement partial image history on `TwoPointDrawTool`.
On 2000x2000 pixel image, the user drew 5 lines. Memory usage:
BEFORE:
`74,432 KB`.
AFTER:
`15,804 KB`.
Win2k3 mspaint:
`37,048 KB`.
=> [MSPAINT] Introduce partial image history

sdk/cmake/msvc.cmake
Fix build with latest VS 2022
Reason: VS solution builds pass the compiler options to the assembler. These are usually ignored and result in a warning only, but ML of the latest VS supports /Gy (function level linking), but that requires all functions to be declared with "PROC" and otherwise results in an error.
=> [CMAKE] Remove "/Gy" option from ML

dll/shellext/stobject/volume.cpp
Based on KRosUser's `volume.patch`.
The pair of `#if 0` and `#endif` was added in https://github.com/reactos/reactos/commit/180b6fb0834038cd558b2791f6afdbf6063ed30c .
This PR will remove it.
JIRA issue: [CORE-18583](https://jira.reactos.org/browse/CORE-18583)
=> [STOBJECT] Remove #if 0 and #endif in Volume_IsMute

dll/cpl/input/advanced_settings_page.c, dll/cpl/input/input.c, dll/cpl/input/input.h, dll/cpl/input/input_list.c, dll/cpl/input/lang/bg-BG.rc, dll/cpl/input/lang/cs-CZ.rc, dll/cpl/input/lang/de-DE.rc, dll/cpl/input/lang/el-GR.rc, dll/cpl/input/lang/en-US.rc, dll/cpl/input/lang/es-ES.rc, dll/cpl/input/lang/fr-FR.rc, dll/cpl/input/lang/he-IL.rc, dll/cpl/input/lang/id-ID.rc, dll/cpl/input/lang/it-IT.rc, dll/cpl/input/lang/ja-JP.rc, dll/cpl/input/lang/no-NO.rc, dll/cpl/input/lang/pl-PL.rc, dll/cpl/input/lang/pt-BR.rc, dll/cpl/input/lang/pt-PT.rc, dll/cpl/input/lang/ro-RO.rc, dll/cpl/input/lang/ru-RU.rc, dll/cpl/input/lang/sk-SK.rc, dll/cpl/input/lang/sq-AL.rc, dll/cpl/input/lang/tr-TR.rc, dll/cpl/input/lang/uk-UA.rc, dll/cpl/input/lang/zh-CN.rc, dll/cpl/input/lang/zh-HK.rc, dll/cpl/input/lang/zh-TW.rc, dll/cpl/input/resource.h, dll/cpl/input/settings_page.c
Allow the user to turn off `"Advanced Text Service"`.
```reg
[HKEY_CURRENT_USER\Software\Microsoft\CTF]
"Disable Thread Input Manager"=dword:00000001
```
- Add `LoadAdvancedSettings` and `SaveAdvancedSettings` helper functions.
- Implement `AdvancedSettingsPageProc` procedure.
- Modify `IDS_REBOOT_NOW` resource string.
=> [INPUT] Implement advanced settings

base/applications/calc/calc.h, base/applications/calc/utl_ieee.c, base/applications/calc/utl_mpfr.c, base/applications/calc/winmain.c
Use safer string functions.
JIRA issue: [CORE-19306](https://jira.reactos.org/browse/CORE-19306)
- `#include <strsafe.h>`
- Use `StringCbPrintf` instead of `_stprintf`.
- Use `StringCbCopy` insteaad of `_tcscpy`.
- Use `StringCbCat` instead of `_tcscat`.
=> [CALC] Adapt to <strsafe.h>

dll/win32/shell32/dialogs/filetypes.cpp
Based on KRosUser's `filestypedel.patch`.
JIRA issue: [CORE-19325](https://jira.reactos.org/browse/CORE-19325)
- Select the first item after the user deleted a file type.
=> [SHELL32] Select 1st item after deletion of file type

dll/shellext/shellbtrfs/reactos.cpp, sdk/include/psdk/winbase.h
Code cleanup.
Follow-up to 455f330 (0.4.15-dev-6969).
See #5802.
- Get rid of FILE_INFO_BY_HANDLE_CLASS.MaximumFileInfoByHandlesClass
=> [PSDK][SHELLBTRFS] Get rid of MaximumFileInfoByHandlesClass

dll/win32/shell32/dialogs/filetypes.cpp
Based on KRosUser's `filetypes.patch`.
JIRA issue: [CORE-19324](https://jira.reactos.org/browse/CORE-19324)
- Check `NULL` for `pEntry`.
=> [SHELL32] Fix exception on modifying deleted file type

dll/shellext/netshell/lanconnectui.cpp
Based on KRosUser's `lanprop.patch`.
JIRA issue: [CORE-19330](https://jira.reactos.org/browse/CORE-19330)
- Add `NM_DBLCLK` handling.
=> [NETSHELL] Double click on component should open properties

base/applications/rapps/appview.cpp
- If the DisplayIcon value points to an invalid path, ExtractIconW can return 1! ExtractIconExW does not have this problem nor [the -1 issue](https://devblogs.microsoft.com/oldnewthing/20050526-07/?p=35533).
- Use the icon index from PathParseIconLocation.
Test:
````bat
@echo off
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Ex1 /v DisplayName /d "Ex1 Normal" /f
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Ex1 /v DisplayIcon /d "%windir%\explorer.exe" /f
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Ex1 /v UnstallString /d "calc.exe" /f
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Ex2 /v DisplayName /d "Ex2 Bad icon path" /f
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Ex2 /v DisplayIcon /d …
```
=> [RAPPS] DisplayIcon needs to handle invalid paths and icon index

dll/win32/setupapi/cfgmgr.c
- Return CR_INVALID_POINTER if `pszVetoName` is NULL and `ulNameLength` is not zero.
- CM_Request_Device_Eject_ExA: Allow `ulNameLength` to be zero when `pszVetoName` is not NULL
Verified with Win2k3 SP2 using ROS hotplug.dll modified to call the function with different `pszVetoName` and `ulNameLength` values.
=> [SETUPAPI] CM_Request_Device_Eject_ExA/W: Fix pszVetoName buffer size validation

dll/win32/setupapi/cfgmgr.c
which is an _Out_ parameter.
Fix "uninitialized" data read.
Follow-up to #5943.
- Do not debugstr_*(pszVetoName)
=> [SETUPAPI] cfgmgr.c: Do not debugstr_*(pszVetoName)

base/applications/mspaint/canvas.cpp, base/applications/mspaint/common.h, base/applications/mspaint/miniature.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/toolsmodel.h, base/applications/mspaint/winproc.cpp
Follow-up to #5994. Reduce the lag and the cost of drawing on large image.
JIRA issue: [CORE-19237](https://jira.reactos.org/browse/CORE-19237)
- Introduce partial image history on `SmoothDrawTool` and `ShapeTool`.
AFTER:
We can draw with pen smoothly even when the image is huge (10000x10000).
=> [MSPAINT] Introduce partial image history, Part 2

dll/win32/setupapi/cfgmgr.c
Follow-up of PR [#5943](https://github.com/reactos/reactos/pull/5943)
Before:
After:
=> [SETUPAPI] CM_Request_Device_Eject_ExW: Allow ulNameLength to be zero when pszVetoName is not NULL

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/main.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/selectionmodel.h
Refactoring and arrangement for selection handling.
- Move some selection-related codes in `canvas.cpp` to `mouse.cpp`.
- Add `SelectionBaseTool` structure for `FreeSelTool` and `RectSelTool`.
- Delete some useless codes.
=> [MSPAINT] Define SelectionBaseTool and use it

base/applications/mspaint/canvas.cpp, base/applications/mspaint/canvas.h, base/applications/mspaint/history.cpp, base/applications/mspaint/history.h, base/applications/mspaint/main.cpp, base/applications/mspaint/mouse.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/selectionmodel.h, base/applications/mspaint/toolsmodel.cpp, base/applications/mspaint/toolsmodel.h
Consistent behavior of the application.
JIRA issue: [CORE-19226](https://jira.reactos.org/browse/CORE-19226)
- Add `ShiftPtStack` and `BuildMaskFromPtStack` helper functions.
- Move some codes of `selectionModel` to `mouse.cpp`.
- Fix Undo/Redo behavior on selection.
=> [MSPAINT] Improve Undo/Redo handling of selection

win32ss/gdi/ntgdi/bitblt.c, win32ss/user/ntuser/nonclient.c
When I am implementing the IME soft keyboard (#6021 and #6036), I noticed an issue with `PatBlt` function.
JIRA issue: [CORE-19334](https://jira.reactos.org/browse/CORE-19334)
Using IME Software Keyboards...
Win2k3:
BEFORE:
AFTER:
Successful.
Win2k3:
BEFORE:
AFTER:
Successful.
BEFORE:
AFTER:
Successful.
- Fix the rectangle coordinates when the value was negative in `NtGdiPatBlt` function.
- Fix `NC_DrawFrame` function.
- Fix `UserDrawWindowFrame` function.
=> [NTGDI] Fix PatBlt with negative values

sdk/lib/CMakeLists.txt, sdk/lib/pathcch/CMakeLists.txt, sdk/lib/pathcch/pathcch.c, sdk/lib/pathcch/pathcch.h
- Isolate PathCch functions from Wine implementation in kernelbase (which are mixed with a ton of unrelated stuff).
- Better header than Wine's own (supersedes PR #5824)
JIRA issue: [CORE-12686](https://jira.reactos.org/browse/CORE-12686)
=> [SDK][PATHCCH] Import PathCch* functions from Wine

dll/cpl/input/input_list.c
Follow-up to #4666. Fix an abnormal termination at setting the default language.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700), [CORE-13244](https://jira.reactos.org/browse/CORE-13244), [CORE-18364](https://jira.reactos.org/browse/CORE-18364)
- `pCurrent` was an invalid pointer at the crime scene. Don't use it there for `SPI_SETDEFALTINPUTLANG`.
- Save the default keyboard layout.
- Use it.
BEFORE:
The crime scene: The user about to add Russian.
AFTER:
Fixed. Successful.
=> [INPUT] Fix exception on setting default language

win32ss/user/user32/misc/exticon.c
_Fix the F1'97 Demo program not showing an icon in explorer.._
JIRA issue: [CORE-10726](https://jira.reactos.org/browse/CORE-10726)
_If the normal method to get an icon fails, then provide an alternate one._
After patch:
Icon shown in W2K3SP2:
=> [USER32] Fix F1'97 Demo icon not showing in explorer

boot/bootdata/hivesft.inf
URL protocol registration is a value, not a key!
IEFrame later comes along and adds the value covering up the issue for everyone except poor gopher.
=> [BOOTDATA] Fix URL protocol registration

dll/win32/kernel32/client/proc.c
Fix 64-bit bug in SetProcessAffinityMask
=> [KERNEL32] Fix 64-bit bug in SetProcessAffinityMask

dll/win32/imm32/ctf.c, dll/win32/kernel32/client/appcache.c, dll/win32/kernel32/kernel32.spec, sdk/include/reactos/compat_undoc.h
- Half-implement `kernel32!BaseCheckAppcompatCache` function.
- Add it to `<compat_undoc.h>`.
- Use `<compat_undoc.h>` in IMM32.
- Modify `kernel32.spec`.
=> [IMM32][KERNEL32][SDK] Half-implement BaseCheckAppcompatCache

dll/win32/shimgvw/shimgvw.c
- Dispose the image.
- Get the current file pathname and the next file pathname.
- Call `SHFileOperation` to delete.
- Free the file list.
- Rebuild the file list and load the next file.
=> [SHIMGVW] Implement ImageView_Delete

dll/win32/comctl32/ipaddress.c
Based on KRosUser's suggestion. `bgCol` is a `COLORREF` value, not a color index.
JIRA issue: [CORE-9853](https://jira.reactos.org/browse/CORE-9853)
- Create a brush from `bgCol`.
- Use it.
=> [COMCTL32] IP Address control: Fix background drawing

dll/win32/imm32/imm.c, dll/win32/imm32/precomp.h
`ImmLoadLayout` was buggy.
- Don't do zero fill `pImeInfoEx`.
- Simplify registry handling.
- Don't reset `pImeInfoEx->fLoadFlag` if failed early.
=> [IMM32] Rewrite ImmLoadLayout

dll/win32/shimgvw/anime.c, dll/win32/shimgvw/shimgvw.c, dll/win32/shimgvw/shimgvw.h
Improve naming consistency. Improve code flexibility.
- Move `Anime_GetFrameDelay` and `Anime_Step`.
- Remove one parameter from `ImageView_SaveSettings`.
- Rename some preview-window functions as `Preview_...`.
- Rename `ImageView_CreateWindow` as `ImageView_Main`.
- Use `lParam` of `WM_CREATE` message.
=> [SHIMGVW] Refactoring Part 2

sdk/include/psdk/ctfutb.idl
For supporting Text Input Processors (TIPs).
- Add many TSF interfaces and definitions into `"ctfutb.idl"`.
=> [SDK][UUID] Strengthen <ctfutb.h>

dll/win32/shimgvw/shimgvw.c, dll/win32/shimgvw/shimgvw.h
Improve code flexibility.
- Remove `g_fnPrevProc`, `g_hDispWnd`, `g_hToolBar`, and `g_Anime` global variables.
- Declare `PREVIEW_DATA` structure and use it.
- Encapsulate preview window by using user data.
=> [SHIMGVW] Refactor Part 3

dll/win32/comctl32/combo.c, win32ss/user/user32/controls/combo.c
Based on KRosUser's `combo.patch`. Enable `Alt+F4`.
JIRA issue: [CORE-18231](https://jira.reactos.org/browse/CORE-18231)
- ComboBox: Do default processing on `WM_SYSKEYDOWN` if necessary.
=> [COMCTL32][USER32] ComboBox: Do default processing on WM_SYSKEYDOWN

dll/win32/comctl32/tab.c
Based on KRosUser's `tab.patch`.
JIRA issue: [CORE-11454](https://jira.reactos.org/browse/CORE-11454)
- In `TAB_SetItemT` function, use `InvalidateRect` instead of `TAB_InvalidateTabArea`.
=> [COMCTL32] Tab control: Use InvalidateRect in TAB_SetItemT update

dll/ime/msctfime/msctfime.c
- Implement `ImeRegisterWord`, `ImeUnregisterWord`, `ImeGetRegisterWordStyle`, `ImeEnumRegisterWord`, `ImeConversionList`, `ImeEscape`, `ImeSelect`, and `ImeSetActiveContext` functions.
- These functions in `MSCTFIME` basically do nothing.
=> [MSCTFIME] Implement ImeRegisterWord etc.

win32ss/user/user32/windows/dialog.c
Based on KRosUser's `SkipStatic_v2.patch`.
JIRA issue: [CORE-6127](https://jira.reactos.org/browse/CORE-6127)
- Skip `DLGC_STATIC` controls on array keys.
- Avoid infinite loop by using `hwndFirst` variable.
=> [USER32] Skip STATIC controls on arrow keys

win32ss/user/ntuser/window.c
- Don't use RETURN() macro
- Remove parentheses around return value
=> [NTUSER] window.c: Don't use RETURN() macro

dll/win32/comctl32/button.c, win32ss/user/user32/controls/button.c, win32ss/user/user32/windows/dialog.c
Based on KRosUser's `button.patch`.
JIRA issue: [CORE-17210](https://jira.reactos.org/browse/CORE-17210)
- Fix `DLGC_...` handling by using `&` operator in `BUTTON_CheckAutoRadioButton` in `button.c`.
- Fix `DLGC_...` handling by using `&` operator in `IsDialogMessageW` in `dialog.c`.
- `BM_CLICK`'s `wParam` must be zero.
=> [COMCTL32][USER32] Button: Fix DLGC_... handling

dll/ntdll/include/ntdllp.h, dll/ntdll/ldr/ldrinit.c, dll/ntdll/nt_0600/DllMain.c, dll/win32/kernel32/kernel32.spec, dll/win32/msvcrt/dllmain.c, dll/win32/msvcrt/msvcrt.spec, sdk/lib/rtl/condvar.c
Initializes some stuff in ntdll and msvcrt entry point.
- [NTDLL] Initialize keyed event for condition variables
- [MSVCRT] Initialize exception support in DllMain
- x86 KVM: https://reactos.org/testman/compare.php?ids=91930,91933,91949,91954
- x64 KvM: https://reactos.org/testman/compare.php?ids=91962,91967,91972,91976
=> [NTDLL][MSVCRT] Initialize stuff in dll entrypoint

sdk/include/ndk/ketypes.h, sdk/include/xdk/ketypes.h
Sync KUSER_SHARED_DATA between NDK and XDK.
- Add missing XSTATE definitions to NDK
- Update XSTATE stuff to latest SDK
- Apply our standard formatting
- Some versioning improvements
- Add field offsets
- Sync KUSER_SHARED_DATA between NDK and XDK
Decide upon how to handle the (growing) number of `#if (NTDDI_VERSION ...)`. A lot of the layout is compatible between versions and adding more fields doesn't change anything. To enable support for modern features like XSTATE configuration, it will be needed to add `|| defined(__REACTOS__)`. Please provide feedback.
=> [XDK][NDK] Improve and sync KUSER_SHARED_DATA

base/setup/usetup/lang/pt-PT.h
Shorten the Portuguese translation to fit on one line.
=> [USETUP] Shorten the Portuguese translation to fit on one line

drivers/network/dd/dc21x4/eeprom.c, drivers/network/dd/dc21x4/power.c
- The return value got lost when refactoring the setup function
- The check against 0xFFFFFFFF was meant to reject an empty EEPROM image
=> [DC21X4] Fix typos

dll/win32/shell32/CShellDispatch.cpp
SW_HIDE is not the correct default show mode.
`WScript.CreateObject("Shell.Application").ShellExecute("calc.exe");`
=> [SHELL32] ShellDispatch::ShellExecute must default to displaying the window

modules/rostests/apitests/user32/LoadImage.c, win32ss/user/user32/windows/cursoricon.c
`GetModuleFileName` fails on `LOAD_LIBRARY_AS_DATAFILE` causing `LoadImage` to fail on icons.
I'm inventing a fake filename for `LR_SHARED`. I don't know if this is a good idea but it does match Windows shared icon handling. The fake name includes `*` and `?` so it should never be confused with a real path. I don't know how this name interacts with WOW64 so in the unlikely case that a WOW64 processes calls the 64-bit `LoadImage`, the worlds will not collide because the fake name is pointer size padded.
The alternative would be to turn off `LR_SHARED` but this means the caller gets a new icon each time and that might cause leaks because the caller does not expect having to call `DestroyIcon` on a shared icon. We would also then be left with no path to pass to `NtUserSetCursorIconData`. …
=> [USER32] Support loading icons from data file module

sdk/cmake/writing_CmakeLists_for_ReactOS.txt
Improve documentation.
- Fix typos
=> [CMAKE] writing_CmakeLists_for_ReactOS.txt: Fix typos

win32ss/gdi/eng/error.c, win32ss/gdi/ntgdi/misc.h
Optimization, consistency, simplification, documentation.
- Remove a useless `#include <debug.h>`.
- Use `pTeb` more.
- Remove a useless `else`.
- Add a SAL2 annotation.
=> [GDI] eng/error.c: Minor code tweaks

dll/win32/browseui/shellfind/CFindFolder.cpp
- The children passed to `SHOpenFolderAndSelectItems` are not supposed to be full pilds.
- Don't leak the array from `IShellFolderView::GetSelectedObjects`.
=> [BROWSEUI] Don't call SHOpenFolderAndSelectItems with full pidls and don't leak them

base/applications/regedit/find.c
Reproduce:
- Search for "program files" and never get a match until you turn on the case matching checkbox and then find "Program Files"
Notes:
- This file is not synced with Wine AFAIK
=> [REGEDIT] Fix inverted case matching when searching value data

dll/apisets/api-ms-win-crt-private-l1-1-0.spec
Stay sync'ed.
Addendum to 1a6b6a2 (0.4.15-dev-7230).
- Forward _seh_longjmp_unwind4() to msvcrt
=> [APISETS] Forward _seh_longjmp_unwind4() to msvcrt

dll/win32/shell32/CDefaultContextMenu.cpp
Split off of #6170.
```
...\dll\win32\shell32\CDefaultContextMenu.cpp(588): warning C4805: '|=': unsafe mix of type 'BOOL' and type 'bool' in operation
...\dll\win32\shell32\CDefaultContextMenu.cpp(590): warning C4805: '|=': unsafe mix of type 'BOOL' and type 'bool' in operation
...\dll\win32\shell32\CDefaultContextMenu.cpp(593): warning C4805: '|=': unsafe mix of type 'BOOL' and type 'bool' in operation
```
Addendum to 7fb91d9 (0.4.15-dev-6915).
- Use 'bool' type.
- Do not abuse '|=' operator.
=> [SHELL32] AddStaticContextMenusToMenu(): Fix 3 MSVC 'warning C4805'

dll/win32/shimgvw/shimgvw.c
Don't lock the file for usability.
JIRA issue: [CORE-19183](https://jira.reactos.org/browse/CORE-19183)
- Add `m_pMemStream` to `PREVIEW_DATA` structure.
- Add `Preview_pFreeImage` helper function.
- Add `MemStreamFromFile` helper function to make a memory stream.
- Avoid file locking by using a memory stream and `GdipLoadImageFromStream`.
=> [SHIMGVW] Unlock file

win32ss/user/ntuser/menu.c
- Don't use RETURN() macro
- Remove parentheses around return value
=> [NTUSER] menu.c: Don't use RETURN() macro

dll/ime/msctfime/msctfime.cpp, dll/ime/msctfime/msctfime.h
- Define `ITfSysHookSink` interface.
- Add implementation to `CicBridge` class.
- Implement `ImeDestroy` and `CtfImeDestroyThreadMgr` functions.
- Implement `CtfImeCreateThreadMgr` function.
=> [MSCTFIME] Implement ImeDestroy and CtfImeDestroyThreadMgr

ntoskrnl/ke/amd64/ipi.c, ntoskrnl/ke/ipi.c, ntoskrnl/ntos.cmake
This PR implements the basic x64 kernel IPI code. For now it only supports APC, DPC and freeze IPIs, which will be made use of soon. DPC for SMP scheduling and freeze for SMP debugging. It doesn't yet support generic function IPIs, which are a bit more complex and will come later.
=> [NTOS:KE/x64] Implement initial IPI code

sdk/tools/winesync/winesync.py
This PR introduces diverse improvements and fixes for the `winesync.py` script.
The most important ones are:
- Fixing some apparent problems with commits manipulation with pygit2;
- Explicitly using posix paths for git file manipulations;
- Allowing using the "new" Wine-Staging patchinstall.py script, that has been introduced in Wine-Staging in Feb.16, 2023;
- Elegantly handle empty 'files' and 'directories' lists (expanding on @tkreuzer commit 4b5a55516)
- Make the Wine-Staging tag optional, when one doesn't want to sync with Wine-Staging, but just with Wine.
These modifications have been used to successfully [sync setupapi](https://github.com/reactos/reactos/commits/hbelusca/setupapi_partial_winesync) [with Wine-Staging 8.15](https://github.com/reactos/reactos/commits/hbelusca/setupapi_w …
=> Winesync.py Script: Diverse improvements

dll/ime/msctfime/CMakeLists.txt, dll/ime/msctfime/msctfime.cpp, dll/ime/msctfime/msctfime.h, sdk/include/ddk/immdev.h, sdk/include/reactos/cicero/imclock.h
- Add link to `imm32.dll`.
- Add `<cicero/imclock.h>`.
- Add `INIT_GUIDMAP` constant to `<immdev.h>`.
- Implement `CtfImeIsGuidMapEnable` by using them.
=> [MSCTFIME][SDK] Implement CtfImeIsGuidMapEnable

dll/ime/msctfime/msctfime.cpp, dll/ime/msctfime/msctfime.h, sdk/include/ddk/immdev.h
- Add `CTFIMECONTEXT` structure.
- Add `CicInputContext` class.
- Rename `INPUTCONTEXTDX.dwUnknown5` as `hCtfImeContext` and retype it as `HIMCC`.
- Implement `CtfImeGetGuidAtom` by using them.
=> [MSCTFIME][SDK] Implement CtfImeGuidAtom

dll/ime/msctfime/msctfime.cpp, dll/win32/msctf/msctf.spec, sdk/include/psdk/msctf.idl
- Implement `GetCompartment`, `SetCompartmentDWORD`, `GetCompartmentDWORD`, `SetCompartmentUnknown`, and `ClearCompartment` helper functions.
- Add `TF_DllDetachInOther` prototype to `"msctf.idl"`.
- Implement `DllMain` function by using `TF_DllDetachInOther`.
=> [MSCTFIME][MSCTF][SDK] Add compartment helper functions

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
Based on KRosUser's `edit_v2.patch`.
Edit control should stop processing characters when left mouse button is down.
JIRA issue: [CORE-10259](https://jira.reactos.org/browse/CORE-10259)
- If `es->bCaptureState` is set, then ignore `WM_CHAR` message.
=> [COMCTL32][USER32] EDIT control: Check bCaptureState on WM_CHAR

dll/ime/msctfime/CMakeLists.txt
Reduce DLL initialization cost.
- Delay-import `msctf.dll`, `oleaut32.dll`, and `imm32.dll`.
- Unlink `comctl32.dll`.
=> [MSCTFIME] Delay-import msctf, oleaut32, and imm32

dll/win32/browseui/addresseditbox.cpp
Based on KRosUser's `gopidlparsed.patch`.
JIRA issue: [CORE-19019](https://jira.reactos.org/browse/CORE-19019)
- Clear `pidlLastParsed` if necessary.
=> [BROWSEUI] Clear pidlLastParsed on CAddressEditBox::Execute

base/shell/explorer/precomp.h, base/shell/explorer/settings.cpp, base/shell/explorer/syspager.cpp, base/shell/explorer/trayclock.cpp
Automatically adjusts the spacing of the tray icons according to the small or large taskbar icons setting. Also, a minor bug fix to the clock spacing when switching between taskbar icon sizes.
Jira Issue: [CORE-19380](https://jira.reactos.org/browse/CORE-19380)
- Update the ROS-specific `CompactTrayIcons` registry value from a binary yes/no to have three states. The three states are as follows:
> 0 (default) - Automatic. When small taskbar icons are used, the notification area will use compact tray icon spacing. When large taskbar icons are used, the notification area will use larger tray icon spacing. While no version of Windows behaves this way, I believe this is a smart default choice for ReactOS since users wanting large taskbar icons will generally expect larger tray icon spacing, …
=> [EXPLORER] Notification area icon improvements

drivers/filesystems/vfatfs/direntry.c
`...\drivers\filesystems\vfatfs\direntry.c(463): warning C4267: '=': conversion from 'size_t' to 'USHORT', possible loss of data`
Addendum to 096a694 (r6279).
- Explicitly cast.
Ok as the line immediately before writes `UNICODE_NULL` within boundary.
=> [VFATFS] FATGetNextDirEntry(): Fix 1 MSVC 'warning C4267'

dll/win32/wshom.ocx/shell.c
The last two parameters are [optional](https://learn.microsoft.com/en-us/previous-versions/d5fk67ky(v=vs.85)).
```
' test.vbs
Set objShell = Wscript.CreateObject("Wscript.Shell")
objShell.Run "calc.exe" ' Should work because the arguments are optional
objShell.Run "winver.exe", invalidnumber ' Windows treats this as SW_HIDE because it can convert VT_EMPTY
objShell.Run "notepad.exe", "invalidnumber" ' Windows fails with error
```
Notes:
- The Wine part of the `else` is not indented correctly but I think this is better than duplicating Wine code inside the `#ifdef`?
=> [WSHOM.OCX] WshShell::Run intWindowStyle parameter is optional

dll/win32/setupapi/cfgmgr.c
Code simplification.
- Remove 5 useless '= NULL' initializations
=> [SETUPAPI] cfgmgr.c: Remove 5 useless '= NULL' initializations

dll/win32/setupapi/cfgmgr.c
At best, the new check was useless too; at worst, it would leak.
Revert new b0a7374 (0.4.15-dev-3912) broken check,
and even remove initial a6eabc0 (r73394) useless check.
- Remove useless/broken check
=> [SETUPAPI] CMP_RegisterNotification(): Remove useless/broken check

base/services/umpnpmgr/rpcserver.c
Type was changed from `DWORD` to `DWORD_PTR` (as handle).
Addendum to 71df39b (0.4.15-dev-7294).
- Fix a string format
=> [UMPNPMGR] PNP_RegisterNotification(): Fix a string format

dll/ntdll/def/ntdll.spec, dll/ntdll/ldr/ldrapi.c, sdk/include/ndk/ldrfuncs.h
Make `LdrUnlockLoaderLock` `Cookie` type consistent with `LdrLockLoaderLock` and `LdrpMakeCookie` functions.
Truncating to a `ULONG` happens to work on ReactOS. However, testing on Windows 10 `LdrUnlockLoaderLock` fails to unlock loader lock unless you change the prototype such that `Cookie` is a `ULONG_PTR`. A `ULONG_PTR` is also what's used by Wine.
=> [LDR][NDK] Fix inconsistent Cookie type

dll/win32/comdlg32/colordlg.c
Color spectrum had inconsistent behaviour in restricting cursor position of color picker.
JIRA issue: [CORE-17002](https://jira.reactos.org/browse/CORE-17002)
- `ClipCursor(NULL)` for `WM_LBUTTONUP` and `WM_NCDESTROY`.
- `ClipCursor(...)` for `WM_LBUTTONDOWN`.
=> [COMDLG32] Color Picker: Fix cursor clipping

win32ss/include/ntuser.h, win32ss/user/ntuser/event.c, win32ss/user/ntuser/timer.c
- Add a new `UserHMSetHandle(obj, handle)` macro and use it instead of `UserHMGetHandle(obj) = handle` or `obj->head.h = handle`.
=> [NTUSER] Add UserHMSetHandle macro

dll/win32/shlwapi/regstream.c
When the system run out of memory, check `NULL` and fail elegantly if necessary.
This doesn't fix CORE-19229 but I think it needs a fix.
JIRA issue: [CORE-19229](https://jira.reactos.org/browse/CORE-19229)
- Check if `strm` was `NULL`.
=> [SHLWAPI] Fix SHCreateMemStream corner case

base/applications/ctfmon/CLoaderWnd.cpp, base/applications/ctfmon/CMakeLists.txt, base/applications/ctfmon/CRegWatcher.cpp, base/applications/ctfmon/CRegWatcher.h, base/applications/ctfmon/ctfmon.cpp, base/applications/ctfmon/precomp.h, dll/ime/msctfime/msctfime.cpp, dll/ime/msctfime/msctfime.h, dll/win32/msctf/utils.cpp, dll/win32/msutb/CMakeLists.txt, sdk/include/reactos/cicero/cicbase.h, sdk/include/reactos/cicero/cicevent.h, sdk/include/reactos/cicero/cicfmap.h, sdk/include/reactos/cicero/cicmutex.h, sdk/include/reactos/cicero/cicreg.h
Cicero interface is not Unicode (W) but ANSI (A).
JIRA issue: [CORE-19361](https://jira.reactos.org/browse/CORE-19361), [CORE-19362](https://jira.reactos.org/browse/CORE-19362), [CORE-19363](https://jira.reactos.org/browse/CORE-19363)
- `ctfmon.exe` is ANSI, not Unicode.
- `msutb.dll` is ANSI, not Unicode.
- Apply generic text mapping to the cicero library.
- Include `<tchar.h>` to use generic text mapping.
=> [CTFMON][MSCTFIME][MSCTF][MSUTB][SDK] Cicero is ANSI, not Unicode

dll/win32/msctf/msctf.spec, dll/win32/msctf/utils.cpp
Supporing TIPs...
- Add `FullPathExec`, and `RunCPLSetting` helper functions.
- Implement `TF_RunInputCPL` function by using them.
- Modify `msctf.spec`.
=> [MSCTF] Implement TF_RunInputCPL

dll/win32/comctl32/propsheet.c
Fix `Ctrl+Tab` and `Shift+Ctrl+Tab` key combination action in property sheet.
JIRA issue: [CORE-17941](https://jira.reactos.org/browse/CORE-17941)
- Use `PROPSHEET_IsDialogMessage` in the message loop of `PropertySheetA/W` function, instead of `IsDialogMessage`.
https://github.com/reactos/reactos/assets/2107452/df9c781f-9c81-4a0a-b0a6-2ee0aedefbf0
=> [COMCTL32] Property Sheet: Use PROPSHEET_IsDialogMessage in message loop

dll/win32/comdlg32/colordlg.c
JIRA issue: [CORE-19402](https://jira.reactos.org/browse/CORE-19402)
- Set maximum value to `value` if `value` was beyond maximum value.
=> [COMDLG32] Color Picker: Limit value by maxval

dll/ime/msctfime/msctfime.cpp, dll/ime/msctfime/msctfime.h, sdk/include/ddk/immdev.h, sdk/include/reactos/cicero/cictf.h
- Define `ITfSysHookSink` and `IID_ITfThreadMgr_P` interfaces in `<cicero/cictf.h>`.
- Implement `CtfImeProcessCicHotkey` function.
=> [MSCTFIME][SDK] Implement CtfImeProcessCicHotkey

dll/ime/msctfime/msctfime.cpp, dll/ime/msctfime/msctfime.h, sdk/include/reactos/cicero/cicimc.h
- Add `GetCharsetFromLangId` and `InternalSelectEx` helper functions.
- Add `CicBridge::GetInputContext` and `CicBridge::SelectEx`.
- Implement `CtfImeSelectEx` function.
- `CTFIMECONTEXT` structure moved into `<cicero/cicimc.h>`.
=> [MSCTFIME][SDK] Implement CtfImeSelectEx

dll/win32/shell32/CDefView.cpp
Based on KRosUser's `cdefview_fixstatus.patch`.
JIRA issue: [CORE-19406](https://jira.reactos.org/browse/CORE-19406)
- In `CDefView::OnSize`, call `_ForceStatusBarResize` function instead of `_HandleStatusBarResize` function.
=> [SHELL32] Fix status bar part sizes

base/applications/regedit/childwnd.c
Based on KRosUser's `regedit_loadfix.patch`.
JIRA issue: [CORE-19298](https://jira.reactos.org/browse/CORE-19298)
- Fix the condition of enabling/disabling the "Load Hive" and `Unload Hive` menu items.
=> [REGEDIT] Fix condition of enabling load/unload hive menu item

dll/win32/imm32/imm.c
@HBelusca said in ReactOS Chat:
> hi, is it possible to disable those two dprints?
>
> > err:(../dll/win32/imm32/imm.c:949) pIMC was NULL
> > err:(../dll/win32/imm32/imm.c:849) pClientImc was NULL
>
> they come out every other second of usage of any app in ReactOS.
- Disable logging on two points by not using `IS_NULL_UNEXPECTEDLY` macro.
=> [IMM32] Disable some annoying logging

dll/win32/comdlg32/colordlg.c
Fix black cross drawing.
JIRA issue: [CORE-19403](https://jira.reactos.org/browse/CORE-19403), [CORE-19405](https://jira.reactos.org/browse/CORE-19405)
- Fix `HRGN` handle leak.
- Fix black cross coordinates.
BEFORE:
The black cross is not drawn.
AFTER:
The black cross is correctly drawn.
Win10:
The black cross is correctly drawn.
=> [COMDLG32] Color Picker: Fix black cross

hal/halx86/apic/halinit.c, hal/halx86/generic/halinit.c, hal/halx86/generic/up.c
Fixes SMP related bugs in hal.
- Don't use `CONFIG_SMP`, this isn't handled in (most of) hal
- Add a dummy HalpSetupProcessorsTable for UP
- Call HalpRegisterKdSupportFunctions only for processor 0
=> [HAL] Fix SMP initialization

base/applications/rapps/gui.cpp
Based on KRosUser's `RAPPS.patch`.
JIRA issue: [CORE-19409](https://jira.reactos.org/browse/CORE-19409)
- If `m_ApplicationView->GetFocusedItemData` was `NULL`, then do not ask for removal.
=> [RAPPS] Don't ask for 'remote from registry' when no selection

dll/win32/comctl32/button.c, win32ss/user/user32/controls/button.c
Based on KRosUser's `button_fixnotif.patch`.
JIRA issue: [CORE-6542](https://jira.reactos.org/browse/CORE-6542), [CORE-19384](https://jira.reactos.org/browse/CORE-19384)
- Notify `BN_CLICKED` to the parent on `WM_SETFOCUS` message handling if the button type was either `BS_RADIOBUTTON` or `BS_AUTORADIOBUTTON`, and if the button was unchecked.
=> [COMCTL32][USER32] RadioButton: Notify BN_CLICKED on WM_SETFOCUS

dll/ime/msctfime/msctfime.cpp, sdk/include/psdk/msctf.idl
- Add `CTextEventSink` class.
- Add `ITfTextLayoutSink` interface into `"msctf.idl"`.
=> [MSCTFIME][SDK] Half-implement CTextEventSink

dll/win32/comctl32/combo.c, win32ss/user/user32/controls/combo.c
Based on KRosUser's `combo_v3.patch`.
JIRA issue: [CORE-16376](https://jira.reactos.org/browse/CORE-16376)
- Set `CBF_NOROLLUP` flag on (`WM_CHAR` or `WM_IME_CHAR`) and `CBF_DROPPED` state.
=> [COMCTL32][USER32] ComboBox: Don't close listbox on letter type

base/applications/ctfmon/ctfmon.cpp, dll/ime/msctfime/msctfime.cpp, sdk/include/reactos/cicero/cicbase.h
Use `new(cicNoThrow)` instead of plain operator `new`.
- Define `CicNoThrow` structure and `cicNoThrow` macro in `<cicero/cicbase.h>`.
- Use `new(cicNoThrow)` instead of plain operator `new`.
=> [CTFMON][MSCTFIME][SDK] Define new(cicNoThrow) and use it

dll/win32/comctl32/edit.c, dll/win32/comctl32/listview.c, dll/win32/comctl32/treeview.c, win32ss/user/user32/controls/edit.c
Based on KRosUser's `memleak_comctl32.patch`.
JIRA issue: [CORE-19405](https://jira.reactos.org/browse/CORE-19405)
- Fix `HRGN` handle leaks.
=> [COMCTL32][USER32] EDIT & ListView & TreeView: Fix HRGN leaks

dll/win32/shell32/shlfileop.cpp
Based on @DougLyons 's `control-panel-copy-to-desktop-fix.patch`.
JIRA issue: [CORE-19210](https://jira.reactos.org/browse/CORE-19210)
- Delete needless `#ifdef __REACTOS__` guards because `shlfileop.cpp` is a forked file.
- Do `NULL` check against `feFrom->szFilename`.
=> [SHELL32] Don't crash on Control Panel item D&D

sdk/include/reactos/cicero/cicbase.h, sdk/include/reactos/cicero/cicuif.h
- Improve `cicGetFN` function.
- Add `CUIFColorTable`, `CUIFColorTableSys`, and `CUIFColorTableOff10` classes.
- Implement `cicInitUIFScheme`, `cicUpdateUIFScheme`, and `cicDoneUIFScheme` functions.
=> [SDK] cicuif.h: Add CUIFColorTable

dll/ime/msctfime/msctfime.cpp, dll/win32/msutb/msutb.cpp, dll/win32/msutb/precomp.h, sdk/include/reactos/cicero/cicuif.h
- Implement `cicInitUIFLib` and `cicDoneUIFLib` functions.
- Use them in `msctfime` and `msutb`.
- Add `CUIFSystemInfo` class in `<cicero/cicuif.h>`.
=> [MSCTFIME][MSUTB][SDK] Add cicInitUIFLib and cicDoneUIFLib

modules/rostests/winetests/msvcrt/CMakeLists.txt, sdk/cmake/gcc.cmake
This adds -mlong-double-64 to make the size of a long double 64 bits in GCC builds to match MSVC builds.
https://reactos.org/testman/compare.php?ids=92420,92423,92426
=> [CMAKE] Add GCC options to make a long double 64 bits

dll/win32/comctl32/tooltips.c
Based on KRosUser's `tooltip_tabfix.patch`.
ToolTip should expand tabs. Otherwise they will become squares.
JIRA issue: [CORE-5635](https://jira.reactos.org/browse/CORE-5635), [CORE-13651](https://jira.reactos.org/browse/CORE-13651)
- Add `DT_EXPANDTABS` flag for `DrawText`.
=> [COMCTL32] ToolTip: Expand tabs

win32ss/user/winsrv/consrv/frontends/gui/conwnd.c, win32ss/user/winsrv/consrv/frontends/gui/conwnd.h
The cursor is not supposed to blink if the console window is not active.
Ideally the blink timer would be turned completely off when the window is inactive but that would require the hack in `GuiWriteStream` to change to a `PostMessage` with a private message?  The scrolling code that uses the same timer would also need changes if scrolling is possible when the window is not active.
A compromise would perhaps be to set the timer to a larger value when the window is not active? `4 * CURSOR_BLINK_TIME`?
=> [CONSRV] Don't blink cursor if the console window is not active

dll/win32/shell32/folders/CRegFolder.cpp
Must add `\` path separator and handle INFOLDER.
```C++
static HRESULT MySHGetNameFromIDList(PCIDLIST_ABSOLUTE pidl, UINT sigdn, PWSTR*str)
{
*str = NULL;
IShellFolder *pSF;
PCUITEMID_CHILD child;
HRESULT hr = SHBindToParent(pidl, IID_PPV_ARG(IShellFolder, &pSF), &child);
if (SUCCEEDED(hr))
{
STRRET sr;
hr = pSF->GetDisplayNameOf(child, SHGDNF(LOWORD(sigdn)), &sr);
pSF->Release();
if (SUCCEEDED(hr)) hr = StrRetToStrW(&sr, child, str);
}
return hr;
}
...
PIDLIST_ABSOLUTE pidl;
SHGetSpecialFolderLocation(NULL, CSIDL_CONTROLS, &pidl);
PWSTR disp, rel, full;
MySHGetNameFromIDList(pidl, SIGDN_NORMALDISPLAY, &disp);
MySHGetNameFromIDList(pidl, SIGDN_PARENTRELATIVEPARSING, &rel);
MySHGetNameFromIDList(pidl, SIGDN_DESKTOPABSOLUTEPARSING, &full);
wprintf(L"%ls (%ls)\n%ls\n", disp, rel, full);
``` …
=> [SHELL32] RegFolder must correctly handle GetDisplayNameOf parsing paths

dll/win32/shell32/shlfileop.cpp
Based on KRosUser's `dragdropfixpart2.patch`.
JIRA issue: [CORE-19417](https://jira.reactos.org/browse/CORE-19417), [CORE-19211](https://jira.reactos.org/browse/CORE-19211)
- Check source file existence.
- `if (flFrom->bAnyDontExist) return ERROR_SHELL_INTERNAL_FILE_NOT_FOUND;`
=> [SHELL32] SHFileOperation: Fail elegantly if source doesn't exist

base/applications/rapps/gui.cpp, base/applications/rapps/include/appdb.h, base/applications/rapps/include/gui.h, base/applications/rapps/unattended.cpp
Providing quick access of Control Panel `"Add/Remove Programs"`.
JIRA issue: [CORE-19419](https://jira.reactos.org/browse/CORE-19419)
- Don't download the `rapps-db` database if `bAppwizMode` in `ParseCmdAndExecute` function.
- Add `CAppDB::GetAvailableCount` method.
- Add `CMainWindow::CheckAvailable` method.
- Use `CMainWindow::CheckAvailable` in some cases of `TVN_SELCHANGED` handling.
=> [RAPPS] Don't download database at startup if appwiz mode

sdk/lib/drivers/ntoskrnl_vista/io.c
Passing parameter-provided context results in missing WorkerRoutine and WorkItem when callback is executed.
=> [NTOSKRNL_VISTA] IoQueueWorkItemEx: Pass new context for the queue

dll/win32/kernel32/client/file/create.c
Improve readability and reduce code.
- Use `InitializeObjectAttributes` macro instead of initialize the ObjectAttributes member manually.
=> [KERNEL32] OpenFile(): Use InitializeObjectAttributes

dll/win32/shell32/shlfileop.cpp
Based on KRosUser's `copyerrorfix.patch`.
JIRA issue: [CORE-19414](https://jira.reactos.org/browse/CORE-19414)
- If `feFrom->szFilename` was empty, then use `feFrom->szFullPath` instead.
=> [SHELL32] Improve error message on copying files

drivers/network/tcpip/datalink/lan.c, drivers/network/tcpip/include/lan.h, drivers/network/tcpip/ip/transport/tcp/if.c
Fix some problems found in lwIP glue related to link status:
- NETIF_FLAG_LINK_UP was not updated properly
- Link speed, MTU and MaxPacketSize were only queried once (at init)
This will also ease update to lwIP 2.x, which requires NETIF_FLAG_LINK_UP to be set correctly.
- Update NETIF_FLAG_LINK_UP flag by calling netif_set_link_up/netif_set_link_down
- Update link speed, MTU and MaxPacketSize only when adapter goes to connected state
=> [TCPIP] Update link status each time link goes up

dll/cpl/joy/joy.c
Based on KRosUser's `joycancel.patch`. Enable `Esc` key and `Close` button.
JIRA issue: [CORE-19424](https://jira.reactos.org/browse/CORE-19424)
- Insert a line of `case IDCANCEL:`.
=> [JOY] Add IDCANCEL action to MainPageProc

sdk/tools/mkisofs/CMakeLists.txt
GCC 8.4 and Clang 13.0.1:
'cc1: note: unrecognized command-line option ‘-Wno-deprecated-non-prototype’ may have been intended to silence earlier diagnostics'
Addendum to 4e3bf25 (0.4.15-dev-6528).
- Add a check for Clang and its version
=> [MKISOFS] CMakeLists.txt: Add a check for Clang and its version

dll/win32/comctl32/edit.c, win32ss/user/user32/controls/edit.c
_Original patch by @I_Kill_Bugs._
_Fix Cursor being in middle of '...file name:' edit box when using 'Search' from the Explorer toolbar._
JIRA issue: [CORE-19407](https://jira.reactos.org/browse/CORE-19407)
_Do not use SetCaretPos in EDIT_SetCaretPos when not focused._
=> [COMCTL32][USER32] Fix caret position on text box of 'Search' pane

modules/rostests/winetests/ws2_32/sock.c
_Disable ReactOS specific tests which are not implemented yet._
JIRA issue: [ROSTESTS-385](https://jira.reactos.org/browse/ROSTESTS-385)
_Bypass part of test that uses MEM_WRITE_WATCH._
_Bypass three tests that are unimplemented: 1) WSPAcceptEx, 2) WSPConnectEx, and 3) WSPDisconnectEx_
winetest_ws2_32_fix_05.patch JID66261 on top of 0.4.15-dev-6526-g8d35887
VBox: https://reactos.org/testman/compare.php?ids=89111,89117 LGTM
KVM:  https://reactos.org/testman/compare.php?ids=89110,89118 LGTM
=> [WS2_32_WINETEST] Patch ws2_32:sock wine test to run on ReactOS

ntoskrnl/ke/amd64/krnlinit.c, ntoskrnl/ke/i386/kiinit.c, ntoskrnl/ke/krnlinit.c
Fix initialization of node block for application processors
- Initialize KeNodeBlock[0] statically
- Update KeNodeBlock[0]->ProcessorMask for all processors
=> [NTOS:KE] Fix initialization of node block for application processors

hal/halx86/generic/buildtype.c, hal/halx86/include/halp.h
Try to get the multiprocessor kernel to boot on x86 again.
- Correct the SYNCH_LEVEL definition for MP vs UP HALs
=> [HALX86] Fix some asserts on multiprocessor kernel

ntoskrnl/ke/amd64/stubs.c, ntoskrnl/ke/arm/thrdini.c, ntoskrnl/ke/i386/thrdini.c
Raise IRQL to `SYNCH_LEVEL` when exiting from the idle thread in the idle loop, in case it is scheduled for the execution. Then restore it back, after that's done. This is a bit similarly to the way it's done on x64.
This prevents bugcheck DRIVER_IRQL_NOT_LESS_OR_EQUAL when booting SMP x86 ReactOS, in `KiTimerExpiration` when calling it 2nd time. It happens because of IRQL levels mismatch, since `SYNCH_LEVEL` is identical to `DISPATCH_LEVEL` on UP, so it has no any difference there, but on MP systems it is different `IPI_LEVEL - 2`.
Do this for both x86 and arm architectures.
Also place the same code for x64 into `CONFIG_SMP` ifdefs, because it is completely useless and unnecessary on UP.
#5874 is badly needed to be applied, to see effect from these changes.
JIRA issue: …
=> [NTOS:KE] Set IRQL to SYNCH_LEVEL when exiting from idle after the thread is ready for execution

ntoskrnl/include/internal/ke_x.h, ntoskrnl/ke/arm/thrdini.c, ntoskrnl/ke/i386/thrdini.c
Acquire the PRCB lock before marking the thread ready for execution in dispatch interrupt routine for x86 and arm. This is needed because thread preparation routine (`KxQueueReadyThread`) releases `PRCB` lock, but does not acquire it, so that always must be done outside the function, same as in all its other usage cases.
This fixes an assert from release `PRCB` routine, when booting x86 ReactOS in SMP mode, because it attempts to release the lock when it is not actually acquired.
#5874 and #6386 PRs are badly needed to see an effect from these changes.
JIRA issue: [CORE-1697](https://jira.reactos.org/browse/CORE-1697)
=> [NTOS:KE] Acquire the PRCB lock before marking the thread ready for execution in dispatch interrupt routine for x86 and arm

ntoskrnl/include/internal/ke_x.h
On the uniprocessor kernel KiAcquirePrcbLock is a stub that doesn't modify the current Prcb's PrcbLock value. 
Quickly protect this assert around CONFIG_SMP
https://git.reactos.org/?p=reactos.git;a=blob;f=ntoskrnl/include/internal/ke_x.h;hb=ab528ac6ae105b19d457587dc680d8016720bc3d#l220
- Protect the new Prcb Check around a CONFIG_SMP preprocessor check
=> [NTOS:KE] Fix boot on UP build - PrcbLocks are not used on UP

media/doc/Romanian translation notes.txt
I proposed more flexible rules. The idea is to be a correct translation that is understandable by any computer user. It will be about both a correct translation and correctly formulated statements.
Rule number 6 does not exist, so it is removed.
Of course, if you agree with these changes I will apply them to every file that needs to be changed.
=> [DOC] Update Romanian translation notes.txt

ntoskrnl/ke/arm/kiinit.c, ntoskrnl/ke/i386/kiinit.c
Addendum to 96d5b62.
JIRA issue: [CORE-1697](https://jira.reactos.org/browse/CORE-1697)
=> [NTOS:KE/x86/arm] Fix boot process affinity

sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenuItem::OnPaintDef` method.
=> [SDK] cicuif.h: Fix CUIFMenuItem::OnPaintDef

sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenuItem::OnPaintO10` method.
=> [SDK] cicuif.h: Fix CUIFMenuItem::OnPaintO10

dll/win32/shell32/wine/classes.c
Update the internal `HCR_RegGetIconW` function to the Wine 9.1 state.
https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/shell32/classes.c#l213 These changes fix the problems when loading custom (user-defined) items icons from registry, like icons defined for the current user or for all users, instead of just default icons from root classes.
JIRA issue: [CORE-14758](https://jira.reactos.org/browse/CORE-14758)
Import the following fixes:
- Use the number of bytes instead of the number of characters in the length passed to `RegQueryValueExW`. Calculate this as multiplying the number of characters on size in bytes of one wide character, since the only length of characters is passed to the function. This fixes `ERROR_MORE_DATA` returned from `RegQueryValueExW`, because the passed number …
=> [SHELL32] Sync HCR_RegGetIconW to Wine 9.1

dll/win32/comctl32/tooltips.c
Based on KRosUser's `tooltip_fix.patch`.
JIRA issue: [CORE-19309](https://jira.reactos.org/browse/CORE-19309)
- Don't set text on default processing of `LPSTR_TEXTCALLBACK`.
=> [COMCTL32] ToolTips: Don't set text on default LPSTR_TEXTCALLBACK

dll/win32/msi/dialog.c, media/doc/WINESYNC.txt
_Fix heap assert in msi/dialog.c._
JIRA issue: [CORE-16693](https://jira.reactos.org/browse/CORE-16693)
_Implement Thomas Faber's suggestion to handle heap assert as noted below._
_Since there's not really something sensible to be done in the_
_"path contains no backslashes" case (adding a backslash seems pointless),_
_the PathAddBackslashW call was moved inside the if condition to avoid the crash._
=> [MSI] Fix heap assert in msi/dialog.c when installing Tortoise GIT

ntoskrnl/fstub/fstubex.c
Otherwise the USHORT members are aligned to 4-byte boundary which overflows the disk sector buffer and ultimately results in crash. This can be reproduced by trying to format the USB drive with Rufus.
Before:
After:
Partition is successfully created, but it fails later on with formatting it.
=> [NTOS:FSTUB] Pack the MASTER_BOOT_RECORD structure

dll/win32/msutb/msutb.cpp
- Half-implement `CTipbarGripper` class.
=> [MSUTB] Add CTipbarGripper

.github/workflows/build.yml
Sanity: do not mix different build configurations.
Addendum to f777e6bd and 732f223.
- Extend cache key.
=> [GITHUB] build.yml: Use all matrix values to restore Linux build cache

modules/rostests/kmtests/ntos_io/IoInterrupt.c, ntoskrnl/io/iomgr/irq.c
Fixes a pool corruption when trying to handle IRP_MN_REMOVE_DEVICE in the driver. The typical use of the `IoDisconnectInterrupt`:
```
if (DevExt->InterruptObject)
{
IoDisconnectInterrupt(DevExt->InterruptObject);
DevExt->InterruptObject= NULL;
}
```
- Initialize InterruptObject to NULL on failure
=> [NTOS:IO] Initialize InterruptObject to NULL on failure

dll/shellext/netshell/lang/es-ES.rc, dll/shellext/netshell/lang/pt-PT.rc, dll/shellext/netshell/lang/zh-TW.rc, dll/shellext/netshell/shfldr_netconnect.cpp
Some trivial tweaks that I saw while backporting other stuff:
- es-ES.rc/pt-PT.rc: undesired spaces at the end of groupboxes, which were used as a historic workaround ~ 10 years ago
- zh-TW.rc: wrong indentation (tabs instead of spaces)
- shfldr_netconnect.cpp: superfluous GPL duplication, unneeded exclamation-marks in dbg-prints, undesired double-space formatting
saves a few bytes
Just opened a PR to quickly drag it through the different toolchains via the buildbots.
=> [NETSHELL] Trivial tweaks

dll/cpl/desk/theme.c, dll/win32/uxtheme/ncscrollbar.c, dll/win32/uxtheme/nonclient.c, dll/win32/uxtheme/uxthemep.h
- Metrics and colours from the theme specified in the `pszThemeFileName`/`pszColorName`/`pszSizeName` parameters are now used, instead of the existing system metrics/colours
- The existing active preview window now has a client area, featuring a preview scrollbar and some preview text
- An inactive preview window is now drawn behind the active preview window
- A preview dialog window is now drawn in front of the active preview window, featuring a preview button
- [CORE-5991](https://jira.reactos.org/browse/CORE-5991)
=> [UXTHEME] Implement the rest of DrawNCPreview

dll/win32/msvidc32/msvideo1.c
Partially reverts https://github.com/reactos/reactos/pull/6118. It had caused a regression.
JIRA issue: [CORE-19453](https://jira.reactos.org/browse/CORE-19453), [CORE-15382](https://jira.reactos.org/browse/CORE-15382)
=> [MSVIDC32] Don't confuse CRAM_MAGIC with MSVC_MAGIC

win32ss/user/ntuser/ime.c, win32ss/user/ntuser/msgqueue.c
First attempt to fix IME hotkey processing around `IMM32!ImmProcessKey` function.
JIRA issue: [CORE-19455](https://jira.reactos.org/browse/CORE-19455)
- Optimize `IntImmProcessKey` a little.
- Remove `(Msg->message == WM_KEYDOWN)` condition for `IntImmProcessKey` function call.
=> [NTUSER] Relax condition for IntImmProcessKey

drivers/usb/usbstor/descriptor.c, drivers/usb/usbstor/pdo.c, drivers/usb/usbstor/usbstor.h
Serial number on some USB devices might exceed the number of 100 characters (eg. 120 characters on "SanDisk Ultra 3.2Gen1" pendrive) and cause buffer overflow, which results in usbstor.sys crash.
Before:
After:
JIRA issue: Possibly [CORE-17625](https://jira.reactos.org/browse/CORE-17625)
=> [USBSTOR] Fix PdoHandleQueryInstanceId and increase serial number descriptor size to MAXIMUM_USB_STRING_LENGTH

dll/win32/uxtheme/lang/uk-UA.rc, dll/win32/uxtheme/uxtheme.rc
Translate theme preview text in "Appearance" tab of "Desktop Properties" into Ukrainian.
Addendum to d11582f.
JIRA issue: [CORE-5991](https://jira.reactos.org/browse/CORE-5991)
- Add rc file with translated strings.
- Include it in main resource file.
=> [UXTHEME] Add Ukrainian (uk-UA) translation

dll/win32/dbghelp/path.c, sdk/lib/3rdparty/libwine/path.c
Wine code expects a non-null ret value. Seen with our GCC debug builds
JIRA issue: [CORE-19444](https://jira.reactos.org/browse/CORE-19444)
=> [LIBWINE] Return empty path when given a UNIX path

drivers/filesystems/ext2/src/read.c
I checked Read and Write: this is the only case where it is missing.
JIRA issue: [CORE-10645](https://jira.reactos.org/browse/CORE-10645)
Co-authored-by: Victor Martinez Calvo <vicmarcal@...>
=> [EXT2FS] Ext2Read(): Complete request on VCB_VOLUME_LOCKED case

win32ss/gdi/ntgdi/misc.h, win32ss/user/ntuser/metric.c, win32ss/user/ntuser/misc/registry.c
Improve code quality.
- Fix `const`-ness of the arguments of `win32k` registry helper functions.
- Compact `UserIsIMMEnabled` function.
=> [WIN32SS] Fix const-ness of registry helper functions

boot/bootdata/hivesft.inf, win32ss/user/ntuser/metric.c
- Add `"IME File"` registry value as `"msctfime.ime"` at `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\IMM`.
- Modify `UserIsCiceroEnabled` function for preparation of CTF IME.
=> [BOOTDATA][NTUSER] Prepare for CTF IME Part 1

dll/win32/shell32/dialogs/filetypes.cpp
I noticed it on releases/0.4.10 with the RosBEWin2.1.6 GCC4.7.2 **rls** configuration:
```
C:/0410rls/reactos/dll/win32/shell32/dialogs/filetypes.cpp: In function 'BOOL FileTypesDlg_InsertToLV(HWND, LPCWSTR, INT, LPCWSTR)':
C:/0410rls/reactos/dll/win32/shell32/dialogs/filetypes.cpp:663:9: warning: variable 'iLargeImage' set but not used [-Wunused-but-set-variable]
C:/0410rls/reactos/dll/win32/shell32/dialogs/filetypes.cpp: In function 'BOOL EditTypeDlg_UpdateEntryIcon(HWND, PEDITTYPE_DIALOG, LPCWSTR, INT)':
C:/0410rls/reactos/dll/win32/shell32/dialogs/filetypes.cpp:1040:9: warning: unused variable 'iLargeImage' [-Wunused-variable]
```
But I do assume, that MSVC compilers would also complain about that in **rls** cfg.
Please notice that before 0.4.10-dev-202-g …
=> [SHELL32] Fix 2 compiler warnings for the rls-configuration 'unused variable'

dll/win32/browseui/addressband.cpp
Retrial of #5052. Improve keyboard interface usability.
JIRA issue: [CORE-18823](https://jira.reactos.org/browse/CORE-18823)
- Add `GetAddressBarAccessKey` helper function to get the accelerator of Address bar from resource string `IDS_ADDRESSBANDLABEL`.
- Implement `Alt+D` (or something) accelerator in `CAddressBand::TranslateAcceleratorIO` method by handling `WM_SYSKEYDOWN` and `WM_SYSCHAR` messages.
https://github.com/reactos/reactos/assets/2107452/832e8abc-4d76-4ee4-b4bf-e6790d0a1964
=> [BROWSEUI] Enable Address bar access key (Alt+D)

dll/win32/shell32/CShellLink.cpp
Fix opening special folder.
JIRA issue: [CORE-19464](https://jira.reactos.org/browse/CORE-19464)
- In `CShellLink::DoOpen`, if there is a PIDL, then use it and set `SEE_MASK_IDLIST` flag.
https://github.com/reactos/reactos/assets/2107452/857b7f38-1832-4a1e-91ec-65f229242c4b
=> [SHELL32] Opening Special Folder shortcut

dll/win32/shell32/wine/brsfolder.c
`pszDisplayName` is for display name, not for full path.
JIRA issue: [CORE-5866](https://jira.reactos.org/browse/CORE-5866)
- If `lpBrowseInfo->pszDisplayName` is valid, use `SHGetFileInfoW` to get display name.
- Don't use `SHGetPathFromIDListW` to get display name. It's wrong.
BEFORE:
AFTER:
Win2k3:
=> [SHELL32] SHBrowseForFolder: Fix pszDisplayName

dll/cpl/appwiz/appwiz.h, dll/cpl/appwiz/createlink.c, dll/win32/shell32/CShellLink.cpp
Now we can open special folder shortcut, thanks to #6546.
Let's allow users to create various shortcut files.
JIRA issue: [CORE-5866](https://jira.reactos.org/browse/CORE-5866)
- Remove `BIF_RETURNONLYFSDIRS` flag because the system can open special folder shortcuts now.
- Add `LPITEMIDLIST pidlTarget` to `CREATE_LINK_CONTEXT` structure.
- Use `pidlTarget` if the target is a special folder.
- Fix `CShellLink::DoOpen` for arguments.
https://github.com/reactos/reactos/assets/2107452/c02146d7-6c1a-4b7b-a4f6-ac5a4eb748f0
- We can create `"My Computer"` shortcut.
- We can create `"My Documents"` shortcut.
- We can create `"Network"` shortcut.
- We can create `"C:\"` shortcut.
- We can create `"C:\Documents and Settings"` shortcut.
- We can create `"cmd /k dir"` shortcut.
=> [APPWIZ][SHELL32] Improve 'Create Shortcut' dialog

dll/win32/shell32/shellmenu/CMenuBand.cpp
JIRA issue: [CORE-17453](https://jira.reactos.org/browse/CORE-17453), [CORE-12328](https://jira.reactos.org/browse/CORE-12328)
In `CMenuBand::_TrackContextMenu` method:
- Use `100` for `idCmdFirst`, instead of zero.
- Use `uCommand - idCmdFirst` for `cmi.lpVerb`.
Zero is an invalid command ID.
I can open notepad from context menu.
=> [SHELL32] idCmdFirst shouldn't be zero

base/applications/mspaint/main.cpp, base/applications/mspaint/selectionmodel.cpp, base/applications/mspaint/selectionmodel.h
Follow-up to #6552. There was a bug that the cropped selection image is not the shape of selection.
JIRA issue: [CORE-19466](https://jira.reactos.org/browse/CORE-19466)
- Extend `SelectionModel::DrawSelection` for drawing selection flexibly.
- Improve `SelectionModel::GetSelectionContents` method.
=> [MSPAINT] Improve GetSelectionContents for free-shape selection

dll/win32/shell32/folders/CDrivesFolder.cpp, dll/win32/shell32/folders/CFSFolder.cpp, dll/win32/shell32/folders/CRegFolder.cpp, dll/win32/shell32/iconcache.cpp, dll/win32/shell32/wine/classes.c, dll/win32/shell32/wine/shell32_main.h
Load the custom icons defined for the current user and for all users from registry, in case they are defined there, instead of always loading default system-defined icons.
**Depends on #6418 PR (is merged now).**
JIRA issue: [CORE-14758](https://jira.reactos.org/browse/CORE-14758)
- Add a code to load the icons specified by user in registry in the following keys:
- `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CLSID\{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}\DefaultIcon` (virtual namespace folders);
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons` (file system folders and drives).
- Implement two functions `HCU_GetIcon` and `HLM_GetIcon`, ANSI and Unicode versions, those are reading the icons from HKCU and HKLM appropriately. Note …
=> [SHELL32] Allow using custom icons for folders, drives and Desktop places

modules/rostests/apitests/shell32/CMakeLists.txt, modules/rostests/apitests/shell32/SHRestricted.cpp, modules/rostests/apitests/shell32/testlist.c
I have a plan to implement `shell32!SHRestricted` correctly.
JIRA issue: [CORE-11515](https://jira.reactos.org/browse/CORE-11515)
- Get `SHRestricted` and `SHSettingsChanged` procedures from `shell32.dll`.
- Use them and check the results.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Skipped.
=> [SHELL32_APITEST] Add SHRestricted testcase

modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/SHGetRestriction.c, modules/rostests/apitests/shlwapi/testlist.c
I have a plan to implement `shell32!SHRestricted` correctly.
JIRA issue: [CORE-11515](https://jira.reactos.org/browse/CORE-11515)
In the testcase:
- Get procedure `SHGetRestriction` from `shlwapi.dll`.
- Call `SHGetRestriction` to test and check the results. 
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
=> [SHLWAPI_APITEST] Add SHGetRestriction testcase

base/shell/cmd/cmdinput.c
`Ctrl+H` should pretend like `BackSpace` key on Command Prompt.
JIRA issue: [CORE-5702](https://jira.reactos.org/browse/CORE-5702)
- Add `Ctrl+H`  action in `ReadCommand` function.
AFTER:
https://github.com/reactos/reactos/assets/2107452/0e61cc84-af3d-47fe-9cea-94ba255f2814
=> [CMD] Enable Ctrl+H (^H) as backspace

ntoskrnl/ke/amd64/interrupt.c
Fail instead of asserting. This is needed because a kmtest triggers it.
Fixes a kernel assertion failure.
=> [NTOS:KE/x64] Gracefully handle invalid Vector in KeConnectInterrupt

hal/halx86/apic.cmake, hal/halx86/apic/apic.c, hal/halx86/apic/apicp.h, hal/halx86/apic/apictrap.S, hal/halx86/apic/rtctimer.c, hal/halx86/generic/up.c, hal/halx86/include/halp.h, hal/halx86/include/smp.h, hal/halx86/smp.cmake, hal/halx86/smp/smp.c
This implements the clock IPI handler, which will ensure that all CPUs get the same time updates.
- Move apicsmp.c from lib_hal_apic to lib_hal_smp
- Implement the Clock IPI handler and broadcast the IPI from the clock handler (this is a no-op on up)
* GCC x86 KVM: https://reactos.org/testman/compare.php?ids=93637,93640,93644,93651
* MSVC x64 KVM: https://reactos.org/testman/compare.php?ids=93638,93642,93646,93652
=> [HALX86] Implement the clock IPI handler

dll/shellext/acppage/CLayerStringList.hpp
For simplicity and short typing. Macro `STDMETHOD` is defined in `<basetyps.h>` as follows:
```c
```
C++11 keyword override is used for checking whether the method is overrided.
- Replace `virtual HRESULT STDMETHODCALLTYPE m` with `STDMETHOD(m)` (`m` is a method name).
- Replace `virtual t STDMETHODCALLTYPE m` with `STDMETHOD_(t, m)` (`t` is a type. `m` is a method name).
- Use `override` keyword as possible.
=> [ACPPAGE] Use STDMETHOD macro and keyword override

dll/shellext/netshell/connectmanager.h, dll/shellext/netshell/enumlist.cpp, dll/shellext/netshell/lanconnectui.h, dll/shellext/netshell/lanstatusui.h, dll/shellext/netshell/shfldr_netconnect.h
For simplicity and short typing. Macro `STDMETHOD` is defined in `<basetyps.h>` as follows:
```c
```
C++11 keyword `override` is used for checking whether the method is overrided.
- Replace `virtual HRESULT STDMETHODCALLTYPE m` with `STDMETHOD(m)` (`m` is a method name).
- Replace `virtual t STDMETHODCALLTYPE m` with `STDMETHOD_(t, m)` (`t` is a type. `m` is a method name).
- Use `override` keyword as possible.
=> [NETSHELL] Use STDMETHOD macro and keyword override

base/shell/rshell/CQuickLaunchBand.h
For simplicity and short typing. Macro `STDMETHOD` is defined in `<basetyps.h>` as follows:
```c
```
C++11 keyword `override` is used for checking whether the method is overrided.
- Replace `virtual HRESULT STDMETHODCALLTYPE m` with `STDMETHOD(m)` (`m` is a method name).
- Replace `virtual t STDMETHODCALLTYPE m` with `STDMETHOD_(t, m)` (`t` is a type. `m` is a method name).
- Use `override` keyword as possible.
=> [RSHELL] Use STDMETHOD macro and keyword override

ntoskrnl/mm/ARM3/expool.c
Remove an ASSERT, which hits with SMP. While Windows seems to have multiple tracker tables, we shouldn't need this.
=> [NTOS:EX] Remove an ASSERT in ExpInsertPoolTracker

dll/win32/browseui/CProgressDialog.h, dll/win32/browseui/CTaskbarList.h, dll/win32/browseui/aclistisf.h, dll/win32/browseui/aclmulti.h, dll/win32/browseui/addressband.h, dll/win32/browseui/addresseditbox.h, dll/win32/browseui/bandproxy.h, dll/win32/browseui/basebarsite.cpp, dll/win32/browseui/brandband.h, dll/win32/browseui/commonbrowser.h, dll/win32/browseui/explorerband.h, dll/win32/browseui/globalfoldersettings.h, dll/win32/browseui/internettoolbar.cpp, dll/win32/browseui/internettoolbar.h, dll/win32/browseui/regtreeoptions.h, dll/win32/browseui/shellbars/CBandSite.h, dll/win32/browseui/shellbars/CBandSiteMenu.h, dll/win32/browseui/shellbars/CBaseBar.cpp, dll/win32/browseui/shellbars/CISFBand.h, dll/win32/browseui/shellbars/CSHEnumClassesOfCategories.cpp, dll/win32/browseui/shellbrowser.cpp, dll/win32/browseui/shellfind/CSearchBar.h, dll/win32/browseui/toolsband.cpp, dll/win32/browseui/travellog.cpp
For simplicity and short typing. Macro `STDMETHOD` is defined in `<basetyps.h>` as follows:
```c
```
C++11 keyword `override` is used for checking whether the method is overrided.
- Replace `virtual HRESULT STDMETHODCALLTYPE m` with `STDMETHOD(m)` (`m` is a method name).
- Replace `virtual t STDMETHODCALLTYPE m` with `STDMETHOD_(t, m)` (`t` is a type. `m` is a method name).
- Use `override` keyword as possible.
=> [BROWSEUI] Use STDMETHOD macro and keyword override

sdk/lib/atl/atlsimpstr.h
This public function is used to allocate memory for the string via private PrepareWrite, but it's missing somehow. Now it shouldn't be.
Implement CSimpleStringT::Preallocate function. Used in `ATL::CStringW` and `ATL::CStringA`, for example:
```c++
ATL::CStringW cswItemText = "";
cswItemText.Preallocate(64);
SendDlgItemMessageW(pdis->CtlID, LB_GETTEXT, pdis->itemID, reinterpret_cast<LPARAM>(cswItemText.GetBuffer()));
cswItemText.ReleaseBuffer();
```
- Update [atlsimpstr.h](https://github.com/reactos/reactos/blob/master/sdk/lib/atl/atlsimpstr.h)
=> [ATL] Implement CSimpleStringT::Preallocate

modules/rostests/apitests/user32/CMakeLists.txt, modules/rostests/apitests/user32/GW_ENABLEDPOPUP.c, modules/rostests/apitests/user32/testlist.c, sdk/include/psdk/winuser.h
JIRA issue: [CORE-6920](https://jira.reactos.org/browse/CORE-6920)
- Add `GW_ENABLEDPOPUP` constant to `<winuser.h>`.
- Add `GW_ENABLEDPOPUP` testcase.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
=> [SDK][USER32_APITEST] Add GW_ENABLEDPOPUP testcase

dll/ntdll/ldr/ldrutils.c, modules/rostests/apitests/ntdll/CMakeLists.txt, modules/rostests/apitests/ntdll/LdrLoadDll.c, modules/rostests/apitests/ntdll/testlist.c
JIRA issue: [CORE-6585](https://jira.reactos.org/browse/CORE-6585)
- Add one comment into `LdrpLoadDll` function.
- Add `LdrLoadDll` testcase.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
=> [NTDLL][NTDLL_APITEST] Add LdrLoadDll testcase

dll/win32/browseui/explorerband.cpp
Display correct menu on right-dragging an item in Folder explorer bar to Desktop.
JIRA issue: [CORE-19474](https://jira.reactos.org/browse/CORE-19474)
In `CExplorerBand::OnTreeItemDragging` method:
- Use `GetAttributesOf` to get the attributes of a folder item.
- Use correct `dwEffect` value for `DoDragDrop` call.
BEFORE:
AFTER:
=> [BROWSEUI] Fix CExplorerBand Right-Dragging menu

modules/rostests/apitests/shell32/FindExecutable.cpp
Make `shell32:FindExecutable` testcase stable and trustworthy.
JIRA issue: [ROSTESTS-389](https://jira.reactos.org/browse/ROSTESTS-389)
- Reduce dependency with sub-program (instead use copy of `notepad.exe`).
- Simplify.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
=> [SHELL32_APITEST] Improve FindExecutable testcase

dll/ime/msctfime/inputcontext.cpp, dll/ime/msctfime/inputcontext.h, sdk/include/psdk/msctf.idl
- Add `ITfContextOwner` interface to `"msctf.idl"`.
- Stub-implement `CInputContextOwner` class.
=> [MSCTFIME][SDK] Add CInputContextOwner (stub)

base/applications/kbswitch/kbswitch.c, dll/cpl/input/input.h, sdk/include/reactos/imm32_undoc.h
Unify the private IMM32 macro definitions. Refactoring...
- Define `IS_SPECIAL_HKL` macro in `<imm32_undoc.h>`.
- Use `IS_IME_HKL` and `IS_SPECIAL_HKL` macros of `<imm32_undoc.h>`, in `kbswitch` and `input` modules.
=> [KBSWITCH][INPUT][SDK] Use <imm32_undoc.h>'s IS_IME_HKL

modules/rostests/apitests/imm32/CMakeLists.txt, modules/rostests/apitests/imm32/KLID.c, modules/rostests/apitests/imm32/testlist.c
Confirming keyboard layout implementation by checking HKL, KLID, and registry.
- Add `KLID` testcase.
- Check HKLs, KLIDs (Keyboard Layout IDs), and related registry, with using `user32!GetKeyboardLayoutList` function.
Tests are all successful.
=> [IMM32_APITEST] Add KLID testcase

sdk/include/ndk/i386/ketypes.h, sdk/include/xdk/x86/ke.h
Fix some inconsistencies in definitions. May contribute fixing SMP support...
The official MS DDK/WDK does not expose KeGetPcr() for x86, so do
not expose it there as well. Use instead the private NDK definition.
If it were exposed in the DDK/WDK, it would have to be a
multiprocessor-compatible definition.
Note that the broken definition was working only in single-processor
mode, using the PCR static memory pointer value.
The official MS DDK/WDK exposes KeGetPcr() as an alias to such a
PCR value only for IA64, MIPS and PPC, which is of course not great.
=> [SDK:NDK/XDK] Remove x86 KeGetPcr() definition from the DDK

sdk/include/ndk/inline_ntcurrentteb.h, sdk/include/ndk/psfuncs.h, sdk/include/xdk/arm/ke.h, sdk/include/xdk/winnt_old.h
Fix some inconsistencies in definitions and complete some others.
Affect ARM(64) platforms too.
```
[SDK:NDK/XDK] Adjust the KeGetPcr() ARM definition
Re-enable the KIPCR() macro and use it for KeGetPcr()
and KeGetCurrentProcessorNumber() definitions.
```
```
[SDK:NDK/XDK] Sync NtCurrentTeb() definitions between NDK and PSDK winnt.h
The definitions in the NDK inline_ntcurrentteb.h and psfuncs.h files are
synced togther with those of winnt.h (in the winnt_old.h generator file).
See commits c1929445d (r49627) and 925c587c8 (r56318).
IMPORTANT NOTE: The ARM64 definition is not yet existent in our headers!
```
=> [SDK:NDK/XDK] Improve KeGetPcr() and NtCurrentTeb() definitions for some platforms

base/shell/explorer/precomp.h, base/shell/explorer/startmnucust.cpp, base/shell/explorer/startmnusite.cpp, base/shell/explorer/util.cpp, dll/win32/shell32/dialogs/general.cpp, sdk/include/reactos/undocshell.h
Improve Start Menu customization.
- Add `SHSettingsChanged` prototype to `<undocshell.h>`.
- Add `SetRestriction` helper function.
- Implement showing/hiding `Run` menu item of Start Menu.
=> [EXPLORER][SHELL32][SDK] Show/hide 'Run' menu item

boot/boot_images.cmake
We shouldn't create an empty `CSIDL_ADMINTOOLS` folder at initial status.
JIRA issue: [CORE-12328](https://jira.reactos.org/browse/CORE-12328)
- Modify `boot/boot_images.cmake`.
AFTER:
=> [BOOT] Don't create empty CSIDL_ADMINTOOLS folder

base/shell/explorer/precomp.h, base/shell/explorer/startmnucust.cpp, base/shell/explorer/startmnusite.cpp, base/shell/explorer/util.cpp, dll/win32/shell32/shellmenu/CStartMenu.cpp
Correct the details of Start Menu customization.
- Hide the setting item if the item is restricted.
- Don't change restriction in Explorer.
- Fix Start Menu settings for restriction and registry.
- Fix and simplify code.
=> [EXPLORER][SHELL32] Fix and improve Start Menu customization

base/shell/explorer/startmnucust.cpp, dll/win32/shell32/shellmenu/CMenuToolbars.cpp, dll/win32/shell32/shellmenu/CStartMenu.cpp
Improve Start Menu customization.
- Add `IsPidlPrograms` helper function.
- Specify a PIDL for Programs menu.
- Check the `"StartMenuAdminTools"` registry value.
- Don't add "Admin Tools" menu item into `CMenuSFToolbar::FillToolbar` if necessary.
=> [EXPLORER][SHELL32] Show/hide 'Admin tools' menu

win32ss/user/ntuser/msgqueue.c
_Fix MSO and Word Viewer not closing when "X" on title bar is clicked._
_This is another @I_Kill_Bugs patch._
JIRA issue: [CORE-14436](https://jira.reactos.org/browse/CORE-14436)
JIRA issue: [CORE-16985](https://jira.reactos.org/browse/CORE-16985)
_Fix MsgFilterLow/MsgFilterHigh handling for nonclient areas for mouse events._
=> [NTUSER] Fix PeekMessageA for MsgFilterLow/High mouse clicks

base/shell/explorer/startmnucust.cpp
Follow-up to #6596. Enable the Favorite menu setting.
- Use `TreeView_GetRoot` instead of `TreeView_GetFirstVisible` in `CustomizeClassic_OnOK` function.
=> [EXPLORER] Start Menu Customize: Use TreeView_GetRoot

dll/win32/shell32/shellmenu/CMenuToolbars.cpp
Follow-up to #6603. Fix a bug in Admin Tools display.
- Fix the value of `bMustHideAdminTools` in `CMenuSFToolbar::FillToolbar`.
=> [SHELL32] Start Menu Customize: Fix bMustHideAdminTools

dll/win32/shell32/shellmenu/CStartMenu.cpp
Improve Start Menu usability.
JIRA issue: [CORE-19477](https://jira.reactos.org/browse/CORE-19477)
- Add `CSIDLFromID` helper function.
- Return a context menu interface at `CShellMenuCallback::OnGetContextMenu`.
=> [SHELL32] Start Menu: Enhance context menu

dll/win32/shell32/folders/CRegFolder.cpp
Fix memory leak.
JIRA issue: [CORE-19478](https://jira.reactos.org/browse/CORE-19478)
- Use `CoTaskMemFree` for `pwszCLSID` to avoid memory leak in `CGuidItemContextMenu_CreateInstance` function.
=> [SHELL32] CGuidItemContextMenu: Fix pwszCLSID leak

win32ss/user/user32/windows/cursoricon.c
_Current Debug Log shows bad header size when PNG found in ICO file._
_Now detect the condition and print an appropriate message to the Debug log._
JIRA issue: [CORE-19107](https://jira.reactos.org/browse/CORE-19107)
_Add code to detect PNG embed in ICO file and print appropriate message to debug log._
_Maybe this will lead to a more correct handling code being implemented._
Debug log Before:
```
err:(win32ss/user/user32/windows/cursoricon.c:201) (1196314761): unknown/wrong size for header
err:(win32ss/user/user32/windows/cursoricon.c:201) (1196314761): unknown/wrong size for header
err:(win32ss/user/user32/windows/cursoricon.c:201) (1196314761): unknown/wrong size for header
err:(win32ss/user/user32/windows/cursoricon.c:201) (1196314761): unknown/wrong size for header …
```
=> [USER32] Show Debug Log Message when unhandled PNG found in ICO file

dll/win32/comctl32/treeview.c
Fix checkboxed treeview selection display.
JIRA issue: [CORE-19480](https://jira.reactos.org/browse/CORE-19480)
- Make the first argument of `TREEVIEW_ToggleItemState` non-`const`.
- Select the item by calling `TREEVIEW_SelectItem` in `TREEVIEW_ToggleItemState`.
BEFORE:
AFTER:
=> [COMCTL32] TreeView: Fix selection display on checking checkbox

modules/rostests/apitests/shell32/CMakeLists.txt, modules/rostests/apitests/shell32/ShellExecuteEx.cpp
Making the tests trustworthy.
JIRA issue: [ROSTESTS-389](https://jira.reactos.org/browse/ROSTESTS-389)
- Enable command line checking.
- Rewrite the tests for better tests.
- Remove dependency with `shell32_apitest_sub`.
- Close the newly opened windows by `Alt+F4` at ending.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
ReactOS:
FAILED.
=> [SHELL32_APITEST] Make ShellExecuteEx testcase stable

dll/win32/shlwapi/ordinal.c, sdk/include/reactos/shlwapi_undoc.h
- Implement `SHSetDefaultDialogFont` function.
- Add `SHSetDefaultDialogFont` prototype to `<shlwapi_undoc.h>`.
=> [SHLWAPI] Implement SHSetDefaultDialogFont

modules/rostests/apitests/shell32/ShellExecuteEx.cpp
Follow-up to #6617.
JIRA issue: [CORE-19482](https://jira.reactos.org/browse/CORE-19482)
- Add `trace`s for error checking.
Win2k3:
Successful.
=> [SHELL32_APITEST] ShellExecuteEx: Fix command line checker

sdk/include/reactos/mc/errcodes.mc
Localize the error messages.
- Modify `errcodes.mc` for Japanese localization.
=> [SDK][MC] errcodes.mc: Add Japanese (ja-JP) translation

base/applications/mspaint/main.cpp, base/applications/mspaint/registry.cpp
Improve usability.
JIRA issue: [CORE-19485](https://jira.reactos.org/browse/CORE-19485)
- Enable the menu items to set the wallpapars.
- Save the current bitmap as file `Wallpaper1.bmp` in `CSIDL_LOCAL_APPDATA` folder.
- Support JPEG/PNG/GIF/TIFF files in `RegistrySettings::SetWallpaper`.
Tested our AFTER `mspaint` on Win2k3:
=> [MSPAINT] Support JPEG/PNG/GIF/TIFF wallpapers

dll/win32/shlwapi/assoc.c
Step up to correct `shell32!FindExecutable`.
- Add `ASSOCF_INIT_NOREMAPCLSID` flag to `SHLWAPI_DEF_ASSOCF` flags.
=> [SHLWAPI] SHLWAPI_DEF_ASSOCF: Add ASSOCF_INIT_NOREMAPCLSID

ntoskrnl/inbv/inbv.c
Fix an infinite loop. This only works currently, because ntoskrnl is the first module.
=> [NTOS:EX] Fix a loop bug

dll/win32/dbghelp/CMakeLists.txt
Remove some defines that are not needed, because they are defined in winnt.h. One was also wrong. Fixes compiler warnings.
=> [DBGHELP] Remove useless broken CMake defines

sdk/include/crt/mingw32/intrin_x86.h
=> [CRT] intrin_x86.h: Use movsl instead of movsd to fix a GCC 13 warning

modules/rostests/apitests/shell32/CMakeLists.txt, modules/rostests/apitests/shell32/RealShellExecuteEx.cpp, modules/rostests/apitests/shell32/ShellExecuteEx.cpp, modules/rostests/apitests/shell32/closewnd.cpp, modules/rostests/apitests/shell32/closewnd.h, modules/rostests/apitests/shell32/testlist.c
Follow-up to #5849.
- Add `closewnd.cpp`, `closewnd.h`, and `RealShellExecuteEx.cpp` files.
- In `closewnd.cpp`, close newly-opened windows.
- Add `RealShellExecuteEx` testcase.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Skipped.
ReactOS:
FAILED.
=> [SHELL32_APITEST] Add RealShellExecuteEx testcase

modules/rostests/apitests/shlwapi/AssocQueryString.c, modules/rostests/apitests/shlwapi/CMakeLists.txt, modules/rostests/apitests/shlwapi/testlist.c
- Add `AssocQueryString` testcase.
- Test `AssocQueryStringA` and `AssocQueryStringW` functions.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
ReactOS:
FAILED.
=> [SHLWAPI_APITEST] Add AssocQueryString testcase

sdk/tools/rsym/rsym64.h
Sync the `enum` (values) to the `DEFINE`s everywhere else.
Follow-up to  #6641.
- Sync UNW_FLAG_* values
=> [RSYM/x64] Sync UNW_FLAG_* values

base/applications/notepad/lang/ro-RO.rc
I fixed the entire translation and all the accelerators. Now everything is like in MSDN.
=> [NOTEPAD] Update Romanian (ro-RO) translation

dll/win32/shell32/shlfolder.cpp, sdk/include/reactos/shellutils.h
- Free pidl from `ILCombine`.
- `ILGetNext` will never return NULL on valid input, it is not the correct way to check.
=> [SHELL32] SHOpenFolderAndSelectItems should handle children correctly

ntoskrnl/config/cmapi.c, ntoskrnl/config/ntapi.c, ntoskrnl/include/internal/cm.h
A hive whose KCBs have a reference count of 0, meaning nobody is using these keys anymore, will not get removed from the cache table. As a result during normal hive unloading you will get orphaned KCBs which results in an unload failure.
This is wrong, because this is what a normal hive unloading is supposed to do. What it cannot do of course is that it cannot scramble the references of opened keys by the users who use the Registry, as it is the job of force unloading mechanism to do that.
Also remove a misleading debug print. Force unloading works as intended by scrambling the references of keys and marking the KCB for deletion, which is what how a force unload works. Namely Windows does exactly that.
Whilst this patch does not fix the issue mentioned in the ticket below, it is a small …
=> [NTOS:CM] Remove orphaned KCBs of keys during normal hive unload

modules/rosapps/applications/devutils/shlextdbg/CMakeLists.txt, modules/rosapps/applications/devutils/shlextdbg/shlextdbg.cpp
Added multiple new actions, most of them will use the system default implementation but can be forced to use a specific CLSID or IShellFolder implementation.
- /shgfi (SHGetFileInfo)
- /assocq (IQueryAssociations)
- /shellexec (ShellExecuteEx on pidl)
- /dumpmenu (Dumps the HMENU of a IContextMenu with its menu ids and verbs)
Added /explorerinstance as a new wait mode and made it the default. All the other wait modes are hacks that just works around bugs in ROS.
=> [SHLEXTDBG] Added IQueryAssociations, SHGetFileInfo and ShellExecute actions

dll/win32/shell32/folders/CDesktopFolder.cpp, dll/win32/shell32/folders/CFSFolder.cpp, dll/win32/shell32/shfldr.h, dll/win32/shell32/shlfolder.cpp
Fixes the reg class key order for FS items. The existing code was close but for some reason used `//` as the path separator for SystemFileAssociations!
- Fixed SystemFileAssociations.
- Swapped the order of `*` and `AllFilesystemObjects`. This is [the documented order](https://learn.microsoft.com/en-us/windows/win32/shell/fa-associationarray#about-association-arrays) and can also be observed in Process Monitor.
- Removed `(..., L"%s//%s", extension, wszClass)`, this does not seem to be a valid thing (`.TestAAExtWeird` in my tests).
- Adds the `Unknown` class when appropriate. Not adding the `openas` verb to `Unknown` rgs registration now to mimic Windows because ROS `CDefaultContextMenu` lacks verb de-duplication and the menu would end up with two Open With entries. This just uses `(cidl …
=> [SHELL32] Fix FS folder assoc array class order

dll/win32/shell32/CQueryAssociations.cpp
Implementing correct `FindExecutable`...
- If there were filename extension, then skip to the extension by using `PathFindExtensionW`.
- Use `"open"` verb if there is no default action if possible.
- Set `outlen` at `CQueryAssociations::ReturnString`.
BEFORE:
12 failures.
AFTER:
9 failures. `AssocQueryStringW` failures are reduced. LGTM.
=> [SHELL32] IQueryAssociations: Fix path and length

base/applications/notepad/lang/sl-SI.rc
Translate notepad and fix some characters being displayed wrong.
- Fix accelerators if needed??
- Remove comments if needed
- English translation of STRING_PRINTFAILED is wrong, should be either Printing failed or Printing has failed 
=> [NOTEPAD] Update Slovenian (sl-SI) translation

dll/win32/shell32/shlexec.cpp
Follow-up to #6656. An approach to implement `ShellExecuteEx` correctly.
- Rewrite code by using `AssocQueryStringW` and `PathResolveW` functions.
Win2k3:
Successful.
BEFORE:
81 failures.
AFTER:
Reduced down to 4 failures. LGTM.
=> [SHELL32] Improve FindExecutableW

dll/win32/shell32/CQueryAssociations.cpp
Follow-up to #6656. I had forgotten to check the slash.
- Add `StrChrW(pszAssoc, L'\\')` check before `PathFindExtensionW` call.
=> [SHELL32] CQueryAssociation: Add slash check

ntoskrnl/ke/amd64/trap.S
This is required since while interrupts are enabled, another user APC could get queued and we want to guarantee that those are all delivered before returning to user mode.
- ✅ https://reactos.org/testman/compare.php?ids=94266,94282,94307,94317
=> [NTOS:KE/x64] Loop in KiInitiateUserApc

boot/freeldr/freeldr/include/peloader.h, boot/freeldr/freeldr/lib/peloader.c, boot/freeldr/freeldr/ntldr/winldr.c, ntoskrnl/mm/ARM3/sysldr.c
Add support for security cookie generation in Freeloader (based on the code from [kernel](https://github.com/reactos/reactos/blob/88107adc9249bcc7eb691a8b3f97a797bb58d5ab/ntoskrnl/mm/ARM3/sysldr.c#L2898)). This allows core modules (kernel/HAL/KD dlls) or boot-start drivers from Windows 8+ loaded with FreeLDR to work (on master+this PR, this can be already tested with null.sys from Windows 8 RTM loaded as a boot-start driver). 
JIRA issue: [CORE-17808](https://jira.reactos.org/browse/CORE-17808)
=> [FREELDR][NTOS:MM] Add security cookie generation to FreeLoader

ntoskrnl/mm/ARM3/virtual.c
This was introduced by commit https://github.com/reactos/reactos/commit/c7e09061ca
So, this is basically just a revert of this commit. I did move a block of the reverted code from miarm.h to virtual.c.
_Fix intermittent BSOD 0x0000001a in mm/ARM3/virtual.c._
JIRA issue: [CORE-18190](https://jira.reactos.org/browse/CORE-18190)
JIRA issue: [CORE-18818](https://jira.reactos.org/browse/CORE-18818)
JIRA issue: [CORE-19253](https://jira.reactos.org/browse/CORE-19253)
and probably others.
_Mostly revert all of the referenced commit in two out of three files._
_One file is left unreverted (page.c). Combine changes in other two files into new virtual.c changes._
_There was a code block regarding ```__MI_PAGING_LEVELS``` in 'ntoskrnl\mm\ARM3\miarm.h'._
_These lines are what I moved into virtual.c …
=> [NTOS:MM] Fix ntoskrnl/mm/ARM3/virtual.c causing intermittent BSOD 0x1a

ntoskrnl/ke/amd64/trap.S
Remove duplicated REX prefix from sysretq
=> [NTOS:KE/x64] Remove duplicated REX prefix from sysretq

dll/win32/kernel32/client/sysinfo.c, dll/win32/kernel32/kernel32.spec, dll/win32/kernel32/kernel32_vista/CMakeLists.txt, dll/win32/kernel32/kernel32_vista/firmware.c, dll/win32/kernel32/kernel32_vista/kernel32_vista.spec, modules/rostests/apitests/kernel32/UEFIFirmware.c, sdk/include/psdk/winbase.h
Implement and export NT6+ firmware API.
Addendum to [PR #5149](https://github.com/reactos/reactos/pull/5149), thanks to kernel32_vista_static introduced in later PR, that's the proper place they should exist.
- Implement `GetFirmwareType` and improve existing API test for it
- Move `(Get/Set)FirmwareEnvironmentVariableEx(A/W)` to `kernel32_vista_static` and export them when NT version >= 6.2
apitest on Windows:
=> [KERNEL32][KERNEL32_APITEST][KERNEL32_VISTA] Implement and export NT6+ firmware API

ntoskrnl/config/cmsysini.c
The problem is detailed in the JIRA ticket: https://jira.reactos.org/browse/CORE-17904. In case of failure, `ObInsertObject` itself dereferences the object, so calling `ObDereferenceObject` one more time in the failure handler is redundant.
JIRA issue: [CORE-17904](https://jira.reactos.org/browse/CORE-17904)
- Remove `ObDereferenceObject` call from `CmpCreateRegistryRoot` in case `ObInsertObject` fails.
- Add missing `RootKey` dereference if `CmpCreateRegistryRoot` failed to get the key cell (`KeyCell`).
=> [NTOS:CM] Avoid unnecessary ObDereferenceObject when handling an ObInsertObject failure

ntoskrnl/ke/amd64/trap.S, ntoskrnl/ke/amd64/traphandler.c
This is needed, because KiSystemCallHandler can be called multiple times for the same syscall entry, which would mess up the linkage.
- https://reactos.org/testman/compare.php?ids=94343,94347,94351,94359
=> [NTOS:KE/x64] Move setting the thread's trap frame to KiSystemCallEntry64

drivers/bus/acpi/eval.c, drivers/bus/acpi/include/acpisys.h, drivers/bus/acpi/main.c, drivers/bus/acpi/precomp.h, modules/rostests/apitests/acpi/Bus_PDO_EvalMethod.c, modules/rostests/apitests/acpi/CMakeLists.txt, modules/rostests/apitests/acpi/testlist.c
This will enable the IDE driver with some hack to execute the _STM (channel timing settings) control method.
- Implement support for complex input buffers
- Fix a memory leak
- Fix returned status code
- Correctly calculate the output buffer size
- Improve buffer validation
- Implement support for async control requests
- Implement local reference conversion
- Implement support for subpackage argument conversion
- Place some code into INIT section
=> [ACPI] Fix object evaluation

ntoskrnl/mm/ARM3/virtual.c
A fix for BSOD 0x1A caused by commit [c7e09061ca](https://github.com/reactos/reactos/commit/c7e09061ca) without re-introducing `MiQueryPageTableReferences`.
It seems that the code introduced by commit [c7e09061ca](https://github.com/reactos/reactos/commit/c7e09061ca) forgot to update `PrototypePte` before exiting loop when deleting PDE.
After applied this PR, I'm unable to reproduce API Monitor BSOD and SumatraPDF 3.1.2 zoom BSOD. Chromium-XP (49.0.2623.113-R2 VS2015 SSE2 from RAPPS) is usable.
This revert commit [0c612980a](https://github.com/reactos/reactos/commit/0c612980ac9699c329035fe25753a52650e28ff3) ([#6633](https://github.com/reactos/reactos/pull/6633)).
JIRA-issue: [CORE-18818](https://jira.reactos.org/browse/CORE-18818) and many duplicates of that like e.g.: …
=> [NTOS:MM] Fix MiDeleteVirtualAddresses

ntoskrnl/ke/amd64/trap.S, sdk/include/asm/trapamd64.inc
This adds some asm macros for trap handling, uses them in the right places. It also fixes some problems, that existed before. The macros will be reused in other places.
- Add ASSERT_TRAP_FRAME_INTS_ENABLED, ASSERT_TRAP_FRAME_IRQL_VALID and ASSERT_IRQL_PASSIVE
- Add HANDLE_USER_APCS, make it versatile enough to be able to pass a register for the current thread and the trap frame
- https://reactos.org/testman/compare.php?ids=94343,94347,94351,94366
=> [NTOS:KE/x64][SDK] Improve trap handling with some asm macros

base/shell/rshell/misc.cpp, dll/win32/shell32/dialogs/folder_options.cpp, dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp, sdk/include/reactos/undocshell.h
Options_RunDLL is supposed to reuse the same window.
On newer Windows versions, tab switching is also supported:
````bat
rundll32 shell32.dll,Options_RunDLL 0& REM General tab
ping localhost
rundll32 shell32.dll,Options_RunDLL 7& REM View tab
REM Should be on the View tab now
rundll32 shell32.dll,Options_RunDLL 1& REM Open the taskbar options
````
=> [SHELL32] Handle the Progman Folder options message and tab switching support

sdk/lib/rtl/amd64/unwind.c
This can fail on optimized builds, where functions can end after a noreturn function call without an epilog / ret, but with an int 3. We simply fail gracefully, which is the right thing to do.
=> [RTL/x64] Remove an ASSERT in RtlpTryToUnwindEpilog

dll/win32/comctl32/status.c
Patch by @I_Kill_Bugs
_Fix bottom right drag triangle updates when window is resized._
JIRA issue: [CORE-19497](https://jira.reactos.org/browse/CORE-19497)
_Make STATUSBAR_WMSize Invalidate rectangle when window is resized._
PR#6696 refs/pull/6696/merge on top of 0.4.15-dev-7857-g24b4026
KVM:  https://reactos.org/testman/compare.php?ids=94433,94435
VBox: Builder Broken
=> [COMCTL32] Fix Status Bar Updating
