reactos/reactos

- base/applications/mspaint/canvas.cpp
- base/applications/mspaint/canvas.h
- base/applications/mspaint/common.h
- base/applications/mspaint/selectionmodel.cpp
- base/applications/mspaint/selectionmodel.h
- base/applications/mspaint/sizebox.cpp
- base/applications/mspaint/sizebox.h
Improve code readability.
- `s/CANVAS_HITTEST/HITTEST/`
- `s/m_whereHit/m_hitCanvasSizeBox/`
- `s/m_rcNew/m_rcResizing/`
- Add comments to `CCanvasWindow`.
> [MSPAINT] Rename some identifiers

- base/applications/fontview/lang/pl-PL.rc
[FONTVIEW] Update Polish (pl-PL) translation
> [FONTVIEW] Update Polish (pl-PL) translation

- hal/halx86/generic/halinit.c
- hal/halx86/legacy/halpcat.c
JIRA issue: [CORE-16302](https://jira.reactos.org/browse/CORE-16302)
> [HALX86] Bugcheck in case the ACPI initialization failed (for ACPI HAL)

- dll/win32/tapiui/lang/ro-RO.rc
> [TAPIUI] Improve Romanian (ro-RO) translation

- base/applications/cmdutils/tasklist/lang/pl-PL.rc
[TASKLIST] Update Polish (pl-PL) translation
> [TASKLIST] Update Polish (pl-PL) translation

- base/applications/cmdutils/mode/lang/ro-RO.rc
I want to fix the mistake when I translated a commented line.
Relates to #5425.
> [MODE] Improve Romanian (ro-RO) translation

- base/applications/mstsc/lang/ro-RO.rc
I forgot to add the year 2023 near my name.
> [MSTSC] Adding the current year in the copyright

- sdk/lib/dmilib/dmilib.h
- sdk/lib/udmihelp/udmihelp.h
Favor pragma once over the include guards. Is shorter.
> [DMILIB][UDMIHELP] Favor pragma once

- dll/win32/framedyn/chstring.cpp
- ntoskrnl/include/internal/mm.h
- sdk/include/psdk/chstring.h
- sdk/tools/txt2nls/main.cpp
Some quick fixes for compilation issues I faced on Fedora 37
See individual commits
> Misc compilation fixes

- base/applications/taskmgr/procpage.c
> [TASKMGR] Process page: Don't hardcode string length

- dll/win32/mscat32/mscat32.spec
> [MSCAT32] Convert stubs into forwarders

- ntoskrnl/mm/section.c
The VAD / memory area can get deleted when calling MmUnmapViewOfSegment, so it must not be used after that.
> [NTOS:MM] Fix use-after-free error

- dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp
- dll/win32/shell32/stubs.cpp
- sdk/include/reactos/undocshell.h
- Implement `SHIsTempDisplayMode` function.
- Add `SHIsTempDisplayMode` prototype to `<undocshell.h>`.
> [SHELL32][SDK] Implement SHIsTempDisplayMode

- media/doc/3rd Party Files.txt
Add Microsoft WDF, update PCI-IDs information and add supplemental rdesktop path in that file.
> Update 3rd Party Files.txt

- base/applications/mspaint/lang/en-GB.rc
- dll/cpl/desk/lang/en-GB.rc
- dll/win32/shell32/lang/en-GB.rc
Fix spellings for en-GB locale.
Replaces PR #5503 with a narrower scope. Checked it doesn't affect third-party files [1](https://github.com/reactos/reactos/blob/master/media/doc/3rd%20Party%20Files.txt),[2](https://github.com/reactos/reactos/blob/master/media/doc/WINESYNC.txt).
\#Translation
Fixes:
- Centre.
- Colour.
- Customise.
- Unauthorise.
> [REACTOS] British English spellings

- base/setup/usetup/lang/pt-PT.h
Add three forgotten error codes to pt-PT.h file.
Update pt-PT Translation file
> [USETUP] Update Portuguese (pt-PT) translation

- dll/win32/comctl32/listview.c
Import a fix from Wine. Fix selection bug in folder details view.
[https://source.winehq.org/git/wine.git/commit/daf95aaadf3a59f0ccc129a853327417b5e4f07c](https://source.winehq.org/git/wine.git/commit/daf95aaadf3a59f0ccc129a853327417b5e4f07c)
Before:
[ReactOS_Before.webm](https://github.com/reactos/reactos/assets/86486978/abec91ce-b345-4720-bbb3-a9d0d079e758)
After:
[ReactOS_After.webm](https://github.com/reactos/reactos/assets/86486978/fc265e78-636b-4d66-9124-100f5abd8ad2)
> [COMCTL32] Listview: Import selection bug fix from Wine

- base/applications/cmdutils/attrib/attrib.c
- Simplify duplicated code by having one EnumFiles() function using
callbacks to perform actual action on enumerated files.
PrintAttribute() and ChangeAttribute() duplicate their functionality,
except for the actual difference of displaying the file attributes vs.
changing them.
Instead, move that per-file action into two callbacks, create a file
enumerator function that contains the common functionality, and make
it call the callback passed in parameter to it.
- Reparse points can be encountered during enumeration. In this case,
don't try to go into too many reparse-point levels (maximum two).
- Verify that paths/file names concatenation don't overflow (with the
StringCch* functions returning an error), as this could cause an
infinite loop in case of recursive-enumeration, and the …
> [ATTRIB] De-duplicate code; handle reparse points; verify path concatenation

- base/shell/cmd/lang/cs-CZ.rc
- base/shell/cmd/lang/el-GR.rc
- base/shell/cmd/lang/es-ES.rc
- base/shell/cmd/lang/id-ID.rc
- base/shell/cmd/lang/pl-PL.rc
- base/shell/cmd/lang/sk-SK.rc
- base/shell/cmd/lang/sq-AL.rc
- base/shell/cmd/lang/uk-UA.rc
- modules/rostests/tests/combotst/combotst.c
- modules/rostests/tests/edit/edittest.c
> fix: height word typo

- boot/freeldr/freeldr/lib/fs/ntfs.c
Addendum to f0d73e0 (and ab3bd82).
- Fix file encoding.
> [FREELDR] Convert ntfs.c to UTF-8 without BOM

- win32ss/user/winsrv/consrv/console.c
Only call CoUninitialize on SUCCEEDED
> [CONSRV] Only call CoUninitialize if initialized

- sdk/lib/crt/except/i386/cpp.s
- sdk/lib/crt/wine/cpp.c
- sdk/lib/crt/wine/cxx.h
- sdk/lib/crt/wine/except_i386.c
- sdk/lib/crt/wine/undname.c
- sdk/tools/winesync/crt.cfg
- sdk/tools/winesync/winesync.py
Syncs some CRT files shared with wine to wine-5.0 and reduces the difference to wine code.
x86 KVM:  https://reactos.org/testman/compare.php?ids=88774,88776,88791,88802,88820
> [CRT][WINESYNC] Sync crt wine 5.0

- dll/ntdll/def/ntdll.spec
- sdk/lib/rtl/unicode.c
Implement and export RtlCompareUnicodeStrings
> [RTL][NTDLL] Implement and export RtlCompareUnicodeStrings

- dll/win32/shlwapi/ordinal.c
- dll/win32/shlwapi/propbag.cpp
- modules/rostests/apitests/shell32/ShellState.cpp
- modules/rostests/winetests/shlwapi/ordinal.c
- sdk/include/reactos/shlwapi_undoc.h
Follow-up to #5546. Implementing missing features...
- Add `CDesktopUpgradePropertyBag` class.
- Implement `SHGetDesktopUpgradePropertyBag` function.
> [SHLWAPI][SDK][SHELL32_APITEST][SHLWAPI_WINETEST] Property Bag on Desktop Upgrade

- sdk/lib/rtl/handle.c
- sdk/tools/rsym/rsym64.c
- sdk/tools/utf16le/utf16le.cpp
- sdk/tools/winesync/winesync.py
- subsystems/csr/csrsrv/procsup.c
- subsystems/csr/csrsrv/status.h
- subsystems/mvdm/ntvdm/bios/bios32/bios32.c
- subsystems/mvdm/ntvdm/cpu/cpu.c
- win32ss/drivers/miniport/vga_new/vga.c
- win32ss/gdi/eng/device.c
- win32ss/gdi/eng/ldevobj.c
- win32ss/gdi/ntgdi/gdipool.c
- win32ss/reactx/dxg/historic.c
- win32ss/reactx/ntddraw/d3d.c
- win32ss/user/ntuser/desktop.c
- win32ss/user/ntuser/hook.c
- win32ss/user/ntuser/hotkey.c
- win32ss/user/ntuser/input.c
- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/ntuser/windc.c
- win32ss/user/user32/controls/ghost.c
- win32ss/user/user32/misc/misc.c
Fixing typos in code comments enhances code readability and comprehension for developers and collaborators.
JIRA issue: No Jira access and no issue
Fix misc typos in comments
> [MISC] Fix typos in comments

- dll/win32/kernel32/kernel32.spec
Improve a few kernel32 NT6 stubs
> [KERNEL32] Improve a few stubs

- dll/win32/kernel32/client/file/find.c
A little fixes for FindFirstFileExW behavior
- Release `RTL_RELATIVE_NAME_U` before function return
- Ignore `lpSearchFilter` completely as well as Windows, MSDoc said `lpSearchFilter` must be `NULL`, but `FindFirstFileExW` will not check it
> [KERNEL32] FindFirstFileExW: Don't forget to release RTL_RELATIVE_NAME_U, and ignore lpSearchFilter correctly

- base/applications/clipbrd/clipbrd.c
- base/applications/clipbrd/cliputils.c
- base/applications/clipbrd/winutils.c
- base/applications/clipbrd/winutils.h
This allows to see what files are being copied into clipboard.
JIRA issue: [CORE-19140](https://jira.reactos.org/browse/CORE-19140)
> [CLIPBRD] Support CF_HDROP format

- dll/win32/browseui/shellbrowser.cpp
Improve mouse usability.
JIRA issue: [CORE-16776](https://jira.reactos.org/browse/CORE-16776)
- Add `WM_APPCOMMAND` handling to the shell browser.
- Handle `APPCOMMAND_BROWSER_BACKWARD` and `APPCOMMAND_BROWSER_FORWARD`.
> [BROWSEUI] Support mouse back and forward buttons

- dll/win32/shlwapi/propbag.cpp
- dll/win32/shlwapi/shlwapi.spec
- Implement `IUnknown_QueryServicePropertyBag` function.
> [SHLWAPI] Implement IUnknown_QueryServicePropertyBag

- dll/win32/shdocvw/CMakeLists.txt
- dll/win32/shdocvw/mrulist.cpp
- sdk/include/reactos/shlobj_undoc.h
- sdk/include/reactos/shlwapi_undoc.h
Follow-up to #5626. Implementing missing features...
- Implement `CMruBase` class.
- Add delay import of `shell32`.
- Add  `RegCreateKeyExWrapW` prototype to `<shlobj_undoc.h>`.
> [SHDOCVW][SDK] Implement MRU List for Shell Bag, Part 2

- dll/cpl/timedate/timezone.c
Addendum to commit aa6923664. Dedicated to KRosUser and reactosfanboy ;)
JIRA issue: [CORE-18666](https://jira.reactos.org/browse/CORE-18666)
> [TIMEDATE] Fix the way the current time-zone is found in the list.

- win32ss/user/ntuser/class.c
If you're gonna probe, probe right...
> [WIN32K:NTUSER] Avoid TOCTOU in ProbeAndCaptureUnicodeStringOrAtom.

- base/applications/mspaint/precomp.h
- sdk/include/reactos/ui/CWaitCursor.h
- Add `sdk/include/reactos/ui/CWaitCursor.h`.
- Use it in `mspaint`.
> [MSPAINT][SDK] Add <ui/CWaitCursor.h>

- dll/win32/shdocvw/mrulist.cpp
Follow-up to #5646. Implementing missing features...
- Implement `CMruNode` class.
> [SHDOCVW] Implement MRU List for Shell Bag, Part 4

- drivers/wdm/audio/drivers/CMIDriver/cmicontrol/main.cpp
- drivers/wdm/audio/drivers/CMIDriver/cmicontrol/main.h
Yes, might slightly improve with x64,
but that wasn't even my main motivation.
(DLGPROC)-casts are nonsense even for x86 actually.
> [CMICONTROL] Avoid (DLGPROC) cast

- modules/rostests/tests/Imagelistviewer/main.c
> [IMAGELISTVIEWER] Avoid (DLGPROC) cast

- dll/win32/shdocvw/mrulist.cpp
- dll/win32/shdocvw/shdocvw_v1.rgs
- modules/rostests/apitests/shdocvw/CMakeLists.txt
- modules/rostests/apitests/shdocvw/MRUList.cpp
Follow-up to #5691. Implementing missing features...
- Strengthen `shdocvw_apitest` testcase.
- Fix `CLSID_MruPidlList` class.
WinXP:
Successful.
Win2k3:
Successful.
Successful.
> [SHDOCVW][SHDOCVW_APITEST] Implement MRU List for Shell Bag, Part 6

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- sdk/include/reactos/undocshell.h
- Add `OpenEffectiveToken` helper function.
- Implement `SHOpenEffectiveToken` and `SHGetUserSessionId` functions.
- Add them to `<undocshell.h>`.
> [SHELL32][SDK] Implement SHOpenEffectiveToken and SHGetUserSessionId

- dll/win32/shell32/shell32.spec
- dll/win32/shell32/utils.cpp
- sdk/include/reactos/undocshell.h
- Implement `SHInvokePrivilegedFunctionW` function.
- Add it to `<undocshell.h>`.
> [SHELL32][SDK] Implement SHInvokePrivilegedFunctionW

- dll/win32/shell32/shell32.spec
- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- sdk/include/reactos/undocshell.h
- Implement `SHTestTokenPrivilegeW` function.
> [SHELL32][SDK] Implement SHTestTokenPrivilegeW

- sdk/lib/crt/except/amd64/ehandler.c
Fixes crash of compiler_apitest pseh
for x64
> [CRT/x64] Fix a bug in __C_specific_handler

- ntoskrnl/mm/ARM3/pagfault.c
Fixes crash in ntdll_winetest info on x64.
> [NTOS] Implement support for opting out of NX policy

- modules/rosapps/applications/screensavers/mazescr/maze.c
> [MAZESCR] Avoid (DLGPROC) cast

- win32ss/printing/base/winspool/printers.c
Otherwise the size isn't set up correctly, leading to a crash.
- GCCLin_x86 on Test KVM: https://reactos.org/testman/compare.php?ids=89873,89887,89893
- MSVC_x64 on Test KVM_x64: https://reactos.org/testman/compare.php?ids=89871,89874,89892
> [WINSPOOL] Properly copy the DEVMODE

- drivers/network/tcpip/include/tags.h
- drivers/network/tcpip/tcpip/main.c
- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/NtAccessCheck.c
- modules/rostests/apitests/ntdll/testlist.c
- ntoskrnl/se/accesschk.c
- ntoskrnl/se/token.c
Fix some denied access request instances where the OS would request access to a resource object but of which access was denied.
[CORE-18620](https://jira.reactos.org/browse/CORE-18620)
[CORE-18576](https://jira.reactos.org/browse/CORE-18576)
[CORE-18250](https://jira.reactos.org/browse/CORE-18250)
> Fix some denied access requests

- dll/win32/netid/netid.c
Addendum to commit 8c4b0c914.
Base ourselves on pSetupIsUserAdmin() and other similar functions in our codebase. Note that what we are actually interested here, is whether the current thread runs with Administrator privileges.
See also:
https://www.codeproject.com/Questions/544981/IsplusProcessplusRunningplusasplusAdministrator
https://www.developpez.net/forums/d1926658/environnements-developpement/delphi/api-com-sdks/detecter-compte-admin-difference-w7-w10/
> [NETID] Simplify IsUserAdmin() helper implementation.

- dll/cpl/desk/desk.c
This avoids having desk.cpl depends on a private function that may change or disappear, and increase the probability of being able to use that CPL across different Windows versions.
(Note: this pSetupMultiByteToUnicode was one of those whose name changed between Windows 2000 and XP+)
> [DESK] Use standard MultiByteToWideChar instead of calling the private pSetupMultiByteToUnicode function.

- dll/win32/t2embed/t2embed.spec
Remove stdcall annotated exports from x64
> [T2EMBED] Fix spec file for x64

- dll/win32/kernel32/CMakeLists.txt
- dll/win32/kernel32/kernel32.spec
- dll/win32/kernel32/kernel32_vista/CMakeLists.txt
Export more Vista functions
- GCCLin_x86 on Test KVM: https://reactos.org/testman/compare.php?ids=90195,90203,90205,90207
- MSVC_x64 on Test KVM_x64: https://reactos.org/testman/compare.php?ids=90198,90206,90208,90209
> [KERNEL32] Export more Vista functions

- drivers/ksfilter/ks/filterfactory.c
- drivers/ksfilter/ks/misc.c
- drivers/wdm/audio/hdaudbus/fdo.cpp
- drivers/wdm/audio/hdaudbus/hdaudbus.cpp
- drivers/wdm/audio/legacy/wdmaud/sup.c
Simpler and more secure code.
- Use ExAllocatePoolZero() and ExFreePoolWithTag()
- Promote/Fix 2 DPRINT()
> [HDAUDBUS][KS][WDMAUD] Use ExAllocatePoolZero() and ExFreePoolWithTag()

- dll/cpl/hotplug/hotplug.c
- Clicking at "Properties" button or right-click menu now opens properties dialog of the selected device
> [HOTPLUG] Add device properties dialog support

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- sdk/include/psdk/shlobj.h
- sdk/include/reactos/undocshell.h
- Add `SHOpenPropSheetA` and `SHOpenPropSheetW` prototypes to `<shlobj.h>`.
- Implement `SHOpenPropSheetA` function.
> [SHELL32][SDK] Implement SHOpenPropSheetA

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- sdk/include/reactos/undocshell.h
- Add `Activate_RunDLL` function implementation.
- Add `Activate_RunDLL` prototype to `<undocshell.h>`.
> [SHELL32][SDK] Implement Activate_RunDLL

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- dll/win32/shell32/wine/shellord.c
- sdk/include/psdk/shlobj.h
- Implement `SHStartNetConnectionDialogA`.
- Add `SHStartNetConnectionDialog` prototype to `<shlobj.h>`.
> [SHELL32][SDK] Implement SHStartNetConnectionDialogA

- dll/win32/shell32/shell32.spec
- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- sdk/include/reactos/undocshell.h
- Implement `CopyStreamUI` function.
- Add `CopyStreamUI` prototype to `<undocshell.h>`.
> [SHELL32][SDK] Implement CopyStreamUI

- dll/directx/dsound_new/precomp.h
- drivers/wdm/audio/hdaudbus/hdaudbus.h
Code cleanup.
dsound_new: Addendum to 5974fe1 (r45584).
hdaudbus: Addendum to cf7fc81 (r68311).
Follow-up of #5818.
- Replace meaningless YDEBUG
- and move debug.h after all includes.
> [DSOUND_NEW][HDAUDBUS] Replace meaningless YDEBUG

- win32ss/user/ntuser/menu.c
Add a check for the system menu opened from the app icon.
JIRA issue: [CORE-19258](https://jira.reactos.org/browse/CORE-19258)
> [NTUSER] Fix system menu mouse handing

- base/applications/mspaint/canvas.cpp
- base/applications/mspaint/toolsmodel.cpp
- base/applications/mspaint/toolsmodel.h
Localize what should be localized.
- Move some mouse moving code to `toolsModel`.
> [MSPAINT] Refactor mouse moving code on canvas

- dll/cpl/hotplug/enum.c
- dll/cpl/hotplug/hotplug.c
- dll/cpl/hotplug/hotplug.rc
- Update files header and copyright information
- Minor code formatting
> [HOTPLUG] Trivial fixes

- dll/win32/shlwapi/CMakeLists.txt
- dll/win32/shlwapi/shlwapi.spec
- dll/win32/shlwapi/utils.cpp
- sdk/include/reactos/shlwapi_undoc.h
- Add `dll/win32/shlwapi/utils.cpp`.
- Implement `IContextMenu_Invoke` function.
- Add it to `<shlwapi_undoc.h>`.
> [SHLWAPI][SDK] Implement IContextMenu_Invoke

- sdk/include/asm/trapamd64.inc
> [NTOS:KE/x64] Remove GCC vs ML hack

- base/applications/games/solitaire/lang/ro-RO.rc
> [SOLITAIRE] Update Romanian (ro-RO) translation

- base/applications/mmc/lang/ro-RO.rc
> [MMC] Update Romanian (ro-RO) translation

- base/applications/notepad/lang/ro-RO.rc
> [NOTEPAD] Update Romanian (ro-RO) translation

- dll/cpl/desk/lang/ro-RO.rc
> [DESK] Update Romanian (ro-RO) translation

- base/applications/rapps/appview.cpp
Based on KRosUser's `rapps_v2.patch`.
JIRA issue: [CORE-19317](https://jira.reactos.org/browse/CORE-19317)
`ExtractIconW` can return `(HICON)1`. We check this invalid value.
> [RAPPS] Fix item icons

- dll/cpl/inetcpl/lang/ro-RO.rc
> [INETCPL] Update Romanian (ro-RO) translation

- sdk/include/reactos/mc/net_msg.mc
> [NET][MC] Update Romanian (ro-RO) translation for message table

- sdk/include/reactos/mc/net_msg.mc
> [NETMSG][MC] Add Romanian (ro-RO) translation to message table

- sdk/include/reactos/mc/neteventmsg.mc
> [NETEVENT][MC] Add Romanian (ro-RO) translation to message table

- dll/win32/rasdlg/lang/ro-RO.rc
> [RASDLG] Update Romanian (ro-RO) translation

- dll/cpl/hdwwiz/lang/ro-RO.rc
> [HDWWIZ] Update Romanian (ro-RO) translation

- base/applications/dxdiag/lang/ro-RO.rc
> [DXDIAG] Update Romanian (ro-RO) translation

- dll/cpl/console/lang/ro-RO.rc
> [CONSOLE] Update Romanian (ro-RO) translation

- base/applications/mspaint/lang/ro-RO.rc
> [MSPAINT] Update Romanian (ro-RO) translation

- base/applications/clipbrd/lang/ro-RO.rc
> [CLIPBRD] Update Romanian (ro-RO) translation

- base/applications/wordpad/lang/ro-RO.rc
> [WORDPAD] Update Romanian (ro-RO) translation

- base/applications/sndrec32/lang/ro-RO.rc
> [SNDREC32] Update Romanian (ro-RO) translation

- win32ss/printing/monitors/localmon/ui/lang/ui_Ro.rc
> [LOCALMON] Update Romanian (ro-RO) translation

- dll/win32/ieframe/lang/ro-RO.rc
> [IEFRAME] Update Romanian (ro-RO) translation

- base/applications/cmdutils/label/lang/ro-RO.rc
> [LABEL] Update Romanian (ro-RO) translation

- win32ss/drivers/miniport/vmx_svga/vmx_svga.c
Improve code and debug output a bit.
Addendum to 486e587 (r45778).
- Demote 3 DPRINT1() and define NDEBUG
> [VMX_SVGA] Demote 3 DPRINT1() and define NDEBUG

- ntoskrnl/include/internal/ex.h
- subsystems/csr/csrsrv/srv.h
- win32ss/pch.h
Self-documentation, safety.
- Add parentheses around parameters.
- Add casts on return value.
> [NTOS:EX][CSRSRV][WIN32K] Make a few #define more explicit/strict

- base/applications/cmdutils/more/lang/ro-RO.rc
> [MORE] Update Romanian (ro-RO) translation

- base/applications/mscutils/servman/lang/ro-RO.rc
> [SERVMAN] Update Romanian (ro-RO) translation

- dll/win32/shell32/lang/ro-RO.rc
> [SHELL32] Update Romanian (ro-RO) translation

- dll/win32/syssetup/lang/ro-RO.rc
> [SYSSETUP] Update Romanian (ro-RO) translation

- base/applications/magnify/lang/ro-RO.rc
> [MAGNIFY] Update Romanian (ro-RO) translation

- base/applications/fltmc/lang/ro-RO.rc
> [FLTMC] Update Romanian (ro-RO) translation

- base/applications/regedit/lang/ro-RO.rc
> [REGEDIT] Update Romanian (ro-RO) translation

- base/applications/msconfig/lang/ro-RO.rc
> [MSCONFIG] Update Romanian (ro-RO) translation

- base/applications/mscutils/eventvwr/lang/ro-RO.rc
> [EVENTVWR] Update Romanian (ro-RO) translation

- base/applications/msconfig_new/lang/ro-RO.rc
> [MSCONFIG_NEW] Update Romanian (ro-RO) translation

- base/applications/cmdutils/find/lang/ro-RO.rc
Attendum to PR https://github.com/reactos/reactos/pull/5908 and I fixed a typo.
> [FIND] Update Romanian (ro-RO) translation

- win32ss/drivers/displays/vga/main/enable.c
- win32ss/gdi/ntgdi/dibobj.c
- win32ss/gdi/ntgdi/region.c
- win32ss/reactx/ntddraw/d3d.c
- win32ss/reactx/ntddraw/d3dkmt.c
- win32ss/reactx/ntddraw/dd.c
- win32ss/reactx/ntddraw/ddraw.c
- win32ss/reactx/ntddraw/ddsurf.c
- win32ss/reactx/ntddraw/dvp.c
- win32ss/reactx/ntddraw/dxeng.c
- win32ss/reactx/ntddraw/eng.c
- win32ss/reactx/ntddraw/mocomp.c
Improve debug log.
- and demote some DPRINT1().
> [NTDDRAW][NTGDI][VGADDI] Add missing \n to DPRINT() calls

- base/applications/utilman/umandlg/process.c
- base/setup/lib/install.c
- base/setup/lib/setuplib.c
- base/setup/lib/utils/partlist.c
- base/setup/usetup/usetup.c
- base/system/services/database.c
Improve debug log.
- Add promote 1 DPRINT().
> [SERVICES][SETUPLIB][UMANDLG][USETUP] Add missing \n to DPRINT() calls

- dll/cpl/inetcpl/security.c
Based on KRosUser's `inetsec.patch`.
JIRA issue: [CORE-19301](https://jira.reactos.org/browse/CORE-19301)
- Don't delete the image list because the image list will be automatically deleted by the list view.
> [INETCPL] Let image list be automatically deleted

- dll/win32/newdev/lang/ro-RO.rc
> [NEWDEV] Update Romanian (ro-RO) translation

- dll/win32/mpr/lang/mpr_Ro.rc
> [MPR] Update Romanian (ro-RO) translation

- modules/rosapps/applications/devutils/vgafontedit/lang/ro-RO.rc
> [VGAFONTEDIT] Update Romanian (ro-RO) translation

- dll/win32/wininet/lang/wininet_Ro.rc
> [WININET] Update Romanian (ro-RO) translation

- dll/win32/advapi32/reg/reg.c
Check for unaligned buffer before calling NtOpenKey instead of checking the result for STATUS_DATATYPE_MISALIGNMENT.
Test x86: https://reactos.org/testman/compare.php?ids=91100,91107,91111,91113
> [ADVAPI32] Improve handling of unaligned key name in RegOpenKeyExW

- dll/win32/shdoclc/lang/Ro.rc
> [SHDOCLC] Update Romanian (ro-RO) translation

- dll/win32/shimgvw/lang/ro-RO.rc
> [SHIMGVW] Update Romanian (ro-RO) translation

- dll/win32/msacm32/lang/msacm_Ro.rc
> [MSACM32] Update Romanian (ro-RO) translation

- dll/win32/comdlg32/lang/cdlg_Ro.rc
> [COMDLG32] Update Romanian (ro-RO) translation

- dll/cpl/mmsys/lang/ro-RO.rc
> [MMSYS] Update Romanian (ro-RO) translation

- hal/halx86/acpi/halacpi.c
- hal/halx86/generic/x86bios.c
- hal/halx86/mp/ioapic.c
Debug log improvement.
- And promote some DPRINT() to DPRINT1().
> [HALX86] Add missing \n to DPRINT() calls

- sdk/tools/widl/CMakeLists.txt
Code cleanup.
Addendum to 8184186 (r55855).
- Remove an obsolete comment
> [WIDL] CMakeLists.txt: Remove an obsolete comment

- dll/win32/netcfgx/tcpipconf_notify.c
Based on KRosUser's `netaltconf_fix.patch`.
JIRA issue: [CORE-19336](https://jira.reactos.org/browse/CORE-19336)
> [NETCFGX] Fix TCP/IP alternate radiobutton behaviour

- dll/shellext/zipfldr/CEnumZipContents.cpp
Fix off-by-one count error during enumeration.
JIRA issue: [CORE-19342](https://jira.reactos.org/browse/CORE-19342)
> [ZIPFLDR] Fix off-by-one count error during enumeration

- base/applications/network/ping/lang/ro-RO.rc
> [PING] Update Romanian (ro-RO) translation

- base/applications/taskmgr/affinity.c
> [TASKMGR] Fix 64-bit bugs

- dll/win32/setupapi/setupapi.rc
> [SETUPAPI] Add version info

- dll/win32/ws2help/CMakeLists.txt
> [WS2HELP] Add ws2help.rc to CMakeLists

- win32ss/user/user32/windows/window.c
Based on I_Kill_Bugs' `IsWinodw.patch`.
JIRA issue: [CORE-11722](https://jira.reactos.org/browse/CORE-11722), [CORE-16432](https://jira.reactos.org/browse/CORE-16432)
> [USER32] Fix IsWindow by not using WNDS2_INDESTROY

- dll/win32/msgina/lang/ro-RO.rc
> [MSGINA] Update Romanian (ro-RO) translation

- ntoskrnl/ke/i386/mproc.c
Don't hardcode pool tag and TSS flag values.
> [NTOS:KE] Don't hardcode pool tag and TSS flag values.

- drivers/bus/acpi/CMakeLists.txt
> [ACPI] Add acpi.rc to CMakeLists

- hal/halx86/apic/apicsmp.c
- hal/halx86/generic/halinit.c
- hal/halx86/generic/up.c
- hal/halx86/include/smp.h
- hal/halx86/smp/ipi.c
- ntoskrnl/include/internal/ke.h
- sdk/include/ndk/kefuncs.h
Add and use Affinity helper functions. Amendment to #6048 
- [NDK] Add Affinity helper inline functions
- [HALX86] Use InterlockedBitTestAndSetAffinity instead of InterlockedBitTestAndSet
- [HALX86] Some improvements / bugfixes for IPI support functions
> [NDK][HAL] Add and use Affinity helper functions

- base/system/diskpart/lang/ro-RO.rc
> [DISKPART] Update Romanian (ro-RO) translation

- base/applications/cmdutils/help/lang/ro-RO.rc
> [HELP] Update Romanian (ro-RO) translation

- dll/cpl/openglcfg/lang/ro-RO.rc
> [OPENGLCFG] Update Romanian (ro-RO) translation

- base/shell/cmd/lang/ro-RO.rc
> [CMD] Update Romanian (ro-RO) translation

- dll/shellext/netshell/lang/ro-RO.rc
> [NETSHELL] Update Romanian (ro-RO) translation

- modules/rosapps/applications/sysutils/ctm/lang/ro-RO.rc
> [CTM] Update Romanian (ro-RO) translation

- base/applications/cmdutils/at/lang/ro-RO.rc
> [AT] Update Romanian (ro-RO) translation

- base/applications/rapps/lang/ro-RO.rc
> [RAPPS] Improve Romanian (ro-RO) translation

- dll/win32/lsasrv/lang/ro-RO.rc
> [LSASRV] Update Romanian (ro-RO) translation

- sdk/include/reactos/mc/neteventmsg.mc
> [NETEVENT][MC] Update Romanian (ro-RO) translation

- dll/cpl/main/lang/ro-RO.rc
> [MAIN] Update Romanian (ro-RO) translation

- dll/win32/iccvid/rsrc.rc
- dll/win32/msrle32/rsrc.rc
- dll/win32/msvidc32/msvideo1.c
- dll/win32/msvidc32/rsrc.rc
Based on KRosUser's `vfw.patch`.
JIRA issue: [CORE-15382](https://jira.reactos.org/browse/CORE-15382)
> [ICCVID][MSRLE32][MSVIDC32] Add VfW codecs version info

- dll/win32/shimgvw/shimgvw.c
Improve human readability. Reduce code amount.
> [SHIMGVW] Some minor refactoring

- dll/win32/shimgvw/CMakeLists.txt
- dll/win32/shimgvw/anime.c
- dll/win32/shimgvw/shimgvw.c
- dll/win32/shimgvw/shimgvw.h
Improve code flexibility.
- Add `anime.c` and move animation code to `anime.c`.
> [SHIMGVW] Split animation code to anime.c

- win32ss/user/user32/windows/dialog.c
Improve WineSync.
Addendum to 61fb8a2 (r19831).
- Remove redundant code.
> [USER32] GetNextDlgGroupItem(): Remove WineSync copy-pasta

- dll/win32/shimgvw/shimgvw.c
- dll/win32/shimgvw/shimgvw.h
JIRA issue: [CORE-19220](https://jira.reactos.org/browse/CORE-19220)
- Modify `s_ZoomSteps`.
- Add `WC_ZOOM` window class and use it for zooming.
- Add `ZoomWnd_OnDraw` function and use it in `ZoomWnd_OnPaint`.
- Use memory bitmap to reduce flickering.
- Make rendering pixel-perfect.
https://github.com/reactos/reactos/assets/2107452/cdd719a9-6051-4889-b9e7-a1c290abba75
> [SHIMGVW] Fix and improve zooming

- dll/win32/shimgvw/shimgvw.c
- dll/win32/shimgvw/shimgvw.h
Improve usability on zooming the image.
- Add `m_xScrollOffset` and `m_yScrollOffset` to `PREVIEW_DATA` structure.
- Add `ZoomWnd_UpdateScroll` helper function.
- Handle `WM_HSCROLL` and `WM_VSCROLL` messages.
- Enable mouse wheel scrolling.
https://github.com/reactos/reactos/assets/2107452/69778311-448e-4aba-b729-66d713a67563
> [SHIMGVW] Enable scrolling

- subsystems/csr/csrlib/connect.c
- subsystems/mvdm/ntvdm/bios/bios32/vbe.c
- subsystems/mvdm/ntvdm/bios/rom.c
- subsystems/mvdm/ntvdm/vddsup.c
- subsystems/win/basesrv/vdm.c
Improve debug log.
- and promote 1 DPRINT().
> [BASESRV][CSRLIB][NTVDM] Add missing \n to DPRINT() calls

- modules/rostests/tests/DxHalTest/main.c
> [DXHALTEST] Fix some typos

- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/ntdll/RtlGetProcessHeaps.c
- modules/rostests/apitests/ntdll/testlist.c
- sdk/lib/rtl/heap.c
- sdk/lib/rtl/heap.h
- sdk/lib/rtl/heapuser.c
All relevant windows version pass the test:
https://testbot.winehq.org/JobDetails.pl?Key=140945
```
VM                   Status 
wxppro               success
w2003std             success
wvista               success
w7u_2qxl             success
w7u_adm              success
w7u_el               success
w7pro64              success
w8                   success
w8adm                success
w864                 success
w1064v1507           success
w1064v1809           success
w1064_2qxl           success
w1064_adm            success
w1064_tsign          success
w10pro64             success
w10pro64_en_AE_u8    success
w10pro64_ar          success
w10pro64_ja          success
w10pro64_zh_CN       success
w11pro64             success
w11pro64_amd         success
debian11             failed …
```
> [RTL] Implement RtlGetProcessHeaps

- dll/ime/msctfime/msctfime.cpp
- dll/ime/msctfime/msctfime.h
- Add `IsMsImeMessage` helper funciton.
- Implement `CtfImeDispatchDefImeMessage` function.
> [MSCTFIME] Implement CtfImeDispatchDefImeMessage

- dll/ime/msctfime/msctfime.cpp
- dll/ime/msctfime/msctfime.h
- Add code to `CicInputContext` and `CicBridge` classes.
- Implement `ImeConfigure` function by using them.
> [MSCTFIME] Implement ImeConfigure

- dll/ime/msctfime/CMakeLists.txt
- dll/ime/msctfime/msctfime.cpp
- Add link to `msctf.dll`.
- Implement `CActiveLanguageProfileNotifySink` class.
- Strengthen `CicProfile` class.
> [MSCTFIME] Implement CActiveLanguageProfileNotifySink

- dll/ime/msctfime/msctfime.cpp
- Define `LIBTHREAD` structure.
- Add `InitDisplayAttrbuteLib` and `UninitDisplayAttrbuteLib` helper functions.
- Define `CThreadMgrEventSink` class.
- Strengthen `CicBridge` class.
> [MSCTFIME] Implemenet CicBridge::InitIMMX/UnInitIMMX

- dll/ime/msctfime/msctfime.cpp
- dll/ime/msctfime/msctfime.h
- sdk/include/reactos/cicero/cicarray.h
- sdk/include/reactos/cicero/cicbase.h
- Modify `<cicero/cicbase.h>` and `<cicero/cicarray.h>`.
- Add `CCompartmentEventSink` class.
> [MSCTFIME][SDK] Implement CCompartmentEventSink

- win32ss/user/ntuser/caret.c
- win32ss/user/ntuser/cursoricon.c
- win32ss/user/ntuser/desktop.c
- win32ss/user/ntuser/focus.c
- win32ss/user/ntuser/hook.c
- win32ss/user/ntuser/message.c
- win32ss/user/ntuser/misc.c
- win32ss/user/ntuser/ntuser.h
- win32ss/user/ntuser/object.c
- win32ss/user/ntuser/painting.c
- win32ss/user/ntuser/scrollbar.c
- win32ss/user/ntuser/scrollex.c
- win32ss/user/ntuser/windc.c
- win32ss/user/ntuser/winpos.c
Remove the remaining uses and the macro itself.
Edit: reactosfanboy. Part 3 of 3, Addendum to  (#6166) and (#6185)
> [NTUSER] Remove RETURN() macro

- dll/ime/msctfime/msctfime.cpp
- sdk/include/reactos/cicero/cicarray.h
Refactoring...
- Add template type parameter.
- Use `size_t` for indexing instead of `INT`.
- Protect `CicArray` members.
- Adapt `msctfime` to new `CicArray`.
> [MSCTFIME][SDK] Improve CicArray

- dll/win32/browseui/internettoolbar.cpp
Based on KRosUser's `go.patch`.
JIRA issue: [CORE-19145](https://jira.reactos.org/browse/CORE-19145)
> [BROWSEUI] Load settings on CInternetToolbar::OnContextMenu

- dll/win32/setupapi/cfgmgr.c
Code cleanup.
Addendum to 9277f53 (0.4.15-dev-7297).
- Remove duplicated code
> [SETUPAPI] CMP_RegisterNotification(): Remove duplicated code

- dll/cpl/desk/advappdlg.c
- dll/cpl/desk/appearance.h
Slightly less annoying to edit a theme if you can define custom colors
> [DESK] Remember color picker custom colors between invocations

- dll/win32/msctf/CMakeLists.txt
- dll/win32/msctf/msctf.spec
- dll/win32/msctf/utils.cpp
- sdk/include/reactos/cicero/cicbase.h
- sdk/include/reactos/cicero/cicreg.h
Implementing Language Bar...
- Add `dll/win32/msctf/utils.cpp`.
- Implement `TF_RegisterLangBarAddIn` and `TF_UnregisterLangBarAddIn` functions.
- Strengthen `<cicero/cicreg.h>`.
- Modify `msctf.spec`.
> [MSCTF][SDK] Implement TF_RegisterLangBarAddIn etc.

- base/applications/ctfmon/CRegWatcher.cpp
JIRA issue: [CORE-19362](https://jira.reactos.org/browse/CORE-19362)
- Dynamic load `advapi32!RegNotifyChangeKeyValue` function.
- Output log if `RegNotifyChangeKeyValue` failed.
> [CTFMON] Unlink RegNotifyChangeKeyValue

- dll/win32/msctf/msctf.spec
- dll/win32/msctf/utils.cpp
- sdk/include/reactos/cicero/cicfmap.h
Supporting TIPs and Language Bar...
- Add many global variables.
- Add `GetUserSIDString`, `InitUserSidString`, `InitUniqueString`, and `GetDesktopUniqueName` helper functions.
- Implement `TF_IsCtfmonRunning` function.
- Fix `CicFileMapping` class in `<cicero/cicfmap.h>`.
- Modify `msctf.spec`.
- Half-implement `ProcessAttach` and `ProcessDetach` functions.
> [MSCTF][SDK] Implement TF_IsCtfmonRunning

- dll/win32/msctf/utils.cpp
- sdk/include/reactos/cicero/cicreg.h
Supporing TIPs and Language Bar...
- Implement `InitLangChangeHotKey` function.
- Add some global variables about hot-keys.
- Fix `CicRegKey` in `<cicero/cicreg.h>`.
> [MSCTF][SDK] Implement InitLangChangeHotKey

- dll/win32/msctf/utils.cpp
Implementing TIPs and Language Bar...
- Add `InitCUASFlag` function.
- Use it in `ProcessAttach` function.
> [MSCTF] Implement InitCUASFlag

- dll/ime/msctfime/msctfime.cpp
- sdk/include/reactos/cicero/cictf.h
- Implement `CicBridge::ActivateIMMX` and `CicBridge::DeactivateIMMX` functions.
> [MSCTFIME][SDK] Implement CicBridge::ActivateIMMX etc.

- base/applications/winhlp32/winhelp.c
Based on KRosUser's `winhlp.patch`. This PR will supersede #5401.
JIRA issue: [CORE-18679](https://jira.reactos.org/browse/CORE-18679)
- Just copy help file title.
> [WINHLP32] Don't show file path in title

- dll/ime/msctfime/msctfime.cpp
- sdk/include/reactos/cicero/cicimc.h
Improve code quality.
- Add some SAL annotations.
- Add readable comments more.
- Rename some member variables.
> [MSCTFIME][SDK] Improve human readability

- dll/ime/msctfime/msctfime.cpp
Supporting Text Input Processors (TIPs)...
- Strengthen `CicInputContext` class.
> [MSCTFIME] Strengthen CicInputContext

- dll/ime/msctfime/msctfime.cpp
> [MSCTFIME] Implement CTextEventSink::_Advise and _Unadvise

- dll/ime/msctfime/msctfime.cpp
- Add `UIComposition` and `UI` classes.
- Add `CIMEUIWindowHandler` structure.
- Half-implement `UIWndProc` by using them.
> [MSCTFIME] Half-implement UIWndProc

- win32ss/user/ntuser/accelerator.c
- win32ss/user/ntuser/caret.c
- win32ss/user/ntuser/clipboard.c
- win32ss/user/ntuser/cursoricon.c
- win32ss/user/ntuser/defwnd.c
- win32ss/user/ntuser/desktop.c
- win32ss/user/ntuser/focus.c
- win32ss/user/ntuser/hook.c
- win32ss/user/ntuser/kbdlayout.c
- win32ss/user/ntuser/menu.c
- win32ss/user/ntuser/message.c
- win32ss/user/ntuser/msgqueue.c
- win32ss/user/ntuser/painting.c
- win32ss/user/ntuser/scrollbar.c
- win32ss/user/ntuser/shutdown.c
- win32ss/user/ntuser/simplecall.c
- win32ss/user/ntuser/timer.c
- win32ss/user/ntuser/windc.c
- win32ss/user/ntuser/window.c
- win32ss/user/ntuser/winpos.c
Use `UserHMGetHandle` macro everywhere instead of `obj->head.h` for consistency.
> [NTUSER] Use UserHMGetHandle macro

- sdk/include/reactos/cicero/cicarray.h
- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFObjectArray` class.
- Add `CUIFObject` class.
- Strenthen `CicArray` and `CUIFTheme` classes.
> [SDK] Add CUIFObject and CUIFObjectArray

- dll/ime/msctfime/msctfime.cpp
Improve readability.
- Reduce the lines of comments by using C++ comments.
> [MSCTFIME] Reduce comment lines

- dll/cpl/desk/settings.c
Based on KRosUser's `desk.patch`.
JIRA issue: [CORE-18187](https://jira.reactos.org/browse/CORE-18187), [CORE-16878](https://jira.reactos.org/browse/CORE-16878)
- Add `FindBestElement` helper function.
- Use `FindBestElement` to find the best display settings.
> [DESK] Find best display settings

- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFBitmapDC` class.
- Add `cicInitUIFUtil` and `cicDoneUIFUtil` functions.
- Add `cicSetLayout`, `cicMirrorBitmap`, `cicCreateDitherBrush`, `cicCreateDisabledBitmap`, and `cicCreateShadowMaskBmp` utility functions.
> [SDK] cicuif.h: Add CUIFBitmapDC

- dll/cpl/intl/lang/ro-RO.rc
Attendum to PRs #5908 and #6239
> [INTL] Update Romanian (ro-RO) translation

- dll/cpl/access/lang/ro-RO.rc
Attendum to PRs https://github.com/reactos/reactos/pull/5908 and https://github.com/reactos/reactos/pull/6239
> [ACCESS] Update Romanian (ro-RO) translation

- dll/win32/msports/lang/ro-RO.rc
> [MSPORTS] Update Romanian (ro-RO) translation

- dll/shellext/deskmon/lang/ro-RO.rc
> [DESKMON] Update Romanian (ro-RO) translation

- dll/win32/msi/lang/msi_Ro.rc
> [MSI] Update Romanian (ro-RO) translation

- base/applications/shutdown/lang/ro-RO.rc
> [SHUTDOWN] Update Romanian (ro-RO) translation

- dll/cpl/appwiz/lang/ro-RO.rc
> [APPWIZ] Improve Romanian (ro-RO) translation

- sdk/include/reactos/cicero/cicuif.h
- Strengthen `CUIFObject`.
- Add `CUIFWindow`.
> [SDK] cicuif.h: Add CUIFWindow

- sdk/include/reactos/cicero/cicuif.h
- Half-implement `CUIFShadow` class.
> [SDK] cicuif.h: Add CUIFShadow

- sdk/include/reactos/cicero/cicuif.h
- Half-implement `CUIFToolTip`.
- Strengthen some classes.
> [SDK] cicuif.h: Add CUIFToolTip

- boot/bootdata/hivesys.inf
Attendum to PRs #5908 and #6239
> [INF] Update Romanian (ro-RO) translation

- dll/win32/winmm/lang/winmm_Ro.rc
> [WINMM] Update Romanian (ro-RO) translation

- dll/win32/modemui/lang/ro-RO.rc
> [MODEMUI] Update Romanian (ro-RO) translation

- base/applications/network/ipconfig/lang/ro-RO.rc
> [IPCONFIG] Update Romanian (ro-RO) translation

- dll/win32/oledlg/lang/oledlg_Ro.rc
> [OLEDLG] Update Romanian (ro-RO) translation

- dll/win32/cryptui/lang/cryptui_Ro.rc
> [CRYPTUI] Update Romanian (ro-RO) translation

- base/system/format/lang/ro-RO.rc
Attendum to PRs https://github.com/reactos/reactos/pull/5908 and #6239
> [FORMAT] Update Romanian (ro-RO) translation

- base/applications/cmdutils/taskkill/lang/ro-RO.rc
> [TASKKILL] Update Romanian (ro-RO) translation

- dll/win32/wldap32/lang/wldap32_Ro.rc
> [WLDAP32] Improve Romanian (ro-RO) translation

- dll/shellext/zipfldr/lang/ro-RO.rc
> [ZIPFLDR] Update Romanian (ro-RO) translation

- sdk/include/reactos/cicero/cicuif.h
Improve readability and reduce code.
- Delete `cicSetLayout` function and use `gdi32!SetLayout` function directly.
- Don't use `SetRect` and `SetRectEmpty` functions.
- `s/CUIFButton::m_dwUnknown10/CUIFButton::m_bPressed/`.
- Reduce lines.
> [SDK] cicuif.h: Refactoring

- win32ss/user/ntuser/class.c
Based on `I_Kill_Bugs`' `class_error.patch`.
JIRA issue: [CORE-13422](https://jira.reactos.org/browse/CORE-13422), [CORE-7531](https://jira.reactos.org/browse/CORE-7531), [CORE-18639](https://jira.reactos.org/browse/CORE-18639)
> [NTUSER] Check class name on IntGetAtomFromStringOrAtom

- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFSchemeDef` class.
- Improve `CUIFWindow` class.
> [SDK] cicuif.h: Add CUIFSchemeDef

- sdk/include/reactos/cicero/cicuif.h
- Fix some mistakes of `CUIFButton::OnMouseIn` and `CUIFButton::OnMouseOut`.
- Fix some mistakes of `CUIFObject` and `CUIFWindow`.
> [SDK] cicuif.h: Refactoring Part 2

- sdk/include/reactos/cicero/cicuif.h
- Improve `CUIFScheme` class.
- Add `CUIFButton2` class.
> [SDK] cicuif.h: Add CUIFButton2

- boot/bootdata/hivecls.inf
- boot/bootdata/hivesys.inf
[BOOTDATA] Add Portuguese (pt-PT) translation to hivecls.inf
> [BOOTDATA] Add Portuguese (pt-PT) translation.

- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFGripper` class.
- Add `CUIFWindow::operator HWND`.
> [SDK] cicuif.h: Add CUIFGripper

- sdk/include/reactos/cicero/cicuif.h
Improve human readability.
- Define some flags of `m_style`.
- Define some flags of `dwDrawFlags`.
- Reduce some magic numbers.
> [SDK] cicuif.h: Reduce magic numbers

- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFToolbarMenuButton` class.
- Add `CUIFToolbarButtonElement` class.
> [SDK] cicuif.h: Add CUIFToolbarMenuButton

- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFToolbarButton` class.
> [SDK] cicuif.h: Add CUIFToolbarButton

- modules/rostests/apitests/crt/crtdata.c
Fix Vista+ tests in msvcrt_crt_apitest:crtdata.
> [CRT_APITEST] Fix some Vista+ tests

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFSchemeDef::DrawCtrlBitmap` method.
> [SDK] cicuif.h: Fix CUIFSchemeDef::DrawCtrlBitmap

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFSchemeDef::DrawCtrlEdge` method.
> [SDK] cicuif.h: Fix CUIFSchemeDef::DrawCtrlEdge

- base/system/winlogon/lang/ro-RO.rc
> [WINLOGON] Update Romanian (ro-RO) translation

- ntoskrnl/include/internal/ke.h
- ntoskrnl/ke/amd64/krnlinit.c
- ntoskrnl/ke/thrdobj.c
- ntoskrnl/ke/thrdschd.c
- Fix some wrong types, which should be KAFFINITY
- Fix wrong 64 bit affinity value
> [NTOS:KE] KAFFINITY fixes

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFWndFrame` class.
> [SDK] cicuif.h: Add CUIFWndFrame

- base/shell/explorer/lang/pt-PT.rc
- dll/cpl/desk/lang/pt-PT.rc
- dll/cpl/input/lang/pt-PT.rc
- dll/win32/shell32/lang/pt-PT.rc
[SHELL32] Improve portuguese (pt-PT) translation
[DESK] Update pt-PT translation
[EXPLORER] Update portuguese (pt-PT) translation
[INPUT] Improve portuguese (pt-PT) translation
[INPUT] Update portuguese (pt-PT) translation
> [TRANSLATION] Improve Portuguese (pt-PT) translation

- sdk/include/reactos/cicero/cicarray.h
- sdk/include/reactos/cicero/cicuif.h
- Half-implement `CUIFMenu` and `CUIFMenuItem`.
- Reduce lines.
> [SDK] cicuif.h: Add CUIFMenu and CUIFMenuItem

- sdk/include/reactos/cicero/cicuif.h
Implementing Language Bar...
- Implement `CUIFBalloonWindow::CreateRegion` method.
> [SDK] cicuif.h: Fix CUIFBalloonWindow::CreateRegion

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenu::InitShow` method.
> [SDK] cicuif.h: Fix CUIFMenu::InitShow

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenuItem::DrawBitmapProc` method.
> [SDK] cicuif.h: Fix CUIFMenuItem::DrawBitmapProc

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenuItem::Init` method.
> [SDK] cicuif.h: Fix CUIFMenuItem::Init

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenu::SetMenuFont` method.
> [SDK] cicuif.h: Fix CUIFMenu::SetMenuFont

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenuItem::InitMenuExtent` method.
> [SDK] cicuif.h: Fix CUIFMenuItem::InitMenuExtent

- sdk/include/reactos/cicero/cicarray.h
- sdk/include/reactos/cicero/cicuif.h
- Add `CUIFMenuItemSeparator` class.
- Implement `CUIFMenu::InsertSeparator` method.
> [SDK] cicuif.h: Add CUIFMenuItemSeparator

- dll/win32/msutb/msutb.cpp
- Implement `CCicLibMenu` and `CCicLibMenuItem` classes.
> [MSUTB] Add CCicLibMenu and CCicLibMenuItem

- dll/win32/msutb/msutb.cpp
- Half-implement `CTipbarAccItem` class.
> [MSUTB] Add CTipbarAccItem

- dll/win32/msutb/lang/en-US.rc
- dll/win32/msutb/msutb.cpp
- dll/win32/msutb/precomp.h
- dll/win32/msutb/resource.h
- sdk/include/reactos/cicero/cicuif.h
- Implement `CUTBMenuWnd` and `CUTBMenuItem` classes.
- Add `IDS_MENUWND` and `IDS_LEFTCLICK` resource strings.
> [MSUTB][SDK] Add CUTBMenuWnd and CUTBMenuItem

- dll/win32/msutb/lang/en-US.rc
- dll/win32/msutb/msutb.cpp
- dll/win32/msutb/precomp.h
- dll/win32/msutb/resource.h
- sdk/include/reactos/cicero/cicuif.h
- Add `IDD_CLOSELANGBAR` and `IDD_MINIMIZELANGBAR` resource dialogs.
- Implement `CUTBLangBarDlg` class.
- Implement `CUTBCloseLangBarDlg` and `CUTBMinimizeLangBarDlg` classes.
> [MSUTB][SDK] Add Language Bar dialogs

- dll/win32/msutb/msutb.cpp
- sdk/include/reactos/cicero/cicreg.h
- Add many global variables to add UTB settings.
- Add `IsSkipRedrawHKL`, `IsBiDiLocalizedSystem`, `InitSkipRedrawHKLArray` helper functions.
- Add `InitFromReg` helper function to load the settings from registry.
- Add `CicRegKey::EnumValue` method.
> [MSUTB][SDK] Add InitFromReg

- dll/win32/msutb/msutb.cpp
- Implement `CUTBLBarMenu` class.
> [MSUTB] Add CUTBLBarMenu

- dll/win32/msutb/msutb.cpp
- Implement `CLBarItemButtonBase` class.
- Improve `CLBarItemBase` class.
> [MSUTB] Add CLBarItemButtonBase

- dll/win32/msutb/msutb.cpp
- sdk/include/reactos/cicero/cicuif.h
- Fix the return value type of `CUIFObject::Initialize` method.
- Implement `CModalMenu` class.
> [MSUTB][SDK] Add CModalMenu

- sdk/include/reactos/cicero/cicuif.h
- Renaming method: `s/OnPointingEnded/OnMouseOutFromWindow/`.
> [SDK] cicutf.h: s/OnPointingEnded/OnMouseOutFromWindow/

- dll/win32/msutb/msutb.cpp
- Implement `CShellWndThread` class.
> [MSUTB] Add CShellWndThread

- dll/win32/msutb/msutb.cpp
- sdk/include/reactos/cicero/cicutb.h
- Add `CTipbarWnd` class (stub; empty implementation).
> [MSUTB][SDK] Add CTipbarWnd (stub)

- .github/workflows/labeler.yml
Release notes: https://github.com/actions/labeler/releases
> [GITHUB] Update labeler.yml: Use v5

- .github/workflows/build.yml
> [GITHUB] Update build.yml: latest versions

- dll/win32/msutb/msutb.cpp
- Implement `ClosePopupTipbar` function.
> [MSUTB] Implement ClosePopupTipbar

- dll/win32/msutb/msutb.cpp
- Add `GetTipbarInternal` helper function.
- Implement `GetPopupTipbar` function.
> [MSUTB] Implement GetPopupTipbar

- .github/workflows/build.yml
Something fixed it in the meantime.
Revert 56a4501 (0.4.15-dev-6069).
JIRA issue: [CORE-18911](https://jira.reactos.org/browse/CORE-18911)
- Re-enable 'build-msbuild-i386'
> [GITHUB] build.yml: Re-enable 'build-msbuild-i386'

- dll/win32/msctf/msctf.spec
- dll/win32/msutb/msutb.cpp
- sdk/include/psdk/msctf.idl
- sdk/include/reactos/cicero/cicuif.h
- Modify `msctf.spec`.
- Add `CTipbarThread` and `CTipbarItem` classes.
> [MSCTF][MSUTB][SDK] Add CTipbarItem and CTipbarThread

- dll/win32/msutb/msutb.cpp
- sdk/include/reactos/cicero/cicutb.h
- Add implementation to `CTipbarWnd`.
- Implement `GetLibTls` function.
> [MSUTB][SDK] Add CTipbarWnd Part 4

- sdk/include/reactos/cicero/cicuif.h
- Implement `CUIFMenuItemSeparator::OnPaintO10` method.
- Implement `CUIFSchemeDef::GetCtrlFaceOffset` method.
- Implement `CUIFWindow::PaintObject` method.
- Implement `cicDrawMaskBmpOnDC` function.
> [SDK] cicuif.h: Implement CUIFMenuItemSeparator::OnPaintO10

- base/applications/ctfmon/ctfmon.cpp
- dll/ime/msctfime/msctfime.cpp
- dll/win32/msctf/utils.cpp
- dll/win32/msutb/msutb.cpp
- sdk/lib/cicero/cicbase.cpp
- sdk/lib/cicero/cicutb.h
- Delete `TFInitLib` and `TFUninitLib` calls from `ctfmon.exe`.
- Delete `TFUninitLib` from Cicero library.
- Implement `InitDisplayAttrbuteLib` in `msctfime.ime`.
- Improve `CIC_LIBTHREAD` structure.
> [CTFMON][MSCTFIME][MSCTF][MSUTB][CICERO] Fix TFUninitLib

- dll/ime/msctfime/bridge.cpp
- dll/ime/msctfime/functions.cpp
- dll/ime/msctfime/inputcontext.cpp
- dll/ime/msctfime/inputcontext.h
- dll/ime/msctfime/msctfime.cpp
- dll/ime/msctfime/msctfime.h
- dll/ime/msctfime/ui.cpp
- sdk/lib/cicero/cicimc.h
- Add missing `CicInputContext` methods.
- Implement `CFnDocFeed` class.
> [MSCTFIME][CICERO] Implement CFnDocFeed

- dll/ime/msctfime/bridge.cpp
- dll/ime/msctfime/functions.cpp
- dll/ime/msctfime/functions.h
- dll/ime/msctfime/inputcontext.cpp
- dll/ime/msctfime/inputcontext.h
- dll/ime/msctfime/tls.h
- dll/ime/msctfime/ui.cpp
- Add `CicInputContext::EscbCompComplete` method (stub).
- Implement `CicBridge::OnSetOpenStatus` method.
> [MSCTFIME] Implement CicBridge::OnSetOpenStatus

- dll/ime/msctfime/misc.cpp
- dll/ime/msctfime/misc.h
- dll/ime/msctfime/tls.cpp
- dll/ime/msctfime/tls.h
- dll/ime/msctfime/ui.cpp
- dll/ime/msctfime/ui.h
- Add implementation to `UIComposition` class.
> [MSCTFIME] Add UIComposition Part 2

- dll/win32/browseui/shellbrowser.cpp
Implement Explorer's "Add to Favorites" feature.
JIRA issue: [CORE-16857](https://jira.reactos.org/browse/CORE-16857)
- Add `CreateShortcut` helper function.
- Add `CShellBrowser::OnAddToFavorites`.
https://github.com/reactos/reactos/assets/2107452/59784df7-755a-446c-9ade-7313fadc5f00
> [BROWSEUI] Implement 'Add to Favorites'

- dll/win32/shell32/lang/pl-PL.rc
[shell32] update Polish [pl-PL] translation
> [SHELL32] Update Polish (pl-PL) translation

- dll/cpl/appwiz/lang/pl-PL.rc
[appwiz] Update Polish (pl-PL) translation
> [APPWIZ] Update Polish (pl-PL) translation

- dll/ime/msctfime/bridge.cpp
- dll/ime/msctfime/bridge.h
- Add `CicBridge::EscHanjaMode`.
- Add code to `CicBridge::EscapeKorean`.
> [MSCTFIME] Half-implement CicBridge::EscapeKorean

- dll/ime/msctfime/bridge.cpp
- dll/ime/msctfime/bridge.h
- dll/ime/msctfime/inputcontext.cpp
- dll/ime/msctfime/inputcontext.h
- Implement `CicBridge::Notify` method.
- Implement `CicBridge::SetCompositionString` method.
- Add some `CicInputContext` methods (stub).
> [MSCTFIME] Implement CicBridge::Notify

- dll/win32/msctf/CMakeLists.txt
- dll/win32/msctf/mlng.cpp
- dll/win32/msctf/mlng.h
Implementing the back-end of the Language bar...
- Rename `GetLocaleInfoString` as `GetHKLName`.
- Implement `GetHKLSubstitute` helper function.
- Fix `GetHKLDesctription` function.
> [MSCTF] Implement GetHKLSubstitute

- modules/rosapps/applications/sysutils/kill/kill.c
Be stricter, more explicit, ...
- kill.c: reformat it
- Improve main().
- Improve ExecuteKill().
- correct some return codes
> [KILL] Improve its behavior

- dll/win32/msutb/msutb.cpp
- Define `LANGBARITEMSTATE` structure.
- Implement `CLangBarItemList` class.
> [MSUTB] Implement CLangBarItemList

- win32ss/user/ntuser/nonclient.c
_Fix Mouse Buttons Sticking Down causing unexpected window dragging._
_This is a patch supplied by @I_Kill_Bugs and seems to work well as tested by @julenuri._
JIRA issue: [CORE-11775](https://jira.reactos.org/browse/CORE-11775)
JIRA issue: [CORE-14998](https://jira.reactos.org/browse/CORE-14998)
Improves JIRA issue: [CORE-18511](https://jira.reactos.org/browse/CORE-18511)
_Add extra code into nonclient.c procedure DefWndDoSizeMove to drop tracking._
_If we get a mouse move with the mouse left button down, then break out of testing._
> [NTUSER] Fix sticky mouse buttons

- sdk/tools/gen_baseaddress.py
We have `dll/ime/msctfime` for the DLL file `msctfime.ime`.
- Add `'.ime'` to `ALL_EXTENSIONS`.
> [TOOLS] gen_baseaddress.py: Add '.ime' to ALL_EXTENSIONS

- sdk/lib/rtl/slist.c
> [RTL/x64] Fix a GCC compiler warning

- drivers/wdm/audio/hdaudbus/fdo.cpp
- drivers/wdm/audio/hdaudbus/hdaudbus.h
Silence annoying debug prints
- Demote a DPRINT1 to a DPRINT
- Define NDEBUG
> [HDAUDBUS] Silence debug spam

- drivers/base/bootvid/arm/arm.h
- drivers/base/bootvid/arm/bootvid.c
- drivers/base/bootvid/bootvid.rc
- drivers/base/bootvid/common.c
- drivers/base/bootvid/fontdata.c
- drivers/base/bootvid/i386/pc/bootdata.c
- drivers/base/bootvid/i386/pc/bootvid.c
- drivers/base/bootvid/i386/pc/pc.h
- drivers/base/bootvid/i386/pc/vga.c
- drivers/base/bootvid/i386/pc98/bootvid.c
- drivers/base/bootvid/i386/pc98/pc98.h
- drivers/base/bootvid/i386/xbox/bootvid.c
- drivers/base/bootvid/i386/xbox/xbox.h
- drivers/base/bootvid/precomp.h
- Add file copyright information headers. @binarymaster @disean Could you double-check these in particular?
- Don't NTAPI non-exported functions; remove useless `@implemented`
- ~~Reorder some functions.~~
> [BOOTVID] Add file info headers + minor cleanup

- dll/win32/devmgr/lang/ro-RO.rc
> [DEVMGR] Update Romanian (ro-RO) translation

- dll/cpl/hotplug/lang/ro-RO.rc
> [HOTPLUG] Add Romanian (ro-RO) translation

- base/applications/sndvol32/lang/ro-RO.rc
> [SNDVOL32] Update Romanian (ro-RO) translation

- dll/cpl/timedate/lang/ro-RO.rc
> [TIMEDATE] Update Romanian (ro-RO) translation

- base/applications/calc/lang/ro-RO.rc
> [CALC] Update Romanian (ro-RO) translation

- drivers/usb/usbohci/usbohci.c
- drivers/usb/usbuhci/usbuhci.c
> [USB] Fix indentation

- dll/win32/advapi32/reg/hkcr.c
- dll/win32/advapi32/reg/reg.c
- dll/win32/advapi32/reg/reg.h
HKCR delete handling; delete the value in HKCU if it exists there, otherwise delete it in HKLM.
Changed RegDeleteKeyValueW to just use the regular Reg functions to get HKCR handling for free.
> [ADVAPI32] Handle HKCR in RegDeleteValueA+W and RegDeleteKeyValueW

- configure.cmd
Update configure.cmd to support MSVC compiler version 19.4x
> [CONFIGURE] Add support for MSVC Compiler 19.4x

- ntoskrnl/ke/amd64/traphandler.c
- Use an index for the table instead of ugly pointer offset
- Invert the check for GUI calls
- Fail with proper status code on invalid win32k syscall ids
- https://reactos.org/testman/compare.php?ids=94282,94307,94313
- spoolss:SplInitializeWinSpoolDrv crashed? -> Do a rerun
- rerun https://reactos.org/testman/compare.php?ids=94313,94326,94331,94334 (first 2 are this PR)
> [NTOS:KE/x64] Improve KiSystemCallHandler code a bit

- media/doc/3rd Party Files.txt
Improve documentation.
Addendum to 4afb647 (0.4.15-dev-5466).
- Add 'AMD LibM for Windows'
> [DOC] 3rd Party Files.txt: Add 'AMD LibM for Windows'

- media/doc/3rd Party Files.txt
Documentation.
Note:
After a quick look, it seems original code simply reads "freeware".
- Update/Complete 'CardLib'
> [DOC] 3rd Party Files.txt: Update/Complete 'CardLib'

- ntoskrnl/ke/amd64/except.c
Return back to the caller instead of exiting through KiServiceExit2, which is broken and needs to be changed to allow restoring of an exception frame.
- KVM x64: https://reactos.org/testman/compare.php?ids=94377,94379,94387,94401
> [NTOS:Ke/x64] Improve KiDispatchExceptionToUser

- dll/win32/shell32/shfldr.h
> [SHELL32] Use Uppercase in SHELL32_GUIDToStringA/W

- dll/win32/shlwapi/lang/ro-RO.rc
> [SHLWAPI] Update Romanian (ro-RO) translation

- dll/shellext/stobject/lang/ro-RO.rc
> [STOBJECT] Update Romanian (ro-RO) translation

- drivers/ksfilter/ks/filter.c
Fix a bug
- KVM x64: https://reactos.org/testman/compare.php?ids=94452,94461,94469,94479
- KVM x86: https://reactos.org/testman/compare.php?ids=94474,94480,94482,94485 (?)
> [KS] Fix a bug found by GCC 13

- ntoskrnl/include/internal/amd64/ke.h
Improve KeGetTrapFrame with a round of braces
> [NTOS:KE/x64] Improve KeGetTrapFrame

- sdk/lib/drivers/sound/mmixer/wave.c
Calculate size of the additional data based on the format tag specified by the caller. For PCM wave format, it should be zero, and for all others, it should be taken from `cbSize` member of `WAVEFORMATEX` structure.
Fixes two crashes in winmm:capture and winmm:wave winetests, which have been introduced by 12b3272d9e6b2810985516ebad0ce545e5601d59. So this is an addendum to that commit.
JIRA issue: [CORE-19514](https://jira.reactos.org/browse/CORE-19514)
- Initialize data size for each format appropriately.
- Append it to the total pin connect allocation size, to allocate enough memory for it.
- Use it as additional data size for requested wave format.
- Append it to the total size of data format.
- Add SAL2 annotations for `MMixerInitializeDataFormat` function.
As visible on the following …
> [MMIXER] Fix additional data size initialization for different audio formats

- media/doc/3rd Party Files.txt
Documentation.
- Update 3 unknown versions
> [DOC] 3rd Party Files.txt: Update 3 unknown versions

- win32ss/user/ntuser/focus.c
- win32ss/user/ntuser/msgqueue.c
- win32ss/user/ntuser/msgqueue.h
JIRA issue: [CORE-14768](https://jira.reactos.org/browse/CORE-14768), [CORE-18525](https://jira.reactos.org/browse/CORE-18525)
> [NTUSER] Release modifier keys when deactivating message queue

- README.md
Update badges to reflect the versions on https://reactos.org/wiki/Build_Environment
- Bump version numbers and change links to point to newer versions
> [README] Update RosBE links and badges to version 2.2.1

- sdk/lib/rtl/CMakeLists.txt
- sdk/lib/rtl/actctx.c
This PR reduces the diff between our actctx.c and wine's as a preparation to do a proper sync.
✅ KVM x86: https://reactos.org/testman/compare.php?ids=94960,94964,94969,94971
✅ KVM x64: https://reactos.org/testman/compare.php?ids=94992,94996,94997,94998
> [RTL] Wine-sync preparation

- ntoskrnl/include/internal/amd64/ke.h
- ntoskrnl/include/internal/i386/ke.h
- ntoskrnl/include/internal/ke.h
- ntoskrnl/ke/amd64/trap.S
- ntoskrnl/ke/except.c
- sdk/lib/rtl/amd64/except_asm.S
Fix NtRaiseException and NtContinue on x64
✅ KVM x86: https://reactos.org/testman/compare.php?ids=94981,94985,94988,94995,94999
- KVM x64: https://reactos.org/testman/compare.php?ids=94992,94996,94997,95000
> [NTOS:KE] Fix NtRaiseException and NtContinue on x64

- ntoskrnl/ex/time.c
_Fix ExpSetTimeZoneInformation so that is is Daylight Savings Time aware._
JIRA issue: [CORE-19290](https://jira.reactos.org/browse/CORE-19290)
_Convert Eric Kohl's TimeZoneID code from ExRefreshTimeZoneInformation to a function._
_Use this new function in the ExpSetTimeZoneInformation function._
> [NTOS:EX] Various fixes for Daylight Saving Time transitions

- dll/ntdll/def/ntdll.spec
- dll/win32/msvcrt/msvcrt.spec
- sdk/lib/crt/printf/_swprintf.c
- sdk/lib/crt/printf/printf.cmake
Add _swprintf implementation. Needed for upcoming wineync.
> [CRT][NTDLL][MSVCRT] Add _swprintf implementation

- sdk/lib/pseh/include/pseh/pseh2_64.h
- sdk/tools/gcc_plugin_seh/main.cpp
The change is needed, because the previous version emitted multiple ".seh_handlerdata" blocks and GAS isn't able to merge them into one, but will instead only include the first one. This is fixed by generating "asm defines" in the code and pass the line number to the "REACTOS seh" pragma, which is then used to create all handler data by referring to the predefined symbols, that include the line number. Also the EstablisherFrame parameter passed to the filter/finally function is the original stack pointer, not the frame pointer! Take this into account by passing __builtin_frame_address(0) from the filter context to the global wrapper function, which includes the frame-offset, and use that to recalculate the frame-pointer from the passed in stack pointer.
- Fix problem with multiple …
> [PSEH/x64] Fix our GCC-SEH-plugin hack

- win32ss/gdi/ntgdi/freetype.c
Slight performance improvement.
- Add `bNoTransform` variable.
- Check whether `mat` is identity matrix.
- If so, then don't do `FT_Vector_Transform`.
BEFORE:
About 6300 milliseconds.
AFTER:
About 6220 milliseconds.
> [NTGDI][FREETYPE] Check 'No transformation' for performance

- win32ss/user/ntuser/msgqueue.c
Patch by @I_Kill_Bugs
_Fixes Skype installer window not able to be moved with mouse by clicking on title bar_
JIRA issues: [CORE-19487](https://jira.reactos.org/browse/CORE-19487) and [CORE-19538](https://jira.reactos.org/browse/CORE-19538)
_Add condition into msgqueue along with filter testing to reject messages that are "NotForUs"._
_Also, do not set AcceptMessage to FALSE, but just keep msgDblClk and idSysPeek values and continue._
> [NTUSER] Fix Skype and other programs installer windows not able to be moved with mouse by clicking on title bar

- win32ss/user/ntuser/menu.c
Patch by @I_Kill_Bugs
_Fix window failing to close when icon on title bar double clicked._
JIRA issue: [CORE-19492](https://jira.reactos.org/browse/CORE-19492)
_Add code in MENU_TrackMenu to account for double click on title bar icon and close window._
Menufix1.patch JID67656 on top of 0.4.15-dev-7800-g2ec785b
VBox: https://reactos.org/testman/compare.php?ids=94111,94114 LGTM
KVM: https://reactos.org/testman/compare.php?ids=94112,94115 LGTM
> [NTUSER] Fix double click on title bar icon not closing window

- win32ss/user/user32/lang/ro-RO.rc
> [USER32] Update Romanian (ro-RO) translation

- dll/shellext/deskadp/lang/ro-RO.rc
> [DESKADP] Update Romanian (ro-RO) translation

- dll/cpl/joy/lang/ro-RO.rc
> [JOY] Update Romanian (ro-RO) translation

- base/applications/osk/lang/ro-RO.rc
> [OSK] Update Romanian (ro-RO) translation

- base/applications/mstsc/lang/ro-RO.rc
> [MSTSC] Update Romanian (ro-RO) translation

- media/doc/Romanian translation notes.txt
I propose some rules closer to the MSDN ones. Of course, I will modify everywhere.
> [DOC] Update Romanian translation notes.txt

- base/services/w32time/register.c
- base/services/w32time/w32time.c
- base/services/w32time/w32time.h
_Update w32time Special Poll Interval from 1 week to 4 hours._
JIRA issue: [CORE-19281](https://jira.reactos.org/browse/CORE-19281)
_Change the registry's Special Poll Interval to 14400._
_To completely fix CORE-19281 it also requires PR #5868 be committed._
_This should help on Daylight Time Transitions until ReactOS supports WM_TIMECHANGE._
> [W32TIME] Change clock update interval to 4 hours

- dll/win32/shell32/shlexec.cpp
Follow-up to #6871. Reduce indentation level.
JIRA issue: [CORE-17482](https://jira.reactos.org/browse/CORE-17482)
- In `ShellExecuteExW`, early check the structure size and return on failure before `SHCoInitializeAnyApartment` call.
> [SHELL32] ShellExecute: Re-work Part 2

- media/themes/Lunar/lunar.msstyles/textfiles/ExtraLargeReactOS.INI
- media/themes/Lunar/lunar.msstyles/textfiles/LargeFontsReactOS.INI
- media/themes/Lunar/lunar.msstyles/textfiles/NormalReactOS.INI
JIRA issue: None...again?
- See image above
> [LUNAR] Fix SizingMargins for the taskbar and notification area backgrounds

- README.md
> Nitpick styling update of README.md

- dll/win32/shell32/CMakeLists.txt
- dll/win32/shell32/brsfolder.cpp
- dll/win32/shell32/wine/brsfolder.cpp
Modernize source code.
- Move `dll/win32/shell32/wine/brsfolder.c` to `dll/win32/shell32/brsfolder.cpp`.
- Adapt to C++.
> [SHELL32] Make brsfolder.c C++ (as brsfolder.cpp)

- dll/keyboard/CMakeLists.txt
- drivers/filesystems/cdfs/CMakeLists.txt
- drivers/filesystems/ext2/CMakeLists.txt
- drivers/filesystems/nfs/CMakeLists.txt
- modules/rostests/apitests/ntdll/CMakeLists.txt
- modules/rostests/apitests/rtl/CMakeLists.txt
> [CMAKE] Stop explicitly setting the C standard

- dll/win32/shell32/lang/pt-PT.rc
Follow-up PR #6861 (addendum to d7be7486c97).
> [SHELL32] Fix accelerator collision in Portuguese (pt-PT) translation

- dll/win32/shell32/brfolder.cpp
Refactoring. Simplify item insertion code.
- Remove `pEnumIL` member from `BrItemData` structure.
- Add `BrFolder_GetChildrenEnum` helper function.
- Remove `IEnumIDList*` argument from `BrFolder_InsertItem` and `BrFolder_Expand` functions.
- Add `BrFolder_OnOK` function and use it.
LGTM.
> [SHELL32] brfolder.cpp: Remove pEnumIL member

- base/applications/regedit/lang/pt-PT.rc
[REGEDIT] Fix accels collisions.
Improve Portuguese (pt-PT) translation
accels compatibility closer to Win2003 Server
> [REGEDIT] Fix accels collisions

- base/applications/notepad/lang/pt-PT.rc
[NOTEPAD] Fix accel collisions. Improve menu cmd translation (pt-PT)
[NOTEPAD] Update Portuguese (pt-PT) translation
> [NOTEPAD] pt-PT: Fix accel collisions. Improve menu cmd translation

- win32ss/gdi/ntgdi/freetype.c
Simplify code.
- Reduce one parameter of `get_glyph_index_flagged` function.
> [NTGDI][FREETYPE] Simplify get_glyph_index_flagged

- base/applications/taskmgr/lang/pt-BR.rc
> [TASKMGR] Fix orthographic error in Portuguese Brazilian (pt-BR) translation

- base/shell/explorer/lang/pl-PL.rc
[EXPLORER] Update Polish (pl-PL) translation
> [EXPLORER] Update Polish (pl-PL) translation

- sdk/include/ddk/mountdev.h
- sdk/include/ddk/mountmgr.h
- Add missing file info headers.
- Make the headers C++ friendly.
> [DDK] mountdev.h, mountmgr.h: Minor cleanup

- dll/win32/msutb/lang/pt-PT.rc
- dll/win32/msutb/msutb.rc
Add new Portuguese (pt-PT) translation.
> [MSUTB] Add Portuguese (pt-PT) translation

- dll/win32/shimgvw/lang/cs-CZ.rc
- dll/win32/shimgvw/lang/sk-SK.rc
Updates the Czech and Slovak translations of shimgvw.
> [SHIMGVW] Update Czech (cs-CZ) and Slovak (sk-SK) translation

- drivers/storage/mountmgr/device.c
- drivers/storage/mountmgr/mntmgr.h
- drivers/storage/mountmgr/mountmgr.c
- drivers/storage/mountmgr/notify.c
- drivers/storage/mountmgr/symlink.c
Introduce MountMgrSendSyncDeviceIoCtl to replace repeated code.
> [MOUNTMGR] Introduce MountMgrSendSyncDeviceIoCtl() to replace repeated code

- dll/cpl/input/lang/pt-PT.rc
Add file header
Change SUBLANG to NEUTRAL
> [INPUT] Update Portuguese (pt-PT) translation: Change SUBLANG to NEUTRAL; Add file header

- base/applications/regedit/lang/pt-PT.rc
[REGEDIT] Update Portuguese (pt-PT) translation
> [REGEDIT] Update Portuguese (pt-PT) translation

- base/system/winlogon/lang/cs-CZ.rc
Updates the Czech translations of winlogon.
> [WINLOGON] Update Czech (cs-CZ) translation

- dll/win32/shimgvw/lang/eo-AA.rc
- dll/win32/shimgvw/shimgvw.rc
Adds Esperanto translation of shimgvw.
> [SHIMGVW] Add Esperanto (eo-AA) translation

- win32ss/gdi/ntgdi/freetype.c
#7009 introduced unexpected freezing on `gdi*` bot tests.
JIRA issue: [CORE-19667](https://jira.reactos.org/browse/CORE-19667)
- Fix the locking-related assertions by adding/removing lock/unlock.
AFTER:
> [NTGDI][FREETYPE] Fix FontLink freeze

- win32ss/gdi/ntgdi/bitblt.c
Follow-up to #7074. Fix `MaskBlt` behaviour.
JIRA issue: [CORE-13133](https://jira.reactos.org/browse/CORE-13133)
- Fix `MaskBlt` error code.
- Fix `MaskBlt` pattern usage check.
BEFORE:
AFTER:
Successful.
> [NTGDI] Fix MaskBlt error code and check pattern usage

- base/system/userinit/lang/sk-SK.rc
Updates the Slovak translation of Userinit Logon Application.
> [USERINIT] Update Slovak (sk-SK) translation

- base/system/userinit/lang/cs-CZ.rc
Updates the Czech translation of Userinit Logon Application.
> [USERINIT] Update Czech (cs-CZ) translation

- dll/cpl/intl/lang/cs-CZ.rc
Updates the Czech translation of international control panel.
> [INTL] Update Czech (cs-CZ) translation

- win32ss/gdi/gdi32/objects/gdiobj.c
Fix returned error code value  based on GetObject gdi32_apitest
> [GDI32] Fix return value based on GetObject gdi32_apitest

- dll/cpl/desk/lang/pt-PT.rc
Add file header. 
Change SUBLANG to NEUTRAL
Improve Portuguese (pt-PT) translation
Add missing accel keys and fix some others accel collisions.
> [DESK] Improve pt-PT Translation; Add missing accel keys and fix some others accel collisions.

- dll/cpl/timedate/lang/cs-CZ.rc
Updates the Czech translation of Timedate Control Panel.
> [TIMEDATE] Update Czech (cs-CZ) translation

- base/applications/rapps/lang/bg-BG.rc
- base/applications/rapps/lang/cs-CZ.rc
- base/applications/rapps/lang/de-DE.rc
- base/applications/rapps/lang/en-US.rc
- base/applications/rapps/lang/es-ES.rc
- base/applications/rapps/lang/et-EE.rc
- base/applications/rapps/lang/fr-FR.rc
- base/applications/rapps/lang/he-IL.rc
- base/applications/rapps/lang/hu-HU.rc
- base/applications/rapps/lang/id-ID.rc
- base/applications/rapps/lang/it-IT.rc
- base/applications/rapps/lang/ja-JP.rc
- base/applications/rapps/lang/no-NO.rc
- base/applications/rapps/lang/pl-PL.rc
- base/applications/rapps/lang/pt-BR.rc
- base/applications/rapps/lang/pt-PT.rc
- base/applications/rapps/lang/ro-RO.rc
- base/applications/rapps/lang/ru-RU.rc
- base/applications/rapps/lang/sk-SK.rc
- base/applications/rapps/lang/sq-AL.rc
- base/applications/rapps/lang/sv-SE.rc
- base/applications/rapps/lang/tr-TR.rc
- base/applications/rapps/lang/uk-UA.rc
- base/applications/rapps/lang/zh-CN.rc
- base/applications/rapps/lang/zh-HK.rc
- base/applications/rapps/lang/zh-TW.rc
This shrinks the binary size a tiny bit.
> [RAPPS] *.rc: Strip 2x "popup"-strings

- dll/cpl/input/lang/cs-CZ.rc
Updates the Czech translation of language control panel.
> [INPUT] Update Czech (cs-CZ) translation

- dll/ime/msctfime/lang/pt-PT.rc
- dll/ime/msctfime/msctfime.rc
Add new Portuguese (pt-PT) translation.
> [MSCTFIME] Add new Portuguese (pt-PT) translation.

- dll/shellext/cryptext/cryptext.rc
- dll/shellext/cryptext/lang/pt-PT.rc
Add new Portuguese (pt-PT) translation.
> [CRYPTEXT] Add new Portuguese (pt-PT) translation.

- win32ss/user/ntuser/winpos.c
Splitted from #7082. Correct behavior of `NtUserSetWindowPlacement` function.
- Check `gptiCurrent->dwExpWinVer` in `NtUserSetWindowPlacement` function.
- Fix the last error.
> [NTUSER] Improve NtUserSetWindowPlacement

- dll/win32/browseui/explorerband.cpp
- dll/win32/browseui/explorerband.h
Refactoring. Optimize for speed.
JIRA issue: [CORE-12619](https://jira.reactos.org/browse/CORE-12619)
- Update file headers.
- Make some parameter type `LPITEMIDLIST` `LPCITEMIDLIST` (Add `const`).
- Add `OnChangeNotify` method.
- Use `SHCNRF_NewDelivery` method for speed.
- Add some SAL annotations.
> [BROWSEUI] CExplorerBand: Use SHCNRF_NewDelivery method

- base/applications/taskmgr/lang/ro-RO.rc
> [TASKMGR] Update Romanian (ro-RO) translation

- base/shell/explorer/lang/ro-RO.rc
> [EXPLORER] Update Romanian (ro-RO) translation

- modules/rosapps/applications/explorer-old/explorer-ro.rc
> [EXPLORER_OLD] Update Romanian (ro-RO) translation

- dll/cpl/input/lang/ro-RO.rc
> [INPUT] Update Romanian (ro-RO) translation

- base/applications/screensavers/logon/lang/ro-RO.rc
> [LOGON] Update Romanian (ro-RO) translation

- dll/cpl/telephon/lang/ro-RO.rc
> [TELEPHON] Update Romanian (ro-RO) translation

- modules/rosapps/applications/screensavers/ssstars/lang/ro-RO.rc
> [SSSTARS] Update Romanian (ro-RO) translation

- dll/cpl/powercfg/lang/ro-RO.rc
> [POWERCFG] Update Romanian (ro-RO) translation

- dll/win32/msvfw32/lang/msvfw32_Ro.rc
> [MSVFW32] Update Romanian (ro-RO) translation

- dll/win32/avifil32/lang/avifile_Ro.rc
> [AVIFIL32] Update Romanian (ro-RO) translation

- dll/win32/userenv/lang/ro-RO.rc
Attendum to https://github.com/reactos/reactos/pull/6517.
Now it synchronizes with Shell32 (look at #6657).
> [USERENV] Update Romanian (ro-RO) translation

- dll/shellext/netplwiz/lang/ro-RO.rc
> [NETPLWIZ] Update Romanian (ro-RO) translation

- dll/win32/setupapi/lang/ro-RO.rc
> [SETUPAPI] Update Romanian (ro-RO) translation

- base/system/winlogon/lang/sk-SK.rc
Updates the Slovak translations of winlogon.
> [WINLOGON] Update Slovak (sk-SK) translation

- dll/cpl/mmsys/lang/pt-PT.rc
Add file hdr.
Improve pt-PT translation. 
Adjust window text length to fix visual glitch.
> [MMSYS] Add file hdr. Improve pt-PT translation. Adjust window text length.

- dll/cpl/usrmgr/lang/pt-PT.rc
Add file header.
Improve Portuguese (pt-PT) translation.
Readjust text window width to fit all text.
> [USRMGR] Add file header. Improve pt-PT translation.

- dll/shellext/acppage/lang/cs-CZ.rc
Updates the Czech translation of Compatibility Layer Shell Extension.
> [ACPPAGE] Update Czech (cs-CZ) translation

- dll/shellext/netshell/lang/pt-PT.rc
Add file hdr. 
Improve portuguese (pt-PT) translation.
Fix typos.
> [NETSHELL] Add file hdr. Improve portuguese (pt-PT) translation.

- dll/shellext/netplwiz/lang/pt-PT.rc
Add file header. 
Fix typos in pt-PT translation.
> [NETPLWIZ] Add file hdr. Fix typos in  pt-PT translation. 

- sdk/include/reactos/libs/sound/mmebuddy_debug.h
- sdk/lib/drivers/sound/mmebuddy/CMakeLists.txt
- sdk/lib/drivers/sound/mmixer/CMakeLists.txt
Fix NDEBUG support, especially on Release builds.
- Remove unwanted value.
- Use add_compile_definitions().
- NDEBUG "depends" on DBG.
> [MMEBUDDY][MMIXER] Fix NDEBUG support

- dll/win32/shell32/CShellLink.cpp
Reduce code. Modernize code.
- Use `CStringW` and `CComHeapPtr<WCHAR>` for dynamic allocation.
> [SHELL32] Refactor CShellLink::DoOpen

- dll/win32/shell32/shellrecyclebin/CMakeLists.txt
- dll/win32/shell32/shellrecyclebin/recyclebin_generic.cpp
- dll/win32/shell32/shellrecyclebin/recyclebin_private.h
Modernize code.
- Rewrite `RecycleBinGeneric` in C++.
> [SHELL32] RecycleBinGeneric: Make it C++

- dll/win32/shell32/shellrecyclebin/CMakeLists.txt
- dll/win32/shell32/shellrecyclebin/recyclebin_private.h
- dll/win32/shell32/shellrecyclebin/recyclebin_v5.cpp
Modernize code.
- Rewrite `RecycleBin5` in C++.
> [SHELL32] RecycleBin5: Make it C++

- dll/win32/shell32/shellrecyclebin/recyclebin_generic.cpp
Follow-up of #7169
- Revert some code in `RecycleBinGeneric::DeleteFile`.
> [SHELL32] Follow-up of #7169

- base/applications/rapps/lang/cs-CZ.rc
Updates the Czech translation of ReactOS Applications Manager.
> [RAPPS] Update Czech (cs-CZ) translation

- dll/win32/uxtheme/lang/cs-CZ.rc
- dll/win32/uxtheme/lang/sk-SK.rc
- dll/win32/uxtheme/uxtheme.rc
Updates the Czech and Slovak translations of uxtheme.
> [UXTHEME] Add Czech (cs-CZ) and Slovak (sk-SK) translations

- dll/cpl/powercfg/lang/cs-CZ.rc
Updates the Czech translation of Power Configuration Applet.
> [POWERCFG] Update Czech (cs-CZ) translation

- win32ss/user/user32/windows/input.c
Code diet. `RegCreateKeyExW` will create sub-keys recursively, so this code is okay.
- Simplify registry key creation code.
> [USER32] Simplify CliSaveImeHotKey

- base/shell/explorer/lang/cs-CZ.rc
Updates the Czech translation of ReactOS Explorer.
> [EXPLORER] Update Czech (cs-CZ) translation

- base/shell/rshell/CQuickLaunchBand.cpp
- base/shell/rshell/CQuickLaunchBand.h
- base/shell/rshell/misc.cpp
Reduce coding stress.
JIRA issue: [CORE-18462](https://jira.reactos.org/browse/CORE-18462)
- Just fix indentation.
> [RSHELL] Fix indentation

- base/shell/rshell/CQuickLaunchBand.cpp
- base/shell/rshell/CQuickLaunchBand.h
- base/shell/rshell/misc.cpp
Follow our standard.
JIRA issue: [CORE-18462](https://jira.reactos.org/browse/CORE-18462)
- Adapt file headers to our coding style.
> [RSHELL] Fix file headers

- dll/ntdll/nt_0600/CMakeLists.txt
- dll/ntdll/nt_0600/ntdll_vista.rc
- dll/win32/advapi32_vista/CMakeLists.txt
- dll/win32/advapi32_vista/advapi32_vista.rc
- dll/win32/kernel32/kernel32_vista/CMakeLists.txt
- dll/win32/kernel32/kernel32_vista/kernel32_vista.rc
- win32ss/gdi/gdi32_vista/gdi32_vista.rc
- win32ss/user/user32_vista/user32_vista.rc
Add 'Version' tab to Vista DLL properties.
- [*_VISTA] Add/Improve version resources
> [*_VISTA] Add/Improve version resources

- dll/win32/browseui/shellbrowser.cpp
The interaction between the shell browser and its address bar causes the browser to read from a freed PIDL, sometimes causing a crash.
Fixes [CORE-19697](https://jira.reactos.org/browse/CORE-19697) crash.
> [BROWSEUI] Don't access callers invalid PIDL during browse

- dll/cpl/sysdm/lang/ro-RO.rc
> [SYSDM] Update Romanian (ro-RO) translation

- modules/rosapps/applications/screensavers/matrix/lang/ro-RO.rc
> [MATRIX] Improve Romanian (ro-RO) translation

- sdk/lib/crt/time/strftime.c
> [CRT] Fix prototype of _Strftime

- win32ss/gdi/gdi32/objects/text.c
- win32ss/user/ntuser/painting.c
> [GDI32][NTUSER] Demote noisy debug prints

- dll/win32/browseui/lang/pt-PT.rc
Add file header.
Fix typos and improve pt-PT translation.
> [BROWSEUI] Fix typos and improve pt-PT translation. Add file header.

- base/applications/rapps/appview.cpp
- base/applications/rapps/include/misc.h
- base/applications/rapps/misc.cpp
NM_RCLICK is too low level, WM_CONTEXTMENU is the correct place to handle context menus.
> [RAPPS] Show listview context menu when the keyboard menu button/Shift+F10 is pressed

- dll/win32/advpack/files.c
Sort out code.
Addendum to 6eb8a1d (0.4.15-dev-6918).
See #5821.
- Properly mark Wine diff
> [ADVPACK] files.c: Properly mark Wine diff

- hal/halx86/acpi/madt.c
- hal/halx86/include/smp.h
- hal/halx86/smp/mps/mps.c
Especially HalpParseApicTables() which looked early-WIP and was buggy.
And keep smp/mps/mps.c in sync'.
Make it work right.
- Rewrite it
> [HALX86] acpi/madt.c: Rewrite it

- win32ss/user/ntuser/desktop.c
Distinguish between the following 3 scenarios:
1. Interactive Winsta0, "Winlogon" desktop: use 128 KB
2. Interactive Winsta0, "Default" & other desktop: use 3 MB (x86) / 20 MB (x64)
3. Non-interactive winsta: use 128 KB
This is what Windows 2003 uses for the interactive desktops on x86 and what Windows 7 uses for x64. Fixes desktop heap exhaustion during testing. The previous value was 512 KB for all desktops. It doesn't handle the even smaller "Disconnected" desktop, which is only meaningful for RDP sessions and we don't use it anyway. See comments in the file for references.
KVM x86:  https://reactos.org/testman/compare.php?ids=97553,97557,97586,97589
- Fixes a lot of tests, no more additional reboots
- Seems to cause a crash in user32:menu (investigating)
- New run: …
> [NTUSER] Increase desktop heap size

- dll/cpl/desk/lang/tr-TR.rc
- dll/win32/uxtheme/lang/tr-TR.rc
- dll/win32/uxtheme/uxtheme.rc
I added the uxtheme translation file for turkish translations, inspired by windows 7 turkish translation.
> [UXTHEME] Add Turkish (tr-TR) translation

- win32ss/user/ntuser/timer.c
The return value of RtlFindClearBitsAndSet is an ULONG, assigning it to an ULONG_PTR will not sign extend it. The error value will stay 0xFFFFFFFF. Comparing it to (UINT_PTR)-1 will sign extend and thus compare it to 0xFFFFFFFFFFFFFFFF on x64. Also use NUM_WINDOW_LESS_TIMERS to initialize the bitmap, rather than the calculated size. This does not make a difference with the current value (32768), but if it was not the case, the bitmap would be larger than this, resulting in invalid bitmap indices being returned, which would cause bugs later on.
> [NTUSER] Fix a 64 bit bug in timer code

- win32ss/gdi/ntgdi/cliprgn.c
This can happen, when the paged pool is full. This will probably cause drawing issues, but at least we don't crash (in this place).
> [NTGDI] Prevent NULL pointer dereference in CLIPPING_UpdateGCRegion

- ntoskrnl/po/power.c
Be consistent with new code.
Addendum to 9e43518 (0.4.15-dev-7560).
- Fix UTF-8 header
- Update a comment
- Tweak a `sizeof()`
> [NTOS:PO] Update a comment

- modules/rostests/kmtests/ntos_se/SeQueryInfoToken.c
- ntoskrnl/ob/obhandle.c
- ntoskrnl/se/access.c
- ntoskrnl/se/priv.c
- sdk/include/ndk/setypes.h
Review commit by commit please.
> [KMTEST][NTOS][NDK] Fix SeQueryInfoToken test failures

- sdk/include/reactos/unaligned.h
- sdk/include/xdk/rtlfuncs.h
- win32ss/include/ntuser.h
- win32ss/user/ntuser/class.c
- win32ss/user/ntuser/ntstubs.c
- win32ss/user/ntuser/window.c
- win32ss/user/user32/windows/class.c
- win32ss/w32ksvc64.h
Implement it.
Fixes a number of tests on x64.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=97726,97729,97732,97734
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=97724,97727,97730,97736
New run:
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=97750,97758,97768
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=97724,97727,97730,97736,97770
> [USER32][NTUSER] Implement (NtUser)SetClassLongPtr(A/W)

- ntoskrnl/mm/mmfault.c
This prevents processes from looping forever, thinking the fault was already resolved, because the page is writable.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=97850,97855,97856,97833
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=97813,97821,97824,97834
> [NTOS:MM] Properly handle execution in NX section

- dll/shellext/acppage/lang/ro-RO.rc
Improvements based on recent Romanian translation document revision 06e89b2e81cd7de029fac2c595a6371eba13d797.
> [ACPPAGE] Update Romanian (ro-RO) translation

- dll/cpl/liccpa/lang/ro-RO.rc
The aim of this PR is to correct the Romanian header mistake
> [LICCPA] Update Romanian (ro-RO) translation

- base/applications/mspaint/lang/tr-TR.rc
> [MSPAINT] Update Turkish (tr-TR) translation

- dll/ime/msctfime/lang/tr-TR.rc
- dll/ime/msctfime/msctfime.rc
Adding the Turkish language file for IME and providing the most accurate translation
> [MSCTFIME] Add Turkish (tr-TR) translation

- dll/ime/msctfime/msctfime.rc
Addendum to 0.4.16-dev-79-g 17be785eef363b5fc12b5461d7148af498a9c83e
> [MSCTFIME] msctfime.rc turkish-sort

- boot/freeldr/freeldr/arch/i386/pc/pcdisk.c
- boot/freeldr/freeldr/arch/i386/pc98/pc98disk.c
- boot/freeldr/freeldr/lib/fs/fat.c
Collapse some tests; remove redundant `continue;`
Pointed out by Serge Gautherie.
> [FREELDR] Simplify some control branches in loops

- ntoskrnl/mm/section.c
> [NTOS:MM] MmFlushSegment: Simplify return

- dll/win32/shell32/CDefView.cpp
JIRA issue: [CORE-19778](https://jira.reactos.org/browse/CORE-19778)
> [SHELL32] Remove view related items from File menu

- dll/win32/shell32/dialogs/folder_options.cpp
JIRA issue: [CORE-19784](https://jira.reactos.org/browse/CORE-19784)
> [SHELL32] Always initialize COM for Folder Options dialog

- base/system/services/database.c
This function combines those that write a message to and read
a message from the specified pipe into a single operation.
Its usage helps in simplifying the code further.
> [SERVICES] ScmControlService: Use TransactNamedPipe() instead of successive Write+Read

- base/setup/usetup/spapisup/cabinet.c
Addendum to 5d4d912 (r15403).
- Add an `else`.
> [USETUP] CabinetExtractFile(): Do not overwrite Status value

- sdk/cmake/msvc.cmake
- subsystems/mvdm/asm16.cmake
Silence ML's "Assembling ..." message.
Makes MSVC build log a tiny bit cleaner.
> [CMAKE] Silence ML's "Assembling ..." message

- dll/ntdll/CMakeLists.txt
- dll/win32/advapi32/CMakeLists.txt
- dll/win32/advapi32/advapi32.spec
- dll/win32/msvcrt/msvcrt.spec
- dll/win32/softpub/softpub.spec
- sdk/include/psdk/winspool.h
- win32ss/printing/base/winspool/devmode.c
- win32ss/printing/base/winspool/printers.c
- win32ss/printing/base/winspool/winspool.spec
Improve some export definitions.
- [ADVAPI32][ETWTRACE] Add etwtrace library and link advapi32 to it on NT6+
- [SOFTPUB] Replace some stubs with forwarders
- [WINSPOOL.DRV] Improve some stubs
- [MSVCRT] Export _vcwprintf
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=98291,98295,98300,98303
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=98355,98358,98361,98362
> [DLLS] Export improvements

- dll/win32/shell32/dialogs/filetypes.cpp
The delete code also needs read access.
JIRA issue: [CORE-19809](https://jira.reactos.org/browse/CORE-19809)
> [SHELL32] Fix broken delete file type verb

- ntoskrnl/ke/dpc.c
Make KeFlushQueuedDpcs SMP ready
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=98408,98419,98428,98442
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=98403,98412,98420,98444
> [NTOS:KE] Make KeFlushQueuedDpcs SMP ready

- base/applications/rapps/loaddlg.cpp
- dll/win32/framedyn/chstring.cpp
- sdk/include/c++/cwchar
- sdk/include/crt/crtdefs.h
- sdk/include/crt/string.h
- sdk/include/crt/wchar.h
Add C++ const correct overloads
> [CRT] Add C++ const correct overloads

- dll/win32/msgina/lang/pt-PT.rc
Update and improve pt-PT translation
> [MSGINA] Update Portuguese (pt-PT) translation

- base/system/diskpart/lang/tr-TR.rc
Fixed translations. 
- Some translations were false, so I fixed them. Now, they should be more understandable.
> [DISKPART] Update Turkish (tr-TR) translation

- dll/cpl/intl/lang/de-DE.rc
Updates the German translation of international control panel.
> [INTL] Update German (de-DE) translation

- drivers/network/tcpip/lwip/src/Filelists.cmake
Fix build with newer CMake versions
> [CMAKE][LWIP] Fix build with newer CMake versions

- base/applications/calc/winmain.c
JIRA report: [CORE-19745](https://jira.reactos.org/browse/CORE-19745)
> [CALC] Fix copy command when output is NaN

- sdk/include/crt/wchar.h
- sdk/include/vcruntime/_mingw.h
- sdk/include/vcruntime/eh.h
- sdk/include/vcruntime/emmintrin.h
- sdk/include/vcruntime/gcc_sal.h
- sdk/include/vcruntime/immintrin.h
- sdk/include/vcruntime/intrin.h
- sdk/include/vcruntime/isa_availability.h
- sdk/include/vcruntime/pmmintrin.h
- sdk/include/vcruntime/stdint.h
- sdk/include/vcruntime/vcruntime.h
- sdk/include/vcruntime/vcruntime_startup.h
Add more definitions to vcruntime headers. This is to be able to build the UCRT code.
> [VCRUNTIME] Add more definitions

- base/setup/lib/CMakeLists.txt
- base/setup/lib/utils/filesup.c
- base/setup/reactos/CMakeLists.txt
- base/setup/usetup/CMakeLists.txt
> [SETUPLIB] Use proper SEH instead of nasty hacks

- boot/bootdata/hivedef.inf
- dll/win32/themeui/lang/de-DE.rc
Updates German translation of Theme UI Library.
> [THEMEUI][INF] Update German (de-DE) translation

- dll/cpl/timedate/lang/de-DE.rc
Updates the German translation of Timedate Control Panel.
> [TIMEDATE] Update German (de-DE) translation

- dll/win32/browseui/shellfind/CFindFolder.cpp
Release view and browser reference.
JIRA issue: [CORE-19780](https://jira.reactos.org/projects/CORE/issues/CORE-19780)
> [BROWSEUI] FindFolder must release the view and the browser

- dll/cpl/wined3dcfg/lang/ro-RO.rc
I made some corrections and I added the missing accelerators.
> [WINED3DCFG] Update Romanian (ro-RO) translation

- base/system/userinit/lang/de-DE.rc
Updates German translation of Userinit Logon Application.
> [USERINIT] Update German (de-DE) translation

- dll/shellext/netshell/shfldr_netconnect.cpp
JIRA issue: [CORE-18750](https://jira.reactos.org/browse/CORE-18750)
> [NETSHELL] Handle DefView accelerators

- modules/rostests/apitests/user32/CopyImage.c
- win32ss/user/user32/windows/cursoricon.c
_Improve CopyImage funciton by adding fast return when HANDLE is NULL and remove previous HACK._
JIRA issue: [CORE-19806](https://jira.reactos.org/browse/CORE-19806)
[CORE-17902](https://jira.reactos.org/browse/CORE-17902)
_Test for HANDLE == NULL and set LastError and do fast return if true._
_Improve previous HACK in PR #6886 and commit d3ec7cd._
> [USER32_APTEST][USER32] CopyImage improve regression test and function.

- ntoskrnl/ke/bug.c
Fix freeze in KeBugCheckWithTf
> [NTOS:KE] Fix freeze in KeBugCheckWithTf

- dll/win32/browseui/basebarsite.cpp
- dll/win32/browseui/shellbrowser.cpp
- dll/win32/shdocvw/CNSCBand.cpp
- dll/win32/shell32/CDefView.cpp
- dll/win32/shell32/shellmenu/CMenuSite.cpp
- dll/win32/shell32/shellmenu/CMenuSite.h
Notes:
- I tried to contact katahiromz about the Release in CNSCBand but never got a response. Commenting out for now.
[CORE-19879](https://jira.reactos.org/browse/CORE-19879) [CORE-19780](https://jira.reactos.org/browse/CORE-19780)
> [SHDOCVW][BROWSEUI][SHELL32] Correctly refcount CNSCBand and Explorer File menu

- dll/win32/shell32/shlexec.cpp
Import new path handling code from Wine 10.0-rc3.
https://gitlab.winehq.org/wine/wine/-/blob/wine-10.0-rc3/dlls/shell32/shlexec.c?ref_type=tags#L631
https://gitlab.winehq.org/wine/wine/-/commit/0bad544aab9e2c9ee93bbabac0386e02c58a39c0
It uses `PathResolveW`, which was hacked in ReactOS for a while but has been implemented properly starting from 0.4.15-dev. So now it should work correctly, and we don't need to use `SearchPathW` anymore.
This fixes a heap corruption from shell32.dll when launching SpotifyXP 2.0.3 Beta and trying to login with Spotify credentials via OAuth login menthod.
JIRA issue: [CORE-14670](https://jira.reactos.org/browse/CORE-14670), [CORE-19953](https://jira.reactos.org/browse/CORE-19953)
As it's visible on the following screenshot, SpotifyXP 2.0.3 Beta is now …
> [SHELL32] SHELL_FindExecutable: import new path handling code from Wine 10.0-rc3

- dll/win32/shell32/dialogs/item_prop.cpp
JIRA issue: [CORE-19933](https://jira.reactos.org/browse/CORE-19933)
> [SHELL32] Pump COM messages while initializing propsheet from IDataObject

- ntoskrnl/include/internal/tag.h
- ntoskrnl/io/iomgr/volume.c
[NTOS:IO] IoVolumeDeviceToDosName(): Add SAL2 annotations and fix pool tag.
> [NTOS:IO] IoVolumeDeviceToDosName(): Add SAL2 annotations, fix pool tag

- base/applications/notepad/lang/tr-TR.rc
> [NOTEPAD] Update Turkish (tr-TR) translation

- base/applications/rapps/lang/tr-TR.rc
> [RAPPS] Update Turkish (tr-TR) translation

- dll/win32/shell32/lang/pt-PT.rc
Fix typos and improve Portuguese (pt-PT) translation.
Add missing accel keys and fix accel collisions.
> [SHELL32] Fix typos and improve Portuguese (pt-PT) translation. Add missing accel keys. Fix accel collisions.

- dll/cpl/access/lang/cs-CZ.rc
Updates Czech translation of ReactOS Accessibility Control Panel.
> [ACCESS] Update Czech (cs-CZ) translation

- base/system/winlogon/sas.c
- base/system/winlogon/winlogon.h
Remove startup sound hack.
JIRA issue: [CORE-13951](https://jira.reactos.org/browse/CORE-13951)
> [WINLOGON] Add WLSESSION logon timestamp

- sdk/lib/rtl/amd64/unwind.c
Improve RtlWalkFrameChain to handle user mode
> [RTL/x64] Improve RtlWalkFrameChain to handle user mode

- dll/cpl/input/lang/de-DE.rc
Updates German translation of language control panel.
> [INPUT] Update German (de-DE) translation

- sdk/include/reactos/drivers/acpi/acpi.h
Fix, sync', document.
- FACS: Reduce size by 1 char.
- FADT: Add 3 new fields.
- Update reserved fields. Use offsets.
- Improve documentation.
Addendum to 0331781 (r46610).
> [SDK:REACTOS] acpi.h: Update FACS and FADT types to ACPI v6.4

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/SHShouldShowWizards.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/reactos/undocshell.h
- Add prototype to `<undocshell.h>`.
> [SHELL32][SHELL32_APITEST][SDK] Implement SHShouldShowWizards

- dll/win32/shell32/shell32.spec
- dll/win32/shell32/shlexec.cpp
- dll/win32/shell32/stubs.cpp
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/ShellExec_RunDLL.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/reactos/undocshell.h
- Move function definitions from `stubs.cpp` into `shlexec.cpp`.
- Add prototypes to `<undocshell.h>`.
> [SHELL32][SHELL32_APITEST][SDK] Implement ShellExec_RunDLL

- sdk/lib/rtl/critical.c
Update CountOfOwnedCriticalSections in the TEB
- Useful for debugging.
- It's per thread, so it doesn't require atomic updates
- Motivation: With SMP on x64 I found a number of instances where critical sections would be left abandoned, causing lockups. From what I can tell it was exceptions inside rpcrt4, which leave the process in a blocked state. Might or might not be related to x64 / SMP.
- For real value, you still need to put checks at certain places manually, but this is not super straight forward, because there can be false positives, e.g. when a process is terminated due to an exception, where the abandoned lock is acceptable, and we have this during testing. It's difficult to 100% distinguish this from silent and very bad lock leaks. I'll try to come up with a solution that works …
> [RTL] Update CountOfOwnedCriticalSections in the TEB

- dll/win32/shell32/shlexec.cpp
Follow-up of #7588.
- Revert "shell32: Fix ShellExecute for non-filespec paths." https://gitlab.winehq.org/wine/wine/-/commit/0bad544aab9e2c9ee93bbabac0386e02c58a39c0.
- Apply "shell32: Look for the file name without extension also for the path search case." https://gitlab.winehq.org/wine/wine/-/commit/38b6640be91047b2cae71c103afed8a5b448542d.
- Clear leading/trailing whitespaces (a suggestion by @Doug-Lyons).
- Update the comment for `xlpFile` buffer definition, to match the current code behaviour.
This fixes some failures for the following tests:
- shell32_apitest:ShellExecCmdLine: 12 failures less,
- shell32_apitest:ShellExecuteEx: 5 failures less,
- shell32_winetest:shlexec: crash fixed, now 13 failures as before,
- wshom_winetest:wshom: crash fixed, now 3 failures as before.
I've …
> [SHELL32] SHELL_FindExecutable: improve path handling code

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/SHSetUnreadMailCountW.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/psdk/shellapi.h
- sdk/include/reactos/undocshell.h
- Add prototype to `<shellapi.h>`.
> [SHELL32][SHELL32_APITEST][SDK] Implement SHSetUnreadMailCountW

- base/applications/regedit/childwnd.c
Enable horizontal scroll on address bar.
JIRA issue: [CORE-19743](https://jira.reactos.org/browse/CORE-19743)
- Add `ES_AUTOHSCROLL` style to the address bar window on its creation.
> [REGEDIT] Add ES_AUTOHSCROLL to address bar

- dll/win32/shell32/droptargets/CFSDropTarget.cpp
- dll/win32/shell32/droptargets/CFSDropTarget.h
- dll/win32/shell32/folders/CDrivesFolder.cpp
- dll/win32/shell32/shldataobject.cpp
JIRA issues: [CORE-17871](https://jira.reactos.org/browse/CORE-17871), [CORE-18271](https://jira.reactos.org/browse/CORE-18271)
> [SHELL32] Allow DnD to create shortcuts across different drives

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/SHEnumerateUnreadMailAccountsW.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/psdk/shellapi.h
- sdk/include/reactos/undocshell.h
- Add prototype to `<shellapi.h>`.
> [SHELL32][SHELL32_APITEST][SDK] Implement SHEnumerateUnreadMailAccountsW

- dll/win32/shell32/stubs.cpp
- dll/win32/shell32/utils.cpp
- modules/rostests/apitests/shell32/CMakeLists.txt
- modules/rostests/apitests/shell32/StrRStr.cpp
- modules/rostests/apitests/shell32/testlist.c
- sdk/include/reactos/undocshell.h
- Move function definitions from `stubs.cpp` to `utils.cpp`.
- Add prototypes to `<undocshell.h>`.
> [SHELL32][SHELL32_APITEST][SDK] Implement StrRStrA/W

- base/applications/rapps/loaddlg.cpp
The last part of the Let's Encrypt issuer string keeps changing. Just checking everything up to that point should be enough.
> [RAPPS] Check Let's Encrypt issuer prefix instead of whole string

- ntoskrnl/ke/amd64/freeze.c
- Set ACTIVE flag on freeze owner like on Windows
- Add a nice state graph
- Change license to MIT
> [NTOS:KE/x64] Improve freeze code

- sdk/cmake/gcc.cmake
- sdk/include/ucrt/corecrt_stdio_config.h
- sdk/include/ucrt/fenv.h
Fix GCC build with UCRT headers
Preparation for importing ucrtbase_winetest
> [CMAKE][UCRT] Fix GCC build with UCRT headers

- dll/win32/shell32/dialogs/dialogs.cpp
JIRA issue: [CORE-19983](https://jira.reactos.org/browse/CORE-19983)
> [SHELL32] Don't close Run dialog on execution failure

- dll/win32/shell32/lang/fr-FR.rc
[SHELL32] Fix french translation
Change "New" by "Nouveau" 
Correct the contextual menu
> [SHELL32] Improve French (fr-FR) translation

- win32ss/user/user32/misc/exticon.c
- win32ss/user/user32/windows/cursoricon.c
_Add PNG (NT6/Vista+) support._
JIRA issue: [CORE-18385](https://jira.reactos.org/browse/CORE-18385)
_Change libpng to add IMPORTLIB libpng.spec to allow linking to it in USER32._
_Add code into mostly cursoricon.c to support PNG icons._
Before:
After:
Before:
After:
> [USER32][LIBPNG] Support PNG/Vista icons

- dll/win32/comctl32/imagelist.c
> Fix version number in reading/writing image list streams and counting pointers for mixing image & mask while reading. Works perfect on data from *.reg files exported from XP/2003.
> This is a part of managing tray icons hiding behavior.
______________________
An attempt was previously made to send this patch to WINE but this fell through as similar to our recent attempts at sending patches to wine regarding comctl32. 
Revise this PR, This is a divergence on synced code so mark it as such.
Improves behavior of vista shell with our comctl32.
From PR #619
`comctl32:listbox` gains 4 more tests and 1 more failure, while `comdlg32:filedlg` appears to be happier.
No visible changes to `comctl32:listbox` and `comdlg32:filedlg`; however, [`comctl32:buttonv6` reduces from 351 to 349 …
> [COMCTL32] Fix image list reading/writing (version number and mixing algorithm) - Revised

- dll/win32/msvcrt/msvcrt.spec
- modules/rostests/winetests/msvcrt/CMakeLists.txt
- modules/rostests/winetests/msvcrt/cpp.c
- modules/rostests/winetests/msvcrt/data.c
- modules/rostests/winetests/msvcrt/dir.c
- modules/rostests/winetests/msvcrt/environ.c
- modules/rostests/winetests/msvcrt/file.c
- modules/rostests/winetests/msvcrt/heap.c
- modules/rostests/winetests/msvcrt/locale.c
- modules/rostests/winetests/msvcrt/misc.c
- modules/rostests/winetests/msvcrt/printf.c
- modules/rostests/winetests/msvcrt/scanf.c
- modules/rostests/winetests/msvcrt/signal.c
- modules/rostests/winetests/msvcrt/string.c
- modules/rostests/winetests/msvcrt/time.c
- sdk/include/crt/math.h
- sdk/include/ndk/iotypes.h
- sdk/include/reactos/wine/test.h
- sdk/include/ucrt/corecrt_math.h
- sdk/lib/crt/stdlib/fcvtbuf.c
Sync msvcrt_winetest to wine-10.0
- ✅ WHS: https://reactos.org/testman/compare.php?ids=100407,100435
- ✅ Windows 2003 x64: https://reactos.org/testman/compare.php?ids=99600,100418
- KVM x86: https://reactos.org/testman/compare.php?ids=100473,100480
- KVM x64: https://reactos.org/testman/compare.php?ids=100475,100487
> [MSVCRT_WINETEST] Sync with wine-10.0

- dll/win32/shimgvw/CMakeLists.txt
- dll/win32/shimgvw/loader.cpp
- dll/win32/shimgvw/shimgvw.c
- dll/win32/shimgvw/shimgvw.h
- Choose an icon image based on size and color and place it first so GDI+ will pick it
- Change .cur files to .ico on the fly so GDI+ can open it
JIRA issue: [CORE-19945](https://jira.reactos.org/browse/CORE-19945)
Notes:
- This PR is not related to the ICO/PNG PR in USER32.
> [SHIMGVW] Choose a better icon image and also support .cur files

- dll/win32/riched20/CMakeLists.txt
- dll/win32/riched20/caret.c
- dll/win32/riched20/clipboard.c
- dll/win32/riched20/editor.c
- dll/win32/riched20/editor.h
- dll/win32/riched20/editstr.h
- dll/win32/riched20/list.c
- dll/win32/riched20/paint.c
- dll/win32/riched20/para.c
- dll/win32/riched20/reader.c
- dll/win32/riched20/riched20.h
- dll/win32/riched20/richole.c
- dll/win32/riched20/row.c
- dll/win32/riched20/rtf.h
- dll/win32/riched20/run.c
- dll/win32/riched20/style.c
- dll/win32/riched20/table.c
- dll/win32/riched20/txthost.c
- dll/win32/riched20/txtsrv.c
- dll/win32/riched20/undo.c
- dll/win32/riched20/wrap.c
- dll/win32/riched20/writer.c
- media/doc/WINESYNC.txt
_riched20.dll Wine sync to Wine version 6.10,_
JIRA issue: [CORE-6727](https://jira.reactos.org/browse/CORE-6727)
_Wine sync riched20 to wine version 6.10 keeping PR https://github.com/reactos/reactos/pull/6976._
_Keep cherry pick of https://gitlab.winehq.org/wine/wine/-/commit/7b2ff977739df25252d46552d2447af50c23040e._
Testbot results after commit 2.
refs/pull/7713/merge on 0.4.16-dev-736-g28b802b
KVM:  https://reactos.org/testman/compare.php?ids=100669,100678 LGTM
VBox: https://reactos.org/testman/compare.php?ids=100668,100679 LGTM
> [RICHED20] Sync to Wine-6.10

- dll/win32/shimgvw/shimgvw.c
- dll/win32/shimgvw/shimgvw.h
- dll/win32/shimgvw/util.c
JIRA issue: [CORE-20002](https://jira.reactos.org/browse/CORE-20002)
> [SHIMGVW] Only enable toolbar edit and print buttons if the shell verb exists

- dll/win32/browseui/shellfind/CSearchBar.cpp
- dll/win32/browseui/shellfind/CSearchBar.h
JIRA issue: [CORE-16424](https://jira.reactos.org/browse/CORE-16424)
> [BROWSEUI] Set find files pane focus

- boot/freeldr/freeldr/arch/realmode/amd64.S
- boot/freeldr/freeldr/arch/realmode/i386.S
- sdk/include/asm/asm.inc
- subsystems/mvdm/dos/asmxtras.inc
This:
```
#ifdef _USE_ML
.long offset MyLabel
#else
.long MyLabel
#endif
```
Can be reduced to that:
```
.long OFF(MyLabel)
```
> [ASM] Move `OFF(x)` macro from `asmxtras.inc` to `asm.inc`

- base/applications/findstr/findstr.rc
- base/applications/findstr/lang/ja-JP.rc
> [FINDSTR] Add Japanese (ja-JP) translation

- base/applications/drwtsn32/drwtsn32.rc
- base/applications/drwtsn32/lang/ja-JP.rc
> [DRWTSN32] Add Japanese (ja-JP) translation

- base/applications/mplay32/lang/ja-JP.rc
- Improve Japanese translation.
> [MPLAY32] Improve Japanese (ja-JP) translation

- base/applications/shutdown/lang/ja-JP.rc
- Improve Japanese translation.
> [SHUTDOWN] Improve Japanese (ja-JP) translation

- base/applications/mscutils/eventvwr/eventvwr.c
- Reduce lines in `InitInstance` function.
> [EVENTVWR] Reduce lines

- CODING_STYLE.md
Improve AI-friendliness.
JIRA issue: [CORE-20011](https://jira.reactos.org/browse/CORE-20011)
- Add `CODING_STYLE.md` at the root directory of this repository.
- This `CODING_STYLE.md` is generated from HTML text of https://reactos.org/wiki/Coding_Style .
> [REACTOS] Add CODING_STYLE.md

- dll/win32/browseui/addressband.cpp
- dll/win32/browseui/addressband.h
- dll/win32/browseui/internettoolbar.cpp
- dll/win32/browseui/internettoolbar.h
- dll/win32/browseui/settings.cpp
- dll/win32/browseui/shellbrowser.cpp
Must read the state from the registry every time.
JIRA issue: [CORE-20018](https://jira.reactos.org/browse/CORE-20018)
Notes:
- Also avoids a band query `FAILED_UNEXPECTEDLY` message during destruction.
> [BROWSEUI] Set AddressBand Go button checkbox state correctly in menu

- boot/freeldr/freeldr/arch/arm/debug.c
- boot/freeldr/freeldr/arch/i386/i386bug.c
- boot/freeldr/freeldr/arch/i386/i386trap.S
- boot/freeldr/freeldr/arch/uefi/uefildr.c
- boot/freeldr/freeldr/include/arch/arm/hardware.h
- boot/freeldr/freeldr/include/arch/pc/hardware.h
- boot/freeldr/freeldr/include/arch/pc/pcbios.h
- boot/freeldr/freeldr/include/debug.h
- boot/freeldr/freeldr/include/linux.h
- hal/halx86/include/halp.h
- hal/halx86/minihal/CMakeLists.txt
This patch series removes some code from the MINIHAL library that isn't used anywhere else
> [MINIHAL] Minor improvements

- base/applications/regedit/childwnd.c
- base/applications/regedit/framewnd.c
JIRA issue: [CORE-19970](https://jira.reactos.org/browse/CORE-19970)
- Fix status bar toggling.
- Improve behaviour of splitter.
- Add `(WS_CLIPCHILDREN | WS_CLIPSIBLINGS)` style to `ChildWnd`.
BEFORE:
https://github.com/user-attachments/assets/e64c5946-095e-4c04-b646-1df9c4ca74ef
AFTER:
https://github.com/user-attachments/assets/ce920995-7daf-4f1d-bf3d-1295e2658549
> [REGEDIT] Reduce flickering and fix rendering

- base/applications/dxdiag/lang/ro-RO.rc
- Fix `IDS_DDPRIMARY_DESCRIPTION` escape sequence.
> [DXDIAG] Romanian (ro-RO): Fix unrecognized escape sequence

- dll/win32/shell32/dialogs/dialogs.cpp
JIRA issue: [CORE-20030](https://jira.reactos.org/browse/CORE-20030)
> [SHELL32] Initialize COM for PickIconDlg

- configure.cmd
- configure.sh
- `[CONFIGURE.CMD] Use multi-command syntax instead of AND operator for successive echo's`
And tweak few echo'ed strings.
- `[CONFIGURE.SH] Surround the echo'ed string in quotes, and tweak some strings.`
> Tweak echoed strings in the configure scripts

- boot/freeldr/freeldr/arch/drivers/hwide.c
- boot/freeldr/freeldr/arch/drivers/hwidep.h
- boot/freeldr/freeldr/arch/i386/pc98/machpc98.c
- boot/freeldr/freeldr/arch/i386/pc98/pc98disk.c
- boot/freeldr/freeldr/arch/i386/xbox/machxbox.c
- boot/freeldr/freeldr/arch/i386/xbox/xboxdisk.c
- boot/freeldr/freeldr/include/arch/i386/machpc98.h
- boot/freeldr/freeldr/include/arch/i386/machxbox.h
- boot/freeldr/freeldr/include/hwide.h
- sdk/include/ddk/ata.h
Fix long-standing bugs, which have a negative impact on the boot stability.
- Make the driver more ATA specification compliant
- Improve the speed of device detection
- Remove inconsistent delays
- Support modern hard drives with sector size greater than 512 bytes
- Add basic error recovery
- Move private definitions to a separate private header
- Remove the useless AtaFree API method
> [FREELDR] Refactor and optimize the IDE driver

- sdk/cmake/gcc.cmake
> [SDK] Fix RelWithDebInfo

- dll/win32/setupapi/install.c
Fix `SetupInstallServicesFromInfSectionEx`.
After PR #7746 #7769 , Virtual Box Guest Addition 7.1.6 setup still fails, because of **the first point below**.
- **Call `SetupDiSetDeviceRegistryPropertyW` only if `DeviceInfoSet` is valid**
- `DeviceInfoSet` can be `INVALID_HANDLE_VALUE`, treat this as `NULL`
- Improve function declaration
---
The install progress passed after this PR, but PNP drivers installed incorrectly, this will be fixed in the following PR #7808 :
> [SETUPAPI] Fix `SetupInstallServicesFromInfSectionEx`

- .github/PULL_REQUEST_TEMPLATE.md
We should make it so new PRs automatically have KVM and KVM_x64 checkboxes so we dont have to type it out everytime.
> [GITHUB] Adjust the pullrequest template to include the buildbot testruns

- boot/freeldr/freeldr/arch/i386/hwacpi.c
- boot/freeldr/freeldr/arch/uefi/uefihw.c
- boot/freeldr/freeldr/freeldr.spec
- boot/freeldr/freeldr/include/arch/pc/hardware.h
- boot/freeldr/freeldr/include/hwacpi.h
- boot/freeldr/freeldr/include/ntldr/winldr.h
- boot/freeldr/freeldr/ntldr/winldr.c
- boot/freeldr/freeldr/ntldr/wlmemory.c
This PR Pass the Real ACPI table instead of hardcoded `(PVOID)1`.
JIRA issue: [CORE-11954](https://jira.reactos.org/browse/CORE-11954) and [CORE-18969](https://jira.reactos.org/browse/CORE-18969)
> [FREELDR] Pass the correct ACPI table for Windows

- base/setup/reactos/lang/fr-FR.rc
Update French translation of base/setup/reactos/lang
> [SETUP] Update French (fr-FR) translation

- ntoskrnl/include/internal/ke.h
- ntoskrnl/ke/thrdobj.c
- ntoskrnl/ke/thrdschd.c
Implement / fix a number of functions wrt SMP.
@DarkFire01 If you find some time, please test if that works with your x86 SMP code.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=100991,100995,100998,101001
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101000,101003,101009,101012
> [NTOS:KE] SMP stuff

- CODEOWNERS
Add myself to the codeowners.
Im going to be handling almost all wine directx imports.
> [CODEOWNERS] Add myself to codeowners for DirectX

- win32ss/gdi/gdi32/objects/font.c
Enabling font removal.
JIRA issue: [CORE-17684](https://jira.reactos.org/browse/CORE-17684)
> [GDI32] Implement RemoveFontResourceExA

- dll/win32/riched20/txthost.c
_Partial Wine Sync of txthost.c function RichEditWndProc_common._
JIRA issue: [CORE-19991](https://jira.reactos.org/browse/CORE-19991)
_Add extra parameters to 'struct host' to handle 'defer_release' and 'notify_level' and use these._
_Update and Retry of https://github.com/reactos/reactos/pull/7733._
> [RICHED20] DevCpp License 'enter' crash fix

- ntoskrnl/cc/view.c
- ntoskrnl/io/iomgr/irq.c
- ntoskrnl/ke/amd64/cpu.c
- ntoskrnl/ke/i386/cpu.c
- ntoskrnl/se/srm.c
Improve debug logs.
- And demote/promote some DPRINT()/DPRINT1().
> [NTOSKRNL] Add missing \n to DPRINT() calls

- dll/win32/shell32/dialogs/drvdefext.cpp
JIRA issue: [CORE-12314](https://jira.reactos.org/browse/CORE-12314)
> [SHELL32] Fix starting disk cleanup from drive properties

- win32ss/gdi/ntgdi/freetype.c
Bad naming slows down development.
JIRA issue: [CORE-19898](https://jira.reactos.org/browse/CORE-19898)
This PR is simply trivial renaming.
In `IntExtTextOutW` function:
- `s/SurfObj/psoDest/`
- `s/SourceGlyphSurf/psoGlyph/`
- `s/HSourceGlyph/hbmGlyph/`
- `s/bitSize/glyphSize/`
> [NTGDI:FREETYPE] IntExtTextOutW: Renaming variables

- boot/freeldr/install/install.c
Update the message in accordance with the changes in 3d516e71d3b044d2030c588f8f3172df8a7f76b3
> [FREELDR][INSTALL] Update the FreeLDR installation message in installfreeldr

- dll/win32/browseui/shellbrowser.cpp
JIRA issue: [CORE-20072](https://jira.reactos.org/browse/CORE-20072)
If always on top worked correctly, this contrived resolution change would not be possible but here we are...
> [BROWSEUI] Handle resolution change when fullscreen

- win32ss/drivers/font/ftfd/rosglue.c
On x64 malloc needs to return a 16 byte aligned buffer, the previous code used an 8 byte header, making the allocations unaligned. This is now fixed with an improved header structure.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101327,101331,101334,101341
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101328,101332,101335,101342
> [FTFD] Fix malloc/realloc/free wrappers

- drivers/storage/mountmgr/database.c
- drivers/storage/mountmgr/device.c
Fixes for some problems I ran into when exercising the reparse point code in mountmgr.
> [MOUNTMGR] Few fixes and improvements

- dll/win32/shell32/dialogs/dialogs.cpp
JIRA issue: [CORE-20125](https://jira.reactos.org/browse/CORE-20125)
> [SHELL32] Enable OK Run dialog button on combo change

- dll/cpl/access/access.c
- dll/cpl/access/mouse.c
- dll/shellext/stobject/csystray.cpp
- dll/shellext/stobject/csystray.h
- dll/shellext/stobject/hotplug.cpp
- dll/shellext/stobject/mouse.cpp
- dll/shellext/stobject/power.cpp
- dll/shellext/stobject/precomp.h
- dll/shellext/stobject/volume.cpp
- win32ss/user/ntuser/sysparams.c
> [STOBJECT][NTUSER][ACCESS] Don't use a systray timer when not needed

- base/shell/explorer/precomp.h
- base/shell/explorer/trayclock.cpp
- base/shell/explorer/trayntfy.cpp
- base/shell/explorer/trayprop.cpp
- base/shell/explorer/traywnd.cpp
> [EXPLORER] Implement NoWinKeys and HideClock restrictions

- dll/win32/comctl32/pager.c
Reverts reactos/reactos#7875.
JIRA issue: [CORE-20121](https://jira.reactos.org/browse/CORE-20121)
> Revert "[COMCTL32] Pager: Fix PGM_RECALCSIZE behaviour"

- modules/rostests/apitests/crt/crtdll_crt_apitest.cmake
- modules/rostests/apitests/crt/msvcrt_crt_apitest.cmake
- modules/rostests/apitests/crt/ntdll_crt_apitest.cmake
- modules/rostests/apitests/crt/setjmp.c
- modules/rostests/apitests/crt/static_crt_apitest.cmake
- modules/rostests/apitests/crt/testlist.c
Splitted from #7839. Improved a little.
JIRA issue: [CORE-19265](https://jira.reactos.org/browse/CORE-19265)
- Add `setjmp` testcase.
> [CRT_APITEST] Add setjmp testcase (Retry)

- base/setup/reactos/lang/ja-JP.rc
- Update `base/setup/reactos/lang/ja-JP.rc`.
> [REACTOS] Improve Japanese (ja-JP) translation

- dll/win32/netcfgx/lang/ja-JP.rc
- Update `dll/win32/netcfgx/lang/ja-JP.rc`.
> [NETCFGX] Improve Japanese (ja-JP) translation

- dll/win32/devmgr/lang/ja-JP.rc
- Update `dll/win32/devmgr/lang/ja-JP.rc`.
> [DEVMGR] Improve Japanese (ja-JP) translation

- base/applications/cmdutils/help/lang/ja-JP.rc
- Update `base/applications/cmdutils/help/lang/ja-JP.rc`.
> [HELP] Improve Japanese (ja-JP) translation

- base/applications/cmdutils/reg/lang/ja-JP.rc
- Update `base/applications/cmdutils/reg/lang/ja-JP.rc`.
> [REG] Improve Japanese (ja-JP) translation

- base/applications/cmdutils/fc/lang/ja-JP.rc
- Update `base/applications/cmdutils/fc/lang/ja-JP.rc`.
> [FC] Improve Japanese (ja-JP) translation

- base/applications/mscutils/servman/lang/ja-JP.rc
- Update `base/applications/mscutils/servman/lang/ja-JP.rc`.
> [SERVMAN] Improve Japanese (ja-JP) translation

- dll/cpl/access/lang/ja-JP.rc
- Update `dll/cpl/access/lang/ja-JP.rc`.
> [ACCESS] Improve Japanese (ja-JP) translation

- dll/cpl/access/lang/ja-JP.rc
Follow-up of #7994.
- Update `dll/cpl/access/lang/ja-JP.rc`.
> [ACCESS] Improve Japanese (ja-JP) translation Part 2

- base/shell/explorer/lang/ja-JP.rc
- Update `base/shell/explorer/lang/ja-JP.rc`.
> [EXPLORER] Improve Japanese (ja-JP) translation

- dll/cpl/access/lang/ja-JP.rc
Follow-up of #7995.
- Update `dll/cpl/access/lang/ja-JP.rc`.
> [ACCESS] Improve Japanese (ja-JP) translation Part 3

- dll/win32/browseui/shellbars/CISFBand.cpp
- dll/win32/browseui/shellbars/CISFBand.h
- Just fix indentation and formatting.
> [BROWSEUI][FORMATTING] Quick Launch: Just formatting

- win32ss/include/ntuser.h
- win32ss/user/ntuser/window.c
- win32ss/user/user32/user32.spec
- win32ss/user/user32/windows/window.c
- Set the last error.
- Check message window.
- Modify `win32ss/user/user32/user32.spec`.
> [NTUSER][USER32] Rewrite GetAncestor

- modules/rostests/kmtests/ntos_mm/MmSection.c
Fix MmSection test on Windows 2003
> [KMTEST] Fix MmSection tests

- base/applications/kbswitch/CMakeLists.txt
- base/applications/kbswitch/kbsdll/kbsdll.spec
- base/applications/kbswitch/kbswitch.c
Debug easy and develop easy.
JIRA issue: [CORE-18546](https://jira.reactos.org/browse/CORE-18546)
- Include `<wine/debug.h>`.
- Import `ntdll` and link to `wine`.
- Enable Wine debug.
> [KBSWITCH] Enable Wine debug

- modules/rostests/apitests/include/apitest.h
- modules/rostests/apitests/ntdll/NtQuerySection.c
- modules/rostests/kmtests/ntos_mm/MmSection.c
Improve ntdll_apitest:NtQuerySection and kmtest:MmSection tests.
- ntdll_apitest:NtQuerySection: Add a numer of new tests, refactor for better readability
- kmtest:MmSection : Add a few more testcases, refactor a test-macro into a function to make it debuggable
> [APITESTS] Improve section related tests

- modules/rostests/apitests/shell32/ItemIDList.cpp
> [SHELL32_APITEST] Fix control panel printers PIDL test

- dll/win32/usp10/usp10.c
_Fix notepad without word-wrap 'select all' using CTRL-A._
JIRA issues: [CORE-20176](https://jira.reactos.org/browse/CORE-20176)
[CORE-20177](https://jira.reactos.org/browse/CORE-20177)
_Cherry-pick Wine 10.8 commit https://github.com/wine-mirror/wine/commit/f998714d318e43db55329c3b4206c38bcf122366._
> [USP10] Fix notepad without word-wrap 'select all'

- dll/win32/msctf/utils.cpp
- Implement `CheckAnchorStore` function.
> [MSCTF] Implement CheckAnchorStore function

- dll/win32/shell32/shlexec.cpp
> [SHELL32] Don't assert on broken ShellExecuteEx error reporting

- dll/win32/riched20/CMakeLists.txt
- dll/win32/riched20/caret.c
- dll/win32/riched20/clipboard.c
- dll/win32/riched20/editor.c
- dll/win32/riched20/editor.h
- dll/win32/riched20/editstr.h
- dll/win32/riched20/list.c
- dll/win32/riched20/paint.c
- dll/win32/riched20/para.c
- dll/win32/riched20/precomp.h
- dll/win32/riched20/reader.c
- dll/win32/riched20/richole.c
- dll/win32/riched20/rtf.h
- dll/win32/riched20/run.c
- dll/win32/riched20/string.c
- dll/win32/riched20/style.c
- dll/win32/riched20/table.c
- dll/win32/riched20/txthost.c
- dll/win32/riched20/txtsrv.c
- dll/win32/riched20/undo.c
- dll/win32/riched20/wrap.c
- dll/win32/riched20/writer.c
- media/doc/WINESYNC.txt
- modules/rostests/winetests/riched20/CMakeLists.txt
- modules/rostests/winetests/riched20/editor.c
- modules/rostests/winetests/riched20/richole.c
- modules/rostests/winetests/riched20/txtsrv.c
- sdk/include/reactos/wine/rbtree.h
- sdk/tools/winesync/riched20.cfg
Keep wine components up to date
- Sync wine/rbtree.h to Wine-10.0 as changes in riched20 require this. Also added a define to allow directx code to compile.
- Sync riched20 to Wine-10.0 and its tests using the script.
> [RICHED20] Sync to Wine-10.0

- dll/win32/shlwapi/ordinal.c
- Implement `SHCreateShellPalette` function.
> [SHLWAPI] Implement SHCreateShellPalette

- dll/win32/shlwapi/ordinal.c
- modules/rostests/apitests/shlwapi/CMakeLists.txt
- modules/rostests/apitests/shlwapi/IsQSForward.c
- modules/rostests/apitests/shlwapi/testlist.c
- sdk/include/reactos/shlwapi_undoc.h
- Implement `IsQSForward` function.
- Modify `IsQSForward` prototype in `<shlwapi_undoc.h>`
- Add `IsQSForward` testcase to `shlwapi_apitest`.
> [SHLWAPI][SHLWAPI_APITEST][SDK] Implement IsQSForward

- dll/win32/oleaut32/usrmarshal.c
- modules/rostests/winetests/oleaut32/usrmarshal.c
Import the following Wine commits:
oleaut32: Implement `LPSAFEARRAY` user marshal interface marshaling.
https://gitlab.winehq.org/wine/wine/-/commit/a1f2b44a1bf9ecbcf772aa8509f87c2be1ccc415
oleaut32/tests: Add tests for `LPSAFEARRAY` user marshal interface marshaling.
https://gitlab.winehq.org/wine/wine/-/commit/b2574278f7ab6709b920f562bb03f23073827327
containing the implementation itself and a test for it.
This fixes:
1) improperly displayed comboboxes with OS type and version selection,
2) failure to save/load virtual machine settings in/from XML file in VirtualBox 3.0.0 - 4.0.36 versions and
3) improperly displayed comboboxes in 3DMark2001.
As a result, this also allows to create and start a virtual machine(s) in VirtualBox up to 3.0.8 version. For newer VirtualBox versions, another …
> [OLEAUT32][OLEAUT32_WINETEST] Import LPSAFEARRAY user marshal interface marshaling support from Wine

- base/system/winlogon/sas.c
Allow workstation (un)locking only if we are in the correct LogonState.
- Locking (`WLX_SAS_ACTION_LOCK_WKSTA`) is allowed only if `LogonState` is either `STATE_LOGGED_ON` or `STATE_LOGGED_ON_SAS`, i.e., either the user invokes the `user32:LockWorkStation()` API or presses Win-L, or, opens the Logged-On SAS dialog then clicks on the "Lock Workstation" button.
- Unlocking (`WLX_SAS_ACTION_UNLOCK_WKSTA`) is allowed only if `LogonState` is either `STATE_LOCKED` or `STATE_LOCKED_SAS`, i.e., the workstation is locked and we are either on the Locked- notice or on the SAS dialog that asks for the user credentials.
Additionally:
- Fix the invocation order of `LockHandler`/`UnlockHandler` notifications:
* the `LockHandler` is invoked on the Winlogon desktop, just before displaying the …
> [WINLOGON] Diverse fixes - Part 3 (Workstation locking/unlocking)

- base/applications/kbswitch/indicdll/indicdll.c
Using `WH_KEYBOARD_LL` is a last resort, virus-like behavior, which may also affect duplicate keystrokes on the virtual machine.
JIRA issue: [CORE-20234](https://jira.reactos.org/browse/CORE-20234)
Switch the keyboard switcher from a low-level (`WH_KEYBOARD_LL`) to a standard keyboard hook (`WH_KEYBOARD`), updating the hook callback and key-detection logic.
- Replace `WH_KEYBOARD_LL` hook and handler with `WH_KEYBOARD` and adapted `KeyboardProc`.
- Expand `CheckVirtualKey` to accept a generic key plus left/right variants.
- Update key-state checks to use `HIWORD(lParam)` flags and `GetKeyState`.
> [INDICDLL] Don't use WH_KEYBOARD_LL but WH_KEYBOARD

- boot/freeldr/freeldr/arch/uefi/uefidisk.c
Improve disk detection on UEFI by using `PublicBootHandle` index
JIRA issue: [CORE-11954](https://jira.reactos.org/browse/CORE-11954)
> [FREELDR] Improve disk detection on UEFI

- dll/win32/syssetup/lang/pl-PL.rc
[SYSSETUP] Update Polish (pl-PL) translation
> [SYSSETUP] Update Polish (pl-PL) translation

- win32ss/user/ntuser/menu.c
A bit clearer code. A bit faster execution.
- NtUserGetTitleBarInfo(): Add/Use early returns
Addendum to 3b4c9ded (r33657).
- NtUserTrackPopupMenuEx(): Check flags a bit earlier
Addendum to 3c35117 (0.4.16-dev-1275).
- NtUserThunkedMenuItemInfo(): Sort out code and comments
- menu.c: Move UserLeave() a bit earlier
> [NTUSER] menu.c: Tiny optimizations

- dll/win32/browseui/shellfind/CFindFolder.cpp
JIRA issue: [CORE-20256](https://jira.reactos.org/browse/CORE-20256)
> [BROWSEUI] Find files must compare the entire path when the view asks about the name

- base/applications/mscutils/eventvwr/lang/fr-FR.rc
- base/shell/cmd/lang/fr-FR.rc
- base/system/winlogon/lang/fr-FR.rc
- boot/freeldr/fdebug/lang/fr-FR.rc
- dll/cpl/inetcpl/lang/fr-FR.rc
- modules/rosapps/applications/explorer-old/explorer-fr.rc
Fix some typos in French translations.
> [TRANSLATIONS] Fix some typos in French translations

- dll/shellext/netshell/lang/fr-FR.rc
Improve fr-FR French translation.
> [NETSHELL] Improve French (fr-FR) translation

- modules/rostests/kmtests/ntos_ex/ExPools.c
Remove totally broken PoolsCorruption test. It was already disabled, but just seeing it, made me cringe. So it has to go.
> [KMTEST] Remove totally broken PoolsCorruption test

- dll/cpl/input/lang/pl-PL.rc
[INPUT] Update Polish (pl-PL) translation
> [INPUT] Update Polish (pl-PL) translation

- modules/rostests/kmtests/include/kmt_test.h
- modules/rostests/kmtests/kmtest_drv/kmtest_drv.c
- modules/rostests/kmtests/ntos_ke/KeDpc.c
- modules/rostests/kmtests/ntos_ke/KeSpinLock.c
- modules/rostests/kmtests/ntos_mm/MmMdl.c
- modules/rostests/kmtests/ntos_mm/MmReservedMapping.c
- modules/rostests/kmtests/ntos_mm/MmSection.c
- modules/rostests/kmtests/ntos_mm/ZwCreateSection.c
- modules/rostests/kmtests/ntos_mm/ZwMapViewOfSection.c
- modules/rostests/kmtests/ntos_ob/ObHandle.c
- modules/rostests/kmtests/ntos_ob/ObTypes.c
- modules/rostests/kmtests/rtl/RtlMemory.c
- modules/rostests/kmtests/rtl/RtlStack.c
Fix several kmtests in preparation for testbots with newer versions of Windows. There's still more kmtests to fix, but this fixes all the kmtests that bugchecked during my testing.
| Test               | 2003 (x86) | Vista (x86)   | Vista (x64)   | 7 (x86)       | 7 (x64)       | 8.1 (x86)     | 8.1 (x64)     | 10 (x86)      | 10 (x64)      |
| ------------------ | ---------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| KeDpc              | 0          | 30            | 30            | 30            | 30            | Bugcheck 0x0A | Bugcheck 0x0A | Bugcheck 0x0A | Bugcheck 0x0A |
| KeSpinLock         | 0          | 0             | 152           | Bugcheck 0x0A | Bugcheck 0x0A | Bugcheck 0x0A | Bugcheck …
> [KMTESTS] Fixes for 2003, Vista, 7, 8, 10 x86 and x64

- base/applications/cmdutils/taskkill/lang/pl-PL.rc
[TASKKILL] Update Polish (pl-PL) translation
>  [TASKKILL] Update Polish (pl-PL) translation

- hal/halx86/acpi/halacpi.c
Based on ACPI v1.0-v6.6 documentations at https://uefi.org/acpi/specs
Addendum to c21792d (r53831).
- Use the correct structure and fields.
> [HALX86] HalpSetupAcpiPhase0(): Fix ACPI version log

- .github/workflows/build.yml
Another extension of ARM* builds.
I "randomly" tried some directories, these succeed.
- Build 4+1 more directories.
> [GITHUB] build.yml: Build some more ARM/ARM64 modules

- base/ctf/cicero/cicbase.h
- base/ctf/msctf/CMakeLists.txt
- base/ctf/msctf/compartmentmgr.cpp
- base/ctf/msctf/context.cpp
Follow-up of #8224. Thanks @HBelusca.
- Add `cicIsNullPtr` function in Cicero `<cicbase.h>`.
- Reordering of `CMakeLists.txt` items.
- Minor refactoring.
> [CICERO][MSCTF] ITfContext: Follow-up of #8224

- dll/cpl/hotplug/lang/pl-PL.rc
[HOTPLUG] Update Polish (pl-PL) translation
> [HOTPLUG] Update Polish (pl-PL) translation

- dll/shellext/stobject/lang/pl-PL.rc
[STOBJECT] Update Polish (pl-PL) translation
> [STOBJECT] Update Polish (pl-PL) translation

- dll/shellext/netshell/lang/pl-PL.rc
[NETSHELL] Update Polish (pl-PL) translation
> [NETSHELL] Update Polish (pl-PL) translation

- base/shell/explorer/appbar.cpp
- base/shell/explorer/taskswnd.cpp
- win32ss/include/ntuser.h
- win32ss/user/ntuser/focus.c
- win32ss/user/ntuser/monitor.c
Enable `ABN_FULLSCREENAPP` notification. Fix some monitor functions.
- Improve `NtUserMonitorFromRect` and `NtUserMonitorFromWindow` functions.
- Remove `if`-statement in `OnWindowActivated` function.
- Don't check `WS_EX_TOOLWINDOW` in `IntIsWindowFullscreen` function.
- Add `IntGetMonitorFromRect` helper function to commonize some code in monitor functions.
BEFORE:
One failure.
AFTER:
Successful.
> [EXPLORER][NTUSER] Notify ABN_FULLSCREENAPP and fix monitor code

- base/system/winlogon/notify.c
AddNotificationDll(): Validate the registry retrieved DWORDs, instead of accepting any sort of value.
Furthermore, add SAL2 annotations and improve a TRACE.
> [WINLOGON] AddNotificationDll(): Validate the registry retrieved DWORDs

- sdk/lib/rtl/random.c
- sdk/lib/rtl/registry.c
Fix some RTL code to pass new ntdll_winetest instead of crashing or failure spam.
- [RTL] Fix random functions
- [RTL] Fix RtlpGetRegistryHandle
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=103382,103384,103393
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=103383,103386,103394
> [RTL] Misc fixes

- base/system/winlogon/sas.c
Per-user network connections (to shared drives...) are restored at user logon: `HandleLogon() -> RestoreAllConnections()`.
These connections should be closed only at user logoff, in `HandleLogoff()`, instead of being done inside the common logoff/shutdown thread, which is also invoked at... shutdown!
- Isolate the network connections closing inside a `CloseAllConnections()` helper (which performs the necessary user thread impersonation, and may do more in the future).
- Invoke this helper directly inside `HandleLogoff()`, and also re-enable the `IDS_CLOSINGNETWORKCONNECTIONS` message display.
> [WINLOGON] Close all the user network connections only at logoff

- ntoskrnl/include/internal/amd64/ke.h
- ntoskrnl/include/internal/i386/ke.h
- ntoskrnl/ke/i386/cpu.c
Fix X86_FEATURE_MTTR typo
- `s/X86_FEATURE_MTTR/X86_FEATURE_MTRR/`
> [NTOS:KE] Fix X86_FEATURE_MTTR typo

- base/system/winlogon/sas.c
- Move WlxShutdown() GINA notification in HandleShutdown().
Both 3rd-party modules and GINA shutdown notifications should be done just when shutdown is being started.
Addendum to commit d3b9c68d22 (r66252)
- Factor the two `DisplayStatusMessage()` calls for shutdown vs. reboot.
JIRA issue: [CORE-8322](https://jira.reactos.org/browse/CORE-8322)
> [WINLOGON] Move WlxShutdown() GINA notification in HandleShutdown()

- sdk/include/psdk/ntddndis.h
Improve header a bit.
- Add/Update 3 NDIS typedefs
> [SDK] ntddndis.h: Add/Update 3 NDIS typedefs

- dll/win32/shell32/folders/CDrivesFolder.cpp
JIRA issue: [CORE-20286](https://jira.reactos.org/browse/CORE-20286)
> [SHELL32] Computer folder sorting must handle mixed drives and regitems

- sdk/lib/rtl/amd64/dynfntbl.c
Fix dynamic function tables
- Fix offset vs address calculation
- Fix range checks accordingly
> [RTL] Fix dynamic function tables

- base/applications/cmdutils/where/lang/pl-PL.rc
- base/applications/cmdutils/where/where.rc
Added Polish translations for usage and messages in the `where` command tool.
> [WHERE] Add Polish (pl-PL) translation
