reactos/reactos

dll/win32/msvcrt20/msvcrt20.c
dll/win32/msvcrt40/msvcrt40.c

Add missing heap initialization in `DllMain` entrypoints of msvcrt20.dll and msvcrt40.dll, similarly to as it is done in msvcrt.dll (CRT). The msvcrt.dll (CRT) initialization code was updated properly during the last winesync, accordingly to the new changes, but msvcrt20.dll/msvcrt40.dll one was not. So update it too.
This fixes the crash of HOVER 1.0 game from Rapps when it tries to allocate a dynamical memory from the uninitialized heap via `malloc()` function exported from our msvcrt20.dll.
Addendum to c47506a which was part of https://github.com/reactos/reactos/pull/4990
JIRA issue: [CORE-19505](https://jira.reactos.org/browse/CORE-19505)
The HOVER 1.0 game from Rapps reported as not running anymore in the ticket, now runs correctly again after applying my changes, as visible on the …

[MSVCRT20][MSVCRT40] Fix heap initialization

---

ntoskrnl/include/internal/amd64/ke.h
ntoskrnl/ke/amd64/usercall.c
ntoskrnl/ke/amd64/usercall_asm.S

This is used in KiUserModeCallout instead of KiServiceExit2. The latter is broken, leaks non-volatile registers and will need to be modified to handle an exception frame, which we don't need/have here. It will also use sysret instead of iret and is generally simpler/faster. Eventually it would be desirable to skip the entire trap frame setup and do everything in KiCallUserMode. This requires some cleanup and special handling for user APC delivery.
- KVM x64: https://reactos.org/testman/compare.php?ids=94452,94461,94469,94477,94490

[NTOS:KE/x64] Implement KiUserCallbackExit

---

modules/rostests/apitests/kernel32/QueueUserAPC.c
ntoskrnl/ke/amd64/trap.S
ntoskrnl/ke/timerobj.c

Multiple fixes for kernel32_apitest QueueUserAPC
Please read carefully!
- Fix calculation of timer expiration (this fixes all test failures on x86 / most on x64)
- Use InterlockedIncrement for proper synchronization in the test
- Add test for multiple queued user APCs
- Fix user APC delivery on syscall exit (this fixes remeaining tests on x64)
- Remove pointless loop in KiInitiateUserApc
✅ Windows 2003 x64: https://reactos.org/testman/compare.php?ids=94438
✅ WHS: https://reactos.org/testman/compare.php?ids=94442
✅ KVM x86: https://reactos.org/testman/compare.php?ids=94429,94434,94440
✅ KVM x64: https://reactos.org/testman/compare.php?ids=94431,94432,94437,94451

[NTOS:KE] Fix kernel32_apitest QueueUserAPC

---

dll/win32/shlwapi/string.c
modules/rostests/apitests/shlwapi/CMakeLists.txt
modules/rostests/apitests/shlwapi/StrDup.c
modules/rostests/apitests/shlwapi/testlist.c

Fix wrong behavior of `shlwapi!StrDupA` and `shlwapi!StrDupW` functions.
- Return `NULL` when `lpszStr == NULL`.

[SHLWAPI][SHLWAPI_APITEST] Fix NULL behavior of StrDupA/W

---

dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDesktopFolder.h
dll/win32/shell32/precomp.h
dll/win32/shell32/utils.cpp
dll/win32/shell32/wine/pidl.c
dll/win32/shell32/wine/shellpath.c
sdk/include/psdk/shobjidl.idl
sdk/include/reactos/shlwapi_undoc.h

- Implement `SHParseDisplayName` and `CDesktopFolder::ParseDisplayName`.
- Add `CStubFolderBase`, `CShellUrlStub`, `CFileUrlStub`, `CIDListUrlStub`, and `CHttpUrlStub` helper classes.
- Add `SHGetSpecialFolderID` and `Shell_ParseSpecialFolder` helper functions.
- Add `BindCtx_ContainsObject`, `BindCtx_GetUIWindow`, `BindCtx_RegisterObjectParam`, `SHBindToObject`, `SHBindToObjectEx`, `SHCoInitializeAnyApartment`, `SHGetAttributes`, `SHGetNameAndFlagsW`, `SHIsFileSysBindCtx`, `SHSkipJunctionBinding`, `Shell_DisplayNameOf`, and `Shell_FailForceReturn` helper functions.
- Modify CSIDL data. 
BEFORE:
52 failures in 144 tests.
AFTER:
40 failures in 180 tests. This PR reduced 12 failures. LGTM.

[SHELL32][SDK] Fix ParseDisplayName Part 1

---

drivers/filesystems/udfs/udffs.h

This is not just wrong, it is criminal.
- KVM x86: https://reactos.org/testman/compare.php?ids=94474,94480,94482,94486
- KVM x64: https://reactos.org/testman/compare.php?ids=94461,94469,94483,94488

[UDFS] Remove packing around include of ntifs.h

---

dll/win32/devmgr/precomp.h
dll/win32/devmgr/properties/hwpage.cpp

This replaces the usage of FIELD_OFFSET for dynamic indexing into array fields.
Sadly GCC has broken __builtin_offsetof and they don't seem to intend to fix it.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95942
I'm open for suggestions to put this into a global header, I just wasn't sure where to put it.

[DEVMGR] Add DYNAMIC_FIELD_OFFSET macro

---

dll/win32/shell32/CShellDispatch.cpp
sdk/include/reactos/shellutils.h

Complete:
- AddToRecent
- Open, Explore
- MinimizeAll, UndoMinimizeALL, CascadeWindows, TileVertically, TileHorizontally, ToggleDesktop
- FindFiles, FindComputer
- FileRun
- ControlPanelItem
- SetTime
- ServiceStart, ServiceStop, CanStartStopService
- Help
- TrayProperties
- IsRestricted
- Windows
- WindowsSecurity
Partial:
- GetSystemInformation (Just the easy ones)
- GetSetting (The relevant ones)
Other:
- BrowseForFolder: RootFolder parameter
----
Most of these newly implemented features are hard to test because they just tell Explorer to open a window or execute a command.
The Service methods and GetSystemInformation/GetSetting are possible to test. I don't know if the WSH support is all there yet to do that or if it has to be done in C++.

[SHELL32] Implement several ShellDispatch methods

---

dll/win32/wdmaud.drv/legacy.c
drivers/ksfilter/ks/connectivity.c
sdk/lib/drivers/sound/mmixer/wave.c

Fix opening audio device error when trying to open it with `WAVE_FORMAT_EXTENSIBLE` format tag set in `wFormatTag` member of `WAVEFORMATEX` by the proper passing additional audio data size and removing a `WAVE_FORMAT_PCM` limitation check, both for Legacy and MMixer APIs.
This fixes audio playback in several apps those are using extensible audio data (e. g. AIMP 5.30 (**needs to manually set BPS to 16 in settings still!**), QMMP 0.12.17, all Chrome/Chromium based browsers, GameDevTycoon Demo game etc.).
Supersedes #3981.
Can be tested in pair with #6682 for better effect (**is merged now**).
JIRA issue: [CORE-10907](https://jira.reactos.org/browse/CORE-10907), [CORE-14783](https://jira.reactos.org/browse/CORE-14783), **other audio issues might also be fixed, they need to be retested too …

[AUDIO] Implement support for WAVE_FORMAT_EXTENSIBLE audio format

---

dll/win32/comdlg32/lang/cdlg_Sq.rc

They do look weird/wrong and no other rcs do have them.
Builds fine with GCC8.4.0dbg x86 here locally,
let's see what the bots and the reviewers think about that.
I do have no clue, why they were added here historically.

[COMDLG32] cdlg_Sq.rc: Strip 2 includes

---

dll/win32/shell32/wine/shellord.c
modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/GUIDFromString.cpp
modules/rostests/apitests/shell32/testlist.c
sdk/include/reactos/undocshell.h

- Add `GUIDFromString` testcase.
- Implement `GUIDFromStringA` function.
- Add NULL check to `GUIDFromStringW`.
- Add `GUIDFromStringA` prototype.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.
Some failures.
Successful.

[SHELL32][SHELL32_APITEST][SDK] Implement GUIDFromStringA

---

win32ss/user/ntuser/cursoricon.c

_I_Kill_Bugs patch to fix extra mouse moves generated when clicking._
JIRA issues: [CORE-8394](https://jira.reactos.org/browse/CORE-8394)
and the following:
[CORE-19423](https://jira.reactos.org/browse/CORE-19423)
[CORE-19422](https://jira.reactos.org/browse/CORE-19422)
[CORE-18529](https://jira.reactos.org/browse/CORE-18529)
_Add check so that mouse moves are not generated unless there is a changed in the mouse x or y position._

[NTUSER] Avoid sending superfluous WM_MOUSEMOVE messages

---

dll/shellext/shellbtrfs/recv.cpp

Make it build with newer mingw-w64 headers.

[SHELLBTRFS] Prevent redeclaration of __cpuidex with newer mingw-w64 headers

---

dll/ntdll/CMakeLists.txt
dll/ntdll/def/ntdll.spec
dll/win32/advapi32/advapi32.spec
modules/rostests/apitests/advapi32/CMakeLists.txt
modules/rostests/apitests/advapi32/Hash.c
modules/rostests/apitests/advapi32/testlist.c
sdk/lib/cryptlib/md4.c
sdk/lib/cryptlib/md5.c
sdk/lib/cryptlib/sha1.c
sdk/lib/cryptlib/sha1.h

Add hash API exports for NT6+ with fixes
- For NT6.0+, NTDLL exports those hash APIs that ADVAPI32 thunks forward to
- Fix undocumented context structure layout and content
- Add apitests to verify both of hash result and structure content
New added apitest proves that the existing context structure layout or content different from Windows:
-  `A_SHA_CTX` structure layout is different (fixed in this PR)
-  Temporary 64-byte buffer in `(A_SHA/MD4/MD5)_CTX` didn't zeroed by `(A_SHA/MD4/MD5)Final` (fixed in this PR)
- `Count` field in `MD(4/5)_CTX` content is different after `MD(4/5)Final` (not fixed in this PR)
Apitest on Win2k3 32-bit and Win11 64-bit, 0/25 no failure:
Apitest on ReactOS before, 10/25 failures:
Apitest on ReactOS after, 3/25 failures, due to the unhandled …

[NTDLL][ADVAPI32][ADVAPI32_APITEST][CRYPTLIB] Add hash API exports for NT6+ and apitests with small fixes

---

dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CFSFolder.h
dll/win32/shell32/precomp.h
dll/win32/shell32/shfldr.h
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/utils.cpp

Follow-up to #6721. Reduce `SHParseDisplayName` failures.
- Re-implement `CFSFolder::ParseDisplayName` method to validate the names.
- Add `CFSFolder::_ParseSimple`, `CFSFolder::_GetFindDataFromName`, and `CFSFolder::_CreateIDListFromName` helper methods.
- Add `PathIsDotOrDotDotW`, `PathIsValidElement`, `PathIsDosDevice`, and `SHILAppend` helper functions.
- Delete `GetNextElementW` and add `Shell_NextElement` function.
BEFORE:
40 failures.
AFTER:
17 failures. This PR reduced 23 failures.

[SHELL32] Fix ParseDisplayName Part 2

---

dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDesktopFolder.h

Follow-up to #6721. This PR can reduce 1KB of binary size.
- Delete `CStubFolderBase` and derived classes.　
- Add `CDesktopFolder::_ParseDisplayNameByParent` method.
- Don't use excessive `IShellFolder` objects in parsing display names.
- Simplify and reduce code.
BEFORE:
AFTER:
No change.

[SHELL32] Refactor and simplify CDesktopFolder

---

sdk/lib/rtl/amd64/except_asm.S
sdk/lib/rtl/amd64/unwind.c

Code is inspired by wine code. It's not entirely correct yet and will probably fail on recursive c++ exceptions, but it fixes basic c++ exception handling.
✅ MSVC_x64 on Test KVM_x64: https://reactos.org/testman/compare.php?ids=94601,94605,94609,94623,94628

[RTL/x64] Handle STATUS_UNWIND_CONSOLIDATE in RtlRestoreContext

---

sdk/include/ndk/amd64/ketypes.h

Remove useless packing that could result in unaligned fields.
✅  KVM x64: https://reactos.org/testman/compare.php?ids=94623,94630,94638,94641

[NDK/x64] Remove #pragma pack(push,4) around KPRCB/KPCR

---

media/doc/3rd Party Files.txt

Documentation.
Note:
Upstream (code) reads:
`win_iconv is placed in the public domain.`
- Add explicit license

[DOC] 3rd Party Files.txt: Complete 'win-iconv'

---

dll/win32/shell32/CDefaultContextMenu.cpp

This prevents an issue where clicking on most of the icons on the desktop that isn't the file explorer causes explorer to throw an exception, and also prevents another issue where most applications won't launch from the start menu; at least on MSVC builds running on VirtualBox 5.2.44.
- Initialize `MenuItemInfoW` struct in `CDefaultContextMenu::AddStaticContextMenusToMenu`

[SHELL32] Initialize MenuItemInfoW struct in AddStaticContextMenusToMenu

---

sdk/lib/rtl/amd64/except.c
sdk/lib/rtl/amd64/except_asm.S

This fixes invalid contexts being passed to RtlDispatchException. Also update the ExceptionAddress field in the EXCEPTION_FRAME, to match the Rip value in the CONTEXT, which is required for proper unwinding.
- KVM x64: https://reactos.org/testman/compare.php?ids=94623,94630,94638,94644,94666

[RTL/x64] Implement RtlRaiseException in asm

---

hal/halx86/apic/apictrap.S
ntoskrnl/ke/amd64/context.c
ntoskrnl/ke/amd64/trap.S
sdk/include/asm/trapamd64.inc

Fix / improve register handling on traps / syscalls.
- Fix handling of non-volatiles in trap vs exception frame
- Clean up EnterTrap/ExitTrap
- Use movaps instead of movdqa
✅ KVM x64: https://reactos.org/testman/compare.php?ids=94655,94659,94663,94672

[NTOS:KE/x64] Fix/improve register handling on traps / syscalls

---

dll/win32/shell32/folders/CRegFolder.cpp

Follow-up to #6740. Reduce `SHParseDisplayName` failures.
- Add `CRegFolder::_IsInNameSpace` helper method.
- Half-implement `CRegFolder::ParseDisplayName` method.
- Parse class string by using `GUIDFromStringW` function.
- Return `CO_E_CLASSSTRING` for invalid `CLSID` string.
BEFORE:
17 failures.
AFTER:
7 failures. This PR reduced 10 failures.

[SHELL32] Fix ParseDisplayName Part 3

---

dll/win32/shell32/folders/CDrivesFolder.cpp

Follow-up to #6746. Reduce `SHParseDisplayName` failures.
- Re-implement `CDrivesFolder::ParseDisplayName` method.
BEFORE:
17 failures.
AFTER:
14 failures. This PR reduced 3 failures.

[SHELL32] Fix ParseDisplayName Part 4

---

base/shell/explorer/tbsite.cpp

Allow the ReactOS explorer to run on Windows Server 2003 without failing an ATL debug assertion.
JIRA issue: [CORE-18807](https://jira.reactos.org/browse/CORE-18807)
- Ensure the band ID is not 0 before trying to get the band object in the `HasTaskBand()` function in the `CTrayBandSite` class.

[EXPLORER] Fix assertion when running on Windows Server 2003

---

dll/win32/browseui/parsecmdline.cpp

JIRA issue: [CORE-16939](https://jira.reactos.org/browse/CORE-16939)
- Remove excessive `(!pInfo->pidlPath)` check in `SHExplorerParseCmdLine` function.
BEFORE:
Cannot open the special folder.
AFTER:
Able to open the special folder.
BEFORE:
63 failures.
AFTER:
61 failures. This PR reduced 2 failures.

[BROWSEUI] SHExplorerParseCmdLine: Fix parsing of /root

---

sdk/include/crt/crtdefs.h

This prevents a redefinition error, when host headers are included when compiling c++ code.

[CRT] crtdefs.h: Wrap localeinfo_struct in ifdef

---

base/applications/regedit/childwnd.c

JIRA issue: [CORE-19516](https://jira.reactos.org/browse/CORE-19516)
- Add `ClampSplitBarX` helper function to delete duplicated code.
- Use a signed value in `WM_LBUTTONUP` handling.
- Use `ClampSplitBarX` in `ResizeWnd` function, `WM_LBUTTONDOWN`, `WM_MOUSEMOVE`, and `WM_LBUTTONUP` handling.
https://github.com/reactos/reactos/assets/2107452/d10a53ad-233e-44de-b41e-fec27e57e624

[REGEDIT] Correctly limit splitter's X coordinates

---

modules/rosapps/lib/vfdlib/CMakeLists.txt

To workaround github actions.
After a back and fourth investigation I've just decided to disable pdb generation for this ROSAPP for now.
We tried taking the code apart a bit and only building parts but alas it didnt yield any sucess.
disabling the AV also didn't help.
For documentation purposes:
https://chat.reactos.org/reactos/pl/akm3mj9yhbdtdgiie3onpn9uzh

[VFDLIB] Disable PDB generation for VFD.dll

---

win32ss/CMakeLists.txt
win32ss/gdi/eng/pdevobj.c

Introduce NATIVE_REACTX and hide some native directx calls behind it 
The code itself isn't wrong but we're entirely missing the logic needed to make it work. This leads to spontaneous crashes with video drivers and various unity games.
JIRA issue: [CORE-19142](https://jira.reactos.org/browse/CORE-19142)
[TESTS_KVM](https://reactos.org/testman/compare.php?ids=94755)

[WIN32SS] Introduce the NATIVE_REACTX define and disable some Dx calls

---

boot/freeldr/freeldr/bootmgr.c
boot/freeldr/freeldr/ntldr/arch/amd64/winldr.c
boot/freeldr/freeldr/ntldr/arch/arm/winldr.c
boot/freeldr/freeldr/ntldr/arch/i386/winldr.c
boot/freeldr/freeldr/ntldr/winldr.c
boot/freeldr/freeldr/ntldr/winldr.h
boot/freeldr/freeldr/ntldr/wlmemory.c
sdk/lib/cmlib/cmlib.h

PR [1905](https://github.com/reactos/reactos/pull/1905) grew very much out of date and the author has expressed that he doesn't wish to continue it. 
Many of the changes in this PR have slowly slept into master or have had an alternative PR for the same functionality. This brings the rest of the changes in. 
HOWEVER; Since freeloader now uses cmlib in a far more clean way we now assert on BIG_KEYS when we used to ignore them. In order to boot vista this assert needs to be disabled, or big keys implemented. A commit to ignore the assert is added in this PR for testing but will be removed before merge :)
- use the correct GDT entry when booting vista
- add the WindowsVista boot type
- Map first page of memory

[FREELDR] Allow FreeLoader to boot Vista - Revised

---

sdk/lib/cmlib/cmlib.h

I should have booted this before i merged the DbgPrint change oops.

[SDK] Don't just infinitely spam the DbgPrint in the bootloader

---

boot/freeldr/FREELDR.INI
boot/freeldr/freeldr/bootmgr.c
boot/freeldr/freeldr/custom.c
boot/freeldr/freeldr/include/custom.h
boot/freeldr/freeldr/include/freeldr.h
boot/freeldr/freeldr/include/miscboot.h
boot/freeldr/freeldr/include/ver.h
boot/freeldr/freeldr/miscboot.c

Merge boot-drive and partition functionalities together.
And deprecate corresponding boot types "Drive" and "Partition". These are replaced by the more general "BootSector" boot type.
Finish the unification of the code, started in commit ff85aa0c3, that loads and boots disk MBR, partition VBR or boot sector in file.
A "WarnDeprecated()" helper is added to warn the user about the deprecated features, and to inform them to adjust their FREELDR.INI file in accordance.
_**NOTE: Another functionality: the separate "BootDrive" and "BootPartition" values, will be deprecated as well in a subsequent PR. They will be replaced by the (already existing) "BootPath" value, which will be made aware of the syntax used in the old values, for example: `hd0,1`**_

[FREELDR] Merge boot-drive and partition functionalities together

---

dll/win32/shell32/CDefaultContextMenu.cpp

Code cleanup.
New init obsoletes old one(s).
Addendum to 6146fd0 (r54688) and 99b2e3d (r54979).
- Remove 2 redundant initializations

[SHELL32] Remove 2 redundant initializations

---

dll/win32/shell32/changenotify.cpp

- Add `Shell_ParsePrinterName` helper function.
- Implement `SHCNF_DWORD`, `SHCNF_PRINTERA`, and `SHCNF_PRINTERW` types of `SHChangeNotify` function.

[SHELL32] SHChangeNotify: SHCNF_DWORD and SHCNF_PRINTERA/W

---

win32ss/user/ntuser/cursoricon.c

Clarify/optimize code.
Addendum to 76290a6 (0.4.15-dev-7889).
- Use an early return

[NTUSER] UserSetCursorPos(): Use an early return

---

sdk/lib/evtlib/evtlib.c

The size is 32bit, don't read a SIZE_T. Fixes crashes of advapi32_winetest eventlog on x64.
✅ KVM x86: https://reactos.org/testman/compare.php?ids=94840,94846,94851,94858
✅ KVM x64: https://reactos.org/testman/compare.php?ids=94842,94843,94853,94864

[EVTLIB] Fix size of event log record

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp

- Add `WM_DEVICECHANGE` message handler in the shell window to detect `DBT_DEVICEARRIVAL` and `DBT_DEVICEREMOVECOMPLETE`.
- Use `GetLogicalDrives` function to detect drives.
- Use `SHChangeNotify` to send `SHCNE_DRIVEADD` and `SHCNE_DRIVEREMOVED` notifications.
- Modify `CDefView::OnChangeNotify`.

[SHELL32] SHChangeNotify: Add drive, remove drive

---

ntoskrnl/include/internal/amd64/intrin_i.h
ntoskrnl/include/internal/amd64/ke.h
ntoskrnl/include/internal/kd64.h
ntoskrnl/include/internal/ke.h
ntoskrnl/kd64/kdapi.c
ntoskrnl/kd64/kddata.c
ntoskrnl/kd64/kdinit.c
ntoskrnl/ke/amd64/cpu.c
ntoskrnl/ke/amd64/freeze.c
ntoskrnl/ke/amd64/trap.S
ntoskrnl/ke/amd64/traphandler.c
ntoskrnl/ke/bug.c
ntoskrnl/ke/freeze.c
ntoskrnl/ke/i386/freeze.c
ntoskrnl/ntos.cmake
sdk/include/ndk/amd64/ketypes.h

This PR implements the code to freeze processors and switch them in WinDbg. It is currently implemented as x64 specific code, but we might share it later with x86 (which on Windows works differently, using normal IPIs instead of NMIs, but there should be no reason to use the NMI based method on x86, too, which has some advantages).
Should be reviewed by commit.
- [NTOS:KE/x64] Add KiNmiInterruptHandler
- [NTOS:KE] Improve freeze code in KeBugCheckWithTf
- [NTOS:KE/x64] Implement KiSaveProcessorState / KiRestoreProcessorState
- [NTOS:KE/x64] Implement processor freeze code
- [NTOS:KE/x64] Implement Kd processor switching
✅ KVM x64: https://reactos.org/testman/compare.php?ids=94853,94869,94882,94889

[NTOS:KE/KD64] Implement x64 freeze and processor switch code

---

modules/rostests/apitests/shell32/SHChangeNotify.cpp
modules/rostests/apitests/shell32/ShellExecCmdLine.cpp
modules/rostests/apitests/shell32/shell32_apitest_sub.cpp
modules/rostests/apitests/shell32/shell32_apitest_sub.h

Make the testcase more stable and faster. Reduce code.
- Use `WM_COPYDATA` message to communicate with `shell32_apitest_sub.exe`.
- Use concept of "stage" and "step".
- Do multiple checks in one step.
- Flush notification by using `(SHCNF_FLUSH | SHCNF_FLUSHNOWAIT)` flags.
WinXP:
Successful. Double checked. About 25 seconds.
Win2k3:
Successful. Double checked. About 25 seconds.
Win10 x64:
Successful. Double checked. About 25 seconds.

[SHELL32_APITEST] Make SHChangeNotify testcase more stable

---

sdk/include/reactos/libs/sound/mmebuddy.h
sdk/lib/drivers/sound/mmebuddy/readme.txt
sdk/lib/drivers/sound/mmebuddy/wave/streaming.c

Fix playing wave header multiple times in case the caller requests to do it. In Windows, it is supported by `WHDR_BEGINLOOP` and `WHDR_ENDLOOP` flags (specified together) and `dwLoops` member of `WAVEHDR` structure (ususally set to `0xFFFFFFFF` (`INFINITE` constant)).
This fixes the playback in the apps those request looped wave playback of some audio data (e. g., BRD Demo app, which did play its sound only first 500 ms before, now it plays endlessly until closing it manually). 
JIRA issue: [CORE-10118](https://jira.reactos.org/browse/CORE-10118)
- Check whenther `WHDR_BEGINLOOP | WHDR_ENDLOOP` flags are set by the caller.
- If they are, get the amount of times to play the header from `WAVEHDR.dwLoops`.
- Perform wave header competion only when the loop count is equal to zero. Otherwise, …

[MMEBUDDY] Implement support for looped wave playback

---

modules/rostests/apitests/shell32/SHChangeNotify.cpp
modules/rostests/apitests/shell32/shell32_apitest_sub.cpp
modules/rostests/apitests/shell32/shell32_apitest_sub.h

Improve coverity and speed.
- Move `NUM_STAGE` to the header file.
- Add stages.
- Add `DIRTYPE_DESKTOP_DIR` and `DIRTYPE_PRINTERS` directory types.
- Improve speed more.
WinXP:
Successful. Double checked. 0.7 seconds.
Win2k3:
Successful. Double checked. 1 second.
Win10 x64:
Successful. Double checked. 3.9 seconds.
Successful. Double checked. 2.7 seconds.

[SHELL32_APITEST] SHChangeNotify: Improve coverity

---

dll/win32/shell32/shelldesktop/CChangeNotifyServer.cpp
dll/win32/shell32/shelldesktop/CDirectoryList.cpp
dll/win32/shell32/shelldesktop/CDirectoryList.h
dll/win32/shell32/shelldesktop/CDirectoryWatcher.cpp

Optimize for speed and memory.
`CDirectoryList` class exists just for remembering which file item is a directory or not, in order to notify the filesystem item changes. This information can become a tree data structure.
- Add `CFSPathIterator` and `CFSNode` helper classes. `CFSNode` is a class for tree nodes.
- Re-implement `CDirectoryList` class by using tree nodes.
- Delete `CDirectoryItem` class.
AFTER:
Successful. 0.6 seconds.

[SHELL32] SHChangeNotify: Use tree for CDirectoryList

---

dll/win32/shell32/shelldesktop/CDirectoryList.cpp
dll/win32/shell32/shelldesktop/CDirectoryList.h
dll/win32/shell32/shelldesktop/CDirectoryWatcher.cpp

Reverts reactos/reactos#6784 that was a guilty commit of CORE-19531 that causing performance regression. 
JIRA issue: [CORE-19531](https://jira.reactos.org/browse/CORE-19531)

Revert "[SHELL32] SHChangeNotify: Use tree for CDirectoryList"

---

modules/rostests/apitests/kernel32/CMakeLists.txt
modules/rostests/apitests/kernel32/LCMapString.c
modules/rostests/apitests/kernel32/testlist.c

@tkreuzer said he wants `LCMapString` testcase in chat.
- Add `LCMapString` testcase.
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.

[KERNEL32_APITEST] Add LCMapString testcase

---

base/applications/taskmgr/procpage.c

If Explorer shell is not available, use ReactOS's alternative file browser instead.
Also improve readability of command line string formatting code.
ReactOS:
ReactOS TaskMgr+FileBrowser on Win2k3:

[TASKMGR] Process page: Allow using "Open File Location" functionality without running Explorer shell

---

sdk/include/crt/process.h

Add _Exit to process.h
This is already done this way in our stdlib.h. It is needed by GCC 13 C++ headers. The problem happens like this:
- telnet/precomp.h includes fstream from GCC
- fstream includes pthread.h from GCC
- pthread.h includes process.h from ReactOS
- process.h defines _CRT_TERMINATE_DEFINED, but doesn't declare _Exit
- fstream includes cstdlib from GCC
- cstdlib includes stdlib.h from GCC (#include_next)
- stdlib.h doesn't declare _Exit, because _CRT_TERMINATE_DEFINED is defined
- cstdlib uses _Exit

[CRT] Add _Exit

---

dll/win32/shell32/wine/control.c
dll/win32/syssetup/wizard.c

This pull request makes `Control_RunDLLW` pass all but one tests from rostests (the one test that fails is the first one, but it only fails if the path to the test program contains a space). It also hopefully fixes [CORE-8981](https://jira.reactos.org/browse/CORE-8981).
- Rework string parsing in the `Control_DoLaunch` routine
- Do not send the `CPL_STARTWPARMSW` message, if no extra parameters were specified (fixes the failing  `Got NULL lParam2!` and some `CPL_STARTWPARMSW: expected -1 got %d` tests)
- Do not resolve invalid dialog names to index zero, unless the name is empty (fixes some of the failing `CPL_DBLCLK: expected -1 got %d` tests)
- Handle quotes in the second part of `wszCmd`
The PR seems to fix [CORE-8981](https://jira.reactos.org/browse/CORE-8981). 
However, …

[SHELL32] Fix Control_RunDLLW

---

sdk/lib/crt/except/amd64/chkstk_ms.s
sdk/lib/crt/msvcrtex.cmake

Only include _CrtDbgReport*, if we don't already export them
Fixes duplcate symbol warning.

[MSVCRTEX] Only include _CrtDbgReport*, if we don't already export them

---

dll/win32/comctl32/header.c

- Fix COMCTL32 headers from being garbage text when resizing while drawn off screen.
JIRA issue: [CORE-19404](https://jira.reactos.org/browse/CORE-19404)
- Invalidate header item rect before scrolling to prevent the divider from being redrawn over and over.
- Invalidate header item text through adding flag SW_INVALIDATE to ScrollWindowEx call to prevent the text from being redrawn over and over.
Before:
After:

[COMCTL32] Fix header redraw glitches when resizing

---

modules/rostests/apitests/ntdll/NtAdjustPrivilegesToken.c
modules/rostests/apitests/ntdll/NtFilterToken.c
modules/rostests/apitests/ntdll/precomp.h

Trivial code cleanup, use `RtlConvertUlongToLuid`.

[NTDLL_APITEST] Use `RtlConvertUlongToLuid`

---

win32ss/user/user32/windows/cursoricon.c

_Fix Wordpad's Open and SaveAs dialog toolbar icon displays on MSVC builds._
JIRA issue: [CORE-17005](https://jira.reactos.org/browse/CORE-17005)
_Modify USER32 to account for differences in Resource Bitmaps between GCC and MSVC builds._
Before:
After:

[USER32] Fix resource display of MSVC BI_BITFIELD 32-bit bitmaps.

---

ntoskrnl/io/iomgr/iofunc.c

ExAllocatePoolWithTag doesn't raise an exception on failure, only ExAllocatePoolWithQuotaTag does.
Bug was introduced in 2006 by @ionescu007: 1c28eb66f45d17712b80f86b27e2d2531a43f5bc
- Use ExAllocatePoolWithQuotaTag where needed
- Handle quota for a user provided size in NtQueryDirectoryFile

[NTOS:IO] Fix broken pool allocations

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefaultContextMenu.cpp

The caller of IContextMenu::QueryContextMenu must set these flags when needed, not CDefaultContextMenu.
Notes:
- CMF_CANRENAME is always set by DefView because it always supports rename in its current form. CDefaultContextMenu verifies that SFGAO_CANRENAME is also set on the items. All other callers are expected to not know how to rename unless they also set CMF_CANRENAME. This fixes the bug that the Rename item is present in the TreeView context menu even though the TreeView in ROS Explorer does not handle renaming.
- While DefView now tries to set CMF_EXPLORE correctly, the flag is never actually set because BROWSEUI does not handle FCW_TREE yet.
- This PR also fixes the bug where the File menu is missing the menu items when there is no selection.

[SHELL32] DefView must set CMF_EXTENDEDVERBS, CMF_CANRENAME and CMF_EXPLORE

---

modules/rostests/apitests/ntdll/NtQueryInformationFile.c
modules/rostests/kmtests/ntos_io/IoFilesystem.c

Add tests for FileEndOfFileInformation
✅ Test WHS: https://reactos.org/testman/compare.php?ids=94854,94862
✅ Test Windows 2003 x64: https://reactos.org/testman/compare.php?ids=94850,94863
✅ Test KVM x86: https://reactos.org/testman/compare.php?ids=95077,95079,95086,95093
✅ Test KVM x64: https://reactos.org/testman/compare.php?ids=95096,95104

[NTDLL_APITEST][KMTEST] Add tests for FileEndOfFileInformation

---

ntoskrnl/cc/view.c

_Put back remove locks and reacquire locks around MmPageOutPhysicalAdress._
JIRA issue: maybe somewhat related to CORE17624, but reactosfanboy doesn't want the important commits of that to be spammed with it. Therefore only mentioned here in the text.
_The original code for CcRosTrimCache had this code._
_The committed PR mistakenly had a patch removing these unlock and reacquire locks_
_This was my mistake._
_This PR puts them back in place._
Revision Note: I added an ASSERT(FALSE) and a DPRINT1 into the main code path here and tested this.
During all of my testing on the items below, I was never able to trigger the ASSERT or get the DPRINT1 message.
1) I ran the large file copy test on 512 K memory as in https://jira.reactos.org/browse/CORE-17624.
2) I ran a full ReactOS regression test …

[NTOS:CC] Restore unlock/reacquire locks around MmPageOutPhysicalAddress

---

dll/win32/msvcrt/msvcrt.spec
sdk/lib/crt/msvcrtex.cmake
sdk/lib/crt/wstring/mbrtowc.c
sdk/lib/crt/wstring/wcrtomb.c
sdk/lib/crt/wstring/wstring.cmake

Import wcrtomb and mbrtowc from wine
These are needed when compiling with GCC 13.

[CRT] Import wcrtomb and mbrtowc from wine

---

dll/win32/shell32/CShellLink.cpp
modules/rosapps/lib/vfdlib/vfdshmenu.cpp

Older NT versions had a smaller CMINVOKECOMMANDINFOEX struct. Places where 3rd-party code passes in the struct needs to accept the small size.

[SHELL32][VFDLIB] Handle size check of CMINVOKECOMMANDINFOEX correctly

---

win32ss/user/ntuser/window.c

Patch by @I_Kill_Bugs.
_Fix SetParent which fixes rendering issues in PeaZip._
JIRA issue: [CORE-9386](https://jira.reactos.org/browse/CORE-9386)
_According to @I_Kill_Bugs we have the following:_
> _In Windows, using SetParent to set to the same parent causes the child window to move to the top of the z-order._
> _PeaZip was calling SetParent after each window creation trying to move the window to the top z-order,_
> _but ReactOS/SetParent was preventing that. Removing the test for equality of same parent hwnd solved the problem._

[NTUSER] Fix co_IntSetParent when calling on itself

---

sdk/include/reactos/shellutils.h

ReleaseCComPtrExpectZero currently always prints the same line from shellutils.h in the warning which is not very useful. A macro is required for __FILE__ to be correct.

[SDK] ReleaseCComPtrExpectZero should print the relevant file:line

---

dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CFSFolder.h

When IShellFolder::ParseDisplayName is asked to parse multiple path elements, the IFileSystemBindData (if any) only applies to the last item. The other elements are always folders.
```C
// Test
struct CStackScopeFileSysBindData : IFileSystemBindData {
WIN32_FIND_DATAW m_wfd;
IFACEMETHODIMP QueryInterface(REFIID riid, void **ppv)
{
if (riid == IID_IUnknown || riid == IID_IFileSystemBindData) return (*ppv = static_cast<IFileSystemBindData *>(this), AddRef(), S_OK);
return (*ppv = NULL, E_NOINTERFACE);
}
IFACEMETHODIMP_(ULONG) AddRef() { return 2; } IFACEMETHODIMP_(ULONG) Release() { return 1; }
IFACEMETHODIMP SetFindData(const WIN32_FIND_DATAW *pfd) { m_wfd = *pfd; return S_OK; }
IFACEMETHODIMP GetFindData(WIN32_FIND_DATAW *pfd) { *pfd = m_wfd; return S_OK; }
};
OleInitialize(0); …
```

[SHELL32] CFSFolder parsing must only apply bind data to the last item

---

dll/shellext/zipfldr/CZipFolder.hpp

ZipFldr responds incorrectly to DFM_INVOKECOMMANDEX. This was not a problem until [now](https://github.com/reactos/reactos/pull/6765) because CDefaultContextMenu does not send it.
There are 4 possible ways to respond to DFM_INVOKECOMMANDEX:
- S_OK: I completed the command. CDefaultContextMenu does nothing because it has already been handled.
- S_FALSE: I cannot perform this command but I want CDefaultContextMenu to perform the action for me (cut/copy/delete/properties).
- E_NOTIMPL: I don't need nor know about DFM_INVOKECOMMANDEX. CDefaultContextMenu will send DFM_INVOKECOMMAND.
- E_*: I tried to complete the command but something failed. CDefaultContextMenu should pass this error back to the caller of IContextMenu::InvokeCommand.
If you only handle your commands in DFM_INVOKECOMMAND then …

[ZIPFLDR] Don't handle DFM_INVOKECOMMANDEX if you need DFM_INVOKECOMMAND

---

sdk/include/reactos/wine/unicode.h

These defines assumed that the (v)swprintf functions were the non-conformant ones (that don't take a 'count' 2nd parameter). Because of that, use instead the _(v)swprintf functions. However, those exist only in NT6+. Therefore, redefine these locally using the _(v)snprintf functions.
NOTE: wine/unicode.h has been removed in wine commit 348eebae872e90a735041a153635d00b01178cfa from July 13, 2022
Needed as part of [my work-in-progress setupapi winesync](https://github.com/reactos/reactos/tree/hbelusca/setupapi_partial_winesync/), this should also help with the winetests being done recently by @DarkFire01 @cbialorucki @maj113 and others.

[SDK:WINE] Improve wine/unicode.h (v)sprintfW defines, regarding the (v)swprintf functions.

---

win32ss/user/ntuser/painting.c

Patch by @I_Kill_Bugs
_Test RgnType and do quick return from Invalidate Window if redraw not needed._
JIRA issue: [CORE-19553](https://jira.reactos.org/browse/CORE-19553)
_Test RgnType for NULLREGION or ERROR and return if Invalidate Window is not needed._

[NTUSER] Remove some extra repaints/redraws

---

sdk/include/reactos/wine/test.h

Newer winetests use debugstr_w(n) helpers; however for whatever reason our wine/test.h glue header, only used for the tests, don't have these. This PR remedies this problem.
Needed as part of [my work-in-progress setupapi winesync](https://github.com/reactos/reactos/tree/hbelusca/setupapi_partial_winesync/), this should also help with the winetests being done recently by @DarkFire01 @cbialorucki @maj113 and others.
- Add two missing debugstr_w* helpers. These will be needed for future winetest syncs.
Note that such change would be unnecessary, would wine/test.h and wine/debug.h be also updated with latest Wine versions. Indeed, wine/debug.h is now allowed to be included in wine tests since wine commit:
```
include: Allow using debug.h in tests.
Signed-off-by: Alexandre Julliard …
```

[SDK:WINE] Some minor additions to wine/test.h

---

ntoskrnl/io/iomgr/irq.c
ntoskrnl/ke/i386/irqobj.c

Fix and improve/optimize this code. Split from PR #6495 by @SergeGautherie 
- [FORMATTING] iomgr/irq.c
- IoConnectInterrupt(): Zero-out the allocated structure at the correct place
- IoDisconnectInterrupt(): Fix disconnecting other interrupts
- IoConnectInterrupt(): Fix default spinlock initialization
- IoConnectInterrupt(): Move InterruptObject assignment back to where it belongs
- IoDisconnectInterrupt(): Switch to ExFreePoolWithTag()

[NTOS:IO] Fixes for Io*onnectInterrupt()

---

win32ss/gdi/ntgdi/freetype.c

Simplify and reduce font code.
- Don't treat bold/italic glyphs specially in font cache.
- Delete useless `IntGetBitmapGlyphNoCache` function.

[NTGDI][FREETYPE] Simplify code around bold/italic glyph caches

---

win32ss/gdi/ntgdi/freetype.c

Slight performance improvement.
`STACK_TEXT_BUFFER_SIZE = 100` was too small for long text.
This PR can reduce unnecessary buffer allocations in `NtGdiExtTextOutW` function.
- Change `STACK_TEXT_BUFFER_SIZE` to `512`.

[NTGDI][FREETYPE] Increase STACK_TEXT_BUFFER_SIZE

---

win32ss/user/ntuser/menu.c

Fix NULL pointer dereference. Happens when the user heap gets depleted.
JIRA issue: [CORE-19367](https://jira.reactos.org/browse/CORE-19367)

[WIN32K] Fix NULL pointer dereference in MENU_HideSubPopups

---

dll/win32/wdmaud.drv/legacy.c
dll/win32/wdmaud.drv/mmixer.c
drivers/wdm/audio/legacy/wdmaud/control.c
drivers/wdm/audio/legacy/wdmaud/mmixer.c
drivers/wdm/audio/legacy/wdmaud/wdmaud.h
sdk/lib/drivers/sound/mmixer/mmixer.h
sdk/lib/drivers/sound/mmixer/wave.c

Implement `GetWavePosition` API for both Legacy and MMixer modes.
This fixes a failure retrieving the current audio playback position and subsequent playing the audio data by several 3rd-party applications which are using this API (for example, some Gecko based browsers by @roytam1: Basilisk (Serpent) 52.9.0 IA-32 build, NewMoon 28.10.7 IA-32 build and KMeleon 76.5.3 Goanna engine).
JIRA issue: [CORE-19542](https://jira.reactos.org/browse/CORE-19542)
[WDMAUD.DRV]
- Fix wrong I/O control code passed to `DeviceIoControl` for Legacy mode. Use `IOCTL_GETPOS` instead of `IOCTL_OPEN_WDMAUD`, to use the correct routine.
- Implement `WdmAudGetWavePosition` for MMixer mode, as it was completely unimplemented there. Call an appropriate MMixer routine and return back resulting wave position. …

[AUDIO] Implement retrieving current audio playback position

---

base/applications/regedit/treeview.c

Fix an unhandled exception in regedit treeview.c when attempting to create a key in root/"My computer"
JIRA issue: [CORE-19567](https://jira.reactos.org/browse/CORE-19567)
- Check if pszKeyPath is NULL and return bSuccess if so

[REGEDIT] Fix unhandled exception when trying to create a key in root

---

win32ss/gdi/ntgdi/freetype.c

Support emoji characters and minor characters.
JIRA issue: [CORE-19030](https://jira.reactos.org/browse/CORE-19030)
NOTE: Not every emoji is supported yet (No ZWJ support). Surrogate pairs only.
NOTE: This feature only works if the appropriate font is selected.
- Add `IS_HIGH_SURROGATE` and `IS_LOW_SURROGATE` macros.
- Add `Utf32FromSurrogatePair` helper function to convert a surrogate pair to a UTF-32 code point.
- Convert the surrogate pairs in the text in `TextIntGetTextExtentPoint`, `IntGetTextDisposition`, and `IntExtTextOutW` functions.
The test program: https://jira.reactos.org/secure/attachment/68032/win32_emoji_draw.zip
With borrowing `"Segoe UI Emoji"` font from Win10.
BEFORE:
Failed.
AFTER:
Successful.
The test program Part 2: …

[NTGDI][FREETYPE] Initial support of Surrogate Pairs and emojis

---

base/setup/lib/bootsup.c
base/setup/lib/utils/bldrsup.c
base/setup/lib/utils/bldrsup.h

The main purpose of this PR is to migrate the usage of the deprecated FreeLoader "Drive" and "Partition" boot types to the unified "BootSector" one (see to this effect, commit 5f3554a40 PR #6760) , as well as the "BootDrive" and "BootPartition" values to the "BootPath" one (this will be the subject of a future FreeLoader PR).
Because this requires the manipulation (addition/modification/removal) of key-values in FREELDR.INI, I took also the opportunity to:
- do a little revamping of the INI helpers (which is also something I had in my TODO list for years),
- add support for removing sections and key values.
```
[SETUPLIB] Some INI support refactoring: function/struct names, duplicated code
And convert ANSI strings to UNICODE in a better way instead of
zero-extending them.
```
``` …
```

[SETUPLIB] Improve the INI helpers; migrate old FreeLdr "Drive/Partition" types and "BootDrive/BootPartition" values

---

dll/cpl/inetcpl/lang/He.rc
dll/cpl/inetcpl/lang/Sr.rc
dll/cpl/inetcpl/lang/bg-BG.rc
dll/cpl/inetcpl/lang/cs-CZ.rc
dll/cpl/inetcpl/lang/de-DE.rc
dll/cpl/inetcpl/lang/en-US.rc
dll/cpl/inetcpl/lang/es-ES.rc
dll/cpl/inetcpl/lang/fr-FR.rc
dll/cpl/inetcpl/lang/id-ID.rc
dll/cpl/inetcpl/lang/it-IT.rc
dll/cpl/inetcpl/lang/ja-JP.rc
dll/cpl/inetcpl/lang/ko-KR.rc
dll/cpl/inetcpl/lang/lt-LT.rc
dll/cpl/inetcpl/lang/nl-NL.rc
dll/cpl/inetcpl/lang/pl-PL.rc
dll/cpl/inetcpl/lang/pt-BR.rc
dll/cpl/inetcpl/lang/pt-PT.rc
dll/cpl/inetcpl/lang/ro-RO.rc
dll/cpl/inetcpl/lang/ru-RU.rc
dll/cpl/inetcpl/lang/sq-AL.rc
dll/cpl/inetcpl/lang/sv-SE.rc
dll/cpl/inetcpl/lang/tr-TR.rc
dll/cpl/inetcpl/lang/uk-UA.rc
dll/cpl/inetcpl/lang/zh-CN.rc
dll/cpl/inetcpl/lang/zh-TW.rc

Fix keyboard navigation in Inet delete browser history menu
JIRA issue: [CORE-19568](https://jira.reactos.org/browse/CORE-19568)
- Remove WS_GROUP from IDOK
- Add WS_GROUP to first AUTOCHECKBOX (IDC_DELETE_TEMP_FILES)
- Move buttons above IDC_DELETE_TEMP_FILES so that the cancel button is focused by default when opening the menu

[INETCPL] Fix missing keyboard navigation

---

dll/win32/browseui/shellbrowser.cpp
sdk/include/reactos/shlobj_undoc.h

Support GetControlWindow, ShowControlWindow and IsControlWindowShown for TREE and STATUS in the Shell Browser.
This combined with the [CMF_EXPLORE DefView PR](https://github.com/reactos/reactos/pull/6776) allows DFM to pick the correct default folder verb:
Notes:
- Yes, it seems like IsControlWindowShown should allow the output parameter to be NULL as some kind of shortcut.
----
I discovered that the commands related to CGID_Explorer are called SBCMDID_* (Shell Browser Cmd Id?). MSDN [leaks](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767714(v=vs.85)) the fact that one of the commands is called SBCMDID_SELECTHISTPIDL. This lead me to [this mailing list archive](https://wtl.yahoogroups.narkive.com/ejpCzFtj/ot-query-shell-sbcmdid …

[BROWSEUI] GetControlWindow must support FCW_TREE for DefView usage

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CNetFolder.cpp
dll/win32/shell32/folders/CRegFolder.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shlfolder.cpp

Moves default processing of all DFM_ callback messages to a single function.
Bugs fixed:
- Properties item in background context menu in FS folders now works correctly ([CORE-18585](https://jira.reactos.org/browse/CORE-18585)).
Notes:
- I'm not convinced that the Windows 7 comments regarding DFM_GETDEFSTATICID is correct but I've retained the handling (for now).
- Adding SHELL_ExecuteControlPanelCPL as a thin wrapper because SHRunControlPanel is officially deprecated and its future as a public export is unclear.
Regarding DFM_GETDEFSTATICID and DFM_INVOKECOMMANDEX, it seems like this code and its comment was copied around to multiple places, here are the ones I found.
- [CNetFolder.cpp](https://github.com/reactos/reactos/commit/668ef9aa19098849693567040164f027727f6d25) 2016
- …

[SHELL32] Use common default DFM callback message handler

---

base/applications/rapps/gui.cpp

Fix refresh not working correctly after commit [33c2903e](https://github.com/reactos/reactos/commit/33c2903e6d4fda32215f553c2189c13d52ed31de)
Before:
[ReactOS-Before.webm](https://github.com/reactos/reactos/assets/86486978/9ab289d7-98b3-42f5-9442-7d80ce03d531)
After:
[ReactOS-After.webm](https://github.com/reactos/reactos/assets/86486978/7fbd9241-0dbe-4233-b0ea-f6f489423563)
Jira issue: Related to [CORE-18459](https://jira.reactos.org/browse/CORE-18459)

[RAPPS] Fix refresh not working correctly

---

base/applications/sndvol32/sndvol32.c
base/applications/sndvol32/sndvol32.h

Adds a Hotkey (CTRL-S) which switches between the Normal and Small Modes of the Volume Control Window (also seen in WINXP)
JIRA issue: [CORE-17043](https://jira.reactos.org/browse/CORE-17043)

[SNDVOL32] Add CTRL-S hotkey to switch between Small and Normal modes

---

base/applications/rapps/geninst.cpp

DelRegEmpty exists to clean up "company" registry parent keys. If another application is writing to the key at the same time as we are gently trying to remove it, our uninstaller should ignore any errors.

[RAPPS] DelRegEmpty instruction should be best-effort, don't propagate errors

---

dll/win32/shell32/shlexec.cpp

The goal is a correct implementation of `shell32!ShellExecute`.
JIRA issue: [CORE-17482](https://jira.reactos.org/browse/CORE-17482)
- Add `SHELL_InRunDllProcess` helper function.
- Add structure size check to `ShellExecuteExA` function.
- Add code to `ShellExecuteExW` function.
- Add `"MaximizeApps"` registry value check.

[SHELL32] ShellExecute: Re-work Part 1

---

dll/win32/shell32/CDefView.cpp

Updating the statusbar on every LVN_ITEMCHANGED causes a massive delay when the number of changed items is large, very noticeable on Ctrl+A.
JIRA issue: [CORE-18663](https://jira.reactos.org/browse/CORE-18663)

[SHELL32] Coalesce DefView item changed statusbar updates

---

base/applications/notepad/dialog.c

Fix access denial on writing file `"C:\freeldr.ini"`.
JIRA issue: [CORE-19575](https://jira.reactos.org/browse/CORE-19575)
- Add `FILE_SHARE_READ` flag and delete `FILE_SHARE_WRITE` flag in `CreateFileW` call.
- Use `OPEN_ALWAYS` instead of `CREATE_ALWAYS`, and then explicitly use `SetEndOfFile` function.
BEFORE:
Access denial.
AFTER:
Successfully saved.

[NOTEPAD] Use FILE_SHARE_READ and OPEN_ALWAYS for writing

---

base/applications/wordpad/wordpad.c

Follow-up to #6880. Fix access denial on writing file "C:\freeldr.ini".
JIRA issue: [CORE-19575](https://jira.reactos.org/browse/CORE-19575)
- Add `FILE_SHARE_READ` flag in `CreateFileW` call.
- Use `OPEN_ALWAYS` instead of `CREATE_ALWAYS`, and then explicitly use `SetEndOfFile` function.
BEFORE:
Access denial.
AFTER:
Successful.

[WORDPAD] Use FILE_SHARE_READ and OPEN_ALWAYS for writing

---

win32ss/gdi/ntgdi/bitblt.c

Improve the checks in `AlphaBlend` and `TransparentBlt` functions: check whether `DCSrc` is of `DCTYPE_INFO` also, to fail in that case properly too. Spotted by PVS-Studio analysis.
Reference: https://pvs-studio.com/en/blog/posts/cpp/1122/.

[NTGDI] AlphaBlend/TransparentBlt: check whether the source DC is an Info DC too

---

dll/win32/shlwapi/shlwapi.spec
dll/win32/shlwapi/utils.cpp
modules/rostests/apitests/shlwapi/CMakeLists.txt
modules/rostests/apitests/shlwapi/PathFileExistsDefExtAndAttributesW.c
modules/rostests/apitests/shlwapi/testlist.c
sdk/include/reactos/shlwapi_undoc.h

- Implement `PathFileExistsDefExtAndAttributesW` function.
- Add its prototype to `<shlwapi_undoc.h>`.
- Add `PathFileExistsDefExtAndAttributesW`  testcase.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
Successful.

[SHLWAPI][SHLWAPI_APITEST][SDK] PathFileExistsDefExtAndAttributesW

---

.github/workflows/build.yml
README.md

Let's establish a set of rules regarding compiler support in ReactOS to avoid holywars in future.
- We officially support __no more than two versions__ of each compiler.
- The term "officially supported" means there is a job on one of our CI systems (either GitHub Actions or BuildBot) checking both Debug and Release builds for this compiler for supported platforms (currently it is i386 and amd64). Every developer has to check changes against those compilers and/or fix breakages ASAP if they happen.
- Two versions usually mean having one "stable" version which is not changed often and one "latest" version. For example, VS 2017 and VS 2019 (or that will likely be VS 2022 soon) or RosBE-provided GCC 8.4.0 and the current latest release (GCC 11.1.0).
- "stable" compiler should be upgraded …

[GITHUB] Remove VS 2015 build from the CI

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHSimpleIDListFromPath.cpp
modules/rostests/apitests/shell32/testlist.c

Inspect the behavior of `shell32!SHSimpleIDListFromPath` function.
JIRA issue: [CORE-19591](https://jira.reactos.org/browse/CORE-19591)
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Successful.

[SHELL32_APITEST] Add SHSimpleIDListFromPath testcase

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/dialogs/filetypes.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CRecycleBin.cpp
dll/win32/shell32/shlfileop.cpp
dll/win32/shell32/wine/pidl.c
sdk/include/psdk/shlobj.h
sdk/include/reactos/undocshell.h

Making shell change notification implementation better. Now recycle bin icon change is working.
JIRA issue: [CORE-19591](https://jira.reactos.org/browse/CORE-19591)
JIRA issue: [CORE-11453](https://jira.reactos.org/browse/CORE-11453)
- Delete `SHSimpleIDListFromPathA/W` hacks.
- Translate simple PIDLs (coming from `SHSimpleIDListFromPathA/W`) in `CDefView::OnChangeNotify` method.
- Add `CDefView::LV_RefreshIcons` method for `SHCNE_UPDATEIMAGE` change event.
- Rename `CDefView::LV_ProdItem` method as `CDefView::LV_UpdateItem`.
- Call `SHUpdateRecycleBinIcon` in `SHFileOperationW` function.
- Half-implement `SHUpdateRecycleBinIcon`.
- Call `SHChangeNotify` in `DeleteExt` function.

[SHELL32][SDK] SHChangeNotify: Re-work Part 1

---

.github/workflows/build.yml
sdk/lib/crt/startup/crtexe.c

Github dropped VS2017 in the windows-latest ~~and seemingly also in windows-2019 (since clang-cl fails to find the 14.1 toolset and it uses windows-2019)~~ runners
https://github.com/actions/runner-images/commit/441122013e49b8a909c8007712da07504a2b4937 It also looks like 14.2 is getting removed
- Drop VS2017 builder 
- Add VS2022 builder
- Add comment regarding Clang-CL, I tested a build from Github Actions that was compiled with 14.1, it did not boot, fails with 0x1E

[GITHUB] Fix builds by dropping VS2017 and retargeting to VS2022

---

dll/win32/shell32/wine/brsfolder.c

`dll/win32/shell32/wine/brsfolder.c`. This file is too hard to read. Nobody reads.
And WineHQ doesn't show no progress recently in this file. OUT OF DATE!
- Rewrite some `SendMessageW` code by using `TreeView_...` macros.
- Add `BrsFolder_GetDataFromItem` helper function and use it.

[SHELL32] SHBrowseForFolder: Refactor brsfolder.c

---

dll/win32/shlwapi/shlwapi.spec
dll/win32/shlwapi/utils.cpp
sdk/include/psdk/shobjidl.idl
sdk/include/reactos/shlwapi_undoc.h

- Implement `IShellFolder_GetDisplayNameOf`, `IShellFolder_ParseDisplayName`, and `IShellFolder_CompareIDs` functions.
- Add them to `<shlwapi_undoc.h>`.
- Add some `SHCIDS_...` macros into `shobjidl.idl`.
- Provide a macro option `SHLWAPI_ISHELLFOLDER_HELPERS` to avoid conflict with `<shobjidl.h>` `IShellFolder_...` inline functions. Ugly hack but effective!

[SHLWAPI][SDK] Add IShellFolder_... helper functions

---

dll/win32/shell32/folders/CRecycleBin.cpp
dll/win32/shell32/shellrecyclebin/recyclebin.c
dll/win32/shell32/shellrecyclebin/recyclebin.h

Generic `HANDLE` type is vague and unreadable.
Declare a special handle type for recycle bin items.
- Declare the `HDELFILE` handle by `DECLARE_HANDLE(HDELFILE);`.
- Use `HDELFILE` instead of `HANDLE` for deleted items.

[SHELL32] Introduce 'HDELFILE' handle type

---

base/applications/regedit/framewnd.c

The ability to go to a favorite and the dialog was already there, just needed to fill in the blanks.

[REGEDIT] Implement "Add to favorites" feature

---

dll/win32/shell32/precomp.h
dll/win32/shell32/utils.cpp
dll/win32/shell32/wine/pidl.c
dll/win32/shell32/wine/shellpath.c

CSIDL_CONNECTIONS is needed by external callers, mainly NetShell PR #6905

[SHELL32] Implement CSIDL_CONNECTIONS and fix CSIDL_PRINTERS

---

dll/win32/browseui/explorerband.cpp
dll/win32/browseui/explorerband.h
dll/win32/browseui/shellbrowser.cpp
dll/win32/browseui/utility.cpp
dll/win32/browseui/utility.h
dll/win32/comctl32/listview.c

IContextMenu (CDefaultContextMenu) only knows how to rename when its site is an IShellView. The tree must detect the rename operation and perform it in the TreeView instead.
Fixed a bug in the ListView that is triggered by activating DefView (to complete the rename): Just after DefView has been activated, the tree performs a navigation to the newly renamed folder, this causes DefView to be destroyed and in turn the ListView. The ListView tries to handle a selection change during destruction of the ListView and ends up accessing an invalid pointer.
Also fixes a memory leak and some minor flaws in IShellBrowser return code handling.
JIRA issue: [CORE-19557](https://jira.reactos.org/browse/CORE-19557)

[BROWSEUI][COMCTL32] Handle rename on other folders in Explorer bar tree

---

dll/win32/shell32/shelldesktop/CChangeNotifyServer.cpp
dll/win32/shell32/shelldesktop/CDirectoryWatcher.cpp
dll/win32/shell32/shelldesktop/CDirectoryWatcher.h

Kill the zombie watchers for system performance.
- Add `HWND` parameter to `CDirectoryWatcher::Create`.
- Check whether the `HWND` is alive at `CDirectoryWatcher::IsDead`.

[SHELL32] CDirectoryWatcher: Check if window is alive

---

ntoskrnl/config/ntapi.c
ntoskrnl/include/internal/cm.h
ntoskrnl/include/internal/cm_x.h

Properly unlock registry on failure in NtUnloadKey2.
Fixes random hang when loading user profile.
Jira Issue: [CORE-19539](https://jira.reactos.org/browse/CORE-19539)
- Add lock debugging code
- Unlock on failure
- KVM x86: https://reactos.org/testman/compare.php?ids=95136,95142,95154,95160,95167
- KVM x64: https://reactos.org/testman/compare.php?ids=95087,95088,95096,95115,95161

[NTOS:CM] Fix unlocking on failure

---

dll/win32/shell32/CMakeLists.txt
dll/win32/shell32/brfolder.cpp
dll/win32/shell32/brsfolder.cpp

Modernize source code. Improve readability and reduce confusing.
- Code formatting.
- Rename `brsfolder.cpp` as `brfolder.cpp`.
- Rename `browse_info` as `BrFolder`.
- Rename `TV_ITEMDATA` as `BrItemData`.
- Rename `InsertTreeViewItem` as `BrFolder_InsertItem`.
- Rename `InitializeTreeView` as `BrFolder_InitTreeView`.
- Rename `GetIcon` as `BrFolder_GetIcon`.
- Rename `GetNormalAndSelectedIcons` as `BrFolder_GetIconPair`.
- Rename `GetName` as `BrFolder_GetName`.
- Fix some confusing and/or non-standard variable names.
- Use ATL to simplify logics.

[SHELL32] brfolder.cpp: Code formatting and refactoring

---

boot/bootdata/hivesft.inf

Prepare for font linking implementation.
- Modify `boot/bootdata/hivesft.inf`.
Successful.

[BOOTDATA][INF] Add FontLink registry entries

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/utils.cpp
dll/win32/shell32/wine/pidl.c

Follow-up to #6898. These PIDLs shouldn't be freed because they are not allocated by `CoTaskMemAlloc`.
We should use PIDLs mainly in internal data instead of physical paths for change notifications.
JIRA issue: [CORE-19612](https://jira.reactos.org/browse/CORE-19612)
- Re-implement `SHGetRealIDL` function.
- Translate child IDLs by using `SHGetRealIDL`.
- Use newly-defined `pidl0Temp` and `pidl1Temp` for temporary creation.
- Improve `ILIsParentOrSpecialParent` function without using `SHGetPathFromIDListW` function.

[SHELL32] Don't free original PIDLs in CDefView::OnChangeNotify

---

dll/win32/syssetup/wizard.c

Switching themes during initial setup broke at some point relatively recently - following said regression, selecting a theme simply has no effect at all.
This PR fixes the regression.
JIRA issue: None...? (Again...??)

[SYSSETUP] Fix theme switcher

---

win32ss/user/ntuser/menu.c

CORE-19579
_Move CMD popup menu to not cover 'Close'._
JIRA issue: [CORE-19579](https://jira.reactos.org/browse/CORE-19579)
_When IS_SYSTEM_MENU was redefined, the old definition worked better in this location, so put its logic back._
_Fix an 'unintended consequence' of https://github.com/reactos/reactos/commit/3ae0ccdcc._
Before:
After:

[NTUSER] menu.c position fix to not hide 'Close'

---

dll/win32/shell32/brfolder.cpp

Follow-up of #6909 (af03438). Fix assertions and exceptions of `CComPtr` and `CComHeapPtr`.
- Don't use `AddRef`, `Release`, and `Attach` methods against `CComPtr` template class. Simply use assignment.
- Fix the 3rd parameter of three `IShellFolder::GetAttributesOf` method calls. It had referenced `CHeapPtr::operator&`.
Successful.

[SHELL32] brfolder.cpp: Follow-up of af03438

---

dll/win32/shell32/brfolder.cpp

New delivery method is better than old method in performance. Now deletion notification partially works.
- Specify `SHCNRF_ShellLevel | SHCNRF_NewDelivery`.
- Rewrite `BrFolder_OnChange` function and add `BrFolder_OnChangeEx` helper function.

[SHELL32] brfolder.cpp: Adopt SHCNRF_NewDelivery method

---

dll/win32/shell32/CDefView.cpp

- In `CDefView::InvokeContextMenuCommand`, call `SFVM_GETCOMMANDDIR` callback and store the directory into `CMINVOKECOMMANDINFOEX` structure.

[SHELL32] CDefView: Implement SFVM_GETCOMMANDIR callback

---

dll/win32/shell32/CDefView.cpp

- Call `_DoFolderViewCB` on `LVN_COLUMNCLICK`.
- If it returned `S_OK`, then don't sort items.

[SHELL32] CDefView: Implement SFVM_COLUMNCLICK callback

---

dll/win32/shell32/CDefView.cpp

- Call `SFVM_CANSELECTALL` callback on `FCIDM_SHVIEW_SELECTALL`.
- If it returned `S_FALSE`, then do not select all.

[SHELL32] CDefView: Implement SFVM_CANSELECTALL callback

---

dll/win32/browseui/shellbrowser.cpp
dll/win32/shell32/CDefView.cpp
sdk/include/psdk/shlobj.h
sdk/include/psdk/shobjidl.idl

- Add `SFVM_PROPPAGE_DATA` structure to `"shobjidl.idl"`.
- Implement `CDefView::AddPropertySheetPages` by calling `SFVM_ADDPROPERTYPAGES` callback.
- Modify `CShellBrowser::DoFolderOptions` that uses `AddPropertySheetPages`.

[SHELL32][BROWSEUI] CDefView: Implement SFVM_ADDPROPERTYPAGES callback

---

dll/win32/shell32/CDefView.cpp

- Call `_DoFolderViewCB` on `LVN_BEGINLABELEDITW` message.
- Send `EM_SETLIMITTEXT` message if the limit was set.

[SHELL32] CDefView: Implement SFVM_GETNAMELENGTH callback

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefViewBckgrndMenu.cpp

This refactor decouples the previous assumption that the ListView column index is the same thing as the IShellFolder column index. By doing this, support for turning columns on or off becomes possible. The `SHCOLSTATE_ONBYDEFAULT` and `SHCOLSTATE_HIDDEN` flags are also respected.
I also fixed the "Arrange icons by" submenu (JIRA issue: [CORE-18526](https://jira.reactos.org/browse/CORE-18526)).
Because the existing code unfortunatly used the entire menu id range allocated for IShellView (`FCIDM_SHVIEWFIRST`..`FCIDM_SHVIEWLAST`) when dealing with IContextMenu, I did have to modify that code slightly because I needed some menu item ids.
I moved two of the existing menu helper functions because I needed to call one of them higher up in the file.
The "More" menu item has been disabled in this …

[SHELL32] Refactor DefView column handling

---

boot/bootdata/hivesft.inf
dll/win32/imm32/utils.c
win32ss/user/ntuser/metric.c

JIRA issue: [CORE-19320](https://jira.reactos.org/browse/CORE-19320)
- Delete `"(brain-dead)"`.
- Fix `"despite of"` as `"despite"`.
- Use `"%S"` instead of `debugstr_w`.

[BOOTDATA][IMM32][NTUSER] Follow-up to #6961

---

win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.h
win32ss/user/ntuser/main.c

Check system integrity by explicitly releasing the font engine.
- Use `RTL_STATIC_LIST_HEAD` against `g_FontListHead` and `g_FontCacheListHead` variables and omit initialization of them.
- Implement `FreeFontSupport` function.
- Call `FreeFontSupport` in `win32k!DriverUnload` function.
- Fix some usages of `CONTAINING_RECORD` macro.

[NTGDI][FREETYPE] Unload font engine on system shut-down

---

dll/win32/shell32/CDefView.cpp

`ZeroMemory` sets `CMINVOKECOMMANDINFOEX::nShow` to `SW_HIDE`. This causes shell extensions that propagates the `nShow` all the way to start child processes hidden.

[SHELL32] CDefView::InvokeContextMenuCommand must specify a showcmd

---

dll/win32/shell32/brfolder.cpp

Refresh the items in the tree-view control of `SHBrowseForFolderA/W` functions against change notifications.
- Add `BrFolder_IsTreeItemInEnum` and `BrFolder_TreeItemHasThisChild` helper functions.
- Add `BrFolder_Refresh`, `BrFolder_RefreshRecurse`, and `BrFolder_UpdateItem` functions to refresh items.
- Call `BrFolder_Refresh` in `BrFolder_OnChangeEx` function and on keyboard `F5` and `Ctrl+R` actions.
https://github.com/reactos/reactos/assets/2107452/65159cfe-aecf-4247-86fd-4a980dc2da3e

[SHELL32] brfolder.cpp: Refresh items

---

dll/win32/wdmaud.drv/legacy.c
dll/win32/wdmaud.drv/mmixer.c
dll/win32/wdmaud.drv/wdmaud.c
dll/win32/wdmaud.drv/wdmaud.h
sdk/include/reactos/libs/sound/mmebuddy.h
sdk/lib/drivers/sound/mmebuddy/auxiliary/auxMessage.c
sdk/lib/drivers/sound/mmebuddy/midi/modMessage.c
sdk/lib/drivers/sound/mmebuddy/mmewrap.c
sdk/lib/drivers/sound/mmebuddy/wave/wodMessage.c

Implement volume level changing for Aux/MidiOut/WaveOut devices. The volume control is represented the following WINMM functions:
- `auxGetVolume`,
- `auxSetVolume`,
- `midiOutGetVolume`,
- `midiOutSetVolume`,
- `waveOutGetVolume`,
- `waveOutSetVolume`,
which are calling the following messages appropriately:
- `AUXDM_GETVOLUME`,
- `AUXDM_SETVOLUME`,
- `MODM_GETVOLUME`,
- `MODM_SETVOLUME`,
- `WODM_GETVOLUME`,
- `WODM_SETVOLUME`.  
This fixes volume control for several 3rd-party programs (like Fox Audio Player 0.10.2 from Rapps, Winamp 2.95 with WaveOut plugin). However it does not fix changing the volume in system volume mixers (SndVol32, MMSys), since they are using their own functionality instead. They technically do the same things, but apart from the functions mentioned above.
JIRA …

[AUDIO] Implement volume control support

---

drivers/wdm/audio/drivers/ac97/prophnd.cpp

Add ReactOS change to use the same Decibel (dB) sound loudness range for Master Volume control as for WaveOut Volume Control. This fixes incompatible volume level change scaling when changing the volume in Fox Audio Player 0.10.2 from Rapps and Winamp 2.95 with WaveOut output plugin. Now it is identical to the one when using original AC97 driver from Windows XP/Server 2003. :slightly_smiling_face: 
Depends on my previous #6922 PR.
Results of my testing:
- ROS with our AC97 driver in VirtualBox (before my changes): :x: the volume is changing only from 51% to 100%, from 0% to 50% it is always at 1% actually.
- ROS with our AC97 driver in VirtualBox (after my changes): :white_check_mark: the volume is changing from 0% to 100%, as it ideally should.
- ROS with original AC97 driver from …

[AC97] Use individual Decibel range for Master Volume control

---

ntoskrnl/config/cmapi.c
ntoskrnl/config/ntapi.c
ntoskrnl/include/internal/cm.h

Two months ago I wrote a patch (#6649) that discards any orphaned KCBs of keys which don't have open references. Before that the kernel would leak useless KCBs still residing in memory that point to a _**potentially unloaded registry hive**_!!!
While this fixed the aforementioned problem that it meant to fix, it brought another issue though. Fundamentally `CmpEnumerateOpenSubKeys` locks down the cached individual KCB (that's correct) before it tears apart its contents but it doesn't address the fact we might get a deadlock as lock recursion is highly to happen there (yikes, big problemo man).
Instead of aggressively acquiring the push lock of a KCB, simply lock the entire registry for exclusive use by the calling thread that does the hive unloading. This simplifies the code a lot and we …

[NTOS:CM] Lock the entire registry down when we unload a hive

---

dll/win32/msi/custom.c

[MSI] CORE-18707 hack. Allow MSI under ROS amd64 to continue when GetSystemWow64DirectoryW is called
Workaround (with a hack) a temporary situation since we have the WOW64 unimplemented (neither GetSystemWow64DirectoryW).
JIRA issue: [CORE-18707](https://jira.reactos.org/browse/CORE-18707)
- Temporary workaround that avoids MSI to continue under our ROS Amd64.

[MSI] CORE-18707 workaround. Allow MSI under ROS amd64 to continue when GetSystemWow64DirectoryW is called

---

dll/win32/dbghelp/compat.c
dll/win32/dbghelp/compat.h
sdk/include/ndk/rtlfuncs.h
sdk/lib/rtl/crc32.c

and sync SAL2 annotations.
Be consistent with other/Wine declarations.
Fix warnings:
gcc:
```
/home/runner/work/reactos/reactos/src/dll/win32/dbghelp/inflate.c:1402:60: warning: passing argument 2 of ‘__RtlComputeCrc32’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
/home/runner/work/reactos/reactos/src/dll/win32/dbghelp/inflate.c:1423:56: warning: passing argument 2 of ‘__RtlComputeCrc32’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
/home/runner/work/reactos/reactos/src/dll/win32/dbghelp/inflate.c:1444:56: warning: passing argument 2 of ‘__RtlComputeCrc32’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
```
msvc:
```
[49/295] Building C object …
```

[DBGHELP][NDK][RTL] RtlComputeCrc32(): Add 'const' to 2nd parameter

---

base/applications/regedit/childwnd.c

Adds the "jump to same key in the other root" feature that Windows 10 has had for a while.
Note:
- Changed the REGSAM for the existing HKCR jump code because non-admins are also allowed to jump.

[REGEDIT] Implement the "Go to HKCU/HKLM" feature

---

dll/win32/browseui/globalfoldersettings.cpp
dll/win32/browseui/globalfoldersettings.h
dll/win32/browseui/settings.cpp
dll/win32/browseui/settings.h
dll/win32/browseui/shellbrowser.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CFolderOptions.cpp
dll/win32/shell32/CFolderOptions.h
dll/win32/shell32/dialogs/view.cpp
dll/win32/shell32/precomp.h
sdk/include/reactos/shellutils.h
sdk/include/reactos/shlobj_undoc.h

Notes:
- ~~I don't know the format of the Windows "Settings" stream. I made our version incompatible on purpose, it is much smaller and uses a special signature.~~
- DefView only understands the Reset part, I'm not sure how/what to store as its settings yet.
- SHELL_ErrorBox is a template to make it harder to pass in a NULL HWND on purpose.

[SHELL32][BROWSEUI] Implement ShellBrowser Apply/Reset default folder settings

---

dll/win32/shell32/folders/CRegFolder.cpp
dll/win32/shell32/utils.cpp

RegItems that pretend to be files should not have Folder verbs

[SHELL32] Don't add folder verbs to non-folder RegItems

---

boot/bootdata/hivesft.inf

Follow-up to #6929.
Latin accented characters will be able to be mixed in East Asian text by FontLink framework in the future.
- Modify `boot/bootdata/hivesft.inf`.
- Add `"tahoma.ttf,Tahoma"` entry to Asian FontLink registry values.

[BOOTDATA][INF] Add Tahoma entry to Asian FontLink

---

boot/bootdata/hivesft.inf

Reverts reactos/reactos#6985
Forgot a comma and a backslash.

Revert "[BOOTDATA][INF] Add Tahoma entry to Asian FontLink"

---

.github/workflows/build.yml

MSVC 17.10 now uses 14.4x for its toolset version
Github just upgraded to this version as seen here:
https://github.com/actions/runner-images/releases/tag/win22%2F20240603.1
- Use latest version that the github image provides instead of clamping to a specific minor version
**NOTE** Some of our runners have not yet been updated to 20240603.1 so it may take a bit of time for them to all use this 
version <-- this should be fixed now

[GITHUB] Fix toolset version for MSVC 17.10

---

boot/bootdata/hivesft.inf

This is re-trial of #6985. Forgot a comma and a backslash.
- Modify `boot/bootdata/hivesft.inf`.

[BOOTDATA][INF] Retry: Add Tahoma entry to Asian FontLink

---

base/applications/rapps/unattended.cpp

- There is a small race between `CreateMutex` and `CMainWindow` creating the window, another instance might get `NULL` in its `FindWindow`. This PR retries multiple times and if the window does not appear within a reasonable, it starts another instance.
- If the existing window is minimized, it should be restored. If the existing window is maximized, it should **not** be "normalized". `SwitchToThisWindow` does all this in addition to calling `SetForegroundWindow`.

[RAPPS] Improve existing window re-use

---

dll/win32/riched20/para.c
modules/rostests/winetests/riched20/editor.c

CORE-8452
_Riched20 partial Wine sync to fix excessive tab count._
JIRA issue: [CORE-8452](https://jira.reactos.org/browse/CORE-8452)
_Partial Wine sync of riched20. No 'ifdef' used because this is already in Wine._

[RICHED20] Fix assert in editpad due to excessive tab count

---

boot/bootdata/CMakeLists.txt
dll/win32/urlmon/CMakeLists.txt
media/themes/Blackshade/blackshade.msstyles/CMakeLists.txt
media/themes/Lautus/lautus.msstyles/CMakeLists.txt
media/themes/Lunar/lunar.msstyles/CMakeLists.txt
media/themes/Mizu/mizu.msstyles/CMakeLists.txt
media/themes/Modern/modern.msstyles/CMakeLists.txt
modules/rosapps/CMakeLists.txt
sdk/cmake/CMakeMacros.cmake

Used when we convert files to UTF16-LE during our build process. Removes duplicated code.

[CMAKE][REACTOS] Introduce a utf16le_convert() cmake helper

---

drivers/storage/partmgr/partition.c
drivers/storage/partmgr/partmgr.h

Used by some 3rd-party software (see example link below). Also, `IOCTL_VOLUME_IS_PARTITION` is an easy way to know whether a `\Device\HarddiskVolumeN` (or whatever other volume) device corresponds to one single disk partition.
- Implement `IOCTL_VOLUME_QUERY_VOLUME_NUMBER`: See usage example in: https://github.com/dansdrivers/ndas4windows/blob/7241cebfa2a2076de546b8841c2ccda8ca599a8d/mayfield/branches/spr/src/umapps/ndassvc/service/drivematch.cpp#L627
- Stubplement `IOCTL_VOLUME_IS_PARTITION`: The only type of volume we support right now is disk partition so we just return success. A more robust algorithm would be to check whether the volume has only one single extent, that covers the whole partition on which it lies upon. If this is not the case, return STATUS_UNSUCCESSFUL instead.

[PARTMGR] Implement IOCTL_VOLUME_QUERY_VOLUME_NUMBER and IOCTL_VOLUME_IS_PARTITION

---

drivers/base/kdvm/kdvm.c
drivers/base/kdvm/kdvm.h

Comply with the standard documented behaviour:
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlequalmemory#return-value
> RtlEqualMemory returns TRUE if Source1 and Source2 are equivalent; otherwise, it returns FALSE.
and
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlcomparememory#return-value
> [...] If all bytes match up to the specified Length value, the Length value is returned.

[KDVM] Fix definition of RtlEqualMemory()

---

drivers/storage/partmgr/partition.c
drivers/storage/partmgr/partmgr.c
drivers/storage/partmgr/partmgr.h

Reimplement IOCTL_MOUNTDEV_QUERY_UNIQUE_ID for MBR and GPT partitions, so that the MOUNTMGR (who sends this query to storage drivers) can retrieve something "nice" to store under `HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices`.
JIRA issue: [CORE-15575](https://jira.reactos.org/browse/CORE-15575)
The returned standard UniqueId has the following format:
- Basic volume on MBR disk: disk Mbr.Signature + partition StartingOffset (length: 0x0C)
- Basic volume on GPT disk: "DMIO:ID:" + Gpt.PartitionGuid (length: 0x18)
- Volume on Basic disk (NT <= 4): 8-byte FTDisk identifier (length: 0x08)
- Volume on Dynamic disk (NT 5+): "DMIO:ID:" + dmio VolumeGuid (length: 0x18)
- Super-floppy (single-partition with StartingOffset == 0),
or Removable media: DiskInterfaceName.
- As fallback, we use the …

[PARTMGR] Reimplement IOCTL_MOUNTDEV_QUERY_UNIQUE_ID for MBR and GPT partitions

---

base/applications/notepad/dialog.c

Telling the user it can't find the `''` string is not very helpful, it's better to just display the find dialog again.
Steps to reproduce:
1. `reg DELETE "HKCU\SOFTWARE\Microsoft\Notepad" /v searchString /f`
2. `start Notepad.exe`
3. <kbd>F3</kbd>
4. <kbd>Esc</kbd>
5. <kbd>F3</kbd>

[NOTEPAD] F3 should not display an error message when the find string is empty

---

dll/win32/setupapi/install.c

When a link section is something like `CmdLine=-1,"d:\","foo.exe"`, the root dirid should not write anything to the path. It currently accesses undefined memory when doing `FullName[wcslen(FullName) - 1] != '\\'` because `DIRID_get_string` returns an empty string for DIRID_ABSOLUTE instead of `NULL` like the code expects and this ends up prefixing the (absolute) path with a `\`.
Notes:
- This `Concatenate` function does not exist in Wine.

[SETUPAPI] Fix absolute dirid ProfileItems bug

---

base/applications/rapps/appview.cpp
base/applications/rapps/gui.cpp
base/applications/rapps/include/appview.h

- Load icons on a background thread to massively reduce loading time.
- Use SM_CXICON sized icons consistently instead of hard-coding 32 in some places.

[RAPPS] Load icons on background thread

---

base/applications/control/control.c
dll/cpl/ncpa/CMakeLists.txt
dll/cpl/ncpa/ncpa.c
dll/win32/shell32/wine/control.c

Fix some Control Panel functionalities not working when explorer.exe is not running.
JIRA issue: [CORE-19648](https://jira.reactos.org/browse/CORE-19648)
If Explorer shell is not available, use ReactOS's alternative file browser instead.

[SHELL32][CONTROL][NCPA] Add file browser fallback

---

drivers/network/dd/dc21x4/media.c

This is the network driver which is used for MSVPC 2007 and according to his author Dmitry Borisov has never been tested on real HW yet.
First and foremost: A disclaimer: I am not a driver developer. The function is marked as CODE_SEG("PAGE"), but I do assume this doesn't play any role with variable initialization.
Long story short: This looks like 'uninitialized variable read' to me at (old) line 503:
if (MiiControl & MII_CR_SPEED_SELECTION)
with the result as far as I can read the code, that the driver might chaotically decide whether it will connect with 10 or 100Mbps.
I will request a review of this PR from Dmitry Borisov.
GCC4.7.2 build warned me about that.
GCC8.4.0 build doesn't give a fuck, and does not warn. Either there is something that I don't understand yet, or the newer …

[DC21X4] Fix uninitialized variable read

---

boot/boot_images.cmake

Reverts reactos/reactos#6551
This caused the non-English programs menu items to not be populated.
JIRA issue: [CORE-12328](https://jira.reactos.org/browse/CORE-12328) will have to be reopened afterwards and approached differently
JIRA issue: [CORE-19652](https://jira.reactos.org/browse/CORE-19652) will get resolved
BEFORE:
AFTER:

Revert "[BOOT] Don't create empty CSIDL_ADMINTOOLS folder"

---

hal/halx86/apic/rtctimer.c

Fix calculation of clock rate. Previously it would go above the maximum, causing issues with KeUpdateSystemTime.

[HAL:APIC] Fix HalSetTimeIncrement

---

win32ss/gdi/ntgdi/freetype.c

_Fix SubstituteFontRecurse to work when multiple indirect Font Substitutes are needed._
JIRA issue: [CORE-19651](https://jira.reactos.org/browse/CORE-19651)
_In SubstituteFontRecurse, after an output is found, then the next input should be the previous output._
Before/After:

[FREETYPE] Multiple indirect Font Substitutes fix for Factusol

---

dll/win32/shell32/dialogs/folder_options.cpp
dll/win32/shell32/shell32.rc

- Enable visual styles for RunDLL using ~ReactOS default DLL manifest~ manifest resource ID 123.
- Dialog: Use `MAKEINTRESOURCE` instead of `LoadString`
Before:
After:

[SHELL32] Folder options: Enable visual styles for RunDLL

---

base/applications/regedit/childwnd.c

CORE-19576
_Fix regedit's splitter redraw issues._
JIRA issue: [CORE-19576](https://jira.reactos.org/browse/CORE-19576)
_Add InvalidateRect to redraw right pane on splitter move._

[REGEDIT] Fix splitter move redraw issues.

---

win32ss/user/ntuser/menu.c

CORE-17838
_Fix secondary popup window position when clicking near the bottom right of the desktop._
JIRA issue: [CORE-17838](https://jira.reactos.org/browse/CORE-17838)
_Secondary popup window is one menu position too high when it is on the left side and has to extend upwards._
_Check if menu needs to move down one menu position and if it will fit on the screen, then move it down._

[NTUSER] Fix popup menu positioning for Miranda IM

---

dll/win32/browseui/internettoolbar.cpp
dll/win32/browseui/internettoolbar.h
dll/win32/browseui/resource.h
dll/win32/browseui/settings.cpp
dll/win32/browseui/shellbrowser.cpp
sdk/include/reactos/browseui_undoc.h

Save/Restore the visibility state of the ShellBrowser toolbar/addressbar/statusbar. This is somewhat related to [CORE-9094](https://jira.reactos.org/browse/CORE-9094).
Windows shares the state of the Go button and the locked state between Explorer and Internet Explorer but the band/bar states are not shared.
Notes:
- Seems to fix [CORE-17236](https://jira.reactos.org/browse/CORE-17236).
- The stream layout does not match Windows so it uses a different name. The toolbar customize dialog needs to be fixed before it makes sense trying to save the toolbar state and the layout of other bands.

[BROWSEUI] Save/Restore ShellBrowser bar states

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/CIDLDataObj.cpp
dll/win32/shell32/brfolder.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/shfldr.h
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/wine/clipboard.c

Support IContextMenu for the desktop folder in Explorer tree and SHBrowseForFolder.

[SHELL32] Implement the desktop folder menu for Explorer tree

---

dll/win32/browseui/internettoolbar.cpp
dll/win32/browseui/internettoolbar.h

Fix for JIRA issue [CORE-19659](https://jira.reactos.org/browse/CORE-19659)
Addendum to https://github.com/reactos/reactos/pull/7035
I'm still not sure why `ShowDW` on the InternetToolbar(rebar) should propagate to all its band children and on top of this, why the menu would care.
Also implemented `IBandSite::EnumBands` and the EnumBands helper function is designed to also ease the implementation of `GetBandObject` later.

[BROWSEUI] Ensure menu dock site is visible when parent ShowDW is called

---

drivers/storage/mountmgr/database.c
drivers/storage/mountmgr/device.c
drivers/storage/mountmgr/mntmgr.h
drivers/storage/mountmgr/mountmgr.c

1. Correct "NoAutoMount" mixup.
This "NoAutoMount" member wasn't consistently used. Sometimes it was
used correctly, some other times it was used as "not NoAutoMount" i.e.
"AutoMount" enabled. (Original code author may not have fully understood
the purpose).
Fix this consistently throughout the source, and fix also some comments.
2. Fix initial sending of device online notification.
- MountMgrMountedDeviceArrival():
Fix the conditions under which the device's online notifications are
skipped (SkipNotifications == TRUE) and fix the code comments.
- QueryDeviceInformation():
Repurpose the the "Valid" parameter to something that actually makes sense:
checking for fault-tolerant volume.
See corresponding commit log for more details.
~~3. Revert commit 4359f488386c604c2e67a03c1fadadb27f40f1ea …

[MOUNTMGR] Correct "NoAutoMount" mixup; Fix initial sending of device online notification

---

base/applications/games/winmine/main.c
base/applications/mscutils/eventvwr/eventvwr.c
base/shell/progman/group.c
base/shell/progman/main.c
dll/cpl/console/layout.c
dll/win32/comctl32/draglist.c
dll/win32/comctl32/toolbar.c
dll/win32/msgina/shutdown.c
dll/win32/shell32/dialogs/dialogs.cpp
win32ss/user/winsrv/consrv/frontends/gui/conwnd.c

Fix wrong `MAKEINTRESOURCEW()` macro usage cases in `LoadCursorW()` system-wide. MSDN documentation for this function states we need to use `MAKEINTRESOURCEW()` macro only for internal application-defined cursors (loaded from the app instance specified by `hInstance` parameter), but not for system-defined cursors (those begin with `IDC_`* prefix), in case when `hInstance` is `NULL`. So get rid from `MAKEINTRESOURCEW()` macro usage for all cases when `hInstance` parameter is `NULL`. And on the contrary, when `hInstance` is valid and points to the application instance, then use it for the resource identifier.

[REACTOS] Fix LoadCursorW() incorrect usage cases

---

base/system/userinit/livecd.c

The LiveCD start dialog was not localized.
- Just call `SetThreadLocale` after `InitializeDefaultUserLocale` call.
Choose Russian for example...
BEFORE:
The LiveCD start dialog was not localized.
AFTER:
The LiveCD start dialog has been localized.

[USERINIT] LiveCD: Set UI language

---

dll/win32/shell32/COpenWithMenu.cpp
dll/win32/shell32/dialogs/filedefext.cpp
dll/win32/shell32/dialogs/filetypes.cpp

Fix file association UX.
JIRA issue: [CORE-19670](https://jira.reactos.org/browse/CORE-19670)
- Check the return value of `shell32!SHOpenWithDialog` function.
- If changed, then update the UI display and internal data.
- Use `OAIF_FORCE_REGISTRATION` flag.
https://github.com/reactos/reactos/assets/2107452/f00b9407-06f3-4808-af6d-a1f2c9290642

[SHELL32] Refresh UI on assoc change (SHOpenWithDialog)

---

dll/win32/shell32/shlexec.cpp

Reduce code. Simplify code logic. Ensure leak zero.
JIRA issue: [CORE-17482](https://jira.reactos.org/browse/CORE-17482)
- Use `CHeapPtr<WCHAR, CLocalAllocator>` for allocation/freeing.

[SHELL32] shlexec.cpp: Automate buffer alloc/free

---

modules/rostests/apitests/gdi32/MaskBlt.c

JIRA issue: [CORE-13133](https://jira.reactos.org/browse/CORE-13133)
- Add `ok_err` tests for error code.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.

[GDI32_APITEST] Enhance MaskBlt testcase for error code

---

dll/win32/imm32/ime.c
win32ss/user/ntuser/ime.c

Reduce log spams that @julenuri reported.
- Use `Imm32IsCrossThreadAccess` instead of `IS_CROSS_THREAD_HIMC` in `ImmSetCompositionWindow` function.
- Reduce `ERR` logging in `NtUserQueryInputContext` function.

[IMM32][NTUSER] Reduce a little IMM spams

---

base/shell/explorer/trayprop.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/dialogs/general.cpp
dll/win32/shell32/dialogs/view.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/wine/shellord.c
dll/win32/shell32/wine/shpolicy.c
sdk/include/psdk/shlobj.h
sdk/include/reactos/shellutils.h
sdk/include/reactos/shlwapi_undoc.h
sdk/include/reactos/undocshell.h

These settings are cached per-process (and invalidated by the global counter). This should reduce the number of registry reads performed by DefView and CFSFolder.
Notes:
- `SSF_SHOWEXTENSIONS` is "inverted" because the registry value is the negative "HideFileExt".
- Pardon the macros, working with the bit fields and masks in `SHELLSTATE` is cumbersome.
- The macros in shlwapi are to help with the transition to the [documented](https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/ne-shlwapi-shglobalcounter) NT6 version of the global counters.

[SHELL32][EXPLORER][SHLWAPI][SDK] Implement SHGetSetSettings

---

base/applications/regedit/listview.c

REG_NONE is usually 0 bytes but can be any size. The binary display string for empty values is better than DWORD and also matches Windows.

[REGEDIT] Display REG_NONE as binary

---

base/shell/explorer/taskswnd.cpp
dll/win32/comctl32/toolbar.c

The ampersand (`&`) a.k.a. prefix of `DrawText` are specially treated for adding underscores.
We have to fix drawing on toolbar button with `BTNS_NOPREFIX` style.
JIRA issue: [CORE-11619](https://jira.reactos.org/browse/CORE-11619)
- Delete DT flags hack in `taskswnd.cpp`.
- Add `TOOLBAR_GetButtonDTFlags` helper function.
- Extend `TOOLBAR_DrawString` parameters for the button info.
- Fix `DrawText` flags for drawing when the button has `BTNS_NOPREFIX` style.
BEFORE (without hack):
There is underscore on taskbar button.
AFTER:
Fixed.

[EXPLORER][COMCTL32] Toolbar: Fix text with BTNS_NOPREFIX

---

win32ss/user/user32/windows/mdi.c

Since my machine performance became lower, we have to adjust timeout to get correct pattern of `user32!TileWindows` function.
JIRA issue: [CORE-19674](https://jira.reactos.org/browse/CORE-19674)
- Adjust timeout value in `QuerySizeFix` function.
BEFORE:
AFTER:

[USER32] TileWindows: Adjust timeout of QuerySizeFix

---

base/shell/explorer/taskswnd.cpp
base/shell/explorer/traywnd.cpp

Reduce system freezing on `Win+D`.
Normal minimizing causes message transfer.
If the window was hanging, then it fell into endless message loop. (We have to support `SW_FORCEMINIMIZE`)
JIRA issue: [CORE-19673](https://jira.reactos.org/browse/CORE-19673)
- In `CanBeMinimize` function of `traywnd.cpp`, check the return value of `IsHungAppWindow` function.
- Before minimizing, check the value of `IsHungAppWindow(...)` in `taskswnd.cpp`.
BEFORE:
`Win+D` won't work expectedly if any hung apps.
`Win+D` has worked within 6 seconds even if any hung apps.

[EXPLORER] Check IsHungAppWindow before minimizing

---

base/applications/regedit/framewnd.c

This PR is just cleanup.
* Strip unneeded WM_TIMER
(an addendum to 0.4.15-dev-7915-g d383b20b01e3528f829068165a2dd0965f869681
where the WM_TIMER has also been stripped from childwnd.c)
There is no SetTimer()-call within the whole app.
* Strip a tab-character before toggle_child
* Also strip some comments with outdated signatures, they are pure bloat, and misleading even.

[REGEDIT] Strip unneeded WM_TIMER, formatting

---

dll/cpl/timedate/lang/bg-BG.rc
dll/cpl/timedate/lang/da-DK.rc
dll/cpl/timedate/lang/de-DE.rc
dll/cpl/timedate/lang/el-GR.rc
dll/cpl/timedate/lang/en-US.rc
dll/cpl/timedate/lang/es-ES.rc
dll/cpl/timedate/lang/et-EE.rc
dll/cpl/timedate/lang/eu-ES.rc
dll/cpl/timedate/lang/he-IL.rc
dll/cpl/timedate/lang/nl-NL.rc
dll/cpl/timedate/lang/no-NO.rc
dll/cpl/timedate/lang/pt-BR.rc
dll/cpl/timedate/lang/sk-SK.rc
dll/cpl/timedate/lang/sq-AL.rc
dll/cpl/timedate/lang/sv-SE.rc
dll/cpl/timedate/lang/th-TH.rc
dll/cpl/timedate/lang/uk-UA.rc

Fixes a typo in Timedate Control Panel's English strings IDS_INETTIMESUCFILL and IDS_INETTIMEWELCOME. The indefinite article is 'an' when it is before a vowel sound.

[TIMEDATE] Fix a typo in en-US locale

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CRegFolder.cpp
dll/win32/shell32/shfldr.h

- When the address-bar asks for FORADDRESSBAR, that should be prioritized over FORPARSING.
- DefView should not enter "special status-bar mode" when viewing the Desktop as a shell folder in the normal IShellBrowser (DefView in Progman/desktop continues to use the old mode).

[SHELL32] Display Desktop folder name in IShellBrowser correctly

---

win32ss/gdi/gdi32/objects/dc.c

There is a bug in Midori installer 0.5.11 that probably causes overflow and bad rendering.
In Windows it is visible as FillRect( 0x89011a1f, 0x0019f87c, 0xabababab ), in ReactOS again as SetBkMode( 0xb5010fce, -1546139919 ).
Unfortunately this bug makes the text in ReactOS hard to read (no background).
Jira issue: [CORE-19656](https://jira.reactos.org/browse/CORE-19656)
After a number of attempts to get the same behavior, I haven't found a way to fix it without a hack so that the installer looks identical to Windows. So I added at least a fix for the incorrect value in SetBkMode. This shouldn't matter anywhere. It may not look the same as on Windows, but the text will at least be readable.

[GDI32] Avoid invalid input in SetBkMode CORE-19656

---

sdk/include/ndk/rtlfuncs.h
win32ss/CMakeLists.txt
win32ss/include/ntuser.h
win32ss/user/ntuser/main.c
win32ss/user/rtl/image.c
win32ss/user/user32/CMakeLists.txt
win32ss/user/user32/windows/window.c

This value is needed for `SetWindowPlacement` and IMM.
JIRA issue: [CORE-19675](https://jira.reactos.org/browse/CORE-19675)
- Add `RtlGetExpWinVer` function into `win32ss/user/rtl/image.c`.
- Add `RtlGetExpWinVer` prototype into `win32ss/include/ntuser.h`.
- Delete `RtlGetExpWinVer` definition in `win32ss/user/user32/windows/window.c`.
- Populate `THREADINFO.dwExpWinVer` and `CLIENTINFO.dwExpWinVer` by using `RtlGetExpWinVer` in `InitThreadCallback` function.

[NTUSER][USER32] Populate dwExpWinVer

---

sdk/lib/rtl/heap.c

_Avoid some ASSERT corner cases._
JIRA issue: [CORE-18196](https://jira.reactos.org/browse/CORE-18196)
Edit: I just realized that @ThFabba has another PR for this here PR #4915.
_Place IF's around some heap.c ASSERT's to allow them to avoid corner cases._

[RTL] Avoid some corner case ASSERTS in heap.c and fix heap allocations larger than MAXUSHORT.

---

dll/ntdll/def/ntdll.spec
dll/shellext/shellbtrfs/reactos.cpp
media/doc/WINESYNC.txt
sdk/include/ndk/rtlfuncs.h
sdk/lib/rtl/actctx.c
sdk/tools/winesync/rtl.cfg

Sync actctx.c to wine-5.18. Why this version? Because that is about the earliest version that guarantees consistent sync of the entire file, since code was in a weird state of being synced to multiple different versions.
The regression in comctl32:animate and comctl32:button are due to user heap exhaustion.

[RTL] Sync actctx.c to wine-5.18

---

base/shell/cmd/locale.c

JIRA issue: [CORE-13848](https://jira.reactos.org/browse/CORE-13848)
- Simply use the result of `GetDateFormat` function in `%DATE%` environment variable and the `DATE` command.
Win2k3:

[CMD] DATE: Simply use short date without weekday

---

sdk/include/reactos/ui/layout.h
win32ss/user/user32/windows/dialog.c

Fixes CORE-19585
I've added the corresponding patch that fixes the keyboard navigation bug that makes the cursor get stuck, according to [CORE-19585](https://jira.reactos.org/browse/CORE-19585). ~The patch just now checks for SBS_SIZEBOX and SBS_SIZEGRIP.~ After some research, this patch just adds WS_GROUP to layout.h to avoid getting the cursor stuck. 
With this path, the bug is fixed:

[SDK] Fixed "Move to... & Copy to..." dialog broken button navigation

---

base/shell/cmd/cmdinput.c
boot/bootdata/hivedef.inf
boot/bootdata/hivesft.inf

Improve compatibility.
JIRA issue: [CORE-8002](https://jira.reactos.org/browse/CORE-8002)
- Fix the default values of `AutoCompletionChar` and `PathCompletionChar` in `cmd.exe`.
- Populate `"SOFTWARE\Microsoft\Command Processor"` registry key like Win2k3 does.
WinXP Japanese (`HKLM`):
Populated.
WinXP Japanese (`HKCU`):
Populated.
Win2k3 (`HKLM`):
Populated.
Win2k3 (`HKCU`):
Populated.
ReactOS (AFTER, `HKLM`):
Populated.
ReactOS (AFTER, `HKCU`):
Populated.

[CMD][BOOTDATA] Populate 'Command Processor' registry data

---

dll/win32/browseui/CAutoComplete.cpp

The auto-complete window and the IME candidate window were conflicting each other.
- Call `HideDropDown` method when processing `IMN_OPENCANDIDATE` message.
IMM/IME is currently unstable.
Works as expected.
FAILED. Conflicting.
Works as expected.

[BROWSEUI] AutoComplete: Close before opening IME candidates

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/COpenWithMenu.cpp

The default value in the shell key specifies the default verb(s) as specified on MSDN:
> Verbs can be ordered by specifying the default value of the Shell subkey for the association entry. This default value can include a single item, which will be displayed at the top position of the shortcut menu, or a list of items separated by spaces or commas. In the latter case, the first item in the list is the default item, and the other verbs are displayed immediately below it in the order specified.
Because our CDefaultContextMenu builds the menu in a different order than Windows, I cannot guarantee that the verbs will always be in the correct order but it's the best we can do for now.
While the order is not crucial, parsing the verb list is. Otherwise we will execute the wrong verb:
```BAT …
```

[SHELL32] CDefaultContextMenu must respect the default verb list

---

win32ss/user/ntuser/nonclient.c

CORE-11569
I_Kill_Bugs patch.
_Ad Muncher does not close when left-clicking with mouse button on the title bar "X"._
JIRA issue: [CORE-11569](https://jira.reactos.org/browse/CORE-11569)
_Change test from 'pWnd->style' to 'pWnd->pcls->style' to check for CS_NOCLOSE._
_Wrong parameter was selected for checking previously._

[NTUSER] Check class style for CS_NOCLOSE instead of window style

---

dll/win32/browseui/CAutoComplete.cpp
dll/win32/browseui/CAutoComplete.h

Unexpectedly remaining AutoComplete list is annoying.
JIRA issue: [CORE-19685](https://jira.reactos.org/browse/CORE-19685)
- Add `CAutoComplete::m_bEditHasFocus` to watch focus.
- Update `m_bEditHasFocus` on `WM_SETFOCUS` and `WM_KILLFOCUS` messages on Edit window procedure.
- Don't open AutoComplete list when `m_bEditHasFocus` was `FALSE`.
BEFORE:
AFTER:

[BROWSEUI] Check focus before opening AutoComplete

---

base/shell/cmd/cmd.c

The switch enables or disables file/path completion in a unique
CMD instance. The defaulted values for the completion characters
are those mentioned in CMD's help (see also MSDN[^1]):
File: Ctrl-F (0x06); Directory: Ctrl-D (0x04)
Manual tests show that only /F:OFF explicitly disables completion.
Otherwise, using /F(anything else following) always enables completion
with the specific values described above.
JIRA issue: [CORE-8002](https://jira.reactos.org/browse/CORE-8002)
[^1]: For additional details, see also
https://technet.microsoft.com/en-us/library/cc978715.aspx
https://technet.microsoft.com/en-us/library/cc940805.aspx

[CMD] Implement /F[:ON|:OFF] switch for file/path completion

---

dll/win32/uxtheme/nonclient.c
win32ss/user/ntuser/defwnd.c

Addendum to commit 71bed0f5f8 (PR #7123).
The problem in uxtheme was introduced in commit 685084b63c (as part
of a fix for CORE-17203), because it was a copy-paste and adaptation
of the corresponding code in `ntuser/nonclient.c!NC_DoButton()`.
The bugs in `win32ss/user/ntuser/defwnd.c` (and `nonclient.c` as fixed by
the previous commit) were in turn introduced from the migration of menu
and related code from user32 to win32k, see commit 6dfa71c487 (r68904).
JIRA issues: [CORE-11569](https://jira.reactos.org/browse/CORE-11569), [CORE-19684](https://jira.reactos.org/browse/CORE-19684)

[UXTHEME][NTUSER] Check class style for CS_NOCLOSE instead of window style

---

dll/shellext/fontext/CFontExt.cpp

Fix font enumeration and AutoComplete on `%WINDIR%\Fonts`.
- Replace `if (dwFlags == SHGDN_FORPARSING)` with `if (dwFlags & SHGDN_FORPARSING)`.
Win2k3:
BEFORE:
AFTER:

[FONTEXT] Fix CFontExt::GetDisplayNameOf for SHGDN_FORPARSING

---

dll/win32/browseui/parsecmdline.cpp
dll/win32/browseui/shellfind/CFindFolder.cpp

Fix memory leaks. `SHStrDupW` uses `CoTaskMemAlloc`. `StrDupW` uses `LocalAlloc`. They are different.
- Use `SHStrDupW` instead of `StrDupW`.

[BROWSEUI] Fix confusion of StrDupW and SHStrDupW

---

win32ss/gdi/ntgdi/freetype.c

Don't free the linked font name if it's already NULL. Since it is allocated only once (when loading the font name from Registry), it should be freed only once too. All subsequent freeing attempts will result in invalid pool freeing. This fixes the 0xC2 BAD_POOL_CALLER bugcheck when trying to resize window (and draw more text) from soundcloud.com in K-Meleon 76.5.4 Goanna engine and when switching between channels (during redrawing the text) in DiscordMessenger v1.06 Beta. Addendum to 0f9e889736f01cef58fd50cd1f5558becbe882d5.
JIRA issue: [CORE-19681](https://jira.reactos.org/browse/CORE-19681)
K-Meleon 76.5.4 Goanna engine: the bug is not reproducible anymore:
DiscordMessenger 1.06 Beta: the bug is not reproducible anymore:

[NTGDI] FontLink: avoid invalid font name buffer freeing

---

dll/appcompat/apphelp/apphelp.c
dll/appcompat/apphelp/sdbapi.c

- Fix MAX_GUID_STRING_LEN define; use it for one buffer
- SdbGUIDToString(): use sizeof(WCHAR) instead of '2'

[APPHELP] Fix MAX_GUID_STRING_LEN define; use it for one buffer

---

win32ss/CMakeLists.txt
win32ss/gdi/ntgdi/gdidbg.c
win32ss/user/ntuser/main.c
win32ss/user/ntuser/ntuser.c
win32ss/user/ntuser/power.c
win32ss/user/ntuser/power.h
win32ss/user/ntuser/win32kdebug.h
win32ss/win32kp.h

In order for the NT power manager to interact with the Win32 subsystem (thus the whole rest of the system), the Win32 kernel-mode subsystem provides a mechanism that communicates with the kernel power manager via power callouts (Windows calls them **power requests** as per PDB symbols but to avoid confusions  with [these power requests and et al](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-posetpowerrequest), I will personally be calling them **power callouts**).
Such mechanism enters in action as soon as Win32 callout routines are estabilished with the `PsEstablishWin32Callouts()` function.
The NT power manager, the power policy manager respectively, invokes a power callout to denote an exceptional phenomena as a result of power policies or capabilities …

[NTUSER] Stubplement the Win32 power management

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shlexec.cpp

JIRA issue: [CORE-14177](https://jira.reactos.org/browse/CORE-14177)
JIRA issue: [CORE-17482](https://jira.reactos.org/browse/CORE-17482)
- Add `SHELL_InvokePidl` helper function.
- Call `SHParseDisplayName` and `SHELL_InvokePidl` in a specific condition.
`shell:sendto` and `::{CLSID}`  won't work.
`shell:sendto` and `::{CLSID}`  work well.

[SHELL32] shlexec.cpp: Parse 'shell:' and '::{CLSID}'

---

dll/win32/shell32/CDefView.cpp

The statusbar should not be updated during drag operations.
There is still a problem with selection changes during drag&drop (sometimes leaves a folder selected on aborted drop) but that should be solved by using `LVIS_DROPHILITED` (I'll look into that after the comctl32 wine merge is completed).

[SHELL32] Don't update statusbar during drag operation

---

win32ss/user/ntuser/menu.c

_Fix popup menu position on menu item half off the left side of the screen._
JIRA issue: [CORE-16729](https://jira.reactos.org/browse/CORE-16729)
_Change menu popup calculated x position when menu item is part way off the left of the screen._
_Mark Jansen's revised positioning code made this fairly simple._

[NTUSER] Fix popup menu position on menu item partly off the left screen

---

base/shell/cmd/batch.c

Recursing batch was prevented by `ClearBatch` call.
JIRA issue: [CORE-18093](https://jira.reactos.org/browse/CORE-18093)
- Check `bSameFn` variable.
- If it was `TRUE`, don't call `ClearBatch` function.
Win2k3:
Successful.
FAILED.
Successful.

[CMD] Batch: Don't ClearBatch if bSameFn

---

base/shell/cmd/cmd.h
base/shell/cmd/misc.c

This `GetPathCase` function does resolve the path with wildcard pattern, and fix the alphabet cases, by using `kernel32!FindFirstFile` function.
Enable wildcard at the middle of the file path in `cmd.exe` by fixing this function.
JIRA issue: [CORE-6609](https://jira.reactos.org/browse/CORE-6609)
JIRA issue: [CORE-13906](https://jira.reactos.org/browse/CORE-13906)
- Fix `GetPathCase` function for supporting wildcard at the middle of the file path.
- Make `GetPathCase` string-safe.
- Optimize `GetPathCase`.
BEFORE:
FAILED.
AFTER:
Successful.

[CMD] Fix GetPathCase function

---

base/applications/regedit/childwnd.c
base/applications/regedit/main.c
base/applications/regedit/regedit.h

Handle <kbd>Ctrl</kbd><kbd>Backspace</kbd> in the AddressBar like Windows 10 by deleting spans of special and/or normal characters.
Notes:
- Also fixes a bug where <kbd>Del</kbd> does not work in the AddressBar nor during Tree/List label edit because it gets eaten by the accelerator.
- Removed the code that handles <kbd>Ctrl</kbd><kbd>A</kbd> in the AddressBar because the Edit control does this out of the box.

[REGEDIT] Handle Ctrl+Backspace in AddressBar

---

base/shell/explorer/explorer.cpp
base/shell/explorer/precomp.h
base/shell/explorer/startup.cpp

Windows executes RunOnce[Ex] before creating the desktop. To verify, turn off the welcome screen (so you see what is going on) and add a RunOnce entry that executes `cmd.exe /C ping example.com`.
Notes:
- RunOnce[Ex] is [not executed by normal users](https://support.microsoft.com/en-us/topic/876472b8-238c-8302-eb9d-ae38226ee76d).
- Fixes JIRA issue [CORE-19501](https://jira.reactos.org/browse/CORE-19501) for the BootCD case. `iexplore.exe /RegServer` creates the icon entry in the registry and since creating the desktop happens after, the icon path is now available in the registry.

[EXPLORER] Execute RunOnce[Ex] before desktop is created

---

dll/shellext/cryptext/cryptext.rc
dll/shellext/cryptext/lang/cs-CZ.rc
dll/shellext/cryptext/lang/sk-SK.rc

Adds the Czech and Slovak translations of CryptExt Shell Extension.

[CRYPTEXT] Add Czech (cs-CZ) and Slovak (sk-SK) translations

---

base/applications/rapps/loaddlg.cpp

CORE-19666
Should be good until 2027: https://crt.sh/?id=12396132897

[RAPPS] Add new Let's Encrypt issuer certificate

---

dll/win32/shell32/shlexec.cpp
modules/rostests/apitests/shell32/ShellExecuteEx.cpp

The following program should successfully open notepad:
```c
#include <windows.h>
int main(void)
{
ShellExecuteA(NULL, NULL, "notepad", NULL, "(An invalid directory)", SW_SHOWNORMAL);
}
```
- Implement parsing `SHELLEXECUTEINFO.lpDirectory`.
- Enhance `ShellExecuteEx` testcase for invalid directory.

[SHELL32][SHELL32_APITEST] ShellExecute should accept invalid directory

---

dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/droptargets/CFSDropTarget.cpp
dll/win32/shell32/shldataobject.cpp

- Ask for the editing name instead of the parsing name to get a suitable shortcut name for non-FS items.
- Don't do the classical ROS error of getting the parsing path of a PIDL and then calling `ILCreateFromPathW` and expecting this to always give you a valid PIDL.
- Properly limit the drag&drop menu to valid options.
- Don't write the link info if the path is a pointer to an empty string.
Notes:
- While it creates shortcuts to Control Panel .cpl items that look valid in a hex editor (similar to Windows) and have the correct icon for .cpls that implements multiple items, `ShellExecute` is not able to launch them. This problem needs to be solved in `CControlPanelFolder`s menu handling.
- `_BindToObject` fails when given a PIDL item on the desktop. Using a helper function that knows how to …

[SHELL32] Use correct PIDL and name when dropping to create a shortcut

---

boot/bootdata/livecd.inf

JIRA issue: [CORE-19202](https://jira.reactos.org/browse/CORE-19202)
- Add `CLSID_Internet` settings to `boot/bootdata/livecd.inf`.
BootCD (AFTER):
Correctly displayed.
`Comments` is OK.
LiveCD (AFTER):
Correctly displayed.
`Comments` is OK.

[BOOTDATA] LiveCD: Fix Internet Browser icon

---

dll/win32/browseui/explorerband.cpp
dll/win32/browseui/explorerband.h
dll/win32/shdocvw/CFavBand.cpp
dll/win32/shdocvw/CFavBand.h
sdk/include/reactos/shlobj_undoc.h

Use correct interface definition for standardization.
JIRA issue: [CORE-19686](https://jira.reactos.org/browse/CORE-19686)
- Use `INamespaceProxy` interface that is documented in the Microsoft official site ( https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ee318424%28v=vs.85%29 ) and Windows 10 PSDK (see um/ienamespacecontrol.idl file).

[BROWSEUI][SHDOCVW][SDK] Fix INamespaceProxy interface

---

base/applications/rapps/cabinet.cpp

- `MultiByteToWide`  had a bug where it calculated the WCHAR size using the codepage passed in but always used `CP_UTF8` for the actual conversion.
- Use CP_UTF8 to convert cab filenames if [the UTF attribute](https://msdn.microsoft.com/en-us/library/bb267310.aspx#cffile) is set.

[RAPPS] Fix CAB codepage handling

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/shlexec.cpp
dll/win32/shell32/wine/classes.c

Invoking the IDList as if the target was double-clicked in Explorer fixes shortcuts to control panel items (both .cpl and ShellFolder types).
Notes:
- The shortcut has to be created by #6999 for shortcuts to .cpl files to work correctly.
JIRA issue: [CORE-19690](https://jira.reactos.org/browse/CORE-19690)

[SHELL32] Invoke the ItemIDList of shortcuts

---

dll/win32/browseui/shellbrowser.cpp
dll/win32/shell32/CDefView.cpp

PR #7141 causes calls to `IShellBrowser::BrowseObject` while the shell browser is in the middle of destruction and the ShellView ListView has already been destroyed and DefView is not prepared for this.
Notes:
- `m_mtxBlockNavigate` in explorerband.cpp could probably be used to block `CExplorerBand::OnSelectionChanged` during `TreeView_DeleteAllItems` in `CExplorerBand::DestroyExplorerBand` but putting the protection in the shell browser instead should protect us from similar situations with other bands in the future.
- The protection in CDefView is not strictly required when hosted by our IShellBrowser after this but better safe than sorry.

[BROWSEUI][SHELL32] Ignore navigation requests during browser destruction

---

dll/win32/shell32/shlexec.cpp

Based on @Doug-Lyons `shlexec-winR-fonts.patch`. #4932 (f691efefc) introduced some regression.
JIRA issue: [CORE-19688](https://jira.reactos.org/browse/CORE-19688)
- Call `SearchPathW` function before `PathFindOnPathExW` call in `ShellExecCmdLine` function.
BEFORE:
`Win+R fonts` cannot open `Fonts`.
AFTER:
`Win+R fonts` can open `Fonts`.

[SHELL32] ShellExecCmdLine: Use SearchPathW

---

dll/win32/shell32/shellrecyclebin/recyclebin_v5.h

Improve interoperability between C and C++.
- Rewrite `IRecycleBin5` interface by using `STDMETHOD` and `DECLARE_INTERFACE_` macro.

[SHELL32] Use DECLARE_INTERFACE_ for IRecycleBin5

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/shlexec.cpp
sdk/include/reactos/shellutils.h

The parameters must be propagated. CShellLink is the most extreme case: `ShellExecuteExW(SEE_MASK_INVOKEIDLIST)` ➜ `CDefaultContextMenu::InvokeCommand` ➜ `ShellExecuteExW(SEE_MASK_IDLIST)`.

[SHELL32] Forward CDefaultContextMenu::InvokeCommand parameters to ShellExecute

---

boot/bootdata/hivesft.inf
dll/win32/setupapi/install.c
media/inf/syssetup.inf

This avoids the console popups on first boot.
Notes:
- I changed it from RunOnce to RunOnceEx because that is executed first.
- I have tested the code from RunOnceEx to completion but not on a real bootcd.
- I don't know if it is acceptable to add these entries to syssetup.inf but it was the most suitable existing inf file.

[INF][BOOTDATA][SETUPAPI] Use Inf instead of Cmd.exe to register IExplore

---

base/applications/rapps/geninst.cpp

In deep directory trees, remove the empty parent directories after the children.
Notes:
- Not updating the `success` variable because cleaning up empty directories is "best-effort".

[RAPPS] Uninstall empty directories after its children

---

.github/labeler.yml

Automatically add `input method` label.
- Modify `.github/labeler.yml`.

[GITHUB] labeler.yml: Add 'input method' label

---

base/setup/usetup/usetup.c

InstallDirectoryPage(): Pressing ESC erases the whole path line.
A similar behaviour exists in Windows <= 2003 text-mode setup, on this screen:
When the user presses ESC key, zero out `InstallDir` buffer and set the cursor position to zero before redrawing the input line and reading keyboard input.

[USETUP] InstallDirectoryPage(): Pressing ESC erases the whole path line

---

sdk/include/reactos/undocuser.h
win32ss/user/ntuser/input.h
win32ss/user/ntuser/kbdlayout.c
win32ss/user/ntuser/keyboard.c

- Rename `KLF_UNLOAD` as `KL_UNLOAD`.
- Move it from `win32ss/user/ntuser/input.h` to `sdk/include/reactos/undocuser.h`.
- Add `UKL_NOACTIVATENEXT` constant and use it.

[SDK][NTUSER] s/KLF_UNLOAD/KL_UNLOAD/

---

dll/win32/rasdlg/lang/ro-RO.rc

which have been introduced during 0.4.15-dev'ing when romanian resources were updated.
C:\buildbot_config\worker\Build_MSVC_x86\build\dll\win32\rasdlg\lang/ro-RO.rc(508) : warning RC4206 : title string too long; truncated at 256
C:\buildbot_config\worker\Build_MSVC_x86\build\dll\win32\rasdlg\lang/ro-RO.rc(521) : warning RC4206 : title string too long; truncated at 256
see MSVC builder https://build.reactos.org/#builders/1/builds/24117
The fix respects the rule 1 of the Romania translation notes also (with the forbidden characters), same as Andreis commit did.
Also fix a few places where ".  " was the case (unintended double-space). I haven't checked other languages for double-space yet, but I don't want to make this PR larger than necessary.

[RASDLG] ro-RO.rc: Fix 2 compiler warnings RC4206

---

base/setup/lib/setuplib.c
base/setup/lib/setuplib.h
base/setup/usetup/usetup.c

Move IsValidPath() back into setuplib for reusability (in the GUI setup).
Reverts the `IsValidPath()` move done in commit 9c64b57dc.
- Turn `IsValidPath()` into a `IsValidInstallDirectory()` helper function
available in the setuplib, so that it can also be used in the GUI setup.
- Introduce a `IS_VALID_INSTALL_PATH_CHAR()` macro.

[SETUPLIB][USETUP] Move IsValidPath() back into setuplib for reusability

---

base/setup/lib/CMakeLists.txt
base/setup/lib/setuplib.c
base/setup/lib/unittests/CMakeLists.txt
base/setup/lib/unittests/IsValidInstallDirectory.c
base/setup/lib/unittests/precomp.h
base/setup/lib/unittests/testlist.c

- Add unit-tests for the setuplib.
- Improve IsValidInstallDirectory() behaviour.
See also commits d329fbebf (r66995), 7c3f4c94a (r68307), and 16daf6700.
The function verifies that each path component of the directory is
a valid 8.3 name, not . or .. nor empty. This behaviour is compatible
with what can be observed from Windows XP/2003 installer.
(To reliably test this with the Windows installer, you need to modify
the TXTSETUP.SIF DefaultPath value in the [SetupData] section.)
JIRA issues: [CORE-6149](https://jira.reactos.org/browse/CORE-6149), [CORE-6179](https://jira.reactos.org/browse/CORE-6179), [CORE-9529](https://jira.reactos.org/browse/CORE-9529)

[SETUPLIB] Add unit-tests for the setuplib. Improve IsValidInstallDirectory() behaviour.

---

ntoskrnl/cc/view.c
ntoskrnl/include/internal/cc.h

JIRA issue: [CORE-19664](https://jira.reactos.org/browse/CORE-19664)
- ~`CcRosLookupVacb` : Add a VACB refcount check to ensure that the returned VACB is valid~ **UPDATE:** This is a hack and was removed.
- ~`CcRosReleaseVacb`: Do inc-dec refcount inside master lock~ **UPDATE:** Not working, still BSoD.
- `CcFlushCache` : Call `CcRosReleaseVacb` when `CcRosFlushVacb` fails (`CcRosLookupVacb` adds a refcount)
- Protect `CcFlushCache` call with a mutex

[NTOS:CC] Fix assertion failed in CcRosReleaseVacb

---

dll/win32/shell32/shlexec.cpp

- Don't expand the application name unless `SEE_MASK_DOENVSUBST` is not specified.

[SHELL32] shlexec: Do not expand without SEE_MASK_DOENVSUBST

---

dll/win32/browseui/aclistisf.cpp
dll/win32/browseui/aclistisf.h
dll/win32/shell32/wine/shellpath.c

Fix shell path parsing.
JIRA issue: [CORE-19693](https://jira.reactos.org/browse/CORE-19693)
JIRA issue: [CORE-19694](https://jira.reactos.org/browse/CORE-19694)
- Fix `CACListISF` class by using PIDL attributes.
- Use `min` macro instead of `max` macro in `Shell_ParseSpecialFolder` function.
BEFORE:
10 failures.
AFTER:
6 failures.
AFTER:
Able to open `"shell:windows\fonts"`.
AFTER:
AutoComplete is working on `shell:windows\system32\`.

[BROWSEUI][SHELL32] Fix shell path parsing

---

win32ss/user/ntuser/kbdlayout.c

Refactoring on keyboard layout.
- Delete `co_UserActivateKbl` function.
- Use `co_UserActivateKeyboardLayout` function instead of `co_UserActivateKbl` in `co_IntLoadKeyboardLayoutEx` function.
- Improve `co_UserActivateKeyboardLayout`.

[NTUSER] Use co_UserActivateKeyboardLayout in loading

---

base/shell/explorer/traywnd.cpp

Fix behavior from Show Desktop button.
JIRA issues: [CORE-19703](https://jira.reactos.org/browse/CORE-19703), [CORE-15369](https://jira.reactos.org/browse/CORE-15369)
Addendum to https://github.com/reactos/reactos/commit/70d7009ad958da5b0952b6e5af5194337a387459
On the second click to "Show desktop" button, the minimized windows are not restored.
This happens because after the first click and the addition to `CSimpleArray<MINWNDPOS> g_MinimizedAll`, a call to `RestoreMinimizedNonTaskWnds()` via `HSHELL_WINDOWACTIVATED` message, emptied the list of minimized windows.
Don't empty `g_MinimizedAll` while processing HSHELL_WINDOWCREATED or HSHELL_WINDOWACTIVATED message. 
(bDestroyed=FALSE).
Empty  `g_MinimizedAll` only when SendPulseToTray is called with bDestroyed=TRUE.

[EXPLORER] Fix behavior from Show Desktop button

---

dll/win32/shell32/shlexec.cpp

Simplify code logic.
- Use `PathGetArgsW`, `PathRemoveArgsW`, and `PathUnquoteSpacesW` for parsing parameters.

[SHELL32] shlexec: Simplify parameters parsing

---

drivers/bus/isapnp/hardware.c
drivers/bus/isapnp/isapnp.c
drivers/bus/isapnp/isapnp.h
drivers/bus/isapnp/isapnphw.h
drivers/bus/isapnp/isapnpres.h
drivers/bus/isapnp/pdo.c
modules/rostests/unittests/CMakeLists.txt
modules/rostests/unittests/isapnp/CMakeLists.txt
modules/rostests/unittests/isapnp/empty_card.c
modules/rostests/unittests/isapnp/isabus.c
modules/rostests/unittests/isapnp/precomp.h
modules/rostests/unittests/isapnp/res_card.c
modules/rostests/unittests/isapnp/testlist.c
modules/rostests/unittests/isapnp/tests.c

- Properly handle the case when the dependent function is placed after fixed resources
- Keep resource descriptors in the correct order
- Initialize the version and revision fields of resource lists
- Improve validation of resource data
- Add more debug prints
- Add unit tests and fix discovered issues
JIRA issue: This is a subtask of [CORE-18562](https://jira.reactos.org/browse/CORE-18562), this issue still persists
Before
```
AltList, AltList->Count 3
[E1063030:0:1] IO: Min 0:388, Max 0:38B, Align 1 Len 4
[E1063050:0:1] INT: Min 5 Max 5
[E1063070:0:0] DMA: Min 3 Max 3
...
```
After
```
AltList, AltList->Count 6
[E12F8030:0:1] INT: Min 5 Max 5
[E12F8050:0:0] DMA: Min 1 Max 1
[E12F8070:0:0] DMA: Min 3 Max 3
[E12F8090:0:1] IO: Min 0:220, Max 0:22F, Align 1 Len 10
[E12F80B0:0:1] IO: Min …
```

[ISAPNP] Fix parsing of complex resource data

---

win32ss/user/ntuser/message.c

_Implement BroadcastSystemMessage with Environment parameter._
JIRA issues: [CORE-19372](https://jira.reactos.org/browse/CORE-19372) and [CORE-19583](https://jira.reactos.org/browse/CORE-19583)
_BroadcastSystemMessage needs to be implemented._
_This allows programs to update Environment variables like PATH._

[NTUSER] Implement BroadcastSystemMessage with 'Environment' parameter

---

dll/win32/shdocvw/CExplorerBand.cpp

Reduce code.
JIRA issue: [CORE-19686](https://jira.reactos.org/browse/CORE-19686)
- Delete useless `_ILIsSpecialFolder` and `GetDisplayName` helper functions.
- Simply use `IShellFolder::CompareIDs` for item comparison.
BEFORE:
AFTER:
No change.

[SHDOCVW] Simplify CExplorerBand::CompareTreeItems

---

base/applications/calc/lang/bg-BG.rc
base/applications/calc/lang/cs-CZ.rc
base/applications/calc/lang/de-DE.rc
base/applications/calc/lang/el-GR.rc
base/applications/calc/lang/es-ES.rc
base/applications/calc/lang/fr-FR.rc
base/applications/calc/lang/it-IT.rc
base/applications/calc/lang/ko-KR.rc
base/applications/calc/lang/nl-NL.rc
base/applications/calc/lang/no-NO.rc
base/applications/calc/lang/pl-PL.rc
base/applications/calc/lang/ro-RO.rc
base/applications/calc/lang/ru-RU.rc
base/applications/calc/lang/sk-SK.rc
base/applications/calc/lang/sv-SE.rc
base/applications/calc/lang/th-TH.rc
base/applications/calc/lang/uk-UA.rc

- de-DE: add accelerators for the menus, inspired by german XPSP3
- *.rc: It is portuguese, not portoguese (this has been fixed in en-US earlier already, but was forgotten to be merged into other languages
- *.rc: CTRL is not used in capital manner by MS, but MS used Ctrl, and MS did not use STRG but Strg for de-DE. Our en-US respected that already, but again stuff was not synced into other languages when it was improved earlier in ros
Therefore this PR has absolutely no changes for en-US because that was good already.

[CALC] de-DE: add menu-accels, *.rc: Portu, CTRL->Ctrl, STRG->Strg

---

dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shlexec.cpp
sdk/include/reactos/shellutils.h

Bugs fixed:
- fDefault detection of default verb is flawed because it checks the `ici` struct after conversion instead of the source `sei` struct.
- The command to execute should not have the filename appended just because %1 nor %L did not appear in the registry command template.
This is a draft simply because I'd like some feedback on the removal of the filename. The existing code is not correct in the cases I have tested but it has been here and in wine for a long time.

[SHELL32] Don't add the file to the parameters if the registry command did not ask for a file

---

ntoskrnl/mm/ARM3/mdlsup.c

Implement undocumented `MmProbeAndLockProcessPages` routine. Based on mm-implement-mappingaddress.patch by @ThFabba from [CORE-10147](https://jira.reactos.org/browse/10147), with some improvements from me.
Split from my old #3654 PR.
It's badly required by FltMgr.sys driver from Windows XP/Server 2003 and closely used by a lot of apps those are depending on this driver (e. g., Avast Free Antivirus several versions, Avira Antivir Personal 8.2 etc. etc.).
Fixes several asserts from MDL support routines when the 3rd-party minifilter drivers are loading FltMgr.
JIRA issue: [CORE-14157](https://jira.reactos.org/browse/CORE-14157)
Implement `MmProbeAndLockProcessPages` as follows:
- First check whether an input `EPROCESS` points to the current process, and if so, attach it to the stack.
- Then, …

[NTOS:MM] Implement MmProbeAndLockProcessPages

---

dll/shellext/netshell/enumlist.cpp
dll/shellext/netshell/precomp.h
dll/shellext/netshell/shfldr_netconnect.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/debughlp.cpp
dll/win32/shell32/wine/pidl.c
sdk/include/reactos/shellfolderutils.h

The NetShell (Connections folder) PIDL format needs to match Windows for the wlanwiz work @SigmaTel71 is doing (specifically, matching the GUID from INetConnection properties with the GUID inside the PIDL).
Notes:
- The PIDL format needs to be Windows compatible so that wlanwiz can check the connection GUID.
- `SHELL32::ILIsEqual` cannot deem PIDL formats it does not understand as invalid.
- DefView must ask the folder when comparing PIDLs.

[NETSHELL][SHELL32] Make NetShell PIDL format more Windows compatible

---

dll/win32/sndblst/sndblst.c
sdk/lib/drivers/sound/mmebuddy/devicelist.c
sdk/lib/drivers/sound/mmebuddy/mmewrap.c
sdk/lib/drivers/sound/mment4/control.c

Trivial debug log fix.
- Add missing \n to SND_*() calls

[MMEBUDDY][MMENT4][SNDBLST] Add missing \n to SND_*() calls

---

dll/win32/browseui/shellbrowser.cpp

Improve UI/UX.
JIRA issue: [CORE-19689](https://jira.reactos.org/browse/CORE-19689)
- In the `CShellBrowser::OnInitMenuPopup` method, check/uncheck menu items depending on `fCurrentVertBar`.
Win2k3:
BEFORE:
AFTER:

[BROWSEUI] Add checkmark for Explorer bar menu items

---

base/applications/notepad/dialog.c

Steps to reproduce:
1. In the open dialog, open `Command Prompt.lnk`.
2. In the open dialog, right-click and create new text file. Open `New text document.txt`.
Notes:
- `DIALOG_FileNew` already has this fix.

[NOTEPAD] Don't leave junk behind when opening smaller file

---

win32ss/user/ntuser/menu.c

_Fix popup menu placement when menu is part way off right edge of screen._
JIRA issue: [CORE-19706](https://jira.reactos.org/browse/CORE-19706)
_Revise calculation of MENU_ShowPopup in menu.c._

[NTUSER] Fix popup menu placement when part way off right edge of screen

---

win32ss/user/ntuser/defwnd.c
win32ss/user/ntuser/nonclient.c
win32ss/user/ntuser/winpos.c
win32ss/user/ntuser/winpos.h

This fixes many Window Snap related bugs and uses the `WS_EX2_VERTICALLYMAXIMIZED*` styles to remember which edge it is snapped to.
The most significant change is that `GetWindowPlacement` lies about the normal position when it is snapped, just like Windows.
Fixes:
* JIRA issue: [CORE-19165](https://jira.reactos.org/browse/CORE-19165)
* JIRA issue: [CORE-19166](https://jira.reactos.org/browse/CORE-19166)
* JIRA issue: [CORE-19160](https://jira.reactos.org/browse/CORE-19160)
Partially fixes:
* JIRA issue: [CORE-16331](https://jira.reactos.org/browse/CORE-16331) (Fixed only for `!DragFullWindows`)
* JIRA issue: [CORE-18039](https://jira.reactos.org/browse/CORE-18039) (Now follows Windows 8 exactly, if this means fixed is up for debate I suppose, it does not meet the reporters definition of …

[NTUSER] Rewrite Window Snap handling

---

dll/shellext/stobject/power.cpp

Support for system batteries in ReactOS is really minimal to the point of non-existing. We are detecting the presence of any upcoming battery but since there's lacking in critical code that deals with communication between PO and the battery class driver as the battery systray icon uses `GetSystemPowerStatus` to gather battery info which in turn inquires the power manager via `NtPowerInformation(SystemBatteryState)`, we have to report to the user that the remaining capacity is unknown rather than returning a pseudo capacity value.
Technically this so called "pesudo" value is just a construct denoted as **BATTERY_PERCENTAGE_UNKNOWN**. Not reporting the actual remaining capacity makes sense, as there could be a scenario where the battery may not properly report its real datum, therefore …

[STOBJECT] Do not report the remaining battery capacity if it is unknown

---

win32ss/user/ntuser/winpos.c
win32ss/user/ntuser/winpos.h

[A small change](https://github.com/reactos/reactos/pull/5705#discussion_r1679758645) before PR #5705 was merged caused a severe downgrade in the snap/unsnap handling. Win key handling should work correctly now.
JIRA issue: [CORE-19165](https://jira.reactos.org/browse/CORE-19165) [CORE-19166](https://jira.reactos.org/browse/CORE-19166)

[NTUSER] Correctly store original unsnap position

---

sdk/include/reactos/libs/sound/mmebuddy_debug.h

`NDEBUG` should not ignore errors and assertions, as suggested by Oleg.
Follow-up of c7a4984 (0.4.15-dev-8414).
- POPUP() is used on DBG only.
- SND_ERR() and SND_ASSERT() are wanted even when defined(NDEBUG).
- Add a FIXME as !defined(NDEBUG) code compilation remains broken.
Note: That is a pre-existing issue, which I am not going to investigate.
- Match WCHAR type.

[SOUND] mmebuddy_debug.h: Sort out macro inclusions

---

dll/win32/shlwapi/ordinal.c
dll/win32/shlwapi/shlwapi.spec
dll/win32/shlwapi/utils.cpp
sdk/include/reactos/undocshell.h

Fixes the SHInvokeCommand verb parameter and implements SHInvokeCommandOnContextMenu[Ex] and SHInvokeCommandWithFlagsAndSite.
Notes:
- The ordinals are from Geoff Chappell and the signatures are based on the documentation by [airesoft.co.uk](https://undoc.airesoft.co.uk/index.php).

[SHLWAPI] SHInvokeCommandOnContextMenu[Ex] and SHInvokeCommandWithFlagsAndSite

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefViewUtil.cpp
dll/win32/shell32/CMakeLists.txt
sdk/include/psdk/shlobj.h

The caller supplied callback function is wrapped in a `IShellFolderViewCB` so we can use (the newer) `SHCreateShellFolderView`.

[SHELL32] Handle SHCreateShellFolderViewEx callback function

---

dll/cpl/desk/screensaver.c

Partial I_Kill_Bugs fix.
_Fix high CPU usage for 3dtext screensaver after calling 'settings'._
_Fix small screensaver preview not restarting after calling 'settings'._
_Fix changed settings not displaying new 'settings' value upon return from 'settings'._
JIRA issue: [CORE-18745](https://jira.reactos.org/browse/CORE-18745)
_Change function type of WaitForSettingsDialog to VOID._
_Always call function SetScreenSaverPreviewBox after calling 'settings'._
_Fix IsDialogMessage call to test for its negative return in the message loop._
_+ This last fix is courtesy of I_Kill_Bugs._

[DESK] Fix 3dtext screensaver restart high CPU usage after opening settings

---

dll/win32/shell32/CDefaultContextMenu.cpp

Forward the .lnk path (if any) so consrv gets `STARTF_TITLEISLINKNAME` and can apply console properties and icon from the shortcut.
This has always worked for shortcuts without a proper PIDL and must also work for PIDLs that now pass through `IContextMenu`.

[SHELL32] CDefaultContextMenu::InvokeCommand must forward the .lnk path

---

base/setup/lib/utils/filesup.c
base/setup/lib/utils/filesup.h

Don't suppose the form of the directory prefix.
Addendum to commit 32e6eed760 (r63715)
JIRA issue: [CORE-5982](https://jira.reactos.org/browse/CORE-5982)
The function assumed that the directory path name to be created always starts with a harddisk-partition root device name of the form:
```
\Device\HarddiskX\PartitionY\
```
Indeed, it can be (when using the volume manager) of the form:
```
\Device\HarddiskVolumeN\
```
and could even have a different format if trying to install ReactOS on an external removable drive or other weird device.
Since the format of this prefix is not 100% always the same, a different way to create the sub-directories is needed. The nested-directory creation algorithm is changed as follows:
Suppose that the directory to be created is:
``` …
```

[SETUPLIB] SetupCreateDirectory(): Don't assume the form of the directory prefix

---

dll/win32/shell32/CDefaultContextMenu.cpp

DFM_INVOKECOMMAND[EX] is supposed to get the CMINVOKECOMMANDINFO/SHELLEXECUTEINFO parameters string as LPARAM.
This PR also does 99% of the work to implement DFM_INVOKECOMMANDEX but I'm leaving it commented out because
- I'm not sure what the id numbers are supposed to be (perhaps our m_iIdCBFirst and m_iIdCBLast values?) nor why the callee needs to know in the first place.
- ROS currently incorrectly handles DFM_INVOKECOMMANDEX in a couple of places. I will fix this in another PR.

[SHELL32] Pass correct lParam to DFM_INVOKECOMMAND

---

base/applications/rapps/appview.cpp
base/applications/rapps/gui.cpp
base/applications/rapps/include/appview.h

The Installed list must re-enumerate the registry when F5 is pressed because just adding the same items from the cached list is pointless.
Most of the code is related to restoring the selected item and as a bonus, works in the other modes as well.

[RAPPS] Refreshing the Installed list should restore the selected item

---

dll/win32/shdocvw/CNSCBand.cpp

Must specify a specific SW command, otherwise cmd.exe from "Command Prompt here" starts invisible.

[SHDOCVW] CNSCBand must specify a ShowWindow command

---

base/applications/mspaint/lang/it-IT.rc

GCC8.4.0dbg warns about:
C:/ros/reactos/base/applications/mspaint/lang/it-IT.rc:267: unrecognized escape sequence
Fix that.
the regression was introduced by
0.4.15-dev-8555-g fbcbbd8768b8a3dda9013dfe3553867176c521b1 from (#7248)
Before-pic:
After-pic:

[MSPAINT] it-IT.rc: Fix compiler warning

---

dll/win32/shell32/droptargets/CFSDropTarget.cpp
dll/win32/shell32/folders/CRegFolder.cpp

For .lnk to .lnk detection, we need the parsing name. We still want a friendlier name for RegItems.
Fixes a bug discussed in PR #7264

[SHELL32] Create link must ask for a parsing name for file targets

---

base/shell/cmd/console.c
base/shell/cmd/error.c

Use unicode APIs explicitly instead of deprecated TCHAR APIs.
This helps avoid weirdness with non-standard functions in TCHAR apis:
_vstprintf is defined to either vsprintf (which has 3 arguments), or vswprintf, which has 4 arguments in the standard-conforming definition and 3 arguments in the legacy definition.

[CMD] Convert to explicitly unicode

---

base/setup/lib/CMakeLists.txt
base/setup/lib/fsutil.c
base/setup/lib/fsutil.h
base/setup/lib/setuplib.c
base/setup/lib/setuplib.h
base/setup/lib/utils/devutils.c
base/setup/lib/utils/devutils.h
base/setup/lib/utils/osdetect.c
base/setup/lib/utils/osdetect.h
base/setup/lib/utils/partlist.c
base/setup/lib/utils/partlist.h
base/setup/lib/utils/volutil.c
base/setup/lib/utils/volutil.h
base/setup/reactos/drivepage.c
base/setup/reactos/reactos.c
base/setup/usetup/partlist.c
base/setup/usetup/usetup.c

This greatly helps in reducing code complexity in some areas: code that
previously iterated over all partitions of a given disk, just to find
which ones were partitioned and contained a valid file system, now just
have to iterate over mounted volumes.
See in particular, lib/utils/osdetect.c and lib/fsutil.c .
JIRA issue: [CORE-13525](https://jira.reactos.org/browse/CORE-13525)
- Add some device utility functions; to be used later.
- Remove FORMATSTATE "Preformatted" enum value;
- Cleanup osdetect code after introducing Volume support;
- Some simplifications for FormatState.
- Differentiate between 'new' partition and 'new' volume:
* "New" partition: it has been created and added in the cached list,
but not yet actually written into the disk.
* "New" volume: newly-created volume (may be …

[SETUPLIB][REACTOS][USETUP] Split FS-volume-specific functionality from partitions

---

modules/rostests/apitests/win32nt/ntuser/NtUserSetTimer.c

Addition of apitests for NtUserSetTimer
Test 1 - test of creating/canceling 20 timers and comparing the raw number of returned messages - without parent window
Test 2 - test of creating/cancelling 20 timers and comparing the raw number of returned messages - with parent window
Test 3 - test creation/cancellation of 40000 timers - without parent window
Test 4 - test of creation/cancellation of 40000 timers - with parent window
Test 5 - test creation/cancellation of 2 timers and compare their index to see if they differ - without parent window

[WIN32KNT_APITEST] Add NtUserSetTimer API tests

---

win32ss/user/ntuser/timer.c

Fixes [CORE-9141](https://jira.reactos.org/browse/CORE-9141) (and maybe some others)
The original code in SetTimer was returning the nearest free index.
But then what was happening was that if SetTimer was called, then KillTimer and then another SetTimer again, it got the same index(nearest free) as the previous SetTimer. This causes confusion in applications that have a single procedure to respond to DispatchMessageW/WM_TIMER for multiple timers and only the indexes(such as Abiword 2.6.8) differentiate them.
Add index increasing (decreasing) after each pass. If there is no free index anymore, the index value is reset to the beginning (HINTINDEX_BEGIN_VALUE).

[NTUSER] IntSetTimer: Update HintIndex on each call

---

modules/rostests/apitests/user32/CMakeLists.txt
modules/rostests/apitests/user32/ScrollBarRedraw.c
modules/rostests/apitests/user32/testlist.c

Check [CORE-19669](https://jira.reactos.org/browse/CORE-19669) to make sure that CS_HREDRAW and CS_VREDRAW are respected when the client area of a window changes due to the scrollbar disappearing or re-appearing.
JIRA issue: [ROSTESTS-397](https://jira.reactos.org/browse/ROSTESTS-397)
Add a new rostests testcase that performs the above-mentioned check.
It works by creating a window, changing its color any time the WM_SIZE handler detects a change in the window's client area size (it switches through the standard 16 VGA colors available in 16-color mode).
The window has a timer which triggers a state transition in a state machine every 500ms, this state machine examines what happens when it makes the scroll bars disappear and re-appear, and it also tries shrinking and growing the window. …

[USER32_APITEST] Add scrollbar showing/hiding testcase

---

dll/ntdll/CMakeLists.txt
modules/rostests/apitests/compiler/CMakeLists.txt
modules/rostests/apitests/compiler/compiler_apitest.sln
modules/rostests/apitests/compiler/compiler_apitest.vcxproj
modules/rostests/apitests/compiler/floatconv.c
modules/rostests/apitests/compiler/testlist.c
sdk/lib/crt/CMakeLists.txt
sdk/lib/crt/math/i386/ftol2_asm.s

Add _ftol2_legacy symbol (forwarding to __ftol) to fix x86 build with VS 17.11+.
Also add a test that tests all kinds of float to int conversions.
- GCCLin_x86 on Test KVM: https://reactos.org/testman/detail.php?id=75960867&prev=0
- MSVC_x64 on Test KVM_x64: https://reactos.org/testman/detail.php?id=75963373&prev=0
Local test with latest VS 2022, CL 19.41.34120 x86
```
C:\ReactOS\build-msvc-x86>modules\rostests\apitests\compiler\compiler_apitest.exe floatconv
floatconv.c:111: Test failed: cast_float_to_long(10000000000.0f) = 1410065408, expected -2147483648
floatconv.c:112: Test failed: cast_float_to_long(-10000000000.0f) = -1410065408, expected -2147483648
floatconv.c:198: Test failed: cast_double_to_long(10000000000.0) = 1410065408, expected -2147483648
floatconv.c:199: Test failed: …
```

[APITESTS][CRT] Add _ftol2_legacy with tests

---

win32ss/user/ntuser/winpos.c

I_Kill_Bugs patch.
_Fix text overwritten and not updated by scrollbars when scrollbars created._
JIRA issue: [CORE-19669](https://jira.reactos.org/browse/CORE-19669)
_Check winpos.c for change in WVR_HREDRAW or WVR_VREDRAW in function co_WinPosSetWindowPos._
_If one occurs then redraw full window._
winpos_min.patch JID68658 on top of 0.4.15-dev-8531-gd5f6b8c
KVM:  https://reactos.org/testman/compare.php?ids=97159,97165
VBox: https://reactos.org/testman/compare.php?ids=97162,97164

[NTUSER] Fix window not updating when scrollbars created.

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CEnumIDListBase.cpp
dll/win32/shell32/CEnumIDListBase.h
dll/win32/shell32/folders/CControlPanelFolder.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDesktopFolder.h
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.h
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CRegFolder.cpp
dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp
dll/win32/shell32/shfldr.h
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/wine/pidl.c
dll/win32/shell32/wine/pidl.h
dll/win32/shell32/wine/shell32_main.h
sdk/include/psdk/shobjidl.idl
sdk/include/reactos/shellutils.h

This partially implements RegFolder required items [as described by Geoff Chappell](https://www.geoffchappell.com/studies/windows/shell/shell32/classes/regfolder.htm).
Fixes JIRA issues CORE-14060, CORE-14061, [CORE-19176](https://jira.reactos.org/browse/CORE-19176) and also fixes the Internet properties menu item.
Notes:
- There is a ton of code in the shell that assumes RegFolder PIDLs all have the same size and that its pidl types are interchangeable. This is not true (the types are per folder and the Control Panel items are larger). This PR starts to untangle this mess but leaves the old behavior intact (for now).
- `REGFOLDERINITDATA` is used as a non-const extra step to pass in the outer folder instance. It is known that the Windows RegFolder implementation uses COM aggregation …

[SHELL32] Don't display non-enumerable nor non-folder items in Explorer tree

---

ntoskrnl/cc/view.c

`ExAllocateFromNPagedLookasideList` returns NULL on failure so return `STATUS_INSUFFICIENT_RESOURCES` error code instead of accessing the invalid pointer.

[NTOS:CC] CcRosCreateVacb: Return error code on pool allocation failure

---

sdk/lib/crt/CMakeLists.txt
sdk/lib/crt/math/i386/ftol2_asm.s
sdk/lib/crt/math/i386/ftoul2_legacy_asm.s
sdk/lib/crt/math/math.cmake
sdk/lib/crt/msvcrtex.cmake

__ftol2 is exported from msvcrt on NT6+, not from ntdll for some reason. So native apps still need to statically link _ftol2 and _ftoul2_legacy, but apps linking to msvcrt only need to statically link _ftoul2_legacy (via msvcrtex), when on NT6+.
I basically reverted the previous change to the existing file ftol2_asm.s and added a new ftoul2_lgacy_asm.s with the new code. So yes, the old file's header is back at the old state. Deal with it ;-)

[CRT] Fix link issues with __ftol2 when compiling for NT6

---

sdk/lib/rtl/debug.c

The string should always be NULL terminated.

[RTL] Fix overflow case in vDbgPrintExWithPrefixInternal

---

boot/bootdata/autorun-livecd.inf

Addendum to 4cc03bbf0192 (r71342).
Before:
After:

[BOOTDATA] Fix LiveCD autorun

---

sdk/lib/drivers/virtio/CMakeLists.txt
sdk/lib/drivers/virtio/linux/virtio_config.h

- Add bugcodes dependency, fixes a rare build failure
- Fix for the sync part of commit 823fdb19d75b29352b1621e16f5c955153d90ed3, somehow it didn't pick up the change from the upstream commit https://github.com/virtio-win/kvm-guest-drivers-windows/commit/b22efbb8b80f76a81627396ed54bfbf4b02f80dc

[VIRTIO] Misc fixes

---

modules/rostests/apitests/win32nt/ntuser/NtUserSetTimer.c

In the newer branch, the message return timeouts stopped working, changed the message return window to a much wider one to make the tests less stringent and find out the actual functionality and time variance.
This PR is a continuation of the previous one: #7277 and #7100

[WIN32NT_APITEST] Update NtUserSetTimer API tests

---

media/doc/3rd Party Files.txt
modules/rosapps/CMakeLists.txt
modules/rosapps/applications/cmdutils/vfdcmd/vfdmsg.mc
modules/rosapps/drivers/vfd/imports.h
modules/rosapps/drivers/vfd/vfddbg.c
modules/rosapps/drivers/vfd/vfdimg.c
modules/rosapps/drivers/vfd/vfdmnt.c
modules/rosapps/drivers/vfd/vfdpnp.c
modules/rosapps/include/CMakeLists.txt
modules/rosapps/include/vfd/vfdio.h
modules/rosapps/lib/vfdlib/vfdctl.c
modules/rosapps/lib/vfdlib/vfdguiopen.c
modules/rosapps/lib/vfdlib/vfdguisave.c
modules/rosapps/lib/vfdlib/vfdguitip.c
modules/rosapps/lib/vfdlib/vfdmsg_lib.mc
modules/rosapps/lib/vfdlib/vfdshext.h
modules/rosapps/lib/vfdlib/vfdshmenu.cpp
modules/rosapps/lib/vfdlib/vfdshutil.cpp

build-linux (gcc, i386, Release, 0x502):
```c
2024-06-20T14:31:18.4098509Z [7100/12822] Building C object modules/rosapps/drivers/vfd/CMakeFiles/vfddrv.dir/vfddbg.c.obj
2024-06-20T14:31:18.4100686Z ../src/modules/rosapps/drivers/vfd/vfddbg.c:13: warning: ignoring #pragma warning  [-Wunknown-pragmas]
2024-06-20T14:31:18.4102219Z  #pragma warning (disable: 4206)
2024-06-20T14:31:18.4102853Z  
2024-06-20T14:31:18.4103740Z ../src/modules/rosapps/drivers/vfd/vfddbg.c:14:9: note: #pragma message: Debug feature is disabled.
2024-06-20T14:31:18.4104893Z  #pragma message ("Debug feature is disabled.")
2024-06-20T14:31:18.4105488Z          ^~~~~~~
```
Addendum to https://github.com/reactos/reactos/commit/25c7e1a8d049932380fb101bf413142dd058d723 (0.4.7-dev-1106) and follow-ups.
- [DOC] 3rd Party …

[VFD] Properly mark ReactOS's diffs

---

modules/rostests/winetests/xmllite/reader.c

Addendum to 3d1ca45 (0.4.15-dev-5553).
- Use matching type.
- Add a missing `#ifdef __REACTOS__`.

[XMLLITE_WINETEST] Fully mark Wine diff

---

win32ss/user/ntuser/winpos.c

Fix a memory leak in `co_WinPosSetWindowPos()` with `VisBefore` and `VisBeforeJustClient`, tidy up the code a bit.
JIRA issue: [CORE-19723](https://jira.reactos.org/browse/CORE-19723)
There are certain situations where `REGION_Delete()` may not be called for `VisBefore` and `VisBeforeJustClient`.  Particularly, when `SWP_AGG_NOPOSCHANGE` is the only "AGG status flag" specified, or when `SWP_NOCOPYBITS` is specified to `SetWindowPos()`, both `VisBefore` and `VisBeforeJustClient` could potentially leak.
Additionally, if `VisAfter` fails to initialize, or if `(WvrFlags & WVR_REDRAW)` evaluates to true, `VisBeforeJustClient` leaks.
This patch does a minor clean-up where it moves the deletion of 4 top-level-scope `PREGION` variables into the top level scope, instead of nested inside of various …

[NTUSER] Fix memory leak in co_WinPosSetWindowPos().

---

base/applications/rapps/appview.cpp

The AppInfo panel (bottom info pane) does not update its color when the system color scheme is changed. Sending `EM_SETBKGNDCOLOR` to a ListView was obviously never going to work.

[RAPPS] Fix AppInfo panel WM_SYSCOLORCHANGE bug

---

ntoskrnl/include/internal/i386/ke.h

clear NpxThread on rundown for SMP as well
Fixes the crash whenever a usermode thread is destroyed on x86
- clear NpxThread on rundown for SMP as well

[NTOS:KE] Clear NpxThread on rundown for SMP as well

---

boot/freeldr/freeldr/settings.c

Initialize the BootMgrInfo struct globally, so the TimeOut value is guaranteed to be negative when no Multiboot cmdline is provided. Fixes the boot timeout regression introduced in commit 7bee32d2372feb55949714eec5c92ca7ef2754bf which occured only on AMD64 builds.

[FREELDR] Fix boot timeout regression on AMD64

---

win32ss/gdi/ntgdi/freetype.c

@I_Kill_Bugs fix.
_For function IntExtTextOutW with space character, the x-dimension should be taken into account._
_Fixes HexEdit 1.2.1 right side of display window not being cleared._
JIRA issue: [CORE-11787](https://jira.reactos.org/browse/CORE-11787)
JIRA issue: [CORE-17721](https://jira.reactos.org/browse/CORE-17721)
JIRA issue: [CORE-19721](https://jira.reactos.org/browse/CORE-19721)
_Get x-dimension of space and add it into length in IntExtTextOutW._
_Account for x-dimension if TA_UPDATECP flag set and 'String' is not NULL._
refs/pull/7274/merge on top of 0.4.15-dev-8570-g938adaa
VBox: https://reactos.org/testman/compare.php?ids=97385,97388,97392 LGTM
KVM:  https://reactos.org/testman/compare.php?ids=97384,97387,97393 LGTM

[NTGDI:FREETYPE] Account for spaces in x-dimension of IntExtTextOutW function

---

win32ss/user/ntuser/message.c

_Optimize BroadcastSystemMessage with Environment parameter._
JIRA issue: [CORE-19372](https://jira.reactos.org/browse/CORE-19372)
_Minimize processing when UserModeMsg->lParam is NULL and KernelModeMsg->message != WM_WININICHANGE._
_Follow-up of #6884._

[NTUSER] Optimize BroadcastSystemMessage a bit. Follow-up of #6884

---

base/applications/notepad/main.c
base/applications/notepad/notepad.h
base/applications/notepad/settings.c

Fixes a bug where if you close Notepad while it is maximized, the next time Notepad is started it will start with its window placed as if maximized but it is still in the SW_RESTORE state and the "real normal placement" is lost.
`SetWindowPlacement` also takes care of making sure the window is placed correctly on the monitor workarea.

[NOTEPAD] Handle serialized maximized state

---

dll/win32/shell32/CShellLink.cpp

If a .lnk is a Darwin link (MSI/Windows installer) or just a PIDL to a non-filesystem item, don't allow the user to edit the target fields. This matches the Windows behavior.
Jira issue: [CORE-16505](https://jira.reactos.org/browse/CORE-16505)

[SHELL32] Lnk propertysheet must disallow editing special targets

---

dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/shlexec.cpp

Recent (unrelated) changes to execute shortcut targets with SEE_MASK_INVOKEIDLIST instead of SEE_MASK_IDLIST exposed a bug in shlexec.cpp where the directory was not passed along. In the uncommon case where the shortcut has no PIDL, we manually expand the directory in the one case where that matters.

[SHELL32] Pass and expand .lnk working directory

---

base/shell/explorer/lang/tr-TR.rc

**Purpose**
I translated the old English shell explorer lines into Turkish and the incorrect Turkish translations were adapted and edited based on the translations used in windows 7

[EXPLORER] Update Turkish (tr-TR) translation

---

dll/keyboard/kbdbe/kbdbe.c
dll/keyboard/kbddv/kbddv.c
dll/keyboard/kbdest/kbdest.c
dll/keyboard/kbdfr/kbdfr.c
dll/keyboard/kbdhe/kbdhe.c
dll/keyboard/kbdheb/kbdheb.c
dll/keyboard/kbdhu/kbdhu.c
dll/keyboard/kbdit/kbdit.c
dll/keyboard/kbdkor/kbdkor.c
dll/keyboard/kbdlt1/kbdlt1.c
dll/keyboard/kbdlv/kbdlv.c
dll/keyboard/kbdpl/kbdpl.c
dll/keyboard/kbdpl1/kbdpl1.c
dll/keyboard/kbdsf/kbdsf.c
dll/keyboard/kbdsl/kbdsl.c
dll/keyboard/kbdsl1/kbdsl1.c
dll/keyboard/kbduk/kbduk.c

I found this bug while testing random games, the left key didn't work. After switching to other keyboard layouts (German, English) the problem disappeared. There are games (e.g. Doom 3 demo, Tomb Raider 2 demo) that somehow use this code from extended_key_names to determine which key the user pressed. It might be a good idea to check other keyboard layouts too, since I found that table inconsistent across languages.

[KEYBOARD] Fix left key code in extended_key_names

---

dll/win32/comdlg32/colordlg.c

Based on @DarkShadow44's merge request to WineHQ.
JIRA issue: [CORE-19402](https://jira.reactos.org/browse/CORE-19402)
Merge Request: https://gitlab.winehq.org/wine/wine/-/merge_requests/5756
- Extend `CC_CheckDigitsInEdit`'s parameters and set `infoPtr->updating` to `TRUE` when updating.
- Call `CC_PaintLumBar` function in `CC_WMCommand` function.

[COMDLG32] ChooseColor: Apply DarkShadow44's suggestions

---

base/applications/notepad/main.c

Ctrl+A,Z,C,X etc. must not be handled by the main window when the Find dialog is active.

[NOTEPAD] Don't handle main window accelerators in Find dialog

---

base/applications/notepad/dialog.c

When `FormatMessage` is unable to find a string for the error, just displaying the error code is much better than an empty string.

[NOTEPAD] Display error code if no error string is available

---

dll/win32/shell32/shellrecyclebin/recyclebin_v5.cpp
dll/win32/shell32/shellrecyclebin/recyclebin_v5_enumerator.cpp

PR #7173 (22b913928f4a1d13120b0ec7a1c6889d37ec0e3a) by @katahiromz fails to initialize the `DELETED_FILE_RECORD` struct when constructing a `RecycleBin5File` instance. This causes `_ILCreateRecycleItem` to create PIDLs without filenames and the `CRecycleBin` IShellFolder implementation does not expect this to happen.
Also fixes incorrect usage of `SHFileOperationW` when restoring deleted files. The previous code might have worked by chance in the past if the string just happened to be double-null terminated as required by this API!

[SHELL32] Fix CRecycleBin crash caused by PR #7173

---

win32ss/gdi/eng/alphablend.c

Fixes the return value, when the clip rect and the output rect do not intersect.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=97706,97709,97712,97715
-

[WIN32K:ENG] Fix return value in EngAlphaBlend

---

dll/win32/serialui/lang/ro-RO.rc

[SERIALUI] Update Romanian (ro-RO) translation

---

ntoskrnl/ke/amd64/trap.S
sdk/lib/rtl/amd64/unwind.c

Improve handling of exceptions.
- [NTOS:KE/x64] Do not overwrite the original context during exception handling
- [NTOS:KE/x64] Fix exception information on page faults
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=97756,97760,97774,97782

[NTOS:KE/x64] Improve exception handling

---

dll/win32/shell32/CShellLink.cpp

The target attributes are mainly to be used by `CShellLink::Resolve` and the link tracking service but I verified on Windows that simply flipping a bit in the link header changes the target description between "File" and "Folder".

[SHELL32] Store target FS attributes in .lnk header

---

base/shell/explorer/traywnd.cpp
dll/win32/browseui/basebarsite.cpp
dll/win32/browseui/shellbrowser.cpp
dll/win32/comctl32/rebar.c
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/shlfileop.cpp

|Before|After|
| ---- | ---- |
|![Before](https://github.com/user-attachments/assets/6a72dcc9-a3dc-4804-adbe-23e580b3362b)|![After](https://github.com/user-attachments/assets/2a8296ef-77a7-4e66-bd87-9833515d175d)|
|![Taskbar](https://github.com/user-attachments/assets/8a14b2d9-54c8-4879-8a06-37bfb33b2ca5)||
Notes:
- Windows also seems to paint the close X on the Explorer band in black no matter what the system colors are.
- If RBBIM_COLORS is never set on Windows, the bands follow the ReBar controls color and if RB_SETBKCOLOR is never sent, the system color is used and is correctly updated when the system colors change.

[SHELL32][COMCTL32][BROWSEUI][EXPLORER] Update color usage on WM_SYSCOLORCHANGE

---

dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/folders/CFSFolder.cpp
sdk/tools/mkshelllink/mkshelllink.c

[EXP_SPECIAL_FOLDER](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/ns-shlobj_core-exp_special_folder) allows parts of a shortcuts pidl to be overridden by a special folder.
This will allow #7154 to call `mkshelllink -o Readme.lnk shell:windows\Readme.txt` to create correct shortcuts for the LiveCD.
JIRA issue: [CORE-19692](https://jira.reactos.org/browse/CORE-19692)

[SHELL32][MKSHELLLINK] Support EXP_SPECIAL_FOLDER datablock in shortcuts

---

drivers/filesystems/fastfat/fatprocs.h
sdk/include/reactos/dbgbitmap.h
sdk/include/xdk/rtlfuncs.h

Temporary enabled debug code to figure out, whether the bitmap gets corrupted or if there is something else going on in fastfat. JIRA issue: [CORE-19741](https://jira.reactos.org/browse/CORE-19741)
- [SDK] Implement RTL debug bitmap
- [FASTFAT] Use debug bitmap
tbd

[SDK][FASTFAT] Bitmap debugging

---

base/applications/rapps/settings.cpp
base/applications/rapps/winmain.cpp

Instead of defaulting all settings if any setting is missing, only set everything to their defaults if all settings are missing and respect any setting that is already set.
Also fixes a bug where szDownloadDir is treated as valid even if the string empty.
I'll admit I'm scratching my own itch here, I want to set bDelInstaller=1 in unattended setup.

[RAPPS] Respect partial settings configuration

---

dll/win32/kernel32/client/proc.c
modules/rostests/rosautotest/main.cpp
sdk/include/ndk/pstypes.h
sdk/lib/rtl/assert.c

This fixes timeouts + reboots for user mode assertion failures on the testbots. As a bonus it now shows a backtrace.

[RTL][KERNEL32][ROSAUTOTEST] Disable debug prompts during autotest

---

base/applications/shutdown/lang/ro-RO.rc

Improvements based on recent Romanian translation document revision 06e89b2e81cd7de029fac2c595a6371eba13d797.

[SHUTDOWN] Update Romanian (ro-RO) translation

---

dll/cpl/liccpa/lang/ro-RO.rc

Improvements based on recent Romanian translation document revision 06e89b2. 

[LICCPA] Update Romanian (ro-RO) translation

---

dll/win32/shell32/brfolder.cpp
dll/win32/shell32/shlfileop.cpp

MSDN says "The application must use the RemoveProp function to remove the entries" but SHELL32 fails to do this. In these two cases, using `SetProp` is pointless anyway since we own the dialog and can use `SetWindowLongPtr`.
On Windows, `SHBrowseForFolder` seems to use `GWLP_USERDATA` or `DWLP_USER` depending on if `BIF_NEWDIALOGSTYLE` is set. `DWLP_DLGPROC` is also different between the two so I'm guessing they have two separate implementations of that dialog.

[SHELL32] Don't leak SetProp ATOM

---

dll/win32/gdiplus/graphics.c

This occurs on the ribbon bar when running Super Finder XT 1.6.3.2 from rapps
CORE-19456
_When the GCC compiler was updated from version 4.7.2 to 8.4.0 this was a regression._
JIRA issue: [CORE-19456](https://jira.reactos.org/browse/CORE-19456)
_Due to some tiny rounding errors in the least significant digits of some math a comparison started to fail._
_As a workaround, I was able to fix this by increasing the precision of some of the calculations._
_Four REAL defined variables were changed to DOUBLE and this made the comparison work again._
_This occurs at the boundary line between two separate graphic objects._
_The upper area is a consistent fill and the lower one is a gradient fill._
_This is visible in the screen captures below._
refs/pull/7348/merge on …

[GDIPLUS] Fix for gdiplus/graphics.c regression with upgrade to GCC 8.4.0.

---

base/setup/usetup/spapisup/cabinet.c

Fixes copying files of size 0 (like foobar.exe.local) from the cab during install.
✅ KVM x86: https://reactos.org/testman/compare.php?ids=98071,98073,98077

[USETUP] Fix handling of 0 sized files in the cab

---

win32ss/user/ntuser/desktop.c
win32ss/user/ntuser/usrheap.c

Create the section with PAGE_READWRITE, not PAGE_EXECUTE_READWRITE and map in user mode with PAGE_READONLY, not PAGE_EXECUTE_READ. Original commit was ea5261f in 2006. The comments suggest that back then the heap code had issues with it, which is not the case anymore.
KVM x86: https://reactos.org/testman/compare.php?ids=97983,97988,97991,97973
KVM x64: https://reactos.org/testman/compare.php?ids=98061,98064,97975

[WIN32K] Fix protection of USER heap

---

boot/freeldr/freeldr/arch/i386/pc/pcdisk.c
boot/freeldr/freeldr/include/fs/iso.h
boot/freeldr/freeldr/lib/fs/iso.c

Some bugs I've encountered while testing aspects of FreeLoader.
- ### `[FREELDR] include/fs/iso.h: Fix definition of the "Primary Volume Descriptor" PVD structure`
For reference, see the cdfs/cd.h RAW_ISO_VD structure.
Each of the old "VolumeSetSize", "VolumeSequenceNumber" and "LogicalBlockSize"
ULONG fields actually correspond to pairs of USHORT fields:
"VolumeSetSizeL" and "VolumeSetSizeM", etc., where the "L" one contains
the value in little-endian format, while the "M" one contains the same
value in big-endian format.
Additionally, use UCHARs for the character arrays.
- ### `[FREELDR] fs/iso.c: Perform extra validation before mounting the ISO filesystem.`
Validate the primary volume descriptor version and its reported
logical block size.
- ### `[FREELDR] Fix the retrieval of seg:off …

FreeLoader: a selection of disk bug fixes (Part 1)

---

boot/freeldr/freeldr/arch/i386/i386bug.c

Recreation of #7269 rebased on last 0.4.15-dev-commit before the branching 945e856031137b566e616248e2f80c92be807c45
to get those stupid MSVC builders green.
Maybe we should have done this way of writing out the version 10 years ago already, because
JIRA issue: all the 100 tickets linked against CORE-6762 (I intentionally did not want this to create a link to that)
See https://jira.reactos.org/browse/CORE-19716?focusedId=143079&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-143079
After pic: (yes, the L in FreeLdr would be capitalized actually) (shows arch, builddate, short-rev):

[FREELDR] Print arch + buildnumber on crash-screen

---

base/applications/rapps/gui.cpp
base/applications/rapps/unattended.cpp

This is a follow up to PR #6655. The two different modes needs separate mutex and window titles, otherwise you can end up stuck in AppWiz mode:
1) Run Rapps.exe /AppWiz (and don't close the window).
2) Run Rapps.exe. Opens existing instance, stuck in AppWiz mode.

[RAPPS] Use different mutex and title for AppWiz mode

---

base/applications/rapps/gui.cpp
base/applications/rapps/include/misc.h
base/applications/rapps/include/rapps.h
base/applications/rapps/loaddlg.cpp
base/applications/rapps/misc.cpp
base/applications/rapps/unattended.cpp
base/applications/rapps/winmain.cpp

Reproducing the issue:
1. Start installing some app.
2. Close the main window that sits behind the download dialog.
Notes:
- The `EmulateDialogReposition` related code is not strictly required but it is nice to make sure the main window is properly on screen as well. The download/install popup dialog supports `DM_REPOSITION` natively.

[RAPPS] Hide the main window during active download/install if the user closes it

---

sdk/include/psdk/wlanapi.h

Avoid using 'magic numbers' for specifying types of Wi-Fi networks to be included into the scan results. The function of subject is used in Wireless LAN Wizard ([wlanwiz](https://github.com/SigmaTel71/reactos/tree/wlanwiz)) I develop specifically for ReactOS. In future more PRs like this one to fill missing defines will appear, so taking small steps might be better for the moment.
Reference: [Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlangetavailablenetworklist)
JIRA issue: [CORE-6905](https://jira.reactos.org/browse/CORE-6905)
- Add definitions of possible values for `dwFlags` applicable to `WlanGetAvailableNetworkList` function.

[PSDK] Add defines for dwFlags used by WlanGetAvailableNetworkList

---

boot/freeldr/fdebug/lang/bg-BG.rc
boot/freeldr/fdebug/lang/cs-CZ.rc
boot/freeldr/fdebug/lang/de-DE.rc
boot/freeldr/fdebug/lang/el-GR.rc
boot/freeldr/fdebug/lang/en-US.rc
boot/freeldr/fdebug/lang/es-ES.rc
boot/freeldr/fdebug/lang/fr-FR.rc
boot/freeldr/fdebug/lang/hu-HU.rc
boot/freeldr/fdebug/lang/id-ID.rc
boot/freeldr/fdebug/lang/it-IT.rc
boot/freeldr/fdebug/lang/ja-JP.rc
boot/freeldr/fdebug/lang/no-NO.rc
boot/freeldr/fdebug/lang/pl-PL.rc
boot/freeldr/fdebug/lang/ro-RO.rc
boot/freeldr/fdebug/lang/ru-RU.rc
boot/freeldr/fdebug/lang/sk-SK.rc
boot/freeldr/fdebug/lang/sq-AL.rc
boot/freeldr/fdebug/lang/tr-TR.rc
boot/freeldr/fdebug/lang/uk-UA.rc
boot/freeldr/fdebug/lang/zh-CN.rc
boot/freeldr/fdebug/lang/zh-HK.rc
boot/freeldr/fdebug/lang/zh-TW.rc

We do have 22 rc files. Strip a hardcoded version in all of them. Which hasn't been groomed by anyone for longer than the year 2005 already (SVN r18478). What a waste of bytes!
Who is crazy enough trying to groom anything like that by hand?

[FDEBUG] *.rc: Less outdated version-hardcodes

---

boot/freeldr/freeldr/include/fs.h
boot/freeldr/freeldr/lib/fs/fs.c

The `ArcOpen()` function has a bug in how direct opening of storage devices is done.
In addition, both `ArcOpen()` and `ArcClose()` need some fixes, regarding (de)referencing of the device and file handles.
These problems will be addressed in PR #7414, but for that, I need some prerequisite ground-work to be done: this is the purpose of the current PR.
- ### `[FREELDR] fs.c: Move the list of filesystem mount routines into a table.`
This allows to make the code better extendable: adding a new FS
mount routine into the table, instead of duplicating also a whole
`if (!FileFuncTable) ...` check.
Later, this table will be made dynamic, so that new filesystems could be
dynamically registered at runtime, and a filesystem could be forced to
be mounted by the user (using a specific syntax).
- ### …

Freeldr: Some minor refactoring in fs.c code, before fixes

---

drivers/usb/usbstor/fdo.c

During investigation into some of the USB stack issues we've been running into I've found that when a USB storage device is already plugged in during boot and removed before it finishes initialization we run into this assert.
The logic in this function removes the pools made for the following entries in DeviceExtension indiscriminately this makes debugging a bit more difficult. Instead of depending on this behavior of ALWAYS being filled with valid data, let's free the following pools ONLY if they're initialized. This change prevents us from bugchecking when USB flash drives are removed early during boot. This makes the debugging experience a little more sane.

[USBSTOR] Don't assert on clean up if initialization didn't finish

---

dll/win32/uxtheme/lang/pt-BR.rc
dll/win32/uxtheme/lang/pt-PT.rc
dll/win32/uxtheme/uxtheme.rc

Add pt-PT.rc and pt-BR.rc translation files for Uxtheme
pt-BR:
pt-PT:

[UXTHEME] Add Portuguese Portugal (pt-PT) and Portuguese Brazil (pt-BR) translation

---

boot/freeldr/bootsect/isoboot.S
boot/freeldr/freeldr/pcat.cmake

The setupldr and freeldr binaries are the same since commit 948e82af1 (r65832), because both their functionality have been shared.
- Remove the setupldr build target in freeldr's cmake files.
- Change "setupldr" to "freeldr" in the ISO boot sector.

[FREELDR] Bye bye "setupldr" build target

---

ntoskrnl/kdbg/kdb_cli.c

Debug log improvement.
Split off of #6012, per Hermès request.
- And demote/promote some DPRINT()/DPRINT1().

[NTOS:KDBG] Add missing \n to DPRINT() calls

---

base/system/format/format.c
dll/win32/fmifs/chkdsk.c
dll/win32/fmifs/fmifs.spec
dll/win32/fmifs/format.c
dll/win32/fmifs/query.c
dll/win32/kernel32/client/file/disk.c
dll/win32/kernel32/client/file/mntpoint.c
ntoskrnl/io/pnpmgr/pnpnotify.c
ntoskrnl/io/pnpmgr/pnpreport.c
sdk/include/reactos/libs/fmifs/fmifs.h

Fixes for getting the format tool (and rufus) to reliably format RAW volumes.
* Handle RAW volumes in format tool.
* Implement and use QueryDeviceInformation in format tool to reliably display volume size before formatting.
* PNP fixes for processing custom notifications. Without this, format (and everything else) was able to successfully set the new volume label, however PNP would still return error code which caused the format tool to exit before printing final statistics after formatting.
* Remove the hack for missing IOCTL_MOUNTDEV_QUERY_DEVICE_NAME in fmifs' FormatEx
* Minor kernel32 fixes
Before:
After:
(Rufus still fails after formatting the volume due to unimplemented SetVolumeMountPoint)

[FMIFS][FORMAT][KERNEL32][NTOS:PNP] Get the format tool fully working

---

win32ss/user/user32/windows/cursoricon.c

Hackfix for CORE-17902 - The cursoricon (copyimage) that returns NULL to render - LR_COPYFROMRESOURCE
In this case, the aim is to render some VB5/6 software icons to show up. Those elements are icons rendered in a way that is common under Visual Basic icons loaded from a .ocx .
ThunderRT6FormDC->ThunderRT6UserControlDC->RebarWindows32->Toolbar20WndClass->msvb_lib_toolbar
Quoting Simone:
> Unable to render embedded object: File (ReactOS_workaround) not found.
> 
> it is making a CopyImage call with the LR_COPYFROMRESOURCE|LB_COPYRETURNORG flags. All of these are returning NULL.
> LB_COPYRETURNORG flag is only managed by bitmap copy function (BITMAP_CopyImage), not by the cursoricon copy function (CURSORICON_CopyImage) but it's not the critical one.
> The critical flag is the …

[USER32] Hackfix for CORE-17902 - The cursoricon (copyimage) that returns NULL to render - LR_COPYFROMRESOURCE

---

modules/rostests/apitests/atl/CAtlList.cpp
sdk/lib/atl/atlcoll.h

Reduce difference between our ATL and official ATL and provide a convenient way to append `CAtlList` at the same time. Both functions exist as of Visual Studio 2005 (at ~~list~~ least; \*ba dum tss*).
Reference: Microsoft Learn
- [AddTailList](https://learn.microsoft.com/en-us/cpp/atl/reference/catllist-class?view=msvc-170#addtaillist)
- [AddHeadList](https://learn.microsoft.com/en-us/cpp/atl/reference/catllist-class?view=msvc-170#addheadlist)
- Implement `CAtlList::AddHeadList` and `CAtlList::AddTailList` functions
- Add API tests for new functions
'no squash merge' label is recommended.

[ATL] Implement CAtlList::AddHeadList and CAtlList::AddTailList

---

sdk/lib/cmlib/cmcheck.c
sdk/lib/cmlib/cmheal.c
sdk/lib/cmlib/hivecell.c
sdk/lib/cmlib/hiveinit.c
sdk/tools/cabman/cabinet.h
sdk/tools/cabman/dfp.cxx

Compiling ReactOS' host-tools on GCC 13.x and also GCC8.4.0 emit new warnings (compared to GCC 8.x and MSVC builds).
In this PR I attempt to fix these for our own (not 3rd-party) code.
Those warnings do happen only on our Linux builders, but they do not happen on our Windows-builders.
JIRA issue: [CORE-19724](https://jira.reactos.org/browse/CORE-19724)
- ### `[CABMAN] Fix GCC13.2.0/GCC8.4.0-Linux buffer format overflow warning`
```
sdk/tools/cabman/dfp.cxx: In member function 'ULONG CDFParser::PerformFileCopy()':
sdk/tools/cabman/dfp.cxx:1136:36: warning: 'sprintf' may write a terminating nul past the end of the destination [-Wformat-overflow=]
1136 |             sprintf(InfLine, "%s=%s", GetFileName(SrcName).c_str(), DstName);
|                                    ^ …
```

Fix some GCC13.2.0+GCC8.4.0 host-tools warnings for our code, that happen on the Linux-builders

---

base/system/services/database.c
base/system/services/rpcserver.c
base/system/services/services.h

_Fix services delay on stopping. Retry of PR #1225._
JIRA issue: [CORE-16949](https://jira.reactos.org/browse/CORE-16949)
and [CORE-15064](https://jira.reactos.org/browse/CORE-15064)
_Retry of @yagoulas services PR #1225 with small fixes from the original PR._
Some tests can be found here: https://github.com/reactos/reactos/pull/7375#discussion_r1779273121
refs/pull/7375/merge on 0.4.16-dev-92-g0c2cdca
KVM:  https://reactos.org/testman/compare.php?ids=98133,98135 LGTM
VBox:  https://reactos.org/testman/compare.php?ids=98132,98140 LGTM
KVM:  Total Test Time 41.1/34.9 minutes (6 minutes less)
VBox: Total Test Time 38.5/33.5 minutes (5 minutes less)
Note two previous VBox runs had an extra reboot/[SYSREG] timeout in user32:sysparams
VBox: …

[SERVICES] Fix services delay on stopping

---

dll/win32/shell32/dialogs/recycler_prop.cpp
dll/win32/shell32/shlfileop.cpp

Allow the user to disable the delete confirmation dialog (in recycle bin properties) when files are deleted to the recycle bin.

[SHELL32] Implement SSF_NOCONFIRMRECYCLE recycler setting

---

ntoskrnl/mm/section.c

Fixes Blender x64.
See https://jira.reactos.org/browse/CORE-19761

[NTOS:MM] Fix PTE protection for executable CoW pages

---

ntoskrnl/io/pnpmgr/pnpreport.c

Previously FsRtlNotifyVolumeEvent would pass a pointer to a TARGET_DEVICE_CUSTOM_NOTIFICATION structure on the stack to IoReportTargetDeviceChangeAsynchronous, which would store a pointer to it in a work-item and process that after the stack object was already out of scope. This broke x64 boot. Started happening after recent fixes to IoReportTargetDeviceChangeAsynchronous.

[NTOS:PNP] Don't use a pointer to a stack structure in a work-item

---

dll/directx/wine/ddraw/ddraw.c

Fix taskbar being displayed when switching to fullscreen when using DirectDraw 
Note that this is still a working fix unlike claimed here:
https://github.com/reactos/reactos/pull/4728#issuecomment-1722302390 | https://jira.reactos.org/browse/CORE-19171 
JIRA issue: 
[CORE-16140](https://jira.reactos.org/browse/CORE-16140)
[CORE-16148](https://jira.reactos.org/browse/CORE-16148)
[CORE-16321](https://jira.reactos.org/browse/CORE-16321)
[CORE-18644](https://jira.reactos.org/browse/CORE-18644)
[CORE-17799](https://jira.reactos.org/browse/CORE-17799)
possibly more?
Games fixed that do not have a Jira ticket:
- Future Cop L.A.P.D.
- Jazz Jackrabbit 2
- Command and Conquer Tiberian Sun
- Raptor: Call of Shadows
- Need For Speed Carbon

[DDRAW] Fix taskbar visibilty when switching to fullscreen

---

base/system/services/database.c
base/system/services/rpcserver.c
base/system/services/services.h

Collapse ScmControlService() and ScmSendStartCommand() implementations together, this greatly simplifies the code.
And SAL2-annotate ScmControlService() as well.
(commit from Feb 25, 2018)
- Merge both these functions.
In addition:
- Acquire ControlServiceCriticalSection just before doing the pipe
operations, and release it just after.
- SAL2-annotate ScmControlService().
- Re-order the ScmControlService() parameters in a more natural way
(1st: service name; 2nd: comm pipe; 3rd: control code; 4th+: arguments
for the control command).

[SERVICES] Merge ScmControlService() and ScmSendStartCommand() together

---

dll/win32/shell32/folders/CRecycleBin.cpp

Notes:
- This does not fix the underlying issue of the Recycle Bin not working correctly in recent builds. It simply prevents Explorer from crashing when given an invalid PIDL. The core issue is from https://github.com/reactos/reactos/commit/22b913928f4a1d13120b0ec7a1c6889d37ec0e3a #7173

[SHELL32] Make Recycle Bin PIDL data handling more robust

---

dll/win32/shell32/brfolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp

JIRA issue: [CORE-19751](https://jira.reactos.org/browse/CORE-19751)
Notes:
- This changes how SFGAO_STREAM is assigned to "Shellfolder" files. [Zip files are both](https://devblogs.microsoft.com/oldnewthing/20171101-00/?p=97325) folders and streams.

[SHELL32] Don't display .zip files in BrowseForFolder

---

sdk/include/crt/stdarg.h
sdk/include/crt/vadefs.h

This is to be compatible with native CRT headers.

[CRT] vadefs.h: Fix name of __crt_va_*

---

modules/rostests/apitests/shell32/ItemIDList.cpp
modules/rostests/apitests/shell32/testlist.c

ROS `ILIsEqual` is rather broken, it compares each item id without context.

[SHELL32_APITEST] Basic ILIsEqual tests

---

boot/freeldr/freeldr/freeldr.c
boot/freeldr/freeldr/include/ver.h
boot/freeldr/freeldr/ui/tui.c

Those strings haven't been groomed anymore for more than 10 years. We had many thousands of different freeldr builds with different behavior and bugs each since then, but nobody ever did have the slightest motivation to update those hardcoded FREELOADER_MAJOR_VERSION, FREELOADER_MINOR_VERSION, FREELOADER_PATCH_VERSION from ver.h. And that is logical, because touching other modules will change the behavior of freeldr as well, so it is absolutely impossible to groom anything like that correctly. Instead we should simply do what we started to do in #7382, which will at least give some information (the actual sources it was built from) instead of some misleading voodoo-version.
This might slightly shrink the size of freeldr as well, but I was too lazy to measure by how much.

[FREELDR] Less outdated version-hardcodes

---

ntoskrnl/kd64/kdtrap.c
ntoskrnl/kdbg/kdb.c
ntoskrnl/kdbg/kdb.h
ntoskrnl/kdbg/kdb_cli.c

The main purpose of this PR is to reintroduce the capability from KdbpCliInit() to interpret the KDBinit file.
(Addendum to commit baa47fa5e.)
Additional improvements are also added, see below.
- Move the printing pager state reset code (setting the number of
printed rows and columns to zero, and the output aborted flag)
to KdbpDoCommand(). This allows to keep the original behaviour,
while also inheriting it whenever KdbpDoCommand() is invoked
elsewhere (for example, from KdbpCliInterpretInitFile()).
- Use KdbPuts/Printf() instead of KdbpPrint() for the entry banners,
so that they aren't subject to the current printing pager state.
Do the same for the "command unknown" error in KdbpDoCommand().
- Add a "Type 'help' for a list of commands" banner, for the users.
- Replace the do-while-loop …

Further improvements for KDBG

---

modules/rostests/winetests/comctl32/CMakeLists.txt
modules/rostests/winetests/comctl32/rebar.c
modules/rostests/winetests/comctl32/static.c

fix warnings when compiling comctl32_winetest
the comctl32 winetest just does a few things so properly mark the ros diff.
```
[5960/7554] Building C object modules\...iles\comctl32_winetest.dir\pager.c.obj
modules\rostests\winetests\comctl32\pager.c(43): warning C4045: 'large_truncated_80_w': array bounds overflow
[5961/7554] Building C object modules\...iles\comctl32_winetest.dir\rebar.c.obj
modules\rostests\winetests\comctl32\rebar.c(21): warning C4005: '_WIN32_WINNT': macro redefinition
sdk\include\psdk\sdkddkver.h(156): note: see previous definition of '_WIN32_WINNT'
modules\rostests\winetests\comctl32\rebar.c(22): warning C4005: '_WIN32_IE': macro redefinition
sdk\include\psdk\sdkddkver.h(189): note: see previous definition of '_WIN32_IE'
[5962/7554] Building C object …
```

[WINETESTS] Fix warnings when compiling comctl32_winetest

---

dll/win32/shell32/dialogs/filetypes.cpp

PathIsExeW is used and will exclude exe, com, pif, cmd, bat, scf and scr. The previous #6122 PR added support for the FTA_Exclude flag and that will exclude .lnk files.
[before_PR7452.webm](https://github.com/user-attachments/assets/235fa69d-de20-4fa5-b400-c091c65631f9)
JIRA issue: [CORE-19805](https://jira.reactos.org/browse/CORE-19805)

[SHELL32] Exclude executable extensions from File Types dialog

---

sdk/tools/spec2def/spec2def.c

This prevents MSVC from reordering the exports in a way that doesn't match our spec file. Also improve the algorithm to apply ordinals, by starting with the first specified ordinal, possibly reserving ordinals for anything declared without an ordinal before.
Windows:
MSVC before:
MSVC after:
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=98330,98340,98343,98346
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=98333,98341,98348,98349

[SPEC2DEF] Use explicit ordinals on MSVC, too

---

boot/freeldr/freeldr/include/fs.h
boot/freeldr/freeldr/lib/fs/ext2.c
boot/freeldr/freeldr/lib/fs/fat.c
boot/freeldr/freeldr/lib/fs/fs.c
boot/freeldr/freeldr/lib/fs/iso.c
boot/freeldr/freeldr/lib/fs/ntfs.c
boot/freeldr/freeldr/lib/fs/pxe.c

- Original code was just incrementing the reference counts (RefCounts)
of the device objects or the device/file handles, without decrementing
them when closing the handles. This is now fixed.
Notice the following:
* When opening a file on a device (disk), the device's (and its
handle's) RefCount is incremented, and the file handle's RefCount
is incremented as well.
* When closing a file, the file handle's RefCount is decremented
(and the file closed if the RefCount reaches zero), and the file's
parent device handle is also closed, recursively.
This has the effect of decrementing the parent device handle's
RefCount, and the device's own RefCount is decremented as well.
- Fix opening a device (disk) in direct access, when this device is
already opened. Indeed, previously we allowed direct …

[FREELDR] fs.c: Fix handling of file handles, (de)referencing, and direct-device access

---

ntoskrnl/ke/i386/mproc.c

Let's be explicit.
Addendum to 516ccad (0.4.15-dev-7016).
- Use explicit variable type and print format.

[NTOS:KE/i386] KeStartAllProcessors(): ProcessorCount is a ULONG

---

boot/freeldr/freeldr/include/arch/amd64/amd64.h
boot/freeldr/freeldr/ntldr/arch/amd64/winldr.c
sdk/include/ndk/amd64/ketypes.h

It is not used by either ReactOS or Windows.
We are saving 4KB of memory!1!11

[FREELDR][NDK][X64] Remove KIP0PCRADDRESS definition and mapping

---

sdk/cmake/msvc.cmake

MSVC defaults to always reporting 199711L to satisfy broken C++ code. You have to add a command line argument to make it work correctly. See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170

[CMAKE] Enable proper definition of __cplusplus macro on MSVC

---

sdk/lib/atl/atlcore.h

[ATL] CComCriticalSection destructor should not be virtual

---

boot/freeldr/freeldr/arch/amd64/entry.S
boot/freeldr/freeldr/arch/i386/multiboot.S
boot/freeldr/freeldr/pcat.cmake
sdk/include/asm/asm.inc

Add Multiboot Header to Allow freeldr boot via Grub2 or any Bootloader compatible with Multiboot v1
JIRA issue: [CORE-18374](https://jira.reactos.org/browse/CORE-18374)
amd64:
i386:
amd64:
i386:

[FREELDR/x64] Add Multiboot header

---

boot/freeldr/freeldr/arch/i386/multiboot.S

Fix the `_MultibootInfoPtr` pointer size for amd64

[FREELDR/x64] Fix the Multiboot Pointer Size

---

base/system/services/database.c
base/system/services/rpcserver.c
base/system/services/services.h

Use pointers to const string (PCWSTR) instead of non-const for argv

[SERVICES] Use pointers to const string (PCWSTR) instead of non-const for argv

---

sdk/tools/mkisofs/CMakeLists.txt

On macOS, CMAKE_C_COMPILER_ID is "AppleClang". While this certainly is Clang, it does not match the exact string "Clang" that is being checked for, and as a result the warning flags guarded thereby are not passed to the compiler.
Get CMake to recognize both "Clang" and "AppleClang".

[MKISOFS] Fix Clang check for macOS platforms

---

CMakeLists.txt
media/doc/3rd Party Files.txt
sdk/cmake/gcc.cmake
sdk/include/ddk/d3dkmthk.h
sdk/include/psdk/d3dkmdt.h
sdk/include/psdk/d3dukmdt.h
win32ss/gdi/gdi32_vista/dc.c

As mentioned, MS released variants of 3/4 WDDM headers under MIT under this repo.
Pulled from commit:
https://github.com/microsoft/libdxg/commit/045831efab4b1e50db2b658dc9e129f11b84b549
Source:
https://github.com/microsoft/libdxg/tree/045831efab4b1e50db2b658dc9e129f11b84b549/include
This PR just imports them

[SDK] Import MIT-licensed WDDM headers from libdxg

---

win32ss/user/ntuser/main.c
win32ss/user/ntuser/object.h
win32ss/user/ntuser/painting.c
win32ss/user/ntuser/win32.h
win32ss/user/ntuser/window.c

Fixes some referencing issues.
- Add debug assertions that all callout references are cleaned up, when the thread exits
- Fix 2 instances of callout referencing
- GCCLin_x86 on Test KVM: https://reactos.org/testman/compare.php?ids=90169,90176,90181,90184
- MSVC_x64 on Test KVM_x64: https://reactos.org/testman/compare.php?ids=90170,90178,90182,90189

[WIN32K] Fix/improve User callout referencing

---

sdk/lib/rtl/amd64/except_asm.S

According to tests, legacy fp state is not saved in kernel mode. Also add an int 2c to the path that changes cs, as it should not be used and probably never will be.
Test KVM x64: https://reactos.org/testman/compare.php?ids=98478,98482,98485,98487

[RTL/x64] Fix RtlCaptureContext/RtlpRestoreContextInternal in kernel mode

---

dll/win32/version/version.c

CORE-19783
Co-authored-by: Timo Kreuzer <timo.kreuzer@reactos.org>
_Fix VerQueryValueW that returns bad Value data when it should return NULL._
JIRA issue: [CORE-19783](https://jira.reactos.org/browse/CORE-19783)
_If the wValueLength is zero, then set a UNICODE_NULL only return string._
_Use the NULL terminator from the key string for that. This is what Windows does, too._

[VERSION] Fix VerQueryValue when return Value is NULL.

---

win32ss/user/ntuser/timer.c

Based on the [Doug-Lyons](https://github.com/Doug-Lyons) test, I found that my previous fix stopped working partially. Or rather, it would only work until the 32767 indexes were exhausted. It seems to me that the behavior of the bitfield has changed, because when I published the previous patch, it passed my tests.
Previous patch versions: #7087
- Bit array generates free ID cyclically, in the previous code after 32767 indexes expired the same index was returned, because of this the previous fix would stop working after expiration, so I changed the logic of calculating the next index.
- I changed the index range to 256-32767 to match Windows, indexes 0-255 can theoretically be used as fixed for system purposes.

[NTUSER] IntSetTimer(): Update HintIndex on each call (update)

---

base/applications/cmdutils/more/more.c

It is useless to check individually and to try to load again.
Follow-up to 2dbbfe8 (0.4.15-dev-2691).
- Use a common flag.

[MORE] PagePrompt(): Optimize check to load string resources

---

modules/rostests/winetests/msvcrt/msvcrt.h
sdk/include/crt/xmmintrin.h
sdk/lib/crt/wine/msvcrt.h

Addendum to commit 318d696f0
It should now be possible to re-enable the MS-PSDK/CRT-compatible malloc.h inclusion in the xmmintrin.h header;
however Wine code is still incompatible in this regard.
The following build errors only happen in 32-bits, but not in 64-bits.
_**MSVC:**_
```
FAILED: sdk/lib/crt/CMakeFiles/crt.dir/wine/cpp.c.obj 
d:\a\reactos\reactos\src\sdk\lib\crt\wine\msvcrt.h(1066): error C4028: formal parameter 1 different from declaration
```
_**Clang:**_
```
FAILED: sdk/lib/crt/CMakeFiles/crt.dir/wine/cpp.c.obj 
In file included from D:\a\reactos\reactos\src\sdk\lib\crt\wine\cpp.c:31:
D:\a\reactos\reactos\src\sdk\lib\crt\wine/msvcrt.h(1066,18): error: conflicting types for 'malloc'
void* __cdecl    MSVCRT_malloc(MSVCRT_size_t);
^ …
```

[SDK:CRT] Reenable malloc.h inclusion in xmmintrin.h

---

dll/win32/shell32/shlexec.cpp
modules/rostests/apitests/shell32/ShellExecuteEx.cpp
modules/rostests/apitests/shell32/closewnd.cpp
modules/rostests/apitests/shell32/closewnd.h

This is mainly to fix the shell32 apitest, a better way to handle `SEE_MASK_IDLIST` should be investigated in the future. ShellExecuteEx with a PIDL that points to a folder should be handled the same as ShellExecuteEx with lpFile set to a folder path, there is no need for all this special handling.
The api test close window code seems to be more robust like this and hopefully fixes the Notepad issue discovered in chat today.
refs/pull/7464/merge on 0.4.16-dev-149-g5797340
WHS: https://reactos.org/testman/compare.php?ids=98388,98390 LGTM

[SHELL32][SHELL32_APITEST] Fix ShellExecuteEx IDLIST folder

---

win32ss/gdi/ntgdi/freetype.c

CORE-19768
Follow up of PR #7274. This stops WARN's from FF 28 as well on ASCII 0x007f (del characters).
Addendum to https://github.com/reactos/reactos/commit/a1bff5b94efa36b9e48d37f91b56428131c10531
_Account for x-dimension for non-breaking space characters._
JIRA issue: [CORE-19768](https://jira.reactos.org/browse/CORE-19768)
_Test for ASCII char 0x00a0 and account for typical space character in x-dimension._
_Ignore ASCII chars less that space (0x0020) since they are normally control characters._
_Ignore ASCII char 'del' (0x007f) because this is a 'DELETE' character and should have no width._

[NTGDI:FREETYPE] Account for non-breaking spaces in x-dim of IntExtTextOutW

---

dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CNetFolder.cpp
dll/win32/shell32/folders/CNetFolder.h

- Don't add a class to the My Computer context menu so the "New" item is not added (not a filesystem folder, cannot create new items here).
- Add Properties item to My Network Places context menu.

[SHELL32] No new menu and working properties in Drives and NetHood background menu

---

modules/rosapps/applications/sysutils/pedump/pedump.c
modules/rosapps/applications/sysutils/regexpl/ShellCommandValue.cpp
modules/rostests/tests/sertest/sertest.c
sdk/lib/drivers/copysup/copysup.c
sdk/lib/drivers/rdbsslib/rdbss.c

Fix typos in comments or log outputs.
- Writting -> Writing
Same typos in 3rd-party files are not modified:
- base\services\nfsd\service.h
- boot\environ\include\efi\BlockIo.h
- boot\environ\include\efi\UgaDraw.h
- dll\opengl\mesa\pb.c

[REACTOS] Fix 'writting' typos

---

ntoskrnl/ex/keyedevt.c

Fix warnings:
>E:\3rdRepo\ReactOS_Fork4\ntoskrnl\ex\keyedevt.c(458): warning C6387: 'Timeout' could be '0':  this does not adhere to the specification for the function 'ExpWaitForKeyedEvent'. 
E:\3rdRepo\ReactOS_Fork4\ntoskrnl\ex\keyedevt.c(527): warning C6387: 'Timeout' could be '0':  this does not adhere to the specification for the function 'ExpReleaseKeyedEvent'. 
`Timeout` parameter of those two functions should be optional.

[NTOS:EX] Fix SAL notations, `Timeout` parameter should be optional

---

sdk/tools/spec2def/spec2def.c

This is used by wine spec files.

[SPEC2DEF] Implement support for negated architecture

---

ntoskrnl/mm/ARM3/miarm.h
ntoskrnl/mm/ARM3/pool.c
sdk/include/xdk/mmfuncs.h

Implement `MmAllocateMappingAddress` and `MmFreeMappingAddress` routines.
Based on mm-implement-mappingaddress.patch by @ThFabba  with some suggestions from @zefklop applied.
Split from #3654.
Required by Microsoft NTFS driver (from Windows Server 2003 SP2 only, the one from Windows XP SP3 does not need them) and by NDIS & TDI drivers (both from Windows XP SP3 and Windows Server 2003 SP2). Also they are called when using Dr. Web Security Space 8 filter drivers together with MS FltMgr & TDI.
Fortunately, this part (these two routines) are enough to get the drivers working in all cases, and others (partially incomplete) routines are not badly required, so they can be finished and committed later.
JIRA issue: [CORE-10147](https://jira.reactos.org/browse/CORE-10147), …

[NTOS:MM] Implement MmAllocate/FreeMappingAddress

---

dll/3rdparty/libtirpc/src/rpc_generic.c
dll/win32/winhttp/inet_ntop.c
dll/win32/wininet/inet_ntop.c
dll/win32/ws2_32/src/addrconv.c
dll/win32/ws2_32/ws2_32.spec
modules/rostests/winetests/ws2_32/sock.c
sdk/include/psdk/ws2tcpip.h
sdk/lib/rtl/network.c

Add implementations of the functions inet_pton and inet_ntop
Add implementations for the functions and their Unicode counterparts
Sync the wine tests for these functions.
Import WINE's implementation for RtlIpv6StringToAddress* (used by inet_pton) as the current implementation fails in tests
These are common functions and should be used instead of attempting to reimplement IP<->String conversions.

[WS2_32] Implement inet_pton and inet_ntop

---

base/applications/mscutils/servman/lang/ro-RO.rc

Improvements based on recent Romanian translation document revision https://github.com/reactos/reactos/commit/06e89b2e81cd7de029fac2c595a6371eba13d797.

[SERVMAN] Update Romanian (ro-RO) translation

---

base/applications/msconfig_new/lang/ro-RO.rc

Improvements based on recent Romanian translation document revision https://github.com/reactos/reactos/commit/06e89b2e81cd7de029fac2c595a6371eba13d797.

[MSCONFIG_NEW] Update Romanian (ro-RO) translation

---

base/applications/regedit/clb/lang/ro-RO.rc

[CLB] Update Romanian (ro-RO) translation

---

modules/rosapps/applications/sysutils/fontsub/lang/ro-RO.rc

[FONTSUB] Update Romanian (ro-RO) translation

---

base/applications/msconfig/lang/ro-RO.rc

[MSCONFIG] Update Romanian (ro-RO) translation

---

dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp

If a .lnk shortcut does not specify a working directory, it should use the directory provided by the `InvokeCommand` caller.
JIRA issue: [CORE-19855](https://jira.reactos.org/browse/CORE-19855)

[SHELL32][BROWSEUI] Set DefView InvokeCommand directory

---

dll/win32/shell32/COpenWithMenu.cpp
dll/win32/shell32/dialogs/filetypes.cpp

Unlike Windows, ROS OpenWith does not fully take over the association by redirecting the ProgId. The best we can do is try to make the new verb the default.
Notes:
- ROS only implements Windows 95 style ProgId handling and cannot behave like XP OpenWith at this point in time.
- The change to FriendlyTypeName allows the user to customize the type description for extensions without a ProgId. We could allow the user to always override it for extensions with a ProgId as well but Windows does not allow that for types with a  FriendlyTypeName already set.
- No longer writes the default icon string if the icon was not changed by the user.
JIRA issue: [CORE-19816](https://jira.reactos.org/browse/CORE-19816)

[SHELL32] Force FileType OpenWith default verb

---

drivers/filesystems/fs_rec/CMakeLists.txt
drivers/filesystems/fs_rec/ext.c
drivers/filesystems/fs_rec/ext.h
drivers/filesystems/fs_rec/fs_rec.c
drivers/filesystems/fs_rec/fs_rec.h

Rename the Ext2 recognizer to a more generic Ext to be more future-proof with a possible upcoming ext4 support.  
Also, it already makes no sense to use the name ext2 as it already recognizes all the FS of the "Ext family".
- rename the Recognizer
- add missing Ext CDs recognizer

[FS_REC] Rename Ext2 recognizer to Ext recognizer

---

ntoskrnl/mm/section.c

`MiGrabDataSection` adds a refcount. There is a missing `MmDereferenceSegment` cleanup in case of range check error.
Move `MiGrabDataSection` calling code to after range check.

[NTOS:MM] MmPurgeSegment: Fix missing MmDereferenceSegment cleanup

---

sdk/include/psdk/intsafe.h

This avoids redefinition warnings.

[PSDK] intsafe.h: Define MIN/MAX macros the same way as in stdint.h

---

dll/win32/shlwapi/string.c
modules/rostests/apitests/shlwapi/StrDup.c

This avoids Alloc/Free while also matching the Windows behavior.

[SHLWAPI][SHLWAPI_APITEST] Optimize StrRetToStrW WSTR handling

---

ntoskrnl/fsrtl/fastio.c

Don't return before file object's resource is acquired in `FsRtlAcquireFileExclusiveCommon`, except some special return cases, when return is required.
Based on hpoussin_filter_extra.patch by Hervé Poussineau (@hpoussin) with improved comment, which matches the actual behaviour now.
This is required by fltmgr.sys driver from Windows XP/Server 2003 to work correctly, so this change fixes asserts/exceptions when releasing the file via `FsRtlReleaseFile` after acquiring, when using 3rd party filter drivers from several antivirus programs (e. g., Avast Free Antivirus all versions, AVG Antivirus Free 18.8, Avira AntiVir Personal 8.2, Dr. Web Security Space 8.0, Kaspersky Antivirus 2012, etc.).
JIRA issue: [CORE-14157](https://jira.reactos.org/browse/CORE-14157), …

[NTOS:FSRTL] FsRtlAcquireFileExclusiveCommon: don't return before acquiring a file resource, except special cases

---

dll/win32/shell32/wine/shellord.c

We should read the items we have not cached yet in case we write REGSHELLSTATE for the first time before Explorer does it.

[SHELL32] Refresh SHELLSTATE before writing it

---

ntoskrnl/cc/copy.c
ntoskrnl/cc/pin.c
ntoskrnl/cc/view.c
ntoskrnl/include/internal/mm.h
ntoskrnl/mm/section.c

Use section object pointer with byte offset instead of using base address. This simplifies the Mm functions themselves and also the code in Cc that calls them.
Replace Mm functions:
`MmArePagesResident` -> `MmIsDataSectionResident`
`MmMakePagesDirty` -> `MmMakeSegmentDirty`
Also adds minor fixes for `MmFlushSegment` and `MmPurgeSegment`.

[NTOS:MM][NTOS:CC] Rewrite some cache memory management functions

---

base/shell/explorer/explorer.cpp

Improved detection of Explorer being the default shell.
JIRA issue: [CORE-19887](https://jira.reactos.org/browse/CORE-19887)
- Check the "Software\Microsoft\Windows NT\CurrentVersion\Winlogon" key to see if Explorer is the default shell.
- Use this check to determine whether to start the desktop & taskbar or only open a file browser window.

[EXPLORER] Check registry key for default shell

---

base/shell/explorer/explorer.cpp

Minor code simplification/fix.
Addendum to df197bc (0.4.16-dev-302).
JIRA issue: [CORE-19887](https://jira.reactos.org/browse/CORE-19887)
- Remove redundant bIsSystemShell assignments.
- And fix StrStrI() typo.

[EXPLORER] Remove redundant bIsSystemShell assignments

---

boot/freeldr/freeldr/lib/peloader.c

Use the PE import table's OriginalFirstThunk array when scanning and
resolving imports during DLL binding.
It points to an array of pointer-sized IMAGE_THUNK_DATA structures
which describe the functions being imported. On the other hand, the
FirstThunk points to an array of pointers, whose initial values are
a copy of those pointed to by OriginalFirstThunk, but are replaced
by the actual function pointers determined at runtime, when a DLL
is loaded (see PeLdrpBindImportName() function).
If we were to use the FirstThunk array to find again later the imports
by name or ordinal, we would fail because these are replaced by the
addresses of the corresponding functions.
This fixes loading kdcom.dll from Windows XP x64 with FreeLDR when
testing on ReactOS x64.
```diff …
```

[FREELDR] peloader.c: Fix PE import binding

---

ntoskrnl/kd64/amd64/kdx64.c
ntoskrnl/kd64/i386/kdx86.c

- ### `[NTOS:KD64] kdx86.c: Fix the Dr7 check to verify whether disabling the debugger is allowed.`
Don't check the whole Dr7 value, but only the first 8 bits that
correspond to the local/global enable breakpoints.
We cannot check the whole value because some of the Dr7 bits are
reserved always set to 1 (bit 10), or describe other debug state.
- ### `[NTOS:KD64] kdx64.c: Implement KdpAllowDisable() the same as in x86.`
AMD64 has the same DR7 register as x86 with the same bits meanings,
thus the same implementation can be used.
- https://en.wikipedia.org/wiki/X86_debug_register#DR7_-_Debug_control
- AMD64 Architecture Programmer’s Manual, Volume 2: System Programming
https://www.amd.com/content/dam/amd/en/documents/processor-tech-docs/programmer-references/24593.pdf
Section "13.1.1.4 …

[NTOS:KD64] KdpAllowDisable(): Fix DR7 check in x86; implement the function for x64

---

ntoskrnl/kd64/kdinit.c

In KdInitSystem(), polling for break-in on symbol load should be done _only_ after symbols are loaded at boot-time,
i.e. when LoaderBlock != NULL and we have loaded the initial hal and ntoskrnl symbols. KdBreakAfterSymbolLoad is then checked for when the other boot symbols have been loaded by ex/init.c!ExpLoadBootSymbols(), invoked by ExpInitializeExecutive().

[NTOS:KD64] KdInitSystem(): Poll for break-in on symbol load *ONLY* at boot-time.

---

sdk/include/crt/corecrt.h

Taken from MIT release of UCRT. These are used by newer mingw headers, which we include when compiling C++ code. Fixes build with GCC 13 based RosBE.

[CRT] corecrt.h: add secure function overload macros

---

dll/win32/ieframe/lang/ro-RO.rc

[IEFRAME] Update Romanian (ro-RO) translation

---

modules/rosapps/applications/devutils/vgafontedit/lang/ro-RO.rc

[VGAFONTEDIT] Update Romanian (ro-RO) translation

---

dll/win32/winmm/CMakeLists.txt
dll/win32/winmm/playsound.c

Currently, if the user environment variables (for example: `%Temp%`) are specified in the path of a system sound. The `PlaySound` function still use the system environment variables when impersonating (for example: `%Temp%` will be expanded to `C:\ReactOS\Temp` instead of the user's Temp folder). This is incorrect.
JIRA issue: [CORE-13951](https://jira.reactos.org/browse/CORE-13951)

[WINMM] PlaySound: Fix user environment variables handling

---

boot/freeldr/freeldr/lib/inifile/ini_init.c
boot/freeldr/freeldr/settings.c

Make freeldr more compatible with w2k3 ini file.
Fall back to using boot.ini file (from NTLDR) if freeldr.ini doesn't exist.

[FREELDR] Make it more compatible with w2k3 ini file

---

modules/rostests/apitests/user32/RedrawWindow.c

This is a continuation of: https://github.com/reactos/reactos/pull/7160
As part of fixing some bugs, they extend the tests to include more detailed testing of rendering functions. In this PR, I am extending the RedrawWindow testing to include tests of all flags. As part of the testing, I am also testing the 2-point states of the render areas.
I left the original test unchanged in a separate function GetMessageRedrawWindowTest. For the flag tests I created the FlagsRedrawWindowTest function.The function sequentially tests the RedrawWindow with different flag combinations and compares the results with those found from Windows XP/Windows 11 (the values for both versions are identical).
The API test turned out well in ReactOS, the only deviation was that in many cases (whenever the …

[USER32_APITEST] Improve RedrawWindow API test. Follow up of #7160

---

ntoskrnl/ke/amd64/traphandler.c
ntoskrnl/ke/amd64/usercall.c

This is a temporary helper for the system call entry point to store the user mode stack, before switching to the kernel mode stack. Initially it was copied to the trap frame inside KiSystemCallHandler. This has been moved to the system call entry point, but some remnants remained. The problem is that KiSystemCallHandler can be called twice in a system call (when the call is the first GUI call and the stack needs to be extended). In that scenario, when the thread was preempted, a new value could be saved in the PCR before running KiSystemCallHandler again, and then overwriting the proper value with a bogus one from a different thread. This rarely seemed to happen on UP, but happens a lot with SMP.

[NTOS:KE/x64] Fix handling of PCR::UserRsp

---

hal/halx86/apic/apic.c
hal/halx86/apic/rtctimer.c
hal/halx86/include/halp.h
ntoskrnl/include/internal/amd64/ke.h
ntoskrnl/ke/amd64/trap.S
ntoskrnl/ke/time.c

Improve some x64 trap handling code.
- [NTOS:KE/X64] Fix KiInterruptDispatch
- [HAL] Remove KiEoiHelper hack
- [NTOS][HAL:APIC] Call HalBegin/EndSystemInterrupt from clock handler
- KVM x86: https://reactos.org/testman/compare.php?ids=99107,99130,99127
- KVM x64: https://reactos.org/testman/compare.php?ids=99108,99111

[NTOS][HAL] Improve x64 trap handling code

---

drivers/battery/battc/battc.c

`KeWaitForSingleObject` takes 100ns unit for timeout. Both **IOCTL_BATTERY_QUERY_TAG** and **IOCTL_BATTERY_QUERY_STATUS** take a wait for the timeout in milliseconds. Supposedly a miniport driver wants to supply a wait of **5000 ms** (which is equivalent to **5 s**), the miniport driver **WON'T BE WAITING** 5 seconds but 0.5!!!
I discovered this bug when I was implementing battery support in ReactOS and I noticed when supplying a timeout to one of the IOCTLs like 3000, the thread did not way for 3 seconds.
This patch is needed for the development of Power Manager (#5719) to continue. Stay tuned for further updates!
[CORE-18969](https://jira.reactos.org/browse/CORE-18969)
[CORE-19452](https://jira.reactos.org/browse/CORE-19452)

[BATTC] Fix the wait timeout conversion

---

drivers/bus/acpi/cmbatt/cmbatt.c
drivers/bus/acpi/cmbatt/cmbatt.h

ReactOS (like any other OSes) expects power data to be represented in milliwatts per hour, not in milliamps per hour. Currently **Control Method Battery** **(CMBATT)** defaults the stats to unknown values, if that's the case, and there are a bunch of machines that do report their data from `_BIF` ACPI method in ampere.
The formula to do so is:
```
(milliAmpere * Volts + 500) / 1000
```
This patch is needed for the development of Power Manager (#5719) to continue. Stay tuned for further updates!
- Convert the power stats from mAh unit to mWh when verifying the power static info
- Annotate `CmBattVerifyStaticInfo` with SAL2
[CORE-18969](https://jira.reactos.org/browse/CORE-18969)
[CORE-19452](https://jira.reactos.org/browse/CORE-19452)

[CMBATT] Convert power statistics from mAh to mWh

---

drivers/battery/battc/battc.c

`BatteryClassStatusNotify` is used by battery miniport drivers to notify the Battery Class of a status change. This can either be a battery status change or battery tag assignation, depending on what the device extension (namely the composite battery) waits for.
We do have implementation for **EVENT_BATTERY_STATUS** but not for **EVENT_BATTERY_TAG**. What happens is when `BatteryClassIoctl` fails to query the battery tag because it has not yet been assigned, the thread is stuck on waiting for the event object to be signaled, forever. This typically happens when a timeout of -1 (meaning the calling thread must wait indefinitely) is supplied. The **composite battery driver (COMPBATT)** is responsible to signal the **Battery Class** when a **CM (Control Method) ACPI battery** receives a tag, …

[BATTC] Signal the wait battery tag event when notifying Battery Class

---

dll/shellext/stobject/power.cpp

We do have **IDS_PWR_HOURS_REMAINING** and **IDS_PWR_MINUTES_REMAINING** string resources but they're never used programmatically. Display the estimated battery time ONLY if the returned time is not unknown.
This patch is needed for the development of the Power Manager (#5719) to continue.
[CORE-18969](https://jira.reactos.org/browse/CORE-18969)
[CORE-19452](https://jira.reactos.org/browse/CORE-19452)

[STOBJECT] Display the estimated battery time when hovering the battery icon

---

modules/rostests/apitests/ntdll/NtQueryInformationProcess.c
ntoskrnl/include/internal/ps_i.h
ntoskrnl/ps/query.c

Fix length mismatch error log spam while running sysinternals Process Explorer.
- `NtQueryInformationProcess`: Move process info-specific variables to their own scope.
- Add query support for `ProcessQuotaLimits` info class with `QUOTA_LIMITS_EX`.
- `NtQueryInformationProcess`: Add api tests for `ProcessBasicInformation` and `ProcessQuotaLimits` info classes.
Test Win2k3:
ReactOS Before:
ReactOS After:

[NTOS:PS][NTDLL_APITEST] Add query support for QUOTA_LIMITS_EX

---

win32ss/user/ntuser/msgqueue.c

Check for NULL desktop window in co_IntProcessMouseMessage
Prevents kernel crash, when creating the desktop window failed.

[WIN32K] Check for NULL desktop window in co_IntProcessMouseMessage

---

ntoskrnl/ke/amd64/cpu.c
sdk/include/reactos/x86x64/Cpuid.h

[SDK] Fix naming of a CPUID structure

---

dll/win32/shell32/debughlp.cpp
dll/win32/shell32/wine/pidl.c

This is related to [CORE-19944](https://jira.reactos.org/browse/CORE-19944) where the created shortcut cannot load the stored PIDL because it's a custom format.

[SHELL32] ILLoadFromStream must allow loading unknown pidl formats

---

dll/win32/shell32/CDefaultContextMenu.cpp

JIRA issue: [CORE-18733](https://jira.reactos.org/browse/CORE-18733) (FastStone Viewer calls IContextMenu::InvokeCommand with capital case verb "Properties" directly).

[SHELL32] CM::InvokeCommand case-insensitive compare verb string

---

dll/win32/shell32/shlexec.cpp
sdk/include/reactos/shlwapi_undoc.h

`ShellExecuteA` correctly calls `ShellExecuteExA` but `ShellExecuteW` somehow skipped `ShellExecuteExW` and called the internal function directly. This means it missed out on the MaximizeApps registry setting, the RunDLL32 handling and CoInitialize.
Also adds the DDEWAIT/NOASYNC flag for 99% of callers (unless the [WIN95SHLEXEC](https://www.geoffchappell.com/studies/windows/shell/shlwapi/api/util/getappcompatflags.htm) compatibility flag is active for the current process).
JIRA issue: [CORE-19952](https://jira.reactos.org/browse/CORE-19952)

[SHELL32] ShellExecuteW must call ShellExecuteExW

---

dll/win32/shell32/brfolder.cpp

The PR #7437 was for fixing the JIRA issue [CORE-19751](https://jira.reactos.org/browse/CORE-19751). I agree with the bugfix, however it introduced a side effect that made impossible to expand a folder when it contained both a ZIP file and subfolders. Fix this by ignoring the return value of `BrFolder_InsertItem` and free the pidlTemp explicitly in all cases.
Jira issue: [CORE-19955](https://jira.reactos.org/browse/CORE-19955)

[SHELL32] Fix BrowseForFolder unable to expand a folder when it contains a zip

---

ntoskrnl/ps/query.c

Use the information from `EPROCESS::Vm`.
Addendum to commit 1e06829961cb597f7e1927a5e35b66febe674a96.
Tests result doesn't change.

[NTOS:PS] Fix returned flags for QUOTA_LIMITS_EX query

---

drivers/bus/acpi/cmbatt/cmbatt.c
drivers/bus/acpi/cmbatt/cmbatt.h
drivers/bus/acpi/cmbatt/cmexec.c

`_BIX` is basically `_BIF` but with more information added, such as cycle count, measurement capacity accuracy and whatnot. Starting with **ACPI 4.0** `_BIF` is rendered obsolete and as a matter of fact a lot of modern hardware fill their ACPI machine data to `_BIX`.
ReactOS must go forward and beyond to support modern hardware, compatibility with **_BIF** is kept. NOTE that a machine can **ONLY** support one battery static information method!
This patch is needed for the development of the Power Manager (#5719) to continue. It is also needed to implement further algorithms that detect if a battery has totally worn out (impending death is imminent), and if so, the user should be warned.
- Implement `CmBattGetBixData`;
- Rename `IOCTL_BATTERY_QUERY_BIF` to `IOCTL_BATTERY_QUERY_BIF_BIX` and …

[CMBATT] Implement support for the _BIX method

---

dll/win32/shell32/wine/control.c

If an out of range dialog box number was given in a single comma syntax for Control_RunDLL, it should be set to 0 to launch the default dialog box instead of failing. 
Should fix [CORE-19580](https://jira.reactos.org/browse/CORE-19580)

[SHELL32] Fix Control_RunDLL single comma syntax out of range dialogbox numbers

---

modules/rostests/apitests/ntdll/CMakeLists.txt
modules/rostests/apitests/ntdll/NtQueryObject.c
modules/rostests/apitests/ntdll/testlist.c
modules/rostests/kmtests/ntos_ob/ObQuery.c
ntoskrnl/io/iomgr/file.c

Fix special case in IopQueryNameInternal() invoked from NtQueryObject(ObjectNameInformation)
- ### `[NTDLL_APITEST][KMTESTS] Add tests for NtQueryObject(ObjectNameInformation)`
- ### Implement the actual fix.
Windows 2003:
Windows 7 (I just ran the ntdll_apitest user-mode test):
ReactOS - Before:
ReactOS - After:

[NTOS:IO] Fix special case in IopQueryNameInternal() invoked from NtQueryObject(ObjectNameInformation)

---

dll/win32/shell32/dialogs/item_prop.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shldataobject.cpp

Addendum to PR #7571. Because SHOpenPropSheetW is modal, there is no way for us to keep COM alive on the original thread until the dialog completes, so a cloned data object is used instead so that the property sheet handlers may access the object even after ShellExeute has returned (this is only relevant for callers like Taskmgr that does not initialize COM even though MSDN says they should).
[CORE-19933](https://jira.reactos.org/browse/CORE-19933)

[SHELL32] Clone properties IDataObject for unlimited lifetime

---

sdk/include/psdk/wlanapi.h

Be able to tell if the WLAN adapter's radio is turned off from ReactOS (software) or from a button/toggle on device (hardware). All three proposed pieces are available at least as of Windows SDK 6.0A (Visual Studio 2008).
Used by [`WlanQueryInterface`](https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlanqueryinterface) with `wlan_intf_opcode_radio_state` opcode.
JIRA issue: [CORE-6905](https://jira.reactos.org/browse/CORE-6905)
Example use case: [wlanwiz.dll, `OnScanNetworks`](https://github.com/SigmaTel71/reactos/blob/b5f603b5c47f772c28e76074a407d02ea6ced7fd/dll/shellext/wlanwiz/scan.cpp#L37)
- Add [WLAN_PHY_RADIO_STATE](https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/ns-wlanapi-wlan_phy_radio_state) struct
- Add …

[PSDK] Add structures and enumeration describing radio power state

---

drivers/bus/acpi/compbatt/compbatt.c
drivers/bus/acpi/compbatt/compbatt.h
drivers/bus/acpi/compbatt/compmisc.c
drivers/bus/acpi/compbatt/comppnp.c

This PR is an attempt to resuscitate the **Composite Battery** driver which is broken, barely usable and it even asserts the kernel because it improperly uses a function with incorrect parameter(s). Nevertheless there are several unimplemented functions which makes the entire driver useless.
With this PR now it can properly talk with the **Battery Class** and **Control Method Battery** drivers via IOCTLs, it can query battery status of each individual ACPI battery and gather static information.
The PR must shall be reviewed by commit, I'll signal everyone that is ready to review once I finished the TODOs. The PR is needed for the development of the Power Manager (#5719) to continue.
- Implement `CompBattSetStatusNotify`
- Implement `CompBattQueryStatus`
- Implement …

[COMPBATT] Resuscitate the Composite Battery driver

---

sdk/include/psdk/batclass.h

Windows SDKs define this constant to **0xFFFFFFFF** but we define it to **0x80000000**. As a result, when our COMPBATT driver is being tested on Windows (namely XP, Vista and 7), `BATTERY_UNKNOWN_TIME` is not interpreted as UNKNOWN TIME but entirely something else.
This patch is needed for further development of #5719 to continue.
[CORE-18969](https://jira.reactos.org/browse/CORE-18969)
[CORE-19452](https://jira.reactos.org/browse/CORE-19452)

[PSDK] Fix BATTERY_UNKNOWN_TIME value constant

---

dll/win32/shell32/shlexec.cpp

Get rid from bogus `SearchPathW`() call, which is marked as most likely not needed in the comment above (by Wine). Simply get a length of the file name and use the file name directly instead, with checking for its validity too. Similarly as it's done for other cases. That call seems actually not needed because it is already done using `SearchPathW`() in another parts of the code in this file, before calling `SHELL_ArgifyW`(). Fixes another heap corruption when trying to login via OAuth method in SpotifyXP 2.0.3 Beta (nightly build).
JIRA issue: [CORE-19953](https://jira.reactos.org/browse/CORE-19953)
- Use `lpFile` explicitly instead of passing it to `SearchPathW`() and using returned data from it.
- Check for a valdity of input 'lpFile' parameter (`!= NULL`).
- Get rid from no longer …

[SHELL32] SHELL_ArgifyW(): don't use SearchPathW() for receiving a path to a file

---

base/applications/rapps/gui.cpp
base/applications/rapps/include/misc.h
base/applications/rapps/include/rapps.h
base/applications/rapps/include/winmain.h
base/applications/rapps/unattended.cpp
base/applications/rapps/winmain.cpp

While most of RApps will happily run with multiple instances, the database update code will delete the whole database directory and assumes nobody else is accessing the directory at the same time.
I made it time out and ignore the lock after 10 minutes just in case somebody is using this in a headless configuration and something somehow broke the update mechanism or is holding a lock on one of the files.

[RAPPS] Protect database update with a mutex

---

drivers/bus/acpi/cmbatt/cmbatt.c
drivers/bus/acpi/cmbatt/cmbatt.h

There are a few issues with the estimated battery time code. First, in `CmBattGetBatteryStatus` we are checking if the battery was discharging for the first time, but we are checking that against **ACPI_BATT_STAT_DISCHARG**. This bit flag is returned by **_BST** ACPI control method in `BstState`, therefore checking the presence of such bit flag against `DeviceExtension->State` is wrong from the start.
The correct approach should be, cache the previous power state of an individual CM battery before resetting it, and check right away if the battery used to discharge before. If not, update the discharge time. Furthermore, in `CmBattQueryInformation` we should be checking if the battery has been discharging for over 15 seconds but the current code does something different.. Fix that.
This …

[CMBATT] Minor improvements to estimated battery time code

---

base/applications/regedit/treeview.c

If we delete a key while the label edit control is visible, the GUI gets messed up and can only be fixed by pressing Esc when the correct control has focus.

[REGEDIT] Block tree label edit if the delete accelerator has been pressed

---

base/services/nfsd/CMakeLists.txt
dll/directx/wine/d3drm/CMakeLists.txt
dll/win32/msxml3/CMakeLists.txt
drivers/filesystems/fastfat/create.c
drivers/filesystems/udfs/CMakeLists.txt
drivers/wdm/audio/drivers/CMIDriver/CMakeLists.txt
sdk/cmake/gcc.cmake
sdk/cmake/msvc.cmake
sdk/include/crt/math.h
sdk/include/crt/stdlib.h
sdk/include/psdk/rpc.h
sdk/include/reactos/wine/exception.h
sdk/include/vcruntime/excpt.h
sdk/include/vcruntime/mingw32/intrin_x86.h
sdk/include/vcruntime/vcruntime.h
sdk/include/vcruntime/xmmintrin.h
sdk/lib/3rdparty/zlib/CMakeLists.txt
sdk/lib/pseh/CMakeLists.txt
sdk/lib/pseh/include/pseh/pseh2.h

A number of fixes and improvements for clang build.
- Fix build with clang-cl 17 (shipped with VS 2022)
- Fix PSEH usage with clang
- Silence a number of warnings
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=99304,99487,99493,99506,99512

Clang build fixes/improvements

---

base/applications/rapps/geninst.cpp

This is useful for wallpaper and theme packs.

[RAPPS] Allow .zip generated installers to skip writing the DisplayIcon value

---

ntoskrnl/mm/balance.c

- Fix `PageOutThreadActive` value check
- Properly mark [CORE-17624](https://jira.reactos.org/browse/CORE-17624) delay hack
- `MiBalancerThread`: Formatting fixes
- ~Fix usage of `MiBalancerDoneEvent` and remove [CORE-17624](https://jira.reactos.org/browse/CORE-17624) delay hack (optional)~ Cancelled because this caused BSoD 0xF4 when running low on memory.

[NTOS:MM] Balancer minor fixes

---

dll/win32/shell32/propsheet.cpp
dll/win32/shell32/utils.cpp

Improve consistency of code management.
- Move `SHOpenPropSheetA` from `utils.cpp` into `propsheet.cpp` that contains `SHOpenPropSheetW`.

[SHELL32] Move SHOpenPropSheetA to propsheet.cpp

---

dll/directx/wine/d3drm/CMakeLists.txt
dll/directx/wine/d3dxof/CMakeLists.txt
dll/win32/comdlg32/CMakeLists.txt
dll/win32/cryptui/CMakeLists.txt
dll/win32/ieframe/CMakeLists.txt
dll/win32/inetcomm/CMakeLists.txt
dll/win32/wininet/CMakeLists.txt
sdk/include/psdk/basetsd.h
sdk/include/psdk/windef.h
sdk/include/psdk/winsock.h
sdk/include/psdk/winsock2.h
sdk/include/xdk/winnt.template.h

- ### `Fix the automatic definition of __ROS_LONG64__`
It is not wishable anymore to automatically define __ROS_LONG64__
whenever __WINESRC__ is defined. Indeed, Wine now has started to
introduce the possibility to "Enable compilation with long types".
Thus, for these modules we import from them, we want to be able to
define __WINESRC__ without __ROS_LONG64__ automatically defined.
Addendum to commits 89c3520c86 (r73383) and 75eeb2a7e4 (r38872).
- ### `Add explicit missing __ROS_LONG64__ for Wine modules (fix build).`
When these get synced with more recent Wine version, you can remove
this define once you get past a "Enable compilation with long types"
Wine commit or similar.

[SDK][WINE] Fixes for __ROS_LONG64__ define

---

dll/win32/shell32/CMakeLists.txt
dll/win32/shell32/stubs.cpp
dll/win32/shell32/utils.cpp
modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHGetUserDisplayName.cpp
modules/rostests/apitests/shell32/testlist.c
sdk/include/psdk/secext.h
sdk/include/reactos/undocshell.h

Implemementing missing features...
- Add `netapi32` and `secur32` delay importing.
- Include some security headers in `utils.cpp`.
- Adapt `<secext.h>` to C++.
- Add prototype to `<undocshell.h>`.

[SHELL32][SHELL32_APITEST][SDK] Implement SHGetUserDisplayName

---

win32ss/gdi/ntgdi/gdiobj.c

_When the input parameter is NULL for GreGetObjectOwner do not output any message to the debug log._
Co-authored-by: Timo Kreuzer <timo.kreuzer@reactos.org>
JIRA issue: [CORE-19962](https://jira.reactos.org/browse/CORE-19962)
_Check if input parameter is NULL and if so, then do a quick return of GDI_OBJ_HMGR_RESTRICTED._

[NTGDI] Quiet debug log spam of GreGetObjectOwner if NULL input

---

base/services/wkssvc/rpcserver.c

Add minimal functionality for for level 1101 in NetrWkstaUserGetInfo to prevent netapi32_winetest:wksta from crashing (introduced in 45b008d).
Also plug some memory leaks, fix an error return and improve formatting.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=99585,99589,99592,99596

[WKSSVC] Stubplement support for level 1101 in NetrWkstaUserGetInfo

---

win32ss/gdi/ntgdi/freetype.c

Try to get ready to support raster fonts.
JIRA issue: [CORE-17327](https://jira.reactos.org/browse/CORE-17327)
- Fix the return value of `ftGdiGetTextMetricsW` function for raster fonts.
BEFORE (with enabling raster fonts):
No text displaying.
AFTER (with enabling raster fonts):
At least, it displays text.

[FREETYPE][NTGDI] Fix ftGdiGetTextMetricsW return for raster fonts

---

modules/rostests/apitests/browseui/SHExplorerParseCmdLine.c

Avoid hardcoding and fix tests.
- Remove hardcoded `"C:\\Windows\\system32"`, using `GetSystemDirectoryW` call in `SHExplorerParseCmdLine` testcase.

[BROWSEUI_APITEST] Don't hardcode C:\Windows

---

dll/win32/shlwapi/path.c
modules/rostests/winetests/shlwapi/path.c

Import fixes for PathUndecorate and PathRemoveBlanks from Wine.
Needed for PR #7633.
- ### `[SHLWAPI][WINESYNC] Import PathUndecorate wine fix + adaptation for ReactOS.`
```
shlwapi: Fix PathUndecorate[AW] implementation.
Signed-off-by: Jacek Caban <jacek@codeweavers.com>
Signed-off-by: Alexandre Julliard <julliard@winehq.org>
wine commit id f3c1d663a4a4a99b5c07000cb0ad9cc55d1e1c88 by Jacek Caban <jacek@codeweavers.com>
```
- ### `[SHLWAPI][WINESYNC] Import PathRemoveBlanks wine fix + adaptation for ReactOS.`
```
kernelbase: Always remove trailing spaces in PathRemoveBlanks.
Signed-off-by: Esme Povirk <esme@codeweavers.com>
Signed-off-by: Alexandre Julliard <julliard@winehq.org>
wine commit id 404cd8a92bd99332a7ef8ec96edbf5aeea8cab76 by Esme Povirk <esme@codeweavers.com>
```
- Test VBox: …

[SHLWAPI] Import Wine fixes for PathUndecorate and PathRemoveBlanks

---

dll/ntdll/def/ntdll.spec
dll/win32/browseui/CAutoComplete.cpp
dll/win32/iernonce/registry.cpp
modules/rosapps/applications/explorer-old/shell/fatfs.cpp
sdk/cmake/gcc.cmake
sdk/cmake/host-tools.cmake
sdk/cmake/msvc.cmake
sdk/include/crt/crtdbg.h
sdk/tools/CMakeLists.txt
sdk/tools/spec2def/spec2def.c

A few changes to improve the handling of Debug vs Release builds.
- [CMAKE] Fix definition of NDEBUG on MSVC release builds
- [CMAKE] Build host-tools as release by default
- [SPEC2DEF] Implement support for debug-only exports
Update:
Removed "[REACTOS] Globally define _DEBUG", because it still causes assertion failures. Needs more investigation.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=99848,99853,99856

[CMAKE][SPEC2DEF] Improve debug handling

---

dll/win32/shell32/CDefView.cpp

Hackfix for [CORE-19624](https://jira.reactos.org/browse/CORE-19624) and [CORE-19818](https://jira.reactos.org/browse/CORE-19818) until ListView is fixed.

[SHELL32] Temporarily disable LVS_EX_DOUBLEBUFFER in DefView

---

dll/win32/shell32/shell32.spec
dll/win32/shell32/stubs.cpp
dll/win32/shell32/utils.cpp
modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHGetUnreadMailCountW.cpp
modules/rostests/apitests/shell32/testlist.c
sdk/include/psdk/shellapi.h
sdk/include/reactos/undocshell.h

- Add `SHELL_ReadSingleUnreadMailCount` helper function.
- Add prototype to `<shellapi.h>`.

[SHELL32][SHELL32_APITEST][SDK] Implement SHGetUnreadMailCountW

---

boot/freeldr/freeldr/arch/realmode/amd64.S

Fix the crash with the new ext2/3 bootsector at PR (#7544)

[FREELDR] Fix wrong segment register at `lgdt` instruction in amd64.S

---

win32ss/gdi/ntgdi/freetype.c

Supporting raster fonts. Using `num_faces` is the generic way.
JIRA issue: [CORE-16165](https://jira.reactos.org/browse/CORE-16165)
- Use `FT_FaceRec.num_faces` instead of `TT_Face.ttc_header.count` in counting the font faces in `IntGdiLoadFontsFromMemory` function.

[FREETYPE][NTGDI] Use num_faces instead of ttc_header.count

---

base/shell/explorer/startctxmnu.cpp

Support Unicode on Start Button context menu for international text support.
- Support Unicode in `CStartMenuBtnCtxMenu::InvokeCommand` method by using `CMINVOKECOMMANDINFOEX` structure.

[EXPLORER] Support Unicode on Start Button InvokeCommand

---

base/shell/explorer/startctxmnu.cpp
base/shell/explorer/startmnusite.cpp
base/shell/explorer/syspager.cpp
base/shell/explorer/taskband.cpp
base/shell/explorer/taskswnd.cpp
base/shell/explorer/tbsite.cpp
base/shell/explorer/trayclock.cpp
base/shell/explorer/trayntfy.cpp
base/shell/explorer/traywnd.cpp

Follow the standard way.
- Use `STDMETHODIMP` and `override` keyword instead of `virtual HRESULT STDMETHODCALLTYPE`.
- Delete `CTaskBand::ProcessMessage` and `CTaskBand::ContainsWindow` methods. I think they are useless.

[EXPLORER] Use STDMETHODIMP and override

---

dll/win32/shell32/shlexec.cpp

_PR#7588 caused regressions in shell32:shlexec tests. This should fix the last one._
JIRA issue: [CORE-19964](https://jira.reactos.org/browse/CORE-19964)
_After the commit of PR's #7588 & #7633 there was still one regression in the shell32:shlexec regression test._
_The failure was in the processing of a path that contained a period (full stop) at the end._
_This adds processing to remove any trailing periods and fixes this last regression._
refs/pull/7643/merge on 0.4.16-dev-545-gb87c6b8
KVM:  https://reactos.org/testman/compare.php?ids=99904,99908,99912 LGTM
VBox: https://reactos.org/testman/compare.php?ids=99905,99909,99914 LGTM
shell32:shlexec is now back to 35 failures, which is the same as before the first PR commit
Plus, more total tests are now run at 1631 than …

[SHELL32] SHELL_FindExecutable: Fix last regression from PR#7588

---

sdk/include/psdk/ddraw.h

This warning appears quite a few times in the build log.
```
D:\a\reactos\reactos\src\sdk\include\psdk\ddraw.h(11): warning C4005: 'CO_E_NOTINITIALIZED': macro redefinition
D:\a\reactos\reactos\src\sdk\include\psdk\winerror.h(2803): note: see previous definition of 'CO_E_NOTINITIALIZED'
```
This fix is also a part of my larger [warning fix PR](https://github.com/reactos/reactos/pull/7031/) but it does not seem that like will ever get accepted so I cherry-picked this one since it bothers me when searching for "error" in the log.

[PSDK] Avoid CO_E_NOTINITIALIZED macro redefinition warning

---

drivers/storage/mountmgr/device.c
modules/rostests/apitests/mountmgr/CMakeLists.txt
modules/rostests/apitests/mountmgr/QueryDosVolumePaths.c
modules/rostests/apitests/mountmgr/QueryPoints.c
modules/rostests/apitests/mountmgr/precomp.h
modules/rostests/apitests/mountmgr/testlist.c
modules/rostests/apitests/mountmgr/utils.c
modules/rostests/kmtests/ntos_io/IoVolume.c
ntoskrnl/io/iomgr/volume.c

The VolumePath buffer returned by `IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH` contains one string stored as a multi-NUL-terminated string, whose total length is given by its `MultiSzLength` member.
The DosName UNICODE_STRING just returns the (single) string as a normal NUL-terminated string. So, we need to remove the two NUL-terminators from the `MultiSzLength` count to retrieve the correct length.
See commit 69e98d56715ade9d5f0ee350730cab9f9f8c3d93.
- Add tests for mountmgr handling of `IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH` and `IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATHS`.
- Add tests for `IoVolumeDeviceToDosName()` (which uses `IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH`).
- Various fixes for these modules.
- Test VBox: https://reactos.org/testman/compare.php?ids=99948,99960,99962,99964
- Test KVM: …

[MOUNTMGR][NTOS:IO] Several fixes for IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH and IoVolumeDeviceToDosName() + tests

---

sdk/lib/3rdparty/freetype/freetype.def
sdk/lib/3rdparty/freetype/include/freetype/ftbitmap.h
sdk/lib/3rdparty/freetype/src/base/ftbitmap.c
win32ss/drivers/font/ftfd/ftfd.spec
win32ss/gdi/ntgdi/freetype.c

Currently, our `FT_Bitmap_Convert` function has a hack to make the bitmap image compatible to ReactOS.
I think the hack on `FT_Bitmap_Convert` should be separated from our font engine.
JIRA issue: [CORE-16047](https://jira.reactos.org/browse/CORE-16047)
- Add `FT_Bitmap_Convert_ReactOS_Hack` function, that is based on `FT_Bitmap_Convert`, and split the hack of `FT_Bitmap_Convert`.
- Use `FT_Bitmap_Convert_ReactOS_Hack` in `IntGetBitmapGlyphWithCache` function instead of `FT_Bitmap_Convert`.
- Modify `ftfd.spec` to add `FT_Bitmap_Convert_ReactOS_Hack`.

[FREETYPE][FTFD][NTGDI] Split FT_Bitmap_Convert hack

---

win32ss/gdi/ntgdi/freetype.c

Simplify code logic and reduce management cost.
JIRA issue: [CORE-19973](https://jira.reactos.org/browse/CORE-19973)
- Add `IntGdiLoadFontByIndexFromMemory` helper function.
- Simplify `IntGdiLoadFontsFromMemory` function.

[FREETYPE][NTGDI] Simplify IntGdiLoadFontsFromMemory

---

dll/win32/urlmon/CMakeLists.txt
modules/rostests/winetests/mshtml/activex.c

Fix crash of mshtml_winetest activex and htmldoc
✅ KVM x86: https://reactos.org/testman/compare.php?ids=99938,99946,99949,99955
- mshtml:activex: crash fixed
- mshtml:htmldoc: crash fixed
- urlmon:misc: crash fixed
- urlmon:sec_mgr: 1 test fixed

[MSHTML_WINETEST] Fix crashes

---

sdk/include/asm/asm.inc

[ASM] Use macros instead of defines
Defines can cause problems, like previously with the end define, which caused a jump to label ".end" to be interpreted as a jump to ".", which is the current address, resulting in an infinite loop.
Remove obsolete CODESEG
Should fix tests

Try to fix regression

---

ntoskrnl/ke/amd64/cpu.c
ntoskrnl/ke/arm/cpu.c
ntoskrnl/ke/i386/cpu.c
ntoskrnl/ke/krnlinit.c
ntoskrnl/ke/processor.c
ntoskrnl/ntos.cmake

In Windows Vista and later, this routine can be called at any IRQL.

[NTOS:KE] Make KeQueryActiveProcessors portable and non-paged

---

dll/ntdll/ldr/ldrinit.c
ntoskrnl/mm/ARM3/procsup.c

[NTOS:MM] Fix process affinity in MmCreatePeb
[NTDLL] Demote UNIMPLEMENTED to DPRINT in LdrpValidateImageForMp to silence spam on SMP builds
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=99946,99949,99953

[NTOS] Fix PEB affinity [NTDLL] Silence LdrpValidateImageForMp

---

base/applications/rapps/gui.cpp
base/applications/rapps/include/misc.h
base/applications/rapps/loaddlg.cpp

Reuse active (non-modal) pending download window when another application is double-clicked instead of opening another (broken) download window.
[CORE-16716](https://jira.reactos.org/browse/CORE-16716) and [CORE-16804](https://jira.reactos.org/browse/CORE-16804)

[RAPPS] Reuse active pending downloads window

---

dll/ntdll/ldr/ldrinit.c

This is required to protect against a race with LdrShutdownThread, which can lead to all kinds of problems, including deadlocks.
Tests
✅ KVM x86: https://reactos.org/testman/compare.php?ids=100087,100102,100100

[NTDLL] Acquire LdrpLoaderLock in LdrpInitializeThread

---

dll/win32/shell32/stubs.cpp
dll/win32/shell32/utils.cpp
modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHIsBadInterfacePtr.cpp
modules/rostests/apitests/shell32/testlist.c
sdk/include/reactos/undocshell.h

- Move function definition from `stubs.cpp` to `utils.cpp`.
- Implement `SHIsBadInterfacePtr` function in `utils.cpp`.
- Add prototype to `<undocshell.h>`.

[SHELL32][SHELL32_APITEST][SDK] SHIsBadInterfacePtr

---

sdk/cmake/host-tools.cmake

This is to fix kmtests on Test WHS. Seemingly something is broken with release builds of host tools, at least on GCC x86.
Jita ticket: https://jira.reactos.org/browse/CORE-19981
Tests:
✅ KVM x86: https://reactos.org/testman/compare.php?ids=100121,100127

[CMAKE] Build host tools as Debug by default

---

dll/win32/uxtheme/CMakeLists.txt
dll/win32/uxtheme/errinfo.c
dll/win32/uxtheme/main.c
dll/win32/uxtheme/system.c
dll/win32/uxtheme/uxtheme.spec
dll/win32/uxtheme/uxthemep.h
modules/rostests/apitests/uxtheme/CMakeLists.txt
modules/rostests/apitests/uxtheme/GetThemeParseErrorInfo.c
modules/rostests/apitests/uxtheme/testlist.c
sdk/include/reactos/uxundoc.h

JIRA issue: [CORE-12805](https://jira.reactos.org/browse/CORE-12805)
- Add `dll/win32/uxtheme/errinfo.c`.
- Implement `GetThemeParseErrorInfo` function in `errinfo.c`.
- Modify `uxtheme.spec`.
- Add `GetThemeParseErrorInfo` prototype to `<uxundoc.h>`.
- Adapt `<uxundoc.h>` to C++.
- Add global variable `gdwErrorInfoTlsIndex`.
- Add `UXTHEME_UnInitSystem` function.

[UXTHEME][UXTHEME_APITEST][SDK] GetThemeParseErrorInfo

---

dll/win32/shell32/shell32.spec
dll/win32/shell32/stubs.cpp
dll/win32/shell32/utils.cpp
dll/win32/shell32/utils.h
modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/SHGetComputerDisplayNameW.cpp
modules/rostests/apitests/shell32/testlist.c
sdk/include/reactos/undocshell.h

- Move function definition from `stubs.cpp` to `utils.cpp`.
- Implement `SHGetComputerDisplayNameW` function.
- Add prototype to `<undocshell.h>`.

[SHELL32][SHELL32_APITEST][SDK] SHGetComputerDisplayNameW

---

modules/rostests/kmtests/CMakeLists.txt
modules/rostests/kmtests/include/kmt_test.h
modules/rostests/kmtests/kmtest/fltsupport.c
modules/rostests/kmtests/kmtest/kmtest.h
modules/rostests/kmtests/kmtest/testlist.c
modules/rostests/kmtests/kmtest_drv/testlist.c
modules/rostests/kmtests/ntos_kd/KdSystemDebugControl.c
modules/rostests/kmtests/ntos_kd/NtSystemDebugControl.c

These are kmtests for the KdSystemDebugControl and NtSystemDebugControl routines, used by WinDbg to implement local kernel debugging.
Their implementation is done in PR #7426.
Tested on Windows 2003 SP1+.
Partially tested (but not completely) on higher versions.
- Build GCC_x86 on Test KVM: https://reactos.org/testman/compare.php?ids=98839,98866
⚠️ [KdSystemDebugControl: 41 tests executed (0 marked as todo, 27 failures), 0 skipped.](https://reactos.org/testman/detail.php?id=77828356&prev=0)
⚠️ [NtSystemDebugControl: 42 tests executed (0 marked as todo, 3 failures), 1 skipped.](https://reactos.org/testman/detail.php?id=77828377&prev=0)
- Build MSVC_x64 on Test KVM_x64: https://reactos.org/testman/compare.php?ids=98850,98852
⚠️ [KdSystemDebugControl: 41 tests executed (0 marked as todo, 27 …

[KMTESTS] Add tests for KdSystemDebugControl and NtSystemDebugControl

---

ntoskrnl/ex/dbgctrl.c
ntoskrnl/ex/sysinfo.c
ntoskrnl/include/internal/ex.h
ntoskrnl/include/internal/kd64.h
ntoskrnl/kd64/amd64/kdx64.c
ntoskrnl/kd64/arm/kdarm.c
ntoskrnl/kd64/i386/kdx86.c
ntoskrnl/kd64/kdapi.c
ntoskrnl/kd64/kdtrap.c
ntoskrnl/mm/ARM3/mmdbg.c
sdk/include/ndk/kdfuncs.h
sdk/include/ndk/kdtypes.h

The KdSystemDebugControl and NtSystemDebugControl routines are used by WinDbg to implement local kernel debugging.
KMTests for these routines can be found in PR #7424.
The vast majority of the implementation has been done by @hpoussin .
The commits titles tell what the proposed changes are.

[NTOS:EX:KD64] Implement KdSystemDebugControl and NtSystemDebugControl

---

base/applications/rapps/geninst.cpp

Some applications are broken and assume the working directory is the same as the .exe directory (xrick etc).

[RAPPS] Set working directory for zip generated shortcuts

---

win32ss/user/ntuser/metric.c
win32ss/user/ntuser/sysparams.c
win32ss/user/ntuser/sysparams.h

Improve usability.
JIRA issue: [CORE-12905](https://jira.reactos.org/browse/CORE-12905)
- Add `nIconSize` and `nSmallIconSize` values to `SPIVALUES` structure.
- Load `"Shell Icon Size"` and `"Shell Small Icon Size"` values from registry.
- Enable changing of `SM_CXICON`, `SM_CYICON`, `SM_CXSMICON`, and `SM_CYSMICON` settings.
BEFORE:
AFTER:

[NTUSER] Load SM_CXICON etc. settings from registry

---

win32ss/user/ntuser/metric.c
win32ss/user/ntuser/sysparams.c
win32ss/user/ntuser/sysparams.h

Reverts reactos/reactos#7679 .
It seems like the shell icon size is not the system icon size.
The wide string `L"Shell Small Icon Size"` is detected in `shell32.dll` and `themeui.dll`.
No `L"Shell Small Icon Size"` in `win32k.sys` found.
JIRA issue: [CORE-12905](https://jira.reactos.org/browse/CORE-12905)

Revert "[NTUSER] Load SM_CXICON etc. settings from registry"

---

base/applications/rapps/include/appinfo.h
base/applications/rapps/loaddlg.cpp

http://example.com/setup.exe?foo=bar needs to use setup.exe as the filename so the type ends up as .exe. The code for this [used to exist](https://github.com/reactos/reactos/commit/1e01918302558828b91a697dc020224817d52877) but was lost at some point. Because xbgpack1.txt already relies on the query not being stripped, this PR introduces a new database entry instead to optionally override the downloaded filename.

[RAPPS] Allow database to override download filename

---

dll/win32/shell32/iconcache.cpp
dll/win32/shell32/wine/shell32_main.c
dll/win32/shell32/wine/shell32_main.h

Improve usability. Re-trial of #7679 with different approach.
JIRA issue: [CORE-12905](https://jira.reactos.org/browse/CORE-12905)
- Add `ShellSmallIconSize`, `ShellLargeIconSize`, and `ShellIconBPP` global variables in `iconcache.cpp`.
- Add `SIC_GetMetricsValue`, `SIC_GetLargeIconSize`, `SIC_GetSmallIconSize`, and `SIC_GetIconBPP` helper functions in `iconcache.cpp`.
- Load shell icon size from registry key `"HKEY_CURRENT_USER\\Control Panel\\Desktop\\WindowMetrics"`.
- Load icon BPP (bits per pixel) from registry.
- Fix `SIC_Initialize` and `SIC_LoadIcon` functions for icon size.
- Fix `SHGetFileInfoW` function for `SHGFI_SHELLICONSIZE` flag.
(With changing `"Shell Icon Size"` value and reboot)
BEFORE:
No change in display.
AFTER:
The Desktop icons are shrinked.

[SHELL32] Load shell icon size from registry

---

dll/win32/shell32/shlexec.cpp

This fixes the execution of `shell:::{645FF040-5081-101B-9F08-00AA002F954E}` in the Run dialog.
The desktop folder parses this string to the PIDL equivalent of `::{645FF040-5081-101B-9F08-00AA002F954E}` (a RegItem PIDL) and `CDefaultContextMenu::InvokePidl` will call back into `ShellExecute`. This PR allows `ShellExecute` to get back the string `::{645FF040-5081-101B-9F08-00AA002F954E}` from the PIDL and `explorer.exe ::{645FF040-5081-101B-9F08-00AA002F954E}` will end up doing the right thing.
JIRA issue: [CORE-16898](https://jira.reactos.org/browse/CORE-16898) (the shell:::{} part).

[SHELL32] SEE_MASK_IDLIST should not assume the PIDL is always a FS path

---

base/shell/explorer/precomp.h
base/shell/explorer/rshell.cpp
base/shell/rshell/misc.cpp
dll/win32/shdocvw/CMakeLists.txt
dll/win32/shdocvw/shdocvw.spec
dll/win32/shdocvw/shdocvw_main.c
dll/win32/shdocvw/winlist.cpp
sdk/include/reactos/shdocvw_undoc.h
sdk/include/reactos/undocshell.h

JIRA issue: [CORE-9368](https://jira.reactos.org/browse/CORE-9368)
- Modify `shdocvw.spec`.
- Add `dll/win32/shdocvw/winlist.cpp`.
- Add stubs of `WinList_*` functions.
- Add `WinList_*` function prototypes to `<shdocvw_undoc.h>`.
- Adapt `explorer` and `rshell` to new `WinList_Init` prototype.

[SHDOCVW][EXPLORER][RSHELL][SDK] Populate WinList_* stubs

---

dll/win32/shell32/shellmenu/CMenuBand.cpp
dll/win32/shell32/shlexec.cpp

Some verbs in the right-click menu of start menu entries starts processes with their window hidden because the show command is incorrectly set to SW_HIDE (0).

[SHELL32] CMenuBand must set ShowWindow value for InvokeCommand

---

ntoskrnl/ex/sysinfo.c
ntoskrnl/include/internal/i386/ke.h
ntoskrnl/include/internal/ke.h
ntoskrnl/ke/amd64/cpu.c
ntoskrnl/ke/amd64/krnlinit.c
ntoskrnl/ke/i386/cpu.c
ntoskrnl/ke/i386/kiinit.c
ntoskrnl/ke/krnlinit.c
sdk/include/ndk/amd64/ketypes.h
sdk/include/ndk/extypes.h
sdk/include/ndk/i386/ketypes.h

- Make KeFeatureBits 64 bits
- Detect more features
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=100025,100028,100029,100035

[NTOS] Make KeFeatureBits 64 bits and detect more features

---

modules/rostests/kmtests/ntos_io/IoDeviceInterface.c
ntoskrnl/io/iomgr/deviface.c

Implement `IoGetDeviceInterfaceAlias` function in PnP, and refactor and improve the test for this and other `IoDeviceInterface`* functions.
This allows to successfully boot ReactOS with audio stack replacement from Windows XP/Server 2003: drmk.sys, kmixer.sys, ks.sys, portcls.sys, swenum.sys, sysaudio.sys wdmaud.sys and wdmaud.drv (in particular, it's called by MS sysaudio.sys driver). However the sound still does not work with such a replacement yet (perhaps due to our setupapi etc.).
This is going to be a sum of my previous #3510 and #3595 PRs. Since no reply from @Extravert-ir in #5042 PR for a while, I decided to revive it myself. :slightly_smiling_face: 
JIRA issue: [CORE-17361](https://jira.reactos.org/browse/CORE-17361)
- Implement `IoGetDeviceInterfaceAlias`.
- Rewrite …

[NTOS:IO] Implement IoGetDeviceInterfaceAlias - Revised

---

sdk/lib/rtl/amd64/unwind.c

Check if the stack pointer is out of bounds, before trying to unwind a frame. This will not fix any crashes, but it prevents simple crashes from going into a recursive exception.

[RTL/x64] Fix a bug in RtlpUnwindInternal

---

modules/rostests/apitests/ntdll/RtlDosSearchPath_Ustr.c
sdk/lib/rtl/path.c

Fix buffer overflow in RtlDosSearchPath_Ustr.
The reason is write null behind buffer, if path length equal MAX_PATH (without null terminator).

[RTL][NTDLL_APITEST] Fix buffer overflow in RtlDosSearchPath_Ustr

---

modules/rostests/apitests/shdocvw/CMakeLists.txt
modules/rostests/apitests/shdocvw/WinList.cpp
modules/rostests/apitests/shdocvw/testlist.c

JIRA issue: [CORE-9368](https://jira.reactos.org/browse/CORE-9368)
- Add `WinList` testcase for `CLSID_ShellWindows` class and `shdocvw!WinList_*` functions.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Partially skipped.

[SHDOCVW_APITEST] Add WinList testcase

---

win32ss/include/ntuser.h
win32ss/user/ntuser/defwnd.c
win32ss/user/ntuser/simplecall.c
win32ss/user/ntuser/userfuncs.h
win32ss/user/ntuser/window.c
win32ss/user/user32/include/ntwrapper.h
win32ss/user/user32/windows/window.c

JIRA issue: [CORE-6920](https://jira.reactos.org/browse/CORE-6920)
- Make the return value of `NtUserCallHwnd` a `DWORD_PTR`.
- Add `DWP_GetEnabledPopup` helper function in `win32ss/user/ntuser/defwnd.c`.
- Add code to `NtUserCallHwnd` for `HWND_ROUTINE_DWP_GETENABLEDPOPUP`.
- Add code to `GetWindow` for `GW_ENABLEDPOPUP`.
- Set last error in `GetWindow` and `IntGetWindow`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
8 failures.
2 failures. Maybe Z-order problem?

[NTUSER][USER32] Support GetWindow.GW_ENABLEDPOPUP

---

base/applications/winver/CMakeLists.txt
base/applications/winver/lang/en-US.rc
base/applications/winver/osinfo.c
base/applications/winver/resource.h
base/applications/winver/winver.c
base/applications/winver/winver.rc
base/applications/winver/winver_p.h

Improve the `winver` utility.
- Display the NT compatibility information. This is useful when the version display on desktop is turned off.
- Don't hardcode the OS name. This make it compatible with Windows.
ReactOS:
Win7:
ReactOS (`ProductName` changed via registry):

[WINVER] Display compatibility information

---

modules/rostests/winetests/riched20/editor.c
modules/rostests/winetests/riched20/richole.c
modules/rostests/winetests/riched20/txtsrv.c
sdk/include/psdk/textserv.h

_Sync riched20_winetest to Wine-6.10._
JIRA issue: [ROSTESTS-398](https://jira.reactos.org/browse/ROSTESTS-398) and [CORE-6727](https://jira.reactos.org/browse/CORE-6727)
_Tests for PR #7611._
_This should be committed before PR #7611._
refs/pull/7692/merge on 0.4.16-dev-688-gee19792
VBox: https://reactos.org/testman/compare.php?ids=100430,100433 LGTM
KVM:  https://reactos.org/testman/compare.php?ids=100429,100434 LGTM
WHS:  https://reactos.org/testman/compare.php?ids=100407,100432 LGTM
For test riched20:editor there are five (5) more fails.
These are due to these tests being "todo_wine" (not counted as fails) and they are no longer designated this way.

[RICHED20_WINETEST] Sync to Wine-6.10. Commit before PR #7611.

---

dll/win32/shell32/CShellLink.cpp

JIRA issue: [CORE-19987](https://jira.reactos.org/browse/CORE-19987)
Handles the case where SEE_MASK_DOENVSUBST will expand it later inside ShellExeute.

[SHELL32] Expand .lnk working directory string before checking if it's valid

---

dll/win32/shimgvw/CMakeLists.txt
dll/win32/shimgvw/loader.cpp
dll/win32/shimgvw/shimgvw.c
dll/win32/shimgvw/shimgvw.h
dll/win32/shimgvw/util.c
sdk/include/reactos/shellutils.h

JIRA issue: [CORE-13340](https://jira.reactos.org/browse/CORE-13340)
Notes:
- The context menu is not available in fullscreen mode.
- Also fixes an unrelated bug where exiting fullscreen with the mouse would not reset the zoom but F11 would.

[SHIMGVW] Display shell context menu for the image on right-click

---

dll/cpl/appwiz/createlink.c

Windows does not set the comment when creating a new shortcut in the wizard and neither should we because we have no useful information to put there.

[APPWIZ] Don't set the .lnk filename as the shortcut comment

---

dll/win32/shell32/COpenWithMenu.cpp
dll/win32/shell32/dialogs/filedefext.cpp
dll/win32/shell32/precomp.h

JIRA issue: [CORE-16980](https://jira.reactos.org/browse/CORE-16980)
Notes:
- I made the rundll32 function a "public" `SHELL32_...` function because `ASSOCF_REMAPRUNDLL` is going to need it later.

[SHELL32] OpenWith should use dll path instead when the command starts with rundll32

---

sdk/lib/ucrt/math/_dclass.c
sdk/lib/ucrt/math/_dtest.c
sdk/lib/ucrt/math/_fdclass.c
sdk/lib/ucrt/math/_fdtest.c
sdk/lib/ucrt/stdlib/div.cpp
sdk/lib/ucrt/stdlib/ldiv.cpp
sdk/lib/ucrt/stdlib/lldiv.cpp

CORE-19996
_Fix MSVC compiling on VS 2017 after recent UCRT commits._
JIRA issue: [CORE-19996](https://jira.reactos.org/browse/CORE-19996)
_Change condition of using '#pragma function..' to only use this on VS 2019 or later._
Based on Serge's comment and Timo's suggestion I tested this on https://godbolt.org/ .
It indicates that the test should use 1922 instead of 1920, so I am changing the PR now to reflect this.

[UCRT] Fix MSVC compiling on VS 2017 after Timo's UCRT commits

---

dll/win32/gdiplus/image.c

Windows returns the icon GUID in `GdipGetImageRawFormat`. Wine still incorrectly returns bitmap in their master.

[GDIPLUS] Identify .ico codec format as ImageFormatIcon

---

dll/win32/comctl32/listview.c

This is mostly for DefView (a files hidden attribute does not depend on window focus) but the fix belongs in ListView.
Undoes flicker caused by PR #4218. Does not cause regression for [CORE-16722](https://jira.reactos.org/browse/CORE-16722) as far as I can tell.
<details><summary>Code example</summary>
<pre><code>InitCommonControls();
SHFILEINFOA shfi;
INT_PTR shil = SHGetFileInfoA("x", FILE_ATTRIBUTE_DIRECTORY, &shfi, sizeof(shfi), SHGFI_USEFILEATTRIBUTES | SHGFI_SYSICONINDEX | SHGFI_SHELLICONSIZE | SHGFI_SMALLICON);
HWND hList = CreateWindowEx(WS_EX_APPWINDOW, WC_LISTVIEW, 0, WS_VISIBLE | WS_OVERLAPPEDWINDOW | LVS_SMALLICON | LVS_ALIGNLEFT | LVS_NOLABELWRAP | LVS_SHOWSELALWAYS, 0, 0, 150, 150, 0, 0, 0, 0);
ListView_SetImageList(hList, (HIMAGELIST)shil, LVSIL_SMALL);
UINT states[] = { …

[COMCTL32] ListView LVIS_CUT image does not depend on focus

---

dll/cpl/desk/background.c

Icons rarely makes good wallpapers and GDI+ does not pick the best image automatically. Implementing the same workaround shimgvw uses is overkill.
JIRA issue: [CORE-20003](https://jira.reactos.org/browse/CORE-20003)

[DESK] Don't include .ico files in the list of wallpapers

---

dll/win32/shell32/COpenWithMenu.cpp
dll/win32/shell32/folders/CRecycleBin.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shellrecyclebin/recyclebin.c
dll/win32/shell32/shellrecyclebin/recyclebin.h
dll/win32/shell32/shellrecyclebin/recyclebin_v5.cpp
dll/win32/shell32/shellrecyclebin/recyclebin_v5.h
dll/win32/shell32/shellrecyclebin/recyclebin_v5_enumerator.cpp
dll/win32/shell32/shlfileop.cpp
dll/win32/shell32/utils.h

JIRA issue: [CORE-19895](https://jira.reactos.org/browse/CORE-19895) (and semi-dupe 19231)
To get a single progress dialog for multiple files, the entire delete/restore operation had to move its calls to `SHFileOperation` from the low-level code to the `IShellFolder` implementation. A callback for each file is used to update the recycle database. This new callback code is inspired by `IFileOperationProgressSink` that was added in Vista and would still be applicable once `IFileOperation` gets implemented.

[SHELL32] Handle multiple files in recycle bin delete/restore operations

---

modules/rostests/apitests/comctl32/imagelist.c
modules/rostests/apitests/comctl32/testlist.c

The test name was conflicting with an existing winetest, which breaks testman.
When adding new tests or modifying existing ones, please always run them on buildbot before merging!

[COMCTL32_APITEST] Rename a test

---

dll/shellext/netshell/shfldr_netconnect.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefViewBckgrndMenu.cpp
dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/CNewMenu.cpp
dll/win32/shell32/droptargets/CFSDropTarget.cpp
dll/win32/shell32/folders/CRecycleBin.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shelldesktop/CDirectoryWatcher.cpp
dll/win32/shell32/utils.h
sdk/include/psdk/shobjidl.idl
sdk/include/reactos/shlguid_undoc.h

- When Ctrl+X is pressed on a selected item, it will appear ghosted until another clipboard action takes place.
- Generate `SHCNE_UPDATE*` notifications when file attributes change.
- When an items hidden attribute is changed (filesystem notification), we must update the ghosted state.
[CORE-9465](https://jira.reactos.org/browse/CORE-9465)

[SHELL32] Display cut items as ghosted

---

base/applications/dxdiag/lang/ro-RO.rc

This file was not translated in Romanian language in any Win version (neither XP/2k3+, nor in the previous ones). I tried to translate this file as close as possible in the way I did in the previous PRs.

[DXDIAG] Update Romanian (ro-RO) translation

---

drivers/storage/ide/uniata/scsi.h

Fix memory corruption if processed SCSIOP_SERVICE_ACTION16.
Reason: 
in uniata driver sizeof(READ_CAPACITY16_DATA) == 33
in reactos sdk sizeof(READ_CAPACITY16_DATA) == 32.
JIRA issue: [CORE-19696](https://jira.reactos.org/browse/CORE-19696)
After fix:

[UNIATA] Fix memory corruption if SCSIOP_SERVICE_ACTION16 processed.

---

ntoskrnl/include/internal/mm.h
ntoskrnl/mm/ARM3/sysldr.c
ntoskrnl/ps/psmgr.c

- [NTOS:PS] `STATUS_INVALID_IMAGE_PROTECT` returned by `MmCheckSystemImage` should be a fatal error too.
- [NTOS:PS] Fix object attributes for opening Ntdll.
- [NTOS:MM] Remove `MmCheckSystemImage` unused parameter.
- [NTOS:MM] Inline `MmVerifyImageIsOkForMpUse` to `MmCheckSystemImage` and reduce a calling to `RtlImageNtHeader`.
From the closed PR #6963

[NTOS:MM][NTOS:PS] Little fixes for NTDLL loading

---

ntoskrnl/mm/freelist.c

Fixes crash when the caller passes HighAddress below MmHighestPhysicalAddress.
Observed with nvidia miniport driver.
JIRA issue: [CORE-20008](https://jira.reactos.org/browse/CORE-20008)
[CORE-19348](https://jira.reactos.org/browse/CORE-19348)
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=100749,100751,100753,100757
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=100750,100752,100754,100756

[NTOS:MM] Fix broken ASSERT

---

dll/ntdll/def/ntdll.spec

Mostly based on Windows 11 22H2 and Vista SP2 and WINE-10.0
This is a revised version of a commit made by @archeYR when we were trying to get browsers and a few apps to work back
in july of 2023.
I've modified it based on some stuff from WINE-10.0. 
(No logic changes so ill just run it on one and one)

[NTDLL] Fix Vista+ stubs (Add Parameters)

---

win32ss/user/user32/misc/exticon.c

This bug breaks the documented `S_FALSE` return value for `SHDefExtractIconW` when the icon is not found.

[USER32] PrivateExtractIcons must return 0 for empty files

---

dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/browseui/shellfind/CFindFolder.h
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CShellLink.cpp

- Shortcut icons require the correct IShellFolder because it needs the full path (`CFSFolder::_CreateShellExtInstance` calls `PathCombineW` with its own path).
- Items in a drive root needs the final backslash to be a valid path (also matches Windows parent path display).
[CORE-18692](https://jira.reactos.org/browse/CORE-18692)
Notes:
- The whole CFindFolder implementation needs to move to shell32 to completely fix multi-selection context menus when the items are in different parent folders.

[BROWSEUI][SHELL32] Fix FindFolder icons

---

base/applications/mscutils/eventvwr/eventvwr.c
base/applications/mscutils/eventvwr/evtdetctl.c
base/applications/mscutils/eventvwr/evtdetctl.h
base/applications/mscutils/eventvwr/lang/bg-BG.rc
base/applications/mscutils/eventvwr/lang/cs-CZ.rc
base/applications/mscutils/eventvwr/lang/de-DE.rc
base/applications/mscutils/eventvwr/lang/el-GR.rc
base/applications/mscutils/eventvwr/lang/en-US.rc
base/applications/mscutils/eventvwr/lang/es-ES.rc
base/applications/mscutils/eventvwr/lang/fr-FR.rc
base/applications/mscutils/eventvwr/lang/he-IL.rc
base/applications/mscutils/eventvwr/lang/it-IT.rc
base/applications/mscutils/eventvwr/lang/ja-JP.rc
base/applications/mscutils/eventvwr/lang/ko-KR.rc
base/applications/mscutils/eventvwr/lang/no-NO.rc
base/applications/mscutils/eventvwr/lang/pl-PL.rc
base/applications/mscutils/eventvwr/lang/pt-BR.rc
base/applications/mscutils/eventvwr/lang/pt-PT.rc
base/applications/mscutils/eventvwr/lang/ro-RO.rc
base/applications/mscutils/eventvwr/lang/ru-RU.rc
base/applications/mscutils/eventvwr/lang/sk-SK.rc
base/applications/mscutils/eventvwr/lang/sq-AL.rc
base/applications/mscutils/eventvwr/lang/sv-SE.rc
base/applications/mscutils/eventvwr/lang/tr-TR.rc
base/applications/mscutils/eventvwr/lang/uk-UA.rc
base/applications/mscutils/eventvwr/lang/zh-CN.rc
base/applications/mscutils/eventvwr/lang/zh-HK.rc
base/applications/mscutils/eventvwr/lang/zh-TW.rc
base/applications/mscutils/eventvwr/resource.h

Don’t display garbage to the users.
JIRA issue: [CORE-19786](https://jira.reactos.org/browse/CORE-19786)
- Localize message text by using newly added `IDS_CONTFROMBEGINNING` and `IDS_CONTFROMEND` resource strings.
- Check item count before showing next/previous item.
- Add `EnableEventDetailsButtons` function.
BEFORE:
Garbage is displayed.
AFTER:
Buttons are disabled.

[EVENTVWR] Localize and check item count

---

media/doc/WINESYNC.txt
win32ss/user/user32/CMakeLists.txt
win32ss/user/user32/user32.spec
win32ss/user/user32_vista/CMakeLists.txt
win32ss/user/user32_vista/dpi.c
win32ss/user/user32_vista/wine/input.c
win32ss/user/user32_vista/wine/misc.c
win32ss/user/user32_vista/wine/sysparams.c
win32ss/user/user32_vista/wine/win.c

Looking at this PR you might wondering why i did half the things i did in this PR but let me explain.
DPI.c stubs? Why not Import WINE?
A conversation was had during the user32_vista PR where it was discussed we can't really use WINEs implementation. However we need this exports to import other dlls
DisplayConfigGetDeviceInfo,DisplayConfigSetDeviceInfo etc, 
These APIs come from WDDM, it's using the VidPn subsystem of DxgKrnl I have implementations of these APIs and we need to do some extra stuff over WINE.
Finally, Why user32?
Well I'd like to keep these files synced so when WINE implements them we can adopt it. we can move it at a later date but these APIS are needed for some new WINESYNCs.
This adds a bunch of Vista+ and even 10+ exports.

[USER32_VISTA][USER32] Import some wine-10.0 files and make some new stubs.

---

dll/win32/kernel32/CMakeLists.txt
dll/win32/kernel32/kernel32.spec
dll/win32/psapi/CMakeLists.txt
dll/win32/psapi/main.c
dll/win32/psapi/psapi.c

This behavior is straight out of win7 where this logic was moved to KernelBase and friends. Required for thousands of apps. But also just preps for the KernelBase sync from Wine-10

[PSAPI][KERNEL32] Convert the PSAPI exports to a static library

---

dll/win32/shell32/iconcache.cpp
modules/rostests/apitests/shell32/ExtractIconEx.cpp
modules/rostests/apitests/shell32/testlist.c

The documentation says "Pass 0 to specify default large and small sizes".
Notes:
- The new `GIL_SIMULATEDOC` test fails on ROS because that feature is not implemented yet.

[SHELL32][SHELL32_APITESTS] SHDefExtractIcon zero icon size as sysmetric

---

dll/win32/comctl32/listview.c

Fixes the behavior when selecting multiple files in a folder with the Shift key, while using either the Large Icons or Small Icons view, so that it is consistent with how it works on Windows.
JIRA issue: [CORE-10386](https://jira.reactos.org/browse/CORE-10386)
- Disable the specialized code for these views in LISTVIEW_SetGroupSelection, using the same code as for the list and details views, which also works fine for them.
Before:
After:

[COMCTL32] Fix shift-selecting files not working as expected in small/large icons views

---

win32ss/user/ntuser/winpos.c

Patch by I_Kill_Bugs for CORE-18799, CORE-18206, and CORE-19371.
I have changed the original logic to be better recommendation from I_Kill_Bugs.
_Adjust update region size if it is larger than current window to smaller size._
JIRA issue: [CORE-18206](https://jira.reactos.org/browse/CORE-18206)
[CORE-18799](https://jira.reactos.org/browse/CORE-18799)
[CORE-19371](https://jira.reactos.org/browse/CORE-19371)
_If Window->hrgnUpdate is not NULL, combine with VisAfter using RGN_AND before invalidating._
_Add explanatory message stating the reason for the changes._

[NTUSER] Handle window update region larger than the current window in clip region

---

ntoskrnl/ke/i386/v86vdm.c

In order for 0.4.15 to continue its release process we should probably get this in. 
Continued from PR #6070
JIRA issue: [CORE-19049](https://jira.reactos.org/browse/CORE-19049)

[NTOS:KE] Implement KeI386VirtualIntExtensions code paths for INT and IRET

---

base/shell/explorer/traywnd.cpp
dll/cpl/desk/theme.c
dll/win32/comctl32/listview.c
dll/win32/shell32/CDefView.cpp

Enable desktop icon title font setting.
JIRA issue: [CORE-13601](https://jira.reactos.org/browse/CORE-13601)
- Forward `WM_SETTINGCHANGE` message up to ListView.
- ListView accepts `WM_SETTINGCHANGE` message.
- Enable icon spacing.
BEFORE:
Desktop icon title font was not changed. Icon spacing not working.
AFTER (1):
Desktop icon title font is changed.
AFTER (2):
Icon spacing is working.

[EXPLORER][COMCTL32][SHELL32] Enable SPI_SETICONTITLELOGFONT

---

.gitattributes

Ensure that .sh script files should (or must...) always use LF (Unix) line endings.
This is what's expected by e.g. Cygwin (ba)sh on Windows. I don't know whether there exists ports of the GNU utils (and shell) that would _NOT_ support LF-only files, though...

[GIT] .sh script files should (or must...) always use LF (Unix) line endings

---

configure.cmd
configure.sh

Display the platform/operating system on which the build configuration takes place.
This information may be useful in some scenarii. For example, see:
https://chat.reactos.org/reactos/pl/wee3sy6ye7g4txynn14s1mo77e
- On Windows, use the `ver` command, embedded in a parsing `for` command to strip the extra leading newline emitted.
Example output:
```
Detected Visual Studio Environment VS16-i386
Configuring a new ReactOS build on:
Microsoft Windows [version 6.1.7601]
Preparing reactos...
```
- On Unix, use `uname -srvpio`
Example output:
```
Configuring a new ReactOS build on:
CYGWIN_NT-6.1-7601-WOW64 3.3.6-341.i686 2022-09-05 11:11 UTC unknown unknown Cygwin
Preparing reactos...
```

[CONFIGURE] Display the platform/operating system on which the build configuration takes place

---

base/applications/network/ping/ping.c

The ping utility found in various versions of Windows fills the optional data field in the ICMP echo request structure with ASCII characters from 'a' to 'w' wrapping back around until SendBuffer is full.  The purpose of this patch is to implement that behavior. Right now the optional data is filled by using the ZeroMemory functon on the SendBuffer variable.
Change SendBuffer to PUCHAR. Add a loop that populates SendBuffer in the function static void Ping(void) as described above.

[PING] Update SendBuffer fill method

---

boot/bootdata/bootcd/unattend.inf
dll/win32/syssetup/install.c
dll/win32/syssetup/wizard.c

Apply theming specified in unattend files very early on when booting the LiveCD or a new install.
_For testing:_ Add a "demo" for testing purposes (won't be included in the final PR).
https://github.com/user-attachments/assets/21983104-47d0-4f55-a216-2c1915f53257
On Windows, neither `shell32.dll!Control_RunDLL` nor `desk.cpl` attempt to expand any environment strings in the _**parameters**_ given to the CPL file (anything that follows "desk.cpl" in the `rundll32.exe shell32.dll,Control_RunDLL desk.cpl,,2 /Action:OpenTheme /file:"%SYSTEMROOT%\Resources\themes\Luna.theme"` , for example). The desk.cpl then shows an error. This means that it's the _caller_ who has to expand the path before sending it as a parameter via `Control_RunDLL` to desk.cpl.
Use a `[Shell]` section with …

[SYSSETUP] Apply theming specified in unattend files very early on when booting the LiveCD or a new install

---

boot/freeldr/bootsect/ext.S
boot/freeldr/bootsect/extldr.S

I'm sorry if i didn't noticed that before

[BOOTSECT][FREELDR] Fix wrong comment of conditional jump on `ext.S` and `extldr.S`

---

dll/cpl/sysdm/advanced.c
dll/ntdll/rtl/version.c
dll/win32/shlwapi/ordinal.c
modules/rostests/apitests/ntdll/RtlGetNtProductType.c

When choosing to install ROS as a server (the default), the ReportAsWorkstation checkbox in sysdm.cpl works correctly. If you instead choose to install ROS as a workstation, the product type is set to WinNT and the checkbox in sysdm.cpl does nothing.
This PR allows "ROS as a workstation" installs to report itself as a basic server to Win32 applications when the user toggles the sysdm.cpl checkbox (to unchecked in this case).
Notes:
- I'm now caching the ReportAsWorkstation value (per-process) instead of looking it up every time `[Rtl]GetVersion[Ex]` is called.
- ReportAsWorkstation now also overrides `RtlGetNtProductType` .

[NTDLL][SHLWAPI][SYSDM] ReportAsWorkstation should always override the product type

---

base/applications/rapps/geninst.cpp
base/applications/rapps/include/misc.h
base/applications/rapps/misc.cpp
base/applications/rapps/settingsdlg.cpp

If the download directory does not exist (Run RAPPS and go to settings without ever downloading anything), creating the directory exits the dialog prematurely without applying the settings.

[RAPPS] Must apply settings changes when a new download folder is created

---

dll/win32/shell32/dialogs/drvdefext.cpp
dll/win32/shell32/dialogs/drvdefext.h
dll/win32/shell32/dialogs/item_prop.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shldataobject.cpp
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/stubs.cpp
dll/win32/shell32/utils.h

- Adds support for multiple drives in a single property sheet
- Fixes crash in SHELL_CloneDataObject when the HIDA contains multiple PIDLs [CORE-20025](https://jira.reactos.org/browse/CORE-20025)

[SHELL32] Multiple drives property sheet support

---

base/applications/rapps/geninst.cpp
base/applications/rapps/include/misc.h
base/applications/rapps/loaddlg.cpp
base/applications/rapps/misc.cpp
base/applications/rapps/winmain.cpp

The "Delete the program installer after installation" setting (off by default) does not work well with compressed files, they are just deleted before the user can extract the files (there is a race between `ShellExecute` and `DeleteFile` here if Explorer is the default app for .zip/.cab). With this PR it will now leave compressed files alone if they open with Explorer. This is a compromise between respecting the users settings and actually being usable.

[RAPPS] Don't delete downloaded ZIP/CAB even if configured to

---

win32ss/gdi/ntgdi/freetype.c

Based on @Doug-Lyons's `wordpad-ruler-fix-05.patch`.
JIRA issue: [CORE-19870](https://jira.reactos.org/browse/CORE-19870)
- In `IntRequestFontSize` function, if `lfWidth < 10`, then `req.width = 0;`.
BEFORE:
AFTER:

[FREETYPE] Fix WordPad ruler rendering

---

dll/win32/shdocvw/CExplorerBand.cpp
dll/win32/shdocvw/CFavBand.cpp
dll/win32/shdocvw/CNSCBand.cpp
dll/win32/shdocvw/CNSCBand.h
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/folders/CDesktopFolder.h
dll/win32/shell32/folders/CRegFolder.cpp
dll/win32/shell32/shell32.spec
dll/win32/shell32/shfldr.h
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/wine/pidl.c

The rename to empty trick now works in the tree view. It does not work in DefView yet because of a bug in the ListView control.
JIRA issue: [CORE-18839](https://jira.reactos.org/browse/CORE-18839)
Notes:
- Regarding the use of `IsIllegalFsFileName` in `CRegFolder::SetNameOf`. RegItems are technically able to have any name but allowing strange things might cause problems during parsing in CDesktopFolder (I did not test) and Windows itself limits the characters it allows.

[SHDOCVW][SHELL32] Rename RegItem to empty name must reset the name to the default

---

boot/freeldr/freeldr/lib/fs/iso.c

Cache the PVD and directory information for ISO volumes to improve performance.
|                    | BEFORE        | AFTER |
| -------------      |:-------------:| -----:|
| Disk read calls    | 916           | 748   |
| Total sectors read | 8829          | 8079  |

[FREELDR] Improve performance of the ISO filesystem library

---

dll/win32/shell32/wine/shellpath.c
modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/PathMakeUniqueName.cpp
modules/rostests/apitests/shell32/testlist.c
sdk/include/psdk/shlobj.h

Sideproduct of #7804. Implementing missing features.
- Implement `PathMakeUniqueName` function.
- Add `PathMakeUniqueName` prototype to `<shlobj.h>`.
- Add `PathMakeUniqueName` testcase to `shell32_apitest`.
WinXP:
Successful.
Win2k3:
Successful.
Win10:
Successful.
Successful.

[SHELL32][SHELL32_APITEST][SDK] Implement PathMakeUniqueName

---

dll/win32/setupapi/query.c
dll/win32/setupapi/setupapi.spec

Sync `SetupQueryInfVersionInformation` stubs to Wine.
- Stub implement `SetupQueryInfVersionInformation`
---
The new synced stubs set `ERROR_CALL_NOT_IMPLEMENTED` as last error and return, rather than raise exception `EXCEPTION_WINE_STUB (0x80000100)`, then the Virtual Box Guest Addition 7.1.6 setup progress can move on.
Before this PR (PR #7746 goes first), setup raises 0x80000100:
After this PR, setup still gets stuck because of another problem (relates to `SetupInstallServicesFromInfSectionExW`), I'll fix that in a separate PR (#7770).

[SETUPAPI] Stub implement `SetupQueryInfVersionInformation`

---

dll/win32/comctl32/listbox.c

@I_Kill_Bugs patch
_Fix ReactOS second stage listbox selection highlight failure._
JIRA issue: [CORE-19814](https://jira.reactos.org/browse/CORE-19814)
_Check for LBS_NOSEL flag for 'descr->style' in 'LISTBOX_PaintItem' and if FALSE, only then set 'selected'._

[COMCTL32] ReactOS second stage listbox selection fix

---

dll/win32/newdev/newdev.c

Match Hardware ID correctly. This fix is required to install the latest (7.1.6) Virtual Box Guest Additions drivers.
- Add [Compatible IDs](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/compatible-ids) match, call `SetupDiGetDeviceRegistryPropertyW` twice, once for `SPDRP_HARDWAREID` and once for `SPDRP_COMPATIBLEIDS`.
- Use case-insensitive comparison (`wcscmp` -> `_wcsicmp`)
- Convert code file to UTF-8 encoding (for the character `é` in file head)
After #7746 , #7769 , #7770 , the installer installs driver VBoxGuest incorrectly, because `UpdateDriverForPlugAndPlayDevicesW` failed with `ERROR_NO_SUCH_DEVINST`. In fact, the device is present, the installer and this function work fine in Win2K3.
According to:
[Microsoft Learning - Compatible …

[NEWDEV] Fix `HardwareId` match logic in `UpdateDriverForPlugAndPlayDevicesW`

---

dll/win32/shell32/wine/shellpath.c

Follow-up of #7805.
- Simplify `formatString` handling.
- Move `pchDotExt` declaration.
- Define `MSDOS_8DOT3_FILENAME_TITLE_LEN` macro and use it.
- Commonize some code.

[SHELL32] Follow-up of #7805: Improve PathMakeUniqueName

---

base/applications/cmdutils/certutil/CMakeLists.txt
base/applications/cmdutils/certutil/asn.cpp
base/applications/cmdutils/certutil/certutil.cpp
base/applications/cmdutils/certutil/hashfile.cpp
base/applications/cmdutils/certutil/precomp.h

Output format based on Windows' version,
but it is not a 1:1 match.
TODO:
Adds output like:
```
0000: 30 82 01 bf                                       ; SEQUENCE (1bf Bytes)
0004:    30 82 01 6d                                    ; SEQUENCE (16d Bytes)
0008:    |  a0 03                                       ; OPTIONAL[0] (3 Bytes)
000a:    |  |  02 01                                    ; INTEGER (1 Bytes)
000c:    |  |     02 
000d:    |  02 10                                       ; INTEGER (10 Bytes)
000f:    |  |  86 bb af 93 85 c2 8c 87 4d f1 01 d9 47 99 0d a9 
001f:    |  30 09                                       ; SEQUENCE (9 Bytes)
0021:    |  |  06 05                                    ; OBJECT_ID (5 Bytes)
0023:    |  |  |  2b 0e 03 02 1d 
|  |  |     ; 1.3.14.3.2.29 sha1RSA …
```

[CERTUTIL] Add -asn verb

---

boot/freeldr/freeldr/options.c

And reduce code bloat.
Split off of #4042.

[FREELDR] DisplayBootTimeOptions(): Simplify concatenation checks

---

modules/rostests/apitests/ntdll/CMakeLists.txt
modules/rostests/apitests/ntdll/NtCreateProfile.c
modules/rostests/apitests/ntdll/NtStartProfile.c
modules/rostests/apitests/ntdll/testlist.c
ntoskrnl/ex/profile.c

This fixes NtCreateProfile `BufferSize` validation (see https://www.geoffchappell.com/studies/windows/km/ntoskrnl/api/ex/profile/bugdemo.htm for the bug description).
It also adds parameter validation tests for NtCreateProfile, and a basic test for a complete profile.
JIRA issue: [CORE-17907](https://jira.reactos.org/browse/CORE-17907)

[NTOS:EX] Fix BufferSize parameter validation in NtCreateProfile.

---

dll/win32/shdocvw/CNSCBand.cpp
dll/win32/shdocvw/CNSCBand.h
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/dialogs/drvdefext.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.h

- Support renaming to empty volume name ([CORE-17292](https://jira.reactos.org/browse/CORE-17292)).
- Use SHGDN_FOREDITING in Explorer tree and DefView ("Volname" instead of "VolName (C:)").
- Added support for the ShowDriveLettersFirst setting.
Notes:
- Renaming to empty does not work in DefView because of a ListView bug (already fixed in Wine).

[SHELL32][SHDOCVW] Fix drive volume renaming

---

modules/rostests/apitests/shell32/CMakeLists.txt
modules/rostests/apitests/shell32/PathProcessCommand.cpp
modules/rostests/apitests/shell32/testlist.c

Implementing `shell32!PathProcessCommand` function.
JIRA issue: [CORE-17659](https://jira.reactos.org/browse/CORE-17659)
WinXP:
Successful.
Win2k3:
Successful.
Win10 x64:
Skipped.
ReactOS:
`PathProcessCommand` is not implemented yet.

[SHELL32_APITEST] Add PathProcessCommand testcase

---

dll/win32/browseui/addresseditbox.cpp
dll/win32/browseui/addresseditbox.h
sdk/include/reactos/shlobj_undoc.h

JIRA issue: [CORE-19704](https://jira.reactos.org/browse/CORE-19704)
- Rename and retype `pidlLastParsed` as `CComHeapPtr<ITEMIDLIST_ABSOLUTE> m_pidlLastParsed`.
- Implement `CAddressEditBox::SetCurrentDir` method.
- Simplify `CAddressEditBox::ParseNow` method.
- Modify `IAddressEditBox` interface.

[BROWSEUI][SDK] Implement IAddressEditBox::SetCurrentDir

---

dll/ntdll/ldr/ldrinit.c
dll/ntdll/ldr/verifier.c
dll/win32/verifier/verifier.c
modules/rostests/apitests/rtl/ldrstubs.c
ntoskrnl/rtl/misc.c
sdk/include/reactos/verifier.h
sdk/lib/rtl/critical.c
sdk/lib/rtl/heappage.c

avrf progress,
adding some noisy stubs instead of nullptr's.
This allows running avrf 4.0.665.0
Not everything works yet, and we need a workaround for wine's hacked critical sections.
https://testbot.winehq.org/JobDetails.pl?Key=69391

Avrf progress

---

dll/win32/comctl32/edit.c

JIRA issue: [CORE-19743](https://jira.reactos.org/browse/CORE-19743)
Prevent moving `es->text` with a negative offset into the heap structures.
EDIT: #7638 hides the bug in regedit, but it does not fix the underlying issue.

[COMCTL32] Fix a heap corruption in EDIT_EM_ReplaceSel

---

dll/win32/kernel32/wine/profile.c
dll/win32/kernel32/winnls/string/lcformat.c
sdk/include/ndk/rtltypes.h
sdk/include/psdk/winbase.h
sdk/include/xdk/winnt_old.h

Improved definition that is compatible with wine hacks.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101167,101169,101171,101183
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101172,101173,101174,101184

[SDK] Improve definition of (RTL_)CRITICAL_SECTION_DEBUG

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/utils.h
dll/win32/shell32/wine/pidl.c
dll/win32/shell32/wine/pidl.h

- Display item sizes inside \\\\ UNC paths.
- Don't display anything in the location pane inside the Recycle Bin ([CORE-20005](https://jira.reactos.org/browse/CORE-20005)).
- Don't display the size and location panes in My Computer (matches Windows NT5.x).
- Don't update the location pane on simple item selection changes.

[SHELL32] DefView statusbar item file size fix in recycler and UNC

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CFolderOptions.cpp
dll/win32/shell32/CFolderOptions.h
dll/win32/shell32/dialogs/view.cpp

JIRA issue: [CORE-20029](https://jira.reactos.org/browse/CORE-20029)
The "Reset all folders" flow is now:
- If we have an IShellBrowser with a IBrowserService2 service, use that (browseui or 3rd-party browser).
- This should (browseui will) reset the browser settings and forward the command to the view (DefView or 3rd-party).
- Forward the command to DefView (in case the browser is hosting a 3rd-party view).
- Reset IGlobalFolderSettings.
- If there is no browser, we reset the global settings and forward the command to DefView.

[SHELL32] CFolderOptions Reset can call DefView directly if there is no browser

---

base/applications/cleanmgr/cleanmgr/CSelectDriveDlg.cpp
base/applications/cleanmgr/cleanmgr/cleanmgr.cpp

Notes:
- It has to use `EnumWindows` to find the other instance window to activate because we don't know if it's in the ScanDrive stage or in PropertySheet.

[CLEANMGR] Only allow one instance per drive

---

dll/win32/shell32/brfolder.cpp

- Use SHGDN_FOREDITING when renaming ([CORE-20064](https://jira.reactos.org/browse/CORE-20064)).
- Handle rename change notification without full refresh.
- Don't use FS path when deleting.

[SHELL32] Use SHGDN_FOREDITING when renaming in BrowseForFolder

---

modules/rostests/rosautotest/CWineTest.cpp
modules/rostests/rosautotest/main.cpp
modules/rostests/rosautotest/precomp.h

Typical results:
[ROSAUTOTEST] System uptime at start was 412412.86 seconds
[ROSAUTOTEST] System uptime at end was 412412.88 seconds
[ROSAUTOTEST] Duration was 0.00 minutes
The main reason that I created this was to allow me to be able to copy a single folder named "bin" into a downloaded ISO install of ReactOS. These have no ReactOS tests included with them. I wanted to be able to get the Regression Test results to use as a base and I originally had to merge my external "bin" folder with the new install and then copy over the rosautotest.exe file into the C:\ReactOS\system32 subdirectory. I wanted to be able to simplify this action, so the idea to make rosautotest.exe exclude itself from trying to run itself as a test was born. Also, these tests take a long time and scroll by hundreds of …

[ROSAUTOTEST] Allow rosautotest to be in the same directory as its files and show its duration at the end.

---

sdk/include/psdk/ntgdi.h
win32ss/gdi/gdi32/objects/text.c
win32ss/gdi/ntgdi/freetype.c

JIRA issue: [CORE-19898](https://jira.reactos.org/browse/CORE-19898)
- Modify `NtGdiExtTextOutW` prototype.
- Add `const` to some paramters.
- Make `Count` parameter unsigned.
- Delete needless type casts.

[GDI32][NTGDI][SDK] ExtTextOut: Fix some type problems

---

modules/rostests/apitests/user32/PrivateExtractIcons.c

Notes:
- All these new tests pass on various Windows versions. A couple of them fail on ROS.

[USER32_APITEST] Add more PrivateExtractIcons tests

---

dll/shellext/stobject/lang/cs-CZ.rc
dll/shellext/stobject/lang/de-DE.rc
dll/shellext/stobject/lang/en-US.rc
dll/shellext/stobject/lang/es-ES.rc
dll/shellext/stobject/lang/fr-FR.rc
dll/shellext/stobject/lang/hi-IN.rc
dll/shellext/stobject/lang/it-IT.rc
dll/shellext/stobject/lang/ja-JP.rc
dll/shellext/stobject/lang/pl-PL.rc
dll/shellext/stobject/lang/pt-PT.rc
dll/shellext/stobject/lang/ro-RO.rc
dll/shellext/stobject/lang/ru-RU.rc
dll/shellext/stobject/lang/tr-TR.rc
dll/shellext/stobject/lang/zh-CN.rc
dll/shellext/stobject/lang/zh-HK.rc
dll/shellext/stobject/lang/zh-TW.rc
dll/shellext/stobject/power.cpp
dll/shellext/stobject/resource.h

Short answer: our UI sucks bolas rojas.
Long answer: when the NT kernel informs the user-mode part of the system that the battery is no longer charging, the machine is directly powered up by the AC adapter. This is understood by determining the presence of **AC_LINE_ONLINE** status bit in `ACLineStatus` member field, which is a Windows API construct. In the NT world this is understood by checking the power state returned by the **BATTERY_STATUS** structure.
What's happening right now is that when the battery is fully charged, ROS UI simply displays "100% remaining" implying the battery is about to discharge, which is not the case. This is extremely confusing to the user. AND WORST PART IS THAT IT'S XP/2003 DESIGN, AND I HATE IT UGGGHHH. With this patch we're leaning towards Windows 10/11 …

[STOBJECT] Explicitly tell the user the battery is fully charged

---

hal/halx86/apic/halinit.c
modules/rostests/apitests/ntdll/NtCreateProfile.c

Fix hang and reboot on x64 on NtStartProfile test
- [HAL/APIC] Set the profiling interrupt handler
- [NTDLL_APITEST] Fix NtCreateProfile tests for x64

[HAL][NTDLL_APITEST] Fix hang of ntdll:NtStartProfile test

---

win32ss/gdi/eng/stubs.c
win32ss/gdi/gdi32/include/gdi32p.h
win32ss/gdi/gdi32/misc/heap.c
win32ss/gdi/gdi32/objects/font.c
win32ss/gdi/ntgdi/font.c
win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/text.h

JIRA issue: [CORE-17684](https://jira.reactos.org/browse/CORE-17684)
- Add `HEAP_strdupA2W_buf` and `HEAP_strdupA2W_buf_free` helper functions for quick string conversion.
- Optimize `HEAP_...` functions.
- Add `IntConvertFontPaths` helper function.
- Support multiple files in `AddFontResource` function.
- Add `cFiles` parameter to some internal font addition/removal functions.
- Half-implement `NtGdiRemoveFontResourceW` and `RemoveFontResourceExW` functions.

[NTGDI][GDI32] AddFontResource: Support multiple files

---

hal/halx86/generic/halinit.c
hal/halx86/smp/i386/spinup.c
ntoskrnl/ex/init.c
ntoskrnl/include/internal/ke.h
ntoskrnl/ke/i386/mproc.c
ntoskrnl/ke/processor.c

Add these switches mainly to test our new SMP support with different number
of CPUs configurations on multiprocessor systems.
- NUMPROC: maximum number of logical processors that can be started
(including dynamically, not currently supported by ReactOS) at run-time.
- BOOTPROC: maximum number of logical processors that can be started at
boot-time.
- MAXPROC: forces the OS to report the maximum possible number of CPUs
as existing on the system.
HAL-only boot switch:
- ONECPU: It causes the HAL to only use one (the boot) CPU on a MP system.
Attempting to start other processors will fail.
For more information, see:
https://www.geoffchappell.com/notes/windows/boot/bcd/osloader/numproc.htm
https://www.geoffchappell.com/notes/windows/license/processors.htm …

[NTOS][HAL] Add simple support for NUMPROC, BOOTPROC, MAXPROC and ONECPU boot switches

---

base/applications/rapps/appview.cpp
base/applications/rapps/include/appview.h

The Install/Uninstall/Modify/... buttons stay disabled by default, unless:
- For installed apps: when an app item is selected, Uninstall (and Registry-remove) are enabled, and modify is enabled under certain conditions.
- For available apps:
* Modify, Uninstall and Registry-remove are always disabled.
* When an app item is selected, Install is enabled.
* Install is also enabled if there is at least one application selected for installation (box checked), in which case the button stays enabled even while changing across apps categories.

[RAPPS] Correctly update the Install/Uninstall/... buttons

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/droptargets/CFSDropTarget.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CRecycleBin.cpp
dll/win32/shell32/precomp.h
dll/win32/shell32/shell32.spec
dll/win32/shell32/shlfileop.cpp
dll/win32/shell32/utils.cpp
dll/win32/shimgvw/shimgvw.c
sdk/include/reactos/undocshell.h

- More consistent error handling and reporting in SHFileOp.
- Use SHFileOp to rename to get its undo handling for free.
- Simplify Recycle Bin notification handling.

[SHELL32] Add SHFileOp error UI and use it for CFSFolder renaming

---

modules/rostests/rosautotest/main.cpp

_Follow-up of PR #7823._
_Used stored value of TestStartTime instead of GetTickCount()._

[ROSAUTOTEST] Final changes to improvements

---

sdk/lib/drivers/sound/mmixer/mixer.c

Skip unsuccessfully initialized devices and continue enumeration until all of devices are enumerated.
Patch by @janderwald.
Should work better in pair with #7741.
This fixes 0 audio devices detected for some audio controllers, and hence allows to properly detect all available devices and play the sound for HD audio controllers (e. g., Realtek) with MMixer routines enabled.
Tested personally with Realtek HD Audio driver version R2.74 for Windows XP/Server 2003 in pair with hdaudbus.sys from Widnows Vista SP2. It works now with MMixer APIs enabled. :smiley: 
JIRA issue: [CORE-17285](https://jira.reactos.org/browse/CORE-17285)
- Skip invalid devices and continue enumeration till the end.
- Improve debug print by displaying the value of returned status in case some of devices failed to …

[MMIXER] Don't stop audio devices enumeration when one or more of them failed to initialize

---

dll/win32/setupapi/interface.c

- Don't stop enumeration on invalid device interface key
- Necessary for drivers, which install multiple device interfaces and all interfaces might not be available for this device.

[SETUPAPI] Do not fail enumeration on invalid device interface keys

---

dll/win32/comctl32/imagelist.c

[CORE-16146](https://jira.reactos.org/browse/CORE-16146)

[COMCTL32] ImageList_LoadImageW with CLR_NONE should not use a mask

---

sdk/lib/vcruntime/__security_init_cookie.c

Fix a bug in x64 __security_init_cookie

[VCRUNTIME] Fix a bug in x64 __security_init_cookie

---

dll/win32/comctl32/listview.c

JIRA issue: [CORE-20080](https://jira.reactos.org/browse/CORE-20080) and partial [CORE-15423](https://jira.reactos.org/browse/CORE-15423)

[COMCTL32] Include size of state imagelist for column 0 LVSCW_AUTOSIZE

---

boot/freeldr/bootsect/pc98/fat12fdd.S
boot/freeldr/freeldr/arch/realmode/helpers_pc98.inc

See this PR's title. I suppose that this setting won't change between calls (when e.g. done from the other `writestr` helpers).
Do the HighRes check and cache the computed value of `VramSegment` only once, then reuse that latter one.

[FREELDR:PC98] Don't do the HighRes check everytime a character is written with writechr.

---

dll/win32/browseui/shellbrowser.cpp

Update backspace button functionality to align with standard Windows behavior in the win32 shell browser.
- Solved FIXME in `CShellBrowser::OnBackspace`
- Added `CShellBrowser::GoBackOrForward()` helper function

[BROWSEUI] Fix backspace button behavior in win32 shell browser

---

dll/win32/riched20/editor.c

_Import Wine commit: https://gitlab.winehq.org/wine/wine/-/commit/5cbe3a6cb186cffed20e3fea5f88abd0880d3914._
_Thanks to @tkreuzer for pointing me to the correctly failing function._
JIRA issue: [CORE-20082](https://jira.reactos.org/browse/CORE-20082)
_Condition adding '\r' and incrementing buffer on 'buflen' not being zero._

[RICHED20] Fix RTC MSVC Failure in function ME_GetTextW.

---

win32ss/user/user32/windows/cursoricon.c

Fix use of uninitialized variable
- KVM x86: https://reactos.org/testman/compare.php?ids=101440,101443,101446,101449
- KVM x64: https://reactos.org/testman/compare.php?ids=101441,101444,101447,101450

[USER32] Fix use of uninitialized variable

---

dll/win32/riched20/CMakeLists.txt
dll/win32/riched20/riched20.h
dll/win32/riched20/txthost.c
dll/win32/riched20/txtsrv.c

Properly fix thiscall functions by enabling thiscall wrappers on MSVC builds.
This reverts commit 74599f6 ("[RICHED20] Fix MSVC Wordpad failure after riched20 Wine Sync to 6.10 (#7789)")
Jira Issue: https://jira.reactos.org/browse/CORE-20079
See also https://jira.reactos.org/browse/CORE-20006
See also https://jira.reactos.org/browse/CORE-20079
- KVM x86: https://reactos.org/testman/compare.php?ids=101394,101397,101400,101404
- KVM x64: https://reactos.org/testman/compare.php?ids=101395,101398,101401,101406

[RICHED20] Fix thiscall functions with MSVC builds

---

sdk/cmake/config.cmake

It was introduced in commit 1f9c4940d (r38270), but this flag isn't used anymore in our source tree, and nowadays, we actively compile both UP and MP support.

[SDK:CMAKE] Remove unused BUILD_MP build option.

---

dll/win32/comctl32/pager.c

JIRA issue: [CORE-7017](https://jira.reactos.org/browse/CORE-7017)
- Add `m_bProcessingReCalcSize` to `PAGER_INFO` structure.
- Fix `EM_FMTLINES` and `PGM_RECALCSIZE` handling, by usiing `m_bProcessingReCalcSize`.
BEFORE:
AFTER:
BEFORE:
AFTER:

[COMCTL32] Pager: Fix PGM_RECALCSIZE behaviour

---

sdk/include/ndk/extypes.h

This will be needed by the mountvol tool.

[NDK] Add definition for SystemSystemPartitionInformation System Information Class

---

dll/win32/kernel32/client/file/dir.c

Drop the idea of using Unicode String, which is not really needed here. Simply allocate buffer on a PWSTR variable so the path string can be manipulated as needed.

[KERNEL32] RemoveDirectoryW: Fix the code for removing a mounted folder

---

dll/win32/imm32/CMakeLists.txt
dll/win32/imm32/ctf.c
dll/win32/imm32/debug.h
dll/win32/imm32/ime.c
dll/win32/imm32/precomp.h
dll/win32/imm32/regword.c
dll/win32/imm32/softkbd.c
media/doc/WINESYNC.txt

Related to #7870. `IMM32` uses NDK. So, we have to remove Wine dependency.
JIRA issue: [CORE-5743](https://jira.reactos.org/browse/CORE-5743)
- Add `dll/win32/imm32/debug.h`.
- Remove Wine dependency.
- Don't use `debugstr_a` and `debugstr_w` macros.
- Update the documentation (`media/doc/WINESYNC.txt`) to reflect the removal of the Wine dependency.

[IMM32] Make IMM32 non-Wine module

---

ntoskrnl/cache/section/data.c
ntoskrnl/include/internal/mm.h
ntoskrnl/mm/ARM3/miarm.h
ntoskrnl/mm/ARM3/procsup.c
ntoskrnl/mm/ARM3/section.c
ntoskrnl/mm/ARM3/vadnode.c
ntoskrnl/mm/ARM3/virtual.c
ntoskrnl/mm/marea.c
ntoskrnl/mm/mmfault.c
ntoskrnl/mm/section.c

Clean up the memory area code a bit to reduce it's hackyness.
This is some preparational work for implementing commitment accounting, i.e. making sure that we do not commit more memory than we have in terms of physical + page file. This requires some cleanup to reduce the amount of code that needs to deal with this.
Should be reviewed by commit.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101510,101513,101515,101507
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101512,101514,101516,101508

[NTOS:MM] Clean up memory area stuff

---

ntoskrnl/io/iomgr/deviface.c
ntoskrnl/io/iomgr/driver.c
ntoskrnl/io/pnpmgr/devaction.c
ntoskrnl/ob/oblink.c

Fix MSVC warnings. Be strict about string length to prevent overflows.
- ❔ KVM x86: https://reactos.org/testman/compare.php?ids=101470,101477,101483,101502
- ❔ KVM x64: https://reactos.org/testman/compare.php?ids=101478,101479,101484,101503
Possible regression in urlmon:protocol. Needs investigation
Retest:
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101558,101560,101562,101564
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101561,101563,101565,101566

[NTOS] Fix MSVC warnings

---

base/applications/mscutils/servman/lang/bg-BG.rc
base/applications/mscutils/servman/lang/cs-CZ.rc
base/applications/mscutils/servman/lang/de-DE.rc
base/applications/mscutils/servman/lang/el-GR.rc
base/applications/mscutils/servman/lang/en-US.rc
base/applications/mscutils/servman/lang/es-ES.rc
base/applications/mscutils/servman/lang/fr-FR.rc
base/applications/mscutils/servman/lang/he-IL.rc
base/applications/mscutils/servman/lang/id-ID.rc
base/applications/mscutils/servman/lang/it-IT.rc
base/applications/mscutils/servman/lang/ja-JP.rc
base/applications/mscutils/servman/lang/ko-KR.rc
base/applications/mscutils/servman/lang/no-NO.rc
base/applications/mscutils/servman/lang/pl-PL.rc
base/applications/mscutils/servman/lang/pt-PT.rc
base/applications/mscutils/servman/lang/ro-RO.rc
base/applications/mscutils/servman/lang/ru-RU.rc
base/applications/mscutils/servman/lang/sk-SK.rc
base/applications/mscutils/servman/lang/sq-AL.rc
base/applications/mscutils/servman/lang/sv-SE.rc
base/applications/mscutils/servman/lang/th-TH.rc
base/applications/mscutils/servman/lang/tr-TR.rc
base/applications/mscutils/servman/lang/uk-UA.rc
base/applications/mscutils/servman/lang/zh-CN.rc
base/applications/mscutils/servman/lang/zh-HK.rc
base/applications/mscutils/servman/lang/zh-TW.rc

_Add missing text above lower listbox._
JIRA issue: [CORE-20115](https://jira.reactos.org/browse/CORE-20115)
_Add static text for all languages for description of lower listbox._
Before:
After:

[SERVMAN] Services Properties 'Dependencies' tab missing text

---

dll/win32/shell32/dialogs/general.cpp
dll/win32/shell32/dialogs/view.cpp
dll/win32/shell32/folders/CControlPanelFolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CFSFolder.h
dll/win32/shell32/folders/CRecycleBin.cpp
dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/wine/shell32_main.h
dll/win32/shell32/wine/shpolicy.c

This setting is controlled by Group Policy and/or Tweak UI.

[SHELL32] Respect StrCmpLogicalW policy in shell folders

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.h

This is the "My Computer => Drives" setting in TweakUI. Hiding a drive only hides it from the listing in Explorer, you can still access it by typing its address in the address bar. Hiding a slow floppy drive is useful to speed up Explorer.
Notes:
- The icons will be fixed in another PR (part of a icon fix branch).
- The StrCmpLogical PR #7900 will make refresh to see the changes work when WM_SETTINGCHANGE is broadcast.

[SHELL32] Respect the REST_NODRIVES restriction

---

base/applications/taskmgr/perfdata.c
base/applications/taskmgr/perfdata.h

In Windows' taskmgr, 32-bit processes are marked with a ` *32` appended to their image name. Even though ReactOS doesn't have a WOW64 yet, this feature could be easily implemented for the future.
ReactOS taskmgr running on Windows 10
- For every process in `pPerfData`, use the open handle, to check if the process is a WOW64 process - if so, change the displayed name

[TASKMGR] Distinguish WOW64 processes with a " *32" in the image name

---

dll/win32/shell32/folders/CControlPanelFolder.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CRegFolder.cpp
dll/win32/shell32/shfldr.h
dll/win32/shell32/shlfolder.cpp
dll/win32/shell32/wine/pidl.c
dll/win32/shell32/wine/shell32_main.h
sdk/include/reactos/shellutils.h

Notes:
- Handling `PKEY_DescriptionID`/`SHGDFIL_DESCRIPTIONID` fixes the Desktop icons page in Tweak UI v2.
- Lays the foundation for fixing the official way to [detect the Recycle Bin](https://devblogs.microsoft.com/oldnewthing/20080918-00/?p=20843).
- Pre-emptive comment about the "switch case return" on one line style; keep in mind that Windows XP supports more than 50 columns here, modern Windows even more!
- The Init/FromBuffer functions are modeled after functions with the same names in propsys.dll but we can't use that directly here since it's Vista+. Once propsys is working properly, shell32 can switch to those functions when targeting NT6+.

[SHELL32] Implement IShellFolder2::GetDetailsEx

---

dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/shell32/CDefView.cpp

Another tiny fix in the saga of the broken find files menu. Using the last id is better than using the first since not everybody does everything correctly and the FCIDM commands can pass through unchanged.

[BROWSEUI] Use the last id for custom find files menu item

---

dll/win32/shell32/shellmenu/CMenuBand.cpp

This PR fixes "[definitely not EXPLORER] a subtle keyboard focus glitch in the startmenu" by deselecting the currently selected item in CMenuBand.
JIRA issue: [CORE-18855](https://jira.reactos.org/browse/CORE-18855)
Add a call to `_ChangeHotItem(NULL, -1, 0)` in `CMenuBand::OnSelect(MPOS_CANCELLEVEL)` which causes to deselect currently selected item the moment the menu bands (including start menu) are closing.
Start Menu is not destroyed when it's closed so its allocated resources can be re-used next time user wants to open it, so to keep this behavior and still not having an item selected every time you open the start menu, you have to deselect the currently selected item.

[SHELL32] Fix: Deselect highlighted item in shell menus on close

---

hal/halx86/apic/apic.c
hal/halx86/apic/apicp.h
hal/halx86/apic/apictimer.c
hal/halx86/apic/halinit.c
hal/halx86/generic/cmos.c

Fix a number of issues, mostly APIC related.
* [HALX86] Set the NMI disable flag when accessing CMOS registers
* [HALX86/APIC] Mask profiling interrupt on init
* [HALX86/APIC] Fix interrupt delivery on bare metal
* [HALX86/APIC] Set timer interrupt to level triggered
* [HALX86/APIC] Use physical addressing in HalEnableSystemInterrupt
* [HALX86/APIC] Read APIC Id from APIC instead of using initial Id
* [HALX86/APIC] Change IRQL for x86 profile interrupt to HIGH_LEVEL

[HAL] Misc fixes

---

win32ss/user/user32/controls/appswitch.c

Notes:
- I don't know if Windows has a way to reload this without rebooting but the overhead of reading them again in debug mode is negligible for those people that keep Scroll-Lock on all the time.
- I don't think `CoolSwitch == FALSE` is correctly implemented in ROS, it should probably still switch the windows while staying hidden? Someone else will have to deal with that in another PR...

[USER32] Read the CoolSwitch settings from the registry

---

dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/CShellLink.h

JIRA issue: [CORE-19971](https://jira.reactos.org/browse/CORE-19971)
The icon and other non-target related properties can now be changed for PIDL-only targets. A Darwin link is also treated as a PIDL-only target even though it technically might have a (unusable) filesystem path.

[SHELL32] Allow .Lnk properties dialog to change icon for non-FS targets

---

win32ss/gdi/gdi32/objects/bitmap.c

_This is a very small revert of #5227 to simplify the code and eliminate an MSVC warning._
_The MSVC warning was spotted by Timo Kreuzer when working on his PR #7894._
_After my investigation, I found that this part of the code was no longer necessary._
JIRA issues:
[CORE-12377](https://jira.reactos.org/browse/CORE-12377)
[CORE-18084](https://jira.reactos.org/browse/CORE-18084)
[CORE-13889](https://jira.reactos.org/browse/CORE-13889)
_This should be done in coordination with PR #7894._

[GDI32] Fix MSVC warning. Simplify code.

---

base/applications/charmap/map.c

This fixes the status bar not being refreshed by ensuring when new set font the SetCaretXY is called
JIRA issue: [CORE-19838](https://jira.reactos.org/browse/CORE-19838)
Same as described above

[CHARMAP] Fix status bar not being refreshed

---

dll/win32/shell32/wine/shellpath.c

JIRA issue: [CORE-19037](https://jira.reactos.org/browse/CORE-19037)
The member for storing the icon was removed in wine [332b90c0064563a9e4f67fb2d9b26a940e5e745c](https://gitlab.winehq.org/wine/wine/-/commit/332b90c0064563a9e4f67fb2d9b26a940e5e745c) so I'm removing the `__REACTOS__` checks (and we are not wine syncing shell32 anyway).

[SHELL32] Don't set a desktop.ini folder icon on WinDir and System32

---

base/shell/explorer/precomp.h
base/shell/explorer/startmnucust.cpp
base/shell/explorer/traywnd.cpp

Note that the normal clear button is also supposed to clear the registry and it also says so in the UI text:

[EXPLORER] Implement ClearRecentDocsOnExit setting

---

base/applications/mscutils/eventvwr/evtdetctl.c

This fixes the radio buttons being enabled by default
JIRA issue: [CORE-20037](https://jira.reactos.org/browse/CORE-20037)
Same described above

[EVENTVWR] Fix "Bytes" and "Word" buttons being enabled with empty entry

---

sdk/include/xdk/iotypes.h

This is split out of https://github.com/reactos/reactos/pull/6577

[XDK] Add missing PCI subclass type definition

---

dll/win32/shell32/shellmenu/CMenuBand.cpp

The menu band window is about to go away, don't pass it to InvokeCommand because it's invalid as an owner window for any dialogs the callee might display.
To reproduce the bug:
1. Create a .txt or .bmp file in My Documents
2. Change the Start Menu settings to expand My Documents
3. Open Start Menu=>Documents=>My Documents and right-click the file and invoke "Open With".
4. `SHOpenWithDialog` dies immediately because the owner window has now been destroyed.

[SHELL32] Don't pass menu band hwnd to InvokeCommand

---

base/applications/regedit/lang/bg-BG.rc
base/applications/regedit/lang/cs-CZ.rc
base/applications/regedit/lang/de-DE.rc
base/applications/regedit/lang/el-GR.rc
base/applications/regedit/lang/en-US.rc
base/applications/regedit/lang/es-ES.rc
base/applications/regedit/lang/fr-FR.rc
base/applications/regedit/lang/he-IL.rc
base/applications/regedit/lang/hu-HU.rc
base/applications/regedit/lang/id-ID.rc
base/applications/regedit/lang/it-IT.rc
base/applications/regedit/lang/ja-JP.rc
base/applications/regedit/lang/ko-KR.rc
base/applications/regedit/lang/nl-NL.rc
base/applications/regedit/lang/no-NO.rc
base/applications/regedit/lang/pl-PL.rc
base/applications/regedit/lang/pt-BR.rc
base/applications/regedit/lang/pt-PT.rc
base/applications/regedit/lang/ro-RO.rc
base/applications/regedit/lang/ru-RU.rc
base/applications/regedit/lang/sk-SK.rc
base/applications/regedit/lang/sl-SI.rc
base/applications/regedit/lang/sq-AL.rc
base/applications/regedit/lang/sv-SE.rc
base/applications/regedit/lang/th-TH.rc
base/applications/regedit/lang/tr-TR.rc
base/applications/regedit/lang/uk-UA.rc
base/applications/regedit/lang/zh-CN.rc
base/applications/regedit/lang/zh-HK.rc
base/applications/regedit/lang/zh-TW.rc

Add missing status text to the "Multi-String Value" and "Expandable String Value" in the "new" menu of the registry editor for the english and german languages.
JIRA issue: [CORE-19886](https://jira.reactos.org/browse/CORE-19886)

[REGEDIT] Add missing status text for "new" elements

---

base/applications/rapps/appdb.cpp
base/applications/rapps/appinfo.cpp
base/applications/rapps/geninst.cpp
base/applications/rapps/include/appdb.h
base/applications/rapps/include/appinfo.h
base/applications/rapps/include/misc.h
base/applications/rapps/loaddlg.cpp
base/applications/rapps/unattended.cpp

This feature is to help streamline the installing experience. It will extract the downloaded .zip file to a subfolder in %temp% and execute the the installer. After the installer has completed, the temporary directory is deleted.
For a package like Hxd, simply adding `Installer = ExeInZip` to the main section is enough because Rapps will default to the first .exe it finds in the root of the extracted zip. For .zip files with a folder structure or multiple .exe files, the file to execute needs to be specified.
For the Royale theme (PR waiting), it would look something like this:
```
[Section]
Name = Royale
...
Installer = ExeInZip
[ExeInZip]
Exe = Royale Theme for Win XP (2)\Royale Theme for Win XP.exe
```
Notes:
- WinGet calls this simply `zip` installer type but they have the concept of …

[RAPPS] Add ExeInZip installer type to support running installers in zip files

---

sdk/include/ddk/immdev.h
win32ss/user/user32/misc/imm.c

Supporting soft keyboard will improve IME usability.
- Define `IMS_SOFTKBDONOFF` constant as `0x13` in `<immdev.h>`.
- Implement `WM_IME_SYSTEM.IMS_SOFTKBDONOFF` message handling in `ImeWnd_OnImeSystem`.

[SDK][USER32] Implement WM_IME_SYSTEM.IMS_SOFTKBDONOFF

---

win32ss/gdi/ntgdi/freetype.c

_Return the original weight from the font instead of the requested weight under certain conditions._
JIRA issue: [CORE-17011](https://jira.reactos.org/browse/CORE-17011)
_Check is FontGDI->OriginalWeight > FontGDI->RequestWeight and if so, then return original weight._
Before:
After:

[NTGDI:FREETYPE] Fix Fonts broken by opening VLC About (Retry of PR #4579)

---

dll/win32/browseui/basebarsite.cpp
dll/win32/riched20/editor.c
dll/win32/winmm/CMakeLists.txt
sdk/cmake/msvc.cmake

- Fix remaining warnings for MSVC x86
- Fix TREAT_ALL_WARNINGS_AS_ERRORS
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101779,101781,101783,101788
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101782,101784,101785,101789

[WARNINGS] Fix MSVC warnings

---

modules/rostests/apitests/ntdll/CMakeLists.txt
modules/rostests/apitests/ntdll/NtQuerySection.c
modules/rostests/apitests/ntdll/RtlUnicodeToOemN.c
modules/rostests/apitests/ntdll/testlist.c

Add a test for NtQuerySection
- ✅ Win 2003 x86: https://build.reactos.org/#/builders/11/builds/7826/steps/1/logs/stdio: "NtQuerySection: 24 tests executed (0 marked as todo, 0 failures), 0 skipped."
- ✅ Win 2003 x64: https://reactos.org/testman/compare.php?ids=101568
- KVM x86: https://reactos.org/testman/compare.php?ids=101569
- KVM x64: https://reactos.org/testman/compare.php?ids=101571

[NTDLL_APITEST] Add a test for NtQuerySection

---

dll/win32/shell32/CShellLink.cpp
dll/win32/shell32/shlexec.cpp
win32ss/user/ntuser/hotkey.c
win32ss/user/ntuser/hotkey.h
win32ss/user/ntuser/main.c
win32ss/user/ntuser/window.c

Notes:
- `SEE_MASK_ICON` only implements the shell32 part, nothing deeper. I was also unable to make it work on NT4/2000/XP (on cmd.exe).
- `SEE_MASK_HMONITOR` works in theory but obviously not tested.
- I verified that `SEE_MASK_HOTKEY` works the same on NT5 and ROS. It does not use the normal MOD flags but the flags from ComCtl32 (don't ask me why), this is also documented on MSDN. `SC_HOTKEY` is sent to the active window, presumably so it can be blocked by fullscreen things.
- `psei->hIcon` is also correct for HMONITOR, they are in a union in newer SDKs.
- `ParseShellInfo` is commened out because a similar function in kernel32 is not implemented either. Hopefully nobody is using this Windows 3 feature.
- Because the  `RegisterHotKey` caller controls all 32-bits of the id and this …

[SHELL32][NTUSER] Implement the SEE_MASK_HOTKEY/ICON/HMONITOR flags

---

base/applications/network/dwnl/dwnl.c

Currently, this is the behavior of `dwnl.exe`, on large files,
```
C:\dwnl>dwnl https://github.com/win32ss/supermium/releases/download/v132-r2/supe
rmium_132_32_setup.exe DL1.exe
--2025-04-17 16:33:24-- https://github.com/win32ss/supermium/releases/download/v
132-r2/supermium_132_32_setup.exe
=> DL1.exe
Connecting to 4.237.22.38... done.
Sending request... Connecting to 185.199.108.133... done.
Sending request... done.
Length: 106478533 [application/x-msdownload]
99% (106471168 byte(s) downloaded)
File saved.
```
Notice that the progression stops at **99%** AND **Length: 106478533** does **NOT** match **106471168 byte(s) downloaded**
This Push Request aims to fix this experience
The following changes were made
* CBindStatusCallback_UpdateProgress - Rework the failsafe check to enable …

[DWNL] improve user experience and fix progress output

---

dll/win32/comctl32/syslink.c

This PR imports a fix from WINE project
Commit: [4805986](https://github.com/wine-mirror/wine/commit/480598680ceb86661bd269b7a64bd90e38a40f98) on wine-mirror/wine
JIRA issue: [CORE-20127](https://jira.reactos.org/browse/CORE-20127)
The font object `infoPtr->Font` is not owned by the `syslink` control, therefore freeing it would make the whole system use a different font. The fix provided by wine removes the code that deletes this font object but I think we need a check in `DeleteObject` routine to prevent a random app from deleting objects used by the system.

[WINESYNC][COMCTL32] Fix: deleting system font object when destroying syslink

---

ntoskrnl/include/internal/mm.h
ntoskrnl/mm/ARM3/miarm.h

Adjust the definition of COLORED_LIST_HEAD to always match the new MI_PTE_FRAME_BITS define.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101658,101660,101663,101681
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101806,101808,101809,101812

[NTOS] Fix x64 definition of MMPFN

---

dll/win32/shell32/shellmenu/CMenuFocusManager.cpp

This PR fixes a mouse focus glitch, happens when you move the mouse over separators in shell menus.
JIRA issue: [CORE-20124](https://jira.reactos.org/browse/CORE-20124)
Since `TB_HITTEST` returns negative numbers for ID for separator menu items ([documentation](https://learn.microsoft.com/en-us/windows/win32/controls/tb-hittest)), shell menu assumes mouse moved outside of the menu popup, highlighting the menu item for currently open submenu.
To fix this behavior, we can detect separators in `CMenuFocusManager::ProcessMouseMove` and "invert" the ID returned by `TB_HITTEST` to make it a positive number again, so the shell menu wouldn't glitch.

[SHELL32] fix: focus glitch when hovering separators with submenu open

---

dll/cpl/desk/desk.c
dll/win32/shell32/wine/control.c

Remove argument parsing hacks from desk.cpl that were originally introduced to make it work with the previous broken implementation of `Control_RunDLLW`. 
JIRA issue: [CORE-20076](https://jira.reactos.org/browse/CORE-20076)
- Remove argument parsing hacks from desk.cpl
- Fix some issues with space separated string parsing in `Control_RunDLL`
- Windows seems to allow invalid dialogbox names if ~~extra arguments are passed~~ there is only one dialogbox; this might need some new cases in rostests
- ~~Revert #6930 (maybe)~~

[DESK][SHELL32] Remove desk.cpl hacks for argument parsing

---

base/applications/wordpad/wordpad.c

This fixes the garbage in the "Get Text" dialog which occurs if theres no text input and you  click "Get Text" under Extras
JIRA issue: [CORE-19868](https://jira.reactos.org/browse/CORE-19868)
Same described above

[WORDPAD] Fix garbage in "Get Text" dialog.

---

dll/win32/comctl32/edit.c

This PR imports an one-line fix from WINE project
Commit: [e71087cd@gitlab.winehq.org:wine/wine](https://gitlab.winehq.org/wine/wine/-/commit/e71087cd39fdc546846f1f74f2e701596bcfd18d)
JIRA issue: [CORE-19903](https://jira.reactos.org/browse/CORE-19903)

[WINESYNC][COMCTL32] Move caret to the end on "select all"

---

base/applications/regedit/framewnd.c

This fixes the incorrect status bar that happens when context menu action is used
JIRA issue: [CORE-19524](https://jira.reactos.org/browse/CORE-19524)

[REGEDIT] Fix Incorrect status bar

---

base/shell/explorer/appbar.cpp
base/shell/explorer/appbar.h
base/shell/explorer/traywnd.cpp
dll/win32/shell32/appbar.c
modules/rostests/apitests/shell32/SHAppBarMessage.cpp
sdk/include/reactos/undocshell.h

Follow-up of #7778.
- Rename `APPBARDATA3264` structure as `APPBARDATAINTEROP`.
- Fix structures for WoW64.
- Use `trace` instead of `DPRINT1`.
- Add `CAppBarManager::RecomputeAllWorkareas` function.
- Fix `WM_DISPLAYCHANGE` handling to re-compute the work areas.

[EXPLORER][SHELL32][SHELL32_APITEST][SDK] AppBar Part 2

---

base/shell/filebrowser/filebrowser.exe.manifest
base/shell/filebrowser/filebrowser.exe.regfree.manifest
dll/win32/atl80/atl80.manifest
dll/win32/gdiplus/gdiplus.manifest
dll/win32/gdiplus/gdiplus11.manifest
dll/win32/msxml3/msxml3.manifest
dll/win32/msxml4/msxml4.manifest
dll/win32/msxml6/msxml6.manifest
modules/rosapps/applications/explorer-old/explorer.exe.manifest
modules/rostests/apitests/kernel32/classtest.manifest
modules/rostests/apitests/kernel32/classtest2.manifest
modules/rostests/apitests/kernel32/dep1.manifest
modules/rostests/apitests/kernel32/deptest.manifest
modules/rostests/apitests/kernel32/redirptest/redir2dep.manifest
modules/rostests/apitests/kernel32/redirptest/redirtest2.manifest
modules/rostests/apitests/user32/verclasstest1.manifest
modules/rostests/apitests/user32/verclasstest2.manifest
modules/rostests/kmtests/kmtest/kmtest.exe.manifest

Change manifest architecture from X86 to *
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=101863,101878,101881,101888
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=101864,101880,101882,101889

[REACTOS] Change manifest architecture from X86 to *

---

drivers/bus/acpi/eval.c
drivers/bus/acpi/include/acpisys.h
drivers/bus/acpi/main.c

Fix a bug introduced in 5070e8960aed88d55cc9b7970dbe7bcb9a775d1a.
- These handlers must be memory resident. Otherwise, this would case a page fault that needs to be resolved. Low-level storage drivers could evaluate ACPI control methods while the device's IRP queue has been paused.
- Minor code enhancements

[ACPI] Remove section assignment from IOCTL handlers

---

win32ss/gdi/ntgdi/freetype.c
win32ss/gdi/ntgdi/misc.h
win32ss/user/ntuser/misc/registry.c

Enable the users to delete fonts.
JIRA issue: [CORE-17684](https://jira.reactos.org/browse/CORE-17684)
- Add `IntDeleteRegFontEntry` helper function.
- Add `RegDeleteValueW` and `RegEnumValueW` helper functions in `win32ss/user/ntuser/misc/registry.c`.
- Add some code to `IntGdiRemoveFontResourceSingle` function.

[NTGDI][NTUSER] Initial support of NtGdiRemoveFontResourceW

---

dll/win32/browseui/addresseditbox.cpp

JIRA issue: [CORE-20091](https://jira.reactos.org/browse/CORE-20091)
Windows also resets the address after invoking a non-folder thing.

[BROWSEUI] Don't remember invoked non-folders in addressbar

---

dll/win32/browseui/shellbars/CISFBand.cpp
dll/win32/browseui/shellbars/CISFBand.h

Respond change notification on Quick Launch.
JIRA issue: [CORE-18475](https://jira.reactos.org/browse/CORE-18475)
- Subclass `CISFBand` to handle messages.
- Register change notification.
- Refresh buttons on change notification.
- Use timer to improve UI/UX and reduce cost.
BEFORE:
AFTER:

[BROWSEUI] Quick Launch: Refresh buttons on change notify

---

dll/win32/browseui/shellbrowser.cpp

Silence `"NtUserSetWindowPos bad window handle!"` error at `win32k!NtUserSetWindowPos` function when Desktop has started up.
JIRA issue: [CORE-19663](https://jira.reactos.org/browse/CORE-19663)
- Add null check of window handle before `SetWindowPos` call in `CShellBrowser::RepositionBars` method.

[BROWSEUI] Fix 'bad window handle' on CShellBrowser::RepositionBars

---

boot/bootdata/hiveinst.inf
win32ss/drivers/miniport/vga/vga_reg.inf
win32ss/gdi/eng/device.c
win32ss/gdi/eng/pdevobj.c
win32ss/user/ntuser/winsta.c

Fall back to VGA driver if "main" driver can't be used because
- not installed
- installed, but .sys file is not present
- is failing its HwInitialize method
- is failing IOCTL_VIDEO_SET_CURRENT_MODE
JIRA issue: [CORE-7728](https://jira.reactos.org/browse/CORE-7728)
JIRA issue: [CORE-16002](https://jira.reactos.org/browse/CORE-16002)
JIRA issue: [CORE-16009](https://jira.reactos.org/browse/CORE-16009)
JIRA issue: [CORE-18245](https://jira.reactos.org/browse/CORE-18245)
JIRA issue: [CORE-19224](https://jira.reactos.org/browse/CORE-19224)
- win32k: handle the fact that the primary device may need to be recalculated (if gbBaseVideo is changed)
- win32k: set DISPLAY_DEVICE_PRIMARY_DEVICE flag only on primary device
- win32k: if main driver fails to initialize, set gbBaseVideo variable and try …

Fallback to VGA display driver if "main" one is not working

---

boot/freeldr/freeldr/ntldr/winldr.c

This PR makes FreeLoader print a notice message before it passes the control to the kernel, if boot option `/DEBUG` is provided.
I'm doing this because people (like me😅) can forget that they're booting in debug mode and they need to attach a debugger for boot process to continue. 
Screenshot:
https://github.com/user-attachments/assets/67f6cc16-2276-475a-a8b5-63f29fe881d2
* Check for absence of `NODEBUG` and `CRASHDEBUG` options and presence of `DEBUG` option
* Use `TuiPrintf` to print the notice message if the check passed
* I tried to use `#if KDBG` to exclude the code from compilation if KDBG support is not enabled, but seems like KDBG is not defined in Free Loader even when it's enabled in the kernel. I tried to use the CMake code included in NTOSKRNL's CMakeLists but …

[FREELDR] Show a notice message when booting in debug mode

---

dll/win32/comctl32/commctrl.c

_Fix regression of missing left border of some text as shown in Explorer._
JIRA issue: [CORE-19854](https://jira.reactos.org/browse/CORE-19854)
_Remove flag BF_MIDDLE from DrawEdge function._
Before: 
After:

[COMCTL32] Fix StatusBar left border frame missing

---

dll/win32/imm32/CMakeLists.txt
dll/win32/imm32/precomp.h

Partially revert #7912.
JIRA issue: [CORE-5743](https://jira.reactos.org/browse/CORE-5743)
- Use `wine` instead of `wine2ros`.
- Improve Unexpected Condition Checkers.

[IMM32] Revert to Wine module

---

dll/win32/netapi32/CMakeLists.txt
dll/win32/netapi32/netapi32.h

Partially revert #7912.
JIRA issue: [CORE-5743](https://jira.reactos.org/browse/CORE-5743)
- Use `wine` instead of `wine2ros`.

[NETAPI32] Revert to Wine module

---

dll/win32/shdocvw/CNSCBand.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/CNewMenu.cpp
dll/win32/shell32/brfolder.cpp
dll/win32/shlwapi/rosordinal.c
sdk/include/reactos/shellutils.h

* Folder Marker 1.4 fails if it gets a `WM_INITPOPUPMENU` it does not expect.
* Owner-draw messages must be forwarded by the window hosting `IContextMenu`.
JIRA issue: [CORE-17811](https://jira.reactos.org/browse/CORE-17811)

[SHELL32][SHDOCVW] Only forward menu messages to the correct shell extension

---

dll/win32/imm32/imemenu.c
dll/win32/imm32/precomp.h
dll/win32/imm32/utils.c

This PR fixes the `ImmLocalAlloc` usage by replacing the `LPTR` flag (designed for `LocalAlloc`) with `0`, which is appropriate for `ImmLocalAlloc` that uses `HeapAlloc` internally.
- Replaces `LPTR` with `0` in two calls to `ImmLocalAlloc` within `imemenu.c` (No need to zero-fill).

[IMM32] Fix ImmLocalAlloc usage

---

modules/rostests/apitests/shell32/testlist.c

This test hangs on Windows 2003 and breaks testing on Windows 2003 x64.
JIRA issue: [CORE-14762](https://jira.reactos.org/browse/CORE-14762)

[SHELL32_APITEST] Comment out OpenAs_RunDLL test

---

modules/rostests/apitests/kernel32/classtest.manifest
modules/rostests/apitests/kernel32/classtest2.manifest
modules/rostests/apitests/kernel32/dep1.manifest
modules/rostests/apitests/kernel32/deptest.manifest
modules/rostests/apitests/kernel32/redirptest/redir2dep.manifest
modules/rostests/apitests/kernel32/redirptest/redirtest2.manifest

Fixes crash of kernel32_apitest LoadLibraryExW and failures in kernel32_apitest  FindActCtxSectionStringW on Test WHS.
- WHS: https://reactos.org/testman/compare.php?ids=102018,102017,102019
- Windows 2003 x64: https://reactos.org/testman/compare.php?ids=102003,102020,102025
- KVM x86: https://reactos.org/testman/compare.php?ids=102000,102004,102028
- KVM x64: https://reactos.org/testman/compare.php?ids=102001,102006,102021,102027

[KERNEL32_APITEST] Revert some manifest architecture changes

---

dll/win32/imm32/imemenu.c

Supporting old IMEs.
- Do null check of `ImeGetImeMenuItems` function of IME side, in `ImmGetImeMenuItemsAW` function.

[IMM32] ImeGetImeMenuItems is optional

---

dll/win32/imm32/ime.c
dll/win32/imm32/precomp.h
dll/win32/imm32/utils.c

Unleash our debugging power.
JIRA issue: [CORE-19455](https://jira.reactos.org/browse/CORE-19455)
- Add some traces for `NotifyIME` calls.
- Improve `Imm32MakeIMENotify` trace.
- Make some parameter types of `Imm32MakeIMENotify` function `DWORD`'s. 
- Fix and improve `ERR_PRINTF` macro.

[IMM32] NotifyIME: Improve debug trace

---

dll/win32/imm32/ctf.c
dll/win32/imm32/ime.c
win32ss/include/ntuser.h
win32ss/user/ntuser/ime.c

This PR enhances Cicero IME support.
- Add null checks for the functions of Cicero IMEs in `Imm32LoadIME` function.
- Add and use `IS_CICERO_COMPAT_DISABLED` macro in `win32ss/include/ntuser.h`.
- Fix `ImmGetImeInfoEx`, `Imm32LoadImeDpi`, `ImmGetDescriptionA`, `ImmGetDescriptionW`, `ImmGetIMEFileNameA`, `ImmGetIMEFileNameW`, and `ImmGetProperty` functions for Cicero IME support.
- Set last error in `NtUserGetImeInfoEx`.

[IMM32][NTUSER] Strictly check Cicero IME

---

drivers/network/dd/e1000/info.c

Implement OID_GEN_PHYSICAL_MEDIUM in e1000 driver to silence annoying debug spam on VBox.

[E1000] Implement OID_GEN_PHYSICAL_MEDIUM

---

sdk/include/reactos/imm32_undoc.h
win32ss/user/imm32/imepro.c

Implementing missing features... These functions are given for IME program handling.
- Implement `ImmIMPQueryIMEA` and `ImmIMPQueryIMEW` functions.
- Implement `ImmIMPSetIMEA` and `ImmIMPSetIMEW` functions.
- Add prototypes to `<imm32_undoc.h>`.

[IMM32][SDK] Support ImmIMPQueryIMEA/W and ImmIMPSetIMEA/W

---

modules/rostests/apitests/appshim/ignoreloadlib.c

Fix appshim:ignoreloadlib test on x86 versions of Vista and 7.
- On x86 builds, accept the sentinel hmodule instead of the 111 hmodule and 0 hmodule for Vista and 7.

[APPSHIM_APITEST] Fix test for x86 Vista and 7

---

win32ss/gdi/dib/alphablend.c
win32ss/gdi/dib/dib_new.c

Match/Use `DIB_16BPP_AlphaBlend` and `DIB_XXBPP_AlphaBlend` where they apply.
- TestKVM x86: https://reactos.org/testman/compare.php?ids=101186,101194,101196,101203
- Test KVM x64: https://reactos.org/testman/compare.php?ids=101188,101195,101197,101204

[WIN32K:DIB] USE_DIBLIB: Use new DIB_16BPP_AlphaBlend()

---

sdk/include/reactos/msctf_undoc.h

This interface is needed for `msctf.dll`.
- Add `ITfRangeAnchor` interface (based on current `msctf` implementation) to `<msctf_undoc.h>`.

[SDK] Add ITfRangeAnchor interface to <msctf_undoc.h>

---

base/shell/cmd/cmd.c
base/shell/cmd/cmd.h
base/shell/cmd/error.c
boot/bootdata/hivecls.inf
dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/COpenWithMenu.cpp
dll/win32/shell32/CQueryAssociations.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/res/rgs/openwithmenu.rgs
dll/win32/shell32/shlexec.cpp
dll/win32/shell32/utils.h
dll/win32/shlwapi/assoc.c

Notes:
- The "Open with" (double-click) handler for unregistered file extensions is now in `HKCR\Unknown\shell\openas` like it is on Windows and can be overridden by the user if they desire.
- Fixes a bug in `ShellExecuteEx` where it tries to use `hkeyClass` when the caller specifies the class as a string (one of the SEE flags is 0x1 and the other is 0x3!).
- Known verbs in CDefaultContextMenu should now only fall back to translated strings in shell32 if they have no friendly name in the registry.
- Fixes a problem in cmd.exe when `ShellExecuteEx` successfully starts a "non-process" command. It will not longer print its "bad command" error message in this case.
- Fixes an Assoc API initialization bug in shlwapi where the init flags mask was also applied to the command.
JIRA issue: …

[SHELL32][CMD][SHLWAPI] Use the openas verb when invoking unknown file types

---

modules/rostests/apitests/crt/setjmp.c

fix failures: https://reactos.org/testman/compare.php?ids=101896

[CRT_APITEST] Fix test failures on Win 2003 x64

---

base/applications/kbswitch/kbswitch.c
base/applications/kbswitch/resource.h

We believe the power of simplicity.
JIRA issue: [CORE-20142](https://jira.reactos.org/browse/CORE-20142)
- Rename `g_nCurrentLayoutNum` as `g_iKL` for simplicity.
- Make `g_iKL` zero-based indexing.
- Add `ID_LANG_BASE` id for language menu items and adjust `ID_EXIT`/`ID_PREFERENCES` values.
- Fix `KbSwitch_OnNotifyIconMsg` function.

[KBSWITCH] Refactor on layout numbers

---

boot/bootdata/hivesys.inf

Correctly sort these two "lists", before looking into "missing" entries (as in #8045).
JIRA issue: [CORE-16766](https://jira.reactos.org/browse/CORE-16766)
- 2 duplicate removals.
- 2 sorts.

[BOOTDATA] hivesys.inf: Sort 5 NLS languages and locales

---

base/system/format/format.c

wmain() already handles this.
Addendum to 9cea0fd (r24253).
JIRA issue: [CORE-20218](https://jira.reactos.org/browse/CORE-20218)
- Remove redundant LoadFMIFSEntryPoints() call

[FORMAT] Usage(): Remove redundant LoadFMIFSEntryPoints() call

---

base/shell/explorer/appbar.cpp
base/shell/explorer/appbar.h
base/shell/explorer/precomp.h
base/shell/explorer/traywnd.cpp

Follow-up of #7946.
- Implement `ABM_GETSTATE`, `ABM_GETTASKBARPOS`, `ABM_ACTIVATE`, `ABM_WINDOWPOSCHANGED`, `ABM_GETAUTOHIDEBAR`, `ABM_SETAUTOHIDEBAR`, and `ABM_SETSTATE` appbar messages.
- Implement `TWM_SETZORDER` tray message.
- Multiple auto-hide bar.
- Rude apps handling.

[EXPLORER] AppBar Part 3

---

boot/freeldr/freeldr/lib/fs/ntfs.c

So when you create a NTFS partition with windows and modify with linux the ntldr/bootmgr will compare the file names ignoring the case of the file while freeldr does not and the same hack is on btrfs file name comparison.
This PR is necessary because the case of the file names on registry are not consistent!!!!
- Try to install windows with ntfs and install freeldr on it
- Try to modify windows partition on linux like creating/copying some new files
- Try to boot with freeldr (it will fail if the hive file path case is different than the actual file path)
- Try to boot with ntldr/bootmgr (it will work finally reaching the desktop)

[FREELDR] Make the NTFS filename comparison conforming to the NTLDR/BOOTMGR

---

dll/win32/shell32/CDefView.cpp
dll/win32/shell32/dialogs/general.cpp
dll/win32/shell32/shfldr.h

This fixes the single-click option in the folder options dialog.
The hand cursor and text underline does not work since the ListView has not implemented those styles yet. The [UseDoubleClickTimer](https://superuser.com/questions/1807158/windows-double-click-detection-usedoubleclicktimer) feature is also missing in the ListView which can cause some focus issues in single-click mode.
I don't particularly like this feature but it's front and center in the folder options dialog so it needs to work.

[SHELL32] Implement single-click mode in DefView

---

modules/rostests/apitests/gdi32/SetWindowExtEx.c

Fixes the gdi32:SetWindowExtEx test for unusual vertical resolutions.
I ran into this test failure often when running this test in VMware Workstation. When maximized, the vertical resolution of the guest VM is 920px, and unfortunately both GCC and MSVC builds will calculate this incorrectly without this fix. I did also test this change with several other vertical resolutions, and it worked on all resolutions while the older version only worked on most resolutions.
- Use multiplying and bit shifting to divide by 3 instead of relying on the compiler to figure out how to best divide by 3.

[GDI32_APITEST] Fix test on all versions of Windows at certain vertical resolutions

---

modules/rostests/kmtests/CMakeLists.txt
modules/rostests/kmtests/hal/HalPortIo.c
modules/rostests/kmtests/include/kmt_test.h
modules/rostests/kmtests/include/kmt_test_kernel.h
modules/rostests/kmtests/kmtest_drv/kmtest_drv.c
modules/rostests/kmtests/kmtest_drv/testlist.c
modules/rostests/kmtests/kmtest_drv/vm_detect.S
modules/rostests/kmtests/kmtest_drv/vm_detect.c

JIRA issue: [CORE-20078](https://jira.reactos.org/browse/CORE-20078)

[KMTESTS:HAL] Add a test for string I/O intrinsic functions

---

win32ss/user/ntuser/hotkey.c
win32ss/user/ntuser/hotkey.h
win32ss/user/ntuser/input.c
win32ss/user/ntuser/message.c

- Remove duplicated code in NtUserRegisterHotKey() and in NtUserUnregisterHotKey() by directly calling UserRegisterHotKey() and UserUnregisterHotKey() after the usual user-validation steps.
- In UserRegisterHotKey(), ignore hotkeys with virtual key VK_PACKET since this is not a real keyboard input, but is instead used in conjunction with unicode characters to simulate keystrokes for non-keyboard input methods.
- s/StartDebugHotKeys/SetDebugHotKeys/
- Remove duplicate code between NtUserCallMsgFilter() and IntCallMsgFilter().

[WIN32SS:NTUSER] Minor code cleanup in hotkey code

---

base/system/winlogon/sas.c
base/system/winlogon/winlogon.h

Register hotkeys for 'Lock Workstation' (Win+L) and 'UtilMan' (Win+U).
In order to simplify code, use instead the hotkey IDs in the WM_HOTKEY handler.

[WINLOGON] Register hotkeys for 'Lock Workstation' and 'Accessibility' (UtilMan)

---

sdk/include/ddk/immdev.h
win32ss/user/imm32/imemenu.c
win32ss/user/user32/include/user32p.h
win32ss/user/user32/misc/dllmain.c
win32ss/user/user32/misc/imm.c

Splitted from #8080. The message handling of `WM_IME_SYSTEM.0x1D` is needed for IME menu handling.
JIRA issue: [CORE-20142](https://jira.reactos.org/browse/CORE-20142)
- Define `IMS_IMEMENUITEMSELECTED` (`0x1D`) in `<immdev.h>`.
- Add `WM_IME_SYSTEM.0x1D` handling in `ImeWnd_OnImeSystem` function.
- Rename and extend `User32GetImmFileName` function as `User32GetSystemFilePath`, with adding a filename parameter.

[USER32][IMM32][SDK] Support WM_IME_SYSTEM.0x1D

---

modules/rosapps/applications/devutils/shlextdbg/shlextdbg.cpp

Modern Windows will query the site for a shell browser etc. and `/SITE` will now log these requests.

[SHLEXTDBG] Added more SEI flags

---

modules/rostests/apitests/user32/MessageStateAnalyzer.c
sdk/include/reactos/msgdump.h

- Replace `MSGDUMP_TPRINTF` with `MSGDUMP_PRINTF` and use ANSI for strings. Now, we can use `printf`-compatible function for dump. 
- Fix some mistakes.
- Adapt `user32_apitest MessageStateAnalyzer` to these changes.

[SDK][USER32_APITEST] Update <msgdump.h>

---

base/shell/explorer/traywnd.cpp

JIRA issue: [CORE-20219](https://jira.reactos.org/browse/CORE-20219)
BEFORE:
AFTER:
- Set `MINMAXINFO` data in `WM_GETMINMAXINFO` message handling.

[EXPLORER] Taskbar: Set MINMAXINFO correctly

---

dll/win32/syssetup/wizard.c

'Locale' format is "0000nnnn".
JIRA issue: [CORE-15848](https://jira.reactos.org/browse/CORE-15848)
- WriteUserLocale(): Fix Locale[] length and value

[SYSSETUP] WriteUserLocale(): Fix Locale[] length and value

---

win32ss/user/imm32/compstr.c
win32ss/user/imm32/ime.c
win32ss/user/imm32/imemenu.c
win32ss/user/imm32/regword.c
win32ss/user/imm32/utils.c

Coding style fix.
- Use `ANSI_NULL` for `'\0'`.
- Use `UNICODE_NULL` for `L'\0'`.

[IMM32] Use ANSI_NULL and UNICODE_NULL

---

base/applications/kbswitch/indicdll/indicdll.c
base/applications/kbswitch/kbswitch.c
base/applications/kbswitch/lang/bg-BG.rc
base/applications/kbswitch/lang/cs-CZ.rc
base/applications/kbswitch/lang/de-DE.rc
base/applications/kbswitch/lang/en-US.rc
base/applications/kbswitch/lang/es-ES.rc
base/applications/kbswitch/lang/et-EE.rc
base/applications/kbswitch/lang/fr-FR.rc
base/applications/kbswitch/lang/he-IL.rc
base/applications/kbswitch/lang/it-IT.rc
base/applications/kbswitch/lang/ja-JP.rc
base/applications/kbswitch/lang/lt-LT.rc
base/applications/kbswitch/lang/no-NO.rc
base/applications/kbswitch/lang/pl-PL.rc
base/applications/kbswitch/lang/pt-BR.rc
base/applications/kbswitch/lang/pt-PT.rc
base/applications/kbswitch/lang/ro-RO.rc
base/applications/kbswitch/lang/ru-RU.rc
base/applications/kbswitch/lang/sk-SK.rc
base/applications/kbswitch/lang/sq-AL.rc
base/applications/kbswitch/lang/sv-SE.rc
base/applications/kbswitch/lang/tr-TR.rc
base/applications/kbswitch/lang/uk-UA.rc
base/applications/kbswitch/lang/zh-CN.rc
base/applications/kbswitch/lang/zh-HK.rc
base/applications/kbswitch/lang/zh-TW.rc
base/applications/kbswitch/resource.h

Finishing IME menu work. The IME menu of the system pen icon has to append the default items if `DMI_LEFT` and `RDMI_RIGHT` are not specified.
JIRA issue: [CORE-20142](https://jira.reactos.org/browse/CORE-20142)
- Add `IsRegImeToolbarShown` and `ShowImeToolbar` helper functions.
- Add more code into `KbSwitch_OnPenIconMsg` function to handle IME menu default items.
- Add many resource strings.
AFTER:

[KBSWITCH] Handle IME Menu default items

---

boot/bootdata/hivesft.inf
win32ss/include/ntuser.h
win32ss/user/ntuser/metric.c
win32ss/user/ntuser/userfuncs.h

Improve CTF IME customization. Use the proper names for CTF IME.
- In the registry key `"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\IMM"`, add `DontLoadCTFIME` value and set it to `1`.
- Delete `LoadCTFIME` value to avoid user confusing.
- Rename `UserIsCiceroEnabled` function as `UserIsCTFIMEEnabled`.
- Rename `SRVINFO_CICERO_ENABLED` flag as `SRVINFO_CTFIME_ENABLED`.

[BOOTDATA][NTUSER] Add DontLoadCTFIME and use it

---

dll/win32/comctl32/edit.c
win32ss/user/user32/controls/edit.c

The caret move on IME was slow until this PR.
- Don't use `ImmIsIME` but use `IS_IME_HKL(hKL)` in `EDIT_SetCaretPos` function. This change improves the caret speed.
- Prohibit display of composition window for Korean in the handling of `WM_IME_SETCONTEXT` and `WM_IME_STARTCOMPOSITION`, because Korean doesn't want it.

[USER32][COMCTL32] Edit: Optimize EDIT_SetCaretPos for speed

---

dll/win32/uxtheme/CMakeLists.txt
dll/win32/uxtheme/buffer.c
dll/win32/uxtheme/metric.c
dll/win32/uxtheme/system.c
dll/win32/uxtheme/uxtheme_vista.spec
sdk/include/psdk/uxtheme.h

Implement various uxtheme functions added in Vista or later - most are from WINE.
JIRA issue: None...? (how)
- KVM [x] https://reactos.org/testman/compare.php?ids=102434,102441
-  KVM x64 [x] https://reactos.org/testman/compare.php?ids=102434,102441

[UXTHEME] Implement various Vista+ functions, mostly from WINE

---

base/shell/explorer/precomp.h
base/shell/explorer/taskswnd.cpp
base/shell/explorer/traywnd.cpp

Adds support for handling fullscreen applications (a.k.a. “rude apps”) so the taskbar can hide or show appropriately.
JIRA issue: [CORE-11242](https://jira.reactos.org/browse/CORE-11242)
Adds support for detecting “rude” fullscreen applications and hiding or showing the taskbar accordingly.
- Removes legacy pulse/timer logic in the tray window and adds a fullscreen notification workflow.
- Implements fullscreen detection across monitors in the task switcher, using a sequence of validation timers.
- Defines a new `ITrayWindow::NotifyFullScreenToAppBars` interface method to broadcast fullscreen state to appbars.
BEFORE:
AFTER:

[EXPLORER] Add fullscreen handling

---

base/system/winlogon/sas.c
base/system/winlogon/wlx.c

Some simple fixes for Winlogon.
- ### `[WINLOGON] DefaultWlxWindowProc(WLX_WM_SAS): return an adequate WLX_DLG_* value`
For more details, see:
https://learn.microsoft.com/en-us/windows/win32/api/winwlx/nc-winwlx-pwlx_dialog_box_indirect_param#return-value
- ### `[WINLOGON] WlxSwitchDesktopToUser/Winlogon(): ensure the calling thread is assigned the specified desktop`
Invoke SetThreadDesktop() after a successful SwitchDesktop() call.
- ### `[WINLOGON] Invoke NtShutdownSystem() with an adequate shutdown action`
Specify a shutdown action value corresponding to the `WLX_SAS_ACTION_SHUTDOWN_*` ones.

[WINLOGON] Diverse fixes - Part 1

---

dll/shellext/netshell/shfldr_netconnect.cpp
dll/shellext/netshell/shfldr_netconnect.h
dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/propsheet.cpp
dll/win32/shell32/shell32.spec
dll/win32/shell32/shlexec.cpp
dll/win32/shell32/wine/PolicyData.h
dll/win32/shell32/wine/shell32_main.h
dll/win32/shell32/wine/shellole.c
dll/win32/shell32/wine/shpolicy.c
sdk/include/reactos/shellutils.h
sdk/include/reactos/undocshell.h

The network extension is not supposed to use a hook (it was not even called in my testing and its implementation does not follow [the documentation](https://web.archive.org/web/20091126210539/http://msdn.microsoft.com/en-us/library/bb775099(VS.85).aspx)). The only expected hook is "URL Exec Hook" on NT5.

[SHELL32] Fix IShellExecuteHookW

---

dll/win32/syssetup/wizard.c

Especially, unskip DateTime page.
Addendum to fc1f0c2 (r75495).
JIRA issue: [CORE-15848](https://jira.reactos.org/browse/CORE-15848)
- Update the correct code line(s).

[SYSSETUP] wizard.c, UnattendSetup: Fix Theme page order

---

ntoskrnl/se/sd.c

[NTOS:SE] SeValidSecurityDescriptor: Use relative security descriptor header size for length calculation

---

ntoskrnl/ps/query.c

A failure is not a success.
Addendum to bf493b9 (r59859).
- Do not overwrite Status failure value.

[NTOS:PS] Fix NtQueryInformationProcess(ProcessImageInformation)

---

modules/rostests/winetests/ntdll/info.c
ntoskrnl/ps/query.c

Correctly handle failures. Plus a couple optimizations.
- test_query_process_debug_object_handle(): 1 WINESYNC
Cherry-pick WineTest part of
https://gitlab.winehq.org/wine/wine/-/commit/52d733b5c4876276d7a2dfc8d9a9bb72a853dfd0
- Fix NtQueryInformationProcess(ProcessDebugObjectHandle)
Addendum to 1e172203a (r55734).
-- Close DebugPort, on failure.
- Optimize NtQueryInformationProcess(ProcessWow64Information)
on 32-bit.
Addendum to 1e172203a (r55734).
- Fix NtQueryInformationProcess(ProcessExecuteFlags)
s/return/break/ on a failure case.
Addendum to 1e172203a (r55734).
- NtQueryInformationProcess(): Optimize *ReturnLength assignment
Addendum to 2278c29 (r23175).
In all these, one additional test in `ntdll:info` is run, and the number of failures didn't change.

[NTDLL_WINETEST][NTOS:PS] Fix a few NtQueryInformationProcess(Process*) handling cases

---

dll/shellext/netshell/shfldr_netconnect.cpp
dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/precomp.h

DefView will now map its internal (FCIDM) commands (when sent from the toolbar and accelerators) to canonical verb strings so clients outside shell32 can detect the verb. This is critical for "rename" and handy for "properties".
JIRA issue: [CORE-18326](https://jira.reactos.org/browse/CORE-18326)

[BROWSEUI][SHELL32] Fixed FindFiles rename operation

---

dll/win32/kernel32/kernel32_vista/CMakeLists.txt
dll/win32/kernel32/kernel32_vista/GetFinalPathNameByHandle.c
dll/win32/kernel32/kernel32_vista/vista.c
modules/rostests/apitests/kernel32/CMakeLists.txt
modules/rostests/apitests/kernel32/GetFinalPathNameByHandle.c
modules/rostests/apitests/kernel32/testlist.c
modules/rostests/apitests/ntdll/NtQueryObject.c
sdk/include/psdk/lmshare.h

This PR implements GetFinalPathNameByHandleW. The wine version is broken and doesn't work, because it relies on a broken behavior of NtQueryObject.
- [PSDK] Fix up lmshare.h
- [NTDLL_APITEST] Add another test for NtQueryObject (This shows that wine's code doesn't work)
- [KERNEL32_APITEST] Add tests for GetFinalPathNameByHandleW
- [KERNEL32_VISTA] Implement GetFinalPathNameByHandleW
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=102622,102628,102631
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=102626,102629,102632

[KERNEL32] Implement GetFinalPathNameByHandleW

---

dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/browseui/shellfind/CSearchBar.cpp
dll/win32/shell32/CDefView.cpp

`CFindFolder` is incorrectly forwarding `SHCIDS_CANONICALONLY` to its inner `CFSFolder` causing `CFSFolder::CompareIDs` to fail.
Notes:
- Also fixes focus stealing during rename if the search completes during a rename.
JIRA issue: [CORE-20250](https://jira.reactos.org/browse/CORE-20250)

[BROWSEUI] Fix CompareIDs lParam passed to inner folder

---

dll/win32/shell32/CDefView.cpp

`IShellFolder::CompareIDs` does not understand ListView columns, we must provide it with a column index it understands during sorting. This bug only happens for folders with columns that are hidden and only the find files folder has columns that are hidden by default (in our shell).
JIRA issue: [CORE-20251](https://jira.reactos.org/browse/CORE-20251)

[SHELL32] Use the folder column, not the list column during DefView sorting

---

dll/win32/browseui/shellfind/CFindFolder.cpp
dll/win32/browseui/shellfind/CFindFolder.h
dll/win32/shell32/folders/CFSFolder.h

This silences the ERR seen in [CORE-20256](https://jira.reactos.org/browse/CORE-20256).

[BROWSEUI] Find files must forward IItemNameLimits to the FS folder

---

base/applications/kbswitch/indicdll/indicdll.c

Related to #8145. We shouldn't use `user32` functions in `DllMain.DLL_PROCESS_ATTACH`. This bug affects Global Hook. See [`DllMain`](https://learn.microsoft.com/en-us/windows/win32/dlls/dllmain#remarks) and ["Dynamic-Link Library Best Practices"](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices#general-best-practices) on MS Learn.
JIRA issue: [CORE-20242](https://jira.reactos.org/browse/CORE-20242)
- Don't use `user32!FindWindow` in `DllMain.DLL_PROCESS_ATTACH`, but in `KbSwitchSetHooks` function.

[INDICDLL] Don't use user32 in DLL_PROCESS_ATTACH

---

modules/rostests/apitests/ntdll/RtlQueryTimeZoneInfo.c

Remove unused / broken definitions. Bad enough that wine has their definitions wrong, let's not spread that into other places.

[NTDLL_APITEST] Remove unused / broken definitions

---

base/shell/explorer/taskswnd.cpp

Taskbar task button context menu was wrongly overlapped by Taskbar. #8105 introduced this bug.
JIRA issue: [CORE-20260](https://jira.reactos.org/browse/CORE-20260)
- Don't bring the taskbar to top on no rude app.
- Check the target window by `FindTaskItem` in `OnWindowActivated` and `OnWindowDestroyed`.
BEFORE:
AFTER:

[EXPLORER] Fix Taskbar context menu Z-order bug

---

sdk/cmake/msvc.cmake

"Far East Asian" Visual Studio had generated a lot of `"warning C4819: File contains characters that cannot be displayed in the current code page..."`.
```txt
error C2220: 次の警告はエラーとして処理されます
warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
```
- Insert `add_compile_options(/wd4819)` into `sdk/cmake/msvc.cmake`.

[CMAKE] msvc.cmake: Add /wd4819 for Far East Asian

---

boot/freeldr/freeldr/include/mm.h

Hack reactos amd64 so we can boot on systems with higher ram amounts tested up to 128gb
@tkreuzer  mentioned a real fix will come eventually but for now i'll apply this hack
JIRA report: [CORE-20265](https://jira.reactos.org/browse/CORE-20265)

[FREELDR] Hack AMD64 to boot with higher amounts of RAM

---

drivers/storage/port/scsiport/ioctl.c

If I understand correctly, this (ATA) ioctl code is valid, but implementation is optional (especially in SCSI).
JIRA issue: [CORE-16422](https://jira.reactos.org/browse/CORE-16422)
Please, double-check the message text.
Note:
`IOCTL_SCSI_PASS_THROUGH` is a stub (only), but that would be a separate issue.

[SCSIPORT] Add an explicit IOCTL_ATA_PASS_THROUGH* case

---

modules/rostests/apitests/shlwapi/IsQSForward.cpp
modules/rostests/apitests/shlwapi/PathIsUNC.c
modules/rostests/apitests/shlwapi/PathIsUNCServer.c
modules/rostests/apitests/shlwapi/SHPropertyBag.cpp

Fix test failures and a heap assertion on Vista+.
| Test            | 2003 (x86) | Vista (x86) | Vista (x64) | 7 (x86) | 7 (x64) | 8.1 (x86) | 8.1 (x64) | 10 (x86) | 10 (x64) |
| --------------- | ---------- | ----------- | ----------- | ------- | ------- | --------- | --------- | -------- | -------- |
| IsQSForward     | 0          | 47          | 47          | 47      | 47      | 0         | 0         | 0        | 0        |
| PathIsUNC       | 0          | 2           | 2           | 2       | 2       | 2         | 2         | 2        | 2        |
| PathIsUNCServer | 0          | 1           | 1           | 1       | 1       | 1         | 1         | 1        | 1        |
| Test            | 2003 (x86) | Vista (x86) | Vista (x64) | 7 (x86) | 7 (x64) | 8.1 (x86) | 8.1 (x64) | 10 (x86) …

[SHLWAPI_APITEST] Fix heap assertion and test failures

---

base/applications/network/telnet/src/tnconfig.cpp
base/applications/wordpad/wordpad.c
dll/win32/dbghelp/CMakeLists.txt
dll/win32/dbghelp/symbol.c
modules/rostests/apitests/shell32/SHChangeNotify.cpp
modules/rostests/apitests/shell32/ShellExecCmdLine.cpp
modules/rostests/apitests/shell32/shell32_apitest_sub.cpp
sdk/include/psdk/ddraw.h
sdk/include/reactos/wine/test.h
sdk/lib/crt/startup/gs_support.c
subsystems/mvdm/ntvdm/dos/dos32krnl/country.c

These are pretty conservative, there are tons of other warnings left, some that look like actual bugs (-Wconstant-logical-operand, "implicit truncation from 'int' to bit-field changes value", "used uninitialized whenever", "overlapping comparisons always evaluate to true" etc.).
The "wine guid sprintf" warning appears many many times. `CO_E_NOTINITIALIZED` and `UNW_FLAG_NHANDLER` a couple of times. The rest are one-offs.

[SDK][SHELL32_APITEST] Fix some warnings

---

base/applications/kbswitch/kbswitch.c

Management of System Pen icon was inconsistent.
- Add `g_bSysPenNotifyAdded` global variable.
- Add checking the result of `Shell_NotifyIcon`.
- Fix `UpdateLanguageDisplayCurrent` function.
- Add `WM_INPUTLANGCHANGEREQUEST` message handling.

[KBSWITCH] Fix System Pen icon visibility

---

sdk/lib/pseh/include/pseh/pseh2.h

Probably **hack**fixing a corner case detected via broken entities of wlanwiz due to its usage of STLport. This was already done to PSEH3 prior to me.
Corner case examples: [broken](https://github.com/SigmaTel71/reactos/actions/runs/15911239148) and ["fixed"](https://github.com/SigmaTel71/reactos/actions/runs/15945705635)
JIRA issue: [CORE-6622](https://jira.reactos.org/browse/CORE-6622)
- Guard SEH2 family macros behind `#ifndef`

[PSEH] Guard SEH2 macros for Clang on Linux x64 builders

---

sdk/lib/rtl/CMakeLists.txt
sdk/lib/rtl/threadpool.c
sdk/lib/rtl/timerqueue.c
sdk/lib/rtl/wait.c

Partial revert of 0bf42067d28ea488e03c9955632d2a614c4262c2.
It was found that the timer code from WINE doesn't work as well as ours, 
This is a revert from that part of the PR as it doesn't change any of the real threadpool code in all reality. Thanks to the investigation of Julenuri and Simone
JIRA issue: [CORE-20245](https://jira.reactos.org/browse/CORE-20245)

[RTL] Partial revert of Wine timer code in thread pooling

---

ntoskrnl/include/internal/amd64/ke.h
ntoskrnl/ke/amd64/context.c
ntoskrnl/ke/amd64/trap.S
ntoskrnl/ps/amd64/psctx.c
sdk/lib/rtl/amd64/unwind.c

Implement stack based context capture. This is used in PspGetOrSetContextKernelRoutine to get the non-volatile registers, which are not present in the trap frame. The same mechanism was already implemented for setting the registers.
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=102964,102973,102975
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=102965,102974,102976

[NTOS:KE/x64] Implement stack based context capture

---

base/setup/reactos/lang/id-ID.rc

noticed by Katayama's comment from chat.reactos.org:
> Indonesian translation warning: `base\setup\reactos\lang/id-ID(15): warning RC4206: title string too long; trunctated at 256`

[SETUP:REACTOS] Fix warning RC4206 in Indonesian (id-ID) translation

---

dll/win32/shell32/dialogs/drvdefext.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp

Partially fixes [CORE-9881](https://jira.reactos.org/browse/CORE-9881). There is still some code that calls `GetVolumeInformation`. If this is a problem then we need a better cache (Explorer on Windows has a MountPoints2 registry key with cached volume information).

[SHELL32] Don't get icon and label from AutoRun.inf on floppy drives

---

dll/shellext/ntobjshex/foldercommon.h
dll/win32/shell32/CDefaultContextMenu.cpp
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shell32/folders/CFSFolder.cpp
dll/win32/shell32/folders/CNetFolder.cpp
dll/win32/shell32/folders/CRegFolder.cpp

This matches Windows and fixes .../winetests/shell32/shlfolder.c closing an invalid key.
Notes:
- I have an upcoming PR with a test for this and several other CDefaultContextMenu things.

[SHELL32][NTOBJSHEX] CDefaultContextMenu cannot close keys it does not own

---

base/setup/lib/spapisup/spapisup.h
boot/freeldr/freeldr/ntldr/setupldr.c

Add support for architecture-specific "SourceDisksNames" section.
Will be used for installing specific drivers on x64 (e.g. the ACPI driver, see PR #8238).
Add also the ARM64 define in the SETUPLIB spapisup.h header.

[SETUPLDR] Add support for architecture-specific "SourceDisksNames" section

---

boot/bootdata/txtsetup.sif

This just makes it so ACPI.sys is always loaded and copied by the bootcd no matter what on amd64. 
On x86 it can depend on whether we're using an ACPI hal but is set up to never boot with ACPI on the bootcd.
The only reason bootcd boots on x64 is because UNIATA is technically not PNP compliant and is rude.
JIRA issues: [CORE-14922](https://jira.reactos.org/browse/CORE-14922), [CORE-17256](https://jira.reactos.org/browse/CORE-17256)

[BOOT] Make ACPI always copy on amd64

---

dll/win32/shell32/CDefView.cpp

One would think only bits set in stateMask would be respected but I guess not.
JIRA issue: [CORE-20273](https://jira.reactos.org/browse/CORE-20273)

[SHELL32] Only set state flag if state is set on items in DefView list

---

modules/rostests/apitests/compiler/ms_seh.c
modules/rostests/apitests/compiler/pseh.c
sdk/lib/rtl/CMakeLists.txt
sdk/lib/rtl/amd64/unwind-asm.s
sdk/lib/rtl/amd64/unwind.c
sdk/lib/rtl/rtlp.h

This PR implements support for collided unwinds to RtlUnwindInternal. This fixes crashes in SEH tests.
- Implement RtlpExecuteHandlerForUnwind in asm
- Implement RtlpExecuteHandlerForUnwindHandler
- Use the correct context in DISPATCHER_CONTEXT when unwinding
- Handle collided unwinds
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=103089,103096,103098
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=103090,103097,103099

[RTL/x64][COMPILER_APITEST] Implement support for collided unwinds

---

sdk/lib/ucrt/inc/corecrt_internal_simd.h
sdk/lib/ucrt/string/string.cmake
sdk/lib/ucrt/string/strnlen-avx2.cpp
sdk/lib/ucrt/string/strnlen-sse2.cpp
sdk/lib/ucrt/string/strnlen.cpp
sdk/lib/vcruntime/inc/internal_shared.h

Fix 2 bugs that caused GCC builds of ucrtbase to crash.
- Fix __crt_fast_encode_pointer
- Fix GCC/Clang SIMD compilation
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=103104,103109,103138
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=103118,103126,103139

[UCRT] Fix GCC crashes

---

base/system/winlogon/notify.c
dll/win32/wlnotify/scard.c
modules/rostests/win32/winlogon/wlntfytests/wlntfytests.c

Analysis of strings in Win2000 and WinXP/2003 winlogon.exe, show that the "Enabled" registry value doesn't exist for notifications.
This value is actually only used by the ScCertProp (Smart Card Certificate Propagation) notifications, in wlnotify.dll, to enable or disable certificate progagation.[^1]
Note that whatever the "Enabled" registry value is, the notification DLL is still loaded within winlogon.exe.
We however keep the `bEnabled` internal flag, so as to be able to disable at runtime notifications that could not be delay-loaded, or that behave erratically, etc.
[WLNOTIFY] Add a comment about the "Enabled" value in scard.c!SCardStartCertProp()
[^1]: For more information, see:
https://www.microfocus.com/documentation/securelogin/9.0/administration_guide/blm54qb.html?view=print …

[WINLOGON][WLNTFYTESTS] The "Enabled" registry value doesn't exist for notifications

---

base/system/winlogon/notify.c
modules/rostests/win32/winlogon/wlntfytests/wlntfytests.c

Historical note:
Investigation shows that this functionality, introduced between builds 1902 and 1906 of Windows NT 5.0 (future 2000) Beta 3, has always been "nop-ed" and has remained this way till Windows Server 2003. The value read from the "SafeMode" registry value is unconditionally overridden afterwards, causing the notification DLLs to always be loaded.
In ReactOS, this functionality is restored, and only the notifications tagged as such are loaded in SafeMode.
Furthermore:
Analysis of strings in Win2000 and WinXP/2003 winlogon.exe, show that the "Safe" registry value doesn't exist for notifications; instead, it is named "SafeMode".
The "Safe" value appears only for the SensLogn (SENS Winlogon Event) handler registry entry. My hypothesis is that the value name is a typo for the …

[WINLOGON][WLNTFYTESTS] Implement loading notification DLLs in safe-boot mode

---

dll/win32/comctl32/listview.c

A bug fix for PR #7783 (by @katahiromz).
Regression spotted by @HBelusca: Click OK in Folder Options when the View tab is active. This causes a WM_SETTINGCHANGE broadcast and the Listview in an open Explorer window (in report view) deletes its font and the header ends up painting with a deleted font.

[COMCTL32] ListView must update header font if it deletes the old font

---

base/applications/network/net/cmdUse.c

CORE-20287
_Fix random failures of 'net use' when mounting an NFS share._
JIRA issue: [CORE-20287](https://jira.reactos.org/browse/CORE-20287)
_Initialize variable lpNet.lpComment that was previously uninitialized._

[NET] Fix 'net use' command random fails

---

drivers/network/tcpip/include/lwip/arch/sys_arch.h
drivers/network/tcpip/ip/lwip_glue/sys_arch.c

Fixes 2 synchronization issues on SMP builds.
- Use ERESOURCE for global synchronization on SMP builds instead of only raising IRQL
- Use KSEMAPHORE instead of NotificationEvent for "mbox" list notification
- ✅ KVM x86: https://reactos.org/testman/compare.php?ids=103070,103080,103082
- ✅ KVM x64: https://reactos.org/testman/compare.php?ids=103320,103323,103331

[TCPIP] Fix synchronization on SMP

---

drivers/network/tcpip/tcpip/iinfo.c

Split Windows Server 2003 and Windows Vista behaviour in two different cases and make them used separately: when ReactOS target version is NT 5.2, use the 1st case, otherwise use the 2nd one instead.
Also, handle `NdisPhysicalMediumNative802_11` case only for NT 6.0 and newer, since it's actually supported starting from NDIS 6.0 only, according to MSDN:
https://learn.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-physical-medium
, while for NDIS 5.1 and newer it's:
https://learn.microsoft.com/en-us/previous-versions/windows/hardware/network/ff560255(v=vs.85).
This fixes:
1. A critical regression with not accessible networking in ReactOS when NT5-compatible Ethernet/Wi-Fi drivers are used (both in VM and on real hardware) caused by commit …

[TCPIP] Return MIB_IF_TYPE_ETHERNET for WLAN adapter types when compiling ReactOS as NT 5.2

---

dll/win32/msgina/msgina.c
dll/win32/userenv/profile.c

Some returned strings, pertaining to user login on domains (Active Directory...), were initialized by MSGINA with unrealistic values. This is fixed in this commit.
- ### `[MSGINA] CreateProfile(): Fix initialization of some `WLX_PROFILE_V2_0` members`
The following members of the returned `WLX_PROFILE_V2_0` structure: `pszProfile`, `pszPolicy`, `pszNetworkDefaultUserProfile`, and `pszServerName`, have a specific meaning and are used when logging to (NT4, Active Directory...) domains.
See the added code comments for details.
In particular, `pszProfile` specifies the path to a *roaming* user profile[^1] on a domain server, if any. It **DOES NOT** specify the local `"C:\Documents and Settings"` path (got via `GetProfilesDirectoryW()`).
Since we don't really support user login on domains, set …

[MSGINA][USERENV] Fix initialization of domain-login-related user profile information fields

---

base/system/winlogon/notify.c
base/system/winlogon/sas.c
base/system/winlogon/winlogon.c
base/system/winlogon/winlogon.h

Initialize the `UserName` and `Domain` fields of the `WLX_NOTIFICATION_INFO` structure passed to the notification handlers, with sensible values.
The following test results incorporate these as well.
- Test 1a: `Asynchronous: FALSE, Impersonation: FALSE`
BEFORE the fix:
OK, the thread isn't impersonated:
```
Thread Token   : 0x00000000 - User: '(null)\(null)'
```
BUT these two WLX notify info fields aren't set when the user is logged in:
```
Info.UserName       : '(null)'
Info.Domain         : '(null)'
```
Results:
```
WLEventStartup: 30 tests executed (0 marked as todo, 1 failure), 0 skipped.
WLEventLogon: 30 tests executed (0 marked as todo, 3 failures), 2 skipped.
WLEventStartShell: 30 tests executed (0 marked as todo, 3 failures), 2 skipped.
(NOTE: WLEventPostShell isn't yet …
```

[WINLOGON] Duplicate the logged-in user/domain names and give them to the notifications

---

dll/win32/kernel32/client/proc.c

If multiple threads call GetStartupInfoA at roughly the same time, a thread that loses the race would free the global BaseAnsiStartupInfo instead of its own local data, resulting in a use-after-free.
- Set `StartupInfo` to point to the global `BaseAnsiStartupInfo` only after the local data has been freed.

[KERNEL32] Fix use-after-free in GetStartupInfoA

---

base/setup/lib/utils/partlist.c

Some partition entries (such as those added by the CreateInsertBlankRegion function) may not have their Volume member allocated. This fixes the USETUP crash when such partitions are handled.

[SETUPLIB] Fix system partition selection DPRINTs

---

drivers/network/ndis/ndis/miniport.c
sdk/include/psdk/ntddndis.h

Another small step, until further investigation/implementation.
JIRA issue: [CORE-13831](https://jira.reactos.org/browse/CORE-13831)
- Define IOCTL_NDIS_RESERVED7 and add a stub

[NDIS][PSDK] Define IOCTL_NDIS_RESERVED7 and add a stub

---

drivers/network/ndis/include/ndissys.h
drivers/network/ndis/ndis/protocol.c

Do not use random tags.
Addendum to e8861acfb2 (r12196) and 5658b2154c (r53045).
JIRA issue: [CORE-18791](https://jira.reactos.org/browse/CORE-18791)
- Let it be "NDIS", instead of variations of "SIMN".
- Use matching ExFreePoolWithTag().
- Remove a redundant 'KeyInformation = NULL;'.
I fixed the existing cases only.
A follow-up would be to use the tag everywhere in this module.

[NDIS] NDIS_TAG: Fix definition and usages

---

modules/rostests/kmtests/include/kmt_test_kernel.h

Let this function compile/run on other architectures, like ARM*.
JIRA issue: [ROSTESTS-363](https://jira.reactos.org/browse/ROSTESTS-363)
- Be explicit about architectures
- And improve code a bit.

[KMTESTS] KmtAreInterruptsEnabled(): Be explicit about architectures

---

drivers/storage/ide/uniata/id_init.cpp

Fix AHCI support regression.
Reverts a part of 1afae58 (r69699).
JIRA issue: [CORE-13346](https://jira.reactos.org/browse/CORE-13346)
- Disable a "new" code block, which is broken.

[UNIATA] UniataChipDetect(): Workaround AHCI detection

---

win32ss/user/ntuser/keyboard.c

Guard against NULL pFocusQueue.
Addendum to commit 25b7447818 (PR #5839)
When being on the ReactOS explorer desktop, open the Start menu and select "Turn Off" (Shutdown).
In the Shutdown dialog, click on the "Cancel" button _**while pressing**_ on the keyboard the Ctrl-Alt-Shift keys combination, and also pressing/releasing each of these keys while maintaining the others very fast.

[NTUSER] IntLanguageToggle(): Guard against NULL pFocusQueue

---

base/shell/explorer/explorer.cpp
dll/cpl/sysdm/advanced.c
dll/ntdll/rtl/version.c
dll/win32/browseui/shellbrowser.cpp
dll/win32/shell32/CDefView.cpp
dll/win32/shell32/CDefViewUtil.cpp
dll/win32/shell32/folders/CControlPanelFolder.cpp
dll/win32/shell32/folders/CControlPanelFolder.h
dll/win32/shell32/folders/CDesktopFolder.cpp
dll/win32/shell32/folders/CDrivesFolder.cpp
dll/win32/shlwapi/ordinal.c
modules/rostests/apitests/ntdll/RtlGetNtProductType.c
sdk/include/psdk/shobjidl.idl
sdk/include/reactos/undocshell.h

OS_SERVERADMINUI changes minor things in Explorer, the most visible is that the default folder view mode changes from large icons to details (although ROS has been incorrectly hardcoding details mode for a long time).
Notes:
- I took the liberty to check the ReportAsWorkstation value. Windows obviously does not do this.
- I'm not implementing the entire shell32 REGINST thing just for the 10 tweaks listed there for this setting.
- Yes, Windows only applies the registry tweaks when the value is true, it does not undo them on false.

[SHLWAPI][EXPLORER] Implement OS_SERVERADMINUI

---

dll/win32/msgina/gui.c
dll/win32/msgina/msgina.h
dll/win32/msgina/shutdown.c
dll/win32/msgina/utils.c
dll/win32/shell32/dialogs/dialogs.cpp

Improve Security and Shutdown dialog features.
- Respect system policies for showing or hiding:
* Security dialog "Lock Workstation", "Log Off", "Shut Down", "Change Password", "Task Manager" buttons;
* "Log Off" entry in the Shutdown dialog;
- Disable the "Shut Down" Security dialog button, and the "Stand by", "Shut down" entries in the Shutdown dialog, if the logged user doesn't have the SeShutdownPrivilege.
- Add other missing `WLX_SHUTDOWN_STATE_*` shutdown flags that are supported by Windows.
- Improve the retrieval of shutdown options to be displayed in the "Shut Down" dialog. In particular, don't hardcode any sort of defaults, but let them come from what the user can do (Is logoff allowed? Does (s)he have the rights to shutdown/reboot? etc.). If no shutdown options are available, …

[MSGINA] Improve Security and Shutdown dialog features

---

win32ss/gdi/ntgdi/dibobj.c

CORE-15002
Credit for this goes to Simone Lombardo
Show actual bitmaps instead of black boxes on graphics of SAI Paint Tool.
JIRA issue: [CORE-15002](https://jira.reactos.org/browse/CORE-15002)
In function NtGdiSetDIBitsToDeviceInternal check if `YDest >= 0` and `YSrc > 0`.
If the above is true, then set `YSrc = 0`.
This fixes the initial graphics display for the SAI paint tool program.
(See `gdi32:bitmap` test.)
Before:
After:
_Note: Since this affects code involving PR #5227, I also tested VB6, Word 2000, Excel 2000, and Hoyle Cards._

[NTGDI] Fix SAI Paint Tool Initial Graphics Display

---

drivers/acpi/cmbatt/cmbpnp.c
drivers/acpi/cmbatt/cmexec.c
drivers/battery/battc/battc.c
drivers/battery/compbatt/compbatt.c

JIRA issue: [CORE-20343](https://jira.reactos.org/browse/CORE-20343)
The 3-second timeout FIXME (instead of waiting indefinitely), made in the COMPBATT worker thread for the IOCTL_BATTERY_QUERY_STATUS case, was done because _*our*_ BATTC handler expects the batteries to always support the BTP (Battery Trip Point) feature for signaling a change of battery status, but in the cases where it isn't supported, any waits it tried for the battery to notify about a status change would never happen.
Furthermore, following commit 3a6e0d4b65, the SetStatusNotify() call (_which always fails if the battery doesn't support the BTP feature_) would now always exit the IOCTL_BATTERY_QUERY_STATUS handling without any waiting nor battery polling [^1], and this would cause the COMPBATT worker thread to …

[BATTC][COMPBATT] Move the IOCTL_BATTERY_QUERY_STATUS wait hack to BATTC

---

dll/win32/powrprof/powrprof.c

This fixes failure to create or open the `PowerProfileRegistrySemaphore`, when it has been first created by a Process1 using powrprof from a "User1", and while this process stays running, the semaphore is attempted to be re-created (or opened) by another Process2 using powrprof from a different "User2".
JIRA issue: [CORE-19104](https://jira.reactos.org/browse/CORE-19104)
For example, this happens when "User1" is either the LocalSystem account with the Process1 being Winlogon.exe (via the msgina.dll -> powrprof.dll dependency), or, "Administrator" with the explorer.exe process when opening the "Shutdown" dialog (via the shell32.dll -> runtime-loading of msgina.dll -> powrprof.dll dependency),
AND,
"User2" being a non-administrator user and Process2 being explorer.exe, again when opening …

[POWRPROF] Fix how & when the global registry semaphore is initialized

---

dll/win32/msgina/CMakeLists.txt
dll/win32/msgina/shutdown.c

JIRA issue: [CORE-19104](https://jira.reactos.org/browse/CORE-19104)
- Use `NtPowerInformation()` and the `IS_PWR_*` macros instead.
- Fancy shutdown dialog:
* Enable or disable the hibernate/sleep buttons depending on the previously-determined available shutdown options.
* Don't invoke `ExitWindowsEx()` or `SetSuspendState()` directly within Msgina, but return a suitable `WLX_SAS_ACTION_SHUTDOWN_*` value, like what's done by the classic dialog. The power action proper is then performed by the caller of the shutdown dialog: either Shell32 or Winlogon.

[MSGINA] Don't depend on powrprof.dll; fix shutdown from fancy dialog

---

modules/rostests/apitests/cmd/cmd.c

Four of the cmd:attrib tests fail on some versions of Windows. In these four tests (and these four only), `bStdOutput` is sometimes true and sometimes false. To work around this issue, I added a tristate option which allows that particular test to return either true or false.
- Add a tristate option to accept either true or false for the `bStdOutput` and `bStdError` tests
- Use this new option on the four tests that are inconsistent.

[CMD_APITEST] Add tristate option to fix cmd:attrib test on different Windows versions

---

modules/rostests/kmtests/ntos_cm/CmSecurity.c
modules/rostests/kmtests/ntos_ex/ExPools.c
modules/rostests/kmtests/ntos_io/IoDeviceObject_drv.c
modules/rostests/kmtests/ntos_io/IoFilesystem.c
sdk/include/ndk/iotypes.h
sdk/include/xdk/setypes.h

Same PR as #8286, all of the work was done by @cbialorucki except some cosmetic refactoring to [2950d94](https://github.com/maramadany/reactos/commit/2950d94bfd76b6a1f5e75765cb4a0bfa520990a3).
Fix failing kmtests on x64, NTFS, and Vista+ Windows systems.
Note: Between testing initially and developing these fixes, I switched my Windows 10 version from 22H2 to build 1607. This resulted in a lot of differences in the CmSecurity test. If we want to properly fix this test for Windows 10, as well as several others, we need to map build numbers from the KUSER_SHARED_DATA page to NTDDI versions and then check against the NTDDI version at runtime.
| Test | 2003 (x86) | Vista (x86) | Vista (x64) | 7 (x86) | 7 (x64) | 8.1 (x86) | 8.1 (x64) | 10 (x86) | 10 (x64) |
| :--- | :---: | :---: | :---: | …

[KMTESTS] Kmtest fixes
